### ISSUE TITLE
Errror when attempting to log on with sign in link

### ISSUE THREAD

**Issue by LukeJJones** [firebase/firebase-js-sdk#1005]
### Describe your environment

  * Operating System version: Windows 10 Pro
  * Browser version: Google Chrome - Version 67.0.3396.99 (Official Build) (64-bit)
  * Firebase SDK version: 5.0.4
  * Firebase Product: auth

### Describe the problem

I've started receiving the following error when a user attempts to logon to our site. We are using the Sign In Link authentication method and it was previously working great.

```
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getOobConfirmationCode?key=[API_KEY] 400 ()
```

#### Steps to reproduce:
1. Visit app.plentybook.com/admin/login
2. Enter a valid email address
3. Press Enter or click Login button
4. Check the console for error
#### Relevant Code:

The following is the event that is fired once the form is submitted. This is a react application. Most of this is a straight copy from the Firebase docs.

```
handleLogin = e => {
    // Prevent the form from refreshing the page
    e.preventDefault();
    // Remove focus from email input
    document.getElementById('email').blur();
    // Set the action code settings
    const urlParts = window.location.href.split('/');
    const actionCodeSettings = {
      // URL you want to redirect back to. The domain (www.example.com) for this
      // URL must be whitelisted in the Firebase Console.
      url: `${urlParts[0]}//${urlParts[2]}/admin/login-complete`,
      // This must be true.
      handleCodeInApp: true,
    };

    // Attempt to send an email sign in link
    firebase
      .auth()
      .sendSignInLinkToEmail(this.state.email, actionCodeSettings)
      .then(() => {
        this.props.toasterProps.show(
          toastTypes.success,
          'awesome! check your email for a login link.'
        );
        window.localStorage.setItem('emailForSignIn', this.state.email);
      })
      .catch(error => {
        if (isDev) {
          console.log(error.message);
        }
      });
  };
```

**Comment by bojeil-google** [comment]
This looks like an issue on your end. You are getting the following error:
```
{
  "error": {
    "code": 400,
    "message": "UNAUTHORIZED_DOMAIN : Domain not whitelisted by project",
    "errors": [
      {
        "message": "UNAUTHORIZED_DOMAIN : Domain not whitelisted by project",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```
You need to whitelist the following domain `app.plentybook.com` in the Firebase Console.
Either it was never there or someone removed it.

**Comment by bojeil-google** [comment]
I was able to replicate the issue on my end by using this with or without an authorized domain. It works as expected for either case. For support issues, please use https://firebase.google.com/support/

**Comment by LukeJJones** [comment]
Thank you! That was indeed the issue.
