### ISSUE TITLE
Missing getSWRegistration_() method in messaging product typings

### ISSUE THREAD

**Issue by jcao02** [firebase/firebase-js-sdk#101]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 14.04
  * Firebase SDK version: 4.1.3
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
I have an already working service-worker and I want to integrate firebase-messaging worker with it. I found in your code that you have a method to get the `ServiceWorkerRegistration` [here](https://github.com/firebase/firebase-js-sdk/blob/master/src/messaging/controllers/controller-interface.ts#L112), however, this method is not in the typings you provide when the library is installed

#### Steps to reproduce:
Just install the library using npm

#### Relevant Code:

```javascript
 const messaging = firebase.messaging();
 messaging.getSWRegistration_()
.then(reg => /* handle registration */);
```

**Comment by gauntface** [comment]
@jcao02 have you tried using the "useServiceWorker()" method?

**Comment by jcao02** [comment]
I wanted to include my service worker in yours, using `importScript`, but I guess the approach you're suggesting is better so I have full control on the service worker.

Just a question: I should call `getToken` after I use `useServiceWorker` method, right?

**Comment by gauntface** [comment]
@jcao02 yes you should, you'll get an error if you call useServiceWorker **after** getToken
