### ISSUE TITLE
Dots in email are not ignored by Firebase Auth for Gmail accounts

### ISSUE THREAD

**Issue by serhiipalash** [firebase/firebase-js-sdk#1012]
Hi Firebase team!

We have the problem with Firebase Auth accounts linking. 

We have Facebook login and email&password login in our app. If user has Firebase Auth account with Facebook provider and with identifier john.doe@gmail.com, and then tries to sign in with email&password using johndoe@gmail.com identifier he will be recognized as different from john.doe@gmail.com user by Firebase Auth.

From my point of view this is a bug because Gmail account identification is case and dots insensitive. User may not know that Firebase Auth is dots sensitive and try to sign in with a slightly different email address. In the end user will get two accounts: one with Facebook auth provider and one with email&password, but should have one with two auth providers in it.

I wanted to submit this bug in Firebase Auth repo but I didn't find it.

**Comment by prene** [comment]
Just want to confirm that this issue still exists, as I just ran into this.

**Comment by samhorlbeck** [comment]
Hi folks, thanks for raising this question. Given that this is [specifically a Gmail quirk](https://stackoverflow.com/questions/14865869/do-all-email-providers-ignore-periods-in-front-of), this is working as intended since periods in emails can be meaningful for other providers.
