### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by darkylmnx** [firebase/firebase-js-sdk#1016]
@jdimond I'm re opening in the right repo now, I still experience slow queries.

Well it's not as much as before but i'm still having it on some queries, and its a query on the root level 
![image](https://user-images.githubusercontent.com/1426357/42846565-97eaf054-8a19-11e8-9c59-8799a6bf1cec.png)

**Comment by mikelehen** [comment]
@darkylmnx Can you provide more detail about what you're doing, what you're expecting, and what you're seeing instead?  As-is, I don't think this is actionable unless @jdimond has a bunch of context that I'm missing or something.

It's worth noting that the web client uses a protocol that relies on "hanging get" type requests to emulate a stream.  That means there won't be a 1-1 correspondence between requests in the network pane and API requests or in their latencies.

**Comment by mikelehen** [comment]
Please reopen if you can provide more details.  Thanks!
