### ISSUE TITLE
Firebase Cordova OAuth does not redirect back to app on iOS 10.0.1

### ISSUE THREAD

**Issue by gspuzic** [firebase/firebase-js-sdk#1025]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 10.0.1
  * Browser version: Cordova web view engine CDVUIWebViewEngine
  * Firebase SDK version: 5.2.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Followed these instructions:

https://firebase.google.com/docs/auth/web/cordova 

to implement OAuth authentications with Facebook.

It works fine on all versions of Android and iOS tested  **EXCEPT** iOS 10.0.1. The user is reporting a blank screen after the Facebook sign in. The plugin does not re-direct back to the app and complete the auth. 

![img_7032](https://user-images.githubusercontent.com/41413117/42922967-52995564-8b62-11e8-83a9-fcea30e204e7.PNG)

#### Steps to reproduce:

Implement OAuth in a simple Cordova app using Ionic as described in the Firebase docs. Run the app on iOS 10.0.1.

#### Relevant Code:

List of Cordova packages:

```javascript
  "dependencies": {
    "angularfire": "^2.0.1",
    "animate.css": "^3.5.2",
    "cordova-android": "6.3.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-buildinfo": "^2.0.1",
    "cordova-plugin-calendar": "^4.6.0",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-customurlscheme": "^4.3.0",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-inappbrowser": "^1.7.1",
    "cordova-plugin-ionic-webview": "^1.1.11",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.3.0",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "cordova-universal-links-plugin": "^1.2.1",
    "es6-promise-plugin": "^4.1.0",
    "firebase": "5.2.0",
    "ionic-native": "^1.3.10",
    "ionic-plugin-keyboard": "^2.2.1",
    "phonegap-plugin-push": "^2.1.3"
  },

```

**Comment by bojeil-google** [comment]
This is a known issue. 
It has been reported via various channels: https://github.com/firebase/firebaseui-web/issues/365

**Comment by gspuzic** [comment]
Yes I've seen those, this is different. I have it working on iOS, except 10.0.1.

**Comment by bojeil-google** [comment]
I see. I have not seen this one. It's unusual it would not work for iOS 10.0 only.
We will look into replicating this.

**Comment by gspuzic** [comment]
I will be debugging this with Safari developer tools directly on the user device next week so can provide further information then. If you have any tips or advice on debugging this please let me know.

**Comment by bojeil-google** [comment]
I would look into the `cordova-plugin-customurlscheme` cordova plugin. This is the plugin we use to detect the custom scheme redirect. Add your own handler to detect that the custom scheme redirect is getting intercepted by the app. 

Also make sure the current URL is a file:// URL. This is the issue I mentioned above in the other bug.

**Comment by gspuzic** [comment]
The issue is that the user had private browsing enable in Safari so signInWithRedirect() launches the Oauth Safari session in private mode.

Firebase is then unable to close Safari and re-direct back to the app with a "can't close the window since it was not opened by javascript" warning printed to the console.

What are my chances of getting this fixed? Any ideas for a workaround?

**Comment by ericgopak** [comment]
Possible workaround:

https://stackoverflow.com/a/53566771/2779681

**Comment by MatthewPringle** [comment]
I have had the same issue, on iOS 12 at least of it never redirecting back to the app successfully.

Instead it eventually ends up at about:blank and the browser tab doesn't close.

It seems that the app goes to sleep when the sign in window is opened and isn't running when the callback is passed.

To solve this I installed https://github.com/katzer/cordova-plugin-background-mode and set it to keep the app awake in the background using cordova.plugins.backgroundMode.enable()

I plan to just enable and disable as needed but can anyone else check if it solves their problem.

**Comment by SandroMoretti** [comment]
@MatthewPringle , does not work for me.

**Comment by MatthewPringle** [comment]
@SandroMoretti which bit isn't working? Below is a list of working plugins

`
    <plugin name="cordova-plugin-buildinfo" spec="2.0.3"/>
    <plugin name="cordova-plugin-background-mode" spec="0.7.3"/>
    <plugin name="cordova-plugin-customurlscheme" spec="4.4.0">
        <variable name="URL_SCHEME" value="YOURLINK"/>
        <variable name="ANDROID_SCHEME" value=" "/>
        <variable name="ANDROID_HOST" value=" "/>
        <variable name="ANDROID_PATHPREFIX" value="/"/>
    </plugin>
    <plugin name="cordova-plugin-inappbrowser" spec="^3.1.0"/>
    <plugin name="cordova-plugin-safariviewcontroller" spec="^1.6.0"/>
    <plugin name="cordova-universal-links-plugin" spec="https://github.com/walteram/cordova-universal-links-plugin"/>
    <universal-links>
        <host name="YOURLINK.page.link" scheme="https"/>
        <host name="YOURLINK.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback"/>
        </host>
    </universal-links>`

You would also need to fool firebase into think you have installed the plugins it is looking for, rather than the ones installed, which are newer and work. I replaced browsertab

`/* Check Plugins */
        if ( window.cordova.plugins === undefined ) {
            window.cordova.plugins = {};
        }
        
        /* Browsertab */
        window.cordova.plugins.browsertab = {};
        
        /* Browsertab - Is Available */
        window.cordova.plugins.browsertab.isAvailable = function( success ) {
            window.SafariViewController.isAvailable( success );
        }
        
        /* Browsertab - Open Url */
        window.cordova.plugins.browsertab.openUrl = function( url ) {
            window.SafariViewController.show( { url: url } , function() {} , function() {} );
        }
        
        /* Browsertab - Close */
        window.cordova.plugins.browsertab.close = function() {
            window.SafariViewController.hide();
        }`

**Comment by MatthewPringle** [comment]
@SandroMoretti I would recommend you stop using Cordova though, so much is now out of date and they have even posted on their own forums about not being sure about the future.

I would instead recommend Capacitor, a bit of a successor to Cordova and it works along the same lines, it can even use Cordova plugins

https://capacitor.ionicframework.com

They have a Firebase integration which works on the native layer and passes the authentication back to the javascript layer, bit harder to setup, but it is current. Editing the iOS and Android folders isn't a issue here though as Capacitor never had you remove or rebuild them.

https://github.com/baumblatt/capacitor-firebase-auth

**Comment by SandroMoretti** [comment]
@MatthewPringle Thank you for the tip.

I really like cordova a lot for small projects. Instead of spending 30 days on a simple app, it can be done in 3 days.

But we know that it has limitations, especially in native consumption, which has bugs according to OS updates. For the projects I currently use, I can do even with the limitations, but if the cordova does die, I imagine it is more beneficial to migrate future projects to react native or flutter than to invest learning in another cordova-style web app.

**Comment by MatthewPringle** [comment]
@SandroMoretti Capacitor is made by Ionic, who have used Cordova for years with their Ionic Framework.

Capacitor is just their new version, a replacement for Cordova. Ionic Framework 4 uses Capacitor and the new web components, generated in Stencil ( also by Ionic ). They have released Capacitor on its own, as well as React / Angular / Vue integrations.

And I've just written up a quick Ember integration.
https://forum.ionicframework.com/t/ember-integration/177429

It has been so easy to get an app up and running in both iOS and Android, I'm moving a Cordova project over at the moment.

**Comment by scottcrossen** [comment]
Multiple suggestions have been made. If these don't work and this is still an issue please re-open this issue.
