### ISSUE TITLE
@firebase/database regression (missing dist/index.d.ts)

### ISSUE THREAD

**Issue by buu700** [firebase/firebase-js-sdk#1032]
After updating from 0.33 to 0.34, my TypeScript code won't compile unless I copy `node_modules/@firebase/database/dist/packages/database/index.d.ts` to `node_modules/@firebase/database/dist/`.

**Comment by schmidt-sebastian** [comment]
@jshcrowthe Josh, can you look at this?

**Comment by Feiyang1** [comment]
The same issue as https://github.com/firebase/firebase-js-sdk/issues/1213
Using the latest firebase should resolve the issue.
