### ISSUE TITLE
Using external orderby without using used query inequality in firebase firestore

### ISSUE THREAD

**Issue by Generalomosco** [firebase/firebase-js-sdk#1046]
Is there anyway i can escape GeoPoint as first order in this postion? If i remove GeoPoint from orderby it triggered the below error and if i put the GeoPoint as first orderby, as instructed as below, it mislead the second orderby priceSort..

> Uncaught Error: Invalid query. You have a where filter with an inequality (<, <=, >, or >=) on field 'GeoPoint' and so you must also use 'GeoPoint' as your first Query.orderBy(), but your first Query.orderBy() is on field 'priceSort' instead.

```
 const locations=NearBy({
      center:{
        latitude:4*.*****,
        longitude:7*.*****},
      radius:30000})



    var db = firebase.firestore();
    var AdsQry = db.collection("ads");

      AdsQry = AdsQry
        .where('GeoPoint', '>', locations.lesserGeopoint)
        .where('GeoPoint', '<', locations.greaterThan)
        .orderBy('GeoPoint', 'asc');

        AdsQry = AdsQry.where('complete', '==', 'yes')
        //.where('countrycode', '==', 'IT')
        .orderBy('priceSort', 'desc')

    AdsQry.get().then(function(snapshot) {
      snapshot.forEach((doc) => {
        console.log(doc.id+": priceSort="+doc.data().priceSort+" dateSort="+doc.data().dateSort);
      })
    })
```

Please one can try it here as same as this, i want the index to order accordingly by numeric [jsbin.com/dekafuvevo/1/edit?js,console](jsbin.com/dekafuvevo/1/edit?js,console)

**Comment by wilhuff** [comment]
What the error message is telling you is that if you're using a where clause with an inequality, your first order by must be on the same field.

This is a limitation of the way indexes work in Firestore: in order to evaluate the inequality, we must perform a scan on an index where that field is in the first position. In other words: the results are going to be ordered by that field, all you get to choose is if there are any other orderings you want to apply after that.

**Comment by mikelehen** [comment]
I'll also point out that using inequalities on geopoints like you are doing is not going to work as expected.  It'll essentially only filter by the latitude, not the longitude (see https://github.com/firebase/firebase-js-sdk/issues/826 for another discussion about this).  Unfortunately we do not yet support proper geo queries.
