### ISSUE TITLE
FR: Batch reads

### ISSUE THREAD

**Issue by ribrdb** [firebase/firebase-js-sdk#1050]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: Chrome 67
  * Firebase SDK version: 5.2.0
  * Firebase Product: firestore

There should be an api to fetch a list of document references, like https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.Firestore.BatchGetDocuments

**Comment by mikelehen** [comment]
Thanks for the suggestion! This is being tracked as https://github.com/firebase/firebase-js-sdk/issues/1176
