### ISSUE TITLE
Firestore does not find out when internet is reestablished  and pending persistence is not send to backend

### ISSUE THREAD

**Issue by fernandovalenzuela** [firebase/firebase-js-sdk#1053]
#### Environment

  * Operating System version: Windows_
  * Browser version: Chrome
  * Firebase SDK version: 4.12.1
Cordova 8.0.0
Platfrom: Android

#### Product:

  * Firebase Product: _Firestore

#### Problem:

Firestore does not find out when the internet connection is recovered and does not send the pending creation to the backend

#### Steps to reproduce:
Steps:
1. Connection to the internet is lost, for example because I walk away from the wifi router
2. I create a document in firestore
3. Internet connection is recovered
4. The persistence mechanism does not send the creation of the document to the backend.
5. If I manually disable the Internet in the cell phone and then re-enable it, the creation of the document is then sent.

It seems that firestore or database does not find out when the internet connection is recovered transparently.

I hope you can help me.
Thanks in advance!

#### Relevant Code:

```javascript

I use this code for enable persistence:

firebase.initializeApp(config)
firebase.firestore().enablePersistence()
  .then(function() {
	db = firebase.firestore();
  })
  .catch(function(err) {
  });

**Comment by mydoal** [comment]
Related to https://github.com/firebase/firebase-js-sdk/issues/1060

**Comment by mikelehen** [comment]
Can you add firebase.firestore.setLogLevel('debug'), reproduce the issue, and then include the log here?  Also, please wait at least 2 minutes to see if the connection is eventually recovered.  Thanks.

**Comment by mikelehen** [comment]
Please re-open if you can provide logs and/or a way to reproduce this.  Thanks!
