### ISSUE TITLE
permission_denied in Firebase database / no permission problem in Firebase auth - anonymous login

### ISSUE THREAD

**Issue by pvdyck** [firebase/firebase-js-sdk#106]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.12.6
  * Firebase SDK version: ^4.1.3
  * Firebase Product: auth database

### [REQUIRED] Describe the problem

- Since yesterday around 7pm GMT+1, I am getting permission_denied from firebase database.
- Credentials did not change and I created a new project with new credentials and the problem persists.
- The anonymous user is **granted access, created and visible** in the user db, so I suppose that my credentials are OK.
- There are no specific database rules.
- I am getting recurrent **base64Decode failed**:  {} in my logs (see below).
- Please note that I did fetch back working code written one week ago and it is exhibiting the same behavior.

#### Steps to reproduce:

Firebase log :
p:0: Browser went online.
event: /.info/connected:value:false
p:0: Auth token refreshed
p:0: Making a connection attempt
getToken() completed. Creating connection.
c:0:0: Connection created
c:0:0:0 Websocket connecting to wss://s-usc1c-nss-210.firebaseio.com/.ws?v=5&ns=parrot-city-test2 
p:0: Auth token refreshed
**base64Decode failed:  {}**
p:0: {"r":2,"a":"gauth","b":{"cred":"eyJh*truncated*midGWOaHZf__yfQ"}}
p:0: Listen on /user/H3AgDslbgJeMf7bM8eyiC3dgc9I2/profile for default
event: /.info/connected:value:true
p:0: from server: {"r":1,"b":{"s":"ok","d":""}}
c:0:0: Primary connection is healthy.
p:0: from server: {"r":2,"b":{"s":"permission_denied","d":"Access denied."}}
**Auth token revoked: permission_denied/Access denied.**
c:0:0: Closing realtime connection.
c:0:0: Shutting down all connections
 c:0:0:0 WebSocket is being closed
 p:0: data client disconnected
 p:0: Trying to reconnect in 0ms
 event: /.info/connected:value:false
 0: onDisconnectEvents 

and of course 

"FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "apiKey" and "databaseURL" properties provided to initializeApp() match the values provided for your app at https://console.firebase.google.com/. "

#### Relevant Code:

I am using standard AngularFire2 to configure and connect.

**Comment by bojeil-google** [comment]
I am seeing this error reported via other channels. They released 4.1.4 today:
https://firebase.google.com/support/release-notes/js#4.1.4
Can you downgrade to 4.1.3 and try again?

**Comment by bojeil-google** [comment]
I just tested this. Downgrading to 4.1.3 will stop the warning from showing. It seems like the typescript refactor introduced this.

**Comment by pvdyck** [comment]
Thanks. Downgrading works indeed.

This is not a warning BTW, it breaks the code.

P.S.: There is definitely a test missing in the CI, this should not have passed QA.

**Comment by bojeil-google** [comment]
Sorry about that. Yeah, we will be investigating this and making sure it doesn't happen again. Thank you for reporting it.

**Comment by jshcrowthe** [comment]
@pvdyck Thank you so much for the report. I have triaged and found a typo from the migration caused the bug. I will get that fixed ASAP. You are exactly right, this should have gotten caught in CI. I will add tests to ensure we have this test case covered going forward! Thank you sir!

**Comment by pvdyck** [comment]
You are welcome.

Please add a link to the solution when available and close the issue then.

**Comment by jshcrowthe** [comment]
This has been fixed and released in version `4.1.5` thanks again for your help!

**Comment by pvdyck** [comment]
Excellent. That was very quick !

I suppose you have the time to add the missing test now.

Keep up the good work !

**Comment by jshcrowthe** [comment]
@pvdyck Yup we will get the test added tomorrow! Thanks again for helping us make Firebase awesome 😄

**Comment by ThorvaldAagaard** [comment]
Is this affecting firebase storage too?

**Comment by mcdonamp** [comment]
@MohitOpenxcel the Admin SDK is using a Service Account which generally ignores security rules. Take a look at https://firebase.google.com/docs/database/admin/start#admin-sdk-authentication for some more info on how to set this up properly (you'll have to make sure the service account you're using has permissions to access the database).

**Comment by MohitOpenxcel** [comment]
@mcdonamp let me try this. My code get access to firebase nodes for 1 hour. then it suddenly get access denied error. Should this work??

**Comment by mcdonamp** [comment]
Sounds like an issue with token refreshing. Either way, it's not related to this bug, which has already been closed. Please try the above, and if it doesn't work, please report an issue here: https://github.com/firebase/firebase-admin-node/issues

**Comment by MohitOpenxcel** [comment]
@mcdonamp your suggestion has solved my issue. Thanks for your comment.
