### ISSUE TITLE
Incorrect Firebase version (4.10.1) printed in log

### ISSUE THREAD

**Issue by mydoal** [firebase/firebase-js-sdk#1061]
### [REQUIRED] Describe your environment

Operating System version: Android 7.1.1
Android SDK: 26.0.2
Browser version: Chrome
Firebase SDK version: 4.12.1
Firebase Product: Firestore
Ionic version: 3.19.1
Ionic Angular version: 3.9.2
Cordova Android: 6.4.0
AngularFire version: 5.0.0-rc.5-next

### [REQUIRED] Describe the problem

When receiving the following error in the log:

[2018-07-30T08:44:27.912Z]  @firebase/firestore: Firestore (4.10.1) [PersistentStream]: close with error: FirebaseError: [code=unknown]: Fetching auth token failed: A network error (such as timeout, interrupted connection or unreachable host) has occurred.

The Firebase version printed is 4.10.1, although the actual version used in package.json and eventually in node_modules is:

```
    "firebase": "4.12.1",
```

Related issue:

https://github.com/firebase/firebase-js-sdk/issues/1060

**Comment by mikelehen** [comment]
I can't repro this.  I get 4.12.1 in the log messages when I install 4.12.1 via npm or reference it directly from the CDN.

**Comment by mikelehen** [comment]
Can you double check you've really installed 4.12.1 and rebuilt everything?  If so, can you provide specific repro steps (might depend on exactly how you're installing / referencing firebase).

**Comment by mydoal** [comment]
Thanks @mikelehen  for your reply.
In root directory package.json:
``` "firebase": "4.12.1" ```

node_moduels/firebase/package.json
```      "firebase@4.12.1" ```

I did a full text search on the entire directory:

under node_modules/@firebase/app/dist/cjs/src ther is afile named firebaseApp.js 

```
function createFirebaseNamespace() {
...
        SDK_VERSION: '4.10.1',
...
}
```

This file seems to belong to AngularFire2. 
Could this interfere with Firestore?

**Comment by mikelehen** [comment]
Hrm.  I'm not sure.  I don't have that file.  Maybe it's worth wiping your node_modules directory, running yarn or npm from scratch, and see if the problem comes back?

**Comment by mydoal** [comment]
I've deleted node_moduels and the package-lock.json, cleared the cache and run npm install.
The output in the log did not appear again.
@mikelehen Thanks for your help.

**Comment by mikelehen** [comment]
Good to hear!
