### ISSUE TITLE
FR: webchannel-wrapper(firestore) ES Module support

### ISSUE THREAD

**Issue by mario-aleo** [firebase/firebase-js-sdk#1070]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS
  * Browser version: Chrome 68.0.3440.75
  * Firebase SDK version: 5.3.0
  * Firebase Product: firestore

I've been using firebase with ES Module for a short time, things like the app, auth, database and Storage works fine, but I can't use the firestore, when I try to import the firestore throws **"The requested module '../../webchannel-wrapper/dist/index.js' does not provide an export named 'ErrorCode'"** error.

I think that it's due the fact that the webchannel-wrapper doesn't have an ES Module implementation like the other firebase products dependencies.
I would be glad if you guys could implement the support for ES Module support and could see if there's anything else that you need to do so we can use the firestore with ES Modules.

**Comment by Westbrook** [comment]
Seconded!

This prevents me from being able to test the really exciting RxFire release from this week as a conversion target for a number of projects where I'd previously employed the dying tools presented PolymerFire.

**Comment by mario-aleo** [comment]
@Feiyang1, this is working good, thank you :)
Closed with merge #1248
