### ISSUE TITLE
Email Link Authentication does not take in Action Code Settings

### ISSUE THREAD

**Issue by nathfreder** [firebase/firebase-js-sdk#1083]
### Describe your environment

  * Operating System version: Windows Server 2016 Datacenter
  * Browser version: Google Chrome 68.0.3440.84 (64-bit)
  * Firebase SDK version: 5.3.0
  * Firebase Product: auth

#### Steps to reproduce:
In order to reproduce this issue you must run the code below, you must set the `emailToLoginWith` constant to your email. Running this code created an error, here is the result.
![Error Message](https://user-images.githubusercontent.com/40307305/43581030-cc35113a-962d-11e8-8c12-86eadfe93f4b.PNG)

#### Relevant Code:

```javascript
    const emailToLoginWith = '';

    const actionCodeSettings = {
      url: window.location.href,
      handleCodeInApp: true,
    };

    firebase
      .auth()
      .signInWithEmailLink(emailToLoginWith, actionCodeSettings)
      .then(() => {
        localStorage.setItem('emailUsedToLoginWith', emailToLoginWith);
        console.log('Yay, I just logged in.');
      })
      .catch((err) => {
        alert('Oh no, something is broken.');
        console.error(err);
      });
```

**Comment by bojeil-google** [comment]
You are using this incorrectly.
[`signInWithEmailLink`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithEmailLink) is called with the email and the optional link. The [`sendSignInLinkToEmail`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sendSignInLinkToEmail)
API takes an email and an `ActionCodeSettings` object.

**Comment by nathfreder** [comment]
Thank you.
