### ISSUE TITLE
Firerstore timestamps are incorrectly saved to backend

### ISSUE THREAD

**Issue by swftvsn** [firebase/firebase-js-sdk#1084]
### [REQUIRED] Describe your environment

  * Operating System version: High Sierra
  * Browser version: All
  * Firebase SDK version: 5.3.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
I populate model like this:
```ts
import * as firebase from 'firebase/app'
import 'firebase/firestore'

const myObject = {
  timestampie: firebase.firestore.Timestamp.fromDate(new Date())
}

//Save object to database using batch.

```

But the data is saved to backend (according to the firestore web-console) as object containing properties nanoseconds and seconds. 

The app is an Angular 6 app written in typescript and gets compiled down to es5. Odd thing is that it works locally, but fails only when I do production build and deploy it. 

The question: given these symptoms, I think that Firestore thinks my timestamp is ordinary object and thus saved as one - how can I make sure that Firestore sees my timestamp as timestamp?

Edit: I played a bit more with this, and it seems that in local development this line
```ts
console.log(myObject.timestampie, typeof myObject.timestampie, myObject.timestampie.constructor.name)
```
prints out
```
Timestamp nanoseconds: 900000000 seconds: 1533234666__proto__: Object "object" "Timestamp"
```
but when run in production it produces
```
{seconds: 1533234339, nanoseconds: 670000000} "object" "Object"
```
Is this the root cause for what's happening?

**Comment by wilhuff** [comment]
This is very likely a dup of #921, either because you're using Vue devtools or something similar.

**Comment by swftvsn** [comment]
OK, thanks for the pointers. I'll keep documenting my journey here in hopes it helps some poor souls that come after.

**Comment by swftvsn** [comment]
On a side note, if vue and angular are both affected, some serious masses will be hit with this one..

**Comment by wilhuff** [comment]
As far as I know, vanilla Angular is not affected.

**Comment by swftvsn** [comment]
If I use this production configuration (which was earlier the standard produced by the cli):
```json
...
         "configurations": {
            "production": {
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
...
```
The changes made to the standard conf are `optimization` and `buildOptimizer`. I also use AngularFire2. And all the latest libs associated. Maybe it's some optimization in uglify-js?
