### ISSUE TITLE
firebase.initializeApp() does not expose firestore() function

### ISSUE THREAD

**Issue by erewh0n** [firebase/firebase-js-sdk#1091]
### [REQUIRED] Describe your environment

  * Operating System version: mac OS 10.13.4
  * Browser version: N/A (react native app)
  * Firebase SDK version: 5.0.3
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Calling `firebase.initializeApp(config).firestore()` errors out with `undefined is not a function`. This occurs whenever I try to run the react native application. However if I run the same code directly with `node` this error does not occur. Something confusing is happening when it is run within the react native project / Android simulator.

#### Steps to reproduce:
* Use `react-native-cli` to initialize a new app.
* Add firebase@5.0.3 to the project.
* Call `firebase.initializeApp(config).firestore()` with a valid `config` object.

#### Relevant Code:

```
import Firebase from 'firebase';

const config = {
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
};

Firebase.initializeApp(config).firestore();
```

**Comment by mikelehen** [comment]
Can you try using the latest SDK (5.3.1)?

If that still doesn't work, I'm curious if adding this helps:

```
import 'firebase/firestore';
```

Thanks!

**Comment by erewh0n** [comment]
I tried creating a clean project (using `react-native-cli`). By simply importing `firestore` the app fails to launch with:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/1220273/43871094-02a9cbb4-9b49-11e8-9f44-d019fb237f3a.png">

Here's a gist of the code and `package.json`: https://gist.github.com/erewh0n/d4703727343a06f37151905fa0496e7a

When I change the import to `import 'firebase/firestore';` the error is:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/1220273/43871277-d0142da6-9b49-11e8-8a46-5eb714cd5d53.png">

**Comment by jshcrowthe** [comment]
@erewh0n thanks for helping us dig into this. The first error you are seeing is due to the Polyfills that firebase loads to ensure that the environment is stable. The reasoning is outlined here: https://github.com/firebase/firebase-js-sdk/issues/871#issuecomment-401431517.

In principle, the following code should work:

```
import firebase from 'firebase/app';
import 'firebase/firestore';

const config = {
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
};

firebase.initializeApp(config).firestore();
```

**Comment by Yingi** [comment]
I have thesame issue as @erewh0n

**Comment by Yingi** [comment]
Actually mine is a bit complex because, It ony gives the error when i do the import in my App.js file

When i do the import

import Firebase from 'firebase';

It works in other screens of my app, but doesnt work in the App.js which the entry level of the app

**Comment by MohitOpenxcel** [comment]
down vote
favorite
I am using com.google.firebase:firebase-admin:6.5.0. I have set following rules in firebase.

{
  "rules": {
    ".read": true,
    ".write": true
  }
}
Still I am getting

PersistentConnection: pc_0 - Authentication failed: permission_denied (Access denied.).

**Comment by mikelehen** [comment]
If any of you are still running into issues, please open a new issue with full repro instructions so that we can investigate.  Thanks!

**Comment by bbangert** [comment]
@mikelehen I'm hitting this as well. I referenced our issue here which @Zirak tracked down to the @firebase/firestore not having a `select` method, while `@google-cloud/firestore` does have a `select` method on its `Query` object. Unfortunately only this library seems to have a testing app allowing one to use the emulator with Firestore, and there's a feature mismatch where the Javascript library does not have `select`.

**Comment by ryanpbrewster** [comment]
It's possible to use the `@google-cloud/firestore` SDK with the Firestore emulator (as of version 2.1.0!). There's an example of how to get started in this PR: https://github.com/googleapis/nodejs-firestore/pull/654

**Comment by bbangert** [comment]
@ryanpbrewster Great, thanks a lot!
