### ISSUE TITLE
After offline data persistence is enabled in an electron app, the error '@firebase/firestore: Firestore (5.0.4): FIRESTORE (5.0.4) INTERNAL ASSERTION FAILED: Persisting non-string stream tokens is only supported with mock persistence .' is shown

### ISSUE THREAD

**Issue by iaaflaafc** [firebase/firebase-js-sdk#1092]
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra
  * Browser version: Electron/1.8.7 Chrome/59.0.3071.115
  * Firebase SDK version: 5.3.1
  * Firebase Product: firestore

#### Steps to reproduce:

I am using firestore in an electron app. It works fine if data persistence is not enabled.
However, if offline data persistence is enabled, the following error is shown
```
 Uncaught Error: FIRESTORE (5.0.4) INTERNAL ASSERTION FAILED: Persisting non-string stream tokens is only supported with mock persistence .
    at fail (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:153)
    at assert (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:161)
    at LocalSerializer.toDbTarget (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:10213)
    at IndexedDbQueryCache.saveQueryData (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:9896)
    at IndexedDbQueryCache.addQueryData (/Useirrs/d/node_modules/@firebase/firestore/dist/index.nod…:9865)
    at /Users/dir/node_modules/@firebase/firestore/dist/index.nod…:11789
    at /Users/dir/node_modules/@firebase/firestore/dist/index.nod…:7456
    at PersistencePromise.wrapUserFunction (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:7442)
    at PersistencePromise.wrapSuccess (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:7456)
    at PersistencePromise._this.nextCallback (/Users/dir/node_modules/@firebase/firestore/dist/index.nod…:7426)
```
#### Relevant Code:

```javascript
import * as firebase from 'firebase';
import 'firebase/firestore';

firebase.initializeApp({
  apiKey: ...,
  authDomain: ...,
  databaseURL: ...,
  projectId: ...,
  storageBucket: ...,
  messagingSenderId: ...,
});

firebase.firestore().settings({ timestampsInSnapshots: true });
firebase.firestore().enablePersistence().then(() => {
    const db = firebase.firestore();
    // use the db variable to access firestore db.
});
```

**Comment by schmidt-sebastian** [comment]
@iaaflaafc Thanks for letting us know about this. 

We believe that you should only see this error if you are using our GRPC-based SDK in an environment that also supports IndexedDb. Most environments support one or the other: A typical browser supports IndexedDb, but not GRPC for networking. Node, on the other hand, doesn't support IndexedDb but uses GRPC as the network layer.

Can you verify that you are using the Node version of the Firestore SDK (one installed from NPM)? Your problem will likely go away if you follow the Web setup of our SDKs: https://firebase.google.com/docs/web/setup and use the SDKs from `https://www.gstatic.com/firebasejs/...`

**Comment by iaaflaafc** [comment]
Yes, I am  using Node version of the Firestore SDK. (installed using `npm install firebase`)

After using the SDKs from the web setup using `<script src="...">`, the issue is not observed.
