### ISSUE TITLE
FR: Easy way to compare equivalent Firebase references

### ISSUE THREAD

**Issue by fongandrew** [firebase/firebase-js-sdk#11]
* Operating System version: Ubuntu 16.04
  * Firebase SDK version: 3.9
  * Firebase Product: database

When creating two Firebase database queries, it'd be nice if we could compare said refs for equivalence, like so:

```javascript
let x = firebase.database().ref('/items').orderByValue();
let y = firebase.database().ref('/items').orderByValue();
x.equiv(y) // => true
```

The use-case is for something like a React component that takes a Firebase ref as a prop. When we're passed a Firebase reference that's functionally different from the previous ref, we want to unsubscribe from the old ref and start listening to the new one. But if the new ref is essentially the same as (but necessarily `===` to) the old one, we want to avoid the overhead of unsubscribing and resubscribing.

**Comment by mikelehen** [comment]
This is actually already supported (it was added a few months ago)!  There's an isEqual method that does exactly as you suggest.

Docs are here: https://firebase.google.com/docs/reference/js/firebase.database.Query#isEqual
Implementation is here: https://github.com/firebase/firebase-js-sdk/blob/master/src/database/js-client/api/Query.js#L472)

**Comment by IchordeDionysos** [comment]
Is there anything similar in Firestore?

**Comment by mikelehen** [comment]
Not yet, but it's a good feature request.  Feel free to open a separate issue.
