### ISSUE TITLE
4.1.4 breaks my app.

### ISSUE THREAD

**Issue by iSuslov** [firebase/firebase-js-sdk#111]
I don't know what's going on, but yesterday, when you updated to 4.1.4 my Polymer app continuously kept losing WS connection and tried to reestablish it. It seems to happen if polymerfire elements tried to call firebase-database.js more than once (components have imports). I tried to debug, did a lot of silly manipulations with my code and it turned out to be just nightmare! When you changed it to 4.1.5 which is not even in release list this problem was solved. So it is clearly `v4.1.4` issue and I was trying to debug my app the whole day without success. The timeframe between two releases (1 day) makes me think that you knew about this issue so PLEASE next time DO some notice that you AWARE of this crazy behavior and resolving it.

**Comment by bojeil-google** [comment]
Hey @iSuslov, this is likely related to https://github.com/firebase/firebase-js-sdk/issues/106 which was quickly fixed as soon as we detected the issue (reported by our developers). We put out a notice about this immediately but you may have missed it: https://status.firebase.google.com/incident/Realtime%20Database/17068
We sincerely apologize for the inconvenience. We are taking steps to ensure we have adequate integration test coverage for future launches. Please, if you ever encounter, any strange issue, feel free to report it so we can either quickly fix it or help you resolve it.
