### ISSUE TITLE
onSnapshot returning type seem not correct, it's returning void instead of unsubscribe function in TypeScript

### ISSUE THREAD

**Issue by micksatana** [firebase/firebase-js-sdk#1110]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.13.6
  * Browser version: Google Chrome 67.0.3396.99
  * Firebase SDK version: 5.3.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
In TypeScript, the return type of onSnapshot seems not correct, according to [the document on how to detach a listener of onSnapshot](https://firebase.google.com/docs/firestore/query-data/listen#detach_a_listener)
The document mentioned it returns unsubscribe function, but in the source code of TypeScript is returning void

#### Relevant Code:
https://firebase.google.com/docs/firestore/query-data/listen#detach_a_listener
https://github.com/firebase/firebase-js-sdk/blob/2f17ba02a3a139678b849cd53b2199156e5bc6d1/packages/firestore-types/index.d.ts#L1072-L1095

**Comment by mikelehen** [comment]
The types are admittedly a bit hard to read, but onSnapshot() is actually returning `() => void` which is a function that takes no parameters and returns void, which is in fact the unsubscribe function mentioned in the docs.  So I think it's actually correct.

**Comment by sven09** [comment]
hi, this helped us ;-D

```
// in class
syncFunctionRef?: Function = undefined; // to keep the ref to your sync
...
// create your onSnapshot
this.syncFunctionRef = await yourSyncCall(params); // await is important in order to get a function and not a promise

...
// stop it
if (syncFunctionRef) {
  this.syncFunctionRef(); // stops the sync
}
```
