### ISSUE TITLE
Typings not being told in package.json

### ISSUE THREAD

**Issue by degroote22** [firebase/firebase-js-sdk#1111]
[Here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/auth/package.json) it doesn't have it.

But [here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/app/package.json#L6) it does.

The Typescript compiler will warn me if I do something like this:
```typescript
const importFirebase = async () => {
  // dynamic import, will return promise
  const fb = await import("firebase/app");
  await import("firebase/auth"); // <-- Error: [ts] Could not find a declaration file for module 'firebase/auth'.
  // 'xxx/node_modules/firebase/auth/dist/index.cjs.js' implicitly has an 'any' type.
  return fb;
};
```

I'm using it with next.js and I don't know why but their's compilation step will fail if I don't add the typing lines to the related "package.json".

Is there a reason not to add the typings to other packages (auth, database, storage don't have it, for instance)?
If there isn't I'd be happy to submit a PR but I wouldn't mind if you did it by yourselves 👍

**Comment by Feiyang1** [comment]
Hi @degroote22, firebase component packages don't export anything. What they do is patching the firebase namespace you import from firebase/app, so it is correct that they don't have any typings (because they don't have export).
You can try 
```javascript
(await import("firebase/auth")) as any
```
Hope it helps!

**Comment by degroote22** [comment]
It did not make the compiler error go away.
My fix was creating a .d.ts file with this content
```typescript
declare module "firebase/storage" {

}
declare module "firebase/auth" {

}

```

**Comment by ifiokjr** [comment]
The issue can be seen in the rxfire examples.

https://github.com/davideast/rxfire-samples/blob/f4b0b6b7959b7fb52b04fb7a8041edb17b92a872/src/preact/index.tsx#L20-L23
