### ISSUE TITLE
Email/Password Sign-in bypasses Authorized domains

### ISSUE THREAD

**Issue by Slaybesh** [firebase/firebase-js-sdk#1117]
### [REQUIRED] Describe your environment

  * Operating System version: Win10
  * Browser version: Version 68.0.3440.106 (Official Build) (64-bit)
  * Firebase SDK version: 5.3.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

I haven't authorized localhost to sign in. Using Google OAuth for example indeed blocks the sign in on localhost. However using Email/Password still allows me to access the database, allowing users to change or modify the entire db structure and mess everything up.

#### How it affects me:
The ability to sign in anywhere introduces a huge security risk for my use, since only my domain and an application should be allowed to change anything in the database.

#### Steps to reproduce:
* Disable localhost in Authorized domains.
* Sign in with Email and password in localhost

#### Relevant Code:

```javascript
var config = {
	apiKey: "apiKey",
	authDomain: "authDomain",
	databaseURL: "https://databaseURL.firebaseio.com",
	projectId: "projectId",
	storageBucket: "",
	messagingSenderId: "messagingSenderId"
};
firebase.initializeApp(config);

// shouldn't allow access, still does
firebase.auth().signInWithEmailAndPassword('user@domain.com', 'user123').catch(function(error){
	console.log(error.message);
});

// mess up database
firebase.database().ref('securelocation/').update({
	important_stuff: 'messing stuff up',
});
```

**Comment by bojeil-google** [comment]
This is currently working as expected. We don't restrict email/password to authorized domains. Email password is supported from various environments such as Cordova/react-native, native mobile flows and even server side flows (Node.js, etc). In addition, adding restrictions based on header origin can easily be bypassed. The right and secure way to do this is by adding a reCAPTCHA requirement to verify origin. This is something we are looking into in our roadmap.

**Comment by Slaybesh** [comment]
I see! But this isn't a feature is it? Not something that deliberately has been done this one in order to achieve something? Because from my perspective it seems to just introduce having to find unneeded workarounds. May I ask why this has been done this way? 

Furthermore I'd like to suggest hinting at this problem in the sign in method tab on firebase, so users would be aware of this restriction. I just happened to stumble across this problem, someone who wasnt as lucky as i was will have major problems if they rely on sign in with email/password like i did.

The reCAPTCHA is definitely a way to solve the problem, but for my case unfortunately not usable. Thanks nevertheless!
