### ISSUE TITLE
FR:Calling .off() on some FB "path" should erase any reference to it!

### ISSUE THREAD

**Issue by mehdi-cit** [firebase/firebase-js-sdk#112]
Hello,
I think it is more intuitive to fully clear any data or meta-data about some firebase path once one calls `.off()` on it. 
At least this was what I expected and had to debug for hours to finally get it.
I'm listening to some collection in firebase through "list events" : `child_added, child_changed, child_removed and child_moved`. When I first start listening I get all data and then from then on I only get updates. So far so good! Works as expected.
If I then call `.off()` on my path/reference. It my happen that after sometime I restart listening to that path again (exp: the user reentered that previous chat room) But this time around I do NOT get the initial data annymore. Somehow, firebase assumes that I still have that data that I previously got.
Since I called `.off()` I assumed firebase "totally forgot about it" and I'm back to the state before I did reference that path at all.
If you think the current implementation is more intuitive, then please make it clear in the documentation.
For now, to fix my problem, I need to start by listening to  .once('value' to make sure I always get my initial data after calling .off()!
Thanks for listening.

**Comment by nkpgardose** [comment]
Do we have progress on this?

**Comment by mikelehen** [comment]
If you call .off() and then call .on() again you should get all the initial data again in your new listener.  If that's not happening in some situation, we'll need a code snippet that demonstrates the problem.

**Comment by rommelpe** [comment]
@mehdi-cit are you still experiencing this issue? If so, feel free to provide a minimal app to [reproduce](https://stackoverflow.com/help/minimal-reproducible-example) the issue.

**Comment by mehdi-cit** [comment]
Hello Rommelpe.
Feel free to remove it. I no longer use firebase and cannot remember if this issue was fixed.
Cheers~
