### ISSUE TITLE
TypeError: Cannot read property 'myID' of undefined

### ISSUE THREAD

**Issue by paularodriguez** [firebase/firebase-js-sdk#1126]
I'm using the firebase database into an Ionic App. Initially all is working properly, but after a while the firebase connection breaks. 

The error only appears when I deploy my app using '--prod' flag. 

The complete error message is the following:

![image 1](https://user-images.githubusercontent.com/6568086/44196397-1eb3a700-a13c-11e8-9d05-7152320e9113.png)

  * Firebase SDK version: 5.3.1

**Comment by everettglovier** [comment]
Hi there! I wanted to add that I also have this issue. It only happens in Safari for me, not Google Chrome. It is identical, happening in polyfills.js. It prevents anything Firebase related from working.

**Comment by everettglovier** [comment]
@paularodriguez 
Here is a better thread on this issue:
https://github.com/firebase/angularfire/issues/970

And here is a quick fix:
```
constructor() {
    localStorage.removeItem('firebase:previous_websocket_failure');
}
```

**Comment by Feiyang1** [comment]
closing the issue since the better place to track it is https://github.com/firebase/angularfire/issues/970

**Comment by andrealeo83** [comment]
Why you close the issue if it seems related to firebase-js.sdk and not to angularfire?
