### ISSUE TITLE
import firebase from 'firebase/app' doesn't compile in angular 6

### ISSUE THREAD

**Issue by tamama** [firebase/firebase-js-sdk#1144]
Hi, when I do these imports in an Angular service, it runs into a compilation error.

[firebase-authentication.service.ts]
... ...
import { Injectable } from '@angular/core';
import firebase from 'firebase/app';
import 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
... ...

ERROR in src/app/service/sdk/authentication/firebase-authentication.service.ts(3,8): error TS1192: Module '"/vagrant/workspace/src/gitlab.com/tamama/ai-google-prive-dialogflow/ai-google-prive-dialogflow/target/angular/tamama/node_modules/firebase/index"' has no default export.

...

However, when I replace one of the line by:
import * as firebase from 'firebase/app';

It compiles. Any best practice?

Kind regards,
Tamama

**Comment by davideast** [comment]
Hi @tamama! For TypeScript you need to use

```
import * as firebase from 'firebase/app';
```

That should do the trick, and thanks for using the sub packages!  🙌

**Comment by tamama** [comment]
Hey @davideast, thank you so much!

Kind regards,
Tamama

**Comment by lukepighetti** [comment]
Hello, I am getting this issue with `create-react-app` with typescript defaults

error:

```
import * as firebase from "firebase/app";
componentWillMount() {
    const ref = firebase.database().ref("/projects");
    /// etc
}
```

<img width="1052" alt="screen shot 2018-10-14 at 1 16 00 pm" src="https://user-images.githubusercontent.com/666539/46919834-4f388580-cfb3-11e8-82eb-c4ec5d16dcaf.png">

**Comment by tharindu9** [comment]
Same issue.Can't it use like this ==> import * as firebase from 'firebase'; in angular6 ??

**Comment by rafongol** [comment]
For the issue of firesql change the firebase import in **firesql.d.ts** file to be like this : 
**From** `import firebase from 'firebase/app';`  **To**  `import * as firebase from 'firebase/app';`
