### ISSUE TITLE
Unable to print in Safari whilst subscribed to real time updates

### ISSUE THREAD

**Issue by parkji** [firebase/firebase-js-sdk#1145]
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra 10.13.5
  * Browser version: Safari 11.1.1
  * Firebase SDK version: 5.4.0
  * Firebase Product: Cloud firestore

### [REQUIRED] Describe the problem

When subscribing to real time updates `window.print()` does not work in Safari.

#### Steps to reproduce:

* Subscribe to real time updates using `onSnapshot`, e.g.
* Try to call `window.print()` from console or by adding an event handler to a button.
* See that nothing happens.

#### Relevant Code:

https://stackblitz.com/edit/js-kpoc7t

```javascript
firebase.initializeApp({
   ...
});

const db = firebase.firestore();
let unsub = null;

const sub = () => {
  unsub = db.collection('testing').onSnapshot(d => window.console.log(d.docChanges()));
}

sub(); // Comment this line out to get printing to work
window.print();
```

**Comment by Feiyang1** [comment]
A quick google search shows that any active network connection will prevent safari from invoking window.print(). https://stackoverflow.com/a/48164941
And when you listen to firestore changes, there is always an active connection. So I think it's a not a firebase issue, but how safari implements the print function.
