### ISSUE TITLE
Bug: Publicize Firestore arrayUnion

### ISSUE THREAD

**Issue by zshannon** [firebase/firebase-js-sdk#1152]
The example code from the Firestore Web docs doesn't work because `firebase.firestore.FieldValue.arrayUnion` isn't public. [Docs](https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array)

Using `firebase.store.FieldValue._arrayUnion` does work.

**Comment by acrollet** [comment]
@zshannon firebase.firestore.FieldValue.arrayUnion() does actually work for me, I think this could be closed?

**Comment by zshannon** [comment]
Are you using the npm distro?

**Comment by samtstern** [comment]
cc @schmidt-sebastian what's the current status of the npm-distributed Firestore web SDK?  I know this works in the "normal" one.

**Comment by acrollet** [comment]
@zshannon yes, version 5.3.0 of the npm firebase package.

**Comment by zshannon** [comment]
Just installed version 5.4.1 from npm and it's still missing.

`TypeError: firebase.store.FieldValue.arrayUnion is not a function`

Calling `_arrayUnion` works fine.

**Comment by acrollet** [comment]
@zshannon did you try using firebase.firestore.FieldValue.arrayUnion()? (Instead of firebase.store?)

**Comment by zshannon** [comment]
Derp, my fault that was misleading. Yes, I'm calling `firebase.firestore` via an object attribute named `store`

**Comment by schmidt-sebastian** [comment]
You should be able to use arrayUnion() in all JS-based SDKs now. That's Node for Mobile, Node for Server and JS for Web.

**Comment by acrollet** [comment]
How are you importing firebase? Here's my working code, snipped:

`
import firebase from 'firebase';

db.collection('XXX').doc('YYY').update({
  photos: firebase.firestore.FieldValue.arrayUnion({ downloadURL }),
}).then((returnData) => {
  console.log(returnData);
});
`

**Comment by zshannon** [comment]
Getting the same result after `rm -rf node_modules && yarn install && yarn start` with `import firebase from 'firebase'` and `firebase.firestore.FieldValue.arrayUnion` (`firebase.firestore.FieldValue._arrayUnion` still works).

**Comment by schmidt-sebastian** [comment]
What version are you using? Can you share your output from `yarn list`? You might have a lock file that prevents updates.

**Comment by zshannon** [comment]
```
$ yarn list | grep firebase
├─ @firebase/app-types@0.3.2
├─ @firebase/app@0.3.3
│  ├─ @firebase/app-types@0.3.2
│  ├─ @firebase/util@0.2.1
├─ @firebase/auth-types@0.3.4
├─ @firebase/auth@0.7.3
│  └─ @firebase/auth-types@0.3.4
├─ @firebase/database-types@0.3.2
├─ @firebase/database@0.3.4
│  ├─ @firebase/database-types@0.3.2
│  ├─ @firebase/logger@0.1.1
│  ├─ @firebase/util@0.2.1
├─ @firebase/firestore-types@0.6.0
├─ @firebase/firestore@0.7.1
│  ├─ @firebase/firestore-types@0.6.0
│  ├─ @firebase/logger@0.1.1
│  ├─ @firebase/webchannel-wrapper@0.2.8
├─ @firebase/functions-types@0.2.0
├─ @firebase/functions@0.3.0
│  ├─ @firebase/functions-types@0.2.0
│  ├─ @firebase/messaging-types@0.2.3
│  ├─ @firebase/messaging-types@0.2.3
├─ @firebase/logger@0.1.1
├─ @firebase/messaging-types@0.2.2
├─ @firebase/messaging@0.3.5
│  ├─ @firebase/messaging-types@0.2.3
│  ├─ @firebase/messaging-types@0.2.3
│  ├─ @firebase/util@0.2.1
├─ @firebase/polyfill@0.3.3
├─ @firebase/storage-types@0.2.3
├─ @firebase/storage@0.2.3
│  ├─ @firebase/storage-types@0.2.3
├─ @firebase/util@0.2.1
├─ @firebase/webchannel-wrapper@0.2.8
├─ firebase-tools@4.1.1
│  ├─ firebase@2.4.2
│  ├─ firebase@2.x.x
├─ firebase@5.4.1
│  ├─ @firebase/app@0.3.3
│  ├─ @firebase/auth@0.7.3
│  ├─ @firebase/database@0.3.4
│  ├─ @firebase/firestore@0.7.1
│  ├─ @firebase/functions@0.3.0
│  ├─ @firebase/messaging@0.3.5
│  ├─ @firebase/polyfill@0.3.3
│  └─ @firebase/storage@0.2.3
├─ firebaseui@3.0.0
│  ├─ @firebase/app-types@0.3.1
│  ├─ @firebase/app@0.3.2
│  │  ├─ @firebase/app-types@0.3.1
│  │  ├─ @firebase/util@0.2.1
│  ├─ @firebase/auth-types@0.3.2
│  ├─ @firebase/auth@0.5.2
│  │  └─ @firebase/auth-types@0.3.2
│  ├─ @firebase/database-types@0.3.1
│  ├─ @firebase/database@0.3.2
│  │  ├─ @firebase/database-types@0.3.1
│  │  ├─ @firebase/logger@0.1.1
│  │  ├─ @firebase/util@0.2.1
│  ├─ @firebase/firestore-types@0.4.2
│  ├─ @firebase/firestore@0.5.3
│  │  ├─ @firebase/firestore-types@0.4.2
│  │  ├─ @firebase/logger@0.1.1
│  │  ├─ @firebase/webchannel-wrapper@0.2.8
│  ├─ @firebase/functions-types@0.1.2
│  ├─ @firebase/functions@0.2.3
│  │  ├─ @firebase/functions-types@0.1.2
│  │  ├─ @firebase/messaging-types@0.2.2
│  ├─ @firebase/messaging@0.3.3
│  │  ├─ @firebase/messaging-types@0.2.2
│  │  ├─ @firebase/util@0.2.1
│  ├─ @firebase/polyfill@0.3.2
│  ├─ @firebase/storage-types@0.2.2
│  ├─ @firebase/storage@0.2.2
│  │  ├─ @firebase/storage-types@0.2.2
│  ├─ firebase@^5.0.0
│  ├─ firebase@5.0.3
│  │  ├─ @firebase/app@0.3.2
│  │  ├─ @firebase/auth@0.5.2
│  │  ├─ @firebase/database@0.3.2
│  │  ├─ @firebase/firestore@0.5.3
│  │  ├─ @firebase/functions@0.2.3
│  │  ├─ @firebase/messaging@0.3.3
│  │  ├─ @firebase/polyfill@0.3.2
│  │  └─ @firebase/storage@0.2.2
├─ react-firebase-file-uploader@2.4.1
├─ react-firebaseui@3.0.4
│  └─ firebaseui@^3.0.0
```

**Comment by schmidt-sebastian** [comment]
@zshannon You are pulling in `firebase` twice. Once at 5.4.1, once via `firebaseui` at 5.0.3.

Please update your firebaseui dependency.
