### ISSUE TITLE
React Native: document is not defined

### ISSUE THREAD

**Issue by onmyway133** [firebase/firebase-js-sdk#1157]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.3
  * Browser version: Chrome
  * Firebase SDK version: 5.4.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

I get `document is not defined` in React Native app

#### Steps to reproduce:

- Follow https://firebase.google.com/docs/firestore/quickstart
- Add these in js code

```javascript
import * as firebase from "firebase"
import 'firebase/firestore'
```
- Then I get

![simulator screen shot - iphone x - 2018-08-22 at 09 35 07](https://user-images.githubusercontent.com/2284279/44449528-b444b000-a5ee-11e8-972d-515addfdd2ee.png)

- If I remove `import 'firebase/firestore'` then the issue is gone

**Comment by wilhuff** [comment]
This is a dup of #1138, the fix for which is slated to go out with our next release.
