### ISSUE TITLE
Unable to Proxy Firebase Url

### ISSUE THREAD

**Issue by therynamo** [firebase/firebase-js-sdk#116]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOs Sierra 10.12.5
  * Firebase SDK version: shouldn't make much of a difference in this issue
  * Library version: ^5.1.0
  * Firebase Product: `database`

### [REQUIRED] Step 3: Describe the problem

When attempting to use `firebase-admin`s `initializeApp` function, the URL is strictly enforced. I'm sure this is intended, however it is keeping me from proxying the firebase URL to a local server for testing. Example:
```js
firebase.initializeApp({
  credential: firebase.credential.cert(FIREBASE_CREDENTIALS),
  databaseURL: 'http://localhost:4001/https://my.firebaseio.com'
});
```

Resulting in the following error:

```bash
Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com
```

I use [mockyeah](https://github.com/ryanricard/mockyeah/wiki/Service-Snapshot-CLI) for integration testing, which is a nice solution for being able to record snapshots for outgoing requests and their responses. The only caveat is that in order to record the response you have to proxy the URL so that the server can make the call itself. 

The issue isn't necessarily with implementation on either side. My overall question is, would supporting a proxied URL be feasible?

#### Steps to reproduce:
Listed above.
#### Relevant Code:

Listed above. 

[Related Issue From `firebase-admin`](https://github.com/firebase/firebase-admin-node/issues/63#issuecomment-318475037).

**Comment by therynamo** [comment]
@jshcrowthe thanks for adding the label. I thought I'd add a little more information now that I've explored around looking for more options. 

Since `mockyeah` would not directly work in this situation due to the strict url enforcement on the firbase side, I moved over to `nock` to try and utilize their direct http intercept functionality. Effectively it should have blocked the call from ever being made and just returning `json`. I quickly found out that google oath was the first call being made by `firebase-admin` and that you couldn't directly return the desired response from there. 

I continued to look around and stumbled upon this post, [`Testing Firebase with firebase-server`](https://firebase.googleblog.com/2015/04/end-to-end-testing-with-firebase-server_16.html) by @urish. This looked really promising and seemed to be the right answer. Unfortunately it was not. After diving in and looking at the example code, both [the example mentioned in the post using mockery](https://github.com/urish/firebase-server/blob/ce6db9414e0ae515e0fd8b2b226cb5a91631b0d4/test/server.spec.js#L11-L28) and the [example on master using proxyquire](https://github.com/urish/firebase-server/blob/master/test/server.spec.js#L20-L31), I found out it is nearly impossible for me to accomplish this using [`Jest`](https://facebook.github.io/jest/docs/en/getting-started.html). After some more time debugging I began to look more to see if anyone else had any similar issues to my own. I then found this in `proxyquire`'s issues, https://github.com/thlorenz/proxyquire/issues/152, leading to this https://github.com/facebook/jest/issues/1937#issuecomment-254089972. 

Turns out the issue with the `firebase-server` approach is using `Jest` due to its mock system. Now you're probably asking why this is a problem for `firebasse-js-sdk` to solve since it seems to be all in the testing framework/mocking system I'm using. To some degree I would agree with that. However, I do believe the issue here comes down to the strict URL enforcement. I'm sure there are some good reasons behind that design choice, but I'm finding it difficult to write integration tests that don't affect the system under test. The best current solution is hacking the `/etc/hosts` file and redirecting the `my.firebaseio.com` URL there, for CI that wont work though. Proxying the base url, even if it was a flag we could pass to the `initializeApp` method to indicate that we're testing, would be wonderful. What would be even better is if we could pass `localhost:5000` into the base url, such that we can use `firebase-server`.

**Comment by rockwotj** [comment]
@therynamo if you set up something like DNSmasq (or just modify your /etc/hosts) you have override a subdomain to a local proxy. That way test-db.mylaptop.local will work and the SDK will parse the database name as test-db. You could also use this to override a database url (foo.firebaseio.com) to another IP

**Comment by jshcrowthe** [comment]
I don't know that I see an issue with allowing localhost URLs. I would defer to @schmidt-sebastian for a final say on that, but I think this could be a great PR for someone to take on.

**Comment by vincentwoo** [comment]
I also want more flexibility in proxying Firebase by domain name to avoid China's block on Firebase traffic.

**Comment by jshcrowthe** [comment]
This was submitted in a PR and should be fixed. LMK if there are any other issues!

**Comment by therynamo** [comment]
Stellar! Thanks @jshcrowthe! 👍
