### ISSUE TITLE
FR: RxFire for Dart

### ISSUE THREAD

**Issue by clarktank** [firebase/firebase-js-sdk#1163]
Can you make the equivalent of RxFire for RxDart and Firebase.
I use Flutter and would love to use this package.

**Comment by samtstern** [comment]
We're already doing a lot of work for Flutter plugins for Firebase:
https://github.com/flutter/plugins

We don't have any plans to explicitly support non-Flutter Dart use cases.  If you'd like to improve the FlutterFire plugins please file an issue on that repo.

cc @kroikie as FYI
