### ISSUE TITLE
Cannot query from Firebase for my React Native app?

### ISSUE THREAD

**Issue by maggiefei** [firebase/firebase-js-sdk#1167]
I'm really new to coding and app development (trying to make my first app) so I'm really sorry if this isn't the right place to ask my question, but I think I'm experiencing a bug, so here goes. It seems I can retrieve all my data from my Firebase Realtime Database with the following:

```
let itemsRef = firebaseApp.database().ref('/');

itemsRef.on('value', (snapshot) => {
let data = snapshot.val();
let item = Object.values(data);
this.setState({item});
});
```
But when I try to query with specific parameters instead of just retrieving all the information, I always end up with this error: @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot convert undefined or null to object

This is how I'm trying to query information... I'm following the documentation, and somehow my code works when I retrieve all information but not when the only change I make is adding a query?

```
let itemsRef = firebaseApp.database().ref('/');

itemsRef.orderByChild('roundedBPM').equalTo('100').on('value', (snapshot) => {
let data = snapshot.val();
let item = Object.values(data);
this.setState({item});
});
```
Is this a bug? Is anyone else having problems querying from Firebase? Or am I doing something wrong? Any help would be much appreciated, thank you!

Is anyone else having problems querying from Firebase or am I doing something wrong? Any advice would be much appreciated, thank you!

**Environment:**
* Operating System version: MacOS High Sierra 10.13.6
* Browser version: Safari 11.1.2
* Firebase SDK version: Web
* Firebase Product: realtime database

**Steps to Reproduce:**
Query information from Firebase database with specific parameters (using orderByChild and equalTo)

**Comment by puf** [comment]
Also posted on https://stackoverflow.com/questions/52030292/cannot-query-from-firebase-for-my-react-native-app

**Comment by Feiyang1** [comment]
Resolved in stackoverflow
