### ISSUE TITLE
Uncaught DOMException logged in @firebase/auth 0.7.3 when used in Chrome extension content script

### ISSUE THREAD

**Issue by Macil** [firebase/firebase-js-sdk#1170]
### Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: 68.0.3440.106
  * Firebase SDK version: 5.4.1
  * Firebase Product: auth, database

### Describe the problem

When Firebase is used in a Chrome extension content script, it causes "Uncaught (in promise) DOMException: 'ready' is only supported in pages." to be logged to the console. The error is caused by this line: https://github.com/firebase/firebase-js-sdk/blob/6ce67519761d256341cceeadfb429a9a1346e557/packages/auth/src/utils.js#L1483

The Chrome extension content script is injected into 3rd party pages, so we don't want to do anything with service workers. If there were a setting to disable attempting to use service workers at all, it would solve the problem really well for us.

This error did not appear in Firebase 5.4.0 (`@firebase/auth` 0.7.2), and seems to be introduced in https://github.com/firebase/firebase-js-sdk/pull/1141.

#### Steps to reproduce:

Use Firebase in a Chrome extension content script.

#### Relevant Code:

Our content script's firebase usage only consists of this:

```javascript
import * as firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';

// ...
const config = {...};
firebase.initializeApp(config);
const firebaseUser = await firebase.auth().signInWithCustomToken(config.token);
firebase.database().ref('...').on('child_added', data => {
  // ...
});
```

Chrome causes `navigator.serviceWorker.ready` accesses to reject when called in an extension's isolated world: https://github.com/chromium/chromium/blob/6a0529ac33f137fa3e850218415f5bda31dbaa88/third_party/blink/renderer/modules/service_worker/service_worker_container.cc#L394

**Comment by bojeil-google** [comment]
Hmm, interesting. The documentation says that `navigator.serviceWorker.ready` never rejects.
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready
To quote:
" It returns a Promise that will never reject..."
We can modify it to catch rejects and ignore.

**Comment by bojeil-google** [comment]
I have the fix in https://github.com/firebase/firebase-js-sdk/pull/1171

**Comment by AgentME** [comment]
That would work for us! Thanks.

**Comment by rommelpe** [comment]
@Macil Were you able to test your use case after the fix? You may also consider upgrading your JS SDK to the [latest version](https://firebase.google.com/support/release-notes/js).
