### ISSUE TITLE
[firebase-talk]importing firebase/app imports all firebase services

### ISSUE THREAD

**Issue by udielenberg** [firebase/firebase-js-sdk#1173]
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra 10.13.6
  * Browser version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
  * Firebase SDK version: 5.3.1
  * Firebase Product: Auth / Firestore / app
  * Bundled with Webpack 4
  * React Application (self customized, **not** `create-react-app`

### [REQUIRED] Describe the problem
I get this warning message: 
When l `import firebase from 'firebase/app'`, I still get all of firebase services, **and not just the `app`**.

![screen shot 2018-08-29 at 12 20 32](https://user-images.githubusercontent.com/39482108/44778650-37817b00-ab86-11e8-9d9a-c3944441fd73.png)

#### Steps to reproduce:

I created this simple app: https://stackblitz.com/edit/react-b1hykn
add a space in the code to trigger hot reload, or try to refresh the page,
you'll notice in the log that sometimes firebase returns a full package with all its services,
instead of just the ones I asked for.

Is it a caching problem? 
#### Relevant Code:
https://stackblitz.com/fork/firebase-issue-sandbox

**Comment by stevecastaneda** [comment]
I can reproduce this locally but on your simple app example, I don't see the error.

**Comment by udielenberg** [comment]
Did you open the console ?
Its the first and only log

**Comment by Feiyang1** [comment]
@udielenberg yep, it's a caching problem caused by hot reload. Hot reload keeps the firebase instance in memory. You always see auth and firestore components because they are loaded before you remove their imports. Change the reload strategy to page reload and you won't see the problem. It's the same issue as https://github.com/firebase/firebase-js-sdk/issues/1226
