### ISSUE TITLE
Why is PushSubscription not refreshed on public VAPID key update on client?

### ISSUE THREAD

**Issue by abhishekcghosh** [firebase/firebase-js-sdk#1175]
If the VAPID key changes, why don't we refresh the browser's PushSubscription as well with a SWRegistration unsubscribe & subscribe (creating a new PushSubscription with the new VAPID key)? 

https://github.com/firebase/firebase-js-sdk/blob/00b50e170d2df2b44e93f37aa58acf79101a863e/packages/messaging/src/controllers/base-controller.ts#L146-L149

https://github.com/firebase/firebase-js-sdk/blob/00b50e170d2df2b44e93f37aa58acf79101a863e/packages/messaging/src/controllers/base-controller.ts#L263-L270

In the code this looks problematic to me because here a FCM Token is being registered with old PushSubscription (created with old VAPID key that it also maintained in the browser's push-service against this subscription), but in FCM records is being assigned the new VAPID key. This way, it's expected that when FCM is sending a push it will use this new VAPID key to create the JWT auth header to be sent to the push-provider along with the message. But since the PushSubscription is old, the browser's push-provider will try to use it's corresponding (old) VAPID keys to validate the sender (FCM here) when a push message is received by it. Will this not cause a auth failure scenario? 

Apologies in advance if I'm missing something basic or my understanding is incorrect on how VAPID & FCM is supposed to work.

**Comment by DellaBitta** [comment]
HI @abhishekcghosh,

It's been a while since you created this issue and I'd like to see if this is still a concern of yours. Thanks!
