### ISSUE TITLE
reason: Country Blocked

### ISSUE THREAD

**Issue by saeedhei** [firebase/firebase-js-sdk#118]
I'm Developing an Application for `Iranian-American` Celebrity.

**Why People From Iran Gets the Message below?** (I spend more time for Firebase and I don't like to Switch to MongoDB)

![photo_ - - _ - -](https://user-images.githubusercontent.com/25050762/28747855-10289642-74be-11e7-8763-04e507010a2c.jpg)

**Comment by mcdonamp** [comment]
Hi @saeedhei,

At present, we're unable to serve traffic from Iranian IPs. Self-hosting or hosting on a non-US based infrastructure provider is likely your best bet.

[Google's Transparency Policy](https://www.google.com/transparencyreport/traffic/?hl=en#expand=IR) also discusses potential blocking issues external to Google (e.g. per country restrictions).

**Comment by saeedhei** [comment]
**Thank you** @mcdonamp 
I don't know what should I say,
For example I have a language learning app and I'm Telling to US Learners: Please Don't Learn Persian, because That Country is Blocked,
By the way, This is a report to Improving.
Thank you.

**Comment by reiniergs** [comment]
I got the same issue with Cubans, they can't log in my app without using VPN since firebase service is not available for Cuba.

**Comment by monajafi** [comment]
There are is a good alternative to firebase which is open source named parse server I can help you get
that installed in your infrastructure
