### ISSUE TITLE
FireStore + push IDs

### ISSUE THREAD

**Issue by aleclarson** [firebase/firebase-js-sdk#1186]
What's the rationale behind FireStore using plain random IDs instead of Firebase push IDs?

**Comment by wilhuff** [comment]
Push IDs in RTDB create a real performance problem by default for a benefit you can't really count on if you care.

The primary problem is that while push Ids appear to be time ordered, they're not: the time component is generated from the _client's_ local clock, which can be wildly wrong. If you actually want things ordered by time, you're much better off indexing on a field populated from a server timestamp.

A related problem though is that most client clocks are set pretty well, so most values will share a common prefix. Unlike RTDB, Firestore shards its keyspace across multiple servers and the key prefix is the shard key. Random keys distribute writes across all shards, whereas keys with a long common prefix tend to hot-spot on a single shard. You'll see this hot-spotting called out in our [Usage and limits](https://firebase.google.com/docs/firestore/quotas#writes_and_transactions): random keys have effectively unlimited throughput while closely clustered keys are limited to about 500 writes/second.

If you really want to use RTDB-style push IDs, nothing's stopping you: [the source is right here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/src/core/util/NextPushId.ts). However, I advise against doing so :-).
