### ISSUE TITLE
Firebase Auth not working in NW.js 0.30+

### ISSUE THREAD

**Issue by blacksoulgem95** [firebase/firebase-js-sdk#1191]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS Mojave Beta 10.14 (18A371a)
  * Browser version: Chrome 65 (NW.js 0.30+)
  * Firebase SDK version: 5.4.1
  * Firebase Product: auth

#### Steps to reproduce:
I've configured a Nw.js project, and this project runs as chrome-extension. 
When I run auth().singInWithEmailAndPassword(email, password) the Google APIs does not give any answer.

I've tried in two ways, manually handling the firebase login and using FirebaseUI.

![schermata 2018-09-03 alle 00 11 48](https://user-images.githubusercontent.com/11537307/44961235-14e8bc80-af0e-11e8-87fc-a986014c9fed.png)

I've also read about another issue in the same field, but on angularFire2, and the answer was to put the issue here in the Firebase js sdk. 
Since I'm unable to find an issue about this here, I'm reporting this.
The AngularFire2 issue is: https://github.com/angular/angularfire2/issues/1768

I'm working with Vanilla javascript, on a project based on RPG Maker MV, which uses NW.js for rendering.

**Comment by bojeil-google** [comment]
I am not familiar with NW.js and I am currently swamped with stuff to do. If you can help isolate the cause of this (code is open sourced), it would make it easier for us to fix.
I can tell you one thing. We have a different mechanism for sending HTTP requests when running from Node.js or browser:
https://github.com/firebase/firebase-js-sdk/blob/master/packages/app/index.node.ts#L30
I wonder if that could be the reason for this.

**Comment by rommelpe** [comment]
@blacksoulgem95 Were you able to isolate the issue? Or do you have any updates to share with us to look into?

**Comment by blacksoulgem95** [comment]
Hi,
sorry for the late reply but I didn't had time to check in depth what the problem was, also I've not been using NW.js for a while, so I'll try again as soon as is possible to me to check if the situation has changed.
