### ISSUE TITLE
unmet peer dependencies @firebase/app-types

### ISSUE THREAD

**Issue by Fandekasp** [firebase/firebase-js-sdk#1207]
### [REQUIRED] Describe your environment

  * Operating System version: arch linux
  * Firebase SDK version: 5.4.2
  * Firebase Product: auth
  * react-redux-firebase 2.1.8

#### Relevant Code:
When installing my packages with yarn, I get:
```
[2/2] Regenerating lockfile and installing missing dependencies...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
warning "firebase > @firebase/database@0.3.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/firestore@0.7.2" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/functions@0.3.0" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/messaging@0.3.5" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/storage@0.2.3" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/auth > @firebase/auth-types@0.3.4" has unmet peer dependency "@firebase/app-types@0.x".                                                                                                           
warning "firebase > @firebase/database > @firebase/database-types@0.3.2" has unmet peer dependency "@firebase/app-types@0.x".                                                                                                   
warning "firebase > @firebase/firestore > @firebase/firestore-types@0.6.0" has unmet peer dependency "@firebase/app-types@0.x".                                                                                                 
warning "firebase > @firebase/functions > @firebase/messaging-types@0.2.3" has unmet peer dependency "@firebase/app-types@0.x".                                                                                                 
warning "firebase > @firebase/storage > @firebase/storage-types@0.2.3" has unmet peer dependency "@firebase/app-types@0.x".                                                                                                     
warning " > eslint-import-resolver-babel-plugin-root-import@1.1.1" has incorrect peer dependency "babel-plugin-root-import@^5.1.0".          
```

Maybe related: #752, #388 

Doesn't seem to have any bad effect on the product. And since we're installing `firebase` instead of `@firebase/auth` and other required components, I don't think this is an issue related to my environment.

**Comment by Feiyang1** [comment]
After a quick google search, It appears to be a known issue with yarn. If a peer dependency is installed by a dependency's dependency (I know it's a mouthful), yarn will complain about it. Your product is totally safe, there is nothing to worry about. 
You can also use npm install instead, and there is no warning.

**Comment by mackelito** [comment]
@Feiyang1 for reference, please add link to that known bug in yarn if possible.. for me I can never just leave a warning unless I have confirmation and have tracking on the issue :)

**Comment by Feiyang1** [comment]
There you go, https://github.com/yarnpkg/yarn/issues/5347
Yarn thinks it's working as expected, so I doubt it will get fixed. It won't be a problem in our use case, since "@firebase/app-types@0.x" is a dependency of "@firebase/app" which is always required.

**Comment by mackelito** [comment]
Well.. one could just install the types and be gone with it :D 
`yarn add @firebase/app-types@0.x --dev`

**Comment by antoinerousseau** [comment]
So if it isn't Yarn's fault, this issue should be reopened

**Comment by PutziSan** [comment]
I'd also say that's not solved. The "more obvious" solution would be to remove "@firebase/app-types@0.x" as peerDependency and add it as normal dependency?

**Comment by garyo** [comment]
This is biting me as well. The warnings look dangerous even though my app is working fine.

**Comment by arpowers** [comment]
@Feiyang1 Is there a reason you can't move the peerDependencies causing this issue to dependencies? That's the consensus at Yarn.

https://github.com/yarnpkg/yarn/issues/5347
