### ISSUE TITLE
Bug: Firebase Auth Error floods console logs when offline

### ISSUE THREAD

**Issue by vixson** [firebase/firebase-js-sdk#1219]
### My Environment

  * Operating System version: win 10 (64bit)
  * Browser version: google chrome v68.0.3440.106
  * Firebase SDK version: 4.13.1
  * Firebase Product: auth

#### Steps to reproduce:

**Steps to set up and reproduce**
1. Make an auth (login or register into firebase either via OAuth or email/password)
2. Then disconnect the internet.
3. Open the browser console.
4. You would see 3000+ error logs

### Debug output

**Errors in the JavaScript console**

_It had 1277 errors and still counting_ sometime it gets up to 4000+, then freezes the tab and overflow my RAM(8gig)

**Output from `firebase.database().enableLogging(true);`**
`auth/network-request-failed`

**Screenshots**
![angularfire2 auth error](https://user-images.githubusercontent.com/10319620/45191590-1bdc3b80-b23c-11e8-97d7-0732b57fa913.png)

### Expected behavior
It should not overflow the browsers log with too many logs,

it should check for internet connection before retrying auth

### Actual behavior
I thinks it retry's a check for the auth token every millisecond

**Comment by bojeil-google** [comment]
I don't think this is an issue with Firebase Auth(Firebase Auth uses a exponential backoff algorithm for retrial). I think this is related to realtime database. It is trying to get a new ID token after expiration but keeps retrying endlessly for some reason.

**Comment by mikelehen** [comment]
Database should be using exponential backoff too. I'm not sure why you'd be getting so many of these.  @vixson Can you verify this happens with the latest SDK (4.13.1 is somewhat old) and provide a code snippet demonstrating the issue?  This is the first report I've seen.

**Comment by vixson** [comment]
OK let me try updating to the latest sdk @mikelehen

**Comment by mikelehen** [comment]
@vixson Sorry, I'm not sure what you're asking at this point. If you're hitting a different problem, please open a new github issue with as much detail as possible.  If it's related to angularfire2 or angular/fire, please open it on their respective github projects.

**Comment by vixson** [comment]
@mikelehen OK
