### ISSUE TITLE
Bug Internet Explorer 11 Auth

### ISSUE THREAD

**Issue by lpj145** [firebase/firebase-js-sdk#122]
![errointernet11](https://user-images.githubusercontent.com/11980109/28991877-897997e8-7965-11e7-8596-a5bfce5e11bd.PNG)

Hey guys, i'm try use auth function on internet explorer 11, but he said "undefined" error by auth session, i'm using windows 10 with internet explorer 11, this errro cause only internet, google chrome, firefox, works right!

**Comment by bojeil-google** [comment]
I tested in IE 11 Windows 10 and it works as expected.

**Comment by lpj145** [comment]
Please, Tell me Whats version SDK YouTube testing... Me os 4.2.0 and error i don't found solution...

**Comment by bojeil-google** [comment]
I tested with the latest (4.2.0). It may be something else in your app.

**Comment by lpj145** [comment]
you can show me you code test ?

**Comment by puf** [comment]
Cross-posted: https://stackoverflow.com/questions/45517637/firebase-authentication-internet-explorer-11 (please indicate when you cross-post)

**Comment by lpj145** [comment]
i not found solution, i keep try firebase samples, but not works perfect. This is only with IE 11.

**Comment by Geoffrey-Pliez** [comment]
I have the same issue.

I tried polymerfire <firebase-auth> which does not work on IE11.
So I replaced it with firebase.auth().SignInWithEmailAndPassword and I get the same result.
So the problem comes from firebase.auth().

I use the version 4.3.0 of firebase

**Comment by bojeil-google** [comment]
Tested both API SignInWithEmailAndPassword and createUserWithEmailAndPassword in IE11 and both work in 4.3.

**Comment by Geoffrey-Pliez** [comment]
This issue is due at promise-polyfill.
In my case, with wecomponentsjs 1.0.1, it works but webcomponentsjs 1.0.10 break all firebase function

**Comment by jshcrowthe** [comment]
@Geoffrey-Pliez I would love to see an example of what you're describing but it sounds to me more like an interop issue with WebcomponentsJS than an actual SDK issue.

Feel free to re-open if you have more information!

**Comment by Geoffrey-Pliez** [comment]
Yes it was an issue with WebcomponentsJS.
Since v.1.0.11, all works fine.
