### ISSUE TITLE
Error: Mutation callbacks processed out-of-order?

### ISSUE THREAD

**Issue by Bartinger** [firebase/firebase-js-sdk#1222]
### Environment (observed on)

  * Operating System version: Windows 7/10
  * Browser version: Chrome 68.0.3440
  * Firebase SDK version: 5.4.2
  * Firebase Product: firestore

### Problem

After upgrading from firebase: `4.12.1` to `5.4.2` we keep getting the following error (over 100 times in the past 6 days) in our bug reporting tool from multiple users:

     FIRESTORE (5.0.4) INTERNAL ASSERTION FAILED: Mutation callbacks processed out-of-order?

Until now we're not able to reproduce the issue but it seems that once this error occurs all subsequent writes fail as well. We believe that the error happens during the up-sync since the local onSnapshot() listener returns the updated data.

**Comment by mikelehen** [comment]
Thanks for flagging this.  We'll take a look.  There were some major persistence changes in 5.4.0 in preparation for supporting multi-tab persistence, so it's possible something was broken.

If you're able to provide any more information, that would be extremely helpful.  Based on @nuvoPoint's comment it sounds like this may only happen for people that had used your app before you upgraded the SDK and then again afterwards?  (i.e. brand new users with no persisted data don't hit this?)

**Comment by nuvoPoint** [comment]
@mikelehen we had the issue in our cordova app which uses the resent chrome for android version.

**Comment by mikelehen** [comment]
Thanks...  And another question...  Does your app use the disableNetwork() / enableNetwork() APIs?

**Comment by nuvoPoint** [comment]
Not at the time of the issue. It came immediately after the update from 5.3.1 to 5.4.0.

**Comment by mikelehen** [comment]
Unfortunately I'm so far unable to reproduce this.  I wrote a test app that writes documents while performing operations that I could imagine triggering the issue (in particular signing in / out of auth and going online / offline), and I ran it before and after upgrading to 5.4.0.  No assertion.

As this is likely a regression in the SDK, we'd really like to get to the bottom of it quickly, so if you have any other hints that might help me reproduce it, please let me know.  Thanks.

**Comment by pjhartin** [comment]
I have also had the same issue on an Ionic app running angularfire2 latest stable release. Unfortunately, in our case, the **enablePersistence** layer was used to provide offline functionality and data logging in the app. It's going to be painful to have to wipe the indexedDB manually to resolve the issue our users are experiencing.

Do you know of a way to access the offline layer so that I may make a manual copy of the data before wiping?

**Comment by mikelehen** [comment]
It would be extremely helpful if anybody can provide more details about how to reproduce this as we've been unable to.  If we understood the issue better, we may be able to provide a solution.

Unfortunately, manually copying the data before wiping would likely cause the problem to just keep happening, so I don't have any suggestions on that front without understanding the issue better. :-/

**Comment by mikelehen** [comment]
We recently found / fixed an issue that may have been responsible for this, so we believe this should no longer happen with the latest SDK release.

If anybody is still running into issues, please holler.
