### ISSUE TITLE
Use shared TypeScript definitions for common types such as CollectionReference, DocumentReference, WhereFilterOp, etc.

### ISSUE THREAD

**Issue by kossnocorp** [firebase/firebase-js-sdk#1225]
I use Firestore both on the back-end and front-end environments. The problem is that the client library uses `@firebase/firestore-types` package (https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore-types/index.d.ts) while in Node.js types are defined in `@firebase/firestore` (https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts). For the most parts, the interfaces are identical, but because they're defined individually, it prevents me from using shared helpers that I can use both in the browser and on the server.

For instance, I'm trying to create typed wrapper:

![screen recording 2018-08-24 at 01 14 pm](https://user-images.githubusercontent.com/52201/45471935-4dbd3880-b73b-11e8-902b-19c9f354d3a6.gif)

But I can't make it work in both environments because it depends on defenition of `CollectionReference`, `DocumentReference`, `WhereFilterOp`, etc:

<img width="490" alt="image 2018-09-13 at 10 10 59 am" src="https://user-images.githubusercontent.com/52201/45472665-92e26a00-b73d-11e8-9c81-8fc4613cd3f8.png">

**Comment by kossnocorp** [comment]
I've created a copy of this issue in https://github.com/googleapis/nodejs-firestore: https://github.com/googleapis/nodejs-firestore/issues/349

**Comment by schmidt-sebastian** [comment]
Please see reply in https://github.com/googleapis/nodejs-firestore/issues/349#issuecomment-422131322

**Comment by kossnocorp** [comment]
@schmidt-sebastian thanks!
