### ISSUE TITLE
Firebase Sandbox for issues Broken

### ISSUE THREAD

**Issue by DennisSmolek** [firebase/firebase-js-sdk#1226]
I'm attempting to write a different issue and use the guideline. 

The sandbox resource is broken. 

I added `var test = true;` and the output is an error:
<img width="1361" alt="screen shot 2018-09-13 at 4 51 11 pm" src="https://user-images.githubusercontent.com/1397052/45517921-5df20980-b775-11e8-8429-bad0410a3287.png">

Direct link:

https://firebase-issue-sandbox-ga29in.stackblitz.io

**Comment by Feiyang1** [comment]
Hi @DennisSmolek, you can change the reload mechanism from hot reload to page reload in the SETTINGS section in the left panel. The problem you encountered is because hot reload keeps the firebase instance and calls initializeApp on the same instance every time a change is made. Hope it helps!
