### ISSUE TITLE
cannot redirect after logging in

### ISSUE THREAD

**Issue by yomi7117** [firebase/firebase-js-sdk#1227]
ERROR Error: Uncaught (in promise): TypeError: this.auth.user$.map is not a function
TypeError: this.auth.user$.map is not a function

"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "angularfire2": "^4.0.0-rc.1",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "firebase": "^4.2.0",
    "firebase-tools": "^4.2.1",
    "g": "^2.0.1",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.2",
    "zone.js": "~0.8.26"

import { Injectable } from '@angular/core';
import { AuthService } from './auth.service';
import { CanActivate, Router, RouterStateSnapshot,  ActivatedRouteSnapshot } from '@angular/router';

import 'rxjs/add/operator/map'; 

@Injectable({
  providedIn: 'root'
})
export class AuthGuard  implements CanActivate {

  constructor(private auth:AuthService,private router:Router) { }
 
    canActivate(route: ActivatedRouteSnapshot,state: RouterStateSnapshot){
     

 return this.auth.user$.map(user=> {
       if (user) return true;
      this.router.navigate(['/login'], { queryParams: {returnUrl:state.url}});
       return false;
    });

    
  }
}

please help a brother

**Comment by VijayDhanvai** [comment]
Try this, it working fine for me. 

The issue is due to newer version on Angular 6 for **map Syntax**. You need to change for import statement and use `.pipe` with the map in Angular 6 version.
```

import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';
import { AuthService } from './auth.service';
import { map } from 'rxjs/operators';

@Injectable()
export class AuthGuard implements CanActivate{

  constructor(private auth: AuthService, private router: Router) { }
  canActivate() {
     return this.auth.user$.pipe(map (
       user => {
      if ( user ) return true;

      this.router.navigate(['/login']);
      return false;
    }
    ));
  }
}

```
