### ISSUE TITLE
firebase-messaging.js broken on iOS Safari 9

### ISSUE THREAD

**Issue by dimanux** [firebase/firebase-js-sdk#1228]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 9.3.5 / iPad 2
  * Browser version: Safari
  * Firebase SDK version: 5.5.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

I included firebase-app.js and firebase-messaging.js at index.html. The firebase-app.js script was loaded ok, but firebase-messaging.js has error "Strict mode does not allow function declarations in a lexically nested statement". Here is the screenshot of the error from MacOS Web Inspector:
![macos 10 13 high sierra_15_09_2018_17_03_16](https://user-images.githubusercontent.com/2279914/45587125-f02b1680-b909-11e8-918a-63ea6fc6fadf.png)
Here is the screenshot of the same error but with javascript code beautifier:
![macos 10 13 high sierra_15_09_2018_16_37_41](https://user-images.githubusercontent.com/2279914/45587051-dfc66c00-b908-11e8-9f0f-719507114833.png)

**Comment by Feiyang1** [comment]
It's the same issue as https://github.com/firebase/firebase-js-sdk/issues/931 . Closing this one.

**Comment by Feiyang1** [comment]
@ecreatures It looks like a different issue. Firebase messaging does browser compatibility checks before initializing itself, Safari 11.1.2 is probably missing some feature messaging requires. Can you please open a new issue, so I can route to the appropriate person to answer your question?
