### ISSUE TITLE
Unable to import { DocumentReference } from "firebase/firestore";

### ISSUE THREAD

**Issue by wujekbogdan** [firebase/firebase-js-sdk#1229]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: Chrome 69.0.3497.92
  * Firebase SDK version: ^5.5.0
  * Firebase Product: firestore

#### Steps to reproduce:
`import { DocumentReference } from "firebase/firestore";`

Use the `DocumentReference` to indicate a return type of a function.

TS compiler complains that:

```
ERROR in /Users/wujekbogdan/htdocs/sw-rss-dashboard/src/views/SingleEntry/SingleEntry.vue
199:35 Could not find a declaration file for module 'firebase/firestore'. '/Users/wujekbogdan/htdocs/sw-rss-dashboard/node_modules/firebase/firestore/dist/index.cjs.js' implicitly has an 'any' type.
  > 199 | import { DocumentReference } from "firebase/firestore";
        |                                   ^
    200 |
    201 | @Component({
    202 |   name: "SingleEntry",
Version: typescript 3.0.3
Time: 816ms
```

#### Relevant Code:

``` ts
import { Component, Vue } from "vue-property-decorator";
import { DocumentReference } from "firebase/firestore";

@Component({
  name: "SingleEntry",
})
export default class SingleEntry extends Vue {
  get entryRef(): DocumentReference {
    return db.collection("dashboard-entries").doc(this.$route.params.id);
  }
}
```

It looks like thre's something wrong with types declarations for firestore.

**Comment by schmidt-sebastian** [comment]
Please try the following, which should work for you:

```
import { firestore } from 'firebase';
const DocumentReference = firestore.DocumentReference
```

Make sure to install the top-level `firebase` package. For Node, we generally don't recommend importing the individual product-specific submodules.
