### ISSUE TITLE
Connecting to database from within a sandboxed iframe

### ISSUE THREAD

**Issue by Pyrolistical** [firebase/firebase-js-sdk#123]
* Operating System version: macOS Sierra 10.12.4
  * Firebase SDK version: 4.2.0
  * Firebase Product: database

#### Steps to reproduce:
Attempt to connect to firebase database while within an iframe that is configured with sandbox attribute `allow-forms allow-scripts`.

The Chrome console will error with:
```
Sandbox access violation: Blocked a frame at "http://localhost:8080" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "null" from accessing a cross-origin frame.
```
#### Relevant Code:
https://gist.github.com/Pyrolistical/d07ece34a9956398b2ca75e9e4c985a0

#### Workaround:

The issue seems to be firebase tries to create an internal iframe first, then opens a websocket. but creating the iframe from within a sandboxed iframe causes the error.

We can workaround this by forcing websockets with:
`firebase.database.INTERNAL.forceWebSockets()`

**Comment by rommelpe** [comment]
@Pyrolistical it is working as expected when loaded in iframe. We are closing this issue as part of the issue cleanup effort
