### ISSUE TITLE
FR: Support shallow query

### ISSUE THREAD

**Issue by soumak77** [firebase/firebase-js-sdk#124]
Is there any plan to have the javascript SDK support the [shallow parameter](https://firebase.google.com/docs/database/rest/retrieve-data#shallow) for queries?

**Comment by pvdyck** [comment]
+1 !

**Comment by eanderson4** [comment]
+1 !
It adds a complicating factor to our codebase to use Rest API for shallow queries, it is hard to do these fast https://stackoverflow.com/questions/35149008/firebase-rest-api-persistent-connection-speed-optimisation and duplicating these records/keeping them in sync is not always practical.

**Comment by Whyser** [comment]
+1. Would also like this feature. In some cases you really don't want to duplicate data and having this would be great! Could we know if there's any plans to add this, or are our wishes in vain? :)

**Comment by schmidt-sebastian** [comment]
Thanks for your suggestion! This is actually how queries work by default in Firestore. We currently don't have any plans to change these semantics in the RTDB SDK.

**Comment by trollkotze** [comment]
SAD

**Comment by kkm** [comment]
+1?!

**Comment by trollkotze** [comment]
@kkm: In this context, "+1" means something like "thumbs up", "I like this suggestion", or "#metoo".

With a split personality you could also do a "+2" or "#methree" etc.

But for this issue probably this won't get any more traction. 'tis supposed to be a special distinguishing feature of Firestore against Firebase, it seems. Maybe not technically feasible for Firebase, who nose.
