### ISSUE TITLE
Cloud Firestore - offline file size and file type limits

### ISSUE THREAD

**Issue by inglesuniversal** [firebase/firebase-js-sdk#1241]
Hello, I would like to ask the following question. I would like to know about the Cloud Firestore offline file size and filed type limits that you currently have available for mobile apps as well as the local browser. can the user for example have several videos or audio files like MP3 or Flac audio available for offline viewing or listening? Do you have a table or chart that shows what the limits are? And lastly do you have any sample code for this matter? Thank you so much

**Comment by samtstern** [comment]
@inglesuniversal Cloud Firestore is a database, so there is no concept of "files" or "file type".  You could try and store binary data in a document within the database, but it would be an unstructured `Blob` field and be subject to a 1MB limit.  Additionally, the Cloud Firestore offline cache would not be a very performant place to keep binary files.

You probably want to look at Cloud Storage if you want to store files:
https://firebase.google.com/docs/storage/

However Cloud Storage has no built-in offline caching, you'd have to build that yourself.
