### ISSUE TITLE
sendEmailVerification() not working with some mail-providers

### ISSUE THREAD

**Issue by kim-marcel** [firebase/firebase-js-sdk#1242]
* Operating System version: Mac OS 10.13.6
  * Browser version: Chrome 69.0.3497
  * Firebase SDK version: I'm not sure, which version angularfire2 uses
  * Firebase Product: auth
  * Firebase: 5.5.1
  * Angularfire2: 5.0.2
  * Angular: 6.0.8

#### Steps to reproduce:

When using angularfire2 and the code below to create a new user and send a verification E-Mail no email is being sent. I think this is a bug either in the firebase SDK or in angularfire2. I alread opened an [issue](https://github.com/angular/angularfire2/issues/1895) in their repository.

I found examples online that seem to work with the code below using older versions of angular/ angularfire2.

#### Relevant Code:

```javascript
  emailSignUp(email: string, password: string) {
    this.afAuth.auth.createUserWithEmailAndPassword(email, password).then(
      () => {
        this.verifyEmail();
      }
    );
  }

  verifyEmail() {
    this.afAuth.authState.subscribe(
      (user) => user.sendEmailVerification().then(
        () => console.log('email sent')));
  }
```

**Comment by bojeil-google** [comment]
If this is only an issue with angularfire2, you should file it in the corresponding repo.
If not, provide details on the error you are seeing or the network request that is failing.

**Comment by kim-marcel** [comment]
I did some more testing and found out that only some mail-providers (I found one for now) don't work. The ones I've come across are addresses from @gmx.de, @gmx.net and @gmx.at. On my Gmail and Outlook address I can receive the verification email.

I think this is either an issue with the firebase SDK as angularfire2 is just a wrapper around it and doesn't handle sending mails or it is a problem with my mail provider.

The email gets sent successfully according to firebase, no errors are thrown and 'email sent' is logged to the console.

I also found a stackoverflow [post](https://stackoverflow.com/questions/52193608/firebause-authentication-emails-sent-but-not-received-on-special-email-addresse) with the same issue.

**Comment by mattk90** [comment]
Having the same problem with the iOS SDK. Super weird! Any updates?

**Comment by kim-marcel** [comment]
@mattk90 Unfortunately, I don't have any updates. According to the StackOverflow post I've linked above a workaround is to set up your own SMTP-Server. However, this doesn't resolve the actual problem of not receiving mails when using the built-in firebase-email-server.

**Comment by dabo248** [comment]
Any news on this issue? 

We're facing the same problem with the iOS and Android SDK and using our own SMTP-Server is not the best workaround..

**Comment by bojeil-google** [comment]
We're not aware of any issues. If you are experiencing issues with email sending, this repo is not the place to report it. This is a client SDK repo. Please open a [Firebase Support issue](https://firebase.google.com/support/).
