### ISSUE TITLE
Firebase database 5.5.1 fails to init in Android 4.4.4

### ISSUE THREAD

**Issue by shonek007** [firebase/firebase-js-sdk#1243]
### [REQUIRED] Describe your environment

  * Operating System version: Android 4.4.4
  * Browser version: Default webview for Android 4.4.4 stock
  * Firebase SDK version: 5.5.1
  * Firebase Product: database

#### Steps to reproduce:

Simply add firebase database version 5.5.1 to a webview project (Cordova/Phonegap) and firebase will fail to initialize throwing the following error:

Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function. firebase-database.js:1
Uncaught TypeError: Object [object Object] has no method 'database' firebase.js:14

This does not happen in the previous version that I was using, version 4.6.2 of firebase. The version 4.6.2 works completely fine in Android 4.4.4

**Comment by mikelehen** [comment]
@Feiyang1 Is this the thing you just fixed?

**Comment by Feiyang1** [comment]
@mikelehen yep. This is the same issue as https://github.com/firebase/firebase-js-sdk/issues/931. It will be addressed by this week's release.
