### ISSUE TITLE
Login error!! error:The redirect operation has been cancelled by the user before finalizing. 

### ISSUE THREAD

**Issue by Santoshah** [firebase/firebase-js-sdk#1254]
The sign in page opens and I log in with my Gmail id then it directs back to the app then shows this error. Not sure where I am missing.

I am using the firebase app domain.

Cordova 8.0.0 tried with 7.0.0 also
npm 5.6.0
node 8.11.1
windows 7

sdk android-28

```   
<script>
      // Initialize Firebase
      var configfirebase = {
        apiKey: "***********************",
        authDomain: "*****************.firebaseapp.com",
        databaseURL: "https://f*************.firebaseio.com",
        projectId: "************",
        storageBucket: "************",
        messagingSenderId: "**********",
      };
      firebase.initializeApp(configfirebase);
    </script>
```

```
var provider = new firebase.auth.GoogleAuthProvider();
function firebaselogin() {
    firebase.auth().signInWithRedirect(provider).then(function() {
      return firebase.auth().getRedirectResult();
    }).then(function(result) {
      var token = result.credential.accessToken;
      var user = result.user;
      app.dialog.alert('Login success!! Welcome:' + result.user );
    }).catch(function(error) {
      // Handle Errors here.
      var errorCode = error.code;
      var errorMessage = error.message;
     app.dialog.alert('Login error!! error:' + errorMessage );
    });
}
```

![screenshot_4](https://user-images.githubusercontent.com/3863771/46063123-845a7080-c189-11e8-84c5-829830cf38d0.png)

EDIT
-------------------
I had missed this step.
```# Substitute *com.firebase.cordova* with the iOS bundle ID of your app.
cordova plugin add cordova-plugin-customurlscheme --variable \
    URL_SCHEME=com.firebase.cordova --save
```

After updating URL_SCHEME with my widget id  `com.buzzwidgets.fix` I am getting this error.

```code: "auth/argument-error"
message: "getRedirectResult failed: Expected 0 arguments but got 1."
__proto__: Error```

**Comment by wti806** [comment]
@Santoshah You need to provide the SDK version you are using. And it would be helpful to provide your config.xml as well. Thanks

**Comment by Santoshah** [comment]
I don't know how to check sdk version. 

But I went through the docs again from top to bottom. I found that I had missed to add 

`<preference name="AndroidLaunchMode" value="singleTask" />`

Now I added it and its working fine. 

Thanks for your co-operation. So kind of you.
