### ISSUE TITLE
email field is null for Twitter users, but it's in the providerData

### ISSUE THREAD

**Issue by shaqq** [firebase/firebase-js-sdk#1257]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Sierra 10.12.6
  * Browser version: Chrome 68
  * Firebase SDK version: 5.5.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

1. Auth via Twitter
2. see `firebase.auth().currentUser.email` to be null
3. however `firebase.auth().currentUser.providerData[0].email` is not null

**Comment by bojeil-google** [comment]
Do you happen to have "multiple accounts per email" enabled?

**Comment by shaqq** [comment]
Nope! One account per email address

**Comment by bojeil-google** [comment]
I can't recreate this. Here is our FirebaseUI sample app: https://fir-ui-demo-84a6c.firebaseapp.com/
Sign in with twitter will populate the top level email.

**Comment by shaqq** [comment]
Hm I'm using the [React component](https://github.com/firebase/firebaseui-web-react) like so:

```js
const uiConfig = {
  signInFlow: 'redirect',
  signInOptions: [firebase.auth.TwitterAuthProvider.PROVIDER_ID],
  callbacks: {
    signInSuccessWithAuthResult: () => false
  }
};

<StyledFirebaseAuth uiConfig={uiConfig} firebaseAuth={firebase.auth()} />
```

and i register an function when the component mounts:

```js
firebase.auth().onAuthStateChanged(
      (firebaseUser) => this.handleOnAuthStateChanged(firebaseUser));
```

**Comment by rommelpe** [comment]
This is an expected behavior. Twitter does not readily share emails of users. You need to request the additional permission to get the email.

![twitter_email_permission](https://user-images.githubusercontent.com/56452310/68770506-3b050300-0661-11ea-9541-e48d5350b44b.png)

We are closing this issue as part of the issue cleanup effort.
