### ISSUE TITLE
"update" instead of "create" validation rules are applied when calling the `add` method.

### ISSUE THREAD

**Issue by wujekbogdan** [firebase/firebase-js-sdk#1261]
### [REQUIRED] Describe your environment

 * Operating System version: macOS 10.13.6
 * Browser version: Chrome 69.0.3497.92
 * Firebase SDK version: ^5.5.0
 * Firebase Product: firestore
#### Relevant Code:

Security rules:

```javascript
service cloud.firestore {
  match /databases/{database}/documents {
    function isManager() {
      return get(/databases/$(database)/documents/managers/$(request.auth.uid)).data.id == request.auth.uid;
    }

    function companyDataIsValid(data) {
    	return data.name is string && data.name.size() <= 50;
    }

    match /{document=**} {
      allow read, write: if false;
    }
    
    match /companies/{company} {
      allow read: if resource.data.isActive == true || isManager();
      allow create: if companyDataIsValid(request.resource.data) || isManager();
      allow update: if isManager();
      allow delete: if isManager();
    }
  }
}
```

Document I use in Simulator and in the JS client

``` json
{
  "name": "test"
}
```

Client-side code:

``` js
db.collection('companies')
  .add({
    name: 'test',
  })
  .then((done) => {
    console.log(done);
  })
  .catch((err) => {
    console.error(err);
  });
```

#### Steps to reproduce:

1. Perform the  **create** operation on `/companies/company` using Simulator as non-authenticated user: **success** as expected.
2. Perform the **update** operation on `/companies/company` using Simulator as non-authenticated user: **failure** as expected. 
3. Perform the **create** operation on `/companies/company` using JS client as non-authenticated user: **failure** <-- **THIS IS NOT EXPECTED**.
2. Perform the **update** operation on `/companies/company` using JS client as non-authenticated user: **failure** as expected. 

On the 3rd step I would expect success, but instead I get `Error: Missing or insufficient permissions.` error in the JS console. 

I suppose that maybe, under the hood, the JS clients creates an empty document, and then calls `update`.  This is the only reason that comes to my mind that would result in validation error that I've just described.

**Comment by schmidt-sebastian** [comment]
Can you verify that the document indeed does not yet exist on the backend? The simulator "trusts you" when you select create versus update and does not verify whether the backend already has a document. I just applied your setup with the latest Firestore release and was not able to reproduce your issue.

If you issue persists, then it would help us if you could send us debug logs. They will show how how many writes the SDK is sending. We should indeed only be sending one. 

Debug logging can be enabled here: https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#setLogLevel

**Comment by rockwotj** [comment]
So there is a bug in the rules engine that incorrectly failed this request. If you change `isManager()` to be the following, this will work as expected (or wait for the fix to go to production).

```javascript
 function isManager() {
      return request.auth != null && get(/databases/$(database)/documents/managers/$(request.auth.uid)).data.id == request.auth.uid;
    }
```

**Comment by rockwotj** [comment]
This fix rolled out a while back.
