### ISSUE TITLE
Firebase does not work from Electron renderer context.

### ISSUE THREAD

**Issue by burtonator** [firebase/firebase-js-sdk#1264]
### [REQUIRED] Describe your environment

  * Operating System version:  Ubuntu 18.0.4
  * Browser version: Electron 3.0.0
  * Firebase SDK version:  5.5.2
  * Firebase Product: firebase cloud firestore (auth, database, storage, etc)

#### Steps to reproduce:

Firebase can't be used within the renderer context via typescript (or 'require') in Electron.

Electron is split into two processes.. the main process which is basically node and the renderer which is basically chromium.

However, if you 'require' firebase from within the renderer you get the following exception (see below).

This means I can't use Typescript from Electron to build Firebase apps.

I think this has something to do with detecting that it's running on nodejs and trying to go that route.

However, if I use the suggested route using <script> elements and just calling the firebase auth code in the examples, everything works perfectly.

There needs to be some way for it to detect that it's running in a browser and go that route instead.

```
/home/burton/projects/polar-bookshelf/node_modules/grpc/src/grpc_extension.js:53 Uncaught Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-x64-glibc
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/burton/projects/polar-bookshelf/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/grpc/src/grpc_extension.js:53)
    at Object.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/grpc/src/grpc_extension.js:63)
    at Module._compile (internal/modules/cjs/loader.js:711)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/grpc/src/client_interceptors.js:145)
```

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by burtonator** [comment]
and I'm not a JS module expert so was difficult to piece things together here.

**Comment by burtonator** [comment]
It's tangentially related to Firebase.

*IF* you were to get GRPC working it's fine but firebase is taking a more complicated and unnecessary code path because it's trying to work with node.  It doesn't realize that it's running in the renderer context - probably because it sees module.exports.

Firebase works just fine if I include it via <script> and perform some hacks to get the types to load but it's kind of ugly that way.

**Comment by hsubox76** [comment]
So this an old issue but it seems like a module resolution issue. In the intervening 5 years we've made a lot of changes to the mainfields and module.exports in the various `package.json`s which should be really good at conforming to the expectations of most tooling in terms of whether to pick up the browser bundle or the node bundle. Feel free to open a new issue (and mention the bundler or tooling) if module resolution is still bringing in the wrong bundle.

Also see: https://medium.com/firebase-developers/using-firebase-in-electron-tips-and-tricks-24ac5b44bf5a (somewhat outdated unfortunately)
