### ISSUE TITLE
How to use with requireJS?

### ISSUE THREAD

**Issue by hamzabinamin** [firebase/firebase-js-sdk#1266]
I'm trying to add firebase javascript components using requireJS in my web project.

Here's the requireJS config file code

```
require.config({
shim: {
'bootstrap': ['jquery'],
'sparkline': ['jquery'],
'tablesorter': ['jquery'],
'vector-map': ['jquery'],
'vector-map-de': ['vector-map', 'jquery'],
'vector-map-world': ['vector-map', 'jquery'],
'core': ['bootstrap', 'jquery'],
'firebase': {
    exports: 'firebase'
},
'firebase-database': {
    exports: 'firebase-database'
},
'home': ['jquery', 'datatables'],
//'datatables': ['jquery-ui', 'datatables']
},
paths: {
.....
'firebase': 'https://www.gstatic.com/firebasejs/5.5.2/firebase-app',
'firebase-auth': 'https://www.gstatic.com/firebasejs/5.5.2/firebase-auth',
'firebase-database': 'https://www.gstatic.com/firebasejs/5.5.2/firebase-database',
'firebase-messaging': 'https://www.gstatic.com/firebasejs/5.5.2/firebase-functions',
'home': 'assets/js/home/home'
}
```
Here's how I'm trying to use firebase in my home.js file
```

define(["jquery", "datatables", "firebase", "firebase-database"], function ($,d,firebase, database) {

    var config = {
        apiKey: "",
        authDomain: "",
        databaseURL: "",
        projectId: "",
        storageBucket: "",
        messagingSenderId: ""
    };
    firebase.initializeApp(config);

    firebase.database().ref('Services/').push({
        test: "Yup"
    }).then(function onSuccess(res) {
            console.log(res);
    }).catch(function onError(err) {
            console.error(err);
    });
```
I get the following error
**Cannot instantiate firebase-database - be sure to load firebase-app.js first.**

How do I go about adding all of the firebase dependencies before executing my function?

**Comment by Feiyang1** [comment]
Hi @hamzabinamin, given how bundles are built at this point, you can only use the include-all firebase.js file with requireJS. You can do: 
```javascript
paths: {
.....
'firebase': 'https://www.gstatic.com/firebasejs/5.5.2/firebase'
}

define(["firebase"], function (firebase) {
...
});
```

**Comment by rommilg** [comment]
you must call firebase.app.js like "@firebase/app"

    paths =  {
        "jquery": "/lib/jquery/dist/jquery",
        //"firebase": "/lib/firebase/firebase",
        "@firebase/app": "/lib/firebase/firebase-app",
        "@firebase/messaging": "/lib/firebase/firebase-messaging",
    }


    define("sw-firebase",
        ["jquery", "@firebase/app", "@firebase/messaging"],
        function ($, FirebaseApp) {

    var config = {
            apiKey: "aaaaaaaaaaaaaaaaaaa",
            authDomain: "aaaaaaaaaaaaaa",
            databaseURL: "aaaaaaaaaaaaa",
            storageBucket: "aaaaaaaaaaaaaaaaa",
            messagingSenderId: "aaaaaaaaaaaaaaaaaaa"
        };
        FirebaseApp.initializeApp(config);
        const messaging = FirebaseApp.messaging();
    }
