### ISSUE TITLE
V 5.5.2 causes firebase-admin error

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [firebase/firebase-js-sdk#1268]
### [REQUIRED] Describe your environment

  * Operating System version: W10, Build: 17134
  * Browser version: Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
  * Firebase SDK version: 5.5.2 - 5.5.1
  * Firebase Product: firestore (I did not test realtime-db)

### [REQUIRED] Describe the problem

Version 5.5.2 causes the following error `channel.createCall is not a function`. 
Downgrading to 5.5.1 will not show this error. 
The reason this error shows up in the first place is, that the `firebase-admin` uses the `^` flag to indicate the `firebase` dependency. Therefore a new install pulls version `5.5.2`. 

#### Steps to reproduce:

use newest firebase-admin sdk version and set firebase version to 5.5.1 or 5.5.2. Furthermore, simply request any resource from Firestore.

**Comment by mikelehen** [comment]
@schmidt-sebastian @hiranya911 FYI

**Comment by shaunc869** [comment]
Any update on this issue?

**Comment by mikelehen** [comment]
I don't see an issue with the latest firebase-admin.  If you're still running into something unexpected, can you please re-open and add specific repro steps (what versions of what packages are you installing, etc.)?  Thanks!
