### ISSUE TITLE
TODO(multitab): Uncomment when multi-tab is released publicly.

### ISSUE THREAD

**Issue by burtonator** [firebase/firebase-js-sdk#1273]
The latest release doesn't have experimentalTabSynchronization enabled in the typescript bindings:

    // TODO(multitab): Uncomment when multi-tab is released publicly.
    // /**
    //  * Settings that can be passed to Firestore.enablePersistence() to configure
    //  * Firestore persistence.
    //  */
    // export interface PersistenceSettings {
    //   /**
    //    * Whether to synchronize the in-memory state of multiple tabs. Setting this
    //    * to 'true' in all open tabs enables shared access to local persistence,
    //    * shared execution of queries and latency-compensated local document updates
    //    * across all connected instances.
    //    *
    //    * To enable this mode, `experimentalTabSynchronization:true` needs to be set
    //    * globally in all active tabs. If omitted or set to 'false',
    //    * `enablePersistence()` will fail in all but the first tab.
    //    *
    //    * NOTE: This mode is not yet recommended for production use.
    //    */
    //   experimentalTabSynchronization?: boolean;
    // }

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over. Looks like I forgot about one of our many typing files. Fix coming.
