### ISSUE TITLE
Polymer 3 and RXFire

### ISSUE THREAD

**Issue by stucker71** [firebase/firebase-js-sdk#1298]
Given that PolymerFire is not supported for use with Polymer 3 it would make sense to have some use examples for using RXFire with Polymer 3. Most important are Firebase Initialization. User Authentication, including sign in and sign out, and reading and writing data to Firestore and Realtime Database. Perhaps using something like the Polymer 3 Starter Kit.

I'm struggling to find anything. Plenty of info and examples for Angular but nothing for Polymer 3. It's **extremely** frustrating given Firebase, Angular, and Polymer are all in the Google camp. Google sort it out and support and resource Polymer 3 properly please.

**Comment by derhuebiii** [comment]
Agreed, I started my project with Polymer 1 and Firebase (as it was pushed like this a lot). Would be nice to have the support ongoing to be able to stay with Polymer nad Firebase.

I even waited a long time to move to Polymer 3 but it looks like we are left alone a bit :/

**Comment by mmikrut** [comment]
same here. Extremely frustrated right now trying to convert Polymer2 + polymerfire to polymer3, no help, we were promised great tool and then left alone in the wild to fend for ourselves
not impressed

**Comment by MarcusGV** [comment]
Someone has an example with RXFire and Polymer 3 or litelement? please that could help a lot :(

**Comment by derhuebiii** [comment]
@mmikrut @MarcusGV 
I made a very basic implementation (it is more a quick&dirty hack yet) but it works for my project. You are welcome to use it or even better let's work on it to improve it. I am happy to give you more rights to the repository if you are interested. I never created a git rep so please be patient ;)

https://github.com/derhuebiii/polymer3-firebase

**Comment by MarcusGV** [comment]
Thank you very much, of course I will check it, Its hard to find examples with this :), thanks again

**Comment by rommelpe** [comment]
Hey folks, I was able to incorporate Firebase using this [Polymer 3.0 Get Started guide repo](https://github.com/PolymerLabs/start-polymer3). Here's the [workaround steps](https://github.com/firebase/firebase-js-sdk/issues/815#issuecomment-389413719) to be able to initialize Firebase services. 

If you happen to encounter a Firestore `timestampsInSnapshots` error message, get rid of this code below in step [2](https://github.com/firebase/firebase-js-sdk/issues/815#issuecomment-389413719):
```
const settings = {
  timestampsInSnapshots: true,
};

firestore.settings(settings);
```

I haven't tried to import RxFire yet, feel free to test it out.
