### ISSUE TITLE
Presence detection does not handle firestore connection issues.

### ISSUE THREAD

**Issue by hudovisk** [firebase/firebase-js-sdk#1300]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: Chrome 69.0.3497.100
  * Firebase SDK version: 5.5.0
  * Firebase Product: firestore, database

### [REQUIRED] Describe the problem
Following the guide: https://firebase.google.com/docs/firestore/solutions/presence for checking whether the user is online or offline does not account for when the firestore service has connection issues. `.info/connected` returns  true even when the user cannot connect with firestore.

#### Steps to reproduce:
1. Testing project: https://github.com/hudovisk/firestore-connection
2. Use a proxy to throttle the connection to firestore services.
3. Check the console log. 

![screen shot 2018-10-10 at 10 03 19](https://user-images.githubusercontent.com/5161722/46738127-c39dbc80-cc73-11e8-9284-9ddfe427b30a.png)

**Comment by hudovisk** [comment]
Is there any other way to listen for the online state changes of firestore? I found a 'hacky' way but was wondering if there is a cleaner way of doing this.

```javascript
const firestoreInitializationCheck = setInterval(() => {
      // This object is loaded async and we don't have a callback for it
      // so we check for it each 500ms
      if (firestore._firestoreClient) {
        // Overwrite the function responsible for handling firestore online state
        // so we can track whether we are online or offline
        const that = firestore._firestoreClient.remoteStore.onlineStateTracker;
        const _onlineStateHandler = that.onlineStateHandler;
        that.onlineStateHandler = function() {
          // arguments[0] is an enum type with:
          // 0 - Unknown
          // 1 - Online
          // 2 - Offline
          if (arguments[0] === 2) {
            console.log("offline");
          } else {
            console.log("online");
          }
          return _onlineStateHandler.apply(that, arguments);
        };
        clearInterval(firestoreInitializationCheck);
      }
    }, 500);
```

**Comment by mikelehen** [comment]
@hudovisk Can you explain what you're trying to accomplish exactly?  The best signal of "online"-ness that we provide is the `metadata.fromCache` flag on snapshots.  So you can do:

firestore.doc('foo/bar').onSnapshot({includeMetadataChanges: true}, snap => {
  if (snap.metadata.fromCache) {
    console.log('offline');
  } else {
    console.log('online');
  }
});
