### ISSUE TITLE
This site has been updated in the background issue

### ISSUE THREAD

**Issue by akilmakda** [firebase/firebase-js-sdk#1306]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04
  * Browser version: Google chrome 69
  * Firebase SDK version: 5.5.1
  * Firebase Product: messaging 

### [REQUIRED] Describe the problem

Two indexed table is created in the same domain. See Below screenshot;
![1](https://user-images.githubusercontent.com/24309502/46873525-6e6cd100-ce54-11e8-87b9-4779d75d6d5b.png)

![2](https://user-images.githubusercontent.com/24309502/46873529-7167c180-ce54-11e8-83c4-008fbf794603.png)

In the same domain only one object store work.

#### Steps to reproduce:

Add scope in service worker. After data store in indexeddb change the scope and run the application again. The second object also creates.

#### Relevant Code:

e.g :  navigator.serviceWorker.register('/firebase-messaging-sw.js' + this.ver, { scope: "/firebase" })
change scope 
 navigator.serviceWorker.register('/firebase-messaging-sw.js' + this.ver, { scope: "/firebase1" })

https://stackblitz.com/fork/firebase-issue-sandbox

```angular 6
// TODO(you): code here to reproduce the problem
```

**Comment by DellaBitta** [comment]
Hi @akilmakda,

It's been a while since this issue has been reported and we're now on SDK version 10. Can you confirm that this is still an inssue in that SDK version? Thanks!
