### ISSUE TITLE
Error using Firebase Auth & RXFIRE

### ISSUE THREAD

**Issue by stucker71** [firebase/firebase-js-sdk#1317]
* Operating System version: OS X Latest Version
  * Browser version: n/a
  * Firebase SDK version: Latest
  * Firebase Product: Auth

When using `import 'firebase/auth';` in my Polymer 3 app and attempt to build (using polymer cli latest version) I get the following errors:

polymer build
info: [cli.command.build]    Clearing build/ directory...

<--- Last few GCs --->

[1708:0x102804400]   101329 ms: Mark-sweep 1311.6 (1493.0) -> 1311.6 (1493.5) MB, 2228.7 / 0.0 ms  allocation failure GC in old space requested
[1708:0x102804400]   103322 ms: Mark-sweep 1311.6 (1493.5) -> 1311.5 (1445.5) MB, 1992.9 / 0.0 ms  last resort GC in old space requested
[1708:0x102804400]   105238 ms: Mark-sweep 1311.5 (1445.5) -> 1311.5 (1441.5) MB, 1915.7 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xcd9e0d25879 <JSObject>
    1: token [/usr/local/lib/node_modules/polymer-cli/node_modules/babel-generator/lib/printer.js:~142] [pc=0x33acf6156a40](this=0xcd974506b61 <Generator map = 0xcd911e96f71>,str=0xcd95cb92341 <String[13]: "twitter.com">)
    2: StringLiteral [/usr/local/lib/node_modules/polymer-cli/node_modules/babel-generator/lib/generators/types.js:144] [bytecode=0xcd9112a1371 offset=37](this=0xcd974506b61 <Ge...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 6: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x33acf5a042fd
 8: 0x33acf6156a40
Abort trap: 6

#### Steps to reproduce:
After installing firebase-js-sdk, simply insert `import 'firebase/auth';`  into Polymer 3 Starter Kit `my-app.js `and build

**Comment by rommelpe** [comment]
@stucker71 I was able to successfully incorporate Firebase into a Polymer 3 with RxFire. I would like to check if you are still facing this issue. If so, we'd be happy to look into this further if you could provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example).
