### ISSUE TITLE
restore

### ISSUE THREAD

**Issue by MooazHammam** [firebase/firebase-js-sdk#1320]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by Feiyang1** [comment]
Closing it since there is no information.
