### ISSUE TITLE
Firestore / gRPC does not use proxy authentication info from electron

### ISSUE THREAD

**Issue by jmeinke** [firebase/firebase-js-sdk#1321]
### Environment

  * Operating System version: Windows 8 / 10
  * Browser version: Electron 2.0.9
  * Firebase SDK version: ^5.4.0
  * Firebase Product: Firestore

#### Steps to reproduce:
Our company has built an electron application using Firestore and now we are trying to deploy the application behind a corporate proxy (customer environment). After setting the proxy authentication settings using electrons `app.on('login')` all network requests in the application are successful, except for the firestore connection. 

The following error occurs:
```
[2018-09-21T09:09:13.556Z]  @firebase/firestore: Firestore (5.5.0) [Connection]: GRPC stream error. Code: 14 Message: 14 UNAVAILABLE: Connect Failed
[2018-09-21T09:09:13.557Z]  @firebase/firestore: Firestore (5.5.0) [PersistentStream]: close with error: FirebaseError: [code=unavailable]: 14 UNAVAILABLE: Connect Failed
[2018-09-21T09:09:13.557Z]  @firebase/firestore: Firestore (5.5.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: 14 UNAVAILABLE: Connect Failed
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

#### Relevant Code:
Debugging the HTTPS request log on the proxy side shows, that the requests by gRPC do not include the proxy authentication info that was given to electrons login function using the following code:
```
app.on('login', function(event, webContents, request, authInfo, callback) {
  if(authInfo.isProxy) {
    callback('username', 'password');
  }
})
```

Why do the gRPC requests not include the proxy auth info as do all the other requests in the electron app?

**Comment by wilhuff** [comment]
Fundamentally the issue is that gRPC (and Firestore) are unaware of electron, so unless electron goes out of its way to configure gRPC this is going to happen.

You can configure gRPC to use a proxy by setting the `https_proxy` environment variable, as described here:

https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a
