### ISSUE TITLE
Writes using .set() are inconsistent between Safari and Google Chrome for certain objects.

### ISSUE THREAD

**Issue by wlim33** [firebase/firebase-js-sdk#1322]
### Environment

  * Operating System version: macOS 10.14 Mojave
  * Browser version: Safari 12, Google Chrome 69.0.3497.100 
  * Firebase SDK version: 5.5.5
  * Firebase Product: database

### Describe the problem
Writes using `.set()` are inconsistent between browsers(Safari and Google Chrome) when passed certain objects. I found that [`RTCSessionDescription`](https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription) as an argument to `.set()` causes this inconsistency between browsers. In Chrome, the write acts as if the argument is `null`, while in Safari, the argument is treated as a typical object.  

#### Steps to reproduce:

https://react-q7r9je.stackblitz.io

1. Open the link above in Chrome and Safari.
2. Press the grey button.

#### Relevant Code:

```javascript
let x = new RTCPeerConnection();
x.createOffer().then((offer) => {
    firebase.database().ref('/examplepath/').set(offer);
});
```

#### Suggested Explanation 
This occurs because of `Object.prototype.hasOwnProperty.call` in the util package, found [here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/util/src/obj.ts). The function returns different things when called on example object above in different browsers, due to how the different browsers implement [`RTCSessionDescription`](https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription).

**Comment by mikelehen** [comment]
Thanks for the report.  Using custom objects with set() is usually not a best practice because the class information is lost when it gets serialized to the database and the set of fields extracted can vary by browser as you see.  The recommended approach would be to not use the RTCPeerConnection object directly and instead to extract the relevant fields into your own object, e.g.:
```
firebase.database().ref(...).set({type: offer.type, sdp: offer.sdp, ... });
```
