### ISSUE TITLE
[auth] getRedirectResult persisted after sign out

### ISSUE THREAD

**Issue by Ehesp** [firebase/firebase-js-sdk#133]
* Operating System version: Mac OS
  * Firebase SDK version: 4.2.0
  * Firebase Product: auth

### Describe the problem

On single page application (SPA), `auth().getRedirectResult()` is persisted even after calling `auth().signOut()`. This means that any page after signing out which subscribes to `getRedirectResult` still returns a user credential.

This means any SPA will need to force a refresh/redirect after sign out, e.g:

```js
  firebase.auth().signOut().then(() => {
    // We need to refresh otherwise redirect state is
    // persisted
    window.location = window.location.origin;
  });
```

This breaks the flow of an SPA.

**Comment by bojeil-google** [comment]
This is work as intended. `signOut` only clears the persistence of a user, eg: currentUser is null. Even after signOut, if you keep a reference to that user, it remains fully functional. In fact, you can even call `linkWithRedirect` on a signed out user and still get it back on redirect via getRedirectResult, provided the operation was successful.

**Comment by Ehesp** [comment]
Okay thank you!

**Comment by bojeil-google** [comment]
You're welcome @Ehesp.

**Comment by ayyash** [comment]
@bojeil-google so what is the way around it? I want the user to logout and stay in the SPA, so they can login again, how to remove the existing user without hard refresh?

**Comment by bojeil-google** [comment]
Hey @ayyash, `signOut` will set the `currentUser` as null. Signing in again will create a new user and update `currentUser` with the new suer. This should be compatible with SPAs.
