### ISSUE TITLE
IE11 "Promise is undefined" when only including firebase/storage

### ISSUE THREAD

**Issue by vbraun** [firebase/firebase-js-sdk#1337]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: IE11
  * Firebase SDK version: 5.5.5
  * Firebase Product: storage

#### Steps to reproduce:

I'm using firebase storage and typescript/browserify to only include that component, as suggested by the helpful js console hint. The import statement is:

```javascript
import * as firebase from 'firebase/app';
import 'firebase/storage';
````

But this fails on startup with the good old `Promise is undefined`  error on IE11.

#### Relevant Code:

When I first import firebase/app then the app starts on IE11

```javascript
import * as firebase from 'firebase/app';
import 'firebase/app';
import 'firebase/storage';
```

Clearly the Promise polyfill is not installed by `firebase/storage`, even though it ends up requiring `@firebase/app`. Probably all components should `require('@firebase/polyfill')` to be on the safe side.

**Comment by Feiyang1** [comment]
Polyfills are included in 'firebase/app'. Since 'firebase/app' is required to be imported before importing any component, it's not necessary to include polyfills in each component. Does the following not working for you?
```javascript
import * as firebase from 'firebase/app';
import 'firebase/storage';
```

**Comment by vbraun** [comment]
Yes, that is what I'm saying: Only using
~~~
import * as firebase from 'firebase/app';
import 'firebase/storage';
~~~
does not work for me, and causes the `Promise is undefined` error on IE11

I looked again at my source file and what is happening is that firebase.* is only used as type in the source file that is browserified first, so the `import * as firebase` is elided (only imports that are used in a value position are emitted to the js output). But `import 'firebase/storage';` is never elided, but also doesn't import the polyfill.  Other source files use firebase as value, of course, but they come later in the load order.

**Comment by Feiyang1** [comment]
Ah I see. Where do you call firebase.initializeApp()? You can import individual component there to avoid the issue.

**Comment by vbraun** [comment]
`initializeApp()` is being called from a separate file, not the one that is first in the load order. But IE11 doesn't get that far, and trips over the first `import 'firebase/storage';`

I agree that not importing `firebase/storage` in the first file avoids the problem, but thats not what the typescript instructions in the browser console message say...

**Comment by Feiyang1** [comment]
You need to make sure firebase/app is loaded before any other component. If the bundler removed the firebase/app due to whatever reason, the constraint is not met. And you need to import the component where the constraint can be met. 

Do you see a message that says "Cannot instantiate firebase-${component} - be sure to load firebase-app.js first." ?

**Comment by vbraun** [comment]
I know that manually importing firebase/app works around the issue, as I wrote in the ticket description.

I did not get any error on Chrome, for the record. The bundler does load firebase/app when it is being used, namely in the (later) files that use firebase in a value position. But firebase/storage references the Promise global before that, which crashes&burns on IE11.

**Comment by HAKASHUN** [comment]
The same issue occurred in IE 11 with my react application using "create-react-app".

I solved this issue by inserting `import "@firebase/polyfill";`  in `index.js`(app endpoint).

**Comment by Feiyang1** [comment]
@vbraun Chrome natively support Promise and other modern javascript features, so it doesn't need polyfills. The point is that any firebase/{component} has dependency on firebase/app for polyfills and other services, so the correct usage is to import component modules after where firebase/app is actually loaded. In your case, the bundler output doesn't actually load firebase/app in the first file, so it didn't work. 

There might be a way to tell the bundler to include the module even if you only reference types, because you might want the side effect from the imported module (which is the case for you). You should check the bundler's API to find out.

@HAKASHUN Make sure firebase/app is actually loaded before any other component.

**Comment by vbraun** [comment]
I think we all understand whats going on now; At the very least its a documentation bug since firebase literally prints
~~~~
For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):
CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');
ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';
Typescript:
import * as firebase from 'firebase/app';
import 'firebase/<PACKAGE>';
~~~~
to the browser console, which is incorrect here. 

IMHO its also a totally unnecessary trap for the unwary, so better than fixing the documentation would be to just make sure that the polyfill is also loaded in this case. Really that just adds an extra require call for each component, thats negligible overhead for removing a rather tricky corner case.

**Comment by Feiyang1** [comment]
I agree that we could provide a more complete example for Typescript usage that includes initialization. 

Including polyfills in each component is redundant and doesn't solve any problem. You can't use components standalone without firebase/app. Even with polyfills they will throw an error without importing firebase/app first. From the whole package's standpoint, importing polyfills in one place (firebase/app) is the right choice. So IMO, It's more of an education thing than how the code is supposed to work.

On the side node, we may remove polyfills completely in the future release and developers should choose what to include depending on the browsers they want to support.

I hope it helps clarify ...
