### ISSUE TITLE
Response data is missing data field after preflight response

### ISSUE THREAD

**Issue by rafinskipg** [firebase/firebase-js-sdk#1338]
### Describe your environment

  * Operating System version: ubuntu
  * Browser version: chrome 
  * Firebase SDK version: "firebase": "^5.5.6",
  * Firebase Product: functions

###  Describe the problem

after a preflight response from the firebase function I get this error from the sdk

```
 Error: Response is missing data field.
    at new HttpsErrorImpl (index.cjs.js:58)
    at Service.<anonymous> (index.cjs.js:504)
```

I can not call the firebase functions from my app. I don't know how to deal with this pre-flight issue. Maybe there's another way to do it on firebase.

**Comment by pankajparkar** [comment]
Any updates on this issue? I'm badly stucked at this.

**Comment by mrvnklm** [comment]
Same here, any updates?

**Comment by rafinskipg** [comment]
@mrvnklm  do you mean that the server must respond with data to the preflight response?

**Comment by mrvnklm** [comment]
@rafinskipg no, the firebase function response must contain data object.

**Comment by rafinskipg** [comment]
@mrvnklm , interesting... I stopped using this SDK long ago, because of this problem, but maybe i dare to try again someday. Thanks for your insights

**Comment by lneninger** [comment]
[Firebase documentation](https://firebase.google.com/docs/functions/callable-reference#response_body) requires the json with a data field.

**Comment by rommelpe** [comment]
@rafinskipg could you confirm if you are still having this issue? If so, would you mind sharing the detailed steps you’ve taken that led to the error message encountered (with a sample [reproducible code ](https://stackoverflow.com/help/minimal-reproducible-example)would be great).

You may also consider upgrading your JS SDK to the [latest version](https://firebase.google.com/support/release-notes/js).
