### ISSUE TITLE
Cannot install firebase npm

### ISSUE THREAD

**Issue by KeevanDance** [firebase/firebase-js-sdk#1341]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Node JS: 11
  * NPM: 6.4.1

### Describe the problem

`npm install --save firebase`"

Cannot install the package, all other packages are installing perfectly fine. If i run this command again, I will get a lot of VSStudio C# errors not sure why? 

#### Relevant screenshot:

![image](https://user-images.githubusercontent.com/10778294/47621372-b9c5e700-dac4-11e8-926c-dc85ef47ddba.png)

**Comment by KeevanDance** [comment]
I was able to get it installed by --force, but I feel like this is not the best :/

**Comment by kczx3** [comment]
I get the same.  No pre-builts for Node 11 it looks like.  Possible I don't have the tools for building native Node add-ons that it needs but wouldn't mind seeing if there is something else at play.

**Comment by Feiyang1** [comment]
It seems to be an issue with Node 11. see https://github.com/grpc/grpc-node/issues/594
As @kczx3 mentioned, downgrading to Node10 is the workaround for now. Please follow the issue in grpc repo for updates.

**Comment by Mindgames** [comment]
grpc/grpc-node#594 Have been fixed. Problem still persist

**Comment by ilog2000** [comment]
Issue still exists. I ran into it with the latest node.js 11.2.0. Workaround with downgrading to node.js 10.13.0 helped
