### ISSUE TITLE
FIRESTORE (5.5.0) INTERNAL ASSERTION FAILED: Got result for empty write pipeline

### ISSUE THREAD

**Issue by sengoontoh** [firebase/firebase-js-sdk#1345]
* Operating System version: Cordova iOS 12.0.1, Android 8
  * Browser version: WebView
  * Firebase SDK version: 5.5.4
  * Firebase Product: firestore (auth, database, storage, etc)

I'm observing this error in some rare instances after doing a "set" operation
FIRESTORE (5.5.0) INTERNAL ASSERTION FAILED: Got result for empty write pipeline
It repeats quite a few times (4-6 times within the next few minutes).

I'm not able to replicate it yet, these were observed in the field.

**Comment by wilhuff** [comment]
Thanks for the report. This seems to be another failure mode related to #1339. For now we're treating these as the same issue.
