### ISSUE TITLE
encoding issue: special characters (umlauts) not saved properly

### ISSUE THREAD

**Issue by neelance** [firebase/firebase-js-sdk#1356]
* Operating System version: multiple
  * Browser version: multiple
  * Firebase SDK version:
```
├─┬ @firebase/app@0.3.4
│ ├── @firebase/app-types@0.3.2
│ ├─┬ @firebase/util@0.2.2
├─┬ @firebase/auth@0.7.8
│ └── @firebase/auth-types@0.3.4
├─┬ @firebase/database@0.3.6
│ ├── @firebase/database-types@0.3.2
│ ├── @firebase/logger@0.1.1
│ ├── @firebase/util@0.2.2 deduped
├─┬ @firebase/storage@0.2.3
│ ├── @firebase/storage-types@0.2.3
```
  * Firebase Product: database

### Describe the problem

The issue is occurring for some of our users since I updated the Firebase packages some weeks ago. Unfortunately I can not reproduce it at will. What I see is that special characters like German umlauts (ä, ö, ü, ß) sometimes do not end up in the database properly but get turned into ��. For most users everything is fine, but for some it fails. Some users contact our support, other just leave our site disappointed. The issue seems to not depend on any particular browser or operating system.

I added some code to explicitly test and detect the issue:
```
ref.update({
  specialCharacterTest: "abc-äöüß-ä-ö-ü-ß-abc",
});
```

If the issue strikes, I end up with this in the database:
```
specialCharacterTest: "abc-�öüß�-��-��-��-��-abc"
```
It is notable that several umlauts in a row cause the � to appear only at the beginning and the end and only the first umlaut is not displayed.

I know that an issue without steps to reproduce is very hard to solve, but I'd still like to bring this to your attention. Maybe someone has an idea why this happens.

**Comment by neelance** [comment]
I finally found the root cause: It is not Firebase's fault, but UglifyJS' which reverses code order. It only affects the code of the long polling fallback, which is why it only happened sometimes. Here is the bug for reference: https://github.com/mishoo/UglifyJS2/issues/3278

**Comment by panfanky** [comment]
Hi, I experience the same problem, anyone knows a workaround? I'm not aware of using any Uglify anywhere, is it a part of the SDK?
My case is described here: https://stackoverflow.com/questions/57178991/json-charset-problem-when-sending-to-firebase-from-js
Thanks!
