### ISSUE TITLE
Installing npm package error (grpc)

### ISSUE THREAD

**Issue by dejanstrancar** [firebase/firebase-js-sdk#1363]
* Operating System version: 10.14.2 Beta
  * Firebase SDK version: 5.5.6
  * Firebase Product: auth, app
  * Node : v11.1.0
  * NPM : v6.4.1

when installing firebase 
```javascript
npm install firebase
```
i get 

```javascript
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! grpc@1.13.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

i tried older versions of firebase but no luck.

**Comment by dejanstrancar** [comment]
Updated:
solution is to downgroade node to v10.13.0 and npm to v6.4.1

**Comment by Feiyang1** [comment]
Known issue with Node 11. https://github.com/grpc/grpc-node/issues/594
