### ISSUE TITLE
Can't build the code with `yarn dev`

### ISSUE THREAD

**Issue by zhaoyi0113** [firebase/firebase-js-sdk#1369]
I cloned this repo and followed the build instruction to build the code with the command `yarn dev`. The command hangs and never stops. Below is the last few lines of output:

```
@firebase/webchannel-wrapper: ^^^^
@firebase/webchannel-wrapper: /Users/joeyzhao/dev/bigcrunch/firebase-js-sdk/packages/webchannel-wrapper/src/index.js:92: WARNING - variable module is undeclared
@firebase/webchannel-wrapper: module['exports'] = {
@firebase/webchannel-wrapper: ^^^^^^
@firebase/webchannel-wrapper: 0 error(s), 15 warning(s)
```

 Below is the version I am using:

```
$ node --version
v8.9.4
$ yarn --version
1.9.1
$ uname -a
Darwin 192-168-1-8.tpgi.com.au 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```
What is the correct way to build the source code?

**Comment by Feiyang1** [comment]
You are running the build with watch. The build was successful as the last line indicates. To do one time build, please run yarn build.
