### ISSUE TITLE
Importing or Requiring Firebase into Electron project leads to failures in WebSockets

### ISSUE THREAD

**Issue by Slapbox** [firebase/firebase-js-sdk#1377]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 7, Windows 10
  * Browser version: Electron v2 & v3
  * Firebase SDK version: 5.5.8
  * Firebase Product: Database

### [REQUIRED] Describe the problem

CONSTANT disconnect and reconnect of WebSockets. Disconnects and reconnects roughly 500x per 24 hour period, based on extrapolation of a 3 hour period. Anonymized Firebase logging output below. 

```
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:10:0 Websocket connection was disconnected. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:10:0 WebSocket is closing itself 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:10: Realtime connection lost. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:10: Closing realtime connection. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:10: Shutting down all connections 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: data client disconnected 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Trying to reconnect in 0ms 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 0: onDisconnectEvents 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Making a connection attempt 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 getToken() completed. Creating connection. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11: Connection created 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11:0 Websocket connecting to wss://s-usc1c-nss-237.firebaseio.com/.ws?v=5&ls=iyT7bcX8tAMsr8uNxJ7Srh8kQnZrUbKV&ns=myProject-prod-db 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11:0 Websocket connected. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11: Realtime connection established. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: connection ready 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: {"r":47,"a":"auth","b":{"cred":"SOME-LONG-STRING"}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Listen on /users/myUID/index for default 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: {"r":48,"a":"q","b":{"p":"/users/myUID/index","h":"hLg1rW5x4h9aA9fGgIkXesWf468="}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Listen on /users/myUID/fileIndex for default 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: {"r":49,"a":"q","b":{"p":"/users/myUID/fileIndex","h":"IbOd4AZWHmGkMlaeuMrm5IBZEM8="}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: from server: {"r":47,"b":{"s":"ok","d":{"auth":{"email_verified":false,"provider":"password","email":"myUser@gmail.com","user_id":"myUID","token":{"email_verified":false,"email":"myUser@gmail.com","exp":1541802299,"user_id":"myUID","iat":1541798699,"sub":"myUID","aud":"myProject-prod-db","auth_time":1529349903,"iss":"https://securetoken.google.com/myProject-prod-db","firebase":{"identities":{"email":["myUser@gmail.com"]},"sign_in_provider":"password"}},"uid":"myUID"},"expires":1541802299}}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11: Primary connection is healthy. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: from server: {"r":48,"b":{"s":"ok","d":{}}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: listen response {"s":"ok","d":{}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: from server: {"r":49,"b":{"s":"ok","d":{}}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: listen response {"s":"ok","d":{}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11:0 Websocket connection was disconnected. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11:0 WebSocket is closing itself 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11: Realtime connection lost. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11: Closing realtime connection. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:11: Shutting down all connections 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: data client disconnected 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Trying to reconnect in 0ms 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 0: onDisconnectEvents 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Making a connection attempt 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 getToken() completed. Creating connection. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:12: Connection created 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:12:0 Websocket connecting to wss://s-usc1c-nss-237.firebaseio.com/.ws?v=5&ls=kQQs676I47Pj96fXCsIk4OyUjNuBk4Wa&ns=myProject-prod-db 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:12:0 Websocket connected. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:12: Realtime connection established. 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: connection ready 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: {"r":50,"a":"auth","b":{"cred":"SOME-LONG-STRING"}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Listen on /users/myUID/index for default 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: {"r":51,"a":"q","b":{"p":"/users/myUID/index","h":"hLg1rW5x4h9aA9fGgIkXesWf468="}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: Listen on /users/myUID/fileIndex for default 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: {"r":52,"a":"q","b":{"p":"/users/myUID/fileIndex","h":"IbOd4AZWHmGkMlaeuMrm5IBZEM8="}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 p:0: from server: {"r":50,"b":{"s":"ok","d":{"auth":{"email_verified":false,"provider":"password","email":"myUser@gmail.com","user_id":"myUID","token":{"email_verified":false,"email":"myUser@gmail.com","exp":1541802299,"user_id":"myUID","iat":1541798699,"sub":"myUID","aud":"myProject-prod-db","auth_time":1529349903,"iss":"https://securetoken.google.com/myProject-prod-db","firebase":{"identities":{"email":["myUser@gmail.com"]},"sign_in_provider":"password"}},"uid":"myUID"},"expires":1541802299}}} 
...node_modules\@firebase\database\dist\index.node.cjs.js:298 c:0:12: Primary connection is healthy. 
```

#### Steps to reproduce:
Run Firebase database using ES6 imports or by requiring modules. Works 100% fine if the Firebase scripts are loaded via `<script>` tags

#### Relevant Code:

```javascript
// I have tried:
import { firebase } from '@firebase/app';
import '@firebase/auth';
import '@firebase/database';
import '@firebase/storage';

// and:
var firebase = require('firebase/app');
require('firebase/auth');
require('firebase/database'); 
require('firebase/storage');

// and 
import * from 'firebase/app';    
import 'firebase/auth';
import 'firebase/database'; 
import 'firebase/storage';
```

This works perfectly fine though:

```js
  let scripts = [];
  scripts.push('https://www.gstatic.com/firebasejs/5.5.8/firebase-app.js');
  scripts.push('https://www.gstatic.com/firebasejs/5.5.8/firebase-auth.js');
  scripts.push('https://www.gstatic.com/firebasejs/5.5.8/firebase-database.js');
  scripts.push('https://www.gstatic.com/firebasejs/5.5.8/firebase-storage.js');
  document.write(
    '<title>myProject</title>',
    scripts
      .map(script => `<script src="${script}" nonce="${nonce}"><\/script>`)
      .join('')
      )
```

Removing my Content Security Policy makes no difference. I also enabled `nodeIntegration`, and disabled `backgroundThrottling`. It makes no difference. This occurs in my app in development and production, on my development and production databases.

Electron does not show a WebSocket connection in any case except loading via `<script>` tags, even though Firebase says it is connecting via WebSockets successfully.

**I can't understand what could possibly cause this discrepancy. This, I believe, is driving my database usage through the roof. I'm seeing usage over 20x what I expect.**

**Comment by mikelehen** [comment]
While I don't know why you're seeing disconnects, I can tell you that index.node.cjs.js is the NODE version of the sdk, which uses the node [faye-websocket](https://www.npmjs.com/package/faye-websocket) module for its websocket functionality rather than the native browser's `WebSocket` implementation.  So that could explain why it behaves differently and why you don't see the websocket connections.

For a bit of added context, the firebase database module has separate entrypoints for node and the browser (see
https://github.com/firebase/firebase-js-sdk/blob/ab4f7aba06df6bdaf506995f92689efc148b2787/packages/database/package.json#L6)

If you're running in node, you'll usually get the node version.  If you're building for the browser, you should get the browser version.

I'm not familiar enough with Electron to know exactly how this applies to your scenario.  But it sounds like you want the browser version (or at least that would solve your issue), but you're getting the node version.  The strange thing is that the node version probably wouldn't work in the browser (since faye-websocket relies on node APIs to create TCP sockets, etc.) and the browser version probably wouldn't work in node (since there's no native `WebSocket` functionality), so I'm surprised you can switch between them and have the rest of your code work.

**Comment by Slapbox** [comment]
@mikelehen thanks very much for some great leads, and especially for shining some light on the phantom WebSockets issue. I'll definitely investigate these.

**Comment by Slapbox** [comment]
@mikelehen, if you have any thoughts on this, I now have my imports getting the standard web version, not the node version, and it works fine unless I lose internet connection at any point (and/or possibly up until I need an auth refresh token.) After this though, it tries exclusively to use long-polling to reconnect, and fails 100% of the time. Using `forceWebSockets()` remedies this and it works perfectly, but I know using the tools in the `INTERNALS` object is not recommended. Do you have any thoughts what could be causing this? Thanks again for your advice. It's gotten me to a pretty much working solution, as far as I can tell.

**Comment by mikelehen** [comment]
@Slapbox Interesting, thanks.  Long-polling is generally more reliable than websockets in browsers and so the SDK will:

1) Try to use WebSockets by default (since it's faster / more efficient).
2) If WebSockets fail, fall back to long-polling (which is expected to work in more scenarios than WebSockets).
3) If long-polling succeeds, try to upgrade back to websockets again for efficiency.

It sounds like you're getting stuck on 2 and so long-polling just fails indefinitely, which is unusual.  Using firebase.INTERNAL.forceWebSockets() sounds like a reasonable workaround for now.

If there's a straightforward way to detect Electron, you could also submit a PR to tweak the logic [here](https://github.com/firebase/firebase-js-sdk/blob/1ed94fa8c61d8a3611d8c10a3b94dd3a5baf14c8/packages/database/src/realtime/BrowserPollConnection.ts#L256) so that we always disable long-polling in Electron.

**Comment by Slapbox** [comment]
@mikelehen thanks a lot for your detailed response! I saw a post of yours on StackOverflow where you mentioned the downsides to disabling long polling, such as potential issues with proxies. Is there any reason you can think of that might explain _why_ Electron is having trouble with long polling? 

There's probably a way to detect Electron and resort to WebSockets, but I would definitely expect long polling to work as a fallback in Electron in any case. I'm certainly not as familiar with the internal workings of the SDK though.

Thanks again!

**Comment by mikelehen** [comment]
TBH I'm not at all clear how Electron is running this code.  Is it a headless Chrome instance?  Something based on Node?  Something else?

Our long-polling implementation relies on adding an invisible frame to the page and dynamically adding `<script>` tags pointing at https://YOUR_DATABASE.firebaseio.com/... URLs.  It's possible that adding the appropriate host to your CSP might solve the issue.

TBH, I think there are probably fewer issues with WebSockets and proxies today than when I wrote that StackOverflow answer (WebSockets have had a lot of time to gain support at this point). So I wouldn't worry too much about disabling long-polling, though it's always worth keeping an eye out for connection issues of course.

**Comment by jsgv** [comment]
I was having the same issue. Looks like Electron runs a renderer with Node.js
![image](https://user-images.githubusercontent.com/2798097/49890753-bd55c900-fdf9-11e8-8a25-3489d0a72747.png)

Firebase & Firestore worked as desired when using the <script> versions.
When including the package via `require` it is pulling in the Node.js version.
I solved for now by including the scripts locally.

**Comment by Saccarab** [comment]
Were you able to get firebase storage work within electron by loading them through script tags?
