### ISSUE TITLE
Unresolved function or method collection() 

### ISSUE THREAD

**Issue by therepo90** [firebase/firebase-js-sdk#1383]
In my Webstorm using firebase-admin package that has `firestore()` inside I can't make my webstorm to resolve the typings for firestore. Unexcluding node modules @google/cloud directory doesnt work. Neiether installing the @google/cloud directory by npm

**Comment by Feiyang1** [comment]
Please open the issue in the admin sdk repo. https://github.com/firebase/firebase-admin-node
