### ISSUE TITLE
DataSnapshot not exposed on firebase.database

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebase-js-sdk#1384]
_Note - copied from https://github.com/firebase/firebase-admin-node/issues/360_

  * Operating System version: any
  * Firebase SDK version: 6.0.0
  * Firebase Product: database

### Describe the problem

`DataSnapshot` is not exposed on `firebase.database`.  From the documentation I would expect to find it at `firebase.database.DataSnapshot`.  I would like to access this for comparison purposes, eg. determining if a thing is a snapshot.

#### Steps to reproduce:

I have made a runnable example on glitch.me:

- See the code: https://glitch.com/edit/#!/hungry-roarer
- Observe the results: https://hungry-roarer.glitch.me

#### Relevant Code:

Related source: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/index.node.ts#L65

Example: 
```js 
var firebase = require('firebase-admin');
console.log(firebase.database.DataSnapshot)
// => undefined 

console.log(Object.keys(firebase.database)) 
// => Reference, Query, Database, enableLogging, INTERNAL, 
//    ServerValue, TEST_ACCESS, initStandalone
```

**Comment by schmidt-sebastian** [comment]
Looks like this is an oversight on our part. PR is coming shortly!
