### ISSUE TITLE
persistence = none + firestore security + custom claims + firestore enabled persistence = leaking custom token between tabs

### ISSUE THREAD

**Issue by Strate** [firebase/firebase-js-sdk#1387]
### Describe your environment

  * Operating System version: Ubuntu Linux
  * Browser version: Chrome 70
  * Firebase SDK version: 5.5.8
  * Firebase Product: auth + firestore security

### Describe the problem

I tries to implement authorization with custom claims set by my backend. I need to open multiple tabs with different claims (and with same user in each other). (this is useful for embedded via iframe application). Application do not behave as I expected, steps are described below.

#### Steps to reproduce:

1. Application goes to my backend, backend authenticates request, generates firebase custome token (with custom claims) and returns token to client.

2. Client receives token, and do these steps: `setPersistence = none`, `signInWithCustomToken(token)`

3. Also client has enabled firestore's `enablePersistence` with `experimentalTabSynchronization: true`

4. When I open 2 tabs of my application with 2 different tokens (and 2 different claims for each other), both tabs actually goes to firebase's backend with same token (randomly selected)

If I disable firestore's `enablePersistence` feature there is no issue, looks like auth token somehow stored in cross-tab storage (indexeddb?). This is very surprising, because on step 2 I explicitly set setPersistence=none for auth package

#### Relevant Code:

I think I can prepare example repo, if it will be needed, but example should require backend code + firestore security rules.

As for now, I solve that problem by just disable `enablePersistence`, but I want to use profits of persistence in future.

**Comment by bojeil-google** [comment]
This works as intended from Auth perspective. Auth persistence is different and not correlated with Firestore persistence. Learn more about persistence https://firebase.google.com/docs/auth/web/auth-state-persistence.
Local persistence is persisted cross tab.

**Comment by Strate** [comment]
@bojeil-google I can agree that this is somehow work as intended. But this was surprising and not very clear. For developer point of view there was a strange security-related issues, but `firebase.auth().currentUser.getIdTokenResult()` returns correct custom claims.

It would be great to warn about this in console, for example.

P.S. This link https://firebase.google.com/docs/auth/web/auth-state-persistence does not contain information about firestore's persistence.

**Comment by bojeil-google** [comment]
Yeah Auth persistence feature was developed independently from Firestore (even before the latter launched). Not all developers using Firebase Auth also use Firestore. But I agree, we should clarify that the Auth persistence doesn't overlap with Firestore persistence in our documentation.

**Comment by wilhuff** [comment]
This is also working as intended from Firestore's perspective. The current identity in the default app applies to all tabs using that app.

The way to implement what you want is to consider the different custom different claims to be different identities. Create a different firebase App for each identity and use Auth and Firestore separately for each one. For example, to use a non-default App with Firestore do this:

```js
let primaryApp = firebase.initializeApp(config, "primary");
let primaryDb = firebase.firestore(primaryApp);

let secondaryApp = firebase.initializeApp(config, "secondary");
let secondaryDb = firebase.firestore(secondaryApp);
```

Any custom token you apply to primaryApp won't affect secondaryApp and vice-versa.

In this example "primary" and "secondary" are arbitrary strings--they have no meaning except to give a name with meaning to you.

**Comment by Strate** [comment]
@wilhuff I am already got expected behaviour with disabled persistence at all. Will your solution allow to enable persistence and giving profits of cache? I mean wouldn't firestore uses different cache slots based on appName?

**Comment by wilhuff** [comment]
Each app is separate so each Firestore instance would have a separate cache.

You could get some benefit by enabling Firestore persistence in only one tab. You don't have to enable persistence in both.
