### ISSUE TITLE
Firestore unhandled internal error 

### ISSUE THREAD

**Issue by Mbouendeu2015** [firebase/firebase-js-sdk#1388]
![image](https://user-images.githubusercontent.com/11772145/48696354-8f80ba00-eb96-11e8-82f8-8ecc3c37e7ee.png)

//cLASS 

import React,{Component} from 'react'
import { View, TextInput, TouchableOpacity, Image, Alert, FlatList, Text,StyleSheet ,Button } from 'react-native'

import firebaseService from '../firebase';

var db=firebaseService.firestore();

const settings ={
	timestampsInSnapshots:true
};

db.settings(settings);

 class LotsOfGreetings extends Component {

	constructor (props){
    super(props)
	
	
    this.handleButtonPress = () => {
		
	alert("A linterieur");
	// Add a new document in collection "cities"
db.collection("test").doc("LA").set({
    name: "Los Angeles",
    state: "CA",
    country: "USA"
})
.then(function() {
    alert("Document successfully written!");
})
.catch(function(error) {
    alert("Error writing document: ", error);
});
    }
		
}
	
    render() {
			
			
			
			return (
		
            <View style= {styles.container}>
				
				<View>
				<TouchableOpacity style={{color:'red'}} 
					onPress={this.handleButtonPress}>
					<Text style={styles.buttonTitle}>TEST  In</Text>
				</TouchableOpacity>
				</View>
				
            </View>
		
            ) 
			
	  
	}
}
 

export default LotsOfGreetings

//FIREBASE INITALIZE

import * as firebase from 'firebase'

import 'firebase/firestore';

import { firebaseConfig } from './firebaseConfig'
 
let instance = null
 
class FirebaseService {
  constructor() {
    if (!instance) {
      this.app = firebase.initializeApp(firebaseConfig);
      instance = this;
    }
    return instance
  }
}
 
const firebaseService = new FirebaseService().app
export default firebaseService;

**Comment by mikelehen** [comment]
Can you please follow the template and include your version numbers, etc.?
