### ISSUE TITLE
FR: Authentication with Microsoft

### ISSUE THREAD

**Issue by suparnavg** [firebase/firebase-js-sdk#1389]
Currently [Firebase authentication](https://firebase.google.com/docs/auth/web/start#next_steps) does not support Microsoft / Outlook authentication. Is this on the roadmap?

**Comment by bojeil-google** [comment]
Thanks @suparnavg, we are looking into this.

**Comment by g-sahu** [comment]
Hi, 
Is there any update on this? Does Firebase plan to support Microsoft/Outlook authentication in the near future?

**Comment by jmandivarapu1** [comment]
Is there any update on this? It would be great if the user can log in with outlook or office 365

**Comment by bojeil-google** [comment]
Microsoft authentication should be working now: https://firebase.google.com/docs/auth/web/microsoft-oauth
