### ISSUE TITLE
Firebase Realtime Database IE - 11 Issue

### ISSUE THREAD

**Issue by pratikindia143** [firebase/firebase-js-sdk#1391]
We have integrated firebase javascript sdk, its working fine for other browsers, not working with IE - 11
We are getting following error (Object doesn't support property or method 'includes' )

**Comment by Feiyang1** [comment]
Hi @pratikindia143, Can you please use the issue template to provide more details, e.g. the version of the library, the relevant code, stacktrace and etc.

**Comment by schmidt-sebastian** [comment]
I don't see any references to `.includes` or `includes()` in the Database SDK. If this is still an issue, can you provide a stacktrace?
