### ISSUE TITLE
Firebase typescript issue during testing.

### ISSUE THREAD

**Issue by maxisg42** [firebase/firebase-js-sdk#1402]
`firebase.auth.Auth.Persistence.NONE` constant causing error "Cannot read property 'Auth' of undefined" while executing tests, but during actual execution there are no errors.  

* Node.js version: 8.11.4
* Firebase version: 5.5.9
* Firebase-admin version: 6.2.0
* Firebase-functions version: 2.0.2

[Related issue](https://github.com/firebase/firebase-js-sdk/issues/752)

**Comment by Feiyang1** [comment]
What does your test look like? Can you please create a minimal reproducible repo? It would be the best way for us to debug.

**Comment by Feiyang1** [comment]
closing it due to inactivity.
