### ISSUE TITLE
FR: comprehensive explanation how to test function with firestore

### ISSUE THREAD

**Issue by hyzhak** [firebase/firebase-js-sdk#1407]
I guess it is Feature Request, because I can't found anything like this in the official docs [here](https://firebase.google.com/docs/firestore/). 

I'm looking for something like Firebase Functions has for unit and integration testing - [Unit testing of Cloud Functions](https://firebase.google.com/docs/functions/unit-testing) - comprehensive explanation how it should implement and which tools use and general recommendations how to mock and simulate/emulate Cloud FireStore locally or in CI env.

In particular I'm writing Firebase Function in Node.js which would use Firebase FireStore, for Actions of Google and I'd like to have good test coverage.

**Comment by calidiHawk** [comment]
Any progress on this?

**Comment by samtstern** [comment]
Apologies for the noise here, the bot closed this as stale because it didn't recognize the `type: feature request` tag, it was looking for `feature-request`.  The config has now been updated.

**Comment by mikelehen** [comment]
Although the bot was wrong, I think this issue is hopefully largely resolved by my comment above: https://github.com/firebase/firebase-js-sdk/issues/1407#issuecomment-455745425

So I'm going to close anyway. :-)  Please feel free to re-open if you have more feedback / questions.  Thanks!
