### ISSUE TITLE
Bad Code bad documentation 

### ISSUE THREAD

**Issue by frank-dspeed** [firebase/firebase-js-sdk#1409]
I only want to open that issue because i am mad about this stack and code it simply don't works don't errors well and also no build documentation

i would call it a total mess up but its funny that your happy with this.

**Comment by merlinnot** [comment]
Hi, thanks for the opinion, however without any specifics it is hard to determine what is the root cause of your issues. Please try again.

**Comment by Feiyang1** [comment]
Appreciate your interest in this project. I understand you are frustrated, but a rant without any detail is neither helpful for us to solve your problem, nor is healthy for the community. We welcome any constructive feedback that help us improve the SDK. I encourage you to open a new issue with details about your experience - what problem you are trying to solve, what the experience is, how do you expect it to work, etc ...

**Comment by frank-dspeed** [comment]
@merlinnot @Feiyang1 https://github.com/firebase/firebase-js-sdk/issues/1363 that is the issue and https://github.com/grpc/grpc-node/issues/594 is solved with the newst version but this project is not update able so easy at all my issue is that it takes me to long to jump into this project to patch it to use the new grpc package that is node 11 compatible

**Comment by frank-dspeed** [comment]
@Feiyang1 talk to google they should spend us some resources and i can give you some releasing code from my projects so you can automate the renovate process. and then apply https://michaljanaszek.com/blog/lerna-conventional-commits
