### ISSUE TITLE
Improve handling of es-modules for browser/node

### ISSUE THREAD

**Issue by lindner** [firebase/firebase-js-sdk#1415]
### Describe your environment

  * Operating System version: MacOS Mojave
  * Browser version: N/A
  * Firebase SDK version: 5.6.0 (via npm)
  * Firebase Product: database

### Describe the problem

- Firebase should detect when a browser based bundle is running in a node environment and warn the user.
- Firebase should either provide esnext bundles or document module loading in differing environments.

#### Steps to reproduce:

Currently Firebase provides a 'main' bundle that is commonjs for Node.  A 'module' bundle that is browser based and a 'browser' bundle that is also browser based.  Here are the entries from package.json:

```
  "browser": "dist/index.cjs.js",
  "main": "dist/index.node.cjs.js",
  "module": "dist/index.esm.js",
```

When using a stock rollup config it will prefer the 'module' bundle.  If the circumstances are right (websocket shim?) it will work.  But often it will fail.  If you enable tracing using a call like this:

```
   firebase.database.enableLogging(true);
```

you will find error messages that look like this:

```
[2018-12-05T14:05:51.668Z]  @firebase/database: p:0: Making a connection attempt
[2018-12-05T14:05:51.690Z]  @firebase/database: getToken() completed. Creating connection.
[2018-12-05T14:05:51.690Z]  @firebase/database: c:0:2: Connection created
[2018-12-05T14:05:51.690Z]  @firebase/database: p:0: Failed to get token: Error: No transports available
[2018-12-05T14:05:51.690Z]  @firebase/database: p:0: data client disconnected
```

To fix this using Rollup you will need to disable `module` resolution for the node-resolve plugin.

```
  import resolve from 'rollup-plugin-node-resolve';
  ....
      resolve({jsnext: true, module: false, modulesOnly: true}),
  ....
```

Not sure of the best solution to this, but a couple come to mind:

- Use jsnext:main for an es6 modules node-oriented artifact.
- Switch module to use a Node version, and use jsnext:browser for the es6 browser artifact.
- Browser code could detect that it is running in the node environment and complain loudly.

**Comment by Feiyang1** [comment]
Thanks for the issue! I think jsnext:main has been deprecated and is equivalent to module. Switching module to use a node version will cause problem for browser use cases (e.g. including unused polyfills), so there is no perfect solution here. 

I think we can do a better job on documenting the build process for the different build targets, and examples with the most popular bundlers. I will keep the issue open and report back once we have an update.

**Comment by lindner** [comment]
Thanks @Feiyang1  -- at the very least people can find this issue when searching for that cryptic error message.  It took me a while to figure out what was going on.

Also would love to have an es6 module for node.  We are using `--experimental-modules` in our environment.

**Comment by Feiyang1** [comment]
Totally reasonable request. Is there any spec on how to specify it on package.json?

**Comment by lindner** [comment]
The latest that I've seen is here:

https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#44-shipping-both-esm-and-cjs

So you'd have:

```
    "main": "dist/index"
```

and then generate dist/index.js and dist/index.mjs files.

**Comment by Feiyang1** [comment]
@lindner We added a warning message if you run browser version of firebase in nodejs.
