### ISSUE TITLE
Event for Permission Change in Messaging

### ISSUE THREAD

**Issue by Plinpod** [firebase/firebase-js-sdk#1417]
Hello,

I am wondering if it's possible to listen to the event of the notification permission changing on a site. I know you can get the current permission state by calling

`firebase.messaging().getNotificationPermission_()`

So it possible to also listen to that change? Something along the lines of

`firebase.messaging().onNoficicationPermissionChange(function() {
    /**Do Something Here**/
})`

Thanks You!

Sorry if I didn't follow the proper posting format. But this isn't an issue just a general feature question.

**Comment by Feiyang1** [comment]
Hi, Can you please describe what your use case is?
You will usually call `firebase.messaging().requestPermission()` to ask for permission. It returns a promise that you can check to see if permission was granted. Is your workflow different than this?

**Comment by Plinpod** [comment]
@Feiyang1 Sure the use case would be if someone at some point granted permission and then removed the permission while they were on the site. I wanted to see if there was a way to catch this as it happened.

**Comment by mmermerkaya** [comment]
Messaging uses [the Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission), and that API unfortunately does not have an event like you specified.
