### ISSUE TITLE
Storage API always logs 404s when files are missing.

### ISSUE THREAD

**Issue by burtonator** [firebase/firebase-js-sdk#1421]
If a file is missing in the storage API the SDK logs a 404 error.

It shouldn't transparently log it. that's my job.  

![image](https://user-images.githubusercontent.com/45447/49677379-6172f500-fa33-11e8-9ba0-5fb9cd11ba78.png)

**Comment by schmidt-sebastian** [comment]
@burtonator Can you let us know what API you are using to download the file? Are you using a URL returned by `getDownloadURL()` to download the file?

**Comment by 55asshole** [comment]
I have this issue with my Gmail account, error code (404) not found, or missing?

**Comment by rommelpe** [comment]
@burtonator @55asshole  are you still having this issue? If so, would you mind sharing the detailed steps you’ve taken that led to the error encountered (with a sample reproducible code would be great). 

You may also consider upgrading your JS SDK to the [latest version](https://firebase.google.com/support/release-notes/js) (7.2.1).
