### ISSUE TITLE
Phone auth error: auth/internal-error / DEVELOPMENT_MODE_MISMATCH

### ISSUE THREAD

**Issue by olegwn** [firebase/firebase-js-sdk#1425]
This issue is more related to internal workings of auth system.  Please help me direct it to the proper repository:

### Describe your environment

  * Operating System version: OS X 10.14.1
  * Browser version: Chrome Version 70.0.3538.102 
  * Firebase SDK version: 3.2.0
  * Firebase Product: auth

###  Describe the problem

Users created by admin SDK with development numbers unable to sign in from clients.

#### Steps to reproduce:

1. Enable phone in sign in method
1. Add developer phone number
1. Create user using admin.auth().createUser() with the developer phone number (i did it using cloud functions admin sdk)
1. Try to sign in using this number from client (javascript or any other)

#### Relevant Code:

```javascript
 Error: An internal error has occurred, please try again. 

code: "auth/internal-error"
userInfo:
NSLocalizedDescription: "An internal error has occurred, print and inspect the error details for more information."
NSUnderlyingError:
code: "3"
domain: "FIRAuthInternalErrorDomain"
message: "underlying error"
FIRAuthErrorUserInfoDeserializedResponseKey:
code: 400
errors: [{…}]
message: "DEVELOPMENT_MODE_MISMATCH"
error_name: "ERROR_INTERNAL_ERROR"
message: "An internal error has occurred, please try again."
```

**Comment by bojeil-google** [comment]
I think this is a duplicate of https://github.com/firebase/firebase-admin-node/issues/405

**Comment by rommelpe** [comment]
@olegwn I would like to check if you are still experiencing this issue or might somehow find it as not related to the mentioned duplicate issue, please feel free to provide a [minimal app](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue.

**Comment by olegwn** [comment]
@rommelpe not encountered it anymore
