### ISSUE TITLE
console error after calling `signOut()` method

### ISSUE THREAD

**Issue by Avrohom** [firebase/firebase-js-sdk#1430]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10 x64 professional
  * Browser version: Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  * Firebase SDK version: "firebase": "^5.7.0"
  * Firebase Product: auth 

### [REQUIRED] Describe the problem
The following console error
![image](https://user-images.githubusercontent.com/6719297/50047537-0da98100-00af-11e9-86fe-00fe79bbfc99.png)
happening after calling `signOut()` on the `auth `object.
#### Steps to reproduce:
call `auth.signOut();`

#### Relevant Code:
`auth.signOut();`

```javascript
// TODO(you): code here to reproduce the problem
signOut(): void {
    this.authProcessService.afa.auth.signOut();
  }
```

**Comment by bojeil-google** [comment]
This is not coming from Firebase Auth. We don't make any network request on sign out.
