### ISSUE TITLE
Firebase Hosting - ¿Redirect?

### ISSUE THREAD

**Issue by robertoaikode** [firebase/firebase-js-sdk#1439]
Hello! I do not know if it's the right place to ask this question ...

How do I redirect the subdomain "proyect-name.firebaseapp.com" to "mydomain.com"?

I am currently viewing the same site in both domains. Is it possible to redirect?

Thank you!

**Comment by samtstern** [comment]
This is not an issue with the Firebase JS SDK so I am going to close, but I hope @mbleigh or @Memeriaj can comment here on how to do this!

**Comment by samtstern** [comment]
@robertoaikode I realize there's no perfect place to file Firebase Hosting issues, but I'd say the best place is probably https://github.com/firebase/firebase-tools since that's the repo for the Firebase CLI which controls hosting deploys and configuration.
