### ISSUE TITLE
FDL don't work on mobile web browser

### ISSUE THREAD

**Issue by therepo90** [firebase/firebase-js-sdk#1448]
When opening FDL from mobile browser ( or chrome mobile emulation) the dynamic link returns "intent://" instead of http so the browser can not open it.

**Comment by samtstern** [comment]
@therepo90 there's really not a lot of information here, some questions I have are:

  * How are you creating the link?
  * On what platform are you opening the link?  
  * How is the link received/displayed?

Also have you tried any of the steps here?
https://firebase.google.com/docs/dynamic-links/debug

**Comment by therepo90** [comment]
Im using REST
Im opening the link on web mobile device (also happens on chrome emulation mobile)
The link is doing 302 and then receiving response header location starting from `intent://` instead of `https://` so the browser can not navigate to this url

Arent these debug steps only for mobile apps?

**Comment by samtstern** [comment]
> Im using REST
So does this issue have anything to do with the Firebase JS SDK?

> Im opening the link on web mobile device (also happens on chrome emulation mobile)
What is "web mobile device"?  Is it an Android phone?  An iPhone?  Something else?  Also what is "chrome emulation mobile"?

Could you post the dynamic link here?

**Comment by therepo90** [comment]
For FDL there is only "REST" api if it comes to JS.
Its both android phone and iphone and chrome dev tools emulation
Sorry can't post dynamic link - NDA

**Comment by samtstern** [comment]
@therepo90 there's really not enough information here to help you.  I would need to see the dynamic link or at least a similar dynamic link.  I also need to understand what you're trying to achieve!  Clearly not every single dynamic link in all apps is broken on the web, so I need to see your particular setup to spot the difference.

Would you be more comfortable writing in to Firebase support?  They can handle your confidential links much better than I can on GitHub.
