### ISSUE TITLE
Typing for sendEmailVerification method should be updated to support parameters

### ISSUE THREAD

**Issue by dbaranovsky** [firebase/firebase-js-sdk#145]
Firebase SDK version: 4.3.0

Typing for sendEmailVerification method has 0 parameters([firebase.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/typings/firebase.d.ts)), though continueUrl feature was added in the recent version ([docs](https://firebase.google.com/docs/auth/web/passing-state-in-email-actions), [release notes](https://firebase.google.com/support/release-notes/js))

**Comment by jshcrowthe** [comment]
@dbaranovsky thanks for the report! This is something that we discovered and will be rolling out in our next release. #140 is part of the fix (we will regenerate our .d.ts from that externs file)
