### ISSUE TITLE
Update @firebase/database-types

### ISSUE THREAD

**Issue by dimitarnestorov** [firebase/firebase-js-sdk#1450]
### Describe your environment

  * Operating System version: macOS 10.14.2
  * Browser version: N/A
  * Firebase SDK version: N/A
  * Firebase Product: database

### Describe the problem
`ThenableRefrence` doesn't have `catch`, while `Reference` does.

https://github.com/firebase/firebase-js-sdk/blob/c6357fbaf99e80257816dafb28e748de4a039edf/packages/database-types/index.d.ts#L101

https://github.com/firebase/firebase-js-sdk/blob/c6357fbaf99e80257816dafb28e748de4a039edf/packages/database/src/api/Reference.ts#L316

Reason for issue: https://github.com/firebase/firebase-admin-node/issues/433

**Comment by mikelehen** [comment]
Just to be clear, per https://github.com/firebase/firebase-admin-node/issues/433 I think the proposal here is that we make ThenableReference extend Promise instead of PromiseLike.

**Comment by dimitarnestorov** [comment]
Out of curiosity, why does `@firebase/database-types` even exist? Why not just generate the definitions from `@firebase/database`?

**Comment by mikelehen** [comment]
@dimitarnestorov I think it's mostly so we can carefully control our public surface area.  There may be properties / methods on our implementation classes that are "public" for the sake of our own implementation details, but which aren't actually part of our supported API surface area for third-parties to use. So we use the d.ts files to clearly define (and document) our public APIs.  Additionally, any changes to our public surface area are carefully reviewed and subject to extra processes, etc. so having them live in a dedicated file is helpful separation.

**Comment by mikelehen** [comment]
I've created a PR which I think should address this. https://github.com/firebase/firebase-js-sdk/pull/1451
