### ISSUE TITLE
 @firebase/firestore: Firestore (5.5.9): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.

### ISSUE THREAD

**Issue by Gursewak-Uppal** [firebase/firebase-js-sdk#1457]
I have a react native app that uses Firebase/firestore. For uploading images, I am using "react-native-fetch-blob" to create a Blob.

I am trying to fetch doc from firestore, but my app is blocked and not getting any response from firestore (not catch / nothing => just passing thru the code).

Is there anything I can do for getting docs from firestore?

Below is my code 

import firebase from "../../../firebaseConfig";
import RNFetchBlob from "react-native-fetch-blob";

// Prepare Blob support
window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest;
const Blob = RNFetchBlob.polyfill.Blob;
const fs = RNFetchBlob.fs;
window.Blob = Blob;
const originalXMLHttpRequest = window.XMLHttpRequest;
const originalBlob = window.Blob;

var firebaseUid = "";

componentDidMount = async () => {
firebaseUid = await firebase.auth().currentUser.uid;
this.getMyStory();
};

 getMyStory = async () => {
  window.XMLHttpRequest = originalXMLHttpRequest;
  window.Blob = originalBlob;
  var docRef = await firebase
   .firestore()
   .collection("demo")
   .doc(firebaseUid)
   .collection("ArrayDoc");
  docRef
  .get()
  .then(querySnapshot => {
    querySnapshot.forEach(doc => {
      console.log(doc.id, " => ", doc.data());
    });
  })
  .catch(error => {
    console.log("error", JSON.stringify(error));
  });
};

![screenshot 2019-01-07 at 5 19 52 pm](https://user-images.githubusercontent.com/28809960/50811120-11899580-1333-11e9-9189-494b7f3a6f54.png)

**Comment by lopeski** [comment]
I have the same error.

**Comment by mikelehen** [comment]
I think there's a known incompatibility with react-native-fetch-blob. See https://github.com/wkh237/react-native-fetch-blob/issues/634 and the workaround suggested [here](https://github.com/wkh237/react-native-fetch-blob/issues/634#issuecomment-367794882).  I would comment on that issue (or maybe open a new one since that one is closed), as I think this is ultimately a problem with react-native-fetch-blob.

**Comment by Huzaifaak** [comment]
I am getting this error with 
` "firebase": "^5.7.3"`
![screenshot_20190128-193924](https://user-images.githubusercontent.com/9552894/51843510-fc51c680-2334-11e9-9409-892e51319e1f.jpg)

**Comment by Ovi** [comment]
This is what I did and it worked for me:

First store ` window.XMLHttpRequest` in a variable
`const tempWindowXMLHttpRequest = window.XMLHttpRequest;`

Now for RN Fetch Blob, use it's settings
`// Prepare Blob support`
`window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest;`
`const Blob = RNFetchBlob.polyfill.Blob;`
`const fs = RNFetchBlob.fs;`
`window.Blob = Blob;`
`const originalXMLHttpRequest = window.XMLHttpRequest;`
`const originalBlob = window.Blob;`

Then just before making your Firestore call - replace `window.XMLHttpRequest` with it's old state:
`window.XMLHttpRequest = tempWindowXMLHttpRequest;`

Hope this would help!

**Comment by ngaffa** [comment]
You should verify your proxy and/or firewall ports because firebase uses websockets.
I have the same error , it was working when i'm not in proxy and blocked when i am in proxy specially for Cloud Firestore.
