### ISSUE TITLE
FR: return promise in transaction

### ISSUE THREAD

**Issue by valterkraemer** [firebase/firebase-js-sdk#146]
* Operating System version: MacOS 10.12.6
  * Firebase SDK version: 4.1.3
  * Firebase Product: database

I would be great to be able to return a promise in a transaction. E.g. to be able to use a confirmation modal.

```javascript
return firebase.database().ref('col').transaction(function(currentData) {
  return new Promise(function(resolve, reject) {
    customModal.confirm('Overwrite?', function() {
      resolve(currentData);
    }, reject);
  });
});
```

**Comment by schmidt-sebastian** [comment]
This is something that we can look at, but you should keep in mind that we might run your transaction function multiple times (up to 25 times). This is needed to deal with conflicting writes on the server and likely doesn't work well with async transaction evaluation.

**Comment by valterkraemer** [comment]
Was this implemented or decided not to be done or..?

**Comment by faraazc** [comment]
any update on this . is this supported currently?

**Comment by mikelehen** [comment]
Not supported. Transactions are designed to run synchronously and should not have any side-effects (like displaying UI to the user) since they are run multiple times before being committed.
