### ISSUE TITLE
linkWithCredential does not automatically links accounts with same email address from different auth providers

### ISSUE THREAD

**Issue by pritamb1** [firebase/firebase-js-sdk#1463]
I am trying to setup a login page for my app and want to give the user the option of logging in with Email/Password, Facebook and Google. I am able to successfully login and logout with each of the method successfully. I want to link all the accounts from different Auth providers with same email address. I was going through firebase docs, and went through the linkwithcredential. Firebase tells to use linkwithcredential after signing in with any of the signin methods if I understand correctly. In my case if I logged in the user via facebbok first->user logs out->signs in with google->invoke linkwithcredential(my expectation is that facebook gets linked at this ). Is my understanding wrong?Else how do i sign in a user smoothly using different auth providers without requesting any action from user. Please `help
`    private void firebaseAuthWithGoogle(GoogleSignInAccount acct){

         final AuthCredential credential = GoogleAuthProvider.getCredential(acct.getIdToken(),null);

        firebaseAuth.signInWithCredential(credential).addOnCompleteListener(this,
                new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if(task.isSuccessful()){

                            linkCredential(credential);

                            Toast.makeText(MainActivity.this,"User Signed In",Toast.
                            LENGTH_SHORT).show();
                            startActivity(new Intent(MainActivity.this, ProfileActivity.class));
                            }
                            else {
                            Toast.makeText(MainActivity.this,"Authentication Failed",
                                    Toast.LENGTH_SHORT).show();
                        }
                    }
                });
    }`

`    public void linkCredential(AuthCredential credential){

        Log.d("shitttttt" + FirebaseAuth.getInstance().getCurrentUser(),credential.toString());

        FirebaseAuth.getInstance().getCurrentUser().linkWithCredential(credential)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            Log.d(TAG, "linkWithCredential:success");
//                            updateUI(user);
                        } else {
                            Log.w(TAG, "linkWithCredential:failure", task.getException());
                            Toast.makeText(MainActivity.this, "linkWithCredential:failure",
                                    Toast.LENGTH_SHORT).show();
//                            updateUI(null);
                        }

                        // [START_EXCLUDE]
//                        hideProgressDialog();
                        // [END_EXCLUDE]
                    }
                });

        //final AuthCredential fbCredential = FacebookAuthProvider.getCredential(acct.getIdToken());

        Log.d("fbcredential",credential.toString());
    }`

**Comment by bojeil-google** [comment]
This question is better suited for stackoverflow. It is not even JS related.
