### ISSUE TITLE
console.log() in trigger doesn't display anything in the console when using firebase serve.

### ISSUE THREAD

**Issue by cedvdb** [firebase/firebase-js-sdk#147]
* OS : Ubuntu 17.04
* Firebase --version : 3.9.2
* Firebase Product: functions

Description:

When using `console.log()` in a trigger function running on `localhost`, `console.log()` doesn't output anything to the console. All in all if this won't be supported I feel like the doc should be explicit about it.

Code:

```javascript

import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

admin.initializeApp(functions.config().firebase);
const db = admin.database();

export let test =  functions.https.onRequest((req, res) => {
	db.ref('/test').push(Math.random())
	.then(v => res.send('v'))
});

export let testTrig = functions
	.database
	.ref('/test/{id}')
	.onWrite(e => {
		console.log(`trigger: new test added with id ${(e.params as any).id}`)
	});

```

**Comment by jshcrowthe** [comment]
Hey @cedvdb! Thanks for the issue, this would probably be better reported at https://github.com/firebase/firebase-functions. This repo is for the actual JS SDK itself (the web/node.js client version) not the functions runtime.
