### ISSUE TITLE
FR: firestore doc.get() enhance error codes

### ISSUE THREAD

**Issue by mohshraim** [firebase/firebase-js-sdk#1472]
### [REQUIRED] Describe your environment

  * Operating System version: all
  * Browser version: _____
  * Firebase SDK version: 5.7
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

when using `doc.get()` tow errors may appear as following;
1- when doc not exist; error will be string  ==>     error: "No such document!"
2- when no connection; error will be object  ==>  error: {
code: "unavailable"
name: "FirebaseError"
toString: ƒ ()
message: "Failed to get document because the client is offline.
}

if applicable let both an objects!!

Thanks

**Comment by mohshraim** [comment]
@mikelehen 
If you can take look at this..
thanks

**Comment by mikelehen** [comment]
@mohshraim Can you explain how you're getting the "No such document!" error?  If you call doc.get() on a nonexistent document, it should succeed with a DocumentSnapshot that has its .exists property set to false.

**Comment by mohshraim** [comment]
@mikelehen 
please accept my apology...
my mistake

**Comment by mikelehen** [comment]
@mohshraim No worries! Glad to hear it's not an issue on our end. :-)
