### ISSUE TITLE
sendSignInLinkToEmail is not working in web

### ISSUE THREAD

**Issue by postalangel** [firebase/firebase-js-sdk#1475]
sendSignInLinkToEmail
not working at all as for today. tried both adding android and ios apps and also by activating dynamic links

"TypeError: __WEBPACK_IMPORTED_MODULE_8_firebase___default.a.auth(...).sendSignInLinkToEmail is not a function"

_Originally posted by @postalangel in https://github.com/firebase/firebase-js-sdk/issues/828#issuecomment-451730232_

**Comment by bojeil-google** [comment]
Hmm, I don't think we changed anything lately. What version are you using? Can you test with an older version? I speculate it is related to your webpack setup.
