### ISSUE TITLE
unable to write (with security rules) to Firestore with signInWithCustomToken

### ISSUE THREAD

**Issue by aconchillo** [firebase/firebase-js-sdk#1478]
### Describe your environment

  * Operating System version: OS X 10.14.1
  * Browser version: Electron 4.0.1
  * Firebase SDK version: 5.7.3
  * Firebase Product: Firestore

### Describe the problem

Unable to write to Firestore when client is signed in with custom token and security rules are in place.

Error message:

```
FirebaseError: [code=permission-denied]: Missing or insufficient permissions.
```

#### Steps to reproduce:

This is the rule I have:

```
allow write: if request.auth.uid != null;
```

If I change the rule to:

```
allow write: if true;
```

everything works fine.

So, I tried one more thing:

```
allow write: if request.auth != null;
```

This failed, which seems to indicate that the client is not authenticated. But it is, since  `auth.currentUser.uid` is valid and `signInWithCustomToken` worked properly on the client.

#### Relevant Code:

```javascript
const app = firebase.initializeApp({...});
const auth = app.auth();
const db = app.firestore();
const firestoreSettings = { timestampsInSnapshots: true };
db.settings(firestoreSettings);
...
const ref = db.doc('/path/to/doc').collection('a-collection').doc('some-doc');
await rosterRef.update({ fields... });
```

I have also tried to initialize with:

```javascript
firebase.initializeApp({...});
const auth = firebase.auth();
const db = firebase.firestore();
const firestoreSettings = { timestampsInSnapshots: true };
db.settings(firestoreSettings);
```

which is equivalent, but that didn't help either. Even I tried, to make sure Firestore was not using another app (I don't know which one..):

```javascript
firebase.initializeApp({...});
const db = firebase.firestore();
const firestoreSettings = { timestampsInSnapshots: true };
db.settings(firestoreSettings);
const auth = db.app.auth();
```

But the same. At this point I don't know what else to try. I enabled `setLogLevel('debug')` in Firestore, but didn't see anything relevant except that the path of the document I'm trying to update is correct, which is also verified by the fact that using the `if true` security rule, everything works fine.

**Comment by aconchillo** [comment]
One more thing. I have also used the simulator to try the rule with custom authentication filling the JWT and had no problem.

**Comment by aconchillo** [comment]
Oh, that's right. Missed to add that. It would be:

```
const app = firebase.initializeApp({...});
const auth = app.auth();
const db = app.firestore();
const firestoreSettings = { timestampsInSnapshots: true };
db.settings(firestoreSettings);
...
auth.signInWithCustom(token);
...
const ref = db.doc('/path/to/doc').collection('a-collection').doc('some-doc');
await rosterRef.update({ fields... });
```

I'll send you the logs in a bit. Thank you!

**Comment by bojeil-google** [comment]
It doesn't seem like you are waiting for `signInWithCustomToken` to resolve before accessing DB. It returns a promise that resolves on successful sign-in.

**Comment by mikelehen** [comment]
Yeah, you'll want to do:

```
await auth.signInWithCustomToken(token);
```

**Comment by aconchillo** [comment]
Pretty sure we are signed in, since I get an `onAuthStateChanged` call and actually writing after that happens. I don't have the await, but since the `onAuthStateChanged` callback was called I assume the `signInWithCustomToken` promise resolved, right?  Sorry about the code above, this was just a snippet I created for the bug.

**Comment by mikelehen** [comment]
Okay, yes. Waiting for onAuthStateChanged should also be sufficient.  And based on the log you sent me, you are signed in.

**Comment by Feiyang1** [comment]
I don't think the import syntax is pertinent to the issue. Do you have firebaseui-web as a dependency in your project? 
If that's the case, can you use the bundler to transform the require('firebase/app') to require('firebase/app').default as suggested in https://github.com/firebase/firebaseui-web/issues/392#issuecomment-389197920, so you can still use `import * as firebase from 'firebase/app'` to get autho-completion?

**Comment by aconchillo** [comment]
No, just `firebase` (ie `yarn add firebase`). I assume that's the firebase-js-sdk. Can the same trick be done there?

**Comment by Feiyang1** [comment]
Yep, you should be good with `import * as firebase from 'firebase/app'`.

**Comment by aconchillo** [comment]
OK, I can't reproduce with a simple test case.

There are a few differences:

- Script ran directly with `node firebase-write-test.js`, instead of inside Electron.
- The way we import is different.

```
const firebase = require('firebase');
```

instead of 
```
const firebase = require('firebase/app').default;

import 'firebase/auth';
import 'firebase/firestore';
```
- JavaScript instead of TypeScript.
- No transpiling being done. No webpack.

I'll keep investigating.

**Comment by mikelehen** [comment]
Please let us know if you figure out how to isolate the issue. Thanks!

**Comment by aconchillo** [comment]
Sorry about that. I was side tracked with other things. I will have time next week to investigate.

**Comment by aconchillo** [comment]
Yes, I deleted the message when I realized I replied to a bot (I thought I was replying to @mikelehen). In any case, content of the message is still valid :-D

**Comment by aconchillo** [comment]
Just did my first test starting from scratch with Electron 4.0.3 and Firebase 5.8.1 and didn't find any issues. The code is like this:

```
const { app, BrowserWindow } = require('electron')

const firebase = require('firebase');

const firebaseConfig = { ... };

const firebaseToken = '...';

const fbApp = firebase.initializeApp(firebaseConfig);
const auth = fbApp.auth();
const db = fbApp.firestore();
const firestoreSettings = { timestampsInSnapshots: true };
db.settings(firestoreSettings);

const refFor = (meetingID) => {
  return `meetings/${meetingID}`;
};

const updateMyRoster = (meetingID, fields) => {
  return new Promise(async (resolve, reject) => {
    try {
      if (!auth.currentUser) {
        throw new Error('Unable to update user roster, not logged in?');
      }

      const userID = auth.currentUser.uid;
      const rosterRef = db.doc(refFor(meetingID)).collection('roster').doc(userID);
      await rosterRef.update(fields);
      resolve();
    } catch (error) {
      reject(error);
    }
  });
}

const firebaseTest = async () => {
  try {
    await auth.signInWithCustomToken(firebaseToken);
    console.log('all good, trying to write...');
    await updateMyRoster('1234567890', { 'key5': 'value5' });
    await auth.signOut();
  } catch (error) {
    console.error('Something went wrong:', error);
  }
};

app.on('ready', firebaseTest);
```

**Comment by samtstern** [comment]
@aconchillo so there is no issue at all with your latest code?  In that case, how do you want to proceed?

**Comment by aconchillo** [comment]
yes, there's no issue starting from scratch, so this seems like an issue in our environment. it seems to me we can close this issue and i can reopen a new one in case i find something. in any case, once i find the issue i will add a comment here so everyone is aware of what was the problem.

**Comment by samtstern** [comment]
@aconchillo sounds good to me, thanks for following up!  If you do run into this issue again we're happy to resume debugging.

**Comment by aconchillo** [comment]
An interesting update. Yesterday, when I started building the Electron app from scratch I had to `rebuild` the modules with native extensions. This is needed for the grpc node module to work inside Electron. That was fine and it worked.

Then, I just realized that I didn't remember having to rebuild anything in our app. So, next step was to start adding things little by little to my simple example. The first thing was to add webpack support. After that, and without modifying any code, the first problem I found was this:

```
TypeError: o.initializeApp is not a function
```

So I switched to (which is what we do in our Electron app):

```javascript
const firebase = require('firebase/app').default;
require('firebase/auth');
require('firebase/firestore');
```

Next error was:

```
Error: The XMLHttpRequest compatibility library was not found.
```

That's when I realized our app is probably not using gRPC! And that's why we don't do the rebuild step.

The fix for this was to simply install the `xmlhttprequest` module and add this before importing firebase:

```javascript
global.XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
```

which we also have in our app.

After doing this change, I got the permission denied error:

```
 FirebaseError: Missing or insufficient permissions.
```

So, it all makes sense now. I'll post a new update once we fix this issue so other people with the same problem (if any) can find it.

**Comment by aconchillo** [comment]
I ended up changing our build system to not use webpack for the main process. That solved the permission denied problem as Firebase now uses gRPC plus it doesn't require all the weird import stuff I mentioned above.

**Comment by samtstern** [comment]
@aconchillo thanks for those details!  There's a big difference between the Firebase **Web Client SDK** and the Firebase **Node Admin SDK**.

The Web SDK does not use gRPC at all, it uses a technology called WebChannel.  It also authenticates using end-user credentials so it's subject to Security Rules.

The Admin SDK uses gRPC.  It authenticates using service account credentials so it does not interact with Security Rules.

Since electron is sort of halfway between a Node.js and Web JS environment (from what I understand) it may be possible that you got the SDKs mixed up!

If you're distributing this app to end users you should only be using the Web SDK, which means no gRPC.

**Comment by aconchillo** [comment]
For our backend we just use `npm install firebase-admin` but for the frontend (Electron) we use `npm install firebase`. Does that mean the `firebase` module also includes the `admin` module?

We don't have any service account credentials specified in our Electron app, we just `signInWithCustomToken` and security rules seem to work properly.

I get this error if I set a write rule to `allow write: if false`:

```
1/31/2019 11:07:20 AM [INFO]: Unable to update my roster ID:,FirebaseError: [code=permission-denied]: 7 PERMISSION_DENIED: Missing or insufficient permissions.
```

And it properly works if I set it to something like `allow write: if request.auth.uid == ${userId}`.

It seems gRPC is also used in the `firebase` module (not the admin one) if gRPC can be used and works as expected.

What am I missing?

**Comment by samtstern** [comment]
@mikelehen has informed me that I am wrong :-)

When you use the Web Client SDK in a Node Client app, then we *do* use gRPC transport.  Webchannel is browser only.

We're actually having some internal discussion right now about where Electron falls on the spectrum so we can get back to you with a 100% correct answer.  Sorry to be misleading before!

**Comment by aconchillo** [comment]
The way it works now makes sense to me and I'd rather use gRPC when possible, so don't touch anything :-).

Thanks!

**Comment by mikelehen** [comment]
@aconchillo Thanks for all the info.  It's very helpful.  It should help future users out, and perhaps we can cobble together some electron recommendations based on it.

**Comment by aconchillo** [comment]
np, happy to help!
