### ISSUE TITLE
auth: onAuthStateChanged should differentiate between unauthenticated and indeterminate state

### ISSUE THREAD

**Issue by nkwood** [firebase/firebase-js-sdk#148]
### Describe your environment

  * Operating System version: N/A
  * Firebase SDK version: 4.3.0
  * Firebase Product: auth

### Describe the problem

Firebase JS SDK provides the [onAuthStateChanged() method](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged) to register a call back on a changed AuthState and [currentUser property](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#currentUser) to return the currentUser or null if unauthenticated. As the docs state, ["currentUser might also be null because the auth object has not finished initializing. If you use an observer to keep track of the user's sign-in status, you don't need to handle this case"](https://firebase.google.com/docs/auth/web/manage-users). The docs also state "[b]y using an observer, you ensure that the Auth object isn't in an intermediate state—such as initialization—when you get the current user."

The AnuglarFire2 library uses onAuthStateChanged to create an observable (authState), which emits a null when unauthenticated and the user when authenticated. See : https://github.com/angular/angularfire2/blob/8767f73193f1f5604d82bd057c465a41e4d96faa/src/auth/auth.ts#L37-L51 As best I can tell it appears that when the Firebase JS SDK initializes onAuthStateChanged fires the callback with a null user (unauthenticated), then upon initialization will fire the callback with the user info. If there is in fact not an authenticated user after initialization no other event is fired as it has already fired the callback with a null user. 

This *could* be an issue with AngularFire2 (@davideast ?), but based on the code above I believe it is an issue with the Firebase JS SDK. I can't seem to locate the implementation of onAuthStateChanged so I'm not entirely sure.

The problem is there is no way, absent waiting for some unknown and arbitrary length of time for the SDK to initialize, for an application to determine if the firing of the callback with the null user is because there is no authenticated user (and thus a login/auth flow needs to be initiated), or because the SDK has not initialized yet (in which case the login/auth flow does not need to be initiated).

To solve this either onAuthStateChanged should not fire until after the library has initialized (which seems to be the intended behavior based on reading the docs) or initially fire with a status (or error) that allows the application to determine whether or not the SDK has initialized and the null user really means no user is authenticated or if it means the SDK is still initializing.

#### Steps to reproduce:
1. Subscribe to the authState observable in AngularFire2 or pass a callback to onAuthStateChanged prior to Firebase JS SDK initializing.

2. Observe onAuthStateChanged fire the callback with null user prior to initialization. 

3. Observe onAuthStateChanged fire the callback with user info if state is authenticated post initialization, or do nothing if the user is not authenticated post initialization.

#### Relevant Code:

I went searching for the implementation of onAuthStateChanged, but it doesn't appear the source is located in the github repo, just https://github.com/firebase/firebase-js-sdk/blob/c58719c13862e59e91145d9566bc323bee2eaa9d/externs/firebase-auth-externs.js#L951-L952 and https://github.com/firebase/firebase-js-sdk/blob/c58719c13862e59e91145d9566bc323bee2eaa9d/src/auth.build.js
Is the source to the auth module not available?

**Comment by bojeil-google** [comment]
I didn't have time to read all of the above, but this is incorrect:
"As best I can tell it appears that when the Firebase JS SDK initializes onAuthStateChanged fires the callback with a null user (unauthenticated), then upon initialization will fire the callback with the user info. "
`onAuthStateChanged`will only trigger when the user initial state is determined. It will never trigger successively on initialization. I don't know what Angularfire does under the hood but this is the expected behavior.

**Comment by nkwood** [comment]
I just tested some other scenarios and I think I was wrong that the onAuthStateChanged is firing before the initial state is determined. It looks like I may have jumped the gun and it does appear to behave as you and the docs describe. I'm going to close the issue for now and investigate further.

**Comment by bojeil-google** [comment]
Thanks @nkwood for confirming the expected behavior. Let us know if you discover anything that contradicts this and we will fix it.
