### ISSUE TITLE
Authentication in a web worker or service worker breaks if window object is not undefined

### ISSUE THREAD

**Issue by guycreate** [firebase/firebase-js-sdk#1486]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.2
  * Browser version: Chrome 71.0.3578.98 
  * Firebase SDK version: 5.8.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Using auth in a `web worker` or `service worker` requires the global `window` object to be `undefined`.   The current SDK (as of 5.8.0) uses the absence of `window` and the presence of `importScripts` to infer that the current environment is a `worker`, and in such cases as long as `IndexedDB` is available, then Firebase allows local persistence of auth.

https://github.com/firebase/firebase-js-sdk/blob/512847e9322e1152078cd7248818738f0f362e89/packages/auth/src/utils.js#L643

The `isWorker` is not a reliable test in those environments where we've already set `window` to be the same as `self` to allow third party packages to run okay in the browser environment.   While we agree that window should be undefined, it is much harder to fix all the potential third party packages out there that assume it is the global object.  Babel runtime (for in browser transpilation) is an example of a package that requires `window` to be set to the global object.  Suggest we amend utils.js `isWorker` and/or `isWebStorageSupported ` to only rely the presence of `importScripts` as if that is available and IndexedDb is available, then `LOCAL` persistence of auth should work.

If `window` is undefined (as per the spec for workers), then firebase auth will use `IndexedDb` to sync sign in status successfully between the host page and the `web worker`.

### Why this is important

* Articles such as [I dropped 95% of my Firebase bundle size using this one weird trick](https://davidea.st/articles/firebase-bundle-size) demonstrate that using Firebase Realtime database Firestore, Storage etc in a web worker gives user responsiveness benefits.   
* These firebase services require a signed in user for common security rules.  Firebase sign in using non email and password services such as Google and Github OAuth require the OAuth flow to be initialzied from the host web page (or frame), and so sign in cannot be done exclusively in the webworker.   
* The easiest way to pass the sign in credentials from the host page to the worker, without relying on a backend cloud function and custom auth tokens, is to simply have the SDK persist it without any extra code;  however behind the scenes it used the IndexedDB to persist the credentials between host and worker, and it only checks that IndexedDB is available in the modern browser if the `window` object is undefined.
* This seems to be the recommended approach to sign in per the current docs for service workers at https://firebase.google.com/docs/auth/web/service-worker-sessions

#### Steps to reproduce:

Initialize firebase in a web worker, and call  `auth.onAuthStateChanged` to be notified when the user is signed in.  Sign in (or remain signed in) on the host page.  auth.onAuthStateChanged is now called correctly with a valid user.     Now call any realtime db, firestore or storage service successfully and authentication credentials will be automatically added by the sdk.

Now to reproduce the error, set the global window object to anything that is not null.    (example code in next section below.).   Sign in on the host page successfully.

This time auth.onAuthStateChanged in the worker is still called but always with a null user, and so all firestore, storage etc. calls will be done with a request.auth that is null and will fail most common security rules for reads and writes that assume an authenticated user.

#### Relevant Code:
```javascript

    // main.worker.js
    // CODE THAT BREAKS FIREBASE ON NEXT LINE; COMMENT OUT TO MAKE THIS CODE WORK
    ; self.window = self;

    const app = firebase.initializeApp(firebaseConfig)
    const auth = firebase.auth()

   auth.onAuthStateChanged(
      async (user) => {
        console.log("WORKER DB", user)    // will be null if window is not null
      }
     )
```

#### Suggested fixes
Use a different method to detect if webstorage is available that does not rely on the absence of the `window` object.

#### Workaround  (tested successfully on firebase SDK 5.8.0)

```javascript
    // main.worker.js

    //HACK TO RESET WINDOW BEFORE CALLING FIREBASE SDK
    ; self.window = null

    const app = firebase.initializeApp(firebaseConfig)
    const auth = firebase.auth()

    //OK TO SET WINDOW BACK TO GLOBAL AFTER FIREBASE IS INIATIALIZED
    ;self.window = self
```

I have not tested if this hack workaround survives token refreshes or how often the SDK tests for the presence of the `window` object.

**Comment by ChrisChiasson** [comment]
@bojeil-google I don't think @guycreate was suggesting to set `self` as `window` as the fix. From above:

> Suggest we amend utils.js `isWorker` and/or `isWebStorageSupported` to only rely the presence of `importScripts` as if that is available and IndexedDb is available, then `LOCAL` persistence of auth should work

**Comment by bojeil-google** [comment]
Forgot to update this bug but this was already fixed: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/utils.js#L642
