### ISSUE TITLE
Terminating node process when using firebase within mocha tests 

### ISSUE THREAD

**Issue by klausbayrhammer** [firebase/firebase-js-sdk#1487]
### [REQUIRED] Describe your environment
  * Operating System version: MacOS 10.13.6
  * Browser version: nodejs v8.11.2
  * Firebase SDK version: firebase@^5.8.0:
  * Firebase Product: datbase

#### Steps to reproduce:
I tried to connect to a firebase database within a mocha test, but even though I deleted the app afterwards (or even within the test) the node process is not terminating. No combination of `app().delete()` or `database().goOffline()` did work in this case.
The result is that the test runner is not able to terminate the process which means it can not be really be used within a CI environment.

It may be related to #859 but since that issue was related to auth it's possibly a different problem.

#### Relevant Code:

sut.js
```javascript
const firebase = require('firebase/app');
require('firebase/database');

firebase.initializeApp({/* config */});
firebase.database();

module.exports = () => {
    firebase.app().delete();
};
```

sut.spec.js
```javascript
const deleteFirebaseApp = require('./sut');
describe('firebase database within mocha tests', function () {
    it('should be able to terminate node process after deleting the firebase app', () => {
        deleteFirebaseApp();
    })
});
```

Run `eslint sut.spec.js` afterwards to invoke the tests. Also see https://github.com/klausbayrhammer/firebase-mocha-pending-connection to reproduce the problem

**Comment by Feiyang1** [comment]
Thanks for providing the repro! What works for me is moving the initialization logic to beforeEach function. I don't exactly know how mocha works internally, but my guess is you need to provide the initialization code in the mocha context, and it does some cleanup for you.
Anyway I think the best practice for unit tests is using beforeEach for initialization. Hope it helps.

**Comment by klausbayrhammer** [comment]
@Feiyang1 Thanks for looking into it and for providing a solid workaround - I really appreciate that.

A somewhat related issue, in case somebody stumbles upon this: If you use `firebase.auth()` you need to `auth().signOut()` so the node process can be terminated. So summarising @Feiyang1's solution - that's what worked for me

```javascript
describe('', () => {
    let firebaseApp;

    before(async () => {
        firebaseApp = await firebase.initializeApp(config);
        return firebaseApp.auth().signInWithEmailAndPassword(mail, password);
    });

    after(() => {
        firebaseApp.auth().signOut();
        firebaseApp.delete();
    });

    it('....', async () => {
    });
});
```

@Feiyang1 would it make sense to perform things like signing out when you delete an app?

**Comment by Feiyang1** [comment]
I'm glad it worked out for you. Can you please open a new issue regarding the signOut, so we can track it properly?
