### ISSUE TITLE
@firebase/testing: making a query results in "TypeError: pr.then is not a function"

### ISSUE THREAD

**Issue by RohanTalip** [firebase/firebase-js-sdk#1488]
### Describe your environment

  * Operating System version: Ubuntu Bionic
  * Browser version: n/a
  * Firebase SDK version: 6.3.0 (as reported by `firebase --version`)
  * Firebase Product: Firestore

### Describe the problem

I'm using [@firebase/testing](https://github.com/firebase/firebase-js-sdk/tree/master/packages/testing) 0.6.0 with the [Firestore emulator](https://firebase.google.com/docs/firestore/security/test-rules-emulator#install_the_emulator).

My tests for .get() and .set() operations are working as expected, however my tests for queries are not.

I get a "TypeError: pr.then is not a function" error, which appears to be coming from https://github.com/firebase/firebase-js-sdk/blob/master/packages/testing/src/api/index.ts#L258

Am I doing something wrong or is this a bug with @firebase/testing ?

#### Steps to reproduce:

I based my tests on the [Quickstart JavaScript example for using the Firestore emulator](https://github.com/firebase/quickstart-nodejs/blob/master/firestore-emulator/javascript-quickstart/test/test.js).

Relevant test code:
```
describe("User", () => {
  describe("list", () => {
    beforeEach(async () => {
      console.log("User list beforeEach() : testNumber =", testNumber);
      const db = authedApp({ uid: "alice" });
      const user = db.collection("User").doc("alice");
      await firebase.assertSucceeds(user.set({id: "alice", displayName: "Alice"}));
    });

    afterEach(async () => {
      console.log("User list afterEach() : testNumber =", testNumber);
    });

    it("should let a user query their own User document", async () => {
      const db = authedApp({ uid: "alice" });
      const userCollection = db.collection("User");
      await firebase.assertSucceeds(userCollection.where("id", "==", "alice").onSnapshot(snapshot => {
        console.log("success - own");
      }, error => {
        console.error("error - own");
      }));
    });

    it("should not allow a user to query any other User document", async () => {
      const db = authedApp({ uid: "bob" });
      const userCollection = db.collection("User");
      await firebase.assertFails(userCollection.where("id", "==", "alice").onSnapshot(snapshot => {
        console.error("success - other user");
      }, error => {
        console.error("error - other user");
      }));
    });
```

Relevant rules:
```
service cloud.firestore {
  match /databases/{database}/documents {
  // ...

    match /User/{userId} {
      allow create, update: if request.auth != null && request.auth.uid == userId && incomingData().id == userId;

// real read rule:
//      allow read: if request.auth != null && request.auth.uid == resource.data.id;

// read rule for showing possible issue with test harness:
      allow read: if true;
    }
```

Output from `yarn test --grep list` :
```
yarn run v1.13.0
$ FIREBASE_FIRESTORE_EMULATOR_ADDRESS='127.0.0.1:8080' mocha --grep list


(node:14255) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
  User
    list
Top-level beforeEach() : testNumber = 1
User list beforeEach() : testNumber = 1
      ✓ should let a user query their own User document
User list afterEach() : testNumber = 1
Top-level beforeEach() : testNumber = 2
success - own
User list beforeEach() : testNumber = 2
      1) should not allow a user to query any other User document
User list afterEach() : testNumber = 2

success - other user

  1 passing (446ms)
  1 failing

  1) User
       list
         should not allow a user to query any other User document:
     TypeError: pr.then is not a function
      at Object.assertFails (node_modules/@firebase/testing/dist/index.cjs.js:166:15)
      at Context.it (test/test.js:189:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)



error Command failed with exit code 1.

```

**Comment by mikelehen** [comment]
onSnapshot() doesn't return a Promise and so you can't call await on it.  What exactly are you trying to test?  Can you just use .get() since it returns a Promise?

**Comment by RohanTalip** [comment]
I simplified this myself by defining a helper function:
```
function onSnapshotPromise(query) {
  const pr = new Promise((resolve, reject) => {
    query.onSnapshot(
      snapshot => {
        resolve();
      },
      error => {
        reject();
      }
    );
  });
  return pr;
}
```

... then calling something like:
```
        await firebase.assertSucceeds(onSnapshotPromise(userCollection.where("id", "==", "alice")));
```
... or:
```
        await firebase.assertFails(onSnapshotPromise(userCollection.where("id", "==", "alice")));
```

**Comment by mikelehen** [comment]
Just FYI- what that code does is essentially re-implement `get()`, except you aren't unsubscribing, so you're going to have an onSnapshot subscriber hanging around (and potentially calling your resolve() function repeatedly).

`get()` and `onSnapshot()` are basically treated the same by security rules.  The only difference is that `onSnapshot()` creates a long-standing listener and so it might initially pass security rules (so you'll get 1+ snapshots back) and then later be rejected if some data changes such that your subscription is no longer allowed by rules.  But based on your wrapper, it looks like you're not testing that piece, so you really might as well just use `get()` if you want to.

Note that you create a query by using filters, like `collection.where("id", "==", "alice")` and then you can use either `get()` or `onSnapshot()` to get results form the query.  So it's not the fact that you're using `onSnapshot()` that makes it a query.

I'm going to close this, since it sounds like there isn't an issue on our side, but feel free to follow up if you have more questions.

**Comment by RohanTalip** [comment]
@mikelehen, thanks for the clarification!

**Comment by ZenModeRy** [comment]
I learned something new as well! Thanks @mikelehen :)
