### ISSUE TITLE
How to backup firestore data daily

### ISSUE THREAD

**Issue by lkhgvsuren** [firebase/firebase-js-sdk#1489]
I can run "gcloud beta firestore export gs://[BUCKET_NAME]" to export firestore data to google storage. But I need to run this command daily. And is there any way to automate it?

**Comment by rockwotj** [comment]
Check out the following docs/repos for scheduling something via cloud functions - then you can schedule running the gcloud command.

https://cloud.google.com/scheduler/docs/tut-pub-sub
https://github.com/FirebaseExtended/functions-cron
