### ISSUE TITLE
cant install firebase with npm

### ISSUE THREAD

**Issue by GavMan1995** [firebase/firebase-js-sdk#149]
I get an unexpected end of file error when trying to install firebase with npm, here are the logs that I get : 
----

0 info it worked if it ends with ok
1 verbose cli [ '/Users/gavyn/.nvm/versions/node/v8.1.2/bin/node',
1 verbose cli   '/Users/gavyn/.nvm/versions/node/v8.1.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'firebase' ]
2 info using npm@5.3.0
3 info using node@v8.1.2
4 verbose npm-session f7e8369d52a9e5f8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/firebase 750ms (from cache)
8 http fetch GET 200 https://registry.npmjs.org/firebase/-/firebase-4.3.0.tgz 13ms (from cache)
9 silly fetchPackageMetaData error for firebase@latest unexpected end of file
10 verbose stack Error: unexpected end of file
10 verbose stack     at Gunzip.zlibOnError (zlib.js:152:15)
11 verbose cwd /Users/gavyn/Programming/personal/style-club
12 verbose Darwin 16.6.0
13 verbose argv "/Users/gavyn/.nvm/versions/node/v8.1.2/bin/node" "/Users/gavyn/.nvm/versions/node/v8.1.2/bin/npm" "install" "--save" "firebase"
14 verbose node v8.1.2
15 verbose npm  v5.3.0
16 error code Z_BUF_ERROR
17 error errno -5
18 error unexpected end of file
19 verbose exit [ -5, true ]
----

What can I do to fix this?

**Comment by jshcrowthe** [comment]
@GavMan1995 I was unable to reproduce this issue. It may have been an intermittent npm service outage or something else. Can you please try again?
