### ISSUE TITLE
Firebase phone auth javascript recaptcha error

### ISSUE THREAD

**Issue by cjorge** [firebase/firebase-js-sdk#1495]
Every time the recaptcha is solved on Phone Auth there is a error:

recaptcha__en.js:179 Uncaught TypeError: Cannot read property 'style' of null
at N (recaptcha__en.js:179)
at nF.<anonymous> (recaptcha__en.js:480)

This will then mess up the prompt dialog asking for the code.

I had to go back to version 4.5.0 to have this not happening (which sounds strange to me). Is this issue known?

**Comment by bojeil-google** [comment]
This looks like it is coming from the reCAPTCHA SDK. Please provide the minimal code to recreate this.

**Comment by cjorge** [comment]
After initializing firebase this is the basic code that will through the error...

<div id="recaptcha-container"></div>
<script>
    var phoneNumber = "+351999999999";
    var appVerifier = new firebase.auth.RecaptchaVerifier('recaptcha-container');

    firebase.auth().signInWithPhoneNumber(phoneNumber, appVerifier)
        .then(function (confirmationResult) {

            console.log(confirmationResult)
            
            return confirmationResult.confirm(testVerificationCode)
        }).catch(function (error) {
            console.log("error")
            
    });
</script>

**Comment by cjorge** [comment]
I rechecked it again. It only happens when the recaptcha shows you pictures to validate. When the recaptcha immediately validates you it works

**Comment by bojeil-google** [comment]
I tested again with reCAPTCHA showing a challenge involving pictures. It still works as expected. My previous analysis and recommendation still holds. This is not related to Auth SDK.

**Comment by vladimirdjurdjevic** [comment]
I get this error every time image verification ends. Images get displayed, i solve a challange, and then this gets printed in console: 

zone-evergreen.js:172 Uncaught TypeError: Cannot read property 'style' of null
    at J (recaptcha__sr.js:186)
    at eF.<anonymous> (recaptcha__sr.js:508)
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Zone.runTask (zone-evergreen.js:168)
    at invokeTask (zone-evergreen.js:481)
    at ZoneTask.invoke (zone-evergreen.js:470)
    at timer (zone-evergreen.js:2535)

Angular 9.next10 + AngularFirebase
