### ISSUE TITLE
Call to getRedirectResult after authenticating is very slow

### ISSUE THREAD

**Issue by mikehans9** [firebase/firebase-js-sdk#1499]
I want to use firebase auth using the redirect mechanism, problem is after successfully authenticating I have to wait for getRedirectResult() to be called. Problem is it is extremely slow and no amount loading indicators can fix this terrible UX. I have posted a demo of the experience below. Is there anything I can do to speed things up?

https://giphy.com/gifs/3JZdd8xDbfkB3RJlJ0

**Comment by puf** [comment]
Also posted on: https://stackoverflow.com/questions/54385124/call-to-getredirectresult-after-authenticating-is-very-slow

**Comment by bojeil-google** [comment]
This is highly dependent on network connection. The expectation is that you display a progress bar on return. Your app displays none.

**Comment by mikehans9** [comment]
@bojeil-google You jumbled two points in there that aren't correlated.  A progress bar won't speed up the network connection. And the network connection is definitely an issue as I have switched libraries to gapi and have no issues at all, I use implicit flow and the the id token from the URI and pass it to firebase auth. I would have liked to stick with firebase auth for the social login but it is too slow. How can gapi be 5-6x faster than firebase auth if I have a network connection issue? I am based in brisbane, australia.

**Comment by bojeil-google** [comment]
You can always choose or switch to gapi to sign in with Google.
As I already mentioned, the performance is dependent on network connection.
Obviously there will always be a delay as there is a lot of work under the hood to get this to work, hence the need to add a progress bar.

**Comment by mikehans9** [comment]
@bojeil-google thanks for the information. appreciate all the work that went into this, but honestly this library is not ready for primetime apps.

**Comment by abhinayar** [comment]
Yeah this is trash. What a dumpster fire.
