### ISSUE TITLE
Firestore in Node env: Failed to get document because the client is offline

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#1500]
I have some Firestore tests I'm running in a node environment. They make a connection to Firestore, then keep the connection open long enough to complete all tests.

It always worked without problem, but today I'm getting this error:
```js
Rejected promise returned by test. Reason:

  FirebaseError (Error) {
    code: 'unavailable',
    toString: Function {},
    message: 'Failed to get document because the client is offline.',
  }

  new FirestoreError (node_modules/@firebase/firestore/dist/index.node.cjs.js:348:28)
  Object.next (node_modules/@firebase/firestore/dist/index.node.cjs.js:19989:28)
  next (node_modules/@firebase/firestore/dist/index.node.cjs.js:19942:30)
  Timeout._onTimeout (node_modules/@firebase/firestore/dist/index.node.cjs.js:18362:21)
```
I didn't change anything.
I try running each test file individually and they don't give me the error anymore.
So now the error seems to be gone.

Any idea what could cause this? Firebase Firestore status seems to be online so...

### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.2
  * Browser version: Node v10.10.0
  * Firebase SDK version: firebase ^5.8.0
  * Firebase Product: firestore

### Reproduction

I cannot

**Comment by mikelehen** [comment]
Sounds like a temporary network hiccup or similar.  If you can't reproduce, I don't think there's anything to investigate but if you have more troubles, let us know. Thanks!

**Comment by zerobytes** [comment]
i have the same issue. 
In my case, perfect internet, even testing in 2 different providers,
and mostly 90% of the times i'm using firestore i get this message. Doesnt matter if im at mobile or browser, code is very simple, getting a collection directly.

**Comment by wilhuff** [comment]
@zerobytes Unfortunately, this first issue didn't include enough for us to go on and this additional comment doesn't help us narrow down your issue.

Could you file a new issue, with all the requested information, including a description of your environment? Also, if you [enable debug logging](https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel) that will include some clues about what's going on.

As it stands we can't help with this issue.
