### ISSUE TITLE
I am a new developer and got the issue while using firebase in vue.js. Can anyone resolve this issue for me?

### ISSUE THREAD

**Issue by sagarbhatia786** [firebase/firebase-js-sdk#1506]
@firebase/firestore: Firestore (5.8.1): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.

**Comment by Feiyang1** [comment]
It's just a heads up we are giving to developers to prepare for future changes. 
Are you manually setting timestampsInSnapshots ? You don't have to do anything now, but if you are setting it manually, we suggest you to not do it if it's possible.
