### ISSUE TITLE
Password Reset Via E-Mail Link Disconnects Social Providers

### ISSUE THREAD

**Issue by washowasho** [firebase/firebase-js-sdk#151]
### [REQUIRED] Describe your environment

  * Operating System version: **JavaScript**
  * Firebase SDK version: **4.3.0**
  * Firebase Product: **Auth**

### [REQUIRED] Describe the problem

If a user first connects social media accounts (e.g., Facebook, Twitter) and then a password is reset using the "send password reset email", the connections to social media are wiped out and must be linked again. Should that be? I don't think an update of a password should remove those connections.

**Comment by bojeil-google** [comment]
This is a security mechanism. It works as intended. If a user's account is taken over and the password changed or another account is linked, original provider is unlinked, or even the email is changed. Firebase Auth will send an email change revocation, but that will not be sufficient. Password reset will allow the user to take back control of the account. In the process, all existing providers will be unlinked.

**Comment by washowasho** [comment]
Thanks @bojeil-google . That makes perfect sense.

**Comment by bojeil-google** [comment]
You're welcome. It comes with some downsides, as you noticed. A user may have just forgotten their password, but it the account is hijacked, the auto unlinking is vital.
