### ISSUE TITLE
Auth state changes after creating new user with email and password

### ISSUE THREAD

**Issue by CristalT** [firebase/firebase-js-sdk#1513]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04
  * Browser version: Chrome 73
  * Firebase SDK version: 5.8.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Auth state changes when a new user is created with email and password.
I implement `firebase.auth().onAuthStateChanged()` observable to watch login state in my app. But it have tool for creating new users that reproduces de issue. After creating new user with`firebase.auth().createUserWithEmailAndPassword()` the observable returns the new user, wich causes my app log out.

#### Relevant Code:

https://stackblitz.com/edit/firebase-issue-sandbox-wym8wf?file=index.js

**Comment by bojeil-google** [comment]
Hey @CristalT, I don't understand what the issue is here. I checked your sample. A user is created and then the `onAuthStateChanged` listener is triggered with the expected user. What exactly is the problem?

**Comment by CristalT** [comment]
Hi @bojeil-google, thanks for your answer. 
I solved the problem making a Cloud Function that creates new user at server side. Anyway, think about this: you log into your app as administrator, then you can create a new user, but when you do it, its state changes making your current session closes. I managed to explain my point?
It's ok for me if this behavior is normal, maybe I'm wrong, but I can't find it into documentation, for that reason I take it as an issue.

**Comment by bojeil-google** [comment]
I still don't understand the issue. Are you trying to have an admin create a user via client SDK and end up having the admin user signed out because the created user replaces the admin user? If so, this is also expected. If you are creating an admin app for provisioning users, you should look into using the Firebase Admin SDK.

**Comment by FrancoAra** [comment]
I am having a similar issue, the problem is that I want to create a user but not to trigger the listener. I think the API should have a configuration to disable such functionality. Specifically, I need to do other operations after successful creation but before logging in the user.

**Comment by CristalT** [comment]
@FrancoAra you must create a Cloud Function that makes the user creation. That's the way I solved my problem. Please, take a look at: https://firebase.google.com/docs/auth/admin/manage-users

**Comment by bojeil-google** [comment]
This keeps coming up. The client SDK is not used for administrative operations like creating users. The [Firebase Admin SDK](https://firebase.google.com/docs/auth/admin/manage-users) is the right tool for that. `createUserWithEmailAndPassword` is equivalent to a sign-in operation and is expected to trigger the auth listeners.
