### ISSUE TITLE
Internal error opening indexedDB in Chrome Extension

### ISSUE THREAD

**Issue by holmberd** [firebase/firebase-js-sdk#1517]
* Firebase SDK version: 5.8.1
  * Firebase Product: database

I'm have a Chrome Extension that is using firestore as database with offline persistence enabled. Firestore is initialised in a non persistent background script of the extension.

Lately I've been seeing a couple of errors show up daily from a number of users in my error tracker:

`@firebase/firestore: Firestore (5.8.1): INTERNAL UNHANDLED ERROR:  Internal error opening backing store for indexedDB.open.`

`@firebase/firestore: Firestore (5.8.1): INTERNAL UNHANDLED ERROR:  Encountered disk full while committing transaction.`

The first error I believe might be related to when Chrome updates the extension, but I've failed to reproduce this. The second error seems unlikely to affect so many users so I'm at a lost to why this is thrown.

**Comment by mikelehen** [comment]
Unfortunately I'm not sure if we can do much about either error (they're somewhat outside our control). :-(  The first one in particular seems like a bug in Chrome if anything ("Internal error opening backing store for indexedDB.open" is not coming from our code, but from Chrome I believe).

Just for the sake of characterizing the impact, do you have data on what percentage of your users are hitting these errors?

**Comment by holmberd** [comment]
@mikelehen you are correct in that the errors originates from within Chrome; corrupt Chrome user profiles being another suspect for the first error.

Second error is referenced in the transaction: https://chromium.googlesource.com/chromium/src/+/master/content/browser/indexed_db/indexed_db_transaction.cc#475

A percentage for the entire user base is still quite small: First error being around **~0.2%**, second error around **~0.3%**. That being a very rough estimate of the entire user base were in reality active users vary. And as I switched to Firestore as storage about 4 months ago I will need more data, i.e. the increase of errors I'm seeing might be a coincidence.
