### ISSUE TITLE
@firebase/testing - collection().add() never returns

### ISSUE THREAD

**Issue by sparkertime** [firebase/firebase-js-sdk#1519]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 10.14.2
  * Browser version: n/a
  * Firebase SDK version: `@firebase/testing 0.7.1`
  * Firebase Product: Firestore

#### Steps to reproduce:
Calling `await collection().add()` never returns when using the testing library. This only happens with add() - passing the same parameters to doc().set() works without incident.

#### Relevant Code:

```javascript
const Firestore = require('@firebase/testing');

const db = Firestore.initializeAdminApp({
  projectId: 'whatever'
}).firestore;

// this will never return
const campaignRef = await db.collection('campaigns').add({
  title: 'hello'
});
```

**Comment by mikelehen** [comment]
@ryanpbrewster Does the testing SDK wrap the firestore method (incorrectly?) or something?  Otherwise I'm not sure how this would break.

**Comment by ryanpbrewster** [comment]
Possible that we're not handling auto-id allocation properly, will investigate.

**Comment by ryanpbrewster** [comment]
This code works as expected for me:
```
const firebase = require("@firebase/testing");

async function main() {
  let app = firebase.initializeTestApp({ projectId: "foo" });
  await app.firestore().collection("c").add({ x: 1 });
  let snap = await app.firestore().collection("c").get();
  console.log(snap.docs.map(d => d.id));
  app.delete();
}

main();
```

I can run it a few times in a row and each time it adds a document to the collection.

My package.json looks like
```
{
  "devDependencies": {
    "@firebase/testing": "^0.7.1"
  }
}
```

and my `firebase` command-line tool is version
```
$ firebase --version
6.3.0
```

**Comment by ryanpbrewster** [comment]
The code snippet you provided doesn't quite work, I get `db.collection is not a function`, can you provide some more details to help me reproduce this issue?
