### ISSUE TITLE
initializeApp causing Polymer ready() to be triggered multiple times

### ISSUE THREAD

**Issue by stucker71** [firebase/firebase-js-sdk#1522]
### [REQUIRED] Describe your environment

  * Operating System version: IOS iPhone 6
  * Browser version: Latest Safari on IOS iPhone 6
  * Firebase SDK version: latest
  * Firebase Product: firebase app

### [REQUIRED] Describe the problem

initializeApp is causing Polymer ready() to be triggered multiple times in IOS (only tested using iPhone 6 Safari latest version). It's a Polymer 3 starter kit project and built using Polymer CLI es5-bundled build preset.

#### Relevant Code:

```
import firebase from '@firebase/app';
import '@firebase/firestore';
import '@firebase/auth';
```

```
constructor() {
    super();
    firebase.initializeApp({
      apiKey: 'xxx',
      authDomain: 'xxx',
      projectId: 'xxx'
    });
  }



  ready() {
    super.ready();
    console.info("ready");
  }

```

You will find ready() is triggered three times. When you remove import `'@firebase/auth';` the issue disappears.

**Comment by stucker71** [comment]
Same issue here https://github.com/Polymer/tools/issues/3349

**Comment by stucker71** [comment]
Appears to be Polymer issue.

**Comment by Feiyang1** [comment]
@stucker71 It seems the issue has been resolved. Can we close it now?

**Comment by stucker71** [comment]
Yep.
