### ISSUE TITLE
Persistency issue with unlisten in 5.8.2 or I'm missing something

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#1524]
### [REQUIRED] Describe your environment

  * Operating System version: windows
  * Browser version: chrome 72
  * Firebase SDK version: 5.8.2
  * Firebase Product: atuh, database

### [REQUIRED] Describe the problem
So I've been on and off enabling persistency. Having for syncing between a lot of clients always had some issues so I disable it unless experimenting.
After upgrade today to 5.8.2 I thought I give it another try.
I now consistently get a:
FIRESTORE (5.8.1) INTERNAL ASSERTION FAILED: Trying to unlisten on query not found.
Because of the VERY HELPFUL Query you now add to the error it was easy to pinpoint the offending subscription.
However repairing it has been not that easy.
I have to unsubscribe/subscribe to the query with different parameters, the first subscribe works but the second one fails already.
I've tried unsubscribing in multiple ways, I normally use the excellenct untilDestroyed(this) library. But I switched to manual unsubscribing (each time I have to subscribe to the query with new parameters), but also that doesn't work.
Disabling persistency solves the issue.

some code:
` 
ngOnChanges(changes: { [propertyName: string]: SimpleChange }) {
    // console.log("changes: ", changes);

    if (changes['selectedOrganisation']) {

      this.loading = true;

      if (this.dataSource) this.dataSource.disconnect();
      if (this.subscription && !this.subscription.closed) this.subscription.unsubscribe();

      if (this.selectedOrganisation) {
        this.subscription = this.OrganisationService.getChildOrganisationsForOrganisationObs(this.selectedOrganisation).subscribe((data: Organisation[]) => { //.pipe(untilDestroyed(this))
          this.dataSource = new MatTableDataSource(data);

          this.dataSource.sort = this.sort;
          this.dataSource.filterPredicate = this.helpers.filterAllStringsPredicate;
          this.loading = false;
        });
      }
    }
  }
`

`
  ngOnDestroy() {
    if (this.subscription && !this.subscription.closed) this.subscription.unsubscribe();
    // if (this.dataSource) this.dataSource.disconnect();
  }`

**Comment by mikelehen** [comment]
Thanks for the report!  By definition, "INTERNAL ASSERTION FAILED" always indicates a bug in the SDK (although occasionally the bug is that we should have a better user-facing error for that circumstance).  So I'd like to get to the bottom of this.

Is there any way you can provide an actual repro I can run, preferably that only involves the Firestore SDK methods (e.g. `onSnapshot()` instead of whatever `...subscription.subscribe()` is doing)?

Thanks!

**Comment by LanderBeeuwsaert** [comment]
Yay (for me then) so it's not me, it's a bug. (less yay for you guys ;).
Well, an actual repo will not be easy to do.
But normally this should help you out:

  getChildOrganisationsForOrganisationObs(organisation: Organisation): Observable<Organisation[]> {
    return this.afs.collection("/organisations",
      ref => ref.where('parent_organisation_refs', 'array-contains',
        {'parent_organisation_ref': firestore().doc(organisation.$path), 'typeOfOrganisation': organisation.type}))
      .snapshotChanges().pipe(map(this.helpers.fsTransColl));
  }

afs is:
private afs: AngularFirestore

I have one other subscription to the same collection (with a different query) at the same time:
this.organisationListObs = this.afs.collection('organisations', ref => ref.where(new firestore.FieldPath('manager_list', this.userService.userModel.email), '==', true));

hope this helps?

**Comment by mikelehen** [comment]
Hrm. I suspect that won't be enough for me to reproduce it either. :-/

One thing that would be useful to know is if you've enabled experimentalTabSynchronization.  (and if you have, does the problem still reproduce if you disable it)

**Comment by LanderBeeuwsaert** [comment]
Aha, yes, it was enabled...
      db.enablePersistence({experimentalTabSynchronization:true}).then(() => {
        console.log("Woohoo! Multi-Tab Persistence!");
       });

**Comment by LanderBeeuwsaert** [comment]
but I just removed it and even then it still happens. So it's independent of that...

**Comment by mikelehen** [comment]
Strange.  But to be clear, if you don't call enablePersistence() at all, then the problem does not happen, correct?

**Comment by LanderBeeuwsaert** [comment]
Correct.

**Comment by schmidt-sebastian** [comment]
I've tried to figure out what is going on and have a possible theory. Can you confirm that you are using multiple tabs? We are using LocalStorage to propagate state between different tabs, and this can't be done synchronously. What I think might be happening here is the following:

- User in Tab B opens a new query (queryA)
- Tab A is the "master" tab and listens to queryA on behalf of Tab B
- Tab B stops listening to the query just as the user in Tab A starts the same query
- Tab A now gets a LocalStorage notification that it should remove the query and it does this even though it itself is now listening.
- When Tab A calls `unsubscribe()`, the `EventManager` knows about this query, but `SyncEngine` doesn't. This triggers this assert.

**Comment by LanderBeeuwsaert** [comment]
Hello Sebastian,

well I think it could have somewhat of a relation to this but it's not 
solving the issue.
I saw there was a bugfix maybe related to this in the newest release so 
i did an upgrade to 5.8.4 but it didn't solve the issue.
Also, if what you say would be the problem, then if I interpret 
correctly it should be solved if I just work in 1 tab => so I tried this 
before and after the update but it didn't fix the issue.

AHA, I found some other info for you:

So this query/subscription:

return this.afs.collection("/organisations",
ref => ref.where('parent_organisation_refs', 'array-contains',
{'parent_organisation_ref': firestore().doc(organisation.$path), 'typeOfOrganisation': organisation.type}))
   .snapshotChanges().pipe(map(this.helpers.fsTransColl));

Actually never completes if persistency is enabled with 
experimentalTabSynchronisation. And the exception occurs when 
unsubscribing from this non-competed subscription.
If I enable persistency without experimentalTabSynchronisation it 
completes the first time and gives not a problem when unsubscribing the 
first time. But it doesn't complete on a subsequent subscribe and then 
fails on this second unsubscribe.

hope this helps.

------ Original Message ------

**Comment by LanderBeeuwsaert** [comment]
@schmidt-sebastian 
@mikelehen 
I'm not sure if the fix is part of 5.9.0?
Just wanted you guys to know that if it is, the issue I've been having is still not solved by the fix:

![image](https://user-images.githubusercontent.com/1098243/54416168-ee96ab80-46fe-11e9-94c7-76cb2ddf008c.png)

**Comment by schmidt-sebastian** [comment]
We missed the cutoff by a couple of hours. It should be part of the next release.

**Comment by LanderBeeuwsaert** [comment]
:), ok, I'll test on the next release.
