### ISSUE TITLE
Firestore error uncaught in promise when primary lease check fails

### ISSUE THREAD

**Issue by holmberd** [firebase/firebase-js-sdk#1531]
* Firebase SDK version: 5.8.2
  * Firebase Product: Firestore

#### Problem:
Firestore error uncaught in promise when primary lease check(canActAsPrimary) fails and `enabledPersistence()` is enabled. Expect `enabledPersistence()` catch block to catch this.

![image](https://user-images.githubusercontent.com/13058304/52598413-79d40700-2e0a-11e9-97f4-ce393303df31.png)

#### Steps to reproduce:
- Run two tabs as primary clients with `enabledPresistence()` enabled.

```javascript
firestore.enablePersistence()
  .catch(err => {
    if (err.code == 'failed-precondition') {
      console.error('Failed to create database persistence: Multiple instances are running.');
    } else if (err.code == 'unimplemented') {
      console.error('Failed to create database persistence: Browser version not supported.');
    } else {
      err.message = 'Failed to create database persistence: ' + err.message;
      console.error(err);
    }
  });
``` 

#### Relevant code:
https://github.com/firebase/firebase-js-sdk/blob/6b53e0058483c9002d2fe56119f86fc9fb96b56c/packages/firestore/src/local/indexeddb_persistence.ts#L611

**Comment by wilhuff** [comment]
Sorry, I don't fully understand. Are you using `enabledPersistence({experimentalTabSynchronization: true})`?

**Comment by holmberd** [comment]
@wilhuff No worries. To answer your question: I'm **not** using `experimentalTabSynchronization: true`. My problem is with the second uncaught error not getting caught by the Promise returned from `enablePersistence()`.

Currently when `canActAsPrimary` fails it is caught in the `enablePeristence()` promise but there is also an uncaught error that bubbles all the way up to through `firebase.initializeApp`.

The comments from `canActAsPrimary` reflect the first behaviour, i.e. reject the Promise returned by `enabledPersistence()`.
```
// Fail the `canActAsPrimary` check if the current leaseholder has
// not opted into multi-tab synchronization. If this happens at
// client startup, we reject the Promise returned by
// `enablePersistence()` and the user can continue to use Firestore
// with in-memory persistence.
```

**Comment by mikelehen** [comment]
Just to be clear, are you experiencing some sort of broken functionality?  Or just seeing the extra log message in the console?  To me it looks like your catch block is getting executed as expected, correct?

**Comment by holmberd** [comment]
Yes, the catch block is getting executed as expected for one of the rejected promises.

Seems similar to issue: [256](https://github.com/firebase/firebase-js-sdk/issues/256)

> When enabling firestore persistance on a second tab there is an error message in the console, regarding an uncaught Promise, even when catching the Promise returned by `.enablePersistance()`.

#### Test code (test.js)
```javascript
const firebase = require('firebase/app');
require('firebase/auth');
require('firebase/firestore');

firebase.initializeApp({
  // config stuff
});

const firestore = firebase.firestore();
firestore.enablePersistence()
  .catch(err => {
    console.error(err);
  });  
```
- Create bundle
`browserify test.js -o test.bundle.js`

- Load script in html and open in two tabs

#### Uncaught error in promise
![image](https://user-images.githubusercontent.com/13058304/52671453-009ee780-2ed0-11e9-8c28-468831b068a3.png)

**Comment by mikelehen** [comment]
@holmberd Thanks! It turns out you're right.  It is the same issue as #256 but it was regressed by [this change](https://github.com/firebase/firebase-js-sdk/commit/f970f9cd51c17897e397d5b0e30dc5abc3c4999d#diff-db492a8b6a1f21cd1cf9bb73da289281R175).

Thanks for the report!
