### ISSUE TITLE
signInAndRetrieveDataWithCredential error 400 : Invalid headless request URL

### ISSUE THREAD

**Issue by matejicekme** [firebase/firebase-js-sdk#1535]
* Operating System version: Android & Ios
  * Browser version: Cordova webview
  * Firebase SDK version: 5.8
  * Firebase Product: Auth

Hi, I'm trying to integrate facebook authentication via firebase on my Cordova application but I have some problems.
I manage to correctly retrieve the token from facebook via the cordova-plugin-facebook plugin4; a popup opens, asks me to accept the application and once accepted returns to the app.
I then pass the requested information to "signInAndRetrieveDataWithCredential" as indicated in the documentation.

```javascript
let credential = new firebase.auth.FacebookAuthProvider().credential(fbAuthDatas.authResponse.accessToken)
      AUTH.signInAndRetrieveDataWithCredential(credential).then((user) => {
console.log(user)
}).catch((error) => {
        console.log(error)
      })
```

The problem then appears, my catch returns an error 400 : Invalid headless request url: http://localhost?id_token=EAA...&providerId=facebook.com

Maybe someone has an idea?

Thank you !

**Comment by bojeil-google** [comment]
Hey @matejicekme, change your credential initializer to:

    let credential = firebase.auth.FacebookAuthProvider.credential(fbAuthDatas.authResponse.accessToken);

That should get it to work.

**Comment by matejicekme** [comment]
Oh @bojeil-google ... reading the docs all of that is written x).
That's what it costs to have your head in the code. Thank you for getting me out of there you saved me a lot of time.

C ya !
