### ISSUE TITLE
Firefox is not opening window in service worker to push messages.

### ISSUE THREAD

**Issue by Deadoc** [firebase/firebase-js-sdk#1538]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Version 1803 Build 17134.472
  * Browser version: Firefox 65
  * Firebase SDK version: 5.8.2
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
I have everything setup, the Push messages are received fine and when I click on it, it opens new window only in Chrome, not in Firefox.
#### Steps to reproduce:
Clients.openWindow("some url") doesn't work if firebaseApp.messaging() was called due to initialization step in FireFox version 57 and greater.
#### Relevant Code:

```typescript
initializeFirebase = (firebaseMessagingSettings: FirebaseMessagingSettings) => {
        this.firebaseApp = Firebase.initializeApp({ "messagingSenderId": firebaseMessagingSettings.messagingSenderId });

        const messaging = this.firebaseApp.messaging(); // this is the reason
        messaging.setBackgroundMessageHandler(this.handleBackgroundPushMessage);
}

this.scope.onnotificationclick = event => {
    this.scope.clients.openWindow(clickUri); // this makes no error, nothing
}
```

**Comment by khoasting** [comment]
I am struggle with the same problem. So this is the bug of firefox 65 or firebase. pls explain.

**Comment by mmermerkaya** [comment]
Using the `link` field works fine in Firefox 65. Have you tried that?

You can find more information here: https://firebase.google.com/docs/cloud-messaging/js/receive#setting_notification_options_in_the_send_request

**Comment by amoenk** [comment]
Hi @mmermerkaya, I'm also experiencing the same problem, however, the versions are newer:
 
Firefox 69.0.2 64bit OSX
Firebase SDK 6.3.4

Like @Deadoc experienced, `Clients.openWindow` works exactly as I'd expect in Chrome, but in Firefox it has no effect. There are no errors - the failure is silent. Clicking the notification will bring the Firefox window to the front, but whatever tab had previously had focus will still have focus. 

Can you tell me what kind of additional info or testing you need to debug and I can try to get that for you? Thank you!
