### ISSUE TITLE
[Tracking] Enable repository gardener on this repo

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-js-sdk#1543]
This is a tracking bug for a process fix.  After https://github.com/GoogleCloudPlatform/repository-gardener/pull/80 the DPEBot is now suitable for keeping this repo up to date.

We need to take the following steps:

1. Run the bot once on this repo manually to see what it would produce
2. Make all desired dependency updates
3. Add `ncurc` files to ignore the others
4. Get CI passing
5. Enable to dependency update bot to run on a ~weekly basis

Steps 1-4 are for @Feiyang1 and then I can do Step 5.

**Comment by samtstern** [comment]
I got pwned by my own robot 🤷‍♂️

**Comment by Feiyang1** [comment]
@samtstern Somehow we didn't get the PR. Any idea?

**Comment by samtstern** [comment]
I am super confused.  After the kokoro job runs `ncu` then `git diff` shows empty.  But when I do it locally, that's not the case.

**Comment by Feiyang1** [comment]
https://github.com/firebase/firebase-js-sdk/pull/1654
