### ISSUE TITLE
FR: getCollections using @firebase/testing

### ISSUE THREAD

**Issue by domness** [firebase/firebase-js-sdk#1550]
### Describe your environment

  * Operating System version: mac OS 10.14.3
  * Browser version: Google Chrome 72.0.3626.109
  * Firebase SDK version: 5.8.3
  * Firebase Product: firestore

### Describe the problem

I'm trying to build a set of tests for a function that uses `docRef.getCollections()`. The cloud function runs fine, and the code inside correctly calls `getCollections()`.

The @firebase/testing doesn't seem to have any knowledge of the function however, giving me the error:

```TypeError: docRef.getCollections is not a function```

Are there any plans, or work arounds to get this working in a set of unit/integration tests?

**Comment by schmidt-sebastian** [comment]
We distribute two different Firebase SDKs. The SDK in this repository is for Mobile/Web usage and used by Firebase SDK. The other SDK is a [Server SDK](https://www.npmjs.com/package/@google-cloud/firestore) and used by Google Cloud Functions. We only support `getCollections()` in the Server SDKs.

Note that you can still test your Cloud Function against the Firestore emulator. You need to initialize the `@google-cloud/firestore` Server SDK with the following options:

```
{
  servicePath: 'localhost', 
  port: 8080,
  sslCreds: grpc.credentials.createInsecure()
}
```

You can pass these options directly to the Firestore constructor or to []([Firestore.settings()](https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L121)) if you are using the Firebase Admin SDK.
