### ISSUE TITLE
Enable TypeScript's --strict flag for the whole repo

### ISSUE THREAD

**Issue by mmermerkaya** [firebase/firebase-js-sdk#1562]
From TS documentation: "Enabling `--strict` enables `--noImplicitAny`, `--noImplicitThis`, `--alwaysStrict`, `--strictBindCallApply`, `--strictNullChecks`, `--strictFunctionTypes` and `--strictPropertyInitialization`."

This would let us take advantage of TypeScript's full potential by enabling maximum type safety, make our code safer,  prevent a lot of bugs that could have been caught easily, and help a lot with refactoring.

AFAIK, currently the only package that enables this flag is Messaging.

**Comment by mmermerkaya** [comment]
Instead of turning `strict` on in one go, we can start by turning on the individual flags one by one. I recommend starting with `strictNullChecks`, since that can catch a lot of errors, and isn't too hard to fix (can just add an assertion with `!`).

**Comment by hsubox76** [comment]
Finished:
https://github.com/firebase/firebase-js-sdk/pull/2078
https://github.com/firebase/firebase-js-sdk/pull/1948
https://github.com/firebase/firebase-js-sdk/pull/1935
https://github.com/firebase/firebase-js-sdk/pull/1915
https://github.com/firebase/firebase-js-sdk/pull/1897
https://github.com/firebase/firebase-js-sdk/pull/1862
https://github.com/firebase/firebase-js-sdk/pull/1805
