### ISSUE TITLE
Push-Notifications Failed to register/update a ServiceWorker

### ISSUE THREAD

**Issue by muscaiu** [firebase/firebase-js-sdk#1566]
### [REQUIRED] Describe your environment
  * Operating System version: Win10
  * Browser version: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
  * Firebase SDK version: "firebase": "^5.8.4",
  * Firebase Product: messaging

#### Steps to reproduce:
[codesandbox](https://codesandbox.io/s/l5n6rw2rwl)
#### Relevant Code:
```javascript
    import * as firebase from 'firebase/app';
    import "firebase/messaging";

    export const initializeFirebase = () => {
      firebase.initializeApp({
        messagingSenderId: "997402867981"
      });
    }

    navigator.serviceWorker
      .register('/my-sw.js')
      .then((registration) => {
        firebase.messaging().useServiceWorker(registration);
      });


    export const askForPermissioToReceiveNotifications = async () => {
      try {
        console.log('askForPermissioToReceiveNotifications');
        const messaging = firebase.messaging();
        await messaging.requestPermission();
        const token = await messaging.getToken();
        console.log('token:', token);

        return token;
      } catch (error) {
        console.error(error);
      }
    }
```

###  Description
I'm following this tutorial on react-firebase push notifications, and can't figure out what I'm doing wrong. Been googling for some time without any working solution, so here I am.

Also posted this question on StackOverflow: https://stackoverflow.com/questions/54907306/push-notifications-failed-to-register-update-a-serviceworker

### The Error when trying to run messaging.getToken() : 

![err_](https://user-images.githubusercontent.com/11426309/53498571-3be40d80-3aaf-11e9-98c1-84a94acb80fc.PNG)

**Comment by hsubox76** [comment]
I don't think this is a Firebase issue.  The tutorial seems a little confusing to follow and you seem to have ended up with code that looks for a `/my-sw.js` file that doesn't exist in your codesandbox repo anywhere. I assume the tutorial wanted you to point it to `firebase-messaging-sw.js`.

Maybe the official docs on adding messaging to web would be a safer resource for getting started? Link: https://firebase.google.com/docs/cloud-messaging/js/client

**Comment by mmermerkaya** [comment]
I agree with @hsubox76, this is definitely not a Firebase bug, as you can see from the previous errors on your screenshot.
