### ISSUE TITLE
Firebase-messaging: cannot read property 'getNotificationPermission_' of undefined

### ISSUE THREAD

**Issue by Dobiday** [firebase/firebase-js-sdk#1569]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Mojave 10.14.3
  * Browser version: Google Chrome 72.0.3626.119, Firefox 65.0.1
  * Firebase SDK version: 5.5.8
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

I work with a website that has some legacy code that is bundled using requirejs, so I copy files `firebase-app.js` and `firebase-messaging.js` into a directory with other libs and require firebase from that directory.

When I call the method `.requestPermission()` from `firebase-messaging` it outputs an error in the console: `Cannot read property 'getNotificationPermission_' of undefined`.

If I replace every `this` binding inside the inner functions of `firebase-messaging.js` file like this: `let self = this` and pass `self` into every inner function, firebase  works as expected, but it's really uncomfortable.

How should I correctly import firebase using requirejs?

I would like to use the same code for requirejs and webpack bundlers, so I use Babel to transpile the code form ESM to AMD.

#### Relevant Code:

```javascript
import firebase from '@firebase/app';
import '@firebase/messaging';

const config = {
  myconfig
};

firebase.initializeApp(config);

firebase.messaging.requestPermission()
```

#### Same code afrer transpiling using [Babel](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAM2FApgIwIYGcWKhEOAcgAElVMcB6DMMIgbgChRJZizl1sUqQUsWDAHNgAO2GMmTAMYQxWeHLFJhcALxwA3kzhwQAT2WqmAX2ZNy3HADpxwGMAwAbYAC8UAQToAKY8GEASgsrShQbfkERcWEbVABHAFcBGAAFFCgQYEFgeR9A6RQADzZ4ABMUBAxE53hQngYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2%2Cenv&prettier=false&targets=&version=7.3.4):

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _app = _interopRequireDefault(require("@firebase/app"));

require("@firebase/messaging");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var config = {
  myconfig: myconfig
};

_app.default.initializeApp(config);

_app.default.messaging.requestPermission();

var _default = _app.default;
exports.default = _default;
```

Here is my requirejs config:

```javascript
require.config({
    baseUrl     :   myUrl,
    // Timeout for modules load
    waitSeconds :   0,
    // Path to libraries
    paths : {
      "@firebase/app"             :   "myFolderWithLibs/firebase/firebase-app",
      "@firebase/messaging"       :   "myFolderWithLibs/firebase/firebase-messaging"
    }
})
```

**Comment by Feiyang1** [comment]
You can't call requestPermission as a property on firebase.messaging. I'm not sure how you were able to invoke requestPermission this way. is it a typo?
You should do `firebase.messaging().requestPermission()` instead. 

Here is a working example: https://jsfiddle.net/thmkdz85/1/

**Comment by Dobiday** [comment]
I`m sorry, my bad. Of course I call `firebase.messaging().requestPermission()` as a method.
This is a part of code which throw error https://codepen.io/anon/pen/XGjGLX
And this is manual way to fix error https://codepen.io/anon/pen/drpLPV
This way is not correct I think, because I violate source code. Is there any other way?

**Comment by Feiyang1** [comment]
You shouldn't need to do it manually. The helper functions should handle `this` arg correctly.

I assume the error is coming from your requirejs build, since you mentioned replacing `this` in firebase-messaging.js file. 
I tried requirejs with file from "https://www.gstatic.com/firebasejs/5.5.8/firebase-messaging", and it worked fine. Is it the file you copied to `myFolderWithLibs/firebase/firebase-messaging`? If not, can you please try this file?

**Comment by Dobiday** [comment]
Sorry for the long absence of comments. 
I already tried to copy https://www.gstatic.com/firebasejs/5.5.8/firebase-messaging.js, than tried to copy file firebase-messaging.js from node_modules. Everything shows the same error.

**Comment by Feiyang1** [comment]
Okay, thanks for confirming that. I would need you to create a minimal repro, so I can take a look at it.

I did a test at https://jsfiddle.net/thmkdz85/1/, and it worked fine. I'd like to know what you do differently with the repro.

**Comment by Dobiday** [comment]
I`m trying to reproduce this bug in new repo. I plan to send a repository on Monday

**Comment by Dobiday** [comment]
Thank you for your help, I resolve the error while creating new repo. In my project was used requirejs with rjs optimization of the `grunt-contrib-require`.
Firebase path was set in requirejs optimization config like 
```javascript
require.config({
    baseUrl: "/another/path",
    paths: {
        "@firebase": "mydir/libs/firebase"
    }
```
Instead of that I must use [the special 'empty:' scheme](https://requirejs.org/docs/optimization.html#empty)
```javascript
require.config({
    baseUrl: "/another/path",
    paths: {
         "@firebase/app"      : "empty:",
          "@firebase/messaging": "empty:"
    }
```
Again thanks for your help, I should have studied the requirejs better and not disturbed you

**Comment by Feiyang1** [comment]
No worries! I'm glad we resolved the issue.
