### ISSUE TITLE
All images put to storage are saved as 'octet-stream' rather than image/jpeg

### ISSUE THREAD

**Issue by Oakyden** [firebase/firebase-js-sdk#1570]
I'm creating a new managed Expo app, on SDK 31. 

I have the following function

```
 uploadImage = async (uri, imageName) => { 

    this.setState({attemptingUpload: true})

    const response = await fetch(uri);
    const blob = await response.blob();

    var ref = firebase.storage().ref().child('images/' + imageName+'.jpg');

    var metadata = { cotentType: 'image/jpeg', };

    return ref.put(blob, metadata);
  }
```

It uploads the image successfully and with the right file extension (and i've dictated the metadata type to be sure) . However, all the files are uploading as 'application/ octet-stream' which is the firebase default and indeed this appears to make the uploaded file non-readable.

Any ideas for why this is happening? Looking at the firebase sdk  sourcecode i'd have thought this would work

**Comment by schmidt-sebastian** [comment]
Hello! You are setting a `cotentType` key, but it needs to be `contentType`. Do you mind fixing the typo and trying this again? 

I am closing this issue for now. Please do re-open if this suggestion does not fix your issue.

**Comment by Oakyden** [comment]
Thanks, the issue was actually this 👍 
https://github.com/expo/expo/issues/2402#issuecomment-443726662 

There's an issue with the way Blobs are handled in react native.

Overall people need to follow this to get image uploads working with firebase from react native https://github.com/expo/firebase-storage-upload-example
