### ISSUE TITLE
Ambiguous error for malformed `continueUrl`

### ISSUE THREAD

**Issue by colinricardo** [firebase/firebase-js-sdk#1571]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.14.4
  * Browser version: 72.0.3626.119 
  * Firebase SDK version: 5.8.4
  * Firebase Product: auth / hosting

### [REQUIRED] Describe the problem
Using the email sign in functionality, if you provide a malformed `continueUrl`, you get a cryptic error: 

![image](https://user-images.githubusercontent.com/21294951/53651910-9b712300-3c3f-11e9-8690-39caaeba7d58.png)

The real error is from the malformed `continueUrl`. 

#### Steps to reproduce
Use a `continueUrl` like:

`https://something.firebaseapp.com:`

Note the `:` after the `something.firebase.com`. The `continueUrl` is invalid, but the error just says "No API key provided!". 

This results in the following redirect:

`https://something.firebaseapp.com/__/auth/action?apiKey=<API_KEY>&mode=signIn&oobCode=<OOB_CODE>&continueUrl=https://something.firebaseapp.com:/auth&lang=en`

Which produces the above cryptic error. 

#### Relevant Code:
See above.

**Comment by hanslivingstone** [comment]
Hi Colin, thanks for reporting this! The issue should be fixed in production now, please give it a shot.
