### ISSUE TITLE
FR: Synchronous browser check for offline persistence compatibility

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#1577]
The documentation on [offline support](https://firebase.google.com/docs/firestore/manage-data/enable-offline) for Firestore JS SDK shows an async check if the browser is compatible or not.

#### Relevant Code:

```javascript
firebase.firestore().enablePersistence()
  .catch(function(err) {
      if (err.code == 'failed-precondition') {
          // Multiple tabs open, persistence can only be enabled
          // in one tab at a a time.
          // ...
      } else if (err.code == 'unimplemented') {
          // The current browser does not support all of the
          // features required to enable persistence
          // ...
      }
  });
```

#### My Question:

I initialise Firebase make this check and then based on that feedback initialise a data store.

Because of my particular setup I need to go through some hoops to work around the a-synchronousness of this browser compatibility check.

Is there any way Firebase can provide us:
- a special **method to make a synchronous check to see if the browser is compatible with offline persistence or not?**

It would make the life of many developers easier if we can just do a synchronous check first then do one thing or the other based upon that feedback.

**Comment by var-const** [comment]
Thank you for the report. Can you please provide some additional information about your use case?
* are you using the `experimentalTabSynchronization` flag?
* is there a reason why enabling persistence might fail that you are particularly concerned about/hit most often?

I think it would be possible to do _some_ checks synchronously (such as checking the browser version to see if it supports IndexedDB). However, my concern is that some errors only happen after an async operation takes place (e.g., the database may fail to open) -- if your app needs to account for this type of errors, then the synchronous check would be insufficient. In other words, it's possible to check synchronously whether enabling persistence is guaranteed to fail, but that check is insufficient to determine whether enabling persistence will actually succeed.

**Comment by mesqueeb** [comment]
@var-const You are right to say:
> it's possible to check synchronously whether enabling persistence is guaranteed to fail, but that check is insufficient to determine whether enabling persistence will actually succeed.

This sentence made me agree to choose the careful way, and make sure **I rewrite my app to work with the asynchronous check** to see if offline persistence failed or succeeded.

**Comment by mesqueeb** [comment]
@var-const As a final question related to this problem.

If I make a wrapper around a `Firebase.firestore()` instance, and I want to know which configuration was enabled in this instance.
How can I know:
- does the `Firebase.firestore()` have `.enablePersistence()` enabled?
- does the `Firebase.firestore()` have the `experimentalTabSynchronization` flag enabled?

**Comment by var-const** [comment]
Unfortunately, we currently don't provide a way to read the Firestore settings, although we may be open to adding that in the future if there's more demand for this. Note, however, that Firestore will never try to modify the settings provided by the app, so you should be able to assume that whichever settings you configured are always in force. Is there any additional context that prevents your app from simply relying on the settings it provided to Firestore? Do you keep several instances of Firestore that are configured differently? In that case, perhaps you could associate the configuration with each wrapper?

For whether enabling persistence has succeeded, the only way to determine that is for the app to store the asynchronous result of calling `enablePersistence`. Firestore doesn't store whether the call has succeeded or not. Normally, we expect the apps using Firestore to continue regardless of whether enabling persistence has succeeded or not, and in most cases to not check the error code. Note that Firestore will continue to work even if enabling persistence doesn't succeed. Can you give more details on how your app treats the result of enabling persistence?

(This may be irrelevant to your usage of Firestore, but just in case -- you can see the checks that Firestore makes to determine whether persistence can be enabled [here](https://github.com/firebase/firebase-js-sdk/blob/e2bbfd0d256a6cc3fb878917638affa6007fa311/packages/firestore/src/local/simple_db.ts#L133-L174) (checks browser version, happens always) and [here](https://github.com/firebase/firebase-js-sdk/blob/54bdfc4cebb038ffe19b16bb263b1007132ca356/packages/firestore/src/local/shared_client_state.ts#L599-L601) (checks whether the browser supports local storage, happens only if `experimentalTabSynchronization` is set to `true`). Your app could do the same checks if it helps your use case. However, in most cases we expect that whether enabling persistence has succeeded or not shouldn't make a difference to the app)
