### ISSUE TITLE
`firebase` package's index.d.ts file has not been updated.

### ISSUE THREAD

**Issue by ogawa0071** [firebase/firebase-js-sdk#1580]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.3
  * Browser version: Google Chrome v72
  * VS Code version: v1.31.1
  * Firebase SDK version: v5.8.5
  * Firebase Product: Storage

### [REQUIRED] Describe the problem

This is `firebase` package's index.d.ts file.
https://github.com/firebase/firebase-js-sdk/blob/400fd786a59340fd9adcb2c7f083479445b8981f/packages/firebase/index.d.ts#L5781

This is `@firebase/storage-types` package's index.d.ts file.
https://github.com/firebase/firebase-js-sdk/blob/400fd786a59340fd9adcb2c7f083479445b8981f/packages/storage-types/index.d.ts#L80-L83

These are the differences.
`@firebase/storage-types` is correct.

VS Code type checking refer to `firebase` package's wrong file.
So, my type checking shows error.

I think `firebase` package's index.d.ts file should be deleted if there is no plan to maintain it.

**Comment by Feiyang1** [comment]
Thanks for reporting this! 
Given how firebase is structured right now, we maintain 2 typing files and sometimes they get out of sync. 

That said, I'm curious to learn why this discrepancy causes an error for you. Typically you import firebase package and only use the types defined in its index.d.ts file.

Can you provide a snippet that shows how you import firebase packages and where the error happens?

**Comment by ogawa0071** [comment]
@Feiyang1 

Thanks!
It's my code.

useUpload.tsx
```typescript
import { useState, useEffect } from 'react';
import firebase from './firebase';

const storage = firebase.storage();

export default function useUpload(
  path: string,
  data: Blob | Uint8Array | ArrayBuffer
): firebase.storage.UploadTaskSnapshot {
  const [uploadTaskSnapshot, setUploadTaskSnapshot] = useState();

  useEffect(() => {
    if (data) {
      const uploadTask = storage.ref(path).put(data);

      uploadTask.on('state_changed', _uploadTaskSnapshot => {
        setUploadTaskSnapshot(_uploadTaskSnapshot);
      });

      (async () => {
        setUploadTaskSnapshot(await uploadTask.then());
      })();
    }
  }, [path, data]);

  return uploadTaskSnapshot;
}
```

firebase.ts
```typescript
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
import 'firebase/storage';

const config = {
  apiKey: 'XXX',
  authDomain: 'XXX',
  databaseURL: 'XXX',
  projectId: 'XXX',
  storageBucket: 'XXX',
  messagingSenderId: 'XXX'
};

firebase.initializeApp(config);

(async () => {
  await firebase.firestore().enablePersistence();
})();

export default firebase;
```

tsconfig.json (generate by `create-react-app`)
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

My VS Code decide `_uploadTaskSnapshot` type is `Object`.
<img src="https://user-images.githubusercontent.com/3258736/53973456-22446500-4144-11e9-9d7e-16493ea21a77.png">

And `Object` don't have `.bytesTransferred` property error.
<img src="https://user-images.githubusercontent.com/3258736/53973483-312b1780-4144-11e9-9a0c-6297d12ad829.png">

**Comment by Feiyang1** [comment]
I see. Thanks for the detailed response!
I went ahead and made a PR to fix it. You can manually cast the object to `firebase.storage.UploadTaskSnapshot` for the time being.
