### ISSUE TITLE
 error:The redirect operation has been cancelled by the user before finalizing

### ISSUE THREAD

**Issue by premtemp1** [firebase/firebase-js-sdk#1608]
hello

Not able to create a user or get the token . After selecting the email address and password,  I am redirected to a "about:blank" page with a done button.. Selecting the done button closes the page and I at the login page of my app. 

This is the error message  in the iOS console
the redirect operation has been cancelled by the user before finalizing.

A similar issue was open here --https://github.com/firebase/firebaseui-web/issues/172  

  * Operating System version: Mac os
  * Firebase SDK version: 5.8.6
  * Firebase Product: authentication
  * cordova:8.1.2 (cordova-lib@8.1.1)

Here is the steps

1:  Install app on iOS and select the open with google button
2: Redirected to a screen where I have to enter my email and pass
3: I am then redirected to a blank page "about:blank"

I verified that the Firebase dynamic  and my custom url scheme is working

4: If I now put the app in background and then bring it back to foreground
5: Select the login with google 
6: I am now redirected to a page and then immediately returned to my app with the token and the user is created

`
This the button click code
$scope.authcicp = function () {
            var provider = new firebase.auth.GoogleAuthProvider();
            firebase.auth().signInWithRedirect(provider).then(function () {
                return firebase.auth().getRedirectResult();
            }).then(function (result) {
                var token = result.credential.accessToken;
                var user = result.user;
            }).catch(function (error) {
                var errorCode = error.code;
                var errorMessage = error.message;
            });
            /* jshint ignore:end */
        };

`
Thanks for your help

**Comment by premtemp1** [comment]
There was a bug with the IBM MFP framework that cause this issue

**Comment by MatthewPringle** [comment]
I have had the same issue, on iOS 12 at least of it never redirecting back to the app successfully.

Instead it eventually ends up at about:blank and the browser tab doesn't close.

It seems that the app goes to sleep when the sign in window is opened and isn't running when the callback is passed.

To solve this I installed https://github.com/katzer/cordova-plugin-background-mode and set it to keep the app awake in the background using cordova.plugins.backgroundMode.enable()

I plan to just enable and disable as needed but can anyone else check if it solves their problem.
