### ISSUE TITLE
Express only, Authentication problems

### ISSUE THREAD

**Issue by ErraticFox** [firebase/firebase-js-sdk#161]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.3.1
  * Firebase Product: auth, functions, hosting

### [REQUIRED] Describe the problem
I am testing / trying to learn Firebase with Node and Express. Using `firebase serve --only functions,hosting`, I am trying to test out authentication as I'm new to Firebase. I have this route, but everytime I click the button that triggers the route, I get this error `This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled`. There's not much on this error on Google when it comes to the JavaScript Firebase SDK. I'm pretty sure web storage is enabled, but I'm quite unsure how to fix the `location.protocol`. What am I doing wrong?

#### Steps to reproduce:
Using `firebase serve --only functions,hosting`, set up this route, use route.
```js
app.get('/auth/facebook', function(req, res) {
  const provider = new firebase.auth.FacebookAuthProvider();
  firebase.auth().signInWithPopup(provider)
    .catch(err => console.log(err));
});
```
#### Relevant Code:

Full Firebase App: https://gist.github.com/ErraticFox/44f7a8f95620f2e41e9cda59ec7ef89c

**Comment by bojeil-google** [comment]
This is work as intended. You can't call `signInWithPopup` from a server environment. It has to run on the client to go through an OAuth sign in flow via a popup/redirect interacting with the DOM.

**Comment by azizj1** [comment]
Is there another way to get an auth token from firebase using google/facebook login on an express server?
