### ISSUE TITLE
FR: add `getCredential` method

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-js-sdk#1611]
### Describe your environment

  * Operating System version: irrelevant
  * Browser version: irrelevant
  * Firebase SDK version: @firebase/auth v0.9.5
  * Firebase Product: auth

### Describe the problem

In an Android SDK there is a way to retrieve a credential to authenticate another instance of the Firebase client using `signInWithCredential` method. It seems that the `getCredential` method is not implemented in JS SDK. I spent quite some time looking for it, sorry if it actually exists and I missed it.

**Comment by bojeil-google** [comment]
I am not sure what `getCredential` method you are referring to.
All authentication methods return a `firebase.auth.UserCredential` which contains a `credential`. `signInAndRetrieveDataWithCredential` conforms to that. We have plans to eventually change the signature of `signInWithCredential` to return the same result. We are just doing it gradually as some developers may still depend on the old return type.

**Comment by merlinnot** [comment]
Oh I see, so it can only be accessed when signing in, it's not possible to get it later on (from an already authenticated client). I can easily work around it, thanks!

Just for reference, here's a link I forgot to add: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AuthResult#getCredential()
