### ISSUE TITLE
Add (link to) release notes for releases

### ISSUE THREAD

**Issue by rejhgadellaa** [firebase/firebase-js-sdk#1613]
The Firebase Releases twitter account includes urls to release notes when a new version is available. This repo does not offer any release notes (or links to them).
https://github.com/firebase/firebase-js-sdk/releases

I think it would be very useful to include the notes or a link.

Related: an rss feed of release notes would also be very appreciated!

**Comment by Feiyang1** [comment]
That's a good idea. I will see if we can add the link soon.

**Comment by Feiyang1** [comment]
We added a version and release note badge and made the link to the release note more visible in README.md, https://github.com/firebase/firebase-js-sdk/pull/1729
