### ISSUE TITLE
firebase.firestore.Timestamp in @firebase/testing is incompatible with initializeAdminApp

### ISSUE THREAD

**Issue by damonmaria** [firebase/firebase-js-sdk#1615]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.14.3
  * Browser version: no browser
  * Firebase SDK version: firebase-admin 7.1.0, @firebase/testing 0.7.6
  * Firebase Product: firestore

#### Steps to reproduce:

Trying to use Firestore `Timestamp`s with `@firebase/testing`. The most logical thing would be to access it from the what was returned from `initializeAdminApp`:
```typescript
import firebaseTesting from '@firebase/testing'
const firebase = firebaseTesting.initializeAdminApp({...})
firebase.firestore.Timestamp.now() // TypeError: Cannot read property 'now' of undefined
```

OK. I guess I can use the real firebase-admin one: 
```typescript
import firebaseTesting from '@firebase/testing'
import firebase from 'firebase-admin'
const firebaseApp = firebaseTesting.initializeAdminApp({...})
await firebaseApp.firestore().collection('test').add({ ts: firebase.firestore.Timestamp.now() })
// FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom object (found in field ts)
```

Hmmm.... looking through the code I can see that the Timestamp actually comes from the `firebase` package, not `firebase-admin`. So let's try that:
```typescript
import firebaseTesting from '@firebase/testing'
import firebase from 'firebase'  // Using client library, even tho we initializeAdminApp
const firebaseApp = firebaseTesting.initializeAdminApp({...})
await firebaseApp.firestore().collection('test').add({ ts: firebase.firestore.Timestamp.now() })
```

That works. But is obviously not right. Best would be that `initializeAdminApp` returned an instance that contained `firestore.Timestamp` of the right type.

**Comment by Feiyang1** [comment]
`initializeAdminApp` returns an instance of FirebaseApp which has a `firestore()` method that gives you the firestore instance for that app, but it's not the firestore namespace, so it has no access to `Timestamp`. You last example is the correct way to access `Timestamp` - firebase.firestore is the firestore namespace.

I agree it's confusing, but it's working as expected. Also it's not specific to a @firebase/testing, but how firebase packages work.

**Comment by ryanpbrewster** [comment]
Additional context: The `initializeAdminApp` function in `@firebase/testing` has a misleading name. It's actually returning a normal client `FirebaseApp` instance, but with admin credentials. This is only possible because the Firestore emulator accepts unsecured JWTs.

**Comment by damonmaria** [comment]
Ah, I see. I was confused because with Typescript the `firebase.app.App` returned by `initializeAdminApp()` has `firestore.Timestamp` defined. But at runtime it's not. 

I should be getting `Timestamp` directly from the `@firebase/testing` import.
