### ISSUE TITLE
NodeJs: FirebaseError: Function Blob.fromUint8Array() requires its first argument to be a Uint8Array, but it was: a custom Buffer object

### ISSUE THREAD

**Issue by coded-aesthetics** [firebase/firebase-js-sdk#1618]
* Operating System version: Ubuntu 18.04
  * Browser version: Node.js
  * Firebase SDK version: 5.9.0
  * Firebase Product: firestore

Trying to get a document containing a blob-field fails on node.js, because the data is returned as a Buffer (by gRPC?). The Blob.fromUint8Array-method then fails, because a Uint8Array is expected there.

Below is a screenshot with the stack-trace:

![Screenshot from 2019-03-20 20-26-20](https://user-images.githubusercontent.com/10363868/54713858-eb148180-4b4f-11e9-9e2d-3ddd53467e40.png)

**Comment by wilhuff** [comment]
That's really, really weird.

As far as I know a [Buffer is a Uint8Array](https://nodejs.org/docs/latest/api/buffer.html#buffer_buffers_and_typedarray) so I wonder what else is going on.

Could you give your node.js version?

**Comment by wilhuff** [comment]
For example:

```
$ node
> buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72])
<Buffer 62 75 66 66 65 72>
> buffer instanceof Uint8Array
true
```

**Comment by coded-aesthetics** [comment]
my node version is v10.15.2

**Comment by wilhuff** [comment]
Hrm:

```
$ nvm install v10.15.2
Downloading and installing node v10.15.2...
Downloading https://nodejs.org/dist/v10.15.2/node-v10.15.2-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v10.15.2 (npm v6.4.1)
$ node --version
v10.15.2
$ node
> buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72])
<Buffer 62 75 66 66 65 72>
> buffer instanceof Uint8Array
true
```

What happens in your environment? It's possible that the error is misleading here. We do have [tests that verify that round trips containing blobs work](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/test/integration/api/type.test.ts#L83) so there's got to be something else going on.

Could you share a small program that demonstrates the problem?

**Comment by coded-aesthetics** [comment]
I get the same result in the node-REPL. I will try to gather further information about what might be causing this issue.

**Comment by wilhuff** [comment]
Here's a small program that shows this works for me:

```js
const firebase = require('firebase');
require('firebase/firestore');

firebase.initializeApp({
  // ...
});

const db = firebase.firestore();
// firebase.firestore.setLogLevel('debug');

async function main() {
  const doc = db.collection('testing').doc();

  const bytes = [72, 73];

  await doc.set({
    bytes: firebase.firestore.Blob.fromUint8Array(
      new Uint8Array(bytes)
    )
  });

  const roundTripped = await doc.get();
  const blob = roundTripped.data()['bytes'];
  if (blob.toUint8Array().toString() === new Uint8Array(bytes).toString()) {
    console.log('got what I sent');
  } else {
    console.log('not equal to what I set');
  }

  console.log(roundTripped.data());
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch(err => {
    console.log(err);
    process.exit(1);
  });
```

It produced this output:

```
node test.js
(node:98924) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
got what I sent
{ bytes: Blob { _binaryString: 'HI' } }
```

**Comment by coded-aesthetics** [comment]
same here... nevertheless, in my test-environment the check for instanceof Uint8Array fails. Even though I can see that array.__proto__ is Uint8Array .
![Screenshot from 2019-03-20 21-43-06](https://user-images.githubusercontent.com/10363868/54718556-0e90f980-4b5b-11e9-81c6-9f1567ae2701.png)

**Comment by coded-aesthetics** [comment]
Okay, I just found out that this is a known issue in jest. Sorry to bother and thanks for the quick response! https://github.com/facebook/jest/issues/4422
