### ISSUE TITLE
Property 'delete' does not exist on type 'App'

### ISSUE THREAD

**Issue by coded-aesthetics** [firebase/firebase-js-sdk#1621]
* Operating System version: Ubuntu 18.04
  * Browser version: node
  * Firebase SDK version: 5.9.0
  * Firebase Product: app / typescript definitions

The delete-method is missing from the typescript definitions. I can still see the jsdoc comment, but the actual definition is no longer there.

**Comment by tspoke** [comment]
I got the same problem.

I tested latest versions and it looks like the method has been removed after the version `0.7.4`.

**Comment by Feiyang1** [comment]
Sorry for any confusion. It was accidentally deleted. It has been fixed in https://github.com/firebase/firebase-js-sdk/pull/1607 and will be available in the next release.
