### ISSUE TITLE
FR: Firestore OR operator in WHERE query

### ISSUE THREAD

**Issue by devpato** [firebase/firebase-js-sdk#1624]
**[REQUIRED] Describe your environment**
Operating System version: N/A
Firebase SDK version: 4.6.2
Firebase Product: firestore
**[REQUIRED] Describe the problem**
Rather than having to make several separate queries I would like to see an OR operator for the WHERE query in Firestore. This is something that is currently available in MongoDB or with the $or operator here.

**Relevant Code:**
The query could look something like this:

```
citiesRef.where("state", "==", "CA", "||", "state", "==", "AZ")
```
or better yet

`citiesRef.where("state == CA || state == AZ")
`
I open a new issues since the #321 got closed. People still looking for a solution on that post and haven't heard anything new from Firebase

**Comment by samtstern** [comment]
@devpato as you mentioned in #321 this is a duplicate.  I understand why you filed this, but it's not very helpful.  Let's keep this on #321.

**Comment by devpato** [comment]
@samtstern can you re open the other then since the issue hasn't been solved?

**Comment by samtstern** [comment]
@devpato it's closed because it's not something we're working on in the JS SDK.  It's something we need to do in the backend.  @mikelehen has explained this very well in his comments.

When there is backend support for this kind of query, we will open a new issue on each of the Firestore SDK repos to get the client support implemented.

**Comment by mesqueeb** [comment]
@samtstern
Thanks! Which open github thread can we go to, to follow the status of this backend feature? I reckon it's a different repo?

**Comment by darren-dev** [comment]
Anyone reading this, please go to the following links and click on the STAR icon at the left of the title:
https://issuetracker.google.com/issues/129070817
https://issuetracker.google.com/issues/129056739

![image](https://user-images.githubusercontent.com/2108283/55222403-7a86f800-5214-11e9-8e44-4355fcbd901c.png)
