### ISSUE TITLE
Bower install fails for latest release firebase@5.9.1

### ISSUE THREAD

**Issue by selvinfehric** [firebase/firebase-js-sdk#1626]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 
  * Browser version: 1.8.8
  * Firebase SDK version: 5.9.1
  * Firebase Product: all

### [REQUIRED] Describe the problem
Install latest firebase sdk using bower. It fails due to empty bower.json file.

#### Steps to reproduce:
bower install firebase
#### Relevant Code:
https://github.com/firebase/firebase-bower/commit/c4babcf4d31ba272fb147db5e65eb6791558132e#diff-0a08a7565aba4405282251491979bb6b

bower.json for latest deploy is cleared in @Feiyang1 commit

**Comment by Feiyang1** [comment]
Thanks for bringing it to our attention! We have fixed it now.

**Comment by selvinfehric** [comment]
It works now, thanks.
