### ISSUE TITLE
The bower package bower.json is an empty file

### ISSUE THREAD

**Issue by mscalora** [firebase/firebase-js-sdk#1627]
### [REQUIRED] Describe your environment

  * Operating System version: _all_
  * Browser version: _all_
  * Firebase SDK version: _5.9.1__
  * Firebase Product: _bower_package_ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

In the master HEAD (5.9.1) [c4babcf4d31ba272fb147db5e65eb6791558132e], the bower.json file is empty in the autogenerated firebase-bower repo.

Previous versions were valid (not empty).

#### Steps to reproduce:

run:
  bower install firebase

#### Relevant Code:

See: https://github.com/firebase/firebase-bower
See: https://github.com/firebase/firebase-bower/blob/master/bower.json
See: https://github.com/firebase/firebase-bower/commit/c4babcf4d31ba272fb147db5e65eb6791558132e

**Comment by Feiyang1** [comment]
Thanks for bringing it to our attention! We have fixed it now.
