### ISSUE TITLE
onAuthStateChanged unsubscribes when the connection drops

### ISSUE THREAD

**Issue by PierBover** [firebase/firebase-js-sdk#163]
### Environment

  * Operating System version: macOS 10.11.6 / Chrome 61.0.3163.79
  * Firebase SDK version: 4.1.3
  * Firebase Product: auth

### Describe the problem
It seems this is a bug.

If the internet connection drops the subscription to `firebase.auth().onAuthStateChanged` is removed.

This seems like a weird behaviour. AFAIK there is no way to know when this happens. So when trying to sign in using `firebase.auth().signInWithCustomToken(token);` there is no error, just nothing happens.

This has been driving me mad because in my case this error could only impact me if the connection dropped when the user was filling the log in form.

IMO the subscription should remain active.

#### Steps to reproduce

1. subscribe to `firebase.auth().onAuthStateChanged()`
2. turn wifi off
3. try to log in using `firebase.auth().signInWithCustomToken(token);`

It is difficult to provide sample code to reproduce this issue since it would involve a third party auth server that provides a valid token. I'm willing to share with the Firebase team a private repo with a small project connected to our dev environment that reproduces the problem.

**Comment by bojeil-google** [comment]
Were you already signed in before with that same user? The reason why I am asking is because if a user signs in successively with the same user, no state change is triggered.

**Comment by PierBover** [comment]
No, there was no user signed in.

**Comment by bojeil-google** [comment]
Is the call to signInWithCustomToken hanging? It should eventually fail with a network error.
There is no way state change would be affected by this. If signInWithCustomToken succeeds then the listener would trigger. The issue is the hanging request. Network requests on mobile devices will timeout after one minute. Please check the request times out. If the sign in attempt fails, the listener will never trigger which is expected.

**Comment by PierBover** [comment]
> It should eventually fail with a network error

It doesn't. I've waited for minutes.

> If signInWithCustomToken succeeds then the listener would trigger

It doesn't. The solution I've found is to detect the network status and when it's back up add a new listener.

> The issue is the hanging request. Network requests on mobile devices will timeout after one minute. Please check the request times out. If the sign in attempt fails, the listener will never trigger which is expected.

I'm testing this on a desktop machine, manually turning wifi on and off.

I know the connection is working because I need to get the token from our auth server before using `signInWithCustomToken()`. I've been able to reproduce this 100% of the times.

Like I said, I'm willing to create a reproducible case connected to our dev env on a private repo, if you are going to take a look at it.

**Comment by bojeil-google** [comment]
I can't reproduce this.
I tested on my laptop. I turned wifi off and then called signInWithCustomToken. It failed immediately with a network error. I turned it back on and tried again. It worked and the listener triggered. I even added a listener when it was offline and it fired afterwards when sign in completed.

Even if this hangs, there is no way the state listener is unsubscribed.

**Comment by PierBover** [comment]
Is there a way to check whether `onAuthStateChanged` has a listener or not?

**Comment by PierBover** [comment]
You were right. There is something else going on. Sorry for wasting your time.

**Comment by bojeil-google** [comment]
No worries. Thanks for following up and confirming.
