### ISSUE TITLE
FR:Firebase testing storage rules.

### ISSUE THREAD

**Issue by asliyilmaz** [firebase/firebase-js-sdk#1631]
@firebase/testing library has both loadFirestoreRules and loadDatabaseRules, however it does not have any loadig method for Storage rules.

**Comment by alwaysprep** [comment]
@asliyilmaz I also need to test my storage rules. Have you found any other way?

**Comment by rommelpe** [comment]
Thanks for taking time filing this FR, @asliyilmaz. We have an existing internal FR (b/139985932) of it. Additionally, be able to test the storage rules through the emulator similar to Firestore. However, I may not be able to provide you with any specifics as to when it will be released.

You may keep an eye out on our [release notes](https://firebase.google.com/support/release-notes/js) for any updates. We really appreciate the feedback, thanks again!

**Comment by pedrocarloto** [comment]
Are any news regarding this subject?

Thank you!

**Comment by hsubox76** [comment]
This was released earlier this year: https://firebase.google.com/docs/rules/unit-tests#test_sdk_methods
