### ISSUE TITLE
auth signInWithCustomToken does not respect http_proxy

### ISSUE THREAD

**Issue by romario333** [firebase/firebase-js-sdk#164]
### Describe your environment

  * Operating System version: MacOS 10.12.6 / Node.js 8.5.0
  * Npm package version: 4.3.1
  * Firebase Product: auth

### Describe the problem

`http_proxy` and `https_proxy` environment variable are not respected in `firebase.auth().signInWithCustomToken()`. 

### How to reproduce

In environment where http proxy is required to access the internet, set proxy variables and call `signInWithCustomToken()`. It will fail with:

```
Firebase token invalid: {"code":"auth/network-request-failed","message":"A network error (such as timeout, interrupted connection or unreachable host) has occurred."}
```

This is caused by `xmlhttprequest` package that does not support `http[s]_proxy` env vars (reported [here](https://github.com/driverdan/node-XMLHttpRequest/issues/149)). As a workaround I'm patching `xmlhttprequest` for now.

**Comment by jshcrowthe** [comment]
As this is an issue with the underlying dependency I'm going to close this. Let me know when the other issue is taken care of and I'd be happy to update our dependency.

**Comment by romario333** [comment]
@jshcrowthe [xmlhttprequest](https://github.com/driverdan/node-XMLHttpRequest) does not seem to be actively maintained, I don't think they will fix this issue. Not sure what is the best way forward here.
