### ISSUE TITLE
setBackgroundMessageHandler is not called in Firefox and shows a notification that opens the action specified in the Android section of the message

### ISSUE THREAD

**Issue by richardkazuomiller** [firebase/firebase-js-sdk#1640]
I noticed that notifications that are meant to just revalidate data in the background are appearing in Firefox. My service worker code is not being called and something is causing notifications to appear even though I've implemented a background message handler. Clicking the notification also opens a URL with the wrong part of the payload.

### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: Firefox 66.0.1
  * Firebase SDK version: 5.9.0
  * Firebase Product: Messaging

#### Steps to reproduce:

1. Add a background message handler that *does not* show a notification.
2. Subscribe to a topic in Firefox
3. Send a notification to the topic subscribed to in step 2 with an Android activity action.
4. Click the notification.
5. The browser opens a URL that looks like `https://mysite.com/com.mysite.app.ACTION`

##### Server code:

```javascript
const message = {...myMessage};
message.android = {
  notification: {
    title,
    body,
    clickAction: 'com.mysite.app.SOME_ACTION'
  }
};
await admin.messaging().send(message);
```

##### ServiceWorker code

```
const messaging = firebase.messaging();
messaging.setBackgroundMessageHandler(async function(payload) {
  console.log('[sw.js] Received background message ', payload);
  // this never gets called
});
```

**Comment by richardkazuomiller** [comment]
🤔

**Comment by richardkazuomiller** [comment]
I've disabled notifications for Firefox. Don't know what else to do. Any help would be appreciated.

**Comment by mmermerkaya** [comment]
About this line: `const message = {...myMessage};`, can you confirm that `myMessage` does not have a `notification` field? It would be even more helpful if you can share the whole payload.

**Comment by richardkazuomiller** [comment]
Here's the payload of my message, except with my actual app ID removed.

```
{
  "data": {
    "title": "2019-04-18T16:57:29.324Z",
    "body": "2019-04-18T16:57:29.324Z",
    "clickUrl": "nothing",
    "isRevalidateOnly": "true"
  },
  "condition": "'revalidate' in topics",
  "android": {
    "notification": {
      "title": "2019-04-18T16:57:29.324Z",
      "body": "2019-04-18T16:57:29.324Z",
      "clickAction": "my.app.id.NOTIFICATION_BROWSE"
    }
  },
  "apns": {
    "payload": {
      "aps": {
        "alert": "2019-04-18T16:57:29.324Z - 2019-04-18T16:57:29.324Z",
        "sound": "ping.aiff"
      },
      "clickUrl": "nothing"
    }
  }
}
```
There's no notification field on the message payload, but there is on the android field. I have a hunch that it is related because when I click the notification it opens the URL `https://{my_host}/my.app.id.NOTIFICATION_BROWSE`.

**Comment by richardkazuomiller** [comment]
🤔

**Comment by richardkazuomiller** [comment]
😢

**Comment by richardkazuomiller** [comment]
In Chrome, a lot of the time notifications don't appear at all when I show them using the background message handler. Could this be related?

**Comment by DellaBitta** [comment]
Hi @richardkazuomiller,

It's been some time since this reported issue. Could you confirm that this is still a problem? Thanks!

**Comment by richardkazuomiller** [comment]
Hi, since it's been four years and I've since moved on from this project I think I probably won't be able to dig into this anymore.

**Comment by DellaBitta** [comment]
Ok, thanks!
