### ISSUE TITLE
Persistency Issue

### ISSUE THREAD

**Issue by rulamon** [firebase/firebase-js-sdk#1648]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 v. 1803
  * Browser version: Chrome 73.0.3683.86
  * Firebase SDK version: 5.9.1
  * Firebase Product: auth, database

### [REQUIRED] Describe the problem

On trying to connect I get this error: 

Error: FIRESTORE (5.9.1) INTERNAL ASSERTION FAILED: Tried to allocate an already allocated query: Query(managers, filters: [email == {redacted}], limit: 1)
at fail (http://localhost:4200/vendor.js:139037:11)
at assert (http://localhost:4200/vendor.js:139045:9)
at http://localhost:4200/vendor.js:152192:17
at http://localhost:4200/vendor.js:147013:63
at PersistencePromise.push../node_modules/@firebase/firestore/dist/index.cjs.js.PersistencePromise.wrapUserFunction (http://localhost:4200/vendor.js:146999:26)
at PersistencePromise.push../node_modules/@firebase/firestore/dist/index.cjs.js.PersistencePromise.wrapSuccess (http://localhost:4200/vendor.js:147013:25)
at PersistencePromise._this.nextCallback (http://localhost:4200/vendor.js:146983:27)
at http://localhost:4200/vendor.js:146953:23
at http://localhost:4200/vendor.js:147013:63
at PersistencePromise.push../node_modules/@firebase/firestore/dist/index.cjs.js.PersistencePromise.wrapUserFunction (http://localhost:4200/vendor.js:146999:26)

When I disable persistence it doesn't occur.

**Comment by mikelehen** [comment]
@rulamon Thanks for the report.  Unfortunately this isn't enough information to isolate the issue.  Can you provide:

1. When you enable persistence, are you using the `experimentalTabSynchronization` option?
2. What does your code do prior to the error occurs?  What queries are you calling get() and/or onSnapshot() on?  Do you have multiple onSnapshot() listeners? When does the error occur?  Ideally if you can provide a small app that reproduces the problem, that will be by far the most helpful.
3. Can you enable logging via `firebase.firestore.setLogLevel('debug')` and send me the output leading up to the error, to michael@firebase.com?  Thanks!

**Comment by rulamon** [comment]
@mikelehen Hi, Sorry I didn't get around to adressing this in more detail, but I'm happy to tell you that for now the problem is gone after updating to 5.10.0

**Comment by mikelehen** [comment]
Okay, thanks.  Let us know if it reappears.

**Comment by rulamon** [comment]
Hi, the problem is back. Should I open a new issue for this?

**Comment by wilhuff** [comment]
It's fine to continue in this issue. However, we'll need the things @mikelehen was asking for, [above](https://github.com/firebase/firebase-js-sdk/issues/1648#issuecomment-478110128).

**Comment by rulamon** [comment]
Okay!
1. We were using the experimentalTabSynchronization option, but it doesn't make a difference if I turn it off.
2. I'll get back to you on this, I'm a newbie and will have to ask for help about it.
3. Should I still send the log output to michael@firebase.com?

**Comment by rsgowman** [comment]
Feel free to send the logs to me (rgowman@google.com) and I'll take a look.

**Comment by mikelehen** [comment]
@rulamon Thanks for the logs. We've been looking them over and it seems that unfortunately there's some corrupt data in your cache before the logs even start, which ultimately leads to this failure.

> index.esm.js:66 [2019-05-07T17:32:12.937Z]  @firebase/firestore: Firestore (5.10.0) [SimpleDb]: GET targetGlobal targetGlobalKey {"highestTargetId":0,"highestListenSequenceNumber":24,"lastRemoteSnapshotVersion":{"seconds":1557079888,"nanoseconds":894140000},"targetCount":0}

It shouldn't be possible to have targetCount and highestTargetId be 0 but have a non-zero lastRemoteSnapshotVersion and highestListenSequenceNumber. I believe that once you get into this state, the bug will reproduce all the time, with and without multi-tab enabled.

So to get to the bottom of this, we're going to need to figure out how this happened.  Do you recall what you did immediately prior to the error starting?  In particular:

1. Did you upgrade the version of Firestore you're using recently?
2. Have you ever directly modified the IndexedDb database by chance (e.g. in the chrome dev tools or programmatically accessing it or something)?

Unfortunately unless we can figure out what led to this corruption (and ideally a way to reproduce it), this is going to be difficult to solve.

**Comment by rulamon** [comment]
We had to turn off multi-tab persistence for a different reason, and re-enabled it again, and I haven't had this issue anymore, so closing this one.
