### ISSUE TITLE
Firebase Authentication- Facebook login does not return the user information on iOS

### ISSUE THREAD

**Issue by premtemp1** [firebase/firebase-js-sdk#1651]
Hello,

I have a cordova project and I am getting null user after authenticating with Facebook on IOS

  * Operating System version: mac os
  * Firebase SDK version: 8.1.2
  * Firebase Product: auth
  * Cordova version 8.1.2

Firebase Authentication- Facebook login does not return the user information

#### Steps to reproduce:

1:  redirected to login screen

2: Enter Email and password

3: Shown a screen to confirm my login with a continue button

4: I am then redirected back to the app after selecting the "continue" button

5: Result -- user = null

#### Relevant Code:
`var provider = new firebase.auth.FacebookAuthProvider();
$rootScope.user  = firebase.auth().currentUser;
if ($rootScope.user) {
  $rootScope.openCommonAlertModal({
  title: 'Sign in Success',
  details: "user log in as "+$rootScope.user.email
 }); 
 $scope.closeSignIn();
 $rootScope.$broadcast('signInEvent');
 } else {
   firebase.auth().signInWithRedirect(provider).then(function () {
    return firebase.auth().getRedirectResult();
 }).then(function (result) {
 var token = result.credential.accessToken;
 $rootScope.user = result.user;
 $rootScope.openCommonAlertModal({
    title: 'Sign in Success',
    details: "user log in as "+$rootScope.user.email
  }); 
  $scope.closeSignIn();
  $rootScope.$broadcast('signInEvent');
}).catch(function (error) {
 var errorCode = error.code;
 var errorMessage = error.message;

 $rootScope.openCommonAlertModal({
     title: 'Sign in failure',
      details: errorMessage + errorCode
  }); 
});
}`

**Comment by hsubox76** [comment]
Instead of using `getRedirectResult()`, can you use `firebase.auth().onAuthStateChanged()` instead?  You also wouldn't put it inside the `signInWithRedirect` callback but at the top level.  The callback inside `onAuthStateChanged` is the most reliable way to do something with user data right when a user has logged in. So

```
firebase.auth().signInWithRedirect(provider);
firebase.auth().onAuthStateChanged(function(user) {
  if (user) { // it will be null on first call or after user logs out
    // do stuff
  }
});

**Comment by rommelpe** [comment]
@premtemp1 are you still having issues here? You may also check out our get started guide for [`Facebook signInWithRedirect`](https://github.com/firebase/quickstart-js/blob/master/auth/facebook-redirect.html) workflow with `onAuthStateChanged` used.
