### ISSUE TITLE
Remove firebase.Promise from externs files.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-js-sdk#166]
https://github.com/firebase/firebase-js-sdk/pull/165#pullrequestreview-64452025 removes our firebase.Promise definition from the .d.ts file, but ideally we would also remove it from the externs.

Unfortunately, when I tried this (changing `firebsae.Promise<>` to `Promise<>` in all of our signatures, etc.), clutz generated `any` in the .d.ts file instead of `Promise<>`.  So I'm not sure if there's some magic needed to make `Promise<>` work in an externs file, or what.

**Comment by Feiyang1** [comment]
@mikelehen is it still an issue?

**Comment by mikelehen** [comment]
Uhhh...  I honestly don't really remember what this is about. We can consider it obsolete unless it comes up again for some reason. :-)
