### ISSUE TITLE
OAuthProvider type definition issue

### ISSUE THREAD

**Issue by malekpour** [firebase/firebase-js-sdk#1667]
* Operating System version: Windows 10
  * Browser version: Chrome 73
  * Firebase SDK version: 5.9.3
  * Firebase Product: auth

As per documentation and in javascript [code](/packages/auth/src/authcredential.js#L604), `OAuthProvider` requires `providerId` constructor parameter but typescript [typing](/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L184) does not accept any parameter.

**Comment by wti806** [comment]
Fix submitted: https://github.com/firebase/firebase-js-sdk/pull/1673
