### ISSUE TITLE
`firebase` package's index.d.ts file has been restored.

### ISSUE THREAD

**Issue by ogawa0071** [firebase/firebase-js-sdk#1671]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.3
  * Browser version: Google Chrome v73
  * VS Code version: v1.33.0
  * Firebase SDK version: v5.9.3
  * Firebase Product: Storage

### [REQUIRED] Describe the problem

The problem I reported and @Feiyang1 modified has been restored by PR #1622.

https://github.com/firebase/firebase-js-sdk/blob/5c8da05c43df1d7da697bb12f8c36c28afb64380/packages/firebase/index.d.ts#L5724

Issue: #1580
PR: #1585

Restored PR: #1622

**Comment by hsubox76** [comment]
Sorry, should be corrected with https://github.com/firebase/firebase-js-sdk/pull/1672

**Comment by ogawa0071** [comment]
@hsubox76 Thanks!!!
