### ISSUE TITLE
Firebase Error code 'cancelled'

### ISSUE THREAD

**Issue by ThomasKuhlmann** [firebase/firebase-js-sdk#1678]
### [REQUIRED] Describe your environment

  * Operating System version: os x 10.13
  * Browser version: Chrome 73
  * Firebase SDK version: 5.9.3
  * Firebase Product: auth, db, firestore, storage

### [REQUIRED] Describe the problem

Since a couple of days I keep encountering a firebase error in my Vue app. The error message is quite generic and I haven't been able to identify a pattern to it. But it keeps happening multiple times a day, sometimes without any visible impact on my application, and sometimes it prevents it from fully loading. 

```
backend.js:13767 Uncaught (in promise) Error {code: "cancelled", name: "FirebaseError", toString: ƒ}code: "cancelled"name: "FirebaseError"toString: ƒ ()__proto__: FirebaseError: Operation cancelled
    at new FirestoreError (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:352:28)
    at DelayedOperation.cancel (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:7582:34)
    at PersistentWriteStream.PersistentStream.cancelIdleCheck (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:14730:28)
    at PersistentWriteStream.PersistentStream.sendRequest (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:14711:14)
    at PersistentWriteStream.writeMutations (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:15041:14)
    at RemoteStore.addToWritePipeline (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:15970:30)
    at RemoteStore.eval (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:15937:30)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:117:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:98:53)
    at fulfilled (webpack-internal:///./node_modules/tslib/tslib.es6.js:88:58)
```

#### Steps to reproduce:
I can't even reproduce the error on my system, it's rather arbitrary.  Are there any options for more extended logs than what the console shows? I wouldn't even know which part of my code to share right now to start fixing this.

**Comment by Feiyang1** [comment]
The error shows it's coming from Firestore. Do you get the error from other SDKs as well, or just Firestore? Just want to clarify because you listed auth, db, firestore, storage as impacted products.

**Comment by mikelehen** [comment]
Strange.  We actually have a dummy catch() block specifically to avoid these canceled promises from logging these sorts of warnings: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/util/async_queue.ts#L89

But maybe somehow this is hitting a slightly different codepath or something.

You can turn on our debug logging with `firebase.firestore.setLogLevel('debug')` but I don't know if that'll help.  The `cancelIdleCheck()` codepath is very normal to be hitting...

In any case, if you can figure out how to reproduce this (or what caused it to start happening only recently?) then we can dig into it...

**Comment by ThomasKuhlmann** [comment]
@Feiyang1 so far the error I posted is the only one that keeps popping up. I listed the other SDKs since I wasn't sure if the firestore error is the cause or just a symptom of one of the other SDKs not working properly...

@mikelehen I'll try and see if there's anything more useful coming to light with the debug logging. But if it's just a normal cancelled promise, I'd assume that it wouldn't be disrupting my app, right? It's a tough one to troubleshoot since it's not recurring in any regular pattern, buy I'll see what the logs come up with...

**Comment by mikelehen** [comment]
@ThomasKuhlmann Correct.  This codepath should actually be getting hit pretty frequently (any time you do a write to Firestore) and have no negative effect whatsoever.

**Comment by ThomasKuhlmann** [comment]
Ok, the error keeps popping up it's been working fine for hours and suddenly it appeared again - here's what I can see when debug logging is turned on:

`index.esm.js?abfd:66 [2019-04-10T18:13:02.514Z]  @firebase/firestore: Firestore (5.9.3) [MemoryPersistence]: Starting transaction: Locally write mutations
index.esm.js?abfd:66 [2019-04-10T18:13:02.516Z]  @firebase/firestore: Firestore (5.9.3) [MemoryPersistence]: Starting transaction: notifyLocalViewChanges
index.esm.js?abfd:66 [2019-04-10T18:13:02.516Z]  @firebase/firestore: Firestore (5.9.3) [MemoryPersistence]: Starting transaction: Get next mutation batch
index.esm.js?abfd:66 [2019-04-10T18:13:02.517Z]  @firebase/firestore: Firestore (5.9.3) [Connection]: WebChannel sending: {"streamToken":"EAEZEGhCAoH0tbU=","writes":[{"update":{"name":"projects/test-56cd1/databases/(default)/documents/presence/XOiaPvYwOWTB17y3g5KpmoDwWii1","fields":{"state":{"stringValue":"online"}}}},{"transform":{"document":"projects/test-56cd1/databases/(default)/documents/presence/XOiaPvYwOWTB17y3g5KpmoDwWii1","fieldTransforms":[{"fieldPath":"lastSeen","setToServerValue":"REQUEST_TIME"}]},"currentDocument":{"exists":true}}]}
index.esm.js?abfd:66 [2019-04-10T18:13:02.518Z]  @firebase/firestore: Firestore (5.9.3) [MemoryPersistence]: Starting transaction: Get next mutation batch
`

then three time 

`backend.js:13767 Uncaught (in promise) Error {code: "cancelled", name: "FirebaseError", toString: ƒ}`

and afterwards

`index.esm.js?abfd:66 [2019-04-10T18:13:02.534Z]  @firebase/firestore: Firestore (5.9.3) [Connection]: WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[12]}}
index.esm.js?abfd:66 [2019-04-10T18:13:02.590Z]  @firebase/firestore: Firestore (5.9.3) [Connection]: WebChannel received: {"documentChange":{"document":{"name":"projects/test-56cd1/databases/(default)/documents/presence/XOiaPvYwOWTB17y3g5KpmoDwWii1","fields":{"lastSeen":{"timestampValue":"2019-04-10T18:13:00.499Z"},"state":{"stringValue":"offline"}},"createTime":"2019-02-21T13:10:29.712738Z","updateTime":"2019-04-10T18:13:00.793128Z"},"targetIds":[12]}}
index.esm.js?abfd:66 [2019-04-10T18:13:02.592Z]  @firebase/firestore: Firestore (5.9.3) [Connection]: WebChannel received: {"targetChange":{"targetIds":[12],"resumeToken":"CgkIi/i8qZDG4QI=","readTime":"2019-04-10T18:13:02.054411Z"}}
index.esm.js?abfd:66 [2019-04-10T18:13:02.594Z]  @firebase/firestore: Firestore (5.9.3) [Connection]: WebChannel received: {"documentChange":{"document":{"name":"projects/test-56cd1/databases/(default)/documents/presence/XOiaPvYwOWTB17y3g5KpmoDwWii1","fields":{"lastSeen":{"timestampValue":"2019-04-10T18:13:02.110Z"},"state":{"stringValue":"offline"}},"createTime":"2019-02-21T13:10:29.712738Z","updateTime":"2019-04-10T18:13:02.145445Z"},"targetIds":[12]}}`

----

I can't see anything obvious in the logs, but maybe any of that rings a bell for you?

**Comment by mikelehen** [comment]
@ThomasKuhlmann Strange. The logs look normal and indeed we should be hitting the cancellation codepath every time we send a mutation (write) to the backend, just as in your logs.  But I still don't know why the codepath is triggering the uncaught exception logging...

One thing that just popped out to me is that your original callstack includes:
```
    at RemoteStore.eval (webpack-internal:///./node_modules/@firebase/firestore/dist/index.cjs.js:15937:30)
```

But there's no eval function in RemoteStore (https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/remote/remote_store.ts#L80) and when I open `@firebase/firestore/dist/index.cjs.js`, eval doesn't appear anywhere in the file.

This has me wondering if there's some kind of funky code transformation in your build setup or something...?

**Comment by ThomasKuhlmann** [comment]
@mikelehen My webpack config is purely out of the box with whatever comes with Vue, so no custom transformation I can think of.

I've also now disabled pretty much everything in my app (no components are being loaded except the minimum for initialisation and what's needed for the initial query to firebase) and still get the error:

`[2019-04-10T18:51:01.468Z]  @firebase/firestore: Firestore (5.9.3) [MemoryPersistence]: Starting transaction: notifyLocalViewChanges
backend.js:13767 Uncaught (in promise) Error {code: "cancelled", name: "FirebaseError", toString: ƒ}
(anonymous) @ backend.js:13767
Promise.then (async)
(anonymous) @ backend.js:13764
_clone @ backend.js:13763
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
_clone @ backend.js:13832
clone @ backend.js:13867
addMutation @ backend.js:14522
onMutation @ backend.js:14277
emit @ VM43984:1
_replayBuffer @ VM43984:1
on @ VM43984:1
VuexBackend @ backend.js:14255
initVuexBackend @ backend.js:14727
connect @ backend.js:1556
initBackend @ backend.js:1466
handshake @ backend.js:2589
postMessage (async)
o @ proxy.js:1
126 @ proxy.js:1
t @ proxy.js:1
(anonymous) @ proxy.js:1
(anonymous) @ proxy.js:1
index.esm.js?abfd:66 [2019-04-10T18:51:01.520Z]  @firebase/firestore: Firestore (5.9.3) [Connection]: WebChannel received: {"targetChange":{"resumeToken":"CgkIwvCv6JjG4QI=","readTime":"2019-04-10T18:51:01.444674Z"}}`

Any more ideas? I'm a little bit at the end of my troubleshooting skills...

**Comment by mikelehen** [comment]
Sorry, I don't know.  I just tried a simple app with 5.9.3 to make sure I don't see the error, and I do not.  If you can provide a repro (ideally without Vue), I can see if I can debug it...  But at the same time, in theory the log message should be benign so if it's not causing problems, you could also potentially just ignore it.

**Comment by ThomasKuhlmann** [comment]
I found the solution. It had nothing to do with firebase in my case - The latest version of the vue devtools (something like 5.0.9 I think) seems to have caused a memory leak which impacted not just firebase (but the firebase errors where the first to pop up). Switching back to an older beta version of vue-devtools for Chrome solved the problem for me. 

Here's the older version in the chrome webstore:
[https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en](url)

Thanks for your help @mikelehen and @Feiyang1 !
