### ISSUE TITLE
PhoneNumber auth on Android: error auth/network-request-failed

### ISSUE THREAD

**Issue by derwaldgeist** [firebase/firebase-js-sdk#168]
* Operating System version: Cordova/Android
  * Firebase SDK version: 4.4.0
  * Firebase Product: phone number auth

After trying the UI widget, which already reported network errors on Android, I tried to implement the phone number handshake using the low-level SDK API.

When I try to call

`firebase.auth().signInWithPhoneNumber()`

this error is thrown:

```
error: O
code: "auth/network-request-failed"
message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
```

This only happens on Android. In the browser and on iOS everything works as expected.

The problem seems to be related to the recaptcha, since it doesn't show up as well.

I added `*.googleapis.com/*`, `*.google.com/recaptcha/*`, `*.google.com/js/*` and `*.gstatic.com/*` to the whitelist of the app, for both http and https. But still the problem persists. There are no other error messages in the console.

**Comment by derwaldgeist** [comment]
BTW: I came to Firebase because of the Digits shutdown. I guess all Cordova apps relying on Digits are affected by this.

**Comment by bojeil-google** [comment]
You already opened several issues for the same problem. You already posted that this was related to the navigator.onLine problem on another repo.

**Comment by derwaldgeist** [comment]
Yep, I posted this in the UI repo, but closed it there, as the problem actually is in the core SDK.

I got this fixed by adding `cordova-plugin-network-information` to my Cordova app, but that's not a nice work-around. It would be better if Firebase used a more reliable mechanism than navigator.onLine.
