### ISSUE TITLE
FR: Firestore Offline Check

### ISSUE THREAD

**Issue by nVitius** [firebase/firebase-js-sdk#1680]
* Firebase SDK version: 5.9.0
  * Firebase Product: firestore

I am working on a VueJS application that uses Firestore for its persistence layer. It is important to me that a user can access the app and their data offline. In conjunction with Firebase, I am using a Vue plugin (https://github.com/mesqueeb/vuex-easy-firestore/) in order to streamline the access to Firestore in my app. Essentially, it is syncing the data from Firestore using `onSnapshot` to a data store that my app interfaces with.

Whenever I insert a doc into my store, I add it to a queue which is processed with a debounce. The queue is created into a batch using `Firebase.firestore().batch()`. I believe this is where problems start to happen.

On a page refresh, I have to receive all the `docChanges` from my `onSnapshot` and insert them into my data store. This works fine whenever the client is online. In offline mode, however, I am unable to differentiate between documents that are being added from the cache, that is documents that were modified locally before the page refresh and in offline mode, and documents that I may have added using `batch.commit()`.

A quick example:

```
dbRef.onSnapshot(snap => {
  console.log(snap.metadata.hasPendingWrites)
  snap.docChanges().forEach(change => {
    console.log(change.type)
  }
})
```

For any documents added in offline mode, when the page is refreshed there will be a snapshot generated.
In that snapshot, `snap.metadata.hasPendingWrites` will be `true` and `change.type` will be `local`
Also, for any documents added with a `batch.commit()` a snapshot is generated.
In that snapshot, `snap.metadata.hasPendingWrites` will be `true` and `change.type` will be `local`

I would like to add steps in my code to, when the client is offline and outside of the `onSnapshot`, add all documents in the offline database to my store. And this is the reason I made this issue: there is currently no way, outside of the promise returned when calling `firestore().enablePersistence()`, to tell if the Firestore client has offline mode enabled.

Right now, I am doing this:
```
if (Firebase.firestore()._firestoreClient.persistence &&
  Firebase.firestore()._firestoreClient.persistence.constructor.name === 'IndexedDbPersistence' &&
  !navigator.onLine
) {
  dispatch('fetchAndAdd')
}
```

I don't think this is very reliable, as the `_firestoreClient.persistence` is set asynchronously. Also, it doesn't feel... right.

Since this code is all in a third-party plugin, it isn't responsible itself for enabling persistence. So I cannot use the result of `firestore().enablePersistence()`. It would be great if something was exposed on the Firestore API so we could verify if the client is operating with offline persistence enabled.

**Comment by var-const** [comment]
I'm not sure I fully understand your use case. Can you please provide some additional information?

> In offline mode, however, I am unable to differentiate between documents that are being added from the cache, that is documents that were modified locally before the page refresh and in offline mode, and documents that I may have added using batch.commit().

Why is it necessary to distinguish between local documents and documents written to the server? What are you trying to achieve?

> I would like to add steps in my code to, when the client is offline and outside of the onSnapshot, add all documents in the offline database to my store. 

If local persistence is disabled, Firestore would use in-memory persistence; there is no case when Firestore has persistence entirely disabled. I might be missing some context, but it's not clear to me why you need to check specifically for local persistence when the app is offline -- would in-memory persistence be sufficient?

> Since this code is all in a third-party plugin, it isn't responsible itself for enabling persistence.

Can the plugin add a wrapper over `firestore().enablePersistence`, or an API call so that the app using the plugin can provide that information manually?
