### ISSUE TITLE
firebase.app().delete() throw error 

### ISSUE THREAD

**Issue by mohshraim** [firebase/firebase-js-sdk#1683]
### [REQUIRED] Describe your environment

  * Operating System version: Mac & Windows
  * Browser version: chrome and safari
  * Firebase SDK version: 5.9.3
  * Firebase Product:  firebase APP

### [REQUIRED] Describe the problem

`firebase.app().delete() ` was working before but now throw error as follow

![Screen Shot 2019-04-10 at 4 23 36 PM](https://user-images.githubusercontent.com/16401732/55882596-77452200-5bad-11e9-9365-7d8060d4a7f0.png)

Thanks 
Moh'd Shraim

**Comment by hsubox76** [comment]
Hi, quick question: when you say "was working before", did you have a previous version of Firebase where this code worked, or was it working before you made a change to your code?

The reason I'm asking is that I do see this error, but it occurs in every version of Firebase as far back as I've gone.  The service that seems to be throwing the error is Functions, so is it possible that you started seeing this error after adding Functions to your app?

It's definitely a bug, I'm just trying to make sure if we need to revert something we broke or add something that was never there.  Thanks!

**Comment by mohshraim** [comment]
Hello @hsubox76 

What i can confirm it was working on 5.0.4 and some after that... 
Which i started using it since this comment https://github.com/firebase/firebase-js-sdk/issues/947#issuecomment-398782452

Thanks

**Comment by hsubox76** [comment]
I think I found the problem and the fix should go out in the next release, but if I'm correct it shouldn't have ever worked in any previous versions either, as long as the app was bringing in the `firebase.functions` component.  I was finding the same error message when I downgraded to 5.0.4. 
 In any case, try out the next release (Thursday)? and see if it fixes things for you.

**Comment by mohshraim** [comment]
Thanks 
Will feed you back

**Comment by mohshraim** [comment]
solved 
Thanks
