### ISSUE TITLE
FR: Upgrade grpc for firestore when 1.20.0 is out and stable

### ISSUE THREAD

**Issue by Djiit** [firebase/firebase-js-sdk#1686]
Hello,

It would be nice to update grpc (for firestore) to a newer version (*1.20.0*) with prebuilt binaries for the latest version of electron (yes, this is a re-edition of #1444 ;-))

**Comment by var-const** [comment]
Thanks for the feature request! I will look into doing the upgrade.

**Comment by mikelehen** [comment]
FWIW- It looks like 1.20.0 isn't a stable release yet?  1.19.0 is still tagged "latest" https://www.npmjs.com/package/grpc

**Comment by Djiit** [comment]
Indeed it's still a -pre3. i'll change the title to reflect that

**Comment by Djiit** [comment]
Hey, 1.20.0 is the new latest version now ;)

**Comment by Djiit** [comment]
It has been addressed by https://github.com/firebase/firebase-js-sdk/commit/d09bee6fbc3f8c4752989f821db1f4ce6f536504; should be release soon I guess.

**Comment by wilhuff** [comment]
That’s correct. In general this should happen mostly automatically.
