### ISSUE TITLE
FR: [Database] Allow access to ".settings" path from Admin SDK

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-js-sdk#1689]
Are you in the right place? Yes.

### [REQUIRED] Describe your environment

  * Operating System version: Linux 5.0.7
  * Browser version: n/a
  * Firebase SDK version: 5.9.4
  * Firebase Product: database

### [REQUIRED] Describe the problem
When using the Admin SDK, it's not possible to read from or write to the special root path `.settings`.

#### Use case
Being able to read and modify the database security rules (`.settings/rules`) directly.

#### Workaround
I'm currently calling the REST API to read and write the database rules, obtaining the admin token from `admin.app().INTERNAL.getToken()` (which I don't like doing, since it's not part of the SDK's public API).

#### Steps to reproduce:
`Error: Reference.child failed: First argument was an invalid path = ".settings/rules". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"`

#### Relevant Code:
```ts
import * as admin from 'firebase-admin';

admin
  .database()
  .ref('.settings/rules')
  .once('value')
  .then(snap => console.log(snap.val()));
```

**Comment by jsayol** [comment]
This should be a pretty straight-forward change by adding a check for the special `.settings` root path [here](https://github.com/firebase/firebase-js-sdk/blob/eccfbe2398a80df162494a5873c52d48ca34aba7/packages/database/src/core/util/validation.ts#L73-L80) (just like with `.info`) but only in case of `CONSTANTS.NODE_ADMIN === true`.

I'll gladly send a PR if you're OK with this.

**Comment by mikelehen** [comment]
Thanks for the feedback!  Unfortunately it's not going to be that easy. 😢  `.settings/rules.json` is actually a special REST endpoint and isn't available via the WebSocket-based realtime transport that the SDK uses for normal data access.  So this would require special effort to perform the appropriate REST requests which would be outside the scope of what we'd consider adding to the JS SDK at this time. Sorry!

That said, it does seem very reasonable for the Firebase Admin SDK to make it easy to read / write your security rules.  If you're having to call internal APIs, that's not ideal.  @hiranya911 may be able to comment on whether there's a better way to get a token from the admin SDK...  or maybe he'd be open to adding specific APIs for reading/writing rules to https://github.com/firebase/firebase-admin-node.

**Comment by jsayol** [comment]
Hey Michael, thanks for the insight. I thought it was strange that this hadn't been taken into account already, but figured it might have been an oversight. I should have known better :smile: 

In this case I'll head over to the Admin SDK repo and see if they're OK with adding a couple of methods to get and set the database rules.

P.S.: There's probably better, officially-sanctioned ways to obtain an admin token to deal with the REST API. But since I was running this code inside a Cloud Function and already didn't need to deal with service accounts and all that, I figured the fastest way to get up and running was by calling the internal `getToken()` method. Just wanted to clarify in case anyone else stumbles upon this in the future.
