### ISSUE TITLE
signInWith* functions have incompletely typed return types

### ISSUE THREAD

**Issue by Airblader** [firebase/firebase-js-sdk#169]
### Environment

  * Operating System version: Manjaro Linux
  * Firebase SDK version: 4.4.0
  * Firebase Product: auth

### Describe the problem

The `signIn*` methods are typed to return `firebase.Promise<any>`, but the Firebase documentation actually states that `firebase.Promise<firebase.User>` is returned. The typings of the SDK should reflect this.

**Comment by Airblader** [comment]
Oddly, it looks like `signInAnonymously` does return `firebase.Promise<firebase.User>`, but things like `signInWithPopup` actually return a promise of an object that _contains_ `user: firebase.User`. Am I missing something here?

**Comment by Airblader** [comment]
I wasn't aware they're generated, but according to the source *.js files' documentation the returned promises are `firebase.User` (anonymous, email) or `firebase.auth.UserCredential` (signInWithPopup) depending on the function.

**Comment by Feiyang1** [comment]
This has been addressed by https://github.com/firebase/firebase-js-sdk/pull/870
