### ISSUE TITLE
FR: (firestore.FieldValue) make _operand & _elements a public property

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#1698]
I have a wrapper around the Firebase JS SDK where I am gathering a bunch of modifications over 1000ms and then commit them all at once with a `batch`.

When I have more than one `FieldValue.increment(n)` I am currently merging them like so:

```js
if (
  originVal instanceof Firebase.firestore.FieldValue &&
  originVal._methodName === 'FieldValue.increment' &&
  newVal instanceof Firebase.firestore.FieldValue &&
  newVal._methodName === 'FieldValue.increment'
) {
  newVal._operand = originVal._operand + newVal._operand
  patchValue = newVal
}
```

However, this `_operand` property starts with `_` which makes me feel like it's more of a "private" property and shouldn't be directly modified like that.

I also really need to prevent this field from being renamed to something else on the Firebase SDK side, because it would break my library.

Is this the best way to combine two `FieldValue.increment(n)` on the same field?

### My request
Please make `_operand` and `_methodName` public & documented properties in the [reference docs](https://firebase.google.com/docs/reference/node/firebase.firestore.FieldValue).

Same goes for `_elements` of the `'FieldValue.arrayUnion'`.

**Comment by var-const** [comment]
Thanks for the feature request. Can I ask you for some additional information? It seems like a potential solution would be to simply store both increments while you're buffering the modifications, and then commit them both in the batch. Is there some reason why the wrapper needs to merge the increments into a single `FieldValue`?

**Comment by mesqueeb** [comment]
I have my increment and arrayUnion (etc) functions in a wrapper function that assigns the updates to my my queue and converts the user input into the actual FieldValue. 

One work around would be only convert it unto a FieldValue when the queue is executed and the batch update is made. 

I’d have to refactor a bit but I guess it’s better I opt for that instead?

**Comment by mikelehen** [comment]
Yes, I think that would be a great approach.  The `FieldValue` objects aren't designed to be stored and mutated over time, and you are right that fields with `_` are considered private and could change between releases.  So only creating the `FieldValue` object when you make the batch update would be ideal.
