### ISSUE TITLE
2FA authentication allowed in firebase..?

### ISSUE THREAD

**Issue by pavan-nw** [firebase/firebase-js-sdk#170]
do we have support to enable 2FA authentication for my express js app..? As per my exploration i did not get anything related to 2FA. Please help us in achieving this,..

**Comment by bojeil-google** [comment]
We don't currently support 2FA authentication.
You could try to use a combination of existing APIs (sign-in with email/pass and phone auth) along with custom Auth to build your own 2FA flow. Though, it would be extremely messy and have limitations.

**Comment by pavan-nw** [comment]
Yes thanks you.. i tried using email and the phone auth using otp. it worked but i need to handle multiple things to achieve this 2FA authentication. thats fine for now.
