### ISSUE TITLE
Problem with onDisconnect() and token not refreshing in inactive tabs

### ISSUE THREAD

**Issue by marszall87** [firebase/firebase-js-sdk#174]
* Operating System version: MacOS 10.12.6, Chrome 62.0.3202.29
  * Firebase SDK version: 4.4.0
  * Firebase Product: auth

### The problem

We're using `onDisconnect()` function to remove inactive user sessions and we noticed that sometimes the session is still there, even though the user disconnected. After some debugging we came to a conclusion that it's caused by expired tokens - `onDisconnect()` can't remove a node if it's not authenticated.

If I understand correctly the token is normally automatically refreshed every ~55 minutes (it's valid for one hour, so there is a 5 minute buffer). However, it seems that Page Visibility API is used to disable this behavior when the tab is inactive. So after the tab or the browser window is inactive for more than an hour and you switch back to it, the token is expired, Firebase client reconnects and gets new token - in which case it's possible to somehow recover from failed `onDisconnect()`. But when you never go back to the tab and just close the browser there's no way to properly remove the data.

I can think of two workarounds for this. One would be to manually refresh the token, even if the tab is inactive. The other would be to go offline when the tab is inactive, before the token expires. However I think that it should be done in the SDK itself, not in the user code, or at very least this behavior should be somehow documented.

#### Steps to reproduce:

Check out this fiddle:
https://jsfiddle.net/625dLa9j/

When you add some value, close the tab, and then reopen it, the value should be removed. But when you leave the tab in background for more than 1h, the value will still be there.

**Comment by bojeil-google** [comment]
We can't refresh tokens when the tab is inactive. That would be quite inefficient, expensive and detrimental to some users. If you need to run stuff in the background, you will need to do it manually.

**Comment by vincentwoo** [comment]
I don't think that's a very satisfactory reply to @marszall87's issue. Having a reliable presence system seems very core to the Firebase experience.

**Comment by bojeil-google** [comment]
The Auth team has no plans to proactive refresh tokens when a tab is not visible. My answer is pretty clear. I have currently 50 tabs open on my workstation. Do you really think it is a good idea to proactively refresh tokens on every tab? Anyway, we provide APIs for developers to refresh on their own. We can't make this the default behavior.

**Comment by vincentwoo** [comment]
Uh, okay, one, that was rude, two, what's the user story for people who have auth'd user sessions but still want reliable data removal via `onDisconnect`? Sure, you can reject OP's suggestion for a fix, but I'd at least expect some guidance given.

**Comment by bojeil-google** [comment]
You can get the expiration of the token at any time. It is in the `exp` field in the token. Based on that you can implement your own token refresh logic. To force a token refresh, call `firebase.auth().currentUser.getToken(true)`. You can run your logic even when the app is not visible.

**Comment by vincentwoo** [comment]
This probably bears mention in the onDisconnect docs:
https://firebase.google.com/docs/reference/js/firebase.database.OnDisconnect

**Comment by bojeil-google** [comment]
Hey @marszall87 and @vincentwoo, to further clarify, we try to minimize activity in the background/when the app is not visible for multiple reasons:
1. For mobile browsers, there are costs on battery life and network calls which will add up to data usage. This is quite undesirable for majority of users.
2. On desktop browsers, it is common to open dozens of tabs and keep them open indefinitely (I fall into that category) and have tabs of the same web app sending these requests is inefficient, negatively affect performance and will basically DDoS our servers.

The Auth team can't apply this as a default as the downsides are far worse than the upsides.

**Comment by tomlarkworthy** [comment]
Tom from RT database team, I don't think this is an auth problem but maybe it is a database problem. We check the token twice when 1. the onDisconnect is enqueued and 2. when the onDsiconnect is applied. Maybe 2 is not necessary given the connection has been authenticated already and the expected use of the feature. It does mean revoking the auth key won't prevent pending onDisconnects to be stopped, but it would stop new onDisconnects from being enqueued. So I personally think that is enough security wise but I would need to raise this with security as it would a novel policy for handling expiring tokens.

**Comment by bojeil-google** [comment]
Re-opening as this could be solved from the Database side.

**Comment by marszall87** [comment]
Thanks for you reply @bojeil-google . I understand that it's important to minimize the activity in background tabs, so what about my second suggestion, i.e. going offline (disconnecting from database) just before the token expires? It should solve the problem as onDisconnect will fire with valid token.

**Comment by mikelehen** [comment]
Thanks for the feedback. This is an interesting suggestion, though not something we could change directly since it may break existing apps.  If we were to do this, it would have to be behind an option or something.  So for now, I think you probably need to implement this yourself (call `firebase.database().goOffline()` when the tab goes to the background). But we'll keep this feedback in mind.

**Comment by itssidhere** [comment]
Any updates on this for a flutter app , how should we handle this?

**Comment by coluccini** [comment]
I totally get the obvious need to minimize activity in the background. But the explanation "it is common to open dozens of tabs and keep them open indefinitely" exactly what makes this issue relevant? If we know most people will keep their tabs opened longer than an hour, we can't rely on `onDisconnet()` method at all.

**Comment by Cubxity** [comment]
I rely on onDisconnect in my app to manage user's connections and session data and it seems like I am affected by this issue as well. Are there any updates on this issue?

**Comment by andrealeo83** [comment]
How a developer can build a presence module with this issue? onDisconnect doesn't work!!!

**Comment by anrice** [comment]
We ran into the same issue.
Why is this unreliable behaviour for onDisconnect not mentioned in the firebase docs? 
https://firebase.google.com/docs/reference/js/firebase.database.OnDisconnect

That's too bad Firebase / RTDB doesn't support building reliable presence.

**Comment by coluccini** [comment]
The solution I've found was to set the user as disconnected after 10 minutes after the tab went to background.

PS: totally agree about the needs to mentions this on the docs…

**Comment by Cubxity** [comment]
> The solution I've found was to set the user as disconnected after 10 minutes after the tab went to background.
> 
> PS: totally agree about the needs to mentions this on the docs…

Do you have a snippet that you can share?

**Comment by coluccini** [comment]
Even this it's something that would be probably pretty coupled to your app logic, the basic logic would be something like this:


```javascript
// A function for setting user connected status base on the window visibility

let isConnectedTimeout = null;
const onWindowVisibilityChange = () => {
  // On tab focus, mark user as online
  if (document.hasFocus()) {
    mark_user_as_ONLINE();
    clearTimeout(isConnectedTimeout);
  } else {
    // On tab blur, mark user as idle
    mark_user_as_IDLE();
    // If remaings idle for more that 10 minutes, set it as offline
    isConnectedTimeout = setTimeout(() => {
      mark_user_as_OFFLINE();
    }, 60000);
  }
}

// Attaching that function to the corresponding window events
window.addEventListener('focus', onWindowVisibilityChange);
window.addEventListener('blur', onWindowVisibilityChange);
```

**Comment by tomlarkworthy** [comment]
Hi I left google some years ago (2018), I am actually using OnDisconnect now and hit this bug, and I am super sad this has not been fixed as it used to be quite a distinguishing feature and something not available in Firestore.

**Comment by r0hin** [comment]
> Even this it's something that would be probably pretty coupled to your app logic, the basic logic would be something like this:
> 
> ```js
> // A function for setting user connected status base on the window visibility
> 
> let isConnectedTimeout = null;
> const onWindowVisibilityChange = () => {
>   // On tab focus, mark user as online
>   if (document.hasFocus()) {
>     mark_user_as_ONLINE();
>     clearTimeout(isConnectedTimeout);
>   } else {
>     // On tab blur, mark user as idle
>     mark_user_as_IDLE();
>     // If remaings idle for more that 10 minutes, set it as offline
>     isConnectedTimeout = setTimeout(() => {
>       mark_user_as_OFFLINE();
>     }, 60000);
>   }
> }
> 
> // Attaching that function to the corresponding window events
> window.addEventListener('focus', onWindowVisibilityChange);
> window.addEventListener('blur', onWindowVisibilityChange);
> ```

Might be worth increasing timeout to one hour (or 55 minutes) so that people aren't marked as offline whilst still being idle. Past the hour, I suppose, is the technical limit so far as discussed.

**Comment by jdboris** [comment]
I haven't checked the exact conditions, but the onDisconnect handlers aren't working in my app either, and the window blur workaround doesn't seem to work for all my users. I think it's because some browsers suspend tabs/apps when they're minimized.

What's the logic behind requiring the client to have a valid token when the onDisconnect handler is called? Is it not enough that they had one when the handler was created?

**Comment by lepatryk** [comment]
This is long overdue, I am really sorry for the delay, but we finally figured out a decent mitigation on the server side and pushed it out to production last week. With this change, the server will drop connection as soon as it notices the credentials are about to expire and runs onDisconnect handlers. I tested it this morning and the issue seems to be fixed.

The solution is not ideal, because our SDKs will try to reconnect almost immediately, get a new token and set up all the onDisconnect handlers again even if the tab is in the background. That's way more work and resources used than a simple token refresh. We'll optimize the SDK behavior as a follow up. 

For now I'm closing this issue as fixed. Thank you all for your patience, and again apologies for the delay.

**Comment by tomlarkworthy** [comment]
@lepatryk u star!

**Comment by tomlarkworthy** [comment]
I have been testing it pretty hard with https://observablehq.com/@tomlarkworthy/multiplayer-cursors which was always prone to zombies. So far so good! I see the client re-quueing an ondisconnect every time it reconnects when the browser regains focus, so it seems to work. Been leaving it on and off for the last 48h... always hard to tell if something is properly fixed but it definitely seems like it. w00t

**Comment by maneesht** [comment]
I will be closing this as it has been resolved. Thanks everyone for your patience.
