### ISSUE TITLE
can not install for electron 5.0

### ISSUE THREAD

**Issue by zkiiito** [firebase/firebase-js-sdk#1749]
### [REQUIRED] Describe your environment

  * Operating System version: ubuntu 18.04
  * Browser version: Electron 5.0
  * Firebase SDK version: 5.11.1
  * Firebase Product: firestore

#### Steps to reproduce:

npm init -f
npm install firebase@5
npm install electron@5
npm rebuild --target=5.0.0 --runtime=electron --dist-url=https://atom.io/download/electron

build error occurs

#### Suggested solution
grpc started supporting electron 5 in 1.20.3, dependency should be upgraded.

**Comment by arjunyel** [comment]
Fix next week https://github.com/firebase/firebase-js-sdk/issues/1738#issuecomment-488936229

**Comment by Feiyang1** [comment]
It will be fixed later this week. For now, you can use `npm install firebase@canary`

**Comment by Feiyang1** [comment]
Please upgrade to 6.0.2 to resolve the issue.

**Comment by zkiiito** [comment]
thanks, works like a charm!
