### ISSUE TITLE
TypeError: firebase_app__WEBPACK_IMPORTED_MODULE_4__.storage is not a function

### ISSUE THREAD

**Issue by amrfarid140** [firebase/firebase-js-sdk#1753]
### [REQUIRED] Describe your environment

  * Operating System version: macOS v10.14.4
  * Browser version: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
  * Firebase SDK version: 5.9.2
  * Firebase Product: Storage

### [REQUIRED] Describe the problem
Unable to use storage API due to the following error: 

`TypeError: firebase_app__WEBPACK_IMPORTED_MODULE_4__.storage is not a function`

#### Steps to reproduce:

1. Initialise Firebase application using the described method in the docs.
2. Try to follow the steps mentioned [here](https://firebase.google.com/docs/storage/web/upload-files?authuser=0#upload_from_a_blob_or_file) to upload a file 
#### Relevant Code:
in `index.ts`
```javascript
import * as firebase from "firebase/app";
import 'firebase/auth';
import 'firebase/storage';
import 'firebase/firestore';
firebase.initializeApp({
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.REACT_APP_FIREBASE_DATABASE_URL,
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID
});
```

The error happens in another file where I do the following

```javascript
import * as firebase from "firebase/app";
import 'firebase/storage';
import 'firebase/firestore';

export default class CandidateRepository {

private readonly copDocument: firebase.firestore.DocumentReference;
private readonly copStorage:firebase.storage.Reference ;

constructor(c: C) {
        this.copDocument =  firebase.firestore().collection("c").doc(c); // this works
        this.copStorage = firebase.storage().ref().child(c); // this fails
   }
}
```

**Comment by hsubox76** [comment]
I'm not able to reproduce this using a test mimimal webpack app where I copied the imports and calls you've made in the code above.  Is it possible for you to create a minimal reproduction of this (your basic build setup and one code file, that still results in this failure) and upload it to Github or somewhere?  Perhaps Firebase is interacting oddly with a Webpack loader or other parts of your setup, and it's hard to see without the full picture.

I also notice you're using a slightly older version of Firebase, does upgrading to the latest version help?  Or alternatively, downgrading to an earlier version?

**Comment by amrfarid140** [comment]
Yes, upgrading to `5.11.1` solved my issue. Still not sure what caused though.

Happy to close this issue for now.

**Comment by guoyunhe** [comment]
I also get this error and found it is because the order I import things in the React project.

If you import `App.jsx` before `initializeFirebase.js`, then `firebase.storage()` is used before it get initialized.

Correct order is to:

```js
import './initializedFirebase'

import App from './App'
import ...
import ...
```
Then you are fine.
