### ISSUE TITLE
6.x ie11 pollyfills

### ISSUE THREAD

**Issue by cekvenich** [firebase/firebase-js-sdk#1769]
Release notes for 6.x say ie11 is no longer supported:
- https://firebase.google.com/support/releases

It states that 'core' polyfills are needed, but not what ones. 
It suggests local bundles be built but we can't do that.
So what ones do I need to load from CDN?
For example https://cdn.polyfill.io/v3/url-builder/

What should I select? 

What specific polyfills are needed and how specifically do I load them from the CDN?

**Comment by Feiyang1** [comment]
You should select ES2015, ES2016 and ES2017.
If you use Cloud Functions or Performance, you should also include fetch.

**Comment by cekvenich** [comment]
THANK YOU!
