### ISSUE TITLE
I can't get setPersistence to work

### ISSUE THREAD

**Issue by richtera** [firebase/firebase-js-sdk#177]
Trying to call firebase.auth().setPersistence as per docs:
https://firebase.google.com/docs/auth/web/auth-state-persistence
but the method is not there in the latest npm module.

### [REQUIRED] Describe your environment

  * Operating System version: _Mac OS X 10.12.6
  * Firebase SDK version: _4.1.3
  * Firebase Product: _auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
Can't call setPersistence API to limit storage of credentials for app.

#### Relevant Code:
The API isn't there so it throws an exception.
```javascript
Uncaught TypeError: firebase.auth(...).setPersistence is not a function
```

http://jsbin.com/rinilu/edit?js,console

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by richtera** [comment]
Looks like 4.4.0 might fix it. Checking....

**Comment by bojeil-google** [comment]
This feature was added in version 4.2.0: https://firebase.google.com/support/release-notes/js#4.2.0

**Comment by jshcrowthe** [comment]
@richtera take a look at the latest version and feel free to re-open with more info if you still can repro the issue.

**Comment by richtera** [comment]
Sorry I meant to close it. I did an npm install firebase but forgot that install no longer does upgrades. So I thought I was running latest but wasn't.

**Comment by jshcrowthe** [comment]
@richtera no worries 😄  thanks for your help!
