### ISSUE TITLE
Crash if cookies are disabled

### ISSUE THREAD

**Issue by neelance** [firebase/firebase-js-sdk#1774]
The line
https://github.com/firebase/firebase-js-sdk/blob/6064f2744bc01b00fa771ffd08e5309c89110f84/packages/performance/src/services/api_service.ts#L60
crashes with `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.` if cookies are disabled (Chrome 74.0.3729.131).

**Comment by Feiyang1** [comment]
Thanks for reporting it! Very interesting that disabling cookie disables localStorage access.
I can see a couple of options:
1.  wrap the code with try catch and falls back to memory 
2. use indexeddb instead

I will take it back to the team and see what we will do.

**Comment by mmermerkaya** [comment]
At least in Chrome, if cookies are disabled IndexedDB doesn't work either. Disabling cookies blocks all client storage features AFAIK.
