### ISSUE TITLE
auth().onAuthStateChanged() throws TypeError after clearing LocalStorage

### ISSUE THREAD

**Issue by mnlfischer** [firebase/firebase-js-sdk#178]
* Operating System version: win10 1703
  * Firebase SDK version: 4.4.0
  * Firebase Product: auth

#### Steps to reproduce:
I'm not sure if this is the expected behavior but after clearing the LocalStorage, I got an TypeError 'indexOf' of null. I expected null in case of missing LocalStorage user element.
#### Relevant Code:
```typescript
@Injectable()
export class AuthService {
  isAuthenticated: boolean;

  constructor() {
    firebase.auth().onAuthStateChanged((user: firebase.User) => {
      if (user) {
        this.isAuthenticated = true;
      } else {
        this.isAuthenticated = false;
      }
    });
  }
}
```

**Comment by bojeil-google** [comment]
Hey @mnlfischer, we are unable to recreate this. Can you provide more instructions on how to get the error to throw?
I signed in a user, called `window.localStorage.clear()` and then signed out the user/signed in a new user, changed persistence via `setPersistence` but none of these threw any error.

**Comment by mnlfischer** [comment]
I used the Clear All Button in Chrome Dev Tools, I'm not sure if the clear button fires the same action you used.

![clear](https://user-images.githubusercontent.com/3883653/31307894-efab83b2-ab6c-11e7-888e-f64796fcc824.PNG)

**Comment by bojeil-google** [comment]
Yeah, I am able to recreate now.  It behaves different than `window.localStorage.clear()`. I didn't expect that.
I will work on the fix next week. Thanks for reporting this.

**Comment by AVVS** [comment]
I'm not sure if it is related to this issue, or not, but here is a stacktrace that throw in yandex browser (based on chromium):

```
TypeError: Cannot read property 'indexOf' of null
  at call(../node_modules/@firebase/auth/dist/auth.js:223:55)
  at vc(../node_modules/@firebase/auth/dist/auth.js:48:161)
  at call(../node_modules/@firebase/auth/dist/auth.js:49:236)
  at ? (../node_modules/@firebase/auth/dist/auth.js:46:179)
```

**Comment by bojeil-google** [comment]
Hey @AVVS, the next release should contain the above fix. You can test to see if that fixes your issue. I will update this thread on that.

**Comment by bojeil-google** [comment]
This should be fixed in the latest version: https://firebase.google.com/support/release-notes/js#4.6.0
