### ISSUE TITLE
@firebase/testing Produces grpc Deprecation Warning

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-js-sdk#1780]
Any test I create using the `@firebase/testing` library litters my test output with `DeprecationWarning`s.

`(node:10167) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead`

**@firebase/testing**: "~0.9.4"

Not sure how simple the fix is as I am unfamiliar with the library but I'm pretty sure it's this line.

https://github.com/firebase/firebase-js-sdk/blob/9f6dbc82b54eaba6551cc969df9b8d43574371e7/packages/testing/src/api/index.ts#L35

**Comment by ryanpbrewster** [comment]
This was fixed by https://github.com/firebase/firebase-js-sdk/pull/1806
