### ISSUE TITLE
FR: Replace grpc with grpc-js

### ISSUE THREAD

**Issue by maxogden** [firebase/firebase-js-sdk#1783]
Hi, I noticed that last week the https://github.com/googleapis/nodejs-firestore package got rid of the grpc node native addon and replaced it with `@grpc/grpc-js`. I was wondering if this package was planning on upgrading to `grpc-js` to remove the complexity of dealing with compiled node addons for different platforms like node and electron. I couldn't find any discussion on this in the issue tracker. Thanks!

**Comment by mikelehen** [comment]
Thanks for bringing this up!  Yes, we are intending to upgrade to grpc-js. It *seems* like this should be a painless switch with no downsides.  The main risk is that it's still beta, so we may drag our feet just a little bit in case there are any issues discovered in the near future.  But if you're running into a specific issue that you think this would solve, we could look at doing it sooner (or if you felt inclined to make a PR for it, that could also speed things along. 😄).

**Comment by mikelehen** [comment]
Unfortunately this had to be reverted (#1813) because it is a breaking change and so must wait until the next time we make a breaking change release to firebase (and increase the major version number).  Sorry for the inconvenience!

**Comment by railerbailer** [comment]
Hello! I would love an update to when this might happen! 😄

**Comment by ctavan** [comment]
Next.js SSR would also benefit from this change: https://github.com/zeit/next.js/issues/7894

**Comment by mkonikov** [comment]
Any idea when to expect the next major release?

**Comment by var-const** [comment]
@mkonikov Historically, we’ve made breaking changes around May, but note that doesn’t mean we’ll do so this year or even that this change will necessarily be in the next breaking change.

**Comment by drizzd** [comment]
This should address Electron's deprecation of non context-aware native modules:

```
(node:380) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

**Comment by schmidt-sebastian** [comment]
We are trying this again this week and officially dropping Node 6 support.

https://github.com/firebase/firebase-js-sdk/pull/2856
