### ISSUE TITLE
firebase.firestore() is not a function

### ISSUE THREAD

**Issue by stot3** [firebase/firebase-js-sdk#1784]
### [REQUIRED] Describe your environment

  * Operating System version: StackBlitz Node
  * Browser version: Stackblitz Browser
  * Firebase SDK version: 6.0.2
  * Firebase Product: firestore

#### Steps to reproduce:
https://stackblitz.com/edit/angular-uh28cf?

Set up a new project, try and initialize firebase into the project. 

#### Relevant Code:

https://stackblitz.com/edit/angular-uh28cf?

firebase.firestore().collection("RetailersCoords").add({lat: 11010001001})

**Comment by Feiyang1** [comment]
You need to import firestore in app.service.ts using:
```javascript
import * as firebase from 'firebase/app';
import 'firebase/firestore';
```

**Comment by mindhivefi** [comment]
This is breaking with the version 6.0.4 but not on 6.0.2.
