### ISSUE TITLE
FR: Add Google analytics For Firebase 

### ISSUE THREAD

**Issue by nsantosdaveiga** [firebase/firebase-js-sdk#1785]
* Operating System version: IOS/Android
  * Browser version: React Native
  * Firebase SDK version: 6.0.2
  * Firebase Product: Analytics

I would like to use Google Analytics for Firebase in the JS SDK, to be use in React Native or Ionic project.

The GA SDK it's now deprecated, we need a proper solution thanks !

**Comment by Feiyang1** [comment]
We hear you! We just added Google Analytics support in `firebase@7.0.0`. 
Please read our [get started guide](https://firebase.google.com/docs/analytics/get-started) for Analytics for Web.
