### ISSUE TITLE
.info/connected does not change to false when offline

### ISSUE THREAD

**Issue by tonila** [firebase/firebase-js-sdk#179]
### Environment

Debian buster
Node.js v 8.5.0
firebase-admin v ^5.0.0

#### Steps to reproduce:

1. Start application and wait for console log "Firebase connected!"
2. Go offline (switch off wifi or remove lan cable etc.)

When internet connection is disabled, application should print "Firebase disconnected".
It seems, it never does!

#### Relevant Code:

```javascript
"use strict";

var path = require('path');
var admin = require("firebase-admin");

var serviceAccount = require(path.join(__dirname, "some-firebase-adminsdk-lu0x5-82c66d50f5.json"));

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://some.firebaseio.com/"
});

const database = admin.database();

var connectedRef = database.ref(".info/connected");
connectedRef.on("value", function(snap) {
  if (snap.val() === true) {
    console.log("Firebase connected!");
  } else {
    console.log("Firebase disconnected!");
  }
});
```

**Comment by jshcrowthe** [comment]
Hey @tonila this looks like it's an issue with the `firebase-admin` project. Can you open this issue at https://github.com/firebase/firebase-admin-node

**Comment by tonila** [comment]
Oops, my bad! I'll open it in firebase-admin

**Comment by jshcrowthe** [comment]
No worries 😄
