### ISSUE TITLE
@firebase/testing does not handle FieldValue.increment

### ISSUE THREAD

**Issue by damonmaria** [firebase/firebase-js-sdk#1799]
### Describe your environment

  * Operating System version: MacOS 10.14.5
  * firebase-admin version: 7.3.0
  * @firebase/testing version: 0.9.4
  * Firebase Product: firestore, emulator, testing

### Describe the problem

When I try and use `FieldValue.increment` in an `update` or `set` when using `@firebase/testing` (with the Firestore emulator) I get:
`FIRESTORE (6.0.2) INTERNAL ASSERTION FAILED: AsyncQueue is already failed: Error: FIRESTORE (6.0.2) INTERNAL ASSERTION FAILED: Transform results missing for TransformMutation.`

#### Relevant Code:

This produces the error:
```typescript
await siteDoc.ref.update({ field: firebase.firestore.FieldValue.increment(1) })
```

If I don't use `increment` then it works:
```typescript
await siteDoc.ref.update({ field: 1 })
```

I understand this could be the emulator not being up to date but thought I'd post here first.

**Comment by wilhuff** [comment]
This is a limitation of the emulator. Support for transformations (increments and array union/remove) is coming.

What you’re seeing here is that unfortunately, the emulator currently only partially implements the protocol for these operations and it's causing the SDK to panic.

@ryanpbrewster

**Comment by ryanpbrewster** [comment]
Just confirmed that this is fixed by https://github.com/firebase/firebase-tools/pull/1318, which will go out with the next CLI release.
