### ISSUE TITLE
FR: Phone Auth Support in React Native

### ISSUE THREAD

**Issue by kirilavdeew** [firebase/firebase-js-sdk#180]

**Comment by bojeil-google** [comment]
You can use an approach similar to the one described for Cordova/Ionic apps:
https://stackoverflow.com/questions/44081040/ionic2-authentication-firebase

**Comment by jshcrowthe** [comment]
I'm going to convert this to a feature request. Seems like something that is unsupported, for good reason, but would be nice to at least investigate in the future.

**Comment by jshcrowthe** [comment]
Sorry for the churn here, closing this as a dupe of https://github.com/firebase/firebase-js-sdk/issues/102
