### ISSUE TITLE
FR: Make Callable Functions Url Configurable

### ISSUE THREAD

**Issue by scottfr** [firebase/firebase-js-sdk#1800]
### Describe your environment

  * Firebase SDK version: 6.0.2
  * Firebase Product: function

### Describe the problem

Currently when using the `functions().httpsCallable(name)` method, the resulting function always queries an endpoint at `cloudfunctions.net`.

Firebase hosting let's you configure an alias to a Cloud Function that lives on your domain:

https://firebase.google.com/docs/hosting/full-config#direct_requests_to_a_function

I would like to be able to use that alias when using callable functions rather than using the standard `cloudfunctions.net` url (we have some users who have extremely locked down networks that run into issues with the standard url).

Could we add an option to the data object passed to httpsCallable that would let you specify the url to lose.

**Comment by thefliik** [comment]
Related: #1641

**Comment by jake-nz** [comment]
Please! I need to optimize request time by eliminating the CORS preflight. I can use Firebase Hosting rewrites to make the function accessible on the same domain as my app but I need this feature to easily implement it on the client.

I've done this in my own fork and would happily send a PR: https://github.com/jake-nz/firebase-js-sdk/commit/10bc54f071b1d5236cf29f8e67e6faf029ecd61b

SO question regarding this: https://stackoverflow.com/questions/55352783/avoid-cors-preflight-for-firebase-callable-function/55369529

**Comment by thefliik** [comment]
@jake-nz `functions().httpsCallable` is a convenience function. You can call a callable function directly so long as you adhere to its expected request format (I did this in an app I made). You can see the expected request format in the source code: 

https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/api/service.ts#L133-L137

**Comment by owlvark** [comment]
I have to agree with the OP. In my opinion `httpsCallable` loses a lot of it's "convenience" if we are forced to use CORS preflight for no real reason. Wanting to straight-forwardly use an Ajax Post to the back-end cannot be considered an obscure use-case, can it?

**Comment by agordeev** [comment]
Totally agree. CORS is not required when calling resource is on the same domain, but Firebase Functions prefer to call `cloudfunctions.net`

@thefliik there is a huge `private async call(...)` function under the hood. Do you suggest to copy/paste its code and substitute the url with the proper one?

**Comment by thefliik** [comment]
@agordeev no. `@jake-nz` sounded like they might need a work-around ASAP, so I was pointing out that you can "call" a callable function via a properly formatted REST request. It's been a while since I've done it, so I don't remember the exact formatting of the request, but it's something like

- body: `{ data: the_function_params }`
- authorization header: `Bearer ${authToken}`

Again, the source code shows the proper request formatting.

**Comment by thefliik** [comment]
I've just learned that you can use [`functions.useFunctionsEmulator(origin)`](https://github.com/firebase/firebase-js-sdk/blob/ae319059e4a083a613a2999c1e61d44c9053a0d7/packages/functions/src/api/service.ts#L130) to accomplish this, though the API isn't super flexible.

When you set an emulator origin, then functions are called with the URL format:

```
url = `${origin}/${projectId}/${region}/${name}`
```

whereas normally the format is

```
url = `https://${region}-${projectId}.cloudfunctions.net/${name}`
```

So, if you use firebase hosting to provide a custom domain for your functions, you can reach them so long as you make the functions available at `YOUR_DOMAIN/FUNCTIONS_PROJECT_ID/FUNCTIONS_REGION/CALLABLE_FUNCTION_NAME`.

**Comment by ebceu4** [comment]
You can use dirty little hack to override this behaviour, as:
```
  const api = firebaseApp.functions()
  api._url = (name) => `api/${name}`
```

**Comment by realappie** [comment]
I think you should use `useFunctionsEmulator` for this, as its what the angular fire team is already using internally, see their [docs](https://github.com/angular/angularfire/blob/master/docs/functions/functions.md#firebase-hosting-integration) and internal code 

https://github.com/angular/angularfire/blob/705505a1806ae02d5bb08d3fc0d6ca24d9635527/src/functions/functions.ts#L36

**Comment by dhstack** [comment]
While I still don't know _exactly_ how you'd use `useFunctionsEmulator` plus hosting rewrites, it does look like [it's now deprecated](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctions#useFunctionsEmulator(java.lang.String)) in favor of [`useEmulator`](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctions#useEmulator(java.lang.String,%20int)).

**Comment by samtstern** [comment]
This is quite an old issue but I realized this was actually fixed a few months ago:
https://github.com/firebase/firebase-js-sdk/pull/3825

You can now use Callable Functions + Hosting Rewrites to call functions on a custom domain.

**Comment by inlined** [comment]
The custom domains approach is a bit limiting because it still assumes a particular path. You can also now use [`httpsCallableFromURL`](https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/api.ts#L100) to use whatever URL scheme you prefer.
