### ISSUE TITLE
Firebase error: "Attempted to find predecessor key for a nonexistent key. What gives?"

### ISSUE THREAD

**Issue by fephil** [firebase/firebase-js-sdk#181]
### [REQUIRED] Describe your environment

  * Operating System version: Android with Chrome WebView 37 (Cordova & Ionic v3)
  * Firebase SDK version: 4.1.2
  * Firebase Product: database

### [REQUIRED] Describe the problem

I have received multiple error logs from Sentry with the Firebase error "Attempted to find predecessor key for a nonexistent key. What gives?" This seems to always be on Android 5.0 with Chrome WebView 37 in a Cordova/Ionic app. My suspicion is that some users use Android 5 but somehow don't update the WebView from the Play Store (or perhaps they don't have access to Play Store).

Unfortunately Sentry.js isn't very forthcoming with data in this issue apart from saying it's in database.js so my guess is that it is happening as soon as the app starts/connects to the firebase database.

Is Firebase supported in Chrome 37? I appreciate it's an old browser version but Firebase does support Cordova so this makes the browser a potential support option.

Thanks.

**Comment by jshcrowthe** [comment]
Hey @fephil, is it possible that you could create a sample repro so I can take a look and see what's going on?

**Comment by fephil** [comment]
Hi @jshcrowthe, I completely understand why you've asked for a repo but I can't see how I can provide one as my code is a commercial app and not open source. I think that my issue is divided into two parts (which may help):

1. What is the official browser, platform, device support for the Firebase JS SDK? Does that support extend to Cordova? If so, does that mean every Chrome Browser version from 37 onwards is supported as the webview is updatable.

2. What would you need from a sample repo? As my app fails on the initial database connection on Chrome 37, it might be enough just to add firebase into a Cordova app and try and connect to the database.
