### ISSUE TITLE
Export logger instances

### ISSUE THREAD

**Issue by Odonno** [firebase/firebase-js-sdk#1815]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 74
  * Firebase SDK version: 5.11.1
  * Firebase Product: firestore (but applicable to all products)

### Describe the problem

I want to be able to retrieve a single logger instance or every logger instances from the @firebase/logger package in order to handle logs with our needs (publishing logs to our infrastructure instead of the console).

https://github.com/firebase/firebase-js-sdk/blob/ae32b2b58a3969266ab701a6b2a4895b790c8ea8/packages/logger/index.ts#L26

I am not sure if it is the right way to do this, is anyone able to provide guidance on this?

**Comment by mikelehen** [comment]
This is more of a "core" question, probably for @Feiyang1.  And it would need to go through our internal API proposal process before it could be implemented, so it could take some time.

For now the best bet is to intercept calls to console.log, console.error, etc.

**Comment by Odonno** [comment]
@mikelehen Thanks for your response. IMO, using console.log in production does not seem like a viable solution at all, even with the interception feature like you suggest.

BTW, I understand the situation and since it is not a major issue, it can wait. And I could also create the PR when the decision is made.

**Comment by hsubox76** [comment]
FYI, accessing Firebase logs was made available in version 7.12.0 https://firebase.google.com/support/release-notes/js#version_7120_-_march_19_2020

`onLog()` lets you supply a callback to do whatever you want with the log messages.

**Comment by Odonno** [comment]
Thank you for the update!
