### ISSUE TITLE
Firebase 6.0.4 and web worker

### ISSUE THREAD

**Issue by universse** [firebase/firebase-js-sdk#1817]
Hi. I'm using firebase authentication, firestore and storage in web worker. After upgrading from version 6.02 to 6.04 i'm starting to get ```ReferenceError: window is not defined```. It seems to come from firestore.

**Comment by Feiyang1** [comment]
Thanks for reporting it! We have made a fix https://github.com/firebase/firebase-js-sdk/pull/1819

**Comment by schmidt-sebastian** [comment]
@universse Are you able to pin your Firestore release to 6.0.2?

**Comment by Feiyang1** [comment]
@universse Can you also post a detailed log, so we can verify we actually fixed what is causing the issue for you?

**Comment by universse** [comment]
Hi. I reverted back to 6.02 when I reported this issue. After upgrading to 6.04 again, there's no more issue. Thank you very much!

**Comment by schmidt-sebastian** [comment]
I'm glad to hear that you are no longer blocked! Please note that the fix for your issue is, however, not yet released and will likely be part of 6.0.5. If you do see this issue again, please upgrade to 6.0.5 when it gets released.

**Comment by universse** [comment]
The issue cropped up again. Somehow it did not show up earlier. Sorry for any confusion caused.
![image](https://user-images.githubusercontent.com/15166715/58365475-972f6b80-7ef7-11e9-9e10-ac054b7e21b3.png)
