### ISSUE TITLE
Add support for collection group queries to @firebase/testing

### ISSUE THREAD

**Issue by CodingDoug** [firebase/firebase-js-sdk#1821]
Currently, @firebase/testing depends on rather old versions of the Firebase JS SDKs.  Therefore, collection group queries are not available for testing with the Firestore emulator.  Please update the versions of the required SDKs.

**Comment by compojoom** [comment]
Just wanted to open an issue about that. Thanks @CodingDoug!
Right now trying to test a collection query doesn't work as .get().then() on a collection query doesn't seem to execute.

**Comment by yuchenshi** [comment]
Can we still reproduce this? I think after the version bump things should just work.

**Comment by yuchenshi** [comment]
Closing for now. The dependencies have been updated and please open a new issue if you still experience problems with collection group queries.
