### ISSUE TITLE
How can I get intellisense / autocompletion in my JS React project with Firebase in VSCode?

### ISSUE THREAD

**Issue by cbdeveloper** [firebase/firebase-js-sdk#1833]
Sorry if this isn't the best place to ask this. I tried [StackOverflow](https://stackoverflow.com/questions/56329806/firebase-intellisense-autocompletion-on-javascript-react-project-in-vscode) and got no luck.

I'm working on a React and Firebase project and I'm having trouble setting up the autocompletion on my code (I'm using VScode).

Here's what I've got so far:

---

**HOW I'M PROVIDING FIREBASE TO MY APP COMPONENTS (VIA CONTEXT)**

---

**FirebaseContext.js**

```
import React from 'react';

const FirebaseContext = React.createContext(null);

export default FirebaseContext;
```

**firebase.js**

```
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
import 'firebase/functions';

// .env file in root folder
const config = {
  apiKey: process.env.FIREBASE_APP_API_KEY,
  authDomain: process.env.FIREBASE_APP_AUTH_DOMAIN,
  databaseURL: process.env.FIREBASE_APP_DATABASE_URL,
  projectId: process.env.FIREBASE_APP_PROJECT_ID,
  storageBucket: process.env.FIREBASE_APP_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_APP_MESSAGING_SENDER_ID
};

firebase.initializeApp(config);
firebase.functions().useFunctionsEmulator('http://localhost:5000');

export default firebase;
```

**index.js**

```
import React from 'react';
import ReactDOM from 'react-dom';
import firebase from './helpers/firebase/firebase';
import FirebaseContext from './helpers/firebase/FirebaseContext';
import { BrowserRouter as Router} from "react-router-dom";

...

ReactDOM.render(

  // HERE'S HOW I'M PROVIDING FIREBASE FOR MY APP
  <FirebaseContext.Provider value={firebase}>
    <Router>
      <App/>
    </Router>
  </FirebaseContext.Provider>

,document.getElementById('root')
);
```

---

**HOW I'M CONSUMING FIREBASE IN MY COMPONENTS**

---

**AddProductContainer.js**

```
import React, { useEffect, useState, useCallback, useContext } from 'react';
import FirebaseContext from '../../../helpers/firebase/FirebaseContext';

function AddProductContainer() {

  const firebase = useContext(FirebaseContext);

  function saveToFirestore() {
    // I DON'T HAVE ANY AUTOCOMPLETION FROM 'FIREBASE...'
    firebase.firestore().collection('products').add({ 
      title: productDetails.title.newTitle,
      description: productDetails.description,
      categories: productDetails.categories
    });
  }

}
```

---

**QUESTION**

How can I get autocompletion from Firebase inside a JavaScript project?

**Note:** All of my component files are `.js`. I'm not using Typescript.

Is there a way to use **JSDoc annotations** to get access to autocompletion in this case?

Something like:

```
/** @type {firebase} */
const firebase = useContext(FirebaseContext);
```

**Comment by hsubox76** [comment]
Hi -

It would definitely be pretty tricky to do it the way you're doing it without Typescript or something, but can I suggest another option?

I don't think it's necessary to put the `firebase` object itself in context.  Putting `app` in context might make sense (the object returned from `firebase.initializeApp`) if you were going to use more than one app or just wanted to be explicit, but it seems like `firebase` itself would make more sense being a direct import (`import firebase from 'firebase/app'`) in any file that's using it.  It won't create a second instance of firebase or anything if that's what you're concerned about, it's just a handle for the firebase library.  It'll pick up the default app you initialized with `firebase.initializeApp()` as long as `initializeApp()` ran first.  `initializeApp()` creates a global default firebase app that any invocation of Firebase methods will pick up.

If you're uncomfortable with globals, you can be explicit about the specific app you're working with by assigning `const app = firebase.initializeApp(...)`, then passing `app` down through props or context, then always calling firebase packages with `app` as an argument, such as `firebase.firestore(app).collection('products').etc...` .

But there should be no cost to importing the `firebase` package directly at the top of any file you're using it in (and want autocomplete in).

**Comment by cbdeveloper** [comment]
> It won't create a second instance of firebase or anything if that's what you're concerned about

 That was exactly my concern. I'll only be using 1 firebase app. But where would I run the firebase.initializeApp() command? Should I call it on every file that imports firebase? Thanks!

**Comment by hsubox76** [comment]
Oh, definitely don't do that!  `initializeApp()` is actually the one thing you want to make sure you only call once.  It does try to make a new app every time it's called.  It creates a new app named `[DEFAULT]`.  So if you call it more than once, you'll see console errors saying that an app named `[DEFAULT]` already exists.

You just need to make sure you call it before you call any other firebase code, and all your other code will be able to access the global default app.  Some people find it more readable to be explicit by assigning the created app to a variable that they pass around like:

```const app = firebase.initializeApp(...)```

Then passing `app` explicitly to anything that needs to use it and calling packages with `firebase.firestore(app).collection(...)`.  But you can leave all that out (`firebase.firestore().collection(...)`) and Firebase will find the default app.  Some people just like to be more explicit.

**Comment by Feiyang1** [comment]
Closing since it seems the question has been answered. Feel free to reopen it if you have any followup questions.
