### ISSUE TITLE
Firestore issue - Error: package.json does not exist at /package.json

### ISSUE THREAD

**Issue by CasperEngl** [firebase/firebase-js-sdk#1835]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Mojave 10.14.5 (18F132)
  * Browser version: Google Chrome v74.0.3729.169
  * Firebase SDK version: 6.0.2
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Building Next.js application with serverless target fails when `firebase/firestore` has been imported. Resulting in the following error:
```
> Build error occurred
Error: package.json does not exist at /package.json
    at Object.module.exports.PsoT.exports.find (.next/ser
verless/pages/index.js:66914:15)
    at Object.<anonymous> (.next/serverless/pages/fotos.j
s:107987:12)
    at Object.wPNL (.next/serverless/pages/index.js:10802
2:30)
    at __webpack_require__ (.next/serverless/pages/fotos.
js:23:31)
    at Object.XpdW (.next/serverless/pages/index.js:83870
:12)
    at __webpack_require__ (.next/serverless/pages/fotos.
js:23:31)
    at Object.g1pB (.next/serverless/pages/index.js:94733
:27)
    at __webpack_require__ (.next/serverless/pages/fotos.
js:23:31)
    at Object.<anonymous> (.next/serverless/pages/fotos.j
s:66074:14)
    at Object.Ou8q (.next/serverless/pages/index.js:66431
:30)
```
This line `at Object.module.exports.PsoT.exports.find (.next/serverless/pages/index.js:66914:15)` tries to resolve `package.json` in `.next/serverless/` like so:

```
var binary = __webpack_require__("PsoT");
var binding_path = binary.find(path.resolve(path.join(__dirname, '../package.json')));
```

Also fails when trying to deploy to Firebase Hosting/Functions and Zeit Now.

#### Steps to reproduce:
Build Next.js application with serverless target.

#### Relevant Code:
```
import firebase from 'firebase/app';
import 'firebase/firestore';
```
Must also not import firebase/app as such:
```
import * as firebase from 'firebase/app';
```

**Comment by wilhuff** [comment]
Hi! We don't directly support Next.js so "Build Next.js application with serverless target" doesn't really mean anything to me. The best way to show us what's going wrong is a self contained example, with detailed instructions for how to reproduce the error.

**Comment by wilhuff** [comment]
Actually this may be a simple error. Shouldn't your imports should be:

```js
import firebase from '@firebase/app';
import '@firebase/firestore'
```
?

**Comment by CasperEngl** [comment]
Didn’t make a difference. Making this change, I got some more errors from TypeScript that some values might be null.
  

  
When searching for the “@“ prefixed versions of these packages, it also says to use the non-prefixed versions in the README.
  

  
I’ve rewritten my app with CRA, so this won’t be an issue for me. Next.js really wasn’t well-suited for what I needed.
  

  
  

  
  
>

**Comment by wilhuff** [comment]
OK. In that case I'll close this issue.

**Comment by SimeonKostov** [comment]
Hi, I had exactly the same problem.
Take a look: [](https://github.com/zeit/next.js/issues/6073#issuecomment-467589586)
I use firebase 5.11.1 . Note that it is possible to have problems if your firebase version is newer

**Comment by CasperEngl** [comment]
Thank you! I’ll check that out, looks very promising :) I am indeed using version 6.0.2.

**Comment by eugrdn** [comment]
Hey, @CasperEngl! Did ^ help you?

**Comment by CasperEngl** [comment]
> Hey, @CasperEngl! Did ^ help you?

Unfortunately, the project I was working on was abandoned before I tried solving it again.

**Comment by eugrdn** [comment]
Oke, jfyi I've just created [the issue](https://github.com/zeit/next.js/issues/8405) that might be related to yours.
