### ISSUE TITLE
incorrectly thinks firebase is loaded in development

### ISSUE THREAD

**Issue by brewster1134** [firebase/firebase-js-sdk#1836]
i am using rollup to create a firebase app, and when i am watching the source files and rebundling the bundle , the `window.firebase` node will exist, but be undefined. this causes firebase to crash since a few lines down it checks for `window.firebase.SDK_VERSION`.

would `if (isBrowser() && self.firebase)` be a better check here? https://github.com/firebase/firebase-js-sdk/blob/f6afa45fe24f7adf5ea9a672100049c2ca8571db/packages/app/index.ts#L26

just a thought...

**Comment by Feiyang1** [comment]
Addressed in https://github.com/firebase/firebase-js-sdk/pull/1868
