### ISSUE TITLE
Issue upgrading to Firebase 6.1 from 6.0.2

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#1837]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 74
  * Firebase FROM SDK version: 6.0.2

    "firebase": "6.0.2",
    "firebase-tools": "^6.9.2",
    "@firebase/app-types": "^0.4.0",
    "@angular/fire": "^5.1.3",
    ...
    "@firebase/testing": "^0.9.4",

  * Firebase TO SDK version: 6.1

    "firebase": "6.1.0",
    "firebase-tools": "^6.10.0",
    "@firebase/app-types": "^0.4.0",
    "@angular/fire": "^5.2.1",
    ....
    "@firebase/testing": "^0.10.0",

  * Firebase Product: auth, database, firestore, storage, functions

### [REQUIRED] Describe the problem

Hello team,

So I'm upgrading from firebase 6.0.2 to 6.1.
I'm using angular & angularFire as well.
When I do a local build & serve everything works fine.
If I do a deploy on firebase hosting (with build optimizer true) I get:
![image](https://user-images.githubusercontent.com/1098243/58783831-33393100-85e2-11e9-9b60-8d94634e963a.png)

I import Timestamp in my components like this:
import { firestore, storage } from 'firebase/app';
import Timestamp = firestore.Timestamp;

Any ideas?

**Comment by hsubox76** [comment]
Two questions:

- Can you do a clean install? Delete `node_modules` and any lock files and reinstall and see if the problem goes away?
- Are you by any chance importing the `firebase-admin` package?  Some people seem to be having issues with packages (such as firebase.auth) being undefined if they are also importing `firebase-admin`.

**Comment by LanderBeeuwsaert** [comment]
First question:
I deleted and reinstalled +- 7 times with all sorts of different tries. In the end it's really the difference between before and after upgrade that makes the difference.

Second one:
I'm installing firebase-admin but in a subdirectory /functions. Where all functions are stored and deployed. So to the best of my knowledge that should be completely independent.

**Comment by hsubox76** [comment]
I'm trying to reproduce this issue but haven't been able to.  Here's the repo for the minimal angularfire Firestore setup I'm trying to reproduce it with: https://github.com/hsubox76/angularfire-test

I'm running `ng build --prod --build-optimizer=true` and then deploying to Firebase Hosting from `dist/angularfire-test`.

I think I've matched all the versions you've listed, is there anything I'm missing or anything you can tweak here to make it fail?  Alternatively, you can try to strip your own app down to a minimal repro of this bug and upload it to a Github repo and I'll take a look.

**Comment by LanderBeeuwsaert** [comment]
Hey @hsubox76 ,

I've got some more information.
So because of the line in main.js in the console:
![image](https://user-images.githubusercontent.com/1098243/59452393-e9382280-8e0d-11e9-9214-e8519966a81e.png)
I have figured out the offending class.
So I commented out import Timestamp = firestore.Timestamp; and removed all references in that class.

The next that happened was:
![image](https://user-images.githubusercontent.com/1098243/59452478-18e72a80-8e0e-11e9-9b1f-1fb697c5d183.png)
which is also imported in the same class: import DocumentReference = firestore.DocumentReference;

Soooo, this class is a helper class/service that I use to do some common tasks.
If I start to remove all usages of firestore in the class itself, it starts to throw:
![image](https://user-images.githubusercontent.com/1098243/59454546-99a82580-8e12-11e9-8bcf-a40c0166168b.png)
for import GeoPoint = firestore.GeoPoint;
So it's actually import { firestore } from 'firebase/app'; that is not known/found it seems.

So in the end, once I remove all declarations that use firestore (but not declarations that use database, like import DataSnapshot = database.DataSnapshot;)...

the error is the same, but now for a different injectable service class.

So maybe firestore typescript definitions are initialized later than before?
I have no idea.

**Comment by hsubox76** [comment]
Thanks for the additional info, but it's too hard to narrow down the problem without seeing your setup and project structure and other dependencies.  The most helpful thing would be if you could provide a minimal repro as described in the [comment above](https://github.com/firebase/firebase-js-sdk/issues/1837#issuecomment-501059388).  You can upload it to a Github repo and I can clone it and take a look.  You can either start from the example repo above and change things until you get the error, or start from your current project, and remove as much extraneous and proprietary code as possible while still getting the error.

And if you can also let me know the specific build/deploy commands to run on that sample repo to get the error, that would be great.

**Comment by LanderBeeuwsaert** [comment]
@hsubox76 ,

I'm happy to say I've been able to break it haha,
and reproduce it quite easily. As I had thought, it seems to be the dependencies on firestore in a service. But that seems to me that a lot of people should have that? Combined with optimization of course but even then.

https://github.com/LanderBeeuwsaert/angularfire-test-broken

you'll need https://www.npmjs.com/package/local-web-server globally installed and then do "npm run t"
it will build and serve.

**Comment by LanderBeeuwsaert** [comment]
Let me know if you can reproduce, I'm curious.

**Comment by hsubox76** [comment]
Thanks for the repro!  I was able to reproduce it and I think we have figured out what's going on.

You're referencing `firestore.Timestamp` at the very top of the file, which is before `firebase.initializeApp()` has been run.  But `initializeApp()` is what attaches all the individual package symbols (firestore, auth, etc.) to the `firebase` object, so until it's been run, there is no `firebase.firestore`.

Some of the other `import =` statements such as `database.Reference` do not cause an error because you are using the result as a type only, and not as a value.  You use `instanceof Timestamp` at one point, which is using it as a value, which causes the code to check if the value actually exists on the import when you try to assign it.  It doesn't check that deeply if it knows it's only used as a type.

So if you just get rid of the `import Timestamp = firestore.Timestamp` line and type out `firestore.Timestamp` whenever you actually use it in the code, inside the class, it works fine.  If you're trying to avoid typing out the full name, you could maybe destructure it at the top of the function you're using it in (put `const { Timestamp } = firestore` near the top of `stringifyObjectsWithFunctions()` or something) or anywhere inside the class, or in any code that's definitely run after `initializeApp()`.

This fixes the problem in the sample code, hope it works in your full project.

**Comment by LanderBeeuwsaert** [comment]
Hello @hsubox76 
ok, thanks for the solution and possible fix!

However, this means that we always have to use firestore.... in the code
Only for Timestamp this is 223 times, DocumentReference 63 times, QuerySnapshot 40 times, ...
All in all, probably +- 500 times that we will have firestore... in the code, where that up until now wasn't the case.

So before I commit a number of hours to refactor; 2 questions:

1. isn't the purpose of being able to do imports at the top of the file just for that reason, to reduce boilerplate. Isn't there a plan/roadmap/ticket to tackle this?

2. What is the change that this worked up until now but doesn't anymore?

**Comment by hsubox76** [comment]
I can't seem to reproduce the error not happening in a previous version.  I tried the following steps:

1) I went into `package.json` and changed the firebase version to 6.0.2 and the `@angular/fire` version to 5.1.3.
2) I ran:
```
rm -fr node_modules
npm install
npm run t
```

I still got the same error in the console.  I also tried versions 6.0.1 and 5.11.1, and still saw the error.  Is it at all possible that the breaking change was in another dependency?

**Comment by LanderBeeuwsaert** [comment]
Hello,

So I did the same as you and I can confirm I have the same result.

And then I've spent hours :-p on copy/pasting parts of the project configuration in the test project, to see if I could make it that it worked with the import QuerySnapshot = firestore.QuerySnapshot;

Now, if you pull the test project & do:
npm run t => it will work

rm -fr node_modules
change firestore to 6.2 and also angularFire to 5.2.1 (I think the firestore upgrade is the culprit but I didn't test)
npm install
npm run t => it will fail

**Comment by hsubox76** [comment]
Thanks for the new info.  I tried this repo and upgraded both and it did fail.  I upgraded `firebase` alone and it did not fail.  I upgraded `@angular/fire` alone and it did fail.  I tried several versions and it looks like the breaking change happens between `@angular/fire` 5.1.3 and 5.2.0.  You may want to open an issue in the `@angular/fire` repo.

**Comment by LanderBeeuwsaert** [comment]
hehe, ok, thanks, well, getting closer alright.
