### ISSUE TITLE
VSCode Intellisense / AutoComplete is not working

### ISSUE THREAD

**Issue by mrfambo** [firebase/firebase-js-sdk#1839]
I read the Issue Template, i am writing the issue in respect of that.

### DESCRIBE THE PROBLEM:

I am using Firebase-js-sdk in my react application. The only problem i am having is that intellisense is not working in the VSCode which is leading to severe anxiety and confusion. I need to go back and forth to documentation and get method names etc.

* Operating System version: macOS Mojave (10.14.5)
* Browser version: Google Chrome (Version 74.0.3729.169 (Official Build) (64-bit))
* Firebase SDK version: ^6.0.4
* Firebase Product: auth, firestore, functions
* Language Mode on VSCode: React, JS, ReactTS (Tested on all)
* VSCode Version: Version 1.34.0 (1.34.0)

#### Steps to reproduce:

Just create a react project and add firebase js sdk. Go in your .js file and import the Firebase instance.
When you will type "Firebase.", nothing will appear as suggestion. 
Same goes to "db.", i tried every way out but nothing worked.

Let me know if i can give you more information on this.

**Comment by mrfambo** [comment]
import * as firebase from "firebase/app";

import 'firebase/auth';
import 'firebase-firestore';
import 'firebase-functions';

var FirebaseConfig = {...REMOVED FOR PRIVACY}

firebase.initializeApp(FirebaseConfig);

when you type "firebase.", after dot nothing is shown as suggestion or autocomplete. Same for other instances.

**Comment by mrfambo** [comment]
I couldn't get it working even with var firebase = require("firebase/app") etc etc. It is not working anyway no matter ES6 or not.

**Comment by hsubox76** [comment]
So I ran

```
npx create-react-app react-autocomplete
yarn add firebase
code .
```

and went to `src/App.js` and pasted in the import lines in your second comment, and autocomplete seems to work:

![Screen Shot 2019-06-03 at 2 59 08 PM](https://user-images.githubusercontent.com/10716545/58837656-12d49b00-8611-11e9-900c-b461af00d3ca.png)

Seems like it could be a problem with your VSCode settings, or possibly a VSCode bug.  It doesn't seem related to the Firebase JS SDK source code.

**Comment by mrfambo** [comment]
Leaving a comment for all, removing the node_modules folder and package-lock.json. Then re-installing with yarn solved the problem for me. Seems like VSCode wasn't reaching the package details.
