### ISSUE TITLE
Auth ID token refresh does not work.  

### ISSUE THREAD

**Issue by Obiwarn** [firebase/firebase-js-sdk#1841]
Something with my token refresh mechanism seems broken, but I cannot debug it since the token takes one hour to expire. I could not find any way to make them expire manually (for testing).

This happens with my new persistence setting: firebase.auth.Auth.Persistence.NONE
We use email login.

**Comment by bojeil-google** [comment]
This question is quite cryptic. What do you mean by "token refresh mechanism seems broken"? We mostly refresh tokens when the current cached token is expired and you make a call to an API (reloading a user, updating a user, etc) that requires a fresh token or if you depend on some other Firebase service that requires a fresh token. Persistence type does not affect tokens at all.

**Comment by Obiwarn** [comment]
Thank you for the quick response.

So with any call to the db the tokens are updated automatically? 

Some customers reported that after keeping my Webapp (that uses Firestore)  open for an hour without using it and then returned to it and typed in some text, it was not saved to the database. They told me "something with token expiration error" showed in the conole logs.

**Comment by eli0shin** [comment]
I have experienced this sissies as well. several hours after `firebase.auth.currentUser()` will return null and tokens that have been saved outside of firebase as a work-around no longer work. Is there a documented solution to this currently or is this behavior unexpected?

**Comment by wti806** [comment]
I tried with firebase.auth.Auth.Persistence.NONE and email password sign-in. I'm still able to get the token after 1 hour via `getIdToken` API on the user. If you use firebase.auth.Auth.Persistence.NONE, firebase.auth.currentUser() will be gone after page refresh as the user is not stored in storage. That's the expected behavior.

**Comment by Obiwarn** [comment]
The only call I do is `db.collection(col).doc(doc.id).update(... )` after one hour. And this seems to cause the above error for some customers.

**Comment by bojeil-google** [comment]
We need a minimum, complete and reproducible example. Otherwise, we can't really do much about this.

**Comment by Obiwarn** [comment]
Is there any way to reduce token expiration time, so I can reproduce this in a better way?

**Comment by rommelpe** [comment]
@Obiwarn currently, there's no way for the developers to check or set the expiration time. If you could reproduce this using the standard expiration time, we'd be happy to investigate further.
