### ISSUE TITLE
Firebase typings, weird argument type for put(data: any | any | any)

### ISSUE THREAD

**Issue by benwinding** [firebase/firebase-js-sdk#1865]
### Describe your environment

  * Operating System version: Ubuntu 19.04
  * Browser version: Chrome 75.0.3770.80
  * Firebase SDK version: 5.11.1
  * Firebase Product: firebase (npm package)

Using the Firebase types included in `firebase` npm package, there is a weird type. Specifically when using the _put()_ method on a storage reference. The following line show's that the input type for put(data). 

https://github.com/firebase/firebase-js-sdk/blob/021a38cbd29854923e6b49eda282bed09136f253/packages/firebase/index.d.ts#L5444

#### Steps to reproduce:
Install the firebase npm package

#### Relevant Code:
https://github.com/firebase/firebase-js-sdk/blob/021a38cbd29854923e6b49eda282bed09136f253/packages/firebase/index.d.ts#L5444

Why is the type `any | any | any`?  it doesn't make any sense to me, could this be done a little better?

**Comment by hsubox76** [comment]
Thanks for the heads up, will be fixed by https://github.com/firebase/firebase-js-sdk/pull/1876.
