### ISSUE TITLE
Bug: Performance Monitoring for Web (Beta) - Old Browsers

### ISSUE THREAD

**Issue by fabian-hiller** [firebase/firebase-js-sdk#1866]
**Environment**

  * Operating System version: iOS 9.3.5
  * Browser version: Version/9.0 Mobile/13G36 Safari/601.1
  * Firebase SDK version: 6.1.1
  * Firebase Product: performance (Performance Monitoring for Web)

**Problem**

My websites with Firebase Performance Monitoring for Web crash in older browsers. An error appears in the console. The error in the console is slightly different depending on the browser and browser version.

> Uncaught ReferenceError: fetch is not defined

<img width="860" alt="firebase" src="https://user-images.githubusercontent.com/35291865/59270596-25268880-8c52-11e9-997b-27486f443e1c.png">

**Steps to reproduce**

Use an old iPad mini (iOS 9.3.5) or just an old browser and open: https://test-62084.web.app/
It's just a simple React app with Firebase Performance Monitoring.

Sample code: https://stackblitz.com/edit/firebase-issue-sandbox-wyst61

**Comment by mmermerkaya** [comment]
You need a fetch polyfill for Safari < 10.1. Please see the [supported environments page](https://firebase.google.com/support/guides/environments_js-sdk#polyfills) for more information.

**Comment by fabian-hiller** [comment]
@mmermerkaya thank you! 😊 I'll check it out.
