### ISSUE TITLE
FR: Proxy for Firebase Authentication

### ISSUE THREAD

**Issue by damian66** [firebase/firebase-js-sdk#1878]
Hello,
I am working on a JS React app that uses Firebase Authentication with this SDK. I could have some potential users from China but... China blocked few Google domains like `googleapis.com`.

I was trying to find some ways around but I could not find anything. I know that they could use a VPN, but that's not the solution I am looking for.

Since the application, I am working on is front-end only, is there a way to create a proxy to allow users in China to authenticate?

**Comment by kulaj** [comment]
Have you managed to solve this?

**Comment by dwybourn** [comment]
Is there any update on this or any progress been made? I'm having the same issue.

**Comment by rosalyntan** [comment]
Thanks for this feature request -- this is not something we are planning to support, for security reasons.
