### ISSUE TITLE
Firebase User Overwritten by other 3rd party provider

### ISSUE THREAD

**Issue by tolotrasamuel** [firebase/firebase-js-sdk#1883]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 74.0.3729.169 
  * Firebase SDK version: 6.2.0
  * Firebase Product: auth

#### Steps to reproduce:

I have a user called Foo with email: foo@example.com Foo has used this email as his primary email in his FACEBOOK account. Foo has used this email to open an account on GOOGLE.

Scenario 1

1) Then Foo attempts to sign up in my app using Firebase Authentication, he chooses Google as 3rd party provider. It is successful. I can see foo@example.com in my users' list on my Firebase Console.

2) Then Foo logs out and attempts to sign up again in my app but this time choose Facebook as 3rd party provider. It fails and He gets the following error:

ERROR_PROVIDER_ALREADY_LINKED` - The current user already has an account of this type linked.
So far everything is working normally as I would expect. But then in this scenario, things are getting me confused.

Scenario 2:

1) I deleted the user foo from the Firebase console.

2) Foo attempts to sign up on my app with Facebook. It is successful. I check my Firebase console and I see the user foo@example.com with the Facebook logo next to it.

3) Then Foo logs out and then attempts to sign up with my app again with Google. I was expecting the same error as above ERROR_PROVIDER_ALREADY_LINKED but instead, Foo signs up successfully!! I quickly checked my Firebase console and I see that the user foo@example.com with Facebook as 3rd party provider has been overwritten by Google.

Is this the desired behavior or a bug? If it is normal, how do prevent this code to overwrite existing user?
#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by bojeil-google** [comment]
This is a known issue. There is a lot of information about it online:
https://stackoverflow.com/questions/40766312/firebase-overwrites-signin-with-google-account

**Comment by puf** [comment]
Also posted on https://stackoverflow.com/q/56596851, so let's keep it there.

**Comment by ForbiddenEra** [comment]
> 
> 
> This is a known issue. There is a lot of information about it online:
> https://stackoverflow.com/questions/40766312/firebase-overwrites-signin-with-google-account

Thanks. Probably should have searched first.

**Comment by ForbiddenEra** [comment]
> 
> 
> Also posted on https://stackoverflow.com/q/56596851, so let's keep it there.

This page doesn't exist. And now this issue is closed. So how is this going to get fixed?

**Comment by ForbiddenEra** [comment]
> That depends on the email address. Google is considered a trusted provider for @gmail.com addresses, so gets special treatment there.

Was one of the comments on question 40755312, but the email I was using is a domain I own/provide for..not a gmail domain..?

Is really the only option to check providers first? also, if this is the case / no fix coming soon / can we update the documentation at least?
