### ISSUE TITLE
Auth email expiration time 

### ISSUE THREAD

**Issue by nes123** [firebase/firebase-js-sdk#1884]
Hi, I didnt find any documentation for the expiration times of password rest, email verification etc. I am especially interested in passwordless sign-in with email link (signInWithEmailLink). It seems that the links expire after a hour and I am curious if we can programmatically extend this time. I am using these links to invite users to my app and since I am the one to send them it usually take the users several hours to open them.

**Comment by bojeil-google** [comment]
The expiration is longer than an hour. There is no way to customize it but you can file a [feature request](https://firebase.google.com/support) for that.

**Comment by aaaguirrep** [comment]
Hi, what is the current expiration time for verifyEmail and ResetPassword link?

**Comment by rommelpe** [comment]
@aaaguirrep The default expiration time is currently about 1 hour, but is subject to change.
