### ISSUE TITLE
Swallowed exceptions

### ISSUE THREAD

**Issue by alexsuh7** [firebase/firebase-js-sdk#1889]
The FCM WEB SDK can potentially swallow parsing exceptions.

https://github.com/firebase/firebase-js-sdk/blob/dd098c6a87f23ddf54a7f9b21b87f7bb3fd56bdd/packages/messaging/src/controllers/sw-controller.ts#L96

**Comment by mmermerkaya** [comment]
Did this behavior cause an issue in your app? If so, can you explain?

**Comment by alexsuh7** [comment]
Hi , thanks you for responding . 

I am not sure , 
we were investigating some issues of getting an 'the site has been updated in the background' by chrome , when sending push message via firebase , and stumbled upon this code in the FCM SDK code. 

It might hide the issue we are facing (e.g. wrongly formatted FCM Messages , some weird characters messing up serialization ) or it might be something else entirely .

As any potential exceptions are swollen by current implementation at this location , we are blind as to any possible issues.

Hope it makes sense , please let me know if any more information is required .

Thank you .

**Comment by mmermerkaya** [comment]
You can add your own event listener to your service worker and receive the event in your code if you want to do debugging.

Adding this line would print the message contents:

```js
self.addEventListener("push", e => console.log(e.data.json()));
```

**Comment by alexsuh7** [comment]
Hi , 
Thanks you for the suggestion , 

Note that this will allows us to track any message handled by the service worker .
We can probably add our own analytics on top of it , to validate push message arrive to the client .

Yet we still remain blind about failures form within the firebase SDK itself , especially , when using the 'notification' payload. As in this case , the message is handled entirely inside the FCM SDK (in case browser window is not visible).

We can add an error handler for the service worker 
e.g. 
self.addEventListener('error', function(e) {
  console.log(e.filename, e.lineno, e.colno, e.message);
});

Yet , this will only work as long as errors are propagated to service worker from inside the FCM SDK.

One approach that should not cause stability issues and flooding the browser developer console with meaningless error logs , might be to add support for optional error handler to FCM SDK .

something like

`
messaging.addEventListener('error',e=> /*do something*/)
`
and let whoever using the library decide what should be done in case of errors.

**Comment by mmermerkaya** [comment]
Thanks for the suggestion. We're currently in the process of creating a better API that includes the ability to do what you suggested, so I'll close this issue.
