### ISSUE TITLE
Error: firebase auth/network-request-failed with sw-precache's navigateFallback

### ISSUE THREAD

**Issue by Shyam-Chen** [firebase/firebase-js-sdk#19]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 3.6.3
  * Library version: 3.6.3
  * Firebase Product: auth

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

```bash
Error: auth/network-request-failed
```

#### Relevant Code:

```js
signInButton.onclick = () => {
  const provider = new firebase.auth.GoogleAuthProvider();
  firebase.auth().signInWithPopup(provider);
};
```

**Comment by bojeil-google** [comment]
Information is really scarce here. 
signInWithPopup will embed a hidden iframe https://[AUTH_DOMAIN]/__/auth/iframe. This is needed to pass back the OAuth result to the page. Can you please provide more context on this?

**Comment by Shyam-Chen** [comment]
https://github.com/Shyam-Chen/Frontend-Starter-Kit/blob/master/tools/utils/service-worker.js#L17

When I enable sw-precache's `navigateFallback` option will return 404.

**Comment by bojeil-google** [comment]
I honestly am not familiar with sw-precache module. I am also forced to speculate on what is going on. Steps to reproduce are needed. 
I do not recommend pre-caching anything under /__/auth/. 
signInWithPopup will late load gapi.iframes which will then embed /__/auth/iframe. Offline, this will fail with the error you are seeing. However, trying again when the network connection is regained will allow the operation to succeed.

**Comment by FluorescentHallucinogen** [comment]
See https://firebase.google.com/docs/hosting/reserved-urls#reserved_urls_and_service_workers.

**Comment by Shyam-Chen** [comment]
@FluorescentHallucinogen Thanks.
