### ISSUE TITLE
FR: support nested arrays in firestore, just like in admin-node-sdk

### ISSUE THREAD

**Issue by mmlleevvyy** [firebase/firebase-js-sdk#193]
### Describe your environment

  * Operating System version: Mac OS 10.13
  * Firebase SDK version: 4.5.0
  * Firebase Product: firestore

### Describe the problem
When saving a field of array type, where each array's item is an object with some array fields/properties, the error is thrown "DocumentReference.set() called with invalid data. Nested arrays are not supported". But admin-node-sdk allows to write such data and in the firestore console, nested arrays are properly shown (although you cannot add nested array).

#### Steps to reproduce:
```
doc(..).set({arrayField: [
 {someArrayProperty: [
   {someField: ["test", "test"]}
  ]},
 {someArrayProperty: [
   {someField: ["test", "test"]}
  ]}
]})
```

**Comment by kato1628** [comment]
+1

**Comment by goekaypamuk** [comment]
+1

**Comment by bjellicious** [comment]
+1
Also: https://stackoverflow.com/questions/46593953/nested-arrays-are-not-supported

**Comment by notsonotso** [comment]
Pretty serious issue... 

+984721

**Comment by wilhuff** [comment]
The [4.6.0 release](https://firebase.google.com/support/release-notes/js#4.6.0) that went out today includes pull https://github.com/firebase/firebase-js-sdk/pull/228 which addresses this.

Note that directly nested arrays are still unsupported (and is a backend restriction).

**Comment by mmlleevvyy** [comment]
@wilhuff great! Thanks

**Comment by notsonotso** [comment]
@wilhuff Fantastic. Thanks.

**Comment by kato1628** [comment]
@wilhuff thx:)

**Comment by yoiang** [comment]
I apologize for not knowing the difference, can someone post an example of directly nested vs indirectly nested arrays?

**Comment by wilhuff** [comment]
Your examples describe this perfectly.

**Comment by jaonoctus** [comment]
Same here..

**Comment by wilhuff** [comment]
@jaonoctus I don't understand your comment.

Release 4.6.0 fixed indirectly nested arrays (i.e. arrays can contain objects can contain arrays).

Directly nested arrays (i.e. arrays directly containing other arrays) are unsupported and there aren't any plans to do so given backend limitations.

When you say "Same here" are you
  * saying that indirectly nested arrays aren't working for you even after release 4.6.0?
  * expressing interest in directly nested arrays?

The former would be a serious regression we need to look into. The latter I can't really help with given the complexity of removing the limitation.

**Comment by Modestas** [comment]
Trying to add from Firestore Database UI:
```
  {
    test: [
      {
        test2: [ 
           { 
             test3: "test4" 
           }
        ]
      }
    ]
  }
```

Results in `Unable to save field`.

**Comment by mikelehen** [comment]
@Modestas Thanks for the report. I've pinged the folks who work on the console UI to see if we can get this resolved. In the meantime you may have to do that write manually via the SDK. Sorry for the convenience!

**Comment by jaschaio** [comment]
Will support for `directly nested arrays` ever come or was the hint that its a `backend restriction` basicly saying that it will never come?

Is this somewhere mentioned within the documentation? I have just found out about it by running into this error after already building parts of the UI with directly nested arrays 😖

**Comment by rockwotj** [comment]
@jaschaio It's in the docs: https://firebase.google.com/docs/firestore/manage-data/data-types#data_types

Also, at some point in the future yes we'll be able to support nested arrays - but it's not going to happen anytime soon. Sorry I can't be more specific, but I won't bank on directly nesting arrays for any apps you're building at the moment.
