### ISSUE TITLE
FR: Sign in with Apple Support 

### ISSUE THREAD

**Issue by jacobg** [firebase/firebase-js-sdk#1931]
Add support for authenticating with Sign in with Apple. With the release of iOS 13, Apple will require that you implement this to be listed on the App Store if your App uses other 3rd party login providers.

> Sign In with Apple will be available for beta testing this summer. It will be required as an option for users in apps that support third-party sign-in when it is commercially available later this year.

https://developer.apple.com/sign-in-with-apple/
https://developer.apple.com/documentation/signinwithapplerestapi
https://developer.apple.com/news/?id=06032019j

There is already an open issue and PR in the Firebase iOS SDK for Sign In With Apple Support, but hybrid apps (e.g., Cordova) will also need this support in the JS SDK.

https://github.com/firebase/firebase-ios-sdk/issues/3145
https://github.com/firebase/firebase-ios-sdk/pull/3162

**Comment by amkoehler** [comment]
In addition to hybrid apps, IMO this makes sense to add as another available provider for use in any web application.

**Comment by bojeil-google** [comment]
Thanks for the feature request. The Firebase Auth team is already looking into this.

**Comment by Shoshin23** [comment]
Hi! 

Now that iOS 13 and 13.1 are publicly available, is it possible for us to have sign in with apple use it Firebase Auth?

**Comment by vankhuong** [comment]
Thanks for the feature request. Most people are looking into this.

**Comment by bojeil-google** [comment]
We launched Apple sign-in support today across all 3 platforms.

https://firebase.google.com/docs/auth/ios/apple
https://firebase.google.com/docs/auth/android/apple
https://firebase.google.com/docs/auth/web/apple
