### ISSUE TITLE
Microsoft Auth - not possible use redirect_uri for my domain

### ISSUE THREAD

**Issue by GuilhermeBCC** [firebase/firebase-js-sdk#1934]
### [REQUIRED] Describe the problem

In https://firebase.google.com/docs/auth/web/microsoft-oauth#before_you_begin 4. b.

"When registering apps with these providers, be sure to register the ***.firebaseapp.com** domain for your project as the redirect domain for your app."

But my App use authDomain: mydomain.com

When I'm going to log in I try to set redirect_uri in OAuthProvider: 

auth.OAuthProvider('microsoft')setCustomParameters({ redirect_uri: 'https://myapp.firebaseapp.com/__/auth/handler' })

This is not possible because of this.
"reserved required OAuth 2.0 parameters such as `client_id`, `redirect_uri`,  `scope`, `response_type` and `state` are not allowed and will be ignored"

I need a solution

You can create fireAuthDomain (initializeApp) and use it when the user attempts to authenticate with the Microsoft provider.

**Comment by wti806** [comment]
You need to register the redirect uri from azure console: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
Instead of passing it as a custom parameter.

**Comment by GuilhermeBCC** [comment]
I think you do not understand, it's working, but it's not possible to use my domain (myapp.com) in my firebase configuration file.

**Comment by wti806** [comment]
check this post: https://stackoverflow.com/questions/44815580/how-to-replace-the-myapp-123-firebaseapp-com-with-my-custom-domain-myapp-com
You need to whitelist your custom domain in azure console and firebase console, and also change the authDomain config to your custom one in the config.authDomain when you initialize firebase.

**Comment by GuilhermeBCC** [comment]
Despite the firebase's doc being restricted to * .firebaseapp.com it worked by swapping in the App and in the azure console for myapp.com. Thanks!. However, they should arrange the documentation.
