### ISSUE TITLE
Rollup message outdated when using sdk in node enviroment

### ISSUE THREAD

**Issue by kaleidawave** [firebase/firebase-js-sdk#1938]
### Environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: firebase@6.2.4
  * Firebase Product: _____ (auth, database, storage, etc)

### Problem

When using this sdk (not the admin one) in a node environment the suggested fix is outdated. It suggests for rollup:
```
If using Rollup, use the rollup-plugin-node-resolve plugin and set "module" to false and "main" to true: https://github.com/rollup/rollup-plugin-node-resolve
```

However according to the usage on [their readme](https://github.com/rollup/rollup-plugin-node-resolve#usage) it says that the `module` and `main` fields are depreciated and replaced by `mainFields`. Can we see a update to this error message which uses `mainFields`

**Comment by p3sn** [comment]
Maybe related, I see this message:

> Rollup: Missing Export
> 'openDb' is not exported by node_modules/@firebase/installations/node_modules/idb/build/idb.js

I'm using StencilJS and Ionic.

**Comment by winstonzhao** [comment]
> Maybe related, I see this message:
> 
> > Rollup: Missing Export
> > 'openDb' is not exported by node_modules/@firebase/installations/node_modules/idb/build/idb.js
> 
> I'm using StencilJS and Ionic.

I'm getting the same error using the same things.

**Comment by kaleidawave** [comment]
Those are not at all related, I was commenting that the console error message for building the standard firebase sdk in a node/ non-browser environment using rollup needs to be updated. It is not the error that is the problem it is the fact the suggested fix in the error message is outdated.

**Comment by corysmc** [comment]
@p3sn and @winstonzhao did you figure this out? I'm just now seeing this myself. Stencil, Ionic, and Firebase.
Thanks

**Comment by corysmc** [comment]
Figured it out: Here's what I did to fix it @p3sn and @winstonzhao 
Uninstalled all of my @firebase/app, /auth, /firestore, /functions, /performance packages and ran
`npm i firebase`
which installed `"firebase": "^6.3.0",`

Then imported each
```ts
import { firebase } from '@firebase/app';
import '@firebase/auth';
import '@firebase/firestore';
import '@firebase/functions';
import '@firebase/performance';
```

**Comment by winstonzhao** [comment]
> Figured it out: Here's what I did to fix it @p3sn and @winstonzhao
> Uninstalled all of my @firebase/app, /auth, /firestore, /functions, /performance packages and ran
> `npm i firebase`
> which installed `"firebase": "^6.3.0",`
> 
> Then imported each
> 
> ```ts
> import { firebase } from '@firebase/app';
> import '@firebase/auth';
> import '@firebase/firestore';
> import '@firebase/functions';
> import '@firebase/performance';
> ```
> 
> Then in my stencil.config.ts file:
> 
> ```ts
> commonjs: {
>     namedExports: {
>       // left-hand side can be an absolute path, a path
>       // relative to the current directory, or the name
>       // of a module in node_modules
>       'node_modules/idb/build/idb.js': ['openDb'],
>       'node_modules/firebase/dist/index.cjs.js': ['initializeApp', 'firestore']
>     }
>   },
> ```

I did the same after asking on Slack.

**Comment by p3sn** [comment]
Solution was to use firebase/app instead of firebase.

Op di 16 jul. 2019 07:31 schreef Cory McArthur <notifications@github.com>:

**Comment by hsubox76** [comment]
Well, the Rollup warning message is updated: https://github.com/firebase/firebase-js-sdk/pull/1949 and should go into the next release.  If anyone's still having problems with the other error (seems to be solved?), feel free to open a separate issue so we can track it.

**Comment by Feiyang1** [comment]
Warning message fix was released in 6.3.1.

**Comment by p3sn** [comment]
> @p3sn and @winstonzhao did you figure this out? I'm just now seeing this myself. Stencil, Ionic, and Firebase.
> Thanks

I fixed it by importing firebase/app instead of firebase.

**Comment by splitinfinities** [comment]
This popped for me today, and I had to make the namedExport path's relative: 

```
commonjs: {
    namedExports: {
      './node_modules/idb/build/idb.js': ['openDb'],
      './node_modules/firebase/dist/index.cjs.js': ['initializeApp', 'firestore']
    }
  },
```
