### ISSUE TITLE
JS properties named '_xyz' are broken by minification.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-js-sdk#194]
If our code defines a property named _xyz, e.g.:

```
public get _databaseId(): DatabaseId {
  return this._config.databaseId;
}
```

Then usages of the property get minified in our build, but the actual property does not, leading to runtime errors.

I had to work around this (see https://github.com/firebase/firebase-js-sdk/pull/197) to fix a customer-reported bug in the minified build.

**Comment by jshcrowthe** [comment]
This was done to be super aggressive about generating our CDN bundles. Until we no longer want to support a "prod ready" CDN build, allowing property mangling is something that we'd like to support.
