### ISSUE TITLE
Can't link user with OAuthCredential

### ISSUE THREAD

**Issue by nalbion** [firebase/firebase-js-sdk#1943]
* Operating System version: Linux
  * Browser version: Chrome 75
  * Firebase SDK version: 6.2.4
  * Firebase Product: auth v0.11.3

https://stackoverflow.com/questions/56884571/linking-anonymous-firebase-user-with-custom-token-user

I'm trying to allow anonymous users to store data in Firebase Realtime Database, and then when they later log in with a 3rd party OAuth provider which is not directly supported by Firebase, then they can link and migrate their existing data.

```javascript
let currentUser = auth.currentUser;
if (!currentUser) {
    currentUser = (await auth.signInAnonymously()).user;
}

// when they log in via LinkedIn/Slack etc my back-end auth service will provide a custom access token:
const accessToken = {
  sub: my-service-account@my-firebase-project.iam.gserviceaccount.com,
  iss: my-service-account@my-firebase-project.iam.gserviceaccount.com,
  aud: "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
  uid: 1234
  // other claims...
}

// and I can successfully log into Firebase using this token:
const newUser = await auth.signInWithCustomToken(accessToken);
```

All good so far - but how do I link the two? According to the [account linking documentation](https://firebase.google.com/docs/auth/web/account-linking) I should be able to do something like this:

```javascript
if (currentUser && currentUser.isAnonymous) {
    const provider = new firebase.auth.OAuthProvider('myprovider');
    const credential = provider.credential(token, token);
    const linkedUser = await currentUser.linkWithCredential(credential);
}
```

However, firebase sends a request to https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion

```
{
  idToken: {
    "provider_id": "anonymous",
    "iss": "https://securetoken.google.com/my-firebase-project",
    "aud": "my-firebase-project",
    "user_id": anonymousUserId,
    "sub": anonymousUserId,
    "firebase": {
      "identities": {},
      "sign_in_provider": "anonymous"
    }
  }
  postBody: {
    id_token: token, 
    access_token: token
    providerId: "myprovider"
  }
  requestUri: "http://localhost"
  returnIdpCredential: true
  returnSecureToken: true
}
```
and I get a 400 error response:

```
INVALID_CREDENTIAL_OR_PROVIDER_ID : Invalid IdP response/credential: http://localhost?id_token=${token}&access_token=${token}&provider=myprovider
```

My front-end is https running on port 3000, and my backend is at /api/oauth/, also https

- how do you configure a different requestUri?
- what is the endpoint supposed to do?

**Comment by nalbion** [comment]
...the "http://localhost" is hard-coded - I don't understand why

https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/authcredential.js#L418
```javascript
var request = {
    'postBody': goog.Uri.QueryData.createFromMap(postBody).toString(),
    // Always use http://localhost.
    'requestUri': 'http://localhost'
  };
```

**Comment by wti806** [comment]
We don't support linking custom token to anonymous user. The reason is, when you create a custom token, we already set the UID of the user. And the anonymous user has a different UID. We don't know how you want to handle the merge of two users. In your case, you can retrieve the date associate with the anonymous user, sign in with custom token, and copy the data to the custom token user.

**Comment by bojeil-google** [comment]
Check out this post: https://stackoverflow.com/questions/40171663/linking-custom-auth-provider-with-firebase
Custom authentication is not a provider. To "link" an unsupported provider to anonymous account, you need the following:
1. Verify the custom OAuth provider on your server and pass the anonymous user ID token (you will need to verify that on your server before the next step)
2. You then create an entry in a map for the custom OAuth provider uid to the Firebase UID (the anonymous user's uid).

The next time the user signs in with the custom OAuth provider, you get the OAuth provider uid and lookup the corresponding Firebase UID from the map and mint a custom token for that.

**Comment by rommelpe** [comment]
Haven’t heard from you in a while, @nalbion. I would like to check if you are still having issues or clarifications here. Just leave a comment and we are happy to look into it.
