### ISSUE TITLE
onSnapshot "add"-listener returns thrice

### ISSUE THREAD

**Issue by olaven** [firebase/firebase-js-sdk#1947]
### Describe your environment

  * Operating System version: macOS Mojave 
  * Browser version: Chrome, 75.0.3770.100
  * Firebase SDK version: `^6.1.0`
  * Firebase Product: firestore

### Describe the problem
I am listening for changes on firestore-collections. 
When the change-type is "added", i trigger a callback. 
That callback is trigger three times, even if just one document 
is added to Firestore. 

#### Steps to reproduce:
Listen for "add"-changes on firestore-collection. 

#### Relevant Code:

```javascript
export default class Listener<T> {

    listen = (query: firebase.firestore.Query) => {

        return query.onSnapshot(snapshot => {

            snapshot.docChanges().forEach(change => {

                const document = (change.doc.data()) as T
                switch (change.type) {

                    case "added":
                        console.log("this is triggered three times"); 
                        break;
                }
            }); 
        }); 
    }
}
```

**Comment by wilhuff** [comment]
Hi, the behavior of this code depends a lot on the query you're running and the data you have in place. For example, if you query a collection that has three documents in it, this code will show `this is triggered three times` three times. Could you please show a complete example of what you believe is incorrect?

**Comment by olaven** [comment]
Hi, thanks for answering! Of course. 

I am listening to new messages in a chat-system. 
The query is like this: 
```typescript
listen = async (thread: string, callback: (message: Message) => void) => {

        const query = this.query.new()
            .where(input.where("thread", "==", thread))
            .where(input.where("time", ">=", Date.now()))
            .rawQuery();

        this.listener.onAdd = callback;
        await this.listener.listen(query);
    };
```

I expect the `time`-check to only return _new_ messages. `time` is a field on the documents that I have added myself. 

When a new message is sent, _one_ message shows up in Firestore (checking via the console) however that one message is caught _thrice_ in the listener. These are duplicates and not three different messages. 

It also just happens sometimes, not always. 

`this.query` is just a wrapper around regular Firetore Queries. `this.listener` is the one described in the original issue, except that it returns the message in a callback instead of just logging, i.e.: 
```typescript
case "added":
    this.callback(document); 
    break;
```

**Comment by wilhuff** [comment]
I can't reproduce this problem. Here's my working example, running the web SDK in node 8.16:

```js
const firebase = require('firebase');
require('firebase/firestore');

firebase.initializeApp({
  projectId: // supply yours here
});

const db = firebase.firestore();

async function add(collection, thread, time) {
  return collection.add({
    thread,
    time,
  });
}

async function main() {
  const messages = db.collection('messages');

  // Delete existing data
  const existing = await messages.get();
  const deletes = existing.docs.map(snap => snap.ref.delete());
  await Promise.all(deletes);

  // Verify no existing data
  const empty = await messages.get();
  console.log('===== initial state =====');
  console.log(empty.docs.map(doc => doc.data()));

  // Pre-seed with data that shouldn't show
  await add(messages, 't1', 1);
  await add(messages, 't2', 2);

  // Query for time after existing messages
  const query = messages.where('thread', '==', 't1')
      .where('time', '>=', 3);

  const unsubscribe = query.onSnapshot(snap => {
    console.log('===== new snapshot =====');
    console.log(snap.docs.map(doc => doc.data()));

    snap.docChanges().forEach(change => {
      const doc = change.doc.data();
      if (change.type == 'added') {
        console.log(`added thread: ${doc.thread}, time: ${doc.time}`);
      }
    });
  });

  console.log('===== adding new messages =====')
  await add(messages, 't2', 4);  // no snapshot
  await add(messages, 't1', 5);
  await add(messages, 't1', 6);

  unsubscribe();
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch(err => {
    console.log(err);
    process.exit(1);
  });
```

I get this output every time I run it:

```
===== new snapshot =====
[]
===== new snapshot =====
[ { thread: 't1', time: 5 } ]
added thread: t1, time: 5
===== new snapshot =====
[ { thread: 't1', time: 5 }, { thread: 't1', time: 6 } ]
added thread: t1, time: 6
```

Which events we deliver when is something that's very well tested in our system so given the above I suspect that there's some issue in the code you've written on top of Firestore. Even so, it's possible we have a bug, and it's possible my example doesn't capture the case you're actually describing. If you can supply a working example that shows this issue I'll happily investigate further.

**Comment by olaven** [comment]
Thank you for your example, it was very hepful! 
As it turns out, I was not unsubscribing properly when switching between different "threads" (conversations in a chat-app). 

It was also partly due to not me not properly understanding how React `useEffect` works. If someone has a similar issue: 

```typescript 

const listen = async (setUnsubscribe) => {

    const unsubscribe = await messageAPI.listen(props.thread.id, message => {

      console.log("new message: ", message);
    });

    console.log("oensker aa sette til: ", unsubscribe);
    setUnsubscribe(unsubscribe);
};

useEffect(() => {

    let unsubscribe = () => {};
    listen(u => {unsubscribe = u});

    return () => {

      console.log("unmounting");
      unsubscribe();
    }
  }, [ context.user, props.thread ]);
```
