### ISSUE TITLE
Can't add performance monitoring to SSR web app

### ISSUE THREAD

**Issue by patrickgordon** [firebase/firebase-js-sdk#1955]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04
  * Browser version: Chrome 70.x.x
  * Firebase SDK version: ^6.1.1
  * Firebase Product: performance

### [REQUIRED] Describe the problem
When using SSR, specifically, Next.js, and importing performance from the library, the server explodes due to trying to access window.

#### Steps to reproduce:
SSR rendered app with Next.js

Add the below code to the usual imports and setup for firebase.
```
import "firebase/performance";
```

Results in:
```
[ error ] ReferenceError: window is not defined
    at Object.<anonymous> (/home/patrick/sites/interior-mood-boards/node_modules/@firebase/performance/dist/index.cjs.js:1196:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/patrick/sites/interior-mood-boards/node_modules/firebase/performance/dist/index.cjs.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by lupas** [comment]
@patrickgordon 
Same issue in my VueJs module here https://github.com/lupas/nuxt-fire/issues/31#issuecomment-510875394, couldn't figure out how to make it work yet. Would be interested if you find a solution.

I do a conditional import only on client-side (which might be the solution for you too), but for some reason firebase/performance does not get imported or added to the Firebase object.

**Comment by patrickgordon** [comment]
@lupas I also tried that but had no success.

**Comment by jpbow** [comment]
Have you tried [dynamic imports](https://nextjs.org/docs#with-no-ssr )?
Maybe something like this would work: `dynamic(() => import('firebase/performance'), {
  ssr: false
});`

**Comment by ralcar** [comment]
Any update on this? I have a React App with SSR, downloaded 6.3.1 and get:

ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open 'C:\<my path>\node_modules\firebase\app\dist\index.esm.js'

I also got the  window is not defined earlier with other version

**Comment by ylihao** [comment]
Use [Dynamic Imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) and place your `import()` in the `ComponentDidMount()` life cycle of `pages/index.js` so that it will only import the Firebase performance library when it starts rendering on the client side.

Remember to check for `!firebase.apps.length` before you initialize Firebase or you may run into an error of trying to initialize multiple Firebase instances.

I'm currently working on a Next.js project and this works for me. Hope this helps.

**Comment by lupas** [comment]
Issue seems to be fixed with Firebase [v.6.3.2](https://firebase.google.com/support/release-notes/js)+. I at least got it to work now in my [VueJs/Nuxt module](https://github.com/lupas/nuxt-fire/issues/31). <:o)

**Comment by alikn** [comment]
Yes, the issue should be fixed in the last release. Thanks for reporting the issue.

**Comment by patrickgordon** [comment]
Nice, thanks for the quick turn around.
