### ISSUE TITLE
FieldValue.increment not working on nested object

### ISSUE THREAD

**Issue by pjc0247** [firebase/firebase-js-sdk#1956]
I have a object for balances(inventory) which contains various type of items.
however `increment` does not work well with this.

Here's an example

```ts
// This works
await this.ref.update({'gold': FieldValue.increment(1)});

// This does not work
await this.ref.update({
  balances: {
    [key]: FieldValue.increment(value)
  }
});
```

**Comment by var-const** [comment]
If you'd like to update an existing nested field, you need to specify a [dot-separated path](https://firebase.google.com/docs/reference/js/firebase.firestore.html#updatedata) to the field as a key in the dictionary you supply to `update`. So in this case, it would look like this:
```javascript
await this.ref.update({
  'balances.${key}': FieldValue.increment(value)
});
```
This snippet should work as expected.

The behavior of the code snippet you posted is different -- it overwrites the field `balances` with a completely new dictionary. When `FieldValue.increment` is [applied to a not-yet-existing field](https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue.html#increment), it behaves   as if the field has a zero value, effectively setting the field to the value of `increment`.

Please let me know if the code snippet I posted works for you. I will close the issue for now, but feel free to follow up on this thread if you're still having any trouble while using a dot-separated path.
