### ISSUE TITLE
user.getIdToken() returns Invalid ID token

### ISSUE THREAD

**Issue by rohantalesara** [firebase/firebase-js-sdk#1958]
### Environment

  * Operating System version: Debian GNU/Linux 9.9 (stretch)
  * Browser version: Chrome 75 in Windows 10
  * Firebase SDK version: 6.1.1
  * Firebase Product: auth

### The problem

I am building a traditional server-rendered website using firebaseui-web with Google Sign-in. I'm using firebase session cookies for authentication as described [here](https://firebase.google.com/docs/auth/admin/manage-cookies).

On the backend, I use firebase-admin to verify the token and create a session cookie.

The problem is that when I send the ID token generated by user.getIdToken() to my backend for verification/creating a cookie, I get the following error:

Server response: {
   "error": {
      "code": 400,
      "message": "INVALID_ID_TOKEN",
      "errors": [
        {
          "message": "INVALID_ID_TOKEN",
          "domain": "global",
          "reason": "invalid"
        }
      ]
    }
  }
I tried verifying the token on https://www.googleapis.com/oauth2/v1/tokeninfo, and I get the same error.
If I check on jwt.io, it says Invalid signature.

#### Relevant Code:
This is how my client side code looks like:

```javascript
signInSuccessWithAuthResult: function(authResult, redirectUrl) { 
                var user = authResult.user;
                var credential = authResult.credential;

                // Do something with the returned AuthResult.
                // Return type determines whether we continue the redirect automatically
                // or whether we leave that to developer to handle.

                user.getIdToken().then( function(idToken) {
                    var xhr = new XMLHttpRequest();
                    xhr.open("POST", "http://example.com/sessionLogin", true);
                    xhr.setRequestHeader('Content-type', 'application/json;charset=UTF-8');
                    xhr.onreadystatechange = function() {
                        if (this.readyState == 4 && this.status == 200) {
                          alert("It worked");
                        }
                        else{
                            alert("Didnt' work");
                        console.log(xhr.statusText);
                        }
                    };
                    var data = JSON.stringify({"idToken":String(idToken)});
                    xhr.send(data);
                    window.location.assign("http://example.com/home");
                });
                return false;
          }
```

Server side code:
```python
import firebase_admin
id_token = request.json['idToken']
expires_in = datetime.timedelta(days=5)
try:
            # Create the session cookie. This will also verify the ID token in the process.
            # The session cookie will have the same claims as the ID token.
            session_cookie = firebase_admin.auth.create_session_cookie(id_token, expires_in=expires_in)
            response = json.dumps({'status': 'success'})
            # Set cookie policy for session cookie.
            expires = datetime.datetime.now() + expires_in
            response.set_cookie(
                'session', session_cookie, expires=expires, httponly=True, secure=True)
            return response
except firebase_admin.auth.AuthError as e:
            print(e)
            return abort(401, 'Failed to create a session cookie')
```

**Comment by bojeil-google** [comment]
Can you open an issue with [Firebase Support](https://firebase.google.com/support). This is a client SDK repo. You will need to provide sample ID tokens and project related sensitive information which are better suited for a private channel.

**Comment by rohantalesara** [comment]
> Can you open an issue with [Firebase Support](https://firebase.google.com/support). This is a client SDK repo. You will need to provide sample ID tokens and project related sensitive information which are better suited for a private channel.

I have opened an issue with Firebase Support. In the mean time, is there anything that you think that I'm doing wrong based on the code posted? I'm sorry I have to ask this as this issue is blocking any further work and there doesn't seem to be a work around.

**Comment by rohantalesara** [comment]
People have posted similar issue here: https://github.com/firebase/firebase-cpp-sdk/issues/3

**Comment by ashishtyagi12** [comment]
I am running into similar problem. I am getting token using firebase client sdk. 
IdTokenResult idToken = await currentUser.getIdToken(refresh: true);
    var headers = {HttpHeaders.authorizationHeader: "Bearer ${idToken.token}"};
Request is being rejected by server.If I check on jwt.io, it says Invalid signature.

**Comment by wti806** [comment]
@ashishtyagi12 Did you provide the public/private key when you decode the jwt in jwt.io? As @bojeil-google suggested, you'd better open an issue with Firebase support for issue like this since you need to provide some information about your project. Thanks

**Comment by dhaval-patel** [comment]
@ashishtyagi12 Have you found any solution? I am also facing similar issue.

**Comment by ashishtyagi12** [comment]
Hi Dhaval,
I was using role-based authentication on a cloud function which was failing. I used the following workaround. 
I turned off the role-based authentication on the function and instead switched to programmatic validation. 
So on the client, I am passing ID token in header **(without bearer tag)**

**IdTokenResult idToken = await currentUser.getIdToken(refresh: true);
var headers = {HttpHeaders.authorizationHeader: "${idToken.token}"};**

In cloud function, I am validating token 
**const admin = require('firebase-admin');
const idToken = req.headers['authorization'];
const decodedToken = await admin.auth().verifyIdToken(idToken);**

The invalid token will result in an error being thrown while decoding. This worked out for me.
I still need to dig in why role-based authentication was not working but now I suspect it might be because I was adding 'bearer' tag to the client previously (example in firebase docs use bearer tag). 
Still, need to verify that.

**Comment by emichristiansen** [comment]
I've found that the valid token can be retrieved from from result.user.ma;

`firebase.auth().signInWithPopup(provider).then((result) => {
        var user = result.user;
        var id_token = user.ma;
 })`

**Comment by yuchenshi** [comment]
As @wti806 and @bojeil-google mentioned, it's better to open a support ticket where you can share the exact token and your private keys. We cannot really help to validate the signature without your private key, but it would be a really bad idea to post your private key on a GiHub issue publicly.

Another approach would be trying to create a minimal repro which can help a lot with moving this issue forward. For example, you can create a simple `index.html`, include the Firebase SDKs and add some code to retrieve the ID token. Then create a Node.js script with the Admin SDK detailing how the validation is done. A GitHub repository or gist is perfect for these things -- just make sure any private keys are not uploaded and provide instructions instead.

**Comment by hawkeng** [comment]
What is the current status of this? I'm having exactly the same issue

**Comment by yuchenshi** [comment]
We currently still recommend reaching out to support for each individual case. (But if you think you've found a bug in Firebase and not your own application, great! Just send us a minimal repro as mentioned above and we will look into it.)
