### ISSUE TITLE
firebase.auth.ConfirmationResult.confirm() invokes signInAndRetrieveDataWithCredential

### ISSUE THREAD

**Issue by henrylearn2rock** [firebase/firebase-js-sdk#1959]
### [REQUIRED] Describe your environment

  * Operating System version: Win10
  * Browser version: Chrome  75.0.3770.100 (Official Build) (64-bit)
  * Firebase SDK version: 6.2.4
  * Firebase Product: auth 

#### Steps to reproduce:

With signInWithPhoneNumber, calling confirm() method in the returned ConfirmationResult https://firebase.google.com/docs/reference/js/firebase.auth.ConfirmationResult#confirm would result depreciation warning in console log:

> firebase.auth.Auth.prototype.signInAndRetrieveDataWithCredential is deprecated. Please use firebase.auth.Auth.prototype.signInWithCredential instead.
> -- | -- | -- | --
>   | Ue | @ | auth.esm.js?b7aa:93
>   | k.nb | @ | auth.esm.js?b7aa:327
>   | jl.confirm | @ | auth.esm.js?b7aa:275
>   | d | @ | auth.esm.js?b7aa:349

#### Relevant Code:
```
firebase
            .auth()
            .signInWithPhoneNumber(phoneNumber, appVerifier)
            .then(confirmationResult => confirmationResult.confirm(verificationCode)
```

**Comment by wti806** [comment]
@henrylearn2rock We fixed this issue in https://github.com/firebase/firebase-js-sdk/commit/99ba9952d84d1da2e87f7c7ce0fe802bf0de836e. It will be in this week's release. Thanks!
