### ISSUE TITLE
Firebase Storage Rules with strange behavior

### ISSUE THREAD

**Issue by GuilhermeBCC** [firebase/firebase-js-sdk#1979]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10
  * Browser version:  Google Chrome 75
  * Firebase SDK version: _____
  * Firebase Product: storage

### [REQUIRED] Describe the problem

```javascript
service firebase.storage {
   match /b/{bucket}/o {
      match /files/{eid}/{fileName} {
         allow read: if request.auth != null;
         allow write: if request.auth != null && request.resource.size < 15 * 1024 * 1024
      }
   }
}
```
use the / USERS word in place of / FILES causes this error when testing on the simulator

![Sem título](https://user-images.githubusercontent.com/28517010/61090161-f4ce3780-a413-11e9-8c4d-65203d3af02b.png)

#### Relevant Code:

edit: It is not the word. Depending on the query does not enter the rule. But the error persists and I do not know what I'm doing wrong.

**Comment by RohanTalip** [comment]
@GuilhermeBCC, did you try adding a semicolon at the end of line 5, i.e. the "allow write" line?

**Comment by GuilhermeBCC** [comment]
Yes, has the semicolon I should have taken when editing the spaces when posting the question

**Comment by avolkovi** [comment]
@GuilhermeBCC did you set the object metadata with appropriate size when testing? I'm having a hard time replicating this issue

![2O2O8X3X7xp](https://user-images.githubusercontent.com/1316937/62235819-99dc9000-b382-11e9-9aa3-e55be894b3f3.png)

**Comment by GuilhermeBCC** [comment]
Hello @avolkovi 

I'll close because it's working I think the problem is in the simulator.
