### ISSUE TITLE
API restrictions problem: Requests from this Android client application <empty> are blocked

### ISSUE THREAD

**Issue by jvkxhola** [firebase/firebase-js-sdk#1982]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Mojave
  * Firebase SDK version: ˆ6.0.2
  * Firebase Product: Auth
  * Framework: Ionic 3 + Cordova 9

### [REQUIRED] Describe the problem
Hello,

I'm having an issue when authenticating with signInWithCredetal(credential) when using it to authenticate with phone on Android. The issue started after I restrict my API for Android with Application name and SHA-1 keys. 

Error message that is displayed below:

`code: "auth/internal-error"`

`message: "{"error":{"code":403,"message":"Requests from this Android client application <empty> are blocked.","errors":[{"message":"Requests from this Android client application <empty> are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}"`

It looks like application name is not being sent. Anyone has ever being in this situation? It's working if I remove the restrictions in API

#### Relevant Code:
```
( < any > window).FirebasePlugin.verifyPhoneNumber(this.completePhoneNumber, 5,
          (credential) => {
            if (!credential.instantVerification) {

              this.smsModal.present();

              // Set function to run when modal is closed
              this.smsModal.onDidDismiss(output => {

                this.nativePhoneVerify(output, credential)
                  .then((data) => {
                    resolve(data);
                  }).catch((error) => {
                    reject({message: 'Invalid', error: error});
                  });
              })
            } else {
              // IF IT IS INSTANT VERIFICATION

                this.nativePhoneVerify(credential.code, credential)
                  .then((data: any) => {
                    resolve(data);
                  }).catch((error) => {
                    reject({message: 'Invalid', error: error});
                  });
              }
            }
          }, (error) => {
            reject({message: 'Invalid number', error: error});
          }
        );
```

```
public nativePhoneVerify(confirmationCode: string, credential: any): Promise < any > {
    return new Promise((resolve, reject) => {
      let signInCredential
      // get signInCredential returned from the verification code
      if (this.platform.is('android')) {
        // for Android
        signInCredential = firebase.auth.PhoneAuthProvider.credential(
          credential.verificationId, confirmationCode);
      } else {
        // for IOS
        signInCredential = firebase.auth.PhoneAuthProvider.credential(
          credential, confirmationCode);
      }
      // If the credential is correct, sign user in
      resolve(firebase.auth().signInWithCredential(signInCredential)); // <-- Problem is here
    })
```

Thanks for the attention and support

---- UPDATE

I'm getting same behaviour for IOS

**Comment by wti806** [comment]
@jvkxhola This is expected. Since cordova iOS/Android apps are still web based, the underlying implementation are using javascript APIs rather than iOS/Android native APIs. As a result, we are not able to pass the bundle ID or App name to the Google APIs. For web, only the origin/referer is used to restrict the API.

**Comment by jvkxhola** [comment]
Ok, makes sense. Not much to do about that, right? Do you know another way I could use cordova to authenticate with phone number?

**Comment by rommelpe** [comment]
We currently don't support [phone authentication for cordova](https://firebase.google.com/support/guides/environments_js-sdk#other_environments) apps.
