### ISSUE TITLE
No matching version found for tslib@1.9.3

### ISSUE THREAD

**Issue by Matttaylor8910** [firebase/firebase-js-sdk#1988]
### My environment

  * Operating System version: MacOS Mojave 10.14.5 (18F132)
  * Browser version: n/a
  * Firebase SDK version: 6.3.0 (latest as of writing)
  * Firebase Product: just installing the js sdk

#### Problem / Steps to reproduce:

Simply trying to install the latest version of the firebase npm package results in the following error:

```
MattBook-Pro:mobile matt$ npm i firebase@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for tslib@1.9.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@firebase/app'
npm ERR! notarget
```

Looks like [this Pull Request](https://github.com/firebase/firebase-js-sdk/pull/1962) is merged and bumps the version to 1.10.0 (which I can install locally). Has this been published to npm? Hoping to get this resolved soon. Thanks!

**Comment by Matttaylor8910** [comment]
Follow up: I can successfully install this canary build: [6.3.0-canary.271476b](https://www.npmjs.com/package/firebase/v/6.3.0-canary.271476b). Hoping this gets deployed as `latest` soon

**Comment by Feiyang1** [comment]
The version bumps will be part of the release this week. 
I'm not sure how it broke the `npm i firebase@latest` for you, but it seems you have figured it out? 

I will close the issue for now. If you have any followup questions, feel free to reopen it.
