### ISSUE TITLE
My credit  card  is declined  need help

### ISSUE THREAD

**Issue by Akhond-Zada** [firebase/firebase-js-sdk#200]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

http://jsbin.com/rinilu/edit?js,console

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jshcrowthe** [comment]
Sorry, this is probably the wrong place for this type of request. I'd recommend getting in touch with support if you have issues w/ billing.

**Comment by Akhond-Zada** [comment]
Hi. Please  let  me  know I need  my card  details  if any changes  I agree  but I  want  my card  please  please  please . I  need  your  kind  help
