### ISSUE TITLE
firebase.auth().signInWithPopup - Refused to display <oauth redirect url with parameteres> in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by cjorge** [firebase/firebase-js-sdk#2000]
Since today I'm getting a Refused to display <oauth redirect url with parameteres> in a frame because it set 'X-Frame-Options' to 'sameorigin' error when trying to auth with Facebook using firebase.auth().signInWithPopup.

Any known issues on firebase or facebook side that might be causing this because yesterday all was working fine...

**Comment by wti806** [comment]
@cjorge Are you saying signInWithPopup stop working for facebook in iframe? I tried with my own test app and it works fine. Which response has the X-Frame-Options header set to sameorigin?

**Comment by bojeil-google** [comment]
The report does not provide any information on how to recreate this issue.

**Comment by cjorge** [comment]
After contacting Firebase support they corrected something on their end that fixed the issue
