### ISSUE TITLE
auth/operation-not-supported-in-this-environment using Capacitor

### ISSUE THREAD

**Issue by laurie71** [firebase/firebase-js-sdk#2014]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Mojave Version 10.14.5
  * Browser version: Capacitor/Cordova (capacitor 1.1.1)
  * Firebase SDK version: 6.3.1
  * Firebase Product: auth

#### Steps to reproduce:

I'm trying to use Firebase authentication in a React app embedded on iOS with Cordova via Capacitor, using the Firebase Web UI react wrapper from https://github.com/firebase/firebaseui-web-react. I've followed the setup instructions from https://firebase.google.com/docs/auth/web/cordova as well as gone through the readme files for Firebase Web UI and Firebase Web UI React, but I still get an `auth/operation-is-not-supported-in-this-environment` error when running on the device.

Everything is working when hosting the app locally over HTTP, so I know the configuration is OK on the Firebase Console side. I think the problem is how the app is hosting inside Capacitor/Cordova; if I log `window.location` I see that the URL scheme is `capacitor://`, which clearly doesn't match one of `http, https or chrome-extension` as listed in the UI error panel.

Since each of the products in the stack claim to work with Cordova, I wonder if this is something specific to how Capacitor configures Cordova?

My uiConfig looks like this:

```
const uiConfig = {
  signInFlow: 'redirect',
  signInOptions: [
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    firebase.auth.FacebookAuthProvider.PROVIDER_ID,
    firebase.auth.EmailAuthProvider.PROVIDER_ID,
    firebaseui.auth.AnonymousAuthProvider.PROVIDER_ID
  ],
}
```

My authentication component is as follows:

```
import React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'

import firebase from '../../firebase'

import Dialog from '@material-ui/core/Dialog'

import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth'

import * as authActions from '../../store/authActions'

const stateToProps = state => {
  const { authUser } = state.auth
  return { authUser }
}

const dispatchToProps = dispatch => {
  return {
    signin: authUser => dispatch(authActions.authSignin(authUser)),
    signout: () => dispatch(authActions.authSignout()),
  }
}

class AuthPopup extends React.Component {
  static propTypes = {
    authUser: PropTypes.object,
    signin: PropTypes.func.isRequired,
    signout: PropTypes.func.isRequired,
  }

  componentDidMount() {
    console.log(window.location)
    this.unregisterAuthObserver = firebase.auth.onAuthStateChanged(
      user => {
        user ? this.props.signin(user) : this.props.signout()
      }
    )
  }

  componentWillUnmount() {
    this.unregisterAuthObserver()
  }

  render() {
    const { authUser } = this.props
    const authenticated = !!authUser

    return (
      <Dialog open={!authenticated}>
        <StyledFirebaseAuth
          uiConfig={firebase.uiConfig}
          firebaseAuth={firebase.auth}/>
      </Dialog>
    )
  }
}

export default connect(stateToProps, dispatchToProps)(AuthPopup)
```

The authentication dialog shows correctly, but tapping `Sign in with Google` or `Sign in with Facebook` results in this error.

**Comment by bojeil-google** [comment]
We don't support this environment. We only support Cordova apps for Android and iOS hosted from a file:// environment. You need to file an [official feature request](https://firebase.google.com/support) for this.
