### ISSUE TITLE
displayName==null Generic Auth 'google.com'

### ISSUE THREAD

**Issue by GuilhermeBCC** [firebase/firebase-js-sdk#2022]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 75.0.3770
  * Firebase SDK version: 6.3.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
I updated to the latest version of firebase@6.3.1 (I don't know if this is related).
I'm using **new auth.OAuthProvider ('google.com)**.
It had never given this problem before.
So I tried using Google Sign (https://developers.google.com/identity/sign-in/web/sign-in) to see if the problem was with my account.

**Result:**
Full Name: Guilherme Lima
Given Name: Guilherme
Family Name: Lima

That is, my account is normal.

I did some tests adding different scopes
```javascript
        const provider = new auth.OAuthProvider('google.com');
        provider.addScope('profile');
        provider.addScope('email');
        provider.addScope('https://www.googleapis.com/auth/userinfo.profile');
        provider.addScope('https://www.googleapis.com/auth/contacts.readonly');
        provider.addScope('https://www.googleapis.com/auth/user.birthday.read');
        provider.addScope('https://www.googleapis.com/auth/user.phonenumbers.read');
        auth().signInWithPopup(provider)
```
None of this information has been retrieved. The login was automatic (one click), did not ask me about access permissions.

**Comment by bojeil-google** [comment]
I am unable to replicate this in my test app. I am seeing the OAuth scopes in the consent screen. Can you revoke your access to the app (in accounts.google.com) and try again. Check the OAuth scopes are appended to the Google authorization URI.

They are locking down OAuth access scopes for Google sign-in (especially for privacy sensitive scopes), so it could be related to that.
I suggest you open a ticket with [Firebase support](https://firebase.google.com/support). This is unlikely to be a client SDK related issue.

**Comment by GuilhermeBCC** [comment]
I try revoke my access to the app. If not right I will open a ticket with Firebase support.

Thanks for your help!
