### ISSUE TITLE
"process is not defined" error in browsers with 6.3.2 release in firebase-database.js (npm)

### ISSUE THREAD

**Issue by victoriafrench** [firebase/firebase-js-sdk#2025]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 10.13.6
  * Browser version: Chrome 75.0.3770.142 (Official Build) (64-bit)
  * Firebase SDK version: 6.3.2
  * Firebase Product: database

### [REQUIRED] Describe the problem

A change in 6.3.2 from 6.3.1 has exposed process.env code to the browser without a catch. Loading the script in the browser results in an exception of "process is not defined".

#### Steps to reproduce:

1. Use the NPM release (`npm i firebase@6.3.2`)
2. Use firebase.js alone or firebase-database.js in combination with firebase-app.js and firebase-auth.js
3. Get error.

#### Relevant Code:

Attempting to load the package will cause the error period. Code snippets are not needed at all to reproduce this. Error occurring in all browsers.

**Comment by Miguel-Alberto** [comment]
Plus one on this. 6.3.1 is fine.

**Comment by mikelehen** [comment]
@victoriafrench @Miguel-Alberto Thanks very much for the report.  It looks like that slipped in as part of https://github.com/firebase/firebase-js-sdk/commit/5e506a636f191e1ce01e9e7fd1118c183bc5f39c.  We'll take a look and get it fixed ASAP.

**Comment by mikelehen** [comment]
We'll push a new release with this fix shortly.

**Comment by mikelehen** [comment]
6.3.3 has been released with the fix.  Thanks again for the report! Sorry for the breakage.
