### ISSUE TITLE
Refs to the same path affect each other

### ISSUE THREAD

**Issue by nareshbhatia** [firebase/firebase-js-sdk#203]
### Describe your environment

  * Operating System version: MacOS 10.12.6
  * Firebase SDK version: 4.5.0
  * Firebase Product: database (auth, database, storage, etc)

### Describe the problem
I have two ref’s to the same path in different components of my application. When the first component turns off its ref, the other component stops receiving value events on its ref. This is unexpected. The two refs should behave independently.

#### Steps to reproduce:
Please run this code

```javascript
import firebase from 'firebase';

const path = 'some_path';

firebase.initializeApp({
    apiKey: '...',
    authDomain: '...',
    databaseURL: '...',
    storageBucket: '...'
});

// Initialize ref1 to path
let ref1 = firebase.database().ref(path);
ref1.on('value', (snapshot) => {
    console.log('ref1:', snapshot.key);
});

// Initialize ref2 to the same path
let ref2 = firebase.database().ref(path);
ref2.on('value', (snapshot) => {
    console.log('ref2:', snapshot.key);
});

// Turns off ref2. Unfortunately this also turns off ref1 :-(
ref2.off();
```

**Comment by mikelehen** [comment]
This is expected. `ref2.off()` explicitly removes all listeners and its usage is somewhat discouraged specifically for this reason.  Instead, you should retain a reference to your callback function and pass it to `.off()` to remove only that callback. Since `.on()` automatically returns your callback function you can do this with:

    let callback = ref.on('value', snapshot => ... );
    // ...
    ref.off('value', callback);

**Comment by nareshbhatia** [comment]
Thanks @mikelehen, never knew that! Trying now.

A quick followup, can I safely avoid retaining the reference to the callback if it is in a function within in a class:

```
class FierbaseValue {

    startListening() {
        ref.on('value', this.onValue);
    }

    stopListening() {
        ref.off('value', this.onValue);
    }

    onValue = snapshot => {
        ...
    }
}
```

I think `this.onValue` is unique to the instance of the class and that's what `ref.on()` would return anyway.

**Comment by mikelehen** [comment]
Yep, that looks fine to me.  Note that if your onValue function needs access to the class via `this` then you'll need to do `ref.on('value', this.onValue.bind(this))` or the equivalent `ref.on('value', this.onValue, this)`.

**Comment by nareshbhatia** [comment]
@mikelehen, is that necessary even though I am using the ES6 arrow function? It will be automatically bound to this, correct?

**Comment by mikelehen** [comment]
Oh! I think you are right. Sorry.  

If instead you did:
```
class FierbaseValue {
    startListening() {
        ref.on('value', this.onValue);
    }

    onValue(snapshot) {
        ...
    }
}
```

**THEN** you would need to explicitly bind to this.

**Comment by nareshbhatia** [comment]
Got it. Thanks.

BTW, using this approach, it is possible that I accidentally don't remove all listeners in my app. Is there an easy way to figure out if I there are any unintended listeners running? Some sort of a debugging aid?

**Comment by nareshbhatia** [comment]
Got it. All set. Thanks for all your help.
