### ISSUE TITLE
Firestore Offline Collection->Add isn't working as expected.

### ISSUE THREAD

**Issue by N-Andronopoulos** [firebase/firebase-js-sdk#2030]
### [REQUIRED] Describe your environment

  * Operating System version:  Win10
  * Browser version:  Chrome 75.0.3770.142
  * Firebase SDK version: 6.3.3
  * Firebase Product: firestore

#### Steps to reproduce:

With the supplied index.html you can (after changing the credentials)
add a couple of documents with the button. Then using chrome dev->network tab click "offline" and try to add a document again. You can see that the document is added but the alert isn't showing until you untick "offline". This should not happen, because I don't know when the data are inserted since I don't even have the id of the inserted data. The promise from collection->add should fulfill even in offline mode.

#### Relevant Code:
```html
<!DOCTYPE html>
<html>
<head>
	<title>Test Firebase Offline</title>
</head>
<body>
	<label for="test">Test me!</label>
	<br/>
	<button name="test" type="button" onclick="tryMe()">Try Collection->Add</button>
	<br/>
	<br/>
	<div id="result" style="color: orangered;"></div>
	<br/>
	<p>Data in DB</p>
	<div id="preData">No data</div>

	<!-- Firebase App (the core Firebase SDK) is always required and must be listed first -->
	<script src="https://www.gstatic.com/firebasejs/6.3.3/firebase-app.js"></script>

	<!-- Add Firebase products that you want to use -->
	<script src="https://www.gstatic.com/firebasejs/6.3.3/firebase-auth.js"></script>
	<script src="https://www.gstatic.com/firebasejs/6.3.3/firebase-firestore.js"></script>

	<script type="text/javascript">
		firebase.initializeApp({
			apiKey: "ADD ME",
			authDomain: "ADD ME",
			databaseURL: "ADD ME",
			projectId: "ADD ME",
			appId: "ADD ME"
		});

		firebase.firestore().enablePersistence()
			.catch((err) => alert(`Something failed for enablePersistence, code: ${err.code}`));

		firebase.firestore().collection('test')
			.onSnapshot(snaps => {
				if (snaps.empty) { return; }
				const preDataElm = document.getElementById("preData");
				while (preDataElm.firstChild) {
					preDataElm.removeChild(preDataElm.firstChild);
				}
				let list = snaps.docs.map(snap => {
					return {id: snap.id, ...snap.data()};
				});
				let newElm = document.createElement("PRE");
				newElm.innerText = JSON.stringify(list, null, 2);

				return preDataElm.appendChild(newElm);
			});

		function tryMe() {
			document.getElementById("result").innerHtml = "";
			firebase.firestore()
				.collection('test')
				.add({test: new Date().toString()})
				.then((docRef) => alert(`Data inserted successfuly ID: ${docRef.id}`));
		}
	</script>
</body>
</html>
```

**Comment by mikelehen** [comment]
@N-Andronopoulos Thanks for the report. Unfortunately this is actually expected behavior.  All of our write operations, including `add()` don't resolve their `Promise` until the operation has been committed on the backend. This is mentioned in our [docs](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference.html#add).

Fortunately there's an easy workaround.  Instead of using `.add()`, you can equivalently use `.doc()` followed by`.set(...)` For example:
```
const docRef = firebase.firestore()
    .collection('test')
    .doc();

docRef.set({test: new Date().toString()}).then(() => 
    alert(`Data inserted successfully on backend. ID: ${docRef.id}`));

alert(`Data inserted successfully locally. ID: ${docRef.id}`));
```

Let me know if this doesn't solve your use case. And sorry for the confusion!
