### ISSUE TITLE
Keycloak, firebase.auth.signInWithCustomToken and invalid JWT 

### ISSUE THREAD

**Issue by fgruchala** [firebase/firebase-js-sdk#2031]
### Describe your environment

  * Operating System version: **Mac OS Mojave v10.14.5**
  * Browser version: **Google Chrome 75**
  * Firebase SDK version: **6.3.3**
  * Firebase Product: **auth**

### Describe the problem

I have a SSO [Keycloak](https://www.keycloak.org/) and I want to sign in with it in the Firebase SSO.
The problem is that the JWT given by Keycloak seems to be invalid for Firebase.

<img width="575" alt="Capture d’écran 2019-07-28 à 14 38 35" src="https://user-images.githubusercontent.com/12196721/62006767-695be280-b145-11e9-8625-827a3a37ffda.png">

#### Relevant Code:
**authentificationService.js**
```javascript
getToken () {
    console.log(this.sso.idToken)
    return this.sso.idToken
}
```

**main.js**
```javascript
firebase.auth.signInWithCustomToken(authentificationService.getToken())
```

**Comment by bojeil-google** [comment]
The custom token JWT needs to be generated based on certain required (signed by expected private, with expected issuer, audience, etc.). Any token that does not meet these requirements will not work. The [official documentation](https://firebase.google.com/docs/auth/admin/create-custom-tokens) provides more details on how to generate a custom token using the Firebase Admin SDK.

**Comment by fgruchala** [comment]
Thanks for your quick reply 😁

So, what i have to do is :
1. create a custom token based on a uid (the same as Keycloak, e.g. email) ;
2. signInWithCustomToken from the front using the custom token ;
3. link the newly Firebase account with the Keycloak account.

And how I can do the third step ?

Thanks a lot,
François GRUCHALA

Le lun. 29 juil. 2019 à 08:13, bojeil-google <notifications@github.com> a
écrit :

**Comment by bojeil-google** [comment]
This is really not the forum for getting advice on how to use keycloak. Stackoverflow is a better forum for such questions. You will get better help for people more familiar with that service. Unfortunately, I have never used keycloak, so you won't get much help here.

**Comment by fgruchala** [comment]
Thanks, I posted a question on Stack : https://stackoverflow.com/questions/57268709/how-to-fix-invalid-jwt-between-keycloak-and-firebase
