### ISSUE TITLE
Couldn't verify the existence of a certain e-mail considering just the _email/password_ provider

### ISSUE THREAD

**Issue by lucgauer** [firebase/firebase-js-sdk#2036]
### Environment

  * Operating System version: MacOS 10.14.4
  * Browser version: Chrome 75
  * Firebase SDK version: 6.7.0
  * Firebase Product: auth 0.9.6

### Problem

I couldn't verify the existence of a certain e-mail considering just the _email/password_ provider in `@firebase/auth`.

Trying to use `auth.fetchSignInMethodsForEmail`, it retrieves me all providers i.e. `facebook@facebook.com` causing some mess.

#### Steps to reproduce:

Having some e-mail provider user like `mail@mail.com`, we link a Facebook provider `facebook@facebook.com` like this:

```java
UserProvider facebookProvider = UserProvider
    .builder()
    .setProviderId(dto.getProvider())
    .setEmail(dto.getMail())
    .setUid(dto.getUid())
    .build());

List<UserProvider> providers = Lists.newArrayList(facebookProvider);

ImportUserRecord.builder()
    .addAllUserProviders(providers)
    .setEmail(user.getEmail())
    .setDisplayName(user.getFirstName())
    .setUid(uid)
    .setDisabled(false)
    .setEmailVerified(true)
    .setPasswordHash(generated)
    .setPasswordSalt(salt)
    .build();
```

In the web client using `@firebase/auth`, we are not able to **verify the existence** of `facebook@facebook.com` as a *email/password provider* not yet registered.

It occurs because this method gets just an email, in the case `facebook@facebook.com`, and returns just the providers from this given e-mail:
```javascript
["password", "facebook.com"]
```

This array is not in a meaningful order, so we couldn't suppose the `facebook@facebook.com` is the Facebook e-mail provider.

In this case we also could not allow users to register with this `facebook@facebook.com` e-mail **as a email/password** provider credential.

**Comment by wti806** [comment]
If I understand correctly, the user has two providers: facebook.com and password. But the email of them are different. In this case, you cannot create users using any of the two emails, cause they are both linked to an existing account. I'm confused about your use case here. Can you provide more detail about your use case?
