### ISSUE TITLE
percentage from storage blows up app when task is cancelled

### ISSUE THREAD

**Issue by Methodician** [firebase/firebase-js-sdk#2038]
### Describe your environment

  * Operating System version: macOS Mojave 10.14.5
  * Browser version: Google Chrome 75.0.3770.100 (Official Build) (64-bit)
  * Firebase SDK version: "^6.2.4"
  * Firebase Product: storage
  * Possibly Relevant: using React Native for iOS app, but the Firebase web SDK

###  Describe the problem

Attempting to cancel an upload crashes the app so fatally I have to completely close the emulator.

This appears on the emulator's red banner: "Firebase Storage: User canceled the upload/download."

In addition to the above, this appears in the debug console: "Unhandled JS Exception: Firebase Storage: User canceled the upload/download"

I believe somewhere a promise rejection is going unhandled, though the stack trace does not point to RxFire so far as I can tell.

#### Steps to reproduce:

Attempt to upload an image (didn't test with other files) to Firebase Storage, and use the "percentage" observable from RxFire to track it. Proceed to cancel the upload in code (I had a dialog with a button to cancel it). For me at least, this fatally blew things up, and when I replaced the RxJS code with vanilla Firebase SDK code (using the "task.on('state_changed')" callback) everything worked fine.

#### Relevant Code:

```javascript

        // In a modal in my case, passing in the task as argument
	useEffect(() => {
		percentage(task).subscribe(action => {
			const { progress } = action;
			setProgress(progress / 100);
		});
		task.then(
			taskSnap => {
				onTaskComplete(taskSnap);
			},
			error => {
				console.log(error);
			}
		);
	}, [task]);

      // Elsewhere in code, maybe in the modal too?
      task.cancel();
      // FIREWORKS


     // and the working alternative in case it's useful to someone:

	useEffect(() => {
		if (task) {
			task.on("state_changed", snap => {
				const progress = snap.bytesTransferred / snap.totalBytes;
				setProgress(progress);
			});
			task.then(
				taskSnap => {
					onTaskComplete(taskSnap);
				},
				error => {
					console.log(error);
				}
			);
		}
	}, [task]);

       // Elsewhere:
      task.cancel();
      // smooth...
```

**Comment by schmidt-sebastian** [comment]
@Methodician Thank you for your report! If you can, it would help to have a small reproducible sample app.

**Comment by Methodician** [comment]
I will try to find time to create a sample. So easy to dismiss when I just wrote a few lines of my own code instead haha...

**Comment by jhuleatt** [comment]
this looks related to #1659
