### ISSUE TITLE
enablePersistence slow in SystemWebChromeClient

### ISSUE THREAD

**Issue by explofish** [firebase/firebase-js-sdk#2044]
### Describe your environment

  * Operating System version: Android 9
  * Browser version: SystemWebChromeClient API 28
  * Firebase SDK version: 6.3.0 Web SDK
  * Firebase Product: Firestore

### Describe the problem
When downloading a List of about 40 Items from Firestore the download in SystemWebChromeClient takes about 2.5 Seconds with enablePersistence enabled.

Disabling Persistence results in a download Time of <1 Second

This does not happen in Desktop Chrome, Mobile Chrome or Safari.

Waiting for persistance enabled did not help in download times.

This occurs in Android simulator and On device.

**Comment by schmidt-sebastian** [comment]
@explofish Thank you for filing this issue and sorry for the trouble. 

The Web SDK uses IndexedDb, which we have found to be not particularly snappy in many different environments. There are some performance improvements we still need to make on our end (in particular in regards to our query speed). For now, however, it is unfortunately the case that that our Web persistence layer is slower on some platforms.

**Comment by explofish** [comment]
@schmidt-sebastian Thanks for your quick reply!

Its quite suprising that its that much slower! For now i guess there is nothing left for me than disabling persistence.
What about the roadmap? Is there a good chance that there will be some focus on improving the speed in Hybrid environments?
Thanks so much!

**Comment by schmidt-sebastian** [comment]
Do you mind sharing a little more about what you are doing and what your data looks like? Are the 40 documents you mentioned returned from a single (filtered) query against a collection? If so, do you know if the collection contains more than 40 elements to begin with?

I don't see any sample code under the link you provided.

**Comment by explofish** [comment]
@schmidt-sebastian 
Sorry for the late reply. Yes its a single query! its not much more than 40! I must say it does not really depend on the type of query. it seems like all of them are at least one second delayed. sorry for the confusion!

**Comment by schmidt-sebastian** [comment]
Do you mind sharing your code (or explaining your structure?). Firestore uses a single worker-queue and all operations are executed serially. A single slow query can therefore introduce delays in query processing even for a much faster query.
