### ISSUE TITLE
Our web app frontend code on Firebase encountered CORS issue when ajax calling Dialogflow V2 APIs: Need urgent help!

### ISSUE THREAD

**Issue by eGlobeBizCom** [firebase/firebase-js-sdk#2052]
Hi All,

**Describe your environment**
Operating System version: Windows 10
Browser version: Chrome, MS Edge, Firefox, Safari
Firebase SDK version: 6.3.0 Web SDK
Firebase Product: Firebase JavaScript SDK

**Describe the problem**

# The issue details are here:
https://github.com/googleapis/nodejs-dialogflow/issues/397

# Based on our researches, we changed some info in our Firebase.json based Firebase guide:
https://firebase.google.com/docs/hosting/full-config#headers
Here are the content of our Firebase.json 
*************************************
_{
  "hosting":
  {
    "public": "./",

    "ignore":
    [
      
      "**/.*",
      "**/node_modules/**"
    ],

    "headers":
    [ {
      "source": "https://dialogflow.googleapis.com/v2/projects/my-chatbot-ID",
      "headers": [ {
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      } ]

   },

  {
      "source": "**/*.@(jpg|jpeg|gif|png)",
      "headers": [ {
        "key": "Cache-Control",
        "value": "max-age=7200"
      } ]
    },

    {
      "source": "404.html",
      "headers": [ {
        "key": "Cache-Control",
        "value": "max-age=300"
      } ]
    } ]

 }

}_
*****************************************

# After the above is deployed, I tested the web app through private browser without caches within 1 day, the above issue is not changed. That means this: The new content in Firebase.json does not solve the problem.

I wish to find out from you: Any content in the above Firebase.js needs to be fixed? I posted this issue here as I thought the viewers on this page may have some good suggestions that is useful to solve this issue.

Any suggestions will be highly appreciated.

**Comment by Feiyang1** [comment]
The problem you are having is `Dialogflow V2 REST APIs` doesn't return `Access-Control-Allow-Origin` header. 
The firebase hosting configuration should not have any effect on it. @samtstern FYI

**Comment by eGlobeBizCom** [comment]
@Feiyang1  Thank you very much for this info that confirmed our understanding on this issue.
