### ISSUE TITLE
After following your sample code below to fix CORS problem in our web app, the CORS still happened in our web app on Firebase calling our Firebase Cloud Functions file

### ISSUE THREAD

**Issue by eGlobeBizCom** [firebase/firebase-js-sdk#2072]
### [REQUIRED] Describe your environment

  * Operating System version: _____Windows 10
  * Browser version: _____
  * Firebase SDK version: _____ firebase-admin 8.3.0.
       <script src="https://www.gstatic.com/firebasejs/6.3.5/firebase-app.js"></script>
  * Firebase Product: _____ Cloud Functions

### [REQUIRED] Describe the problem

We followed the following pages sample code to fix our web app on Firebase, but these sample code is not working in our web app
https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint/functions/index.js  
https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint/firebase.json   
https://stackoverflow.com/questions/42755131/enabling-cors-in-cloud-functions-for-firebase  

​#In our firebase.json, we followed this sample code to add the following code:
https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint/firebase.json     

​===========

    "rewrites":
     [
          {
            "source":"**",
            "function":"dialogflowReply"
          }
     ],

    "headers":
    [ {
      "source": "https://us-central1-inspire.cloudfunctions.net/dialogflowReply",
      "headers": [ {
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      }
    ]
==========================​

​# In our function file Index.js, We followed this ​sample code below to add these code: 
​https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint/functions/index.js  ​
​==================
 const cors = require('cors') ({origin: 'https://inspire.firebaseapp.com'});

  res.set('Access-Control-Allow-Origin', "*");
  res.set('Access-Control-Allow-Methods', 'GET');

dialogflowReply.use(cors);

exports.dialogflowReply = functions.https.onRequest(dialogflowReply);
===============​

​# The ajax call in our xyz.js in this web app on Firebase
============
$.ajax
({
     crossDomain: true,
      type: "GET", 
      url: baseUrl + "userInputEn", 
      contentType: "application/json; charset=utf-8",
      dataType: "json",
})
=============​

# We have tried all the solutions posted on this page, but nothing worked:
https://stackoverflow.com/questions/42755131/enabling-cors-in-cloud-functions-for-firebase   

​# After ​the above, when we test the web app, we still saw the following error message
=================
Access to XMLHttpRequest at 'https://us-central1-inspire.cloudfunctions.net/dialogflowReplyuserInputEn?{%22userInputEn%22:%22hi%22,%22languageCode%22:%22en%22}' from origin 'https://inspire.firebaseapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
=================

​Any advice and thoughts are warmly welcome​

**Comment by Feiyang1** [comment]
This forum is only for issues and discussions about the client SDK itself. I suggest you open a ticket with [Firebase Support](https://firebase.google.com/support).
