### ISSUE TITLE
Error 400 with signInWithCustomToken

### ISSUE THREAD

**Issue by luco** [firebase/firebase-js-sdk#2075]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.5
  * Browser version: Chrome 75.0.3770.142
  * Firebase SDK version: 6.2.3
  * Firebase Product: 6.2.3

#### Steps to reproduce:

Is anyone getting the error 400 with signInWithCustomToken? I started getting it right now.

```POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken?key=.... 400```

**Comment by bojeil-google** [comment]
Please open a ticket with [Firebase Support](https://firebase.google.com/support). This is a client SDK repo. To debug backend behavior, sensitive information will be needed. This is not the appropriate forum for it. You will need to provide actual data to reproduce. The actual tokens, project information, etc.
