### ISSUE TITLE
 "FR:"  Urgent!  Wish the Cloud Function feature can connect to Dialogflow V2 APIs without needing Google Service Account Key just as Firebase Cloud Function has done with Google Cloud Translation APIs

### ISSUE THREAD

**Issue by eGlobeBizCom** [firebase/firebase-js-sdk#2086]
Hi Firebase Team,

Our web apps on Firebase have used several Google Cloud  APIs such as Translation APIs without using Google Service Account Key for these APIs. This is one of the major reasons for us to use Firebase for several years. 

# Our web app on Firebase has used  Dialogflow V1 APIs through frontend code for several years.  Recently, this web app is forced to use  Google Service Account Key to connect with Dialogflow V2 APIs  in its Index.js.  Now, our live production web app on Firebase stopped working due to the above issue.  After many hours of experiments on this, we only found this point on the following page: Google Service Account Key  cannot be used in Firebase CLI yet, and our app needs to wait for a while before this is enabled in  Firebase CLI:
https://github.com/firebase/firebase-tools/issues/787

# Now, the only option for our web app to use Dialogflow V2 APIs  in its Index.js without  Google Service Account Key is this: Firebase Cloud Function feature can enable Dialogflow V2 APIs  as other Google Cloud  APIs.  Dialogflow V2 APIs is part of Google Cloud  APIs.  Our experiences with Dialogflow shows that more Firebase users will need to access Dialogflow V2 APIs in the Index.js shortly.

Wish that this feature will be added shortly!

Thank you !

**Comment by Feiyang1** [comment]
Thank you for the feature request, but this repo is not the right forum for this specific request. Can you please file a ticket with [Firebase Support](https://firebase.google.com/support?authuser=0)?
