### ISSUE TITLE
`updatePassword` and `updateEmail` work, but return undefined

### ISSUE THREAD

**Issue by sfyfedotcom** [firebase/firebase-js-sdk#2093]
* Operating System version: macOS
  * Browser version: N/A (React Native)
  * Firebase SDK version: 6.4.0
  * Firebase Product: auth

Using `updatePassword` or `updateEmail` return undefined:
```
const { currentUser } = firebase.auth()
const response = await currentUser.updatePassword(newPassword)
console.log(response)
```
Outputs:
```
undefined
```
```
const { currentUser } = firebase.auth()
const response = await currentUser.updateEmail(newEmail)
console.log(response)
```
Outputs:
```
undefined
```

If I haven't signed in recently, they throw the usual error about needing to sign in again. Which I'm handling. But from the [documentation](https://firebase.google.com/docs/reference/js/firebase.User.html#updatepassword) I'd expect it to return a boolean response. Like everything else does.

It does seem to successfully change the password and email.

**Comment by sfyfedotcom** [comment]
Tried updating to `6.4.0`, but still returns `undefined`

**Comment by bojeil-google** [comment]
I think there were some issues using await/async with `goog.Promise` if I recall correctly, which the Auth library uses. Try using regular promise then/catch.

**Comment by bojeil-google** [comment]
Wait actually both APIs resolve with void:
https://firebase.google.com/docs/reference/js/firebase.User.html#updateemail
https://firebase.google.com/docs/reference/js/firebase.User.html#update-password

So this seems like it works as expected.
