### ISSUE TITLE
Support custom url scheme

### ISSUE THREAD

**Issue by Yuripetusko** [firebase/firebase-js-sdk#2118]
### [REQUIRED] Describe your environment

  * Operating System version:  Cordova
  * Browser version: Cordova
  * Firebase SDK version: 6.3.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Using ionic webview, on ios which in turn uses custom url scheme (in our example mobileapp://, doesn't let firebase web to start. Looks like this is the culprit: https://github.com/firebase/firebase-js-sdk/blob/6b53e0058483c9002d2fe56119f86fc9fb96b56c/packages/auth/src/error_invalidorigin.js#L54

Would be nice to allow custom url schemes.

#### Steps to reproduce:
Start a server with custom url scheme and use firebase js sdk, `onAuthStateChange` events will never fire

I know that alternative would be to use native firebase implementation in my case, but if there's a plan to allow custom schemes in future maybe I can hold it off.

**Comment by rommelpe** [comment]
Were you able to check out our [Authenticate Using OAuth Providers with Cordova](https://firebase.google.com/docs/auth/web/cordova#handle_the_sign-in_flow_with_the_firebase_sdk)? Did you install the [cordova-plugin-customurlscheme](https://www.npmjs.com/package/cordova-plugin-customurlscheme) plugin and configure the iOS bundle ID as the custom scheme? This plugin allows you to start your app by calling it with a URL like `mycoolapp://path?foo=bar`

**Comment by Yuripetusko** [comment]
@rommelpe I don't like to use this way because it then authenticates using browser, I much prefer using native facebook and Google plugins to get token and pass it to firebase auth, but it's not about that.  When I visit web server with custom url scheme it seems like firebase-js sdk is not working there at all, not saving auth token in cookie/local storage etc. Could that be the case? Unfortunately since reporting this issue I switched back to older version of ionic webview which still uses http as a scheme instead of custom url scheme so I can't do much reporting now

**Comment by rommelpe** [comment]
I'd love to look into this if you can provide a minimal repro that we can run locally to confirm. Atm, it's difficult to pinpoint what might be the cause since we don't have something to look at but if you can debug further and provide a reproducible scenario, we'd happy to investigate further.  Thanks @Yuripetusko
