### ISSUE TITLE
auth().languageCode not working on v4.2.0

### ISSUE THREAD

**Issue by ramonrooliveira** [firebase/firebase-js-sdk#2119]
I'm using the SDK at version 4.2.0 and I need to set the laguageCode for auth(), but it does not seem to work. I changed the version to 5,5,3, just to test this, and it worked fine. I can't find any reference to this issue and to which version it was solved at. Would someone know at what version was this updated?

**Comment by wti806** [comment]
Seems it's supported from v4.3.0 https://firebase.google.com/support/releases#aug_17_2017 
You can check from the release note. V4 is a very old version though, we strongly suggest to update to the later version.
