### ISSUE TITLE
'initializeApp' is not exported by 'node_modules\@firebase\app\dist\index.cjs.js'

### ISSUE THREAD

**Issue by Yodamaul** [firebase/firebase-js-sdk#2120]
I am writing a Svelte application with a Firebase backend. I am using Rollup as my bundler. 
As suggested by the docs I am trying to import Firebase as following:
```
// Firebase App (the core Firebase SDK) is always required and must be listed first
import * as firebase from "@firebase/app";

// Add the Firebase products that you want to use
import "firebase/auth";
import "firebase/firestore";

```

however when I try to do this I get the following error:
`'initializeApp' is not exported by 'node_modules\@firebase\app\dist\index.cjs.js'`

Writing it like this though:

```
import firebase from 'firebase/app';
import 'firebase/database';
import 'firebase/auth';
```

Lets me sucessfully use the database in my app, albiet with a warning that I'm using the browser version of Firebase instead of the necessary modular one. I can't access the auth this way.

**Comment by Feiyang1** [comment]
`firebase` currently doesn't provide a modular API that let you import individual functions.

I also notice that you are importing `@firebase/app` instead of `firebase/app`. Please use `firebase/app`, otherwise you won't get proper types. The following is copied from the official [guide](https://firebase.google.com/docs/web/setup?authuser=0) and should work: 
```
import * as firebase from "firebase/app";

// Add the Firebase services that you want to use
import "firebase/auth";
import "firebase/firestore";

// TODO: Replace the following with your app's Firebase project configuration
var firebaseConfig = {
  // ...
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);
```

**Comment by flawyte** [comment]
I can confirm. This doesn't work :

```ts
import * as firebase from 'firebase/app';
import 'firebase/firestore';
```

It gives a warning and my app won't run :

```
[ WARN  ]  Bundling Warning MISSING_EXPORT
'initializeApp' is not exported by 'node_modules/firebase/app/dist/index.cjs.js'
```

However this does work :

```ts
import firebase from 'firebase/app';
import 'firebase/firestore';
```
