### ISSUE TITLE
onAuthStateChanged passes with a user/signed in on iPhone X (react-native)

### ISSUE THREAD

**Issue by bytewiz** [firebase/firebase-js-sdk#2132]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 10
  * Browser version: (iPhone X)
  * Firebase SDK version: 6.4.2
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
So I am building a react-native app using expo and then I test it on iPhone and Android it seems to work fine even the emulator works fine, but on iPhone X (real device), the `onAuthStateChanged` seems to be skipped and the user is forwarded into the apps main screen which only way of getting directly there is on successful sign in and with `user` object existing but still for some reason this happens and the user is not signed in nor does the user appear in exist in the system. 

#### Steps to reproduce:

No clue, shouldn't be possible to bypass the `onAuthStateChanged` handler?

#### Relevant Code:

So the steps should be:
1) app loads
2) goes to AuthLoading
3) checks the `onAuthStateChanged`
4a) redirects to sign in (if not signed in)
4b) redirects to home screen (if signed in)
```
// AuthLoading
componentDidMount() {
    const self = this;
    auth.onAuthStateChanged(async (user) => {
      if (user) {
        self.props.navigation.navigate(Routes.MAIN)
      } else {
        // User is signed out.
        self.props.navigation.navigate(Routes.AUTH)
      }
    })
```

Hope some can help me or have any ideas what could be going wrong?

**Comment by wti806** [comment]
Are you using the react-native-firebase library: https://github.com/invertase/react-native-firebase?

**Comment by bytewiz** [comment]
@wti806 I am using the `expo` (react-native) and the firebase js SDK

**Comment by wti806** [comment]
We use AsyncStorage for react-native: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/storage/factory.js#L79  I don't know why it only doesn't work on iphoneX(real device). Btw, why do you need the `async` keyword for the callback?

**Comment by bytewiz** [comment]
@wti806 I am currently checking several options to solve this, let me get back on this!

Also yea I need it from some async functions I just stripped out for simplicity :)

**Comment by bytewiz** [comment]
@wti806 I found out that this was an issue caused by `react-navigation`, just behaved so weird that the auth part was also affected, ripped out react-navigation and did some custom work, now it works like a charm! 👍 appreciate the assistance! have a great day!
