### ISSUE TITLE
Firestore encounters "TimeoutError: Transaction timed out due to inactivity." after laptop recovers from sleep.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-js-sdk#2136]
[Forking this from https://github.com/firebase/firebase-js-sdk/issues/1642 which is currently conflating several issues.]

We have gotten reports that when using Firestore in a web app in Chrome, if the computer goes to sleep (e.g. you close the lid on your laptop), when it wakes back up, sometimes you encounter an error like:

> Uncaught (in promise) Error: FIRESTORE (5.11.0) INTERNAL ASSERTION FAILED: AsyncQueue is already failed: Transaction timed out due to inactivity.

We are currently considering this a bug in Chrome which is being tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=855624

If you are encountering this, please add details to that Chrome bug, especially if you can help reproduce it. Thanks.

**Comment by markterrill** [comment]
Hi, I have been regularly experiencing this issue on ios when an ionic 4 app is backgrounded and then resumed.

So not just chrome.

Firestore (7.0.0)

**Comment by mikelehen** [comment]
@schmidt-sebastian has added some retry logic to the client which may not 100% resolve this but should significantly reduce the frequency of it occurring.  I would encourage folks to upgrade to JS SDK v7.2.3 or newer and comment here if they still experience the issue. I'm optimistically closing this issue, but will re-open based on additional feedback.  Thanks!
