### ISSUE TITLE
XHR requests sent by Firebase hang for some users

### ISSUE THREAD

**Issue by nialna** [firebase/firebase-js-sdk#2140]
### [REQUIRED] Describe your environment

  * Operating System version: Any (tried on iOS, Android and Chrome desktop)
  * Browser version: desktop Chrome latest, Android chrome latest, iOS Safari latest
  * Firebase SDK version: 6.5.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Some requests appear to hang for extremely long times and eventually get stalled, while trying to use firestore functions.

This only happens to some users and not all of them, but happens on any device

#### Steps to reproduce:

Steps to reproduce are unclear. It seems to happen randomly on requests, but not to all users.

What I don't understand is what Firebase might be doing for requests to hang like this. I assume that if we're sending bad data or doing some sort of invalid operation, it would throw an error. But instead we get requests hanging and getting stalled, with the promises only returning minutes later, if ever.

Thos are also very simple operations (ie. updating a specific document), not complex queries that would take a long time to process.

Because of HTTP2 removing the limit of 6 open connections per domain, I also assume that there is no reason the browser would stall requests from firebase due to too many requests being sent in parallel (we don't have many in the first place, at most there will be up to 5 requests being sent in quick succession). But I might be wrong on that.

**Comment by MatthewPringle** [comment]
I have also noticed this.

I have 2 pages, one that queries firestore and one that has no firebase functionality, in an Ember single page app.

Flipping back for fourth between the 2 pages will eventually cause Firebase to stall and stop responding. The network request just keeps on spinning in the console and nothing happens after that.
