### ISSUE TITLE
auth/account-exists-with-different-credential issue

### ISSUE THREAD

**Issue by ForbiddenEra** [firebase/firebase-js-sdk#2156]
* Operating System version: Win 10 1809/Ubuntu 18.04
  * Browser version: FF Current/Chrome current
  * Firebase SDK version: Current -> pulled in last 24h
  * Firebase Product: Auth

Steps to reproduce:
-> clear login for my app from my google account, clear login for my app from my facebook account
-> make sure I'm logged out with firebase
-> do a facebook sign in
--> my account is shown as a facebook account in the firebase console
-> sign out
-> do a google sign in
--> my account is now shown as a google account in firebase console, no error

Now, if I do the reverse (start with google then try to use facebook):
-> clear login for my app from my google account, clear login for my app from my facebook account
-> make sure I'm logged out with firebase
-> do a google sign in
--> my account is shown as a google account in the firebase console
-> sign out
-> do a facebook sign in
--> I get error ``auth/account-exists-with-different-credential`` as expected.

I would expect to get the same error in both situations, thus I can provide the user with the option to link the other provider's account. In this situation, if they sign in with facebook first, then sign in with google, then try and sign in with facebook again it will give an error.

https://www.youtube.com/watch?v=DUj6yNXCh0A

**Comment by bojeil-google** [comment]
This is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/1883

**Comment by ForbiddenEra** [comment]
> 
> 
> This is a duplicate of #1883

Thanks -> should have searched better I guess.
