### ISSUE TITLE
createUserWithEmailAndPassword  does not do authentication by default

### ISSUE THREAD

**Issue by amazedge** [firebase/firebase-js-sdk#2162]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 76
  * Firebase SDK version: 6.4.0 or even 6.6.0
  * Firebase Product: AUTH and DATABASE (auth, database, storage, etc)

### [REQUIRED] Describe the problem
Trying to sign up with createUserWithEmailAndPassword and then as well trying to insert data at REALTIME Database. However Permission Denied while inserting entries in the database.
Believe authentication is not happening.

#### Steps to reproduce:

1)Firebase.auth().createUserWithEmailAndPassword(email, password)
2)Once the uid is obtained , try to set data @ REALTIME Database
3) We get Error Permission Denied.

Believe authentication is not happening while createUserWithEmailAndPassword

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```
RULE set at DB:
      "$uid": {
        ".read": "auth != null && auth.uid == $uid",
        ".write": "auth != null && auth.uid == $uid",

JS Code:
       return Firebase.auth().createUserWithEmailAndPassword(email, password)
          .then((res) => {
            // Send user details to Firebase database
              if (res && res.user.uid) {

                var createDate= Firebase.database.ServerValue.TIMESTAMP;

                var tenantKey = FirebaseRef.child('tenants').push().key;   
                var tenantData= {tenantCompany,tenantCountry,tenantCurrency,tenantTimeZone,tenantPlan, createDate};
                var userData = {firstName,lastName, email,mobile, createDate,lastLoggedIn:createDate,role,isActive,rewards,userType,tenantId:tenantKey,superTenantId:tenantKey};
        
                return FirebaseRef.child('/tenants/'+tenantKey).set(tenantData)
                .then(()=>{
                    return FirebaseRef.child('/users/'+ res.user.uid).set(userData)
                    .then(resolve);
                }).catch(reject);
                }
                }

**Comment by Shreykhanna** [comment]
Hi, What do you mean by default? If you mean that when user enters emailId and password then createUserWithEmailAndPassword checks automatically with emailId and password stored , then this is not the case. You have to write comparison code by fetching details from database and perform accordingly.
Cheers

**Comment by amazedge** [comment]
> serWithEmailAndPassword checks automatically with emailId and password stored , then this is not the case. Yo

Hi,

createUserWithEmailAndPassword supposed to automatically perform the authentication once user is created.[this is as per the documentation provided by firebase].Infact happening in older versions..Howevever not happening in the latest versions..

**Comment by wti806** [comment]
I tried with createUserWithEmailAndPassword, it does sign in the user you created. I'm not sure if the issue is related to database.

**Comment by hsubox76** [comment]
I wasn't able to reproduce this either, using the same rules you have and this minimal code: ```    firebase.auth().createUserWithEmailAndPassword("test@test.example", "password1234")
        .then((cred) => {
            firebase.database().ref('users/' + cred.user.uid).set({
                test: 'testValue'
            });
        });```

I notice you're first doing a write to a `tenants` collection, is it possible by any chance the permissions error happens on that write?  If not, can you:

- find the latest Firebase version where this is working with your current code?

and/or

- create a small repo with the minimum code needed to reproduce the error?

Thanks!

**Comment by amazedge** [comment]
Its working..pls close this.  Believe it was permission issue at realtime database...Thanks for the help
