### ISSUE TITLE
Latency Compensation Path Mutation

### ISSUE THREAD

**Issue by bryce-pilcher** [firebase/firebase-js-sdk#2185]
### [REQUIRED] Describe your environment

  * Operating System version: Win 10 64bit
  * Browser version: Chrome (77.0.3865.90)
  * Firebase SDK version: 6.6.1
  * Firebase Product: firestore

#### Steps to reproduce:
Hey!

I found a bug with writing to Firestore in the same place that you have an active listener.  I need to use the id of a document to get a document from a subcollection.  

A -> 1 -> B -> *

With the id of saving space, I did not want to store the ID of document 1 in that document.  I also knew that I could retrieve the id from the _key.path.segments array.  Instead of indexing by the size of segments minus one, I decided to use the reverse function and get the initial element.  This caused firebase to write the document to the wrong place in Firestore.  I've attached a minimum example of this attached to a test Firestore in my account.  Obviously feel free to change that configuration, but you should see it write to a path like:

autoId -> B -> 1 -> A

I worked around it by using the length of segments array to get the last index from it.  But just thought you might be interested in this. 

_I also filed a report through firebase support, and was directed to file a corresponding ticket here._

Also, you can check out the minimum example on [github](https://gist.github.com/bryce-pilcher/76dff7d29be23540de08774a415e3042)

Cheers,

Bryce

#### Relevant Code:
[Github Gist](https://gist.github.com/bryce-pilcher/76dff7d29be23540de08774a415e3042)

**Comment by wilhuff** [comment]
Use of internal methods on the document reference is unsupported.

In this case you're mutating a key in-place where the code expects such things to be immutable. Who knows what's going to break when that invariant is broken.

If you can reproduce the problem you're describing using public APIs, then we might have something to discuss.

**Comment by mikelehen** [comment]
FWIW- You can probably do something like `doc.ref.parent.parent.id` to solve your use case.  But as Gil alludes to, `doc._key` is _not_ a public API and using it is not supported.  Even if your code "worked", it could be broken by a subsequent release if we e.g. renamed `_key` to something else.  Stick to the publicly-documented API (which as a rule does not contain `_` in the names 😄 )

**Comment by bryce-pilcher** [comment]
@mikelehen Thanks for the suggestions! I overlooked the `id` field on the DocumentSnapshot itself.  

@wilhuff I legitimately thought this might have been something overlooked and was just trying to provide an extra set of eyes. 

Thank you both for a great product!
