### ISSUE TITLE
Cannot  call Firebase Cloud functions from Client SDK(React-Native)

### ISSUE THREAD

**Issue by amazedge** [firebase/firebase-js-sdk#2186]
### [REQUIRED] Describe your environment

  * Operating System version:Windows 10
  * Firebase SDK version: 6.6.1
  * Firebase Product: JS CLient SDK  from React Native App cannot invoke Firebase cloud functions

### [REQUIRED] Firebase functions cannot be invoked from JS Client SDK..
**The error message is just "not-found"**

#### Relevant Code:
var provisions_createClaims = FirebaseFn.httpsCallable(
                'provisions_createClaims'
              );

All necessary imports etc done already elsewhere.

**Comment by Feiyang1** [comment]
The error code indicates that you are calling a function that doesn't exist or returns a 404. 

Can you please check the logs on the back end to see if the function gets called?
Please also double check to make sure the function name is correct.
