### ISSUE TITLE
Typescript types for FirebaseApp require unsettable automaticDataCollectionEnabled

### ISSUE THREAD

**Issue by zeroasterisk** [firebase/firebase-js-sdk#2189]
* Operating System version: osx
  * Browser version: 
  * Firebase SDK version: 6.6.1
  * Firebase Product: FirebaseApp (typescript)
```
├─┬ firebase@6.6.1
│ ├─┬ @firebase/app@0.4.16
│ │ ├── @firebase/app-types@0.4.3 deduped
```

```
$ tsc --version
Version 3.6.2
```

### Problem:

I can use `app.initializeApp(config)` to create a `FirebaseApp` app.
But Typescript is never happy.

The 2 errors I get are:
> Property 'automaticDataCollectionEnabled' is missing in type 'App' but required in type 'FirebaseApp'.  TS2741
or
> Argument of type 'FirebaseAppConfig' is not assignable to parameter of type 'string'.  TS2345

#### Steps to reproduce: Without the AppConfig, name as string

```typescript
import { FirebaseApp, FirebaseOptions, FirebaseAppConfig } from '@firebase/app-types';
import * as app from 'firebase/app';

const config: FirebaseOptions = {...};
const appName: string = 'Decryptilito';
const myApp: FirebaseApp = app.initializeApp(config, appName);
```

Results in error:

> Property 'automaticDataCollectionEnabled' is missing in type 'App' but required in type 'FirebaseApp'.  TS2741

#### Steps to reproduce: With the AppConfig

```typescript
import { FirebaseApp, FirebaseOptions, FirebaseAppConfig } from '@firebase/app-types';
import * as app from 'firebase/app';

const config: FirebaseOptions = {...};
const appConf: FirebaseAppConfig = { name: 'Decryptilito', automaticDataCollectionEnabled: false };
const myApp: FirebaseApp = app.initializeApp(config, appConf);
```

Results in error:

> Argument of type 'FirebaseAppConfig' is not assignable to parameter of type 'string'.  TS2345

#### Possible solution

I suspect that maybe types and JS code have diverged a bit?  

https://github.com/firebase/firebase-js-sdk/blob/master/packages/app-types/index.d.ts#L49

When I'm looking at the overloaded types def of `initializeApp()` I see both supported, but I can't us the config based one.

Also, I see that `automaticDataCollectionEnabled` is optional in the config, but required in the app itself.

**Comment by Feiyang1** [comment]
Types from `@firebase/app-types` are not meant to be used directly. You should only use the types directly exposed by `import * as firebase from firebase`. For example:
```
import * as firebase from 'firebase/app';

const config = {...};
const appName: string = 'Decryptilito';
const myApp: firebase.app.App = firebase.initializeApp(config, appName);
```
