### ISSUE TITLE
Realtime Database rules are not being loaded if launching tests with `emulators:exec`

### ISSUE THREAD

**Issue by evindor** [firebase/firebase-js-sdk#2191]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS 10.14.4, Alpine 3.9
  * Browser version: Irrelevant
  * Firebase SDK version: @firebase/testing@0.12.0 & up, firebase@6.4.0 & up
  * Firebase Product: database emulator, @firebase/testing

### [REQUIRED] Describe the problem
`firebase.loadDatabaseRules` does not load rules if tests are being run using `firebase emulators:exec`.
#### Steps to reproduce:
- Clone [database emulator example](https://github.com/firebase/quickstart-nodejs/tree/master/database-emulator/typescript-quickstart)
- Bump `@firebase/testing` to any version from `0.12.0` and up to `0.13.2`
- `yarn install`
- `firebase emulators:exec --only database "yarn test"`

3/4 tests will fail, reporting `Error: Expected request to fail, but it succeeded.` indicating that rules were not set by testing code and default emulator rules apply (allow all reads & writes).

Latest version of `@firebase/testing` which works fine is `0.11.10`

**Comment by mikelehen** [comment]
cc/ @ryanpbrewster

**Comment by ryanpbrewster** [comment]
This has something to do with the `FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000` environment variable being set. I think it's automatically configuring the SDK to act as an admin.

**Comment by yuchenshi** [comment]
This has been fixed `@firebase/testing`. Please `npm i -D @firebase/testing@latest` and that should fix it. I also bumped the version in the quickstarts.
