### ISSUE TITLE
Missing typings for setSettings and setDefaults

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-js-sdk#2200]
The documentation makes mention of the methods `setDefaults()` and `setSettings()`. However upon implementing remote config I noticed they were missing.

`firebase-js-sdk@7.0.0`

https://github.com/firebase/firebase-js-sdk/blob/2b412d7c5c81ae2e99e922cf1d06f7838d470a8d/packages/firebase/index.d.ts#L1475

**Comment by Feiyang1** [comment]
Sorry, we made mistake in the remote config guide. `index.d.ts` is correct.
There is no setter for defaults and settings, instead they are top level properties that you can assign to directly. see [reference doc](https://firebase.google.com/docs/reference/js/firebase.remoteconfig.RemoteConfig.html?authuser=0#defaultconfig).

You will set settings and defaults as follows:
```
const remoteConfig = firebase.remoteConfig();

remoteConfig.settings = {
  minimumFetchIntervalMillis: 3600000,
};

remoteConfig.defaultConfig = {
   'welcome_message': 'Welcome'
}
```

Once the doc is fixed, I will report back.

**Comment by Feiyang1** [comment]
The [guide](https://firebase.google.com/docs/remote-config/use-config-web?authuser=0) has been updated. Closing the issue.
