### ISSUE TITLE
signInWithEmailAndPassword: getting auth/user-token-expired

### ISSUE THREAD

**Issue by navneetgarggate6** [firebase/firebase-js-sdk#2201]
I am using signInWithEmailAndPassword method in client sdk and getting auth/user-token-expired

1. It is happening when I am first calling revokeRefreshTokens and just after that using signInWithEmailAndPassword method to relogin user again.

2. I want to logout the user from all other devices.

3. I notice that after 30 sec signInWithEmailAndPassword again start working

**Comment by bojeil-google** [comment]
`revokeRefreshTokens` will reject all tokens before the present time. The precision is at the 1 second level. Calling `signInWithEmailAndPassword` immediately after may risk getting the current token getting rejected. You may have to add some delay before you allow the sign-in to execute.

**Comment by navneetgarggate6** [comment]
@bojeil-google delay of 30 sec is very log duration for user experience perspective. Is there any alternative to this ?

**Comment by bojeil-google** [comment]
Unfortunately there isn't any. Only option is possibly switch to using `Math.floor` for revocation: https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth-api-request.ts#L1009
But that will impact existing behavior.

I suggest you start a post on stackoverflow. There are probably other ways to achieve this via security rules, etc.

**Comment by bojeil-google** [comment]
Actually my bad, somehow i thought you said 30milliseconds. You shouldn't wait for 30 seconds. I speculate maybe your device clock is off or something.

**Comment by navneetgarggate6** [comment]
Right now its taking 30 secs. I checked the device clock is sync with the internet.

**Comment by bojeil-google** [comment]
After you call `revokeRefreshTokens`, can you `getUser` and check the `tokensValidAfterTime` on that user. That should be set to the current time. i speculate it is getting set to a future date due to you device clock being off.

**Comment by navneetgarggate6** [comment]
Well i am using following code. Let me check the time I am getting in serRecord.tokensValidAfterTime

FirebaseAdmin.auth()
      .revokeRefreshTokens(userId)
      .then(() => {
        return FirebaseAdmin.auth().getUser(userId);
      })
      .then(userRecord => {
        console.log(userRecord.tokensValidAfterTime);

        return new Date(userRecord.tokensValidAfterTime).getTime() / 1000;
      })
      .then(timestamp => {
        //return valid response to ios app to continue the user's login process
        console.log('Tokens revoked at: ', timestamp);
        return true;
      });

**Comment by navneetgarggate6** [comment]
As I checked the dates at same time getting following data

```
tokensValidAfterTime = Mon, 30 Sep 2019 05:30:31 GMT
device date: 2019-09-30T05:30:31.619Z
```

**Comment by bojeil-google** [comment]
I am talking about your server date where you revoke tokens. It has to be equal to the current present time. If it is off my 1 minute. That is sufficient to cause this issue.

**Comment by navneetgarggate6** [comment]
server time is the same 2019-09-30T05:30:31.619Z at that  time

**Comment by navneetgarggate6** [comment]
Ok, I got it. NTP synchronized  was off I change it now my code is working fine.
Thanks for the help

**Comment by bojeil-google** [comment]
A 1 second delay would be a good idea, just incase.
