### ISSUE TITLE
VS Code keeps auto-importing undefined from 'firebase/empty-import'

### ISSUE THREAD

**Issue by simonhaenisch** [firebase/firebase-js-sdk#2203]
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: _____
  * Firebase SDK version: 7.0.0
  * Firebase Product: empty-import

### [REQUIRED] Describe the problem

Every time I type "undefined", VS Code auto-imports

```ts
import undefined from 'firebase/empty-import';
```

This started happening since updating firebase a while ago, and is really inconvenient for the dev experience.

The only thing [empty-import.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/empty-import.d.ts) seems to be good for is to set the `typings` field on various packages (e. g. [here](https://github.com/firebase/firebase-js-sdk/blob/b4ee745b4ed7a4f4a95acd08c9e384868ae4dbae/packages/firebase/installations/package.json)). Can't it

```ts
export = {};
```

instead of `export = undefined`?

Thanks!

**Comment by Jaki117** [comment]
I have the same problem.

**Comment by camsjams** [comment]
I have the same issue, its probably occurring 3-5 times a day.

**Comment by Kordian-Dziwisz** [comment]
Same
vscode info:
```Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.80-1-MANJARO```

**Comment by mrubiales** [comment]
As a workaround while the issue is fixed I'm pressing
 the `esc` key when VSCode suggest me the Auto import action for `undefined`.

<img width="809" alt="Captura de pantalla 2019-11-13 a las 14 28 05" src="https://user-images.githubusercontent.com/20309236/68768292-8cda6880-0622-11ea-8d4f-6ad41d66ddb5.png">

**Comment by zjaml** [comment]
Same, unbelievable

**Comment by kevinphelps** [comment]
This is extremely annoying.

**Comment by simonhaenisch** [comment]
The team just ignoring this issue is even more annoying than the actual issue... not even a comment about why they wouldn't be able to change that 🙄

**Comment by bjon** [comment]
+1000 for annoying

**Comment by camsjams** [comment]
Hopefully they accept my PR: https://github.com/firebase/firebase-js-sdk/pull/2379

The original commit was from: https://github.com/firebase/firebase-js-sdk/commit/d96a80616bba66f7eb17be0ca8f07236ff1d96b9#diff-f1b496116df86a8f96044cc9a1a11b9c

I think it aimed to solve: https://github.com/microsoft/TypeScript/issues/6022
