### ISSUE TITLE
Remote Config: remoteConfig.setSettings is not a function

### ISSUE THREAD

**Issue by jkmosa01** [firebase/firebase-js-sdk#2207]
### Describe your environment  
  * Operating System version: MacOS Mojave
  * Browser version: Chrome 77
  * Firebase SDK version: 7.0.0
  * Firebase Product: Remote Config

### Describe the problem

I am unable to call setSettings or setDefaults for Firebase Remote Config for the web.

#### Steps to reproduce:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
    firebase.initializeApp(firebaseConfig);
    var remoteConfig = firebase.remoteConfig();

    remoteConfig.setSettings({
      minimumFetchIntervalInSeconds: 3600,
    });

    remoteConfig.setDefaults({
      'test': 'Test Value',
    });

    console.log(remoteConfig.getValue("testValue").asString());
```

**Comment by Feiyang1** [comment]
There is no `setSettings()` method on `remoteConfig`. It is the mistake we made in the [guide](https://firebase.google.com/docs/remote-config/use-config-web?authuser=0). I will report back once the doc is fixed.

`setting` is a property on `remoteConfig`. You can assign to it directly. For example:
```
const remoteConfig = firebase.remoteConfig();

remoteConfig.settings = {
  minimumFetchIntervalInSeconds: 3600,
};
```
You can see its definition in the [reference doc](https://firebase.google.com/docs/reference/js/firebase.remoteconfig.RemoteConfig.html?authuser=0#settings).
Sorry again for the confusion.

**Comment by kroikie** [comment]
Updated the snippet to:

```
remoteConfig.settings = {
  minimumFetchIntervalMillis: 3600000,
};
```

Switched to `minimumFetchIntervalMillis` from the reference doc.

**Comment by Feiyang1** [comment]
Closing since the issue has been resolved.
