### ISSUE TITLE
can't install firebase js sdk  because it requires... python2?

### ISSUE THREAD

**Issue by ttaranov** [firebase/firebase-js-sdk#2209]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS X
  * Browser version: n/a
  * Firebase SDK version: latest/7.0
  * Firebase Product: all

### [REQUIRED] Describe the problem
`npm install --save firebase` fails with
...
> grpc@1.23.3 install node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.23.3 and node@12.11.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error unable to verify the first certificate 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "//anaconda3/bin/python"
gyp ERR! find Python - version is "3.7.3"
gyp ERR! find Python - version is 3.7.3 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python 
```

#### Steps to reproduce:
<!--
  What happened? How can we make the problem occur?
  This could be a description, log/console output, etc.
-->
#### Relevant Code:

`npm install --save firebase`


<!--
  Reproduce the issue on StackBlitz and provide your forked URL
  or give us some sample code below
-->
https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by Feiyang1** [comment]
It seems the prebuilt binaries for grpc are not installed successfully for you, so it falls back to build it from source, which requires Python.

Are you using anti virus software or behind a company proxy? From the past experience, these things can fail the grpc prebuilt binaries download. e.g. https://github.com/grpc/grpc-node/issues/121

**Comment by ttaranov** [comment]
Thanks! it wasn't AV, but a corporate proxy
`NODE_TLS_REJECT_UNAUTHORIZED=0 npm i --save firebase` 
fixed it for me

**Comment by Berkmann18** [comment]
Trying `NODE_TLS_REJECT_UNAUTHORIZED=0 npm i --save firebase` didn't help in my case.
