### ISSUE TITLE
Firestore doesn't compile with Typescript + Webpack

### ISSUE THREAD

**Issue by luskin** [firebase/firebase-js-sdk#2215]
### [REQUIRED] Describe your environment

  * Operating System version: OSX
  * Browser version: N/A
  * Firebase SDK version: 7.0.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

All firebase products work fine _EXCEPT_ firestore when using Typescript and webpack. Our imports are as follows:

```javascript
import * as app from 'firebase/app'
import 'firebase/auth'
import 'firebase/database'
import 'firebase/firestore'
```

Without the `firestore` import there are no problems, auth and database work just as expected, however when introducing firestore into the mix typescript/webpack fails to compile with the following weird error:

`"errorMessage": "package.json does not exist at /package.json"`

I have tried all other variations of importing firestore from node_modules but nothing seems to fix this issue (as reported in #1008)

**When running a script directly with `ts-node` there is no problem so it must be something with the webpack process that is breaking.**

#### Steps to reproduce:
*webpack.config.js*:
```javascript
const path = require('path')
const slsw = require('serverless-webpack')
const webpack = require('webpack')

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: 'source-map',
  resolve: {
    mainFields: ['main'],
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  plugins: [new webpack.IgnorePlugin(/^pg-native$/)],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' },
    ],
  },
}
```

*tsconfig.json:*
```json
{
  "compilerOptions": {
    "lib": ["es2017"],
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "target": "es2017",
    "sourceRoot": "/",
    "rootDir": "./app",
    "outDir": "src",
    "allowSyntheticDefaultImports": true
  },
  "exclude": ["node_modules"]
}
```

**Comment by schmidt-sebastian** [comment]
Thanks for your report!

@Feiyang1 @hsubox76 Is this something you could look at? Thanks!

**Comment by Feiyang1** [comment]
I used my own webpack config and It worked fine.  
I wonder if `serverless-webpack` has something to do with it, so I installed `serverless-webpack` and tried your webpack config file, but I got an error that says `configuration.entry should be an non-empty object`.

Sorry I have no knowledge on how `serverless-webpack` works, or how to set it up in a project. It would help me a lot to debug if you can create a minimal repro and upload to github or somewhere.

**Comment by luskin** [comment]
hi @Feiyang1 I was able to find time to create a small reproduction repo, please see [here](https://github.com/luskin/firestore-ts-issue/)

Let me know if you have any issues and thanks for the support!

**Comment by Feiyang1** [comment]
Sorry for the delayed response. The issue is that grpc packages which are dependencies of firestore should not be bundled. See my [answer](https://github.com/firebase/firebase-js-sdk/issues/2010#issuecomment-516646790) to a similar issue.

To fix your issue, add the following block to your webpack config:
```
  externals: [
    function (context, request, callback) {
      if (/grpc/.test(request)) {
        return callback(null, 'commonjs ' + request);
      }

      callback();
  }]
```

**Comment by luskin** [comment]
@Feiyang1 thank you for the recommendation - it did fix that specific problem but introduced a new one. We are now receiving the following error:

```
 @firebase/firestore: Firestore (7.0.0): INTERNAL UNHANDLED ERROR:  Error: ENOENT: no such file or directory, open '/src/protos/google/firestore/v1/firestore.proto'
```

**Comment by Feiyang1** [comment]
The bundling changed the relative path. You need to copy the protos to the webpack output folder.
Install `copy-webpack-plugin` and add the following lines to your webpack config:
```
const CopyPlugin = require('copy-webpack-plugin');
module.exports = {
...
  node: {
    __dirname: false // it is needed so webpack doesn't change the __dirname to `/`
  }, 
  plugins: [
    new CopyPlugin([
      {
        from: 'node_modules/@firebase/firestore/dist/src',
        to: 'src'
      }
    ])
  ]
}
...
```

A simpler solution might be just excluding the entire `@firebase/firestore` package from bundling, so the relative path is maintained inside it. You need to change the regex of my initial solution to match `@firebase/firestore`
```
  externals: [
    function (context, request, callback) {
      if (/@firebase\/firestore/.test(request)) {
        return callback(null, 'commonjs ' + request);
      }

      callback();
  }]
```

**Comment by luskin** [comment]
Thanks @Feiyang1 

Unfortunately for some reason the first fix breaks other aspects of the compilation process.

I tried going for the simpler solution fix and am now receiving this error:

`firebase_app__WEBPACK_IMPORTED_MODULE_0__.firestore is not a function`

**Comment by Feiyang1** [comment]
Ah I see. Please change  the regex to `/@firebase/` to exclude all firebase packages from bundling.
The issue was that `@firebase/app` was bundled and the unbundled `@firebase/firestore` couldn't find it and register itself.

**Comment by luskin** [comment]
@Feiyang1 thanks for the continued support! Unfortunately we are STILL running into errors. I have upgraded the webpack config as you requested:

webpack.config.js:
```javascript
const path = require('path')
const slsw = require('serverless-webpack')
const webpack = require('webpack')
const CopyPlugin = require('copy-webpack-plugin')

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: 'source-map',
  resolve: {
    mainFields: ['main'],
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  plugins: [new webpack.IgnorePlugin(/^pg-native$/)],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' },
    ],
  },
  externals: [
    function (context, request, callback) {
      if (/@firebase/.test(request)) {
        return callback(null, 'commonjs ' + request);
      }

      callback();
    }]
}
```

However we are now receiving this error:
```javascript
Error	{
    "errorType": "Error",
    "errorMessage": "Cannot find module '@firebase/app'",
    "code": "MODULE_NOT_FOUND",
    "stack": [
        "Error: Cannot find module '@firebase/app'",
        "    at Function.Module._resolveFilename 
...... etc
```

**Comment by Feiyang1** [comment]
I used your configuration and it works fine with the repo you provided. 
I uploaded it to https://github.com/Feiyang1/firestore-ts-issue. Can you try it and see if you can get the same error?
Perhaps you have some other code that might be the culprit, but is not in this repo? I made you a collaborator, so feel free to upload to a new branch if you can repro.

**Comment by luskin** [comment]
Seems like it's working locally, however when deployed to AWS Lambda it throws that error. I tried locally using `node10.x` as well as `node8.10` and both work, however using the same node version on lambda throws this error.

At this point I think we're going to have to remove firestore completely and work towards another solution.

**Comment by Feiyang1** [comment]
Ok. How easy/hard is it to deploy it to AWS? If you can provide some instructions, I can try it and see if I can figure it out. 
I totally understand you have to move to another solution, but if you want to continue to explore Firestore, I'd love to help.

**Comment by luskin** [comment]
@Feiyang1 all you need to do is setup a serverless.com account and grant access to your AWS account ([see here](https://serverless.com/framework/docs/providers/aws/guide/deploying/))

**Comment by luskin** [comment]
@Feiyang1 any update on this? It's the only thing holding us back from a release.

**Comment by Feiyang1** [comment]
I managed to get it to work on lambda. See what I did in this [commit](https://github.com/Feiyang1/firestore-ts-issue/commit/4d50b3daa7bb71ca5dc4a5e1cf0c228da58b6ce1).

There are 2 issues I had to overcome:
1. `node_modules` was not deployed to lambda, so I had to copy it to the output folder using `copy-webpack-plugin`. This is why you are getting `Cannot find module '@firebase/app'`.

2. The grpc binary we build locally isn't compatible with the runtime environment in lambda, so I had to do `npm rebuild --target=10.0.0 --target_arch=x64 --target_platform=linux --target_libc=glibc` before running `sls deploy`. Change `--target` to match the node version you are deploying to. 

Some caveats - It will increase the size of the deployment payload significantly because we are uploading the entire `node_modules`. You can probably do some optimization where you only upload firebase and its dependencies in `node_modules`.

Hope it helps!

<img width="1516" alt="Screen Shot 2019-12-12 at 2 35 34 PM" src="https://user-images.githubusercontent.com/4391036/70755721-6f66f000-1cef-11ea-8d92-ef3c4e1f24ff.png">

**Comment by luskin** [comment]
@Feiyang1 unfortunately this solution increases our payload by over 100x and thus lambda's fail to deploy since it's so large.

I'm struggling to understand why it's only Firestore that has this issue, without any of these changes we run realtime db and auth from firebase without any issues, so it definitely can find `@firebase/app` - the only thing that doesn't work is when we try to query against firestore.

**Comment by Feiyang1** [comment]
Firestore uses gRPC when running in Nodejs, and gRPC can't be bundled because it is a native module. Database and Auth don't use gRPC.
As a result, Firestore in Nodejs isn't designed to be bundled as well (It assumes the path to the proto files and bundling would break the assumption).

Basically if you are using Firestore, you can't bundle any firebase SDKs, but if you don't use Firestore, you can bundle them.

Can you make `node_modules` synthetically that only has firebase and its dependencies, so you can avoid the 100x size increase? 
serverless allows you to specify the artifact zip file to be deployed, so you can point it to your custom zip file. - https://serverless.com/framework/docs/providers/aws/guide/packaging#artifact

**Comment by luskin** [comment]
@Feiyang1 I actually just now got it working thanks to [this tutorial](https://medium.com/mtlserverless/firestore-the-serverless-framework-the-easy-way-262e574581d0) - I don't know how I missed this before. A few small issues but was able to get everything up and running on lambdas.

Thank you for all of you continued support, I will go ahead and close this out now.

**Comment by Feiyang1** [comment]
Awesome. Glad you figured it out!
