### ISSUE TITLE
remoteConfig.getString doesn't return values for conditions based on user properties

### ISSUE THREAD

**Issue by ttaranov** [firebase/firebase-js-sdk#2221]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS
  * Browser version: Latest Chrome 77
  * Firebase SDK version: Latest/7.0
  * Firebase Product: Remote Config

#### Steps to reproduce:
Remote Config getString() (and I presume others), don't return correct values based on conditions setup using user properties

#### Relevant Code:
Maybe I'm doing something wrong, but here is what it is right now...

- setup remote config WelcomeMessage in firebase and define condition for a value based User Property `state` (say default value is `Welcome!` and for users with `state`=`ca` set value as `Welcome CA!`
- run code below and check output for `remoteConfig.getString('WelcomeMessage')` - no matter what I tried, the value always comes back as default and not based on the condition setup around user property

```javascript

firebase.initializeApp(firebaseConfig);
const remoteConfig = firebase.remoteConfig();
remoteConfig.settings = {
    minimumFetchIntervalMillis: 3600000,
    defaultConfig: {
        'WelcomeMessage': 'Welcome Default'
    }
};

firebase.analytics().setUserProperties({
    state: 'ca'
},{
    global: true
});

remoteConfig.fetchAndActivate()
    .then(() => {
        console.log("Remote-config initialized")
        console.log(remoteConfig.getString('WelcomeMessage'))
    })
    .catch((err) => {
        console.error("Remote config error", err);
    });

```

**Comment by Feiyang1** [comment]
Thanks for reporting the issue! We found a problem with `{global: true}` that prevents user properties from being sent to our backend. We are working on a fix and will report back once it's fixed. 

As a workaround for now, please set user properties with the `global` parameter:
```
firebase.analytics().setUserProperties({
    state: 'ca'
});

// send an event, so user properties are uploaded.
firebase.analytics().logEvent('');
```
Note: on web, user properties need to be uploaded for being used for targeting.

**Comment by ttaranov** [comment]
thank you for the response, although that didn't work either (I removed global, added logEvent). Is there no way to fetch properties with user attributes without involving analytics?

**Comment by Feiyang1** [comment]
Correct. User props need to be processed by analytics backend first, then they become available for targeting. Remote config backend uses a device id to look up the corresponding user props at backend when you send a fetch request.

It's different than how it works in native SDKs where user props are attached with remote config fetch request at client side.

There might be a slight delay btw when you send the user props and when it becomes available for targeting. Have you tried after sometime?

Another way you can check is create an audience based on the user property. In the creation page, there should be a summary section that tells you how many users are in this audience. What number do you see?
