### ISSUE TITLE
auth().sendPasswordResetEmail returns malformed error object in catch

### ISSUE THREAD

**Issue by tannerellen** [firebase/firebase-js-sdk#2227]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.14.6
  * Browser version: 12.1.2
  * Firebase SDK version: 5.10.1
  * Firebase Product: auth

#### Steps to reproduce:

Errors from using an invalid email with firebase.auth().sendPasswordResetEmail are malformed. The error object returned should have a code and message property as shown in the docs:
https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#sendpasswordresetemail

It appears that the error object returned contains another object and that object contains the code and message properties. This object is usually named "Vi" but I have also seen "Ki".

I have tested this in both version 5.10.1 and 7.0.0 and the issue exists in both versions.

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
firebase.auth().sendPasswordResetEmail(
    'user@example.com')
    .then(function() {
      // Password reset email sent.
    })
    .catch(function(error) {
      // Error occurred. Inspect error.code.
      console.log(error);
    });
```

**Comment by wti806** [comment]
I tested on my end and it works fine. Can you deploy the code snippet to https://stackblitz.com/fork/firebase-issue-sandbox so I can reproduce?

**Comment by tannerellen** [comment]
The code is up but it looks like the version of firebase being used there is 4.9.0. I’m pretty sure this worked for me also when using an older version of firebase. If we change that to 5.10 or newer I believe the issue should occur. I’m not sure exactly what version started having the issue but this used to work for me and then I updated to firebase 5.10.1 and now it’s happening.

Thanks,

Tanner Ellen
tannerellen@me.com

**Comment by wti806** [comment]
You didn't provide the URL of your repo. I created one using 5.10.1. Both code and message are in the error: https://stackblitz.com/edit/firebase-issue-sandbox-rnhcey
