### ISSUE TITLE
Fails to create installation on older versions of webOS

### ISSUE THREAD

**Issue by MilosRasic** [firebase/firebase-js-sdk#2247]
### [REQUIRED] Describe your environment

  * Operating System version: webOS 1.x - webOS 3.x
  * Browser version: http://webostv.developer.lge.com/discover/specifications/web-engine/
  * Firebase SDK version: 0.4.18
  * Firebase Product: app, remote-config

### [REQUIRED] Describe the problem

When trying to initialize app on webOS 1.x through 3.x, the SDK fails with create-installation-failed error.

The app works fine in browser and on webOS 4.x

#### Steps to reproduce:

- Package a simple sample app as LG webOS web app, either packaged or hosted (problem noticed with a hosted app)
- Install your ipk on a device
- Try to open the app

#### Relevant Code:

No sample code to reproduce but I did some debugging and it seems the SDK is using IndexedDB `deleteObjectStore()` method which is unsupported on older versions of webOS as shown here: http://webostv.developer.lge.com/application/files/api_references/20170608_1496987509/

Since the remote dev tools on webOS are crippled and the stack trace is useless, I've added some console logs to the installations index.esm.js like this:

```javascript
/** This will be executed only once for each new Firebase Installation. */
function registerInstallation(appConfig, installationEntry) {
    return __awaiter(this, void 0, void 0, function () {
        var registeredInstallationEntry, e_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    console.log('REGISTER: CREATE INSTALLATION');
                    _a.trys.push([0, 2, , 7]);
                    return [4 /*yield*/, createInstallation(appConfig, installationEntry)];
                case 1:
                    console.log('REGISTER: SET');
                    registeredInstallationEntry = _a.sent();
                    return [2 /*return*/, set(appConfig, registeredInstallationEntry)];
                case 2:
                    console.log('REGISTER: REMOVE');
                    e_1 = _a.sent();
                    if (!(isServerError(e_1) && e_1.serverCode === 409)) return [3 /*break*/, 4];
                    // Server returned a "FID can not be used" error.
                    // Generate a new ID next time.
                    return [4 /*yield*/, remove(appConfig)];
                case 3:
                    console.log('REGISTER: SENT');
                    // Server returned a "FID can not be used" error.
                    // Generate a new ID next time.
                    _a.sent();
                    return [3 /*break*/, 6];
                case 4: 
                    console.log('REGISTER: SET 2');
                // Registration failed. Set FID as not registered.
                return [4 /*yield*/, set(appConfig, {
                        fid: installationEntry.fid,
                        registrationStatus: 0 /* NOT_STARTED */
                    })];
                case 5:
                    console.log('REGISTER: SENT 2');
                    // Registration failed. Set FID as not registered.
                    _a.sent();
                    _a.label = 6;
                case 6: throw e_1;
                case 7: return [2 /*return*/];
            }
        });
    });
}
/** Call if FID registration is pending. */
function waitUntilFidRegistration(appConfig) {
    return __awaiter(this, void 0, void 0, function () {
        var entry;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: 
                    console.log('WAIT UNTIL FID REGISTRATION: UPDATE INSTALLATION REQUEST', appConfig);
                    return [4 /*yield*/, updateInstallationRequest(appConfig)];
                case 1:
                    console.log('WAIT UNTIL FID REGISTRATION: SENT');
                    entry = _a.sent();
                    _a.label = 2;
                case 2:
                    console.log('WAIT UNTIL FID REGISTRATION: IN PROGRESS');
                    if (!(entry.registrationStatus === 1 /* IN_PROGRESS */)) return [3 /*break*/, 5];
                    // createInstallation request still in progress.
                    return [4 /*yield*/, sleep(100)];
                case 3:
                    console.log('WAIT UNTIL FID REGISTRATION: IN PROGRESS 2', appConfig);
                    // createInstallation request still in progress.
                    _a.sent();
                    return [4 /*yield*/, updateInstallationRequest(appConfig)];
                case 4:
                    console.log('WAIT UNTIL FID REGISTRATION: SENT 2')
                    entry = _a.sent();
                    return [3 /*break*/, 2];
                case 5:
                    if (entry.registrationStatus === 0 /* NOT_STARTED */) {
                        throw ERROR_FACTORY.create("create-installation-failed" /* CREATE_INSTALLATION_FAILED */);
                    }
                    console.log('WAIT UNTIL FID REGISTRATION: DONE');
                    return [2 /*return*/, entry];
            }
        });
    });
}
```

Here's the output. Note that I'm trying to initialize two Firebase apps:
![firebase2](https://user-images.githubusercontent.com/533052/66482388-20100380-eaa3-11e9-951e-54a174902cb9.png)
(yeah, welcome back to 20 years ago)

~~Looks like this confirms it's failing after an attempt to call `deleteObjectStore()`~~

**Comment by MilosRasic** [comment]
Turns out it's actually failing because of missing fetch API but error handling is obscuring the real error. After logging `e_1` in `case 2` of `registerInstallation()` I could see that it's failing when trying to call `Headers` constructor.

**Comment by Feiyang1** [comment]
Hi, thanks for your report!
Based on my quick google search on webOS, it seems possible to add polyfill to webOS apps. Can you add a fetch polyfill, e.g. https://github.com/lquixada/cross-fetch and see if it works?

**Comment by MilosRasic** [comment]
@Feiyang1 yeah, I used whatwg-fetch and it works for now. Going to see if it works fine with IndexedDB cache expiry because I did find a use `deleteObjectStore()` in the SDK code.

Not sure about cross-fetch. Says it's unsupported on Safari at the bottom of the readme and older versions of webOS (Tizen too) are running a build of webkit most similar to Safari 6.

So, there's to issues here I guess:
* Would be nice if we could get a dev-friendly error that fetch API is not available or at least the original error. Took hours to figure out what's wrong without proper dev tools. With the original error it would have been instantly obvious.
* If not me someone is going to hit the problem with missing `deleteObjectStore()` at some point. Might make sense to fall back to local storage if incomplete IndexedDB API is available.

**Comment by adamduren** [comment]
Here is a screenshot of all occurrences from our error reporting service since we started seeing the same error.

**Some notes from the data:**
  * Started occurring after upgrading to `firebase@7.0.0`
  * Firebase remote config for web was also implemented at this time
  * Has appeared in a very small percentage of users at ~1% (12 out of 1,233)
  * Occurs on browsers that have the `fetch` api
  * Occurs when the fetch call fails as seen in XHR logs

Is there a prescribed workaround?

![sentry io_organizations_truzen_issues_1246685247_events__project=1461556 statsPeriod=14d (1)](https://user-images.githubusercontent.com/581097/66612173-c9bfc500-eb75-11e9-8d27-696253654d1a.png)

**Comment by Feiyang1** [comment]
@adamduren What Firebase products do you use? The error comes from `@firebase/installations` which is a dependency of Remote Config/Analytics/FCM/Performance.

Did the fetch call fail due to network issue or server error? If server error, what is the error?

**Comment by adamduren** [comment]
I use many firebase products but these are client side error reports and it appears to have started appearing once I implemented remote config for web.

Not sure what the status of the http request is when it fails but looking at other requests for other resources around the same time appear to be successful so I'm thinking the remote config service is occasionally erroring out.

**Comment by MilosRasic** [comment]
We released a version of our app for Vizio devices with Firebase yesterday and in around 24 hours we've got 49 installations/create-installation-failed errors. This is all Chrome v68. Is preserving the original error something a PR would be welcome for? We'd really like to figure out why it's failing before considering our next steps.

**Comment by Feiyang1** [comment]
@mmermerkaya Can we add more detailed message for the error?

**Comment by mmermerkaya** [comment]
Done in #2297 :)

**Comment by Feiyang1** [comment]
Nice! 
@MilosRasic Can you please upgrade the sdk to `firebase@7.2.3` or above? Let me know what error message you get after the upgrade.
