### ISSUE TITLE
Fails to retreive data in Microsoft Edge -- Firestore (6.6.2): Could not reach Cloud Firestore backend

### ISSUE THREAD

**Issue by ekfuhrmann** [firebase/firebase-js-sdk#2253]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home (v1903 -- OS Build 18362.418)
  * Browser version: Microsoft Edge 44.18362.387.0
  * Firebase SDK version: 6.5.0
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

My website is having issues pulling data from Firestore; however, this issue only occurs with Microsoft Edge. When the page loads in edge, I get the following **Error**:

```console
@firebase/firestore: Firestore (6.6.2): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

My firebase config is as follows:
```javascript
import firebase from 'firebase/app';
import 'firebase/app';
import 'firebase/firestore';
import 'firebase/storage';

export const fb = firebase.initializeApp({
  apiKey: '<removed>',
  authDomain: '<removed>',
  databaseURL: '<removed>',
  projectId: '<removed>',
  storageBucket: '<removed>'
});

export const store = fb.firestore();

export const storage = fb.storage();
```

and then in App I have this:
```javascript
componentDidMount() {
    store
      .collection('col')
      .where('Listing Status', '==', 'active')
      .onSnapshot(function(querySnapshot) {
        let cols = [];
        querySnapshot.forEach(function(doc) {
          cols.push(doc.data());
        });

        that.setState({
          datas: cols
        });
      });
  }
```

From testing I can tell that it seems to be breaking down inside the `forEach` as I can't return any `console.logs` inside of there., but I'm following the docs in terms of pulling the data and I've had no trouble in other browsers.

Any help would be much appreciated!

Quick edit: The data DOES eventually pull, it just takes **minutes** for it to finally render?

**Comment by var-const** [comment]
Sorry to hear about your issues! I will try to reproduce this tomorrow, once I get to my Windows machine.

**Comment by ekfuhrmann** [comment]
Thanks for taking a look. If it helps, I could PM you the staging site as well so you can see it get caught up on Edge, but outside of that the code I have up there is all that I'm using for firebase.

**Comment by ekfuhrmann** [comment]
@wilhuff Thanks for the help. It does indeed seem to be something wrong with my instance of Edge as opposed to anything Firebase related. Thanks for the help.

**Comment by millscan** [comment]
I'm having a similar issue. Fetching on Edge works on my system, but not on my client's. Any update on this issue?
