### ISSUE TITLE
Firestore security rules for collections

### ISSUE THREAD

**Issue by Siegrift** [firebase/firebase-js-sdk#2283]
### [REQUIRED] Describe your environment

  * Operating System version: Linux Mint 19.2 Tina
  * Browser version: 77.0.3865.120
  * Firebase SDK version: ^6.4.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
I am using the following security rules in firestore:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
  	match /{document=**} {
      allow read: if resource.data.authId == request.auth.uid;
      allow write: if resource.data.authId == request.auth.uid;
    }
  }
}
```
However in my code I want to query for all documents inside a collection and I want firebase to return only the ones for which the rules apply. Like this:
```
firestore().collection('transactions')
```

This however fails with a firestone error:
```
Uncaught Error in onSnapshot: FirebaseError: Missing or insufficient permissions.
    at new FirestoreError ...
```

This is consistent with the rules simulator as well. Can you please tell me how to fix this? I was trying to find examples of this, but I couldn't find any... 

If this is not possible for some reason, can you recommend how to structure the data and write the rules?

**Comment by rockwotj** [comment]
Firestore security rules are not filters. 

Your query needs to ensure that you only return documents where the user ID is that of the logged in user. Here is a following query that would work:

```
db.collection("Foo").where("authId", "=", currentUserUid()).get();
```

**Comment by Siegrift** [comment]
@rockwotj Thank you.

**Comment by rockwotj** [comment]
Also see this page of the documentation @Siegrift 
https://firebase.google.com/docs/firestore/security/rules-conditions#rules_are_not_filters
