### ISSUE TITLE
Update grpc denepency of firestore package to 1.24.1

### ISSUE THREAD

**Issue by dzhamshed** [firebase/firebase-js-sdk#2293]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 7.2.1
  * Firebase Product: Firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem
Firestore package has dependency on grpc version 1.24.0, but grpc 1.24.0 has problem with installation and it gives error while installing firebase. According to [this](https://github.com/grpc/grpc-node/issues/1067#issuecomment-545066689), the problem with grpc installation was solved in 1.24.1. Please, update the grpc version from 1.24.0 to 1.24.1 in firestore dependencies, so we could upgrade firebase to the latest version. This issue prevents to upgrade to the firebase major version 7.

#### Steps to reproduce:
npm install firebase

**Comment by thebrianchen** [comment]
@dzhamshed The renovate-bot automatically updates core dependencies every week (example [PR](https://github.com/firebase/firebase-js-sdk/pull/2278)), and we manually merge it every week. The update to the gRPC dependency should go out in the next release.
