### ISSUE TITLE
Allow SDK to auto initializeApp when hosted on Firebase

### ISSUE THREAD

**Issue by justweb1** [firebase/firebase-js-sdk#23]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Firebase Hosting
  * Firebase SDK version: Future with lazy loading - see https://github.com/firebase/firebase-js-sdk/pull/15
  * Library version: 
  * Firebase Product: All

#### Issue:

1. Currently when hosted on Firebase a user has to load component scripts in the correct order (auth, database, app)
2. Then they need to call `'/__/firebase/init.js'`

These steps do not play well with polymerfire or angularfire. The user still needs to declare the config properties either directly or by setting up their own secrets.

#### Request:

1. Add a test to check if app is hosted on Firebase.
```
var _isFirebaseHosted = fetch('/__/firebase/init.js').then(response => {
  if (response.status == 200) {
    return true;
  }
  return false;
});
```
2. Auto initializeApp
```
if (_isFirebaseHosted) {
 firebase.initializeApp('/__/firebase/init.js');
}
```
@mbleigh @jshcrowthe

**Comment by jshcrowthe** [comment]
Hey @justweb1 I'm not sure that we want to necessarily add this kind of support to the SDK itself. It seems like customizing the SDK, based on where it is being hosted, could have some **very** interesting issues. It's an interesting idea though and I agree that we can do a better job of simplifying the startup for consumers of the SDK.

**Comment by GzusGo** [comment]
I have already 2 weeks trying to get this set up in my environment, the angular 4 framework does not play well with the request of the file /__/firebase/init.json and I getting out of ideas. I think if this is done would increase the productivity . on angular dev exponentially. make available something I have every another project that is the ability to switch environment without been recording all the credentials and server vars all the time.
