### ISSUE TITLE
Database permission_denied after linking a provider (linkWithPopup)

### ISSUE THREAD

**Issue by khammami** [firebase/firebase-js-sdk#230]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Chrome Version 63.0.3236.0 (Official Build) dev (64-bit)
  * Firebase SDK version: 4.5.1
  * Firebase Product: database, auth

### [REQUIRED] Describe your environment
database write permission denied after linking other providers with a popup. updates in the same page before works as intended but after linking an other provider I get a warning

it used to work fine before updating js sdk

```javascript
util.js:189 FIREBASE WARNING: update at /users/xxxxxxxx/data failed: permission_denied 
t.warn @ util.js:189
(anonymous) @ Repo.js:309
(anonymous) @ PersistentConnection.js:411
t.Tt @ PersistentConnection.js:444
e.Tt @ Connection.js:262
e.an @ Connection.js:256
(anonymous) @ Connection.js:157
t.Fn @ WebSocketConnection.js:197
t.handleIncomingFrame @ WebSocketConnection.js:247
mySock.onmessage @ WebSocketConnection.js:144
15:33:47.264 Repo.js:510 Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied
    at Repo.js:510
    at Object.t.exceptionGuard (util.js:556)
    at e.callOnCompleteCallback (Repo.js:501)
    at Repo.js:314
    at PersistentConnection.js:411
    at t.Tt (PersistentConnection.js:444)
    at e.Tt (Connection.js:262)
    at e.an (Connection.js:256)
    at t.onMessage (Connection.js:157)
    at t.Fn (WebSocketConnection.js:197)
```

#### Steps to reproduce:

database rule ".write": "$uid === auth.uid"
main provider is Google to signin/ create an account in my app
try to write data to the current user ref after linking another provider with popup 

=> https://local-guides-directory.firebaseapp.com/account

**Comment by stivaliserna** [comment]
I'm experiencing the same issue, after fresh install of my dependency tree which pulls latest version of firebase `4.5.2`.

**Comment by stivaliserna** [comment]
@khammami can you try with firebase version `4.5.0`?

I forced `4.5.0` on my setup and the issue disappeared. Somehow it seems related to #223. I came across the idea to downgrade to `4.5.0` after ready this comment: https://github.com/firebase/firebase-js-sdk/issues/223#issuecomment-336610508

**Comment by khammami** [comment]
thanks @stivaliserna, I have already reverted to 4.5.0 as noticed the issues after updating my dependencies.

**Comment by jshcrowthe** [comment]
@stivaliserna @khammami, I spun up an isolate repro of this and was unable to reproduce the issue.

I went through the following path:

1. Sign in with a fresh google account
1. Push Data to firebase with security settings mentioned above (i.e. `$uid === auth.uid`)
1. Validate pushed data
1. Link twitter account to google account
1. Push data to same firebase ref
1. Validate data

Can you guys get me some sample code to look at to help debug this?

**Comment by jshcrowthe** [comment]
I was able to repro this with help from the discussion here:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/8UJISRriQjE/nRDbjkJNAgAJ

There seems to be an odd minification issue going on.

**Comment by tianweiliu** [comment]
I can confirm this happens not only in linking providers but also with email and password. Basically auth after 4.5.0 brakes all "auth.uid === $uid" rules (read/write).
