### ISSUE TITLE
Testing Cloud Firestore: All calls time out

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [firebase/firebase-js-sdk#2305]
### Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 7.6.1
  * Firebase Product: Cloud Firestore security rules testing (`@firebase/testing`)

### Describe the problem

All Cloud Firestore tests time out:

```
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

#### Steps to reproduce:

Follow [the quickstart JS guide](https://github.com/firebase/quickstart-nodejs/blob/master/firestore-emulator/javascript-quickstart/README.md) precisely.  
I tried [everything here](https://stackoverflow.com/a/45858343/6509751), but I cannot fix it. Every test with `firebase.assertSucceeds` and `firebase.assertFails` times out.

#### Relevant Code:

```js
it(`whatever`, async function() {
  await firebase.assertSucceeds(db.doc(`a/b`).set({a: 4}))
})
```

**Comment by mikelehen** [comment]
Offhand it sounds like the tests can't talk to the emulator.  Just to confirm, `firebase emulators:start --only firestore` ran successfully and doesn't log any interesting output while the tests run?

**Comment by creativecreatorormaybenot** [comment]
@mikelehen Yes.

**Comment by mikelehen** [comment]
@yuchenshi Any ideas?

**Comment by yuchenshi** [comment]
Could you please upload the `firestore-debug.log` file after starting the emulator and running `npm test`?

**Comment by creativecreatorormaybenot** [comment]
@yuchenshi I created a Gist: https://gist.github.com/creativecreatorormaybenot/5709f3004d4ce8a6efb9c9721ee6e012

I also added the emulator and `npm test` logs. *Note* that I did not ever see the `Could not reach Cloud Firestore backend.` error before. I also tried running with virus & threat protection turned off.

**Comment by creativecreatorormaybenot** [comment]
I can finally run tests successfully after upgrading to `@firebase/testing 0.15.0`! However, the failing tests throw errors - I am not sure if that is intented to work like that, i.e. if any of my tests fail, the script will exit with error `code 1` and npm will generate a complete log of the run.
