### ISSUE TITLE
Add note to documentation clarifying state for `onAuthStateChanged`

### ISSUE THREAD

**Issue by fastfedora** [firebase/firebase-js-sdk#2306]
### [REQUIRED] Describe your environment

  * Operating System version: Mac 10.13.6
  * Browser version: Chromium 75
  * Firebase SDK version: 5.8.3
  * Firebase Product: auth

### [REQUIRED] Describe the problem

The documentation for getting the currently signed in user and for `onAuthStateChanged` does not make clear that `onAuthStateChanged` is called while the auth state is still being initialized. The name of the method implies that the auth state *has* changed by the time this event is called, when in fact, it is in the process of changing. 

This causes problems when writing code that assumes that `currentUser` is set when `onAuthStateChanged` is called. For instance:

```
firebase.auth().onAuthStateChanged(async function(authUser) {
  await initializeApp();        // somewhere in the init chain we call `firebase.auth().currentUser`
});
```

While this can be remedied by relying *only* on the user passed to `onAuthStateChanged` and avoiding `currentUser` entirely, it is not obvious from the current documentation that this is required.

This is causing much confusion, such as in issue #462 where there is a request to make an async `getCurrentUser`. 

The specific docs to add a note would be:

- [Get the currently signed-in user](https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user)
- [Firebase API - Auth.onAuthStateChanged](https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#onauthstatechanged)

There is already a note in the first one indicating the `currentUser` may be null because the auth object may not be finished initializing, but it does not make clear that this may be the case _within_ the `onAuthStateChanged`.

For instance, it is possible for the error below to throw:

```
firebase.auth().onAuthStateChanged(async function(authUser) {
  if (authUser && !firebase.auth().currentUser) {
    throw new Error('The auth state is not done being initialized.')
  }
});
```

The confusion comes from the name of the event being `onAuthStateChanged`, which implies that `firebase.auth().currentUser` is finished being initialized when the method is called. A clearer way of handling this would be to rename the function `onAuthStateChanging` or `onAuthStateWillChange`, but this would be a breaking change. 

#### For [Get the currently signed-in user](https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user)

Update the note to read something like:

> Note: `currentUser` might also be null because the auth object has not finished initializing. Because `onAuthStateChanged` is called while the auth object is still initializing, this may be the case even within this observer. If you use an observer to keep track of the user's sign-in status, and avoid calling `currentUser` entirely, you don't need to handle this case.

#### For [Firebase API - Auth.onAuthStateChanged](https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#onauthstatechanged)

Add a note:

> This observer is triggered while the user's sign-in state is still being initialized and may be called before `currentUser` is set with the new user.

**Comment by hsubox76** [comment]
I would definitely like to dive into this more, but I haven't been able to reproduce the condition in the snippet above:

```
firebase.auth().onAuthStateChanged(async function(authUser) {
  if (authUser && !firebase.auth().currentUser) {
    throw new Error('The auth state is not done being initialized.')
  }
});
```

I gather from your phrasing ("it is possible") that the condition only happens sometimes.  Can you give me any tips on how to cause this to happen or increase its chances of happening?

It is not supposed to happen, so it may be a bug, or it may be an edge case.  Either way I would like to pin down exactly what is going on so we can give people the most correct info in any text we add to the documentation.
