### ISSUE TITLE
Firestore: check document existence without retrieving its data

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-js-sdk#2309]
* Firebase SDK version: 7.2.2
  * Firebase Product: Firestore

Hi, is there a way to check the existence of a document without retrieving its data through the network in case this document already exists?
The function `collection("myCol").doc("myDoc").get()` asynchronously retrieves the document snapshot. Then to check the existence of the document we can use `snapshot.exists` or we can get the data with `snapshot.data()` that returns `undefined` if the document does not exist. But if the document already exists we downloaded it for nothing even if it's huge and the network speed is terrible. It's the same with `query.limit(1).get().size == 1`: we have to retrieve a query snapshot prior to checking existence. 

What would you guys think of an asynchronous function `collection("myCol").doc("myDoc").exists()` that would only check the existence of a document and simply return a promise of a boolean instead of a snapshot?

**Comment by wilhuff** [comment]
There isn't a way to do this in the mobile/web SDKs. In the server SDKs you can do a keys-only query (that is, issue a query where the field mask is empty). In this regard this is a duplicate of #212, and similar feasibility problems.

However, it may be possible to do the higher level task you're trying to perform with the SDK as-is. Why do you want to know if a document exists but not have the document locally?

**Comment by laurentpayot** [comment]
Please note that the difference with #212 is that with this new `exists()` function there would be no need to retrieve a partial document with all the associated offline issues, but simply to return a promise of a boolean.

**Comment by wilhuff** [comment]
Makes sense. Unfortunately this isn't something we can do immediately.

For now a workaround is to keep two profile collections, one with the actual profile data and one that just reserves the username. Check for existence from the usernames collection. Once you go to actually create the profile use a transaction to create both documents at the same time. Inside the transaction you'll need to perform reads of both documents and validate they don't exist and then write out the username reservation and the profile.

See additional discussion here: https://stackoverflow.com/q/47405774.

**Comment by Rebel13Lvt** [comment]
This best be directly sent from me and correctly ,  confusion disturbed song !! Whoa baby whao!! Chill !? Got correct data thank god!!! Never mind above typos and thank yall for the help and also hope infos getting to correct phones!!! I Love you bambinos very much!!
~ Legacy

Naomi
Phoenix Legacy Photography ©️
2019

________________________________

**Comment by laurentpayot** [comment]
I ended up using Firestore REST API with the query string `mask.fieldPaths=none` to avoid downloading all the fields:
`https://firestore.googleapis.com/v1/projects/myproject/databases/(default)/documents/profiles/myusername?mask.fieldPaths=none`
404 errors tell me there is no such document.

Is there a cleaner way than using a `none` field name that does not exist to avoid downloading all the fields? The REST API documentation really lacks examples.

**Comment by laurentpayot** [comment]
UPDATE: You can now use the [count() aggregation](https://firebase.google.com/docs/firestore/query-data/aggregation-queries) to check if a document exists without downloading it. [See here for a TypeScript example.](https://stackoverflow.com/a/74373949/2675387)
