### ISSUE TITLE
analytics-types EventNameString definition is broken

### ISSUE THREAD

**Issue by MarcDAFrame** [firebase/firebase-js-sdk#2312]
#614 # [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18
  * Browser version: Chrome 71.0.3578.98 (Official Build) (64-bit)
  * Firebase SDK version: @latest
  * Firebase Product: analytics

### Describe the problem
analytics has an improper type definition. logEvent is supposed to accept "any custom string and interprets it as a custom event name." (https://firebase.google.com/docs/reference/js/firebase.analytics.html#event-name-string)
but the type is this
```ts
export type EventNameString =
  | 'add_payment_info'
  | 'add_to_cart'
  | 'add_to_wishlist'
  | 'begin_checkout'
  | 'checkout_progress'
  | 'exception'
  | 'generate_lead'
  | 'login'
  | 'page_view'
  | 'purchase'
  | 'refund'
  | 'remove_from_cart'
  | 'screen_view'
  | 'search'
  | 'select_content'
  | 'set_checkout_option'
  | 'share'
  | 'sign_up'
  | 'timing_complete'
  | 'view_item'
  | 'view_item_list'
  | 'view_promotion'
  | 'view_search_results';

  logEvent(
    eventName: EventNameString,
    eventParams?: EventParams,
    options?: AnalyticsCallOptions
  ): void;
``` 
this is also an issue for the EventParams
#### Steps to reproduce:
```ts
analytics = firebase.analytics()
analytics.logEvents("CUSTOMEVENTNAME")
```

**Comment by hsubox76** [comment]
Hi, can I ask you what error you are seeing when you do that?  I have tried to reproduce it with the following lines and they all seem to give no errors.  When executing the code, it does seem to log the events, as seen in the network request.

```app.analytics().logEvent('CUSTOMEVENTNAME');
firebase.analytics().logEvent('CUSTOMEVENTNAME2');
let analytics = firebase.analytics();
analytics.logEvent('CUSTOMEVENTNAME3');```

How are you importing firebase? Are you importing `@firebase/analytics` or just `firebase/analytics`?  The first will get you internal types which looks like the snippet you've pasted above, whereas the second will get you the public-facing type definitions, which have many overloads for `logEvent`, including a fallback for a custom eventName string.

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/67989880-9d461880-fc0a-11e9-8b51-4ce9f6fe9715.png)

it still compiles and runs, I just think that the type definition is wrong. 

I'm importing like this
```ts
import { firebase } from '@firebase/app';
import '@firebase/auth';
import '@firebase/functions';
import '@firebase/firestore';
import '@firebase/analytics';
import '@firebase/storage';
```
```ts
   "dependencies": {
     ...
        "firebase": "^7.1.0",
     ...
    }
```

but looking at the type definition (unless I'm missing something) it does't allow for custom strings

**Comment by Feiyang1** [comment]
You should use `firebase` package instead of the scoped packages, like below:
```
import * as firebase from 'firebase/app';
import 'firebase/analytics';
...
```
`firebase` is the official package that has all the proper typings. Ideally we should have the same typings in the scoped packages as well, but for historical reasons, they are slightly different.

**Comment by MarcDAFrame** [comment]
that fixed it.

thanks a bunch

closing the issue
