### ISSUE TITLE
Multiple database instances dont work [AUTH]

### ISSUE THREAD

**Issue by GuilhermeBCC** [firebase/firebase-js-sdk#2330]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10
  * Browser version: _____
  * Firebase SDK version: 7.2.2
  * Firebase Product: auth, database

Hello,

According to this [page](https://firebase.google.com/docs/database/usage/sharding#connect_your_app_to_multiple_database_instances) we can use several applications in the same App.

But they forget one crucial fact: I can't use RealtimeDB without Authentication!
There are no examples using authentication anywhere.

I would just like to use more than one database in my app.

Below a way that could work more does not work, why?

```javascript
      const app2 = firebase.initializeApp({
        apiKey: "myApiKey",
        databaseURL: 'https://mydb-2.firebaseio.com',
        appId: "myAppId",
      },'2');

      const token = await firebase.auth().currentUser.getIdToken(true);

      await firebase.auth(app2).signInWithCustomToken(token);

```

**Comment by hsubox76** [comment]
The token returned by `getIdToken()` is not the same as the custom token you would need to sign in.  Custom tokens are for a different use case, where you already have your own authentication process ([more here](https://firebase.google.com/docs/auth/admin/create-custom-tokens)).

[This blog post](https://firebase.googleblog.com/2016/12/working-with-multiple-firebase-projects-in-an-android-app.html) describes how to do what you're asking for in Android (see "Authenticating to two different Firebase Databases").

I'm trying to do some research to figure out how to translate that to web, namely, how to get the credential, but it seems like the solution is different depending on the auth provider (Google, Facebook, etc.) so can you tell me what provider you're using?

In any case, for this to succeed, you need to use `signInWithCredential()` and not `signInWithCustomToken()`.

**Comment by GuilhermeBCC** [comment]
I found the solution
https://stackoverflow.com/a/47879085

They should put it on the page I mentioned.  It was hard to find.
