### ISSUE TITLE
node-gyp build of gRPC fails due to a version mismatch?

### ISSUE THREAD

**Issue by sysRoot** [firebase/firebase-js-sdk#2331]
### [REQUIRED] Describe your environment

  * Operating System version: _____ Windows 10
  * Browser version: _____ Chrome Dev Version 80.0.3955.4 (Official Build) dev (64-bit)
  * Firebase SDK version: _____  I'd assume it's the latest, or whatever the Node package uses, I have tried the latest, next, and canary flags.
  * Firebase Product: _____ (auth, database, storage, etc) Firebase Node Package

### [REQUIRED] Describe the problem

Using Node 13, gRPC fails to build, have somewhat determined it's related to the firebase package looking for 1.24.1 however Node 13 support was added in 1.24.2

#### Steps to reproduce:

`npm i firebase` on NodeJS ver 13. 

#### Relevant Code:

```javascript
import firebase from 'firebase'
```

#### Addendum
A simple change to accept use of 1.24.2 grpc possible?
Otherwise, how can I specify it to use the local version of gRPC I have npm i'd already?

**Comment by markchristianlacap** [comment]
I am having the same problem. I am also using the latest version of node.

**Comment by markchristianlacap** [comment]
`yarn add firebase@canary`
 seems to work for me.

**Comment by AlphaWong** [comment]
same error

```console
node: v12.13.0
npm 6.12.0
Software:

    System Software Overview:

      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0
```

**Comment by marianzburlea** [comment]
`npm i firebase@7.2.2` worked for me

**Comment by hsubox76** [comment]
Hi, thanks for letting us know.  We have just upgraded Firebase deps to `grpc@1.24.2` in https://github.com/firebase/firebase-js-sdk/pull/2314.  This will not be in the official release until this Thursday (Nov 7) but you can get the current repo build as-is with `firebase@canary` (as mentioned by @markchristianlacap above) if you are in a rush.  Either that or temporarily downgrade Node if possible.  Sorry about the delay!

**Comment by Feiyang1** [comment]
`firebase@7.3.0` is out with `grpc@1.24.2`
