### ISSUE TITLE
Why does sendSignInLinkToEmail(email, settings) not check whether the given email exists?

### ISSUE THREAD

**Issue by fabianmarcus** [firebase/firebase-js-sdk#2332]
I don't understand, why firebase.auth().sendSignInLinkToEmail(email, settings) sends a login email to an email address which has not been registered yet.

Moreover, when I then click the link, which opens the site where I check the email with firebase.auth().signInWithEmailLink(email, signInEmailLink), the email gets registered and the user is logged in!

I think that's curios, because then (in case I only want to offer login by email link) it's not possible to separate the login process from the registration process. *I would expect, that I get an error when I call firebase.auth().sendSignInLinkToEmail(email, settings) with an unregistered email.*

Isn't that a design problem?

That's my code for sending the email and signing in when user clicked the link.
```
async login(email) {
    try {
        const settings = {
            handleCodeInApp: true,
            url: encodeURI(`${location.protocol}//${location.host}/#!/user/verifizieren`),
        };
        await firebase.auth().sendSignInLinkToEmail(email, settings);
        window.localStorage.setItem(storageKeyEmail, email);
    } catch(error) {
        console.error(error);
        throw error;
    }
},

async verify(email, link) {
    const signInEmailLink = link || window.location.href;
    if(!firebase.auth().isSignInWithEmailLink(signInEmailLink)) {
        return Promise.reject('auth/link-invalid');
    }
    try {
        await firebase.auth().signInWithEmailLink(email, signInEmailLink);
        firebase.auth().currentUser.reload();
        firebase.auth().currentUser.getIdToken(true);
        window.localStorage.removeItem(storageKeyEmail);
    } catch(error) {
        console.error(error);
        throw error;
    }
},
```

**Comment by bojeil-google** [comment]
This has already been answered at: https://stackoverflow.com/questions/58652045/why-does-sendsigninlinktoemailemail-settings-not-check-whether-the-given-emai/58666733?noredirect=1#comment103660468_58666733
