### ISSUE TITLE
"IDB requires a browser environment" when using Analytics/Performance

### ISSUE THREAD

**Issue by dsgriffin** [firebase/firebase-js-sdk#2336]
### Describe your environment

  * Operating System: Mac OSX
  * Firebase SDK version: 7.2.3
  * Firebase Product: Analytics/Performance

### Describe the problem

When trying to run setup (e.g. Jest tests in a Create-React-App project), getting `IDB requires a browser environment` when trying to include `analytics` and `performance` function calls. All other imports are fine. 

#### Relevant Code:

When running a Jest test on a component that interacts with the Firebase setup (shown below)

```javascript
import firebase from 'firebase/app';
import 'firebase/analytics';
import 'firebase/performance';
import 'firebase/firestore';
import 'firebase/auth';
...
export const analytics = firebase.analytics(); // Error: "IDB requires a browser environment"
export const performance = firebase.performance(); // Error: "IDB requires a browser environment"
export const firestore = firebase.firestore(); // Fine
export const auth = firebase.auth(); // Fine
export const storage = firebase.storage(); // Fine
```

If I run the test with a `-- --browser` flag it instead errors out at the import:

```
   ReferenceError: IDBIndex is not defined

      1 | import firebase from 'firebase/app';
    > 2 | import 'firebase/analytics';
```

**Comment by Feiyang1** [comment]
Both services require `indexedDB` to work. As far as I understand, Jest runs in Node where `indexedDB` is not available. 2 possible options:
1. Include an indexeddb shim in your tests before initializing Firebase services, e.g. [indexeddbshim](https://github.com/axemclion/IndexedDBShim)
2. Mock firebase services instead of initializing the real Firebase services in your tests.

What is the `--browser` flag? I can't find any documentation about it. When I passed it to `react-scripts test`, I got `ReferenceError: regeneratorRuntime is not defined`. 
Also I'm not aware of such flag for Jest.

**Comment by robbie-c** [comment]
I had a similar problem when trying to use the JS SDK in an expo app (another non-browser environment), and made an Issue here https://github.com/firebase/firebase-js-sdk/issues/2244

Probably your best bet is to mock out any calls to Firebase as @Feiyang1 suggested

**Comment by dsgriffin** [comment]
> Both services require `indexedDB` to work. As far as I understand, Jest runs in Node where `indexedDB` is not available. 2 possible options:
> 
> 1. Include an indexeddb shim in your tests before initializing Firebase services, e.g. [indexeddbshim](https://github.com/axemclion/IndexedDBShim)
> 2. Mock firebase services instead of initializing the real Firebase services in your tests.
> 
> What is the `--browser` flag? I can't find any documentation about it. When I passed it to `react-scripts test`, I got `ReferenceError: regeneratorRuntime is not defined`.
> Also I'm not aware of such flag for Jest.

Can't find a reference now but found it on a CRA github issue as a solution for some vaguely related issue, can't find it now though. I'll need to try out the indexeddbshim I think as my current testing setup involves using a test instance with the firebase emulator suite etc. Thanks!
