### ISSUE TITLE
[firestore] Is it possible to index and query collection group with the field of its parent document?

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-js-sdk#2337]
Suppose there was a database of restaurant that has menu as child collection. In the parent(the restaurant) has a field category. And the menu has each dish detail description and so on

And then I want to query all of dishes in the menu collection from restaurant in the same category. For example, I want to show all dishes from every Italian restaurant in the database

Is it possible?

**Comment by mikelehen** [comment]
Thanks for the question.  This is possible, but you'd need to do it as multiple queries (first query for all Italian restaurants and then query the menu for each one).

For future reference, this github repo is for reporting bugs or specific feature requests for the Firebase JS SDK.  For more general questions / help, check out our other [support options](https://firebase.googleblog.com/2018/02/best-help-for-firebase-support.html).  Thanks!

**Comment by Thaina** [comment]
@mikelehen Sorry but what I meant with word "possible" is making a collection group query that also include parent document's field. Not a double querying

**Comment by mikelehen** [comment]
@Thaina Yeah, the only way to do that with a single query would be to duplicate the field into each of the documents in the collection group (i.e. add a Category=Italian entry to each menu document).  For feature requests not specific to the JS SDK (this would be a Firestore-wide feature), you can report them here: https://firebase.google.com/support/troubleshooter/report/features/  Thanks!
