### ISSUE TITLE
Problem calling firebase.auth().signInWithPhoneNumber from ie11, Headers is not defined

### ISSUE THREAD

**Issue by marcomasotti** [firebase/firebase-js-sdk#2345]
Calling firebase.auth() with ie11 with all correct data I always get Error

Headers is not defined

Any suggestion?
thanks

Marco

**Comment by Feiyang1** [comment]
Hi, thanks for the report. I'm not aware of any general auth implementation issue in IE11, so I suspect it's an environmental issue. Are you behind a proxy, or using a firewall?
Can you please also provide the code snippet to show the Auth methods you call?
