### ISSUE TITLE
@firebase/testing breaks on `httpsCallable`

### ISSUE THREAD

**Issue by hodeyp** [firebase/firebase-js-sdk#2353]
### [REQUIRED] Describe your environment

  * Operating System version: MAC OS X 10.15
  * Browser version: N/A (Node 12)
  * Firebase SDK version: @firebase/testing 0.15.0
  * Firebase Product: functions / emulators (auth, database, storage, etc)

I am trying to test onCall functions locally using the firebase emulators and the @firebase/testing package. When I try to call the function I get the following error message...

```
Error: Response is not valid JSON object.
      at new HttpsErrorImpl (node_modules/@firebase/functions/dist/index.node.cjs.js:60:28)
      at Service.<anonymous> (node_modules/@firebase/functions/dist/index.node.cjs.js:534:35)
      at step (node_modules/tslib/tslib.js:136:27)
      at Object.next (node_modules/tslib/tslib.js:117:57)
      at fulfilled (node_modules/tslib/tslib.js:107:62)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### Steps to reproduce:

Running the test script (see below) in mocha the error message is returned immediately. It does not look as if the function is actually being invoked so I suspect the issue is in the testing lib itself. I can call the endpoint manually using curl and it works as expected.

#### Relevant Code:

Function example
```javascript

export const demoCallable = functions.region('europe-west1').https.onCall((data: any, context: CallableContext): any => {

    console.log(data);

    return {
        test: true
    };

});
```

test example...

```javascript

const firebase = require('@firebase/testing');
const expect = require('chai').expect;
const adminApp = firebase.initializeAdminApp({projectId: 'XXXXX'});

const fn = adminApp.functions('europe-west1').httpsCallable('demoCallable');

console.log('Running callable...');
const response = await fn({test: true});

console.log('response...');
console.log(response);
console.log('...response');

expect(response).to.eql({test: true});


```

**Comment by rommelpe** [comment]
Thanks for your report, @hodeyp. Not sure yet if this is a limitation as what the [docs](https://firebase.google.com/docs/functions/unit-testing#testing_http_functions) says:

> Testing of HTTP Callable Functions is not yet supported.

I’ll try to reproduce this then will confirm to function folks.

**Comment by rommelpe** [comment]
Sorry for keeping you waiting, @hodeyp. You may review our updated [docs](https://firebase.google.com/docs/functions/unit-testing#testing_http_functions) to properly test your HTTP functions.

Should you have any other questions or issues, leave a comment and we're happy to help you out.
