### ISSUE TITLE
yarn test:setup throws HTTP 500 error

### ISSUE THREAD

**Issue by tomonoriyamada** [firebase/firebase-js-sdk#2356]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Mojave 10.14.6
  * Browser version: Google Chrome 78.0.3904.97
  * Firebase SDK version: commit cfaedf4
  * Node.js version: v10.15.0
  * yarn version: 1.19.1
  * Java version:
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

### [REQUIRED] Describe the problem
yarn test:setup throws HTTP 500 error

#### Steps to reproduce:

Follow the steps described [here](https://github.com/firebase/firebase-js-sdk/tree/master#testing-the-sdk). At the step of `yarn test:setup`, the following error occurs:

`FirebaseError: HTTP Error: 500, Internal error encountered.`

**Comment by rommelpe** [comment]
Thanks for reporting. I tried to reproduce the error on both cfaedf4 and `master` but can't seems to replicate it successfully, though I have a different Java version installed. 
![yarn](https://user-images.githubusercontent.com/56452310/68859857-31dc6a80-0723-11ea-8969-fd5e42477b70.png)

While I'm setting up the used Java version, have you tried considering your network connectivity? If you have any plugins/extensions/addons/firewall/proxies, you could try disabling them first as they might be blocking the network requests.

**Comment by hsubox76** [comment]
I also want to just double check if you were able to successfully log in to firebase on the command line first, either by using the firebase-cli's `firebase login` ahead of time, or by successfully entering the authorization code when prompted after `yarn test:setup`.
