### ISSUE TITLE
Firestore doesn't preserve new lines

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-js-sdk#2366]
Okay, I'm not sure if this repo is the right place for this kind of issue, so please move it if needed.

It is impossible to save a multiline text into Firestore using Firebase Console. I'm trying to store this text:

```
Text
New Line
```

But, as soon as it's inserted into the document, Firebase Console replaces new lines with spaces.
<img width="345" alt="Screenshot 2019-11-16 at 10 01 41" src="https://user-images.githubusercontent.com/2883524/68989450-2a6aad80-0858-11ea-970f-4b3a3b8e5d0f.png">

I tried to retrieve the document in my Flutter app and can confirm that the stored value is

```
Text New Line
```

**Comment by puf** [comment]
The Firebase console strips new lines when displaying string values, but the newline is stored correctly in the database. So when you read it back, you can handle the `\n` character the way you want it to be displayed in your code.

**Comment by agordeev** [comment]
@puf please see this GIF demonstrating that new lines are converted to and stored as spaces:

![1](https://user-images.githubusercontent.com/2883524/69026769-595e5c00-09dd-11ea-873f-27e42d463248.gif)

**Comment by puf** [comment]
The console indeed also seems to strip newlines in input you provide. This is not a problem in the Firebase JavaScript SDK, or database server however. For example, here's a small runnable test script that stores and reads a string with newlines without problems: https://jsbin.com/pelelus/edit?js,console.

You might want to [file a bug report](https://firebase.google.com/support/contact/bugs-features/) for the way the console silently strips newlines (both on input and on output).
