### ISSUE TITLE
Firestore onSnapshot does not respect my .where condition after a doc is updated

### ISSUE THREAD

**Issue by matheusbaumgart** [firebase/firebase-js-sdk#2387]
### Environment
  * Operating System version: iOS
  * Firebase SDK version: @react-native-firebase/firestore": "^6.0.0"
  * Firebase Product: Firestore

### The problem
It only returns todos if the date in the doc is the same as the date on my local state. I have the indexes created and all works well, until a document is updated with a date change.

If the date changes, the listener will return the right results a couple of times, without the doc that had it date change and no longer matches the conditions. BUT THEN, it returns the changed doc and all other docs with the same new date, which is driving me crazy as those docs don't match my where().

I've tried debugging it, with my limited knowledge and I managed to ignore that last response by using !querySnapshot.metadata.hasPendingWrites. That works but stops listening for new docs created that DO match the condition.

#### Steps to reproduce
Change the date of a document, the listener will suddenly return other docs with the same new date, which don't match my **where** condition.

#### Relevant Code
```javascript
const getTodos = () => {
    firebase
      .firestore()
      .collection("todos")
      .where("date", "==", startOfDay(currentDate))
      .where("user", "==", firebase.auth().currentUser.uid)
      .orderBy("created_at")
      .onSnapshot(function (querySnapshot) {
        if (querySnapshot) {
          let listTodos = [];
          let itemsProcessed = 0;

          querySnapshot.docs.forEach((doc, index, array) => {
            itemsProcessed++;

            let { title, complete, date, created_at, list } = doc.data();

            listTodos.push({
              key: doc.id,
              docRef: doc.ref, // doc, // DocumentSnapshot
              title,
              complete,
              date: date,
              created_at,
              list
            });

            if (itemsProcessed === array.length) {
              setTodos(listTodos)
            }
          })
        }
      });
  };
```

**Comment by wu-hui** [comment]
I'll try to re-produce this. I have some question though, which lib do you get `startOfDay` from?

Also, just so I understand, so there is a `docA` with `date==2019-11-28` which matches the query initially. Then you changed the date to `2019-11-27` for example, and you first see a snapshot without `docA` in the results. But then, you see a subsequent snapshot with documents all having `date==2019-11-27`, including `docA`. 

Is my description correct?

**Comment by schmidt-sebastian** [comment]
@matheusbaumgart What version for the Firestore Web SDK are you using? Can you also share debug logs (enable via `firebase.firestore.setLogLevel('debug')`)?

**Comment by matheusbaumgart** [comment]
Sorry for the delay in getting back.

> which lib do you get startOfDay from?
I get it from `date-fns`

> Is my description correct?
Yes, that's correct.

However... I believe the issue was on my side. I wasn't unsubscribing correctly, so my assumption is that it was keeping multiple listeners. It works as I expect now, here is what I use to run the function and to unsubscribe:

```
  // WHEN DATE CHANGES
  useEffect(() => {
    this.unsubscribe && this.unsubscribe()
    getTodos();
  }, [currentDate]);
```

Thanks for your help anyway!
