### ISSUE TITLE
Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).

### ISSUE THREAD

**Issue by raphaelarias** [firebase/firebase-js-sdk#2391]
* Operating System version:  macOS Catalina version 10.15 
  * Browser version: Version 78.0.3904.108 (Official Build) (64-bit)
  * Firebase SDK version: 6.6.1
  * Firebase Product: messaging

Description:
We followed the official guide to setup the Firebase messaging webworker, but we just can't get passed the error:

```
Uncaught FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).
    at Object.messaging (https://www.gstatic.com/firebasejs/6.6.1/firebase-messaging.js:1:31477)
    at I._getService (https://www.gstatic.com/firebasejs/6.6.1/firebase-app.js:1:7413)
    at I.a.<computed> [as messaging] (https://www.gstatic.com/firebasejs/6.6.1/firebase-app.js:1:9899)
    at Object.i [as messaging] (https://www.gstatic.com/firebasejs/6.6.1/firebase-app.js:1:9683)
    at onmessage (https://app.geteducation.link/firebase-messaging-sw.js:1:297)
```

Even when we copy and paste the code it throws the same error. We followed every advice on https://github.com/firebase/firebase-js-sdk/issues/1220 and no luck.

This is our code:

```javascript
// Firebase messaging Service Worker

importScripts('https://www.gstatic.com/firebasejs/6.6.1/firebase-app.js'); // eslint-disable-line
importScripts('https://www.gstatic.com/firebasejs/6.6.1/firebase-messaging.js'); // eslint-disable-line

onmessage = (e) => {
  if (e.data.settings) {
    const config = JSON.parse(e.data.settings);

    firebase.initializeApp(config.firebase); // eslint-disable-line
    const messaging = firebase.messaging(); // eslint-disable-line

    messaging.setBackgroundMessageHandler((payload) => {
      const title = 'Test';
      const options = {
        body: payload.data.status,
      };

      return self.registration.showNotification(title, options); // eslint-disable-line
    });
  }
};
```

Note that we send the firebase settings from our app, that's why we have a listener. Even when we don't have it, it throws the same error.

![image](https://user-images.githubusercontent.com/5008166/69840179-b34d0480-12ae-11ea-890a-18efbcffb52b.png)

No other stackoverflow, guide, issue or looking into te code helped. Our browser has the capability but still get the same error over and over.

**Comment by raphaelarias** [comment]
When we manually run the piece of code that throws the error:
```javascript
console.log(self && 'ServiceWorkerGlobalScope' in self ? 'PushManager' in self && 'Notification' in self && ServiceWorkerRegistration.prototype.hasOwnProperty('showNotification') && PushSubscription.prototype.hasOwnProperty('getKey') : navigator.cookieEnabled && 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window && 'fetch' in window && ServiceWorkerRegistration.prototype.hasOwnProperty('showNotification') && PushSubscription.prototype.hasOwnProperty('getKey'));
```

We first get `true` then it stops working.
![image](https://user-images.githubusercontent.com/5008166/69840523-01163c80-12b0-11ea-9891-981611abbf93.png)

**Comment by raphaelarias** [comment]
Changing to 7.5.0 doesn't help:

```javascript
importScripts('https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js'); // eslint-disable-line
importScripts('https://www.gstatic.com/firebasejs/7.5.0/firebase-messaging.js'); // eslint-disable-line
```

**Comment by raphaelarias** [comment]
When I separate the `if` in the console.log above, in the first execution, it passes the test, in the second execution, it fails:
![image](https://user-images.githubusercontent.com/5008166/69841919-4a1cbf80-12b5-11ea-9867-c53d81a36133.png)

```javascript
console.log(self && 'ServiceWorkerGlobalScope' in self ? 1 : 2);

console.log('PushManager' in self,
  'Notification' in self,
  ServiceWorkerRegistration.prototype.hasOwnProperty('showNotification'),
  PushSubscription.prototype.hasOwnProperty('getKey'));
```

**Comment by raphaelarias** [comment]
If I put a `setInterval`, we get a `true` and `false` very frequently:

```javascript
setInterval(() => {
  console.log(self && 'ServiceWorkerGlobalScope' in self);
}, 500);
```

![image](https://user-images.githubusercontent.com/5008166/69842139-33c33380-12b6-11ea-9ec7-9d208bcca456.png)

**Comment by rommelpe** [comment]
Thanks for reaching out! I tried to reproduce using the [quickstart guide](https://github.com/firebase/quickstart-js/tree/master/messaging) on different Chrome & Firebase versions but can't seem to encounter it only when running to lower version of Firefox v68.2.


Could you provide a simple repro that we run locally & detailed steps to recreate this?

**Comment by amstrad** [comment]
Hi, i´m just facing this issue.. trying to add push notifications to my webapp. I´m following the guide [here](https://firebase.google.com/docs/cloud-messaging/js/client?hl=es-419#configure_web_credentials_with_fcm)

My firebase config looks as follows.

`import firebase from 'firebase/app'

// Add additional services that you want to use
require("firebase/auth");
require("firebase/firestore");
require("firebase/storage");
require("firebase/analytics");
require("firebase/messaging");

//My firebase keys:
var config = {
    apiKey: "****",
    authDomain: "****",
    databaseURL: "****",
    projectId: "****",
    storageBucket: "****",
    messagingSenderId: "****",
    appId: "****",
    measurementId: "****",
};

firebase.initializeApp(config);
firebase.analytics();
// Initialize another app with a different config

firebase.firestore().settings({
    //timestampsInSnapshots: true
})

const auth = firebase.auth()
const db = firebase.firestore()
const storage = firebase.storage()

const messaging = firebase.messaging()

//Web Push certificates taken from firebase panel Settings-> Clound Messaging -> Web configuration

messaging.usePublicVapidKey("****");

export {
    firebase,
    config,
    auth,
    db,
    storage,
    messaging
}`



- Works Ok if i remove the firebase/messaging related lines
- upgraded SDK to ^7.5.2.. No luck
- Chrome V. 78.0.3904.108
![Captura de pantalla 2019-12-10 a las 12 43 26](https://user-images.githubusercontent.com/772421/70526894-e1520480-1b4a-11ea-9d01-5e4c36b62336.png)
