### ISSUE TITLE
Firebase not transpiling since version 6.2.2 with Ionic 3 / Angular 5

### ISSUE THREAD

**Issue by ludovicfourrage** [firebase/firebase-js-sdk#2392]
* Operating System version:  Windows 10
  * Browser version:  Chrome 78
  * Firebase SDK version: 6.2.2+
  * Firebase Product: The issue has appeared since the introduction of analytics in 6.2.3

#### Steps to reproduce:
1) Install the ionic CLI 
`npm install -g ionic`
2) Create new project with Ionic 3 using the command 
`ionic start test blank --type=ionic-angular`
3) install the latest firebase and angularfire (5.2.1 or above)
4) add firebase to Angular's app.module.ts
5) run ionic serve

#### Error message:

![screencapture-localhost-8101-2019-11-29-13_28_26](https://user-images.githubusercontent.com/28280112/69890726-2b65fb00-12ac-11ea-9b42-788f80b4bc4f.png)

**Comment by sengoontoh** [comment]
Try npm install typescript@2.8.3

**Comment by ludovicfourrage** [comment]
Thanks, typescript needs to be upgraded indeed to 2.8.3, and tslib as well in order to make it all work. Installing typescript v 2.8.3 and tslib v1.10.0 works.

**Comment by zarko-tg** [comment]
Duplicated of (closed) https://github.com/firebase/firebase-js-sdk/issues/2335
