### ISSUE TITLE
FR: Firestore Cross-Origin Multi-Tab Persistence

### ISSUE THREAD

**Issue by scottfr** [firebase/firebase-js-sdk#2419]
### Describe your environment

  * Operating System version: Mac OS
  * Browser version: Chrome 78
  * Firebase SDK version: 7.3
  * Firebase Product: Firestore

### Describe the problem

I would like to be able to use multi-tab persistence across multiple origins.

The motivation for this is I have a website and a companion Chrome Extension. The website has the origin <https://mysite.com> and the Chrome extension the origin <chrome-extension://IDENTIFIER>. They both connect to the same Firestore database.

Allowing them to share the same persistence layer would provide faster syncing and, most importantly, enable off-line syncing between them.

**Comment by thebrianchen** [comment]
@scottfr Thanks for filing a feature request! Unfortunately, our persistence functionality is implemented via IndexedDB, and it adheres to a same-origin policy ([link](https://stackoverflow.com/a/23874433)), which means that we can't add cross-origin persistence at this time.
