### ISSUE TITLE
Can we use Phone number authentication without using Recaptcha

### ISSUE THREAD

**Issue by karthickms** [firebase/firebase-js-sdk#2422]
Hey all,

I am using web API's only, not any frontend (angular, react, ...). So can we use following function without Recaptcha.

firebase.auth().signInWithPhoneNumber(phoneNumber, appVerifier)

Thanks in advance.

**Comment by rommelpe** [comment]
Hi @karthickms, you may try to implement the [invisible reCAPTCHA](https://firebase.google.com/docs/auth/web/phone-auth#use-invisible-recaptcha). 

I am going to close this issue. If you have other questions/clarifications just leave a comment here and we are happy to re-open this.

**Comment by karthickms** [comment]
Yes. when we using this following code, Is "sign-in-button" client side work ?

window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
  'size': 'invisible',
  'callback': function(response) {
    // reCAPTCHA solved, allow signInWithPhoneNumber.
    onSignInSubmit();
  }
});

**Comment by rommelpe** [comment]
It should be working as expected (see sample implementation in the [quickstart guide](https://github.com/firebase/quickstart-js/blob/fcf68cb3f0bfc033d536447b65967f4b0567720e/auth/phone-invisible.html#L144) | [live](https://onlinereservation-2lx.firebaseapp.com/phone-invisible.html)). In case you still didn’t receive the SMS, I'd suggest that you try using a different phone number or device.

**Comment by karthickms** [comment]
Yes. I can receive message. But my question is, without using HTML code, how to authentication with phone number ?

Because we are working back end part (Api ). On that, phonenumber and country code only in my hand. Using that, how to authenticate ?

**Comment by rommelpe** [comment]
There's no way to directly authenticate phone number in the backend side. It should be always rendered in client side and pass back the recaptcha token to the backend and complete the sign in there but the recaptcha is required.

**Comment by karthickms** [comment]
Okay. Thanks for your information.
