### ISSUE TITLE
firestore emulator timeout when providing auth object 

### ISSUE THREAD

**Issue by florianlenz** [firebase/firebase-js-sdk#2424]
### Env

  * Operating System version: OSX Catalina
  * Browser version: (not relevant)
  * Firebase SDK version: (not installed)
  * Firebase Product: firestore

### Describe the problem
When I am running my tests and I am using `@firebase/testing` to create my tests databases 

In my tests I am using `@firebase/testing` to create my databases. When I am not providing an `auth` object everything works as expected. However, when I do provide one, transactions nor queries or anything else is being executed. It just hangs and does nothing. 

#### Steps to reproduce:
I added a test project. Please find it attached. 
- You can run `npm install` to install the dependencies. 
- Run `npm run fb:emulator:setup` to setup the emulator
- Run `npm run fb:emulator:start` to start the emulator
- Run `node run.js`, `before transaction` should be printed in the console
- Now remove the `auth` object on line `12` and run `node run.js`. The following should be printed:
   - `before transaction`
   - `in transaction`
   - `done`

#### Relevant Code:
The `run.js` file in the test project

[fbtesting.zip](https://github.com/firebase/firebase-js-sdk/files/3941670/fbtesting.zip)

**Comment by thebrianchen** [comment]
@florianlenz Thanks for reporting the issue! I see in your `package-lock.json` file that you are using `@firebase/testing` at `v0.16.2`. There is currently an open [bug](https://github.com/firebase/firebase-js-sdk/issues/2417) at this version with the same issue you are running into. We are currently working on releasing a fix, but in the meantime, using `v0.16.0` should fix the issue.

**Comment by Elyx0** [comment]
Rolled back and it worked for me as well to `16.0`

**Comment by yuchenshi** [comment]
This is now fixed in 0.16.3.
