### ISSUE TITLE
How to get results based on user id ?

### ISSUE THREAD

**Issue by karthickms** [firebase/firebase-js-sdk#2426]
When we using following snap, how to get results based on user id ?

shop:
{
  "24AAUGPB213H6K0XKVRC" : {
    "country_code" : "91",
    "email" : "gjksks@yahoo.com",
    "name" : "Hato sjs",
    "phone_number" : "7985463120",
    "pin_code" : 5571,
    "role" : 1,
    "user_id" : "5cee22582297901fe036b5a1"
  },
  "PZTOXPYH1E1MRD3L7LZ7" : {
    "country_code" : "45",
    "email" : "haha@gmail.com",
    "name" : "Firebase store",
    "phone_number" : "21364578",
    "pin_code" : 2294,
    "role" : 1,
    "user_id" : "5cee22582297901fe036b5a1"
  }
}

**Comment by rommelpe** [comment]
Thanks for filling this issue, @karthickms. Are you using RTDB? Have you tried checking out [equalTo](https://firebase.google.com/docs/reference/js/firebase.database.Query#equal-to)? It returns items equal to the specified key or value, depending on the order-by method chosen.
```
ref.child("shop")
   .orderByChild("user_id")
   .equalTo("5cee22582297901fe036b5a1")
   .once('value'), function(snapshot) {
      console.log(snapshot.val());
    });
```

**Comment by karthickms** [comment]
Yes. I am using RTDB. I also using equalTo it returns good. But how to include multiple condition using this?

**Comment by rommelpe** [comment]
To achieve your desired multiple queries, you will either have to;

> 1. filter most on the server, do the rest on the client
> 2. add a property that combines the values that you want to filter on
> 3. create a custom index programmatically

You can refer to this post which provides a detailed info;
https://stackoverflow.com/questions/26700924/query-based-on-multiple-where-clauses-in-firebase?answertab=votes#tab-top
