### ISSUE TITLE
Apple branded white screen before redirect

### ISSUE THREAD

**Issue by Christilut** [firebase/firebase-js-sdk#2427]
### [REQUIRED] Describe your environment

  * Operating System version:  Windows 10
  * Browser version:  Chrome 78
  * Firebase SDK version:  7.5.2
  * Firebase Product: auth

#### Steps to reproduce:

1. Load FirebaseUI with Apple configured
2. Click Apple button
3. Login to Apple
4. White screen with Apple header

I'm using FirebaseUI to login with social providers. Most work fine except Apple.
It redirects me to the Apple website and asks me to login. Then after that is done successfully, it shows me an Apple branded white screen that only says in the top that I'm signed in.

This is probably where it should redirect to back to my SPA but it doesn't.

I guess this is a Firebase issue and not FirebaseUI but correct me if I'm wrong.

#### Relevant Code:

```ts
const uiConfig: firebaseui.auth.Config = {
  signInSuccessUrl: `${location.protocol}//${location.host}/dashboard`,
  signInFlow: 'popup', // Same problem with 'redirect'
  signInOptions: [
    'apple.com',
  ]
}
```

**Comment by bojeil-google** [comment]
Hey @Christilut can you file this in the [`firebaseui-web` repo](https://github.com/firebase/firebaseui-web/)? Thanks.

**Comment by wti806** [comment]
I cannot reproduce the issue with our demo app: https://fir-ui-demo-84a6c.firebaseapp.com/
Did you see any error message in the console? If you can provide a minimal reproducible example, as well as the screenshot of the white screen you mentioned, we can help you debug. Thanks

**Comment by Christilut** [comment]
Actually the demo app has the same problem for me.

I get this screen
![image](https://user-images.githubusercontent.com/3471363/70625816-83ddb680-1c23-11ea-882c-541985ee6e64.png)

There's nothing in the console other than SameSite warnings.

This is the URL that's on that screen:
```
https://appleid.apple.com/auth/authorize?response_type=code&client_id=com.firebase.auth.services2&redirect_uri=https%3A%2F%2Ffir-ui-demo-84a6c.firebaseapp.com%2F__%2Fauth%2Fhandler&state=<<omitted>>>>&scope=email%20name&response_mode=form_post&locale=en&context_uri=https%3A%2F%2Ffir-ui-demo-84a6c.firebaseapp.com
```

**Comment by Christilut** [comment]
Windows 10, Chrome 78

**Comment by Christilut** [comment]
Just tried it on Firefox. Had to log in with Apple 2factor and it asked if I wanted to share my info with the firebase app. I can't get that far on Chrome. 

I already logged into Apple with Chrome before, so I guess the state is different here causing this.

Let me know what you need from me to figure this out. I'll not clear the browser yet, I can still reproduce this every time now.

**Comment by bojeil-google** [comment]
Hey @Christilut we can't reproduce this. It seems to be local to your device. I would suggest you test it out using a different device / browser / network to isolate the cause. One thing to also consider are chrome extensions. Sometimes the issue could be caused by that.

**Comment by Christilut** [comment]
I turned off my adblock and such, so that can't be it. It's still showing a white screen now. But I assume it's a strange bug that might have happened during my development, not sure.

I'll close this then unless you want to try pursue this further.

**Comment by Christilut** [comment]
Upon further investigation it seems that this is because of uBlock Origin. Even though I whitelisted the site, Apple was still silently blocked without any errors in the console or network tab. Only completely disabling the extension worked. Reported to the uBlock team.
