### ISSUE TITLE
TransactionInactiveError in IE11 on Windows 10 in Browserstack and Sauce Labs

### ISSUE THREAD

**Issue by kenkus-futurice** [firebase/firebase-js-sdk#2430]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: IE11
  * Firebase SDK version: 7.5.2
  * Firebase Product: remoteconfig

### Describe the problem

Occasionally running `firebase.remoteConfig().fetch()` or `firebase.remoteConfig().fetchAndActivate()` throws `TransactionInactiveError` in IE11 on Windows 10 in Browserstack and Sauce Labs. However, not able reproduce on a local machine. As a result Remote Config values cannot be used.

#### Steps to reproduce:

Run `firebase.remoteConfig().fetchAndActivate()` in IE11 on Windows 10 in Browserstack and Sauce Labs.

#### Relevant Code:

```javascript
import * as firebase from 'firebase/app'
import 'firebase/remote-config'

firebase.remoteConfig().fetchAndActivate()
.catch((err) => {
  console.error(err) // TransactionInactiveError
})
```

**Comment by rommelpe** [comment]
Were you ever able to reproduce this without depending on Browserstack and Sauce Labs? Can share the complete error logs? Thanks @kenkus-futurice!

**Comment by jacobg** [comment]
My application is also reporting the TransactionInactiveError to our Bugsnag account. We've seen this error on both IE 11 and iOS 10.2 Safari. On iOS, it also reports error detail:
`Failed to store record in an IDBObjectStore: The transaction is inactive or finished.`

**Comment by rommelpe** [comment]
Hi @jacobg, Can you help me reproduce the error? It would be great if we can isolate this without relaying on any third party monitoring app.

You can provide a [minimal repro](stackoverflow.com/help/minimal-reproducible-example) of your app that I can run locally.  Also, if you find any patterns or info that we can use to troubleshoot, we're happy to help.

**Comment by jacobg** [comment]
Hi @rommelpe. I'm not sure for us right now it's high enough priority of an issue for us to try to repro. But we are seeing the specific error
`Failed to store record in an IDBObjectStore: The transaction is inactive or finished.`
only in iOS 10 Safari for 6 unique users. I remember hearing that IndexedDb on iOS 10 does not work so well. 

On IE 11 the `TransactionInactiveError ` error occurred for two unique users. It seemed to occur right after a change to the url history path. It was an unhandled promise rejection, and Bugsnag is showing:

`unknown file unknown method`
```
rejection reason
{
  "[object DOMException]": {
    "name": "TransactionInactiveError",
    "message": "TransactionInactiveError",
    "code": 0
  }
}
```
