### ISSUE TITLE
Rollup 1.27.10 fails to build firebase/auth with rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by Laincito** [firebase/firebase-js-sdk#2431]
* Operating System version: Windows 10
  * Browser version: Any
  * Firebase SDK version: 7.5.2
  * Firebase Product: auth

### Rollup 1.27.10 fails to build firebase/auth

When trying to build with the latest rollup version we get a memory error:

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

#### Relevant Code:

*packaje.json*:
```json
{
  "name": "firebaseauth",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c"
  },
  "dependencies": {
    "firebase": "^7.5.2"
  },
  "devDependencies": {
    "rollup": "1.27.10",
    "rollup-plugin-node-resolve": "^5.2.0"
  }
}
```

*index.js*:
```javascript
import '@firebase/auth';
```

*rollup.config.js*:
```javascript
import resolve from 'rollup-plugin-node-resolve';

export default {
    input : "index.js",
    output : {
        dir : "public",
        format: "es",
        entryFileNames: '[name]'
    },
    plugins: [
        resolve()
    ]
};
```

**$ npm install**
**$ npm run build**

**Comment by rommelpe** [comment]
Thanks for reporting the issue, @Laincito. It seems that _rollup_ folks have addressed this in their latest release ([v1.27.12](https://github.com/firebase/firebase-js-sdk/issues/2431)). I was able to successfully test it on my end.

![image](https://user-images.githubusercontent.com/56452310/70811828-60706280-1e01-11ea-93b5-24425d74f77f.png)

If you're still interested in working on this case and want to continue the discussion, just leave a comment here and we are happy to re-open this.Thanks.
