### ISSUE TITLE
Cannot find module '@firebase/auth-interop-types'

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-js-sdk#2440]
Upgrading to version 7.6.0 from 7.5.0 with a Web project written in Typescript, a transpilation  (before any bundling) reports the following errors:

> node_modules/@firebase/database/dist/src/core/AuthTokenProvider.d.ts:18:42 - error TS2307: Cannot find module '@firebase/auth-interop-types'.
> 
> 18 import { FirebaseAuthInternalName } from '@firebase/auth-interop-types';
>                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/@firebase/database/dist/src/core/Repo.d.ts:24:42 - error TS2307: Cannot find module '@firebase/auth-interop-types'.
> 
> 24 import { FirebaseAuthInternalName } from '@firebase/auth-interop-types';

The error problem has been introduced in version 7.5.1 and is present in version 7.5.2 and 7.6.0. Reverting to version 7.5.0 prevents the issue.

**Comment by rommelpe** [comment]
Hi @lpellegr, I wasn't able to get the same error result tested on my existing TS project. Can you help me reproduce the error? If you could provide a minimal repro that I can run locally and detailed steps to replicate it, that would be a great help for us to speed up the investigation. Thanks

**Comment by lpellegr** [comment]
@rommelpe Thanks for your comment. Here is a minimal example for reproduction:

https://github.com/lpellegr/firebase-issue-2440

By running the next commands you will get the exact same errors as in the original report:

```
$ npm install
# tsc
```

**Comment by rommelpe** [comment]
Were you able to try importing Firebase modules as follow? (See  [Add Firebase SDKs and initialize Firebase](https://firebase.google.com/docs/web/setup#add-sdks-initialize) under  `Using module bundlers` tab) 

```
// Firebase App (the core Firebase SDK) is always required and must be listed first
import * as firebase from "firebase/app";

// If you enabled Analytics in your project, add the Firebase SDK for Analytics
import "firebase/analytics";

// Add the Firebase products that you want to use
import "firebase/auth";
import "firebase/firestore";

```

**Comment by lpellegr** [comment]
The problem remains the same. Did you try the example I provided?

**Comment by rommelpe** [comment]
Yes, it worked when I try using the recommended imports even switching to v7.5.1;


![image](https://user-images.githubusercontent.com/56452310/70923784-68c7d800-2063-11ea-84f6-b104fdb6f35c.png)

**Comment by lpellegr** [comment]
I just did a clean try again and I still get the issue. Are you importing `import '@firebase/database';`? The problem seems to come from this module:

```
import * as firebase from "firebase/app";

import '@firebase/database';
```

**Comment by rommelpe** [comment]
Instead of `import '@firebase/database';` try `import 'firebase/database';`

**Comment by lpellegr** [comment]
Thanks for your help. That is solving the issue on the minimal example I provided. Unfortunately, using these imports in my real project leads to another problem while serving with es-dev-server:

> Uncaught TypeError: firebase.initializeApp is not a function

I will close this issue and investigate further with recommended imports and open another issue if required.

**Comment by lpellegr** [comment]
Finally, here are working imports for Typescript with ESM support in the case this could help others:

```
import firebase from 'firebase/app';

import 'firebase/auth';
import 'firebase/database';
import 'firebase/firestore';
import 'firebase/storage';

firebase.initializeApp(config.firebase);
```
