### ISSUE TITLE
Auth ID token expire time offset

### ISSUE THREAD

**Issue by Christilut** [firebase/firebase-js-sdk#2446]
### [REQUIRED] Describe your environment

  * Operating System version:  Win 10
  * Browser version:  Chrome 79
  * Firebase SDK version:  7.5.2
  * Firebase Product:  auth

### [REQUIRED] Describe the problem

It seems that Firebase Auth has slight time offset when refreshing the ID token causing the token to be invalid for a short time.

I just tested this by logging in and not doing anything for an hour except read and verify the token with the Admin SDK. At the 1 hour mark, it was invalid for about 20 seconds. I kept trying and after those 20 seconds the client automatically refreshed the token and the Admin SDK confirmed that the new token was valid.

![image](https://user-images.githubusercontent.com/3471363/70790464-69c3e580-1d95-11ea-90dc-f8a1734eddb0.png)

AWS Amplify has/had the same problem with the clock being slightly different I believe.

I'm doing a workaround that force refreshes the token when it's nearly expired.

#### Steps to reproduce:

1. Log in with any Firebase Auth provider
2. Do a server call every second that verifies token and log result
3. Do this for an hour. Don't refresh the client.

#### Relevant Code:

```ts
    const currentUser = firebase.auth().currentUser
    
    if (currentUser) {
      const token = await currentUser.getIdToken()
  }
```

**Comment by bojeil-google** [comment]
We already have a [30 second buffer](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/token.js#L158) for refreshing the ID token ahead of time. I suspect the issue is with your server or device clock. Please check those 2 first.

**Comment by Christilut** [comment]
Well, you're right! For some reason my Windows 10 time sync stopped working for a long time. Only happened in development luckily
