### ISSUE TITLE
Firebase Messaging is ignoring setBackgroundMessageHandler()

### ISSUE THREAD

**Issue by RafaelLiendo** [firebase/firebase-js-sdk#2449]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 x64
  * Browser version: Chrome 78.0.3904.108
  * Firebase SDK version: 7.6.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
Background web push notifications are not being handled by the callback function set in setBackgroundMessageHandler(callback).

Although a notification is shown, it's not what I defined in the callback.
#### Steps to reproduce:

I forked the firebase quickstart-js [here](https://github.com/RafaelLiendo/quickstart-js)
and looking at it's code
```javascript
messaging.setBackgroundMessageHandler(function(payload) {
  console.log('[firebase-messaging-sw.js] Received background message ', payload);
  // Customize notification here
  const notificationTitle = 'Background Message Title';
  const notificationOptions = {
    body: 'Background Message body.',
    icon: '/firebase-logo.png'
  };

  return self.registration.showNotification(notificationTitle,
    notificationOptions);
});
```
whatever the message is, it should show
Ttile: Background Message Title
Body: Background Message body
Icon: (firebase icon)

instead, it shows whatever is sent in the payload bypassing the setBackgroundMessageHandler callback

![image](https://user-images.githubusercontent.com/12666898/70857683-fbd10880-1ed1-11ea-8caa-5fa59517b1ae.png)

What shows is:
![image](https://user-images.githubusercontent.com/12666898/70857701-6f731580-1ed2-11ea-84cd-1510cdf2dd4d.png)

What was expected:
![image](https://user-images.githubusercontent.com/12666898/70857777-a3026f80-1ed3-11ea-8dae-eab1341a8248.png)

#### Relevant Code:

https://github.com/RafaelLiendo/quickstart-js

**Comment by RafaelLiendo** [comment]
Looks like the problem is right here
https://github.com/firebase/firebase-js-sdk/blob/ae319059e4a083a613a2999c1e61d44c9053a0d7/packages/messaging/src/controllers/sw-controller.ts#L103-L121
It only calls bgMessageHandler if msgPayload.notification is not present
which dosen't make sense to me, shouldn't it call bgMessageHandler regardless of what's in msgPayload?

**Comment by RafaelLiendo** [comment]
Ok, after searching the docs I found this
https://firebase.google.com/docs/cloud-messaging/concept-options.html#notifications_and_data_messages
which says that messages could be one of two types: 
- Notification messages (msgPayload.notification is present)
- Data messages (msgPayload.notification is not present)

so, in order to trigger the background message handler I have to send a Data message.

if that's the case, the code should reflect that by naming the method setBackgroundDataMessageHandler

but IMO, the developer should be able to decide if it wants to handle Notification messages also.

**Comment by rommelpe** [comment]
Thank you for taking time filling this issue, @RafaelLiendo. You can check out this [docs](https://firebase.google.com/docs/cloud-messaging/js/receive) too.

![image](https://user-images.githubusercontent.com/56452310/71069416-a50a4e00-21b3-11ea-99b7-493c2def8f98.png)

While this is currently an expected limitation, we'll treat this as a feature request and keep this open.

**Comment by RafaelLiendo** [comment]
Thanks @rommelpe. But while this FR is being evaluated, a simple comment on the quickstart code pointing to the docs would help a lot.

**Comment by zwu52** [comment]
> It only calls bgMessageHandler if msgPayload.notification is not present
> which dosen't make sense to me, shouldn't it call bgMessageHandler regardless of what's in msgPayload?

Hi @RafaelLiendo, as you have noticed. The current SDK is failing to handle FCM message with both "data" and "notification payload. We'll be having a major release later this year to resolve the long-lasting issue. Meanwhile, having a better quickStart is very reasonable.
