### ISSUE TITLE
await sleep(3000): why?

### ISSUE THREAD

**Issue by nuragic** [firebase/firebase-js-sdk#2453]
Sorry to bother but I can't `sleep` after seeing this line... 😄 

https://github.com/firebase/firebase-js-sdk/blob/7bb33dcb15354471f63d71c48a0c58996fd25f36/packages/messaging/src/controllers/sw-controller.ts#L201

This is a question for @Feiyang1.

Thanks!

**Comment by mmermerkaya** [comment]
There's a comment right above it :roll_eyes:

**Comment by nuragic** [comment]
Ha, not the answer I was looking for, sorry. My fault I think, the tone was a bit sarcastic.

Now seriously, my question is about why there's an hardcoded arbitrary timeout. That's non deterministic, smells like an hack. Why is it needed to send a message after 3 (and why not 1, or 5) seconds to a client that just opened a URL? That URL will load a PWA that's supposed to handle whatever logic based on _that URL._

Moreover, suppose that the window will open, and the message is sent after 3 seconds: the message will be delivered via the `onMessage` callback on the window?

**Comment by nuragic** [comment]
@mmermerkaya 

As stated in [docs](https://firebase.google.com/docs/cloud-messaging/js/receive):

```js
// Handle incoming messages. Called when:
// - a message is received while the app has focus
// - the user clicks on an app notification created by a service worker
//   `messaging.setBackgroundMessageHandler` handler.
messaging.onMessage((payload) => {
  console.log('Message received. ', payload);
  // ...
});
```

Now suppose that, when the app has focus, I also want to display a `Notification`... e.g.

```js
messaging.onMessage((payload) => {
  const notification = new Notification('PUSH!', {
    // use payload to set the notification options…
  });
  notification.onclick = (e) => {
    notification.close();
    // whatever
  };
});
```

When the app is in background, the `Notification` will show from the SW, users click on it, then firebase will `postMessage` the client after 3 seconds, and then the `onMessage` callback is called... showing the notification again!

So apart from being an hack IMHO, this logic in place of "sending a message to the client after 3 seconds once the user click the notification" prevents implementing this use case. Please, correct me if I'm wrong.

**Comment by nuragic** [comment]
Regarding `setBackgroundMessageHandler`:
```
   * If you do not set this callback then all push messages will let and the
   * developer can handle them in a their own 'push' event callback
```

That's what I'm doing. I'm managing the `push` event on my own... but that's not possible for the `notificationclick` event. The solution for this case would be enabling to opt out from the default firebase callback for the notification click.

**Comment by nuragic** [comment]
Ok, I was wrong about that isn't possible to opt out from the `notificationclick` event default handler.

The (only) way to opt out is to NOT send a `notification` field in the push message payload. 🤷‍♂ 

Now I'm avoiding the `await sleep(3000)` and related code. Thanks anyway!
