### ISSUE TITLE
Firebase not working in authicating

### ISSUE THREAD

**Issue by tchimih** [firebase/firebase-js-sdk#2454]
Hello folks,

I want to use firebase to authenticate my users to my backend. To do so, I am implmenting a vuejs (+ vuetify) webapp + firebase. The only problem is that when I try to send to post request to my firebase, I doesn't work and it displays the following error:

![image](https://user-images.githubusercontent.com/23434135/71113070-1c98a700-21cd-11ea-87bb-6987096c4217.png)

Here is my code snippet for the authentication:
`````
methods: {
            emailAndPasswordlogin: function(e){
                firebase.auth().SignInWithEmailAndPassword(this.email, this.password).then(user => {
                        alert(`Logged in as ${user.email}`)
                    },
                    err => {
                        alert(err.message)
                    })
                e.preventDefault()
            }
        }
`````

**Comment by rommelpe** [comment]
Thanks for reporting the issue, @tchimih. Based from the error logs, it seems to be an issue on how the [SDKs were added and being initialized](https://firebase.google.com/docs/web/setup#add-sdks-initialize). Could you share a minimal repro and detailed steps to replicate this?

**Comment by tchimih** [comment]
Thanks for the reply @rommelpe, I followed the tutorial as described on the link you gave:

- I initiate my vue project (then added vuetify)
```vue create myapp```
- I created a firestore js file where I included all my config as follow:

```
import firebase from 'firebase'
import 'firebase/firestore'
import 'firebase/auth'

var firebaseConfig = {
  apiKey: "api-key",
  authDomain: "project-id.firebaseapp.com",
  databaseURL: "https://project-id.firebaseio.com",
  projectId: "project-id",
  storageBucket: "project-id.appspot.com",
  messagingSenderId: "sender-id",
  appId: "app-id",
  measurementId: "G-measurement-id",
};
const firebaseApp = firebase.initializeApp(firebaseConfig);
const firestore = firebaseApp.firestore();
export default firestore
```
- I tried to use the  signInWithEmailAndPassword in my methods in another vue component as follow:
```
import firebase from '../firebase'
export default{
...,
methods: {
            emailAndPasswordlogin: function(e){
                console.log(firebase)
                firebase
                .auth()
                .signInWithEmailAndPassword(this.email, this.password)
                .then(data => {
                    console.log(data);
                })
                .catch(err => {
                    console.log(err)
                });
                e.preventDefault()
            }
        }
...
```
But I still have the error on my app and the method isn't working. I tried to reinstall firebase as described in other issues but it didn't solve my issue :(

**Comment by rommelpe** [comment]
Thanks for working on the repro. I wasn't still able to get the same behavior, though it seems to be working as expected when implementing `signInWithEmailAndPassword` using this [sample vue project](https://github.com/rommelpe/showcase). Have you considered upgrading your SDK to the latest one ([v7.6.0](https://firebase.google.com/support/release-notes/js#version_760_-_december_12_2019))?

It'll be great to have a sample minimal runnable repro for us to debug further.

**Comment by tchimih** [comment]
Hello @rommelpe,

Thanks for your help, I found out my issue. I upgraded to v7.6.0 as recommanded and it worked fine :)
