### ISSUE TITLE
Client SDK incurs additional reads on doc(id).get()

### ISSUE THREAD

**Issue by dlockwo** [firebase/firebase-js-sdk#2458]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Mojave
  * Browser version: NA (Node v.10)
  * Firebase SDK version: firebase@7.6.1, firebase-admin@8.8.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When conducting a load test we discovered that the client SDK incurs significant additional reads compared to the admin SDK. In each test a virtual user gets the document, then updates the document. When using the client SDK with 10 virtual users getting and updating the same document once per second 10 times, StackDriver reports a peak query rate of ~35 per second and the Usage tab reports ~3.4K reads (significantly more than expected) and a peak write rate of ~1 per second (expected). When using the admin SDK with the exact same test, StackDriver reports a peak lookup rate (not query) of ~.9 per second (expected) and peak write rate of ~1 per second (expected).

Digging into the client SDK, it appears that doc().get() uses snapshot listeners rather than an actual get in the client SDK. We theorize that we are being charged for reads on those listeners every time we invoke a get().

#### Steps to reproduce:
1. Unzip the attached zip file.
2. Add your client and admin credentials to the client and server .ts files.
2. Create a stackdriver dashboard tracking firestore reads and writes.
2. Install all relevant packages and compile with typescript (tsc).
3. Change directory to lib.
4. Execute node testrunner_client.
5. Execute node testrunner_server.
6. View results in stackdriver.

#### Relevant Code:

```javascript
async function updateOptionResponders(responderuid, fieldid) {
  const db = firebase.firestore()
  const fieldref = db.collection('fields2').doc(fieldid)
  const fielddoc = await fieldref.get() // <== EXTRA READS INCURRED
  if (fielddoc.exists) {
    const field = fielddoc.data() as ITestField
    if (field.options['0'].responders !== undefined && field.options['0'].responders.includes(responderuid)) {
      //array remove
      await fieldref.update({
        "options.0.responders": firebase.firestore.FieldValue.arrayRemove(responderuid),
        "updated": firebase.firestore.FieldValue.serverTimestamp()
      })
    } else {
      //array union
      await fieldref.update({
        "options.0.responders": firebase.firestore.FieldValue.arrayUnion(responderuid),
        "updated": firebase.firestore.FieldValue.serverTimestamp()
      })
   }
 }
}
```
[repro.zip](https://github.com/firebase/firebase-js-sdk/files/3984632/repro.zip)

**Comment by var-const** [comment]
Apologies for the slow reply. I will try to reproduce the issue (thanks for the repro case!) and will post an update here.

**Comment by dlockwo** [comment]
No problem. Let me know if you need anything more. Thanks.

**Comment by var-const** [comment]
Quick update -- I was able to reproduce the 3K reads using the repro case. We will investigate further after the holidays.

**Comment by var-const** [comment]
I can confirm that this case (repeatedly rereading a document as it gets updated) would result in extra reads, and those reads will get billed. Note, however, this only affects the case when persistence is disabled. You mentioned that the issue came up in a load test; is the load test representative of your actual app? In particular:

* the load test runs on Node, which doesn't support persistence. If your actual environment will be a browser, then you could work around the issue by enabling persistence;
* is this particular pattern (modifying and reading the same document in quick succession) representative of the workload of your app? Normally, reading a document doesn't incur the extra reads you're seeing;
* as a last resort, one workaround you could use is to read the document within a transaction; this should result in a single read, no matter the circumstances. Note, however, that the SDKs currently don't support reading a document in a transaction without writing to it, so you would have to abort the transaction.

**Comment by dlockwo** [comment]
The load test was intended to mimic multiple users updating the same document which is indeed part of our use case. We were attempting to determine if we need to be concerned about hitting the once per second write limit on a document.

Regarding persistence, how would persistence prevent the additional reads we are seeing? I assume each user would still get updates for the document from other users while the listener was open? I will look into how I can test this in the browser, but I'm curious as to how persistence prevents reads in this situation.

**Comment by wilhuff** [comment]
When you enable persistence, the client records information about the synchronization state of the document in its cache. This is called a resume token. When the client performs the next read, it includes the resume token with the request, essentially indicating that the server should only send the document if it has changed. With persistence disabled there's no resume token to send.

The server behaves differently for requests with resume tokens. We verified that with persistence enabled we couldn't replicate your results.

**Comment by dlockwo** [comment]
Thanks for the explanation and for the workarounds.
