### ISSUE TITLE
Can't access readTime on DocumentSnapshot

### ISSUE THREAD

**Issue by iwikal** [firebase/firebase-js-sdk#2459]
### [REQUIRED] Describe your environment

  * Operating System version: x86_64 GNU/Linux 5.4.2-arch1-1 
  * Browser version: N/A, nodejs: 10
  * Firebase SDK version: firebase-admin@8.8.0, firebase-functions@3.3.0
  * Firebase Product: functions

### [REQUIRED] Describe the problem

I tried to access the readTime field on the snapshot passed as argument to onWrite cloud functions. This resulted in a crash.

#### Steps to reproduce:

https://github.com/iwikal/read-time-mcve

-   clone my repo
-   switch firebase project to one you have access to
-   deploy functions
-   create a document in the /test collection
-   look in the functions logs.

You should get an error looking something like:

```
Error: Called 'readTime' on a local document
    at QueryDocumentSnapshot.get readTime [as readTime] (/srv/functions/node_modules/@google-cloud/firestore/build/src/document.js:277:19)
    at exports.readReadTime.functions.firestore.document.onWrite.change (/srv/functions/index.js:6:18)
    at cloudFunction (/srv/functions/node_modules/firebase-functions/lib/cloud-functions.js:131:23)
    at Promise.resolve.then (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### Relevant Code:

```js
const functions = require('firebase-functions')

exports.readReadTime = functions.firestore
  .document('test/{docId}')
  .onWrite(change => {
    change.after.readTime
  })
```

**Comment by rommelpe** [comment]
Hi @iwikal, I was able to get the same behavior. I'm not that sure though if that's the proper way of getting the `readTime`. Will confirm this internally and keep you posted for any updates. Thanks

**Comment by schmidt-sebastian** [comment]
@iwikal Thank you for reporting this. This is indeed a bug. I tracked this down to an issue in the Functions SDK and filed https://github.com/firebase/firebase-functions/issues/599 on your behalf. Since the offending code does not live in `firebase-js-sdk`, let's move the conversation to the new issue.
