### ISSUE TITLE
CORS with angularfire2 v5.0.0-rc.3

### ISSUE THREAD

**Issue by trenthm** [firebase/firebase-js-sdk#246]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Sierra v10.12.6
  * Firebase SDK version: 4.6.0
  * Firebase Product: angularfire2 v5.0.0-rc.3

### [REQUIRED] Describe the problem
Running an angularfire2 app from a local server (via `ionic serve` in my environment) should allow an app to access Firestore from a web browser (Chrome, for me) without needing special CORS or server configuration.

The previous angularfire2 version (4.0.0-rc.2) worked in Chrome with the Realtime Database. Only when I upgraded to 5.0.0-rc.3 and switched to Firestore did it not work "out-of-the-box."

The console error shows:
> Failed to load
> https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel?gsessionid....:
> No 'Access-Control-Allow-Origin' header is present on the requested
> resource. Origin 'http://localhost:8100' is therefore not allowed
> access.

#### Steps to reproduce:
Serve an angularfire2 app from a local server, and run it in Chrome.

(Also note that "localhost" is setup as an Authorized domain on the Firebase authentication screen.)

#### Relevant Code:

    items: Observable<any[]>;
    constructor(db: AngularFirestore) {
    this.items = db.collection("my-collection").valueChanges();

    this.items.subscribe(data => {
      console.log("data:", data);
    });

#### Notes:

This issue was originally posted in the angularfire2 repository, and was directed to post it here.

angular/angularfire2#1293

**Comment by trentrand** [comment]
Any update?

**Comment by DarioLondon** [comment]
same problem here

**Comment by binarybro** [comment]
Same here.

**Comment by trentrand** [comment]
I've found that moving firebase requests outside of my resolve and into the controller onInit gets rid of this problem. Still would like to fix that though.

**Comment by jonathanbakley** [comment]
@trentrand Could you give an example of moving your firebase requests outside of your resolve and into the controller?

**Comment by mikelehen** [comment]
Sorry this issue got missed.  Are folks still running into this?  Could somebody post a repro project that demonstrates the issue so that we can investigate?  I'm unaware of any reason that you'd run into CORS issues with Firestore when used with AngularFire.  Thanks!

**Comment by marty331** [comment]
I'm hitting this issue also, would love to see how people are getting around this.  I'm simply trying to pull a link from my Firebase storage, the link is stored in Cloud Firestore as a string.

**Comment by mikelehen** [comment]
Closing this until somebody can provide an example repro.

**Comment by dreadstar** [comment]
I am having a similar issue trying to update a document from an angular  service (testing locally).
macOSX 10.13.2
Angular: 6.1.4

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      6.4.6
@angular/cli                      6.1.5
@angular/flex-layout              6.0.0-beta.17
@angular/material                 6.4.6
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

"angularfire2": "^5.0.0-rc.12"
"firebase": "^5.4.2",

The auth service in my angular app is  able to successfully complete anonymous authorization however when i then try to update the User doc with a default role, I get a CORS error. This is while using ng -serve on my local machine. 

`
import * as firebase from 'firebase/app';

import { AngularFireAuth } from 'angularfire2/auth';
import { AngularFireModule } from 'angularfire2';
import { AngularFirestore, AngularFirestoreDocument } from 'angularfire2/firestore';

import { User } from './user'; // class definition



@Injectable({
  providedIn:'root'
})
export class AuthService implements OnInit{



  authState: any = null;
  user: any;

  constructor(

    public afAuth: AngularFireAuth,
    private afs: AngularFirestore,
    private router: Router,
  ) {

      this.afAuth.authState.subscribe((user)=> {
        if (user) {
          // User is signed in.
          console.log('authStateChange: logged in',user);
          this.user= user;
          this.authState= user;

        } else {
          // User is signed out.
          console.log('authStateChange not logged in:',user);
          this.anonymousLogin();
        }
      });
    }

    ngOnInit(): void {
  
    }
    anonymousLogin():any {
      return this.afAuth.auth.signInAnonymously()
        .then((user) => {
          this.authState = user;
          user['name']='anon-'+ this.currentUserId;
          user['email']='';
          user['roles']={guest: true};
          this.updateUserData(user);
          console.log('anonymous complete:',user)
        })
        .catch(error => console.log(error));
    }


  private updateUserData(user) {
    // Sets user data to firestore on login
    const userRef: AngularFirestoreDocument<User> = this.afs.doc<User>(`users/${this.currentUserId}`);
  
    const data = {
      email: user.email,
      name: user.name,
      roles: user.roles
    }
  
    // return userRef.update(data)  // also did not workvs below
    return userRef.set(data, { merge: true })
  }

  // Returns current user UID
  get currentUserId(): string {
    return this.authenticated ? this.authState.uid : '';
  }
}
`

The error I get is 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Write/channel?database=projects%2Felevated-honor-859%2Fdatabases%2F(default)&VER=8&RID=14866&CVER=22&X-HTTP-Session-Id=gsessionid&%24httpHeaders=Authorization%3ABearer%20eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmNTVkZWZlOWU5YzU2ZmRhZTRkOGY0MDFjZjQ5Njc4YzE2N2MzYWEifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWxldmF0ZWQtaG9ub3ItODU5IiwicHJvdmlkZXJfaWQiOiJhbm9ueW1vdXMiLCJhdWQiOiJlbGV2YXRlZC1ob25vci04NTkiLCJhdXRoX3RpbWUiOjE1MzY4Njk0NjUsInVzZXJfaWQiOiJqT29TU3h1eHZKY0hNWmJpb2FJRmh2SnZRQTAzIiwic3ViIjoiak9vU1N4dXh2SmNITVpiaW9hSUZodkp2UUEwMyIsImlhdCI6MTUzNjg2OTQ2NSwiZXhwIjoxNTM2ODczMDY1LCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImFub255bW91cyJ9fQ.jGC3iOUh76M4ZMFpq35NF8ws9rYlzyOl_jGlTLD8FkTlGhO80XbWs1b1h6xCqKXgTdkpFO4063iQCS5iT54S4lDQpA5kekWJu41ft714MqUIvrnLlTcnyCf22u90n-K2thWmGxk4SUoaGcjNFuWB9zLCMp0MbuSoN1amxpj8oihLQBkQZktYZw60ygP3T1fEXx1YlpD7_F8JXwfPcu5RDRt00OALmXTgpdZrc9y3MNb6NZXx7A7zRQCWI3cbOFCOYABKJmSDuyvhTHgX7DHGYohS6_K-hgg1SR7NQlZcJsTwjZSZlaiVxR4DAJEQM7KBzK2HYbKXcDNoLWS371vcsQ%0D%0AX-Goog-Api-Client%3Agl-js%2F%20fire%2F5.0.4%0D%0A&zx=b3k72ygb3lj9&t=1. (Reason: CORS request did not succeed).

**Comment by abhinavkrdeeps** [comment]
same issue ..any help
