### ISSUE TITLE
FR: Firebase Messaging: SDK installation crashes in Edge InPrivate

### ISSUE THREAD

**Issue by merey90** [firebase/firebase-js-sdk#2465]
### Describe your environment

  * Operating System version: Windows 10 Enterprise Evaluation (version 1809, build 17763.379)
  * Browser version: Microsoft Edge 44.17763.1.0 (Microsoft EdgeHTML 18.17763)
  * Firebase SDK version: 7.6.1
  * Firebase Product: messaging

### Describe the problem
Messaging product of firebase SDK has `idb` dependency, which throws uncatched errors.
This causes crashes on Microsoft Edge in InPrivate mode. Also in Firefox in private mode throws uncatchable error.

#### Steps to reproduce:
1. Install Firebase SDK to web page
2. Initiate the firebase app with `messaging` product
3. Open the web page with Microsoft Edge in InPrivate browsing
4. SDK Initialization will crash because IndexedDB's apis are undefined in Edge's InPrivate mode

#### Relevant Code:
https://stackblitz.com/fork/firebase-issue-sandbox

#### Screenshots:
Microsoft Edge browser crashes:
![Screen Shot 2019-12-20 at 11 29 18 AM](https://user-images.githubusercontent.com/8048802/71252239-baeb5080-2324-11ea-81d9-ee20326f4889.png)

Firefox renders the page, but throws uncatchable error:
![Screen Shot 2019-12-20 at 11 28 44 AM](https://user-images.githubusercontent.com/8048802/71252292-e2421d80-2324-11ea-81e1-43369d920cba.png)

### Desired behavior
Make it possible to catch the error or handle indexedDB unsupported state

**Comment by hsubox76** [comment]
See related issue: https://github.com/firebase/firebase-js-sdk/issues/2373

As suggested in that issue, can you detect private mode and not initialize messaging if that's the case?

Otherwise @mmermerkaya is it worth it to find a way to throw a catchable error on trying to initialize messaging when there is no IndexedDB?

**Comment by mmermerkaya** [comment]
I'll see if I can add this to the `isSupported()` check.

**Comment by merey90** [comment]
> See related issue: #2373
> 
> As suggested in that issue, can you detect private mode and not initialize messaging if that's the case?
> 
> Otherwise @mmermerkaya is it worth it to find a way to throw a catchable error on trying to initialize messaging when there is no IndexedDB?

If it is possible I would prefer catchable error. if not, then will try detecting private mode 👍

**Comment by alexiusp** [comment]
@mmermerkaya @hsubox76 any news on this topic? having a catchable error would be really appreciated.

**Comment by zwu52** [comment]
Hi @alexiusp, We currently have a proposal on adding messaging.isSupported (or something like that) into the API. Will keep this thread posted. Thanks

**Comment by zwu52** [comment]
Hi @alexiusp ,
@mmermerkaya has added [the API support ](https://firebase.google.com/docs/reference/js/firebase.messaging#issupported). [Here](https://github.com/firebase/firebase-js-sdk/issues/1260#issuecomment-426684713) is an example on how to use. Cheers.
