### ISSUE TITLE
firebase.messaging.deleteToken() FAILED when deleting token

### ISSUE THREAD

**Issue by tbua** [firebase/firebase-js-sdk#2469]
### [REQUIRED] Describe your environment
Operating System version: Microsoft Windows 10 Pro Version 10.0.10586 Build 10586
Browser version: Google Chrome Version 79.0.3945.88
Firebase SDK version: 6.4.2
Firebase Product: Firebase Cloud Messaging

### [REQUIRED] Describe the problem
I am trying stop web browser from receiving notification for cases where user logs out/ when oauth refresh token timeout (forced logout). 

But when calling method `firebase.messaging.deleteToken()` with a valid token passed in as parameter,  I keep getting errors "A problem occurred while unsubscribing the user from FCM: Requested entity was not found. (messaging/token-unsubscribe-failed)". I'm not sure why the request failed and why it's even trying to unsubscribe first even though I'm calling deleteToken.

After failing to delete the token, I try querying its info using this api: `https://iid.googleapis.com/iid/v1/info/{token}?details=true`, and saw that the token still exists and is even subscribed to a topic. And when I try to manually delete the token itself, via DELETE method to url https://iid.googleapis.com/v1/web/iid/{token}, it seems to work fine. 

#### Steps to reproduce:
The problem occurs after taking the following steps:

Call firebase.messaging.requestPermission() and user grants permissions

Call firebase.messaging.getToken() and save token somewhere

Subscribe to a topic

Call firebase.messaging.deleteToken(token) using the token saved previously as parameter. Get error:
```err = FirebaseError: Messaging: A problem occured while unsubscribing the user from FCM: FirebaseError: Messaging: A problem occured while unsubscribing the user from FCM: Requested entity was not found. (messaging/token-unsubscribe-failed). ). at IidModel.<anonymous>```

#### Relevant Code:

```javascript
    navigator.serviceWorker
      .register(`assets/firebase-messaging-sw.js?messagingSenderId=${environment.firebaseConfig.messagingSenderId}`)
      .then(registration => {
        this.messaging = firebase.messaging();

        this.messaging.useServiceWorker(registration);
        this.sw = registration;

.........


      this.messaging
        .requestPermission()
        .then(() => {
          return this.messaging.getToken();
        })
        .then(token => {
          this.tokenFB = token;
          // send request to backend with token to subscribe to topic
        })
        .catch(err => {
          console.error(err);
        });

...........

this.messaging
                        .deleteToken(this.tokenFB)
                        .then(resp => {
                          return;
                        })
                        .catch(err => {
                          console.error(this.tokenFB, err);
                        });




```

**Comment by lusk** [comment]
I can confirm the above. I'm having the same problem with Firebase SDK version: 5.11.1
I've also tried Firebase SDK version: 6.4.2 with same result.

**Comment by rommelpe** [comment]
Related to https://github.com/firebase/firebase-js-sdk/issues/2364, you may try upgrading your SDK to the latest version ([7.6.1](https://firebase.google.com/support/release-notes/js))

**Comment by lusk** [comment]
Upgrading to 7.6.1 resolved the issue for me. Thanks for the hint!
