### ISSUE TITLE
FR: Pass the changed path to the on("value"/"child_added"/"child_removed"/"child_changed") callback

### ISSUE THREAD

**Issue by escrimeuse** [firebase/firebase-js-sdk#247]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04
  * Firebase SDK version: 4.0.0
  * Firebase Product: Realtime database (auth, database, storage, etc)

### [REQUIRED] Describe the problem

Currently, the callback that is bound to a database reference using the `on("value"/"child_added"/"child_removed"/"child_changed")` is passed a `DataSnapshot` that contains _all_ the data for that reference. It would be nice to also pass to the callback the path of the property that changed (either by including it in the `DataSnapshot` itself, or passing it as a separate argument).

To illustrate this, consider the following database structure: 

```
project : {
	name : ...
	priority : ...
	tasks : {
		one   : { name : ..., priority: ...}
		two   : { name : ..., priority: ...}
		three : { name : ..., priority: ...}
	}
}
```
I have a callback bound to the `project` ref using `on("value")`. In the callback, if I want to know exactly which property changed and triggered the "value" event, then I need to do this manually by going through the `DataSnapshot` and comparing it with whatever I have stored locally. If the path of the changed property was passed to the callback, it would simplify the callback code considerably. 

From my research in the SDK, the path of the changed property is present up to the `EventQueue.raiseEventsForChangedPath` function, but it's not passed along with the `DataSnapshot` when `queueEvent` is called. Since the changed path is already available and potentially highly useful, it should be passed along as well. 

Thanks!

**Comment by mikelehen** [comment]
FYI- Given the current features, the recommended way to do this is to attach additional child_added, child_changed, and child_removed events if you want to know which child changed.  Since you already have a 'value' listener on the data, the additional events incur no extra bandwidth and minimal extra processing.

**Comment by escrimeuse** [comment]
@mikelehen, that's essentially what we are currently doing. For example, right now we have listeners bound to the value events for each individual `task` property (so, using the database structure defined above, a listener for `task one`'s name, a listener for `task one`'s priority, a listener for `task two`'s name, etc). In our actual use case, we have 16 task properties and around 1000 tasks. The problem is that the binding of this many listeners at once takes a really long time (around 4 seconds from the binding of the first listener to the binding of the last). Ideally, we'd like to just bind one listener per task.

**Comment by mikelehen** [comment]
Thanks for the added info.  Just to be clear, I think you could add a single child_changed (and if necessary child_added and child_removed) listener to each of the 1000 tasks, rather than 16 'value' listeners to each task.  While still somewhat expensive, it should be quite a bit faster.

**Comment by schmidt-sebastian** [comment]
Please let us know if @mikelehen doesn't work for you. For now, I am closing this issue.
