### ISSUE TITLE
auth/network-request-failed

### ISSUE THREAD

**Issue by tenjojeremy** [firebase/firebase-js-sdk#2473]
![Annotation 2019-12-26 192632](https://user-images.githubusercontent.com/25231946/71494502-a8d24c00-2815-11ea-9d86-58087b1d51c0.jpg)

**Comment by rommelpe** [comment]
Thanks for reporting, @tenjojeremy. Could you provide the following:

- [Minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally 
- Detailed steps taken that led to the error message encountered
- Actual and expected result
- Browser version and OS used

**Comment by tenjojeremy** [comment]
It fixed itself after rebooting chrome
