### ISSUE TITLE
getting null when user solve image captcha

### ISSUE THREAD

**Issue by developdeez** [firebase/firebase-js-sdk#2475]
My frontend is React. I've noticed this when solving captchas myself.

`
xhr | POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/sendVerificationCode?key={key} [400]`
-- | -- followed by

```
TypeError: null is not an object (evaluating 'e.style')
--
```

 Here's my recaptcha tag.
<div id="recaptcha-container" style={{ display: "none" }}></div>

Considering the user can click the captcha its clearly rendered. Am I missing something here?

**Comment by schmidt-sebastian** [comment]
@developdeez Thanks for filing this issue. You seem to have an issue with ReCaptcha - this repository is for the Firebase Web SDKs. We won't be able to help you here. Please take a look here: https://support.google.com/recaptcha/?hl=en
