### ISSUE TITLE
TypeError: "Object(...) is not a function" when doing a batch insert in Firestore

### ISSUE THREAD

**Issue by brpaz** [firebase/firebase-js-sdk#2476]
### Environment

  * Operating System version: Fedora 30
  * Browser version: Firefox 71
  * Firebase SDK version: 7.6.1
  * Firebase Product: firestore

### Describe the problem

I am trying to insert some "tag" documents in batch in Firestore and I am getting the following error in console:

**TypeError: "Object(...) is not a function"**

The error occurs on the `batch.set` instruction.

Here is a snippet of my code:

```
 // insert tags
const batch = db.batch()

 for (const tag of tagsToBeCreated) {
      const tagRef = db.collection('tags').doc()
      batch.set(tagRef, { code: slug(tag.name), name: tag.name })
    }
  batch.commit()
```

I have seen #1885 but I am initializing the Firestore instance from the app already like suggested.

Any help?

Thank you.

**Comment by schmidt-sebastian** [comment]
@brpaz Sorry to hear about your troubles. Are you able to use other functionality in Firestore (e.g. would your code snippet work if you used tagRef.set()?).

If that doesn't help, can you console.log `db` so that I can see if it contains the expected set of properties. Thank you!

**Comment by rommelpe** [comment]
Haven’t heard from you in a while, @brpaz . Just wondering if you are still interested working on this issue. We are happy to look into this further if you could provide the info that we asked for.

**Comment by brpaz** [comment]
@rommelpe yes. I will get back to the project I am working on next weekend. I will then provide the requested info.

**Comment by brpaz** [comment]
Solved the problem. 
I was using the "slug" function, inline with the `batch.set` and it was that was causing the error, not firestore.

```
  batch.set(tagRef, { code: slug(tag.name), name: tag.name })
```

Everything is working fine now.

**Comment by schmidt-sebastian** [comment]
Thanks for the update! Glad you figured it out.
