### ISSUE TITLE
FR: prefill serverTimestamp() with Timestamp object with .onSnapshot() before the response is received

### ISSUE THREAD

**Issue by magpiedigital** [firebase/firebase-js-sdk#2477]
* Operating System version: macOS 10.14.6
  * Browser version: Chrome 79.0.3945.88
  * Firebase SDK version: 7.6.1
  * Firebase Product: firestore

### Describe the problem
When you add a serverTimestamp to a document, listened to with onSnapshot(), the local version is cached as `null` before the response is returned with the timestamp.

I think it would be a better experience if the local version returned a firestore timestamp based on the local time instead of null.

#### Steps to reproduce:
listen to a collection
add/update an entry with a serverTimestamp
the first local result returns null value in the serverTimestamp field
once a response is received, this is now a Timestamp object.

**Comment by schmidt-sebastian** [comment]
@magpiedigital Thanks for filing this issue! This is actually something we support. You can get "estimated" timestamps as such:

```
collection.onSnapshot(result => {
  for (const doc of result.docs) {
     const dataWithEstimate = doc.data({  serverTimestamps: 'estimate'  });
     const fieldWithEstimate = docSnap.get('timestamp', {  serverTimestamps: 'estimate'  });
  }
});
```

I hope that works for you!
