### ISSUE TITLE
Google Sign In not possible from within electron

### ISSUE THREAD

**Issue by TomTomB** [firebase/firebase-js-sdk#2478]
### Describe your environment

  * Operating System version: Windows 10 Build 1909
  * Browser version: Electron 7.1.7
  * Firebase SDK version: 7.6.1
  * Firebase Product: auth

### Describe the problem

I am not able to sign in with my Google account. After clicking the sign in button inside the popup the following message appears:

```
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

I´ve already resolved every electron security warning

#### Steps to reproduce:

I´ve prepared a repo to reproduce this issue. You can find it [here](https://github.com/TomTomB/electron-firebase-auth-issue)

**Comment by bojeil-google** [comment]
We don't support  popup/redirect sign-in operations in Electron. The error message also does not appear to come from our SDK. Are you using the Google sign in library?

**Comment by TomTomB** [comment]
I´ve read [this Medium article](https://medium.com/firebase-developers/using-firebase-in-electron-tips-and-tricks-24ac5b44bf5a) about using Firebase with Electron and it´s caveats. After that, I´ve resolved every issue that may appear (like getting Firebase to think its not being ran inside an node env) and created the issue repo mentioned above. 
My actual project is using the Firebase SDK wrapped within the [Angular/Fire package](https://github.com/angular/angularfire), nothing else.

**Comment by hsubox76** [comment]
It seems like this may be an issue with Google Sign-In and not Firebase.  It seems from this issue, which is about using Google Sign-In in Electron, without Firebase, that it may have to do with Chrome or some back-end security requirements of Google Sign-In. https://support.google.com/accounts/thread/22873505?hl=en

**Comment by TomTomB** [comment]
Apparently, for whatever reason, the issue is caused by the User Agent. 

**Steps to reproduce:**

- Open Dev Tools inside the Google Sign-In popup
- Open the Network conditions tab (which can be found inside the 3 dot menu -> More Tools -> Network conditions) 
- E.g. choose the "Firefox - Windows" User Agent
- Reload the page 
- Sign in works 

Is there, by any chance, a way to change the User Agent before opening the popup dialog?
I´ve already looked inside the Electron "new-window" Event but without success. 
It´s only possible to edit the User Agent via [Session.setUserAgent](https://electronjs.org/docs/api/session#sessetuseragentuseragent-acceptlanguages) and inside the [window.loadUrl](https://electronjs.org/docs/api/browser-window#winloadurlurl-options) options.

**Comment by hsubox76** [comment]
I don't think the best solution is to have Firebase open up the capability to spoof a different user agent when opening a popup window, it doesn't seem like a good practice in general.

Have you tried using Electron's `userAgentFallback` as described in this Reddit thread? https://www.reddit.com/r/electronjs/comments/eiy2sf/google_blocking_log_in_from_electron_apps/

**Comment by TomTomB** [comment]
Me neither. I can confirm that setting [app.userAgentFallback](https://electronjs.org/docs/all#appuseragentfallback) to e.g. `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) old-airport-include/1.0.0 Chrome Electron/7.1.7 Safari/537.36` fixes the issue.  

Hopefully this workaround won't be need for ever from now on.

**Comment by malcolmdeck** [comment]
It sounds like this issue is resolved - a workaround is explained above, and we don't intend on supporting this directly at this time.

**Comment by kbourro** [comment]
It seems that user-agent bypass stopped working.

**Comment by varun508** [comment]
useragentfallback isn't working anymore. Any update on that?

**Comment by malcolmdeck** [comment]
Can you please go into a little bit more detail about what's broken with that workaround now? Is it a problem with Google Sign-In or Firebase Auth? What error are you getting? Again, we don't support popup/redirect sign-in operations in Electron, but I'll try to help if I can.

**Comment by bartoszhernas** [comment]
The issue is that for some accounts, Google is blocking login page when that page was opened in Electron window. This only happens for some accounts and not all, which is really weird. 

Changing user agent of Electron worked for some credentials, but we are still getting errors that users are not able to log in :(

**Comment by pejmanjohn** [comment]
I am seeing this issue as well. I have a private Google Spreadsheet in a webview in Electron. In order to view it I have to sign into my Google account first but after I enter my email address and hit continue I see this: "This browser or app may not be secure."

<img width="514" alt="Screen Shot 2020-05-14 at 10 19 17 PM" src="https://user-images.githubusercontent.com/481729/82014197-fae30500-9630-11ea-86fd-b98802da0478.png">

**Comment by tofutim** [comment]
the fun may be over :(
