### ISSUE TITLE
A mutation operation was attempted on a database that did not allow mutations

### ISSUE THREAD

**Issue by xerosanyam** [firebase/firebase-js-sdk#2481]
### Describe your environment

  * Operating System version: MacOS 10.15
  * Browser version: Firefox 71
  * Firebase SDK version: 7.2.2
  * Firebase Product: auth, database, performance, analytics

### [REQUIRED] Describe the problem
In Firefox incognito, the firebase js throws error `A mutation operation was attempted on a database that did not allow mutations.`

I am Trying to access data from an anonymous user.
Works as intended in Normal Window(non-incognito)

**Comment by rommelpe** [comment]
Duplicate of #2373, see https://github.com/firebase/firebase-js-sdk/issues/2373#issuecomment-557293448

**Comment by xerosanyam** [comment]
I am not using remote config, still facing this issue.
