### ISSUE TITLE
Firebase authentication issue

### ISSUE THREAD

**Issue by tchimih** [firebase/firebase-js-sdk#2483]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04 LTS
  * Browser version: Chrome 78
  * Firebase SDK version: 7.6.0
  * Firebase Product: auth

#### Steps to reproduce:
Hello,

I'm using firebase for authenticating my users to my backend. Everything is working fine. However, when I refresh my page, it asks me to re authenticate ... this is bad for the user experience. I tried evey tutorial on the documentation website (method onAuthStateChanged). Nothing's working for me so far. Can you help me out ?
#### Relevant Code:

```javascript
// file main.js
//imports
...
import firebase from './firebase' // a file at the same level as main.js

let app = '';

// check if the user is logged in on every reload

firebase.auth().onAuthStateChanged( () => {
  if (!app) {
    app = new Vue({
      vuetify,
      router,
      store,
      render: h => h(App)
    }).$mount('#app')
  }
})
```
the firebase file 
```javascript
import firebase from 'firebase'

var firebaseConfig = {
 // infos about my firebase
};

// Initialize Firebase
const firebaseApp = firebase.initializeApp(firebaseConfig);

export default firebaseApp
```

**Comment by rommelpe** [comment]
Thanks for reporting the issue, @tchimih. I'm not an expert with Vue apps. Can you help me reproduce the issue? If you could provide a minimal repro that I can run locally and detailed steps to replicate it, that would be a great help for us to speed up the investigation. Thanks!

**Comment by tchimih** [comment]
Hello @rommelpe,

Here is a [showcase git repository](https://github.com/tchimih/showcase-firebase) describing my issue.

Steps to reproduice:
1- ``` npm install ```
2- Change the firebase configuration in main.js file
3- ``` npm run serve ```
4- Upon the login phase, you will be redirected to the about view. However, as soon as you reload the page, you will be asked to login (although you're logged in the firebase).

Thanks for your time.

**Comment by rommelpe** [comment]
Thanks for working on the repro. It looks like that you missed to check whether the user is currently signed-in. 

```
firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    // User is signed in.
  } else {
    // No user is signed in.
  }
});
```

You could also check out our [quickstart guide](https://github.com/firebase/quickstart-js/blob/master/auth/email-password.html) for a sample auth cycle implementation.
