### ISSUE TITLE
.info/connected does not change to false when offline

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-js-sdk#249]
From https://github.com/firebase/firebase-admin-node/issues/99

I've verified that this issue occurs with latest RTDB code as well (`@firebase/database 0.1.2`)

### Environment

Debian buster
Node.js v 8.5.0
firebase-admin v ^5.0.0

#### Steps to reproduce:

1. Start application and wait for console log "Firebase connected!"
2. Go offline (switch off wifi or remove lan cable etc.)

When internet connection is disabled, application should print "Firebase disconnected".
It seems, it never does!

#### Relevant Code:

```javascript
"use strict";

var path = require('path');
var admin = require("firebase-admin");

var serviceAccount = require(path.join(__dirname, "some-firebase-adminsdk-lu0x5-82c66d50f5.json"));

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://some.firebaseio.com/"
});

const database = admin.database();

var connectedRef = database.ref(".info/connected");
connectedRef.on("value", function(snap) {
  if (snap.val() === true) {
    console.log("Firebase connected!");
  } else {
    console.log("Firebase disconnected!");
  }
});
```

**Comment by schmidt-sebastian** [comment]
Hiranya, do you know if this a Node only issue? Our networking layer is different in Node and I wonder whether this is something we never supported (it also doesn't make as much sense in Node as it does on the mobile platforms).

**Comment by mikelehen** [comment]
FWIW, I would expect it to work (the websocket connection should die and trigger .info/connected to change), but it may take a really long time (e.g. 15 minutes) depending on OS TCP timeout settings, etc.

**Comment by hiranya911** [comment]
I have only tested this in Node (with the Admin SDK). I think @mikelehen may be right. I remember seeing this event fire long time (> 15 mins) after a disconnect. Since the delay was long, I brushed it off as a fluke. I also agree that it is not a very popular use case for server-side environments. So may be we can just ensure it works in the web SDK, and document the behavior for Node?

**Comment by schmidt-sebastian** [comment]
It really depends on the underlying network stack. We have seen that this event doesn't fire for a full hour on some Android devices as the TCP retry window prevents the network stack from bubbling up these connection drops.

**Comment by kkm** [comment]
+1

**Comment by AndryBray** [comment]
I have the same after upgrading to 4.1.5 - previous versions where OK.
It's like the event is fired twice:
- first time offline
- second time online again (but this is wrong)

**Comment by gsushant** [comment]
As @AndryBray pointed out, I am having the same issue (event firing twice - offline followed by online).  The example at: https://firebase.google.com/docs/database/web/offline-capabilities#section-presence works fine with 4.1.3 but doesn't work with 4.1.4 (and 5.0.4).

**Comment by DennisSmolek** [comment]
For me it's never turning true... It's stuck at false..

**Comment by vincentwoo** [comment]
I think this is a reasonable argument for using heartbeat keepalive

**Comment by lukepighetti** [comment]
Hey guys, I *think* this is related

```
async function main() {
  await admin
    .database()
    .ref("/test")
    .set(admin.database.ServerValue.TIMESTAMP);

  admin.database().goOffline();
}
```

This does not allow Node.js process to exit like one would expect.

**Comment by ristiisa** [comment]
I can confirm that it works with 4.1.3 but not with latest version (5.9.0)

**Comment by jedierikb** [comment]
on chrome, using 6.0.0, problem persists.

**Comment by LanderBeeuwsaert** [comment]
I have the same as @AndryBray : when simulating a disconnect in chrome by using devtools, I get an offline directly followed by online.

If I run:

  async isConnected(): Promise<boolean> {
    return (await database()
      .ref('.info/connected')
      .once('value')).val();
  }

then it returns true, while I have in the network tab of chrome devtools that I'm offline.

version: "firebase": "6.0.2",
Persistency is off.

**Comment by zabaat** [comment]
Having same issue as well
firebase 5.10.0
when simulating a disconnect in chrome by using devtools, I get an offline directly followed by online.
When i disconnect internet connection it doesn't even fire an offline.

**Comment by zabaat** [comment]
In the meantime I'm doing an interval check on
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

**Comment by squigglybob** [comment]
+1 on firebase 6.2.0

**Comment by mintu19** [comment]
+1 on firebase 6.6.1 on node

**Comment by kkm** [comment]
+1 more than 3 still not solved.

**Comment by LanderBeeuwsaert** [comment]
Just encountered this again, with latest libraries.
Maybe can be interesting:
When I disconnect my wifi, it works fine. When I do a disconnect in chrome devtools network tab, it gives the issue.

**Comment by johnnyoshika** [comment]
Does this work for anyone? This is what I see:

* If I navigate away from my app or close my browser, onDisconnect correctly gets called and I can detect offline.
* If I set my network status to offline in dev tools, `ref('.info/connected').on('value')` gets called twice. First for offline then immediately again for online. So even though I'm offline, I can't detect that.
* If I turn off my WiFi,  `ref('.info/connected').on('value')` correctly gets called once, but `onDisconnect` doesn't, so there's no indication on the database end that the user went offline.

**Comment by norcrel** [comment]
> Does this work for anyone? This is what I see:
> 
> * If I navigate away from my app or close my tab, it's a clean disconnect and the following immediately happens:
>   
>   * `ref('.info/connected').on('value')` === false
>   * `onDisconnect()` gets called
> * If I set my network status to offline in dev tools, `ref('.info/connected').on('value')` gets called twice. First with `false` then with `true`. So even though I'm offline, it doesn't detect that.
> * If I turn off my WiFi (i.e. dirty disconnect),  `ref('.info/connected').on('value')` === false correctly gets called immediately, but `onDisconnect` doesn't. It takes a few minutes before `onDisconnect` gets called, leaving the server thinking that the user is online when s/he isn't for up to a few minutes.
> 
> There's some interesting insight about `onDisconnected()` here: https://stackoverflow.com/a/49547545/188740

This is also happening to me on Chrome. Setting "offline" in dev tools on chrome also caused a `false` then `true` to be logged

**Comment by oveddan** [comment]
@johnnyoshika I have the same issue, where I get 2 `.info/connected` events, the first with value false the second with true.

**Comment by johnnyoshika** [comment]
@oveddan it's a very strange behaviour. I think it's a bug.

**Comment by LanderBeeuwsaert** [comment]
@schmidt-sebastian 
This seems to be a bug that has been happening for some years in a consistent manner.
Is there an idea about/planning for looking into this?

**Comment by b2m9** [comment]
I'm running into the same issues that toggling network status in the Chrome/Chromium DevTools (v 91.0.4472.77) fire twice and stay in the "online" state. I'm on version `9.0.0-beta.2`.

It makes debugging online/offline behavior unnecessarily complicated.

**Comment by kkm** [comment]
almost 4 years and still bug.

**Comment by oveddan** [comment]
I built a lot of my application based on this documented feature, and as a result of this bug it's lead to some pretty critical bugs happening in my application.  If it's not working as documented and expected, and there doesn't seem to be a stated acknowledgement of the issue or plan to look at it, then why leave it in the documentation?

**Comment by Rubilmax** [comment]
If you are using React: it only works when inside a `useEffect` hook.

```javascript
React.useEffect(() => {
    database.ref('.info/connected').on('value', (snapshot) => {
      const isOnline = snapshot.val();
    });
  }, []);
```

**Comment by johnnyoshika** [comment]
@Rubilmax, which part are you referring to when you say it works inside of `useEffect`? I experienced several problems with `.info/connected` that I outlined here: https://github.com/firebase/firebase-js-sdk/issues/249#issuecomment-791199152, but I don't think `useEffect` will change anything. Are you seeing something different?

**Comment by Rubilmax** [comment]
> @Rubilmax, which part are you referring to when you say it works inside of `useEffect`? I experienced several problems with `.info/connected` that I outlined here: [#249 (comment)](https://github.com/firebase/firebase-js-sdk/issues/249#issuecomment-791199152), but I don't think `useEffect` will change anything. Are you seeing something different?

I am referring to how `.info/connecteed` is expected to work. Respectively, I tested your 3 use cases with the listener added inside a `useEffect` and using a `debounce` of `2000ms` and the results were the following:
- clean disconnect: `false`, when opening a new tab: `true`
- devtools offline: `false`, then online: `true`
- dirty disconnect: `false` then when re-enabling wifi: `true`

I did not test any feature related to `onDisconnect`

**Comment by johnnyoshika** [comment]
@Rubilmax Thanks. Use case 1 and 3 that you're seeing is the same behavior that I saw for `.info/connected`. You're seeing a different behavior for use case 2 with dev tools and that's interesting. My `.info/connected` would get called twice when I went offline in dev tools: once with online==false and once for online==true even if I left it in offline mode.

I still believe there's a problem with `onDisconnect`.

Note:
* I didn't re-test my examples, so I'm basing my comments off of my tests I did on March 4th. Things could have changed since then.
* I did all of my tests inside of `useEffect` as well

**Comment by Ajiharan** [comment]
I have the same situation here. **info/connected** events  called with the first with value false the second with true, then I  set my network offline through chrome dev tools  **.info/connected** called twice with value false and the second with true. when I disconnect my wifi   .info/connected called with value false as expected but **onDisconnect** doesn't call after my wifi disconnected
firebase version: 8.9.1

**Comment by maneesht** [comment]
@vasujogani are you still having issues on the latest version of the JS SDK?
