### ISSUE TITLE
Errors messages appearing when reinstalling firebase on reimaged device

### ISSUE THREAD

**Issue by HsuTimothy** [firebase/firebase-js-sdk#2491]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS Catalina
  * Browser version: Not applicable
  * Firebase SDK version: "firebase": "^6.0.4",
  * Firebase Product: installation (auth, database, storage, etc)
* Node version: v13.5.0
* Npm version: 6.13.4

#### Steps to reproduce:

When running `npm install --save firebase` I'm seeing some errors 

```
../ext/call.cc:104:53: error: no matching member function for call to 'Get'
    Local<String> current_key(Nan::To<String>(keys->Get(i)).ToLocalChecked());
                                              ~~~~~~^~~
/Users/timothyhsu/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/timothyhsu/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../ext/call.cc:681:27: error: no matching member function for call to 'Get'
    if (!op->ParseOp(obj->Get(type), &ops[i])) {
                     ~~~~~^~~
/Users/timothyhsu/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/timothyhsu/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,

2 errors generated.
make: *** [Release/obj.target/grpc_node/ext/call.o] Error 1
```

This issue only started happening after I re-imaged my device . I've tried `npm cache clean --force`, deleting my node_modules folder, and deleting the package-lock.json but all to no avail. Can anyone provide some insight?

Thanks!

**Comment by rommelpe** [comment]
Hi @HsuTimothy, can you share your npm & node version? Have you considered using the stable version?

**Comment by HsuTimothy** [comment]
@rommelpe Hi rommel thanks for helping out. I've updated the original post

**Comment by hsubox76** [comment]
Can you try going back to an older version of Node (using `nvm` so you don't have to uninstall and reinstall the whole thing), 12 or maybe even 10?

Searching around, I see some npm install node-gyp issues reported with Node 13 and Catalina, with various packages, the suggested solution being to temporarily downgrade the Node version to 8 or 10.

**Comment by HsuTimothy** [comment]
@hsubox76 That did the trick! I switched from v13 -> v12 and now it's installing just fine. Thanks for everyone's help! I was pulling my hair out over something so simple 🤣
