### ISSUE TITLE
Firebase upload progress number going over 100 from snapshot.bytesTransferred / snapshot.totalBytes

### ISSUE THREAD

**Issue by nica0012** [firebase/firebase-js-sdk#2498]
SDK version:   "^7.6.1",
Firebase Product: storage

This used to work fine until very recently.

When uploading a file, I am tracking the upload progress like this:

 ```
uploadImage = uri => {
            const image = Platform.OS === 'ios' ? uri.replace('file://', '') : uri;
            const Blob = RNFetchBlob.polyfill.Blob;
            const fs = RNFetchBlob.fs;
            window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest;
            window.Blob = Blob;

            let uploadBlob = null;

            const imageRef = firebase
            .storage()
            .ref('categories/')
            .child(`${this.props.userData.uid}`)
            .child(`${this.state.img}`);

            const mime = this.state.isVideo ? 'video/mp4' : 'image/jpg';

            fs.readFile(image, 'base64')
            .then(data => {
                return Blob.build(data, {type: `${mime};BASE64`});
            })
            .then(blob => {
                uploadBlob = blob;
                this.uploadTask = imageRef.put(blob, {contentType: mime});

                this.uploadTask.on(
                'state_changed',
                snapshot => {
                    // Observe state change events such as progress, pause, and resume
                    // Get task progress, including the number of bytes uploaded and the total number of bytes to be uploaded
                    const progress =
                    (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
                    LayoutAnimation.easeInEaseOut();
                    this.setState({ uploadProgress: progress });
                    console.log(`Upload is ${progress}% done`);
                    switch (snapshot.state) {
                    case firebase.storage.TaskState.PAUSED: // or 'paused'
                        console.log('Upload is paused');
                        break;
                    case firebase.storage.TaskState.RUNNING: // or 'running'
                        console.log('Upload is running');
                        break;
                    }
                },
                error => {
                    // Handle unsuccessful uploads

                },
                () => {
                    // Handle successful uploads on complete
                },
                );
            });
        };

```

Here is how I am displaying the number in my component:

```
<Text>          
  {Math.trunc(this.state.uploadProgress)}%  
 </Text>
```

I am setting the number in my components state then displaying it to the user. For some reason recently the number exceeds 100, it shows something big like 38154017 for example.

When I log the progress, I can see where it goes wrong:

```
 console.log(`Upload is ${progress}% done`);

 LOG  Upload is 0% done
 LOG  Upload is 38.15395542514653% done
 LOG  Upload is 38.15395542514653% done
 LOG  Upload is 38154017.271191105% done
 LOG  Upload is 100% done
```

For some reason, the progress is multiplying the third log by 100? This is only happening as of about a month, and after researching people seem to still be doing it this way.

Here are the logs for the bytesTransferred and totalBytes:

```
console.log(snapshot.bytesTransferred);

LOG  bytesTransferred 0
LOG  bytesTransferred 0262144
LOG  bytesTransferred 262144
LOG  bytesTransferred 262144524288
LOG  bytesTransferred 786432
LOG  bytesTransferred 786432176078
```

The numbers seem to be getting doubled / concatenated somehow all of a sudden?

I don't know if firebase changed something, but whatever it is I would love to hear people's comments!

Cheers.

**Comment by rommelpe** [comment]
Thanks for reporting, @nica0012. This might be an isolated case as [Firebase storage is healthy](https://status.firebase.google.com/) so far, and no signs of trending issues.

While I'm trying to reproduce this on my end, it would be great if you provide provide a [working repro](https://stackoverflow.com/help/minimal-reproducible-example) that we can run locally and a copy the sample file to speed up the investigation. Thanks!

**Comment by rommelpe** [comment]
Thanks for reporting, @nica0012. This might be an isolated case as Firebase storage is [healthy](https://status.firebase.google.com/) so far, and no signs of trending issues.

While I'm trying to reproduce this on my end, it would be great if you can provide a working repro that we can run locally and a copy the sample file to speed up the investigation. Thanks!

**Comment by rommelpe** [comment]
Sorry for not getting back to you sooner, @nica0012. I can't seem to replicate it or am just missing something. I always end up in the initial log;

![image](https://user-images.githubusercontent.com/56452310/72920939-44a79700-3d85-11ea-8ce9-f77dd07dae3b.png)


Are you still having this issue? You may share a working repro for us to check if the issue you encountered is intended or could be related to your implementation. Thanks!
