### ISSUE TITLE
TypeMismatchError in Microsoft Edge 14

### ISSUE THREAD

**Issue by ernsheong** [firebase/firebase-js-sdk#251]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10, Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393
  * Firebase SDK version: 4.5.2
  * Firebase Product: auth

#### Steps to reproduce:

I'm not doing anything fancy with Firebase in my JS SPA app, but I'm getting a TypeMismatchError in Edge browser, originating from auth.js

![image](https://user-images.githubusercontent.com/1343284/31848139-de11c156-b65d-11e7-98b0-53a7b56a1aa2.png)

![image](https://user-images.githubusercontent.com/1343284/31848179-8320c656-b65e-11e7-8f32-fbb9f14b587b.png)

It might be related to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11358518/, but I am not sure how to verify this, as the code is minified and I can't see into it. 

No error is thrown in other evergreen browsers.

**Comment by bojeil-google** [comment]
I tested the latest version 4.6.0 in Edge 14. I signed in users via different methods and didn't get this error. Can you provide a more concrete way to reproduce this?

**Comment by ernsheong** [comment]
The problem kinda went away in 4.6.0. I'm not quite sure what happened. I will close this for now.

Currently getting a 400 error when trying to log in for API in Edge 14: 
`POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=SOMEKEY`
