### ISSUE TITLE
FCM - Without results message_id when sending to EDGE, on Chrome works fine

### ISSUE THREAD

**Issue by mcostabr** [firebase/firebase-js-sdk#2517]
I get the sample code here, tested it on Chrome it worked fine, on MS EDGE don't get the message.

Is there any incompatibility? 
The EDGE version is 18, theoretically supposed to work.
Microsoft Edge 44.18362.449.0 / Microsoft EdgeHTML 18.18362
https://firebase.google.com/support/guides/environments_js-sdk

Printscreen test on Chrome, EDGE and postman results.

![TEST1](https://user-images.githubusercontent.com/957542/71459021-60b71900-2784-11ea-8892-4034162b5973.PNG)

Postman results, the **message_id is empty**:

```
{
    "multicast_id": 9215195938054196561,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": ""
        }
    ]
}

```

Chrome results message.
![image](https://user-images.githubusercontent.com/957542/71460644-7e3bb100-278b-11ea-8dc6-90bfb56598e2.png)

CHROME TOKEN IID INFO
![image](https://user-images.githubusercontent.com/957542/71460582-33ba3480-278b-11ea-8f30-7490531467cb.png)

EDGE TOKEN IID INFO
![image](https://user-images.githubusercontent.com/957542/71460546-0e2d2b00-278b-11ea-85b1-519e04925cbb.png)

Tks!

**Comment by samtstern** [comment]
@mcostabr sorry about the slow response!  Transfered this issue to the JS SDK where it belongs.

**Comment by rommelpe** [comment]
Thanks for reporting this issue, @mcostabr. Indeed, the issue only occurs in Edge (v81.0 on my end). I'll confirm this internally and keep you posted for any updates, thanks!

**Comment by mcostabr** [comment]
Thank you very much for the feedback, I am available to help if necessary.

**Comment by dwyfrequency** [comment]
Is this still an issue? It's referencing an issue with a much older version of edge.
