### ISSUE TITLE
FR: firestore externs for closure compiler

### ISSUE THREAD

**Issue by rubenlg** [firebase/firebase-js-sdk#252]
* Operating System version: N/A
  * Firebase SDK version: 4.6.0
  * Firebase Product: firestore

Please generate an -externs.js file for the firestore API, to be able to compile client code using that DB with the closure compiler.

**Comment by YsightTechie** [comment]
Any news on the status of the externs?  Thank you.  This is high priority for our work as we always use advanced compilation for our web apps.

**Comment by ericfode** [comment]
Please!

**Comment by pianostringquartet** [comment]
Any updates? I'm interested in this as well.

**Comment by gabrielsimoes** [comment]
I have created my own externs, I'm not sure if I did it correctly, but you can use: https://gist.github.com/gabrielsimoes/4b9607670043f8dbb02b70eae21f4168

I didn't submit a PR because it is not even as neat as the other documented externs.

**Comment by gabrielsimoes** [comment]
I think this can be closed as it was solved with commit #844.

**Comment by mikelehen** [comment]
Yes, I believe #844 addressed this. Thanks for the ping @gabrielsimoes
