### ISSUE TITLE
QuotaExceededError occured in Android Chrome 66

### ISSUE THREAD

**Issue by al002** [firebase/firebase-js-sdk#2522]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.2
  * Browser version: Chrome 79.0.3945.117
  * Firebase SDK version: 7.5.2
  * Firebase Product: performance

### [REQUIRED] Describe the problem
We use firebase performance product to report performance metrics of our websites.

But many `QuotaExceededError` reported to our Sentry platform.

This error mostly occured in Android Chrome 66.0.3359(some in Android Chrome 79.0.3945), and I found this Chrome bug https://stackoverflow.com/questions/50109435/indexeddb-write-to-database-fails-in-webview-66-0-3359-126

But I cannot reproduce this error in Chrome 66.0.3359, Android 7.1, Xiaomi Note 4X, don't know why.

#### Steps to reproduce:

I tried start Chrome use `Chrome --user-data-dir=tmp_dir`, `tmp_dir` is a small temp storage. and this error would occur.

![截屏2020-01-10上午10 34 17](https://user-images.githubusercontent.com/1555320/72121131-1db89080-3395-11ea-9eb5-41413450eacf.png)

So, maybe this is because @firebase/performance use indexedDB. 

#### Relevant Code:

I looked up source code, and found `getInitializationPromise` function call in `performance/src/services/initialization_service.ts` is not catched. when this running on buggy Android Chrome 66.0.3359, error would be occured.

Cannot catch this in outside, and should not use window.onunhandledrejection, because it is a library that we write, don't want control this global reject catch.

https://stackblitz.com/edit/firebase-issue-sandbox-jz4eva

What can I do to suppress or catch this error, thanks!

**Comment by LanderBeeuwsaert** [comment]
The quotaExceeded error is something we have on chrome 79 desktop windows and apple version as well for users now and then. I've not been able to contact people however to show their console.log yet. But we have the issue already quite some months.

**Comment by mmermerkaya** [comment]
Installations (which Performance depends on) is the library that uses IndexedDB, but I don't think we can do anything from the Installations side as this is a Chrome issue, and to implement an alternative storage method in the rare case of IndexedDB failing wouldn't be cost effective and would increase the library size unnecessarily.

**Comment by LanderBeeuwsaert** [comment]
@mmermerkaya 
do I understand correctly that everything except installations will continue working when this error occurs? So firestore, firebase, authentication, functions calling, ... will be ok?
So I can just try to 'absorb' the error in the application and this will not cause unexpected issues?

**Comment by al002** [comment]
@mmermerkaya I understand your concern.

For now, we cannot catch any async errors on the application side, and I think it is ok. If we do not need to care about those errors, because other functions still work? should we silence this kind of error in the library?

**Comment by alikn** [comment]
Performance sdk depends on the Installations. If Installations return an error, Performance will not be able to report Performance logs from that instance. Firebase sdks which do not depend on Installations should work fine.
