### ISSUE TITLE
Firebase service worker messaging error?

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#2527]
I have the following error in our error logging.
This is happening for a user running in the following environment:

![image](https://user-images.githubusercontent.com/1098243/72221775-02e54800-355e-11ea-95a8-659515d4c275.png)

We yesterday upgraded from firebase 7.6.1 to 7.6.2
Funny thing is that firestore and firebase read/writes are working correctly for that user if I look at the logging but it's in a part of the code when there is a HttpCallable. Then the error happens.
Could it have something to do with this:
![image](https://user-images.githubusercontent.com/1098243/72221883-fb726e80-355e-11ea-8d19-e09eb532c06d.png)

Error:

"Error: Uncaught (in promise): FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('https://www.acro-companion.com/firebase-cloud-messaging-push-scope') with script ('https://www.acro-companion.com/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).\nFirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('https://www.acro-companion.com/firebase-cloud-messaging-push-scope') with script ('https://www.acro-companion.com/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).\n    at https://www.acro-companion.com/main.e8cd9632f5ed6455b9fd.js:1:2117136\n    at l.invoke (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:7385)\n    at Object.onInvoke (https://www.acro-companion.com/main.e8cd9632f5ed6455b9fd.js:1:693884)\n    at l.invoke (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:7325)\n    at a.run (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:2797)\n    at https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:13722\n    at l.invokeTask (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:8003)\n    at Object.onInvokeTask (https://www.acro-companion.com/main.e8cd9632f5ed6455b9fd.js:1:693802)\n    at l.invokeTask (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:7924)\n    at a.runTask (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:3412)\n    at C (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:12957)\n    at https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:12061\n    at a (https://www.acro-companion.com/main.e8cd9632f5ed6455b9fd.js:1:2301038)\n    at l.invoke (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:7385)\n    at Object.onInvoke (https://www.acro-companion.com/main.e8cd9632f5ed6455b9fd.js:1:693884)\n    at l.invoke (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:7325)\n    at a.run (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:2797)\n    at https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:13722\n    at l.invokeTask (https://www.acro-companion.com/polyfills.463ff94e44500e6d0af9.js:1:8003)\n    at Object.onInvokeTask (https://www.acro-companion.com/main.e8cd9632f5ed6455b9fd.js:1:693802)"

**Comment by LanderBeeuwsaert** [comment]
Testing the same code myself now, I get:
![image](https://user-images.githubusercontent.com/1098243/72222328-bac92400-3563-11ea-942a-700325e90947.png)

Reverting to 7.6.1 solves the issue.

**Comment by rommelpe** [comment]
Sorry to hear about your issues, @LanderBeeuwsaert. Atm, I'm quite not sure if they are related.
Could you let us know what steps you did to reproduce it? Also, it would be a necessary starting point to have a minimal runnable code so we can easily replicate the issue. Thanks!

**Comment by LanderBeeuwsaert** [comment]
Hello, apologies, our timeschedule is really busy at the moment (we help organize competitions and the season is gearing up) so making a repro will not be possible to spend the time.
It was just in the first await functions().httpsCallable('somefunction')(input);
Nothing more than that that I can see for the moment.
But after downgrading it works. So if you prefer I can close.

**Comment by rommelpe** [comment]
Thanks for the inputs. As much as I wanted to help you out here, I need to reproduce it first on my end to be able to move forward. If you decided to work on the [repro](https://stackoverflow.com/help/minimal-reproducible-example) (including the detailed steps), then we are happy to look into further.

You can always reply to this thread to reopen the issue so we can pick up our conversation where we left off.
