### ISSUE TITLE
Auth: updateCurrentUser() not triggering onAuthStateChanged

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-js-sdk#2529]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 19.10
  * Browser version: Chrome 81.0.4021.2
  * Firebase SDK version: 7.6.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

`updateCurrentUser()` call does not trigger `onAuthStateChanged`, unlike specified in [documentation](https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#update-current-user).

#### Steps to reproduce:

1. create new auth user and sign in with `createUserWithEmailAndPassword` (new user `emailVerified` is false)
1. send a verification email
1. in the email, click on the verification link (then `emailVerified` is true)
1. refresh current auth user with `currentAuthUser.reload()` to ensure current auth user emailVerified is true
1. call `updateCurrentUser(currentAuthUser)`
1. `onAuthStateChanged` is never triggered in this whole process (except after first login step). You have to sign out then sign in again (impossible if password form page was refreshed) to trigger it.

Note that `onIdTokenChanged` _is_ triggered after the `updateCurrentUser` call.

My app actions depend on the `emailVerified` status of the current auth user. Neither `onAuthStateChanged` nor `onIdTokenChanged` are triggered directly after the verification email link is clicked. Is it a bug or a feature? :wink:

**Comment by rommelpe** [comment]
Thanks for providing a detailed steps to reproduce this, @laurentpayot. I'm a bit curious though on how/where you invoke `updateCurrentUser`. Can you share a sample reproducible code of your app so we can easily replicate the issue?

**Comment by bojeil-google** [comment]
Calling `updateCurrentUser` with the same current user will not trigger `onAuthStateChanged` again. `onAuthStateChanged` is only triggered when a user signs out or a new user signs in.

**Comment by laurentpayot** [comment]
@rommelpe my app is is a bit complex as Firebase is run [in a web worker](https://github.com/firebase/firebase-js-sdk/issues/983) to unload the main thread.
In my worker I have this TypeScript API (simplified) that I'm calling via messages:

```typescript
// worker.ts

importScripts('./index.js')
declare const firebaseBundle: typeof import('./index')
const { auth } = firebaseBundle

let currentAuthUser: AuthUser|null = null

const API = {

    auth: {

        start(lang: string) {
            auth.languageCode = lang
            auth.onAuthStateChanged(async (authUser) => {
                currentAuthUser = authUser

                // …doing stuff and finally sending a message with the auth user back to the main thread…
            })
        },

        // …

        async reloadUser() {
            await currentAuthUser?.reload().catch(sendAuthError)
            // triggering onIdTokenChanged, but not onAuthStateChanged
            auth.updateCurrentUser(currentAuthUser).catch(sendAuthError)
        },
    }

    // …

}
```

@bojeil-google 

> onAuthStateChanged is only triggered when a user signs out or a new user signs in.

So is it not really the auth _state_ (with the state being the user _attributes_) but rather the reference to the user object that is watched by `onAuthStateChanged`? If so naming it `onNewAuthUser` or something like that would have been less confusing…

**Comment by laurentpayot** [comment]
To sum it up I wish I had a `reloadUser` function that would refresh the current auth user with all its attributes refreshed, whatever their depth. Is it impossible to do in Firebase without a new sign in?

I also opened #2536 for the same kind of issue but on the server side.

**Comment by laurentpayot** [comment]
I also opened #2536 for the same kind of issue but on the server side. For the email to be "really" verified, it also seems that a new sign in is required after a user signs up and confirm its email. This is a pain in my password sign up process :confused:

**Comment by rommelpe** [comment]
Sorry to hear about your issues, @laurentpayot. It's the current design that  the user has to sign in again, in order to refresh the token. Check out [this post](https://stackoverflow.com/questions/47117399/is-login-needed-after-user-email-verification-on-firebase?answertab=votes#tab-top) as to why verification process should be separated from sign in.

If you haven't checked [this](https://stackoverflow.com/questions/47243702/firebase-token-email-verified-going-weird?answertab=votes#tab-top) yet, you may want to try `firebase.auth().currentUser.getIdToken(true)` to force refresh to update the token claim.

**Comment by laurentpayot** [comment]
I tried `firebase.auth().currentUser.getIdToken(true)` instead of `updateCurrentUser()` and it was exactly what I needed to update the token!

Thank you so much @rommelpe :+1:
