### ISSUE TITLE
Expected behavior when requiring submodules

### ISSUE THREAD

**Issue by qwales1** [firebase/firebase-js-sdk#253]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04
  * Firebase SDK version: 4.1.4
  * Firebase Product: database

### [REQUIRED] Describe the problem

Are the submodules expected to follow semver of the overall package? I just assumed they did and I usually import them separately to reduce bundle size, but ran into the issue below.
Apologies if this is already addressed somewhere and I missed it.

In firebase pre - 4.1.4 requiring `firebase/database` returned a function. 
Starting in firebase 4.1.4 it returns an object

#### Steps to reproduce:

Using firebase 4.1.3

```
const firebase = require('firebase/app');
const database = require('firebase/database');
const app = firebase.initializeApp({...});
const db = database(app);
//No Errors
```

Using firebase 4.1.4

```
const firebase = require('firebase/app');
const database = require('firebase/database');
const app = firebase.initializeApp({...});
const db = database(app);
//Errors - database is not a function
```
#### Relevant Code:
`git clone https://github.com/qwales1/firebase-database-change-repro.git`
`cd firebase-database-change-repro`
`npm i`
`npm test`

**Comment by jdbence** [comment]
It looks like [v4.1.4](https://github.com/firebase/firebase-js-sdk/releases/tag/v4.1.4) had a refactor of the Database class. It also might be helpful to show some working examples and reference the [Database.ts](https://github.com/firebase/firebase-js-sdk/blob/d90beabb584d34236980462e783b6f69e98a5c11/packages/database/src/api/Database.ts#L50) constructor.

### Using `firebase 4.12.0`
```JS
// yarn add firebase

const config = require('./firebase.json');
const firebase = require('firebase/app');
require("firebase/database");

this.app = firebase.initializeApp(config);
this.db = this.app.database();
```
### Using `@firebase/app 0.1.10` and `@firebase/database 0.2.1`
```JS
// yarn add @firebase/app @firebase/database

const config = require('./firebase.json');
const firebase = require('@firebase/app').default;
require('@firebase/database');

this.app = firebase.initializeApp(config);
this.db = this.app.database();
```

**Comment by jshcrowthe** [comment]
@qwales1 the behavior that you are describing is leveraging an undocumented entrypoint into the database SDK that isn't consistent w/ the rest of our SDK.

i.e.
```
const database = require('firebase/database'); // <-- this
```

This will be removed in a future release so I'd recommend going with the first solutions that @jdbence proposed. The second is directly leveraging the scoped packages which are still technically semver major 0 and are subject to breaking changes as we need.
