### ISSUE TITLE
Server side rendering: ReferenceError: IDBIndex is not defined 

### ISSUE THREAD

**Issue by zd-dalibor** [firebase/firebase-js-sdk#2530]
I'm trying to make the serverside rendering bundle with webpack. And my application using messages sdk:

```typescript
import * as firebase from 'firebase/app';
import 'firebase/messaging';
```

My bundle must be self-contained (do not load node module at runtime - everything should be inside bundle).

I'm trying to solve my problem with suggestions from this #1797 using something like this in webconfg to force loading node compatible scripts:

```
resolve: {
    alias: {
      ['firebase/app']: path.resolve(__dirname, '../node_modules/firebase/app/dist/index.cjs.js'),
      ['firebase/messaging']: path.resolve(__dirname, '../node_modules/firebase/messaging/dist/index.cjs.js'),
      ['@firebase/app']: path.resolve(__dirname, '../node_modules/@firebase/app/dist/index.node.cjs.js'),
      ['@firebase/messaging']: path.resolve(__dirname, '../node_modules/@firebase/messaging/dist/index.cjs.js'),
      ['@firebase/util']: path.resolve(__dirname, '../node_modules/@firebase/util/dist/index.node.cjs.js'),
      ['@firebase/component']: path.resolve(__dirname, '../node_modules/@firebase/component/dist/index.cjs.js'),
      ['@firebase/logger']: path.resolve(__dirname, '../node_modules/@firebase/logger/dist/index.cjs.js'),
      ['@firebase/installations']: path.resolve(__dirname, '../node_modules/@firebase/installations/dist/index.cjs.js'),
    },
    extensions: ['.js', '.ts']
  }
```

but the problem is in this module `@firebase/installations`, both browser and node version have reference on `idb` module (https://www.npmjs.com/package/idb) with code:

```javascript
proxyRequestMethods(Index, '_index', IDBIndex, [
  'get',
  'getKey',
  'getAll',
  'getAllKeys',
  'count'
]);
```

So I do not know how to get rid of this.

I em using firebase 7.6.2 version.

**Comment by hsubox76** [comment]
Messaging actually is not supported in Node (see [supported environments table](https://firebase.google.com/support/guides/environments_js-sdk)). Can you set up a different entry point for your server rendering bundle that doesn't import it?

**Comment by zd-dalibor** [comment]
@hsubox76 Ok, I solve this problem with dynamic imports:

```typescript
import('firebase/messaging').then(() => { ... });
```

**Comment by jamesdaniels** [comment]
FYI looks like this is the same as #6042. One major issue with the work around, dynamic imports break tree-shaking. Which is why it's not something we should be advising.
