### ISSUE TITLE
Console not showing added Data

### ISSUE THREAD

**Issue by ankitjt** [firebase/firebase-js-sdk#2540]
### [REQUIRED] Describe your environment

  * Operating System version: ___Windows 10__
  * Browser version: __Chrome 79
  * Firebase SDK version: __7.6.2
  * Firebase Product: Database

### [REQUIRED] Describe the problem
I am unable to see data added in my console, though when I export the JSON it shows the added data.

#### Relevant Code:
  let database = firebase.database()
    function writeUserData(userId, name, email, imageUrl) {
        firebase.database().ref('users/' + userId).set({
          username: name,
          email: email,
          profile_picture : imageUrl
        });
      }
      writeUserData(12345,"Jhon Doe", "xyz@abc.com", "https://dummyimage.com")

**Comment by rommelpe** [comment]
Thanks for reporting, @ankitjt. It might be an isolated case as RTDB is currently [healthy](https://status.firebase.google.com/). Have you tried accessing the Firebase console in **incognito** mode? You may also do the following:

- Verify if there are any other program that might be blocking your connection such as antivirus or firewall.
- Log out of your dashboard (ensure that there's no multiple account logged-in).
- Try accessing the Firebase console using a different device, connection or browser.
- Clear your browser cache.
- Disable all plugins/extensions/add-ons.
- Restart the browser and login again.

If the issue persists, just let me know and kindly provide the following information so I can discuss this with the engineers:

- Video showing how the issue occurs
- HAR file of your browser when having this issue
- Any additional information that might be helpful for us to narrow down the issue

**Comment by ankitjt** [comment]
@rommelpe it started showing the data in the console on its own after a while without me doing anything.
Thanks for the immediate response :)
