### ISSUE TITLE
documentation says CollectionReference#add should return a DocumentReference promise

### ISSUE THREAD

**Issue by ryanmtaylor** [firebase/firebase-js-sdk#2543]
### [REQUIRED] Describe your environment

  * Operating System version: n/a
  * Browser version: n/a
  * Firebase SDK version: 7.6.2
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Using `CollectionReference#add`, the `.add()` command, returns a promise containing a WriteResult, but the documentation says it should be a DocumentReference.
- https://firebase.google.com/docs/reference/node/firebase.firestore.CollectionReference.html#add
- https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference.html#add
- https://googleapis.dev/nodejs/firestore/latest/CollectionReference.html#add

```javascript
const admin = require('firebase-admin');
admin.intializeApp({ ... });
const db = admin.firestore();
db.collection('things').add({ a: 1 }).then((ref) => {
  // "ref" is of type WriteResult
  console.log(ref.id) // is undefined
})
```

**Update**: I do not see see this issue in the web version of the sdk, just in the admin `@google-cloud/firestore` thing.

Probably has something to do with this: https://github.com/googleapis/nodejs-firestore/blob/94ddc897400cafe5a1ee16f3ad0d285411bdd0b2/dev/test/typescript.ts#L158

**Comment by thebrianchen** [comment]
@ryanmtaylor Thanks for writing in! 

Having `CollectionReference.add()` return a `WriteResult` is strange, since we currently have a [test](https://github.com/googleapis/nodejs-firestore/blob/94ddc897400cafe5a1ee16f3ad0d285411bdd0b2/dev/system-test/firestore.ts#L195) in the admin sdk that checks to make sure we receive a `DocumentReference`. Could you provide a minimal repro that shows when a `WriteResult` is returned instead? Also, what version of the admin sdk are you seeing this behavior on? Thanks!

**Comment by ryanmtaylor** [comment]
The test is wrong as per the link I included at the end – https://github.com/googleapis/nodejs-firestore/blob/94ddc897400cafe5a1ee16f3ad0d285411bdd0b2/dev/test/typescript.ts#L158

As you can see the actual code in the test is actually verifying a `WriteResult`, although it says it's looking for a `DocumentReference` in the description of the test

**Comment by thebrianchen** [comment]
The test you linked to is verifying that all methods on `DocumentReference` have the correct typings. `create()`, `set()`, and other methods on `DocumentReference` have `WriteResult` as their return type. However, `CollectionReference.add()` has a `DocumentReference` return type, and its corresponding typescript test can be found [here](https://github.com/googleapis/nodejs-firestore/blob/94ddc897400cafe5a1ee16f3ad0d285411bdd0b2/dev/test/typescript.ts#L319).
