### ISSUE TITLE
Batch writes blocks rendering

### ISSUE THREAD

**Issue by antoniozzo** [firebase/firebase-js-sdk#2545]
### Describe your environment

  * Operating System version: macOS 10.14.6
  * Browser version: Chrome 79.0.3945.117
  * Firebase SDK version: 7.6.2
  * Firebase Product: firestore

### Describe the problem

When I'm updating a few hundred documents with batches, rendering is blocked while firestore is sending the changed documents back through the WebChannel. Having `firebase.firestore.setLogLevel("debug")` on I can see that I get a bunch of messages, one for each document change: `[Connection]: WebChannel received: {"documentChange": ...`. While these messages are received the rendering of my application is blocked.

Using `snapshot.docChanges()` I have already got the documents and rendered the changes, but the lag happens after that, while the server is responding with pending writes.

**Comment by thebrianchen** [comment]
@antoniozzo Thanks for filing an issue! We're currently working on improving the performance of Firestore. While Firestore is processing the documents, the rendering of your application will unfortunately be blocked. However, if you update your documents in smaller batches, there will be gaps in between batches for you to render, even though the total amount of processing time required by Firestore is still the same.

Another option is to offload Firestore onto a [web worker](https://davidea.st/articles/firebase-bundle-size), which will free up your main thread while Firestore is processing documents received over WebChannel. The caveat is that persistence currently does not work when Firestore is run on web workers (though we currently have an experimental [build](https://github.com/firebase/firebase-js-sdk/issues/983) trying to test that out).
