### ISSUE TITLE
Firestore Document update failed to update one field

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-js-sdk#2547]
Hi, I have witnessed a major bug with Firestore where when you update a document, one field failed to get updated while succeeding in other fields. There is no way I can reproduce it again, and there no debugging logs from Firestore that I have to give you, but the update method for document failed to update one field while updating the other two. in the below example once.

Is it possible that update for document fails for one field but not the others? Does the update gets written all together atomically? All or nothing?

I saw it happen in Firebase database console, after I called cloud function, it updated 2nd and 3rd rows, but not 1st row of the document (see below example). I am troubled by it, and without changing anything I re-ran the function, and all three field got updated just fine. But it is deeply troubling that sometimes firebase update would not update all fields.

I have stared at the code and really the dictionary key from the below example should have been updated, but it didn't. Codes around this "await" line got called meaning this code did get executed and updated two fields, and I know this for SURE. After staring at my code, there is no way that I could have caused this. Is it possible that Firestore update to a document field fails to write while succeeding in other fields in rare cases? My dictionaryObject is 2 dictionary objects inside a dictionary.

Let me know if this is ever possible.

```
await documentSnapShot.ref.update({
            dictionary: dictionaryObject,
            [`outerDictionary.${innerDictionaryKeyName}.fieldName`] : object1,
            [`outerDictionary.${innerDictionaryKeyName}.fieldName2`] : object1,
        }
```

**Comment by thebrianchen** [comment]
@coolcool1994 Our backend performs updates atomically, so it's very unlikely that an update for a document succeeded in one intended field but not another. If you run into such an error and have logging enabled, please share the logs with us!

**Comment by coolcool1994** [comment]
I did log things from console.log('texts'), but I did more things afterwards now and it is hard to find. I am assured that things like this won't happen often since update happens atomically. But I have double, triple, and probably checked like 10 times, why it could have happen and the final answer is Firestore failed to update append an object to that dictionaryObject which is one field while succeeding in updating the other two. I am sure of it. But I cannot reproduce it again even when I went through the exact steps I did to cause it. I recently realized that I deleted the highest level collections user and chatRooms from Firebase console to start over again. Deleting those and saving onto them may have caused this issue perhaps? I do not know.

As of now, I don't think it is necessary for me to provide the project code (very valuable). If this EVER happens again, I will take the required steps and send you the logs next time. So for the future reference if this happens again, what exactly is the log that you need from me? Do you mean the log that I print out from Cloud Function : console.log('text')??? I don't see how this logging would be helpful. If there is other log, I am not aware of it - I don't know how to turn it on either. Let me know how to log things so I can share you the details in the future when it happens again - I will keep an eye and def report everything!

**Comment by thebrianchen** [comment]
You can enable debug logging here:
https://firebase.google.com/docs/reference/js/firebase.firestore.html#setloglevel

These logs will allow us to examine Firestore's behavior and see what's happening internally.
