### ISSUE TITLE
Authentication Broken When Called from Web Worker

### ISSUE THREAD

**Issue by milky2028** [firebase/firebase-js-sdk#2552]
* Operating System version: Windows 10 1909, MacOS 13.1, Ubuntu 16.04
  * Browser version: Chrome 79
  * Firebase SDK version: 7.2.3
  * Firebase Product: auth, firestore

I'm getting a "permission denied" error when trying to get a document from a web worker when the document requires authentication. Auth is happening outside the worker, on the main thread. The request succeeds as normal when security rules are relaxed not to require authentication.

I'm somewhat under the impression that this should work as normal since auth information is stored in IndexedDB, but this might not be the case? Is there a way to manually supply a token to the firestore request?

**Comment by milky2028** [comment]
I think I'll actually just use [this doc](https://firebase.google.com/docs/auth/web/service-worker-sessions) to try to proxy all calls. If anyone out there looked at this, thanks for your help!

**Comment by milky2028** [comment]
If anyone ever finds this and has the same issue, what I actually ended up doing was still doing authentication on the main thread (since signInWithPopup requires access to Window), then passing that UserAuthentication object to the worker and calling [signInWithCredential](https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#signinwithcredential) inside the worker.

Is this the best way to do this? Dunno. But it works.

**Comment by bojeil-google** [comment]
Auth state should be visible within a web / service worker. I tested out myself recently: https://github.com/FirebaseExtended/firebase-auth-service-worker-sessions/

User signs in from a browser. The `currentUser` is accessible from the service worker.

**Comment by milky2028** [comment]
I thought this would be the case as well, but it wasn't working for me. I'm using a plain ol' web worker, not a service worker. This might be the difference, but I wouldn't think that this is the case since I know auth credentials are stored in IndexedDB, which a web worker also has access to.

Since most of the Firebase libraries are huge, I'm dynamically importing all of them. Since auth isn't used in the worker, it's never imported into the worker. Do you think that because Auth was never initialized, this could be the reason that auth requests weren't working?

**Comment by bojeil-google** [comment]
It has to be imported in the worker and initialized.
