### ISSUE TITLE
14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by SeanDez** [firebase/firebase-js-sdk#2556]
### [REQUIRED] Describe your environment

  * Operating System version:  Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  * Browser version: Google Chrome 79.0.3945.88 (Official Build) (64-bit)
  * Firebase SDK version: "firebase": "^7.5.0"
  * Firebase Product: core, admin, testing, firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

A test db call fails instantly with the connection error in this issue's title. 

#### Steps to reproduce:

1. Clone this repo https://github.com/SeanDez/buyUsedShopifyServer   
2. Install dependencies
3. Run `nvm use 8` to switch to node version 8 (I am on 8.17.0)
3. Run `git checkout StoreFrontToken` to get to the most up to date branch with the issue. 
4. run `jest --watch`
5. terminal should show the issue coming from the test file in functions/src/classes/_tests_/FirestoreConnection.test.ts

#### Relevant Code:

```
// FirestoreConnection.ts
import {DocumentTarget, RecordTypes, WhereDefinition} from "../../../shared";

import {firestore} from "firebase-admin";

export default class FirestoreConnection {
  protected shopDomain: string;
  protected database: firestore.Firestore;
  
  constructor(shopDomain: string, database: firestore.Firestore) {
    this.shopDomain = shopDomain;
    this.database = database;
  }
  
  protected async addDocument(collectionName: string, documentData: object): Promise<firestore.DocumentSnapshot|null> {
    try {
      const newlyAddedDocument = await this.database
        .collection(collectionName)
        .add(documentData);
    
      return await newlyAddedDocument.get();
    }
    catch (e) {
      console.log(e, `=====error=====`);
      return null;
    }
  }
  
  public async createNew(type: RecordTypes, documentData: object): Promise<firestore.DocumentSnapshot|null> {
    // can be void/empty
    return await this.addDocument("testArea", documentData);
  }
}

// FirestoreConnection.test.ts
import * as firebaseTesting from "@firebase/testing";
import {RecordTypes} from "../../../../shared";

import FirestoreConnection from "../FirestoreConnection";
import {getDatabase, setDatabase} from "../../../../shared/database";

/* * * * * * * * * * * * * * * * * * * * *
                  Setup
* * * * * * * * * * * * * * * * * * * * */
const createTestDatabase = (credentials): any => {
  return firebaseTesting
    .initializeTestApp({
      projectId: 'testProject',
      auth: credentials
    })
    .firestore();
};

const nullAllApps = firebaseTesting
  .apps().map(app => app.delete());

const db = new FirestoreConnection('testShopDomain', createTestDatabase(null));

/* * * * * * * * * * * * * * * * * * * * *
                  Tests
* * * * * * * * * * * * * * * * * * * * */
test("creates new record", async () => {
  const addedDocument = await db
    .createNew(RecordTypes.globalRule, {
      storeId : "dummyStoreId"
      , globalPercent : 40
    });

  expect(addedDocument).toEqual({
    storeId : "dummyStoreId"
    , globalPercent : 40
    , badProp : 0
  });
}, 100000);
```

## The Expected Error

```
// in terminal
FAIL  functions/src/classes/__tests__/FirestoreConnection.test.ts (114.693s)
  ✕ creates new record (100026ms)
  ○ skipped 

  ● creates new record

    : Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error:

      51 | 
      52 | 
    > 53 | test("creates new record", async () => {
         | ^
      54 |   const addedDocument = await db
      55 |     .createNew(RecordTypes.globalRule, {
      56 |       storeId : "dummyStoreId"

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (functions/src/classes/__tests__/FirestoreConnection.test.ts:53:1)

  ● creates new record

    14 UNAVAILABLE: failed to connect to all addresses

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 skipped, 2 total

**Comment by SeanDez** [comment]
`FirestoreConnection.test.ts` is there but you have to switch to branch StoreFrontToken. Here is a link to the repo/file: https://github.com/SeanDez/buyUsedShopifyServer/blob/StoreFrontToken/functions/src/classes/__tests__/FirestoreConnection.test.ts

**Comment by rommelpe** [comment]
Thanks for reaching out, @SeanDez. I was able to reproduce the issue but I'm not sure if it's an intended behavior. 

I tried running our [quickstart](https://github.com/firebase/quickstart-nodejs/tree/master/firestore-emulator/javascript-quickstart) guide, it successfully creates connection from the db and be able to save docs. Using Firebase CLI command: `firebase emulators:exec --only firestore 'npm test'`
![image](https://user-images.githubusercontent.com/56452310/72824465-40f61080-3cb0-11ea-8f1b-0ae3726db14d.png)


Using `npm test`, I got the same result like on your project.
![image](https://user-images.githubusercontent.com/56452310/72825046-4f90f780-3cb1-11ea-8a72-57ab44fcd54d.png)

I'll confirm this to our engineers to give us some insight. I'll keep you posted once I've heard from them.

**Comment by SeanDez** [comment]
Thank you @rommelpe . I think I can explain the difference:

In the first test suite you are testing firebase security rules which is in firebase.rules in the project root. 

In the 2nd test, you are testing the class at `functions/src/classes/FirestoreConnection.ts` using the testing file one level deeper in `__tests__` by the same prefix. These are not rules tests but database CRUD operations tests. In the current example that fails, the test attempts to do a create record.

Hopefully the other devs can see what the issue is exactly. Looks like I low level dependency issue; I've been struggling to find information online that pertains to it.

**Comment by SeanDez** [comment]
I've found that the initial error may have been caused because the server/emulator was not found by gRPC, I ran `firebase serve --only functions,firestore` to ensure the firestore service was also emulated locally. Terminal showed emulators running on different ports for both services. 

Rerunning `jest --watch` now produces a slightly different error:

```
 2 UNKNOWN:

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

```

**Comment by thebrianchen** [comment]
@SeanDez 

You are correct that the initial error you were getting was because you did not point your tests to the firestore emulator, which you have to do either manually in your app, or setting `FIRESTORE_EMULATOR_HOST=localhost:8080` in your environment when running the tests.

If you enable logging in the the admin SDK with `firestore.setLogFunction()` and run your tests, you can see the underlying error ([additional context](https://github.com/firebase/firebase-tools/issues/1147)):
```
[2020-01-22T21:39:04.453Z] Jan 22, 2020 1:39:04 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: Invalid app id
```

According to the [documentation](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects), it appears that your projectId `testProject` is invalid. Changing the projectId to `testproject` with all lowercase letters allows the tests to run.
