### ISSUE TITLE
HTTP REST API to generate custom token from id_token

### ISSUE THREAD

**Issue by Suhail** [firebase/firebase-js-sdk#2557]
Hi there, I am trying to generate a custom token via an id_token.

Today, I have working code like this:

```ts
/**
 * Generates a custom token we can use to sign in given an id_token
 * @param {string} id_token
 * @returns {string} custom token
 */
function get_custom_token(id_token: string): Promise<string> {
  return request.get({
    url: `https://us-central1-${firebase_config['projectId']}.cloudfunctions.net/create_custom_token?id_token=${id_token}`,
    json: true,
  });
}
```

I'd like to cut the latency down of this request and I am hoping there's a closer region than us-central-1 by chance. 

Questions:

1. Where are the HTTP APIs for this documented? I've looked everywhere via Google but couldn't find anything.
2. Is there a closer region I can use?

**Comment by mbleigh** [comment]
Hi Suhail, you can deploy HTTP functions to any of the [available Cloud Functions locations](https://firebase.google.com/docs/functions/locations). If you're deploying using the Firebase CLI, you can do this like so:

```js
functions.region('europe-west2').https.onRequest(...);
```

**Comment by Suhail** [comment]
Oh, interesting, so there's no us-west region? Bummer!

A us-west zone I suspect would help reduce login latency fwiw. That's really important for our application to the point where we'd need to replace the auth mechanism perhaps.

**Comment by suryacaprice** [comment]
> Hi there, I am trying to generate a custom token via an id_token.
> 
> Today, I have working code like this:
> 
> ```ts
> /**
>  * Generates a custom token we can use to sign in given an id_token
>  * @param {string} id_token
>  * @returns {string} custom token
>  */
> function get_custom_token(id_token: string): Promise<string> {
>   return request.get({
>     url: `https://us-central1-${firebase_config['projectId']}.cloudfunctions.net/create_custom_token?id_token=${id_token}`,
>     json: true,
>   });
> }
> ```
> 
> I'd like to cut the latency down of this request and I am hoping there's a closer region than us-central-1 by chance.
> 
> Questions:
> 
> 1. Where are the HTTP APIs for this documented? I've looked everywhere via Google but couldn't find anything.
> 2. Is there a closer region I can use?

I am having a similar issue . Is there any solution or documentation to it

**Comment by rommelpe** [comment]
While setting HTTP functions in `us-west` isn't yet available, we'll treat this as a feature request and keep this open. I'll be reaching out internally to upvote the existing request as well. Thanks!

**Comment by Suhail** [comment]
Cool, feel free to change the title to something more useful.

**Comment by avolkovi** [comment]
Folks, I'm going to close this out since there's nothing we can do in the SDK to help here.  You may be interested in looking into Cloud Run, which is available in the us-west1 region (https://cloud.google.com/run/docs/locations).
