### ISSUE TITLE
Uncaught error in Promise when enabling persistance on a second tab, even if catching errors

### ISSUE THREAD

**Issue by Maistho** [firebase/firebase-js-sdk#256]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.6.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When enabling firestore persistance on a second tab there is an error message in the console, regarding an uncaught Promise, even when catching the Promise returned by `.enablePersistance()`.
#### Steps to reproduce:
```html
<script src="https://www.gstatic.com/firebasejs/4.6.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.6.0/firebase-firestore.js"></script>

<script>
firebase.initializeApp({
    // config goes here
})

firebase.firestore().enablePersistence()
    .then(res => console.log('Success'))
    .catch(err => console.warn('Error'))

// Will still get an Uncaught error in console
</script>
```
#### Relevant Code:
http://jsbin.com/mahifukeqe/1/edit?js,console

**Comment by mikelehen** [comment]
Thanks for the bug report. This should not be happening, but I think it's a result of us creating a failed promise in response to the failure, but not immediately returning it (and so a catch handler can't be synchronously attached).

https://github.com/firebase/firebase-js-sdk/blob/9f356b6e9ecdf15a7eb16ca554c0c595b7ae8ccd/packages/firestore/src/local/simple_db.ts#L128

We perhaps should add a dummy .catch() handler here to transactionFnResult, but it's a bit ugly.  

I'm leaving this open for now (I assume it's not super high-priority), but we'll address this in the future.  Thanks!

**Comment by schmidt-sebastian** [comment]
This has been fixed as part of https://github.com/firebase/firebase-js-sdk/pull/823

The original implementation created two rejected Promises (one in runTransaction, and one transaction.onerror), only the latter of which was returned to the user. With the PR above, we no longer reject the Promise in `runTransaction`.
