### ISSUE TITLE
[Firestore] TypeError: firebase.INTERNAL.registerComponent is not a function

### ISSUE THREAD

**Issue by christian-miljkovic** [firebase/firebase-js-sdk#2570]
### Describe your environment

  * Operating System version: _____
  * Firebase SDK version: 7.12.0
  * Firebase Product: Firestore
  * Node.js version: 12.5.0
  * NPM version: 6.10.2

#### Steps to reproduce:

I am running npm start which is building my react-firebase application, which compiles fine but when I look at my app on localhost I receive the error [here](https://i.stack.imgur.com/CE0Ys.png)

#### What I've Tried to Do

- I tried to follow suggestions in this Github post [#722](https://github.com/firebase/firebase-admin-node/issues/722).
- I noticed that by going to node_modules/@firebase/firestore/dist/index.cjs.js:27457:21 and changing firebase.INTERNAL.registerComponent to firebase.INTERNAL.registerComponent this changed the error to TypeError: instance.registerVersion is not a function which makes me believe that there must be some issue with my version of firebase.
- I have tried to revert firebase to version 7.6.0 since there was a recent update made on 01/09/2020 to no avail.
- I tried doing all the installing of dependencies in a virtual environment just in case, for some reason, there were some discrepancies between projects
- I have posted this issue on Stackoverflow [here](https://stackoverflow.com/questions/59742766/typeerror-firebase-internal-registercomponent-is-not-a-function-at-configurefor)

#### First Error Location:

```
function configureForFirebase(firebase) {
    firebase.INTERNAL.registerComponent(new component.Component('firestore', function (container) {
        var app = container.getProvider('app').getImmediate();
        return new Firestore(app, container.getProvider('auth-internal'));
    }, "PUBLIC" /* PUBLIC */).setServiceProps(shallowCopy(firestoreNamespace)));
}
```
Second Error location:

```
function registerFirestore(instance) {
    configureForFirebase(instance);
    instance.registerVersion(name, version);
}
```

**Comment by schmidt-sebastian** [comment]
This seems to be an issue with the JS SDK. I transferred your issue.

**Comment by hsubox76** [comment]
Can you tell me more about your project?  Is `react-firebase` a specific tool or template or do you just mean you're using React and Firebase?  Are you also using Firebase functions and/or `firebase-admin` in the same project?  What does your `package.json` look like, and how are you importing/requiring Firebase?

If possible, can you put together a minimal repro (the smallest amount of code that causes the same error) and share it (you can put it up as a github repo)?

**Comment by christian-miljkovic** [comment]
I was able to resolve the issue by installing dependencies using yarn instead of npm - then using node v10.16.2

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know you are now unblocked. I will close this issue for now.
