### ISSUE TITLE
Firestore: Multiple orderBy not sorting result

### ISSUE THREAD

**Issue by ArslanBouzid** [firebase/firebase-js-sdk#2577]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 7.7.0

#### Steps to reproduce:
Using 2 successive orderBy followed by a startAt returns result sorted in the wrong direction. (asc instead of desc)
#### Relevant Code:

```javascript
  let result = await db    // db = firebase.firestore()
    .collection('/orders')
    .where('userId', '==', userId) // userId = 'zHJgWUFL54deq4a...'
    .orderBy('orderId')
    .orderBy('co', 'desc')
    .startAt(filter)      // filter = '2020-01-YND'
    .get()
```

**Orders collection**: 

```json
// Item 1
{
  "co": 0,
  "userId": "zHJgWUFL54deq4a...",
  "orderId": "2020-01-YNDKALCK"
}

// Item 2
{
  "co": 1,
  "userId": "zHJgWUFL54deq4a...",
  "orderId": "2020-01-YNDSCSAD"
}
```

- Composite indexes created: 
```
orders   	userId Ascending orderId Ascending co Descending	Collection 		Enabled
```  
<br/>

**RESULT** : result is not sorted (descending) by **co**.

```
// Item 1
{
  "co": 0,
  "userId": "zHJgWUFL54deq4a...",
  "orderId": "2020-01-YNDKALCK"
}

// Item 2
{
  "co": 1,
  "userId": "zHJgWUFL54deq4a...",
  "orderId": "2020-01-YNDSCSAD"
}
```
Instead of Item 2 first then Item 1

Is this a known issue ?

Thank you

**Comment by rommelpe** [comment]
Thanks for reporting, @ArslanBouzid. I was able to get the same behavior.

![image](https://user-images.githubusercontent.com/56452310/73272820-f4fe1b00-421d-11ea-8ad0-b07f8461118c.png)

It seems that it's an intended behavior when having multiple `orderBy`s. It'll be sorted from the first declared order by, in your case, it's `orderId` then `co` will be ordered within.

As mentioned [here](https://firebase.google.com/docs/firestore/query-data/order-limit-data#order_and_limit_data):

> You can also order by multiple fields. For example, if you wanted to order by state, and within each state order by population in descending order:
![image](https://user-images.githubusercontent.com/56452310/73273756-730ef180-421f-11ea-8f94-129bb4f7fdc2.png)

**Comment by ArslanBouzid** [comment]
The problem with switching orderBy is that I get no result... I've already created the composite index.
**filter** is used to "search" orderId (search text, not full-text searching since it's not supported).

So these 2 queries return [] :
```
// changed orderBy order
 let result = await db    // db = firebase.firestore()
    .collection('/orders')
    .where('userId', '==', userId) // userId = 'zHJgWUFL54deq4a...'
    .orderBy('co', 'desc')
    .orderBy('orderId')
    .startAt(filter)      // filter = '2020-01-YND'
    .get()

and: 

// added endAt
 let result = await db    // db = firebase.firestore()
    .collection('/orders')
    .where('userId', '==', userId) // userId = 'zHJgWUFL54deq4a...'
    .orderBy('co', 'desc')
    .orderBy('orderId')
    .startAt(filter)      // filter = '2020-01-YND'
    .endAt(filter + '\uf8ff')
    .get()
```

But, if I remove orderBy('co', 'desc'), I got results:
```
 let result = await db    // db = firebase.firestore()
    .collection('/orders')
    .where('userId', '==', userId) // userId = 'zHJgWUFL54deq4a...'
    .orderBy('orderId')
    .startAt(filter)      // filter = '2020-01-YND'
    .endAt(filter + '\uf8ff')
    .get()

returns:
// Item 1
{
  "co": 0,
  "userId": "zHJgWUFL54deq4a...",
  "orderId": "2020-01-YNDKALCK"
}

// Item 2
{
  "co": 1,
  "userId": "zHJgWUFL54deq4a...",
  "orderId": "2020-01-YNDSCSAD"
}
```

**Comment by wilhuff** [comment]
This is working as intended. The second orderBy is for tie-breaking only.  The primary sort will always be by the first orderBy.

Values you pass to startAt must correspond to the fields in your orderBy. If you reverse your orderBy fields and pass the same filter it won't match anything because none of your `co` values start with "2020-01-YND".

If you want to apply the filter you're doing your first order by field must be on `orderId`. If you want the primary ordering of the results to be on `co` you'll need to sort those locally after receiving the results.

**Comment by ArslanBouzid** [comment]
@wilhuff if I understood correctly:

- primary sort is done by the first orderBy
- startAt filters the first orderBy (sometimes both) 

Which means that I cannot achieve what I intend to, filter orderId and have the result sorted by co , OR, have the collection sorted by co and filtered by orderId.

Getting all the data and doing the sort locally is not an option due to the volume of data.

**Comment by wilhuff** [comment]
That's right. startAt is choosing the first row in the index that you're using for your orderBys.

All Firestore queries must be satisfied by an index scan. This limitation exists to ensure that the work Firestore does to satisfy a query is proportional to the number of rows in the result set. Without this property we couldn't offer the managed service with simple pricing the way we do.

If this kind of query is critical and the volume of data is as large as you're suggesting you may be better off keeping the data in something like BigQuery, which does not have the same indexing requirements that Firestore does. Depending on how often you need to do this you could keep your transactional data in Firestore and export periodically. Alternatively, you can use [Cloud Dataflow](https://codelabs.developers.google.com/codelabs/modern-data-pipeline-firestore-bigquery-dataflow-templates/index.html) to keep this up-to-date in closer to real time.
