### ISSUE TITLE
Regression bug in the firebase console

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#2580]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: chrome 79
  * Firebase SDK version: all
  * Firebase Product: database console

### [REQUIRED] Describe the problem

Hello,

I don't know about a specific github for the firebase console so I'm posting here.
Since a few months, when you have a path in your firebase RTDB tree structure that has specific characters, like spaces and I think also * , when you want to only show that node, the node will always be null in the console, even if it in fact has data.

![image](https://user-images.githubusercontent.com/1098243/73431177-19521880-4340-11ea-9443-56f409c1be73.png)

![image](https://user-images.githubusercontent.com/1098243/73430910-70a3b900-433f-11ea-8da8-ab51ed59fe27.png)

**Comment by puf** [comment]
Hey @LanderBeeuwsaert ,

Since the issue is not specific to the JavaScript SDK, can you [file a bug report](https://firebase.google.com/support/contact/bugs-features/) with our support team?

Thanks!
