### ISSUE TITLE
FR: Firebase Analytics support in Node

### ISSUE THREAD

**Issue by membla** [firebase/firebase-js-sdk#2588]
### Describe your environment

  * Operating System version: macOS 10.14.6
  * Firebase SDK version: 7.8.0
  * Firebase Product: Analytics

### Describe the problem

Any plans to implement Analytics for Node processes? Use cases include the Electron main process (using browser based analytics in the renderer process is everything but straightforward), other Node-based desktop app platforms as well as reporting server side events. A quick Google leads me to believe this is a feature that would be well received!

**Comment by hsubox76** [comment]
I notice you've left a comment in a similar issue: https://github.com/firebase/firebase-js-sdk/issues/2243

So I've tried to leave a clearer explanation of the root problem in that issue (which will stay open), and I'll close this with a link to it, so anyone searching can be directed to the same answer.

**Comment by membla** [comment]
@hsubox76 Thanks for your answer. The issue you are referencing concerns the use of Firebase analytics in the Chromium browser renderer process of Electron, this issue is regarding the use of Firebase Analytics in node.js. I would say these issues are quite separate but will also comment on the answer you made there.
