### ISSUE TITLE
firestore.rules automatically applied on firebase.initializeTestApp?

### ISSUE THREAD

**Issue by baptisteArnaud** [firebase/firebase-js-sdk#2589]
### Describe your environment

  * Operating System version:  Mac OS X 10.15.2
  * Firebase SDK version:  firebase: 7.6.1, @firebase/testing: 0.16.6
  * Firebase Product: emulator https://firebase.google.com/docs/firestore/security/test-rules-emulator

### Describe the problem

It seems that firestore rules are automatically loaded with the method `firebase.initializeTestApp`. We don't want this behavior because we should be able to populate the database freely without the rules already applied.

#### Steps to reproduce:
In `firestore.rules`:
```
match /users/{userId} {
  allow write, get: if isSignedIn() && userOwner(userId);
}

function isSignedIn(){
  return request.auth != null
}

function userOwner(userId){
  return userId == request.auth.uid
}
```

The test:
```
test("read succeed only if requested user is current user", async () => {
  const projectId = `rules-spec-${Date.now()}`;
  const app = firebase.initializeTestApp({
    projectId,
    auth: { uid: "testid", email: "test@test.com" }
  });

  const db = app.firestore();

  //Populate database
  const data: any = {
    "users/testid": {},
    "users/anotherid": {}
  };
  for (const key in data) {
    const ref = db.doc(key);
    await ref.set(data[key]);
  }
  expect(true).toBe(true);
});
```

It throws the error :
```
FirebaseError: 7 PERMISSION_DENIED:
    false for 'create' @ L5, false for 'create' @ L9
```
It couldn't create my mock data because of the rules. But I didn't explicitly load the rules with `firebase.loadFirestoreRules`. I don't think it's a wanted behavior.

**Comment by hsubox76** [comment]
I think I should let the firestore/emulator folks weigh in on whether they think the behavior should change or not, but if you are blocked, I think for now you can at least use `loadFirestoreRules` to load a different rules file with no restrictions.  (Which it seems like you're aware of, but just in case.)

**Comment by baptisteArnaud** [comment]
In fact, It is written in the documentation.
["The emulator will initially load the rules specified in the firestore.rules field of your firebase.json file. If the file does not exist and you don't use the loadFirestoreRules method as described below, the emulator treats all projects as having open rules."](https://firebase.google.com/docs/rules/unit-tests#before_you_run_the_emulator)

It works fine as you suggested @hsubox76 , I load an open rules file before adding mock data then reload the correct rules file like this:

```
test("read succeed only if requested user is current user", async () => {
  const projectId = `rules-spec-${Date.now()}`;
  const app = firebase.initializeTestApp({
    projectId,
    auth: { uid: "testid", email: "test@test.com" }
  });

  const db = app.firestore();
  
  await firebase.loadFirestoreRules({
    projectId,
    rules: fs.readFileSync("firestore-no.rules", "utf-8")
  });

  //Populate database
  const data: any = {
    "users/testid": {},
    "users/anotherid": {}
  };
  for (const key in data) {
    const ref = db.doc(key);
    await ref.set(data[key]);
  }

  await firebase.loadFirestoreRules({
    projectId,
    rules: fs.readFileSync("firestore.rules", "utf-8")
  });

  expect(true).toBe(true);
});
```

I strongly think this should be said in documentation. Should I contribute somehow?

**Comment by hsubox76** [comment]
Can you clarify what changes you think should be in the documentation?  I might be misunderstanding but the current text seems to explain this correctly.  Were you suggesting additional text with the exact steps to address this specific use case?

By the way, the reference docs are open source in this repo but the detailed documentation with guides, quickstarts, etc. is maintained internally, so for this page, we would have to change it for you.

**Comment by baptisteArnaud** [comment]
Ok now that I'm thinking about it, it's quite clear. :)
Sorry about this!
