### ISSUE TITLE
Sending firebase.database.ServerValue.TIMESTAMP in custom metadata for storage throws 503 (should be 4xx)

### ISSUE THREAD

**Issue by apsdehal** [firebase/firebase-js-sdk#259]
### [REQUIRED] Describe your environment

  * Operating System version: Linux Mint 18.1 Serena
  * Firebase SDK version: 4.1.3
  * Firebase Product: Storage

#### Steps to reproduce:

Sending `firebase.database.ServerValue.TIMESTAMP` for one of the values in custom metadata throws 503 (Service Unavailable) which is not the right status code for this I think. It should be something on the lines of 400 (Bad request).
#### Relevant Code:

**Comment by sphippen** [comment]
I can reproduce, this is a server-side problem. I'll leave this Github issue open until the fix is live.

**Comment by rommelpe** [comment]
@apsdehal I would like to check if you are still having this issue. It seems that it was already addressed in the previous releases. I tried reproducing this using the [latest version ](https://firebase.google.com/support/release-notes/js)(7.4.0) and it throws 400 as you expect.
