### ISSUE TITLE
remoteConfig doesn't return values for conditions based on user properties

### ISSUE THREAD

**Issue by shtengel** [firebase/firebase-js-sdk#2592]
* Operating System version:  macOS Version 10.15.1 (Build 19B88)
  * Browser version: 78.0.3904.87
  * Firebase SDK version: 7.8.0
  * Firebase Product: remote-config, analytics

### [REQUIRED] Describe the problem

i am trying to use remoteConfig().getValue('someRandomKey') and to get the value from my RemoteConfig based on User Property..
i'm setting the UserProperties through firebase.anaylitics but remoteConfig still fetch the default one and not the condition one
same as - https://github.com/firebase/firebase-js-sdk/issues/2221
but the workaround didn't work for me 

`
firebase.initializeApp(firebaseConfig);
const remoteConfig = firebase.remoteConfig();

firebase.analytics().setUserProperties({selectedCountry: 'Canada'})

// send an event, so user properties are uploaded.
firebase.analytics().logEvent('new-web-test-user-property');
remoteConfig.fetchAndActivate().then(() => {
    remoteConfig.getValue('someRandomKey')
})
`

**Comment by shtengel** [comment]
ok it changed, im now getting the remote config based on userProperty but it took a few hours for it to update, also how do reset that value in order to get the condition-less values of remote config?

**Comment by rommelpe** [comment]
You may set your userProperty to `null`. Also, you may want to consider adding `minimumFetchIntervalMillis` to speed up your testing in development, as mentioned [here](https://firebase.google.com/docs/remote-config/use-config-web#throttling):
> During app development, you might want to refresh the cache very frequently (many times per hour) to let you rapidly iterate as you develop and test your app. To accommodate rapid iteration on a project with numerous developers, you can temporarily add a property with a low minimum fetch interval (Settings.minimumFetchIntervalMillis) in your app.
