### ISSUE TITLE
Update release dates 

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-js-sdk#2597]
Update the release dates from 2019 to 2020. See the screenshot attached. It's for the following link. 

https://firebase.google.com/support/release-notes/js

<img width="939" alt="Screen Shot 2020-02-05 at 9 49 51 AM" src="https://user-images.githubusercontent.com/4000076/73852339-fe2e4f80-47fc-11ea-9315-29c9ead3b6d6.png">

<img width="1371" alt="Screen Shot 2020-02-05 at 9 53 11 AM" src="https://user-images.githubusercontent.com/4000076/73852543-5c5b3280-47fd-11ea-9f5a-af70b6d58fd9.png">

**Comment by rommelpe** [comment]
That's a good one, @JamesVanWaza@! I'll reach out to our documentation team and file an internal request.

Again, thanks for bringing this up. Have a wonderful day!

**Comment by hsubox76** [comment]
Sorry, I will fix this in the next release.

**Comment by hsubox76** [comment]
This has been fixed: https://firebase.google.com/support/release-notes/js#version_781_-_february_6_2020

Thanks for letting us know!
