### ISSUE TITLE
Unable to Deploy on Firebase 

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-js-sdk#2598]
I am trying to run `firebase-deploy` but I keep getting the following error. See the screenshot attached. 
<img width="1352" alt="Screen Shot 2020-02-05 at 9 59 08 AM" src="https://user-images.githubusercontent.com/4000076/73853147-66316580-47fe-11ea-8b4c-bdc8c5024518.png">

**Comment by rommelpe** [comment]
Thanks for reporting the issue, @jamesdaniels. Based from the error message, it looks like you're using an unsupported version of Node.js. Have you tried to upgrade it (v8 or v10)? 

If it persists, can you share your `package.json` in functions directory?

**Comment by JamesVanWaza** [comment]
@rommelpe attached. 

<img width="1307" alt="Screen Shot 2020-02-05 at 11 35 44 AM" src="https://user-images.githubusercontent.com/4000076/73861882-b7942180-480b-11ea-8d6d-dfc9c0f80afe.png">

**Comment by rommelpe** [comment]
Thanks, @JamesVanWaza. Is there any specific use case why you used `node:12` in your `package.json` instead of 8? I was able to reproduce the issue by upgrading it to 12 using [quickstart](https://github.com/firebase/functions-samples/blob/master/quickstarts/uppercase/functions/package.json). 

>   "engines": {
>     "node": "8"
>   },

**Comment by JamesVanWaza** [comment]
@rommelpe 
Is there a way to have multiple node versions running at the same time. I used 12, because that was the most current one.

**Comment by rommelpe** [comment]
From what I observed in every functions (even in quickstart), it's only allowing one node version per functions, also mentioned [here](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version).

> The engines field is required; it must specify one of the supported Node.js versions in order for you to deploy and run functions. Currently firebase init functions sets this field to 8, which is the recommended Node version for most deployments.

To get rid of the error, you may use either of the supported ones ([v8 or v10](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version)).

**Comment by hsubox76** [comment]
Just in case, because of the question about multiple Node versions at the same time, the one specified is the one that Cloud Functions will use to run your functions code.  You don't need to necessarily have that same version running locally.
