### ISSUE TITLE
firebase-firestore.js  snapshot listener not working

### ISSUE THREAD

**Issue by MarcelEdward** [firebase/firebase-js-sdk#2605]
I am trying to do:

streamSubAddPanel = userQuery.snapshots().listen((data)

In a flutter app, it works on android and ios but not on the webapp.
The log from chrome states a missing plugin ?

dom_renderer.dart:500 Overflow on channel: plugins.flutter.io/cloud_firestore.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
DL @ dom_renderer.dart:500
(anonymous) @ plugin_registry.dart:84
(anonymous) @ async_patch.dart:307
js_helper.dart:1342 Uncaught MissingPluginException(No implementation found for method Query#addSnapshotListener on channel plugins.flutter.io/cloud_firestore)

**Comment by rommelpe** [comment]
Thanks for reporting, @MarcelEdward. I'm not an expert with Flutter, so it may take some time for me to replicate this. If you could provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally and detailed steps, that would be a great help for us to speed up the investigation. Thanks!

**Comment by MarcelEdward** [comment]
Flutter web  uses firebasejs

https://firebase.google.com/docs/web/setup
https://flutter.dev/web

The example code below gets all the users from the database with specific value. And it listens to update when new ones are added. It works on android and ios, but not on the web. It than gives 'No implementation found for method Query#addSnapshotListener on channel plugins.flutter.io/cloud_firestore'  

`    
var userQuery = Firestore.instance.collection('users').where('listenkey', isEqualTo: widget._listenkey);
    streamSubAddPanel = userQuery.snapshots().listen((data) {
      if (data.documents.length == 0) {
        print('Geen user gevonden');
        _message = 'User bestaat niet';
      } else {
        userdata = data.documents.first.data;
      }
    });
`

**Comment by hsubox76** [comment]
Are you using [flutterfire](https://github.com/FirebaseExtended/flutterfire)? It looks like the error is in a Dart interface that calls into the JS library.  `addSnapshotListener` isn't in the JS codebase but there are some references to it in the Flutterfire repo.

It might be a good idea to open this issue in the Flutterfire repo.
