### ISSUE TITLE
Error "CollectionReference.add() requires its first argument to be of type object" when used with withConverter

### ISSUE THREAD

**Issue by skflowne** [firebase/firebase-js-sdk#2606]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 79
  * Firebase SDK version: 7.8.1
  * Firebase Product: database

### Describe the problem
Using `add` on a `CollectionReference` built with `withConverter` throws an error when passing a custom class instance : 
"[native Error Function CollectionReference.add() requires its first argument to be of type object, but it was: a custom Strategy object]"

The converter is only called if I pass a plain object, which seems to defeat the purpose of using a converter, unless I'm misunderstanding how this is supposed to work entirely

I'm encountering this in my Vue app and was able to reproduce it on CodeSandbox, link below

This seems similar to #2601 

#### Relevant Code:

[CodeSandbox](https://codesandbox.io/s/objective-golick-34zwe?fontsize=14&hidenavigation=1&theme=dark)

**Comment by thebrianchen** [comment]
@skflowne Thanks for reporting the bug! Currently working on a fix for this.
