### ISSUE TITLE
firebase.messaging is not function()

### ISSUE THREAD

**Issue by huybsd** [firebase/firebase-js-sdk#261]
### [REQUIRED] Describe your environment

  * Operating System version: react-native@'0.46.4'
  * Firebase SDK version: firebase@'^4.1.3'
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

i use code: 
import * as firebase from 'firebase';
var config = {
    apiKey: "xxxxxxxxxxx",
    authDomain: "xxx.firebaseapp.com",
    databaseURL: "https://xxx.firebaseio.com",
    projectId: "xxx",
    storageBucket: "xxx.appspot.com",
    messagingSenderId: "xxxxxxxxxxxxx"
  };
  firebase.initializeApp(config);
  export const firebaseRef = firebase.database().ref();
  export default firebase;

firebase.messaging().requestPermission() eror firebase.messaging is not a function
![screen shot 2017-10-25 at 2 20 45 pm](https://user-images.githubusercontent.com/29419746/31985949-e52b1a24-b990-11e7-9a34-dfd52dbf68a6.png)

**Comment by billyohgren** [comment]
You must also import '@firebase/messaging' for it to work.

Like this:
import * as firebase from 'firebase';
import '@firebase/messaging';
var config = {
apiKey: "xxxxxxxxxxx",
authDomain: "xxx.firebaseapp.com",
databaseURL: "https://xxx.firebaseio.com",
projectId: "xxx",
storageBucket: "xxx.appspot.com",
messagingSenderId: "xxxxxxxxxxxxx"
};
firebase.initializeApp(config);
export const firebaseRef = firebase.database().ref();
export default firebase;
