### ISSUE TITLE
FirebasePlugin[native]: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0x...

### ISSUE THREAD

**Issue by Sroose** [firebase/firebase-js-sdk#2610]
### Describe your environment

  * Operating System version: IOS 13.3
  * Browser version: Mobile Safari UI/WKWebView 13.3
  * Firebase SDK version: 7.6.2
  * Firebase Product: database (firestore)

#### Steps to reproduce:
Ionic cordova app using Firebase. Using FirebaseX which is wrapper for firebase-js-sdk.

When opening app through notification the error is generated:
`FirebasePlugin[native]: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0xe3de509f452e504d`

Note this error seems to appear always when the device screen was put off, I was not able to reproduce it with just briefly setting the app to the background.
Maybe related to different kinds of sleep states?

#### Relevant Code:

(Cannot reproduce this on stackblitz as it is on device.)
Simplified use case:

```javascript
constructor( private firebase: FirebaseX, ..) {}

this.firebase.onMessageReceived().subscribe(data => {
  console.log('NOTIFCATION RECEIVED');
```

clicking the notification generates these logs:

```
FirebasePlugin[native]: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0xe3de509f452e504d

GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Fmyproject%2Fdatabases%2F(default)&gsessionid=somestring_&VER=8&RID=rpc&SID=somestring&CI=0&AID=0&TYPE=xmlhttp&zx=xm67taboe68s&t=1 [0]

NOTIFCATION RECEIVED
```

This is related to #2581 
Sometimes this error is followed by the assertion error, sometimes it's just breaking the code.

**Comment by Sroose** [comment]
Hi, an extra clue on this error: 
when waking the phone normally, we see a GET happening towards Firestore as first action the app logs after waking:
```
xhr GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?database=projects%2Fmyproject%2Fdatabases%2F(default)&gsessionid=somestring&VER=8&RID=rpc&SID=somestring&CI=0&AID=5&TYPE=xmlhttp&zx=somestring&t=3
resume detected // own log in this.platform.resume.subscribe
```

However when waking the phone by tapping the notification, we get this error and the GET is not happening. I assume that this is also causing any subscriptions we do from there don't return any data.
```
FirebasePlugin[native]: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance
.. notification received code .. // everything inside this.firebase.onMessageReceived().subscribe
resume detected // own log in this.platform.resume.subscribe
```

I hope this can get fixed, but in the meantime: is there some way to 'restart' the Firestore connection?

**Comment by wilhuff** [comment]
Firestore does not call `NSTaggedPointerString` in its iOS implementation let alone in the JavaScript SDK. This must be a bug in one of your wrapping layers. Whether or not it's secondary damage stemming from #2581 is an open question, but that's something to work on with those other teams.
