### ISSUE TITLE
Firebase service worker messaging error: firebase-messaging-sw.js

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#2618]
See also this ticket:
https://github.com/firebase/firebase-js-sdk/issues/2527

I found the issue and a (temp) solution.
It is because firebase-messaging-sw.js was not present in my project and not deployed to the firebase hosting.
When calling cloud functions, seems somehow that this file is necessary?
My temporary solution has been to create and deploy an empty firebase-messaging-sw.js, which solves the issue it seems.
The question I have is: why is this file needed? And if this file is indeed needed, shouldn't I put some code in it? Is this described somewhere in the manual of firebase? I don't find it on first search.

best regards

**Comment by Feiyang1** [comment]
This file is only needed for using Firebase Cloud Messaging. You can read more about it in our [devsite](https://firebase.google.com/docs/cloud-messaging/js/receive?authuser=0).

How do you include firebase SDKs in your project? You should only include SDKs that you use. 
Do you use Firebase Cloud Messaging? If not, you should not include it in your code.
Here is a [guide](https://firebase.google.com/docs/web/setup?authuser=0#add-sdks-initialize) on how to add individual Firebase SDKs.
