### ISSUE TITLE
connect with Facebook doesn't return user with a few accounts, returns user without email field with other and works correctly with others

### ISSUE THREAD

**Issue by mohamedaboelmagd** [firebase/firebase-js-sdk#2622]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04
  * Browser version: Version 79.0.3945.130 (64bit)
  * Firebase SDK version: 7.1.0
  * Firebase Product: auth (auth, database, storage, etc)

#### Steps to reproduce:
Create a new Facebook account, and log in with Facebook the below link

https://feature-pathways--badgewell-main.netlify.com/auth/login

There are console.logs with a login 

```javascript
async facebookLogin(): Promise<any> {
    const provider = new auth.FacebookAuthProvider();
    provider.addScope('email');
    return await this.angularfireAuth.auth
      .signInWithPopup(provider)
      .then(function(result) {
        // This gives you a Facebook Access Token. You can use it to access the
        const token = result.credential;
        // The signed-in user info.
        const user = result.user;
        console.log('{result}', result);
        console.log('{result token}', token);
        console.log('{result user}', user);
        // ...
      })
      .catch(function(error) {
        // Handle Errors here.
        const errorCode = error.code;
        const errorMessage = error.message;
        // The email of the user's account used.
        const email = error.email;
        // The firebase.auth.AuthCredential type that was used.
        const credential = error.credential;
        // ...
        console.log('{err}', errorCode, errorMessage, email, credential);
      });
  }
```

**Comment by rommelpe** [comment]
Thanks for the report, @mohamedaboelmagd. This is actually intended behavior. Whenever a user decides not to share their email, we don't get that information back from the provider. The users can edit how much information they wanted to share. 

Also, you may check out these related posts [[1](https://stackoverflow.com/questions/37522582/empty-email-field-of-firebase-auth-user-using-facebook-login-integration-fireba), [2](https://stackoverflow.com/questions/17532476/facebook-email-field-return-null-even-if-the-email-permission-is-set-and-acce)] for allowing users to share their email and any other issues regarding undefined email.
