### ISSUE TITLE
`storage.refFromURL()` is not working correctly

### ISSUE THREAD

**Issue by dominikfoldi** [firebase/firebase-js-sdk#2625]
### Describe your environment

  * Operating System version: Windows 10 1909
  * Browser version: Google Chrome 80.0.3987.100 
  * Firebase SDK version: 7.8.1
  * Firebase Product: storage

### Describe the problem

`firebase.storage.refFromURL()` is looking for a different storage base url than the one I got from the File information on the backend, plus the [docs ](https://firebase.google.com/docs/storage/web/download-files#create_a_reference) are not correct.

#### Steps to reproduce:

I wanted to use the `firebase.storage.refFromURL()` method to get a reference from my URL that I put together from the File information I got from firebase-admin-sdk on the backend. 
The url looks like this: `https://storage.googleapis.com/storage/v1/b/<project-id>.appspot.com/o/<file-name>`. When I try to paste this URL to my browser it displays the metadata of my public file.

This should work in my opinion however it throws an error that the URL is incorrect. I see in the [implementation ](https://github.com/firebase/firebase-js-sdk/blob/eb614f0e7bcfee5b4bc1d390f894bea3d8f3867b/packages/storage/src/implementation/location.ts#L69) that it is looking for an URL like this: `https://firebasestorage.googleapis.com/v1/b/<project-id>.appspot.com/o/<file-name>`. When I format the URL like this and paste it to my browser I got a 404 error. But of course in this case the Firebase SDK is able to get the reference from it but just becuase these values are hardcoded to the SDK.

Additionally, there is a third type of URL in the [download URL docs](https://firebase.google.com/docs/storage/web/download-files#create_a_reference). As you can see, there is no version tag there and if I format my URL like this it is not working with the SDK either. Also, if I submit this URL to my browser it return 404.

**Comment by rommelpe** [comment]
Sorry for the late response, @dominikfoldi. I'm not an expert with Cloud Storage, maybe you can help me reproduce the issue first.

How would you be able to get the `https://storage.googleapis.com/storage/v1/b/<project-id>.appspot.com/o/<file-name>` from your backend? (a working repro would be more helpful). From what I observed, by default, the client SDK returns `https://firebasestorage.googleapis`. Also, have you checked if there's a token appended to it?

**Comment by dominikfoldi** [comment]
@rommelpe, unfortunately, right now I do not have time to put together a working repro, but I am adding the details how you can get these urls.

First upload a file and get the upload response:

```js
const uploadResponse = await firebaseAdmin.storage().bucket().upload(filePath, options);
const file = uploadResponse[0]; 
const metadata = uploadResponse[1]; 
```

Then there are lots of urls in the response for the uploaded resource and it is hard for the developer to decide which one to use:
1. `metadata.mediaLink` - this is the download link for the file so I could use this but to be able to download this I have to make the file public first which I do not want
2. `metadata.selfLink` - in my opinion this url should be suitable for the `firebase.storage.refFromURL()` method in the client SDK but it is not
3. `file.storage.baseUrl + file.bucket.baseUrl + "/" + file.bucket.id + file.baseUrl + file.id` - this gives us the `https://storage.googleapis.com/storage/v1/b/<project-id>.appspot.com/o/<file-name>` string which in my opinion should also be suitable for the `refFromURL()` method on the client

Right now only the `"gs://" + file.bucket.id + "/" + file.id` string works for the `refFromURL()` method but I would rather store the `metadata.selfLink` string in my database and use that link on the frontend to download the file if needed.

**Comment by schmidt-sebastian** [comment]
@dominikfoldi Unfortunately, the SDKs used by Firebase Web and Firebase Admin talk to different backends. As such, they return and expect different hosts. Internally, we have been trying out different ways to reduce the differences between the Cloud Storage and Firebase Storage product, but as you can see we still have a long way ahead of us.

In the next couple days (or 1/2 weeks), I will update our SDKs to allow both hosts. Thank you for your feedback.

**Comment by schmidt-sebastian** [comment]
Internal tracking bug: b/51463659
