### ISSUE TITLE
There is no event on click outside of recaptcha

### ISSUE THREAD

**Issue by ruslanakholod** [firebase/firebase-js-sdk#2636]
### Environment

  * Operating System version: macOS Catalina 10.15.3
  * Browser version: Version 79.0.3945.130 (Official Build) (64-bit)
  * Firebase SDK version:  firebase@7.6.1
  * Firebase Product: auth

###  Describe the problem

I use phone authorization of firebase in my application
When user clicks at 'Login' button I switch form to the 'Loading state' (which makes 'Login' button disabled) and call `firebase.auth().signInWithPhoneNumber(phone, recaptcha)` function to authorize user. Sometimes firebase opens Recaptcha to verify user's identity. However, if user clicks outside of Recaptcha, it is hiding and no event is triggered, what makes impossible to switch form back to 'Normal state'

#### Steps to reproduce:
1. Make a button which signs in user with phone provider by clicking on it and switches to disabled state immediately after the click
2. Click at the button and see Recaptcha
3. Click outside of Recaptcha to hide it

Actual result: 'Sign in' button is disabled. There is no way to make it enabled (no event for that)

Expected result: There is an event to know if users clicked outside of recaptcha (which hides it)

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
const sendCode = (phone: string) => {
  return firebase
    .auth()
    .signInWithPhoneNumber(phone, recaptcha)
    .then(rsp => rsp.verificationId)
}

// sendCode() returns a promise which will be Pending forever if user clicks outside of Recaptcha
```

**Comment by rommelpe** [comment]
Sorry for the late response, @ruslanakholod. I'm not sure if that's the recaptcha's expected behavior. I tried reproducing it using [quickstart](https://github.com/firebase/quickstart-js/tree/master/auth), the recaptcha never gets hidden at all. If you could provide a working repro, that would be a big help for us to start with.
