### ISSUE TITLE
firebase.messaging().deleteToken(Token) Failed on Firebase WEB SDK 7.8.0

### ISSUE THREAD

**Issue by itsmerachit** [firebase/firebase-js-sdk#2643]
Related to https://github.com/firebase/firebase-js-sdk/issues/2364, you may try upgrading your SDK to the latest version ([7.6.1](https://firebase.google.com/support/release-notes/js))

_Originally posted by @rommelpe in https://github.com/firebase/firebase-js-sdk/issues/2469#issuecomment-570599385_

**Comment by itsmerachit** [comment]
I have the latest Firebase SDK version till date, i.e, 7.8.0. I tried to delete the FCM registration token but it failed. The error stated Internal error encountered.

**Comment by rommelpe** [comment]
Thanks for reaching out, @itsmerachit. Can't seem to reproduce it.
![image](https://user-images.githubusercontent.com/56452310/74818298-59059200-5339-11ea-9f21-517d7277562a.png)

- Have you tried clearing your browser's data storage/cache?
- Is the same error mentioned in the previous ones? Could I ask for a screenshot?
- Considering this https://github.com/firebase/firebase-js-sdk/issues/2364#issuecomment-566077630. Can you identify where the issue coming from (`getToken`  or `deleteToken`) - by placing some `console.log`s. 
- Were you able to replicate it using [quickstart](https://github.com/firebase/quickstart-js/tree/master/messaging)?

**Comment by itsmerachit** [comment]
The information has still not been resolved.
![image](https://user-images.githubusercontent.com/33215684/75612063-3861e700-5b46-11ea-8311-25b51fe1dcdb.png)


My code what I'm actually trying.
`messaging.getToken()
                    .then(function (currentToken) {
                        console.log("FCM"+currentToken);
                        messaging.deleteToken(currentToken)
                            .then(function () {
                                console.log("FCM token deleted");
                                // firebase_signout();
                            })
                            .catch(function (error) {
                                console.log("Error deleting FCMToken.\n" + error);
                                // firebase_signout();
                            });
                    });`

**Comment by itsmerachit** [comment]
The issue still exists at my end.
Here's my code:
`messaging.getToken()
                    .then(function (currentToken) {
                        console.log("FCM"+currentToken);
                        messaging.deleteToken(currentToken)
                            .then(function () {
                                console.log("FCM token deleted");
                                // firebase_signout();
                            })
                            .catch(function (error) {
                                console.log("Error deleting FCMToken.\n" + error);
                                // firebase_signout();
                            });
                    });`

Here's the screenshot of what's happening.
![image](https://user-images.githubusercontent.com/33215684/75612117-ae664e00-5b46-11ea-9054-7a59acff172d.png)

Ps. I'm using firebase SDK 7.8.2 in my project.

**Comment by itsmerachit** [comment]
The issue still exists.
Here's my code:
`messaging.getToken()
                    .then(function (currentToken) {
                        console.log("FCM"+currentToken);
                        messaging.deleteToken(currentToken)
                            .then(function () {
                                console.log("FCM token deleted");
                                // firebase_signout();
                            })
                            .catch(function (error) {
                                console.log("Error deleting FCMToken.\n" + error);
                                // firebase_signout();
                            });
                    });`

Here's the screenshot of what's happening:
![image](https://user-images.githubusercontent.com/33215684/75612221-9ba04900-5b47-11ea-9597-8a1bc43eaa1b.png)

Ps. I'm using firebase SDK 7.8.2

**Comment by rejhgadellaa** [comment]
Same problem on 7.9.3 when I call .getToken()

**Comment by zwu52** [comment]
Hi @itsmerachit, as @rommelpe suggested. Can you try to purge your browser data/cache? After clearing, you can check your indexDb in the developer tool under "application" tab -> "indexDb".  The indexDb should have no data entry before you accept the notification permission. Once you hit accept and a new token is generated, try delete the token from there. 

If that didn't work, please give more information on your browser version

**Comment by zwu52** [comment]
> Same problem on 7.9.3 when I call .getToken()

@rejhgadellaa you could be hitting a different error. If you are having trouble calling getToken(), I'd encourage you to file a separate ticket with a list of description of your environment and stack traces.
