### ISSUE TITLE
IndexedDB Shim doesn't work on ReactNative

### ISSUE THREAD

**Issue by swittk** [firebase/firebase-js-sdk#2651]
At here
https://github.com/firebase/firebase-js-sdk/blob/542240d093ad54f3c8e5739dcb8449e8b9cab131/packages/firestore/src/local/indexeddb_schema.ts#L468-L470
> db.createObjectStore(DbMutationQueue.store, {
>   keyPath: DbMutationQueue.keyPath,
>   autoIncrement: true
> });

Is an autoIncrement: true statement missing here? I'm not sure.

I ran into problems with using an IndexedDB Shim on Android React Native and found that there are errors with autoIncrement not being set to true where needed. (Logging on the iOS version shows the exact opposite/intended behavior). The queries in question were performed when adding new empty objects into a collection, resulting in a new empty object with keyPath batchId, which seems to match the behavior expected from this snippet of code.

Could not specifying autoIncrement explicitly cause unexpected behavior?

**Comment by schmidt-sebastian** [comment]
The DbMutationQueue store doesn't actually. store mutation batches (that's what DbMutationBatch does). It merely stores metadata for each user that has accessed that Firestore instance (via logging in). As such, it is keyed by the user ID and not by an auto-incrementing ID.

The IndexedDbShim is very fragile and we unfortunately cannot support in your endeavor. I do hope that someone else might know the solution to your problem, in which case it would be nice to share the solution with everyone. I will keep this issue open for a couple of days to facilitate this.

**Comment by swittk** [comment]
Thank you for your helpful information :)
