### ISSUE TITLE
Firebase crashes during boot on facebook  in app browser

### ISSUE THREAD

**Issue by leolux** [firebase/firebase-js-sdk#2660]
#### Describe the problem
Facebook in app browser does not support push notifications which is why firebase crashes during boot if you pass `messagingSenderId` to the firebase config. 

Instead of crashing the whole application firebase should be able to boot even if the push notification API is not available.

#### Steps to reproduce:
1. Pass a `messagingSenderId ` to `firebase.initializeApp({messagingSenderId :'value', ...});`
2. Build & deploy your app
3. Post a link to the app on facebook
4. Use the native facebook app and click on the link you have just posted
5. Your app crashes because firebase fails to boot

**Comment by rommelpe** [comment]
Thanks for the report, @leolux. AFAIK, Facebook browser uses a webview. Currently, FCM can be run on browsers that supports [Push API](https://www.w3.org/TR/push-api/). If the browser used doesn't support this, you will receive a similar message to `This browser doesn't support the API's required to use the firebase SDK.` See the public [guide](https://firebase.google.com/docs/cloud-messaging/js/client) for more info.

If there's a way for you to share an error log, that would be more helpful to start with.
