### ISSUE TITLE
Messaging: This browser doesn't support the API's required to use the firebase SDK.

### ISSUE THREAD

**Issue by hamza005** [firebase/firebase-js-sdk#2664]
FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. messaging/unsupported-browser).
I'm using firebase 7.8.0.

But getting this error on every browser. It's a duplicate issue but as I couldn't find anything there, that's why I re-created it.

Thanks

**Comment by hamza005** [comment]
importScripts('https://www.gstatic.com/firebasejs/7.8.0/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/7.8.0/firebase-messaging.js');

// Initialize the Firebase app in the service worker by passing in the
// messagingSenderId.

  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();
  if ('serviceWorker' in navigator) {
    console.log('in the service worker')
    navigator.serviceWorker.register('../firebase-messaging-sw.js')
    .then(function(registration) {
      console.log('Registration successful, scope is:', registration.scope);
    }).catch(function(err) {
      console.log('Service worker registration failed, error:', err);
    });
  }
  messaging.setBackgroundMessageHandler((payload) => {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    // Customize notification here
    const notificationTitle = 'Notification Service';
    const notificationOptions = {
      body: 'you have some new notifications.',
      icon: '/firebase-logo.png'
    };
  
    return self.registration.showNotification(notificationTitle,
      notificationOptions);
  });

**Comment by hamza005** [comment]
this is my service worker file. I just followed the steps on firebase console. But couldn't get rid of this issue.

**Comment by hamza005** [comment]
PS, I'm using a http not https

**Comment by rommelpe** [comment]
Thanks for the report, @hamza005. Most of these reports tend to be [browser related issues](https://firebase.google.com/support/guides/environments_js-sdk#supported_environments). It's strange that it persists in every browser. Can you share their version?

Also, I'm not sure if it has something to do with `http` protocol. I can't seem to encounter it when running my app in `localhost`. 

While I'm trying to replicate this using your provided `service worker` code, could try our [quickstart](https://github.com/firebase/quickstart-js/tree/master/messaging) and see if you're still having this issue. We can use it as a baseline for troubleshooting as well.

**Comment by hamza005** [comment]
Hi, Actually I'm using firebase with react and it's working perfectly fine over the localhost. but when I deployed the build over and aws instance, it started giving that error on every browser. I assumed it's because of the http protocol of my hosting as all my browsers are latest and the same app is working on them when using npm start on localhost. My firefox version is 73.0. My chromium version is 77.0.3865.90 and my chrome version is 77.0.3865.120.

**Comment by rommelpe** [comment]
Bumped into our public [docs](https://firebase.google.com/docs/cloud-messaging/js/client), and indeed, messaging only supports HTTPS pages.

> The FCM SDK is supported only in pages served over HTTPS. This is due to its use of service workers, which are available only on HTTPS sites.

If you'd like to test it out, you could take advantage of our [Firebase Hosting](https://firebase.google.com/docs/hosting/quickstart) for free HTTPS hosting.

**Comment by hamza005** [comment]
Hi, @rommelpe Thanks for your response. the issue seems to be fixed as I just attached an ssl certificate with my domain. Thanks
