### ISSUE TITLE
Auth Error names are out of date in docs

### ISSUE THREAD

**Issue by EliasTouil** [firebase/firebase-js-sdk#2702]
###  Describe your environment

  * Operating System version: OSX Catalina 10.15.2
  * Browser version: Version 80.0.3987.122 (Official Build) (64-bit)
  * Firebase SDK version: "^8.9.2"
  * Firebase Product: Auth

###  Describe the problem
I think Error messages may be out of dates in the docs.
For a user trying to sign up with an email already in use by another user, I get the error code "auth/email-already-in-use", but I was expecting "auth/email-already-exists" by reading the docs [here](https://firebase.google.com/docs/auth/admin/errors)

#### Steps to reproduce / Relevant code

Any visitor is signed in anonymously

```javascript
auth
        .signInAnonymously()
        .then(r => {
          let nextUser = {
            uid: r.uid,
            isAnonymous: r.isAnonymous
          };
          this.setState({ guser: r, user: nextUser });
        })
        .catch(e => this.handleError(anonymousLoginError(e)));
      this.setState({ guser: u });
```

Code used to sign up a visitor 

```javascript
const convertAnon = (email, pw) => {
  if (!validateEmail(email)) {
    throw new Error("E-mail invalide");
  }
  if (!validatePassword(pw)) {
    throw new Error("Mot de passe faible");
  }
  let credential = firebase.auth.EmailAuthProvider.credential(email, pw);
  return auth.currentUser.linkWithCredential(credential).then(r => r.user);
};
```

**Comment by bojeil-google** [comment]
You are conflating client SDK errors with admin SDK errors. The link you are referencing is for admin sdk errors.
