### ISSUE TITLE
If signInWithPhoneNumber is called once it freezes the 2nd time

### ISSUE THREAD

**Issue by developdeez** [firebase/firebase-js-sdk#2704]
For some reason if a user fails to login the first time. And they try again without refreshing the page signInWithPhoneNumber freezes with no response. How do we reset this?

**Comment by MeghaB** [comment]
For internal tracking, b/156547581

**Comment by looptheloop88** [comment]
Hi @developdeez, we apologize that we never got back to you on this issue. I've tried to reproduce this issue using the latest version of the SDK (9.16.0) but I'm not able to, so it's likely that this is no longer relevant. I am going to close this issue, but if you think we should keep it open, just comment and let us know.
