### ISSUE TITLE
error:The redirect operation has been cancelled by the user before finalizing

### ISSUE THREAD

**Issue by Pitouli** [firebase/firebase-js-sdk#2718]
It's been days I'm trying to make firebase auth works with Cordova on Android.

Everything (concerning auth) works well on the web (desktop, iOS Safari, iOS PWA, Android Chrome, Android PWA) or on Cordova iOS, but I do not know why, on Cordova Android, I always have the error "The redirect operation has been cancelled by the user before finalizing".

I tried to make a small app to reproduce the issue. And the issue is... that it works on the small app!

BUT...

Something is different in the Firebase Console!

On my real app, it's like I haven't finished the SDK configuration (see the red dots), because I skipped the last steps (installing the file that the doc about cordova auth explicitly says we can skip, and the step where we are asked to "check" the app connection)
![image](https://user-images.githubusercontent.com/542778/76042173-46ec3c00-5f54-11ea-97f6-a54d966c1eb7.png)

And in my test app, everything seems perfectly configured:
![image](https://user-images.githubusercontent.com/542778/76042585-7e0f1d00-5f55-11ea-8471-95a9943df86d.png)

The thing I do not understand is this: when I set up an Android App on my "real" project, I have 4 steps, the last one is "Run your app to verify installation". I skip this step because it does not work (most probably because I haven't installed the native Android SDK).
![image](https://user-images.githubusercontent.com/542778/76042232-7bf88e80-5f54-11ea-8624-7e7b021ce4d9.png)

But when I do EXACTLY the same thing on my "test" app, then the 4th step is "Read the get started guide for Android". And when I skip all the final steps, the app is considered as correctly installed.
![image](https://user-images.githubusercontent.com/542778/76042287-a1859800-5f54-11ea-8815-7f705ba11217.png)

I spent so much time trying to debug this horrible "operation cancelled" error that I consider EVERYTHING to be a potential reason for it...

So could you please explain why my two dashboards are not working the same way? :) 

Thanks!

**Comment by Pitouli** [comment]
Note : after replacing in my "real project" the firebase config keys (the thing to copy paste from the console, with the apiKey, the authDomain, etc.) and the cordova config.xml by those from the "test" project, my "real" app now successfully connect _(but it is not a solution: my datas are on the "real" project, and the "test" project has its keys publicly shared on the internet...)_

**So it really seems it's something related to the firebase configuration.** 

I compared the consoles for both project: everything seems to be configure the same way, they both have the SHA1 declared (technically, it is the same since I'm using the "debug" keystore), and the only difference I can see at the moment is that one is shown like it has finished its configuration while the other not.

**Comment by Pitouli** [comment]
Hello, help would be greatly appreciated :)

**Comment by prateekj117** [comment]
I am also facing the same issue. Did you find any solution @Pitouli ?

**Comment by Pitouli** [comment]
Nope ; still waiting for an answer :(

**Comment by Pitouli** [comment]
Any idea?

**Comment by prateekj117** [comment]
No. I had to switch to flutter for my app. Though there were many solutions on the Internet. Surprisingly, none of them worked for me.
