### ISSUE TITLE
Firestore rules failing with firebase/firestore but work with firebase/testing

### ISSUE THREAD

**Issue by tad3j** [firebase/firebase-js-sdk#2719]
### Environment

  * Operating System version: Windows 10
  * Browser version: Chrome 80.0.3987 & Firefox 73.0.1
  * Firebase SDK version: ^7.10.0
  * Firebase Product: firestore

#### Steps to reproduce:
I've noticed a strange behavior when `firebase/firestore` (my web app) behaves differently than `firebase/testing` (functions test suite). 

Specifically I have problem with this query:

```javascript
firebase.firestore().collection('signals').where('group.id', 'in', ['owner', 'reader']).orderBy('updatedAt', 'desc').get()
```

### `firebase/testing` result

When using this query in jest test, my **firestore rule passes/returns true**, which I can confirm via coverage report (value returned = true) and my test passing:
![image](https://user-images.githubusercontent.com/4150904/76117461-2ec7fb80-5fec-11ea-92bd-17a645eb5d0a.png)

### `firebase/firestore` result

But the exact same query is failing in my web app, saying that the **same rule returns false**:
![image](https://user-images.githubusercontent.com/4150904/76117571-5ae37c80-5fec-11ea-9ce6-6153c24be107.png)

#### I have:

- made sure firestore database data is the same in both cases to exclude that as a reason. 
- removed package react-redux-saga to exclude it's fault and added query directly to react component.
- also tried to deploy this to staging and test with real firestore instance but I get the same result. 

Because all of that I feel like it's a bug, could it be?

#### Relevant Code:

I've cehcked StackBlitz  but it seems I can't reproduce my problem there because I'm using rules. So I'm just sharing relevant part of rules that I'm using (according to tests and rules test coverage the issue shouldn't be originating from here):

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow get, create, update, delete: if false;
      match /signals/{signalId} {
        allow read: if isSignedIn() && 'group' in resourceData() && isSignalGroupMember(database, resourceData().group.id);
      }
    }
  }
}
function isSignalGroupMember(database, groupId) {
  return isSignalGroupSubscriber(database, groupId) || isSignalGroupOwner(database, groupId);
}
function isSignalGroupOwner(database, groupId) {
  return groupId in getUserSecrets(database).signalGroupsOwned;
}
function isSignalGroupSubscriber(database, groupId) {
  return groupId in getUserSecrets(database).signalGroupsSubscribed;
}
function getUserSecrets(database){
  return get(/databases/$(database)/documents/userSecrets/$(request.auth.uid)).data;
}
```

**Comment by schmidt-sebastian** [comment]
@tad3j Thank you for your report! Unfortunately, I don't have a good answer for you right now, but I will try to find someone that can help,

In the meantime, do you think you could provide either of the following:
- A reproduction app
- Log output from the Firebase SDK. You can find some guidance here: https://stackoverflow.com/questions/48674134/how-to-set-log-level-for-firestore

Thank you!

**Comment by yuchenshi** [comment]
Hi there, I see you're using rules coverage report. Would you mind looking into the coverage report when you're using `firebase/firestore` and see what is different there? I mean, you can drill down to each expression to see what part is returning `false` where it should not.

Also, feel free to attach the coverage report from `firebase/testing` v.s. `firebase/firestore`. These are just plain HTML files that you can just save and upload to GitHub so we can take a look as well.

**Comment by tad3j** [comment]
@schmidt-sebastian, I was able to reproduce it with 2 tests, here is my repo: https://github.com/tad3j/firestore_rules_query_issue

@yuchenshi , I've checked and it returns false when it can't find `userSecrets` document (with `getUserSecrets()` ), but this works with `@firebase/testing`.

**Comment by yuchenshi** [comment]
@tad3j  I've tried this myself, and I found that in the rules `isSignedIn()` returns false in the second test with `firebase/firestore`. Reading through the code, I've noticed that you've never used `firebase.auth` in your tests. As you can see, `firebase/firestore` is a general purpose client library and does not support mocking auth compared to `@firebase/testing`, and you will need to actually sign in for anything `request.auth` to work in security rules. In other words, this works as intended.

For these kind of integration testing, I'd recommend setting up a dedicated production project with anonymous auth enabled, and make sure to sign in before each test. Or you can stick with `@firebase/testing` unit testing if you'd prefer to only use mock auth.

**Comment by tad3j** [comment]
@yuchenshi , I think you misunderstood. Preparing these 2 tests was just my attempt to reproduce the issue (didn't think about what you are saying), but as mentioned in my first post I'm experiencing this issue on a **web app where user is logged** (locally and on staging) in (so I'm not trying to mock anything or even use firebase/firestore in my tests).

And right, it felt strange putting those two libs together in one test, but access was denied on the same rule, so I though I reproduced it. However, this makes me think now that maybe something is wrong with auth part in my web app.

**Comment by yuchenshi** [comment]
Sure a thing, just let us know if you still see this problem after you made sure auth is working properly, and we can dig in further if you can get another repro with auth.
