### ISSUE TITLE
How to query substring in firestore?

### ISSUE THREAD

**Issue by ab2d3e8** [firebase/firebase-js-sdk#2721]
I couldn't find a reliable method for searching part of the text in a variable.
this example some time work but not useful .
`firebase.firestore().collection('user').where('fullName', '>=', search).where('fullName', '<=', search + '\uf8ff')`
and also this : 
`firebase.firestore().collection('user').orderBy('fullName').startAt(search).endAt(search + '\uf8ff');`
why not have like this: 
`firebase.firestore().collection('user').where('fullName', 'contain', search)`
or 
`firebase.firestore().collection('user').where('fullName', '<>', search)`

**Comment by schmidt-sebastian** [comment]
@ab2d3e8 Thanks for your feature request! 

Firestore currently does not support full-text search, but we do know that it is a pretty popular feature request. Please take a look at how Algolia can be used to add full-text search to Firestore: https://firebase.google.com/docs/firestore/solutions/search
