### ISSUE TITLE
Messaging: Not receiving messages - neither in-app, nor background - Chrome @ Windows 10

### ISSUE THREAD

**Issue by denkan** [firebase/firebase-js-sdk#2722]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro (v. 1909)
  * Browser version: Chrome v. 80.0.3987.132
  * Firebase SDK version: 7.10.0
  * Firebase Product: Messaging

### [REQUIRED] Describe the problem
I tried to implement Firebase Messaging into an Angular app, but just couldn't get it to work: 
- I got tokens, backend could subscribe them  to topics and got successfully responses when sending to them. 
- But no messages was received on the client; not in-app by `onMessage()`, nor background by using `setBackgroundMessageHandler()`.

To better test and reduce factors from other things in the app, I wrote a barebone demo of Firebase Messaging (also using a brand new Firebase account). 

**The test site is found here:**
https://denkan-firebase-lab.web.app/

**The code for the site is found here:**
https://github.com/denkan/firebase-messaging-example

**What I found out** was that Chrome on my Windows 10 indeed doesn't receive any messages at all. Not in-app, nor from background handler. No errors in the console log.

However, Microsoft Edge and Firefox received in-app messages correctly. Background handler wouldn't trigger notifications in Windows, but Firefox shows them by its own UI as long as the browser is open (e.g blank tab).

The same Chrome works fine with other web push examples.
It all worked fine on another Windows 10 computer.

**Why I'm posting this**, instead of dismiss it as a specific faulty computer issue:
1. It took me a week of limbo boredness to realize the problem actually didn't seem to lie in my code. 
2. Didn't find any good trace of issues like this from googling, which made me anxious and lost. Maybe this post will bring lights to future debuggers. 
3. I get that my computer could have a faulty setting preventing web push notifications - but shouldn't at least in-app messaging work in all cases? It's my understanding that the in-app reception is more like synced realtime data à la Firestore, so why wouldn't I receive them?

**Comment by zwu52** [comment]
Hi Denkan, 
I tested with your [test app](https://denkan-firebase-lab.web.app/) on Window 10 (v 1903) with Chrome (v. 80.0.3987.132). I am able to get a valid token and receive both foreground and background messages. 

I am also suspecting a faulty browser setting. I would encourage you to clear the browser data/db and step through the SDK code. If you find any suspicious spots, please update in this thread and I am happy to help to investigate further.
