### ISSUE TITLE
FR: prefix JS functions to avoid conflicts with other libraries.

### ISSUE THREAD

**Issue by digiiitalmb** [firebase/firebase-js-sdk#2723]
I have spent hours trying to figure out why getToken function only worked sometimes in my code implementation. Apparently I had another js function in my code called fetch() which was not related to Firebase, and if getToken() function would be called after my other scripts were loaded I would get an error with no proper trace to the issue. 

I would have expected that library functions would be prefixed fb_fetch() or something like that to avoid potential conflicts.

This issue is present in all versions of firebase-js-sdk, to reproduce simply create js function fetch(){} in your firbase-js-sdk implementation.

**Comment by Feiyang1** [comment]
`fetch` is a native Web API (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). We uses it in our code, but we don't define it. 
Generally speaking, you should not define a global function with the same name as any native APIs.
Closing the issue.
