### ISSUE TITLE
API Key is invalid when calling firebase.auth()

### ISSUE THREAD

**Issue by hindsc52** [firebase/firebase-js-sdk#2724]
* Operating System version: macOS 10.15
  * Browser version: Chrome@latest
  * Firebase SDK version: 7.10
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Setting up firebase auth in an existing project. Before importing and using auth the app works as expected and can read data from firestore. As soon as I include auth() the app errors with

```
provider.ts:108 Uncaught M {code: "auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly."}
```

Code that initialises firebase

```
import app from "firebase/app";
import "firebase/auth";
import "firebase/firestore";

const firebaseConfig = {
  ApiKey: process.env.REACT_APP_FIREBASE_API_KEY,
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.REACT_APP_FIREBASE_DATABASE_URL,
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGIN_SENDER_ID,
  appId: process.env.REACT_APP_FIREBASE_APP_ID
};

// constants
const guestCollection = "guests";

class Firebase {
  constructor() {
    app.initializeApp(firebaseConfig);

    // Firebase auth API
    this.auth = app.auth();

    // Firebase APIs
    this.db = app.firestore();
  }

  // Guests API
  guest = uid => this.db.doc(`${guestCollection}/${uid}`);
  addGuest = guest => this.db.collection("guests").add(guest);
  getGuests = () => this.db.collection("guests").get();
}

export default Firebase;
```

The API key is present and is valid as it works when reading and writing to firestore.
Commenting out this line `this.auth = app.auth();` gets rid of the error and the app continues working.

I have enabled auth in the firebase console as well as the email auth provider.

I have used auth with this project before, however that was a long time ago.

**Comment by hsubox76** [comment]
Sorry if this is a silly question, but just in case, is the "A" in "ApiKey" capitalized like that in your actual code or did it just happen on the copy-paste to here? It should be a lowercase "a".

**Comment by hindsc52** [comment]
> Sorry if this is a silly question, but just in case, is the "A" in "ApiKey" capitalized like that in your actual code or did it just happen on the copy-paste to here? It should be a lowercase "a".

Major facepalm moment here 🤦‍♂ That was the issue. I had assumed it was working previously, however I guess just reading and writing from the firestore doesn't use the API Key?
