### ISSUE TITLE
FR: Overload DocumentReference.set() to take a CollectionReference argument and add it as a subcollection

### ISSUE THREAD

**Issue by sventer444** [firebase/firebase-js-sdk#2729]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Firefox 73.0.1
  * Firebase SDK version: 7.2.3
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Calling documentreference.set() with a collectionreference argument should create
a copy of the collectionreference as a subcollection. The only way to make a subcollection
through the js sdk currently is to manually iterate through all items in the subcollection
and add them individually.

#### Relevant Code:
DocumentReference.set(CollectionReference) //sets up a subcollection identical to the argument

**Comment by schmidt-sebastian** [comment]
@sventer444 Thanks for the feature request!

That's a pretty interesting feature request. Copying collections, however, is actually a very expensive operation and something that we cannot implement atomically using the Mobile SDKs. As such, there is a risk that the data we copy is outdated by the time we copy it. 

In general, if we were to implement this feature it would probably live in one our Server SDKs, and possibly in a Firebase Extension (https://firebase.google.com/products/extensions). If an extension can solve your use case, we can certainly work with you to guide you in your development. Please do let us know if this would address your needs!

**Comment by sventer444** [comment]
@schmidt-sebastian What about using snapshots? The process under the hood of DocumentReference.set(CollectionReference) would be to copy the collection to a new object using a snapshot of the documents in it, then after the copy is complete, take another snapshot and add any changes that may have occurred using docChanges, then add the copied and updated object to the document as a subcollection

**Comment by schmidt-sebastian** [comment]
QuerySnapshots may indeed help with this, but they would be limited to 500 documents to ensure an atomic commit. For fewer than 500 documents, using a QuerySnapshot to create a copy is already possible with our current API:

```
const source = firestore.collection(...);
const target = firestore.collection(...);

const snapshot = await source.get();

const batch = firestore.batch();
snapshot.forEach(docSnap => {
    batch.set(target.doc(docSnap.id), docSnap.data());
});
await batch.commit();
```

We can certainly add this to our API, but we would need to see more demand for a feature like this.
