### ISSUE TITLE
[SSR Issue] Setting firestore.settings results in "Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object"

### ISSUE THREAD

**Issue by lupas** [firebase/firebase-js-sdk#2733]
### Describe your environment

  * Operating System version: macOS Catalina 10.15.3
  * Browser version: Chrome 80.0.3987.132
  * Firebase SDK version: v7.10.0
  * Firebase Product: Firestore

### Describe the problem

_firestore.settings()_ does not work in SSR application

#### Steps to reproduce:

- Create a SSR project with a Framework like **Nuxt.js**, where Firebase SDK is run in a Node.js environment.
- Set `firestore.settings({ anything: 'foo' })`
- The error appears on server-side

<img width="1438" alt="Screenshot 2020-03-12 at 08 07 48" src="https://user-images.githubusercontent.com/4020037/76497114-abb70300-643a-11ea-8a3e-580dae68bda2.png">

#### Relevant Code:

https://github.com/lupas/nuxt2-firestore/tree/ssrSettingsIssue

```js
// This works
const fireStore = firebase.firestore()
if (process.client) { //
    fireStore.settings(settings)
}
// This fails
const fireStore = firebase.firestore()
fireStore.settings(settings)
```

#### Links:
https://github.com/nuxt-community/firebase-module/issues/116

**Comment by wilhuff** [comment]
Sorry, we're not Nuxt.js developers here.

Using the Firebase Javascript SDK in Node.js is supported and tested. The following works just fine:

```ts
const firebase = require('firebase');
require('firebase/firestore');

firebase.initializeApp({
  projectId: // ...
});

const db = firebase.firestore();
db.settings({
  host: 'localhost:8080',
  ssl: false,
});
```

This means the problem must be in Nuxt.js but I can't help you debug that.

**Comment by lupas** [comment]
@wilhuff 
Alright, good to know. Will check with Nuxt where the issue could lie. Thanks :)
