### ISSUE TITLE
Rifalmyname 

### ISSUE THREAD

**Issue by rifalmyname** [firebase/firebase-js-sdk#277]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

http://jsbin.com/rinilu/edit?js,console

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by rifalmyname** [comment]
http://www.savelagu.press/top/rifalmyname

**Comment by larssn** [comment]
Weird place to spam
