### ISSUE TITLE
Firestore has a huge TTFB (15sec), is this normal?

### ISSUE THREAD

**Issue by alexvandervegt** [firebase/firebase-js-sdk#2773]
I am using the latest version of firebase (7.12.0).

I was checking my waterfall graph using gtmetrix.com and I did see something weird.

The TTFB on a simple firestore call is about 15 seconds. See the attachments below.

Did analyse with chrome dev tools also on this kind of urls:

```
https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F<PROJECT_NAME>%2Fdatabases%2F(default)&gsessionid=o6ZCTXNf40AsYfTxhyCK1k29hML0M1aB&VER=8&RID=rpc&SID=AGDMPooZoCbZQxhv0ORH6g&CI=0&AID=0&TYPE=xmlhttp&zx=8wfo5u7gg3hg&t=1
```

<img width="388" alt="Screenshot 2020-03-20 at 12 01 29" src="https://user-images.githubusercontent.com/3672692/77158230-2cad7480-6aa3-11ea-9d5a-a6cf0ce6de0f.png">
<img width="1346" alt="Screenshot 2020-03-20 at 12 01 52" src="https://user-images.githubusercontent.com/3672692/77158234-2e773800-6aa3-11ea-8d47-1f59be912817.png">

**Comment by schmidt-sebastian** [comment]
@alexvandervegt Thanks for raising this!

Firestore uses HTTP in a pretty unique way. This reduces the overhead for long-lived streams and allows us to re-use long-lived connections. It would be interesting to see if you continue to see the same timeouts if you opt out of these optimizations and switch to long polling, which emulates traditional request/response traffic and may work better in some environments.

Can you run your experiment again with long polling enabled?

See here: https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#experimentalforcelongpolling

**Comment by wilhuff** [comment]
Given the waterfall graph you posted I don't actually see where the 15 second TTFB is coming from. If you measure with the wall clock do you actually see a 15 second delay before the first result is shown?

The one line listed as incomplete is a hanging GET where Firestore is waiting for updates from the server for any active queries. By default this connection will run for about 60 seconds, receiving as many updates as the server sends and then we'll start another one.

If you enable force long polling, Firestore will still start a hanging GET, but will start a new one after every response from the server.

**Comment by alexvandervegt** [comment]
When i use this option:

experimentalForceLongPolling: true,

The TTFB time moves to the content download area
<img width="383" alt="Screenshot 2020-04-01 at 17 24 37" src="https://user-images.githubusercontent.com/3672692/78155415-b3683700-743d-11ea-82e2-b85fccae830b.png">

**Comment by wilhuff** [comment]
To me this seems like your tool just isn't measuring Firestore's traffic in a useful way.

If you're able to observe a 15-30 second delay of getting data while actually using your application we'll have something to work with, but otherwise you may be better off reporting this as a bug to your tool provider.
