### ISSUE TITLE
FR: Make Firebase Auth working in WebWorker

### ISSUE THREAD

**Issue by muhammadsayuti** [firebase/firebase-js-sdk#278]
#### Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.6.0
  * Firebase Product: auth

#### Describe the problem
I use firebase in many of my projects, but recently i'm trying to use firebase in web worker to synchronize the data to IndexedDb for offline use. The problem i'm facing right now is with firebase auth where i always need to do authentication every time i reload the page because currentUser is always null after reload. I don't know if my thought is right or not, but i think that firebase using localStorage to save the currentUser, and the problem is localStorage is not available in WebWorker.
![devtool screenshot](https://firebasestorage.googleapis.com/v0/b/simpeg-2fd0e.appspot.com/o/firebase-auth-issue.jpg?alt=media&token=775e1a08-b85c-40b3-80b8-3ffd09444516 "Devtool Screenshot")
[https://stackoverflow.com/questions/6179159/accessing-localstorage-from-a-webworker](https://stackoverflow.com/questions/6179159/accessing-localstorage-from-a-webworker)

#### Steps to reproduce:
clone this repository [https://github.com/muhammadsayuti/firebase-auth-issue.git](https://github.com/muhammadsayuti/firebase-auth-issue.git)

fill the config and credential from firebase auth and then run it using either xampp or python SimpleHTTPServer.
the first output that show up first is always "authenticate success", it means that user is always null.

#### Relevant Code:
```javascript
importScripts('./firebase.js');

var config = {
  apiKey: "FIREBASE_API_KEY",
  authDomain: "FIREBASE_AUTH_DOMAIN",
  databaseURL: "FIREBASE_DATABASE_URL",
  projectId: "FIREBASE_PROJECT_ID",
  storageBucket: "FIREBASE_STORAGE_BUCKER",
  messagingSenderId: "FIREBASE_MESSAGING_SENDER_ID"
};
firebase.initializeApp(config);
const auth = firebase.auth();
const credential = { email: 'FIREBASE_AUTH_EMAIL', password: 'FIREBASE_AUTH_PASSWORD' };
auth.onAuthStateChanged(user => {
  if (!user) {
    auth.signInWithEmailAndPassword(credential.email, credential.password).then(user => {
      postMessage('authenticate success');
    });
  } else {
    postMessage('already authenticated');
  }
});
```

**Comment by bojeil-google** [comment]
Thanks, @muhammadsayuti. This is already on our list of features.

**Comment by mohshraim** [comment]
any updates regarding this FR?

**Comment by bojeil-google** [comment]
The feature is in but not fully tested. You should be able to use it. In the process, we had to migrate local persistence to `indexedDB`. There were a few issues with that that have been fixed but not released yet.

**Comment by mohshraim** [comment]
@bojeil-google 
a question please about currentUser..

if user logged-in and refresh the page..
We should **not** rely on auth().currentuser on page refresh as its value will be null, and consider onAuthStateChanged to determine if user already logged-in or not??

And is there anyway to know that user already logged-in in user refresh page (cached) while he is offline? (wifi-off)

thanks

**Comment by SebasG22** [comment]
Is this still in progress ?

**Comment by bojeil-google** [comment]
The latest version should support it but there may be some undiscovered issues with it. You are welcome to test it and if you discover any issues, please let us know.

**Comment by SebasG22** [comment]
@bojeil-google Thanks, works as expected.

**Comment by bojeil-google** [comment]
Thanks for confirming, @SebasG22 . Please let us know if you come across any issues.

**Comment by muhammadsayuti** [comment]
mark this as closed now.

**Comment by SebasG22** [comment]
@bojeil-google @muhammadsayuti This issue must be open again, the library only supports email-password login, not allow to use Google, Github, Facebook and Twitter.
When I used on Web Worker, the library shows this error: 
![image](https://user-images.githubusercontent.com/17608169/49347413-2c9a2300-f66c-11e8-9163-534383279e86.png)
This is the web worker code:
![image](https://user-images.githubusercontent.com/17608169/49347421-43d91080-f66c-11e8-8047-62fe4f54c87d.png)

**Comment by bojeil-google** [comment]
There is no DOM in a web worker. This works as expected. You have to call sign in with popup/redirect from a window. You can use `signInWithCredential` from within a web worker.
