### ISSUE TITLE
ERROR in node_modules/firebase/index.d.ts(134,13): error TS2304: Cannot find name 'unknown'.

### ISSUE THREAD

**Issue by kartik-sampath** [firebase/firebase-js-sdk#2780]
Angular version 6
typescript 2.9.2
node 8.9.4
firebase 7.4

**Comment by zarko-tg** [comment]
<img width="510" alt="Screenshot 2020-03-23 at 08 44 03" src="https://user-images.githubusercontent.com/6142411/77293382-7df77700-6ce2-11ea-8cb8-4dab8164c804.png">

typescript 2.8.4

**Comment by Feiyang1** [comment]
Thanks for the report! https://github.com/firebase/firebase-js-sdk/pull/2434 introduced the type unknown that's added in Typescript 3.0. It is technically a breaking change, so it should be done in a major release, we will revert the change.

For now, can you please stay at 7.11.0, or if possible, upgrade your typescript to 3.0 or above?

**Comment by zarko-tg** [comment]
@Feiyang1 We're staying on 7.11.0 for now. Upgrading Typescript is usually the least desirable option as it's typically locked/recommended to some version by one or another framework (version).
