### ISSUE TITLE
Audit: Stop minimist dependancy prototype pollution

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#2781]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.3
  * Browser version: unrelated - it's a dependency problem
  * Firebase SDK version: latest version (^7.12.0)
  * Firebase Product: all

#### Steps to reproduce:
```
npm i firebase@latest
```

gives these security warnings:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ firebase                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ firebase > @firebase/firestore > grpc > node-pre-gyp >       │
│               │ mkdirp > minimist                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179
```
see: https://npmjs.com/advisories/1179

**Comment by Feiyang1** [comment]
I did a fresh install of firebase and I got `minimist@1.2.5`.
Can you try removing `node_modules` and `package-lock.json` and do a fresh install to see if it resolves the issue?

**Comment by retnikt** [comment]
I have tried clearing it, and have minimist@1.2.5 but still end up with the npm warning. Seems like this is an issue elsewhere.

**Comment by maheshkumar2150** [comment]
Same problem. Any solution?

**Comment by dev-magesstudio** [comment]
We are getting the same issue as well, with fresh install of Firebase, tried the removal of nodes+package-lock.json and it's still persisting

**Comment by mesqueeb** [comment]
Hi @google-oss-bot 👋 
What info do you need more?

**Comment by stevecastaneda** [comment]
Same issue here.  
- Firebase 7.13.2
3 `low` vulnerabilities all regarding minimist

Tried to clear my package-lock.json and delete node_modules folder + npm install on project folder but that did not fix the issue.

**Comment by tvvignesh** [comment]
Same on my end as well. Showing 3 vulnerabilities in minimist. Screenshot below.

![Screenshot from 2020-04-09 18-24-10](https://user-images.githubusercontent.com/1165845/78897124-53057500-7a8f-11ea-912f-04af721f177e.png)

**Comment by Polatouche** [comment]
```
├─┬ firebase@7.13.1
│ ├─┬ @firebase/firestore@1.13.0
│ │ ├─┬ grpc@1.24.2
│ │ │ ├─┬ node-pre-gyp@0.14.0
│ │ │ │ ├─┬ mkdirp@0.5.1
│ │ │ │ │ └── minimist@0.0.8
│ │ │ │ ├─┬ rc@1.2.8
│ │ │ │ │ ├── minimist@1.2.0
```
firebase 7.13 is using old versions of minimist .
firebase@7.14.0 fix that

**Comment by Feiyang1** [comment]
Thanks @Polatouche! Yes, we replaced `grpc` with `grpc-js`, so `minimist` is not a dependency of firestore any more.
