### ISSUE TITLE
API surface for QueryDocumentSnapshot not the same between firebase & firebase-admin: missing updateTime

### ISSUE THREAD

**Issue by garyo** [firebase/firebase-js-sdk#2785]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04
  * Browser version: Chrome latest
  * Firebase SDK version: 7.5.2 (also tested 7.12.0)
  * Firebase Admin SDK version: 8.10.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

I'm writing code which can be used on the client (`firebase.firestore.db()`) as well as the server (`firebase-admin.firestore.db()`). There doesn't seem to be a single source of type info between these two, so I'm defining some merge types:
```typescript
import * as fbadmin from 'firebase-admin'
import * as fbapp from 'firebase/app'

// Firebase types that can come from either source
type Firestore = fbapp.firestore.Firestore | fbadmin.firestore.Firestore
type DocumentSnapshot = fbapp.firestore.DocumentSnapshot | fbadmin.firestore.DocumentSnapshot
```
But when I try to use that DocumentSnapshot, I discover that only the server side (fbadmin.firestore.DocumentSnapshot) has a `.updateTime` property. It seems to be missing from the client-side lib.

### [REQUIRED] Repro

To repro, try these two functions:
```
import * as fbadmin from 'firebase-admin'
import * as fbapp from 'firebase/app'

async function worksOK() {
  const foo = (await fbadmin.firestore().collection('').get())
  const t = foo.docs[0].updateTime
}

async function doesNotWork() {
  const foo = (await fbapp.firestore().collection('').get())
  const t = foo.docs[0].updateTime // No such property here
}
```

**Comment by wilhuff** [comment]
Hi! Thanks for writing in.

Unfortunately, this difference is intentional. We've discussed it before in #570 and differences in the transaction APIs in #2112. In short, this is a value that's not always well defined due to offline support.

If you want to be able to read update times in the mobile clients, our best advice is to write a field in your documents that contains a server timestamp.
