### ISSUE TITLE
7.12.0 database is undefined

### ISSUE THREAD

**Issue by puppybits** [firebase/firebase-js-sdk#2787]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 10.15.13
  * Browser version: 80.0.3987.149
  * Firebase SDK version: 7.12.0
  * Firebase Product: database

#### Steps to reproduce:
updated from 7.11.0 to 7.12.0 and database is undefined

#### Relevant Code:

```javascript
import firebase from 'firebase/app'
import 'firebase/database'
console.log(firebase.firestore); // fn(...)
console.log(firebase.database); // undefined
```

**Comment by Feiyang1** [comment]
That's weird. I can't reproduce.
Can you please delete `node_modules` and do a clean install to see if it resolve the issue?

**Comment by puppybits** [comment]
Yes I did rm -rf /node_modules; rm yarn.lock; yarn install; yarn start and it still listed database as undefined.

**Comment by Feiyang1** [comment]
OK. Can you please create a repro and point me to it?
