### ISSUE TITLE
Analytic not working with cordova

### ISSUE THREAD

**Issue by Pitouli** [firebase/firebase-js-sdk#2791]
### Describe your environment

  * Operating System version: iOS 13.3, Android 5
  * Browser version: Cordova
  * Firebase SDK version: 7.12
  * Firebase Product: Analytic

### Describe the problem

Analytics are working perfectly on the web app, but no data are sent back to the server on the cordova apps (both android or ios).
From the guide, it seems that cordova is officially supported: https://firebase.google.com/support/guides/environments_js-sdk#other_environments

**Comment by Feiyang1** [comment]
hmm, FirebaseAnalytics generally only works in the native browsers. It has a couple of requirements the environment needs to meet:
1. cookie access
2. using http/https protocol

I don't think Cordova meets any of them, so it is a mistake that the doc says it's supported in Cordova. I will update the doc.

https://github.com/firebase/firebase-js-sdk/issues/2243 already tracks this issue and I'm closing this one.
