### ISSUE TITLE
Firestore doesn't add documents after bulk user creation

### ISSUE THREAD

**Issue by qminds** [firebase/firebase-js-sdk#2797]
### [REQUIRED] Describe your environment

  * Operating System version: **Windows 10**
  * Browser version: **Google Chrome 80.0.3987.149**
  * Firebase SDK version: **7.12.0**
  * Firebase Product: **auth**, **firestore**

#### Steps to reproduce:

I'm trying to seed my Firebase with a list of initial users in the web app. This should be a two-step process:

- Add user to Firebase Auth using the `createUserWithEmailAndPassword()` method.
- Add user to a Firestore collection using the `collection.add()` method.

My expectation is that the following code should create 10 users, and add 10 corresponding documents to the database on success. However, it adds only part of documents (approx. 1-3) to the database, even though the users are created properly. Besides, the `catch` part never gets executed: the promise is neither resolved nor rejected.

#### Relevant Code:

```javascript
// Initialize Firebase:

var db = firebase.initializeApp(config).firestore();

// Function to add a new user:

function add(email) {
  firebase.auth().createUserWithEmailAndPassword(email, 'password')
    .then(function (user) {
      console.log('User created:', email, user.user.uid);
      return db.collection('users').add({
        email: email,
        uid: user.user.uid
      });
    })
    .then(function () {
      console.log('Document created:', email);
    })
    .catch(function (error) {
      console.error('Could not create user/document:', error);
    });
}

// Seed database with random users:

for (var i = 0; i < 10; ++i) {
  add(i + '@foo.bar');
}
```

**Comment by Feiyang1** [comment]
Is `console.log('User created:', email, user.user.uid);` executed 10 times, or just 1-3 times that correspond to the successful database writes?

**Comment by qminds** [comment]
### Current behavior:

- `console.log('User created:', email, user.user.uid);` is called **10** times.
- `console.log('Document created:', email);` is called just **several** times (< 10).
- `console.error('Could not create user/document:', error);` is **never** called.

Moreover, if I disallow `write` in the Firestore rules, the `catch` block *is* handled properly, but still only several (< 10) times:

### When I disallow `write` in Firestore rules:

- `console.log('User created:', email, user.user.uid);` is called **10** times.
- `console.log('Document created:', email);` is **never** called (which is expected due to the rules).
- `console.error('Could not create user/document:', error);` is called just **several** (e.g., 3) times reporting insufficient permissions. The other 7 promises are neither resolved not rejected.

**Comment by thebrianchen** [comment]
@qminds Thanks for reporting the issue! I've managed to reproduce it, and I'll update this issue after I investigate.

**Comment by thebrianchen** [comment]
@qminds It appears that you are not waiting for the promise to complete in your for loop with `add()`. You can either wait for the promise in `add()` in each loop, or create the users and write to Firestore in separate loops.

Each time a new user is created with Auth, it sets the newly created user as the current user of the application. Whenever Firestore detects that a user change has occurred, it closes all outstanding streams and cancels any requests in flight. This means that by not waiting for your promise in `add()` to complete before starting the next loop, the write could be interrupted by the user change that results from the subsequent call to `createUserWithEmailAndPassword()`.

I'm going to close this issue, but feel free to open it again if you have any more questions.

**Comment by qminds** [comment]
> Each time a new user is created with Auth, it sets the newly created user as the current user of the application. Whenever Firestore detects that a user change has occurred, it closes all outstanding streams and cancels any requests in flight.

Totally makes sense, thanks a lot for the explanation!
