### ISSUE TITLE
Can't find variable: IDBIndex

### ISSUE THREAD

**Issue by kresogalic8** [firebase/firebase-js-sdk#2801]
Hello, after implementation of analytics in react native, i am getting this error **Can't find variable: IDBIndex**

This is my firebase initialisation: 

```
import * as firebase from 'firebase';
import 'firebase/analytics';

import config from '../env/development.env';
import configProd from '../env/production.env';

if (!firebase.apps.length) {
    firebase.initializeApp(configProd);
}

export default firebase;
```

and this is my log event

`Firebase.analytics().logEvent('page_view');`

**Comment by Feiyang1** [comment]
FirebaseAnalytics doesn't work in React Native. The error you see is one of the several reasons why it doesn't work in non-browser envs.
See https://github.com/firebase/firebase-js-sdk/issues/2243

Just want to point out that you should replace the first line with `import * as firebase from 'firebase/app'`, then import individual products like you are already doing. 
Importing `firebase` directly pulls in all firebase products including the ones you don't use.
