### ISSUE TITLE
RemoteConfig indexedDB errors in production

### ISSUE THREAD

**Issue by josh-m-sharpe** [firebase/firebase-js-sdk#2804]
* Operating System version: iOS 13.3.1
  * Browser version: Safari
  * Firebase SDK version: 7.11.0
  * Firebase Product: remote config

Production Error in the wild.  Difficult to reproduce.

```
firebase.remoteConfig().fetchAndActivate().then(() => { // etc})
```

Results in these errors:
```
Error: Uncaught (in promise): UnknownError: An internal error was encountered in the Indexed Database server
```

```
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```

Seems like an internal error while trying to execute fairly generic fetchAndActivate.  Should firebase be handling this error somehow and not allowing it to bubble up to my application?

**Comment by erikeldridge** [comment]
> not allowing it to bubble up to my application

We explicitly bubble the error up, eg so app logic can handle cases where IndexedDB is unavailable (#2381).

**Comment by erikeldridge** [comment]
Given the context above, and to help us triage incoming issues, I'll close this, but please reopen if I've misunderstood the issue.
