### ISSUE TITLE
firebase.auth().signInWithRedirect() followed by getRedirectResult() times out

### ISSUE THREAD

**Issue by nathanblair** [firebase/firebase-js-sdk#2808]
### [REQUIRED] Describe your environment

  * Operating System version: Void Linux (Mainline kernel 5.4.25)
  * Browser version:  Chromium 80.0.3987.132 (Developer Build) (64-bit)
  * Firebase SDK version:  7.12.0
  * Firebase Product: auth

This issue is occurring in a PWA where all of the app shell is served directly from cache. The firebase script ('/__/firebase/*') urls are also cached, along with the 'https://apis.google.com/js/api.js' url. There is a whitelist filter to allow network access to the '/identitytoolkit/v3/relyingparty/getProjectConfig' url that I guess is requested upon `signInWithRedirect`? Was thinking about caching this too as I think it should be pretty static but wanted to eliminate as many variables as possible first.

### [REQUIRED] Describe the problem
Two things I'm noticing:

1) No user is being created in the Authentication portal on the Firebase console after I've "consented" (all I'm prompted for 'consent' is clicking my account in the account list screen). I thought there used to be an explicit 'Login' -> 'Consent' flow? What happened to this?
2) Upon redirection back to the landing page, the getRedirectResult() just hangs, and eventually fails with a `code: "auth/timeout"
message: "The operation has timed out."
a: null` error.

#### Steps to reproduce:
Clicking the google sign-in button attached to signInWithGoogle() correctly performs a redirect navigation to prompt for my google account. I select my account, and am navigated back to my landing page (its a single page app, so the button is clicked right from the landing page and the login form is only presented when the user is not logged in).

#### Relevant Code:
```javascript
const docBody = document.body
const firebaseAppScript = docBody.appendChild(document.createElement('script'))
const firebaseInitScript = docBody.appendChild(document.createElement('script'))
const firebaseAuthScript = docBody.appendChild(document.createElement('script'))

async function signInWithGoogle() {
  /** @type {import('firebase').auth.Auth} */
  const auth = firebase.auth()
  auth.useDeviceLanguage()

  const googleProvider = new firebase.auth.GoogleAuthProvider()
  auth.signInWithRedirect(googleProvider)
}

firebaseAppScript.src = '/__/firebase/7.12.0/firebase-app.js'

firebaseAppScript.addEventListener('load', () => {
  firebaseInitScript.src = '/__/firebase/init.js'
})

firebaseInitScript.addEventListener('load', () => {
  firebaseAuthScript.src = '/__/firebase/7.12.0/firebase-auth.js'
})

firebaseAuthScript.addEventListener('load', () => {
  console.log('Firebase auth loaded')
  firebase
    .auth()
    .getRedirectResult()
    .then(user => {
      console.log('Redirect result loaded')
      console.log(user)
    })
    .catch(reason => {
      console.error(reason)
    })
  firebase.auth().onAuthStateChanged(user => {
    console.log('Auth state changed')
    if (!user) {
      fetch('components/sign-in-form.html').then(signinresponse =>
        signinresponse.text().then(html => {
          document
            .getelementsbytagname('main')[0]
            .insertadjacenthtml('beforeend', html)
          document
            .getelementbyid('google-sign-in-btn')
            .addeventlistener('click', signinwithgoogle)
        })
      )
      return
    }
    document.getElementById('sign-in-form').remove()
    const token = user.credential.accessToken
    const userInfo = user
  })
})
```

**Comment by nathanblair** [comment]
As I'm debugging this more, it looks like the redirect is triggering the 'activate' event of my service worker.

After I realized that, I also realized that the 'auth' portion of the sdk was installing a 'firebaseLocal' indexedDB. Its not documented anywhere but I suspect this functionality is for authenticating offline?

My PWA clears out any DB upon activation that isn't whitelisted, so it removes the firebaseLocal upon activation. I've only just seen it now as I started logging about anything I can think of.

I think there are some opportunities for improvement here:

1) Its very possible that I don't want to enable offline authentication for my app. This offline functionality (and the creation of the firebaseLocalDB) should be configurable.
2) It should be noted in the documentation that this database is created. I believe it is mentioned in the firestore documentation, as there is a configurable option to use firestore offline, in which case, it does create a couple...indexedDB object stores I think?

I will be continuing to investigate the nature of why my service worker is being activated when the landing page is redirected to. While the 'why' is being investigated, I'll also be looking into how the deletion of the firestoreLocal indexedDB object store may be affecting the behavior.

**Comment by nathanblair** [comment]
Another update: I have adjusted the the service worker registration and it no longer appears to be activating when the landing page is redirected to. So the 'firebaseLocalStorageDb' object store still shows in the IndexedDB. But I've no idea why it was created in the first place, what purpose it serves, and there's no entries inside of it, before or after redirection.

**Comment by bojeil-google** [comment]
`firebaseLocalStorageDb` is used to store the current user if available.
Service worker should be tweaked to not intercept certain internal paths `/__/` needed by auth services.

**Comment by nathanblair** [comment]
Can you give a list on what paths would need to be whitelisted? I don't see it practical to have a progressive web app that doesn't take full advantage of a cache-first strategy. I get that authentication redirects require network access, but that's outside of the sw domain. Once its redirected back to the landing page, if its using the implicit flow, the url should have the consent code embedded in the url. So an auth library should be able to just grab that code and cache it somewhere and reload the page, and the getRedirectResult just grab wherever it was cached (indexedDB?). I know I've done the flow myself, I may end up having to just look up how I did the implicit flow in another C++ app.

Either way, I don't think firebase auth is setup for my needs. I'll close this.

**Comment by bojeil-google** [comment]
You can easily exclude certain paths that do not need to be cached. Blind inclusion always has downsides. There is a sample in the auth package to make it easy for you. We don't use indexedDB for the redirect flow. We actually use `sessionStorage` to pass back the result. As I said, indexedDB is used to store the current user. The code flow is not the implicit flow. The implicit flow passes the credential (id token) directly in the URL which we don't do here.
