### ISSUE TITLE
Index is undefined in Firestore forEach() loop

### ISSUE THREAD

**Issue by ShadeAJ1** [firebase/firebase-js-sdk#2825]
### Describe your environment

  * Operating System version: MacOS Catalina
  * Browser version: Chrome 80.0.3987.149
  * Firebase SDK version: 7.9.3
  * Firebase Product: Firestore

### Describe the problem

I am using the 'forEach()' method in the Firestore SDK and am encountering some problems. Below is the code I am using to iterate through the docs I get from a collection query, pushing their data to a local array, and printing the index of the loop to the console.

```javascript
.then(docs => {
    var array = []
    docs.forEach((doc, index) => {
            array.push(doc.data())
            console.log(index)
     })
});
```
However, the I get the error that index is undefined. I looked into the docs and there is no index argument for the forEach loop. What is the workaround for getting the current index?

#### Steps to reproduce:

It is possible to replicate the problem by querying to get all the documents in a collection, then using the below code after `.get()'

```javascript
.then(docs => {
    var array = []
    docs.forEach((doc, index) => {
            array.push(doc.data())
            console.log(index)
     })
});
```
The doc's data will be printed but the index of the doc is shown as undefined.

#### Relevant Code:

Here is a sample query...

```javascript
    getData: function() {
      db.collection("Data")
        .limit(10)
        .get()
        .then(docs => {
          var array = []
          docs.forEach((doc, index) => {
            array.push(doc.data())
            console.log(array[0], index)
          })
          });
    }
```

**Comment by schmidt-sebastian** [comment]
@ShadeAJ1 

The `forEach` method does not return an index (unlike other forEach methods in the JavaScript core libs). Please see the documentation here: https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot#foreach

If you need the index, you can use `.docs` to obtain a JavaScript array.
