### ISSUE TITLE
firestore: crypto not supported by IE11  

### ISSUE THREAD

**Issue by caspergreen** [firebase/firebase-js-sdk#2826]
### [REQUIRED] Describe your environment

  * Operating System version: Windows
  * Browser version: IE11
  * Firebase SDK version: 7.13.0, 7.13.1
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
Commit a85f81d introduces a call to `crypto`, which is undefined on IE11, thus throwing an exception. 

The fix is to use `msCrypto` if crypto is undefined, as seen [here](https://github.com/firebase/firebase-js-sdk/blob/2348a259ca0e63e451f677909e71388fdb802e70/packages/installations/src/helpers/generate-fid.ts#L32-L34).
```typescript
const crypto =
  self.crypto || ((self as unknown) as { msCrypto: Crypto }).msCrypto;
```

#### Steps to reproduce:

1. Make a web app that calls `firebase.firestore()`.
2. Open web app from IE11.

#### Relevant Code:
https://stackblitz.com/edit/firebase-issue-sandbox-wvfegd
A simple call like this will fail (any client configuration will)
```typescript
  firebase
    .firestore()
    .enablePersistence();
```

**Comment by thebrianchen** [comment]
@caspergreen  Thanks for reporting a bug! This issue is currently being tracked at #2827, so I'll close this ticket.
