### ISSUE TITLE
IE11 broken on 7.13.x

### ISSUE THREAD

**Issue by thesandlord** [firebase/firebase-js-sdk#2827]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: IE11
  * Firebase SDK version: 7.13.1
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

Firestore (both memory-only and standard versions) breaks on IE11 with version 7.13.0 and 7.13.1

Everything works fine on 7.12.0

The first error is:

`SCRIPT5009: 'crypto' is undefined`

Which is easy to fix with a pollyfill
`var crypto = window.crypto || window.msCrypto;`

After that, this error pops up:
`SCRIPT438: Object doesn't support property or method 'forEach'`

I think this is caused by this PR:
https://github.com/firebase/firebase-js-sdk/pull/2764

Specifically this line:
https://github.com/firebase/firebase-js-sdk/blob/97aada8c57d8f481433b8b3fb288c33dd91f931a/packages/firestore/src/util/misc.ts#L34

This is a Uint8Array, so it needs to be pollyfilled like this:
`Uint8Array.prototype.forEach = Array.prototype.forEach;`

I don't think these pollyfills are included in @babel/preset-env or the core-js all in one script

**Comment by schmidt-sebastian** [comment]
This will be fixed in the next release.
