### ISSUE TITLE
Firebase Cloud Messaging with ServiceWorker in an app running inside a subdirectory

### ISSUE THREAD

**Issue by Reflex-Gravity** [firebase/firebase-js-sdk#2831]
* Operating System version: Linux Debian 10
  * Browser version: Chrome 80
  * Firebase SDK version: 7.13.1
  * Firebase Product: messaging
## Description
My application is running under `https://DOMAIN/app/` and my firebase sw is under `https://DOMAIN/app/firebase-messaging-sw.js`
But while accessing the application, it shows a `HTTP: 404` error and tries accessing the sw file at `https://DOMAIN/firebase-messaging-sw.js`

**Comment by Feiyang1** [comment]
If the service worker file is not at the default location, you need to register it manually and pass it to FCM. e.g.
```

const fcm = firebase.messaging();
swRegistration = await navigator.serviceWorker.register(
          '/app/firebase-messaging-sw.js',
          {
            scope: '/myscopeforfcm'
          }
)

// make sure that you call useServiceWorker before calling getToken
fcm.useServiceWorker(swRegistration);
fcm.getToken();
```

**Comment by Reflex-Gravity** [comment]
Thanks!!
It worked. I was registering the service-worker after getToken.
