### ISSUE TITLE
auth.OAuthProvider returns undefined

### ISSUE THREAD

**Issue by wongpeiyi** [firebase/firebase-js-sdk#2844]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 10.14.6
  * Browser version: Chrome 80.0.3987.149
  * Firebase SDK version: 7.5.0 (also tried 7.13.1)
  * Firebase Product: auth (web)

### [REQUIRED] Describe the problem

https://firebase.google.com/docs/auth/web/apple has a code snippet:
```js
var provider = new firebase.auth.OAuthProvider('apple.com');
```
However, `firebase.auth.OAuthProvider('apple.com')` returns `undefined` (for any argument actually).

I get that there is a `FacebookAuthProvider` now but there isn't one for Apple Sign In, so maybe that is the problem and the docs are out of date?

Failing jsbin: https://jsbin.com/repopalupu/edit?html,js,console

**Comment by hsubox76** [comment]
In your jsbin example, you omitted the `new` keyword, which is needed.  Is that the case in your project as well or just a typo when copying to your jsbin?

**Comment by wongpeiyi** [comment]
Brainfart on my part, thank you for the response
