### ISSUE TITLE
Cloud Messaging `onMessage` callback in Chrome Extension doesn't work

### ISSUE THREAD

**Issue by enkot** [firebase/firebase-js-sdk#2846]
### Describe your environment

  * Operating System version: macOS Catalina (10.15.3)
  * Browser version: Google Chrome (80.0.3987.149)
  * Firebase SDK version: 7.13.1
  * Firebase Product: messaging

### Describe the problem

Trying to use Firebase Cloud Messaging in Chrome Extension. Messaging in service worker works correctly, while `onMessage` callback in foreground doesn't work. 

#### Steps to reproduce:

Sample project you can find here: [https://github.com/enkot/extension-firebase-messages](https://github.com/enkot/extension-firebase-messages)

#### Relevant Code:

Part of the code, where `onMessage` callback should be called:
```javascript
const messaging = firebase.messaging();
messaging.usePublicVapidKey(/* Public key here */);

messaging.onMessage((payload) => {
  console.log('Message received: ', payload)
})
```

**Comment by zwu52** [comment]
Hi @enkot the sample project link doesn't seem to lead to the correct contents. Could you update it.

**Comment by enkot** [comment]
Hi @zwu52 Thanks for noticing, updated the link.

**Comment by zwu52** [comment]
Hi @enkot this is working as intended (However, the behavior for chrome extension should be documented better). When you look at the [FCM Web Receive Rules](https://firebase.google.com/docs/cloud-messaging/js/receive), chrome extension receives should be categorized in "background receive". That is if you are sending a FCM message with "notification" payload, the SDK displays it for you. If you are sending notification with a "data" payload, you can handle it in your callback set with `setBackgroundMessageHandler`.

**Comment by enkot** [comment]
Hi @zwu52 Why did you close the issue? Even when I send message in this format: 
```js
{ "to":"/* mytoken */", "data": { "body": "mybody" } }
```
and extension is in foreground - `onMessage` is not called. Did you test it in sample project?

**Comment by enkot** [comment]
> Hi @enkot this is working as intended (However, the behavior for chrome extension should be documented better). When you look at the [FCM Web Receive Rules](https://firebase.google.com/docs/cloud-messaging/js/receive), chrome extension receives should be categorized in "background receive". That is if you are sending a FCM message with "notification" payload, the SDK displays it for you. If you are sending notification with a "data" payload, you can handle it in your callback set with `setBackgroundMessageHandler`.

@zwu52 Just checked on more time, `onMessage` works in web page but **not** in chrome extension page.
