### ISSUE TITLE
Facing error installing with NPM 

### ISSUE THREAD

**Issue by ronaklalwaniii** [firebase/firebase-js-sdk#2848]
Hi firebase team, I am facing the following error while using `npm i`:

`TypeError: firebase_app__WEBPACK_IMPORTED_MODULE_0__.auth is not a function`

**Please Note:** I am not facing the same with `yarn install`

**Comment by hsubox76** [comment]
I tried a basic install with the following steps and it works as normal:

```
 mkdir test-install
 cd test-install
 npm init
  npm i firebase
```

Can you please describe the exact steps needed to reproduce this error? If it is not a fresh install, perhaps deleting `node_modules`, removing `package-lock.json`, and clearing your cache may help.

If you can reproduce it with a fresh npm project, that would be the best, and make it most likely for us to be able to reproduce it on our end.

**Comment by comxd** [comment]
I have encountered the same problem, `rm -fr node_modules/ && npm i`, solved the building task.
