### ISSUE TITLE
webchannel-wrapper build process not compatible with web worker

### ISSUE THREAD

**Issue by PCreations** [firebase/firebase-js-sdk#285]
### Describe your environment

  * Operating System version: OSX 10.12.1
  * Firebase SDK version: 4.6.0
  * Firebase Product: firestore 4.5.2

### Describe the problem
When trying to use firestore inside a webworker, the window object is not set to the `self` variables, as it is for auth build process for example, thus making firestore to fail as if we were trying to use the browser sdk in a node environnement.

I think the problem lies in the Closure compiler code of the webchannel-wrapper : 
webchannel-wrapper/tools/build.js
```javascript
// actual code
closureBuilder.build({
  name: 'firebase.webchannel.wrapper',
  srcs: glob([resolve(__dirname, '../src/**/*.js')]),
  externs: [resolve(__dirname, '../externs/overrides.js')],
  out: 'dist/index.js',
  options: {
    closure: {
      output_wrapper:
        "(function() {%output%}).call(typeof window !== 'undefined' ? window : this)",
      language_out: 'ECMASCRIPT5',
      compilation_level: 'ADVANCED_OPTIMIZATIONS'
    }
  }
});

// I think this should be done like this :
closureBuilder.build({
  name: 'firebase.webchannel.wrapper',
  srcs: glob([resolve(__dirname, '../src/**/*.js')]),
  externs: [resolve(__dirname, '../externs/overrides.js')],
  out: 'dist/index.js',
  options: {
    closure: {
      output_wrapper:
        "(function() {%output%}).call(typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : typeof window !== 'undefined' ? window : {})",
      language_out: 'ECMASCRIPT5',
      compilation_level: 'ADVANCED_OPTIMIZATIONS'
    }
  }
});
```

When modifying this file, and `yarn link`ing the package manually, I get rid of the "nodejs" like error (`k.setTimeout is not defined`, etc.) but some others pop out from browser.window dependent method like `Image` that are not defined in a webworker environnement (this error commes from the goog.net.WebChannel package).
Any chance to add support for using firestore in webworker ?

**Comment by mikelehen** [comment]
We resolved the webchannel / Image issue separately.  Can you try your workaround again and see if the webworker issue is again?  If so, we can likely get your change implemented (if you're willing, a PR would be most appreciated :-))

**Comment by r0bn** [comment]
i had the same error message, i tested the proposed change from @PCreations and it seems to work.

**Comment by PCreations** [comment]
Seems good now ! Maybe we can close this issue when the master branch is released :)

**Comment by mikelehen** [comment]
Holler if anybody is still seeing issues!
