### ISSUE TITLE
FR: Apple sign in does not work simultaneously in a Reactjs & React Native (with Expo) application.

### ISSUE THREAD

**Issue by robbm1** [firebase/firebase-js-sdk#2854]
### [REQUIRED] Describe your environment

  * Firebase SDK version: `^7.13.1`
  * Firebase Product: auth

### [REQUIRED] Describe the problem

I'm currently using the same Firebase project, for authentication in a website made with Reactjs and a React Native app (in combination with the Expo managed workflow). When implementing Apple Sign in, I run into the problem that on both platforms a different value is expected in the Service ID field in Firebase (Firebase console > Authentication > Sign in method > Apple).

I managed to make it work in the Expo app by using my bundle identifier (which is also my Apple App ID) on the Service ID field in Firebase. But now the sign in with Apple on my website does not work. I managed to make it work there, by changing the Service ID field in Firebase to my specific App Service ID (found in Apple developer console > Identifiers > Services IDs), but then Apple Sign in breaks in my Expo app…

So I am stuck with an app that requires something and a website that requires an other. This makes it impossible to implement Apple sign in combination with Firebase Authentication in both platforms. Maybe accepting multiple Service IDs within Firebase would solve this problem.

**Comment by scottcrossen** [comment]
This doesn't sound like a JS SDK issue but rather something related to the auth service itself. Do you have the same issue when using

https://github.com/invertase/react-native-firebase

?

**Comment by robbm1** [comment]
The getting started of the React-Native-Firebase library describes the following about Expo apps:

> Expo does not support integration with native modules via it's "Managed workflow". Integration is only possible when used with the "Bare workflow".

Using the "Managed workflow" it is not possible for me to make use of this library. Any other ideas @scottcrossen ?

**Comment by scottcrossen** [comment]
Have you verified that your iOS app is registered in the project settings of firebase (Gear next to "Project Overview" -> "Project settings" -> General -> "Add app"? If not can you add your iOS app and then continue to use the supported service ID in the auth configuration. Let me know if you've already verified that the iOS bundle is listed there.

**Comment by robbm1** [comment]
I have tried to do this. But for this step, I for example need to move a GoogleService-Info.plist-file to the root of my Xcode-project en add some required initialization code (Swift). This requires access to the native code and native dependencies, something which is not possible in the "Managed workflow".

**Comment by scottcrossen** [comment]
This sounds like a shortcoming of Expo and not the Firebase SDK. The workflow Firebase currently supports is for developers to provide app information in the "Add app" menu I mentioned earlier. We do not support adding bundle IDs into the Service ID field of Firebase Auth. Please consider using a react-native workflow that provides system information.
