### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by jpreynat** [firebase/firebase-js-sdk#2855]
### [REQUIRED] Describe your environment

  * Operating System version: Any
  * Browser version: Firefox, all versions
  * Firebase SDK version: 7.12.0 and earlier
  * Firebase Product: database

### [REQUIRED] Describe the problem

Many of our users in production using Firefox have the following error in their browser:

```js
TypeError: can't access dead object
  at createIFrame_(./node_modules/@firebase/database/dist/index.cjs.js:10360:13)
  at FirebaseIFrameScriptHolder(./node_modules/@firebase/database/dist/index.cjs.js:10295:56)
  at fn(./node_modules/@firebase/database/dist/index.cjs.js:10043:37)
  at executeWhenDOMReady(./node_modules/@firebase/database/dist/index.cjs.js:386:9)
  at open(./node_modules/@firebase/database/dist/index.cjs.js:10038:9)
  at apply(./node_modules/@firebase/database/dist/index.cjs.js:11125:40)
```

This seems to happen in all environments (MacOS, Windows and Linux), but only with Firefox.
This error is thrown many times for a single user session.

#### Steps to reproduce:

I've tried to reproduce it myself many times but didn't have the problem.
You might want to look at [this page on the subject on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object) to check if the object is dead for Firefox.

**Comment by schmidt-sebastian** [comment]
@jpreynat Thanks for filing this issue! This looks like an issue in our networking layer. The Realtime Database by default tries to use WebSockets for its communication with the backend. When this fails, we fall back to "long polling", which uses an iFrame to establish long lived connections. It looks like this fallback is causing issues for you.

While I can't promise that we will be able to isolate the root cause, you can disable long polling via an internal API: https://stackoverflow.com/questions/20805467/firebase-is-there-a-flag-to-force-long-polling-when-websockets-are-blocked-by

If you manage to create a reproduction, I can take a closer look and see if we can fix the underlying issue.

**Comment by jpreynat** [comment]
Hi @schmidt-sebastian, thanks for the advice.
I've just tested locally to force polling on my Mac running first Firefox 72, with which it works fine.

But running it with Firefox 68, which seems to be one of the most faulty versions for our users.
I didn't get an error, but there's seems to be an infinite loop while fetching the database, as you can see in the network chart below.

![image](https://user-images.githubusercontent.com/7927876/78280059-c69c0500-7518-11ea-87f8-3a21525f7bc0.png)

All requests are taking 25s, which seems a bit weird, as they were all ended by a timeout, and receive the response `pRTLPCB(x,[]);`, with `x` starting at `2` and incrementing by one at each new request.

If it helps, the fetched URL is:
```
https://s-usc1c-nss-231.firebaseio.com/.lp?id=<number>&pw=<hash>&ser=<number>&ns=<my-fb-project>
```
Only the `ser` parameter seems to be incremented by one at each request too.
It's been running for about 10 minutes now and the app still didn't load...

**Comment by schmidt-sebastian** [comment]
What are you seeing is exactly how Long Polling is meant to work. In this mode, the SDK sends repeated requests that each last `n` seconds. In this time. the server has a chance to respond. Once a single request times out, the SDK will open the next request.

Please take a look here for a more accurate description: https://en.wikipedia.org/wiki/Push_technology#Long_polling

**Comment by jpreynat** [comment]
Hi @schmidt-sebastian,
I understand that this is how it is supposed to work in long polling mode, but this actually doesn't really work. When switching to this mode, our whole application doesn't even start and never finishes loading in Firefox 68, so there might be something else which doesn't work properly here.

**Comment by schmidt-sebastian** [comment]
@jpreynat If you can provide us log outputs from the SDK I might be able to take another look. 

https://firebase.google.com/docs/reference/js/firebase.database#enablelogging
