### ISSUE TITLE
7.13.2 has unhandled promise rejection Wu.getRandomValues is undefined

### ISSUE THREAD

**Issue by pdugan20** [firebase/firebase-js-sdk#2858]
### Describe your environment
  * Operating System version: react native 0.61
  * Browser version: n/a
  * Firebase SDK version: 7.13.2
  * Firebase Product: firestore

### Describe the problem
Getting the following error when trying to initialize within react native:
```
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'Wu.getRandomValues')]
```

Not sure what Wu is, is that referring to [Kai Wu](https://github.com/firebase/firebase-js-sdk/commit/aab78f9dfbf2138cf4c1d8dd8bae102b7a5bd0b1)? 

#### Steps to reproduce:
Try and initialize firebase within a react native environment.

#### Relevant Code:
```
import Constants from 'expo-constants';
import { decode, encode } from 'base-64';
import firebase from 'firebase';
import '@firebase/firestore';

global.btoa = encode;
global.atob = decode;
global.crypto = {};

global.crypto.getRandomValues = (byteArray) => {
    for (let i = 0; i < byteArray.length; i += 1) {
        byteArray[i] = Math.floor(256 * Math.random());
    }
};

class Fire {
    constructor() {
        if (!firebase.apps.length) {
            firebase.initializeApp(Constants.manifest.extra.firebaseConfig);
        }
    }
}

Fire.shared = new Fire();

export const db = firebase.firestore();
export const storage = firebase.storage();
export const auth = firebase.auth();

export default Fire;
```

**Comment by schmidt-sebastian** [comment]
@pdugan20 Thanks for filing this issue.

@dconeybe The following line is likely the culprit:

```
const crypto = window.crypto || (window as any).msCrypto;
```
`msCrypto` is not in any of the .d.ts files we include here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/externs.json Hence, it gets mangled. 

Since we likely don't want to include an externs file just for this, your best bet may be to use object-literal access: `window["msCrypto"]` (please verify that this does work - the best build for these kind of verifications is the 'dist/index.esm2017.ts' build.

If I interpet this issue correctly. "crypto" is also not available in ReactNative. Otherwise, `msCrypto` should never get evaluated. Do we need to provide a fallback to Math.random()?

**Comment by RWOverdijk** [comment]
I get this on @firebase/firestore@1.13.1.

**Comment by IjzerenHein** [comment]
> I get this on @firebase/firestore@1.13.1.

@RWOverdijk Yes at the moment the latest working version for react-native seems to be 7.9.0

https://github.com/expo/expo/issues/7507#issuecomment-608299120

**Comment by IjzerenHein** [comment]
> If I interpet this issue correctly. "crypto" is also not available in ReactNative. Otherwise, msCrypto should never get evaluated. Do we need to provide a fallback to Math.random()?

@schmidt-sebastian Yes this does seem to be the case. At the moment this is breaking the react-native support so a fallback to `Math.random` would be great on the platforms that don't support crypto.

**Comment by dconeybe** [comment]
I've reverted this "crypto" change for now.  Our next release will therefore fix this error.

**Comment by IjzerenHein** [comment]
> I've reverted this "crypto" change for now. Our next release will therefore fix this error.

Awesome great to hear @dconeybe !

There is currently another issue which breaks the react-native supported due to the absence of `atob` in the pure js environment. Is this something you also plan on addressing?

**Comment by IjzerenHein** [comment]
Alright thanks for the info @dconeybe !
