### ISSUE TITLE
FCM Notification showing ["This site has been updated in the background"] only when Firestore persistence is enabled and the user is on mobile.

### ISSUE THREAD

**Issue by Hadza** [firebase/firebase-js-sdk#2869]
### [REQUIRED] Describe your environment

  * Operating System version: Android 10
  * Browser version: Chrome 80.0.3987.162
  * Firebase SDK version: 7.13.2
  * Firebase Product: Firestore and Firebase Cloud Messaging

### [REQUIRED] Describe the problem
On a PWA application, I'm sending notifications through FCM and using Firestore as the database, everything works perfectly, my database works great, FCM push notifications are getting received almost instantly until I enable Firestore persistence.

#### Steps to reproduce:

1. Set a PWA application
2. Install Firestore and FCM
3. Open Chrome on mobile and grant notifications permission
4. Send notification through Firebase Console
5. Receive notification with title and body being properly displayed
6. Enable Firestore persistence with or without synchronizeTabs: true
7. Reload app on browser or delete data from installed PWA
8. Send notification through Firebase Console
9. Receive notification only showing the text "This site has been updated in the background"

#### Relevant Code:

store.js
```javascript
db.enablePersistence({synchronizeTabs:true})
    .then(() => {
       console.log('data persistence enabled')
    })
    .catch(err => {
       console.log('failed persistence', err)
    })
```
firebase-messaging-sw
```javascript
importScripts('https://www.gstatic.com/firebasejs/3.9.0/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/3.9.0/firebase-messaging.js');
var config = {
//config
};
firebase.initializeApp(config);

let messaging = firebase.messaging();

messaging.setBackgroundMessageHandler(function(payload) {
    const notificationTitle = payload.title;
    const notificationOptions = {
        body: payload.body,
        icon: 'alarm.png'
    };

    return self.registration.showNotification(notificationTitle, notificationOptions);
});
```
registerServiceWorker.js
```javascript
import { register } from 'register-service-worker'

if (process.env.NODE_ENV === 'production') {
  register(`${process.env.BASE_URL}service-worker.js`, {
    ready () {
      console.log(
        'App is being served from cache by a service worker.\n' +
        'For more details, visit https://goo.gl/AFskqB'
      )
    },
....
```
main.js
```javascript
navigator.serviceWorker
    .register("/firebase-messaging-sw.js")
    .then(registration => {
      messaging.useServiceWorker(registration);
    })
    .catch(err => {
      console.log(err);
    });
```

**Comment by Feiyang1** [comment]
It seems you are using 2 service workers, is it possible that the firebase one was overwritten by yours?
If you put a console.log in the callback you pass to `setBackgroundMessageHandler`, does it get displayed? 

I also noticed that you are using very old firebase scripts in the service worker.
```
importScripts('https://www.gstatic.com/firebasejs/3.9.0/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/3.9.0/firebase-messaging.js');
```
is it just a copy/paste mistake? If not, can you update them to the same version as your client code is using?

**Comment by Hadza** [comment]
> 
> 
> It seems you are using 2 service workers, is it possible that the firebase one was overwritten by yours?
> If you put a console.log in the callback you pass to `setBackgroundMessageHandler`, does it get displayed?
> 
> I also noticed that you are using very old firebase scripts in the service worker.
> 
> ```
> importScripts('https://www.gstatic.com/firebasejs/3.9.0/firebase-app.js');
> importScripts('https://www.gstatic.com/firebasejs/3.9.0/firebase-messaging.js');
> ```
> 
> is it just a copy/paste mistake? If not, can you update them to the same version as your client code is using?

It seems like I'm using 2 service workers, now that I've updated the scripts to my version (copy/paste mistake), firebase service worker is overwriting the PWA one, I tried to mix both service workers into one and it doesn't throw any errors anymore, notifications are working now but PWA still doesn't works.

firebase-messaging-sw.js
```javascript
importScripts('https://www.gstatic.com/firebasejs/7.13.0/firebase-messaging.js');
importScripts("https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");
importScripts(
  "./precache-manifest.44d66ed330d1d3a52efe6ddf665b1b65.js"
);

var config = {
appConfig
};
firebase.initializeApp(config);

let messaging = firebase.messaging();

messaging.setBackgroundMessageHandler(function(payload) {
    console.log('BackgroundMessageHandler registered')
    const notificationTitle = payload.title;
    const notificationOptions = {
        body: payload.body,
        icon: 'alarm.png'
    };

    return self.registration.showNotification('Nuevo pedido', {body:'Se ha registrado un nuevo pedido'});
});

workbox.core.setCacheNameDetails({prefix: "chatbot-dashboard"});
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

```

**Comment by Feiyang1** [comment]
Does `console.log('BackgroundMessageHandler registered')` execute whenever you see `This site has been updated in the background` ?

And just to isolate the issue, if you don't register the PWA service worker, does notification always work correctly?

It would be really helpful if you can create a repro, so I can use it to debug.

**Comment by Hadza** [comment]
> 
> 
> Does `console.log('BackgroundMessageHandler registered')` execute whenever you see `This site has been updated in the background` ?
> 
> And just to isolate the issue, if you don't register the PWA service worker, does notification always work correctly?
> 
> It would be really helpful if you can create a repro, so I can use it to debug.

I made some tweaks and noticed i failed to add this lines to the service worker.
```javascript
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});
```

After these lines were added, PWA started working and the notifications started working properly too, strangely the console.log has never shown even with PWA totally disabled and notifications being shown correctly.

I already tried sending a notification through console and using POSTMAN, both are working now.

**Comment by Feiyang1** [comment]
FCM supports 2 types of messages, data messages and notification messages. The SDK shows  a notification automatically for notification messages, while the callback in `setBackgroundMessageHandler` only handle data messages, so I guess you were sending notification messages? 

[Here](https://firebase.google.com/docs/cloud-messaging/concept-options?authuser=0) you can read more about the 2 types of messages.

I'm closing the issue since you figured it out, but feel free to reopen if you encountered other issues.
