### ISSUE TITLE
"ReferenceError: window is not defined" when using firestore in a web worker.

### ISSUE THREAD

**Issue by universse** [firebase/firebase-js-sdk#2870]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Firefox 74.0.1
  * Firebase SDK version: 7.13.2
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
![image](https://user-images.githubusercontent.com/15166715/78465969-b8bfcd00-772e-11ea-9619-7ad39886d166.png)
![image](https://user-images.githubusercontent.com/15166715/78465953-8d3ce280-772e-11ea-9e5e-122e18446f1b.png)

**Comment by laurentpayot** [comment]
@universse are you using the custom build from #983? I had the same error has you. The Firestore directory to overwrite has changed: you now have to copy your custom build into `node_modules/firebase/node_modules/@firebase/firestore`.

**Comment by schmidt-sebastian** [comment]
Thanks for reporting this! For now, do you mind downgrading to 7.12.0? We will get this fixed in the next release.

**Comment by universse** [comment]
Thanks for your response. Sure no worry.

**Comment by merlinnot** [comment]
I'm also experiencing this issue when using the library in a Web Worker. In Web Workers, the API is actually available, but you need to access it through `self`, not `window`. So I'd suggest to fix it by checking both references if that's possible.

**Comment by schmidt-sebastian** [comment]
We are going to revert this "crypto" change for now and will release a version that will support WebWorkers and IE11 shortly after.
