### ISSUE TITLE
Firestore emulator: Seeing "invalid wire type 4" occasionally

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-js-sdk#2894]
### Environment

  * Operating System version: macOS 10.15.4
  * Browser version: (no browser involved)
  * Firebase SDK version: 8.0.2
  * Firebase Product: firestore

### Problem

I'm getting this on console, running tests against a locally running Firestore emulator:

```
console.error node_modules/grpc/src/common.js:62
    Response deserialization failed: invalid wire type 4 at offset 198
```

It looks strange. It's certainly a protobuf mismatch, but I shouldn't be aware of those as a Firebase-tools user, right?

I've tried so far:
- `rm -rf node_modules; npm install`. Did not help

More details (including steps to reproduce) are described in [this issue at my repo](https://github.com/akauppi/GroundLevel-es6-firebase-web/issues/10). (you'll need to clone the repo so you could check the symptoms there, I assume..)

**Comment by rafikhan** [comment]
@akauppi - it looks like you've resolved your own issue by updating to a newer version of `@firebase/testing` to 0.19.0. I'm going to close this issue out.
