### ISSUE TITLE
auth.js throws a javascript error with minified version

### ISSUE THREAD

**Issue by hrasoa** [firebase/firebase-js-sdk#290]
* Operating System version: Mac Os
  * Firebase SDK version: 4.6.0
  * Firebase Product: auth

#### Steps to reproduce:
I have this error with minified version when I try to register a new user with ```
firebase.auth().createUserWithEmailAndPassword```:

![capture d ecran 2017-11-02 a 23 46 50](https://user-images.githubusercontent.com/796524/32354099-80aa1430-c028-11e7-8f14-e7d45cb223de.png)

#### Relevant Code:

index.js
```javascript
import * as firebase from 'firebase/app';
import 'firebase/auth';

firebase.initializeApp({ ... });
```

On a user action somewhere in my app:

```javascript
firebase.auth().createUserWithEmailAndPassword(email, password)
    .catch(err => ({ error: err.message }));
```

The user is created on firebase side, but I got the error on the return.
I am using ```webpack``` and ```babili-webpack-plugin``` (without any options) for the minifications.

**Comment by bojeil-google** [comment]
Can you provide the Firebase version you are using? Is this a regression? Can you pinpoint the version where this started happening?

**Comment by hrasoa** [comment]
I updated the ticket it the right version:  4.6.0

**Comment by bojeil-google** [comment]
Can you downgrade to 4.5.1 and 4.5.0 and try again?

**Comment by hrasoa** [comment]
Same issue with both versions

**Comment by hrasoa** [comment]
Seems like I found the issue.
in @firebase/auth/dist/auth.js, we actually have:

```javascript
h.dispatchEvent = function(a) {
  re(this);
  var b = this.Kd;            
  if (b) {
    var c = []; // <-- issue here
    for (var d = 1; b; b = b.Kd)
      c.push(b),
        w(1E3 > ++d, "infinite loop")
  }
  ...
  ...
  if (c)
    for (var f = c.length - 1; !a.Wa && 0 <= f; f--) {
```
But should have been:
```javascript
h.dispatchEvent = function(a) {
  re(this);
  var b = this.Kd;            
  var c = []; // <-- works
  if (b) {
    for (var d = 1; b; b = b.Kd)
      c.push(b),
        w(1E3 > ++d, "infinite loop")
  }
  ...
  ...
  if (c)
    for (var f = c.length - 1; !a.Wa && 0 <= f; f--) {
```
I edited the files in the node modules and it works.

**Comment by bojeil-google** [comment]
We just open sourced and we have had the first build using the open source code published today in `4.6.1`. Do you still encounter that in the latest version?

**Comment by hrasoa** [comment]
It works with ```4.6.1``` !  Thank you for your help.

**Comment by bojeil-google** [comment]
Cool! Thanks for confirming. Glad it works.
