### ISSUE TITLE
Unable to set up a project for local unit-testing (HTTP Error: 404)

### ISSUE THREAD

**Issue by IjzerenHein** [firebase/firebase-js-sdk#2912]
### Describe your environment

  * Operating System version: OSX 10.15.4
  * Node version: 10.16.0
  * Firebase CLI (firebase-tools): `6.5.0` and `8.0.3`

### Describe the problem

Setting up a new Firebase project in order to run the unit tests locally fails with:

```
FirebaseError: HTTP Error: 404, Project 'fir-js-sdk-test' does not exist
```

#### Steps to reproduce:

* Clone the `firebase-js-sdk` repo
* Install packages (`yarn install`)
* Run `yarn test` (it prompts to specify a Firebase project for testing)
* Create new empty project on `https://console.firebase.google.com/`
* Run `yarn test:setup` and select the new project

The following error occurs:

```
hein@MacBook-Pro-van-Hein firebase-js-sdk % yarn test:setup
yarn run v1.21.1
$ node tools/config.js
✔ Preparing the list of your Firebase projects
? Which project would you like to use to test? firebase-js-sdk-test (fir-js-sdk-test)
{ FirebaseError: HTTP Error: 404, Project 'fir-js-sdk-test' does not exist.
```

**Comment by hsubox76** [comment]
Can I ask you to clear up which error you are getting, the 403 or the 404?  Did you get them at different times?

If 403, does the account you are currently logged into the CLI with match the one you used to create the project in the console?  Is it listed as an editor or owner of that new project?

**Comment by katowulf** [comment]
As Christina mentioned, please start by trying `firebase logout` and then `firebase login`. Make sure the account logged in with has access to the project in the console. If still failing, please include a minimal repro, with the test units, and the yarn config file, as well as any other supporting files needed to run the test locally. Obviously we'd run this against our own test project, but without a minimal, complete repro, it's going to be hard to sort this one out.

**Comment by IjzerenHein** [comment]
> Can I ask you to clear up which error you are getting, the 403 or the 404? Did you get them at different times?
> 
> If 403, does the account you are currently logged into the CLI with match the one you used to create the project in the console? Is it listed as an editor or owner of that new project?

So it seems the first time I tried this I got the 403 error yesterday. Now I only seem to get the 404 error (tested a couple times today with both CLI 6.5.0 and 8.03).
I've update the issue description accordingly to only include the 404.

> If 403, does the account you are currently logged into the CLI with match the one you used to create the project in the console? Is it listed as an editor or owner of that new project?

Yes I've checked both Firebase projects I tested with were newly created and I'm the owner of both of them.

**Comment by IjzerenHein** [comment]
> As Christina mentioned, please start by trying firebase logout and then firebase login.

I've logged out (`firebase logout`) and logged back in again (`firebase login`). Still getting the same 404 error.

> Make sure the account logged in with has access to the project in the console.

I checked, the account is the owner of the selected project.

![image](https://user-images.githubusercontent.com/6184593/79426470-7d8d8b80-7fc3-11ea-8914-4f2e7e98f258.png)


> If still failing, please include a minimal repro, with the test units, and the yarn config file, as well as any other supporting files needed to run the test locally. Obviously we'd run this against our own test project, but without a minimal, complete repro, it's going to be hard to sort this one out.

So to recap. I'm investigating on creating a PR for the `firebase-js-sdk` repo. But in order to do this I want to run its unit tests locally. I'm trying to follow the PR guidelines as mentioned here: https://github.com/firebase/firebase-js-sdk/blob/master/CONTRIBUTING.md#pull-request-guidelines
It mentions to run `npm test`, but in order to do that I need to setup a firebase project for that. I'm assuming a blank Firebase project should work.

The steps to repro are in the description:

* Clone the `firebase-js-sdk` repo
* Install packages (`yarn install`)
* Run `yarn test` (it prompts to specify a Firebase project for testing)
* Create new empty project on `https://console.firebase.google.com/`
* Run `yarn test:setup` and select the new project

**Comment by IjzerenHein** [comment]
FYI, here is the stack-trace of the error:

```
hein@MacBook-Pro-van-Hein firebase-js-sdk % yarn test:setup
yarn run v1.21.1
$ node tools/config.js
✔ Preparing the list of your Firebase projects
? Which project would you like to use to test? firebase-js-sdk-test (fir-js-sdk-test)
{ FirebaseError: HTTP Error: 404, Project 'fir-js-sdk-test' does not exist.
    at module.exports (/Users/hein/repos/firebase-js-sdk/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/Users/hein/repos/firebase-js-sdk/node_modules/firebase-tools/lib/api.js:39:35)
    at Request.self.callback (/Users/hein/repos/firebase-js-sdk/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/hein/repos/firebase-js-sdk/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/hein/repos/firebase-js-sdk/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FirebaseError',
  children: [],
  context:
   { body: { error: [Object] },
     response:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [ClientRequest],
        request: [Request],
        toJSON: [Function: responseToJSON],
        caseless: [Caseless],
        body: [Object] } },
  exit: 1,
  message:
   'HTTP Error: 404, Project \'fir-js-sdk-test\' does not exist.',
  original: undefined,
  status: 404 }
error Command failed with exit code 1.
```

**Comment by Feiyang1** [comment]
Since you are able to see and select the project in the previous step, your login is probably not the problem. Folks from `firebase-tools` (the library we use under the hood) might be able to help. @mbleigh, any idea?
`firebaseTools.projects.list({ token })` was successful, and a project was selected. we use the projectId from the selected project to call `firebaseTools.setup.web({ project, token })` which failed with `Project \'fir-js-sdk-test\' does not exist.'`.

[source code ](https://github.com/firebase/firebase-js-sdk/blob/master/tools/config.js#L50-L83)

**Comment by bodazhao** [comment]
> #### Steps to reproduce:
> * Clone the `firebase-js-sdk` repo
> * Install packages (`yarn install`)
> * Run `yarn test` (it prompts to specify a Firebase project for testing)
> * Create new empty project on `https://console.firebase.google.com/`
> * Run `yarn test:setup` and select the new project
> 
> The following error occurs:

Have you tried to run `yarn build` after `yarn install`? 

I had a `403` error while following the README, but soon realised it was my fault for somehow skipping `yarn build` and after that, the `403` error was fixed 🤦‍♂️

**Comment by IjzerenHein** [comment]
Omg that was it, it immediately started working after running `yarn build`. I must have completely overlooked that in the instructions. Thanks for clarifying @bodazhao !
