### ISSUE TITLE
FR: Add the word listener to onAuthStateChanged so people know it's a listener

### ISSUE THREAD

**Issue by 619** [firebase/firebase-js-sdk#2942]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Catalina 15.10.4
  * Browser version: Chrome 80
  * Firebase SDK version: Not sure
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
onAuthStateChanged is a listener that does not have the word "listener" in its name. It would be prudent to add the word listener to its name so that people don't mistake it for something else.
#### Steps to reproduce:
None.

**Comment by hsubox76** [comment]
I can let the auth team answer but I believe beginning a method name with `on` is a pretty standard naming convention for any listeners. The DOM itself uses `onClick`, `onChange` etc. for event listeners, and other Firebase libraries use it for subscriptions, such as Firestore's `onSnapshot` or RTDB's `on('value')`.

**Comment by 619** [comment]
You're right about that. However, if a naming convention requires common sense to understand then it's not a great naming convention. There is a higher than normal occurrence of autistic tendencies among developers, and autistic people lack common sense. If you believe some of the rumours about the peculiar behaviour about a certain google founder, then it's not far of a stretch to reasonably assume that he might make the same mistake I made if he was using Firebase.
