### ISSUE TITLE
FR: Allow providing own generics for Typescript

### ISSUE THREAD

**Issue by diminishedprime** [firebase/firebase-js-sdk#2959]
Hi, I wanted to file this issue to see if there's interest in merging this in before starting work on a PR.

## Proposal

To be able to provide my own generic bounds for `firebase.firestore.doc()`, `firebase.firestore.collection()`, etc. 

### What might this look like

```
import firebase from 'firebase/app'

interface Person {
  username: string,
}

const getPerson = (userId: string): Promise<Person | undefined> => {
  // Developer can provide their own generic to doc, etc. 
  return firebase.firestore.collection('users').doc<Person>(userId).get().data();
}
```

### What this would _not_ do

Runtime validation that the type asserted by the user is actually correct. It would still be up to the user to validate that the data from the collection has the correct structure to be used. 

### Why is this useful

By being able to add type bounds for values returned by firestore, it is easier to have the compiler help you avoid some mistakes.

Eg

```
const getPerson = async (userId: string): Promise<Person | undefined> => {
  // Should have called .get(), so this is actually a DocumentReference, not the 
  // data from inside, but since the developer wanted to assert their own type, 
  // they added the as any at the end which throws away checking. 
  return firebase.firestore.collection('users').doc(userId).get() as any;
}

const doThingWithPerson = async () => {
  const person = await getPerson('abcdef');
  // Calling `indexOf` on an undefined value, but typesystem didn't help. 
  person.username.indexOf('a')
}

```

**Comment by hsubox76** [comment]
If I'm understanding your request correctly, generic types for Firestore collections, documents, and queries were added in 7.6.0 ([release notes](https://firebase.google.com/support/release-notes/js#cloud-firestore_14))

Reference docs for `withConverter()` method here: https://firebase.google.com/docs/reference/js/firebase.firestore.Query#withconverter

**Comment by diminishedprime** [comment]
Excellent! That's exactly what I was hoping for. I was gonna follow up with a request to pass your own serializer/deserializer, but looks like that update handles everything!
