### ISSUE TITLE
[GitHub API] Deprecation notice for OAuth Application API

### ISSUE THREAD

**Issue by yeldarby** [firebase/firebase-js-sdk#2962]
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: Chrome 81
  * Firebase SDK version: 7.13.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem
We got an email from github that our Firebase Auth app is using a deprecated endpoint that will be discontinued in ~2 weeks.

#### Steps to reproduce:
Use `auth` with `firebase.auth.GithubAuthProvider.PROVIDER_ID`

#### Relevant Code:

> Hello there!
> 
> On April 21st, 2020 at 13:20 (PDT), your application (Roboflow) issued a request using the deprecated form of OAuth Application API that includes access tokens in the URL path. GitHub has deprecated these endpoints and replaced them with a version that accepts access tokens in the request body.
> 
> The deprecated endpoints will be removed on May 5th, 2021 at 4:00 PM UTC.
> 
> Please visit https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint for more information about suggested changes, brownouts, and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by bojeil-google** [comment]
Thanks for filing this. I have relayed this issue to the right folks internally. I would also recommend you file a [support ticket](https://firebase.google.com/support) to track the status.

**Comment by bojeil-google** [comment]
We will work on fixing this. The shutdown date is actually a year from now (May 5th, 2021) and not 2 weeks from now. We should have it fixed long before that.

**Comment by yeldarby** [comment]
Ah phew! 😅

**Comment by bojeil-google** [comment]
Hey @yeldarby, the fix should be in production now. You should no longer be getting these email notifications.
