### ISSUE TITLE
IncludesMetadataChange does not re-fires with the changed doc

### ISSUE THREAD

**Issue by Pitouli** [firebase/firebase-js-sdk#2981]
### Describe your environment

  * Operating System version: Mac OS 10.15
  * Browser version: Chrome 81
  * Firebase SDK version: 7.14.2
  * Firebase Product: firestore

### Describe the problem

I have a list of documents to display.
I want to show a spinner when a document has updates non confirmed from the server.
If the document has `hasPendingWrites === true` I show my spinner, otherwise I hide it.

I use the option `includeMetadataChanges`, and I observe the following:

- When I modify my document, I immediately receive an update with a list of (generally 1) document changes with `metadata.hasPendingWrites===true`
- Then I receive a second update. But this one does not have any docChanges, so I cannot update my document status

Note: I cannot use Promises, for 2 raisons:

1. it is not the recommended way to go with Vuex
2. More importantly, the user can be offline, so he kills the app before the Promise resolves. But I still wants to show that the document is not synced when the app reopens.

Concerning point 2, it works perfectly well: when app is reopened, still offline, only the modified documents have a `hasPendingWrites` state at `true`.

#### Relevant Code:

Here is my code. When I modify a document, I receive a `Hello` and `Bonjour` immediately. Then, once the server has confirmed the update, I receive a new `Hello`, but no `Bonjour`.

        const unbind = firestoreRef.onSnapshot(
          { includeMetadataChanges: true },
          (ref) => {
            console.log('Hello!');
            ref.docChanges().forEach((change) => {
              console.log('Bonjour!');
              commit('objectChange', { collection, ...change });
            });
            commit('dbLoaded', { collection, loaded: true });
          },
          error => console.error(error),
        );

**Comment by schmidt-sebastian** [comment]
@Pitouli Thanks for filing.

Please update you code to also pass `{ includeMetadataChanges:true }` to [docChanges()](https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot#docchanges).

**Comment by Pitouli** [comment]
Thanks a lot! You're blazing fast! 😃 

If I may, perhaps an update of the Documentation is necessary? I believe I haven't seen anywhere any example or warning about the necessity of doubling the parameter.

_On the other hand, if I'm the only one to raise the problem, it's probably between my seat and my screen!_

**Comment by schmidt-sebastian** [comment]
I agree that the documentation is not all that great: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L9184. We should improve upon this, but to make this a team effort, I was wondering if you could tell us what you would like to see there?

**Comment by Pitouli** [comment]
@schmidt-sebastian : I would concentrate my efforts on the Guide, which is --at least for me-- the main entry point to understand the possibilities of Firestore. I only use the References to deepen some understanding.

Concerning our topic, I would update this part:
https://firebase.google.com/docs/firestore/query-data/listen#events-metadata-changes

> If you want to receive snapshot events when the document or query metadata changes, pass a listen options object when attaching your listener

Could become something like:

> If you want to receive snapshot events when the document or query metadata changes, pass a listen options object when attaching your listener. If the listener is attached to a collection, pass the same listen options object when looping over the docChanges

And I would replace the code example by the following:

```
// For documents
db.collection("cities").doc("SF")
    .onSnapshot({
        // Listen for document metadata changes
        includeMetadataChanges: true
    }, function(doc) {
        // ...
    });

// For collections
db.collection("cities")
    .onSnapshot({
        // Listen for document metadata changes
        includeMetadataChanges: true
    }, function(ref) {
        // Loop over changes, including metadata only changes
        ref.docChanges({ includeMetadataChanges: true }).forEach((doc) => {
          // ...
        });
    });
```

Finally, one question: is there situations where a user could want to include MetadataChanges in his listener, but not in the docChanges? 
If not, would it be possible to default "docChanges" to use the same behavior than the listener that call it, except if the user explicitly provides a parameters saying the opposite?

**Comment by schmidt-sebastian** [comment]
@Pitouli Thanks for this! I will forward this to our docs writer. 

To answer your question: If you are only interested in the `fromCache` state, it might make sense to use the top-level  `include MetadataChanges` but filter out `hasPendingWrite` updates by not specifying it a second time in `docChanges`.

**Comment by schmidt-sebastian** [comment]
Filed b/155351977
