### ISSUE TITLE
"Error in onSnapshot: FirebaseError: The query requires an index. You can create it here:" Error doesn't work with multiple logins

### ISSUE THREAD

**Issue by josh-m-sharpe** [firebase/firebase-js-sdk#2989]
Env:

  * Operating System version: OSX 10.15.4
  * Browser version: Brave: Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
  * Firebase SDK version: 7.14.1
  * Firebase Product: firestore

This is probably a larger/general issue related to how Google after literally decades, still hasn't implemented multiple logins well across their developer sites.  I'm looking at you Google Play Console.

Step1: In browser, log into multiple Google accounts: e.g. work/personal/whatever
Step2: hack on a firebase, build a query where an index hasn't been created
Step3: See error like:
```
Error in onSnapshot: FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/myproj/firestore/indexes?create_composite=somekeyetc
```
Step4: follow link, but get redirected to Google Cloud Platform as the "first" account you logged in with and see this error: 
You do not have sufficient permissions to view this page

This wouldn't be a huge issue, except the fix is wildly inconvenient.   You have to:
1) Log out of all your google accounts
2) Ensure you log into the correct developer account first
3) re-visit that link

The huge issue here, is this logs me out of all windows/tabs.  It's not super fun to have to reload them all.

I realize there are possible workarounds here, like:

1) use incognito/private mode
2) always login to my "developer" account "first"

...but these are just crutches. It would be better if google redirected appropriately.

**Comment by schmidt-sebastian** [comment]
@josh-m-sharpe Thanks for the feedback! Unfortunately, as you may have expected, this is not something we can address in the SDK or even in Firestore as a whole. The error message you are seeing is actually an error message that is visible externally (e.g. in the developer console of your customer). Not revealing which Google identities act as project owners in an important step in securing your project.

**Comment by josh-m-sharpe** [comment]
@schmidt-sebastian `Unfortunately, as you may have expected, this is not something we can address in the SDK or even in Firestore as a whole.` 

Yet it's still a problem with the SDK.  *Your* user experience is undermined by upstream issues. Just because the problem doesn't exist in this project doesn't mean it's a non-issue here.

Instead of closing the issue and ignoring it, you could instead work with your people inside Google to address the issue.

Your response is just sweeping it under the rug.
