### ISSUE TITLE
remoteConfig.getString doesn't return values for conditions based on user properties

### ISSUE THREAD

**Issue by shtengel** [firebase/firebase-js-sdk#2990]
Having the same problem as described here:
https://github.com/firebase/firebase-js-sdk/issues/2221

i have a site which uses RemoteConfig values for US and i want different values for Canada but if i change the userproperty `country` to Canada it still fetches the US configuration..
how can i force and immidiately fetch the correct configuration ?

**Comment by shtengel** [comment]
i just need the first fetch to be based on a Condition and then 12 hours update is fine. how do i fetch ?

**Comment by shtengel** [comment]
anyone ?

**Comment by dwyfrequency** [comment]
@shtengel this issue hasn't been updated for years. Is this still an issue?

**Comment by shtengel** [comment]
Probably, in the end I used a different library so I don't know if it's still an issue.. thanks!
