### ISSUE TITLE
TypeError: e.addEventListener is not a function - Firestore (Expo)

### ISSUE THREAD

**Issue by tomadimitrie** [firebase/firebase-js-sdk#2991]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.3
  * Browser version: - (Expo SDK 37)
  * Firebase SDK version: 7.14.2
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

Running any query to Firestore throws this error:

`[Unhandled promise rejection: TypeError: e.addEventListener is not a function. (In 'e.addEventListener("visibilitychange", this.ah)', 'e.addEventListener' is undefined)]`

#### Steps to reproduce:

Initialize Firebase, then run any query.

#### Relevant Code:

```ts
static subscribeToAvailableRides(callback: (rides: Ride[]) => void) {
    return firebase
      .firestore()
      .collection("rides")
      .where("driver.id", "==", null)
      .onSnapshot((docs) => {
        callback(
          docs.docs.map(doc => doc.data())
        );
      });
  }
```

**Comment by snownoop** [comment]
Having same issue. Did not have solution right now.
There is also same topic on stackoverflow:
https://stackoverflow.com/questions/61429599/error-cloud-firestore-addeventlistener-is-not-a-function-react-native-firestor

Any ideas ?

**Comment by tomadimitrie** [comment]
> Having same issue. Did not have solution right now.
> 
> There is also same topic on stackoverflow:
> 
> https://stackoverflow.com/questions/61429599/error-cloud-firestore-addeventlistener-is-not-a-function-react-native-firestor
> 
> 
> 
> Any ideas ?

I am using Expo so I ran `expo install firebase` and it installed 7.9.0 and the error was gone

**Comment by schmidt-sebastian** [comment]
@tomadimitrie Thanks for this report. We added a `window. addEventListener()` call that is executed when `window` is defined. I will add a check to only call `addEventListener` when it `window.addEventListener` exists.

**Comment by gwendall** [comment]
@tomadimitrie in the meantime, mock it by putting something like `window.addEventListener = x => x` at the top level of your code

**Comment by tomadimitrie** [comment]
@gwendall thank you. One question, is the last version of the Firebase JS SDK fully compatible with Expo? For some reason running `expo install firebase` installs version 7.9.0 and I don't know whether to stick with that or upgrade to the latest version

**Comment by edi** [comment]
@tomadimitrie that's not something firebase contributors can answer. Look for @evanbacon on the `expo-cli` repo.

Regards!

**Comment by tomadimitrie** [comment]
@edi thanks!

**Comment by snownoop** [comment]
installing 7.9.0 helped me. Will check later if it can work with higher versions of firebase.
I also did cache clean, and watchman delete all. Then restart and all is working fine.

**Comment by schmidt-sebastian** [comment]
This will be fixed in our release next week. We are not doing any releases this week.

**Comment by BrianGuerra2019** [comment]
I have tried several versions and none of them works, when downloading some previous version, the error disappears but the connection to firebase stops working, even with version 7.14.1

**Comment by edi** [comment]
> This will be fixed in our release next week. We are not doing any releases this week. Please either downgrade to 7.14.1 or define `window.addEventListener`.

RN/Expo users will have to define `global.addEventListener`.
