### ISSUE TITLE
FR: Generic Types for RxFire library (Typescript)

### ISSUE THREAD

**Issue by alexbchr** [firebase/firebase-js-sdk#2996]
### [REQUIRED] Describe your environment

  * Platform: React-Native (Expo + Typescript) (using Firebase JS Web Version)
  * Firebase SDK version: 7.14.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When using RxFire library, generic types from Firestore are lost. What I mean by this is that generics in `CollectionRef`,  `DocumentRef` and `Query` firestore objects are lost when using RxFire functions like `fromCollectionRef`, `docData`, `collectionData`, etc.

Sample code: 
```typescript
interface Post {
  id: string
  title: string
  content: string
}

const getPosts = (): Observable<Post[]> => {
  // Get CollectionReference<Post>
  const firestoreRef = firebase.firestore().collection('posts') as firebase.firestore.CollectionReference<Post>

  // fromCollectionRef just takes a firebase.firestore.Query type, with no generic type provided,
  // fallbacking to default DocumentData, even though if query is typed.
  return fromCollectionRef(firestoreRef).pipe(
    // x.data() has Firestore type DocumentData here and should have custom Post type.
    map(snapshot => snapshot.docs.map(x => x.data()) 
}
```

On a separate note, firestore functions like `collection()` or `doc()` should accept a generic parameter to override the `DocumentData` type, therefore preventing the need to cast the return type.

**Comment by var-const** [comment]
Can you please file this issue in the [React Native Firebase issue tracker](https://github.com/invertase/react-native-firebase/issues)? This repo is for the Firestore Web SDK, whereas React Natives Firebase modules are a separate product. Sorry about the trouble!

**Comment by alexbchr** [comment]
The issue I have is using the Firebase JS SDK (non react-native one) with RxFire, since I use Expo. I don't use the React Native Firebase library.

What I have in my `package.json`:
```
"dependencies": {
  // Other deps
  "firebase": "7.14.1",
  "rxfire": "^3.9.13"
}
```

**Comment by var-const** [comment]
Apologies, I have misread that. I will assign the issue to somebody working on `RxFire`.

> firestore functions like `collection()` or `doc()` should accept a generic parameter to override the `DocumentData` type, therefore preventing the need to cast the return type.

The intended way to achieve this is by using [`withConverter`](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#withconverter):
```typescript
const colRef = db
    .collection('posts')
    .withConverter({
        toFirestore(post: Post): firestore.DocumentData {
          return { id: post.id, title: post.title, content: post.content };
        },
        fromFirestore(
          snapshot: firestore.QueryDocumentSnapshot,
          options: firestore.SnapshotOptions
        ): Post {
          const data = snapshot.data(options);
          return new Post(data.id, data.title, data.content);
        }
    });
```
(see [`FirestoreDataConverter` docs](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter))

Note that casting might result in problems because the resulting object will fail an `instanceof(Post)` check (and should `Post` ever have its own methods, the cast object will be missing them).

**Comment by alexbchr** [comment]
Hmmm yes I was aware of the `withConverter` function. However we decided not to use it for now, as we simply use Typescript Interfaces representing the Firestore schema. I understand though that you want to force people to use converters to prevent comprehension issues.

Thanks for following this up!

**Comment by romain-faust** [comment]
Hi,

We encounter the same issue with generic types when using the RxFire library. Despite using `withConverter` the returned type is not correct.

**_Example:_**

```ts
import { app, firestore } from 'firebase/app';
import { doc } from 'rxfire/firestore';

type User = {
    readonly id: string;
    readonly name: string;
};

const userConverter: firestore.FirestoreDataConverter<User> = {
    fromFirestore: (snapshot) => ({
        id: snapshot.id,
        name: snapshot.get('name'),
    }),
    toFirestore: (user) => ({
        name: user.name,
    }),
};

const getUser = (id: string) => {
    const userRef = app()
        .firestore()
        .collection('users')
        .doc(id)
        .withConverter(userConverter);

    // Should return `Observable<firestore.DocumentSnapshot<User>>` but
    // returns `Observable<firestore.DocumentSnapshot>`
    return doc(userRef);
};
```

After looking at the source code, I noticed that generic types are not taken into account. I can open a PR to solve the problem, but I want to be sure that it will be taken into account before investing time on it.

**Comment by var-const** [comment]
@romain-faust A PR would be very welcome. Thanks!

**Comment by romain-faust** [comment]
@var-const https://github.com/firebase/firebase-js-sdk/pull/3239

**Comment by jamesdaniels** [comment]
We're addressing in the new dedicated RxFire repo https://github.com/FirebaseExtended/rxfire/pull/10
