### ISSUE TITLE
Firestore API seems to be stuck in debug console mode

### ISSUE THREAD

**Issue by geelen** [firebase/firebase-js-sdk#300]
Can't figure out a way to stop getting this kind of output with a new Firestore app:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/23264/32476936-d2e6beac-c3ce-11e7-904f-0935ebc11701.png">

From reading some source, I found a function called `setLogLevel` but calling

```js
firebase.firestore.setLogLevel('silent')
```

before or after `const db = firebase.firestore()` doesn't seem to do anything. New to this so maybe missing something obvious but it's making my console fairly noisy...

**Comment by mikelehen** [comment]
Can you try https://www.gstatic.com/firebasejs/4.6.2/firebase-firestore.js and see if it goes away?

**Comment by geelen** [comment]
Yep, `4.6.2` appears to have fixed the issue, cheers.

**Comment by mikelehen** [comment]
Great! Thanks for following up.
