### ISSUE TITLE
InvalidStateError: IDBDatabase.transaction: Can't start a transaction on a closed database

### ISSUE THREAD

**Issue by AoDev** [firebase/firebase-js-sdk#3008]
### Describe your environment

  * Operating System version: Mac OS X 10.15
  * Browser version: Firefox 75.0
  * Firebase SDK version: 7.6.1
  * Firebase Product: not sure (auth, database, storage, etc)

### Describe the problem

I have this error being thrown recently in Firefox: 
`InvalidStateError: IDBDatabase.transaction: Can't start a transaction on a closed database`

It seems to come from Firebase. 

### From a _sentry.io_ report .

```
mechanism: instrument
handled: yes
function: setTimeout
```
|  Time    |  type  |         Req                                                              |
|----------|-----|-----------------------------------------------------------------------|
|04:04:27|xhr|POST https://securetoken.googleapis.com/v1/token?key=EDITED [200]
|04:04:30|xhr|POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=EDITED [200]
|04:04:32|xhr|GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F[EDITED_PROJECT]]%2Fdatabases%2F(default)&gsessionid=[EDITED]&VER=8&RID=rpc&SID=[EDITED]&AID=219&TYPE=xmlhttp&zx=t4fi495rfwy3&t=1 [0]
|05:06:04|xhr|POST https://securetoken.googleapis.com/v1/token?key=EDITED [200]
|05:06:05|xhr|GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F[EDITED_PROJECT]]%2Fdatabases%2F(default)&gsessionid=[EDITED GSESSION ID 1]&VER=8&RID=rpc&SID=[EDITED SID 1]&CI=0&AID=193&TYPE=xmlhttp&zx=u1tnq6vcqjt&t=1 [0]
|06:09:06|xhr|POST https://securetoken.googleapis.com/v1/token?key=EDITED [200]
|06:14:00|xhr|GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F[EDITED_PROJECT]]%2Fdatabases%2F(default)&gsessionid=[EDITED GSESSION ID 2]&VER=8&RID=rpc&SID=[EDITED SID 2]&CI=0&AID=190&TYPE=xmlhttp&zx=ankhy1dr47t4&t=1 [0]
|07:11:08|xhr|POST https://securetoken.googleapis.com/v1/token?key=EDITED [200]
|07:11:08|xhr|GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F[EDITED_PROJECT]]%2Fdatabases%2F(default)&gsessionid=[EDITED GSESSION ID 3]&VER=8&RID=rpc&SID=[EDITED SID 3]&CI=0&AID=55&TYPE=xmlhttp&zx=bglarmnayfp4&t=1 [0]
|07:28:45|xhr|GET https://apido-dev.battletraders.io/market/ohlcv?interval=5s [200]
|07:46:09|xhr|GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F[EDITED_PROJECT]]%2Fdatabases%2F(default)&gsessionid=[EDITED GSESSION ID 3]&VER=8&RID=rpc&SID=[EDITED SID 3]&CI=0&AID=187&TYPE=xmlhttp&zx=xei5wa9v6glp&t=1 [0]
|08:12:39|xhr|POST https://securetoken.googleapis.com/v1/token?key=EDITED [200]
|08:12:41|xhr|GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F[EDITED_PROJECT]]%2Fdatabases%2F(default)&gsessionid=[EDITED GSESSION ID 4]&VER=8&RID=rpc&SID=[EDITED SID 4]&CI=0&AID=186&TYPE=xmlhttp&zx=uya7mg2uaj68&t=1 [0]
|09:13:41|xhr|POST https://securetoken.googleapis.com/v1/token?key=EDITED [200]
|09:13:42|exception|Error: InvalidStateError: IDBDatabase.transaction: Can't start a transaction on a closed database|

#### Steps to reproduce:
From the user feedback, it happens after leaving the app for a while and then come back to it.

**Comment by var-const** [comment]
Sorry to hear about your issue. We would need more information to be able to investigate. Is this error reproducible? Would it be possible for you to [enable logging](https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel) and provide the logs (omitting any sensitive information)?

**Comment by AoDev** [comment]
@var-const I'll try to reproduce it but it seems I'd need to let Firefox/computer idle for some time so it might take a while.

So far I've found this answer in SO that could be relevant:
https://stackoverflow.com/questions/13972385/invalidstateerror-while-opening-indexeddb-in-firefox#answer-45672895

**Comment by Frenchcooc** [comment]
I'm getting this error for each user running Firefox, presumably in incognito mode. Other browsers are not impacted. Here's a screenshot from Bugsnag reporting the issue in production:

<img width="1151" alt="Screenshot 2021-04-06 at 23 01 45" src="https://user-images.githubusercontent.com/3255133/113777977-19139100-972c-11eb-9d6c-594dba18aa5a.png">

Anything we could do to help Firefox users?
