### ISSUE TITLE
Testing collection group queries always succeeds

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-js-sdk#3028]
The @firebase/testing library won't handle collection group queries properly.

### Environment info

**firebase-tools:** 8.2.0

**Platform:** macOS

### Test case

See the attached ZIP
[firestore-collectionGroup-emulators-test.zip](https://github.com/firebase/firebase-tools/files/4581849/firestore-collectionGroup-emulators-test.zip)

### Steps to reproduce

**firestore.rules:**

```
rules_version = '2';

service cloud.firestore {
  match /{path=**}/videos/{video} {
    allow read: if true;
  }
}
```

**Test script:**

```js
firebase.assertSucceeds(db.collectionGroup("videos").get());
firebase.assertFailed(db.collectionGroup("videos").get());
```

### Expected behavior

Either:
```js
firebase.assertSucceeds(db.collectionGroup("videos").get());
```

or:

```js
firebase.assertFailed(db.collectionGroup("videos").get());
```

succeeds while the other is rejected.

### Actual behavior

Errors are logged silently, but both promises are returning successfully, thus all test cases won't work.

**Comment by IchordeDionysos** [comment]
@yuchenshi is there any update on this?

**Comment by yuchenshi** [comment]
> @yuchenshi is there any update on this?

Sorry, I don't have any specific updates at this point. Is this issue still present in the latest version of `@firebase/testing` and Firestore SDK? If so, just let me know the versions.

Also, given that the `@firebase/testing` assert succeeds / assert fails are just thin wrappers around the promises, can someone also try without `@firebase/testing`? Just initialize the Node.js Client SDK (`firebase`, not the Admin SDK `firebase-admin`!) directly and see how those promises behave. There is a good chance this affects all Node.js clients as well.

**Comment by IchordeDionysos** [comment]
@yuchenshi sorry this took such a while :D

I've tested it now directly with the `firebase` package and I get an error there.
Then I was wondering if the error is still there for the `@firebase/testing` package.

To test it, I 
- downloaded my own ZIP file I made back then, 
- replaced the project ID, 
- ran `cd firestore`
- ran `yarn remove @firebase/testing`
- ran `yarn add @firebase/rules-unit-testing`
- ran `yarn add firebase-admin`
- replace `@firebase/testing` with `@firebase/rules-unit-testing` in `tests.ts`
- started a Firestore emulator using `firebase emulators:start --only firestore`
- ran `yarn test`.

The output I got was this:

```js
yarn run v1.22.10
warning package.json: No license field
$ tsc
$ mocha --timeout=10000


Warning: FIRESTORE_EMULATOR_HOST not set, using default value localhost:8080
  MyApp
    ✓ test collection group query succeeds (642ms)
(node:9053) UnhandledPromiseRejectionWarning: FirebaseError: No matching allow statements
    at new FirestoreError (/Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:153:28)
    at fromRpcStatus (/Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:4667:12)
    at fromWatchChange (/Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:4903:35)
    at PersistentListenStream.onMessage (/Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:12913:27)
    at /Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:12846:30
    at /Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:12882:28
    at /Users/dennis/Downloads/firestore-collectionGroup-emulators-test/firestore/node_modules/@firebase/firestore/dist/index.node.cjs.js:14472:20
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:9053) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9053) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    ✓ test collection group query fails (119ms)

View rule coverage information at http://localhost:8080/emulator/v1/projects/simpleclub-stage:ruleCoverage.html


  2 passing (1s)

✨  Done in 7.07s.
```

So the error gets sent to the console, but the test still succeeds.

**Comment by yuchenshi** [comment]
You need to `await` for the promise so that your tests can fail on it. Otherwise, your tests will return immediately and the Promise will set off on its own, giving you the unhandled rejection warning you see. Example:

```diff
     @test
     async "test collection group query succeeds"() {
         const db = await this._preparePlaylistCollectionGroupQueryTest();
 
-        firebase.assertSucceeds(db.collectionGroup("videos").get());
+        await firebase.assertSucceeds(db.collectionGroup("videos").get());
     }
```

**Comment by IchordeDionysos** [comment]
No way 😂  This is the only test case I missed the await and the only test involving collection group queries ...

Thanks for the good catch 👍
