### ISSUE TITLE
Password Reset not functioning due to one-time use links

### ISSUE THREAD

**Issue by kidGodzilla** [firebase/firebase-js-sdk#3029]
### Describe your environment

  * Operating System version: Cross browser (MacOS+Windows repro)
  * Browser version: Chrome 81.0.4044.129 
  * Firebase SDK version: 7.14.2 (Node.js) 8.11.0 (firebase-admin)
  * Firebase Product: auth

#### Steps to reproduce:

Perform a Firebase Email+password account password reset.

You will be sent a one-time use link via email, which can only be used once.

Problem is, almost every email client follows the link before a human gets to read the email (virus / malware scanning, additional features, etc.). So, a one-time use link to reset a password will not work.

#### Relevant Code:

`firebase.auth().sendPasswordResetEmail(email).then(console.log)`

**Comment by MeghaB** [comment]
@kidGodzilla I'm not able to reproduce this issue - and the one-time link works. If you're running into issues, it might be something specific to your project/configuration. Please file a [ticket with Support](https://firebase.google.com/support/troubleshooter/contact), so we can investigate further!

**Comment by kidGodzilla** [comment]
You can't just send a one-time link in an email. The email client will open it to scan for malware, and the user will never get it.
