### ISSUE TITLE
FR: source option for onSnapshot

### ISSUE THREAD

**Issue by Pitouli** [firebase/firebase-js-sdk#3040]
For `get()` calls, we can pass a `source` option to force the request to be taken from the cache.
https://firebase.google.com/docs/firestore/query-data/get-data#source_options

**Could we have the same option for onSnapshot calls?**

## Use Case

I have an app where my users have around 1000 items which do not evolve so often. I sync them all on the app, which allows me to offer client side research, and others optimizations.

The issue is that every time the user opens the app after more than 30 minutes of inactivity, I have to paid for 1000 readings, even if the data have not changed.

If there was the possibility of forcing the onSnapshot to read from the cache, I could read to my 1000 items collection from the cache, and have another document that stores the number of documents in the db and the date of the last update (easy with cloud functions or batch update). 

I would simply have to add a realtime listener to this document to ensure that my local cache is aligned with the distant database (in case the user has made updates from another device, or has cleared the indexDB on the local device), and only sync the distant version of my collection when I detect a default.

It would make the firestore read drop from [1000 / app opening] to [1 / app opening].

I believe it should be easy to implement since onSnapshot already manages "offline" scenario.

What do you think?

## Note

`disableNetwork()` is not a good solution: I still want to send the writes (create/update/delete) to the server (and use the latency compensation to update my "offline" snapshot), and I need an "online" snapshot on the document that check the current version of the data.

`get()` is not a good solution neither: it would effectively retrieve the data from the cache, but every time the user writes a new data, I would have to manually update my copy. The advantage of onSnapshot is that the latency compensation feature automatically triggers when there are updates, even local and offline.

## Additional scenario

When you update a document, the latency compensation triggers the `onSnapshot` immediately with a `hasPendingWrites` version (we should trigger my "only cache" `onSnapshot` listener).

Also, the update request returns a promise that resolves when the server confirms the correct write. 

**Questions:**
- **if I do a "connected" `get()` on this document once the update resolved, I should obtain a version of the document where `hasPendingWrites` is false, correct?**
- **Will the request on this specific document, that is now updated in the cache, trigger an update on my "cache only" `onSnapshot` listener, so the document is now marked has not having pending writes?**
- **Or even better, will the `hasPendingWrites` flag disappears automatically without having to manually trigger a `get()` request once the write has succeeded?**

If this additional scenario is working, providing a `source` option for onSnapshot would really be a killing feature!

**Comment by wu-hui** [comment]
Hi Pitouli,

Thank you for reporting this issue! 

This has actually been discussed internally before, and we generally feel it is a reasonable request. It is deferred because we don't see users requesting for this, and are not sure how much it'd help.

Now we do have a request, I think we will go back to see if we could start planning for this. 

I'd like to close this issue for now. We will continue update this issue once we have some updates.

**Comment by Pitouli** [comment]
@wu-hui: if this was to be implemented, what would be the minimal delay? Are we speaking of a month-long wait, a year-long wait, or something in between? Thanks in advance for your insight!

**Comment by wu-hui** [comment]
Something in between is most likely, but please note this can change (either direction). I'll bring this up with the team in our next planning meeting, and will update here when we have a decision.

Thanks.
