### ISSUE TITLE
 Unable to register a messaging service worker on a custom path if another service worker is already in place.

### ISSUE THREAD

**Issue by jackie-d** [firebase/firebase-js-sdk#3042]
* Operating System version: Mac OS, Unix Server
  * Browser version: Chrome LTS, Firefox LTS
  * Firebase SDK version: 7.14.2
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

Unable to register a messaging service worker on a custom path if another service worker is already in place.

First one supersedes the chosen one.

#### Steps to reproduce:

```
navigator.serviceWorker.register('my-general-service-worker.js');

const swRegistration = await navigator.serviceWorker.register(
    'my-firebase-messaging-sw.js'
);
messaging.useServiceWorker(swRegistration);
```

Reload the page a second time after first sw get installed.

**Comment by zwu52** [comment]
Hi Jackie,
thanks for filing the ticket. I tried to reproduce in my own test app with 

``` javascript 
navigator.serviceWorker.register("other-sw.js");
navigator.serviceWorker.register("firebase-messaging-sw.js").then((swReg) => {
  messaging.useServiceWorker(swReg);
});
``` 


I am able to see firebase-messaging-sw is registered for the SDK.  If you could create a min repo to reproduce I am happy to help further. (Also, pasting your console log here might be also useful for us)

**Comment by jackie-d** [comment]
Hi, thanks for your answer!

I'll try to investigate more, debug the service worker subscriptions and get back to you with my results!

**Comment by zwu52** [comment]
Closing this ticket since it's been inactive for a while
