### ISSUE TITLE
Error when calling a firestore collection get()

### ISSUE THREAD

**Issue by Migalvao** [firebase/firebase-js-sdk#3047]
Describe your environment

  * Operating System version: Windows10
  * Browser version: Google chrome version 81.0.4044.138 (64 bit)
  * Firebase SDK version: 7.14.2
  * Firebase Product: Cloud Firestore

Describe the problem
When attempting a get() call to a collection stored in my project's firestore database, an exception is thrown: "@firebase/firestore: Firestore (7.14.2): INTERNAL UNHANDLED ERROR:  TypeError: this.tf.has is not a function". Another error is also raised by the same function "TypeError: this.tf.has is not a function".
EDIT: I found out that the same errors are thrown when attempting to set() something. But despite those errors the data is stored in the database! However the get() method never finishes, thus never reaches .then().

#### Steps to reproduce:
Call the get() method in GameEngine.js:
                 db.collection("players")
				.get()
				.then(function (querySnapshot) {
					console.log(querySnapshot);
				});

#### Relevant Code:
INSIDE THE index.html HEADER:

                <script src="https://www.gstatic.com/firebasejs/7.14.2/firebase-app.js"></script>
		<script src="https://www.gstatic.com/firebasejs/7.14.2/firebase-firestore.js"></script>
		<script>
			// Your web app's Firebase configuration
			const firebaseConfig = {
				apiKey: "api key",
				authDomain: "project.firebaseapp.com",
				databaseURL: "https://project.firebaseio.com",
				projectId: "projectid",
				storageBucket: "project.appspot.com",
				messagingSenderId: "id",
				appId: "id",
				measurementId: "G-id",
			};
			// Initialize Firebase
			firebase.initializeApp(firebaseConfig);
			const db = firebase.firestore();
		</script>
		<script type="text/javascript" src="gameEngine.js"></script>

![image](https://user-images.githubusercontent.com/47303987/81512953-99632380-931c-11ea-9494-3c2130990146.png)

**Comment by wu-hui** [comment]
Sorry to hear your issue! 

I tried to reproduce on Windows10/Chrome 81 though, and could not see this issue, with the code you provided.

To proceed, I'd like to know the full content of html/js that could produce this issue, maybe it's something else in the header (for example) that has messed up firestore here.

**Comment by Migalvao** [comment]
@wu-hui Here is the info you requested.
My html file:
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8" />
		<title></title>
		<!--FIREBASE-->
		<script src="https://www.gstatic.com/firebasejs/7.14.2/firebase-app.js"></script>
		<script src="https://www.gstatic.com/firebasejs/7.14.2/firebase-firestore.js"></script>
		<script>
			// Your web app's Firebase configuration
			const firebaseConfig = {
				 apiKey: "api key",
			         authDomain: "project.firebaseapp.com",
			         databaseURL: "https://project.firebaseio.com",
			         projectId: "projectid",
			         storageBucket: "project.appspot.com",
			         messagingSenderId: "id",
			         appId: "id",
			         measurementId: "G-id",
			};
			// Initialize Firebase
			firebase.initializeApp(firebaseConfig);
			const db = firebase.firestore();
		</script>
		<!--states-->
		<script type="text/javascript" src="phaser.js"></script>
		<script type="text/javascript" src="Load.js"></script>
		<script type="text/javascript" src="Level1.js"></script>
		<script type="text/javascript" src="Boot.js"></script>
		<script type="text/javascript" src="gameEngine.js"></script>
		<script type="text/javascript" src="Options.js"></script>
		<script type="text/javascript" src="NameInput.js"></script>
		<script type="text/javascript" src="MainMenu.js"></script>
		<script type="text/javascript" src="Ranking.js"></script>
		<script type="text/javascript" src="Help.js"></script>
		<script type="text/javascript" src="LevelSelector.js"></script>
		<script type="text/javascript" src="CanvasInput.js"></script>
	</head>
	<body>
		<script type="text/javascript">
			var game = new GameEngine();
			window.onload = function () {
				game.phaser.state.add("Boot", bootState);
				game.phaser.state.add("Load", loadState);
				game.phaser.state.add("Options", optionsState);
				game.phaser.state.add("MainMenu", MainMenuState);
				game.phaser.state.add("NameInput", nameInputState);
				game.phaser.state.add("Level1", level1);
				game.phaser.state.add("Ranking", rankingState);
				game.phaser.state.add("Help", helpState);
				game.phaser.state.add("LevelSelector", levelSelectorState);
				game.phaser.state.start("Boot");
			};
		</script>
	</body>
</html>

```
The JS function where the call is made (GameEngine.js):
```
getName() {
		if (this.input.canvasInput._value != "") {
			var docRef = db.collection("players").doc(this.input.canvasInput._value);

			// check if name is in the database
                       	var doc = docRef
				.get()
				.then((doc) => {
					if (doc && doc.exists) {
						console.log("Document data:", doc.data());
					} else {
						console.log("No such document!");
					}
				})
				.catch((err) => {
					console.log("Error getting document", err);
				});

			game.player = new Player(
				this.input.canvasInput._value,
				5,
				5,
				5,
				0,
				docRef
			);
			this.toMainMenu();
		} else {
			alert("Please enter a name");
		}
	}
```

None of the console.log()'s are called. 
Thank you so much in advance.

**Comment by schmidt-sebastian** [comment]
With https://sourcemaps.info/, I am able to trace this back to: https://github.com/firebase/firebase-js-sdk/blob/5a60243bf264967819fc5c3897892084c5eb4d43/packages/firestore/src/core/sync_engine.ts#L289

`this.sourceMapInfo` is a JavaScript Map. It sounds like your environment doesn't support `Map.has`, which has nearly ubiquitous support: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

We recommend that you follow the steps here to install Polyfills for the environments you are targeting. You can find a guide here: https://firebase.google.com/support/guides/environments_js-sdk

**Comment by Migalvao** [comment]
Just found out what the problem was... 
We're making a game and we defined a class called Map() which was overwriting JS's original class, that's why the .has method was not available.
Well, this is embarrasing. Thank you for your help and I'm sorry you had to waste time with something so stupid.
