### ISSUE TITLE
Updates to Database Type Definitions

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-js-sdk#306]
* Expose `ThenableReference` type from the database type definitions.
* Currently `then()` and `catch()` methods are exposed from the `Reference` type, which doesn't seem to be correct. Those belong in `ThenableReference`.
* Add `EventType` type:

```
type EventType = 'value' | 'child_added' | 'child_changed' | 'child_moved' | 'child_removed';
```

**Comment by Crazometer** [comment]
`then` and `catch` still exist on all references https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/src/api/Reference.ts#L45

but the exposed types were fixed in https://github.com/firebase/firebase-js-sdk/pull/334.

> type EventType = 'value' | 'child_added' | 'child_changed' | 'child_moved' | 'child_removed';

Is the only point that still needs to be addressed.
