### ISSUE TITLE
Vuejs: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).

### ISSUE THREAD

**Issue by gokhan-cinar** [firebase/firebase-js-sdk#3067]
hello everyone, can you help with this problem please
![Screen Shot 2020-05-14 at 22 37 41](https://user-images.githubusercontent.com/26310911/81978017-8c537680-9633-11ea-99c3-d262fc485504.png)

**Comment by pedromoraisf** [comment]
UP! I have a same problem...
My frontend app is hosted with Netlify and writed with Vue.js

**Comment by pedromoraisf** [comment]
I've been realizing that there are several cases like this here in the repository, and all are being closed by @google-oss-bot  with no conclusion ...

**Comment by pedromoraisf** [comment]
**Context:**
I notified that the problem happens only on iOS >= 13

**Comment by gokhan-cinar** [comment]
Hey Pedro,

I solved the problem this way;

import firebase from 'firebase/app';
import 'firebase/messaging';

//  'firebase/messaging'; no safari support

end 

if (firebase.messaging.isSupported()) { 
     // code block
     // console.log('supported');
} else  {
    //  console.log('not supported');
}

**Comment by pedromoraisf** [comment]
My problem persists in iOS...... :/
Show me your code so i can see where this is implanted

**Comment by pedromoraisf** [comment]
I implemented this code in serviceWorkerRegistration.js and firebase-messaging-sw.js

**Comment by gokhan-cinar** [comment]
import firebase from 'firebase/app';
import 'firebase/messaging'; 

// Initialize Firebase
const config = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: "",
};

firebase.initializeApp(config);
// Retrieve Firebase Messaging object.

if (firebase.messaging.isSupported()) {
    const messaging = firebase.messaging();
    const key = ""
    messaging.usePublicVapidKey(key);

    messaging.requestPermission().then(() => {
        messaging.getToken().then((token) => {
            localStorage.setItem('notificationToken', token);
            if (localStorage.getItem('notificationToken')) {
                // console.log('');
            } else {
                let notification = localStorage.getItem('notificationToken');
                const userData = JSON.stringify({
                    deviceId: uuid,
                    googleAdvertisingId: `'',`
                    pushId: notification,
                    platform: 3
                });
            }
        })
    }).catch();
} else {
    // console.log('no supported');
}

messaging.onMessage(response => {
     console.log('response: ', response);
});

**Comment by pedromoraisf** [comment]
Thanks my brother, worked perfectly 👊🏽

**Comment by gokhan-cinar** [comment]
you are welcome my brother
