### ISSUE TITLE
Redirection after successful social authentication is super slow (performance issue)

### ISSUE THREAD

**Issue by deepfriedbrain** [firebase/firebase-js-sdk#3079]
* Operating System version: MacOS 10.15.4
  * Browser version: Chrome 81.x
  * Firebase SDK version: 7.14.2
  * Firebase Product: auth

I'm migrating from Google Identity Toolkit to Firebase Auth. While using Google or Facebook login, after I successfully authenticate with provider, I'm sent back to my original sign in page. From here it takes another 3-5 secs on average (sometimes higher) to get the current user from the Observer (code shown below). I've timed the call to get the logged in user from both my localhost and from the hosted application, and it is consistently slow in both cases.

This is on top of the already very slow authentication with social providers, which I had previously reported in June 2018 on FirebaseUI Web Github project but the issue was closed without any resolution saying it was a network problem. Here's a link to that issue:

https://github.com/firebase/firebaseui-web/issues/436

I'm posting this issue here now as the current issue is that after I'm successfully authenticated with the identity provider, it take 3-5 secs to get the authenticated UI from Firebase JS SDK on my sign in page.

I also decided not to use FirebaseUI Web because of its poor non-user friendly interface, and even slower performance, and built my own login page.

I see another issue reported on this project itself in Jan 2019 about the slow performance, and it was also closed with the same comment 'network problem':

https://github.com/firebase/firebase-js-sdk/issues/1499

There's not even an acknowledgement of the problem.

I had put my migration on hold as there was no real urgency to switch over. Now Google has started turning the lights off on the Identity Toolkit API services (new user registration was completely turned off), and I'm forced to move out.

Can we get someone to take a serious look at this issue?

On a related note, why can't we have a custom redirect URL to directly redirect the user to the target page? This request has been going around since 2016 and apparently no progress has been made. It doesn't make for a good UX to redirect the user back to the sign in page, make them wait for 4-5 secs staring at a progress bar or a spinner, and then again redirect them to their target page.

Overall, the whole process has more than 8 secs of wait time at different steps. It makes for a horrible UX.

```
function getCurrentUser() {
    return new Promise((resolve, reject) => {
        var start_time = new Date().getTime();
        var unsubscribe = firebase.auth().onAuthStateChanged(user => {
            unsubscribe();
            var request_time = new Date().getTime() - start_time;
            console.log("Time to get user: " + request_time);
            resolve(user);
        }, reject);
    });
}
```

**Comment by deepfriedbrain** [comment]
And I have been even getting "timeout" errors with Google Sign In after it returns back on the sign in page in `getCurrentUser`. It happened twice in the last couple hours. Once on Firefox incognito (private browsing) mode, and another time on Safari Incognito mode. Both were first attempts on these browsers after opening the respective incognito modes.

The timeout error showed nexttick.js line 37 in the console.

Is there anything I can check or do to resolve these issues?

Please don't tell me it's a network issue.

**Comment by Immortalin** [comment]
Same issue here, the demo Firebase Oauth site is almost instant but if you use the library it takes a a couple seconds before the state change gets triggered.

**Comment by deepfriedbrain** [comment]
@Immortalin Have you tried the demo app in an incognito window? In my testing it's about the same as my application that does "not" use FirebaseUI Web. Remember that if you are already signed in to Google, it would be a lot faster. 

**Hosted FirebaseUI Web Demo app results (using Login with Redirect option):**

Step 1. Click on Google Sign In -> Google email form display: ~8 secs
Step 2. Click on Next after entering password -> Back to demo page display: ~10 secs

There was no VPN involved. Testing from Singapore. I would not mind downloading the demo app and running it from my local to test if it was giving better results with the hosted version. But it's not faster.

Just a pure call to get user using the method described in my original post takes 4.5 secs (median), average is about 5 secs and even goes up to 8 secs (this is after discounting the time outs I've had).

And before someone says network issue, let me share the numbers from the current version of my web app that still uses Google Identity Toolkit, and the new version using Firebase Auth JS. Of course these are not scientific tests but these results have been quite consistent.

**Current version (Google Identity Toolkit):** 

Step 1: ~2 secs ; This is a remarkable difference. It indicates that there's clearly a performance issue with `firebase.auth().signInWithRedirect(provider)`, which takes 4 times longer in the demo app and 2.5 times longer in my app.

Step 2: ~5 secs ; This is also twice as fast as the Firebase Auth JS.

**New version (Firebase Auth JS):** 

Step 1: ~5 secs (faster than the demo)
Step 2: ~10 secs (similar to the demo)

**Comment by Immortalin** [comment]
For me popups are instant but redirections are quite slow, see: https://stackoverflow.com/questions/55509797/firebase-slow-redirect-after-sign-in

The problem is that I cannot detect when the signin was triggered as I am using the default widgets from firebaseui-react short of forking the library.

**Comment by rosalyntan** [comment]
Hi, thanks for the report! This is on our radar and we're working to improve this.

In the meantime, as a workaround, you can also handle the sign-in flow manually by integrating Google Sign-in/Facebook Login and calling signInWithCredential.

**Comment by farah** [comment]
This is a long standing problem, at least for 4+ years. 

`signInWithRedirect` method, without any exaggeration, is totally useless.  

1. Unable to change the redirect url after authentication, you'll always be redirected back to where the sign in was initiated.
2. The extremely long delays after redirecting back to log in page. This does not only apply to 'slow' connections but even extremely fast ones. This is totally confusing for the user, they have no idea why they went back to the log in page, it takes on average 7 seconds for the listener to fire.

My current solution is to have a server side implementation utilising the 'Sign in with OAuth credential' endpoint [1]. Would really like to remove that and have client side only implementation but the UX is just too terrible.

[1] https://firebase.google.com/docs/reference/rest/auth#section-sign-in-with-oauth-credential

**Comment by farah** [comment]
@rosalyntan interesting, I'm not sure why I didn't use the `signInWithCredential' method, i will try that.

**Comment by dosstx** [comment]
Just wanted to report that I am having the same issue and didn't see this thread yet, however, I did post a stackoverflow question about it (no answers yet): https://stackoverflow.com/questions/66177706/firebase-auth-and-google-sign-in-redirection-slow-after-user-is-authenticated

I'll check out the suggestion by @rosalyntan

**Comment by ARivas16** [comment]
I am having the same issue and the only way to handle that was with local storage. I found the solution in this question: https://stackoverflow.com/questions/55509797/firebase-slow-redirect-after-sign-in
I hope that this is useful to bypass the issue for now.

**Comment by pedrorabbi** [comment]
Just found out that the problem was that my local IP wasn´t whitelisted as a domain on Firebase.
Added it on Firebase console and now the redirect is pretty fast (even on mobile), on both Facebook and Google.
