### ISSUE TITLE
Firebase analytics is broken when using Typescript

### ISSUE THREAD

**Issue by nicholaschiang** [firebase/firebase-js-sdk#3080]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04.2
  * Browser version: Mozilla Firefox for Ubuntu 76.0.1 (64-bit)
  * Firebase SDK version: 7.14.2
  * Firebase Product: Analytics

#### Steps to reproduce:

1. Clone [this repository](https://github.com/tutorbookapp/covid-tutoring).
2. Install our dependencies by running (see the `README.md` for more info):
```
$ npm i && lerna bootstrap --hoist
```
3. Checkout to `develop` (and make sure you've got the latest commit) by running:
```
$ git checkout develop && git pull
```
4. Try to compile our Typescript source into a deployable web app using Next.js by running:
```
$ npm run build
```
5. Notice that the `firebase.analytics().logEvent()` calls are showing up as miss-typed (i.e. they don't appear to match any overload) even though they correctly implement the types defined in `firebase/index.d.ts` (the type definitions included in the [official Firebase package](https://npmjs.com/package/firebase)).

#### Relevant Code:

For example, this call fails to compile:

```typescript
firebase.analytics().logEvent('login');
```

Running `npm run build` results in the following error:
```
Failed to compile.

/home/nchiang/repos/covid-tutoring/src/firebase/lib/user.tsx
ERROR in /home/nchiang/repos/covid-tutoring/src/firebase/lib/user.tsx(58,37):
58:37 No overload matches this call.
  Overload 1 of 22, '(eventName: "add_payment_info", eventParams?: { [key: string]: any; coupon?: string | undefined; currency?: string | undefined; items?: Item[] | undefined; payment_type?: string | undefined; value?: number | undefined; } | undefined, options?: AnalyticsCallOptions | undefined): void', gave the following error.
    Argument of type '"login"' is not assignable to parameter of type '"add_payment_info"'.
  Overload 2 of 22, '(eventName: never, eventParams?: { [key: string]: any; } | undefined, options?: AnalyticsCallOptions | undefined): void', gave the following error.
    Argument of type '"login"' is not assignable to parameter of type 'never'.
    56 |   private async handleChange(user: FirebaseUser | null): Promise<void> {
    57 |     if (user) {
  > 58 |       firebase.analytics().logEvent('login');
       |                                     ^
    59 |       const userRecord: Partial<UserInterface> = {
    60 |         name: user.displayName || '',
    61 |         email: user.email || '',
```
Even though that login `eventName` is defined in `node_modules/firebase/index.d.ts` as:
```typescript
    /**
     * Sends analytics event with given `eventParams`. This method
     * automatically associates this logged event with this Firebase web
     * app instance on this device.
     * List of recommended event parameters can be found in
     * {@link https://developers.google.com/gtagjs/reference/event
     * the gtag.js reference documentation}.
     */
    logEvent(
      eventName: 'login',
      eventParams: {
        method?: EventParams['method'];
        [key: string]: any;
      },
      options?: firebase.analytics.AnalyticsCallOptions
    ): void;
```

**Comment by nicholaschiang** [comment]
Fixed this myself. Wasn't an error with you guys after all haha.

**Comment by darchard1984** [comment]
@nicholaschiang What was the issue for you ? I'm having the same problem.

**Comment by zhGio** [comment]
Same problem here, I would like to know what happened to you and how did you fix it?
