### ISSUE TITLE
Analytics drops 8 point in Best Practices

### ISSUE THREAD

**Issue by MichaelSolati** [firebase/firebase-js-sdk#3092]
### Describe your environment

  * Operating System version: Mac 10.15.4
  * Browser version: 81.0.4044.138 (Official Build) (64-bit)
  * Firebase SDK version: 7.14.4
  * Firebase Product: Analytics

#### Steps to reproduce:

If you include analytics on your page and run it through web.dev's [Measure page](https://web.dev/measure/) it will drop 8 points in Best Practices because of "Browser errors were logged to the console".

#### Relevant Code:

I have a super simple [glitch here](https://glitch.com/edit/#!/abyssinian-wooded-hospital?path=index.html%3A10%3A52) and it is live @ [https://abyssinian-wooded-hospital.glitch.me](https://abyssinian-wooded-hospital.glitch.me). So if you put that URL on [https://web.dev/measure/](https://web.dev/measure/) it'll have a "Best Practices" score of 92. Comment out `firebase.analytics();` in the glitch's `index.html` and it's 100.

The big problem here is that the I can't tell what is being logged, but apparently something is.

**Comment by Feiyang1** [comment]
You can see the error message in the detailed report by clicking on the `View Report` link - https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fabyssinian-wooded-hospital.glitch.me%2F#best-practices

The lighthouse runtimes seems to block analytics requests. It's probably just an environmental issue specific to lighthouse, not a problem with your app.

**Comment by MichaelSolati** [comment]
(Thank you @Feiyang1)
