### ISSUE TITLE
FR: Allow for gradual "firebase.initializeApp"

### ISSUE THREAD

**Issue by mehdi-cit** [firebase/firebase-js-sdk#31]
Hello,
In order to minimize load time, I am trying to build an web-app where I do not include all js files at startup time. Rather, I gradually download the different firebase-js files on a need to have basis. 
I only need to interact with the firbase-database after the user has been authenticated. so initially I only include` firebase-app.js `and `firebase-auth.js`.
After the user had been successfully logged in, I download `firebase-database.js` and start interacting with the real-time database.
My problem is that I am getting an error:
`firebase.database() takes either no argument or a Firebase App instance.`
I believe the above error is caused as I call `firebase.initializeApp(config);`  before `firebase-database.js` is available. Note, that the exception is only thrown when I try to use firebase.database!

I guess it should not be too hard to allow for gradual firebase initialization. For instance, only initializing with the databaseURL after some time (i.e. after firebase-database.js is available).
PS: Obviously, my web-app works without problem if I do include/download all necessary js files at startup (` firebase-app.js `, `firebase-auth.js` and `firebase-database.js`)

**Comment by mbleigh** [comment]
This ability just shipped in version 4.1.1 -- have you tried it with that
code? You should initialize with all of the config values up front, but you
can now gradually load the js files.

**Comment by mehdi-cit** [comment]
Sounds great! 
I only tried 4.0.0. I will try 4.1.1 and report back!

**Comment by mehdi-cit** [comment]
Works well. Thank you :)
