### ISSUE TITLE
[Firestore] Not getting "The query requires an index" error message

### ISSUE THREAD

**Issue by AoDev** [firebase/firebase-js-sdk#3107]
### Describe your environment

  * Operating System version: OSX 10.14.6
  * Browser version: Brave 1.8.90
  * Firebase SDK version: 7.6.1
  * Firebase Product: Firestore

### Describe the problem
I was expecting the error message:

`"Error in onSnapshot: FirebaseError: The query requires an index. You can create it here:[console link]" `

But I didn't get it despite trying to run the queries. The response / list was just empty so I ended up creating the indexes manually.

### Context

I have 2 Firebase projects. One for dev environment and one for production. I was in the process of updating production and this involved some Firestore queries that need an index.

I remember how in dev, I got an error message that would link to the creation of an index in the Firebase console. (really cool)

But this has not happened. So I thought of creating them manually __but the UI recommends to run the queries on the client side and click the link of the error message__. In the end I gave up and created the indexes manually. It's a bit "annoying" to have a recommendation in the console UI but not being able to follow it.

### Steps to reproduce:
Not sure it can be reproduced all the time. Create a project with a query that needs an index and expect an error message on the client.

### Relevant Code:

I have functions that look like this:
```js 
async function getHistory (userId, options = {limit: 15}) {
  const result = await fdb.collection('randomcollection')
    .where('userId', '==', userId).orderBy('time', 'desc').limit(options.limit)
    .get()
  return result.docs.map((doc) => doc.data())
}
```

### Being able to copy indexes?

So, I did this manually, no problem. But it would be nice if we could just export / copy indexes config between projects. I know it's not the scope of this issue but, just saying :)

**Comment by dconeybe** [comment]
Hello @AoDev. I'm currently investigating why you didn't get the "create index" URL in the error; however, note that it *is* indeed possible to copy/export security rules between projects: https://stackoverflow.com/questions/52778542/how-to-export-security-and-index-rules-from-firestore.

**Comment by AoDev** [comment]
@dconeybe Thanks. Do you need any project id?

**Comment by dconeybe** [comment]
If you don't mind posting the project IDs publicly then feel free to post them here. Otherwise, I'll let you know if I need them.

**Comment by AoDev** [comment]
The project is in production at https://battletraders.io/

The authentication is with Firebase auth and we have Firestore as DB.
Project id is `'battle-traders'`.

There are more details but not sure of what I can share publicly. If you visit the game, you will see requests to Firebase with more details, but I can give more info privately if needed.

**Comment by dconeybe** [comment]
I tried to reproduce using the query from the OP and it did what was expected: it failed and the error message included an HTTP URL to create the index.

The first thing that I notice is that you are using a 5-month-old version of the Firebase SDK: 7.6.1. Is it possible to upgrade to the latest version (7.14.5 at the time of writing)?

Could you write a minimal app and publish it to GitHub that you can use to reproduce? With this app you could just point it to one project (via initializeApp), run it, then point it to the other project and run it? If you can find a minimal scenario that can be used to reproduce that will go a long way to diagnosing.

Another possibility is that you were offline or simulated offline by calling [disableNetwork](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#disablenetwork) when executing the queries that were expected to fail with the index-creating HTTP URL. If you were offline then `get()` would have returned as if successful and given you an empty result set. The [metadata](https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot#metadata) of the result would have `fromCache: true` to indicate that the remote server was not consulted. If you can reproduce, can you provide the JSON-ified `metadata` of the `QuerySnapshot` returned?

**Comment by AoDev** [comment]
@dconeybe I will update the SDK. I was not offline at that moment. I have more features coming in our product with new indexes so, when I reach that point, I will see if I get the message or nothing, and I'll try to share everything I get.

In the meantime, we can put this issue on standby / close, if you prefer.

**Comment by dconeybe** [comment]
Sounds good. For now, I'll close the issue but feel free to re-open if you experience it again.
