### ISSUE TITLE
Setting up a reverse proxy server for Firestore emulator

### ISSUE THREAD

**Issue by mlejva** [firebase/firebase-js-sdk#3126]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 7.14.5
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem
In our company, I need to run a Firebase emulator suite on a separate machine from my own. I was trying to set up a simple reverse proxy server to be able to re-route my Firebase client SDK 
Firestore requests to a Firestore emulator on that machine. So far with no luck though.

I was under the impression that the Firestore communication is handheld through gRPC but when examining the client SDK Firestore requests it seems those are handheld vie the REST approach, is that correct?

I have a basic reverse proxy server in Go
```golang
package server

import (	
	"net/http"
	"net/http/httputil"
	"net/url"
	"log"
	
	"github.com/gorilla/mux"
	"github.com/rs/cors"
)

func serveReverseProxy(res http.ResponseWriter, req *http.Request) {	
	// parse the url
	url, _ := url.Parse("http://localhost:8080")

	// create the reverse proxy
	proxy := httputil.NewSingleHostReverseProxy(url)

	// Update the headers to allow for SSL redirection
	req.URL.Host = url.Host
	req.URL.Scheme = url.Scheme
	req.Header.Set("X-Forwarded-Host", req.Header.Get("Host"))
	req.Host = url.Host

	// Note that ServeHttp is non blocking and uses a go routine under the hood
	proxy.ServeHTTP(res, req)
}

func Start() {
	router := mux.NewRouter()
        router.PathPrefix("/").HandlerFunc(serveReverseProxy)

	// Start server
	if err := http.ListenAndServe(":3600", router); err != nil {
		panic(err)
	}	
}
```

To change the Firestore host in the client SDK I'm using the following code
```javascript
firebase.firestore().settings({
  host: "localhost:3600",
  ssl: false
});
```

Is the reverse-proxy setup even possible? If so, could you please point me in the correct direction?

Eventually, I'd like to handle all parts of the emulator suite, would that be possible?

**Comment by mlejva** [comment]
Hey @rafikhan, thank you for the response.
I'm using the Firebase client browser SDK.

We had decided to go with the 3rd option. The Firebase emulator is running on our server that is publicly accessible. Each emulator has its own domain like so:
- Firestore: `firestore.custom.domain.com`
- Database: `database.custom.domain.com`

Although Firestore works without any problem there's a problem with using such custom URL for Firebase Database. When passing our custom Firebase Database URL the SDK throws a following error
```
Error: "FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com "
```

When looking at Firebase SDK I found that it only allows either `localhost` URLs or URLs in the format mention in the error above. 
Would it be possible to allow arbitrary database URLs? I'm happy to send a PR.

**Comment by yuchenshi** [comment]
@mlejva You need to make sure to include `?ns=namespace-name` if you use a custom domain. Like: `{databaseUrl: 'http://database.custom.domain.com/?ns=foo-bar'}`.

**Comment by mlejva** [comment]
Thanks @yuchenshi, that helped.

What happens now is that I'm getting following error in the browser console (using Firefox 76.0.1):
![image](https://user-images.githubusercontent.com/5136688/83540607-d9bb5900-a4f8-11ea-939a-ed37ea2ac7b2.png)


My database URL looks like this:
```
{databaseURL: 'https://database.custom.example.com/?ns=test'}
```
When I curl the database it seems to work. This is a response I get after `$ curl -v https://database.custom.example.com/?ns=test`

```
< HTTP/2 400
< server: nginx/1.17.8
< date: Tue, 02 Jun 2020 15:39:39 GMT
< content-type: text/plain
< content-length: 45
< access-control-allow-origin: *
< x-firebase-project-id: database
< x-firebase-project-number: 123456789
< x-firebase-uuid: 4c926135-1fd3-4f02-9bd9-426b6c8a814b
< strict-transport-security: max-age=15724800; includeSubDomains
<
* Connection #0 to host database.custom.example.com left intact
Append .json to your URL to use the REST API.* Closing connection 0
```

**Comment by yuchenshi** [comment]
This is surprising since the JS SDK doesn't hard code "0.0.0.0" or switch based on browser. My guess is that you're seeing cached JavaScript code from e.g. your previous configuration.

Please try clearing the browser cache and try again. If this still happens to you, please create a minimal, self-contained repro with just one single HTML file containing a `<script>` tag showing how you're initializing the SDK and interacting with the database.

**Comment by mlejva** [comment]
This seems to be problem in my local environment and unrelated to Firebase. So closing this issue.

Thank you for assistance!
