### ISSUE TITLE
Topic messaging with condition 'or' operator not working 

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-js-sdk#3134]
### [REQUIRED] Describe your environment

  * Operating System version: _____irrelevant
  * Browser version: __________irrelevant
  * Firebase SDK version: _____latest FCM
  * Firebase Product: _____messaging (auth, database, storage, etc)

### [REQUIRED] Describe the problem

This is a bug that has already raised multiple times but I cant find any open issue on it. This one for instance: https://github.com/firebase/quickstart-js/issues/183
 What is the status?

**Comment by Feiyang1** [comment]
Since it is a backend issue, you should contact Firebase support for updates as @jhuleatt pointed out in https://github.com/firebase/quickstart-js/issues/183#issuecomment-621381797. This repo is only for SDK issues.  Thus, closing the issue.
