### ISSUE TITLE
FCM rxjs compatibility broken? 

### ISSUE THREAD

**Issue by zwu52** [firebase/firebase-js-sdk#3142]
FCM API suggests that it offers rxjs compatibility out of box. Specifically, you could do
```
let foregroundMessages$ = rxjs.Observable.create(function subscribe(observer) {
  messaging.onMessage(observer);
});

foregroundMessages$.subscribe({
  next: (msg) => handleForegroundMessage(msg),
  error: (err) => console.log("err: " + err),
});
```

However, an error is thrown:
```
Uncaught (in promise) TypeError: this._next is not a function
    at rt.Subscriber.next [as onMessageCallback] (rxjs.umd.js:472)
    at rt.<anonymous> (window-controller.ts:197)
    at tslib.es6.js:100
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at v (tslib.es6.js:70)
    at rt.messageEventListener (window-controller.ts:188)
    at ServiceWorkerContainer.<anonymous> (window-controller.ts:47)
```

Came across this error here as well (https://github.com/angular/angularfire/issues/2299)

**Comment by zwu52** [comment]
ref: [FCM API](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging)

**Comment by Feiyang1** [comment]
Reading https://github.com/angular/angularfire/issues/2299#issuecomment-636366297, seems it was working before `7.6.0`. Any idea what changed?

**Comment by zwu52** [comment]
Finally got a chance to route back to this. I think I found the cause for this:  currently window controller stores a member variable `onMessageCallback` which gets fed with value from `nextOrObserver`.  Internally, if this `nextOrObserver` is not a callback function, we do `this.onMessageCallback = nextOrObserver.next` assuming the `next` callback is passed directly from the observer object developer provided in 
```javascript
{
  next: (msg) => handleForegroundMessage(msg),
  error: (err) => console.log("err: " + err),
}
```
 However,  rxjs actually does some internal operation and converts the observer into a [subscriber instance](https://rxjs.dev/api/index/class/Subscriber), such instance should be used as a unit as it is (e.x. `subsciber.next()).  Trying to extract the next callback from it will result in
 ```javascript
this.onMessageCallback = function: ƒ (value) {
            if (!this.isStopped) {
                this._next(value);
            }
        }
```
since next is stripped away from the generated subscriber, `this._next` nor `this.isStopped` is `undefined`. 
I have a PR that would resolve this issue.

**Comment by hiepxanh** [comment]
perfect, I'm coming from https://github.com/angular/angularfire/pull/2497#issuecomment-648593433 and I'm wating for your fix to update my PR
