### ISSUE TITLE
Firebase JS SDK OAuth2 request parameters: access_type: 'offline'

### ISSUE THREAD

**Issue by fosteman** [firebase/firebase-js-sdk#3159]
### Environment
  * Operating System version: MacOS Catalina
  * Browser version: latest chrome
  * Firebase SDK version: 7.14.3
  * Firebase Product: Firebase JS library for Node.js and Web 

### The problem
In my Serverless React app, I authenticate using
```
this.auth.googleAuthProvider = new app.auth.GoogleAuthProvider()
        this.auth.googleAuthProvider.setCustomParameters({
            access_type: "offline"
        })
        this.auth.googleAuthProvider.addScope('https://www.googleapis.com/auth/calendar')
// class constructor ends
authenticate = () => this.auth.signInWithPopup(this.auth.googleAuthProvider)
                .then((userCredential) => {
                    const res = userCredential.getAuthResponse()

                    console.log(res, res.id_token)
                })
```

#### Expected behavior
This returns oauth2 access_token to user's API (Yay!), and `refresh_token` (Nay)

#### Real behavior
However, I need `Offline Authorized Access` to user's API resources, therefore`refresh_token`. 

I didn't seem to be able to find documentation on how to implemented incremental authorization either.

How do I specify 
```
state=key
access_type: 'offline'
```
 using this library ?

**Comment by fosteman** [comment]
I am trying to work around it now on cloud functions
<img width="575" alt="Screen Shot 2020-06-03 at 1 53 02 PM" src="https://user-images.githubusercontent.com/32850517/83670687-8c46f680-a5a1-11ea-8328-54623de091d1.png">
<img width="523" alt="Screen Shot 2020-06-03 at 1 53 12 PM" src="https://user-images.githubusercontent.com/32850517/83670707-94069b00-a5a1-11ea-95ad-dc2a4a9d16d4.png">

But this does not create the session in frontend, `auth.onAuthStateChanged` doesn't fire.
Solution ?

**Comment by rosalyntan** [comment]
Thanks for the question! To clarify, are you trying to access the refresh token for Google APIs or Firebase APIs? If you are trying to access Google APIs, you'll want to sign in with the Google SDK manually to get the refresh token. Then, to authenticate with Firebase, you can call signInWithCredential with the credential returned from signing in with the Google SDK.
