### ISSUE TITLE
Adding images to Firebase Authentication email templates doesn't work

### ISSUE THREAD

**Issue by bhatiak** [firebase/firebase-js-sdk#316]
I'm not sure if this is the right place to ask this question. Please let me know if there's a better place.

I'm trying to edit my authentication email templates (email address verification, password reset, email address change) to include an image. In Firebase console, the email preview shows the image, but the actual email sent to me does not. The URL in the email shows up as:

https://ci6.googleusercontent.com/proxy/2005D4byJrwPzXXcfuZyX2hLp035YJA0Lw2A_IxyOtqAemf0un87Mt_aJ8t0ZXPBhIru=s0-d-e1-ft#https://slidesup.com/logo.svg

...which leads to a 404 page rather than displaying the image at https://slidesup.com/logo.svg.

**Comment by bojeil-google** [comment]
This is not the right place for this issue. Please go through Firebase Support. They will reroute you to the right people: https://firebase.google.com/support/

**Comment by bhatiak** [comment]
Thanks. I'll try there.
