### ISSUE TITLE
Time consuming debug: Function DocumentReference.update() called with invalid data. Unsupported field value: undefined

### ISSUE THREAD

**Issue by arthabus** [firebase/firebase-js-sdk#3169]
### Describe your environment

  * Operating System version: macOs 10.14.5
  * Browser version: Chrome, Version 83.0.4103.61 (Official Build) (64-bit)
  * Firebase SDK version: 7.9.1
  * Firebase Product: database (firestore)

###  Describe the problem

Is it possible to include "key" name and the failed database path in the error message?

Since our application is growing, it becomes harder and harder to debug this error - our objects became quite complex and often times we are doing multiple requests in parallel (Promise.all(...)) 

It started to take quite a chunk of time to just figure out where exactly we've got an `undefined` field.

#### Steps to reproduce:

1. Create  a complex JSON object with multiple nesting.
2. Assign an `undefined` to a random field in one of the objects.
3. Save it to firestore database

Bonus step:

4. Create several objects, randomly assign `undefined` to one of their fields and save each of them to a different location in firestore in parallel.

**Problem**: Trying to figure out what object failed and which field is `undefined` using the error log takes quite some time as it currently just says: `Unsupported field value: undefined`

**Expected**: The log specifies the name of the key with the `undefined` value and the database path where the update/insert was suppose to happen so it's clear from the log where to look at.

**Comment by wilhuff** [comment]
Hi! Thanks for writing in and sorry for the difficulty. I've put together #3189 that should address this.
