### ISSUE TITLE
FR: Firestore document onCreate event

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-js-sdk#317]
I am implementing a command/response pattern where the user writes to a command collection by calling `add` with a payload under his own userId, and then gets the data from a similar response path.

However the code below doesn't work, because onSnapshot can not listen for a document that hasn't yet been created. This would be easy to solve with an onCreate handler, which does exist for cloud functions. 

The client code is using [redux-firestore](https://github.com/prescottprue/redux-firestore) and some of my app helper functions, but you'll get the idea. The command and response document structure use { payload, error} similar to [FSA](https://github.com/acdlite/flux-standard-action)

### Cloud Function

```javascript
export const register = functions.firestore
  .document("commands/{userId}/register/{commandId}")
  .onCreate(async event => {
    const payload = event.data.get("payload");
    const { userId, commandId } = event.params;
    const response = db.document(`responses/${userId}/register/${commandId}`)

    // possibly something bad will happen
    try {

      // do something with payload...

      return response.set({
        payload: "ok" // or pass relevant response data
      })
    } catch(err) {
      return response.set({
        error: true
        payload: err
      })
    }
  });
```

### Client

```javascript
export async function register(fs: any, userId: string) {
  try {

    // issue a new command
    const command = await fs.add(
      { collection: `commands/${userId}/register` },
      { payload: fs.firestore.FieldValue.serverTimestamp() }
    );

    // wait for the response to be created
    fs.onSnapshot(
      { collection: `responses/${userId}/register`, doc: command.id },
      function onNext(doc) {
        const {error, payload} = doc.data()

        if (error) {
          return notify.error({ title: 'Failed to register', message: payload.message });
        }
        notify.json(payload);
      },
      function onError(err) {
        notify.error(err);
      }
    );
  } catch (err) {
    notify.error(err);
  }
}
```
Why is there no such thing? I'm wondering if I'm not overlooking some API...

The only scalable solution I can think of is to store the response data as a child in the command document, but I think it is not as nice, because I suspect you can not make the permissions as strict then.

I would like the user __only__ to be able to write to the command, and __only__ read from the response paths. If I place the response as a child of command, this would not be possible I think?

**Comment by mikelehen** [comment]
I believe this issue was resolved via your Google Group post: https://groups.google.com/d/msgid/firebase-talk/CADypTEaaFQva9UfgF8ivLzHtA8dtHtMmUg-2fxH5J2cPK39LPw%40mail.gmail.com?utm_medium=email&utm_source=footer

If you have further questions, please follow up there.

**Comment by 0x80** [comment]
@mikelehen Thanks, I did not see that reply yet! I think I need to check my notification settings.... 

So apparently my conclusion that listening for an non-existing document with onSnapshot would be impossible was wrong. I will investigate this again.
