### ISSUE TITLE
Unexpected Token in node_modules/@firebase/util/dist/index.cjs.js Rollup Error

### ISSUE THREAD

**Issue by alteredorange** [firebase/firebase-js-sdk#3186]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04
  * Browser version: Chrome 83
  * Firebase SDK version: 7.15.0
  * Firebase Product: auth, analytics, messaging

### [REQUIRED] Describe the problem

Unexpected token error when trying to import firebase with Rollup. Using the latest Firebase 7.15 from npm. I've tried both importing and requiring methods.

#### Steps to reproduce:
Importing firebase and trying to export a project with rollup.

#### Relevant Code:

    var firebase = require('firebase');
    require('firebase/auth');
    require("firebase/analytics");
    require("firebase/messaging");
    //or import method...
    import firebase from 'firebase/app';
    import "firebase/analytics";
    import "firebase/auth";
    import "firebase/messaging";

Both methods return an unexpected token error from node_modules/@firebase/util/dist/index.cjs.js:

    [!] Error: Unexpected token
    549: function isNode() {
    550:     try {
    551:         return (Object.prototype.toString.call(global.process) === '[object process]');
                                                              ^
    552:     }
    553:     catch (e) {
    Error: Unexpected token
    at error (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:217:30)
    at Module.error (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:15144:16)
    at tryParse (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:15031:23)
    at Module.setSource 
    (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:15435:30)
    at ModuleLoader.addModuleSource 
    (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:17470:20)
    at ModuleLoader.fetchModule 
    (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:17537:9)
    at /home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:17500:36
    at async Promise.all (index 4)
    at ModuleLoader.fetchModule 
    (/home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:17538:9)
    at /home/oranges/petshow/node_modules/rollup/dist/shared/rollup.js:17500:36`

**Comment by alteredorange** [comment]
I believe this has something to do with Routify itself, not firebase. Compilation works fine with Sapper, so closing this issue for now.

**Comment by quantuminformation** [comment]
I got the same error when trying to use dotenv.

**Comment by quantuminformation** [comment]
And I am not using routify.

You can make it go away by returning true in that function 551, But obviously that's not a long term fix
