### ISSUE TITLE
Bug Report : Registration failed - push service error

### ISSUE THREAD

**Issue by naveedahmed1** [firebase/firebase-js-sdk#3195]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
  * Firebase SDK version: 7.15.0
  * Firebase Product: Firebase Messaging

### [REQUIRED] Describe the problem
I'm using Angular Fire and when requesting token using below code it throws error

**Code**
```
this.messaging.requestToken
      .subscribe((token) => {
        this.sendTokenToServer(token);
      },
        (error) => {
          console.error(error);
          this._gs.hideOverlay();
        },
      );
```

**Error**
`Uncaught DOMException: Registration failed - push service error`

This issue occurs randomly, I mean the same code which works perfectly suddenly breaks and start throwing this errror.

If I create a new profile on Chrome (i.e. a new user), the exact same code starts working on same machine.

I think its an old issue but has not be permanently fixed, and I believe this should be thoroughly investigated and fixed.

Below are the issues I found on Firebase and Angular Fire Repos,

https://github.com/firebase/firebase-js-sdk/issues/909

https://github.com/FirebaseExtended/polymerfire/issues/345

https://github.com/firebase/firebase-js-sdk/issues/771

https://github.com/firebase/firebase-js-sdk/issues/152

https://github.com/angular/angularfire/issues/2475

#### Steps to reproduce:
I have no idea whats actually causing the issue and issue occurs randomly, hence don't know how to reproduce the issue.

For https://www.mustakbil.com/ its working for some users and not for others. In my case its working fine on Android and broken on desktop, if I setup new profile it works jut fine. 

The issue is, its broken even for some of the new and first time users of the website.

#### Relevant Code:
Angular Fire code.
```
this.messaging.requestToken
      .subscribe((token) => {
        this.sendTokenToServer(token);
      },
        (error) => {
          console.error(error);
          this._gs.hideOverlay();
        },
      );
```

I would have reported this issue on Angular Fire repo, but in my opinion the issue is related to Firebase library. Since I have seen posts complaining about same issue while using different frameworks.

Thank you or your attention to this issue.

**Comment by mmikrut** [comment]
Same issue yesterday on a stable PWA deployed many months ago.
However it seems to be browser related.  Clearing Service workers and storage in Chrome Dev Tools / Application have fixed the problem.

**Comment by naveedahmed1** [comment]
> Clearing Service workers and storage in Chrome Dev Tools / Application have fixed the problem.

In my case even this doesn't work unless I creat new user profile (reported by other users as well)

I also initially thought this that it must be related to the browser but then I came across the other demos of firebase push notifications, hosted on different domains and all of them had the same issue on the same chrome user profile. But when I tested it with other websites that were for example using other push notification service providers for example one signal it was working fine on same user profile of chrome.

**Comment by mmikrut** [comment]
I still think its browser related, as we just tested, same user on two PCs ( iMac & Linux), both running newest version of chrome.  PWA works on iMac, chrome on linux displays push service error

**Comment by naveedahmed1** [comment]
In my case it only happens with sites using `firebase js sdk`.

**Comment by shadow1349** [comment]
I left a comment on the other issue, but this is a super annoying issue so I'm going to link that comment here as well: https://github.com/angular/angularfire/issues/2475#issuecomment-711099922

**Comment by shadow1349** [comment]
Yeah all the other browsers were working ok for me, but Brave is my main browser

**Comment by eugenioclrc** [comment]
same error here!, also using brave in linux

**Comment by naveedahmed1** [comment]
Any update on this?

I just checked `chrome://gcm-internals/` and under **Registration Log** it shows `TOO_MANY_REGISTRATIONS`. Any idea what could have caused this? And how to fix this?

**Comment by naveedahmed1** [comment]
If I take a look at  **Registration Log** it seems any call to `messaging.getToken` and `messaging.requestToken` methods tries to get registration token with a new random `App Id`. as a result we have too many registrations.

Example 'App Id's

```
wp:https://www.mustakbil.com/#BB0DB796-278C-474F-A734-32B35E3E2-V2
wp:https://www.mustakbil.com/#D00AD433-4922-4E22-846D-05DF35109-V2
wp:https://www.mustakbil.com/#D00AD183-4922-4E22-885D-05DF35109-V2
wp:https://www.mustakbil.com/#3FF9E22C-231B-4C61-9C1E-F38B31290-V2
wp:https://www.mustakbil.com/#D7158487-E513-4C08-A904-373567A69-V2

```

**Comment by naveedahmed1** [comment]
I have also opened a issue with Chrome team, https://bugs.chromium.org/p/chromium/issues/detail?id=1153182

**Comment by marcusmmmz** [comment]
Any updates on this? Still happens in Brave in Manjaro Linux

**Comment by natemartins** [comment]
I'm also experiencing same issue on Brave and Chrome

**Comment by aalluri7** [comment]
any updates on this we are getting the same error intermittently

**Comment by atzzCokeK** [comment]
@wbobeirne 
Thanks, it helps a lot.

**Comment by DellaBitta** [comment]
It's been a while. Checking in to see if this is a Brave configuraiton issue for folks that's helped by wboberine's post above. Thanks!

**Comment by soulcm** [comment]
I have the same issue on Android Chrome，Does anybody resolved？

**Comment by DellaBitta** [comment]
@soulcm, is your environment the same as the original ticket? If not, I'd ask you to create a new issue with details about the configuration you're using and the code that's failing. Thanks!

**Comment by naveedahmed1** [comment]
In my experience the issue occurs on frequent calls to `requestToken / deleteToken`. In our case, we were calling `requestToken` on user login and `deleteToken` on user logout from our website, or when user clicks the toggle notifications button i.e. call `requestToken` when user clicks Enable Notifications button and call `deleteToken` when user click Disable Notifications button.

As a workaround, we now never call `deleteToken`, instead we track the unsubscription on our own server.

**Comment by zwu52** [comment]
> In my experience the issue occurs on frequent calls to `requestToken / deleteToken`. In our case, we were calling `requestToken` on user login and `deleteToken` on user logout from our website, or when user clicks the toggle notifications button i.e. call `requestToken` when user clicks Enable Notifications button and call `deleteToken` when user click Disable Notifications button.
> 
> As a workaround, we now never call `deleteToken`, instead we track the unsubscription on our own server.

following up on this thread, couple qs:
- @naveedahmed1  what SDK versions are you on? 
- out of curiosity: `we track the unsubscription on our own server` how is this flow currently implemented in breid
