### ISSUE TITLE
Firebase onAuthStateChanged observable not working

### ISSUE THREAD

**Issue by Arieg419** [firebase/firebase-js-sdk#3208]
Hey friends,

I'm **coding a chrome extension** that is using **firebase for authentication**. I've add the "**email-link**" sign in method.

### **Flow:**
a user gets a link in their email.
Once it is clicked user is redirected to our web domain via firebase link.
Firebase link is verified and sign in is completed with this code (this code succeeds):

```
if (!firebase.auth().isSignInWithEmailLink(window.location.href)) {
      console.error("failure... bad link")
      setHeaderText(errorHeader)
      setHeaderSubText(errorMessage)
      return
    }
    // The client SDK will parse the code from the link for you.
    firebase
      .auth()
      .signInWithEmailLink(email, window.location.href)
      .then(function (result) {
        console.log("sign in success...")
        setHeaderText(successHeader)
        setHeaderSubText(successMessage)
      })
      .catch(function (error) {
        console.error(`login failed...`, error)
        setHeaderText(errorHeader)
        setHeaderSubText(errorMessage)
      })
```

### **Problem:**
In the background script of my chrome extension I am using the recommended observable to listen for auth state changes like so:
```
  firebase.auth().onAuthStateChanged(function (user) {
    if (user) {
      console.log("saw user auth change! ", user)
      isLoggedIn = true
    } else {
      // No user is signed in.
    }
  })
```
However, this code is not invoked. I also tried a naive busy/wait loop trying to querying the firebase user like so but can still not see the current user after a successful login:

```
      // Poll user logged in
      await new Promise((resolve, reject) => {
        const intervalId = setInterval(async () => {
          const cu = firebase.auth().currentUser
          console.log(`current user is `, cu)
          if (cu != null) {
            clearInterval(intervalId)
            resolve()
          }
          // })
        }, 2000)
        setTimeout(() => {
          clearInterval(intervalId)
          reject()
        }, 60000)
      })
```
### **Suspicion:**
I am not seeing any firebase related requests in the network tab. It looks like once the firebase app is inited it doesn't fetch the updated user. I've set the content-security-policy identical to what is set in the example repo: https://github.com/firebase/quickstart-js/blob/master/auth/chromextension/manifest.json so I dont think it's a csp issue.

**### Additional sanity checks:**
- I've authorized under firebase console -> authentication -> domains my chrome extension id like so: ```chrome-extension://<ID_HERE>```. 
- I am seeing the user created successfully in the Auth table in firebase

What am i missing here?

Thanks!

**Comment by rphlmr** [comment]
Hello,
Maybe https://firebase.google.com/docs/auth/web/auth-state-persistence#supported_types_of_auth_state_persistence can help ?

I think that auth persists only on domain where the user logedin. It can explain why the the observable doesn't fire.

Disclaimer : I never used auth with chrome extension 😅

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out. I believe this is a bug. Tracking internally in b/159230717

**Comment by yuchenshi** [comment]
@Arieg419 Could you please share more details about your use case? Especially, where are you initiating the sign-in flow? Where is the sign-in actually handled? And where do you eventually want to implement features that requires the user to be signed in? For each of these questions, is it:

* A normal web page (like `example.com`)?
* A content script injected by your Chrome extension to run on the web page?
* A Chrome extension page? Like `chrome-extension://xxxxxxxxx/options.html`, or
* A Chrome extension background page / script?

Just in case you wonder, each of those contexts listed above have its own different window object and may have its own instance of the Firebase SDK. For example, when the user signs in on a normal web page, it will NOT affect the Firebase SDK running on your Chrome extension background page. You may however find some way to manually pass the access token from one place to another, using Chrome extension superpowers.

Also, the Firebase Auth SDK does not current have a method exposing the _refresh_ token, which you'll need to keep the users "signed in" for long term. But if you dig deeper you may find it in the web storage... We don't officially support that though, yet.

One last thing, could you please check the Chrome dev tools for each of the contexts you're using to see if there is any error?
