### ISSUE TITLE
RTDB logger will always print permission denied warnings

### ISSUE THREAD

**Issue by filipesilva** [firebase/firebase-js-sdk#3211]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 83
  * Firebase SDK version: 7.15.1
  * Firebase Product: database

### [REQUIRED] Describe the problem

It's not possible to disable or configure the logger for Realtime Database, declared in

https://github.com/firebase/firebase-js-sdk/blob/0131e1fcade96853997fc04ba1fee0e8d40ed445/packages/database/src/core/util/util.ts#L34

When using failing validation via security rules, RTDB will show messages such as the below even if the error is caught:
```
[2020-06-12T13:41:19.487Z]  @firebase/database: FIREBASE WARNING: set at /v10/dbs/filipesilva/log/-M9ckqvwrPq3XeeZZabl failed: permission_denied 
```

These can be expected and handled at the application level, but they will always show up in the console.

#### Steps to reproduce:
Use validation rules, write to the validated path in such a way as to prevent the write, and catch the error.

**Comment by schmidt-sebastian** [comment]
@filipesilva Thanks for taking the time to file this issue.

You can raise the global log level by invoking `firebase.setLogLevel()` - https://firebase.google.com/docs/reference/js/firebase#setloglevel. This should change the log output for all Firebase SDKs, including the Realtime Database.

**Comment by filipesilva** [comment]
Heya @schmidt-sebastian, I had tried that before on my application and it didn't seem to make any difference.

I've pushed a reproduction to https://github.com/filipesilva/firebase-rtdb-loglevel that shows this using the emulator.

To reproduce, follow these steps:
- `git clone https://github.com/filipesilva/firebase-rtdb-loglevel`
- `cd firebase-rtdb-loglevel`
- `npm i`
- `npm run emulators`
- save `database.rules.json` once, I'm not sure why this is needed but it seems like an emulator bug
- open http://localhost:5000/
- see the following logs:
```
pushing
[2020-06-16T19:07:23.460Z]  @firebase/database: FIREBASE WARNING: set at /path/-M9yWq8Gqh1CeOXMsQty failed: permission_denied
caught
```

That reproduction contains the following code in `public/index.html`, including a call to `setLogLevel`:
```
  <script>
    var config = {
      databaseURL: "http://localhost:9000?ns=undefined",
      projectId: "emulator-test-1",
    };
    firebase.initializeApp(config);
    firebase.setLogLevel("silent")
    console.log("pushing")
    firebase.database().ref('/path').push('value')
      .then(() => console.log("pushed"))
      .catch(() => console.log("caught"));
  </script>
```

And the following security rules:
```
{
  "rules": {
    ".read": true,
    ".write": false,
    "path":{
      ".validate": false
    }
  }
}
```

**Comment by filipesilva** [comment]
@schmidt-sebastian WDYT of reopening it given the repro showing the `setLogLevel` not having an effect?

**Comment by schmidt-sebastian** [comment]
We will look at this again.

**Comment by Feiyang1** [comment]
I notice that you are using individual CDN scripts, `firebase-app.js` and `firebase-database.js`. They don't share the same logger implementation because the way they are packaged (each of them has its own copy of logger implementation), so calling `firebase.setLogLevel()` has no effect on `firebase-database.js`.

To workaround it, you can use `firebase.js` instead, but you will get a warning that says don't use this build in production. So to completely silent console, you may need to use the npm version and build a bundle.

**Comment by filipesilva** [comment]
@Feiyang1 trying what you suggested and I can confirm the warning is gone, thanks!
