### ISSUE TITLE
`onAuthStateChanged` parameter `complete` doesn't fire when unsubscribed.

### ISSUE THREAD

**Issue by yi-fan-song** [firebase/firebase-js-sdk#3214]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro Version: 10.0.18363 Build 18363
  * Browser version: Firefox 77.0.1 (64-bit)
  * Firebase SDK version: 7.15.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
When using `onAuthStateChanged`, the third parameter `complete` doesn't fire when the listener is unsubscribed.

#### Steps to reproduce:
Subscribe to `onAuthStateChanged`, include third parameter, then unsubscribe, the `complete` parameter will not fire.

#### Relevant Code:

https://jsbin.com/qebanicipe/1/edit?js,console

```javascript
var unsubscribe = firebase.auth().onAuthStateChanged(
    (user) => {
  	  console.log("0");
      unsubscribe();
    },
    (a) => {},
    () => {
      // this doesn't run
      console.log("1");
    }
  );
```

**Comment by samhorlbeck** [comment]
Thanks for reaching out, this looks like a bug. Tracking internally at b/159232037

**Comment by bojeil-google** [comment]
It is not clear this is Auth related, We use `firebase.INTERNAL.createSubscribe()` to handle these listeners. I would investigate there first.

**Comment by hsubox76** [comment]
So I think I've found the issue but I'm not sure what the correct fix is.

The 3rd argument to `onAuthStateChanged()` (the function that's not getting called in the example above) ultimately ends up being passed as the 3rd argument to `Observer.subscribe()` in [packages/util/subscribe.ts](https://github.com/firebase/firebase-js-sdk/blob/c436bcc6477c964861d0014cd0c74c6493f24cf2/packages/util/src/subscribe.ts#L131)

This param is named `complete` which gives the impression it would be run on unsubscribe, but it is not. Comments on [lines 25 and 27](https://github.com/firebase/firebase-js-sdk/blob/c436bcc6477c964861d0014cd0c74c6493f24cf2/packages/util/src/subscribe.ts#L25) seem to indicate it was actually meant to a method that could be manually called to terminate the stream?

In any case, the [actual unsubscribe function](https://github.com/firebase/firebase-js-sdk/blob/c436bcc6477c964861d0014cd0c74c6493f24cf2/packages/util/src/subscribe.ts#L198) has no hooks to run a user-provided callback. It can be modified to do so, but I'm not sure if `complete` should be run here or if if we should have an additional param that is run here. Not sure if changing what `complete` does will affect other packages. Perhaps the auth code can wrap the returned `Unsubscribe` to run a user-provided callback as well?

**Comment by yi-fan-song** [comment]
The references and comments should be added to match its behaviour, [onAuthStateChanged doc](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged) has no comments about the usage of the `error` and `complete` arguments, so I assumed that it would be the same than [onIdTokenChanged](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onidtokenchanged), maybe the comments for `onIdTokenChanged` are wrong?

**Comment by marcusx2** [comment]
2022, this still wasn't fixed.

**Comment by sam-gc** [comment]
The current version of the SDK is v9, which is a total rewrite. Please update to v9 (compatibility, as necessary, as the syntax has changed). We won't be making any fixes to v8 or earlier unless it's a security vulnerability.

**Comment by marcusx2** [comment]
I am talking about v9

**Comment by nhtzq** [comment]
Same here. I am using `onAuthStateChanged` and I want to trigger a custom callback when the observer is removed by adding the call back to the 4rd param (`completed`). It doesn't work.

For your reference:
```
export declare function onAuthStateChanged(auth: Auth, nextOrObserver: NextOrObserver<User>, error?: ErrorFn, completed?: CompleteFn): Unsubscribe;

/**
 * Adds an observer for changes to the signed-in user's ID token, which includes sign-in,
 * sign-out, and token refresh events.
 *
 * @param auth - The {@link Auth} instance.
 * @param nextOrObserver - callback triggered on change.
 * @param error - callback triggered on error.
 * @param completed - callback triggered when observer is removed.
 *
 * @public
 */
```

**Comment by marcusx2** [comment]
@nhtzq Well according to @sam-gc the error and completed parameters are [not used](https://github.com/firebase/firebase-js-sdk/issues/6254#issuecomment-1122652146) in the v9 version.

**Comment by lisajian** [comment]
Seems like this is no longer an actionable issue, marking as closed, but feel free to re-open or file a new bug if you want to discuss further!

**Comment by hsubox76** [comment]
Thanks! It's also in the reference docs (which are derived from those comments): https://firebase.google.com/docs/reference/js/auth.md#onauthstatechanged
