### ISSUE TITLE
Youtube access with firebase authentication

### ISSUE THREAD

**Issue by techterbium** [firebase/firebase-js-sdk#3215]
### [REQUIRED] Describe your environment

  * Operating System version: mac
  * Browser version: Chrome 83
  * Firebase SDK version: 7.14.5
  * Firebase Product: auth

I am using firebase authentication to login my users. I have added necessary scopes to access youtube API. I got stuck from here. 

How do I access youtube API from here on? which library to use to access youtube live API? what data that I get from firebase auth needs to be passed on to this library to access youtube on behalf of user?

Any pointers here will be much appreciated. thanks in advance.

**Comment by samhorlbeck** [comment]
Hi,
You will likely need to use the Google access token that is returned in the promise immediately following sign in (this code, and more info, is [from our docs here](https://firebase.google.com/docs/auth/web/google-signin)):
```js
firebase.auth().signInWithPopup(provider).then(function(result) {
  // This gives you a Google Access Token. You can use it to access the Google API.
  var token = result.credential.accessToken;
});
```
