### ISSUE TITLE
After being offline SDK doesn't get back online 

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-js-sdk#3232]
### [REQUIRED] Describe your environment

  * Operating System version: _____iOS 12.4.7
  * Browser version: _____ Safari 12.4.7
  * Firebase SDK version: _____ 7.15.1 and 7.15.3 (I tried to upgrade to see if the issue remains, and it does)
  * Firebase Product: _____ auth, firestore, storage

#### Steps to reproduce:
I have persistence enabled on my PWA and _sometimes_ when it goes back online after having been offline for some time, the connection to Firebase is never re-established until I kill the app and restart.
I write _sometimes_ because this does not always happen and I have not been yet to reproduce it accurately.

Notes:
1) I am testing my PWA on various other browsers (IE, Chrome, Firefox) and platforms (Windows 10, Ubuntu, Android) and this only happens on Safari on iOS (I have not tested it on Mac through).
2) My PWA is using other data sources and they are working fine when my PWA is back online so it is not a network issue

#### Relevant Code:
Not been able to reproduce it yet. Is it a known issue however?

**Comment by var-const** [comment]
Thank you for reporting the issue. The description has some similarities to #1533, which in turn is due to [this issue](https://bugs.webkit.org/show_bug.cgi?id=197050) in Safari. However, that issue only manifests if the app is put in the background -- does that happen in your case? Also, can you please [enable debug logging](https://gist.github.com/katowulf/0475fb7a5907ed757f687aab6ed15878) and post the resulting logs (please make sure to omit any sensitive information)?

**Comment by olivierkrener** [comment]
I have enable debug logging, will post the logs once the issue happens again.

Fyi the link you post shows for JS
https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#setLogLevel

This is incorrect, should be updated to
https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel

**Comment by olivierkrener** [comment]
Attached is a log file during which the issue occurred, I cant find anything suspicious but maybe you are more lucky. It also contains my app's logs but you will have no pb making the difference. Nothing sensitive in there. 

[logs.txt](https://github.com/firebase/firebase-js-sdk/files/4814561/logs.txt)

**Comment by var-const** [comment]
Unfortunately, nothing immediately stood out in the logs. It's a little weird that some expected log entries about communication with the backend are missing, though.

> This is incorrect, should be updated

Thanks for noticing! This was fixed.

**Comment by olivierkrener** [comment]
How to proceed? Should I send you more logs?

**Comment by var-const** [comment]
Are these the full logs? If yes, then more logs probably won't contain any additional information. We would need a reproduction case to proceed.

One more question: how does your app notice that Firestore is offline? Does it start getting snapshots with `fromCache=true`?
