### ISSUE TITLE
Feature Request: get partial doc data like GraphQL

### ISSUE THREAD

**Issue by cbazza** [firebase/firebase-js-sdk#3235]
It would be really nice if we could specify a filter when getting doc data so that only certain fields of the document are returned. It could be something very similar to GraphQL and it would work for real time updates as well.

```
var docRef = db.collection("cities").doc("SF");

var getOptions = {
    filter: '{
      name
      stats {
        area
        population
      }
    }',
};

docRef.get(getOptions).then(function(doc) {
    // city would only contain '{name, stats:{area, population}}'
    var city = doc.data();
}).catch(function(error) {
    console.log("Error getting cached document:", error);
});
```

**Comment by wilhuff** [comment]
Hi! Thanks for writing in. This has been requested before in #212. See discussion there for why we haven't attempted this yet.
