### ISSUE TITLE
FR: Using a document's ID for pagination

### ISSUE THREAD

**Issue by wceolin** [firebase/firebase-js-sdk#3238]
### Describe your environment

  * Operating System version: MacOS 10.13.6
  * Browser version: Chrome 83.0.4103.106
  * Firebase SDK version: 7.15.1
  * Firebase Product: Firestore

### Describe the problem

Using [pagination on Firestore](https://firebase.google.com/docs/firestore/query-data/query-cursors#paginate_a_query) currently requires keeping track of the fields used in our `orderBy` query or using the `DocumentSnapshot` from the last visible item.

However, sometimes we don't have the last item's snapshot - just its ID. For example: for one application, I'm server-rendering the initial list of items. I can't send the latest item's snapshot to the client. To make pagination work right now, I need to send an additional request just to get that item's snapshot.

It would nice to allow pagination by using a document ID or path instead.

#### Steps to reproduce:

The code below should work:

```javascript
firebase
  .firestore()
  .collection('posts')
  .orderBy('score', 'asc')
  .startAfter('posts/lastVisibleID')
  .limit(10)
  .get()
```

Or using something similar such as `startAfter(postId)`, `startAfter(db.doc('posts/postId'))`, etc.

#### Relevant Code:

https://codesandbox.io/s/firebase-template-1d7d1?file=/src/App.js

**Comment by var-const** [comment]
Thanks for the feature request! Unfortunately, the issue here is that a document ID doesn't uniquely identify the _position_ of a document within the result set of a query. Certain kinds of indexes can contain a document more than once, in which case using a document ID in `startAfter` or similar clauses would be ambiguous.
