### ISSUE TITLE
firebase.auth().currentUser.updateProfile() promise doesn’t resolve

### ISSUE THREAD

**Issue by Haraldson** [firebase/firebase-js-sdk#325]
### My environment

  * Operating System version: macOS 10.12.5
  * Firebase SDK version: 4.6.1
  * Firebase Product: auth

### The problem

When calling `firebase.auth().currentUser.updateProfile({ displayName: 'foo' })`, the profile is updated correctly, but the promise doesn’t resolve.

#### Steps to reproduce:

Call `firebase.auth().currentUser.updateProfile()` with a `.then()`.

#### Relevant Code:

My React component below for reference. The `onSubmit` handler is called, and the profile gets updated correctly, but the `then` callback is never executed.

```javascript
import React, { Component } from 'react'
import Fire from '../fire' // an initialized firebase app, but the same happens when using the firebase dependency directly
import { formSerialize } from 'react-form-utils'

const auth = Fire.auth()

export default class EnrichProfile extends Component {
    onSubmit(e) {
        e.preventDefault()

        const profile = formSerialize(e.target)
        auth.currentUser.updateProfile(profile)
            .then(() => {
                this.props.onDisplayNameChanged(profile.displayName)
            })
            .catch(error => {
                // An error occured
            })
    }

    render() {
        return (
            <form onSubmit={this.onSubmit}>
                <h1>Enrich your profile</h1>
                <input type="text" name="displayName" placeholder="Your username" pattern="[A-Za-z0-9æÆøØåÅ]{3,30}" required />
            </form>
        )
    }
}
```

**Comment by Haraldson** [comment]
My apologies. I thought I’d covered all the bases, but the error is – once again – on my end

**Comment by tenwang** [comment]
How did u get it working.. I have the same issue

**Comment by Haraldson** [comment]
The problem was elsewhere, the `.then()` should work.

**Comment by tenwang** [comment]
Thanks..though I had to use some other route. this.af.auth.currentUser.updateProfile  where af is import { AngularFireAuth } from 'angularfire2/auth';

**Comment by KaneNguyen** [comment]
I have some issue, Somebody help me :(
