### ISSUE TITLE
nested firebase rules fail, owner id within parent document

### ISSUE THREAD

**Issue by matze1234** [firebase/firebase-js-sdk#3258]
I can't get these rules to work:
I've got a collection with projects, which all have an owner. The owner should be allowed to read/write his projects and the subcollection working_copies as well.

This implementation succesfully grants reading the project, but fails (insufficient permissions) when reading a working_copy from the sub collection. I suspect it tries to find an owner within the sub-document.

    service cloud.firestore {
    
      match /databases/{database}/documents {
    
        match /projects/{projectId} {
          allow read, write: if 
          	resource.data.owner == request.auth.uid;
    
          match /working_copies/{doc} {
            allow read, write: if true;
          }
    
      }
    }

I've also tried using this condition either in the project path or in the working_copies path, but it both fails as well:

        get(/databases/$(database)/documents/projects/$(projectId)).data.owner == request.auth.uid

Everything above also fails when i use a recursive wildcard for nesting:

    match /projects/{projectId=**} {
       ...

The strange thing is, i think the first version used to work until some days ago.

I call it using angularfire:

`this.db.collection('projects').doc('3279').collection<ProjectData>('working_copies').valueChanges().pipe(...`

In the simulator it works though.

**Comment by scottcrossen** [comment]
Are you able to reproduce this in the [emulator suite](https://firebase.google.com/docs/rules/emulator-setup)?

Please attach your [coverage report](https://firebase.google.com/docs/firestore/security/test-rules-emulator#generate_test_reports) after a run of the rules. Also feel free to attach a report used with the wildcard matching

If the Rules Playground (FKA simulator) works then I suspect it has something to do with the queries not actually targeting your listed collections.

**Comment by scottcrossen** [comment]
I am listing this under auth for internal tracking purposes (and because there isn't a label for rules yet)

**Comment by scottcrossen** [comment]
[This link](https://firebase.google.com/docs/rules/emulator-reports) may be helpful when creating those test reports.

Also, I'm going to mention your name to let you know I've responded: @matze1234

**Comment by matze1234** [comment]
I've finally found a workaround:
`!('owner' in resource.data) || resource.data.owner == request.auth.uid`

So it seems, when nesting rules, the parent rules are also applied to child documents. I guess in most use cases, that doesn't make sense.

I'm somewhat suprised i'm the only one having this problem and this use case. Somehow in most examples with nesting, the owner id is reflected as a document id in the tree's root, not as a property within the data object. But there are more things in the world you can own than your own user object.

By the way, i found out that projectId was != null but also != any real projectId, that i tried. So it remains mysterious to me what it is, since i can't debug it.

**Comment by matze1234** [comment]
I expected this to be re-opened. Isn't the described behavior a bug in the rules processor?
