### ISSUE TITLE
FR: handle temp mail vs EmailAuthProvider

### ISSUE THREAD

**Issue by AoDev** [firebase/firebase-js-sdk#3281]
### Describe your environment

  * Operating System version: OSX 10.14.6
  * Browser version: Brave
  * Firebase SDK version: 7.15.1
  * Firebase Product: auth

### Describe the problem

With the explosion of temporary mail providers, **e-mail validation is practically useless**.  
We are about to use a project like [mailChecker](https://www.npmjs.com/package/mailchecker) to deal with the problem. (more than 30 000 domains blacklist)
But we **can not do anything at Firebase auth level**. We can only let the user register and then implement a solution to delete or block the account right after.

### Feature Request
I'd like to know if Google/Firebase could do something on their side to deal with email providers blacklist / whitelist or something else.

Thanks

**Comment by nVitius** [comment]
You might be interested in checking out Identity Platform's new [Blocking Functions](https://cloud.google.com/identity-platform/docs/blocking-functions).

I haven't used it yet, but from what I understand Identity Platform is fully compatible with Firebase Auth and you can just switch over to it.
Some more reading:
https://cloud.google.com/identity-platform/docs/product-comparison
https://github.com/firebase/firebase-admin-node/issues/875

That said, you might consider creating a cloud-function that checks the email domain and calling it directly from the registration page. Decide wether or not to register the user base on that. I feel that should block most of the registrations.
You could also have a separate cloud function that's triggered with `functions.auth().onCreate` and check the emails again in there. This would catch any that bypassed the Frontend validation.

If you delete user accounts this way, it's probably a good idea to also revoke their access tokens. https://firebase.google.com/docs/auth/admin/manage-sessions#revoke_refresh_tokens

**Comment by DellaBitta** [comment]
I'm going to close this issue for now as this appears to be more of a platform feature request than a JS SDK feature request. Please reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) to submit a formal feature request to the platform team. Thanks!
