### ISSUE TITLE
Callable Function throw Deadline Exceeded Error even on successful response

### ISSUE THREAD

**Issue by stevecastaneda** [firebase/firebase-js-sdk#3289]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Catalina 10.15.5
  * Browser version: Chrome 83.0.4103.116
  * Firebase SDK version: 7.15.5
  * Firebase Product: Functions
  * Issue persists with Node 12.18.1 and 14.4.0

https://github.com/firebase/firebase-js-sdk/blob/ee130b56b2813fb1c01fd9430059814ece45a738/packages/functions/src/api/service.ts#L187

#### Steps to reproduce:
This is a continuation from issue #2746, and I'm experiencing the same `deadline-exceeded` error even after Promise.race successfully returns a promise (as evidenced by the callable function returning data as I expect).

@minism

#### Function Relevant Code: [Typescript]

```
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
admin.initializeApp();

export const helloUser = functions.https.onCall((data, context) => {
  if (context.auth) {
    return { response: "There's a user!", data };
  } else {
    throw new functions.https.HttpsError("permission-denied", "You must be logged in.");
  }
});
```
### Frontend (React)
```
async function testFunction() {
  try {
        let functionTest = functions.httpsCallable("helloUser");
        let response = await functionTest();
        console.log(response);
      } catch (error) {
        console.log(error);
      }
}
```

**Comment by stevecastaneda** [comment]
For reference, could this be a proposed solution so that the timer is cleared when Promise.race is satisfied?

https://stackoverflow.com/questions/30936824/what-is-the-best-general-practice-to-timeout-a-function-in-promise

```
export function race({promise, timeout, error}) {
  let timer = null;

  return Promise.race([
    new Promise((resolve, reject) => {
      timer = setTimeout(reject, timeout, error);
      return timer;
    }),
    promise.then((value) => {
      clearTimeout(timer);
      return value;
    })
  ]);
}
```

**Comment by Feiyang1** [comment]
@stevecastaneda issue #2746 mentions the issue only manifests in Node. Is your issue also happening in Nodejs (server rendering)? Just want to clarify because you include React code, also that I can't reproduce it in browser.

**Comment by stevecastaneda** [comment]
I'm running React locally along with emulated firebase functions.  Interestingly enough, I just noticed that after deploying the site to a host along with functions to Firebase, I don't get the error anymore.  (the deployed site is using firebase functions vs. local emulated functions, same code though).

So perhaps this is isolated to running a local build of React?

**Comment by stevecastaneda** [comment]
Using the deployed function still threw the error, so it looks like the culprit is the local build of React that I'm running.  This is create-react-app with Typescript.

**Comment by stevecastaneda** [comment]
Nevermind.  It's also happening on the deployed site, unfortunately.  Tested by adding a 10-second timeout to the callable function (that did return well before that).

Any recommendations on how I can help diagnose this issue?

**Comment by Feiyang1** [comment]
Would you mind sharing the deployed site?

**Comment by minism** [comment]
@Feiyang1 I have a repro for the bug at the end of #2746.  I was hoping my comment would reopen the bug but unfortunately it didn't.

**Comment by stevecastaneda** [comment]
@minism Thanks!

@Feiyang1 If you can't reproduce there, let me know and I can create a new CRA site and deploy it for testing.

**Comment by stevecastaneda** [comment]
I'm able to trigger this error even with the simplest of callable functions.  Here's an example:

https://gist.github.com/stevecastaneda/7c07f91ce1eeef005175071efda39401

**Comment by Feiyang1** [comment]
https://github.com/firebase/firebase-js-sdk/pull/3330 should resolve the issue.

**Comment by stevecastaneda** [comment]
@Feiyang1 Thank you!
