### ISSUE TITLE
"initStandalone" function missing from database JS file

### ISSUE THREAD

**Issue by ryanlitalien** [firebase/firebase-js-sdk#329]
### Context
I'm working with an electron app that uses Node and firebase-admin.

### Problem
When calling `DatabaseService.prototype.getDatabase`, it looks up the wrong `@firebase/database` file via `require`, as it loads the `index.js` file first and skips the `index.node.js` file. As such, there is no `initStandalone` method in the `.js` version, but one exists in the .node` version. I was able to rename the `index.js` file to `index.foo` and it properly loaded the `.node` file and the code continued successfully. 

This is the line it fails on: https://github.com/firebase/firebase-admin-node/blob/a8db16efd76882554f0037d854a255d1fdfa045a/src/database/database.ts#L69

### References
https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/index.node.ts#L38-L51
https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/index.ts - missing
https://github.com/firebase/firebase-admin-node/blob/a8db16efd76882554f0037d854a255d1fdfa045a/src/database/database.ts#L69

### Request
Add the `initStandalone(...)` function to the `js` source

Thanks! :smile:

**Comment by mickbalaban** [comment]
I ran into this issue last night when deploying serverless app with firebase-admin. 
Renaming index.js, like @ryanlitalien suggested, fixed the error.

**Comment by jshcrowthe** [comment]
I will work with @hiranya911 to get this resolved. the `initStandalone` function exists only for our admin SDKs so I'm disinclined to add it into the client code.

However there is probably a way to solve this w/o impacting our users. I'll circle back when I have an update on this.

**Comment by brian-traceme** [comment]
I'm hitting this issue when trying to update a firebase db from an aws lambda, also deployed via serverless.

**Comment by brian-traceme** [comment]
So, we fixed it in our webpack file with resolve: {mainFields: ['main']}

It seemed to not be just the database, but we needed every bit of firebase loaded with index.node.js

**Comment by fantapop** [comment]
It looks like what we were running into is that the firebase packages are assuming that if you're using the module syntax then you're on the web.  The package.json files all specify "modules" to point to the web specific js files.

**Comment by ayyouboulidi** [comment]
I am running into the same problem.

is there a way to solve it ? 
indeed i am trying to use the admin sdk on a web app and not on the server.

**Comment by jshcrowthe** [comment]
@brian-traceme, @fantapop [NPM's package.json doc](https://docs.npmjs.com/files/package.json) doesn't support a pkg.module. This was [driven by the folks on the Rollup team](https://github.com/rollup/rollup/wiki/pkg.module) and support was added to Webpack to allow for code optimizations. If you are using a bundler that supports pkg.module, but are targeting node.js, you will need to force that bundler to import the node version.

@ayyouboulidi Using the admin SDKs is not possible from a web app as it requires certain low level libraries that have no support in web.
