### ISSUE TITLE
Reference docs on DeltaDocumentSnapshot data method is incorrect

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-js-sdk#330]
In the [reference docs]( https://firebase.google.com/docs/reference/functions/functions.firestore.DeltaDocumentSnapshot#data) it says that the DeltaDocumentSnapshot `data` method returns a DeltaDocumentSnapshot. 

The text is correct I guess, just not the return type. According to the source code it is `any`.

**Comment by rockwotj** [comment]
Hello, thanks for bringing this up! I believe you are referring to the functions code found here: https://github.com/firebase/firebase-functions/blob/master/src/providers/firestore.ts#L79

If that's it would you mind opening the issue in that repo and closing this one? Thanks!

**Comment by laurenzlong** [comment]
It's actually an issue with the functions docs, closing this bug.
