### ISSUE TITLE
Firebase Invisible ReCaptcha callback not being fired

### ISSUE THREAD

**Issue by vinaysharma14** [firebase/firebase-js-sdk#3314]
### Environment

  * Operating System version: macOS Catalina 10.15.5 (19F101)
  * Browser version: Version 83.0.4103.116 (Official Build) (64-bit)
  * Firebase SDK version: ^7.15.1
  * Firebase Product: auth

### Problem
Callback is not being fired using invisible reCaptcha for phone number authentication.

#### Steps to reproduce:
Click on the submit button and you'll notice that the callback is not being fired with the console statement.

#### Relevant Code:

```
import React from 'react';

import firebase from 'firebase/app';
import 'firebase/auth';

const firebaseConfig = {
  apiKey: 'xxx',
  authDomain: 'xxx',
  databaseURL: 'xxx',
  projectId: 'xxx',
  storageBucket: 'xxx',
  messagingSenderId: 'xxx',
  appId: 'xxx',
  measurementId: 'xxx',
};

firebase.initializeApp(firebaseConfig);

function App() {
  const handleSubmit = event => {
    event.preventDefault();

    window.reCaptchaVerifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
      size: 'invisible',
      callback: function (response) {
        // callback is not being fired
        console.log(''I am not being logged in console);
      },
    });
  };

  return (
    <form onSubmit={handleSubmit}>
      <input />
      <button id="sign-in-button">Submit</button>
    </form>
  );
}

export default App;
```

**Comment by scottcrossen** [comment]
Internal tracking bug: b/160175350

**Comment by vinaysharma14** [comment]
> Internal tracking bug: b/160175350

Hi @scottcrossen were you able to reproduce this issue?

**Comment by 99diagha** [comment]
Hi,
Has there been any progress on this issue so far?

**Comment by vinaysharma14** [comment]
@99diagha don't think so.

**Comment by jossydeleon** [comment]
At the end add: 
`window.reCaptchaVerifier.render()`

**Comment by colinwagaba** [comment]
Initially thought I had something misconfigured - same issue here, any luck?

**Comment by vinaysharma14** [comment]
@jossydeleon an invisible reCaptcha is supposed to render itself. As per docs, we do not need to render it explicitly with `window.reCaptchaVerifier.render()`. This is absolutely optional if you need to [pre-render](https://firebase.google.com/docs/auth/web/phone-auth#optional:-pre-render-the-recaptcha) it.

**Comment by vinaysharma14** [comment]
@jossydeleon an invisible reCaptcha is supposed to render itself. As per docs, we **do not need to render it explicitly** with `window.reCaptchaVerifier.render()`. This method is optional and used only in case you need to [pre-render](https://firebase.google.com/docs/auth/web/phone-auth#optional:-pre-render-the-recaptcha) it.

**Comment by jossydeleon** [comment]
@vinaysharma14 Yes I know, but using render() or verify() was the only way to run the function and get the callback fire with response.

`
window.reCaptchaVerifier = new Auth.RecaptchaVerifier("sign-in-button", {
      size: 'invisible',
      callback: function (response) {
        // callback is not being fired
        console.log('I am not being logged in console: ' + JSON.stringify(response));
      },
    }).verify()
`

**Comment by vinaysharma14** [comment]
@jossydeleon well this is not an appropriate approach and needs a fix in Firebase's internal working.

**Comment by vinaysharma14** [comment]
@jossydeleon well, this is not an appropriate approach. Firebase team needs to be rectify this under the hood.

**Comment by jossydeleon** [comment]
@vinaysharma14 you are assigning a function to window.recaptchaVerifier, but you never call the method to run it. For that reason is render and verify. You have to call then in order to execute the promise. You can google some examples.

https://stackoverflow.com/questions/48349567/firebase-phone-sign-in-where-to-put-firebase-recaptcha-code

https://medium.com/google-developer-experts/verifying-phone-numbers-with-firebase-phone-authentication-on-your-backend-for-free-7a9bef326d02

**Comment by colinwagaba** [comment]
The above works, thanks, tho I think the documentation/guide should be updated - if that's how it's meant to work! 👏🏾

**Comment by sugar3103** [comment]
> @vinaysharma14 Yes I know, but using render() or verify() was the only way to run the function and get the callback fire with response.
> 
> `window.reCaptchaVerifier = new Auth.RecaptchaVerifier("sign-in-button", { size: 'invisible', callback: function (response) { // callback is not being fired console.log('I am not being logged in console: ' + JSON.stringify(response)); }, }).verify()`

i have fixed that by add ".verify()" to make to callback fired.
Thank you

**Comment by vinaysharma14** [comment]
@jossydeleon thanks for sharing your valuable suggestions. Would try and check how it works. But I still believe the documentation should be updated.

**Comment by solkpolk** [comment]
Here is an ugly solution https://stackoverflow.com/questions/66740255/next-js-firebase-auth-phone-number-invisible-recaptcha

**Comment by willvlad** [comment]
It's been over a year this issue has been raised. Anyone from Firebase - any solutions? This is quite important for us now!!

**Comment by samhorlbeck** [comment]
Hi folks,

The original snippet doesn't work because it's set up slightly wrong, I believe. The invisible recaptcha needs to be attached to the button _before_ the form is submitted (in the snippet, the verifier is created _after_ the button has been pressed). Here's an example:

```html
<form action="#" onsubmit="doSubmit(); return false;">
  <button type="submit" id="sign-in-button">Test!<button>
</form>
```

```js
// After page load
const verifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
  size: 'invisible',
  callback: () => { console.log('Callback!'); },
});

async function onSubmit() {
  const cr = await firebase.auth().signInWithPhoneNumber('######', verifier);
  // Get the code from the SMS
  await cr.confirm(code);
}
```

The key here is that the verifier is created and attached to the button _before_ the form submit code is called. The callback is correctly called and "Callback!" is logged with this code.

**Comment by kawerewagaba** [comment]
@sam-gc you're right. The mistake I was making was to attach on submit. Thanks for the analysis.

**Comment by sam-gc** [comment]
Thanks for double checking! I'm going to go ahead and close this bug out for now.
