### ISSUE TITLE
@firebase/testing should have dependency on @firebase/component

### ISSUE THREAD

**Issue by adelespinasse** [firebase/firebase-js-sdk#3331]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04
  * Browser version: Node.js v10.19.0
  * Firebase SDK version: 7.15.5
  * Firebase Product: Firestore, auth

### [REQUIRED] Describe the problem

Project uses, among other things, Firestore, React 16.12.0, Jest 24.9.0.

The devDependencies include:
```
    "@firebase/testing": "^0.20.5",
```

When the Jest tests run, each test that uses `@firebase/testing` gives an error like this:
```
    Cannot find module '@firebase/component' from 'index.cjs.js'

    However, Jest was able to find:
    	'../testUtil/firebase.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@firebase/testing/dist/index.cjs.js:9:17)
```

Looking at the code in `@firebase/testing`, it does indeed try to import module `@firebase/component`. Since `@firebase/component` is meant only for use by other Firebase components, I don't think I should need to explicitly declare a dependency on it; the dependency should be declared by `@firebase/testing`.

I think. There are subtleties of npm dependencies that I don't understand.

#### Steps to reproduce:

Make a project that depends on `@firebase/testing` and does not have a direct dependency on `@firebase/component`, and try to run it.

#### Workaround:

For now I have worked around this by adding to my devDependencies:
```
    "@firebase/component": "^0.1.15",
```

**Comment by Feiyang1** [comment]
`@firebase/testing` depends on `firebase` which depends on firebase packages (e.g. @firebase/app, @firebase/auth, etc) which all depend on `@firebase/component`, so `@firebase/component` should be installed for you automatically. 

Can you please remove `node_modules` and the lock file and do a clean install? It should solve your problem.
