### ISSUE TITLE
"firebase.remoteConfig is not a function" in Expo on React Native

### ISSUE THREAD

**Issue by bitttttten** [firebase/firebase-js-sdk#3339]
* Operating System version: mac OS 10.15.5
  * Browser version: React Native (Expo)
  * Firebase SDK version: firebase@7.9.0
  * Firebase Product: remote config

#### Relevant Code:

I am trying to use remote config in a React Native project using Expo.

```javascript
import * as firebase from "firebase"
import Constants from "expo-constants"

const firebaseConfig = {
	apiKey: Constants.manifest.web.config.firebase.apiKey,
	authDomain: `xxxxx.firebaseapp.com`,
	projectId: "xxxxx",
	databaseURL: `https://xxxx.firebaseio.com`,
	storageBucket: `xxxx.appspot.com`,
	messagingSenderId: `xxxxx`,
	appId: `1:xxxxx:web:xxxxxx`,
	measurementId: `G-xxxx`,
}

firebase.initializeApp(firebaseConfig)

const remoteConfig = firebase.remoteConfig()

remoteConfig.settings = {
	minimumFetchIntervalMillis: 3600000,
	fetchTimeoutMillis: 10000,
}

remoteConfig.defaultConfig = {
	questionnaire: "disabled",
}
```

Although I get an error on `const remoteConfig = firebase.remoteConfig()` with "TypeError: firebase.remoteConfig is not a function. (In 'firebase.remoteConfig()', 'firebase.remoteConfig' is undefined)". Even though the types are correct, as I am using TypeScript but in the typings .remoteConfig is defined.

I am not sure what I am doing wrong, although it is perhaps because I am trying to use expo and RN and I am doing something wrong, although I followed the [expo docs](https://docs.expo.io/guides/using-firebase/).

**Comment by bitttttten** [comment]
I imported the remote config package with `import "firebase/remote-config"`, although I see this is not supported on non-browser environments, and so I am a bit stuck. I guess this is an issue with support for remote config in a management expo workflow? So I don't mind it being closed for that reason, although I won't close it myself incase there is something I missed.

**Comment by Feiyang1** [comment]
You are correct that remote config doesn't work in React Native. Remote config requires indexeddb which is not available in React Native. I'm not aware of any good indexeddb polyfill for React Native, but if you found one, you might be able to get it to work. 

If you are open to switch from expo to vanilla react native development, you can take a look at https://rnfirebase.io/ which supports remote config and other growth products natively.

**Comment by bitttttten** [comment]
I am open to switching from Expo to vanilla react but I fear the overhead a bit. I am not sure what life without Expo looks like since I have only written a few projects with RN and they are all using Expo :)

I'll look into polyfilling indexeddb! Many thanks for your detailed reply 🙆‍♂️
