### ISSUE TITLE
Calling onMessage multiple times overwrites previous handler

### ISSUE THREAD

**Issue by svmn** [firebase/firebase-js-sdk#3345]
### [REQUIRED] Describe your environment

  * Operating System version: macos catalina 10.15.5 (19F101)
  * Browser version: chrome Version 83.0.4103.116 (Official Build) (64-bit) 
  * Firebase SDK version: 7.15.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
Calling onMessage multiple times overwrites previous handler
This was broken in this commit - https://github.com/firebase/firebase-js-sdk/commit/f7bf249d5b5182a579bf6424eed98710cfe6239e#diff-c33e1919c11b64f326bc1bf69a7b263eL152

#### Relevant Code:

```javascript
const messaging = firebase.messaging();
messaging.usePublicVapidKey(/* Public key here */);

messaging.onMessage((payload) => {
  console.log('Message received: ', payload)
})
messaging.onMessage((payload) => {
  console.log('Message received again: ', payload)
})
```

**Comment by infokani** [comment]
I  have same problem

**Comment by zwu52** [comment]
Hi svnm & infokani,
Looks like currently Internally FCM SDK stores the one callback for `onMessage` and hence the overriding behavior is WAI. Can you help me to understand your use cases for wanting to have two onMessage callbacks?
