### ISSUE TITLE
FR: Add the possibility to set the host and ssl in `firebase.clearFirestoreData` call.

### ISSUE THREAD

**Issue by mvolpato** [firebase/firebase-js-sdk#3355]
### Describe your environment

  * Operating System version: macOS 10.15.5
  * Browser version: No browser.
  * Firebase SDK version: 7.15.5
  * Firebase Product: Firebase, Firestore

### Describe the problem
I cannot call `firebase.clearFirestoreData` to clear the Firestore data, when Firestore emulator is not launched on port 8080. 

#### Steps to reproduce:
While working with the emulators, for testing Firestore rules, I start Firebase on a port that is not the default one.
I use `5002` instead of `8080`.
For this reason, when writing unit tests, I use
```
const firebase = require('@firebase/testing');
...
const db = firebase.initializeTestApp({ projectId: MY_PROJECT_ID, auth: { uid: uid } }).firestore()
db.settings({ host: "localhost:5002", ssl: false });
```

At the end of the tests, I would like to clear the data I created during tests, but `await firebase.clearFirestoreData({ projectId: MY_PROJECT_ID });` does not allow me to set the host, and produces the error `connect ECONNREFUSED 127.0.0.1:8080`

In fact, I see that `ClearFirestoreDataOptions` accepts only the project id.

It would be nice to be able to set the host and ssl option in the `firebase.clearFirestoreData` call.

**Comment by dzhamshed** [comment]
For now, you can do it by setting **FIRESTORE_EMULATOR_HOST** environmental variable:
```ts
process.env.FIRESTORE_EMULATOR_HOST = 'localhost:5002';
await testing.clearFirestoreData({ projectId: MY_PROJECT_ID });
```

**Comment by yuchenshi** [comment]
Fixed in rules unit testing v2.
