### ISSUE TITLE
Lighthouse 2.6.0 "DOM mutation events" fail audit

### ISSUE THREAD

**Issue by yaronyosef** [firebase/firebase-js-sdk#336]
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra 10.13
  * Firebase SDK version: "0.1.3"
  * Firebase Product: database

### [REQUIRED] Describe the problem

Lighthouse Version: 2.6.0 fails at the "Best Practices" section:

"Uses Mutation Events in its own scripts
Audit error: Required EventListeners gatherer encountered an error: Protocol error (DOM.resolveNode): No node with given id found"

#### Steps to reproduce:

just run Lighthouse Version: 2.6.0 on firebase database 0.1.3 and you'll see that error.

#### Relevant Code:

```javascript
document.addEventListener('DOMContentLoaded', wrappedFn, false);
```
at "packages/database/src/core/util/util.ts" line 260

**Comment by schmidt-sebastian** [comment]
@yaronyosef Thanks for reporting this issue. We have not seen this error before. Do you know if other users are affected? Thanks!

**Comment by esprehn** [comment]
DOMContentLoaded is not a mutation event, not sure what Lighthouse is finding. @paulirish

**Comment by paulirish** [comment]
Lighthouse TL here. The "Required EventListeners gatherer encountered an error" bit is an internal error of lighthouse. It means that audit couldn't complete. 

I'm pretty sure this sdk doesn't use DOM mutation events.

you can close this ticket.

**Comment by idibidiart** [comment]
@paulirish I see the same error when testing macys.com

"Audit error: Required EventListeners gatherer encountered an error: Protocol error (DOM.resolveNode): No node with given id found" 

If it's an internal error, it should be fixed.  Exposing internal errors in such low level detail without a high level explanation, e.g. audit could not complete, is a UX issue.

**Comment by jshcrowthe** [comment]
Thanks @paulirish! Can confirm, no DOM mutation events here. Closing per his comments.
