### ISSUE TITLE
IE11 Crashes with Firestore 7.15.5 - accessing the 'caller' property of a function or arguments object is not allowed in strict mode

### ISSUE THREAD

**Issue by thesandlord** [firebase/firebase-js-sdk#3367]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: IE 11
  * Firebase SDK version: 7.15.5
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

The `7.15.5` SDK crashes on IE11 in strict mode with the error:

```
Accessing the 'caller' property of a function or arguments object is not allowed in strict mode
```

`7.15.2` works fine, not sure what changed in between

#### Steps to reproduce:
Just using 7.15.5 in IE11 causes the issue, all you need to do is init the database.

Example here: https://tth9o.csb.app/

Code here: https://codesandbox.io/s/simple-firestore-javascript-example-tth9o?file=/index.html

**Comment by schmidt-sebastian** [comment]
This was fixed in https://github.com/firebase/firebase-js-sdk/pull/3309 and will be released this week.
