### ISSUE TITLE
firebase.loadFirestoreRules() causes "Payload Error"

### ISSUE THREAD

**Issue by aya-eiya** [firebase/firebase-js-sdk#3396]
When I updated firebase (and some related) modules, `firebase.loadFirestoreRules()` method turned to causes the "Payload Error", at a test uses "Firestore emulator".

## my code
```js
await firebase.loadFirestoreRules({
  projectId,
  rules: fs.readFileSync('./firestore/default.rules'),
});
```

## the error reported
```
Failed: Object {
 "code": 400,
 "message": "Payload isn't valid for request.",
 "status": "INVALID_ARGUMENT",
}
```

## work around

I removed the code from my test. the rules defined in 'default.rules' are seems to be loaded on emulator by default.

I'm not sure, but I remember in previous version, the rule file were not loaded by default, so
I wrote above code, I think. Is there are something change and the rule turned to be loaded automatically?

## Environments

* Operating System version: macOS 10.15.5
* Firebase SDK version: 7.16.0
* Firebase Product: Firestore

* the updated module settings are
```
"@firebase/testing": "^0.19.4" -> "^0.20.6"
"firebase-admin": "^8.12.1" -> "^8.13.0"
"firebase-functions": "^3.6.1" -> "^3.7.0"
"firebase-tools": "^8.3.0" -> "^8.5.0"
"firebase": "^7.14.4" -> "^7.16.0"
"google-gax": "not exists" -> "^2.0.0"
```

**Comment by MeghaB** [comment]
Hi @aya-eiya : You need to additionally pass in the encoding format to readFileSync (utf8), to ensure it's serialized properly, and can be loaded correctly.  See the (docs on testing with rules)[https://firebase.google.com/docs/firestore/security/test-rules-emulator#run_local_tests] for more details!

**Comment by aya-eiya** [comment]
Hi @MeghaB Thank you to replay.
setting the encoding works well.

P.S. I was curious, so I looked into the cause.

I found the change was how load the rule option to emulator.

https://github.com/firebase/firebase-js-sdk/pull/3236/files#diff-3262da3202f66a3ae1365d700617181eL225

previous code does not use `JSON.stringy()`.

* previous
```ts
client.setSecurityRules({
  project: `projects/${options.projectId}`,
  rules: { files: [{ content: options.rules }] }
})
```

* current
```ts
JSON.stringify({
  rules: {
    files: [{ content: options.rules }]
  }
})
```

`fs.readFileSync()` returns Buffer object when called without encode option, it exists, then returns String. and I did not set the option.

The previous code probably worked even if you passed a Buffer object, but current code uses `JSON.stringify()` so that the option modified to like '<Buffer 72 75 6c 65 73 5f 76 65 ...>' string, and it causes 'INVALID_ARGUMENT'.

Since the optional Type is defined as follows
```
export type LoadDatabaseRulesOptions = {
  databaseName: string;
  rules: string;
};
```

It seems that the previous behavior was precisely undefined behavior.

All bad is that the javascript code doesn't check the type.(you should use a "type" script.)
