### ISSUE TITLE
Microsoft social logins are only partly considered verified

### ISSUE THREAD

**Issue by sebastiaan-de-vries** [firebase/firebase-js-sdk#3404]
### Describe your environment

  * Operating System version: All
  * Browser version: All
  * Firebase SDK version: 7.14.5
  * Firebase Product: Auth

### Describe the problem
Microsoft social logins are considered verified if a hotmail.com account is used, but not if a microsoft.com account is used. I have not checked outlook.com, and perhaps there are even more domains that categorize as a Microsoft login.

In this [thread](https://github.com/firebase/firebase-ios-sdk/issues/5344), and other threads, it is stated that a social login provided by a party that actually owns the email service, should be trusted. Therefore I think this might be a bug?

#### Steps to reproduce:
Using a hotmail.com account, I am verified, using a microsoft.com account, I am not considered verfied, both by frontend code (Web SDK) and backend code (Firebase functions token verification).

**Comment by rosalyntan** [comment]
Thanks for reporting this! Filed b/161747786 for internal tracking.

**Comment by rosalyntan** [comment]
This should now be fixed and rolled out.

**Comment by sebastiaan-de-vries** [comment]
Thats great, thanks for letting me know!
Get Outlook for Android
