### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by sfthomas** [firebase/firebase-js-sdk#343]
* Operating System version: MacOS Sierra, Ubuntu 14
  * Firebase SDK version: 4.6.2
  * Firebase Product: core
  * npm@4.2.0 and npm@5.5.1
  * node@v7.10.1 and node@v8.7.0

Running 

`npm install --save firebase` fails with:

`npm ERR! code E404
npm ERR! 404 Not Found: @firebase/firestore@^0.1.4`

Other NPM packages work well.
Tried locally as well as on CircleCI build server.
Looks like something went wrong with the NPM packages?

**Comment by jshcrowthe** [comment]
Hey @sfthomas, I just tried to reproduce this using `npm@5.5.2` and was unsuccesful. Can you try again?

**Comment by sfthomas** [comment]
Hi @jshcrowthe, apologies, this is not a firebase problem - finally found the real root cause: https://github.com/npm/npm/issues/18569
