### ISSUE TITLE
Firebase Authentication + Quasar | Error: Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by myd-mannheim** [firebase/firebase-js-sdk#3438]
### [REQUIRED] Describe your environment
  * Operating System version: Windows 10
  * Browser version: Chrome 84.0.4147.89
  * Firebase SDK version: 7.16.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
I use firebase in my [Quasar](https://quasar.dev/) project. When I invoke one of the authentication functions signInWithRedirect or signInWithPopup provided by the firebase SDK (https://firebase.google.com/docs/auth/web/google-signin) I see the error 
'Uncaught SyntaxError: Unexpected token '<' ' in the console three times for the files vendor.<hash>.js, app.<hash>.js and manifest.json.
This occurs for dev builds (spa and pwa) as well as productive builds (also spa and pwa) (Quasar uses webpack). When I inspect the content of these files by clicking on the file name in the console I see that the content is in fact my index.html. So to me it looks like when these files are requested after the sign-in the index.html is returned for some reason.
I'm also able to reproduce this with a completly new setup project with the latest quasar app and CLI version and latest firebase SDK version.

#### Steps to reproduce:
To completly reproduce this from from scratch:

1. Setup a new Quasar project (newest version does the job). I followed https://quasar.dev/quasar-cli/installation and used quasar create
2. Setup PWA (https://quasar.dev/quasar-cli/developing-pwa/preparation) (not sure if pwa really has something to do with this)
3. Init new project with firebase. I used the npm variant: https://firebase.google.com/docs/web/setup#node.js-apps
4. Implement a button that triggers either signInWithRedirect or signInWithPopup as shown in the jsfiddle
5. quasar dev => Open the app => press 'Sign In' => Error occurs
6. quasar build + firebase deploy --only hosting -> visit the deployed app => press 'Sign In' => Error occurs

#### Relevant Code:
I've setup a JSFiddle with quasar where I can reproduce the behaviour for my firebase project:
https://jsfiddle.net/n4jp6b35/3/

I cannot setup a JSFiddle with the example project jscore-sandbox-141b5 because the JSFiddle domain needs to be added to the authorised domains in the firebase project settings.

I appreciate any help!
Thanks

**Comment by rosalyntan** [comment]
Hi @myd-mannheim , this seems like something may be misconfigured in your set up. I would recommend you contact Firebase support instead.
