### ISSUE TITLE
Cloud Functions callable function for Web not working in IOS 9  

### ISSUE THREAD

**Issue by LounaAkkad** [firebase/firebase-js-sdk#3447]
### [REQUIRED] Describe your environment

  * Operating System version: IOS 9
  * Browser version: SAFARI/chrome
  * Firebase SDK version:7.16.1
  * Firebase Product:Firebase Analytics

### [REQUIRED] Describe the problem
The Cloud Functions calling for Web give error in ios9 device
i already added core-js for polyfills

#### Steps to reproduce:
Create a sample html page
Add Firebase SDK (core and Analytics) :
import firebase from "firebase/app";
import "firebase/auth";
import "firebase/firestore";
import "firebase/database";
import "firebase/storage"
import "firebase/functions"
import "firebase/analytics";

open page in IPAD AIR 2  IOS9

**Comment by hsubox76** [comment]
I don't see the error under "gives below error", did you mean to attach an image or paste some text?
