### ISSUE TITLE
ServerValue is defined differently across `@firebase/database` and `@firebase/database-types`

### ISSUE THREAD

**Issue by MathBunny** [firebase/firebase-js-sdk#3477]
While working on [this PR](https://github.com/firebase/firebase-admin-node/pull/963) I came across the fact that ServerValue is defined differently across the two modules.

The concern is that for `@firebase/database-types`, an interface is exported which can be removed at compilation time, rendering my code (which was re-exporting the type) to not work.

The error would look something like this:
```
const serverValue = admin.database.ServerValue;

throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/example.test.ts (69,40): Property 'ServerValue' does not exist on type 'typeof database'. (2339)
```

Is it possible to use something closer to what is today in `@firebase/database`? For example a namespace?

**Comment by hiranya911** [comment]
AFAIK `ServerValue` is usually used as a value in the code:

```
// Calling static method
firebase.database.ServerValue.increment();

// As a value
ref.push({
 timestamp: firebase.database.ServerValue,
})
```

None of the above would work if `ServerValue` is defined as an interface. This may be a bug in the database-types package.
