### ISSUE TITLE
SEVERE: Something significant has changed after 4.6.0

### ISSUE THREAD

**Issue by richtera** [firebase/firebase-js-sdk#348]
try to call firebase.database() won't work since firebase.database is no longer defined when importing firebase.js.

### [REQUIRED] Describe your environment

  * Operating System version: Mac OS X and Ubuntu node 8 (webpack) browser (chrome, safari)
  * Firebase SDK version:  > 4.6.0 (didn't try 4.6.1 but 4.6.2 and 4.7.0 fails)
  * Firebase Product: database (auth, database, storage, etc)

use the new npm module and reference firebase.database.

### [REQUIRED] Describe the problem
 All my apps no longer work with 4.6.2 or 4.7.0 due to firebase.database being undefined.

#### Relevant Code:

http://jsbin.com/rinilu/edit?js,console

```javascript
// TODO(you): code here to reproduce the problem
firebase.database.ServerValue.TIMESTAMP
```
throws error that ServerValue of undefined cannot be accessed.

**Comment by richtera** [comment]
Caution my testing yesterday revealed that then 4.6.2 patch contains the broken 4.7.0 SDK. Took me a while to figure that out.

**Comment by richtera** [comment]
Looks like someone pushed updated to the npm repo. The yarn repo was still out of date 10 hours ago, but this morning both repos are up to date with a fixed version of 4.7.0.

**Comment by jshcrowthe** [comment]
Hey there @richtera, I've looked into this and this issue seems to be related to the semver capable versioning that was being used.

The behavior that you were seeing likely was due to yarn's caching. A clean reinstall, with a clean cache, would have fixed this.

That said, I can update the versioning to use exact versioning and that will help a bit.

**Comment by richtera** [comment]
Yea a clean install works now. It was failing with a clean yarn cache for some time yesterday which is why I posted the issue. It took a full yarn install with --no-cache to repair it on an affected machine. But thanks for fixing.

**Comment by jshcrowthe** [comment]
Awesome. I'm going to resolve this issue and hopefully you won't see it going forward.

Thanks for your help!
