### ISSUE TITLE
@firebase/performance TypeError: entryTypes contained only unsupported types

### ISSUE THREAD

**Issue by qnp** [firebase/firebase-js-sdk#3486]
Hi,

### My  environment

  * Operating System version: MacOS 10.14.6
  * Browser version: N/A but certainly Firefox
  * Firebase SDK version: 7.8.2
  * Firebase Product: performance 0.3.10

#### Steps to reproduce:

This error is thrown by @firebase/performance lib and watched by a global error tracker plugged on top of a webapp. I cannot reproduce the steps of the end user for which the error occured.

#### Relevant Code:

I could not isolate a piece of code reproducing the error. The only information I get is this stack-trace.

```
TypeError: entryTypes contained only unsupported types 
    at observe@[native code]
    at setupObserver (webpack:///node_modules/@firebase/performance/dist/index.cjs.js:176:25)
    at measureName (webpack:///node_modules/@firebase/performance/dist/index.cjs.js:1243:32)
```

**Comment by visumickey** [comment]
Thanks for the report. Internally tracking at b/162244513.

**Comment by visumickey** [comment]
@qnp Do/Can we know the version of the browser that is showing this error? The current possibility of this occurring is when the version of the browser is very old. We could protect this by catching the error on the SDK, but trying to think if there are any other possibilities where this could be occurring to make sure we are not masking it by catching the error.

**Comment by qnp** [comment]
@visumickey I contacted the user for which the error appeared to ask him which browser(s) he uses. Meanwhile, I modified the global error tracker we use to log the `user-agent`, that was unfortunately missing. If the error appears again, we'll know the user agent responsible for that. Keep in touch. Best regards.

**Comment by mdirolf** [comment]
@visumickey I've seen this happen to a user running Safari 11.1.2
