### ISSUE TITLE
XMLHttpRequest is not defined -> when using storage -module on nodejs

### ISSUE THREAD

**Issue by mikamaunula** [firebase/firebase-js-sdk#349]
### Environment
  * Operating System version: Linux
  * Firebase SDK version: 4.7.0
  * nodejs version: 8.9.1
  * Firebase Product: firebase-js-sdk storage

### Problem and steps

When using storage module on nodejs side I'll get an error. 
```
this.xhr_ = new XMLHttpRequest();
                        ^

ReferenceError: XMLHttpRequest is not defined
```

Seems that is missing nodejs support.

Example code

```
var storageRef = firebase.storage().ref();
var ref = storageRef.child('mountains.jpg');
var bytes = new Uint8Array([0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2c, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x21]);
ref.put(bytes).then(function(snapshot) {
  console.log('Uploaded an array!');
});
```

**Comment by jshcrowthe** [comment]
This is working as intended, the Firebase Storage SDK doesn't support Node.js environments right now (see: https://github.com/firebase/firebase-js-sdk/issues/18)

**Comment by joonhocho** [comment]
@jshcrowthe I am getting same error trying to call `firebase.auth().signInWithEmailAndPassword()`

**Comment by joonhocho** [comment]
I figured out why

So you can't do this:

```
var firebase = require('firebase/app');
require('firebase/auth');
require('firebase/database');

var app = firebase.initializeApp({ ... });
```

You have to import entire `'firebase'` or you will get the error.

May want to fix Readme about this.

**Comment by jshcrowthe** [comment]
@joonhocho That is a different issue that is probably worth taking a look at. I'll make an issue and see if we can get that addressed.

**Comment by pmoleri** [comment]
There's a workaround, that involves adding `XMLHttpRequest` to node.

```
global.XMLHttpRequest = require("xhr2");
```

I don't know if this solves every issue, but it works for what I need.

**Comment by Methodician** [comment]
For Using TypeScript, wrap global as any

```
// Polyfills required for Firebase
(global as any).XMLHttpRequest = require('xhr2');
(global as any).WebSocket = require('ws'); // May also come in handy
```
