### ISSUE TITLE
Fetch firebase storage collection  all list 

### ISSUE THREAD

**Issue by shubhamvishwakarma19** [firebase/firebase-js-sdk#3494]
i'm using the firebase storage for file uploading. Uploading is working fine but when i'm trying to retrieving the all files as a list getting an error i'm also using the same syntax which is provided in the google firebase documentation.
anyone can help how can i retrieve all storage files 
here is my code 
<img width="702" alt="Screenshot 2020-07-28 at 12 38 27 PM" src="https://user-images.githubusercontent.com/50484716/88631249-823c0280-d0cf-11ea-833a-1203ce009bf2.png">

this is error screenshot 
<img width="611" alt="Screenshot 2020-07-28 at 12 32 23 PM" src="https://user-images.githubusercontent.com/50484716/88631303-97b12c80-d0cf-11ea-88eb-29ad6beabede.png">

**Comment by Feiyang1** [comment]
I'm not able to reproduce the issue. What version of firebase are you using? Are you using script tag or bundler?
