### ISSUE TITLE
FR: Access Firestore OnlineState

### ISSUE THREAD

**Issue by scottfr** [firebase/firebase-js-sdk#3496]
* Firebase SDK version: 7.16
  * Firebase Product: firestore

## Request

The Firestore SDK tracks online connectivity internally but it does not appear to be publicly exposed in the API anywhere.

It is tracked here:

https://github.com/firebase/firebase-js-sdk/blob/ea2fcf5553c93d8e847dd30589fb94111c41e9a7/packages/firestore/src/remote/online_state_tracker.ts

Please add public API's to check this connectivity state and respond to changes in connectivity.

## Use Case

We are observing that some VPN's may interfere with Firestore connectivity leading to Firestore failing to connect while the website does in fact have general internet connectivity.

When this happens we need the ability to detect this and inform the user of the issue and suggest a fix (e.g. checking and disabling their VPN). 

Note that when Firestore fails to connect it prints a message like the following to the console but it's not surfaced to the app directly so we can convey it to the user:

> Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
>
> This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**Comment by Feiyang1** [comment]
Thanks for the feature request. We recently added an API to allow you to listen to our internal log messages. It seems to be what you are looking for.

You can use it to look for this specific message, then show a message to your user. 
For example:
```
import * as firebase from 'firebase/app';

firebase.onLog((args, level, message, type) => {
    if (message.includes('Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds') {
         // show message to user
    }
});
```
Does it solve your use case?
You can find API reference [here](https://firebase.google.com/docs/reference/js/firebase?authuser=0#onlog).

**Comment by wilhuff** [comment]
While Firestore does track an estimate of its online state, this is inexact in ways that make it hard to document and support as a public API.

The best available way to track whether or not Firestore thinks its online is to start a listener with `includeMetadataChanges` enabled, and look at the `fromCache` bit in the resulting snapshots. If `fromCache` is false, the connection is definitely good.

Most of the time, if there's a connectivity problem, you can enable long-polling mode in the SDK. We're currently working on automating detection of this case and automatically falling back. With this in place it should be far less likely that you'll have to manually intervene.

**Comment by scottfr** [comment]
Thank you for these replies, they are very helpful as I was unaware of the onLog function or the force long polling flag. It is also great to hear there is an automatic solution for this in the works.

It there any downside for us to just flip on experimentalForceLongPolling besides beyond (to quote the docs) "this option will cause some performance degradation"?

Is it correct that feature should not affect billing costs or negatively impact app stability?

**Comment by wilhuff** [comment]
Enabling the long polling transport should have no impact on billing costs or stability. We've marked the feature experimental to convey that the API may be removed at a later date, but that would only happen once it is no longer needed and the SDK can automatically handle fallback for itself.
