### ISSUE TITLE
chrome://flags/#cookies-without-same-site-must-be-secure and from Firefox 69 in about:config by setting network.cookie.sameSite.noneRequiresSecure.

### ISSUE THREAD

**Issue by markymarkfunky** [firebase/firebase-js-sdk#3504]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by Feiyang1** [comment]
Closing the issue since it provides no information. Feel free to open a new issue with details.
