### ISSUE TITLE
analytics.isSupported() type error

### ISSUE THREAD

**Issue by herbievine** [firebase/firebase-js-sdk#3510]
* Operating System version: Windows 10 Pro
* Firebase SDK version: 7.17.1
* Firebase Product: analytics
* Vue: vue-rc-3.0.0-0

I'm using the new Vue 3 with TypeScript and I get a error when I use the new `analytics.isSupported()` method in my IDE (WebStorm 2020.2 - latest as of this post). I don't get an error however when I serve my app locally.

Am I doing this the right way or could this be an issue with type declaration in TS? As I also don't get any code completion as I type.

Steps to reploduce:

1. Create a simple Vue 3 project
2. run `firebase init`
3. Setup app as followed (src/main.ts):
```typescript
import { createApp } from 'vue';
import App from './App.vue';
import './registerServiceWorker';
import router from './router';
import store from './store';
import * as firebase from 'firebase/app';
import 'firebase/analytics';

const firebaseConfig = {
    apiKey: 'xxx',
    authDomain: 'xxx',
    databaseURL: 'xxx',
    projectId: 'xxx',
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
firebase.analytics // Error is here
    .isSupported()
    .then(res => (res ? firebase.analytics() : null));

createApp(App)
    .use(store)
    .use(router)
    .mount('#app');
```

![image](https://user-images.githubusercontent.com/41120535/88845272-33cc5800-d1e4-11ea-969b-b0a713158aee.png)

**Comment by hsubox76** [comment]
The types look correct so if you updated from a previous version it's possible the file didn't get updated properly. Can you clean out `node_modules` and do a clean yarn or npm install?

Another thing to check is, does `firebase.analytics.settings({})` also fail to autocomplete, or show an error? It's initialized and typed the same way as `isSupported()` but was added in an earlier version.

**Comment by herbievine** [comment]
Yep that sorted the issue out! Thanks a lot
