### ISSUE TITLE
Usage instructions are inconsistent/conflicting/confusing

### ISSUE THREAD

**Issue by Download** [firebase/firebase-js-sdk#3514]
In [one place](https://www.npmjs.com/package/@firebase/firestore#usage) it says:

```js
import firebase from '@firebase/app';
import '@firebase/firestore'
```
Note the use of the namespace `@firebase`.

In [another place](https://www.npmjs.com/package/firebase#get-the-code-nodejs---server-and-command-line) it says:

```js
// This import loads the firebase namespace.
import firebase from 'firebase/app';
 
// These imports load individual services into the firebase namespace.
import 'firebase/auth';
import 'firebase/database';
```

Note how this basically all uses the same package `firebase`, without a namespace.

I think the first form, with `@firebase` is the new/preferred form or not?

Looking at the first example, it uses [@firebase/app](https://www.npmjs.com/package/@firebase/app). If we open that up, we see that it points us to [firebase](https://www.npmjs.com/package/firebase)

> This package is not intended for direct usage, and should only be used via the officially supported firebase package.

...and then we come to the second example. This is confusing. Which form should I use on my new project?

All packages point to this Github Repo, which is why I am making this issue here.

### EDIT
I read more docs and now I'm more confused... 

It seems the [docs on GCP](https://firebase.google.com/docs/web/setup#using-module-bundlers) use yet another form:

```js
// Firebase App (the core Firebase SDK) is always required and must be listed first
import * as firebase from "firebase/app";

// If you enabled Analytics in your project, add the Firebase SDK for Analytics
import "firebase/analytics";

// Add the Firebase products that you want to use
import "firebase/auth";
import "firebase/firestore";
```

I don't see the namespace used here. So in that sense it looks like the second example. But this one uses `import * as firebase from` instead of `import firebase from`.

I know many big projects (e.g. Babel, Webpack) have been moving over to using namespaces/scopes. So they have been introducing the `@` symbol in their package names and have been [recommending their users](https://babeljs.io/docs/en/v7-migration#scoped-packages) to use the new form. Is the same true for Firebase? Is the first form actually the recommended form? And so are the second example and the docs on GCP outdated? Or is the opposite true and is the example on the Firestore package the one that is outdated? And if we need to use the non-scoped package, do we use it like `import firebase from` or like `import * as firebase from`? Please advice.

**Comment by Download** [comment]
Thanks Google OSS Bot, but when I spend time creating an issue, I sorta expect a human to look at it...

**Comment by hsubox76** [comment]
The first link seems to be the README for the individual @firebase/firestore package which, as it says on the page, shouldn't be directly installed by itself (it will come in as part of `npm install firebase`, along with the other components). I can go ahead and change the text in the README for anyone who ends up on that page.

As for `import * as firebase from 'firebase/app'` vs `import firebase from 'firebase/app'`, these are both valid, we provide firebase as a default export and as a named export, for developers who need to consume it one way or the other. This question dives into the difference between them and why libraries (in this case React) often provide both: https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react

I'll look into if we can settle on one of these as the "official" default suggested format and we can change either the README or the docs site so they're consistent. (I think it'll probably `import firebase from 'firebase'`.)
