### ISSUE TITLE
W/Firestore(  885): (21.3.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds W/Firestore(  885): W/Firestore(  885): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

### ISSUE THREAD

**Issue by zeyadsharo** [firebase/firebase-js-sdk#3515]
![image](https://user-images.githubusercontent.com/33178745/88952415-165cc400-d2a0-11ea-9339-7efe403c4790.png)
![image](https://user-images.githubusercontent.com/33178745/88952910-caf6e580-d2a0-11ea-8153-f201d66d57bb.png)
![image](https://user-images.githubusercontent.com/33178745/88953584-ced73780-d2a1-11ea-9467-ebd8434e1122.png)

```
Future getdata() async {
    Firestore db = Firestore.instance;
    var data = await db.collection('event_details').getDocuments();
    var details = data.documents.toList();
    details.forEach((element) {
      print(element.documentID);
    });
  }
```
W/Firestore(  885): (21.3.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore(  885):
W/Firestore(  885): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
Reloaded 1 of 537 libraries in 344ms.

**Comment by hsubox76** [comment]
This seems to be a flutter project which doesn't use the JS SDK. Did you mean to file an issue in the Flutterfire project? https://github.com/FirebaseExtended/flutterfire
