### ISSUE TITLE
@firebase/firestore: Firestore (7.13.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.

### ISSUE THREAD

**Issue by spaceghostu** [firebase/firebase-js-sdk#3525]
Im still getting this issue.
    "angular": "^1.8.0",
    "angularfire2": "^5.4.2",

@firebase/firestore: Firestore (7.13.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.

@sanket1703 Thanks for these logs. Unfortunately, these only show the connection attempt, but not any responses. This could be expected if your device did not receive any data, but it makes it hard for us to debug. 

One thing that you could try is to enable `experimentalForceLongPolling`, which switches our client to a different networking model. You can enable it as such:

```
firebase.firestore().settings({ experimentalForceLongPolling: true });
```

If that does not help, we probably need a small repro app that we can run locally to continue this investigation.

_Originally posted by @schmidt-sebastian in https://github.com/firebase/firebase-js-sdk/issues/2923#issuecomment-618183242_

Where do i put this code?

**Comment by schmidt-sebastian** [comment]
My knowledge of Angular is fairly limited, but going from the code snippet provided at https://github.com/angular/angularfire, I would expect it would look something like:


```
import { Component } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

export class MyApp {
  items: Observable<any[]>;
  constructor(firestore: AngularFirestore) {
    firestore.settings({experimentalForceLongPolling: true});
    this.items = firestore.collection('items').valueChanges();
  }
}
```

Please do note that `settings()` needs to be called before any other Firestore APIs. Let us know if you have more questions.
