### ISSUE TITLE
Some user properties are lost in analytics

### ISSUE THREAD

**Issue by n-spl1nter** [firebase/firebase-js-sdk#3527]
### [REQUIRED] Describe your environment
  * Operating System version: MacOS Catalina 10.15.2
  * Browser version: Google Chrome 84.0.4147.105
  * Firebase SDK version: 7.16.1
  * Firebase Product: analytics

### [REQUIRED] Describe the problem
When using `firebase.analytics().setUserProperties` some user properties are not displayed in the debug console.
Also in big query data user properties are missed too.

#### Steps to reproduce:
Initialize firebase app
Set user properties
Trigger event
#### Relevant Code:

```javascript
import React from 'react';
import * as firebase from 'firebase';
import 'firebase/analytics';
import firebaseConfig from './firebaseConfig'

const setUserProperties = () => {
  firebase.analytics().setUserProperties({
    user_ldap: '40000000',
    user_position: 'продавец-консультант',
    user_shop: '741 магазин Москва',
    user_name: 'User Name',
    user_division: '5 напольные покрытия',
  });
};
const Main = () => {
  const [isAuthenticated, setIsAuthenticated] = React.useState(false);
  React.useEffect(() => {
    if (isAuthenticated) {
      setUserProperties();
    }
  }, [isAuthenticated]);
  if (!isAuthenticated) {
    return (
      <button onClick={() => setIsAuthenticated(true)}>AUTH</button>
    );
  }
  const logEvent = () => {
    firebase.analytics().logEvent('custom-event', { customKey: 'customValue' });
  };
  return (
    <button onClick={logEvent}>LOG EVENT</button>
  );
}
export default function App() {
  React.useEffect(() => {
    firebase.initializeApp(firebaseConfig);
  }, []);
  return (
    <Main />
  );
}
```

### As is:
![image](https://user-images.githubusercontent.com/16477075/89031051-64260a80-d33a-11ea-8af6-eed25f802dcf.png)

### As should be:
All user properties are displayed

**Comment by Feiyang1** [comment]
Can you please verify that all user properties are present in the analytics event?

If you are using Chrome, you can open the developer console and navigate to the network tab. After clicking on `LOG EVENT` button, look for a url that starts with `https://www.google-analytics.com/g/collect`. Inspect the request body and the url parameters, look for fields that starts with `up.` (these are user properties), do you see all of your user properties? Then do you see all of them in console?

**Comment by n-spl1nter** [comment]
@Feiyang1 

<details>
  <summary>In query params all user properties are presented</summary>

  ![image](https://user-images.githubusercontent.com/16477075/89097531-69419300-d3e8-11ea-8323-d2f3cffd9648.png)
</details>
<details>
  <summary>In console log with google analytics debugger extension</summary>

  ![image](https://user-images.githubusercontent.com/16477075/89097619-29c77680-d3e9-11ea-91a0-2b686e127244.png)
</details>

**Comment by Feiyang1** [comment]
Thanks for the info, so I think it is a backend issue. Can you please open a ticket with Firebase support? https://firebase.google.com/support/troubleshooter/analytics/help
