### ISSUE TITLE
ThenableReference type definition

### ISSUE THREAD

**Issue by Crazometer** [firebase/firebase-js-sdk#354]
To my understanding all `ThenableReference`s return a `Reference` on completion. Is this correct and could the typings be updated to accomodate it? Primarily in the database project.

**Comment by mikelehen** [comment]
Can you be more specific about exactly what you want changed in https://github.com/firebase/firebase-js-sdk/blob/master/packages/database-types/index.d.ts#L122 ?

A ThenableReference _is_ a reference, but with the addition of a .then() method.

**Comment by Crazometer** [comment]
Should it be `export interface ThenableReference extends Reference, PromiseLike<Reference> {}`. With `PromiseLike<Reference>` instead of `PromiseLike<any>`.

**Comment by mikelehen** [comment]
Yes, that does seem more correct. Want to open a PR? :-)

As for the nullable types, when one compiles with --strictNullChecks (which is often a good idea), types are /not/ nullable by default. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

**Comment by Crazometer** [comment]
Thanks for the `--strictNullChecks` tip. It does sound handy.

I'll open up a PR.
