### ISSUE TITLE
SSR / Compilation / Can't resolve 'google-auth-library'

### ISSUE THREAD

**Issue by vroussel35** [firebase/firebase-js-sdk#3542]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS / SSR context
  * Browser version: N/A
  * Firebase SDK version: 7.15.2 and above
  * Firebase Product: all (auth, database, storage, etc)

### [REQUIRED] Describe the problem

Error when trying to execute `npm run dev:ssr`

```
ERROR in ./node_modules/@grpc/grpc-js/build/src/channel-credentials.js
Module not found: Error: Can't resolve 'google-auth-library' in '[local-project-directory]/node_modules/@grpc/grpc-js/build/src'
this.debug is not a function
```

This problem has started from firebase version 7.15.2 where the grpc-js dependancy version has been modified to ^1.0.0.

#### Steps to reproduce:

1. Download this project https://github.com/vroussel35/error-ssr-compile
2. Execute `npm install`
3. Execute `npm run dev:ssr`

**Comment by siva636** [comment]
I also face the same issue. I use:
"firebase": "^7.13.1",
"@angular/fire": "^6.0.2",

**Comment by vroussel35** [comment]
@siva636 In the meantime - waiting for a fix - if you use `"firebase": "7.15.1"` instead of `"firebase": "^7.13.1"`, it should be OK.

**Comment by wu-hui** [comment]
Looks like newer version of the SDK no longer has this problem? At least `7.17` looks fine to me.

**Comment by vroussel35** [comment]
Hi @wu-hui - the newer version of the SDK **still has this problem**.

To fix this issue (or better to say, to put in place a workaround), from version 7.15.2 of the firebase package, you have to modify the `angular.json` file and add the @firebase package to the externalDependencies config of the "server" target as explained by @Feiyang1 in https://github.com/firebase/firebase-js-sdk/issues/3541#issuecomment-671566251 as you can see below:

```
"server": {
 "builder": "@angular-devkit/build-angular:server",
 "options": {
  "outputPath": "dist/server",
  "main": "server.ts",
  "tsConfig": "tsconfig.server.json",
  "externalDependencies": [
   "@firebase/analytics",
   "@firebase/analytics-types",
   "@firebase/app",
   "@firebase/app-types",
   "@firebase/auth",
   "@firebase/auth-interop-types",
   "@firebase/auth-types",
   "@firebase/component",
   "@firebase/database",
   "@firebase/database-types",
   "@firebase/firestore",
   "@firebase/firestore-types",
   "@firebase/functions",
   "@firebase/functions-types",
   "@firebase/installations",
   "@firebase/installations-types",
   "@firebase/logger",
   "@firebase/messaging",
   "@firebase/messaging-types",
   "@firebase/performance",
   "@firebase/performance-types",
   "@firebase/polyfill",
   "@firebase/remote-config",
   "@firebase/remote-config-types",
   "@firebase/storage",
   "@firebase/storage-types",
   "@firebase/util",
   "@firebase/webchannel-wrapper",
  ]
 },
 ...
```

The root cause of this issue is most probably due to "some agressive tree-shaking somewhere in the ngcc build tooling" as mentioned by @jamesdaniels in this https://github.com/firebase/firebase-js-sdk/issues/3541#issuecomment-671541140

PS : from an IT process point of view, I would have not closed this issue as its root cause has not been clearly identified and a proper fix is not in place... ;)
