### ISSUE TITLE
Firebase Auth (Accent problem with verification message)

### ISSUE THREAD

**Issue by andrefedev** [firebase/firebase-js-sdk#3543]
I don't know if this error should precisely go here. But I am trying to integrate firebase auth and select the Spanish template where the message has accents. But when the message arrives by sms it arrives malformed. I have tried for several days, is there any solution for this?

![Screenshot_20200723-193256_Messages](https://user-images.githubusercontent.com/14114839/88351487-1e56ba00-cd1c-11ea-90f3-646c702f6e98.jpg)

**Comment by Feiyang1** [comment]
Can you please open a ticket with Firebase support? https://firebase.google.com/support/troubleshooter/report/bugs

**Comment by andrefedev** [comment]
Hi @Feiyang1. No, but I already finished sending the report, any possible solution for this?

**Comment by samhorlbeck** [comment]
Thanks for reaching out. Looks like this issue is unrelated to the SDK; I'm going to close this out for now, please follow up with Firebase support
