### ISSUE TITLE
[messaging] Notifications displayed onPush despite of simple data-only payloads

### ISSUE THREAD

**Issue by rstoica** [firebase/firebase-js-sdk#3565]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 14.04.6 LTS
  * Browser version: Chrome 84.0.4147.89 (Official Build) (64-bit)
  * Firebase SDK version: 7.15.1
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
Hi, thanks a lot for the hard work on Firebase.

There is an issue regarding the display of notifications from the background when **data-only** payloads are being pushed over to a web app. 

#### Use case
I used Firebase to proxy short sporadic messages between a mobile app and a web app (web extension) containing **data-only** payloads. For this I set a basic service worker to handle the incoming messages to the web extension together with a custom `setBackgroundMessageHandler` to pipe the incoming data payload to the web extension background script. Connections work as expected given the docs, but notifications are displayed for each individual message, which is not the expected behavior given the `setBackgroundMessageHandler` docstring. 

How can one disable this ? Default should be as documented no notification for data payloads.

#### Steps to reproduce:
1. Send data-only (no notifications) to web extension (may / may not have visible browser_action content)
2. Receive data async in the service worker `setBackgroundMessageHandler` and consume it in some way as needed 

#### Relevant Code:
Here is my `setBackgroundMessageHandler` callback implementation. Nothing fancy, just a print for debugging and piping further the message to a background script to the web extension.

```javascript
const broadcastChannel = new BroadcastChannel("DATA_CHANNEL");
messaging.setBackgroundMessageHandler(function (message) {
    console.log('Received message in service worker', message);
    console.log(
        'SW :' +
          'a background message is received: ' +
          JSON.stringify(message)
    );
    // Send data for more processing to the background web extension script
    broadcastChannel.postMessage(message.data);
});
```

The output of the debugging statement for one of my messages that spawns an unwanted notification is like this for instance:
```
SW a background message is received: {"data":{"nonce":"dcnWkPWUNMs59qeV","ciphertext":"778tLdA0YbKu8it7Ni/H8lp5yLBbU114uQNJzTR7i7HXl8pqS8vpGsFBBORvmO8Frl+jknmJJ7XGygt+i6OIYClLlV9YPZT0"},"from":"235446243855","priority":"high","collapse_key":"do_not_collapse"}.
```

Debugging a bit into the problem, the `onPush` method in the messaging SW controller is called appropriately and handles the push notification as expected, but once it is done and the `waitUntil` of the event is consumed a generic notification pops up with the following components:

- title: `chrome-extension//<extensionID>`
- body: `This site has been updated in the background.`

**Comment by Feiyang1** [comment]
It is a limitation on Chrome(Working as designed). Chrome doesn't allow silent push notification in order to prevent websites from secretly running code in the background. If you don't show a notification, chrome will show a default one, which is what you saw. See https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web#what_are_the_limitations_of_push_messaging_in_chrome

**Comment by rstoica** [comment]
@Feiyang1 Thanks for the reply and reference.
