### ISSUE TITLE
NPM | Not Found - GET https://registry.npmjs.org/@firebase%2fapp

### ISSUE THREAD

**Issue by Yoruba** [firebase/firebase-js-sdk#3571]
After running `npm install --save firebase` I get a message Not Found - GET https://registry.npmjs.org/@firebase%2fapp

Did run `npm cache clean --force ` and did also try it on an other PC.
But get stil the message Not Found

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'firebase'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.13.1
4 verbose npm-session 6bc47ee181b549e6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/firebase 306ms
8 http fetch GET 200 https://registry.npmjs.org/firebase/-/firebase-7.17.1.tgz 420ms
9 silly pacote tag manifest for firebase@latest fetched in 764ms
10 timing stage:loadCurrentTree Completed in 788ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule firebase@7.17.1 checking installable status
18 http fetch GET 404 https://registry.npmjs.org/@firebase%2fapp 54ms
19 http fetch GET 404 https://registry.npmjs.org/@firebase%2fmessaging 68ms
20 http fetch GET 404 https://registry.npmjs.org/@firebase%2fauth 73ms
21 http fetch GET 404 https://registry.npmjs.org/@firebase%2fapp 21ms
22 silly fetchPackageMetaData error for @firebase/app@0.6.9 404 Not Found - GET https://registry.npmjs.org/@firebase%2fapp - Not found
23 http fetch GET 404 https://registry.npmjs.org/@firebase%2ffirestore 76ms
24 http fetch GET 404 https://registry.npmjs.org/@firebase%2fstorage 73ms
25 http fetch GET 404 https://registry.npmjs.org/@firebase%2fapp-types 82ms
26 http fetch GET 404 https://registry.npmjs.org/@firebase%2ffunctions 83ms
27 http fetch GET 404 https://registry.npmjs.org/@firebase%2finstallations 83ms
28 http fetch GET 404 https://registry.npmjs.org/@firebase%2fdatabase 91ms
29 http fetch GET 404 https://registry.npmjs.org/@firebase%2fmessaging 23ms
30 http fetch GET 404 https://registry.npmjs.org/@firebase%2fauth 24ms
31 silly fetchPackageMetaData error for @firebase/messaging@0.6.21 404 Not Found - GET https://registry.npmjs.org/@firebase%2fmessaging - Not found
32 silly fetchPackageMetaData error for @firebase/auth@0.14.9 404 Not Found - GET https://registry.npmjs.org/@firebase%2fauth - Not found
33 http fetch GET 404 https://registry.npmjs.org/@firebase%2fapp-types 23ms
34 silly fetchPackageMetaData error for @firebase/app-types@0.6.1 404 Not Found - GET https://registry.npmjs.org/@firebase%2fapp-types - Not found
35 http fetch GET 404 https://registry.npmjs.org/@firebase%2ffirestore 28ms
36 http fetch GET 404 https://registry.npmjs.org/@firebase%2fstorage 28ms
37 silly fetchPackageMetaData error for @firebase/firestore@1.16.2 404 Not Found - GET https://registry.npmjs.org/@firebase%2ffirestore - Not found
38 silly fetchPackageMetaData error for @firebase/storage@0.3.41 404 Not Found - GET https://registry.npmjs.org/@firebase%2fstorage - Not found
39 http fetch GET 404 https://registry.npmjs.org/@firebase%2finstallations 25ms
40 silly fetchPackageMetaData error for @firebase/installations@0.4.15 404 Not Found - GET https://registry.npmjs.org/@firebase%2finstallations - Not found
41 http fetch GET 404 https://registry.npmjs.org/@firebase%2fdatabase 22ms
42 silly fetchPackageMetaData error for @firebase/database@0.6.9 404 Not Found - GET https://registry.npmjs.org/@firebase%2fdatabase - Not found
43 http fetch GET 404 https://registry.npmjs.org/@firebase%2ffunctions 30ms
44 silly fetchPackageMetaData error for @firebase/functions@0.4.49 404 Not Found - GET https://registry.npmjs.org/@firebase%2ffunctions - Not found
45 http fetch GET 404 https://registry.npmjs.org/@firebase%2futil 31ms
46 http fetch GET 404 https://registry.npmjs.org/@firebase%2fanalytics 36ms
47 http fetch GET 404 https://registry.npmjs.org/@firebase%2futil 29ms
48 silly fetchPackageMetaData error for @firebase/util@0.3.0 404 Not Found - GET https://registry.npmjs.org/@firebase%2futil - Not found
49 http fetch GET 404 https://registry.npmjs.org/@firebase%2fanalytics 31ms
50 silly fetchPackageMetaData error for @firebase/analytics@0.4.1 404 Not Found - GET https://registry.npmjs.org/@firebase%2fanalytics - Not found
51 http fetch GET 404 https://registry.npmjs.org/@firebase%2fpolyfill 844ms
52 http fetch GET 404 https://registry.npmjs.org/@firebase%2fpolyfill 27ms
53 http fetch GET 404 https://registry.npmjs.org/@firebase%2fperformance 804ms
54 silly fetchPackageMetaData error for @firebase/polyfill@0.3.36 404 Not Found - GET https://registry.npmjs.org/@firebase%2fpolyfill - Not found
55 http fetch GET 404 https://registry.npmjs.org/@firebase%2fremote-config 797ms
56 http fetch GET 404 https://registry.npmjs.org/@firebase%2fperformance 33ms
57 silly fetchPackageMetaData error for @firebase/performance@0.3.10 404 Not Found - GET https://registry.npmjs.org/@firebase%2fperformance - Not found
58 http fetch GET 404 https://registry.npmjs.org/@firebase%2fremote-config 24ms
59 silly fetchPackageMetaData error for @firebase/remote-config@0.1.26 404 Not Found - GET https://registry.npmjs.org/@firebase%2fremote-config - Not found
60 timing stage:rollbackFailedOptional Completed in 1ms
61 timing stage:runTopLevelLifecycles Completed in 1723ms
62 silly saveTree └── firebase@7.17.1
63 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@firebase%2fapp - Not found
63 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
63 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
64 verbose statusCode 404
65 verbose pkgid @firebase/app@0.6.9
67 verbose Darwin 19.5.0
68 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "firebase"
69 verbose node v12.13.1
70 verbose npm  v6.13.4
71 error code E404
72 error 404 Not Found - GET https://registry.npmjs.org/@firebase%2fapp - Not found
73 error 404
74 error 404 '@firebase/app@0.6.9' is not in the npm registry.
75 error 404 You should bug the author to publish it (or use the name yourself!)
76 error 404 It was specified as a dependency of 'firebase'
77 error 404 Note that you can also install from a
78 error 404 tarball, folder, http url, or git url.
79 verbose exit [ 1, true ]

**Comment by kukurudz-volodymyr** [comment]
The same issue. 
Getting '@firebase/storage-types@0.3.13' is not in the npm registry.' and similar issues during 'npm install'

**Comment by nielskramerr** [comment]
Facing a similar issue here with `npm install`. 
404 Not Found - GET https://registry.npmjs.org/@firebase/auth/-/auth-0.13.6.tgz

**Comment by kukurudz-volodymyr** [comment]
UPDATE: looks like it's an issue with npm itself - https://status.npmjs.org/

**Comment by amulgarg** [comment]
I am getting the same errors. Hoping npm resolves it soon

**Comment by hassaannahmed** [comment]
Same issue.

**Comment by suvi277** [comment]
Same issue ...waiting for the npm fix

**Comment by E-jarod** [comment]
Same here...

**Comment by CodeforChao** [comment]
Same issue
![image](https://user-images.githubusercontent.com/49122071/89528402-8b3e7980-d81d-11ea-832e-58b87f0241ab.png)

**Comment by footios** [comment]
npm install --save firebase 
IT'S WORKING AGAIN!!!

**Comment by CodeforChao** [comment]
> Same issue
> ![image](https://user-images.githubusercontent.com/49122071/89528402-8b3e7980-d81d-11ea-832e-58b87f0241ab.png)

works well now.
