### ISSUE TITLE
SameSite issue for google resources in Firebase project

### ISSUE THREAD

**Issue by writerdanhardy** [firebase/firebase-js-sdk#3574]
### [REQUIRED] Describe your environment

  * Operating System version: windows
  * Browser version: Chrome 84
  * Firebase SDK version: 5.7.3
  * Firebase Product: cse (auth, database, storage, etc)

### [REQUIRED] Describe the problem
SameSite issues using google resources such as custome search , google fonts, material components etc.

Name | Domain & Path
-- | --
_ga | .unpkg.com/
_ga | .getmdl.io/
HSID | .google.com/
SSID | .google.com/
APISID | .google.com/
SAPISID | .google.com/
OGPC | .google.com/
SID | .google.com/
SIDCC | .google.com/
_ga | www.google.com/
UULE | www.google.com/

#### Steps to reproduce:
Try to use a cdn for material components using Chrome 84 for example or custom search engine

**Comment by hsubox76** [comment]
Hi, can you help me understand this issue better? Are you using the Firebase JS SDK?

I see you mentioned material components and fonts but not any Firebase JS SDK APIs. What Firebase product are you using? Is it just Firebase hosting?

**Comment by writerdanhardy** [comment]
<script src="/__/firebase/5.7.3/firebase-app.js"></script>
    <script src="/__/firebase/5.7.3/firebase-auth.js"></script>
    <script src="/__/firebase/5.7.3/firebase-storage.js"></script>
    <script src="/__/firebase/5.7.3/firebase-messaging.js"></script>
    <script src="/__/firebase/5.7.3/firebase-firestore.js"></script>
using Firebase hosting and using material components and google custom search engine which seem to be throwing the issues

**Comment by hsubox76** [comment]
Unless I'm misunderstanding, this doesn't seem to be a Firebase JS SDK issue? Are you getting any Firebase JS SDK errors from app, auth, storage, messaging, or firestore?

If not, you might want to file a support ticket for Firebase hosting, as hosting services are not part of this repo.

Please let me know if I'm misunderstanding something and you have reason to believe this is related to usage of the Firebase SDK.

Also, while I think this is unrelated to the SameSite issue, 5.7.3 seems to be a pretty old version and you may want to try to update at some point (the current version is 7.17.2).

**Comment by writerdanhardy** [comment]
Thank you will do. Correct it seems to be a Chrome issue with google domain.  Thank you
