### ISSUE TITLE
 @firebase/firestore: Firestore (7.17.2): Could not reach Cloud Firestore backend - Error

### ISSUE THREAD

**Issue by danielHype** [firebase/firebase-js-sdk#3584]
### [REQUIRED] Describe your environment

  * Operating System version: Mac, macOs Catalina, Version 10.15.1
  * Browser version: Chrome 84.0.4147.105
  * Firebase SDK version: 7.12.2
  * Firebase Product: Auth, Database, Storage

#### Steps to reproduce:

Since a few days we are getting an error while trying to communicate via Firebase/ Firestore. However, the issue only comes in our localhost, as soon as we build and deploy on our server everything works fine. Please see the issue getting logged into my console.

![image](https://user-images.githubusercontent.com/66954240/89645194-9b0b9b80-d8b9-11ea-8d4e-22bf48610ed6.png)

![image](https://user-images.githubusercontent.com/66954240/89645711-a7442880-d8ba-11ea-8772-71680977cba6.png)

Furthermore: 
```
[2020-08-07T12:34:27.214Z]  @firebase/firestore: Firestore (7.17.2): FirestoreClient Initializing. user= 4iMbM6Fy7nUq41u5rDYfPTNfQ963
index.esm.js?abfd:106 [2020-08-07T12:34:27.220Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Get next mutation batch
index.esm.js?abfd:106 [2020-08-07T12:34:27.222Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Get next mutation batch
index.esm.js?abfd:106 [2020-08-07T12:34:27.227Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Allocate target
index.esm.js?abfd:106 [2020-08-07T12:34:27.229Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Execute query
index.esm.js?abfd:106 [2020-08-07T12:34:27.229Z]  @firebase/firestore: Firestore (7.17.2): IndexFreeQueryEngine Using full collection scan to execute query: Query(target=Target(othergame, filters: [userId == 4iMbM6Fy7nUq41u5rDYfPTNfQ963], orderBy: [__name__ (asc)]); limitType=F)
index.esm.js?abfd:106 [2020-08-07T12:34:27.232Z]  @firebase/firestore: Firestore (7.17.2): FirebaseCredentialsProvider getToken aborted due to token change.
index.esm.js?abfd:106 [2020-08-07T12:34:27.233Z]  @firebase/firestore: Firestore (7.17.2): Connection Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel {"httpSessionIdParam":"gsessionid","initMessageHeaders":{"X-Goog-Api-Client":"gl-js/ fire/7.17.2","Content-Type":"text/plain","Authorization":"Bearer <omitted>"},"messageUrlParams":{"database":"projects/<project>/databases/(default)"},"sendRawJson":true,"supportsCrossDomainXhr":true,"internalChannelParams":{"forwardChannelRequestTimeoutMs":600000},"forceLongPolling":true,"httpHeadersOverwriteParam":"$httpHeaders"}
index.esm.js?abfd:106 [2020-08-07T12:34:27.234Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Allocate target
index.esm.js?abfd:106 [2020-08-07T12:34:27.235Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Execute query
index.esm.js?abfd:106 [2020-08-07T12:34:27.235Z]  @firebase/firestore: Firestore (7.17.2): IndexFreeQueryEngine Using full collection scan to execute query: Query(target=Target(users, filters: [userId == <user id>], orderBy: [__name__ (asc)]); limitType=F)
index.esm.js?abfd:106 [2020-08-07T12:34:27.236Z]  @firebase/firestore: Firestore (7.17.2): RemoteStore RemoteStore received new credentials
index.esm.js?abfd:106 [2020-08-07T12:34:27.239Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Get next mutation batch
index.esm.js?abfd:106 [2020-08-07T12:34:27.239Z]  @firebase/firestore: Firestore (7.17.2): Connection Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel {"httpSessionIdParam":"gsessionid","initMessageHeaders":{"X-Goog-Api-Client":"gl-js/ fire/7.17.2","Content-Type":"text/plain","Authorization":"Bearer <jwt left our for privavy purposes>},"messageUrlParams":{"database":"projects/<project>/databases/(default)"},"sendRawJson":true,"supportsCrossDomainXhr":true,"internalChannelParams":{"forwardChannelRequestTimeoutMs":600000},"forceLongPolling":true,"httpHeadersOverwriteParam":"$httpHeaders"}
index.esm.js?abfd:106 [2020-08-07T12:34:27.240Z]  @firebase/firestore: Firestore (7.17.2): PersistentStream stream callback skipped by getCloseGuardedDispatcher.
index.esm.js?abfd:106 [2020-08-07T12:34:27.244Z]  @firebase/firestore: Firestore (7.17.2): Connection Opening WebChannel transport.
index.esm.js?abfd:106 [2020-08-07T12:34:27.245Z]  @firebase/firestore: Firestore (7.17.2): Connection WebChannel sending: {"database":"projects/<project>/databases/(default)","addTarget":{"query":{"structuredQuery":{"from":[{"collectionId":"othergame"}],"where":{"fieldFilter":{"field":{"fieldPath":"userId"},"op":"EQUAL","value":{"stringValue":"4iMbM6Fy7nUq41u5rDYfPTNfQ963"}}},"orderBy":[{"field":{"fieldPath":"__name__"},"direction":"ASCENDING"}]},"parent":"projects/<project>/databases/(default)/documents"},"targetId":2}}
index.esm.js?abfd:106 [2020-08-07T12:34:27.245Z]  @firebase/firestore: Firestore (7.17.2): Connection WebChannel sending: {"database":"projects/<project>/databases/(default)","addTarget":{"query":{"structuredQuery":{"from":[{"collectionId":"users"}],"where":{"fieldFilter":{"field":{"fieldPath":"userId"},"op":"EQUAL","value":{"stringValue":"4iMbM6Fy7nUq41u5rDYfPTNfQ963"}}},"orderBy":[{"field":{"fieldPath":"__name__"},"direction":"ASCENDING"}]},"parent":"projects/l<project>t/databases/(default)/documents"},"targetId":4}}
[2020-08-07T12:19:45.762Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Release target
index.esm.js?abfd:106 [2020-08-07T12:19:45.763Z]  @firebase/firestore: Firestore (7.17.2): MemoryPersistence Starting transaction: Release target
index.esm.js?abfd:106 [2020-08-07T12:19:45.764Z]  @firebase/firestore: Firestore (7.17.2): Connection Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel {"httpSessionIdParam":"gsessionid","initMessageHeaders":{"X-Goog-Api-Client":"gl-js/ fire/7.17.2","Content-Type":"text/plain","Authorization":"Bearer <jsw token left out for privacy purposes>"},"messageUrlParams":{"database":"projects/<our project>/databases/(default)"},"sendRawJson":true,"supportsCrossDomainXhr":true,"internalChannelParams":{"forwardChannelRequestTimeoutMs":600000},"forceLongPolling":true,"httpHeadersOverwriteParam":"$httpHeaders"}
```

As you can see in the results, I tried different things: At first, forceLongPolling, logging extensive logging and trying different firebase versions. Updating to the newest version, which many people helped, did not help me. 

I think code reproduction may work, but should not be needed here as this is probably an easyfix. 

Still, googling and putting many hours in did not help for me thus I am seeking help here. 

If more information is needed, please inform me and i am very happy to provide more information. 

I am not sure if this may be subject to changes made by chrome due to new enforced CORS and cookie policy. As the screenshot suggest, I am having a problem with the CORS Policy. However, if yes, how can I enforce CORS with firebase? 

I am not using API Calls, I am using the firebase functions.

**Comment by Nithanaroy** [comment]
Thanks firebase team for creating such a wonderful software and making for open source & free for simple usage.

I am facing a similar CORS issue on Chrome 84, Safari and Firefox with 7.9.1, 7.9.3, 7.9.3 and 7.17.2 versions of firebase app, and **storage** on both localhost and on a website deployed via Google app script. 

I enabled CORS on my storage bucket as shared in https://stackoverflow.com/a/37765371/1585523. However it was mentioned in https://cloud.google.com/storage/docs/cross-origin#client-side-support that such a thing is not necessary.

**Comment by schmidt-sebastian** [comment]
@danielHype Can you confirm that you are indeed using version 7.12.2 and not 7.17.2? We made changes in our networking stack in version 7.17.2 and I would like to figure out if this is a possible regression.

**Comment by schmidt-sebastian** [comment]
@danielHype I talked to the maintainer of the WebChannel library about this issue. It turns out that we need a couple more things to look at this. Can you send us the URL and the request/response headers for the failed requests as recorded by the Chrome debugger? Thanks!

**Comment by asaduzzaman69** [comment]
i have the same issue...please solve this isse..getting this error for calling get method in documentRef..please google solve this

![Screenshot_95](https://user-images.githubusercontent.com/66587375/90666585-6b707200-e26f-11ea-8143-f79ecaa3b3ed.png)

**Comment by chris-ryu** [comment]
I have same error 7.19.1
React Native expo SDK 38

var firebaseConfig = {
  apiKey: "mykey",
  authDomain: "react-native-chat-8b961.firebaseapp.com",
  databaseURL: "https://react-native-chat-8b961.firebaseio.com",
  projectId: "react-native-chat-8b961",
  storageBucket: "react-native-chat-8b961.appspot.com",
  messagingSenderId: "366682905206",
  appId: "1:366682905206:web:537cc31fdad7d4be6c1d57",
  measurementId: "G-8PRQ8YNTH3",
};

[2020-08-29T02:09:26.941Z]  @firebase/firestore:, Firestore (7.19.1): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=not-found]: The project react-native-chat-8b961 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=react-native-chat-8b961 to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
* [native code]:null in __expoConsoleLog
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
- node_modules/expo/build/environment/muteWarnings.fx.js:27:4 in error
- node_modules/@firebase/component/dist/index.cjs.js:22:13 in Component
- node_modules/@firebase/component/dist/index.cjs.js:134:16 in Provider.prototype.getImmediate
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:171636:19 in A
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:181537:20 in xa
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:181521:102 in Oa
- node_modules/@firebase/firestore/dist/index.rn.esm2017.js:8114:5 in bi
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:293:29 in invoke
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:154:27 in invoke
- node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
- node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:22 in doResolve
- node_modules/promise/setimmediate/core.js:66:11 in Promise
- node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:181806:41 in Xa
* [native code]:null in Xa
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:181214:66 in close$
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:293:29 in invoke
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:154:27 in invoke
- node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
- node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:22 in doResolve
- node_modules/promise/setimmediate/core.js:66:11 in Promise
- node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
- node_modules/@firebase/firestore/dist/index.rn.esm2017.js:7150:34 in ti.Kr
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:181286:94 in fa
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:181255:30 in <unknown>
- node_modules/@firebase/firestore/dist/index.rn.esm2017.js:7272:12 in hi
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:177842:35 in <unknown>
- node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:135:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:183:16 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:446:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:396:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:144:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:373:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by hsubox76** [comment]
Even though the original issue opener hasn't responded, I see other users have the issue and I think the Firestore team still requires this additional information to help solve the problem:

> @danielHype I talked to the maintainer of the WebChannel library about this issue. It turns out that we need a couple more things to look at this. Can you send us the URL and the request/response headers for the failed requests as recorded by the Chrome debugger (specifically the URL and Origin header for the initial POST handshake request)? Thanks!

Can any of the other users having this problem provide this info? I believe they need the actual POST request details, not just error logs.

**Comment by chris-ryu** [comment]
@hsubox76 Here is my http dump.

[1.har.zip](https://github.com/firebase/firebase-js-sdk/files/5156086/1.har.zip)

Request
origin: file://
sec-fetch-dest: empty
x-goog-api-client: gl-js/ fire/7.8.1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) ReactNativeDebugger/0.11.3 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36
content-type: application/x-www-form-urlencoded

count=1&ofs=0&req0___data__=%257B%2522database%2522%253A%2522projects%252Freact-native-chat-8b961%252Fdatabases%252F%28default%29%2522%252C%2522addTarget%2522%253A%257B%2522query%2522%253A%257B%2522structuredQuery%2522%253A%257B%2522from%2522%253A%255B%257B%2522collectionId%2522%253A%2522chats%2522%257D%255D%252C%2522orderBy%2522%253A%255B%257B%2522field%2522%253A%257B%2522fieldPath%2522%253A%2522__name__%2522%257D%252C%2522direction%2522%253A%2522ASCENDING%2522%257D%255D%257D%252C%2522parent%2522%253A%2522projects%252Freact-native-chat-8b961%252Fdatabases%252F%28default%29%252Fdocuments%2522%257D%252C%2522targetId%2522%253A2%257D%257D


Response
:status: 200
date: Tue, 01 Sep 2020 12:06:24 GMT
content-encoding: gzip
x-content-type-options: nosniff
server: ESF
x-frame-options: SAMEORIGIN
content-type: text/plain; charset=utf-8
cache-control: private
x-client-wire-protocol: h2
x-http-session-id: HKkOstWt4zadr9UdM8ZWKV3ArtDhKEHV
alt-svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
content-length: 71
x-xss-protection: 0

51
[[0,["c","FI0waj_NK_Ntfq2dpKr3jQ","",8,12,30000]]]

**Comment by hsubox76** [comment]
In your case (unlike the original post), I noticed the error message contained this text:

>The project react-native-chat-8b961 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=react-native-chat-8b961 to add a Cloud Datastore or Cloud Firestore database.

Just wanted to double check, did you create a Firestore database in the console for this project?

**Comment by chris-ryu** [comment]
@hsubox76 I just found out that "Realtime" and "Firestore" are different things. I created "Realtime" and tried to access "Firestore".
Thank you for your double check :)

**Comment by hsubox76** [comment]
Glad that helped! If anyone is still having the initial problem in this issue, can you please provide the details @schmidt-sebastian asked for above? I can re-quote:

> @danielHype I talked to the maintainer of the WebChannel library about this issue. It turns out that we need a couple more things to look at this. Can you send us the URL and the request/response headers for the failed requests as recorded by the Chrome debugger (specifically the URL and Origin header for the initial POST handshake request)? Thanks!

If not, I'll leave the "needs-info" tag up and let the bot auto-close the issue if there are no responses after a certain amount of time.
