### ISSUE TITLE
Unable to unlink password provider and clean up the email

### ISSUE THREAD

**Issue by tuannguyent20** [firebase/firebase-js-sdk#3592]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome Version 84.0.4147.105
  * Firebase SDK version: npm package firebase@7.15.3
  * Firebase Product: auth

#### Steps to reproduce:

When unlink provider 'password' from user that has 2 providers: 'phone', 'password', the main (top level) email is still existed.
#### Relevant Code:
>  async doUnlinkProvider(providerId: string) {
    // this.authState: firebase.User;
    await this.authState.unlink(providerId);
    await this.authState.reload();
    // this.afAuth: firebase.auth.Auth;
    this.authState = await this.afAuth.currentUser;
    console.log('unlink after reload: ', this.authState);
    return this.authState;
  }

console output:
customClaims: null
disabled: false
displayName: "Tuan yahoo"
email: "tuant20@yahoo.com"
emailVerified: true
metadata: {lastSignInTime: "Sun, 09 Aug 2020 09:31:02 GMT", creationTime: "Fri, 07 Aug 2020 02:06:51 GMT"}
passwordHash: null
passwordSalt: null
phoneNumber: "+84903373094"
photoURL: null
providerData: [{…}]
...

#### Expected result:
email: null
emailVerified: false

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by samhorlbeck** [comment]
This is working as intended; when you add an email, the email address gets attached to the account. That is just "info" that is now part of the account. When you unlink "password" provider, the user can no longer sign in with an email/password pair, but the email itself is still attached to the account.

**Comment by tuannguyent20** [comment]
The problem is when I unlink an email from account A, I cannot link it to another account B due to error {code: "auth/wrong-password", message: "The password is invalid or the user does not have a password.", a: null}.
No way to get the email back to register with the system as a new account except 2 ways:
1. Delete the account A (maybe with alot providers there) to refresh the email availability. I would never do this.
2. Link the email again to the account A => the email still stucks with the account A forever until you delete the account A so actually there is just one way to delete the whole account A for just get back the email availability.
Think about the providers spaghetti :)

**Comment by samhorlbeck** [comment]
Interesting. I'm unable to reproduce that scenario. After unlinking password I'm still able to link another email account. Are you able to `signInWithEmailAndPassword()` into account B and then link with your original (phone) account using `linkWithPhoneNumber()`?

**Comment by tuannguyent20** [comment]
It's not important to link **another** email account to user A.
The point is reuse the original-unlinked email for another account B, C, ...
