### ISSUE TITLE
FR: support remote config 

### ISSUE THREAD

**Issue by rolele** [firebase/firebase-js-sdk#36]
It seems that remote config is only available in the ios, and, c++ and unity sdk.
Could it be possible to implement it in the js sdk as well.
I think having the A/B Testing feature using some analytics for segmentation would be very nice.

I see few project that tried to create some workaround like: cordova-plugin-firebase-remoteconfig and react-native-firestack but I think the right place is in the sdk itself.

Some people where requesting this feature last year already ( https://stackoverflow.com/questions/38321012/firebase-remote-config-feature-for-web-app-after-firebase-expansion ). 
What is the problem with adding this feature to the js sdk ?

**Comment by jshcrowthe** [comment]
@rolele I'll have to reiterate what @puf said in the SO question you listed. Specifically:

> We're considering adding it in a future version, but as usual: no commitments, no timelines.

But stay tuned for future updates! As with all feature requests, make sure you are signed up for the [Firebase Alpha Program](https://services.google.com/fb/forms/firebasealphaprogram/).

**Comment by jshcrowthe** [comment]
Oops! My apologies, wrong issue!

**Comment by kyle-ssg** [comment]
Out of interest, what's the actual rationale for leaving out web for this feature? Seems a bit bizarre to me.

We almost ditched our internal feature flagger project for this having seen how flexible the conditions are - we have quite a few cross platform projects we'd love to try this on, real shame this isn't available for web.

**Comment by mehrdaad** [comment]
anyone knows an alternative service/project to Firebase remote config?

**Comment by kurisu** [comment]
I agree with @kyle-ssg.  All our apps are cross platform; web/android/ios, and the ability to remotely configure and A/B test across these platforms is a basic need; one we're satisfying with internal tools only because Firebase Remote Config doesn't support JS.

**Comment by kyle-ssg** [comment]
Not to be cheeky but since posting I've come quite a way to developing a potential opensource cross platform alternative, as I said I tend to need this a lot. I think there's a lot of crossover between this and something like launchdarkly that isn't being catered for. If people care to, I've posted a questionare to see whether it would help many people out https://lm.facebook.com/l.php?u=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLScXbn7-FgSKwU-ZfgMIvKAxKpUUoCstTuVLn54fRRKl-ry62A%2Fviewform%3Fusp%3Dsf_link0&h=ATM-_1B_g_W3vMgK2G4ShMFIJanOx-BaTMOA1VdCBUZ52s6s_gJ9fjPQF-W6VdaF7oZqVy81QCQgyHk5J7nik9qiU6ys0-IdcLfK2TeUfZ1g8LiM-w51RYVLAAFabzyel94o29Q

**Comment by kyle-ssg** [comment]
Ended up open sourcing https://bullet-train.io/ - hopefully it might help some people here out :)

**Comment by mehrdaad** [comment]
@kyle-ssg  perfect, got the source on github?

**Comment by kyle-ssg** [comment]
@mehrdaad yup, split out into the frontend app, API and client sdks https://github.com/search?q=org%3ASolidStateGroup+bullet+train

**Comment by mehrdaad** [comment]
Thank you, but do you provide any guide how to setup self hosted instances?

**Comment by IchordeDionysos** [comment]
@landsman Not quite.
Still no first-class support, but you can at least now access all remote config values via a [REST API](https://firebase.google.com/docs/remote-config/use-config-rest)

**Comment by landsman** [comment]
@IchordeDionysos I read about this REST API but there is the problem about access to editing values which you don't want to allow for public visitors on web.

**Comment by dandv** [comment]
I've tried to create credentials to access Firebase Remote Config data via the REST API from a browser, but got an error that "Application data cannot be accessed securely from a web browser". I don't actually care about secure access - all I want is to fetch some config values, read-only.

![image](https://user-images.githubusercontent.com/33569/45249114-90ac8580-b2cf-11e8-91a6-c5250d397ad6.png)

**Comment by IchordeDionysos** [comment]
Yeah, I guess you would need to build your own API abstraction layer which only allows reads :)

**Comment by dandv** [comment]
I think a **read-only web API to fetch Remote Config values** would be really useful, and doesn't seem that hard to implement - we should just make the current template available as a JSON string at an HTTPS endpoint. @puf, thoughts?

**Comment by kostia-lev** [comment]
also it would be good to add access type: 'web' for certain config. Now I see ability to add only ios and android access type

**Comment by landsman** [comment]
exactly!

**Comment by superphil0** [comment]
bump

**Comment by VladimirMakaev** [comment]
What I don't understand why is this such a big ask ? This makes the most KISS solution unusable when you have a cross-platform app with a web version.

**Comment by landsman** [comment]
Or if you are using remote config for storage API endpoints in mobile apps and you want to do same in web app :)

**Comment by developius** [comment]
I'm building a Trusted Web App to target Android devices with Nuxt.js and lack of Remote Config support is a real bummer.
I'm considering writing a Firebase function to [retrieve them using the REST API](https://github.com/firebase/quickstart-nodejs/tree/master/config) and then call that from my app. I'd have to write the offline cache from scratch as well, which is abstracted away in the iOS/Android Firebase clients.

Would be awesome if the JS SDK supported for Remote Config. It's a bit of a deal-breaker.

**Comment by davireis** [comment]
This is really a bummer. The REST API is write-only, so it doesn't need seem to allow for a workaround.

Did anyone try to wrap the c++ desktop api in a server which we could use to access the configs indirectly from the web?

**Comment by IchordeDionysos** [comment]
@davireis No, it is not:
Here is the REST API call to retrieve the latest Remote Config values which can be used to write a wrapper for the web:
https://firebase.google.com/docs/reference/remote-config/rest/v1/projects/getRemoteConfig

Also, you can use a Cloud Functions trigger to mark the cached values as stale:
https://firebase.google.com/docs/functions/rc-events

**Comment by IchordeDionysos** [comment]
I guess this can now be closed 
https://firebase.google.com/docs/remote-config/use-config-web

**Comment by Feiyang1** [comment]
Thanks everyone for your continued support! I know it's a long standing feature request and we have now added Remote Config support for Web!! It's available now in `firebase@7.0.0`! 

Thanks @IchordeDionysos for the link. I will close the issue now.
