### ISSUE TITLE
Unable to link email/password provider to another user B after unlink from user A

### ISSUE THREAD

**Issue by tuannguyent20** [firebase/firebase-js-sdk#3603]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome Version 84.0.4147.105
  * Firebase SDK version: npm package firebase@7.15.3
  * Firebase Product: auth
  * Firebase Authentication Sign-in method: Multiple accounts per email address

#### Steps to reproduce:

1. Login to account A using a phone number: ok
2. Link the email (i.e importantEmail@gmail.com) to the account A: ok
3. Unlink the email (importantEmail@gmail.com) from account A: ok
4. Logout of account A: ok
5. Login to another account B using another phone number: ok
6. Link the email (importantEmail@gmail.com) to the account B: tada -> error {code: "auth/wrong-password", message: "The password is invalid or the user does not have a password.", a: null}

#### Relevant Code:

>  const email               = 'importantEmail@gmail.com';
  const password            = '123456';
  const phoneNumber1        = '+1 650-555-1234'; // add this phone number to your Firebase Authentication Phone numbers for testing with verification code '123456'
  const phoneNumber2        = '+1 650-555-5678'; // add this phone number to your Firebase Authentication Phone numbers for testing with verification code '123456'
  const verificationCode    = '123456';
  
>  // 1. Login to account A using a phone number:
  let userA: firebase.User;
  const applicationVerifier = new firebase.auth.RecaptchaVerifier('recaptcha-buton', {size: 'invisible'});
  const phoneProvider       = new firebase.auth.PhoneAuthProvider();
  const verificationId      = await phoneProvider.verifyPhoneNumber(phoneNumber1, applicationVerifier);
  const phoneCredential1    = firebase.auth.PhoneAuthProvider.credential(verificationId, verificationCode);
  const signInResult1       = await firebase.auth().signInWithCredential(phoneCredential1); // -> ok
  userA                     = signInResult1.user;
  console.log('user after signin: ', userA); // -> user providers: 'phone'
  
>  // 2. Link the email (i.e importantEmail@gmail.com) to the account A:
  const emailCredential     = firebase.auth.EmailAuthProvider.credential(email, password);  // -> ok
  const linkResult          = await userA.linkWithCredential(emailCredential);              // -> ok
                              await userA.reload();
  userA                     = await firebase.auth().currentUser;
  console.log('user after link: ', userA); // -> user providers: 'phone', 'password'
  
>  // 3. Unlink the email (importantEmail@gmail.com) from account A:
                              await userA.unlink('password');                               // -> ok
                              await userA.reload();
  userA                     = await firebase.auth().currentUser;
  console.log('user after unlink: ', userA); // -> user providers: 'phone'
  
>  // 4. Logout of account A:
                              await firebase.auth().signOut();                              // -> ok
  userA                     = null;
  
>  // 5. Login to another account B using another phone number:
  let userB: firebase.User;
  const anotherVerifier     = new firebase.auth.RecaptchaVerifier('recaptcha-buton', {size: 'invisible'});
  const otherPhoneProvider  = new firebase.auth.PhoneAuthProvider();
  const verificationId2     = await otherPhoneProvider.verifyPhoneNumber(phoneNumber2, anotherVerifier);
  const phoneCredential2    = firebase.auth.PhoneAuthProvider.credential(verificationId2, verificationCode);
  const signInResult2       = await firebase.auth().signInWithCredential(phoneCredential2); // -> ok
  userB                     = signInResult2.user;
  console.log('user after signin: ', userB); // -> user providers: 'phone'
  
>  // 6. Link the email (importantEmail@gmail.com) to the account B:
  const emailCredential2    = firebase.auth.EmailAuthProvider.credential(email, password);  // -> ok
  const linkResult2         = await userB.linkWithCredential(emailCredential2);
  // -> 1st case: {code: "auth/wrong-password", message: "The password is invalid or the user does not have a password.", a: null}
  // -> 2st case: {code: "auth/requires-recent-login", message: "This operation is sensitive and requires recent au…ation. Log in again before retrying this request.", a: null}

To mitigate the 2nd case, I did:
1. Login using the email/password => {code: "auth/wrong-password", message: "The password is invalid or the user does not have a password."}
2. Register the email/password => {"code":"auth/email-already-exists","message":"The email address is already in use by another account."}

Finally, I have to delete the userA with any providers it has just to get back the email availability.
Though I can trick firebase to hold an invalid@emailaddress.com by the privileges of the service account but this way is a not-fair work around.

**Comment by scottcrossen** [comment]
Hi! As mentioned in your previous [issue](https://github.com/firebase/firebase-js-sdk/issues/3592), The unlink password operation only unlinks the password from the account. The email remains as part of the account data, as intended. It's possible to overwrite this using a sentinel value or by sending the identifier "EMAIL" to the deleteAttributesList of the REST API [endpoint](https://developers.google.com/identity/toolkit/web/reference/relyingparty/setAccountInfo).

**Comment by tuannguyent20** [comment]
> The unlink password operation only unlinks the password from the account. The email remains as part of the account data, as intended.

Firebase has the right to keep the email **only as part of its local account data** for later use of its authentication purposes but it has no right to occupies the email **as exposed account data** as its intended because this could caused inhibition to freely use the unlinked email as of **expectation of the email owner**, though the email owner could had the chance to never link the email to a firebase user otherwise...

> It's possible to overwrite this using a sentinel value or by sending the identifier "EMAIL" to the deleteAttributesList of the REST API [endpoint](https://developers.google.com/identity/toolkit/web/reference/relyingparty/setAccountInfo).

So instead of unbelievable delete the firebase user that may has a lot of linked providers to just only grab his/her own email from firebase, we have 2 more choices:

1. Overwrite the email using a sentinel value: fine but as I mentioned before that's ugly work around
2. Sending the identifier "EMAIL" to the deleteAttributesList of the REST API [endpoint](https://developers.google.com/identity/toolkit/web/reference/relyingparty/setAccountInfo): as I have seen there has no deleteAttributesList field in the request of your mentioned endpoint, maybe it was a hidden field? Could you give me an example of code to make the request with deleteAttributesList field? I appreciated.
