### ISSUE TITLE
Npm does not install the package ?

### ISSUE THREAD

**Issue by MenaiAla** [firebase/firebase-js-sdk#3628]
Command : `npm install --save firebase`
Expected : package installed
Happened : `npm ERR! Response timeout while trying to fetch http://registry.npmjs.org/firebase (over 30000ms)`

**Comment by hsubox76** [comment]
This seems likely to be an npm issue. Can you install other packages?

**Comment by MenaiAla** [comment]
Yes, I can install any package. Also, I installed firebase 4.0.0 but the build status for 7.x.x is failed on npm.

**Comment by Feiyang1** [comment]
I just tried it and it worked for me. npm recently had [issue](https://github.com/npm/cli/issues/1624) with installing scoped packages, but your problem seems to be different. You should create an issue with npm if it persists.

Closing the issue because it's out of scope of this repo.
