### ISSUE TITLE
Breaking changes in initializeApp behaviour

### ISSUE THREAD

**Issue by piuccio** [firebase/firebase-js-sdk#363]
### [REQUIRED] Describe your environment

  * Operating System version: any
  * Firebase SDK version: 4.8.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

```javascript
  const app = firebase.initializeApp(config, key);
  app.auth().useDeviceLanguage();
```

The code above used to work just fine with `4.6.2` but when I update to `4.8.0` I get the error

```
Uncaught TypeError: app.auth is not a function
```

The return value of `initializeApp` used to look like this

<img width="144" alt="screen shot 2017-12-10 at 16 51 14" src="https://user-images.githubusercontent.com/680284/33803083-c0da98b2-ddca-11e7-9f13-a8e3cd3fe6eb.png">

it now looks like

<img width="143" alt="screen shot 2017-12-10 at 16 53 04" src="https://user-images.githubusercontent.com/680284/33803086-c99ef68c-ddca-11e7-81b0-fbe8f10ea1f7.png">

`services` is now an empty object and `auth` is missing from the prototype

**Comment by bojeil-google** [comment]
Just tried it with Chrome and it works as expected:
```
 var app = firebase.initializeApp(config, 'myapp');
 app.auth().useDeviceLanguage();
  app.auth().signInWithEmailAndPassword('user@example.com', 'secretPassword')
```

Can you provide environment specified data?

**Comment by jshcrowthe** [comment]
Can you please do a clean reinstall of your dependencies and tell me if the issue persists?

**Comment by piuccio** [comment]
Had to `rm -rf node_modules`, `rm package-lock.json` and install again. Odd
