### ISSUE TITLE
FR: Allow for reading fields of a document, instead of retrieving the entire document

### ISSUE THREAD

**Issue by jsilvao** [firebase/firebase-js-sdk#3639]
Just like in Real Time Database you can get a specific field/leaf in the tree, allow for Firestore to get a specific field of a document. This is to prevent downloading the entire document for the sake of a field and to prevent restructuring the database as a workaround when simply something like `/path/to/doc/field` makes more sense.

**Comment by wu-hui** [comment]
Hi @jsilvao 

This has been asked before: https://github.com/firebase/firebase-js-sdk/issues/212. I think there are some very useful discussion in that thread, from both sides, please add your point there if you have a new use case that has not been discussed there.

In the meantime, I am closing this one to keep discussion consolidated.
