### ISSUE TITLE
TypeError: firebase.analytics is not a function

### ISSUE THREAD

**Issue by Gonza462** [firebase/firebase-js-sdk#3675]
### [REQUIRED] Describe your environment

  * Operating System version: __xxxx___
  * Browser version: __xxx__
  * Firebase SDK version: __^7.15.0___
  * Firebase Product: _analytics____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

I have a backend functions project with cloud functions and its deployed already and working. Im trying to add analytics to my app. I have my config.js file seperate with the measurement id and everything. It looks like this

module.exports = {
  apiKey: "xxxxxxxxxxxxxxxxxxxxx",
  authDomain: "xxxxxxxxxxxxxxxxx",
  databaseURL: "xxxxxxxxxxxxxxx",
  projectId: "xxxxxxxxxxxxxxxx",
  storageBucket: "xxxxxxxxxxxxxxx",
  messagingSenderId: "134652497661",
  appId: "xxxxxxxxxxxxxxxx",
  measurementId: "xxxxxx",
};

then in my users.js file i have these imports where i initialize firebase. However it crashes on line where I try to call analytics.

package.json looks like this. I already tried npm installing @firebase/analytics and still doesnt solve the problem. Any reason why i can do firebase.initializeApp(config) but cant call analytics()???

 "dependencies": {
    "express": "^4.17.1",
    "firebase": "^7.15.0",
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.6.1",
    "firebase-tools": "^8.4.2"
  },

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem









const { db } = require("../util/admin");
const firebase = require("firebase");

const config = require("../util/config");

firebase.initializeApp(config);

//crashes here TypeError: firebase.analytics is not a function when I do firebase deploy.
firebase.analytics();







 "dependencies": {
    "express": "^4.17.1",
    "firebase": "^7.15.0",
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.6.1",
    "firebase-tools": "^8.4.2"
  },

```

**Comment by hsubox76** [comment]
So if I'm understanding correctly, you are trying to call this in a Node function? Analytics isn't supported in Node.

See https://firebase.google.com/support/guides/environments_js-sdk for which environments are supported for which products.

**Comment by Gonza462** [comment]
Im guessing i am in a node environment. I just have a javascript backend project thats already deployed using cloud functions and authentication which I see is supported. If I want to add Analytics to my React front-end web app thats using this deployed firebase backend is not possible then because im in a Node environment? Is there any alternative solutions.

**Comment by Feiyang1** [comment]
Seems like you are doing SSR? If so, you can detect the environment and only call `firebase.analytics();`when it's in browser. Something like:
```
if (typeof self !== 'undefined' && typeof self.document !== 'undefined') {
   firebase.analytics()
}
```

You can also guard your code using the newly added `firebase.analytics.isSupported()`, but it is asynchronous. see https://firebase.google.com/docs/reference/js/firebase.analytics?authuser=0#issupported

**Comment by bkr32** [comment]
i seem to be having the same issue, however running on firebase, in dev its fine but the issue sprouts up on production deploy
`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta content="" name="description">

  
  <meta content="yes" name="apple-mobile-web-app-capable">
  <meta content="black" name="apple-mobile-web-app-status-bar-style">
  <meta content="" name="apple-mobile-web-app-title">
  <meta content="-.apps.googleusercontent.com"
        name="google-signin-client_id">
  <link href="icons/Icon-192.png" rel="apple-touch-icon">

  
  <link href="favicon.png" rel="shortcut icon" type="image/png"/>

  <title></title>
  <link href="manifest.json" rel="manifest">
</head>
<body>
<script src="https://www.gstatic.com/firebasejs/7.16.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.16.1/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.16.1/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.18.0/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.18.0/firebase-performance.js"></script>
<script>
  // Your web app's Firebase configuration
  var firebaseConfig = {
    apiKey: "-",
    authDomain: ".firebaseapp.com",
    databaseURL: "https://.firebaseio.com",
    projectId: "",
    storageBucket: ".appspot.com",
    messagingSenderId: "",
    appId: "1::",
    measurementId: "G-"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  var perf = firebase.performance();
  firebase.analytics();






</script>

<script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }






</script>
<script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
`

**Comment by alejandroaap** [comment]
Hello,
In flutter the same thing occurs but only when it is built, not when it is executed directly. https://github.com/FirebaseExtended/flutterfire/issues/3409

**Comment by hsubox76** [comment]
First of all, it's probably not a good idea to use different versions of packages (7.16.1 and 7.18.0) as there could be incompatibilities. This may not be the cause of this specific problem but it can cause other problems.

Secondly, does this problem occur in a non-flutter webpage set up the same way? If not, it seems more likely it has something to do with FlutterFire's build process and it may be better to open an issue in the FlutterFire repo or follow the existing one there. If it turns out something in the JS SDK (this repo) needs to change to accommodate FlutterFire's build process, you can open an issue requesting that specific change.

**Comment by fourman-alex** [comment]
In case someone else is still in search of a solution/reason. Check that you don't have any tracking blockers running at the same time. Like adblock etc.
