### ISSUE TITLE
facing issue on success Sing in with Apple in web

### ISSUE THREAD

**Issue by RomikMk** [firebase/firebase-js-sdk#3699]
### Environment

Firebase Product: auth (apple)
Angular CLI 9

### Problem
Implemented successfully
facing issue when also sign in successfully from apple, and pop up is close,
then show 

I am not getting user which is login using apple...

#### Steps to reproduce:
```
Uncaught (in promise): Error: Error getting access token from https://appleid.apple.com,
 OAuth2 redirect uri is: https://bizyfreelancer-378f7.firebaseapp.com/__/auth/handler, 
response: OAuth2TokenResponse
{
       params: error=invalid_client, 
       httpMetadata: HttpMetadata{
      status=400, 
      cachePolicy=NO_CACHE, 
      cacheDurationJava=null,
       cacheImmutable=false,
       staleWhileRevalidate=null, filename=null, lastModified=null, 
      retryAfter=null,
       headers=HTTP/1.1 200 OK
```

**Comment by tamngonesv030** [comment]
same error...with firebase sdk sign with apple on unity.
No one supports....

**Comment by yuchenshi** [comment]
Hi all, please double check the configuration in Firebase Console, especially Services ID (and code flow fields if you're using that).

Friendly note that these fields are confidential -- please do not share screenshots or copy-pastes publicly on GitHub. If you still experience problems, please contact Firebase Support at https://firebase.google.com/support/troubleshooter/contact -- we can help you troubleshoot project settings there.
