### ISSUE TITLE
bug: firestore() will not work in prod build

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#371]
Are you in the right place?
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.

### [REQUIRED] Describe your environment
  * Operating System version: local: Win10
  * Firebase SDK version: tested with:
"firebase": "4.6.0",
    "firebase-tools": "3.14.0",
AND
"firebase": "4.8.0",
    "firebase-tools": "3.16.0",

  * Firebase Product: database: firestore

#### Steps to reproduce:
I use all the newest libs: angular5.1, angular-cli 1.6, angularfire: 5.0.0-rc-4.
When I have code where I use firestore as follows:
import firestore = firebase.firestore;
firestore().collection(...
it works on my development server.
when I deploy to firebase hosting with a production build the code fails, saying Wb() is not a function.
(Wb being the uglified firebase() function I suppose)

tested with 2 versions of firebase & firebase-tools, occurs in both.
If I do a deploy on firebase hosting with a dev build: the code works
If I run locally with a production build: the code fails.

if I do: firebase.firestore().collection(... the code works.

So, I suppose it's because 
firestore().collection(... as such is incorrectly parsed/processed by the production builder...

greetzzzz...

**Comment by mikelehen** [comment]
If you're still having this issue and believe there's something we can do in the Firebase SDK to address this, please let us know.  Thanks!
