### ISSUE TITLE
Using source-map-loader with firebase/auth gives multiple console warnings

### ISSUE THREAD

**Issue by jkevingutierrez** [firebase/firebase-js-sdk#3711]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Catalina 10.15.6 (19G2021)
  * Browser version: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
  * Firebase SDK version: 7.19.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Despite the issue #3353 being closed, I'm still having the same warning:

```
WARNING in ./node_modules/@firebase/auth/dist/auth.js
webpack_1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
webpack_1  | Failed to parse source map from '/code/node_modules/@firebase/auth/dist/ [synthetic:es6/util/makeiterator] ' file: Error: ENOENT: no such file or directory, open '/code/node_modules/@firebase/auth/dist/ [synthetic:es6/util/makeiterator] '
webpack_1  |  @ ./node_modules/firebase/auth/dist/index.esm.js 1:0-24
webpack_1  |  @ ./node_modules/firebaseui/dist/esm.js
```

**Comment by spencercap** [comment]
it's true on `"firebase": "^8.1.1",` too

**Comment by strom2357** [comment]
Thanks for reporting.  This is being tracked internally at b/174247852

**Comment by devmdmamun** [comment]
I'm having the same problem. I'm using firebase 8.5.

```
WARNING in ./node_modules/@firebase/auth/dist/auth.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
```

**Comment by TPXP** [comment]
The root cause is that the generated source map refers to "synthetic" files that don't exist and other files `node_modules` which don't exist when `@firebase/auth` is installed as a dependency.

To get rid of the warning, you can simply drop the reference to the source map file at the end of `/@firebase/auth/dist/auth.esm.js` (or `/@firebase/auth/dist/auth.js`):

```diff
diff --git a/node_modules/@firebase/auth/dist/auth.esm.js b/node_modules/@firebase/auth/dist/auth.esm.js
index 604afac..13e21a3 100644
--- a/node_modules/@firebase/auth/dist/auth.esm.js
+++ b/node_modules/@firebase/auth/dist/auth.esm.js
@@ -436,5 +436,3 @@ Y(tm.prototype,{Sb:{name:"getSession",j:[]},fc:{name:"enroll",j:[Eo(),V("display
 Z(a,"OAuthProvider",Pg,[V("providerId")]);Z(a,"SAMLAuthProvider",Og,[V("providerId")]);Z(a,"PhoneAuthProvider",lh,[Bo()]);Z(a,"RecaptchaVerifier",uo,[X(V(),Ao(),"recaptchaContainer"),W("recaptchaParameters",!0),Co()]);Z(a,"ActionCodeURL",Jf,[]);Z(a,"PhoneMultiFactorGenerator",eo,[]);firebase.INTERNAL.registerComponent({name:"auth",instanceFactory:function(b){b=b.getProvider("app").getImmediate();return new Fn(b)},multipleInstances:!1,serviceProps:a,instantiationMode:"LAZY",type:"PUBLIC",onInstanceCreated:function(b){b.getProvider("auth-internal").initialize()}});
 firebase.INTERNAL.registerComponent({name:"auth-internal",instanceFactory:function(b){b=b.getProvider("auth").getImmediate();return{getUid:q(b.getUid,b),getToken:q(b.nc,b),addAuthTokenListener:q(b.cc,b),removeAuthTokenListener:q(b.Pc,b)}},multipleInstances:!1,instantiationMode:"LAZY",type:"PRIVATE"});firebase.registerVersion("@firebase/auth","0.16.8");firebase.INTERNAL.extendNamespace({User:Im})}else throw Error("Cannot find the firebase namespace; be sure to include firebase-app.js before this library.");
 })();}).apply(typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : typeof window !== 'undefined' ? window : {});
-
-//# sourceMappingURL=auth.esm.js.map
```

**Comment by NickPelov** [comment]
Can we get an update on this. Because this source-map issue is still present in the latest v8.10.1 of firebase.

**Comment by simarpreetsingh-019** [comment]
so is there no particular solution till now to solve this issue in versions before 9.8.3? I am using 7.1.1(default version downloaded from npm I command

**Comment by hsubox76** [comment]
> so is there no particular solution till now to solve this issue in versions before 9.8.3? I am using 7.1.1(default version downloaded from npm I command

I was going to say that 7.1.1 is a very old version but it actually doesn't even exist. 7.1.0 was released October 2019 and the version after that was 7.2.0, one week later. Are you thinking of another package?
