### ISSUE TITLE
Regarding firebase collection issue - Try to access firebase collection multi times

### ISSUE THREAD

**Issue by yogeshpatil143** [firebase/firebase-js-sdk#3715]
### Try to access firebase collection multi times

  * Operating System version: MAC OS
  * Browser version: Ionic 3
  * Firebase SDK version: Latest
  * Firebase Product: firebase collection

### 
 .ts file

export class ABC {
        ......
        .......
        ......... 
         xyzList = ["abc", "XYZ", "pqr"];
        xyzList.forEach(async (item) => {
            await this.getDepartmentAbsentCount()
              .then((data: any) => {
              /// getting error
                console.log("Response =" + data)
              })
          })

   getDepartmentAbsentCount(){
       const snapshot = await firebase.firestore().collection('XXXX')
          .where('XXX', '>', '0').get()
         return snapshot.docs.map(doc => doc.data());
    }
}
#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by dconeybe** [comment]
Hi @yogeshpatil143! I don't fully understand the issue that you are experiencing. Could you explain what the actual behavior is, compared to your expected behavior? When you say "getting error" what is the actual error code and error message that you are seeing? Thanks!

**Comment by dconeybe** [comment]
I haven't had a chance to investigate yet, but one of my colleagues noted that using an `async` function as an argument to `forEach` could cause issues in that it doesn't work how you would expect. Can you try replacing the `forEach` statement with a traditional `for` loop? Here is a post with some more context: https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop

**Comment by dconeybe** [comment]
Hi @yogeshpatil143. I've attempted to reproduce this issue by adapting the sample code you provided in the issue description; however, I am not seeing any errors and the code completes successfully.

Could you try using the app that I posted to https://github.com/dconeybe/FirebaseJsBug3715 to see if this reproduces the issue for you?

For convenience, here is the interesting code in that app:

```ts
async function getDepartmentAbsentCount() {
  const snapshot = await firebase.firestore().collection('XXXX').where('XXX', '>', 0).get()
  return snapshot.docs.map(doc => doc.data());
}

async function main() {
  // Create some documents for the query.
  const collection = firebase.firestore().collection('XXXX');
  await collection.doc("Match1").set({"XXX": 1});
  await collection.doc("Match2").set({"XXX": 2});
  await collection.doc("NoMatch1").set({"XXX": 0});
  await collection.doc("NoMatch2").set({"XXX": 1});

  // Run the problematic query.
  const xyzList = ["abc", "XYZ", "pqr"];
  xyzList.forEach(async (item) => {
    await getDepartmentAbsentCount().then((data: any) => {
      console.log("Response =" + JSON.stringify(data));
    })
  })
}
```
