### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by sebitoelcheater** [firebase/firebase-js-sdk#3775]
### [REQUIRED] Describe your environment

  * Operating System version: Android 7.0
  * Browser version: Chrome Mobile 51.0.2704
  * Firebase SDK version: ^7.16.0
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

I have a web application that uses firebase and gets data from firestore. It works fine in my MacBook, iPhone and some Android devices. But when I try it in Chrome Mobile 51.0.2704 in Android 7.0, it seems to fail because Object.values is [unsupported in that browser](https://stackoverflow.com/questions/38748445/uncaught-typeerror-object-values-is-not-a-function-javascript).

```
@firebase/firestore: Firestore (7.19.0): FIRESTORE (7.19.0) INTERNAL ASSERTION FAILED: Unexpected state
```

#### Steps to reproduce:

Use firestore in a web app from Chrome Mobile 51.0.2704 in Android 7.0.

**Comment by hsubox76** [comment]
If developers require Firebase apps to work on older browsers, we require the developer to include polyfills in their app. See https://firebase.google.com/support/guides/environments_js-sdk#polyfills
