### ISSUE TITLE
Unresponsive page when trying to Create New Index in Firestore

### ISSUE THREAD

**Issue by dllmkdir** [firebase/firebase-js-sdk#3776]
### env

  * Operating System version: Macbook Air OS X (10.15.5)
  * Browser version: Google Chrome 
  * Firebase SDK version: 8.6.0
  * Firebase Product: Firestore

I have an error with the `collectionGroup` method because I haven´t created an index for this query,
The Error is:

```bash
Error: 9 FAILED_PRECONDITION: The query requires a COLLECTION_GROUP_ASC index for collection Comments and field creator.id. You can create it here: https://console.firebase.google.com/v1/r/project/MYFIREBASEPROJECT-c4a92/firestore/indexes?create_exemption=Cllwcm9qZWN0cy9pbm5vdGVraGViLWM0YTkyL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9Db21tZW50cy9maWVsZHMvY3JlYXRvci5pZBACGg4KCmNyZWF0b3IuaWQQAQ 
    at Object.exports.createStatusError (/workspace/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/workspace/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/workspace/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/workspace/node_modules/grpc/src/client_interceptors.js:1277:15)
    at InterceptingListener._callNext (/workspace/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/workspace/node_modules/grpc/src/client_interceptors.js:618:8)
    at /workspace/node_modules/grpc/src/client_interceptors.js:1033:24
```

So, I try to create the index with the URL that is described in the error, but when the page loads the background turns dark blue and the page stays unresponsive always trying to load from `console.firebase.google`.  In my particular case, my computer starts to heat up only with this page.

![Screen Shot 2020-09-14 at 15 23 21](https://user-images.githubusercontent.com/32945317/93134352-47515680-f69e-11ea-95a2-b4df0be10905.png)

#### Steps to reproduce:

Create a new Query Index and following the error link.

**Comment by wilhuff** [comment]
Substituting a test project into the URL you used, I was able to create an index on `creator.id` in `Comments` so there are a few possibilities:

  * An extension (e.g. an ad blocker) could be interfering; check by disabling extensions
  * There may be something specific to your project, but we can't help you with this here--only support has permission to inspect your account.

If this isn't caused by an extension, your best bet would be to open a [support ticket](https://firebase.google.com/support).

**Comment by dllmkdir** [comment]
I was able to do it manually, but the link crashed also in other navigators (Firefox, Safari). Could be a bug in the link generation.

**Comment by wilhuff** [comment]
The like seems correct: substituting my project id into the link created the index you were attempting to create.
