### ISSUE TITLE
node-fetch vulnerability for Denial of Service

### ISSUE THREAD

**Issue by carnun** [firebase/firebase-js-sdk#3796]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.15.6
  * Firebase SDK version: 
  * Firebase Product: firebase node module (functions and firestore)
  * Node.js version: 7.20.0
  * NPM version: yarn 1.22.4

### [REQUIRED] Step 3: Describe the problem

A low (Denial of Service) advisory has been issue for node-fetch versions prior to 2.6.1 https://www.npmjs.com/advisories/1556 which is a dependency of @firebase/firestore and @firebase/functions via isomorphic-fetch. Can these dependencies please be updated to circumvent this potential security risk.

#### Steps to reproduce:

Run the following commands
`yarn init` - setup a new project
`yarn add firebase` - add the node firebase package
`yarn audit` - display security vulnerabilities

**Comment by hsubox76** [comment]
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/3768 which is currently being addressed.
