### ISSUE TITLE
Issue with 'npm install firebase' like JSON parse input while parsing near <some file name>

### ISSUE THREAD

**Issue by PhoenixCreation** [firebase/firebase-js-sdk#3806]
### [REQUIRED] Describe your environment

  * Operating System version: windows 7 (32bit)
  * Browser version: none
  * Firebase SDK version: none(default by npm)

### [REQUIRED] Describe the problem
while installing the firebase with
`npm install firebase`
it shows error like below
![firebase_error](https://user-images.githubusercontent.com/63447220/93565476-111b1c00-f9a9-11ea-96c6-cac44023e19a.png)

It shows different file after json input while parsing near <different files here>

I have tried
`npm cache clean --force`
but still the issue peersists.

**Comment by akauppi** [comment]
@PhoenixCreation This is likely due to your `package.json` not being valid JSON. Please check it with e.g. https://jsonlint.com

**Comment by PhoenixCreation** [comment]
@akauppi but I am able to install other modules without any problem. And by the way it is auto generated by 'npx create-react-app'.

**Comment by hsubox76** [comment]
This doesn't seem like a Firebase error. First, can you delete your node_modules folder and your package-lock.json file and try reinstalling everything? I don't think `npm cache clean` does all of that.

If you're still having problems can you provide a minimum repro project that reproduces this issue, or at least your package.json?

**Comment by PhoenixCreation** [comment]
@hsubox76 I have tried creating one empty directory and then just initialized it with `npm init` and then just tried to install firebase and it also has the same issue.

Is there something to do with my system in this? Or slow internet connectivity can cause this?

**Comment by hsubox76** [comment]
I can't reproduce this, and looking around, Firebase doesn't have any dependency on @types/sinon version 4.3.1, which seems to be a very old version. Are you using an older version of node or npm? Can you update these?

**Comment by PhoenixCreation** [comment]
@hsubox76 I will try that. Thank you for responses.

**Comment by PhoenixCreation** [comment]
@hsubox76 `yarn add firebase` solved my issue but I have tried updating my node but the issue was still there. Maybe this is to do something with my system. Thank you for your support.
