### ISSUE TITLE
esbuild gives comparison to -0 compiling firestore

### ISSUE THREAD

**Issue by ojanvafai** [firebase/firebase-js-sdk#3814]
* Operating System version: N/A
  * Browser version: N/A
  * Firebase SDK version: 7.16.0
  * Firebase Product: firestore

[esbuild](https://github.com/evanw/esbuild) gives the following error compiling firestore:

```
node_modules/@firebase/firestore/dist/index.cjs.js:718:11: warning: Comparison with -0 using the === operator will also match 0
    return -0 === t && 1 / t == -1 / 0;
```

Technically both 0 and -0 work the same with === operator. The esbuild warning seems reasonable in general. Can we change the -0 to a 0? In some ways that's also more clear since -0 indicates that it needs to be -0 for the code to work.

Looks like this was added in https://github.com/firebase/firebase-js-sdk/commit/4f1f303402180224dd0d4f843e8dc2faee39fdea, which points to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is, which does not use -0.

So the proposal is to change the current code:
```
export function isNegativeZero(value: number) : boolean {
  return value === -0 && 1 / value === 1 / -0;
}
```

To the following:
```
export function isNegativeZero(value: number) : boolean {
  return value === 0 && 1 / value === 1 / -0;
}
```

**Comment by schmidt-sebastian** [comment]
@ojanvafai Thanks for letting us know about this. This is certainly something we can fix. I will prepare a PR right away.

**Comment by ojanvafai** [comment]
Wow. 3 days since filing! I had low hopes this had any chance of getting fixed at all. Thanks. :)
