### ISSUE TITLE
facebook login is broken

### ISSUE THREAD

**Issue by l02162010** [firebase/firebase-js-sdk#3815]
### [REQUIRED] Describe your environment

  * Operating System version: MAC OS 10.15.6
  * Browser version: Chrome 85.0.4183.102
  * Firebase SDK version: ^7.21.0
  * Firebase Product: auth

#### Steps to reproduce:
Use the firebase fb auth and follow [document](https://firebase.google.com/docs/auth/web/facebook-login?authuser=0) step by step.
When I use fb test account login and I got login page and login work
But after login, nothing happen, no response, no callback
what happen ?
#### Relevant Code:
I use vue .
```js
login(type) {
      let provider = null
      if (type === 'FB') {
        provider = new firebase.auth.FacebookAuthProvider()
      } else if (type === 'GOOGLE') {
        provider = new firebase.auth.GoogleAuthProvider()
      }
      if (provider) {
        auth
          .signInWithPopup(provider)
          .then((result) => {
            console.log(result)
            // This gives you a Google Access Token. You can use it to access the Google API.
            const token = result.credential.accessToken
            // The signed-in user info.
            const { user } = result
            this.$router.push({ name: 'Start' })
            console.log(token)
            console.log(user)
          })
          .catch((error) => {
          // Handle Errors here.
            const errorCode = error.code
            const errorMessage = error.message
            // The email of the user's account used.
            const { email } = error
            // The firebase.auth.AuthCredential type that was used.
            const { credential } = error
            console.log(error)
            console.log(errorCode)
            console.log(errorMessage)
            console.log(email)
            console.log(credential)
          })
          .finally((done) => {
            console.log(done)
          })
      }
    },
```
https://stackblitz.com/edit/vue-puqpfa?file=src%2FApp.vue

**Comment by malcolmdeck** [comment]
Hey l02162010,

Thanks for showing your code and explaining what's happening. Can you share a stack trace or and Console logs that happen during this flow? That might give us a better idea of how to reproduce this.

Thanks,
~Malcolm
