### ISSUE TITLE
waitForPendingWrites() doesn't resolve with multi-tab persistence

### ISSUE THREAD

**Issue by scottfr** [firebase/firebase-js-sdk#3816]
###  Describe your environment

  * Operating System version: Mac
  * Browser version: Chrome 85
  * Firebase SDK version: 7.21.0
  * Firebase Product: firestore

### Describe the problem

When using multi-tab synchronized persistence, waitForPendingWrites() does not resolve in some of the tabs when you have multiple tabs open.

In our experiments, it correctly resolves in one of the tabs when a write is initiated and tracked in it with waitForPendingWrites(). This is presumably the primary tab for the persistence synchronization.

For writes initiated and tracked in any of the secondary tabs though, waitForPendingWrites() never resolves.

**Comment by schmidt-sebastian** [comment]
@scottfr Thanks for letting us know! Looks like we missed this in our design. I will take a look to see how difficult it would be to fix.

**Comment by schmidt-sebastian** [comment]
We should be able to fix this soon.
