### ISSUE TITLE
'Can't find variable: self' in React Native - `app.messaging()`

### ISSUE THREAD

**Issue by diegoperini** [firebase/firebase-js-sdk#383]
For some reason during accessing a messaging instance via `app.messaging()`:

https://github.com/firebase/firebase-js-sdk/blob/a6b66892806d8393d20fad4f11325ba5b1a0e701/packages/messaging/index.ts#L26-L28

this shortcut condition despite self's being undefined doesn't work and it eventually throws in React Native 49. I fixed it with the work around below.

`global.self = {};`

Edit: It seems the work around doesn't work at all.

### Necessary Info:
React Native version: 49
Device: IPhone 5s iOS 11, iOS 9 Emulator, Sony Xperia Z5 Compact running Android 7.1.1
App State: Foreground
Firebase SDK version: 4.8.0
Firebase Product: messaging
Developer Machine OS: macOS High Sierra 10.13

**Comment by diegoperini** [comment]
Further investigation revealed current cloud messaging implementation does not support React Native. All these lines fail:

https://github.com/firebase/firebase-js-sdk/blob/a6b66892806d8393d20fad4f11325ba5b1a0e701/packages/messaging/src/controllers/window-controller.ts#L340-L348

**Comment by nighttiger1990** [comment]
@diegoperini can you make step by step config to use this package to React-Native to received Notification? 
Or can show me a link?
I alway got error when call "import firebase from 'firebase' firebase.messaging()"
messaging is not a function

**Comment by diegoperini** [comment]
@nighttiger1990 
```javascript
import firebase from 'firebase'
import 'firebase/messaging'

let app = firebase.initializeApp({
    apiKey: '<your-api-key>',
    authDomain: '<your-auth-domain>',
    databaseURL: '<your-database-url>',
    storageBucket: '<your-storage-bucket>',
    messagingSenderId: '<your-sender-id>'
  })

app.messaging()
```

**Comment by nighttiger1990** [comment]
when i call `app.messaging()` get `self is not defined`

**Comment by mmermerkaya** [comment]
Unfortunately React Native doesn't support the JS implementation of Firebase Messaging.

You can try [react-native-firebase](https://github.com/invertase/react-native-firebase) or [react-native-fcm](https://github.com/evollu/react-native-fcm).
