### ISSUE TITLE
Can't add both email sign in methods (emailLink, password) for a user account

### ISSUE THREAD

**Issue by Agusfn** [firebase/firebase-js-sdk#3856]
### [REQUIRED] Describe your environment

  * Operating System version: Android 10
  * Browser version: n/a (React Native App)
  * Firebase SDK version: 8.3.3 (auth)
  * Firebase Product: auth

### [REQUIRED] Describe the problem

I cannot appear to add the 'emailLink' sign in method to an account that already has the 'password' sign in method (both belong to Email/Password sign in provider). I can do the opposite though.

#### Steps to reproduce:

1) Create user account with email and password. 
`auth().createUserWithEmailAndPassword(email, password)`

This creates a new auth user in firebase, with "password" sign in method. We can check this with. `auth().fetchSignInMethodsForEmail(email)`
Returns` ["password"]`

2) Sign into this account with mail and password
`auth().signInWithEmailAndPassword(email, password)`

3) Now we want to associate the "emailLink" sign in method as well. We send the normal sign in mail to this account's address.
`auth().sendSignInLinkToEmail(email, actionCodeSettings)`

4) Click the link sent to the e-mail, handle the event, and verify it:
`auth().isSignInWithEmailLink(emailLink)`

5) Sign in with email link (this account is already signed in in the app though)
`auth().signInWithEmailLink(email, link)`
This returns the account credentials.

6) Obtain the new account sign in methods for e-mail:
`auth().fetchSignInMethodsForEmail(email)`

Returns` ["emailLink"]`, which doesn't include password, it has been discarded instead of added as a new method. **Maybe I am using the wrong method, or maybe it's not possible, i couldn't find any info on the internet.**

If i do the opposite (login without password on a new account, which creates a new auth user with "emailLink" method, and then call `auth().currentUser.updatePassword(password)`) firebase does add "password" to the sign in methods, which end up being `["emailLink", "password"]`.

I would appreaciate it if you could help me with this.

**Comment by kimbaudi** [comment]
@Agusfn - have you tried `firebase.auth.EmailAuthProvider.credentialWithLink`? see [Linking/re-authentication with email link](https://firebase.google.com/docs/auth/web/email-link-auth?authuser=0#linkingre-authentication_with_email_link)

```js
// Construct the email link credential from the current URL.
var credential = firebase.auth.EmailAuthProvider.credentialWithLink(
  email, window.location.href);

// Link the credential to the current user.
firebase.auth().currentUser.linkWithCredential(credential)
  .then((usercred) => {
    // The provider is now successfully linked.
    // The phone user can now sign in with their phone number or email.
  })
  .catch((error) => {
    // Some error occurred.
  });
```

**Comment by kimbaudi** [comment]
@Agusfn - I am able to add both email signin methods [`emailLink`, `password`] using `auth().signInWithEmailLink(email, href)` so I'm not sure why it is not working for you.

Here are my steps to sign up a user with email/password verification and then verify the email:

1. `const userCred = await firebase.auth().createUserWithEmailAndPassword(email, password)`
2. `if (userCred) { await user.sendEmailVerification() }
3. `await firebase.auth().applyActionCode(actionCode)`
4. `await firebase.auth().currentUser.reload()`

Also, a user might already have signed up with email/password verification. In this case,
here are my steps to sign in a user with email/password verification:

1. `const userCred = await firebase.auth().signInWithEmailAndPassword(email, password)`
2. `if (userCred) { /* user is signed in */ }`

At this point, `fetchSignInMethodsForEmail` returns `['password']`

Now, here are my steps to add `emailLink` to signin methods for email. Note: the user is logged in w/ password at this point:

1. `await firebase.auth().sendSignInLinkToEmail(email, actionCodeSettings)`
2. `window.localStorage.setItem('emailForSignIn', email)`

First, send an email w/ signin link and store user email in local storage (or cookie). When the user clicks the link, it should take the user to your page where you create [custom email action handlers](https://firebase.google.com/docs/auth/custom-email-handler) The link should contain a `mode=signIn` query parameter so handle `signIn` actions:

```js
if (mode === 'signIn') {
  if (firebase.auth().isSignInWithEmailLink(href)) {
    let email = window.localStorage.getItem('emailForSignIn')
    if (!email) {
      // User opened the link on a different device. To prevent session fixation
      // attacks, ask the user to provide the associated email again. For example:
      email = window.prompt('Please provide your email for confirmation')
    }
      firebase
        .auth()
        .signInWithEmailLink(email, href)
        .then((result) => {
          console.log('success signing in with email link')

          // Clear email from storage.
          window.localStorage.removeItem('emailForSignIn')

          // You can access the new user via result.user
          // Additional user info profile not available via:
          // result.additionalUserInfo.profile == null

          // You can check if the user is new or existing:
          // result.additionalUserInfo.isNewUser
        })
        .catch((error) => {
          // Some error occurred, you can inspect the code: error.code
          // Common errors could be invalid email and invalid or expired OTPs.
          console.log('error signing in with email link')
          console.log(error)
        })
  }
}
```

At this point, fetchSignInMethodsForEmail returns `['emailLink', 'password']`
