### ISSUE TITLE
Firestore Database Functions Fail To Execute in Mobile Devices Web Browsers

### ISSUE THREAD

**Issue by KanteLabs** [firebase/firebase-js-sdk#386]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10, iOS 9, iOS 11
  * Firebase SDK version: 4.8.0
  * Firebase Product: database

### [REQUIRED] Describe the problem
Currently, when using firestore to request data such as in Image 1 you run into unlogged errors on mobile devices. Specifically those on iOS 9 or lower. What I noticed is that any function that relies on db.collection... or db.doc.... never executes. This really problematic because it makes it impossible to design a web application that can work for devices above and below iOS 9. This is a problem that is not limited to Apple devices. I also noticed this on an Android device, that is fully updated. The current workaround for this problem is to use either Axios or the fetch API, to request data from a database URL. You can see an example of this in the attached Image 2 The final two images are a visual of the problem. In the Image 3, you can see that the webpage page never loaded because it never receives the data from the firestore request. However, in Image 4, the data is able to be requested and loaded. To actually test this, all you have to do is log an alert inside of a db.get() function. The alert runs on a desktop but never runs on mobile devices. If you switch this to an axios.get() the alert runs as expected. 

##### Image 1
[Code Sample Thats Broken on iOS 9](https://ibb.co/imMkX6)
##### Image 2
[Temp Solution/Workaround using Axios/Fetch](https://ibb.co/m8j5X6)
##### Image 3
[Broken Code View, No Data Loaded](https://ibb.co/ctx3Km)
##### Image 4
[Data Loaded using Axios](https://ibb.co/iLb8kR)

```javascript
// TODO(you): code here to reproduce the problem

```

**Comment by mikelehen** [comment]
That certainly shouldn't be the case.  Can you enable logging with `firebase.firestore.setLogLevel('debug')` and send the output?

**Comment by KanteLabs** [comment]
Alright, this, debug output is from a page that lists all the articles in my database. This, however, doesn't work on iOS 9 devices and below. Only on the desktop. 

Live site: https://streetwearboutiques.com/editorial
And code: https://github.com/KanteLabs/Clothing-Marketplace/blob/master/client/src/components/Article.jsx

[Debug Output](https://pastebin.com/xvRvYX4t)

**Comment by mikelehen** [comment]
Hrm...  The debug output actually looks successful (I can see that it's connecting to the backend and receiving the article documents' contents).  You're 100% sure your firestore callbacks aren't getting called at all?

**Comment by KanteLabs** [comment]
Yes it's really weird. I even updated to the latest version of chrome. The simplest way I was able to test the firebase executions was using an alert.

In the code below the alert will run on all devices except iOS 9. So from that, I was able to assume that the db.collection wasn't even executing, And I can't really debug a console on a mobile device to see what the console is logging. The debug output was from the desktop browser. I was thinking that maybe the firebase promises are triggering correctly on older devices? 
`
db.collection('articles').get.then((res)=>{
  alert("hi");
  res.forEach((article)=>{
      alert(article.data().title)
      })
 })
`

**Comment by mikelehen** [comment]
Oh!  iOS Safari 9.3 does not support arrow functions (https://caniuse.com/#feat=arrow-functions).  Try using `function(res) { ... }` instead of `(res) => { ... }`

**Comment by merlinnot** [comment]
@mikelehen nice catch 👍 

2k18 and we still have to worry about such things ;)

**Comment by KanteLabs** [comment]
Which means I have to either change to ```React.createClass``` in my components now in order to use 
```function(res) { ... }```. I think I have to find a way to compile my app to es5 so that it can work with older devices. Thanks for the help, I'm not able to test it at the moment since I will have to change a lot of my code.
