### ISSUE TITLE
Snyk reports new security vulnerability for firebase 7.17.2

### ISSUE THREAD

**Issue by mhnsn** [firebase/firebase-js-sdk#3861]
### [REQUIRED] Describe your environment

  * Operating System version: Windows
  * Browser version: Electron (Chromium)
  * Firebase SDK version: 7.17.2
  * Firebase Product: Auth? (The current release of firebase in npm)

### [REQUIRED] Describe the problem
Snyk.io, an integration we use for security auditing, reports a new vulnerability in the [version of node-fetch that firebase 7.17.2 uses](https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311). In our case, any new security vulnerability causes our CI pipeline to fail.

#### Steps to reproduce:

Run a snyk security audit on any nodejs project with firebase 7.17.2 installed.
#### Relevant Code:
package.json

**Comment by hsubox76** [comment]
This has been fixed. Please update to the latest version of Firebase (currently 7.21.1)

**Comment by mhnsn** [comment]
Wonderful, thank you.
