### ISSUE TITLE
FieldValue.serverTimestamp() no longer serializable

### ISSUE THREAD

**Issue by cmditch** [firebase/firebase-js-sdk#3862]
* Operating System version: macOS 10.15.6
  * Browser version: Chrome 85.0.4183.121
  * Firebase SDK version: 7.21.1
  * Firebase Product: firestore

This change appeared after 7.15.0 (worked in 7.14.6).

```
console.log(JSON.stringify(firebase.firestore.FieldValue.serverTimestamp()));

> Uncaught TypeError: Converting circular structure to JSON
>    --> starting at object with constructor 'n'
>    --- property 's_' closes the circle
>    at JSON.stringify
```

The value references itself.
![Screen Shot 2020-09-29 at 10 45 30 AM](https://user-images.githubusercontent.com/15849320/94607071-aa271e00-0258-11eb-98d8-60f608047476.png)

**Comment by schmidt-sebastian** [comment]
@cmditch Thanks for filing this. Almost all of our types will have this problem and I am trying to understand what the user impact is here. Can you describe your use case?

**Comment by schmidt-sebastian** [comment]
@cmditch Never mind. This is already fixed in the release that is going out this week. Thanks for catching it.

**Comment by cmditch** [comment]
In short, we [granularly track](https://github.com/RealKinetic/elm-firestore/blob/master/src/index.d.ts#L96) the state of a document, and need to serialize this latest version of the doc to pass off to our runtime (Elm).

Our stack is [elm-lang](https://elm-lang.org) + firebase. Elm is a compile-to-js language. If you want to talk to native javascript (e.g. firebase-js-sdk) from Elm you must use [ports](https://guide.elm-lang.org/interop/ports.html). Ports rely on `JSON.stringify` which allow [decoders](https://guide.elm-lang.org/effects/json.html#json-decoders) to work their magic. Long story short, since Elm <-> JS interop is not callback based, the cleanest way we've found to update the state of our Elm app is to pass the entire firestore document each time an alteration occurs.

The library we've written ([elm-firestore](https://github.com/RealKinetic/elm-firestore/blob/master/src/index.d.ts#L62)) also uses [hooks](url) which allow the user to [massage document data](https://github.com/RealKinetic/elm-firestore/blob/master/example/index.ts#L56) in ways that Elm can't, e.g. adding `FieldValue.serverTimestamp()` to a field.

**Comment by schmidt-sebastian** [comment]
This has already been fixed by https://github.com/firebase/firebase-js-sdk/pull/3819
