### ISSUE TITLE
Error: INTERNAL ASSERTION FAILED in production build

### ISSUE THREAD

**Issue by AkisArou** [firebase/firebase-js-sdk#3865]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chromium 87.0.4251.1 (Electron)
  * Firebase SDK version: 7.21.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Electron app in production, running Chromium 87.0.4251.1 randomly throws: 
Error: FIRESTORE (7.21.1) INTERNAL ASSERTION FAILED: Unexpected state.
It is mentioned for jest tests in an issue now closed, but never for a production build.
User probably has no or unstable internet connection.
Firestore persistence is enabled

#### Steps to reproduce:
Tried to reproduce while offline but with no luck.

**Comment by wu-hui** [comment]
Hi @AkisArou 

Thank you for reporting the issue. 

`INTERNAL ASSERTION FAILED` is very generic, it simply means the SDK run into a state that it does not know how to handle, it is not very useful for trouble shooting purpose.

We are not very familiar with Electron ourselves, and I am afraid there is not much help we can provide unless you can provide a reliable reproduction.

Sorry.

**Comment by schmidt-sebastian** [comment]
@AkisArou Do you have a stacktrace? We should be able to narrow down the location of the error.

**Comment by xero88** [comment]
I have exactly the same issue.

Ionic, with last version of firebase

"firebase": "^7.22.1"

on electron too, with firestore persistence enabled.

It's thrown after a few create / fetch in firestore.

My code look like this : 

`
    async fetchSecurityPointList(trackID: string): Promise<SecurityPoint[]> {
        const securityPointListRef = this.db
            .collection(`tracks/${trackID}/pointOfInterestList`)

        const securityPointListSnap = await securityPointListRef.get();
        return await Promise.all(securityPointListSnap.docs.map(async (doc: any) => {
            const data = doc.data()

            const pointOfInterestRef =
                await this.db
                    .collection(`tracks/${trackID}/pointOfInterestList`)
                    .doc(doc.id)
                    .get()
            const pointOfInterest = pointOfInterestRef.data()

            const securityElementListRef =
                await this.db
                    .collection(`tracks/${trackID}/pointOfInterestList/${doc.id}/securityElementList`)
                    .get()

            return (new SecurityPoint({
                id: data.id,
                pointOfInterest: new PointOfInterest({
                    ...pointOfInterest,
                    coordinates: {
                        latitude: pointOfInterest.coordinates.latitude,
                        longitude: pointOfInterest.coordinates.longitude,
                        altitude: pointOfInterest.coordinates.altitude,
                    }
                }),
                securityElementList: await Promise.all(securityElementListRef.docs.map(async (doc: any) => {
                    const data = doc.data()
                    const iconElement = (await data.iconElement.get()).data()

                    return new SecurityElement({
                        ...doc.data(),
                        iconElement: iconElement
                    })
                }))
            }))
        }));
    }

    createPointOfInterest(pointOfInterest: PointOfInterest, trackID: string) {
        this.db
            .collection(`tracks/${trackID}/pointOfInterestList`)
            .doc(pointOfInterest.id)
            .set(new PointOfInterestConverter().getConverter().toFirestore(pointOfInterest))
    }
`

Do you want more ?

I wil try to downgrade, to see if it's work

**Comment by xero88** [comment]
I think that I have maybe found my issue : 

I was using  `enableNetwork`  somewhere in my code : 

```
  setInterval(() => {
            if (this.checkOnline()) {
                this.db.enableNetwork().then(() => this.setIsOnline(true));
                this.setIsOnline(true)
            } else {
                this.db.disableNetwork().then(() => this.setIsOnline(false));
                this.setIsOnline(false)
            }
        }, 10 * 1000); // each 5 seconds
```

I commented `this.db.enableNetwork` and `db.disableNetwork` lines

**Comment by schmidt-sebastian** [comment]
@xero88 Your last stacktrace is very interesting ("Cannot read property 'mutations' of undefined"). Unfortunately, there are still about 15 spots in the SDK where this could occur. If you are able to reproduce this, can enable debug logging (`setLogLevel('debug')`) and let me know the couple of log lines that immediately precede this statement?

Otherwise, if you are able to run your code unminified or let me know what "4.57dc4c40.chunk.js:2:2195597" corresponds to (via your sourcemap) I should be able to fix this quickly.
