### ISSUE TITLE
FR: collection group query within collections of a document's subcollections' documents.

### ISSUE THREAD

**Issue by dzhamshed** [firebase/firebase-js-sdk#3867]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 7.21.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
With the [Run Query](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases.documents/runQuery) we can query within collection group of a document's subcollections, but this is not available in the client SDK. The client SDK allows querying collection group only on the root level. 

#### Steps to reproduce:

For example we have a collection of __rootCollection__ and its documents have subcollection __subCollection__. Documents of __subCollection__ also have subcollection __subSubCollection__. It's possible to query collection group __subSubCollection__ across all database, but not just inside __rootCollection/someDocId.__

#### Relevant Code:
```ts
firebase.firestore().collectionGroup('subSubCollection'); // OK

// collectionGroup does not exist in DocumentReference. 
firebase.firestore().collection('rootCollection').doc('docId').collectionGroup('subSubCollection'); // Error
```
Is there anything preventing from implementing this in the client SDK?

**Comment by wu-hui** [comment]
Hi @dzhamshed 

Thanks for pointing out the inconsistencies between SDKs and the REST API.

First I want to confirm that it is possible to run collection group queries on sub-collections via REST API, it has a restriction though: there must not be any filters or order-by with the query. 

Second, given the restriction above, we will not support this in SDKs, we will re-evaluate this when this restriction is lifted.

Third, there are some workarounds in SDKs that you can do to simulate a collection group query on sub-collections, unfortunately they require you to have some sort of special filed in your documents. For example,  you can have a field for parent's collection path in a document, and filter on this field when running collection group queries.

Thank you again!
