### ISSUE TITLE
Failures/Warnings when retrieving measurementId via GetDynamicWebConfig 

### ISSUE THREAD

**Issue by mcoolidge** [firebase/firebase-js-sdk#3877]
### Describe your environment

  * Operating System version: Windows
  * Browser version: 85
  * Firebase SDK version: 7.21.1
  * Firebase Product:  all

###  Describe the problem
After updating to the latest versions, I now see a 403 and warning during initialization

"index.esm.js:106 [2020-10-01T19:41:18.520Z]  @firebase/analytics: Failed to fetch this Firebase app's measurement ID from the server. Falling back to the measurement ID XXXXXX provided in the "measurementId" field in the local Firebase config. [Analytics: Dynamic config fetch failed: [403] Requests to this API firebase.googleapis.com method google.firebase.service.v1alpha.DynamicConfigService.GetDynamicWebConfig are blocked. (analytics/config-fetch-failed).]"

I have tried granting access to all the following, but the error persists:
- Cloud Firestore API
- Identity Toolkit API
- Firebase Installations API
- Places API
- Maps JavaScript API
- Token Service API
- Firebase Remote Config API
- Firebase Dynamic Links API

The config object does have a measurementID passed in, but the SDK seems to ignore this unless there is a failure. Nothing else was changed.

**Comment by hsubox76** [comment]
Analytics was updated in 7.20.0 to dynamically retrieve the measurement ID from dynamic config and only fall back to the local config if the dynamic config fetch fails. [See the release notes for more](https://firebase.google.com/support/release-notes/js#version_7200_-_september_10_2020).

As for why the fetch is failing, let me check with the backend team about which API permissions you would need to enable.

If you are able to temporarily set it to no restrictions and let me know if the error goes away when you do that, that would be helpful. Maybe you could try it on another test project if that is a production project where you don't want to lift restrictions.

**Comment by hsubox76** [comment]
So the API you need to enable should be the `Firebase Management API`. Let me know if that solves the problem (also if it doesn't).

**Comment by hsubox76** [comment]
I also have one more question if you don't mind, did you manually restrict the API key on your project, or was it set up that way by default? If manually, can I ask why? I just want to see how likely other users are to run into this issue, and in which use cases.

**Comment by mcoolidge** [comment]
Thanks so much! Adding Firebase Management API resolved the error.

We have our client side API key locked down as much as possible with website and API restrictions. With this being client side JS, this API key only has access to firebase and maps APIs.

The application behavior was unchanged and I found the PR with the updated logic, so I figured this was a callout to a new service that wasn't already enabled. It just wasn't clear what service would need to be enabled (you would think just remote config). It might be helpful to add a note to the changelog in case others run into the same issue. Thanks again for the help!

**Comment by solid-yuriiuvarov** [comment]
> So the API you need to enable should be the `Firebase Management API`. Let me know if that solves the problem (also if it doesn't).

Also, if your API Key has [restrictions](https://console.cloud.google.com/apis/credentials), you need to allow access to this API.

**Comment by nilsreichardt** [comment]
> So the API you need to enable should be the `Firebase Management API`. Let me know if that solves the problem (also if it doesn't).

This solves the problem 👍  So I think we can close this ticket.
