### ISSUE TITLE
The setting 'timestampsInSnapshots: true' is no longer required and should be removed

### ISSUE THREAD

**Issue by wceolin** [firebase/firebase-js-sdk#3879]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.13.6
  * Browser version: Chrome 85.0.4183.121
  * Firebase SDK version: 7.22.0 / 7.21.0
  * Firebase Product: Firestore

#### Steps to reproduce:
When we use the `merge: true` option in the `settings` (implemented by #3464), we get the error below even though we are NOT setting `timestampsInSnapshots` to `true`:

```
@firebase/firestore: Firestore (7.22.0): The setting 'timestampsInSnapshots: true' is no longer required and should be removed.
```

#### Relevant Code:

https://codesandbox.io/s/firebase-merge-settings-dxbx1?file=/src/firebase.js

```javascript
firebase.firestore().settings({ merge: true });
```

**Comment by thebrianchen** [comment]
Thanks for filing the bug report with a repro! I've repro'd it on my machine as well. Will look into this deeper next week.
