### ISSUE TITLE
Firebase issues: an open discussion

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-js-sdk#389]
Hi,

I’d like to start a public discussion on the issues with Firebase and a courage to admit those. Since Thursday there’s an ongoing issue with Firestore where data from some collections cannot be accessed. I’ve been in touch with Firebase support and they’ve acknowledged the issue:

> Upon checking on our end, there's an ongoing discussion regarding the error log you've sent to us. We are currently working to get it fixed, however, at the moment we cannot share any details or timeline for the fix.

Despite being aware of the issue, it’s not mentioned at the [status](https://status.firebase.google.com) page. It’s a global outage impacting 100% of certain queries, super easy to reproduce.

Two weeks ago there was another issue which was acknowledged by Firebase support and not listed on the status page, another one about two month ago. I have emails to back all of these statements.

If I’d be to choose a technology for my next project, I’d like to be aware of it being down so often for such an extended period of time. You guys must not keep this information hidden.

**Comment by jshcrowthe** [comment]
Hey @merlinnot, thanks so much for the feedback. Awesome developers providing feedback (especially the criticisms of our weaknesses) are extremely important to us and a big part of how we got here. The best place to discuss this would be on the [Firebase Talk Group](https://groups.google.com/forum/#!forum/firebase-talk) and I'd love to see you post this there. That would help us to keep the issues here focused on SDK code specific issues while still enabling the conversation. 

I'm going to close this issue, but I look forward to the conversation in the other channel!
