### ISSUE TITLE
Cannot use Svelte with "firebase/storage"

### ISSUE THREAD

**Issue by GoldStrikeArch** [firebase/firebase-js-sdk#3892]
### [REQUIRED] Describe your environment

  * Operating System version: ___windows 10__
  * Browser version: __latest chrome, latest firefox___
  * Firebase SDK version: _7.22.0____
  * Firebase Product: __storage___ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

I am trying import "firebase/storage" and I am getting this error:

`instance.INTERNAL is undefined`

and it leads me into registerStorage function inside index.esm.js at line 3492:
`instance.INTERNAL.registerComponent(new Component(STORAGE_TYPE, factory, "PUBLIC" /* PUBLIC */)`

If am using **ANY** other "firebase/__PACKAGE_NAME__" import everything is fine.
#### Steps to reproduce:

1) Get official [svelte template](https://github.com/sveltejs/template) or use "npx degit sveltejs/template firebase-error"
2) Run "yarn install" and "yarn add firebase"
3) try to import "firebase/storage" in your App.svelte

#### Relevant Code:

```
//inside App.svelte
<script>
  import firebase from "firebase/app";
  import "firebase/firestore";
  import "firebase/auth";
  import "firebase/storage"; // Error occurs here

  let firebaseConfig = {
    // Insert Firebase Credentials here
  };
  firebase.initializeApp(firebaseConfig);
</script>

<h1>If your remove `import "firebase/storage"` line, the error is gone</h1>

```

**Comment by MihailPertsev** [comment]
This might be useful for someone with the same problem.
The source of the problem is @rollup/plugin-commonjs devDependency, you should downgrade it to 11.0 and then everything works. I dont know why tho...

**Comment by hsubox76** [comment]
Note for self: We are using `rollup-plugin-commonjs` which was deprecated about 10 months ago in favor of `@rollup/plugin-commonjs`, not sure if that has something to do with this, should look into upgrading.

**Comment by hsubox76** [comment]
After some testing it seems it's not related to our usage of the rollup-plugin-commonjs dependency.

However it seems likely to be a bug related to some recent change in `@rollup/plugin-commonjs` that affects named exports. Would you be able to post an issue in that repo?

If you're looking for hacky workarounds, sounds like downgrading the @rollup/plugin-commonjs version is one solution you have found to work, another workaround that works for me is removing `browser: true` from the Svelte project's rollup.config.js here:

```
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
```

This could affect other dependencies in the project in unexpected ways, though. You can also replace `browser: true` with `mainFields` and mess around with the order, putting `module` before `browser`. These workarounds ensure you're using the esm bundle from all Firebase packages that provide it and not the cjs bundle, which seems to be affected by this possible plugin bug.
