### ISSUE TITLE
signInWithCustomToken - auth/invalid-api-key

### ISSUE THREAD

**Issue by brancusi** [firebase/firebase-js-sdk#39]
### [REQUIRED] Describe your environment

  * Operating System version: OSX - 10.12.6
  * Firebase SDK version: 3.4.1
  * Firebase Product: auth

#### Steps to reproduce:
1. Create a service account via the firebase console. Follow the instructions to generate a custom token on the server.
2. Attempt to sign in with the token on the client: `signInWithCustomToken`
3. This calls the endpoint `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken?key=MYAPIKEY`

With the following payload:

```json
{
  "token" : "my_custom_jwt_returned_from_server",
  "returnSecureToken" : true
}
```

4. Returns a 400:

```json
"error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "keyInvalid",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
```
#### Relevant Code:

```js
function (user, context, callback) {
    var admin = require("firebase-admin");

    var serviceAccount = {
      projectId: "my-fb-project",
      privateKey: "-----BEGIN PRIVATE KEY-----\nMYKEY\n-----END PRIVATE KEY-----\n",
      clientEmail: "firebase-adminsdk-u6ikt@my-fb-account.iam.gserviceaccount.com"
    };

    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      databaseURL: "https://my-fb-account.firebaseio.com"
    });

    var uid = "some-uid";

    admin.auth().createCustomToken(uid)
      .then(function(customToken) {
        user.user_metadata = user.user_metadata || {};
        user.user_metadata.fbtoken = customToken;

        return callback(null, user, context);
      })
      .catch(function(error) {
        console.log("Error creating custom token:", error);

        return callback(error, user, context);
      });
}
```

Is there a way to verify the token manually to see if it is indeed correct? When I put the token this function returns into jwt.io everything looks fine, but obviously something is failing. How can I attempt to validate it the same way the service: `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken?key=MYAPIKEY`

**Comment by bojeil-google** [comment]
Did you happen to add any restrictions to your browser API key? If so, you need to remove them via the Cloud Console. The error you are seeing is typically thrown in that situation.

**Comment by brancusi** [comment]
So sorry you are absolutely right, the last digit was missing from the key. Head smack! Thank you for the fast response.
