### ISSUE TITLE
`enablePersistence` doesn't work when the app starts offline

### ISSUE THREAD

**Issue by moshfeu** [firebase/firebase-js-sdk#3905]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.6 (19G2021)
  * Browser version: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
  * Firebase SDK version: 7.22.0
  * Firebase Product: realtime database, firestore

#### Steps to reproduce:

1. Initial regular firebase app.
2. Add `firebase.firestore().enablePersistence();` after the app initilization.
3. Add `app.database().goOffline();` (just to demonstrate offline mode. I also tested it without this line and without internet).
4. Add `db.ref().on( 'value', (snapshot) => { console.log(snapshot) })`

The `cosnole.log` never fired.

If the app **starts** in online and **then** go offline, it works well.

A note: If I understand correctly, `firebase.firestore().enablePersistence();` makes firebase storing a local version of the data but I couldn't find it anywhere (localStorage, cache, indexedb)

(Followed this doc: https://firebase.google.com/docs/firestore/manage-data/enable-offline#configure_offline_persistence)

#### Relevant Code:

https://codesandbox.io/s/charming-haslett-hfu7l?file=/src/App.js

```javascript
const app = firebase.initializeApp(firebaseConfig);
app.firestore().enablePersistence();
app.database().goOffline();
app.database().ref().on(value, snapshot => console.log(snapshot))
```

**Comment by hsubox76** [comment]
I might be misunderstanding, but are you enabling persistence in Firestore and then expecting it to enable persistence for Realtime Database? They are two separate products. If you want to use Firestore's offline persistence I believe you want to be querying Firestore (`app.firestore().collection(items)`) not Realtime Database (`app.database().ref('items')`). Realtime Database doesn't have an equivalent offline persistence feature (at least for Web).

Sorry if I'm misunderstanding what you're trying to do!

**Comment by moshfeu** [comment]
Apparently I was the one who misunderstanding. I didn't notice that this doc is under `firesotre` and that `firestore` is a totally different product. I thought that it another layer on top of the realtime db.
Sorry for that.

**Comment by moshfeu** [comment]
If someone is interested, I implemented a partially offline support for firebase.
This service wraps firebase realtime api. 

When the user online, each snapshot (`on('value')`) stored in localStorage.
When the client goes offline, the service, along with updating localStorage, it also add the changes in a queue. When the client is online again, the service send the updates to firebase and clean the queue.

As I said, it's only partially implemented but it can gives an idea and the basic for further work.

https://github.com/moshfeu/synced-shopping-list/commit/7124fb8968b305848c1e95bc2fbf32591ee0a45b#diff-b13a37881b4b22091b672007c3d25647
