### ISSUE TITLE
Breaking TypeScript definition changes in SemVer patch (4.8.1) release

### ISSUE THREAD

**Issue by colinskow** [firebase/firebase-js-sdk#392]
It appears that between 4.8.0 and 4.8.1 you did some major refactoring which affects the import of TypeScript definitions. The most common error is `Cannot find namespace 'firebase'.`

See: https://github.com/angular/angularfire2/issues/1387

This should ideally be done at a SemVer major release since basically everyone who imports TS definitions from Firebase now needs to refactor the imports because the build is broken. At bare minimum it should be a SemVer minor release so that `~4.8.0` will prevent builds from breaking.

Feel free to close this issue but I just wanted to point out the impact of the changes to developers. Many TypeScript projects aren't SemVer compliant and I think it benefits the community quite a bit when they are.

**Comment by LostOnEast** [comment]
Same problem, I find it when read this tutorial
 https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md

**Comment by jshcrowthe** [comment]
Hey @colinskow thanks for the issue and we appreciate your patience 😄 .

We're going to rollback the part of the typings refactor exposed by the NPM firebase package which should fix this issue (see #401). Thanks so much for your help!
