### ISSUE TITLE
`initializeTestApp` from `@firebase/rules-unit-testing` with jest, file scope variables are unset

### ISSUE THREAD

**Issue by ScottPierce** [firebase/firebase-js-sdk#3920]
### [REQUIRED] Describe your environment

  * Operating System version: OSX
  * Browser version: This is for test
  * Firebase SDK version:
```
        "firebase": "^7.23.0",
        "firebase-admin": "^9.2.0",
        "@firebase/rules-unit-testing": "^1.0.7",
        "@firebase/testing": "^0.20.11",
```
  * Firebase Product: firestore
  * Running tests with Jest inside of a NX workspace library

### [REQUIRED] Describe the problem
When I use `initializeTestApp` with the `@firebase/rules-unit-testing`, any variables that I set in the root scope of the file are invalidated in jest tests. The first test will pass, but then, when the second test is run, and `initializeTestApp` is called, the second test won't pass because file scoped variables are unset.

* In the second test, if `initializeTestApp` is removed,  the test passes just fine.
* If the import is changed from `@firebase/rules-unit-testing` to `@firebase/testing`, the test passes just fine.

Likely Unrelated:
I'm doing this in an nx react application.

#### Steps to reproduce:

Run the given code sample with Jest. The second test will fail, even though it shouldn't, because `testData.uid` will be unset.

Again, simply changing the import from `rules-unit-testing` to `testing` fixes the problem.

#### Relevant Code:

```typescript
import {
    apps,
    assertFails,
    assertSucceeds,
    clearFirestoreData,
    initializeAdminApp,
    initializeTestApp,
    loadFirestoreRules,
} from "@firebase/rules-unit-testing"

const testData = { uid: "UserId" }
const projectId = `user-feedback-db`
const myAuth = { uid: "user_me", email: "me@gmail.com" }

test("test1", () => {
    initializeTestApp({
        projectId: projectId,
        auth: myAuth
    })
    expect(testData.uid).toEqual("UserId")
})

test("test2", () => {
    initializeTestApp({
        projectId: projectId,
        auth: myAuth
    })
    expect(testData.uid).toEqual("UserId")
})
```

**Comment by n0mer** [comment]
@ScottPierce i have the similar problem. Try downgrading `@firebase/rules-unit-testing` from `1.0.7` to `1.0.6`, until this is fixed.

This serves as changelog: https://github.com/firebase/firebase-js-sdk/compare/@firebase/rules-unit-testing@1.0.6...@firebase/rules-unit-testing@1.0.7

**Comment by samtstern** [comment]
@ScottPierce sorry about that this one is my fault, fixing it here:
https://github.com/firebase/firebase-js-sdk/pull/3923

In the meantime if you downgrade your `rules-unit-testing` dependency to `1.0.5` it should not have that bug.

**Comment by ScottPierce** [comment]
How is this even possible? How did you unset variables in the parent scope, a `const` no less. I'm new to js / ts.

**Comment by samtstern** [comment]
If you look at the PR you'll see I was doing `delete auth.uid` which removes the `uid` key from the object.  I now make a copy before doing that.

`const` doesn't protect your obejct from being mutated, it only protects the reference from being reset. So:

```ts
const x = { a: 1 };

// This is allowed
x.a = 2;

// This is not allowed
x = { a: 2 };
```

**Comment by ScottPierce** [comment]
@samtstern So how was it failing for my above test with `testData.uid` in my example above, which is an object I'm not even giving to firebase. How could it remove the key from an object it doesn't even have access too?
