### ISSUE TITLE
fetchSignInMethodsForEmail() method is not returning the PHONE_SIGN_IN_METHOD method

### ISSUE THREAD

**Issue by nelson6e65** [firebase/firebase-js-sdk#3940]
### [REQUIRED] Describe your environment

  * Operating System version: any
  * Browser version: any
  * Firebase SDK version: 7.22.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

The `fetchSignInMethodsForEmail()` method is not returning the 'phone' method (`auth.PhoneAuthProvider.PHONE_SIGN_IN_METHOD`). I'm only getting `['facebook.com', 'password']`, but when I inspect the `providerData` property of `currentUser`, 'phone' provider is listed:

(Similar to #3856)

#### Steps to reproduce:

```console.log(auth().fetchSignInMethodsForEmail(currentUser.email))```
```json
[
  "password",
  "facebook.com"
]
```

```console.log(currentUser.providerData)```
```json

[
	{
	  "uid": "xxxxx",
	  "displayName": "xxxxx",
	  "photoURL": "https://graph.facebook.com/xxxxxxxx/picture",
	  "email": "xxxxxxxx@gmail.com",
	  "phoneNumber": null,
	  "providerId": "facebook.com"
	},
	{
	  "uid": "+xxxxxxxxxxxxx",
	  "displayName": null,
	  "photoURL": null,
	  "email": null,
	  "phoneNumber": "+xxxxxxxxxxxx",
	  "providerId": "phone"
	},
	{
	  "uid": "xxxxxxx@gmail.com",
	  "displayName": null,
	  "photoURL": null,
	  "email": "xxxxxxx@gmail.com",
	  "phoneNumber": null,
	  "providerId": "password"
	}
],
```

Is this intended or there is a way to get all providers for same user of email?

**Comment by abumoallim** [comment]
Did you found any solutions for this?

Because I have already authenticated with Phone Number and provided email in it and now I want to link Facebook account because I am getting ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL. But when I query fetchSignInMethodsForEmail I don't get the phone as a method. The array is empty

**Comment by nelson6e65** [comment]
@abumoallim, A workaround is, **_for an already authenticated user_**, to use the list of providers it has and match the `providerId`:

```typescript
import { auth } from 'firebase/app';

// ...

async fetchSignInMethodsFor(user: User): Promise<string[]> {
  const { email } = user;

  if (!email) {
    throw new Error('User has not email set');
  }

  const methods = await auth().fetchSignInMethodsForEmail(email);

  if (!methods.includes(auth.PhoneAuthProvider.PHONE_SIGN_IN_METHOD)) {
    if (user.providerData) {
      const phoneProvider = user.providerData.find((provider) => {
        return (
          provider &&
          provider.providerId === auth.PhoneAuthProvider.PROVIDER_ID
        );
      });

      if (phoneProvider) {
        methods.push(auth.PhoneAuthProvider.PHONE_SIGN_IN_METHOD);
      }
    }
  }

  return methods;
}
```

> BTW, using auth().fetchSignInMethodsForEmail() could hit your firebase quotas, so, for authenticated user I preffer to use `user.providerData` (just reload() in appropiated bootstrap/login flow of your application)

**Comment by abumoallim** [comment]
So you mean to say I anyways need to SignIn first with phone number and then link facebook to it.
What I was doing for Facebook and Google linking was to just use fetchSignInMethodsForEmail to get which one I am already authenticated with and just attach the other one if not found in fetchSignInMethodsForEmail and sign in later.

In the case of Google, it doesn't throw the error of ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL so I can just sign in with google and attach the phone number with it.
But in this case, I need to log in with Phone number and then link Facebook?

Also, Can you help me with finding the quota limit of fetchSignInMethodsForEmail? 
I tried this link: https://cloud.google.com/identity-platform/quotas#email_limits_2 but couldn't find this particular request.

Thank you so much for your help.

**Comment by nelson6e65** [comment]
> So you mean to say I anyways need to SignIn first with phone number and then link facebook to it.

Essentially, yes. 😓

BTW, it does not throw error if it is a Google account (gmail.com or any custom business domain for Gmail) because it auto-confim (actually, replaces the credentials if email is not confirmed).

> But in this case, I need to log in with Phone number and then link Facebook?
Yes. You can get the auth token when login with Facebook, log out, and redirect to phone login (if only Facebook, you may need to delete the account, but keeping the auth token to link when you redirect to phone login).

In my case I had to change my authentication flow in order to prevent this. First, phone, then, if not `emailVerified` try to verify (as I said, in case of Google sign in, it auto-verifies). If uses Facebook, I do what I said before: Link to Facebook later.

It is a little sad this, but, after the phone, the verifiedEmail is an important step before you link another provider to prevent some account details to get replaced (email/password provider get disappear).

**Comment by abumoallim** [comment]
Ok I understood completely.
Thanks for the detailed response.

**Comment by saqibsoftwares** [comment]
I'm also facing this issue and have reported to firebase team. Expecting their response anytime soon. Will share the response here when received.

**Comment by saqibsoftwares** [comment]
Here is the response from Firebase team:

> I was able to reproduce this behavior with the JS SDK and with Kotlin on Android. In the description of the method is mentioned that the method 'Gets the list of possible sign in methods for the given email address.', so, it returns the possible sign in methods, not all the methods because it fetches by email which phone auth doesn't have like the other sign in methods.
> 
> But, to be sure, I have escalated this issue to the engineering team for them to take a look and decide if this is working as expected or if there's indeed a bug, I'll let you know any news that they share with me.

**Comment by rosalyntan** [comment]
Hi, thanks for filing this issue! This is working as intended--`fetchSignInMethodsForEmail` is primarily intended to help differentiate sign-in methods for the same provider (for example, email/link sign-in vs. email/password sign-in).

https://firebase.google.com/docs/reference/js/firebase.auth.Auth#fetchsigninmethodsforemail
