### ISSUE TITLE
Firebase Auth doesn't work in ReactJS (I have tried several possibilities, none of them work)

### ISSUE THREAD

**Issue by 619** [firebase/firebase-js-sdk#3948]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.15.7
  * Browser version: Chrome 86
  * Firebase SDK version: 7.19.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
If you implement signInWithEmailAndPassword with await and wrapping it in a try block, it will literally throw an uncaught error despite the try block if the sign in fails as mentioned here(https://github.com/firebase/firebase-js-sdk/issues/1881). If you remove the awaits and use .then() and .catch(), it doesn't resolve asynchronously. The only solution is to redirect to home without catching errors and without looking at a callback, but then its impossible to tell if there has been a sign in error (like the user doesn't exist). Under the circumstances, I cannot think of a working implementation of Firebase auth that works like a regular signin service would. 

#### Steps to reproduce:
Try implementing firebase auth.

**Comment by 619** [comment]
I have found that CurtisHugh's comment on this [thread](https://github.com/firebase/firebase-js-sdk/issues/1881) works, however that doesn't change the fact that auth is fundamentally broken on web and only works due to a workaround.

**Comment by hsubox76** [comment]
There is a large auth rewrite in progress, converting from Closure to Typescript, which should address this when complete.

**Comment by 619** [comment]
Thank you, looking forward to it!
