### ISSUE TITLE
Getting error while trying to install firebase using npm in windows 10

### ISSUE THREAD

**Issue by meghsohor** [firebase/firebase-js-sdk#3950]
`npm ERR! Unexpected end of JSON input while parsing near '...":{"@firebase/app":"0'`

  * Operating System version: Windows 10

**Comment by hsubox76** [comment]
In past reported issues like this, the problem has been solved by doing a fresh install or there has been an issue with npm.

For the clean install: Can you delete node_modules and reinstall? If that doesn't work, can you also delete your lock file (package-lock.json or yarn.lock) before reinstalling.

For npm issues: (1) Make sure you're using an updated version of npm, (2) try different versions of Node, (3) there may be a temporary issue with the npm service, so try again after some time.

Also see https://github.com/firebase/firebase-js-sdk/issues/3806

**Comment by meghsohor** [comment]
Thank you @hsubox76 , I did follow your instruction. Unfortunately, it was not working. But then, I tried Yarn and it worked.
