### ISSUE TITLE
Performance monitoring murders performance.

### ISSUE THREAD

**Issue by jwalton** [firebase/firebase-js-sdk#3969]
### Describe your environment

  * Operating System version: MacOS 10.15.6
  * Browser version: Chrome 86
  * Firebase SDK version: 7.20.0
  * Firebase Product: Performance Monitoring

#### Steps to reproduce:

I've just tried enabling firebase performance monitoring, and I notice that firebase periodically blocks the event thread for between 0.3 and 1.0 seconds, repeatedly calling `createUserTimingTrace()`:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/1771003/96644250-c4ec3000-12f6-11eb-866f-56cf29815a5b.png">

The top level of that flame chart is [this anonymous function in `setupObserver()`](https://github.com/firebase/firebase-js-sdk/blob/cb1caa0e3de4f17d7c35ff7a2bbbe2d7beb7494c/packages-exp/performance-exp/src/services/api_service.ts#L141-L146).  If I dig down into `createUserTimingTrace()` I see it's logging a lot of stuff about our various react components.

#### Relevant Code:

This is what I added to my app:

```javascript
firebase.performance();
```

**Comment by raymondlam** [comment]
Hi @jwalton,

Firebase Performance uses the [User Timing api](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) under the hood.  It also allows users to use it directly so you can start logging performance traces even before the Firebase Performance sdk is loaded. See [Custom code traces](https://firebase.google.com/docs/perf-mon/custom-code-traces?platform=web#user-timing-api) for more details. This means that anytime the User Timing api is used, Firebase Performance also picks up the performance log.

React seems to be using the User Timing api extensively during development. However, based on their [documentation](https://reactjs.org/docs/profiler.html), it is disabled by default in production builds.  That is why you may see a lot of events being logged by Firebase Performance.

On a side note: Firebase Performance runs in [separate tasks for logging](https://github.com/firebase/firebase-js-sdk/blob/602ec18e92fd365a3a6432ff3a5f6a31013eb1f5/packages/performance/src/services/perf_logger.ts#L149), so it will not block the main thread. This [article](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) has more info on tasks.

**Comment by jwalton** [comment]
Ahh!  Probably won't be a problem in production then. Thanks!
