### ISSUE TITLE
SDK not Reconnecting to Real time database when network is changed in React Native app.

### ISSUE THREAD

**Issue by chris-dev07** [firebase/firebase-js-sdk#3972]
Library version--> "firebase": "^7.24.0",

//Method for presence
checkFirebasePresence = () => {
            var connectedRef = firebase.database().ref(".info/connected");
            connectedRef.on("value", (snap) => {
            console.log('fb-connected-', snap.val())
        });
    }

I used above method to check the user presence. 

My scenario is :
1. Run the app  RTDB(Real time database) is working fine, getting 'true' value in checkFirebasePresence() method, also able to send and receive messages.
2. Change the Internet network or turn off then on the internet I got 'false' value in checkFirebasePresence() method (mentioned above).
3. When the internet got back the value in checkFirebasePresence() doesn't change to true.
4. Only way to run the RTDB again is to reinstall the app.

Please help, Thank you in advance!!

**Comment by schmidt-sebastian** [comment]
@chris-dev07 Sorry to hear about your troubles. Do you mind enabling debug logging, which will show us what is happening with the network. You can able debug logging by invoking `firebase.database.enableLogging(true)`;
