### ISSUE TITLE
runTransaction after clearFirestoreData fails

### ISSUE THREAD

**Issue by lovebug356** [firebase/firebase-js-sdk#3977]
### [REQUIRED] Describe your environment

  * Operating System version: Archlinux
  * Browser version: Chrome
  * Firebase SDK version: git
  * Firebase Product: rules-unit-testing

### [REQUIRED] Describe the problem

When clearFirestoreData is called, runTransaction does not work anymore.

#### Steps to reproduce:

When I add the following test case, it fails. I would expect that I can use a transaction after clearFirestoreData.

https://github.com/lovebug356/firebase-js-sdk/commit/9b6b0b39dc9ace122897dd2bd3bfb6804e6d14f6

```
 it('should allow transaction after clearFirestoreData', async function() {
    await firebase.clearFirestoreData({
      projectId: 'foo'
    })
    const app = firebase.initializeTestApp({
      projectId: 'foo',
    });

    const doc = app.firestore().doc('test/test');
    await firebase.assertSucceeds(
      app.firestore().runTransaction(async (transaction) => {
        await transaction.get(doc);
      })
    );
  })
```

In the logs, 
` {"metadata":{"emulator":{"name":"firestore"},"message":"Oct 22, 2020 2:29:52 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError\nINFO: operation failed: the stored version (1603369765688732) does not match the required base version (0)\n"}}
[2020-10-22T12:29:54.916Z] Oct 22, 2020 2:29:54 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: the stored version (1603369765688732) does not match the required base version (0)
 {"metadata":{"emulator":{"name":"firestore"},"message":"Oct 22, 2020 2:29:54 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError\nINFO: operation failed: the stored version (1603369765688732) does not match the required base version (0)\n"}}
[2020-10-22T12:29:55.003Z] Oct 22, 2020 2:29:55 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: the stored version (1603369765688732) does not match the required base version (0)
 {"metadata":{"emulator":{"name":"firestore"},"message":"Oct 22, 2020 2:29:55 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError\nINFO: operation failed: the stored version (1603369765688732) does not match the required base version (0)\n"}}
`

**Comment by schmidt-sebastian** [comment]
@lovebug356 Thanks for filing this. The error message you are seeing is actually from the Emulator. The code snippet you provided should work, so I would be interested in your client logs. These logs will contain all communication with the emulator. 

You can able logging by invoking `firebase.firestore.setLogLevel('debug')`.

Thank you for your help!
