### ISSUE TITLE
Message from facebook requiring token for user photos

### ISSUE THREAD

**Issue by borgen12** [firebase/firebase-js-sdk#3985]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.3
  * Browser version:chrome 86.0.4240.75
  * Firebase SDK version: 7.8.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

My project is using firebase auth to enable facebook sign-in/sign-up and we recently received this alert from facebook:

"You need to generate a client or app token to access user pictures starting October 23, 2020 @ 10AM PDT.
As part of Graph API v8.0, we've made changes to our token requirements. These changes will impact your app, ****"

I have looked for ways to implement/get a token through our code (we are using the signInWIthRedirect method), but there doesn't seem to be any immediate opportunities to do so and I'm wondering if firebase already takes care of this natively?

#### Steps to reproduce:
Not really a re-producible error.

#### Relevant Code:

```
const loginWithFacebook = () => {
    // token and error commands: https://firebase.google.com/docs/auth/web/facebook-login
    const provider = new firebase.auth.FacebookAuthProvider();
    signInRedirect(provider);
}

const signInRedirect = (provider: any) => {
    firebaseAuth.signInWithRedirect(provider);
    firebaseAuth.getRedirectResult().then(function (result) {
    }).catch(function (error) {
        const errorMessage = error.message;
        alert(errorMessage);
    });
}
const listenUserAuth = (updateUser: (user: firebase.User | null) => void): void => {
    firebaseAuth.onAuthStateChanged((authUser) => {
        if (authUser) {
            updateUser(authUser);
        } else {
            updateUser(null);
        }
    });
}

**Comment by zachu90** [comment]
Is there an update on this? I also need to make this change in order to login with facebook and fetch user profile picture

**Comment by borgen12** [comment]
I just checked today and it still works fine for us. Now that we are a few days past the deadline facebook stated, I guess it turns out that firebase auth takes care of this already and facebook alerts are just infuriatingly broad.

**Comment by rosalyntan** [comment]
Hi @borgen12, thanks for filing this issue! You can obtain a Facebook access token in `getRedirectResult`. Our docs have an example of this: https://firebase.google.com/docs/auth/web/facebook-login#redirect-mode
