### ISSUE TITLE
FR: Support fast local cache resolution for documents indexed by primary key

### ISSUE THREAD

**Issue by burtonator** [firebase/firebase-js-sdk#3993]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS catalina
  * Browser version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
  * Firebase SDK version: 7.24.0
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

The Firestore local cache is very very slow at resolving cache objects when there is a lot of data.

More here:

https://github.com/firebase/firebase-js-sdk/issues/2591

A lot of our queries are collection + primary key 

For collections and static index lookups a simple key could be computed.

especially for collection(foo).doc('1010') lookups.

I think this should/could take you guys just a few hours to implement.

I'd bet that 50-70% of Firestore queries would fall into this category which would yield a big performance improvement.

It might also be nice to allow the *user* to specify a cache key so that this data is resolved from that key.

Without this we are going to implement our own workaround but that sort of defeats about 50% of the reason we're using Firestore.  We're expecting you guys to do the heavy lifting here and we shouldn't have to work around bugs like this ideally.

We have one simple query that reads user prefs by primary key.  The pk is the uid.  The data is less than 1k.

This takes 3 seconds to resolve.  That's really bad considering it's easy to build a cache key for this data.

We're pretty happy with Firestore other than this but this is a big issue for us.

**Comment by burtonator** [comment]
Another idea I had... maybe the cache cold be sped up by using namespaces where subsets of your cache formed a namespace.

the downside is that you would not be able to read something if it's in another cache namespace but at least it would segmented

**Comment by schmidt-sebastian** [comment]
@burtonator Thanks for filing this. We are already optimizing our query processing for these kind of lookups (see https://github.com/firebase/firebase-js-sdk/blob/fee4e8bb7e576daeff80bde515bda1288546791e/packages/firestore/src/local/local_documents_view.ts#L165). 

The processing here may be delayed because other items in our worker queue are executed beforehand. Do you think that might be the case? Firestore currently executes all cache-based operations sequentially and a query that is expensive to compute will delay all other operations. 

We may also need debug logs if you cannot find an obvious culprit.

**Comment by burtonator** [comment]
@schmidt-sebastian thanks. I didn't see your comments before. I'm going to try to fix my email settings.

So I think that what you're saying is that document snapshots are probably fast BUT if they're competing with other slow queries the performance will be slow.

I think this is what we're probably seeing.  The store we have is somewhat large.  About 100-200MB and Firestore is super slow when dealing with the local store.
