### ISSUE TITLE
[Messaging] onNewToken support

### ISSUE THREAD

**Issue by shtoffeine** [firebase/firebase-js-sdk#3994]
### [REQUIRED] Describe your environment

  * Operating System version: Any
  * Browser version: Any
  * Firebase SDK version: Latest
  * Firebase Product: messaging, cloud-messaging

### [REQUIRED] Describe the problem

Are there any plans for support [onNewToken()](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService#onNewToken(java.lang.String)) method?

Method [onRefreshToken](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#ontokenrefresh) is deprecated and need some feature to understand that token has been updated and it should be sent on the application backend tokens store.

Also, as I understand, Firebase doesn't attach modified tokens now when backend sends notifications to invalid/expired tokens via `sendMulticast`. How to have up-to-date tokens always?

**Comment by zwu52** [comment]
Hello @shtoffeine ,
Thanks for reaching out. Sadly [onRefreshToken](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#ontokenrefresh) was an no-op. In other words, no token rotation would be initiated from our backend. It's stable. 

So to have up-to-date tokens, you can:
- call getToken if your app doesn't have a token and update to server. 
- remove outdated token them when you send messages (check for the success/fail response)
