### ISSUE TITLE
Storage: TypeError thrown when UploadTask#on observer is missing some methods

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-js-sdk#40]
### [REQUIRED] Describe your environment

  * Operating System version: Linux & Windows 10
  * Firebase SDK version: 4.1.1
  * Firebase Product: storage

### [REQUIRED] Describe the problem
[According to the documentation](https://firebase.google.com/docs/reference/js/firebase.storage.UploadTask#on), the `nextOrObserver` parameter for the `firebase.storage.UploadTask#on` method should accept an observer with only **some** of the methods: `next`, `complete`, and `error`.

That means this should be allowed:
```ts
uploadTask.on(TaskEvent.STATE_CHANGED, {
  next: (snapshot) => { console.log(snapshot); },
  error: (err) => { console.error(err); }
});
```

This, though, raises the following error: `TypeError: Cannot read property 'bind' of undefined` since `observer.complete` is `undefined`. Relevant code [here](https://github.com/firebase/firebase-js-sdk/blob/c054dab68ce4d30af7fcb0bb850f1a064ba023c5/src/storage/task.ts#L570).

Currently, the only workaround besides providing an actual method is this:
```ts
uploadTask.on(TaskEvent.STATE_CHANGED, {
  next: (snapshot) => { console.log(snapshot); },
  error: (err) => { console.error(err); },
  complete: null
});
```

#### Steps to reproduce:
See JS Bin link below.

#### Relevant Code:
http://jsbin.com/yujaraboma/1/edit?js,console

**Comment by jsayol** [comment]
PR merged, closing!

**Comment by mokupindia** [comment]
Looks this is still a issue - i am getting this > Cannot read property 'snapshot' of undefined
    at Observer.complete
