### ISSUE TITLE
no changelog for 8 version

### ISSUE THREAD

**Issue by saiqulhaq** [firebase/firebase-js-sdk#4005]
I am using 7 version
but worry to upgrade it
because no changelog
any breaking changes?

**Comment by Feiyang1** [comment]
You can find our official release notes [here](https://firebase.google.com/support/release-notes/js).

**Comment by Feiyang1** [comment]
I will add a link to our README, so it's easier to find it going forward.

**Comment by dimitropoulos** [comment]
note: https://github.com/firebase/firebase-js-sdk/pull/4009
