### ISSUE TITLE
[firebase_auth]: Error code 'user-not-found' missing from 'reauthenticatewithcredential'

### ISSUE THREAD

**Issue by helenaford** [firebase/firebase-js-sdk#4015]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.15.6
  * Browser version: Chrome 86.0.4240.111
  * Firebase SDK version: 7.5.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
[reauthenticateWithCredential](https://firebase.google.com/docs/reference/js/firebase.User#reauthenticatewithcredential) throws an error with code `user-mismatch` instead of `user-not-found`.

#### Steps to reproduce:
Call `reauthenticateWithCredential()` with credentials that doesn't match an existing user

#### Relevant Code:
[`fireauth.AuthCredential.verifyTokenResponseUid`](https://github.com/firebase/firebase-js-sdk/blob/3f6f5e4912a044664b8746a727ecd75429344dc9/packages/auth/src/authcredential.js#L136) 

In the `.thenCatch` the `USER_DELETED` is translated to `USER_MISMATCH`
```js
fireauth.AuthCredential.verifyTokenResponseUid =
    function(idTokenResolver, uid) {
  return idTokenResolver.then(function(response) {
   // ..
  })
  .thenCatch(function(error) {
    // Translate auth/user-not-found error directly to auth/user-mismatch.
    throw fireauth.AuthError.translateError(
        error,
        fireauth.authenum.Error.USER_DELETED,
        fireauth.authenum.Error.USER_MISMATCH);
  });
};
```

#### Code to reproduce:
```javascript
    await firebase.auth().signInWithEmailAndPassword('foo@bar.com', '1234');
    var user = firebase.auth().currentUser;

    var credential = firebase.auth.EmailAuthProvider.credential( 'userdoesnotexist@foobar.com', 'password123');
    await user.reauthenticateWithCredential(credential);
```

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out!

This is working as intended; the rationale is that when calling one of the `reauthenticate*` methods, barring other errors (like a network error), there are two outcomes: either the user is reauthenticated, or the wrong account was chosen. I think the idea really is that with reauth, you're already signed in, so the relevant information for the user isn't that the account they used to reauth was deleted or missing, it's that they chose the wrong account in the first place.

**Comment by helenaford** [comment]
Hey no problem. I can see what you mean about it being 'reauth'. But, the docs should be updated in that case. Also, it would be nice if the behaviour was the same on all platforms (iOS & Android). I think that's the confusing bit, to throw different error codes based on platforms.

**Comment by samhorlbeck** [comment]
That's a good point. I'm only really familiar with the web SDK so I wasn't aware how it worked in the other SDKs :) 

I've filed an internal bug to track this (b/172337512) for both documentation and consistency across the SDKs. Thanks for pointing that out!
