### ISSUE TITLE
Admin SDK orderByChild().equalTo sometimes returns null

### ISSUE THREAD

**Issue by deremer** [firebase/firebase-js-sdk#402]
Originally raised on SO at: https://stackoverflow.com/questions/47931563/admin-sdk-orderbychild-equalto-sometimes-returns-null

We have a fixed list of data where each item in the list has a display_date in a format like this...

![image](https://user-images.githubusercontent.com/772290/34390100-8ef6cbe2-eb0b-11e7-8ba1-c5f3111523d8.png)

We run a query to retrieve results that have a display_date equal to the date string we are looking for.

Using typescript and the Firebase Admin node.js SDK, the code looks like this:

```
let trivia = (await admin.database().ref('trivia/GLOBAL')
  .orderByChild('display_date')
  .equalTo(triviaDate)
  .once('value')).val()

if (isNil(trivia)) {
  throw new NotFoundError(`No trivia questions found for ${triviaDate}`)
} else {
  return trivia;
}
```
(Note that isNil() is from lodash.)

The weird part is that for 1000's of runs this works perfectly. But for a very small fraction, it throws the NotFoundError. We have confirmed that the value of triviaDate is correct and there should be results. It's as if the first 'value' returned is null sometimes and in an inconsistent way.

As an update to the SO post, we added a check where if the first time it returns null we attempt to do it again before throwing the error indicating we have null. And, we are still seeing it return null the second time. In fact, it has happened 59 times in the last 24 hours, and we have had 49k+ invocations of the cloud function that executes this code. That means it's happening 0.12% of the time. Very small, but I'd expect a range query on a db to _always_ return the same result.

Any ideas?

**Comment by mikelehen** [comment]
Hard to say.  I'd be curious if you're doing any other operations at the same time, in particular reading or writing data in a path related to your query.

If you can enable logging with `firebase.database.enableLogging(true)` and capture tho log output, it might shed some light, in particular verify whether the server is sending correct results or not.

**Comment by deremer** [comment]
Just wanted to update this that we've updated all of our Google Cloud and Firebase dependencies to the latest version and it is still happening.

We modified the code to attempt to requery if the result was null but it is still happening...

```
let triviaQuery = admin.database().ref('trivia/GLOBAL')
    .orderByChild('display_date')
    .equalTo(triviaDate)
    .once('value');

  let trivia = (await triviaQuery).val()

  if (isNil(trivia)) {
    // Retry b/c of occassional null result
    console.log(`No trivia questions found for ${triviaDate}, retrying query...`);
    trivia = (await triviaQuery).val();
    if (isNil(trivia)) {
      throw new TriviaNotFoundError(`No trivia questions found for ${triviaDate} - ${trivia}`)
    } else {
      return trivia;
    }
  }
```

What's weird is that this only happening on a very small percentage of invocations. 

We haven't tried enableLogging(true) yet. We are using the `firebase-admin` library, so any tips of how to enableLogging with that library? I assume just `admin.database.enableLogging(true);` will that write to the FB Functions / Stackdriver logs? Also, I'm only interested in logging this one section of code, so can I enable it just before the query and then disable it immediately after without broader effect?

**Comment by deremer** [comment]
Actually I found this happening on a totally different firebase project as well. This time with a `startAt(x)`. I'm wondering if this is somehow related to the number of concurrent queries. In this particular case ~1000 cloud functions were fired off all that were making similar range queries to the same node.

**Comment by mikelehen** [comment]
You can pass a function to enableLogging() which would let you capture log messages and then once you hit the error condition, send the (last N) logs to some useful place (stackdriver or even just write it into the DB or something).

You can probably use this code as a guide, though it needs to be changed to use admin.database.enableLogging() instead of Firebase.enableLogging(): https://github.com/mikelehen/firebase-rolling-log/blob/master/index.js

**Comment by Beslinda** [comment]
I have the same issue `this.ref.orderByChild('UserID').equalTo(this.id.toString()` returns null

**Comment by vaske** [comment]
I have opposite problem with `orderByChild().startAt` which always return all records and `orderByChild().equalTo` return matching one...

**Comment by mikelehen** [comment]
In order to make this issue actionable we need a concrete repro that demonstrates the problem and/or log output (from `admin.database.enableLogging()`) so we can verify the query sent to the backend and the results received.  Thanks!

**Comment by vaske** [comment]
@mikelehen I sorted out it by combining `startAt ` and `endAt`

sample code

```
databaseReference.orderByChild('text')
                 .startAt(queryText)
                 .endAt(queryText+"\uf8ff")
```
this way it works perfect  :)

in future would be awesome to have ability to do full text search

**Comment by mikelehen** [comment]
@vaske Ah, glad to hear it!  Yes, full-text-search would definitely be very nice. :-)  It's on our radar but is more likely to (eventually) happen for Firestore than Realtime Database at this point.  We'll see.

I'm going to go ahead and close this issue since I don't think it's tracking any actionable issue.  If folks run into issues, please open a new issue with full details and logs.  Thanks!
