### ISSUE TITLE
No auth in firebase/app ?

### ISSUE THREAD

**Issue by webplease** [firebase/firebase-js-sdk#4022]
Hi to all,

I upgrade my firebase package in my angular app to@angular/fire 6.0.4 and firebase 8.0.0.

Now I have an error here: 

import { auth } from 'firebase/app'
Module '"../../../node_modules/firebase"' has no exported member 'auth'

Why?

**Comment by Feiyang1** [comment]
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/4023.
