### ISSUE TITLE
Problem with AUTH in firebase/app

### ISSUE THREAD

**Issue by webplease** [firebase/firebase-js-sdk#4023]
Hi to all,

I upgrade my firebase package in my angular app to@angular/fire 6.0.4 and firebase 8.0.0.

Now I have an error here: 

import { auth } from 'firebase/app'
Module '"../../../node_modules/firebase"' has no exported member 'auth'

Why?

**Comment by leon** [comment]
According to the docs you cannot import this way any more.
It is only possible to get auth from the default export.

```ts
import firebase from 'firebase/app

// then use the full path to get the auth service.
firebase.auth.
```

I don't like this, but it seems like this is the way forward.

**Comment by hsubox76** [comment]
Is it common to import Firebase objects directly when using angularfire? I thought it was accessed through angularfire wrappers like: https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md

In any case, for users not using the Angularfire wrappers, I don't think we've ever advocated the first pattern. Recommended usage is something like:

```
import firebase from 'firebase/app';
import 'firebase/auth';

firebase.auth().signInWithEmailAndPassword(...) // or whatever auth method/property you need
```

**Comment by webplease** [comment]
right, I solved importing in this way:

import auth from 'firebase/firebase-auth'

Thanks!

**Comment by 74nguyentan** [comment]
install 
 "firebase": "^7.21.0",
