### ISSUE TITLE
Can't Login with email & password created from google console

### ISSUE THREAD

**Issue by mosamuhana** [firebase/firebase-js-sdk#4029]
### My environment

  * Operating System version: Windows
  * Browser version: Google Chrome v86
  * Firebase SDK version: 8.0.0
  * Firebase Product: auth

### The problem

Hello

I have two apps
- Mobile App with Flutter using FlutterFire plugins.
- Web App with Angular using AngularFire.

I have created in the firebase project two apps one for android and one for web

Using firebase auth with same firebase project
I can signup and signin for both apps

But the problem is:
If account created with flutter app -> can not login with web app.
If account created with web app -> can not login with flutter app.
Also if account created from firebase console -> can not login in flutter.

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out!

What particular error is being thrown when the logins fail?

**Comment by mosamuhana** [comment]
Gives me FirebaseAuthException with
code: wrong-password
message: The password is invalid or the user does not have a password.

But I can login in web with same email and password

I said before that:
If account created with flutter app -> can not login with web app.
If account created with web app -> can not login with flutter app.

**Comment by malcolmdeck** [comment]
This sounds like you have two separate projects and your flutter app is using a different one than the one you're interacting with in the console. Can you please verify that the API key that the flutter app is using matches one associated with your target project?

**Comment by mosamuhana** [comment]
> This sounds like you have two separate projects and your flutter app is using a different one than the one you're interacting with in the console. Can you please verify that the API key that the flutter app is using matches one associated with your target project?
---

I have two projects one Flutter (Android), and the other Web (Angular)
both projects uses the same Firebase project.
both projects can SignUp and SignIn.
both projects creates user account in the same firebase project (Authentication/Users in firebase console).

**Comment by looptheloop88** [comment]
Hi @mosamuhana, just checking if you're still having issues with email and password authentication? If so, please provide any error logs and a [sample project](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally to replicate the issue.

You may also want to try updating the SDK version that you're using.
