### ISSUE TITLE
Missing kid when connecting to Realtime database emulator 

### ISSUE THREAD

**Issue by gamereat** [firebase/firebase-js-sdk#4041]
### [REQUIRED] Describe your environment

  * Operating System version:  Win 10
  * Browser version:  Chrome  86.0.4240.183 
  * Firebase SDK version: 8.0.1
  * Firebase Product: auth, database

#### Steps to reproduce:

I'm unable to access my emulators realtime database but is working as expected in production.

It appears to be failing to initialize correctly not all configs appear to be working as expected. 

1. Init Firebase 
2. Init Realtime Database
3. Call use Emulator for Database
4. attempt to call `once` on a database ref
5. Observe logs bellow 

relevant logs:
 `@firebase/database: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "apiKey" and "databaseURL" properties provided to initializeApp() match the values provided for your app at https://console.firebase.google.com/.`

From turning on database logging i'm also getting 
![image](https://user-images.githubusercontent.com/7132438/98296583-09d8bd80-1fab-11eb-9902-34f5cd58da22.png)

`Auth token revoked: invalid_token/missing 'kid' in header`

See bellow for relevant code snippets 

#### Relevant Code:

```javascript
    constructor() { 

       firebase.initializeApp(config);
        console.log(config)
        /* Config is outputting expect results
      apiKey: "xx"
    appId: "xx"
    authDomain: "xx.firebaseapp.com"
    databaseURL: "https://xx.firebaseio.com"
   measurementId: "G-xx"
   messagingSenderId: "xx"
    projectId: "xx" 
    storageBucket: "xxx"
   */
        this.analytics = firebase.analytics(); 
        this.db = firebase.database();
        firebase.database.enableLogging(true);
        this.storage = firebase.storage();
        this.auth = firebase.auth(); 
        this.functions = firebase.functions();

        // when a local env use the emulator endpoints
        if(process.env.NODE_ENV !== 'production'){
          this.auth.useEmulator('http://localhost:9099'); 
          this.db.useEmulator('localhost',9000); 

          this.functions.useEmulator("localhost",5001)
        }
    } 


```

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out. This issue should be addressed in the latest release of the emulator. See: https://github.com/firebase/firebase-tools/issues/2758
