### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by Prottoy2938** [firebase/firebase-js-sdk#4048]
### [REQUIRED] Describe your environment

  * Firebase SDK version: ^8.0.1
  * Firebase Product: all, (I suppose)

### Update Documentation

`firebase.initializeApp({...})` doesn't work, have to use `firebase.default.initializeApp({...})`

Update the npm documentation.

**Comment by hsubox76** [comment]
Thanks for letting us know. How are you importing Firebase (`require`, ESM imports, `<script>` tags?) and do the release notes here cover your use case?
https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020

**Comment by Prottoy2938** [comment]
ESM imports

Yes, they look good to me
