### ISSUE TITLE
Lint errors in version 4.81

### ISSUE THREAD

**Issue by chandanch** [firebase/firebase-js-sdk#405]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.8.1
  * Firebase Product: auth 

### [REQUIRED] Describe the problem

Lint errors for firebase 4.8.1 version:

1. 'stack' is declared but never used. *Source*: firebase/util/src/errors.ts, line: 93
2. 'key' is declared but never used. *Source*: firebase/util/src/obj.ts, line: 77
3. 'key' is declared but never used. *Source*: firebase/util/src/obj.ts, line: 85

**Comment by rommelpe** [comment]
Hi @chandanch, it looks like these lint errors didn't persist in the latest version.

If you're still interested working on this case and want to continue the discussion, just leave a comment here and we are happy to re-open this.Thanks.
