### ISSUE TITLE
Unable to see data in Analytics dashboards or log events to Firebase

### ISSUE THREAD

**Issue by 00111000** [firebase/firebase-js-sdk#4052]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: Version 86.0.4240.183 (Official Build) (x86_64)
  * Firebase SDK version: 8.0.1
  * Firebase Product: hosting, analytics

### [REQUIRED] Describe the problem

Not getting any data displayed in the dashboards even after running the up for more than 24 hours, tried sending an event manually and got the following error message in the console.

`@firebase/analytics: The measurement ID in the local Firebase config (G-xxx) does not match the measurement ID fetched from the server (G-yyy). To ensure analytics events are always sent to the correct Analytics property, update the measurement ID field in the local config or remove it from the local config.`

I am using the reserved Hosting URLs, so I do not have a config object locally.

#### Steps to reproduce:

```
<script src="/__/firebase/8.0.1/firebase-app.js"></script>
<script src="/__/firebase/8.0.1/firebase-analytics.js"></script>
<script src="/__/firebase/init.js"></script>

<script>
  firebase.analytics().logEvent('notification_received');
</script>
```

**Comment by hsubox76** [comment]
If you go to your project's settings in the Firebase console and look at the config snippet, and look at the measurementId in that config, does it match the first ID listed in the error message or the second?

**Comment by 00111000** [comment]
It matches the second id.

**Comment by hsubox76** [comment]
Can you check your DevTools network tab and look to see if a couple of REST calls are being made and what they say? The first should be a GET to:

```
https://www.googletagmanager.com/gtag/js?id=G-yyy&l=dataLayer&cx=c
```
where `G-yyy` is a measurement ID, and the second (may be delayed a few seconds after page loads) should be a POST to:
```
https://www.google-analytics.com/g/collect?...
```
with a lot of URL params, where one of the params should be `tid=G-yyy` where `G-yyy` is a measurement ID.

Are you seeing both of these network requests being sent, and is the measurementID there in both, and which measurementID is it?

**Comment by 00111000** [comment]
Hi, yes, I see the 2 calls being made, they both have the measurement ID that matches the one in the Firebase console. Actually, Analytics magically started to work (if I log an event), however, I have a new problem, if I do not log an event, then Analytics to not work, meaning that I must call `firebase.analytics().logEvent('some event');` in order to "activate" Analytics.

I checked and no GA cookies are set if no event is logged, is this normal behaviour? do I need to log some initial event?

**Comment by hsubox76** [comment]
You don't need to call `logEvent` but at some point you need to call `firebase.analytics()` (with or without any method like logEvent chained after it) to initialize it, does your code do that?

**Comment by 00111000** [comment]
oh, I wasn't aware that I had to call `firebase.analytics()` to init analytics. 
Anyways, it is all good now. Thank you!
