### ISSUE TITLE
Google auth fails in Chrome, only works in incognito window

### ISSUE THREAD

**Issue by nareshbhatia** [firebase/firebase-js-sdk#406]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.12.6
  * Firebase SDK version: 4.8.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
On Chrome, `signInWithRedirect()` is unable to log user in. The Google account selection popup comes up. User has multiple Google accounts, they select one, control returns to app - but user is not signed in with Google provider.

- This is happening only on one user's machine. We don't have access to that machine and we are unable to reproduce this on our machines.
- If user tries to log in using a Chrome incognito window OR Safari, they are able to log in. So the issue is specific to a normal Chrome window.

#### Steps to reproduce:
Unable to reproduce on our machines.

#### Relevant Code:

    signInWithProvider(provider) {
        return firebase.auth().signInWithRedirect(provider);
    }

**Comment by bojeil-google** [comment]
The data available is not enough to debug/recreate this issue.
