### ISSUE TITLE
Analytics data not showing up, "Ignored config command. Invalid arguments found."

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-js-sdk#4063]
### [REQUIRED] Describe your environment

Web app, ReactJS

  * Browser version: Tried safari newest and chrome newest
  * Firebase SDK version: Initially 7.23.0, then i upgraded to 8.0.1 to see if that would help (no it did not)
  * Firebase Product:  analytics

### [REQUIRED] Describe the problem

Go to firebase console, Analytics, DebugView.
Problem: No events show up there, and data doesn't show up in Google Analytics either. I have a v4 GA property. 
More data here: https://stackoverflow.com/questions/64809907/cant-get-firebase-webapps-data-to-arrive-at-google-analytics

**I do not use GTAG or any other analytics -- just firebase analytics**

#### Relevant Code:

Startup code: see https://stackoverflow.com/questions/64809907/cant-get-firebase-webapps-data-to-arrive-at-google-analytics ... essentially:
```javascript
export const app = firebase.initializeApp(config);
app.analytics().logEvent('firebase-init-client');
```

After installing the Google Analytics Debugger Chrome extension I see this:

![analytics-fail](https://user-images.githubusercontent.com/3776302/99008203-b539c300-2513-11eb-877b-859737e5efe8.png)

I'm guessing those errors are why no analytics are being reported?

**Comment by xaphod** [comment]
... a snippet from `package-lock.json` in case it helps:

```
   "@firebase/analytics": {
      "version": "0.6.2",
      "resolved": "https://registry.npmjs.org/@firebase/analytics/-/analytics-0.6.2.tgz",
      "integrity": "sha512-4Ceov+rPfOEPIdbjlpTim/wbcUUneIesHag4UOzvmFsRRXqbxLwQpyZQWEbTSriUeU8uTKj9yOW32hsskV9Klg==",
      "requires": {
        "@firebase/analytics-types": "0.4.0",
        "@firebase/component": "0.1.21",
        "@firebase/installations": "0.4.19",
        "@firebase/logger": "0.2.6",
        "@firebase/util": "0.3.4",
        "tslib": "^1.11.1"
      }
    },
    "@firebase/analytics-types": {
      "version": "0.4.0",
```

**Comment by xaphod** [comment]
... after moving startup logic around (just reordering things), I can get these errors to go away. 
SOME events show up in the DebugView then, but most do not: I assume that is because I am seeing a lot of this:

**sending event "screen_view" to undefined**

... which you see in my original screenshot (when the errors were present) too. Man this is messed up

**Comment by hsubox76** [comment]
In your network tab in devtools, can you look at network requests and see if there is a GET request to this endpoint:

`https://firebase.googleapis.com/v1alpha/projects/-/apps/[APP_ID]/webConfig`

(where [APP_ID] is your appId)

Is it there, was it successful, and what did it return? Thanks. (It should contain a JSON object with most of your Firebase config params, including measurementId. The second param to gtag config that is reading as "undefined" in your log would be the measurementId from that object. This indicates that JSON object is being returned without a measurementId field or something else is wrong with that GET request.)

**Comment by xaphod** [comment]
Hi Christina, apologies but I seem to have lost the repro for that error now -- not sure how or why!
I'm configuring firebase manually like this, does that matter?
```
const config = {
  apiKey: 'redacted',
  authDomain: 'redacted.firebaseapp.com',
  databaseURL: 'https://redacted.firebaseio.com',
  projectId: 'redacted',
  storageBucket: 'redacted.appspot.com',
  messagingSenderId: 'redacted',
  appId: '1:redacted',
  measurementId: 'G-redacted',
};

export const app = firebase.initializeApp(config);
app.analytics().logEvent('firebase-init-client');
```

**Comment by hsubox76** [comment]
No, it doesn't matter, unless your apiKey or appId are wrong. The newest versions of Firebase Analytics always try to fetch  measurementId from the dynamic config endpoint.

Does the network request to that endpoint look normal then? (as mentioned above)

If you're not getting any errors or warnings and are just not seeing events in the dashboard, try following the instructions in this comment to help debug and narrow down where the issue might be: https://github.com/firebase/firebase-js-sdk/issues/2600#issuecomment-623654673

**Comment by xaphod** [comment]
I don't think apiKey/appId are wrong because i'm using lots of other Firebase services without an issue (firestore, storage, and so on).
The network request looks ok: a 204.
I've discovered a major source of my confusion: the Firebase Analytics DebugView shows nothing, BUT if I go to Google Analytics realtime view, I *do* see data (https://analytics.google.com/analytics/web/#/<redacted>/realtime/overview) ... is that expected & ok?

**Comment by hsubox76** [comment]
Oh I didn't realize you were looking at only DebugView. I believe events only show up on DebugView if you set a special config param (usually enabled by using the Chrome extension you mentioned above). The standard place to view analytics in the Firebase console is Dashboard, which should contain a box similar to Google Analytics realtime view. (Right now it seems to be a solid blue box near the top that says "Users in last 30 minutes".)

In short, if you are using the Chrome extension it should be setting the param that enables events to be logged in DebugView, if you're not, nothing will go to DebugView, as DebugView is only meant for development and not for end user data.

All events, extension or not, should show up in the console under Analytics > Dashboard.

If some of our recent changes are breaking the Chrome extension somehow that's worth looking into, though, if you can narrow down what is happening and provide steps to repro.

**Comment by xaphod** [comment]
Ah ok thank you for the explanation! That makes it clear. I didn't realize
DebugView won't show anything _unless_ debugging is on...
IMO it'd be great if the DebugView page said that.
Thanks for your help, i'll let you know if I see these errors anymore...
