### ISSUE TITLE
Firestore: Failed to load (default)

### ISSUE THREAD

**Issue by hypernova7** [firebase/firebase-js-sdk#4066]
* Operating System: Windows 10 Pro
* Browser version: Firefox 82.0.3
* Firebase version: 8.0.1
* Firebase product: firestore

Firestore throws me the following console error from Firefox console:
> Failed to load 'https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?database=projects%2FXXXXX%2Fdatabases%2F(default)&gsessionid=XXXXXXXXXXXXXX&VER=8&RID=rpc&SID=XXXXXXXXXXXXXXXX&CI=0&AID=5&TYPE=xmlhttp&zx=XXXXXXXXXXXX&t=1'

This is my script:

~~~javascript
import firebase from 'firebase/app'
import 'firebase/firestore'
firebase
  .firestore()
  .settings({
    cacheSizeBytes: firebase.firestore.CACHE_SIZE_UNLIMITED
  });
firebase
  .firestore()
  .enablePersistence({
    synchronizeTabs: true
  });
~~~

My rules:
~~~
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
~~~

**Comment by wu-hui** [comment]
Hi @hypernova7 

I have failed to reproduce this on Firefox with Windows with your snippet. It worked as intended without the error you posted.

Are you in a restricted environment (corp network)? If so, can you switch to a less restricted environment and test again? If the problem persists, then I'll need to full reproduction from you to proceed.

Thanks.

**Comment by hypernova7** [comment]
This is my full configuration:

~~~javascript
import firebase from 'firebase/app';
import 'firebase/performance';
import 'firebase/firestore';
import 'firebase/analytics';
import 'firebase/storage';
import 'firebase/auth';

if (typeof firebase === 'undefined') throw new Error('Firebase SDK not detected.');
if (!firebase.apps.length) {
  firebase.initializeApp(process.env.FIREBASE_CONFIG);
}
firebase
  .firestore() 
  .settings({
    cacheSizeBytes: firebase.firestore.CACHE_SIZE_UNLIMITED
  });
firebase
  .firestore()
  .enablePersistence({
    synchronizeTabs: true
  });
export default firebase
~~~
The error that throws me is notified by the Service Worker using Workbox

**Comment by wu-hui** [comment]
I see. 

Does your app run from service worker?

Would you kindly provide a full mini-reproduction, as a npm package and share with us via github or just zip file? I am afraid that whatever I setup is going to have subtle differences that matter.

**Comment by wu-hui** [comment]
Also, does this problem only happen with Firefox?

**Comment by hypernova7** [comment]
> Also, does this problem only happen with Firefox?

No, it also happens with other browsers. Although at the moment I have only used Firefox and Chrome

**Comment by hypernova7** [comment]
> I see.
> 
> Does your app run from service worker?
> 
> Would you kindly provide a full mini-reproduction, as a npm package and share with us via github or just zip file? I am afraid that whatever I setup is going to have subtle differences that matter.

No, my application is not running from Service Worker. And I'm just using the basic `workbox-webpack-plugin` configuration with the ` GenerateSW` function.

**Comment by hypernova7** [comment]
This is muy webpack config:

```javascript
import { GenerateSW } from 'workbox-webpack-plugin'
module.exports = {
  entry: './src/firebase.js',
  output: {
    filename: 'js/[contenthash].js',
    chunkFilename: 'js/[contenthash].js',
    jsonpFunction: '___' + pkg.jsonpFunction,
    path: path.resolve(__dirname, 'public', 'assets'),
    publicPath: `${URL_PROJECT}/assets/`
  },
  plugins: [
    new GenerateSW({
      skipWaiting: true,
      clientsClaim: true,
      swDest: '../sw.js',
      directoryIndex: '/',
      navigationPreload: true,
      inlineWorkboxRuntime: true,
      cleanupOutdatedCaches: true,
      offlineGoogleAnalytics: true,
      cacheId: 'sw-js',
      maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      include: [/\.svg$/, /\.eot$/, /\.woff(2)?$/, /\.ttf$/, /\.html$/, /\.js$/, /\.css$/, /\.jpe?g$/, /\.png$/, /\.gif$/, /manifest.json$/],
      runtimeCaching: [{
        urlPattern: /\.(?:js|css)$/,
        handler: 'StaleWhileRevalidate',
        options: {
          cacheName: 'sw-static',
          expiration: {
            maxEntries: 10,
            maxAgeSeconds: 10 * 24 * 60 * 60
          }
        }
      }, {
        urlPattern: /\.(?:png|gif|svg|jpe?g)$/,
        handler: 'StaleWhileRevalidate',
        options: {
          cacheName: 'sw-dynamic',
          expiration: {
            maxEntries: 60,
            maxAgeSeconds: 24 * 30 * 60 * 60
          }
        }
      }, {
        urlPattern: /.*(?:googleapis|gstatic).com.*$/,
        handler: 'CacheFirst',
        options: {
          cacheName: 'sw-static',
          expiration: {
            maxEntries: 10,
            maxAgeSeconds: 90 * 24 * 60 * 6
          }
        }
      }, {
        urlPattern: /.*(?:segment|googletagmanager|google-analytics).com.*$/,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'sw-static',
          expiration: {
            maxEntries: 10,
            maxAgeSeconds: 90 * 24 * 60 * 6
          }
        }
      }]
    })
  ]
}
```
