### ISSUE TITLE
firestore.googleapis.com blocked by corporate firewall  

### ISSUE THREAD

**Issue by wiesson** [firebase/firebase-js-sdk#4067]
I'd like to reverse proxy firestore.googleapis.com through my own domain to avoid blocking by corporate firewalls. I can't find information, how to set the service URL and I'm wondering if this is supported at all.

```Typescript
function initializeApp(options: Object, name?: string): firebase.app.App;
``` 

I tried to derive the config from initializeApp, but it just takes an generic Object and the text does not mention something like a serviceUrl:

```Javascript
firebase.initializeApp({
  apiKey: "AIza....",                             // Auth / General Use
  appId: "1:27992087142:web:ce....",      // General Use
  projectId: "my-firebase-project",               // General Use
  authDomain: "YOUR_APP.firebaseapp.com",         // Auth with popup/redirect
  databaseURL: "https://YOUR_APP.firebaseio.com", // Realtime Database
  storageBucket: "YOUR_APP.appspot.com",          // Storage
  messagingSenderId: "123456789",                  // Cloud Messaging
  measurementId: "G-12345"                        // Analytics
});
```

The idea is that I setup and endpoint like `/api/v1/external/firestore` and reverse proxy the requests to `firestore.googleapis.com`

**Comment by wiesson** [comment]
It looks like I have found it:

```
firebase.firestore().settings({ host: "..." });
```

**Comment by jmeinke** [comment]
Thanks for this information!
