### ISSUE TITLE
Incorrect sorting behavior, first record always positioned at the end v8.0.2.

### ISSUE THREAD

**Issue by heliomarpm** [firebase/firebase-js-sdk#4071]
Hello, after upgrading from v7.24.0 to v8.0.2, all the compositions are showing incorrect behavior, the first record is always being returned in the last position.

`this.fireStore.doc(`Users/${this.userId}`)
          .collection<Card>('Cards', ref => ref.where('active', '==', true)
          .orderBy('order')
          .orderBy('createdAt', 'desc'));
`

**Example:**
{order: 1, condition2: 'AA' ...}
{order: 2, condition2: 'BB' ...}
{order: 3, condition2: 'AB' ...}
{order: 4, condition2: 'DD' ...}
{order: 3, condition2: 'AB' ...}

**Return:**
{order: 2, condition2: 'BB' ...}
{order: 3, condition2: 'AB' ...}
{order: 3, condition2: 'AB' ...}
{order: 4, condition2: 'DD' ...}
_{order: 1, condition2: 'AA' ...}_

**Comment by atlesj** [comment]
Saw similar behavior going from 8.0.1 to 8.0.2, in addition to problems propagating updates in my angular app... Downgrading to 8.0.1 fixes the problem...

**Comment by heliomarpm** [comment]
> Saw similar behavior going from 8.0.1 to 8.0.2, in addition to problems propagating updates in my angular app... Downgrading to 8.0.1 fixes the problem...

I am working with ionic 5 + angular. I also had a propagation problem in version 8.0.2, my solution was to go back to 8.0.0.

**Comment by wu-hui** [comment]
I believe the issue is from angularfire, filed a issue there: https://github.com/angular/angularfire/issues/2657

**Comment by jamesdaniels** [comment]
If it is AngularFire it's not 2657. As developers are reporting that they started encountering it with 8.0.2 IMO it's probably the JS SDK.

**Comment by wu-hui** [comment]
@jamesdaniels Thanks!

@heliomarpm I tried reproduce with angularfire and could not reproduce. Can you kindly provide a mini repro? This would greatly help me identifying the root cause quicker.

**Comment by schmidt-sebastian** [comment]
This looks like https://github.com/firebase/firebase-js-sdk/issues/4079

@jamesdaniels Does AngularFire use `oldIndex` or `newIndex` from `DocumentChange`?

**Comment by jamesdaniels** [comment]
@schmidt-sebastian AngularFire and RxFire use both old/newIndex: [AngularFire `combineChange`](https://github.com/angular/angularfire/blob/c57cef4a0d08f7df43754a30c18d707d1806cbd0/src/firestore/collection/changes.ts#L50), [RxFire `processIndividualChange `](https://github.com/firebase/firebase-js-sdk/blob/6a154eb131b6459213de02e0f0c573d4436a77fb/packages/rxfire/firestore/collection/index.ts#L78)
