### ISSUE TITLE
DocumentChange.newIndex equals -1 for 'added' events

### ISSUE THREAD

**Issue by MieleVL** [firebase/firebase-js-sdk#4079]
* Operating System version: Windows 10
  * Browser version: Chrome (latest)
  * Firebase SDK version: 8.0.2
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
DocumentChange.newIndex === -1 for 'added' events. According to the documentation, this should only be the case for 'removed' events: https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentChange#newindex

#### Steps to reproduce:
Create a query snapshot listener. When the callback is triggered for the first time, change.newIndex is always -1.

#### Relevant Code:
```javascript
db.collection("cities").docChanges().forEach(change => {
  if (change.oldIndex === -1) {
    // Should only be true for added documents.
    // change.newIndex also equals -1, which should not be the case imo. Should be >= 0.
  }

  if (change.newIndex === -1) {
    // Should only be true for removed documents.
    // Currently also true for added documents.
  }
});
```

**Comment by schmidt-sebastian** [comment]
@MieleVL Thanks for filing this. We have been changing the internals of our SDK and it looks like this might be a regression. We will try to get this fixed as soon as possible.
