### ISSUE TITLE
Meaningless return statements

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-js-sdk#408]
Hi,

I’ve noticed a meaningless return statement like this:
```ts
async () => {
  return Promise.resolve()
}
```

I’d like to create a PR to remove this statement, but you’ve asked in CONTRIBUTING.md to create an issue first. So here I am :)

**Comment by jshcrowthe** [comment]
Hey @merlinnot 😄 

Thanks for reading the `CONTRIBUTING.md` if you can point to the specific issue(s) then let's talk!

**Comment by merlinnot** [comment]
Here you go:

https://github.com/firebase/firebase-js-sdk/blob/1a1bd233b0f459932f8f970836fb7ec2c13d1ee5/packages/firestore/test/integration/api/database.test.ts#L678

**Comment by jshcrowthe** [comment]
Feel free to submit a PR. I'll leave it to those closer to the code to discuss if there are any issues.
