### ISSUE TITLE
The onSnapshot listener on error callback is not being called when there is an issue connecting and persistence is disabled

### ISSUE THREAD

**Issue by akeshk** [firebase/firebase-js-sdk#4089]
### [REQUIRED] Describe your environment

  * Operating System version: __macOS 10.15.7___
  * Browser version: _Chrome Version 86.0.4240.198____
  * Firebase SDK version: _8.0.2____
  * Firebase Product: __firestore___ 

On the snapshot listener for a document ref when there is trouble connecting and an error appears in the console the onError callback is not called even-though persistence is disabled and it shouldn't be using the cache. 

#### Steps to reproduce:
One way to reproduce is disable the calls to firestore.googleapis* so that the listener is unable to connect and call the onsnapshot listener on a document ref , persistence should be disabled by default for web.

Should see an error similar to this in the console logs 
![image](https://user-images.githubusercontent.com/16065212/99543893-b2125d00-2981-11eb-9cfe-509cba4c1b9f.png)

#### Relevant Code:

```javascript
eventChannel(emit => {
        const db = firebase.firestore(getFirebaseApp())
        const ref = db.collection(path).doc(name)
        return ref.onSnapshot(
            { includeMetadataChanges: true },
            document => emit({ document, snapshotTimestamp: Date.now() }),
            error => emit({ error, snapshotTimestamp: Date.now() }),
        )
})
```

**Comment by thebrianchen** [comment]
@akeshk Thanks for filing an issue with a reproduction!

Firestore only raises offline errors when you directly attempt to get a document. The `onSnapshot()`'s `onError()` handler does not surface offline errors, but raises an initial snapshot that you can use to see if Firestore is offline. If the `fromCache` property on the `SnapshotMetadata` in your snapshot event is set to `true`, then the app is in an offline state.

**Comment by thebrianchen** [comment]
I'm going to mark this issue as closed, but feel free to comment if you have any other questions.
