### ISSUE TITLE
Dynamically importing `firebase/analytics` doesn’t populate namespace

### ISSUE THREAD

**Issue by jamesdaniels** [firebase/firebase-js-sdk#4109]
If you dynamically import `firebase/analytics` the `firebase.analytics` namespace isn't populated, so settings cannot be modified and `isSupported` can't be called.

```ts
import firebase from `firebase/app`;

import('firebase/analytics').then(() => {
   // both error
   firebase.analytics.isSupported();
   firebase.analytics.settings({
      dataLayerName: 'myDataLayer',
      gtagName: 'myGtagFn'
   });
   // this works fine though
   firebase.analytics();
});
```

Expectation would be that the namespace would be populated per the reference guide https://firebase.google.com/docs/reference/js/firebase.analytics#functions

**Comment by hsubox76** [comment]
I haven't been able to reproduce, this is the full file I used, got no errors:

```
import firebase from 'firebase/app';

firebase.initializeApp(/* config */);

import('firebase/analytics').then(() => {
    // both error
     firebase.analytics.isSupported();
    firebase.analytics.settings({
           dataLayerName: 'myDataLayer',
       gtagName: 'myGtagFn'
     });
 });
```

I got an error copying the exact file you used but it was an "app hasn't been initialized" error and I assume you have the initialization in your actual code or `firebase.analytics()` wouldn't have worked either.

I just used a single js file with a standard webpack build and `@babel/preset-env`.

**Comment by jamesdaniels** [comment]
Interesting, I'm running into this in Angular. Let me dig in a bit more.

**Comment by jamesdaniels** [comment]
Sorry it turns out my firebase peer was still 7 & those APIs were introduced with 8.
