### ISSUE TITLE
analytics throws invalid domain error from firebase hosting channels

### ISSUE THREAD

**Issue by zanona** [firebase/firebase-js-sdk#4123]
### [REQUIRED] Describe your environment

  * Operating System version: linux
  * Browser version: firefox 81
  * Firebase SDK version: 8.1.1
  * Firebase Product: analytics

#### Steps to reproduce:

when calling `firebase.analyitcs()` from within a hosting channel domain .ie: _(my-project--alpha-1234.web.app)_ Google Analytics will throw the following warning, resulting on the GA cookie not being stored :

    Cookie “_ga” has been rejected for invalid domain.

This is thrown directly by `https://www.googletagmanager.com/gtag/js` and since it tries to assign the domain of `wep.app` for the cookie instead of the whole hostname of `my-project--alpha-1234.web.app`.

In a standard installation, this could be prevented by setting the following `gtag` options. _(taken from https://stackoverflow.com/a/62569420/165750, see the *update* section)_;

```js
window.dataLayer = window.dataLayer || [];
window.gtag = function(){dataLayer.push(arguments);}

window.gtag("config", "GA_MEASUREMENT_ID", {
	cookie_domain: location.hostname,
	cookie_flags: "SameSite=None;Secure",
});

```

Therefore, the only way to workaround this at the moment is to add the above snippet before `firebase.analytics() ` is called, like so:

```js
window.dataLayer = window.dataLayer || [];
window.gtag = function(){dataLayer.push(arguments);}

window.gtag("config", firebaseConfig.measurementId, {
	cookie_domain: location.hostname,
	cookie_flags: "SameSite=None;Secure",
});
firebase.initializeApp(firebaseConfig);
firebase.analytics();
```

#### Expected behaviour

I would like to have the `location.hostname` automatic setup when running `firebase.analytics()` or having a way to define that myself.

**Comment by MatthewFallon** [comment]
I am also currently using the above fix only slightly edited to work within a create-react-app context. (specifically to fix the cookie flags issue.)  Would love to hear about a fix for this being implemented directly into the analytics library by default. :+1: 

```js
window.dataLayer = window.dataLayer || [];
window.gtag = function(){window.dataLayer.push(arguments);}

window.gtag("config", firebaseConfig.measurementId, {
	cookie_domain: window.location.hostname,
	cookie_flags: "SameSite=None;Secure",
});
// Initialize Firebase
export const firebaseApp = initializeApp(firebaseConfig);
export const analytics = getAnalytics(firebaseApp);
```

**Comment by hsubox76** [comment]
Sorry I didn't see this in the backlog. In v9, you can add an argument to `initializeAnalytics()` where you can set initial gtag config properties. Reference: https://firebase.google.com/docs/reference/js/analytics.md#initializeanalytics (see AnalyticsSettings).

So you can do
```
export const firebaseApp = initializeApp(firebaseConfig);
export const analytics = initializeAnalytics(firebaseApp, {
  config: {
    cookie_domain: window.location.hostname,
    cookie_flags: "SameSite=None;Secure"
  }
});
```
