### ISSUE TITLE
Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "FieldValue$1" (found in field "date"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).

### ISSUE THREAD

**Issue by ScottPierce** [firebase/firebase-js-sdk#4129]
### [REQUIRED] Describe your environment

  * Operating System version: OSX
  * Browser version: N/A - Running Tests
  * Firebase SDK version:
```
        "firebase": "^8.1.1",
        "firebase-admin": "^9.4.1",
        "firebase-functions": "^3.11.0",
        "@firebase/rules-unit-testing": "^1.1.3",
```
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

I recently upgraded firebase versions so that I could use the emulators as per the documentation with the `useEmulator` functions. I'm now seeing massive failures for tests. For each collection of data in the app, I have a `Service` object responsible for interacting with it. I pass a `Firestore` instance into them. Sometimes for running tests, I want to ensure that I properly interact with the data in consistent ways, so I pass a `Firestore` instance from the admin sdk into the `Service`. It works really well.

Ever since upgrading though, I'm seeing an error in several of our tests:
```
Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "FieldValue$1" (found in field "date"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
```

This is coming because it has a problem with the use of `FieldValue.serverTimestamp()`. The admin sdk doesn't like when I use the non admin `FieldValue.serverTimestamp()`, and vice versa. This discourages good programming practices, like abstracting the use of Firestore so that it's consistent. This is very difficult to do though with the inability to interchange `FieldValue.serverTimestamp`.

Please allow `FieldValue` constant values to be interchangeable between Admin and non-Admin sdks.

**Comment by dconeybe** [comment]
Hi @ScottPierce. Unfortunately, using the objects from the Web SDK and Admin SDK interchangeably is not supported. You've been fortunate that so far it has worked but that was sheer luck.

I will discuss with the team though and reply back to this issue in a week or so. It may be feasible to at least make `FieldValue` interchangeable.

**Comment by ScottPierce** [comment]
@dconeybe One of the problems is that if I have a `Firestore` instance, I can't access the `FieldValue` instances dynamically. I can only resolve them statically via importing something else.

If I could simply do something like `firestore.fieldValues.serverTimestamp()` that would also be acceptable.

My planned work around is to wrap `Firestore` and do just that.

It seems to me that creating an owner to own database access so that it can be centralized would be something your team would want to encourage, so that the same data could be accessed in the same way from multiple places in the app, and also shared with firebase functions. The scariest thing by far about using Firebase is accessing / storing things differently across platforms.

**Comment by dconeybe** [comment]
We discussed this as a team and decided that we want to do something about the issue that you are facing. We haven't made any specific plans or set any timelines so for now your idea of creating a "wrapper" sounds like a great way forward. Since there is no immediate action for the Firestore SDK team, I'm going to close this ticket. But thank you for reporting this and participating in the discussion. I hope that your workaround serves you well until we improve things on our end. For googlers, this feature request is tracked internally as b/175201836.

**Comment by ScottPierce** [comment]
@dconeybe So how will I know when you guys do something to officially support this since this ticket is being closed?

**Comment by bradleymackey** [comment]
I'd also like to express support for this - I'm currently using Firestore closely with Cloud Functions where a document write can trigger a function can create a new model and write it back to the database. The new, generated document might contain `FieldValue`s, `Timestamp`s and `GeoPoint`s, all of which are `firebase-admin` backed. I'd like to perform rules-based unit tests by creating these objects in my existing model code and writing them to the database manually (to test that only admin has permission to do this), but they're all `firebase-admin` backed, so I can't. I've created a very "hacked together" module to get me by in the meantime which can convert from `@firebase/rules-unit-test` to `firebase-admin` and back again: https://gist.github.com/bradleymackey/803538b7b7a416a530b8caee2f027efe

**Comment by dconeybe** [comment]
I've added a note to our internal ticket b/175201836 to comment back on this issue once it's implemented.

**Comment by maxsap** [comment]
Maybe post the wrapper for others to get help on the same issue in the mean time?
