### ISSUE TITLE
onTokenRefresh is deprecated

### ISSUE THREAD

**Issue by longcharmroeun** [firebase/firebase-js-sdk#4132]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10
  * Browser version: google chrome
  * Firebase SDK version: 8.1.1
  * Firebase Product: cloud messaging (auth, database, storage, etc)

#### Steps to reproduce:

onTokenRefresh is `deprecated`

#### Relevant Code:

https://stackoverflow.com/questions/63766386/what-does-ontokenrefresh-deprecation-mean

After onTokenRefresh is `deprecated`, is there any option to handle new token refresh without too much frequency like the old one.

**Comment by Feiyang1** [comment]
Token refresh was never actually implemented in the JS SDK. The API is a no-op, and we don't plan to implement it anytime soon, so we decided to deprecate and eventually remove it.
@zwu52 Anything to add?

**Comment by zwu52** [comment]
That is correct. The FM registration token is stable in the case where no rotation will be triggered from the backend side.
