### ISSUE TITLE
Encoding is not UTF-8 error

### ISSUE THREAD

**Issue by ardmn** [firebase/firebase-js-sdk#414]
### [REQUIRED] Describe your environment

  * Operating System version: mac os
  * Firebase SDK version: 4.8.1
  * Firebase Product: database

### [REQUIRED] Describe the problem

browser show error When I try add firebase.js to chrome extension: 
Can't load file  /../firebase.js ... . Encoding is not UTF-8.

I try convert it to utf-8 but browser show error anyway 

#### Steps to reproduce:
1) download firebase.js using https://www.gstatic.com/firebasejs/4.8.1/firebase.js
2) add firebase.js to chrome extension package
3) enable developer mode in chrome browser
4) load extension to chrome browser

**Comment by ardmn** [comment]
Only avalible solution what I find it is using backgrounf.html, wich load firebase.js (<script> tag) and with messaging betwin background and conten scripts. 

But if u know how download firebase.js or how transform firebase.js in order to use the js file in chrome extension - please tell me

**Comment by barna-n** [comment]
Same problem...

**Comment by davemart-in** [comment]
Seeing the same thing...

**Comment by winterlightning** [comment]
same problem

**Comment by davemart-in** [comment]
I found a work-around. It doesn't look pretty, but by recompiling the second library that is included in firebase.js with [Google closure compiler](https://closure-compiler.appspot.com/home) I was able to make it work: https://pastebin.com/QPDqVimD

**Comment by falcondai** [comment]
Another workaround by *avoiding* to import `firebase-auth.js`  https://stackoverflow.com/a/49496631/1121123. The issue is likely the same as https://github.com/pouchdb/pouchdb/issues/5798

**Comment by protonhs** [comment]
@davemart-in  your solution's awesome ! it solves it perfectly! Thanks!

**Comment by davemart-in** [comment]
Awesome!  Glad to hear!

**Comment by aseire** [comment]
@davemart-in Brilliant! it solves it perfectly! Thank You!

**Comment by lukejacksonn** [comment]
So I don't know what this approach might break.. but I wasn't happy with recompiling or using background.html and sending messages. So I searched the source for `\u` and eventually you come across the character `￿` it is used in this snippet of code `xb=/\uffff/.test("￿")`. If you remove all instances of this character so that the code reads `xb=/\uffff/.test("")` then the error no longer appears but everything seems to work as normal (database and auth at least).

**Comment by laocoi** [comment]
I have the same problem with PHP when I extract text from HTML string by substr function.
`substr($meta, 0, 160);`
Look everything is good with `echo` but when use `print_r` function, end of extracted string has a mark like this ��.

**The solution for who has the same problem like me:**
`mb_substr($meta, 0, 160, "utf-8")`

**Comment by jasan-s** [comment]
Is recompiling still the best solution for this?
