### ISSUE TITLE
[firebase_auth] onAuthStateChanged returns NULL intial user on web

### ISSUE THREAD

**Issue by devj3ns** [firebase/firebase-js-sdk#4145]
The  ```authStateChanges()``` stream initially returns ```null``` before returning the currently logged in user.

I am using **Flutter** for developing a Web-App. In my index.html file inside my Flutter project I have the following imports (latest versions):
```
<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-auth.js"></script>
```

When I change them to **version 7.5.0 it works fine** (all newer versions have the issue):
```
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>
```

When I export my project to android everything works fine. The only **AuthStateChange** is the currently logged in user instead of null and then the currently logged in user.

  * Operating System version: Windows 10 20H2
  * Browser version: Chrome 87.0.4280.66
  * Firebase SDK version: 8.1.1
  * Firebase Product: auth
  * Flutter version: 1.24.0-10.2.pre • channel beta

**Comment by rosalyntan** [comment]
Hi @devj3ns, thanks for filing this issue! Can you try this with v8.1.2? There's a fix in that version that may potentially solve your issue.

**Comment by devj3ns** [comment]
Hey @rosalyntan. Thanks for letting me know. Unfortunately version 8.1.2 does not solve my issue.

**Comment by rosalyntan** [comment]
I see, thanks for the quick response! We'll take a look -- I've filed b/175034991 for internal tracking.

**Comment by devj3ns** [comment]
@rosalyntan Thanks a lot!

**Comment by cesarvarela** [comment]
Hey guys any news? Its's been months.

Using `8.3.2`

**Comment by Ehesp** [comment]
It's worth noting here that original issue relates to Flutter web. The native platforms for Flutter (Android/iOS) are implemented totally differently under the hood so they're not relevant in this case.

**Comment by Ehesp** [comment]
I'm not convinced this is an issue with the JS SDK.  Doing some testing locally and it appears the version change only impacts FlutterFire.

**Comment by vinwonghk** [comment]
I have tried that below combinations of Flutter version and Firebase plugins version work:
- Flutter version: 2.0.4 • channel stable
- Firebase JS SDK version: 8.0.1
- firebase_core: ^1.0.4
- firebase_auth: ^1.1.1

**Comment by Ehesp** [comment]
Yes this can be closed, I fixed this in FlutterFire via https://github.com/FirebaseExtended/flutterfire/pull/5766

**Comment by devj3ns** [comment]
> Yes this can be closed, I fixed this in FlutterFire via https://github.com/FirebaseExtended/flutterfire/pull/5766

Okay, thank you 💙
