### ISSUE TITLE
@firebase/xyz namespaced packages on npmjs/yarnpkg do not link to GitHub

### ISSUE THREAD

**Issue by jthegedus** [firebase/firebase-js-sdk#415]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 17.04
  * Firebase SDK version: @firebase/auth v0.3.1
  * Firebase Product: auth 

### [REQUIRED] Describe the problem
@firebase/util links to GitHub on yarnpkg.com and npmjs.com

@firebase/auth does not. Additionally, the owner field for @firebase/auth is not 'Firebase' but rather [jshcrowthe](https://github.com/jshcrowthe), which after an investigation is revealed to be a significant contributor, which is fine. These two things in combination will cause people to flinch when glancing for the repo and contributor.

**Comment by jshcrowthe** [comment]
Hey @jthegedus thanks for the issue! I have added an author field and fixed the repo field for `@firebase/auth` in #416
