### ISSUE TITLE
[8.1.1] firebase.messaging().onMessage not called but setBackgroundMessageHandler works

### ISSUE THREAD

**Issue by globules-io** [firebase/firebase-js-sdk#4152]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 x64
  * Browser version: 87.0.4280.66
  * Firebase SDK version: 8.1.1
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

Message is received in the background but `firebase.messaging().onMessage` is never triggered. I do see that the message has been received in the background so I believe everything is setup properly.

`[firebase-messaging-sw.js] Received background message  {from: "108937435448", collapseKey: "do_not_collapse", data: {…}}`

I do use a self signed SSL cert for dev purposes and launched google chrome with 

`--ignore-certificate-errors --unsafely-treat-insecure-origin-as-secure=https://localhost:443`

If I unregister the service worker and reload the page, OR reset notification permission, I get the error

`api.ts:131 DELETE https://fcmregistrations.googleapis.com/v1/projects/xxx-221900/registrations/dwFjUvyslYDE9yCK_K21hc:APA91bHuOsovoz50ZSfex7Ue68Q8jKZW6B0R4hPgFahS0SFST8UOnP4YWumhiG5KiMTGV6sYEIJiSBpCKaYvgq5bhX6jjA7PqdVS4yxOCYmYesttkt-ME2HotiVV2rp31ODVNyap9Jl1 404`

```
token-management.ts:65 FirebaseError: Messaging: A problem occurred while unsubscribing the user from FCM: FirebaseError: Messaging: A problem occurred while unsubscribing the user from FCM: Requested entity was not found. (messaging/token-unsubscribe-failed). (messaging/token-unsubscribe-failed).
    at https://www.gstatic.com/firebasejs/8.1.1/firebase-messaging.js:1:24157
    at https://www.gstatic.com/firebasejs/8.1.1/firebase-messaging.js:1:1982
    at Object.next (https://www.gstatic.com/firebasejs/8.1.1/firebase-messaging.js:1:2087)
    at r (https://www.gstatic.com/firebasejs/8.1.1/firebase-messaging.js:1:833)
```

Side note, the API in Google console is domain restricted. I of course added my local domain to the list. (Edit: removing the restriction does not change the result)

#### Steps to reproduce:

I made sure I unregistered any previous Firebase worker and cleared IndexedDB. Then loaded the page.

#### Relevant Code:
Worker
```
importScripts('https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.1.1/firebase-messaging.js');
var firebaseConfig = {
    apiKey: "xxx",
    authDomain: "xxx",
    databaseURL: "https://xxx-221900.firebaseio.com",
    projectId: "xxx-221900",
    storageBucket: "xxx-221900.appspot.com",
    messagingSenderId: "108937435448",
    appId: "1:108937435448:web:0fd8a6df335f2334bf49cd"
};
firebase.initializeApp(firebaseConfig);   
const messaging = firebase.messaging();
messaging.setBackgroundMessageHandler(function(payload) {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    // Customize notification here
    const notificationTitle = 'Background Message Title';
    const notificationOptions = {
        body: 'Background Message body.',
        icon: '/firebase-logo.png'
    };
    return self.registration.showNotification(notificationTitle,
    notificationOptions);
});

```

Front end

```
<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-messaging.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-analytics.js"></script>
var messaging = firebase.messaging();  
messaging.usePublicVapidKey('xxx');
messaging.getToken(...) <= works, receives token            
messaging.onMessage(...); <= not working 
```

**Comment by globules-io** [comment]
Anybody ? This is very blocking when in dev.

**Comment by onderTM** [comment]
same problem

**Comment by globules-io** [comment]
@onderTM don't hold your breath, no reply in 50 days.........

**Comment by onderTM** [comment]
I added following line and it worked 👍
<link rel="manifest" href="/manifest.json">

**Comment by globules-io** [comment]
@onderTM Anything specific to firebase in your manifest ?

**Comment by onderTM** [comment]
just 
```
{
  "gcm_sender_id": "xxx"
}
```

**Comment by Vijayakumarktm** [comment]
Same problem. I'm getting "this site has been updated in the background". Also not receiving message in onMessage.

I'm using Reac.js
"react": "^17.0.2",
"firebase": "9.6.7",

Any one can help?

**Comment by zwu52** [comment]
> Same problem. I'm getting "this site has been updated in the background". Also not receiving message in onMessage.
> 
> I'm using Reac.js "react": "^17.0.2", "firebase": "9.6.7",
> 
> Any one can help?

This looks like another issue. normally caused by sending a silent notification. you would need to call the showNotification explicitly if you don't have a notification payload.
