### ISSUE TITLE
privacy concern: signInWithEmailAndPassword errors tell if a given email is used or not

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-js-sdk#4164]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.10
  * Browser version: 89.0.4343.0
  * Firebase SDK version: 8.1.2
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem

[`signInWithEmailAndPassword` errors](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#error-codes_12) should be the same for non-existent email and wrong password so we cannot tell a given email is used in the app or not.

For instance if you want to know if `president@whitehouse.gov` has an account in a Firebase-based adultery dating website just try to log in with this email and a random password. If the error message code is `auth/wrong-password` instead of `auth/user-not-found` then bingo.

This is a serious privacy concern.

**Comment by rosalyntan** [comment]
Hi @laurentpayot, thanks for filing this issue! This is intended behavior -- the same information is available when creating a new account, if the requested email is already in use, and also via the `fetchSignInMethodsForEmail` method.

**Comment by laurentpayot** [comment]
For the same privacy reasons when creating a new account with an existing email shouldn't the error message happen only once the email has been verified? Is there a reason why this is not the actual behavior?
