### ISSUE TITLE
Spam requests token?key =

### ISSUE THREAD

**Issue by SheerGeyser** [firebase/firebase-js-sdk#4173]
Hello, I cannot understand why there is "spam" requests if the user is authorized in the system. It started after I added a call to firestore.

![image](https://user-images.githubusercontent.com/56490213/101238757-5a028700-36f3-11eb-85d8-2672c5790d6e.png)

it starts on every page refresh and ends on first request with code 400.

I made a similar application before "https://todo-3c55c.firebaseapp.com/", it did not contain such spam requests, but yesterday I went in there the same thing.
Tried changing firebase versions did not help, rewriting the authorization logic, etc.

Here is the project repository with this problem: https://github.com/SheerGeyser/test-very-interesting
Sorry if this is my stupid mistake in writing logic :)

**Comment by SheerGeyser** [comment]
UPD: 
![image](https://user-images.githubusercontent.com/56490213/101282677-81d31700-37e7-11eb-8c09-c3a22937ed22.png)
if you comment on this line, the spam will stop because of what is it?

**Comment by samhorlbeck** [comment]
Hi @SheerGeyser, thanks for reaching out.

This seems odd, I don't think you should be seeing that many requests to the token endpoint. When the responses turn into `400`s, what is the error message returned from the server (under the "response" tab)?

**Comment by SheerGeyser** [comment]
> This seems odd, I don't think you should be seeing that many requests to the token endpoint. When the responses turn into `400`s, what is the error message returned from the server (under the "response" tab)?

![image](https://user-images.githubusercontent.com/56490213/101947427-85a8d400-3c01-11eb-9519-7bf4cdae0543.png)

**Comment by mikerowe81** [comment]
This sounds related to #3222 

Check your OS timezone and time to make sure they are correct....I know it sounds crazy, but I ran into this after a clean Windows install and didn't realize my timezone was wrong.

**Comment by SheerGeyser** [comment]
@mikerowe81 LOL, you were right, set the automatic detection of the region and time and the error disappeared...
Thank you very much:)
