### ISSUE TITLE
getIdTokenResult is not handling properly utf-8 claims due base64 encoding compatibility issue with browsers

### ISSUE THREAD

**Issue by mgenov** [firebase/firebase-js-sdk#4174]
### [REQUIRED] Describe your environment

  * Operating System version: OSX
  * Browser version: Firefox 83
  * Firebase SDK version: 8.1.2
  * Firebase Product: auth 

### [REQUIRED] Describe the problem
The token created with with custom claims by admin.auth().createCustomToken(uid, additionalClaims) are encoded in base64 and getIdTokenResult is decoding it on the client but the base64 decoding causes issues with the UTF-8 encoded strings. 

#### Steps to reproduce:

Authenticate user with a custom token with utf-8 claims:
```jsx
admin.auth()
        .createCustomToken("123", {role: "Админ"})
       ..
```

And on the JS side try to read it with:
```jsx
 user.getIdTokenResult(false)
                    .then(idToken => {
                      const { role } = idToken.claims
                      // role here is bad encoded 
```

As a workaround the encoded role with base64 on the server and decoding it with the following function:

```jsx
function b64DecodeUnicode(str) {
    // Going backwards: from bytestream, to percent-encoding, to original string.
    return decodeURIComponent(atob(str).split('').map(function (c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join('')).trim();
}
```

is working properly.

**Comment by rosalyntan** [comment]
Thanks for filing this issue! Filed b/175030610 internally for tracking.

**Comment by yuchenshi** [comment]
I can reproduce this with Chrome and Auth Emulator too. It doesn't seem to affect only Firefox. I think this has something to do with the JS SDK's base64 decoding and I'll take a look.
