### ISSUE TITLE
Firestore Query using where == not working as intended in Cloud Function

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-js-sdk#4176]
Already figuring out this mess for a couple of hours. I just want to get all documents where `isPartnershipVerified` is equal to a certain boolean value. Currently I only have one document in my collection, the queries seems to be not working or having a conflict but I see no error in Cloud Console. So my document data is like this and how the response currently look like

```
{
  "list": [
    {
      "first_name": "Clark",
      "ltoImage": "link",
      "mobile_number": "0964782947",
      "carImage": "link",
      "gender": "Male",
      "proofImage": "link",
      "driverLicense": "link",
      "isAvailable": false,
      "email_address": "archeremiya5@gmail.com",
      "address": "address",
      "last_name": "Kent",
      "isEmailVerified": true,
      "nbiImage": "link",
      "validId": "link",
      "chassis": "IKB4830NKA4950",
      "isPartner": true,
      "plateNumber": "LTO 1234",
      "isPartnershipVerified": false,
      "insurance": "SUV",
      "vehicle": "Toyota Fortuner",
      "profile": "link",
      "medicalCert": "link",
      "pickUpAddress": "address
      "time": {
        "_seconds": 1607270400,
        "_nanoseconds": 0
      },
      "engine": "580NOLSM863095",
      "modelYear": "2019",
      "id": "7Hqgx4D7zAO4HYcqnWqcL7m5Tbo1"
    }
  ],
  "message": "Success"
}
```

This is my Cloud Function HTTP

```
exports.getList = functions.https.onRequest((req, res) => {

	if (req.method !== 'GET') {
		return res.status(500).json({
			message: "Incorrect request method."
		}).end();
	}

	if (req.query.collection === undefined || req.query.idToken === undefined) {
		return res.status(422).json({
			message: "Incorrect parameters."
		}).end();
	}

	return admin.auth().verifyIdToken(req.query.idToken)
		.then(decodedToken => {

			var q = db.collection(req.query.collection)
				.limit(10)
				.orderBy('time', 'desc');

			if (req.query.qk !== undefined && req.query.qv !== undefined)				
				q.where(req.query.qk, "==", (req.query.qv === "true"));

			return q.get().then(querySnapshot => {
				const list = [];

				//This part is very important as for 'where' to work as intended
				if(!querySnapshot.empty && querySnapshot.size > 0){
					querySnapshot.forEach(doc => {

						//This part is very important as for 'where' to work as intended
						if(doc.exists){
							var obj = doc.data();
	
							obj.id = doc.id;
		
							list.push(obj);	
						}
						
					});
				}

				return res.status(200).json({
					list: list,
					message: "Success"
				}).end();

			}).catch(error => {
				return res.status(500).json({
					message: error.message
				}).end();
			});

		}).catch(error => {
			console.error("Failed to verify admin.", error);
			return res.status(403).json({
				message: "Authentication is required."
			}).end();
		});

});
```

Then accessing it from website that is hosted by Firebase Hosting like this.

   ```
 switch (reqCode) {
        case PARTNERS:
            query += "&collection=" + "Partners" + "&qk=" + "isPartnershipVerified" + "&qv=" + true;
            break;
        case PARTNERSHIP:
            query += "&collection=" + "Partners" + "&qk=" + "isPartnershipVerified" + "&qv=" + false;
            break;
    }

    console.log("https://my-app.web.app/getList?"+ query + "&page=" + 1);

    xhttp.open("GET", "https://my-app.web.app/getList?"+ query + "&page=" + 1, true);
    xhttp.send();
```

It returns the document but not matching the `where` condition. It ignores the boolean value and still returning same document that is not match by the `equal` condition, I searched similar issue from SO and I thought adding query.empty and document.exists will resolve the problem I also tried removing the `orderBy` but nothing works.

This is my compound indexes for such query
![image](https://user-images.githubusercontent.com/38008900/101290548-03ee2a80-383e-11eb-95b8-6c405dfa759f.png)

**Comment by hsubox76** [comment]
I notice there's a number of steps here and would like to narrow it down. Do you still have the same issue when you run the same query directly with the client side Firebase JS library? (Instead of using `firebase-admin` in a Cloud function receiving query params from an http request.)

**Comment by ArcherEmiya05** [comment]
> 
> 
> I notice there's a number of steps here and would like to narrow it down. Do you still have the same issue when you run the same query directly with the client side Firebase JS library? (Instead of using `firebase-admin` in a Cloud function receiving query params from an http request.)

I haven't tried to use compound queries using JS SDK of Firestore, however this is my current set up. You can try to reproduce this without `idToken` verification and just directly perform the query and get the result.

**Comment by rafikhan** [comment]
Hi @ArcherEmiya05, I skimmed the code and it references the wrong promise when calling `get()`. When the `qk` and `qv` parameters are set `q` should be reassigned to the result of the `where()` method. See below:

```
			var q = db.collection(req.query.collection)
				.limit(10)
				.orderBy('time', 'desc');

			if (req.query.qk !== undefined && req.query.qv !== undefined)				
				q = q.where(req.query.qk, "==", (req.query.qv === "true"));   // Update this line

			return q.get().then(...
```

**Comment by ArcherEmiya05** [comment]
> 
> 
> Hi @ArcherEmiya05, I skimmed the code and it references the wrong promise when calling `get()`. When the `qk` and `qv` parameters are set `q` should be reassigned to the result of the `where()` method. See below:
> 
> ```
> var q = db.collection(req.query.collection)
>         .limit(10)
>         .orderBy('time', 'desc');
> 
> if (req.query.qk !== undefined && req.query.qv !== undefined)				
>         q = q.where(req.query.qk, "==", (req.query.qv === "true"));   // Update this line
> 
> return q.get().then(...
> ```

You are correct, I forgot that it needs to be reassigned what am I even thinking? Thought that it will automatically concatenate but I just realized that there is no such thing as that on this. Thanks!
