### ISSUE TITLE
firebase-bower not updated to 8.1.2

### ISSUE THREAD

**Issue by bigjimhere** [firebase/firebase-js-sdk#4180]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: 8.1.2
  * Firebase Product: _____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

The firebase-bower repository has not updated to version 8.1.2, which appeared in the Firebase Release Notes for the SDK on Dec 3. Attempting to download 8.1.2 via Bower results in the error "No tag found that was able to satisfy 8.1.2"

A Firebase support representative suggested filing this issue here.

#### Steps to reproduce:

Attempt to download v8.1.2 using the "bower install" command.

#### Relevant Code:

N/A

**Comment by hsubox76** [comment]
Sorry! This step got missed in the weekly release. Just pushed it.
