### ISSUE TITLE
signInWithCustomToken fails with auth/network-request-failed under phantomJS ONLY when hosted on Firebase Servers

### ISSUE THREAD

**Issue by mattbryson** [firebase/firebase-js-sdk#419]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 10.13.2 (issue only occurs when hosted on firebase servers)
  * Firebase SDK version: 4.6.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

I am trying to capture a PDF of an authenticated web app page.  
Phantom JS is run in a CloudFunction, and the web app is a firebase app hosted on Firebase.

Calling `signInWithCustomToken` fails with 

`auth/network-request-failed. A network error (such as timeout, interrupted connection or unreachable host) has occurred.`

But ONLY when running the cloud function / pantomJS on the firebase hosting. 

Serving the cloud functions / phantom locally (and still capturing a firebase hosted web app) works fine.

##### SETUP
- A HTTP cloud function uses pantomJS to capture an authenticated firebase hosted web app.
- The cloud function creates a custom token with `admin.auth().createCustomToken`.
- A url to the hosted firebaseapp app is created, with the token appended as a query param.
- The URL is given to phantomjs to create a pdf of the page.
- When the firebase webapp boots, it grabs the token, and uses `firebase.auth().signInWithCustomToken`
- On success of the sign in, it tells phantom to take the PDF.
- The cloud function then saves the pdf in firebase storage
- The http cloud function then returns to the user / web app with the URL of the document.

This all works fine in the browser, but fails under phantom ONLY when hosted on firebase.

It is a paid up plan so external URLS can be loaded.

Interestingly I can validate the token with the REST API fine, but I can't quite get the SDK to realise the user is authed.

#### Steps to reproduce:

I have a hosted app demoing the issue:

https://hello-firebase-ea30c.firebaseapp.com/

##### Hosted (fails)
go to https://hello-firebase-ea30c.firebaseapp.com, and press the 'Create PDF (Auth with SDK)' button.

This will generate the PDF, return the file AND return the pre authed URL created by the cloud function for you to see in the browser.

The PDF will show the network error. The URL it was taken from will work fine in the browser.

##### Local (works)
Check out the repo https://github.com/mattbryson/phantomjs-firebase-auth-issue and then

`cd functions && npm install && cd ../`

then

`firebase serve --only functions,hosting`

Ensure that the functions are running under port 5001. If not you must update the following file to match your port number

`/public/main.js line 183`

Then open the locally hosted web app, hit the same buttons and you will get a working PDF, and a working URL. The PDF is created using the HOSTED web app, the only difference is that phantom is running locally.

The fact it works locally, sounds like some kind of domain black / whitelist issue?
The hosting domain is added to the Approved domains in the console.  

#### Relevant Code:

https://github.com/mattbryson/phantomjs-firebase-auth-issue

There is more info in the read me of the repo.

**Comment by mohshraim** [comment]
face the same problem..
any update?

**Comment by rommelpe** [comment]
Sorry for the delay here, @mattbryson. I tried following the steps to reproduce this but it looks like some packages were outdated and the functions endpoint didn't exist anymore. 
![image](https://user-images.githubusercontent.com/56452310/68851313-ad80ec00-0710-11ea-83f7-757aceb17e4a.png)

If you are still interested working on this issue, you can help me replicating the error using these latest versions [Firebas JS SDK](https://firebase.google.com/support/release-notes/js) v7.3.0 | [firebase-admin](https://www.npmjs.com/package/firebase-admin) v8.7.0 | [firebase-functions](https://www.npmjs.com/package/firebase-functions) v3.3.0 to speed up the investigation. Thanks.
