### ISSUE TITLE
[firebase_auth]: signInWithPopup fails with "Blocked a frame with origin from accessing a cross-origin frame."

### ISSUE THREAD

**Issue by zienna** [firebase/firebase-js-sdk#4202]
### [REQUIRED] Describe your environment

  * Operating System version: __N/A___
  * Browser version: __N/A___
  * Firebase SDK version: __7.21.1___
  * Firebase Product: _auth____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
We are using Facebook login with signInWithPopup for our web app in NextJS. The signup fails **on mobile** when the app is open from within Facebook's browser. This is the error we get:

**SecurityError · Blocked a frame with origin "https://app.metnu.com" from accessing a cross-origin frame. Protocols, domains, and ports must match.**

#### Steps to reproduce:
The error can be reproduced by opening a signup form using Facebook login with Firebase through Facebook's browser. (Post a link to it on Facebook and then open it from mobile)

#### Relevant Code:

`  try {
    let provider;
    if (platform === "google") {
      provider = new firebase.auth.GoogleAuthProvider();
    } else if (platform === "facebook") {
      provider = new firebase.auth.FacebookAuthProvider();
    } 

    provider.setCustomParameters({
      promt: "select_account",
    });

    return firebase
      .auth()
      .signInWithPopup(provider)
      .then(async (resp) => {

///// other stuff here //////
          dispatch(signUpSuccess());
        } else {
          dispatch(
            signUpError({
              code: "auth/email-already-in-use",
              message: `A user with email ${resp.user?.email} already exists`,
            })
          );
        }
      })
      .catch(async (error) => {
        console.log(error);
        dispatch(
          signUpError({
            code: "auth/email-already-in-use",
            message: error?.message,
          })
        );
      });
  } catch (error) {
    const err = error?.response?.data?.error || error;
    console.log(err);
  }
};`

**Comment by malcolmdeck** [comment]
Thanks for the report! I've filed b/175598904 to track this internally.

**Comment by gavmck** [comment]
Did you ever figure this out? I'm looking at a similar issues with the facebook in-app browser

**Comment by taylorchance** [comment]
Having this same issue with GoogleAuthProvider. On my older code branches, it works fine. Something else is breaking it but I can't pinpoint what it is.

**Comment by markfilan** [comment]
Same-Origin Policy (SOP) restricts how a document or script loaded from one origin can interact with a resource from another origin. For example, when Site X tries to fetch content from Site Y in a frame, by default, Site Y's pages are not accessible due to security reasons, it would be a huge security flaw if you could do it.

**How to solve?**

The window.postMessage() method provides a controlled mechanism to securely circumvent this restriction. The window.postMessage() safely enables cross-origin communication between Window objects; e.g: between a page and an iframe embedded within it.

```
const frame = document.getElementById('your-frame-id');
frame.contentWindow.postMessage(/*any variable or object here*/, 'http://your-second-site.com');
```

The window.postMessage is available to [JavaScript](http://net-informations.com/js/default.htm) running in chrome code (e.g., in extensions and privileged code), but the source property of the dispatched event is always null as a security restriction. (The other properties have their expected values.)

**Comment by P4R4DiSi4C** [comment]
Hello
Encountering the same issue, only **locally** after **signInWithPopup** when I try to apply the returned user to the store:
It only happens with Pinia, same code with vuex is fine

![image](https://user-images.githubusercontent.com/17826095/218399099-a3099e84-ab4c-41ee-ba87-1a0247a320f4.png)

main.js:
```
let app;
onAuthStateChanged(auth, (user) => {
  if (!app) {
    app = createApp(App);
    app.use(createPinia());
    app.use(router);
    app.use(vuetify);
    app.mount("#app");
  }

  const store = useAppStore();

  if (user) {
    // ERROR HAPPENS HERE!
    store.user = user;
  } else {
    store.user = null;
    router.push("/login");
  }
});
```

Pinia store:
```
actions: {
		async login() {

			try{
				const provider = new OAuthProvider('microsoft.com');

				provider.setCustomParameters({
					tenant: 'xxxxxxxxxxxx'
				});

				const res = await signInWithPopup(auth, provider);
			}
			catch(error)
			{
				console.log(error)
			}
		}
```

**Comment by arnonrdp** [comment]
@P4R4DiSi4C, did you find a solution?

**Comment by prameshj** [comment]
Does this issue occur if the main page and the iframe are on the same origin? You can try the best practices in https://firebase.google.com/docs/auth/web/redirect-best-practices to keep everything on the same origin. It is possible that the popup flow is treated similar to a redirect in facebook browser.

**Comment by arnonrdp** [comment]
> 

Issue persists even after the update.

**Comment by prameshj** [comment]
> > 
> 
> Issue persists even after the update.

By update are you referring to the iframe and the main app being on the same domain? Can you post an HAR file? Thanks!
