### ISSUE TITLE
Sourcemaps Don't Compile With Rollup/Vite

### ISSUE THREAD

**Issue by Pandawan** [firebase/firebase-js-sdk#4203]
### Describe your environment

  * Operating System version: macOS 11.0.1
  * Browser version: Firefox 84.0b8
  * Firebase SDK version: 8.2.0
  * Firebase Product: auth (auth, database, storage, etc)

### Describe the problem

It seems `firebase/auth`'s sourcemaps use some unusual syntax which [prevents them from working/compiling correctly](https://github.com/vitejs/vite/issues/1031) on Vite (which uses Rollup, not sure if that's relevant).

The sourcemap contains non-path properties which vite is unable to read. 
```jsonc
{
"version":3,
"sources": [
  "../../node_modules/google-closure-library/closure/goog/base.js",
  " [synthetic:util/defineproperty] ",
  " [synthetic:util/global] ",
  " [synthetic:util/polyfill] ",
  ],
  // ...
}
```

The vite team is issuing a fix (not yet released) which ignores invalid sourcemap paths, but perhaps this is something that could/should be fixed in this package directly rather than ignored through config on each compiler. I'm not sure of the consequences of a change like this, so I'm just proposing this as a possible issue.

#### Steps to reproduce:
Taken directly from the linked issue:
```
$ yarn create vite-app firebase-example
$ cd firebase-example
$ yarn add firebase
$ yarn

// in App.vue, add:
import firebase from 'firebase/app'
import 'firebase/auth'

$ yarn dev
```

**Comment by chaoming** [comment]
Is this issue fixed?

I recently upgrade to react-scripts 5 which uses webpack 5, and this issue happens to my application. I am using `firebase v8.3.3`.

**Comment by hsubox76** [comment]
The Firebase Auth JS SDK v8 and below were written in Closure which I'm guessing would cause some weird incompatibility issues with modern build tools. v9 was completely rewritten in TypeScript which hopefully fixed some of these issues? Let me know if you're experiencing the same issue with v9+ and I will reopen the issue.
