### ISSUE TITLE
import auth error

### ISSUE THREAD

**Issue by rohantumma** [firebase/firebase-js-sdk#4208]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 (VS Code)
  * Browser version: chrome 87.0.4280.88
  * @angular-devkit/architect :          0.1100.4
  * @angular-devkit/build-angular:   0.1100.4
  * @angular-devkit/core :                 11.0.4
  * @angular-devkit/schematics:      11.0.4
  * @angular/fire:                              6.1.4
  * @schematics/angular/                 11.0.4
  * @schematics/update /                0.1100.4

### [REQUIRED] Describe the problem
* import auth
Module '"../../../node_modules/firebase"' has no exported member 'auth'. Did you mean to use 'import auth from "../../../node_modules/firebase"' instead?ts(2614)

#### Steps to reproduce:

![image](https://user-images.githubusercontent.com/34683346/102119548-4aa7da00-3e67-11eb-8313-c483a7813104.png)
![image](https://user-images.githubusercontent.com/34683346/102119597-5eebd700-3e67-11eb-8c72-b7e5509609d9.png)

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
* import { auth } from 'firebase/app';
```

**Comment by hsubox76** [comment]
It seems like that was the recommended import pattern in angularfire guides until recently, when we (the Firebase JS SDK) changed our export pattern in v8. Looks like the angularfire documentation was updated to match:

https://github.com/angular/angularfire/blob/master/docs/auth/getting-started.md

And if you follow that, the line should be:
`import firebase from 'firebase/app';`

**Comment by alejoorduz** [comment]
Instead of  " import { auth } from 'firebase/app"  --> use " import firebase from 'firebase/app'; "
y enand instead of auth.GoogleAuthProvider() --> use firebase.auth.GoogleAuthProvider()
