### ISSUE TITLE
DatabaseURL not present in firebase config for web app

### ISSUE THREAD

**Issue by harshshinde07** [firebase/firebase-js-sdk#4211]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome Version 87.0.4280.88
  * Firebase SDK version: _____
  * Firebase Product: database

### [REQUIRED] Describe the problem

Database URL is not provided when creating a new Firebase project from console

#### Steps to reproduce:

Create a new Firebase project and Add Firebase to your web app.
The firebase config created does not have `databaseUrl` parameter

#### Screenshot:

![firebase](https://user-images.githubusercontent.com/25999879/102173123-583d7e00-3ec0-11eb-9557-033548c0796c.png)

**Comment by hsubox76** [comment]
I believe you shouldn't need one: https://github.com/firebase/firebase-js-sdk/pull/3650#issuecomment-681138610

But I tried creating a test project and although it didn't initially show up in the config, after I went to the Realtime Database tab and clicked to create a database, the databaseURL property showed up in my web app config in the console.

**Comment by dhstack** [comment]
I noticed this too today. This change doesn't seem to be documented anywhere except here on GitHub. This is a minor problem for me since I'm using CloudBuild environment variables, and my code expects a value for the `databseURL`. That said, I don't use the realtime database (only Firestore), so I just left the `databseURL` property as an empty string and that seems to work. I'll have to refactor my code to remove this value as expected since I'm not using it anyway.

**Comment by harshshinde07** [comment]
Hi, leaving the `databaseUrl` property empty doesn't work for me. I'm using `8.2.0` version of the firebase. Following is the error text:
```
@firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com 
```

As @hsubox76 suggested, I tried creating a realtime database and copying the URL from there but I'm getting the following  warning:
```
@firebase/database: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "apiKey" and "databaseURL" properties provided to initializeApp() match the values provided for your app at https://console.firebase.google.com/.
```
This is because the realtime database has a different URL from that of firestore. The URL received was of the following type:
```
https://<APP_NAME>-default-rtdb.firebaseio.com/
```

Thanks.

**Comment by katowulf** [comment]
Realtime database is not Firestore. You can't retrieve data in Firestore using a Realtime Database URL.

This repo if for reporting SDK bugs related to the JavaScript SDK, not a support forum. Please [reach out to support](http://firebase.google.com/support) if you need help.
