### ISSUE TITLE
Firebase Auth throws in incognito tab

### ISSUE THREAD

**Issue by jamesdaniels** [firebase/firebase-js-sdk#4218]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.15
  * Browser version: Chrome 88
  * Firebase SDK version: 0.0.900-exp.a9388d5b2
  * Firebase Product: auth

#### Steps to reproduce:

Open a site using Auth@exp in Chrome Incognito, auth throws `FirebaseError: Firebase: Error (auth/web-storage-unsupported).` and halts.

#### Relevant Code:

```javascript
const auth = getAuth(app);
onAuthStateChanged(auth, user => console.log(user));
```

**Comment by DellaBitta** [comment]
Closing this issue because I have conferred with James and we don't believe that this is an issue anymore.
