### ISSUE TITLE
[Bug] Field type reference in DocumentSnapshot obtained in transaction is not an instance of DocumentReference

### ISSUE THREAD

**Issue by rulamon** [firebase/firebase-js-sdk#4226]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home 1909
  * Browser version:  Chrome 87
  * Firebase SDK version: 8.1.2
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When getting a document through a transaction (Transaction.get()) the field type reference does not does not return an instance of DocumentReference anymore. Similar to https://github.com/firebase/firebase-js-sdk/issues/4125 but with transactions instead of queries.

**Comment by schmidt-sebastian** [comment]
Thanks for reporting this. We will get this fixed in the next release, which unfortunately is not slated to happen until the beginning of January.
