### ISSUE TITLE
Firebase.SDK_VERSION stuck at 8.0.1

### ISSUE THREAD

**Issue by lupas** [firebase/firebase-js-sdk#4235]
* Operating System version: Mac OS 11.1
  * Browser version: not applicable
  * Firebase SDK version: 8.2.1
  * Firebase Product: all

####  Describe the problem

```js
const firebase = require('firebase/app')
console.log(firebase.SDK_VERSION)
// Result: "8.0.1"
// Expected: "8.2.1"
```
Also see all the `.js` files in `@firebase/app/dist` contain the following:
```js
const version$1 = "8.0.1";
```
#### Steps to reproduce:

See the two lines above.

#### Relevant Code:

See the two lines above.

#### Background

We use the `SDK_VERSION` in the Firebase module for NuxtJS (https://firebase.nuxtjs.org) to load the appropriate Firebase scripts in the created service-workers (e.g. via `'https://www.gstatic.com/firebasejs/8.0.1/firebase-app.js'`)

**Comment by hsubox76** [comment]
Thanks for reporting this, it's on our list to fix. It seems like we need to have `@firebase/app` get the version string dynamically somehow instead of being bundled into its code at compile time, since the `@firebase/app` package isn't necessarily published with every release.
