### ISSUE TITLE
[Firestore] Registering an unload listener and best practices

### ISSUE THREAD

**Issue by dbstratta** [firebase/firebase-js-sdk#4236]
### Describe your environment

  * Operating System version: **Ubuntu 20.10**
  * Browser version: **Chrome 87.0.4280.88 (Official Build) (64-bit)**
  * Firebase SDK version: **8.2.1**
  * Firebase Product: **firestore**

### Describe the problem

Lighthouse 6.4.0 on Chrome 87 warns that the firebase SDK registers an `unload` event listener and it can prevent browser optimizations like the Back-Forward Cache.

![Screenshot from 2020-12-23 20-19-52](https://user-images.githubusercontent.com/18295954/103044054-d3a4cc80-455d-11eb-8ee9-b8ee23ccd8c9.png)

#### Steps to reproduce:

Enable the firestore local persistance.

#### Relevant Code:

```javascript
import firebase from 'firebase/app';
import 'firebase/firestore';

firebase.firestore();
firebase.firestore().enablePersistence({ synchronizeTabs: true }); // Happens with `synchronizeTabs: false` too.
```

**Comment by wu-hui** [comment]
Thanks for the report! I believe this is something we should address, I can provide an update after the holidays, in the meantime, I'll keep the issue open.

**Comment by johanchouquet** [comment]
Hi @wu-hui,

I have the same issue. It brings our score in lighthouse to be not as high as it could be.

Did you plan to address that point in the end ?
