### ISSUE TITLE
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by Iamstanlee** [firebase/firebase-js-sdk#4237]
* Operating System version: MacOS catalina 10.15.7
  * Browser version: FIrefox 84.0(64 bits)
  * Firebase SDK version: 8.2.0
  * Firebase Product: firestore

PROBLEM
 Cannot read/write data on the cloud firestore with exception Uncaught (in promise) FirebaseError: Missing or insufficient permissions.

The firestore rules has been set to allow read/write operations
Firestore Rules
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```
![Screenshot 2020-12-24 at 07 28 32](https://user-images.githubusercontent.com/39183287/103066700-428a2180-456e-11eb-984e-282cbd67584e.png)
![Screenshot 2020-12-24 at 07 31 33](https://user-images.githubusercontent.com/39183287/103066906-af052080-456e-11eb-9f4b-75c50424838c.png)

**Comment by hsubox76** [comment]
1. Are you definitely using the same Firebase project in your client side config that you are setting the rules for in the console?
2. Can you show the code you are using to do the Firestore write/read?
