### ISSUE TITLE
auth/argument-error errors are swallowed in signInWithEmailAndPassword

### ISSUE THREAD

**Issue by blikblum** [firebase/firebase-js-sdk#4242]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10
  * Browser version: firefox 84
  * Firebase SDK version: 8.2.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Calling firebase.auth().signInWithEmailAndPassword() with invalid args, the error ("auth/argument-error") is swallowed and ctach block is not called

#### Steps to reproduce:

Call irebase.auth().signInWithEmailAndPassword with invalid args

#### Relevant Code:

```javascript
firebase
  .auth()
  .signInWithEmailAndPassword()
  .catch((error) => {
    console.log("login:error", error);
  });
```

Here is a live example: https://codepen.io/blikblum/pen/WNGdvPj

**Comment by Railly** [comment]
Any updates on it?

**Comment by alvin883** [comment]
Hi, I ran into the same issue with `signInWithCustomToken()` method, I guess it's related to this issue as well https://github.com/firebase/firebase-js-sdk/issues/1881 but somehow it's closed?

However if I change the code into async function and using try catch block like this, it works:
```javascript
async () => {
  try {
    await firebase.auth().signInWithCustomToken();
  } catch (err) {
    console.error("err", { err });
  }
};
```

it's the workaround for me right now, but I would like to use the ECMA Promise and use the Promise `.catch()` method instead. And also in my opinion, it feels unintuitive having a different Promise spec for this and it cause a lot of confusion.

Thanks!

**Comment by sadnessOjisan** [comment]
I have similar error with `sendSignInLinkToEmail`.

This is my source code.

```ts
const auth = getAuth(app);
export const authWithMailLink = async (email: string) => {
  try {
    const res = await sendSignInLinkToEmail(auth, email, {
      url: `https://localhost:3000`,
    });
    return res;
  } catch (e) {
    console.error(e);
    throw new Error("fail auth");
  }
};
```

**Comment by weixifan** [comment]
I've filed an internal b/211321187 to track.

**Comment by oztek22** [comment]
It's been a while and I can still reproduce it on firebase `9.13.0` with react `18.2.0` and parcel `2.7.0`.
Is there any update or place to track the update on this issue?

**Comment by DellaBitta** [comment]
Hi @oztek22,

The internal issue was recently marked as obsolete, but are you still encountering this issue?  Thanks!

**Comment by oztek22** [comment]
Hi @DellaBitta I do not remember the outcome as it is very old but I know that I found some workaround already so for me this issue is already resolved.

**Comment by DellaBitta** [comment]
HI @oztek22

Ok, thanks for getting back to me. I'm going to close this issue then. If you do encounter a similar problem please open a new issue and link to this one within it. Thanks!

**Comment by blikblum** [comment]
I confirm that with v9, the issue does not exists anymore: https://stackblitz.com/edit/vitejs-vite-tsvswl?file=main.js
