### ISSUE TITLE
Incorrect warning: "Warning: Firebase is already defined in the global scope."

### ISSUE THREAD

**Issue by DylanVann** [firebase/firebase-js-sdk#4245]
When using firebase in development (`NODE_ENV=development`) I get a warning logged `Warning: Firebase is already defined in the global scope."`.

Looking at the code in `@firebase/app` it seems this warning will always be trigged because `var firebase` is defined above the check for `self.firebase !== undefined`.

# `@firebase/dist/index.esm.js`:

## line 542:

```js
var firebase = createFirebaseNamespace();
```

## line 640:

```js
if (isBrowser() && self.firebase !== undefined) {
    logger.warn("\n    Warning: Firebase is already defined in the global scope. Please make sure\n    Firebase library is only loaded once.\n  ");
```

It looks like this is a bundling/scoping issue because I can see:

## line 665:

```js
var firebase$1 = firebase;
```

So it seems the intention may have been that `var firebase` should not have been included on line `542`, or at least it should not be in the same scope.

## Temporary workaround:

As a temporary workaround I am using `patch-package` to change the code to what I think is the intention:

```diff
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
-if (isBrowser() && self.firebase !== undefined) {
+if (isBrowser() && self.firebase$1 !== undefined) {
     logger.warn("\n    Warning: Firebase is already defined in the global scope. Please make sure\n    Firebase library is only loaded once.\n  ");
```

**Comment by hsubox76** [comment]
I'm not seeing any issues in a standard test app so can I have some more information about how you're importing Firebase? Can you show me the lines of code? You mentioned "NODE_ENV=development," are you using it in Node? Any information like that would be helpful. I need to be able to reproduce the problem before applying any fix, to make sure it's the right fix.

**Comment by DylanVann** [comment]
I'm not seeing this issue anymore, maybe my bundler (vite/esbuild) was actually doing something incorrectly 😅 . I'll re-open if I can reproduce the issue again with newer versions. Thank you!
