### ISSUE TITLE
Firestore rules-unit-testing does not accept FieldValue.serverTimestamp

### ISSUE THREAD

**Issue by gavingolden** [firebase/firebase-js-sdk#4246]
### [REQUIRED] Describe your environment

  * Operating System version: OSX Catalina 10.15.6
  * Browser version: _____
  * Firebase SDK version: `firebase-tools: 9.1.0`, `@firebase/rules-unit-testing: 1.1.6`
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Firebase admin accepts `FieldValue.serverTimestamp()`, but `@firebase/rules-unit-testing` throws the following error:
```
FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom object (found in field timestamp in document test/1)
```
#### Steps to reproduce:

Minimal repo: https://github.com/gavingolden/server-timestamp-test
#### Relevant Code:
```ts
import * as admin from "firebase-admin"
import * as rulesTester from "@firebase/rules-unit-testing"
import {firestore} from "firebase-admin/lib/firestore";
import FieldValue = firestore.FieldValue;

const projectId = 'test-project' // this is also set when starting the emulators
const clientOptions = {projectId}
process.env.GCLOUD_PROJECT = projectId
process.env.FIRESTORE_EMULATOR_HOST = "localhost:8080"

describe("firestore serverTimestamp", () => {

  //  ✅ passes
  it("admin allows serverTimestamp", async () => {
    await admin.initializeApp(clientOptions)
      .firestore()
      .collection("test")
      .doc("1")
      .set({
        timestamp: FieldValue.serverTimestamp(),
      })
  })

  // ❌ fails with "FirebaseError: Function DocumentReference.set() called
  // with invalid data. Unsupported field value: a custom object (found in field
  // timestamp in document test/1)"
  it("rulesTester allows serverTimestamp", async () => {
    await rulesTester.initializeTestApp(clientOptions)
      .firestore()
      .collection("test")
      .doc("1")
      .set({
        timestamp: FieldValue.serverTimestamp(),
      })
  })
})
```

**Comment by bradleymackey** [comment]
This is a known issue, see https://github.com/firebase/firebase-js-sdk/issues/4129. The Firestore data types between `firebase-admin` and `@firebase/rules-unit-testing` are not interchangeable at the moment. You need to make sure you're using the `firebase-admin` models when calling `admin.initializeApp` and `@firebase/rules-unit-testing` models when initialising a `rulesTester.initializeTestApp`.
