### ISSUE TITLE
@firebase/firestore: Firestore (8.2.1): Connection WebChannel transport errored

### ISSUE THREAD

**Issue by kachinon** [firebase/firebase-js-sdk#4248]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by hsubox76** [comment]
Can you please add some more information? What browser or environment are you using? How are you importing Firebase? What are your lines of code that you are using to call Firestore? When does this error happen? Any information you can provide would be helpful.

**Comment by SpectorHacked** [comment]
Also just happend on me,
Firebase javascript SDK 7.24.0, expo app, Firebase trying to sign in but get a Network error.
**Urgent..** fix??

**Comment by kachinon** [comment]
> ### [REQUIRED] Describe your environment
> * Operating System version: _____
> * Browser version: _____
> * Firebase SDK version: _____
> * Firebase Product: _____ (auth, database, storage, etc)
> 
> ### [REQUIRED] Describe the problem
> #### Steps to reproduce:
> #### Relevant Code:
> ```js
> // TODO(you): code here to reproduce the problem
> ```

**Comment by hsubox76** [comment]
> Also just happend on me,
> Firebase javascript SDK 7.24.0, expo app, Firebase trying to sign in but get a Network error.
> **Urgent..** fix??
> ![image](https://user-images.githubusercontent.com/31251714/103372089-c9447e80-4ad9-11eb-92c5-e1e1eaeba19c.png)

Can you please start a separate issue with full details about what line is causing you to see this error, and what error you are seeing? You have imported `firestore` but you seem to be trying to use `database` (RTDB), which is a separate package. It seems like you would get an error about database being undefined, long before you would get the error in the title of this issue.

**Comment by Chinna111** [comment]
I have faced the same problem, any solution available? 
I can't understand what went wrong!

Here my code..

**App.js**

 import React, { Component } from 'react';
import {StyleSheet,Text,View,TextInput,Button,TouchableHighlight} from 'react-native';

import firebase from 'firebase';
import firestore from '@react-native-firebase/firestore';

const firebaseConfig = {
  apiKey: "*********************",
  authDomain: "test-c78ec.firebaseapp.com",
  projectId: "test-c78ec",
  storageBucket: "test-c78ec.appspot.com",
  messagingSenderId: "106189113329",
  appId: "1:106189113329:web:4bf80ec51eba69ab042650",
  measurementId: "G-875ZSQLZS4"
};
firebase.initializeApp(firebaseConfig);

 export default class App extend components{

check2(){
  console.log("level strarted");
  firebase
  .firestore()
  .collection("MyCollection")
  .doc("mydoc")
  .set({
    key: "2",
    value: "World",
  })
  .then((ref) => { console.log(ref);
    console.log("sucessssssssssssssss")
   });
}

render(){
 return(
  <View>
    <TouchableHighlight style={[styles.buttonContainer, styles.loginButton]} onPress={() =>    this.check2('login')}>
          <Text style={styles.loginText}>Store data</Text>
        </TouchableHighlight>
   </View>
  );
 }
}
```

**Error:**
 ```
WARN     [2021-01-06T10:27:51.153Z]  @firebase/firestore: Firestore (8.2.1): Connection WebChannel transport errored: {"a": {"C": null, "K": [Circular], "a": {"A": 0, "B": [U], "C": true, "F": 45000, "G": false, "I": true, 
"J": -1, "K": "IKeNE9pC779MSM5Rj_dnMg", "Ka": 5000, "Ma": false, "Na": false, "Oa": false, "P": 0, "Pa": 2, "Qa": undefined, "R": [Object], "S": 0, "T": 45498, "Ta": 1, "U": true, "Ua": 10000, "V": 4, "X": false, "Y": [Object], "a": null, "b": [zd], "c": 
[bc], "f": [Z], "fa": false, "g": [Array], "ga": undefined, "h": null, "ha": "https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel", "i": null, "ia": "", "j": null, "ja": 8, "l": null, "m": null, "ma": 12, "na": [U], "o": 3, "oa": 
600000, "pa": "ATXNDTEvJ_SpMuY50LXD23HPyh9-AVCM", "qa": -1, "ra": [Ed], "s": null, "u": 0,
```
