### ISSUE TITLE
Firebase Cloud messaging => unable to use payload data, and showing "This site has been updated in the background"

### ISSUE THREAD

**Issue by varora1406** [firebase/firebase-js-sdk#4249]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro version 2004, OS build - 19041.572
  * Browser version: Chrome 87.0.4280.88 (Official Build) (64-bit)
  * Firebase SDK version: 7.16.1
  * Firebase Product: messaging

#### Steps to reproduce:
* Use repo - https://github.com/varora1406/firebase-push-notification-demo
* replace firebase config with project config in 2 files - `firebase-messaging-sw.js` and `index.html`
* launch index.html with any server like [web server for chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en)
* Copy the curl request from `curl-test.sh`, and try to send this request from any API tool, like [insomnia](https://insomnia.rest/)
* You will see that notification body and title are not coming in notification. Instead it's showing site URL and message - "This site has been updated in the background"
![image](https://user-images.githubusercontent.com/24986539/103415954-6ff85000-4baa-11eb-98e1-9adf746c8d06.png)

Note: Your tab should not be focused to see this notification.

We were about to launch our PWA with happy faces, but got stuck with this problem.
I even used latest firebase version from npm, and tried multiple ways, but still no success.

How to resolve this problem?

**Comment by greatelv** [comment]
I think this issue is about how to refer to the module.
I was able to solve it like this : 

```
// before
import firebase from 'firebase/app';
const firebaseApp = firebase.initializeApp(getFirebaseConfig());
```
```
// after
// firebase is replaced commonjs to UMD global module
// set allowUmdGlobalAccess: true, if you used typescript.
const firebaseApp = firebase.default.initializeApp(getFirebaseConfig());
```

None of the comments helped but I solved it with this !
