### ISSUE TITLE
Type Issue in Documentation

### ISSUE THREAD

**Issue by SCasarotto** [firebase/firebase-js-sdk#4250]
I 100% understand this isn't the right place for this but couldn't seem to get a response or update through the normal https://firebase.google.com/docs Send Feedback flow.

[This PR](https://github.com/invertase/react-native-firebase/issues/4545) is being held open until the official firebase docs match. 

The issue:
Type definition described [here](https://firebase.google.com/docs/reference/js/firebase.database.Query#on) (Specifically `cancelCallbackOrContext ? :  Object | null `) are inaccurate and should match the actual type definition file [here](https://github.com/firebase/firebase-js-sdk/blob/5b2d1073a7a4e1366b0d807510f2bded713ed7bc/packages/database-types/index.d.ts#L87).

Sorry to bug but hope this can get resolved. Thanks

**Comment by hsubox76** [comment]
This is the correct place for reference docs errors! We currently generate reference docs from packages/firebase/index.d.ts. Hopefully soon they will be generated directly from the code. Made a PR:

https://github.com/firebase/firebase-js-sdk/pull/4259

After that is checked in, we need to run our doc generation script and push it to our docs site. I will try to keep the issue open until that part is done.

**Comment by hsubox76** [comment]
Merged the fix, still need to regenerate docs and push to docs site.

**Comment by hsubox76** [comment]
Doc page is updated: https://firebase.google.com/docs/reference/js/firebase.database.Query#on
