### ISSUE TITLE
@firebase/firestore: Firestore (8.2.1): Connection WebChannel transport errored

### ISSUE THREAD

**Issue by kachinon** [firebase/firebase-js-sdk#4251]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro 64-bit (10.0, Build 18363
  * Browser version: Chrome Version 87.0.4280.88 (64bit)
  * Firebase SDK version: 8.2.1
  * Firebase Product: firestore

#### Steps to reproduce:
hi, i am new here,
Since a few days i am getting an error while trying to communicate via Firebase/ Firestore. but on Firebase/Auth its works.
#### Relevant Code:
`[2020-12-30T19:06:12.669Z]  @firebase/firestore: Firestore (8.2.1): Connection WebChannel transport errored: {"a": {"C": null, "K": [Circular], "a": {"A": 0, "B": [U], "C": true, "F": 45000, "G": false, "I": true, "J": -1, "K": "ytRMh7YN4EMr7Roe7DSAXQ", "Ka": 5000, "Ma": false, "Na": false, "Oa": false, "P": 0, "Pa": 2, "Qa": undefined, "R": [Object], "S": 0, "T": 68273, "Ta": 1, "U": true, "Ua": 10000, "V": 4, "X": false, "Y": [Object], "a": null, "b": [zd], "c": [bc], "f": [Z], "fa": false, "g": [Array], "ga": undefined, "h": null, "ha": "https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel", "i": null, "ia": "", "j": null, "ja": 8, "l": null, "m": null, "ma": 12, "na": [U], "o": 3, "oa": 600000, "pa": "8LdCXTKPzkjUOQ8lpNAaBFDgt6fFDWdT", "qa": -1, "ra": [Ed], "s": null, "u": 0, "v": "gsessionid"}, "b": {"database": "projects/hipmi-sulteng-app/databases/(default)"}, "c": {"a": [Object], "b": 4, "src": [Circular]}, "f": {"a": [Circular]}, "i": undefined, "j": false, "l": true, "m": true, "o": "https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel"}, "defaultPrevented": false, "status": 1, "target": {"C": null, "K": [Circular], "a": {"A": 0, "B": [U], "C": true, "F": 45000, "G": false, "I": true, "J": -1, "K": "ytRMh7YN4EMr7Roe7DSAXQ", "Ka": 5000, "Ma": false, "Na": false, "Oa": false, "P": 0, "Pa": 2, "Qa": undefined, "R": [Object], "S": 0, "T": 68273, "Ta": 1, "U": true, "Ua": 10000, "V": 4, "X": false, "Y": [Object], "a": null, "b": [zd], "c": [bc], "f": [Z], "fa": false, "g": [Array], "ga": undefined, "h": null, "ha": "https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel", "i": null, "ia": "", "j": null, "ja": 8, "l": null, "m": null, "ma": 12, "na": [U], "o": 3, "oa": 600000, "pa": "8LdCXTKPzkjUOQ8lpNAaBFDgt6fFDWdT", "qa": -1, "ra": [Ed], "s": null, "u": 0, "v": "gsessionid"}, "b": {"database": "projects/hipmi-sulteng-app/databases/(default)"}, "c": {"a": [Object], "b": 4, "src": [Circular]}, "f": {"a": [Circular]}, "i": undefined, "j": false, "l": true, "m": true, "o": "https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel"}, "type": "c"}`
```javascript
// TODO(you): code here to reproduce the problem
`  firebase
      .auth()
      .createUserWithEmailAndPassword(email, password)
      .then((result) => {
        firebase
          .firestore()
          .collection('users')
          .doc(firebase.auth().currentUser.uid)
          .set({
            nama,
            email,
          });
        console.log(result);
        this.props.navigation.replace('MainScreen');
      })
      .catch((error) => {
        if (error.code === 'auth/email-already-in-use') {
          Alert.alert('Error', 'That email address is already in use!');
        }

        if (error.code === 'auth/invalid-email') {
          Alert.alert('Error', 'That email address is invalid!');
        }
      });`

**Comment by thebrianchen** [comment]
@kachinon Thanks for writing in! What line of code causes the error? Is it the call to `createUserWithEmailAndPassword()`, or to `set()`? Does it consistently reproduce?

Also, this might be unrelated to your error, but note that `DocumentReference.set()` is an [async method](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#set), which means that you'll need to use async/await in order to ensure that your next line of code executes after the set is completed.

**Comment by Chinna111** [comment]
I have faced the same problem, any solution available?

**Comment by sgatius** [comment]
Dear all, I've the same problem. Anyone repair it?

**Comment by thebrianchen** [comment]
@Chinna111 @sgatius Can you provide some more details on the conditions in which you run into the problem, or provide a repro where this error is being thrown? I've tried reproducing it in this [Github repo](https://github.com/thebrianchen/js-webchannel-issue) without any success.

**Comment by llbbdd** [comment]
@thebrianchen The console.log('result', result) in your repo isn't waiting for the firebase.firestore call to resolve. It's giving you the result of the firebase.auth call.

**Comment by thebrianchen** [comment]
@llbbdd Thanks! My intention was to recreate @kachinon's original repro code, which didn't work for me. Waiting for the `firestore.set()` call in my code doesn't reproduce the Webchannel error for me either. Do you have any luck with a reproduction?

**Comment by llbbdd** [comment]
@thebrianchen Ah, I see that now. I have the same code with the same error. Although it isn't an error, it's a warning (not caught in the catch), and it takes between 3 and 4 minutes to appear.

**Comment by thebrianchen** [comment]
@llbbdd Does it appear for you with my code repo? I played around with it some more and also waited, but I wasn't getting any errors. Can you share a repro or share logs with [logging enabled](https://firebase.google.com/docs/reference/node/firebase#setloglevel)?

**Comment by llbbdd** [comment]
@thebrianchen It's just occurred to me, and I'm not sure if this ties in with @kachinon's issue or not, that I'm trying to use this in a React Native component. I may be way off base getting involved here. @kachinon?
