### ISSUE TITLE
firebase.initializeApp throws type error in all 8.x versions but not in V 7.x versions

### ISSUE THREAD

**Issue by pfiadDi** [firebase/firebase-js-sdk#4252]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS X Big Sur
  * Browser version: Chrome 87.0.4280.88
  * Firebase SDK version: 8.x
  * Firebase Product: Firebase / Firestore

### [REQUIRED] Describe the problem

I try to initialize the Firebase App with:

```firebase.initializeApp(configJson)```

That leads to this Error:

```TypeError: firebase.initializeApp is not a function```

BUT:
- the same code works with every 7.x version but with none of 8.x

#### Steps to reproduce:
I created a little tool to load a JSON into Firestore.
You can use it yourself to reproduce the error:
https://github.com/pfiadDi/json-to-firestore

- Clone the project
- Run `npm install`
- Change the config.json in `/examples` to your Firebase Project and start the local emulator of this project
- Start it with `parcel index.html`
- In the browser click on `Add CONFIG` and `Add Data json` 
- Start the function with `Start importing data`

If a version 7.x is installed it should work as expected (the example data should be in your Firestore if your security rules are: allow write true)

If version 8.x is installed you should get the JS error from above in the console

#### Relevant Code:
In the file index.js:
```javascript
document.getElementById("add").addEventListener("click", () => {
    ...
    firebase.initializeApp(configJson)<----
    ...
}
```

**Comment by johnorourke** [comment]
Not sure if this helps but the import syntax changed in v8 - see https://firebase.google.com/docs/web/setup

```
// Firebase App (the core Firebase SDK) is always required and must be listed first
import firebase from "firebase/app";
// If you are using v7 or any earlier version of the JS SDK, you should import firebase using namespace import
// import * as firebase from "firebase/app"
```

**Comment by pfiadDi** [comment]
@johnorourke  YES thank you that did the trick.
I changed it from:
```
const firebase = require("firebase/app");
require("firebase/firestore");
```

to import syntax.

Thank you and sorry for raising an issue instead of more carefully studying the docs :)
