### ISSUE TITLE
Outdated Error Message

### ISSUE THREAD

**Issue by MrAndrew** [firebase/firebase-js-sdk#4253]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome
  * Firebase SDK version: 6.14.10
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem/steps to reproduce:

I get an error message when running a query with the not equal comparison combined with an order by on another field:
```
Invalid query.... You have a where filter with an inequality (<, <=, >, or >=) on field 'myDocField' and so you must also use 'myDocField' as your first argument to Query.orderBy(), but your first orderBy() is on field 'someOtherDocField' instead.
```
I believe the error message need to be updated to include the "!=" symbol.

```
#### Relevant Code:

 My query is like this:
```
myQuery = myReference.where("myDocField", "!=", 0).orderBy("someOtherDocField").get(); //throws error
```
while this doesn't throw the error:
```
myQuery = myReference.where("myDocField", "!=", 0).orderBy("myDocField").orderBy("someOtherDocField").get(); //allowed

**Comment by thebrianchen** [comment]
@MrAndrew Thanks for reporting this! I'll have an update for the error message out shortly :)
