### ISSUE TITLE
TypeError: _firebase__WEBPACK_IMPORTED_MODULE_2__.default.auth.RecaptchaVerifier is not a constructor

### ISSUE THREAD

**Issue by colinwagaba** [firebase/firebase-js-sdk#4254]
### [REQUIRED] Describe your environment

  * Operating System version:  `macOS Mojave 10.14.5`
  * Browser version: `Google Chrome 87.0.4280.88 (Official Build) (x86_64)`
  * Firebase SDK version: `8.15.1`
  * Firebase Product: `auth`

#### Steps to reproduce:
Trying to implement `Phone Authentication` but can't seem to get past the `reCaptcha` stage!
`TypeError: _firebase__WEBPACK_IMPORTED_MODULE_2__.default.auth.RecaptchaVerifier is not a constructor`

Not sure this is useful but, I also use the `realtime database` which works fine.

After hours of stackoverflow, I decided to check out the firebase reference and came across a few things:
1. `firebase.auth` is a `callable` - from my understanding it is a function that's called with parens, as in `firebase.auth()`.
2. `RecaptchaVerifier` is one of the classes on `firebase.auth()`.
3. `firebase.auth()` returns `firebase.auth.Auth` - the auth service with a method to `signInWithPhoneNumber`.
4. `Do not call this constructor (firebase.auth.Auth) directly. Instead, use firebase.auth()`.
5. The firebase guide instead uses `new firebase.auth.RecaptchaVerifier()` excluding the parens from `firebase.auth`.

I then tried to debug using `console.log()` to see the properties/methods/classes on `firebase[.auth/auth()]` and here are the results:
`console.log(firebase)`

<img width="457" alt="Screenshot 2021-01-02 at 11 16 21" src="https://user-images.githubusercontent.com/24539185/103453541-36c7f900-4cec-11eb-9d27-9302acf2d38d.png">

`console.log(firebase.auth)`

<img width="469" alt="Screenshot 2021-01-02 at 11 19 04" src="https://user-images.githubusercontent.com/24539185/103453558-6119b680-4cec-11eb-81bc-416b4a658303.png">

`console.log(firebase.auth())`

<img width="438" alt="Screenshot 2021-01-02 at 11 23 37" src="https://user-images.githubusercontent.com/24539185/103453647-02087180-4ced-11eb-8de3-021cdfe7865e.png">

The above logs show that `firebase.auth` is a `function` - no?
Also, in each case, I can't seem to find `RecaptchaVerifier()` in the output, and when I try to log it I get:
`auth.RecaptchaVerifier is not a function` and `auth(...).RecaptchaVerifier is not a function` respectively. These two errors, and `auth.RecaptchaVerifier is not a constructor` (when the `new` keyword is used) led me to wonder: **where th is RecaptchaVerifier() located** 🤔

#### Relevant Code:

```javascript
// config file

import firebase from 'firebase/app';
import 'firebase/database';
import 'firebase/auth';

export default firebase.initializeApp({
...
});

// auth component

import firebase from '[path-to-config]';

window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
  'size': 'invisible',
  'callback': (response) => {
    // reCAPTCHA solved, allow signInWithPhoneNumber
  }
});
```

**Comment by hsubox76** [comment]
`initializeApp` returns a FirebaseApp. This is not identical to `firebase` the library, imported from `firebase/app`. In most tutorials we suggest assigning the result of `initializeApp` to a variable called `app` or similar, to avoid this confusion. Naming it `firebase` here in your auth component import has probably contributed to the confusion.

`RecaptchaVerifier` is a static property on auth, and you can only get it from the `firebase` library. If you name the import `app` instead, and add `import firebase from 'firebase/app'` to your auth component file, it should probably work fine. You can call any `auth()` functions on app if you like (`app.auth().signInWithEmailAndPassword`, etc.), or any other component (`app.firestore()`), you just can't access any static properties.

**Comment by colinwagaba** [comment]
Wow! That was a real gotcha! Thanks a lot.
