### ISSUE TITLE
firestore.collection.where fails if requested ID does not exist

### ISSUE THREAD

**Issue by johnorourke** [firebase/firebase-js-sdk#4255]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04 (WSL2) for build, Windows 10 for browser
  * Browser version: Chrome 87 on Windows 10
  * Firebase SDK version: 8.2.1
  * Firebase Product: firestore (auth, database, storage, etc)

#### Steps to reproduce:

* create a simple web page app
* have working local emulators for hosting, firestore
* have working auth and the ability to fetch a document by ID
* have working code to fetch from a collection using a .where filter
* initialize using the magic URLs eg.  `/__/firebase/init.js?useEmulators=true`

All that works - we can use collections and docs.

#### Relevant Code:

* set up a collection in the root of your firestore called "profiles"
* add one document, ensure you can read it - let's put the ID in a variable like `const realId = "abc123";`
* try `firestore.collection("profile").where(firebase.firestore.FieldPath.documentId(), "in", [realId])` - no errors, 1 document found
* create a non-existent ID in a string variable eg. `const nonExist = "xxxxxxxxxx";` 
* now try firestore.collection("profile").where(firebase.firestore.FieldPath.documentId(), "in", [nonExist])
** Result: "TypeError: Cannot read property 'ht' of undefined"

(my client is actually Typescript / create-react-app, but I don't think that's causing the issue since it's specific to a non-existent document ID)

![image](https://user-images.githubusercontent.com/2004038/103478134-6d6d4480-4dbc-11eb-8129-dd93a3efd156.png)

**Comment by johnorourke** [comment]
(just for clarity - yes, I know you don't need a 'where' to fetch one document. My use case is fetching an array of document IDs as a filtered collection.)

**Comment by thebrianchen** [comment]
@johnorourke Thanks for filing an issue with detailed repro steps and logging!

I tried reproducing this locally but was unable to. I created a Firebase project with hosting and added these two files to the `public` directory:
- [index.html](https://gist.github.com/thebrianchen/f34d5dd88fd1f9b2475da84bea7d8bdc) for loading Firebase URLs.
- [init2.js](https://gist.github.com/thebrianchen/9a99aaadd889731a1eec17d11437f2f0) for performing the queries.

Can you take a look to see if I'm missing anything, or provide another repro that showcases the error?
