### ISSUE TITLE
Firebase Issues on Internet Explorer 11

### ISSUE THREAD

**Issue by andsalves** [firebase/firebase-js-sdk#4261]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Internet Explorer 11
  * Firebase SDK version: 7.21.1
  * Firebase Product: analytics, performance

### [REQUIRED] Describe the problem
Hi guys,
I'm having issues with the firebase/analytics integration with IE11. I've tried different approaches to overcome it, but with no success.
The issue is that, when I import firebase and analytics, I get a TransactionInactiveError, and I can't log events to  analytics.

There's already a related reported issue (https://github.com/firebase/firebase-js-sdk/issues/2430), but, in my case, I see the error also from a local windows machine (not just from sauce labs or browserstack). 
Also, #2430 seemed to be closed with no solution.

#### Steps to reproduce:

- Import firebase-app, firebase-analytics and firebase-performance.
- Initialize firebase with `firebase.initializeApp`.

#### Relevant Code:
This is a minimal code that successfully reproduces the error on Windows 10, Internet Explorer 11:
(replace the app config accordingly).

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.jsdelivr.net/npm/fetch-ie8@1.5.0/fetch.js"></script>
    <script src="https://unpkg.com/core-js-bundle@3.8.1/minified.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.21.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.21.1/firebase-analytics.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.21.1/firebase-performance.js"></script>
</head>
<body>
<script>
  if (firebase) {
    console.log('Initializing app')
    firebase.initializeApp({
      "apiKey": "...",
      "authDomain": "...",
      "databaseURL": "...",
      "projectId": "...",
      "storageBucket": "...",
      "messagingSenderId": "...",
      "appId": "...",
      "measurementId": "..."
    })

    firebase.analytics()
  }
</script>
</body>
</html>
```

**Comment by hsubox76** [comment]
Will try to reproduce. Quick question: Do you still see the same error in the current version of Firebase (8.2.1 as of this post)?

**Comment by andsalves** [comment]
Hello, 
Weirdly, I tried to reproduce also, with the same code and Windows installation I could reproduce previously and... The error simply didn't show up anymore. 
With our web platform, the issues persisted though, but as of this point I can't provide a reliable minimal repro, I'll close the issue for now. Will reopen in future if I can't find a solution for our platform and can provide a good minimal repro.
Thank you.
