### ISSUE TITLE
auth/timeout during auth().getRedirectResult()

### ISSUE THREAD

**Issue by chaitanya4288** [firebase/firebase-js-sdk#4267]
* Operating System version: Windows 10 Pro
  * Browser version: Google chrome 87.0.4280.88
  * Firebase SDK version: 7.24.0
  * Firebase Product: auth

User clicks on social login (with Google) where we call 
**firebase.auth().signInWithRedirect(provider);**

Now user is redirected to google login page, where user enters his credentials.
After successful authentication, he is redirected to our login page where we do the 
**firebase.auth().getRedirectResult();**

Here it is giving an error
{code: "auth/timeout", message: "The operation has timed out.", a: null}

As per the documentation, it says: 

> _Thrown typically if the app domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console._

But if that is the case then I wonder why it works for most of our users & doesn't for a rare few. 

Also, I don't see any api calls in the network tab for this operation.

**Comment by strom2357** [comment]
Thanks for reporting.  This - 

> I wonder why it works for most of our users & doesn't for a rare few.

is my thought too - have you noticed anything in common with these users?  We've experienced issues in the past for example that have turned out to be specific to disabled cookie / incognito mode usage.

**Comment by chaitanya4288** [comment]
I got access to one of the user. On his browser, it worked once on normal window and in incognito it always failed. 
I didn't find any settings like disabled cookie on his browser. everything was usual.

**Comment by rosalyntan** [comment]
Hi @chaitanya4288, thanks for the additional info! We are aware of issues with `signInWithRedirect` in incognito mode, as seen in #3004. For now, we suggest falling back to `signInWithPopup` and following #3004 for updates.
