### ISSUE TITLE
Extending Object Prototype causes the firebase to fail

### ISSUE THREAD

**Issue by efsolInc** [firebase/firebase-js-sdk#4276]
###  Describe your environment

  * Operating System version: MacOS 11.0.1
  * Firebase SDK version: 9.4.2
  * Firebase Product: database 
  * Node.js version: 12.13.0
  * NPM version: 6.12.0
  
### Describe the problem

Firebase SDK fails to establish connection to the Realtime database. No error is thrown in the callback or in console.
When accessing a reference from the realtime database in a new project, everything works fine. It's just when I extend the Object.prototype with a function, this behaviour is triggered. However after removing the prototype function everything goes back to normal.

I am aware that extending something that the firebase SDK is using in prototype could trigger this behaviour but no matter how you extend the prototype, even with weirdest names possible, it just doesn't work.

#### Steps to reproduce:

* Setup the Firebase admin sdk as in Firebase documentation
* Extend the Object Prototype with a function

#### Relevant Code:

```
const admin = require('firebase-admin');
const serviceAccount = require('./service-account.json');


// ----------------------------- //
// - START OF OBJECT PROTOTYPE - //
// ----------------------------- //

//! Commenting out this function will make everything work as expected
//! It's only if we keep this function here, the VALUE callback will never
//! get fired. Notice that this toJson function can be replaced with anything
//! and it has nothing to do with the name itself. You can name the function 
//! anything and it would still cause the code to break.

Object.prototype.toJson = function () {
    return JSON.stringify(this);
}

// ----------------------------- //
// - END OF OBJECT PROTOTYPE - //
// ----------------------------- //


function start() {

    // Initialize the app with a service account, granting admin privileges
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount),
        databaseURL: "https://<firebase-db>.firebaseio.com"
    });

    var db = admin.database();

    // Any existing Reference on Realtime Database
    var usersRef = db.ref().child("users");

    usersRef.on('value', snap => {

        //! THIS CALLBACK IS NEVER CALLED
        // Printing out the value appearing on the mentioned child
        console.log(snap.val())
    })
}



// Starting the code
start();
```

**Comment by schmidt-sebastian** [comment]
I will take a look this week.

**Comment by schmidt-sebastian** [comment]
This is an issue in our of our dependencies. I opened a PR: https://github.com/faye/websocket-driver-node/pull/41

**Comment by efsolInc** [comment]
@schmidt-sebastian Thanks for your help!

**Comment by schmidt-sebastian** [comment]
We were not able to merge the PR and won't be able to address this.
