### ISSUE TITLE
[FR] Expose DataSnapshot for unit testing

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-js-sdk#4279]
**Is your feature request related to a problem? Please describe.**
It would be useful to create `firebase.database.DataSnapshot`s from some data and a path for use in unit tests when the input is a `DataSnapshot`.

**Describe the solution you'd like**
Something like `firebase/firebase-functions-test` does - see https://github.com/firebase/firebase-functions-test/blob/master/src/providers/database.ts

**Describe alternatives you've considered**
Creating a mocked `DataSnapshot` but this is a bit brittle as will have to be maintained when `firebase.database.DataSnapshot` is updated.

**Additional context**
Not sure if this belongs here or in `firebase/firebase-js-sdk`

**Comment by maneesht** [comment]
Hi @rhodgkins - starting with v9, you should have access to the DataSnapshot from the `firebase/database` package, or is there more functionality you need?

**Comment by rhodgkins** [comment]
I'll have a look, it's been such a long time I can't remember now...

**Comment by maneesht** [comment]
@rhodgkins - Not sure I follow. Is my comment incomplete?

**Comment by rhodgkins** [comment]
Sorry @maneesht when I first read this in the app it was missing the final line of your comment! I'll have a check when I get a moment and report back. Though tbh I can't remember what I even wanted it for now :s

**Comment by maneesht** [comment]
No worries, please feel free to close this if you no longer require this feature.
