### ISSUE TITLE
Sorry! This step got missed in the weekly release. Just pushed it.

### ISSUE THREAD

**Issue by bigjimhere** [firebase/firebase-js-sdk#4292]
Sorry! This step got missed in the weekly release. Just pushed it.

_Originally posted by @hsubox76 in https://github.com/firebase/firebase-js-sdk/issues/4180#issuecomment-740776912_

Happening again for 8.2.2

**Comment by Feiyang1** [comment]
We just pushed 8.2.3 to firebase-bower. Updating firebase-bower is a manual step outside the main release flow today. We should incorporate it into the main script. FYI, @hsubox76
