### ISSUE TITLE
Module ''firebase'' has no exported member 'firebase'.

### ISSUE THREAD

**Issue by divanvb** [firebase/firebase-js-sdk#430]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro
  * Firebase SDK version: 4.8.2
  * Firebase Product: Firebase itself

### [REQUIRED] Describe the problem

Updated to the latest Firebase version with my Ionic 3 project and now I get the error below! 

#### Steps to reproduce:

By simply importing the package
```import { firebase } from 'firebase';```

#### Relevant Code:
```javascript
[ts] Module ''firebase'' has no exported member 'firebase'.
```

**Comment by jshcrowthe** [comment]
I don't believe the firebase NPM package has ever supported a named `firebase` export. Instead you should use either:

```javascript
import firebase from 'firebase';
```

**Or:**

```javascript
import * as firebase from 'firebase';
```
