### ISSUE TITLE
Typescript Typings not working after V8.0.0

### ISSUE THREAD

**Issue by glumb** [firebase/firebase-js-sdk#4303]
### Describe your environment

  * Firebase SDK version: 8.2.3
  * Firebase Product: js SDK TS Typings
  * Typescript: 4.1.3

### Describe the problem

firebase/index.d.ts has ts errors and thus the Typings can not be used in the project. Specifically line 7851 "Identifier expected. 'default' is a reserved word that cannot be used here.ts(1359)" Thus I can not use the typings for e.g. `firebase.default.firestore.FieldValue` since `default` is not recognised as a valid key.

```javascript
import firebase from 'firebase/app'
import 'firebase/firestore'

export const increment = firebase.firestore.FieldValue.increment // error Namespace 'firebase' has no exported member 'firestore'.
export const FieldValue = firebase.default.firestore.FieldValue // error Namespace 'firebase' has no exported member 'default'.
```

**Comment by maccman** [comment]
This needs fixing pretty urgently.

**Comment by hsubox76** [comment]
We tried to reproduce this and weren't able to. I made a fresh Webpack/TS project from scratch using TS 4.1.3, Firebase 8.2.3, and ts-loader. The index.ts only contains:
```
import firebase from 'firebase/app';
import 'firebase/firestore';

firebase.initializeApp({...});

console.log(firebase.firestore.FieldValue.increment);
```
and there are no errors. Can you upload a minimal repro to github with just a minimal index.ts and your build config, package.json, everything needed to build and reproduce this error?
