### ISSUE TITLE
ref.collection is not a function when using withConverter with onSnapshot

### ISSUE THREAD

**Issue by taylorhoward92** [firebase/firebase-js-sdk#4309]
### [REQUIRED] Describe your environment
  * Operating System version: macOS 11.1
  * Browser version: Chrome  87.0.4280.141
  * Firebase SDK version: 8.2.3
  * Firebase Product: Firestore

#### Steps to reproduce:
When using `withConverter` with `onSnapshot` the `QueryDocumentSnapshot` passed to `toFirestore` has a `ref` property that does not have a `collection` function. However, when using `onSnapshot` without `withConverter` each `DocumentChange` has a `QueryDocumentSnapshot` with a `ref` that does have a `collection` function.

#### Relevant Code:
```ts
import firebase from 'firebase';

class Country {
  name: string;
  citiesCollection: firebase.firestore.CollectionReference;

  constructor(name: string, citiesCollection: firebase.firestore.CollectionReference) {
    this.name = name;
    this.citiesCollection = citiesCollection;
  }
}

const firestoreDataConverter = (): firebase.firestore.FirestoreDataConverter<Country> => ({
  toFirestore: (country) => ({
    name: country.name,
  }),
  fromFirestore: (snapshot): Country => {
    const data = snapshot.data();
    return new Country(data.name, snapshot.ref.collection('cities'));
  },
});

const firebaseApp = firebase.initializeApp({ projectId: 'test' });

// when doing it like this I get the error "snapshot.ref.collection is not a function" in the fromFirestore function
firebaseApp
  .firestore()
  .collection('countries')
  .withConverter(firestoreDataConverter)
  .onSnapshot((snapshot) => {
    snapshot.docChanges().forEach((country) => {
      console.log(country.doc.data());
    });
  });

// manually using fromFirestore instead of including withConverter works fine
firebaseApp
  .firestore()
  .collection('countries')
  .onSnapshot((snapshot) => {
    snapshot.docChanges().forEach((country) => {
      console.log(firestoreDataConverter.fromFirestore(country.doc));
    });
  });

```

**Comment by dconeybe** [comment]
Hi @taylorhoward92. I apologize for this issue that is affecting you but thanks for taking the time to write up this excellent bug report. The good news is that it has already been reported (#4278) and a fix will be merged soon. Since this issue appears to be a duplicate, I'm going to close it; however, feel free to re-open if you disagree.
