### ISSUE TITLE
@firebase/database - Invalid parameters at `/some_ref_path`: Unknown error

### ISSUE THREAD

**Issue by bteng22** [firebase/firebase-js-sdk#4311]
* Operating System version: Big Sur 11.1
  * Browser version: N/A
  * Firebase SDK version: Listed below  
 ```
    "firebase-admin": {
      "version": "9.4.2",
      "resolved": "https://registry.npmjs.org/firebase-admin/-/firebase-admin-9.4.2.tgz",
      "integrity": "sha512-mRnBJbW6BAz6DJkZ0GOUTkmnmCrwVzMreMc6O+RXWukFydOzi5Xr6TKSiPKxoOQw41r9IluP2AZ3Qzvlx2SR+g==",
      "requires": {
        "@firebase/database": "^0.8.1",
        "@firebase/database-types": "^0.6.1",
        "@google-cloud/firestore": "^4.5.0",
        "@google-cloud/storage": "^5.3.0",
        "@types/node": "^10.10.0",
        "dicer": "^0.3.0",
        "jsonwebtoken": "^8.5.1",
        "node-forge": "^0.10.0"
      },
```  
  * Firebase Product: database

### Describe the problem
We have a script utilizing the offending code posted below. It was working perfectly last week, but this week it began failing with an `Unknown error`. I have a feeling it may be due to an updated sub-dependency, since there was no code changes that were deployed on our end. Tried searching through the Firebase dependencies to pinpoint what might have broken the following code, but if anyone else is experiencing this issue or knows where to look, help would be greatly appreciated!

#### Relevant Code:

Offending code:
```javascript
  const usersPrivateSnapshots = await db
    .ref("/users_private")
    .orderByKey()
    .startAt(lastKey)
    .limitToFirst(100)
    .once("value");
```

Error:  
```javascript
 Error: invalid_parameters at /users_private: Unknown Error
    at errorForServerCode (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:640:17)
    at onComplete (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:8942:33)
    at Object.onComplete (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:12468:34)
    at /PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:11612:32
    at PersistentConnection.onDataMessage_ (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:11854:17)
    at Connection.onDataMessage_ (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:11171:14)
    at Connection.onPrimaryMessageReceived_ (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:11165:18)
    at WebSocketConnection.onMessage (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:11066:27)
    at WebSocketConnection.appendFrame_ (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:10658:18)
    at WebSocketConnection.handleIncomingFrame (/PROJECT_DIR/node_modules/@firebase/database/dist/index.node.cjs.js:10708:22) {
  code: 'INVALID_PARAMETERS'
}
```

**Comment by psychonetic** [comment]
@bteng22 Having the same issue.

**Comment by MunifTanjim** [comment]
Hey @bteng22 , what's the value of `lastKey`?

**Comment by hdaba** [comment]
Having the same issue, how can we solve this ?

**Comment by hdaba** [comment]
> Having the same issue, how can we solve this ?

Hello, some news ?

**Comment by hsubox76** [comment]
I can't reproduce this, using firebase-admin@9.4.2 as in the example. If anyone can supply a full minimal reproduction, that would be really helpful. I've created a fresh Node project where the only dependency is `firebase-admin` and the only file is an `index.js` that contains:

```
const admin = require("firebase-admin");

var serviceAccount = require(/* my service key */);

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: // my project url,
});

const stuff = admin
  .database()
  .ref("/users")
  .orderByKey()
  .startAt("uzB39haDZLTmQPjIc1q2NaUEsQg1")
  .limitToFirst(100)
  .once("value");

stuff.then(value => console.log(value.val()))
```

It logs the contents of the document with no errors or warnings.

By any chance, do people have `firebase` and `firebase-admin` installed in the same project? This might cause conflicts with different versions of `@firebase/database`.

**Comment by MunifTanjim** [comment]
@hsubox76 I faced this exact error when I called it with `.startAt("")` (empty string)

**Comment by hdaba** [comment]
> @hsubox76 I faced this exact error when I called it with `.startAt("")` (empty string)

Hello I've replaced `.startAt("")`  by `.startAt("0")`  and it's ok for me 👍 

Thanks

**Comment by hsubox76** [comment]
Based on this I'm guessing that for the original poster, `lastKey` was an empty string or empty value? Let me know if anyone's having a problem where this isn't the case, otherwise we'll let the issue auto-close.
