### ISSUE TITLE
additionalUserInfo not returned by signInWithCredential() Method

### ISSUE THREAD

**Issue by chwzr** [firebase/firebase-js-sdk#432]
### [REQUIRED] Describe your environment

  * Operating System version: all
  * Firebase SDK version: v4.8.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

When using `firebase.auth().signInWithCredential(credential)` with a given oAuth Token, Firebase does not return the additionalUserInfo Object. 

No chance to check if this user is new/has registered in this Firebase Project with this auth attempt 
(without going to db and check if UID is already stored there...)

When using e.g. signInWithPopup() or Phone auth it is returned.

#### Steps to reproduce:

1.  retrieve a oAuth Token e.g. from Google Yolo.
2. pass it to the GoogleAuthProvider Object credential() Method
3. run signInWithCredential()
4. log user object or use provided code example:

#### Relevant Code:

http://jsbin.com/rinilu/edit?js,console

```javascript
// retrieve tokenFromYolo here e.g (with oneTapSignIn/Automatic SignIn)...
let credential = firebase.auth.GoogleAuthProvider.credential(tokenFromYolo);            
firebase.auth().signInWithCredential(credential).then((user)=>{  
  console.log(user)
  if(user.additionalUserInfo){
    console.log("No additionalUserInfo Object returned")
  } else {
    console.log("additionalUserInfo Object returned, im Happy!", user.additionalUserInfo)
  }
})
```

**Comment by bojeil-google** [comment]
Please check the references for full details.`signInWithCredential` never returns `additionalUserInfo`. `additionalUserInfo` is not a property of the user. It is a property of `firebase.auth.UserCredential`. To get that, you need to use `signInAndRetrieveDataWithCredential` documented here: https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInAndRetrieveDataWithCredential
