### ISSUE TITLE
Auth emulator throws unauthorized-domain error on sign-in

### ISSUE THREAD

**Issue by holmberd** [firebase/firebase-js-sdk#4335]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04.5 LTS
  * Browser version: Version 86.0.4240.183 (Official Build) (64-bit)
  * Firebase SDK version: 8.2.4 (also tested on 8.0.0 and 7.24.0)
  * Firebase Product: Auth, Emulator

### [REQUIRED] Describe the problem
I'm experiencing an `auth/unauthorized-domain` error when trying to use the auth-emulator with `signInWithPopup` and the `GoogleAuthProvider` in a chrome extension application.

When I'm not running the emulator sign-in works fine, but when enabling the emulator for auth it will throw the `auth/unauthorized-domain` error on sign-in, see below.
```
code: code: "auth/unauthorized-domain"
Message: "This chrome extension ID (chrome-extension://your-extension-id) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab."
```

#### Steps to reproduce:
1. Setup a new Firebase project with Google Auth Sign-in.
2. Setup Firebase-tools for the newly created project.
3. Follow the steps under [Setup a dummy Chrome Extension](https://github.com/firebase/quickstart-js/tree/master/auth/chromextension) to obtain a **Chrome Extension ID** and **Public Key**.
4. Add the chrome extension URI in the Firebase Console under **Authorised domains**.
5. Add Firebase to your project code and include the **Public Key** and necessary CSP in the extension manifest.
6. Setup the Google Auth sign-in provider with Firebase-auth.
7. Verify that Google auth sign-in works without using the auth emulator.
8. Start the emulators through the Firebase CLI.
8. Change to use the auth emulator, i.e. `firebase.auth().useEmulator('http://localhost:9099/')`
9. Observe the `auth/unauthorized-domain` error being logged in the console.

#### Relevant Code:
```js
import firebase from 'firebase/app';
import 'firebase/auth';

firebase.initializeApp(firebaseConfig);
firebase.auth().useEmulator('http://localhost:9099');
const provider = new firebase.auth.GoogleAuthProvider();
provider.setCustomParameters({ prompt: 'select_account' });
...
await this.firebase.auth().signInWithPopup(provider);
```

### Additional Information
I can see that the origin validation should be skipped if we are in an emulated environment in the firebase-js-sdk, https://github.com/firebase/firebase-js-sdk/blob/0dfef5dd58f961208e29e249f5e8f5a3e2908c88/packages-exp/auth-exp/src/core/util/validate_origin.ts#L29

**Comment by malcolmdeck** [comment]
Thanks for the detailed report! :) Internal bug filed as b/178377748

**Comment by holmberd** [comment]
https://github.com/firebase/firebase-js-sdk/blob/b6a9bf0a187f4dceb713264ca4bbcd6a8e68b332/packages/auth/src/iframeclient/ifchandler.js#L525

Looks like the `OriginValidator` in the `iframeClient` doesn't respect the emulator environment.

**Comment by aiyan** [comment]
I have experienced the same issue and can confirm that the sign-in flow works as expected when not using the emulator. When the emulator is used, it rejects the `signInWithPopup` call even if the domain is authorized on the Firebase dashboard.

**Comment by BUONJG** [comment]
I experiment the same issue, is there a workaround?

**Comment by radube** [comment]
Same here, is there a workaround for this?

**Comment by holmberd** [comment]
@radube In development you can use the `signInWithEmailAndPassword` instead. Create the new user auth in your Firebase Emulator or import it from export when starting the emulator.

```js
const devCredentials = {
  email: 'test@gmail.com',
  password: 'test12345',
};

async signIn() {
  if (process.env.NODE_ENV === 'development') {
    const { email, password } = devCredentials;
    await signInWithEmailAndPassword(getAuth(), email, password);
    return this.currentUser;
  }
  
  await signInWithPopup(getAuth(), googleAuthProvider);
  return this.currentUser;
}
```

**Comment by Bastianowicz** [comment]
I am experienceing the very same. What does work for whatever reason:
if i open chromes dev tools and enable device toolbar (so it behaves like a touch device) it works.
Would love to see a fix or solution for that anyways since I cannot test on actual end devices.

**Comment by holmberd** [comment]
I've upgraded to Firebase 9.2.0 and the issue seem to be resolved.

**Comment by HarryAlvarado28** [comment]
Has this been resolved, and what was the solution? 👨‍💻

**Comment by prameshj** [comment]
I see a comment from @holmberd that this might be resolved.

We do skip origin validation checks in the emulator mode - https://github.com/firebase/firebase-js-sdk/blob/fde5adf638dae4714ff7f25c75e475344907e05e/packages/auth/src/core/util/validate_origin.ts#L29.

Closing based on the comment that it might be resolved, please reopen if you still see this issue.
