### ISSUE TITLE
Cloud function invocation via the SDK fail (net::ERR_FAILED) while CURL work

### ISSUE THREAD

**Issue by tzvc** [firebase/firebase-js-sdk#4336]
* Operating System version: MacOS 10.15.6
  * Browser version: Chrome 87.0.4280.141
  * Firebase SDK version: 8.2.4
  * Firebase Product: functions

#### Steps to reproduce:

Deploy a function:

```javascript
// server code
export default functions
  .region('europe-west1')
  .https.onRequest((request, response) => {
    functions.logger.info('Hello logs!', { structuredData: true });
    response.send("hello world");
  });
```

Invoke it using the URL:

```bash
curl https://europe-west1-myapp-prod.cloudfunctions.net/helloWorld
```

It works properly.

Invoke it using the js SDK:

```javascript
// client code
try {
  this._app = firebase.initializeApp(this._config);
  const func = this._app.functions("europe-west1").httpsCallable(name);
  return await func(data);
} catch (e) {
  console.log(e);
  if (e.code) throw Error(e.code);
  throw Error("unknown");
}
```

It fails: 

```
Access to fetch at 'https://europe-west1-myapp-prod.cloudfunctions.net/helloWorld' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
functions.js:555 POST https://europe-west1-myapp-prod.cloudfunctions.net/helloWorld net::ERR_FAILED
firebase_helper.js:27 Error: internal
    at new HttpsErrorImpl (functions.js:119)
    at _errorForResponse (functions.js:214)
    at Service.<anonymous> (functions.js:631)
    at step (functions.js:64)
    at Object.next (functions.js:45)
    at fulfilled (functions.js:35)
```

I doubt that this error is really due to a CORS problem (as I never had to setup anything for CORS for my cloud functions). I still tried adding CORS handling using [this guide](https://cloud.google.com/functions/docs/writing/http#authentication_and_cors) but the problem persist.

I am aware that the policy changed recently in regards to invocation of function unauthenticated. I therefore made sure that my function were accessible to anyone:
<img width="459" alt="Screen Shot 2021-01-24 at 1 46 03 pm" src="https://user-images.githubusercontent.com/14275989/105630622-85c80080-5e4a-11eb-8f60-3657bd0e09f3.png">
.

I also tried calling it while authenticated (anonymous auth), same problem.

Any ideas ?

**Comment by hsubox76** [comment]
If you want to call it using `httpsCallable`, the cloud function should be created on the server as an `onCall` function. `onRequest` functions are for REST calls.

See:
https://firebase.google.com/docs/functions/callable
