### ISSUE TITLE
I can't update email to user profile

### ISSUE THREAD

**Issue by ljcucc** [firebase/firebase-js-sdk#438]
I try to update the user email ,because it didn't fill the email when I create account with facebook.
So I run this code to setup user's email:
```js
firebase.auth().currentUser.updateProfile({
    email:$("#email").val()
});
```
then nothing change. email still empty.
How could I do?

Thanks!

**Comment by bojeil-google** [comment]
Hey @ljcucc, please refer to the references:
https://firebase.google.com/docs/reference/js/firebase.User#updateEmail
`updateProfile` only updates the `displayName` and `photoURL`. To update email, call `currentUser.updateEmail` instead.

**Comment by ljcucc** [comment]
Thanks! 👍 😄
