### ISSUE TITLE
Webstorm doesn't recognize imports: has no exported member

### ISSUE THREAD

**Issue by RaviH** [firebase/firebase-js-sdk#4381]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS Catalina
  * Browser version: Brave 1.19.88
  * Firebase SDK version: ^0.900.11
  * Firebase Product: firebase/app

#### Steps to reproduce:
Import dependencies into a Typescript file and you would notice imports not being recognized:

![image](https://user-images.githubusercontent.com/141136/106555215-fbc70a00-64d1-11eb-9c34-b75340628a1f.png)

#### Relevant Code:

```typescript
import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getStorage } from 'firebase/storage';
```

**Comment by Feiyang1** [comment]
That's weird. Can you try to do a clean install - delete `node_modules/` and npm install again?

**Comment by RaviH** [comment]
@Feiyang1 So I deleted `node_modules` and `yarn.lock` and removed `firebase` from package.json, then ran `yarn add firebase@exp`. That seems to have helped.

Now I get this:

![image](https://user-images.githubusercontent.com/141136/106679668-06d17700-6572-11eb-9a54-5f2126b28073.png)

I will try to create a brand new project and see if it happens there. I might be getting old firebase from another dependency.

**Comment by Feiyang1** [comment]
Great. It does look like you have multiple versions of Firebase. Yeah, the old firebase can't be used with the new one side by side, so make sure you are not pulling the old firebase in the project.

**Comment by RaviH** [comment]
Hello, I am trying to work on my `firebase-functions` module but can't find docs here: https://modularfirebase.web.app/common-use-cases/functions/ as to how to use `firebase-admin` with `firebase-functions`. Is that not a possibility right now or are the docs missing?

**Comment by RaviH** [comment]
Also, another issue: 
![image](https://user-images.githubusercontent.com/141136/106975754-f6550400-670b-11eb-918b-37be58207b40.png)

```
import { getApp } from "firebase/app";
import { getFunctions } from "firebase/functions";

const functions = getFunctions(getApp());
```

Then I can't use:

`functions.firestore.document('/questions/{questionId}').onCreate(`

**Comment by hsubox76** [comment]
The functions from `firebase/functions` (part of the `firebase` client-side package) is completely different from `firebase-functions`, which is a separate npm package for writing functions code for the server. `firebase-functions` does not have a modularized version, and you should continue to use it the same way you have in the past, hopefully in a separate directory (it's usually installed in a subdirectory of your main project, if you use firebase-cli).

`firebase/functions` (client-side) pretty much does only one thing, which is call `httpsCallable` functions that you wrote and deployed using the actual `firebase-functions` library.

**Comment by RaviH** [comment]
Thank you @hsubox76. That's very helpful to know.

I am not sure if there would be a good way to distinguish it in the names like may be firebase/functions-client. 

Regardless your comment above is really helpful!

**Comment by RaviH** [comment]
Another error below that occurs from this import: `import { Timestamp } from 'firebase/firestore';` or the usage of `Timestamp`

```
  startDateTime: Date | Timestamp | null,
  endDateTime: Date | Timestamp | null,
```

```
node_modules/@firebase/firestore/dist/exp/index.d.ts:858:53 - error TS2315: Type 'LoadBundleTask' is not generic.

858     catch<R>(onRejected: (a: FirestoreError) => R | LoadBundleTask<R>): Promise<R | LoadBundleTaskProgress>;
                                                        ~~~~~~~~~~~~~~~~~

node_modules/@firebase/firestore/dist/exp/index.d.ts:866:65 - error TS2315: Type 'LoadBundleTask' is not generic.

866     then<T, R>(onFulfilled?: (a: LoadBundleTaskProgress) => T | LoadBundleTask<T>, onRejected?: (a: FirestoreError) => R | LoadBundleTask<R>): Promise<T | R>;
                                                                    ~~~~~~~~~~~~~~~~~

node_modules/@firebase/firestore/dist/exp/index.d.ts:866:124 - error TS2315: Type 'LoadBundleTask' is not generic.

866     then<T, R>(onFulfilled?: (a: LoadBundleTaskProgress) => T | LoadBundleTask<T>, onRejected?: (a: FirestoreError) => R | LoadBundleTask<R>): Promise<T | R>;
                                                                                                                               ~~~~~~~~~~~~~~~~~
```

**Comment by RaviH** [comment]
I was able to move forward by using `import { Timestamp } from 'firebase/firestore/lite'`;

Now I can't find: firebase.messaging.isSupported?

**Comment by Feiyang1** [comment]
@zwu52 I don't see `isSupported()` in the API. Should it be added?

**Comment by zwu52** [comment]
Yes probably should be added. Seems `isSupported` was used in both window and sw context. If that's the case, I think we should not move forward w/ https://github.com/firebase/firebase-js-sdk/pull/4446 but just export directly.

**Comment by RaviH** [comment]
@zwu52 Seems like we are saying that `isSupported` should be added. Should we create a new ticket for that?

**Comment by Feiyang1** [comment]
@zwu52 I think we should keep running the checks internally, because we still want to warn people if messaging is used in an unsupported environment. 

@RaviH yes, can you please create a FR for adding `isSupported()`, and close this one?

**Comment by RaviH** [comment]
@Feiyang1 Added https://github.com/firebase/firebase-js-sdk/issues/4474 and closing this ticket
