### ISSUE TITLE
FR: Cache API

### ISSUE THREAD

**Issue by PierBover** [firebase/firebase-js-sdk#44]
Something I had to develop myself when working with Firebase is a small cache API so that users going back to previous views would not have to wait for data.

I implemented a in memory cache with a persistent `on()` connection in the background completely decoupled from my views. After the initial data download from a database path, this memory cache is only updated with `value` events so even for large datasets it works great. My users always see the updated data when returning to previous views instantly.

In any case, the Firebase SDK needs to provide a way to cache the data somehow. Maybe this would go hand in hand with the [offline functionality](https://github.com/firebase/firebase-js-sdk/issues/17), or not.

**Comment by jshcrowthe** [comment]
AFAICT, this is a fork of the discussion going on in #17. I'm going to close this in favor of the other thread.

If I'm not understanding, please re-open with some more context! 😄
