### ISSUE TITLE
Storage SDK missing methods to reference multiple buckets

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-js-sdk#4407]
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: N/A
  * Firebase SDK version: `exp`
  * Firebase Product: storage

### [REQUIRED] Describe the problem

Originally reported here:
https://github.com/firebase/firebase-js-sdk/discussions/4402

#### Relevant Code:

There seems to be no way to reproduce either of these snippets in the new modular SDK:

```js
const storage = firebase.app().storage("gs://my-custom-bucket");
```

```js
  const customApp = firebase.initializeApp({
    // ... custom stuff
  });

  // Get the default bucket from a custom firebase.app.App
  const storage = customApp.storage();

  // Get a non-default bucket from a custom firebase.app.App
  const storage = customApp.storage("gs://my-custom-bucket");
```

**Comment by hsubox76** [comment]
You can do:
```
const storage = getStorage(app, "gs://my-custom-bucket")
```

The second param is named `url` in the definition so I guess it should probably be named "bucket,"  and it doesn't have an accompanying jsdoc description so that should be added. Is that enough or am I missing anything else that would be needed?
