### ISSUE TITLE
messaging.onBackgroundMessage does not prevent the default notification

### ISSUE THREAD

**Issue by Qendolin** [firebase/firebase-js-sdk#4412]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 88
  * Firebase SDK version: 7.21.1
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

[Original Issue](https://github.com/firebase/quickstart-js/issues/495#issue-731652913)

The [comment here](https://github.com/firebase/quickstart-js/blob/29248d166833e51f154a0ed04bb41bfcd309703e/messaging/firebase-messaging-sw.js#L42) says `onBackgroundMessage` can be used to customize background messages which is true by itself but the problem is that the default notification is still shown by the Firebase SDK. There is currently no way to prevent the default notification.

Here is the relevant code from the [onPush](https://github.com/firebase/firebase-js-sdk/blob/b5e9d6ae8e6406b9a31ec9e4d60216527b256a4a/packages/messaging/src/controllers/sw-controller.ts#L173) method
```javascript
// background handling: display and pass to onBackgroundMessage hook
let isNotificationShown = false;
if (!!internalPayload.notification) {
  await showNotification(wrapInternalPayload(internalPayload));
  isNotificationShown = true;
}

// MessagePayload is only passed to `onBackgroundMessage`. Skip passing MessagePayload for
// the legacy `setBackgroundMessageHandler` to preserve the SDK behaviors.
if (
  isNotificationShown === true &&
  this.isOnBackgroundMessageUsed === false
) {
  return;
}

if (!!this.bgMessageHandler) {
  const payload = externalizePayload(internalPayload);

  if (typeof this.bgMessageHandler === 'function') {
    this.bgMessageHandler(payload);
  } else {
    this.bgMessageHandler.next(payload);
  }
}
```
The only case where `showNotification` is not called is when `internalPayload.notification` is falsy. 

#### Steps to reproduce:
1. Register a onBackgroundMessage handler that shows a custom notification
2. Receive a push notification
3. Original and custom notification are shown.

#### Relevant Code:
See https://github.com/firebase/quickstart-js/blob/master/messaging/firebase-messaging-sw.js

```javascript
const messaging = firebase.messaging();

messaging.onBackgroundMessage(function(payload) {
  console.log('[firebase-messaging-sw.js] Received background message ', payload);
  // Customize notification here
  const notificationTitle = 'Background Message Title';
  const notificationOptions = {
    body: 'Background Message body.',
    icon: '/firebase-logo.png'
  };

  self.registration.showNotification(notificationTitle,
    notificationOptions);
});
```

**Comment by Feiyang1** [comment]
It is working as intended. To not trigger the default notification, you need to send a data message instead of a notification message. See https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

But you are absolutely right that the comment is not clear and we should update the comment.
@Qendolin Do you mind making a PR to the quickstart-js project to update the comment to mention you need to send a data message in order to customize the notification?

**Comment by Qendolin** [comment]
I missed that part when reading about FCM because in my mind a data message did not sound like what I wanted, my bad. I'll go ahead and make the PR

**Comment by Qendolin** [comment]
Created PR:  https://github.com/firebase/quickstart-js/pull/537
