### ISSUE TITLE
Messaging: This browser doesn't support the API's required to use the firebase SDK. 

### ISSUE THREAD

**Issue by faviocabral** [firebase/firebase-js-sdk#4423]
hello, 

this message give me the broswer when I build my angular proyect in production what could be the problem , my server run in http ...  node js

this is my code :

   messagingFirebase: firebase.messaging.Messaging;
   token: any;
  currentMessage = new BehaviorSubject(null);
  constructor(private http: HttpClient){
    firebase.initializeApp(environment.firebase);
    this.messagingFirebase = firebase.messaging();
  }

importScripts('https://www.gstatic.com/firebasejs/8.2.2/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.2.2/firebase-messaging.js');

    "@angular/core": "~11.0.5",
    "@angular/fire": "^6.1.4",

**Comment by Feiyang1** [comment]
What browser do you use? Messaging SDK requires Web APIs that some older browsers don't support. See [here](https://github.com/firebase/firebase-js-sdk/blob/21ee150c6d8fab7d613e071d3c7e2e0443d56fdf/packages-exp/messaging-exp/src/helpers/isSupported.ts#L31-L57) what the required APIs are.

If you still think it is an issue, can you please reopen the issue using the template to tell us what browser you use?

**Comment by faviocabral** [comment]
> What browser do you use? Messaging SDK requires Web APIs that some older browsers don't support. See [here](https://github.com/firebase/firebase-js-sdk/blob/21ee150c6d8fab7d613e071d3c7e2e0443d56fdf/packages-exp/messaging-exp/src/helpers/isSupported.ts#L31-L57) what the required APIs are.
> 
> If you still think it is an issue, can you please reopen the issue using the template to tell us what browser you use?

hello , I m using chrome version 88 the last version , but I thinking  use web-push could be more easily...

**Comment by faviocabral** [comment]
I'm starting to think that firebase message only works on https...
