### ISSUE TITLE
Auth - account linking

### ISSUE THREAD

**Issue by klinki** [firebase/firebase-js-sdk#444]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.8.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Hi guys, I would like to link multiple auth providers to account. 

I tried to follow documentation: https://firebase.google.com/docs/auth/web/account-linking but I have a problem with `currentUser` object. It doesn't contain `link()` method

#### Steps to reproduce:
Use `firebase.auth().currentUser.link()`

see following error in console:

> firebase.auth(...).currentUser.link is not a function

Note: I've noticed similar problem is also on polymer firebase: https://github.com/firebase/polymerfire/issues/91   but suggested method `linkWithCredential()` doesn't exist either.

**Comment by bojeil-google** [comment]
`link` has been removed since version 4.x.x. This has been updated in the references but the docs need to be fixed. You should use `linkWithCredential` instead.

**Comment by klinki** [comment]
You are right, `linkWithCredential` actually exists. Thanks!  I haven't seen it when I inspected `currentUser` object in console
