### ISSUE TITLE
alpha: Type 'LoadBundleTask' is not generic

### ISSUE THREAD

**Issue by peterpeterparker** [firebase/firebase-js-sdk#4441]
### [REQUIRED] Describe your environment

  * Firebase SDK version: "firebase": "^0.900.12"
  
### [REQUIRED] Describe the problem

When I try to start my (Stencil) app which I migrated  to the Firebase SDK Alpha I get the following error:

> [ ERROR ]  TypeScript: ./node_modules/@firebase/firestore/dist/exp/index.d.ts:858:53
>          Type 'LoadBundleTask' is not generic.
>
>   L857:   */
>   L858:  catch<R>(onRejected: (a: FirestoreError) => R | LoadBundleTask<R>): Promise<R | LoadBundleTaskProgress>;
>   L859:  /**

Happy to help to debug it but not sure where to start.

I also spotted in issue #4381  almost the same exception but in my case, I don't use `Timestamp` and the msg does not contains much information.

#### Steps to reproduce:

```
git  clone https://github.com/deckgo/deckdeckgo/ -b firebase_alpha
cd deckdeckgo/studio
npm ci
npm run start
```

#### Relevant Code:

Signin component:

https://github.com/deckgo/deckdeckgo/blob/bd41dd2b192ff366ccb660532a988f73b0169b6c/studio/src/app/components/core/app-signin/app-signin.tsx#L3

Firebase init:

https://github.com/deckgo/deckdeckgo/blob/firebase_alpha/studio/src/app/utils/editor/firestore.utils.ts

Auth state change:

https://github.com/deckgo/deckdeckgo/blob/firebase_alpha/studio/src/app/services/auth/auth.service.ts

**Comment by wu-hui** [comment]
Hey, sorry for the late reply, we are working on a fix already: https://github.com/firebase/firebase-js-sdk/pull/4207

This should address the issue.

**Comment by peterpeterparker** [comment]
Nice thx for the fix! I'll give it a try when released 🚀
