### ISSUE TITLE
CDN Link in the README is out of date

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-js-sdk#445]
### [REQUIRED] Describe your environment

  * Operating System version: all
  * Firebase SDK version: all
  * Firebase Product: all

### [REQUIRED] Describe the problem

The CDN link in the README points to `4.0.0`

#### Relevant Code:

http://jsbin.com/rinilu/edit?js,console

```html
<script src="https://www.gstatic.com/firebasejs/4.0.0/firebase.js"></script>
```

**Comment by Feiyang1** [comment]
It's being addressed by https://github.com/firebase/firebase-js-sdk/pull/1303
