### ISSUE TITLE
FR: Expose firestore network events

### ISSUE THREAD

**Issue by wooliet** [firebase/firebase-js-sdk#4454]
### Environment

  * Operating System version: macOS 11.2
  * Browser version: Chrome 88.0.4324.146
  * Firebase SDK version: 8.2.3
  * Firebase Product: firestore

### The problem

We have users who will very often be using our app under very poor network conditions. When simulating this, I can see firestore producing logs related to network issues, but I can find no way to tap into those events. 

On plain document `get`, the "unavailable" error code is thrown, but:

1. It does not seem practical to try and hook into every document `get` in the app
2. That error code i[s not produced on document or collection snapshot listeners](https://github.com/firebase/firebase-js-sdk/issues/4089#issuecomment-731345568)

It would be extremely useful if we were able to attach an event handle to the firebase instance to have access to network related events.

The main goal is to inform the user that their network is poor and use of the app will be degraded. 

#### Steps to reproduce:

In Chrome dev tools, at the network panel, add a custom network profile using 1 for up and down speeds and then use your firestore dependent app.

![image](https://user-images.githubusercontent.com/1421908/107545399-da7cb280-6b90-11eb-9393-bc62d733dcf8.png)

**Comment by wu-hui** [comment]
Hey, sorry for the late reply.

Your request is similar to https://github.com/firebase/firebase-android-sdk/issues/947

Please note you can get more or less what you want from this comment: https://github.com/firebase/firebase-android-sdk/issues/947#issuecomment-547537941

Also an explanation of why we do not expose network events: https://github.com/firebase/firebase-android-sdk/issues/947#issuecomment-548144542

Thanks.
