### ISSUE TITLE
Feature Request: add isSupported to firebase.messaging and firebase.analytics

### ISSUE THREAD

**Issue by RaviH** [firebase/firebase-js-sdk#4474]
Current firebase api provides `firebase.messaging.isSupported()` and `firebase.analytics.isSupported()`. Please add the same/similar feature to firebase alpha.

Please see: https://github.com/firebase/firebase-js-sdk/issues/4381#issuecomment-778417724

**Comment by hsubox76** [comment]
I know it needs to be added to messaging but I just checked and it is exported from analytics. Are you not seeing it?
<img width="593" alt="Screen Shot 2021-02-16 at 9 45 04 AM" src="https://user-images.githubusercontent.com/10716545/108101234-cc6cdd00-703b-11eb-915e-e3dcbe3cb4b8.png">

**Comment by zwu52** [comment]
You should see messaging's `isSupported` in the latest release w/ https://github.com/firebase/firebase-js-sdk/pull/4665
