### ISSUE TITLE
Warning: It looks like you're using the development build of the Firebase JS SDK...

### ISSUE THREAD

**Issue by offg777** [firebase/firebase-js-sdk#4482]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home 64-bit operating system, x64-based processor
  * Browser version: Google Chrome Version 88.0.4324.182 (Official Build) (64-bit)
  * Firebase SDK version: 
```json
"dependencies": {
    "@firebase/app": "^0.6.4",
    "@firebase/firestore": "^1.14.5",
    "firebase": "^7.14.5"
},
"devDependencies": {
    "firebase-tools": "^8.20.0"
}
```
  * Firebase Product: all_ (auth, database, storage, etc)
  * Angular: 9.1.7

#### Steps to reproduce:
`It looks like you're using the development build of the Firebase JS SDK...`

How do I get rid of it?

#### Relevant Code:

Typescript
```typescript
import firebase from 'firebase/app'
import 'firebase/app'
import 'firebase/firestore'
import 'firebase/auth'
```

#### Code in context:

```typescript
import { Injectable } from '@angular/core'
import { AppService } from './app.service'

import firebase from 'firebase/app'
import 'firebase/app'
import 'firebase/firestore'
import 'firebase/auth'

@Injectable()
export class FirebaseService {

    constructor( readonly appService: AppService ) { }

    app = new Promise<firebase.app.App>( async ( resolve, reject ) => {
        try {
            const response = await fetch( '/__/firebase/init.json' )
            const config = await response.json()
            const app = firebase.initializeApp( config )
            resolve( app )
        } catch ( error ) {
            console.error( error )
            reject( error )
        }
    } )

    auth = firebase.auth
    firestore = firebase.firestore
}
```

**Comment by hsubox76** [comment]
I'm not sure why you're getting that message specifically but you have some redundant imports and dependencies. You don't need to npm install `@firebase/app` and `@firebase/firestore` as separate dependencies if you already have `firebase`, and if you have `import firebase from 'firebase/app'` you don't need a second line saying `import 'firebase/app'.

I think you also usually don't need to have `firebase-tools` installed locally in your project, unless you have some use for it you haven't mentioned.

The only way you should be able to get that message if you're doing `import * from 'firebase'` or `import firebase from 'firebase'` (no `/app`) somewhere, or you're including `firebase.js` using a `<script>` tag somewhere. Could that be happening in another file?

**Comment by offg777** [comment]
I was able to track down the code that was incorrectly importing firebase, but it took awhile. I feel like the warning should state something about what file the incorrect import is in. This way, it isn't so hard to understand where I went wrong.
