### ISSUE TITLE
FR: client only mode (db with no remote link)

### ISSUE THREAD

**Issue by hville** [firebase/firebase-js-sdk#45]
It would be nice to be able to initiate a client-only database (no url, no remote link). Use cases:

* viewStore seperate from the datastore
* prototypes, stubs and testing
* components with common interfaces

My specific use case is that the model data (what is shared) needs to be heavily transformed on the client side (monte carlo simulations in web worker) so that an internal view DB is needed in addition to the shared model DB.

Given that firebase database lib is  already over 100kb it feels akward need another lib (pouch db, lokijs, gun, ...) for internal app use to implement similar functionalities in a different API.

This is partly related to #34 (testing) since it would also facilitate creating and unit-testing independent module and components by removing all of the console registering and development server requirements.

## Edit

I found out I can use `firebase.initializeApp({databaseURL: 'x.y.z'}, 'local').database().goOffline()` but it feels like a bit of hack. Is it the correct way to do it or is this likely to fail in the future?

**Comment by hville** [comment]
FWIW i closed this issue since it could work as described.
It still doesn't work for me because the es6 exports for node and the browser are different and incompatible. I can't get it to work with rollup which is likely another issue.

**Comment by jshcrowthe** [comment]
I'd love to hear more about the rollup issue. If you could get me an isolated repro (and open a new issue) I'd love to take a look.

**Comment by hville** [comment]
Thanks @jshcrowthe , I don't know if what I am encountering is a bug, a feature or my incompetence so I did not really know where to park it. In any case, I've opened #47 in case something can be done.
