### ISSUE TITLE
Cloud Firestore: document whether calling `.onSnapshot` multiple times with the same query will have the reads be shared or not 

### ISSUE THREAD

**Issue by vinayluzrao** [firebase/firebase-js-sdk#4501]
It is unclear whether calling the method `.onSnapshot(...)` method, of the `DocumentReference` and `Query` types, multiple times and with the same "logical" query (i.e. not necessarily the same `Query` or `DocumentSnapshot` object, but with identical querying parameters) will:

- multiply the amount of reads, or
- have the optimization where the reads are shared among all listeners.

This is very useful information for properly minimizing the read cost and client network bandwidth usage.

**Comment by thebrianchen** [comment]
@vinayluzrao Firestore bills you based on the number of reads performed by the SDK. The first query you perform charges you for the reads, but subsequent queries that include those read documents will not bill you unless the underlying documents have changed. The [section](https://firebase.google.com/docs/firestore/pricing) "Listening to query results" explains the pricing mechanics in more detail.

Also, note that after 30 minutes, the server stops tracking changes to the query on behalf of the client. When a client resumes after this point, the server has to re-run the whole query to see what changed, which bills you for the size of the resulting document set.

**Comment by vinayluzrao** [comment]
@thebrianchen I'm aware it works that way for a single query snapshot listener.

But, to clarify, are you saying that in this scenario I described in the issue, where `onSnapshots()` is called multiple times causing multiple snapshot listeners to be active at once, the reads performed by the sdk are the same as if only a single listener was active?

**Comment by thebrianchen** [comment]
@vinayluzrao If the multiple listeners are listening to the same collection, you will only be charged once for the read (assuming the underlying documents in the collection do not change). Adding additional `onSnapshot` listeners to that same collection will not cost you additional reads.
