### ISSUE TITLE
{ignoreUndefinedProperties: true} causing FirebaseError: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by Huolju** [firebase/firebase-js-sdk#4502]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.1
  * Browser version: safari 14.0.2
  * Firebase SDK version: 8.2.6
  * Firebase Product: firestore / rules

### [REQUIRED] Describe the problem

If I add the following option in my firebase client `firestore.settings({ ignoreUndefinedProperties: true });`, when I try to read or write a document I always get `FirebaseError: Missing or insufficient permissions.`

#### Relevant Code:

I noticed the problem running my web app in the emulator but I was also able to reproduce it in my unit tests

Rules (this is a dummy version my rules are more complicated but to I went back to the basics to find out the issue):
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false
      function userIsAuthenticated() {
        return request.auth != null
      }
      match /users/{userId} {
            allow read, write: if debug(userIsAuthenticated())
      }
    }
  }
}
```

Note: when I run my test it looks like the debug() is not logged as if the rules where not even run... 

```javascript
import * as firebase from "@firebase/rules-unit-testing";

// initialize Firestore client
export function getFirestore(auth?: TokenOptions) {
  let firestore = firebase
    .initializeTestApp({ projectId: MY_PROJECT_ID, auth: auth })
    .firestore();
  firestore.settings({ ignoreUndefinedProperties: true });
  return firestore;
}
```

```javascript
describe("Firebase Rules", () => {
  export const auth_user = {
    uid: "user_1",
    email: "user_1@njc-software.com",
  };

  it("Can read user information if user authenticated", async () => {
    const db = getFirestore(auth_user);
    const userDoc = db.collection("users").doc("user_1");
    await firebase.assertSucceeds(userDoc.get());
  });

  it("Can write user information if user authenticated", async () => {
    const db = getFirestore(auth_user);
    const userDoc = db.collection("users").doc("user_1");
    await firebase.assertSucceeds(userDoc.set({ nickname: "toto" }));
  });
});
```

Best,
Julien.

**Comment by thebrianchen** [comment]
@Huolju Thanks for filing an issue with detailed repro steps! I'll take a stab at reproducing the error and report back with my findings.

**Comment by thebrianchen** [comment]
@Huolju Thanks for filing an issue with detailed repro steps! I'll take a stab at reproducing the error and report back with my findings.

**Comment by thebrianchen** [comment]
@Huolju Sorry for the delay! I was able to repro the error, but nothing immediately obvious stands out. I'll look into this issue more next week.

**Comment by thebrianchen** [comment]
@Huolju When you call `initializeTestApp().firestore()`, Firestore is initialized with settings based on the auth and projectId objects you pass in. Calling `firestore.settings()` by default overrides all existing settings with the passed in settings, unless you pass in `merge: true` (see [docs](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#optional-merge)).

So, to ensure that the original settings are preserved, you'll have to do:
```
firestore.settings({ ignoreUndefinedProperties: true, merge: true });
```

I'm going to mark this issue as closed, as it's WAI, but feel free to ask any other questions you may have!

**Comment by Huolju** [comment]
@thebrianchen Thanks a lot and sorry to have missed this.

I don't want to take too much of your time but I just want to make sure. You mentioned that auth and projectId could be affected by `firebase.settings()`? 

In that case, maybe it will make more sense to remove the `merge` option from these options because you cannot set the projectId or the auth object here right?

I will write some feedback directly on the documentation page for this, I guess it is the right place to report this.

Thanks!

**Comment by thebrianchen** [comment]
@Huolju No worries! The issue you filed first came up in #3354 and #2619 if you want to get some more context. We considered applying `merge` on default, but that would result in a breaking change. That being said, we definitely should make the overriding behavior more obvious in the documentation. Thanks for the suggestion!
