### ISSUE TITLE
alpha:  Module '"../../app-types"' has no exported member '_FirebaseService'.

### ISSUE THREAD

**Issue by peterpeterparker** [firebase/firebase-js-sdk#4505]
### [REQUIRED] Describe your environment

  * Firebase SDK version: "firebase": "^0.900.14"

### [REQUIRED] Describe the problem

When I try to start my (Stencil) app which I migrated  to the last Firebase SDK Alpha I get the following error:

> [ ERROR ]  TypeScript: ./node_modules/@firebase/storage-types/exp/index.d.ts:18:23
>           Module '"../../app-types"' has no exported member '_FirebaseService'.
>
>     L18:  import { FirebaseApp, _FirebaseService } from '@firebase/app-types';
>     L19:  import { CompleteFn, FirebaseError, NextFn, Unsubscribe } from '@firebase/util';
>
> [29:19.8]  build failed, watching for changes... in 19.06 s

#### Steps to reproduce:

```
git  clone https://github.com/deckgo/deckdeckgo/ -b firebase_alpha
cd deckdeckgo/studio
npm ci
npm run start
```

#### Relevant Code:

The service  which I use to implement the storage features (according output, I guess it is related):

https://github.com/deckgo/deckdeckgo/blob/firebase_alpha/studio/src/app/services/storage/storage.online.service.ts

**Comment by hsubox76** [comment]
Missed `packages/storage-types/exp` in PR https://github.com/firebase/firebase-js-sdk/pull/4461/files. We can change the line now for a quick fix or just go a head and do the complete planned removal of `storage-types/exp`, depending on how soon we will cut the next exp release.

**Comment by peterpeterparker** [comment]
No rush when it comes to me. Thx for the feedack, will of course continue testing alpha as soon as this will be published, happy to help.

**Comment by Feiyang1** [comment]
Similar to https://github.com/firebase/firebase-js-sdk/issues/4392. We need to hide our internal typings.

**Comment by Feiyang1** [comment]
I actually don't understand what makes stencil care about the internal typings. I tried webpack and rollup and both compiled successfully.

**Comment by peterpeterparker** [comment]
#4392 which is also an issue coming from me. do I have a not correct import in my application?

stencil uses rollup underneath aka it's a rollup build

**Comment by Feiyang1** [comment]
Just released 0.900.15. I tried to build your repo and it worked without errors.
Your imports look good. It might be some special rollup configuration that stencil applies. Anyway, I think we should hide our internal typings. 

I do see that you are importing types from `@firebase/auth-types`. One thing to note is we are retiring the `-types` packages, and will export types directly from `@firebase/auth` once https://github.com/firebase/firebase-js-sdk/pull/4487 is merged.

**Comment by Feiyang1** [comment]
Closing. Feel free to reopen if there are still issues.

**Comment by peterpeterparker** [comment]
@Feiyang1 perfect, I am able to boot the app now, no more typescript errors. thx 👍
