### ISSUE TITLE
Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution.

### ISSUE THREAD

**Issue by agersoncgps** [firebase/firebase-js-sdk#453]
According to the Firebase Cloud Firestore documentation for orderBy this should work:

`var facultyQuery = facultyRef.where("Middle School", "==", true).orderBy('bb_last_name', 'desc');`

I also tried this to make sure it wasn't the Map data causing issues:

`var facultyQuery = facultyRef.where("department", "==", "Core Teacher").orderBy('bb_last_name', 'desc');`

However it produces the error: 

`Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution. (firestore/failed-precondition).`

Both of these simpler cases work just fine:
```
var facultyQuery = facultyRef.orderBy('bb_last_name', 'asc');
var facultyQuery = facultyRef.where("department", "==", "Core Teacher");
```

But when I combine the where and the orderBy, something I have done before with other Firestore collections, it fails. The documentation also states that "...queries that only use equality clauses don't need additional indexes" so I did not think I needed one.

The link to create an index does appear if you run adb logcat if you are running on Android, but not in the Chrome error console, which is where I think it should be. Where would an iOS developer see it?

<img width="413" alt="spkcb" src="https://user-images.githubusercontent.com/336441/33860505-35cd16ea-dea7-11e7-8bca-c2539af1a6e7.png">

**Comment by compojoom** [comment]
@agersoncgps - did you find what was the problem in your case? I'm actually running into the same with this query:
```js
    firebase.firestore().collection('fertilizings')
      .where('company_id', '==', 'UPoHN1GMxlqLpSFEsnzp' )
      .where('active_crop_uid', '==', 'BWkgxDxU27K0scE3al0x')
      // .orderBy('created', 'desc')
      .get()
      .then(snap => {
        console.log('works')
      })
      .catch(error => error)
```
this is the data I'm trying to order
<img width="733" alt="grafik" src="https://user-images.githubusercontent.com/693770/35495002-d7f65a34-04be-11e8-8475-634a6d83afc6.png">

If I don't use orderBy - the query works. The second I add orderBy - it fails...

**Comment by compojoom** [comment]
@agersoncgps - I had the same error as you. It turns out you need to set an index. But you know this already? https://github.com/invertase/react-native-firebase/issues/515

**Comment by agersoncgps** [comment]
Yes, I think the documentation did not make it entirely clear in this scenario, but you do in fact need an index. It was also confusing for me that I had to go into adb logcat to see the url for creating the index. I would have expected it in the error console.

**Comment by afdolriski** [comment]
in case you can't open the generated link from the log you need to ensure the link pointed to the right account, for example:
```
https://console.firebase.google.com/u/0/project
```

make sure the number (in this case is zero) before the **/project** is pointing to the account that has the project
