### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_4__firebase__.b.ref is not a function

### ISSUE THREAD

**Issue by OmarKhattab** [firebase/firebase-js-sdk#456]
### [REQUIRED] Describe your environment

  * Operating System version: macos high sierra v. 10.13.2
  * Firebase SDK version: current: 4.9.0
  * Firebase Product: db

#### Steps to reproduce:

I am trying to update my users photoURL in my database while using the user.updateProfile function.
error: TypeError: __WEBPACK_IMPORTED_MODULE_4__firebase__.b.ref is not a function
#### Relevant Code:

```javascript
const ChangeProfilePicture = (props, {authUser}) => {
const change = () => authUser.updateProfile({
  photoURL: props.photoURL
}).then(function() {
  db.ref(`users/${authUser.uid}`).set({
photoURL:props.photoURL
});
  
  console.log(authUser.photoURL)
}).catch(function(error) {
  console.log(error)
});
  return <div>
    <div> Change Your Profile Picture </div>
    <input value={props.photoURL} onChange={props.getProfilePictureURL} placeholder={"attach a link to an image to change your profile"}/> <br />
    <button onClick={change}> submit </button>
  </div>
}
```

**Comment by jshcrowthe** [comment]
@OmarKhattab from what you've provided it doesn't seem like your `db` variable is being properly set though I can't tell. Can you please include a more detailed repro so we can help you debug the issue?

**Comment by rommelpe** [comment]
I'd like to check if you are still having issues here, @OmarKhattab. If you could provide a minimal [repro](https://stackoverflow.com/help/minimal-reproducible-example) of your app that we can run locally, that would be a great help for us to investigate further.

You may also consider upgrading your JS SDK to the [latest version](https://firebase.google.com/support/release-notes/js).
