### ISSUE TITLE
when did Node 8.0.0 or greater become a requirement?

### ISSUE THREAD

**Issue by jthegedus** [firebase/firebase-js-sdk#457]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu
  * Firebase SDK version: latest
  * Firebase Product: all

### [REQUIRED] Describe the problem
When did 
> Before you can start working on the Firebase JS SDK, you need to have Node.js 8.0.0 or greater installed on your machine.

become a requirement? I can't seem to find a mention of this over at https://firebase.google.com/docs/web/setup

#### Relevant Code:

Client SDK

**Comment by jshcrowthe** [comment]
This requirement is only for the development workflow which is separate from the Node.js engine support (which we compile to work in the active LTS versions of Node).

This type of discussion is probably better for the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk), so feel free to pick up the conversation there if you have further questions/concerns.
