### ISSUE TITLE
Firestore compound query - documentation not mentioning any limitation regarding combining not-in and inequality?

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-js-sdk#4587]
### [REQUIRED] Describe your environment

  * Operating System version: _____ NA
  * Browser version: _____ NA
  * Firebase SDK version: _____ v8.2.2
  * Firebase Product: _____ Firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

This [post](https://stackoverflow.com/questions/66499618/firestore-compound-query-combining-not-in-and-inequality) on stackoverflow describes it but here is a copy paste:

I want to perform a compound query combining an inequality < and not-in

```
collection("somecollection)
.where("field1", "<", somevalue)
.where("field2", "not-in", [value1,value2,value3] 
Looking at the documented queries limitations in Firestore this should be possible
```

But I get the following error:

> FirebaseError: Invalid query. All where filters with an inequality (<, <=, !=, not-in, >, or >=) must be on the same field. But you have inequality filters on 'field1' and 'field1'

This is not documented in the [queries limitation](https://firebase.google.com/docs/firestore/query-data/queries#query_limitations)

**Comment by Feiyang1** [comment]
Good catch! Thanks for the report. 
@samtstern Can we get the doc updated?

**Comment by samtstern** [comment]
Yep I'm on it!

**Comment by samtstern** [comment]
Just submitted a docs change to correct this information, it should be published automatically in the next day or so.
