### ISSUE TITLE
signInWithPopup doesn't work in Firefox (Google, Facebook), but works in Safari/Chrome

### ISSUE THREAD

**Issue by olso** [firebase/firebase-js-sdk#4590]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Big Sur 11.2
  * Browser version: Firefox 86
  * Firebase SDK version: 8.2.10
  * Firebase Product: auth
  * React: 17.0.1

#### Steps to reproduce:

**Fails in Firefox**

https://user-images.githubusercontent.com/7975158/110214232-f596c580-7ea3-11eb-8a30-183728d8e2c9.mov

**Works in Safari !!!**

https://user-images.githubusercontent.com/7975158/110214449-d0568700-7ea4-11eb-8a3e-3e59ae1dec82.mov

#### Relevant Code:

`signInFirebasePopup` is called with onClick, not asynchronously

```typescript
const getAuthProvider = (
  providerId: "facebook" | "google" | "apple",
): Firebase.auth.AuthProvider => {
  switch (providerId) {
    case "facebook": {
      const provider = new Firebase.auth.FacebookAuthProvider();
      provider.addScope("public_profile");
      provider.addScope("email");
      return provider;
    }
    case "google": {
      const provider = new Firebase.auth.GoogleAuthProvider();
      provider.addScope("profile");
      provider.addScope("email");
      return provider;
    }
    default: {
      throw new Error("Invalid provider");
    }
  }
};
```

```typescript
export const signInFirebasePopup = async (
  providerId: "facebook" | "google" | "apple",
): Promise<ExtractedFirebaseProfileData> => {
  try {
    const provider = getAuthProvider(providerId);
    // await reloadFirebaseUser(); // This causes errors, flow may fail because its asynchronous
    const userCredential = await Firebase.auth().signInWithPopup(provider);
    const profileData = extractProfileData(userCredential);

    return profileData;
  } catch (e) {
    await logoutFirebase(); // dump state
    throw e;
  }
};
```

**Comment by looptheloop88** [comment]
I wasn’t able to replicate this issue using the SDK version 8.2.10 and the [latest one](https://firebase.google.com/support/release-notes/js). The signInWithPopup is working fine for Firefox 86 64-bit running in MacOS Big Sur 11.2.1.
 
Did you see any error logs generated when the error occurred? It would help if you could provide a minimal, but complete sample project that I can run locally to replicate this issue. Also, have you tried using the quickstart sample project to see if the issue persists?

**Comment by olso** [comment]
There were no errors, but, somehow, Google now works, but Facebook still doesn't. Maybe it has to do something with Firefox Facebook Container?

**Comment by looptheloop88** [comment]
Hi @olso, thanks for the confirmation. I tried the Facebook login again using a Firefox browser and it worked fine. You may try to use our [quickstart sample project](https://github.com/firebase/quickstart-js/tree/master/auth) for Facebook login or authentication, then see if the issue persists.
