### ISSUE TITLE
Auth emulator warning message types missing

### ISSUE THREAD

**Issue by Joebayld** [firebase/firebase-js-sdk#4591]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.2
  * Browser version: Chrome 88
  * Firebase SDK version: 8.2.10
  * Firebase Product: auth

#### Steps to reproduce:
Installed the firebase client library via `npm i firebase`

I'm still having an issue with the types not showing the change. 
![image](https://user-images.githubusercontent.com/9399317/110226658-01838700-7ea6-11eb-9dd3-1ac0fc07a482.png)

I see the PR for this - https://github.com/firebase/firebase-js-sdk/pull/4119 

I'm not sure how to get the latest version though? I'm on the latest version of firebase but looking at the `node_modules` path, the `@firebase` library is out of date. How could this happen?

**Comment by Joebayld** [comment]
An update. This seems to be the issue. The types are being referenced from: https://github.com/firebase/firebase-js-sdk/blob/8ba98cb8610dedcbff785ff46a5ce5a2c548e194/packages/firebase/index.d.ts#L3141

And not from the `@firebase/auth-types`. Not sure why - but I think this is what needs to be updated.

**Comment by samhorlbeck** [comment]
Hi @Joebayld, thanks for filing this. We're tracking the issue internally in b/182168072

**Comment by binajmen** [comment]
Any update on that topic?

**Comment by hatboysam** [comment]
I am still seeing this (v8.10.0) ... is this something which is only fixed in 9.0+?

**Comment by sam-gc** [comment]
@hatboysam yep only fixed in 9.0+. I'm going to go ahead and close this issue. The typing is correct in v9 and we won't be patching v8.
