### ISSUE TITLE
Failed to execute 'open' on 'Window' with invalid URL 'https://cyberblitz-3f5a6.firebaseapp.com%0D/__/auth/handler?

### ISSUE THREAD

**Issue by razermouse** [firebase/firebase-js-sdk#4600]
Hi, 

I've got a project that recently started having the above issue and I have no idea why. I had been able to successfully have my application login into the development environment (CodeSandBox.io) with no issues. The authentication with Firebase still works in my staging environment (I can log in).

I think for some reason, the Unicode for 'enter' (%0D) is being injected into the URL in multiple places which causes the URL to be incorrect.

**Comment by hsubox76** [comment]
Can you provide some more info? I'm guessing from context that you're using auth. What auth method are you using to sign in? You mentioned that your development and staging environment don't have this problem. Can you describe the environment that does have the problem?

How do you get your Firebase config? (The config object you pass to `firebase.initializeApp()`) Is it in a separate file? How do you read it? The "authDomain" in that object should be where it's getting the first part of the URL from, and if it's being read from a text file that file might have a trailing carriage return.
