### ISSUE TITLE
Broken types imports

### ISSUE THREAD

**Issue by TeoTN** [firebase/firebase-js-sdk#4604]
### Describe your environment

  * Operating System version: Ubuntu
  * Browser version: latest
  * Firebase SDK version: 8.2.10
  * Firebase Product: auth (auth, database, storage, etc)

### Describe the problem
Key typescript interfaces are not available for single-line imports when using firebase and create-react-app.

#### Steps to reproduce:

An example is importing `User` interface. Ideally, this is what I'd expect from a normal library to allow:
```
import { User } from 'firebase/auth';
```

Unfortunately, the Firebase's internal structure is rather intricate and wrapped in namespaces. Until v7, I was importing `User` using this trick:
```
import { User } from 'firebase/index'; // Resolved to index.d.ts
```
But this has stopped working with v8. My IDE suggested importing as follows:
```
import firebase from 'firebase';
import User = firebase.User;
```
To my taste, this is pretty messy, requiring additional lines of code and making it difficult to read. But apart from that, this doesn't work with Create React App, ending up in the following error:
```
`import =` is not supported by @babel/plugin-transform-typescript
Please consider using `import <moduleName> from '<moduleName>';` alongside Typescript's --allowSyntheticDefaultImports option.
```
Even though my `tsconfig.json` does include `"allowSyntheticDefaultImports": true,` 🤷‍♂️
Currently the only working way of getting `User` "imported" is:
```
import firebase from 'firebase';
type User = firebase.User;
```

It looks like a bug not to be able to import types in a single line of code and a regression compared to v7

**Comment by hsubox76** [comment]
You can also just use `firebase.User` wherever you use the type, the second line is only needed if you want to shorten the name, which is understandable.

However, in the upcoming modularized version of Firebase that's currently in alpha now, you should be able to import types just as you want:
```
import { User } from 'firebase/auth';
```

You can sign up and [try the alpha](https://github.com/firebase/firebase-js-sdk/issues/4368) if you want, or just wait until it's officially released.

**Comment by TeoTN** [comment]
Thanks for replying - I'd say neither seems suitable for me, writing namespace in front of every type, in every line using Firebase's types would make the code less legible, would artificially add length to all lines of code using it, and is generally inconvenient.
Using alpha version is also not exactly the kind of stability I'm looking for...

This is though a regression, types were easily available in previous major version, maybe they could be re-exported again easily somehow?

**Comment by DellaBitta** [comment]
Hi @TeoTN,

The modular SDK has shipped now and is no longer in the alpha state. Checking in to see if this solves your problem. Thanks!

**Comment by TeoTN** [comment]
That's cool! I'm afraid it's been over 2 years now and I don't use Firebase anymore, so closing the issue.
