### ISSUE TITLE
FirestoreDataConverter not working with update

### ISSUE THREAD

**Issue by Joebayld** [firebase/firebase-js-sdk#4611]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.2
  * Browser version: Chrome 88
  * Firebase SDK version: 8.2.10
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When using the `withConverter` function, `update` doesn't use the converter. 

In my app, I combine the snapshot id to my data model with a converter, then remove the id when saving back to firestore. This works great when using the `get` and `set` methods. But if I need to update a document, the id gets stored in my database. 

#### Steps to reproduce:
Create a converter that ignores some data when saving to firestore. 
Update a document with that converter. 
You will see that all the data was passed through to the document.
#### Relevant Code:

```typescript
interface SomeData {
  id: string
  name: string
}

const SomeDataConverter: firebase.firestore.FirestoreDataConverter<SomeData> = {
  toFirestore (data: SomeData) {
    return {
      name: data.name
    }
  },
  fromFirestore (snapshot) {
    return {
      id: snapshot.id,
      name: snapshot.data().name
    }
  }
}

const example: SomeData = {
  id: '1',
  name: 'Adam'
}

firestore
.collection('my_collection')
.doc('1')
.withConverter(SomeDataConverter)
.set(example)

// you will find that the id is ignored and the document only contains the name field. 

await firestore
.collection('my_collection')
.doc('1')
.withConverter(SomeDataConverter)
.update(example)

// you will find that the id is now stored in the document. this shouldn't happen
```

I did find a workaround but it's not elegant.. 
```typescript 
await firestore
.collection('my_collection')
.doc('1')
.update(SomeDataConverter.toFirestore(example))
```
I feel like this should work? There shouldn't be a reason why the converter wouldn't want to convert the data.

**Comment by schmidt-sebastian** [comment]
@Joebayld  Thanks for filing this. 

The converter is meant to make it easier for Firestore developers to enforce a schema. It's main purpose is to simplify conversion between user owned model objects and theFirestore data model. For this to work, we need to know what schema to apply with each operation. This schema for `set()` and `get()` calls is the based on the typings of the `CollectionReference<T>` or `DocumenrReference<T>`.

`update()` on the other hand doesn't use `T` as its data model. It uses a slightly different representation to allow you to update a deeply nested field directly (e.g. `update('foo.bar', 'foobar')` for a `CollectionReference<{ foo: { bar: string }})>`). This representation is not compatible with the current `FirestoreDataConverter` concept and as such, we currently do not offer converter support for `update()`.
