### ISSUE TITLE
FR: DocumentData as generic type

### ISSUE THREAD

**Issue by jsakas** [firebase/firebase-js-sdk#4646]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.6
  * Browser version: Chrome latest
  * Firebase SDK version: 8.2.10
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Using Firestore with TypeScript I've found its very useful to type the documents that come back from either `db.collection` or `db.doc`. So far I have found the only way to do this is using type assertion, but it seems like it would be very useful to allow `DocumentData` to be a generic type which would offer some flexibility to us developers on how we write our code. This is especially useful for me because of wrapping database calls in hooks such as `useCollection` and `useDocument`. 

So right now the types for these functions look like this:

```typescript
    collection(collectionPath: string): CollectionReference<DocumentData>;
    doc(documentPath: string): DocumentReference<DocumentData>;
    collectionGroup(collectionId: string): Query<DocumentData>;
```

So then I have to do things like this to type the values that come back from the queries:

```typescript
const data = snap.data() as Product;

// or

db.collection('products').doc('12345').get() as firebase.firestore.DocumentSnapshot<Product>;
```

I think it would be really useful if we updated the types to be something like this:

```typescript
    collection<T = DocumentData>(collectionPath: string): CollectionReference<T>;
    doc<T = DocumentData>(documentPath: string): DocumentReference<T>;
    collectionGroup<T = DocumentData>(collectionId: string): Query<T>;
```

And then I can write:

```typescript
const p = await database.doc<Product>('products/123').get().then(snap => snap.data());
// p is already a Product!
```

I notice that some other classes allow generics but not these which are most commonly used in the Firebase docs.

**Comment by var-const** [comment]
Thank you for your suggestion! Unfortunately, we cannot recreate objects of a type `T` in the implementation without a user-specified callback. Note that simply casting would not really work if `T` is a class type (the result of the cast won't contain the right methods and would fail an `instanceof` check). The intended way to achieve similar functionality is by using [`withConverter`](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter), would that work for your use case?

**Comment by jsakas** [comment]
Thanks for the info. I hadn't seen withConverter, so I will look into it. I figured there must be another way to do it but just wasn't sure.

**Comment by var-const** [comment]
Glad it helped! I will close this issue for now, but feel free to reopen or open a new one should you run into any trouble.
