### ISSUE TITLE
Intermittent SecurityError on signInWithCustomToken

### ISSUE THREAD

**Issue by Jack-2025** [firebase/firebase-js-sdk#4657]
* Operating System version: Linux Mint 19.3
  * Browser version: Chrome 87.0.4280.141 (Official Build) (64-bit)
  * Firebase SDK version: firebase sdk 7.5.4; firebase/auth 0.15.0
  * Firebase Product: auth

Hello everyone,

I'm having an intermittent SecurityError on Chrome when calling signInWithCustomToken,
`Blocked a frame with origin "[URL]" from accessing a cross-origin frame.`

Unfortunately I'm not sure how to reproduce the problem right now, but I'd appreciate if I can get some feedback, or whether this might be a problem with the Firebase SDK or if it's more likely to be a problem with the caller code (an Angular app).  The former seems less likely, since the only parameter to signInWithCustomToken is the token string.

**Comment by looptheloop88** [comment]
Hi @Jack-2025, it seems that the error you've provided has nothing to do with the Firebase JS SDK. I might be wrong, so please share with us a complete stack trace of the error.
 
It's also hard to tell whether this is an issue with the SDK or not, since it can't be reproduced consistently.
