### ISSUE TITLE
Firebase Auth high percentage of errors calling GrantToken (Token Service API)

### ISSUE THREAD

**Issue by vieira** [firebase/firebase-js-sdk#4666]
### Describe your environment

  * Operating System version: macOS 10.15.7 (Catalina) (also observed in Windows, Linux multiple versions)
  * Browser version: Safari 13.1.3 (also observed in Chrome, Firefox, multiple versions)
  * Firebase SDK version: 8.3.1 (but also observed in multiple prior versions)
  * Firebase Product: auth

### Describe the problem

From some months now we see an elevated number (and percentage) of errors in calls to the Token Service API (`google.identity.securetoken.v1.SecureToken.GrantToken`) that are made with the tokens generated by Firebase (Browser key, iOS Key, Android Key).

The only library that we use calling this endpoint from the frontend, that we can think of, is Firebase Auth.

![Screen Shot 2021-03-22 at 19 10 36](https://user-images.githubusercontent.com/207460/112045063-53810980-8b42-11eb-91e6-bb83492d1ef7.png)

![Screen Shot 2021-03-22 at 19 28 35](https://user-images.githubusercontent.com/207460/112047170-d4d99b80-8b44-11eb-9dfc-b729bf1fee3c.png)

From what I understand this endpoint would be called by Firebase Auth with a refresh token to obtain a new token when the existing one is expiring (?).

We were able to confirm that network going down results in retries with exp backoff and that the exchange works when the network comes back. 

Not sure in what other circumstances an error can occur (e.g. server responding with 4xx, etc), how these would be retried and if that could cause some kind of loop that would justify this high number of requests/errors.

We also saw the issues reported in #3222 and #2824 but in our case Firestore is not used.

#### Steps to reproduce:
Unfourtunately after many attempts to reproduce we were unable to consistently do it, however we continue to see an elevated % of errors in the Token Service API (GrantToken call) coming from the "Browser Key" generated by Firebase.

We also see "Quota Exceeded" errors in Sentry related to calls to the Identity Tookit endpoinds that we assume are related to this issue.

**Comment by looptheloop88** [comment]
Hi @vieira, issues of this nature are best directed to the [Firebase support](https://firebase.google.com/support/troubleshooter/report/bugs) channel. They have the tools to check the errors, rate and API keys in question.
