### ISSUE TITLE
Emulators wipe mock data on second close

### ISSUE THREAD

**Issue by simeon9696** [firebase/firebase-js-sdk#4681]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 20H2
  * Browser version: Chrome Version 89.0.4389.90 (Official Build) (64-bit)
  * Firebase SDK version: 8.3.1
  * Firebase Product:  Firestore emulators

### [REQUIRED] Describe the problem
The firestore emulator does not retain the mock data when it is started for a second time.

#### Steps to reproduce:
 - Inital import, run `firebase emulators:start --import=./mock --export-on-exit` # Runs fine, db emulator is populated with data
 - Close emulator
 - Start emulator again `firebase emulators:start --import=./mock --export-on-exit` # db emulator is wiped no data present

I would expect that it exports the same file with added data, if any, when it's exiting but if that assumption is wrong please let me know. 

Note: I'm also running the auth emulator and the data from the export persists through every emulator startup

**Comment by looptheloop88** [comment]
Hi @simeon9696, I wasn't able to replicate the issue. Using the same steps that you've shared, the database contents saved locally were successfully imported and the changes made were successfully exported when the emulator was shut down.

Please make sure that Firestore is actually using the emulator with the correct port.

`firestore.useEmulator("localhost", 8081);`

<img width="454" alt="Screen Shot 2021-03-27 at 12 33 05 AM" src="https://user-images.githubusercontent.com/80330521/112663669-12fff380-8e94-11eb-94f6-edd690e94450.png">

**Comment by simeon9696** [comment]
Hi @looptheloop88 should I use `8081` specifically or any port available?

**Comment by looptheloop88** [comment]
Yes, you may use any available port in your machine.

**Comment by simeon9696** [comment]
Hi @looptheloop88 I haven't been able to reproduce the error and everything is working as it expected. It  does not clear the data on shutdown. I should note this issue occurred with `firebase-tools 9.7.0` and I've since upgraded to `9.8.0.` I'm not sure if that helped.
