### ISSUE TITLE
signInWithEmailAndPassword doesn't validate email (it never throws auth/invalid-email)

### ISSUE THREAD

**Issue by loomchild** [firebase/firebase-js-sdk#4687]
### [REQUIRED] Describe your environment

  * Operating System version: Linux Debian Testing / Bullseye  
  * Browser version: Firefox 82.0b4
  * Firebase SDK version: 8.3.1
  * Firebase Product: auth

#### Steps to reproduce:

1. Call `signInWithEmailAndPassword` with the following email: `jarek@test.c`.
2. The function throws `auth/user-not-found` instead of `auth/invalid-email`. It means that the latter error will never be thrown despite being mentioned in the documentation, because such user can't be registered so it won't be found. Due to this, there's no way of validating email format before registering the user.

#### Remarks

The same issue applies to `fetchSignInMethodsForEmail`, it accepts any email address. Only `createUserWithEmailAndPassword` seems to be throwing `auth/invalid-email` error. 

This is problematic, since there is no way to validate email format before user fills the entire registration form, whereas before the error was thrown right away, so it could be shown to the user before navigating to the registration form.

I believe it's a regression, as previously these methods were throwing `auth/invalid-email` error on badly formatted email as described in documentation.

**Comment by looptheloop88** [comment]
Hi @loomchild, this is working as expected. A user can't sign-in until it's registered. It's also not possible to use an email address with invalid format in the registration process.
 
Since `createUserWithEmailAndPassword()` can catch invalid email formats, there's no way for a user to sign-in with an invalid email format. If a user not registered in the first place, then `signInWithEmailAndPassword()` is expected to throw a user not found error.

**Comment by loomchild** [comment]
OK, but the question is which error will be thrown first by signIn function if I pass unknown email which is also not valid: user not found or invalid email?

I believe that if it's the former, then the latter error can't be thrown by this function at all, which means documentation is wrong. I also think the behavior has changed recently which could suggest a regression, since I was receiving invalid email errors when signin in previously.

If this is the expected behavior then there's no way ro validate email format before registering the user (I also tried with, which is problematic in my particular case.

**Comment by looptheloop88** [comment]
Hi @loomchild, the current version of the SDK (8.3.1) is throwing the user not found error. Could you recall the version of the SDK which throws the invalid email error?

**Comment by loomchild** [comment]
I will try, I think it was 7.x.x. Another possibility is that the Firebase backend has changed - in this case I won't be able to verify it.

Could you clarify what should be the desired behavior of this function?

**Comment by looptheloop88** [comment]
This is an intended behavior. The registration will validate email address format, then the authentication will validate if the user exists or not.

**Comment by loomchild** [comment]
OK, in that case if t’s intended that it should not possible to validate email format before registering the user, then there’s nothing to fix, feel free to close this ticket.

To give you a bit more context, my UI is currently as follows:
1. User enters an email
2. If email does not exist (checked via signin or fetch method), then I show a custom registration form (could contain many fields, but the email is not displayed as it’s taken from the previous step)
3. Once the user fills the form, I call createUser. If the email entered was in invalid format, I receive the error at this point and need to redirect the user back to the first screen, losing all the entered registration data. 

I tested it few months ago and I am pretty sure the invalid-email error was thrown immediately in step two, which allowed me to avoid showing the registration form to users who entered an invalid email. If that’s the intended behavior, I would need to rethink the UX.
