### ISSUE TITLE
Missing word in invalid SMS verification code error message

### ISSUE THREAD

**Issue by chiptech-kirk** [firebase/firebase-js-sdk#4692]
* Operating System version: Windows 10
  * Browser version: Firefox 87
  * Firebase SDK version: 8.3.1
  * Firebase Product: auth

Messages like "The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure [to] use the verification code provided by the user." are missing the word 'to' as marked.

I found matches for 'be sure use' in:

packages/auth/src/error_auth.js
packages-exp/auth-exp/src/api/authentication/mfa.test.ts
packages-exp/auth-exp/src/api/authentication/sms.test.ts
packages-exp/auth-exp/src/api/authentication/sms.test.ts
packages-exp/auth-exp/src/core/errors.ts

**Comment by looptheloop88** [comment]
Hi @chiptech-kirk, I was able to replicate the issue. I've filed an internal bug for this, however there's no definite timelines or details for when it will be fixed. I will keep this thread posted for any updates.
