### ISSUE TITLE
FCM - Request is missing required authentication credential.

### ISSUE THREAD

**Issue by peili** [firebase/firebase-js-sdk#4697]
### [REQUIRED] Describe your environment

  * Operating System version: OSX 11.2.1
  * Browser version: Chrome 89.0
  * Firebase SDK version: 8.3.1
  * Firebase Product: Messaging (FCM)

#### Steps to reproduce:
Followed the steps described in: https://firebase.google.com/docs/cloud-messaging/js/client
Give Permission for PushNotification. After Page refresh Firebase Messaging will throw an error.

#### Relevant Code:

Component where user can opt in for Push Notifications. No errors.
```javascript
const token = await messaging.getToken({
          vapidKey: firebaseConfig.vapidKey
        });
```

Main Application Reload after `messaging.getToken`  was called will throw an error.
```javascript
import 'firebase/messaging';
messaging = firebase.messaging() 
```
This will throw an error:

> instrument.js?ea14:136 POST https://fcmregistrations.googleapis.com/v1/projects/projectId/registrations 401
> index.esm.js?8071:464 Uncaught (in promise) FirebaseError: Messaging: A problem occurred while subscribing the user to FCM: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (messaging/token-subscribe-failed).

**Comment by looptheloop88** [comment]
Hi @peili, please check if the value of your `vapidKey` is valid and doesn't contain any spaces.

**Comment by peili** [comment]
Hi @looptheloop88 , yes we used the public key from the WebPush Certificate Page in the Firebase Console. 
A workaround to prevent this error to call usePublicVapidKey right after messaging(). However usePublicVapidKey is deprecated.

```
  Vue.prototype.$messaging = firebase.messaging();
  Vue.prototype.$messaging.usePublicVapidKey(firebaseConfig.messagingPublicKey);
```

**Comment by looptheloop88** [comment]
Hi @peili, I tried `messaging.getToken({ vapidKey: 'BPHcTKVtOSm-...' })` and it's working fine. Could you please share a [minimal, but complete sample project](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally to replicate the issue?

**Comment by zwu52** [comment]
@looptheloop88  thanks for handling this. Let me know if I could help w/ anything.
