### ISSUE TITLE
Initializing functions emulator using firebase@8.3.1 throws "TypeError: Cannot read property 'instanceIdentifier' of undefined"

### ISSUE THREAD

**Issue by acmcc** [firebase/firebase-js-sdk#4698]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.7 
  * Browser version: any
  * Firebase SDK version: 8.3.1
  * Firebase Product: functions emulator

#### Steps to reproduce:

1. Run the functions emulator with `firebase emulators:start`.
1. Initialize the functions emulator in client code.

#### Relevant Code:

```javascript
firebase.functions().useEmulator("localhost", 5001);
```

#### Stack Trace:

```
TypeError: Cannot read property 'instanceIdentifier' of undefined
    at Component.eval [as instanceFactory] (index.esm.js:843)
    at Provider.getOrInitializeService (index.esm.js:285)
    at Provider.getImmediate (index.esm.js:153)
    at FirebaseAppImpl._getService (index.esm.js:219)
    at FirebaseAppImpl.firebaseAppImpl.<computed> [as functions] (index.esm.js:498)
    at Object.serviceNamespace [as functions] (index.esm.js:474)
```

#### Other Notes:

Downgrading to firebase@8.3.0 fixes the issue.

**Comment by looptheloop88** [comment]
Hi @acmcc, I tried replicating the issue, but I wasn't able to. I used the [quickstart project](https://github.com/firebase/quickstart-js/tree/master/functions) and tested different versions of the SDK (8.3.0, 8.3.1, 8.3.2), but all of them worked fine. I didn't get any errors similar to what you've encountered.

Would you mind sharing a [minimal, but complete sample](https://stackoverflow.com/help/minimal-reproducible-example) of a project that I can run locally to replicate this issue?
