### ISSUE TITLE
Document creation failing

### ISSUE THREAD

**Issue by kidsonfilms-python-rules** [firebase/firebase-js-sdk#4699]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.2.2
  * Browser version: **not used, using Node.js version: 14.6.0**
  * Firebase SDK version: 8.3.1
  * Firebase Product: Firestore (auth, database, storage, etc)
  * Electron (Main Process) version: 12.0.1 

### [REQUIRED] Describe the problem
When trying to create a new document, the following error occurs:
```js
(node:87126) UnhandledPromiseRejectionWarning: TypeError: path.indexOf is not a function
    at Function.ResourcePath.fromString (/Users/siddharth/dev/DJTorsten/node_modules/@firebase/firestore/dist/node-cjs/database-ee8aa46d-0243185b.js:536:22)
    at doc (/Users/siddharth/dev/DJTorsten/node_modules/@firebase/firestore/dist/node-cjs/database-ee8aa46d-0243185b.js:21706:71)
    at CollectionReference$1.doc (/Users/siddharth/dev/DJTorsten/node_modules/@firebase/firestore/dist/node-cjs/database-ee8aa46d-0243185b.js:26046:64)
    at /Users/siddharth/dev/DJTorsten/main.js:301:38
```
I am using the following function to create the document:
```js
// partyCodeGen is defined and is new
db.collection('parties').doc(partyCodeGen).set({
    data: "mydata"
})
```
#### Steps to reproduce:
1. Create a Firebase Project and set-up Firestore with one collection (in my case called `parties`)
2. Create an Electron project and place the above code in the Main Process (`main.js`)
3. Install firebase using `npm i firebase`
4. Start the Electron application using `npm start`
#### Relevant Code:

```javascript
// partyCodeGen is defined and is new
db.collection('parties').doc(partyCodeGen).set({
    data: "mydata"
})
```

**Comment by hsubox76** [comment]
I get this same error if the argument provided to `doc()` is an object and not a string. Can you double check that `partyCodeGen` is a string?

**Comment by kidsonfilms-python-rules** [comment]
@hsubox76 I tried adding `.toString()` to the end of `partyCodeGen` and it worked!
