### ISSUE TITLE
`Duplicate identifier` errors when compiling a project which links a module

### ISSUE THREAD

**Issue by SamVerschueren** [firebase/firebase-js-sdk#474]
### Describe your environment

  * Operating System version: macOS Sierra
  * Firebase SDK version: 4.9.0
  * Firebase Product: auth, database

### Describe the problem

We are using a monorepo and have a module (A) which depends on another module (B). Both of `firebase` listed as dependency. Compiling module B is not a problem. Compiling module A however is. These errors are showing up:

<img width="762" alt="screen shot 2018-01-28 at 19 19 31" src="https://user-images.githubusercontent.com/1913805/35587954-8841c716-05ff-11e8-9a09-85915e40aed1.png">

I tweeted about this, and @DanielRosenwasser replied that it should be fixed in here.  https://twitter.com/drosenwasser/status/957872358978609152

I was able to solve it with `paths` mappings in `tsconfig.json`, but would be nice if it just worked without.

#### Steps to reproduce:

1. Create 2 modules which both have `firebase` as dependency
2. Link one module to the other `yarn add link:../module-b`
3. Compile

(Better to look at the reproduction repository)

#### Relevant Code:

Here's the repository I created to reproduce the problem. https://github.com/SamVerschueren/firebase-duplicate-tsd

// @jshcrowthe

**Comment by PascalPrecht** [comment]
I can confirm this issue. This a problem that exists with `firebase` version `4.9.0+`.

**Comment by PascalPrecht** [comment]
🎉
