### ISSUE TITLE
firebase-messaging-sw.js:326 Uncaught ReferenceError: window is not defined - Trying to register fireabase-messaging-sw fails

### ISSUE THREAD

**Issue by flygis** [firebase/firebase-js-sdk#475]
### [REQUIRED] Describe your environment

  * Operating System version: Virtual Ubuntu 16.04.2 (Xenial) on Windows 10
  * Firebase SDK version: 4.9.0 (npm package)
  * Firebase Product: messaging
  * Webpack 3.10.0

### [REQUIRED] Describe the problem
Installed firebase with npm, created firebase-messaging-sw.js file into project root folder, started webpack, and on page load got error during sw registration:
Uncaught ReferenceError: window is not defined firebase-messaging-sw.js:326
#### Steps to reproduce:
Using Webpack 3 with ReactJS, install firebase, configure webpacak to make service-worker file as a separate js file in folder where webpack-dev-server serves js files. Initialize firebase messaging. At service-worker registration got this error: Uncaught ReferenceError: window is not defined firebase-messaging-sw.js:326

#### Relevant Code:
Debugging the service worker file I found out that the line of code that causes the error is following:
var d = window.webpackHotUpdate;

**Comment by mmermerkaya** [comment]
Sounds like an issue with Webpack's [hot module replacement](https://webpack.js.org/concepts/hot-module-replacement/).
