### ISSUE TITLE
UNKNOWN: 14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-js-sdk#4780]
This code assumes it will receive a FirestoreError without asserting such and can end up throwing an unwrapped exception from grpc

https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/firestore/src/remote/datastore.ts#L126-L131

**Comment by dconeybe** [comment]
Hi @nbransby. Thank you for reporting this. I'll get a fix out in the next couple of days.
