### ISSUE TITLE
Error on app.d.ts about static credential

### ISSUE THREAD

**Issue by condorman** [firebase/firebase-js-sdk#48]
Hello,

In **app.d.ts** and **firebase.d.ts** the function credential return a Promise, but when i compile the application i have this error in console: " the function .then() missing". 
In the firebase-js-sdk the function "credential" return firebase.auth.AuthCredential ?

static credential (verificationId : string , verificationCode : string ) : firebase.Promise < any > ;
==>
static credential (verificationId : string , verificationCode : string ) : firebase.auth.AuthCredential ;

Is a goog solution?

Thank you!

**Comment by bojeil-google** [comment]
This operation is synchronous and it should return a firebase.auth.AuthCredential. It doesn't return a promise.

**Comment by jsayol** [comment]
@bojeil-google - I think @condorman is referring to `firebase.auth.PhoneAuthProvider.credential()`, which [according to the d.ts files](https://github.com/firebase/firebase-js-sdk/blob/fd0728138d88c454f8e38a78f35d831d6365070c/typings/firebase.d.ts#L199) and t[he documentation](https://firebase.google.com/docs/reference/js/firebase.auth.PhoneAuthProvider#.credential) should return a `firemase.Promise<any>` but actually (and correctly) returns a `firebase.auth.AuthCredential`.

**Comment by jsayol** [comment]
This has been fixed so this issue can be closed now.

**Comment by jshcrowthe** [comment]
Thanks @jsayol!
