### ISSUE TITLE
onSnapshot() results in `unknown` snapshot data type

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-js-sdk#4812]
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: Chrome latest
  * Firebase SDK version: 9.0.0-beta.1
  * Firebase Product: firestore

#### Relevant Code:

**index.ts**
```ts
import { collection, getFirestore, onSnapshot } from "firebase/firestore";

function main() {
  const firestore = getFirestore();
  const colRef = "col";

  onSnapshot(
    collection(firestore, colRef),
    (snap) => {
      if (snap.empty) {
        return;
      }
      const documents = snap.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(), // error: Spread types may only be created from object types
      }));
    },
    (error) => {
      console.warn(error);
    }
  );
}
```

In this code `snap` is `QuerySnapshot<unknown>` which makes it hard to use `.data()`.  This can be fixed by either:

  * Casting `doc.data() as any`
  * Using `onSnapshot<any>`

Is this the intended behavior in the new SDK?

**Comment by samtstern** [comment]
cc @puchesjr

**Comment by schmidt-sebastian** [comment]
TypeScript does not retain the type of the generic class unless the type is part of the API surface. Unfortunately, `CollectionReference<T>` does not refer to `T` in any of its members. This means that we have to change the API to accommodate this. I will prepare a PR, but we need to obtain approval for this API change internally.
