### ISSUE TITLE
Installations: Create Installation request failed on googlebot

### ISSUE THREAD

**Issue by dbanisimov** [firebase/firebase-js-sdk#4823]
### [REQUIRED] Describe your environment

  * Browser version: googlebot [Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/89.0.4389.127 Safari/537.36]
  * Firebase SDK version: 9.0.0-beta.1
  * Firebase Product: app

### [REQUIRED] Describe the problem
We're seeing an error in our monitoring coming from firebase code executed by google bot:

```
FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument." (installations/request-failed).
    at getErrorFromResponse (webpack://introwise-experts/node_modules/@firebase/installations/dist/index.esm2017.js:94:25)
    at async (webpack://introwise-experts/node_modules/@firebase/installations/dist/index.esm2017.js:176:8)
    at registerInstallation (webpack://introwise-experts/node_modules/@firebase/installations/dist/index.esm2017.js:549:19)
```

It's coming from googlebot only, both mobile and desktop bots, and doesn't seem to affect real users. 

The first appearance of the issue was around 4/16/21, 6:37 PM  pacific time.

**Comment by looptheloop88** [comment]
Hi @dbanisimov, sorry for the additional loop. Please open a ticket via Firebase [support](https://firebase.google.com/support) channel. They have the tools and resources to check issues related to Firebase Installations Service (FIS).

I will close this issue now.
