### ISSUE TITLE
Version 9 doesn't work through Skypack

### ISSUE THREAD

**Issue by wperron** [firebase/firebase-js-sdk#4830]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.10
  * Browser version: Deno 1.9.2
  * Firebase SDK version: 9.0.0-beta.1
  * Firebase Product: app, firestore

### [REQUIRED] Describe the problem

I'm trying to run a simple script in Deno to add data to Firestore, I tried the stable version of the SDK but it doesn't work because it relies on `XMLHttpRequest` doesn't support (our problem, not Firebase's). I then tried version 9 in beta but Skypack is erroring out with this error message:

```text
Download https://cdn.skypack.dev/firebase@0.900.25/app?dist=es2017&dts
Download https://cdn.skypack.dev/firebase@0.900.25/firestore?dist=es2017&dts
Download https://cdn.skypack.dev/new/firebase@v0.900.25/dist=es2017/app
Download https://cdn.skypack.dev/new/firebase@v0.900.25/dist=es2017/firestore
Download https://cdn.skypack.dev/error/build:firebase@v0.900.25-8cD1Qp4U3uEeSjoy6Fo6
Download https://cdn.skypack.dev/error/build:firebase@v0.900.25-8cD1Qp4U3uEeSjoy6Fo6
[Package Error] "firebase@v0.900.25" could not be built. 
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
ENOENT: no such file or directory, open 'firebase/compat/installations/dist/index.esm.js'
ENOENT: no such file or directory, open '/tmp/cdn/_8cD1Qp4U3uEeSjoy6Fo6/node_modules/firebase/compat/installations/dist/index.esm.js'
error: Uncaught Error: [Package Error] "firebase@v0.900.25" could not be built. 
    at https://cdn.skypack.dev/error/build:firebase@v0.900.25-8cD1Qp4U3uEeSjoy6Fo6:19:7
```

#### Steps to reproduce:

Here's the full repro in Deno:
```typescript
// deno run --no-check this.ts
import firebase from "https://cdn.skypack.dev/firebase@0.900.25/app?dist=es2017&dts";
import "https://cdn.skypack.dev/firebase@0.900.25/firestore?dist=es2017&dts";

firebase.initializeApp({
  apiKey: "***********************************",
  authDomain: "*******.firebaseapp.com",
  projectId: "**********",
  storageBucket: "***********.appspot.com",
  messagingSenderId: "**********************",
  appId: "1:************:web:***************************"
});

const db = firebase.firestore();
try {
  const docRef = await db.collection("test").add({
    ts: new Date().toISOString(),
  });
  console.log(`successfully added record ${docRef.id}`);
} catch(err) {
  console.error(err)
}
```

**Comment by Feiyang1** [comment]
I think I know what is causing the error. We need to remove [this block ](https://github.com/firebase/firebase-js-sdk/blob/master/packages-exp/firebase-exp/package.json#L55-L58) in package.json.

Put this compiling error aside, you'll have to rewrite your code in order to use v9. v9 is a total revamp of the SDK, and has a very different API. You need to import individual functions instead of a single `firebase` object. You can check out our [upgrade guide](https://firebase.google.com/docs/web/modular-upgrade?authuser=0) and the [reference docs](https://firebase.google.com/docs/reference/js/v9?authuser=0).

**Comment by wperron** [comment]
Yeah I've trying a bunch of different things to get it to work inside Deno, flip-flopping between v8 and v9
