### ISSUE TITLE
sendSignInLinkToEmail sends no mail

### ISSUE THREAD

**Issue by Rampdisli** [firebase/firebase-js-sdk#4831]
Hello,

I use this code to send a signInLink to the customer. 
`  auth.sendSignInLinkToEmail(email, {
    url: getURL(),
    handleCodeInApp: true,
  }).then(() => {
    this.setState({ showMessage: true });
    localStorage.setItem('emailForSignIn', email);
  })
  .catch((error) => {
    this.setState({ error });
  });`

It worked the last few years but now it is no longer send the mail.
The Promise is resolving and no error is catched.
I have @firebase/auth@0.7.2 in use.

**Comment by samhorlbeck** [comment]
Are you using the [firebase auth](https://www.npmjs.com/package/@firebase/auth) package directly? Please try installing [the core library](https://www.npmjs.com/package/firebase) instead (and removing the direct Auth dependency)

**Comment by Rampdisli** [comment]
I think I figure it out. I have some problem with wrong smtp config on firebase.

**Comment by looptheloop88** [comment]
I also tried this using the [quickstart sample project](https://github.com/firebase/quickstart-js/tree/master/auth) for Firebase Authentication and it worked fine. I was able to receive email notification and sign-in successfully.
 
It seems that you’ve figured out the issue. I will close this now. Please reopen if you have any other concerns or questions.
