### ISSUE TITLE
Error Install Firebase

### ISSUE THREAD

**Issue by Waingapucoder** [firebase/firebase-js-sdk#4843]
I'm having trouble installing the latest version of firebase (8.4.2)

I took pictures during the installation process, drawing the process in order.

Step 1
![snap-1](https://user-images.githubusercontent.com/62747828/116370231-c6198f00-a83c-11eb-90d6-6f115b23954d.png)

Step 2
![snap-2](https://user-images.githubusercontent.com/62747828/116370244-c9147f80-a83c-11eb-8a30-63dc9dddde20.png)

step 3
![snap-3](https://user-images.githubusercontent.com/62747828/116370266-cd409d00-a83c-11eb-9641-3cf9fa65dce0.png)

step 4
![snap-4](https://user-images.githubusercontent.com/62747828/116370282-d2055100-a83c-11eb-9331-1d54df90408a.png)

step 5
![snap-5](https://user-images.githubusercontent.com/62747828/116370328-dc274f80-a83c-11eb-9bb7-bb292a5a65a6.png)

On view, the error message becomes "error for @ firebase / performance @ 0.4.11 Unexpected end of JSON input while ..."

I've tried deleting all the files in the ".npm / _logs" folder, but nothing has changed either.

This also occurs when trying to install a version of firebase earlier than the current one (8.3.2)

The same error message came from "error fro @ firebase / auth @ 0.16.4 Unexpected end of JSON input while parsing ..."

Thank you.

**Comment by looptheloop88** [comment]
Hi @Waingapucoder, I wasn't able to replicate this issue. The SDK version `8.4.2` was successfully added to my project dependencies without any error.

Please try to delete the `node_modules` directory and the `package-lock.json` file, then install the dependencies again. You may also want to update the version of your Firebase Tools, Node and NPM.

**Comment by Waingapucoder** [comment]
I'm not sure what the cause is, but it was resolved successfully with the `npm cache clean --force` command
Thank you for answering. @ looptheloop88
