### ISSUE TITLE
Storage useEmulator

### ISSUE THREAD

**Issue by Kevinand11** [firebase/firebase-js-sdk#4873]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
What is the use of adding the useEmulator function for the storage object in firebase when there is no storage emulator in the emulator suite? 

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
firebase.storage.useEmulator('localhost', xxxx)
```

This fails because there is no exposed port for the storage emulator in the emulator suite

**Comment by abeisgoat** [comment]
Give it a few days :) The SDK release came before the emulator launch to make life easier for a early-access partners.

**Comment by laurentpayot** [comment]
@Kevinand11 try running `firebase --open-sesame storageemulator` to unlock the emulator :wink:

**Comment by Kevinand11** [comment]
@laurentpayot Thanks, I did that and it worked. A storage emulator is started whenever I start the emulator suite.

I can upload files to the storage emulator from the emulator UI, but whenever I try to upload a file programmatically, I get the error "cannot convert variables for cloud storage rules runtime" and it shuts down my emulator hub

**Comment by Kevinand11** [comment]
@laurentpayot Yeah thanks, I think I will just wait for the official release
