### ISSUE TITLE
Auth emulator not used with currentUser.linkWithPopup 

### ISSUE THREAD

**Issue by patelnav** [firebase/firebase-js-sdk#4879]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.3.1 (20E241)
  * Browser version: Version 90.0.4430.93 (Official Build) (x86_64)
  * Firebase SDK version: 9.10.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem
currentUser.linkWithPopup doesn't use auth emulator, instead going to accounts.google.com

#### Steps to reproduce:
Enable emulator using auth.useEmulator(...)
Login with auth.signInAnonymously()
Attempt to link with popup
```javascript
auth.currentUser.linkWithPopup(new firebase.auth.GoogleAuthProvider()) 
```
##### PROBLEM: 
<img width="368" alt="Screen Shot 2021-05-07 at 12 48 54 AM" src="https://user-images.githubusercontent.com/1034157/117399426-869f1280-aece-11eb-9fac-803d1f687078.png">

Note: ```javascript auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())``` (skipping anonymous login) works as desired: 
<img width="339" alt="Screen Shot 2021-05-07 at 12 49 25 AM" src="https://user-images.githubusercontent.com/1034157/117399523-bfd78280-aece-11eb-9cd2-d6124e571bc0.png">

**Comment by looptheloop88** [comment]
Hi @patelnav, I've filed an internal bug for this issue, however we can't provide definite timelines or details for when it will be fixed. You may keep an eye out on our release notes or check this issue thread for any updates in the future.

**Comment by patelnav** [comment]
Hey sorry, meant to follow up on your request for error logs. There are no error logs pertaining to this as far as I can tell. 

Please do prioritize this bug appropriately. It makes it very difficult to test escalation of anonymous users to logged in ones without a fix. Thanks!

**Comment by weixifan** [comment]
For internal reference: the internal bug is b/188039872.
