### ISSUE TITLE
Recaptcha unnecessarily rerenders itself

### ISSUE THREAD

**Issue by majorb22** [firebase/firebase-js-sdk#4885]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.2.3
  * Browser version: Google Chrome 90.0.4430.93
  * Firebase SDK version: 8.5.0
  * Firebase Product: auth
  * ReactJS: 16.14.0

### [REQUIRED] Describe the problem
After succesfull recaptcha validation, the recaptha rerenders itself. If I access the from code, it is considered accepted, however it rerenders itself as if nothing happened. It happens with normal recaptcha and with invisible also.

#### Steps to reproduce:

https://user-images.githubusercontent.com/37476814/117684331-2f8e8b80-b1b5-11eb-8786-3b9c0a33d7c1.mov

#### Relevant Code:

```javascript
import React, { useEffect } from 'react';
import firebase from 'firebase/app';
import 'firebase/auth';


const Test = (props) => {


    useEffect(() => {
        if (!firebase.apps.length) {
            const firebaseConfig = {
                ...
            };

            firebase.initializeApp(firebaseConfig);
        }
        firebase.auth().useDeviceLanguage();
        window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('recaptcha-container', {
            'size': 'normal',
            'callback': function (response) {
                console.log(response);
            },
            'error-callback': response => {
                console.error('[RECAPTHCHA ERROR]: ', response);
            }
        });

        let phoneNumber = props.phone;
        var appVerifier = window.recaptchaVerifier;
        console.log(appVerifier);
        firebase.auth().signInWithPhoneNumber(phoneNumber, appVerifier)
            .then(function (confirmationResult) {
                console.log('CONF result', confirmationResult);
                window.confirmationResult = confirmationResult;

            }).catch(function (error) {
                console.error('[FIREBASE_ERROR]: ', error);
            });
    }, []);



    return (
        <div id="recaptcha-container" style={{ height: '50rem' }}></div>
    )
}

export default Test;
```

**Comment by looptheloop88** [comment]
Hi @majorb22, this is working as expected. You might need to update the UI of your app and hide the recaptcha container. See the sign-in flow of the [quickstart sample project](https://github.com/firebase/quickstart-js/blob/master/auth/phone-invisible.html) for your reference.
