### ISSUE TITLE
Automatically manage encryption keys for persisted data

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-js-sdk#492]
Foolow-up on https://github.com/firebase/firebase-js-sdk/issues/491

Exposing an API for managing persisted data encryption is a huge step in the field of security, but it might be hard to manage. That would be great if we could leverage two existing services to make it much more simple for developers: Google Key Management Service and Firebase Authentication. Unless we decide to use sth else instead of standard keys.

Please add `Component: Firestore`, `feature-request` and `Status: Blocked` labels.

**Comment by mikelehen** [comment]
We don't currently have any plans to integrate Google Key Management Service with the Firebase SDK, though maybe this could be a cool 3rd-party library for somebody to build.
