### ISSUE TITLE
Example: service-worker-sessions Web v9 is not working

### ISSUE THREAD

**Issue by leroytromp** [firebase/firebase-js-sdk#4923]
I ran into an issue while attempting to follow along with your documentation found here: https://firebase.google.com/docs/auth/web/service-worker-sessions

The service worker throws the following error (in the browser console):

```
Uncaught ReferenceError: window is not defined
    at new Ye (service-worker.js:845)
    at Q (service-worker.js:307)
    at Array.map (<anonymous>)
    at service-worker.js:1242
    at service-worker.js:1242
    at e.instanceFactory (service-worker.js:1242)
    at e.getOrInitializeService (service-worker.js:114)
    at e.initialize (service-worker.js:114)
    at service-worker.js:1242
    at service-worker.js:1242
Ye @ service-worker.js:845
Q @ service-worker.js:307
(anonymous) @ service-worker.js:1242
(anonymous) @ service-worker.js:1242
(anonymous) @ service-worker.js:1242
(anonymous) @ service-worker.js:114
(anonymous) @ service-worker.js:114
(anonymous) @ service-worker.js:1242
(anonymous) @ service-worker.js:1242
(anonymous) @ service-worker.js:1242
```

Below I have also attached a snippet of some of the code causing the error. As you can see there is a reference to window.localStorage, and this triggers the ReferenceError, because service workers do not have access to the `window` object.

```
class Ye extends Xe {
    constructor() {
        super(window.localStorage, "LOCAL"),
        this.listeners = {},
        this.localCache = {},
        this.pollTimer = null,
```

**Comment by Feiyang1** [comment]
@sam-gc Have we added service worker support in v9 auth?

**Comment by sam-gc** [comment]
It should work, but it's possible we've introduced a regression. That said, `getAuth()` does include a dependency on `localStorage`, which isn't available in workers. Instead, try initializing auth like this:

```js
import { initializeApp } from "firebase/app";
import { initializeAuth, indexedDBLocalPersistence, onAuthStateChanged, getIdToken } from "firebase/auth";

// Initialize the Firebase app in the service worker script.
const app = initializeApp(config);
const auth = initializeAuth(app, {persistence: indexedDBLocalPersistence});
```

(See the docs for [`initializeAuth()`](https://firebase.google.com/docs/reference/js/v9/auth.md#initializeauth))

**Comment by leroytromp** [comment]
@sam-gc Thanks for the suggestion. I can confirm that it solves the issue. The error was indeed being caused by `getAuth()` and not by `initializeApp()`.

A question: Should using `initializeAuth()` be considered a temporary workaround, or a permanent solution? In other words, will `getAuth()` support the service worker use case in the future?

If `getAuth()` is not meant to support the service worker use case, then this issue can be closed and only the Firebase documentation (firebase/snippets-web, url in my original comment) needs to be updated.

**Comment by sam-gc** [comment]
It's an open question I need to chat with the team about. We provide distinct entry points for other platforms, in which case workers would have their own dedicated `getAuth()`. Regardless the docs will need to be updated. Thanks for catching this!

**Comment by ellcrev** [comment]
How can we export the `auth` object while avoiding the `auth/already-initialized` error? My initial instinct is to do something like the following, but unfortunately this doesn't work as `getAuth` errors out due to undefined window in service worker.
```ts
export const getFirebaseAuth = () => {
  try {
    const auth = initializeAuth(app, {persistence: indexedDBLocalPersistence});
    return auth;
  } catch (e) {
    return getAuth(app);
  }
} 
```

**Comment by sam-gc** [comment]
I know this is perhaps not an ideal solution, but I'd suggest putting the auth object in a global variable. For example,

```js
export function getFirebaseAuth() {
  if (!self.firebaseAuth) {
    self.firebaseAuth = initializeAuth(...);
  }
  return self.firebaseAuth;
}
```

The issue with using `getAuth()` is that it assumes a browser DOM context

**Comment by sam-gc** [comment]
This issue is resolved; `getAuth()` now works properly in service workers.
