### ISSUE TITLE
modular SDK throws an error in rxjs

### ISSUE THREAD

**Issue by uny** [firebase/firebase-js-sdk#4937]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.7 (19H1030)
  * Browser version: Chrome 90.0.4430.212 (Official Build) (x86_64)
  * Firebase SDK version: 9.0.0-beta.2
  * Firebase Product: auth

#### Steps to reproduce:

With rxjs@7.1.0, I get a runtime error:
```
Uncaught (in promise) TypeError: Cannot read property 'isStopped' of undefined
    at Subscriber.next (Subscriber.js?4701:29)
    at newNext (index.esm2017.js?5994:823)
    at eval (index-02c0b8e8.js?43e4:2203)
```

#### Relevant Code:

moduler:
```javascript
import { getApp, getApps, initializeApp } from "firebase/app";
import { getAuth, onAuthStateChanged } from "firebase/auth";
import { Observable } from "rxjs";

const firebase = (() => {
  if (getApps().length === 0) {
    return initializeApp({/* OPTIONS */});
  } else {
    return getApp();
  }
})();
new Observable(
  (observer) => {
    const unsubscribe = onAuthStateChanged(getAuth(firebase), observer);
    return { unsubscribe };
  }
).subscribe(console.log);
```

compat:
```javascript
import firebase from "firebase/compat/app";
import "firebase/compat/auth";
import { getApps } from "firebase/app";
import { Observable } from "rxjs";

if (getApps().length === 0) {
  firebase.initializeApp({/* OPTIONS */});
}

new Observable(
  (observer) => {
    const unsubscribe = firebase.auth().onAuthStateChanged(observer);
    return { unsubscribe };
  }
).subscribe(console.log);
```

Both of them throw the error.

#### Additional Information
If I change the code like below, the error will be solved.
```
const unsubscribe = onAuthStateChanged(getAuth(firebase), (user) => {
  observer.next(user);
});
```

If I use firebase@8.6.2 and rxjs@7.1.0, the error also does not occur.

**Comment by jamesdaniels** [comment]
FWIW we ran into this in RxFire, here's the work-around we used in `@exp` https://github.com/FirebaseExtended/rxfire/blob/exp/auth/index.ts#L34

**Comment by Feiyang1** [comment]
@jamesdaniels Have you had a chance to debug? Any chance you already know the root cause?

**Comment by uny** [comment]
In fact, I am using rxfire@4.0.0 and found the problem.
I will try rxfire@exp, but I wonder if this issue can be fixed and should be fixed.

**Comment by jamesdaniels** [comment]
@Feiyang1 I just worked around it, my sniff test says it's a binding failure, e.g, it's expecting the callback to be a bound and not passed by reference or anonymously. Those have popped up from time to time in point releases and I've learned to program defensively around them, so doesn't surprise me.

@uny yeah we should absolutely address the root cause. [Let us know what you think of exp here](https://github.com/FirebaseExtended/rxfire/pull/1), latest canary is `rxfire@6.0.0-canary.da26625` and we'll start cutting alpha/beta releases soon.

**Comment by uny** [comment]
https://github.com/firebase/firebase-js-sdk/blob/b49345d31cdd3dfd42d65768156818dc09c7fa61/packages-exp/auth-exp/src/core/auth/auth_impl.ts#L509
```diff
-            : nextOrObserver.next;
+            : nextOrObserver.next.bind(nextOrObserver);
```
I haven't tried it yet, but this may fix the problem.

**Comment by uny** [comment]
I confirmed that this solve the issue in my environment.
I will make a PR.
