### ISSUE TITLE
Cannot read property 'container' of undefined Angular Universal

### ISSUE THREAD

**Issue by zal1000** [firebase/firebase-js-sdk#4949]
* Operating System version: Windows 20H2
  * Browser version: Angular universal pretender ( @nguniversal/builders 12.0.0, @angular/platform-server 12.0.1)
  * Firebase SDK version: 9.0.0-beta.2
  * Firebase Product: auth 

### [REQUIRED] Describe the problem
When I try to load the page, the server sends this error back

#### Steps to reproduce:
```
TypeError: Cannot read property 'container' of undefined
    at Object._getProvider (D:\Github\waik-hu\node_modules\@firebase\app\dist\index.cjs.js:268:16)
    at getAuth (D:\Github\waik-hu\dist\waik-hu\server\main.js:114683:24)
    at new AppComponent (D:\Github\waik-hu\dist\waik-hu\server\main.js:216217:72)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (D:\Github\waik-hu\dist\waik-hu\server\main.js:216258:10)
    at getNodeInjectable (D:\Github\waik-hu\dist\waik-hu\server\main.js:59399:44)
    at instantiateRootComponent (D:\Github\waik-hu\dist\waik-hu\server\main.js:65966:23)
    at createRootComponent (D:\Github\waik-hu\dist\waik-hu\server\main.js:68319:23)
    at ComponentFactory$1.create (D:\Github\waik-hu\dist\waik-hu\server\main.js:80981:25)
    at ApplicationRef.bootstrap (D:\Github\waik-hu\dist\waik-hu\server\main.js:85452:42)
    at D:\Github\waik-hu\dist\waik-hu\server\main.js:85165:64
```
#### Relevant Code:

```typescript
    //im not sure about it, but its probably that part
    const auth = getAuth();

    onAuthStateChanged(auth, user => {
      const defavatar = 'DEFAULT_IMAGE_URL_HERE';
      if(user) {
        this.userpp = user.photoURL ? user.photoURL : defavatar;
        this.msg.success(`Bejelentkezve mint: ${user.displayName}(${user.email})`)
      } else {
        this.userpp = defavatar;
      }
    });
```

**Comment by looptheloop88** [comment]
Hi @zal1000, thanks for the report. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue?

**Comment by zal1000** [comment]
https://github.com/zal1000/firebase-js-issue

TODO: replace credentials

I hope this is helpful!

**Comment by looptheloop88** [comment]
Hi @zal1000, I really appreciate the time and effort you've spent in creating the code repro. I did try to use it, however I still can't reproduce the error.

<img width="1409" alt="Screen Shot 2021-06-10 at 9 39 07 PM" src="https://user-images.githubusercontent.com/80330521/121538459-61ef0b00-ca37-11eb-8c0c-144b72269fe3.png">
<img width="804" alt="Screen Shot 2021-06-10 at 9 41 00 PM" src="https://user-images.githubusercontent.com/80330521/121538523-6ca9a000-ca37-11eb-9761-1ea29114fb24.png">

**Comment by zal1000** [comment]
Hi @looptheloop88,  when the error accrued for me I used it with SSR

And if you still can't reproduce the error, I can share the full code with you if needed

**Comment by looptheloop88** [comment]
Hi @zal1000 , it's not necessary to share the full code or repository. You may remove other parts and leave the one that will produce the error.

**Comment by zal1000** [comment]
Hi @looptheloop88 , I just noticed that you started it without SSR, when the issue accrued to me I used it with SSR, and to start it I used `npm run dev:ssr`, when I tried it in production mode, the issue also accrued to me, the commands for that is `npm run build:ssr` and `npm run serve:ssr`. I hope this was helpful, and have a great day!

**Comment by looptheloop88** [comment]
Hi @zal1000, apologies for the delay in response. I was able to reproduce the error now when using SSR build. We will check this out and update this thread accordingly.

In addition, have you tried replicating this issue using SDK v8?

**Comment by hsubox76** [comment]
Can I ask what happens if you provide the "app" argument to `getAuth()`?

So in your main.ts:
```
export const app = initializeApp(environment.firebaseConfig);
```

Then in your app.component.ts, import that `app` variable and:
```
auth = getAuth(app);
```

Does that fix anything?

**Comment by zal1000** [comment]
Hi @hsubox76 , yes, that fixes the problem! And thanks for the help! Have a great day!

**Comment by hsubox76** [comment]
Good to know there is a workaround for now. I think this is still a bug. `getAuth()` should work without the app argument. Something unusual going on with `getApp()` in SSR and prod environments perhaps.
