### ISSUE TITLE
auth/argument-error when using a third party auth provider with beta js sdk

### ISSUE THREAD

**Issue by sakettawde** [firebase/firebase-js-sdk#4950]
### [REQUIRED] Describe your environment

  * Operating System version: Mac
  * Browser version: Chrome 90.0.4430.212 (Official Build) (x86_64)
  * Firebase SDK version: 9.0.0-beta.2
  * Firebase Product: auth 

### [REQUIRED] Describe the problem

When signing in with a third party auth provider like Google/Facebook, receiving following error:
FirebaseError: Firebase: Error (auth/argument-error).

#### Steps to reproduce:
Visit codesandbox, add your own config object.
https://codesandbox.io/s/mystifying-lichterman-si8q9?file=/pages/index.js

#### Relevant Code:

```javascript
import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";

const auth = getAuth();
const provider = new GoogleAuthProvider();
signInWithPopup(auth, provider)
  .then((result) => {

})
```

The above block of code, does not work. It throws the auth/argument-error error.

**Comment by sakettawde** [comment]
Similar but not the same: #4242

**Comment by looptheloop88** [comment]
Hi @sakettawde, apologies for the delay in response and thanks for the report. First off, the relevant codes that you've provided should work.

```
import { initializeApp } from "firebase/app";
import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";

const firebaseConfig = {
   ...
};
initializeApp(firebaseConfig);

const auth = getAuth();
const provider = new GoogleAuthProvider();
signInWithPopup(auth, provider)
   .then((result) => {
      ...
});
```

I checked your code [repro](https://codesandbox.io/s/mystifying-lichterman-si8q9?file=/pages/index.js) and was able to replicate the `auth/argument-error` error. It seems you're using incorrect parameter values in [`initializeAuth()`](https://firebase.google.com/docs/reference/js/v9/auth.md#initializeauth). I highly suggest that you check its reference documentation.

```
import { initializeApp } from "firebase/app";
import { signInWithPopup, GoogleAuthProvider, initializeAuth,
 browserSessionPersistence, browserPopupRedirectResolver } from "firebase/auth";

const firebaseConfig = {
   ...
};
const firebaseApp = initializeApp(firebaseConfig);

const auth = initializeAuth(firebaseApp, {
   persistence: browserSessionPersistence,
   popupRedirectResolver: browserPopupRedirectResolver,
});
const provider = new GoogleAuthProvider();
signInWithPopup(auth, provider)
   .then((result) => {
      ...
});
```
