### ISSUE TITLE
SDK produces invalid URL for callable Cloud Functions

### ISSUE THREAD

**Issue by azzazkhan** [firebase/firebase-js-sdk#4956]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome 90.0.4430.212 (Official Build) (64-bit)
  * Firebase SDK version: 8.6.1
  * Firebase Product: functions

#### Steps to reproduce:
When I called a callable function in my Next.js project it threw a CORS error. When I inspect the dev tools I noticed that the SDK was sending the request to **http://localhost:5001/%22project-name%22,/us-central1/emailExists** instead of **http://localhost:5001/project-name/us-central1/emailExists**. Due to CORS policy, the browser blocks the request because no function was available at that URL.
#### Relevant Code:

```javascript
function MyComponent() {
  useEffect(() => {
    functions
      .httpsCallable('emailExists')({email: 'someone@example.com'})
      .then(res => console.log('Function response: ', res))
      .catch(err => console.error('Function error: ', err))
  })
  return null
}
```
```javascript
exports.emailExists = exports.emailExists = functions.https.onCall(async (data, context) => {
  const { email } = data || {}
  if (!isValidEmail(email)) throw new HttpsError('invalid-argument', 'Invalid email provided!')
  try {
    const snapshot = await firestore.collection('users').where('user', '==', email).get()
    // Email is available
    if (snapshot.empty) return { code: 'available', message: 'The provided email is not linked with any account.' }

    // The email is already bound with another account
    return { code: 'unavailable', message: 'The email is already linked with another account.' }
  } catch {}
  throw new HttpsError('unknown', 'An unknown issue occurred!')
})
```

**Comment by hsubox76** [comment]
1) Did this work in a previous version of Firebase?

2) Your url has "localhost" in it so I assume you're using `useEmulator()`?

3) If so, the `projectId` string in the url is pulled directly from your project config that you initialize Firebase with (`firebase.initializeApp({ apiKey: ..., projectId: ... })`). Do you have an extra pair of quotes around the strings in that object somehow?

**Comment by azzazkhan** [comment]
@hsubox76 No I don't have extra quotes around the string and if you loop closely it also appends a trailing comma after the project ID. I'm loading the data through environmental variables.

**Comment by looptheloop88** [comment]
Hi @azzazkhan, I tried all SDK 8.6.+ versions and I wasn't able to replicate the issue. I used the same code snippets you've shared and got the expected result from the function. Would you mind sharing a sample project that I can run locally, including the implementation for initializing the SDK and using the emulator? Also, what is the firebase-tools version you have in you machine?
