### ISSUE TITLE
Catching the error 'auth/user-token-expired' during a proactiveRefresh after revoking refreshToken

### ISSUE THREAD

**Issue by mlahp7** [firebase/firebase-js-sdk#4967]
### Describe your environment

  * Operating System version: ubuntu 18.04
  * Browser version: Chrome 90
  * Firebase SDK version: 8.2.3
  * Firebase Product: auth

### Describe the problem
When we revoke a refreshToken for a user, if the user is still active within our client application, and the expiration of the refreshToken is near (proactiveRefresh time?) an uncaught error from firebase is thrown:  
`code: "auth/user-token-expired", message: "The user's credential is no longer valid. The user must sign in again."`<br>
We understand that the error message itself is normal, but in our case we are unable to catch the error as it seems to be internal. 

Is there a way to catch this error?
#### Steps to reproduce:

Revoke the refreshToken of a user while they are logged in / authenticated and wait about an hour for the expiration of their current id token. An exception is thrown.

![image](https://user-images.githubusercontent.com/72365595/120573228-39d62b00-c3eb-11eb-9ee7-830b43512b51.png)

the stack trace continued ...
![image](https://user-images.githubusercontent.com/72365595/120573530-bbc65400-c3eb-11eb-9b13-b26c674b0b61.png)

**Comment by looptheloop88** [comment]
Hi @mlahp7, thanks for the report and patiently waiting. I'm trying to reproduce the error, but I wasn't able to. Have you tried updating the SDK version that you're using to the latest one and see if the issue persists?

Just to confirm, after you sign in and call `firebase.auth().currentUser.getIdToken(true)`, you don't need to do any action and just wait for the refreshed token to expire again. After this, the error will be thrown?

Also, could you check if the `onAuthStateChanged` listener fires when this error occurs?
