### ISSUE TITLE
import firebase version 8.6.4 cannot compile on npm install - react

### ISSUE THREAD

**Issue by unclehooptie** [firebase/firebase-js-sdk#4977]
* Browser version: nodejs v14.17.0
  * Firebase SDK version: 8.6.4

#### Steps to reproduce: npm install firebase @8.6.4 and import firebase from "firebase" within react. on npm start, recieve "failed to compile" start error

when attempting to import firebase in React, I am met with the error below.

  ./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').

by removing the FetchXmlHttpFactory import within the referenced prebuilt file above, I can get Firebase to compile correctly within React.

**Comment by armandabric** [comment]
I got the same issue when bundeling with vitejs my application with the version v8.6.4

``` 
$ vite
...
 > node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js:5:110: error: No matching export in "node_modules/@firebase/webchannel-wrapper/dist/index.esm.js" for import "FetchXmlHttpFactory"
    5 │ ...eateWebChannelTransport as p, getStatEventTarget as y, FetchXmlHttpFactory as v, WebChannel as m, Event as g, Stat as w } from "...
      ╵                                                           ~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js:5:110: error: No matching export in "node_modules/@firebase/webchannel-wrapper/dist/index.esm.js" for import "FetchXmlHttpFactory"
    at failureErrorWithLog (/home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:1466:15)
    at /home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:1148:28
    at runOnEndCallbacks (/home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:938:63)
    at buildResponseToResult (/home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:1146:7)
    at /home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:1253:14
    at /home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/armand/workspace/pepettes/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
error Command failed with exit code 1.
```

Downgrading the issue to v8.6.3 resolve the issue

**Comment by dkocich** [comment]
same issue here with WIN10, firebase@6.4.4, node 14.7.0, npm 6.14.11; it started working again after `npm i firebase@8.6.3 --save-exact`

```
./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').
```

**Comment by rudenick0309** [comment]
Same issue to me, I solved to fix this problem 
I did downgrade the firebase version to "firebase": "^8.4.1".
( maybe, the latest version of firebase is 8.6.4 or 8.6.1 )

**Comment by barakiva** [comment]
Downgraded to 8.4.3, 8.6.1, 2, and 3. Ran a clean install multiple times with `npm ci`. Still getting the same message.

**Comment by rudenick0309** [comment]
@barakiva Did you delete about firebase library in package-lock.json?

**Comment by schmidt-sebastian** [comment]
We need to publish a new version of WebChannel Wrapper.

**Comment by barakiva** [comment]
> @barakiva Did you delete about firebase packages in package-lock.json?

I deleted all of package-lock.json multiple times when NPM got stuck trying to degrade firebase. Still didn't work.

**Comment by schmidt-sebastian** [comment]
I will see if we can publish the newer WebChannel Wrapper this morning, but in the meantime an older install of Firestore should work.

**Comment by unclehooptie** [comment]
@schmidt-sebastian Thank you!

**Comment by ptxmac** [comment]
A bit premature closing of the issue? The new package haven't been published yet: https://www.npmjs.com/package/@firebase/webchannel-wrapper

**Comment by schmidt-sebastian** [comment]
We generally close issues once the necessary code changes are merged. I will ping this issue when the change is published.

**Comment by schmidt-sebastian** [comment]
Package is published.

**Comment by nelson6e65** [comment]
Thanks!
