### ISSUE TITLE
OnAuthStateChanged triggers twice

### ISSUE THREAD

**Issue by Mocsa1974** [firebase/firebase-js-sdk#4978]
Operating System version: Windows 10 64 bit
Browser version: Chrome 91.0.4472.77
Firebase SDK version: 8.6.4
Angular version: 12
Angular/fire: 6.1.5

After signed in into firebase an onAuthStateChanged triggers with a signed user's credentials. immediately after then onAuthStateChanged triggers again with a null value. After then a realtime database security rules auth variable is becomes null so i get a permission denied error message when trying to get some data from realtime database.

When I refresh a page a onAuthStateChanged triggers once, with a a user credentials but a permission denied message persists.
downgrade to firebase 8.6.0 problem solved.

Thans a lot

Peter

**Comment by Mocsa1974** [comment]
UPDATE1:
sorry. when signed in into firebase onAuthStateChanged triggers once and eveything works fine. When refresh a page onAuthStateChanged triggers again once with a signed in user credentials but a security rule auth variable is null and get a permission denied error message when getting some data from rtdb.

**Comment by looptheloop88** [comment]
Hi @Mocsa1974, thanks for the report and for patiently waiting. I tried replicating the issue, but I wasn't able to. I set the security rules to just `"auth != null"` and if the user is authenticated, the data is successfully saved to the database. I refreshed the page a couple of times, but it's still working as expected.
 
Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue?

**Comment by Mocsa1974** [comment]
Thanks for your reply.

 

we are signing in with custom token. custom token created on back-end with cloud function

 

let token = await admin.auth().createCustomToken(user.uid, {

                    venue_id: user.venue_id,

                    id: user.user_id,

                    administrator: user.administrator == '1'

                });

 

the token send back to frontend and use it in

angularfireauth object signInWithCustomToken method.

 

Best regards

Peter

**Comment by looptheloop88** [comment]
Hi @Mocsa1974, I tried a generating custom token using Admin SDK and used it with `signInWithCustomToken()`. However, I wasn't still able to reproduce the permission denied error. I have successfully saved the data to database.

If I can replicate the issue, I can have a better look into it. It would help a lot if you could share a sample project, database security rules and error logs.

**Comment by Mocsa1974** [comment]
I have found a problem. If i am using Angular/fire package a problem still exists, but when using a firebase js SDK without angularfire everything works fine. So i wrote an issue to AngularFire github.
Thanks

**Comment by looptheloop88** [comment]
Thanks for the confirmation, @Mocsa1974. I will close this issue now.
