### ISSUE TITLE
firebase/index.d.ts contains wrong type for DocumentSnapshot data()

### ISSUE THREAD

**Issue by wereHamster** [firebase/firebase-js-sdk#498]
DocumentSnapshot data() return type should be nullable (or rather, undefined-able). The same underlying issue has already been fixed in #364, but in a different file. There seems to be duplication of code between packages/firestore-types/index.d.ts and packages/firebase/index.d.ts.

```javascript
const ds: DocumentSnapshot = undefined as any
ds.data().foo // <- should be a type error
```

**Comment by samtstern** [comment]
@schmidt-sebastian can you look into this?
