### ISSUE TITLE
[discuss}:import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper'

### ISSUE THREAD

**Issue by KishaniKandasamy** [firebase/firebase-js-sdk#4984]
I got this error while running my app.Can anyone help me to resolve this?

./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').

**Comment by rudenick0309** [comment]
you find this #4977

**Comment by unclehooptie** [comment]
Clear your package lock and import the newest firebase version. The webchannel wrapper has been updated to resolve this issue.

**Comment by KishaniKandasamy** [comment]
Thanks I will import the updated version.

**Comment by KishaniKandasamy** [comment]
It works fine now :) Thanks so much

**Comment by looptheloop88** [comment]
Hi @KishaniKandasamy, thanks for the report. I will close this now, since the issue is already fixed.
