### ISSUE TITLE
Node script using firebase js sdk (v9) doesn't terminate

### ISSUE THREAD

**Issue by mgreenbe** [firebase/firebase-js-sdk#4987]
### [REQUIRED] Describe your environment

  * Operating System version: MACOS 11.5
  * Browser version: N/A
  * Firebase SDK version: 9.0.0-beta.2
  * Firebase Product: functions

### [REQUIRED] Describe the problem

A simple node script calling a cloud function (handled by the functions emulator) doesn't terminate, even though I deleted the relevant app. If I remove the function call (line labelled `(*)`) and the call to `deleteApp` (line labelled `(**)`), then the script terminates normally.

#### Steps to reproduce:

Run the script below. "Done!" is logged too the console, but the process doesn't terminate.

#### Relevant Code:

```javascript
let { initializeApp, deleteApp } = require("firebase/app")
let { getFunctions, useFunctionsEmulator, httpsCallable } = require("firebase/functions");

let config = {
// redacted!
};


async function f() {
    let app = initializeApp(config)
    let fns = getFunctions(app)
    useFunctionsEmulator(fns, "localhost", 5001)
    let helloWorld = httpsCallable(fns, "helloWorld")
    console.log(await helloWorld()) // (*)
    await deleteApp(app) // (**)
}

f().then(() => { console.log("Done!") })
```

**Comment by looptheloop88** [comment]
Hi @mgreenbe, I wasn't able to replicate the issue. The function execution was finished successfully. If you're trying to create a function that will return a promise or return the `helloWorld` value as a promise, then try to use the code snippets below:

```
 function f() {
    return new Promise(async resolve => {
      const helloWorld = await httpsCallable(fns, 'helloWorld');
      resolve(helloWorld);
    });
 }

f().then((res) => { console.log(res) })
```

Also, it would help a lot if you could share a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue.
