### ISSUE TITLE
Firestore: returns undefined on Windows but document exists

### ISSUE THREAD

**Issue by cristianpoleyJS** [firebase/firebase-js-sdk#5001]
###  Describe your environment

  * Operating System version: Microsoft Windows 10 - Version 1909 (compilation SO 18363.1556)
  * Browser version: Chrome Version 89.0.4389.90 (Build oficial) (32 bits)
  * Firebase SDK version: 8.6.3
  * Firebase Product: Firestore

### Describe the problem
In my application I have some users that use Windows and they have problems to list documents that exist in Firestore. Other users with, for example Mac, display them correctly, or the same users with Windows access the application from Firefox and it displays correctly.
As attached in the screenshots, when doing the _doc.data()_ it returns **undefined**, but that document exists in the database (is not italicized, i.e., it is not deleted) and if you access it from Firefox you can see it correctly.

![Screenshot 2021-06-09 at 16 40 39](https://user-images.githubusercontent.com/15108191/121376166-95e80480-c941-11eb-8b5f-e6cb0e67e00a.png)

#### Steps to reproduce:
I don't know how to reproduce it, I haven't managed it because I don't have Windows but it seems that there must be some combination between Windows + Chrome that makes Firebase fail.

#### Relevant Code:

```javascript
async openWatch () {
      const collection = '/namespaces/default/ExampleCollection'

      return new Promise((resolve, reject) => {
        this.exampleWatch = this.$store.getters.database
          .collection(collection)
          .doc(this.$route.params.id)
          .onSnapshot((doc) => {
            console.log(doc.data()) // This is undefined
            this.$store.dispatch('actionSetExampleCollection', doc.data())

            return resolve()
          },
          error => {
            return reject(error)
          })
      })
}
```

**Comment by var-const** [comment]
A couple of quick questions:
* for the affected users, are they unable to load _any_ documents from Firestore? Or does it only affect _one_ document or perhaps only certain documents?
* could it be that the application code on Windows somehow ends up using a different document ID from other platforms? In other words, can you please double-check that both the document ID and the full document path (including the collection IDs) is exactly the same between Windows and other platforms?

**Comment by cristianpoleyJS** [comment]
Hi @var-const 

I will answer you in parts:
- You cannot read any document from the database. It perfectly complies with the Firestore rules, if it is this would appear the "Missing of permissions..." error.
- Yes, they are the same IDs. The ID that appears in the console.log I checked it in the database and it exists, and I can access correctly.

Thank you!

**Comment by cristianpoleyJS** [comment]
Hi @var-const,

Did you see anything?

**Comment by var-const** [comment]
Sorry about the delay. I have run our testapp on Windows using Chrome and didn't see any issues with documents (I'd also expect to see more bug reports if this was widespread), so this has to be somehow specific to your configuration.

Can you please [enable logging](https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel) (`firebase.firestore.setLogLevel('debug');`) on _both_ the Windows app and one other app that works (e.g. Mac) and share both the resulting logs (please make sure to remove any sensitive information)? That would be very helpful.

Also, does this happen only when using `collection().doc()`? Can you try querying for all the documents in the collection -- would it return no documents?

**Comment by cristianpoleyJS** [comment]
Hi @var-const ,

Thank you for your response.

The problem happens in some collections, even sometimes in the same collection some documents are not listed and others are, it is very random.
For the moment, the workaround is to use Firefox instead of Chrome, could it be some configuration in the Cookie or privacy policies?
As soon as I get the results of the logs I will write it here.

Thanks again!

**Comment by var-const** [comment]
> The problem happens in some collections, even sometimes in the same collection some documents are not listed and others are, it is very random.
Are they always the same collections and documents that are undefined? Or does this change between different app runs?

Looking forward to the logs!

**Comment by cherau** [comment]
Hi. I am facing this issue https://stackoverflow.com/questions/67845455/could-not-reach-cloud-firestore-backend-connection-failed-1-times for a long time now. Any fixes ?

> @firebase/firestore: Firestore (8.6.5): Could not reach Cloud Firestore backend. Connection failed 1 times.
   Most recent error: FirebaseError: [code=permission-denied]:
   Permission denied on resource project.

**Comment by var-const** [comment]
@cherau Please open a new issue -- this error looks like a separate problem. It would also be very helpful if you could enable debug logging (`firebase.firestore.setLogLevel('debug');`) and attach your logs (please make sure to remove any sensitive information).

"Permission denied" error likely means that you need to configure [Firestore security rules](https://firebase.google.com/docs/firestore/security/get-started) on your project. By default, they are configured to reject every request -- if you haven't changed the configuration, that would explain the error.

Let's continue this conversation in the new issue.

**Comment by cristianpoleyJS** [comment]
I have not yet uploaded to production, so I have no logs available.
As soon as I have something I'll let you know.
Thanks!

**Comment by cristianpoleyJS** [comment]
Hi @var-const !!

In this case, the user is using what is described in the issue:
- Microsoft Windows 10 - Version 1909 (build SO 18363.1556)
- Version 89.0.4389.90 (Official Build) (32 bits)

He gets the error when reading the collection "CollectionFile", he gets it as null but the rules are fine (no permissions error) and in Firefox it works perfectly.

This happens to other users with other collections and having the same system configuration.

I give you the logs (note that it has entered in Firefox and can access these collections).

```
[2021-07-02T09:51:36.296Z]  @firebase/firestore: Firestore (8.6.3): FirestoreClient Initializing OfflineComponentProvider
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.783Z]  @firebase/firestore: Firestore (8.6.3): IndexedDbPersistence Starting transaction: Allocate target
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.784Z]  @firebase/firestore: Firestore (8.6.3): SharedClientState SET firestore_sequence_number_firestore/[DEFAULT]/confidential_information_bd/ 487282
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.791Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb GET owner owner {"ownerId":"qrJHmd1mvipZTZQxXfBu","allowTabSynchronization":true,"leaseTimestampMs":1625219497355}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.792Z]  @firebase/firestore: Firestore (8.6.3): IndexedDbPersistence Client 'qrJHmd1mvipZTZQxXfBu' is not zombied in LocalStorage
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.794Z]  @firebase/firestore: Firestore (8.6.3): SharedClientState SET firestore_clients_firestore/[DEFAULT]/confidential_information_bd/_qrJHmd1mvipZTZQxXfBu {"activeTargetIds":[2,6,8,44,48],"updateTimeMs":1625219498794}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.794Z]  @firebase/firestore: Firestore (8.6.3): IndexedDbPersistence Starting transaction: Execute query
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.795Z]  @firebase/firestore: Firestore (8.6.3): SharedClientState SET firestore_sequence_number_firestore/[DEFAULT]/confidential_information_bd/ 487283
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.796Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb GET owner owner {"ownerId":"qrJHmd1mvipZTZQxXfBu","allowTabSynchronization":true,"leaseTimestampMs":1625219497355}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.796Z]  @firebase/firestore: Firestore (8.6.3): IndexedDbPersistence Client 'qrJHmd1mvipZTZQxXfBu' is not zombied in LocalStorage
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.798Z]  @firebase/firestore: Firestore (8.6.3): QueryEngine Using full collection scan to execute query: Query(target=Target(namespaces/default/CollectionFile/collection_id, orderBy: [__name__ (asc)]); limitType=F)
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.800Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb GET remoteDocuments ["namespaces","default","CollectionFile","collection_id"] {"unknownDocument":null,"noDocument":{"path":["namespaces","default","CollectionFile","collection_id"],"readTime":{"seconds":1625219461,"nanoseconds":224140000}},"document":null,"hasCommittedMutations":false,"readTime":[1625219461,224140000],"parentPath":["namespaces","default","CollectionFile"]}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.802Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel sending: {"database":"projects/confidential_information_bd/databases/(default)","addTarget":{"documents":{"documents":["projects/confidential_information_bd/databases/(default)/documents/namespaces/default/CollectionFile/collection_id"]},"targetId":48,"resumeToken":"CgkIkYuo5YzE8QI="}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:38.920Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel transport opened.
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.103Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[2]}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.104Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"resumeToken":"CgkIsqaj5YzE8QI=","readTime":"2021-07-02T09:44:18.422578Z"}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.105Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[6]}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.105Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"resumeToken":"CgkIsqaj5YzE8QI=","readTime":"2021-07-02T09:44:18.422578Z"}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.105Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[8]}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.106Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"resumeToken":"CgkIsqaj5YzE8QI=","readTime":"2021-07-02T09:44:18.422578Z"}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.106Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[44]}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.107Z]  @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"resumeToken":"CgkIsqaj5YzE8QI=","readTime":"2021-07-02T09:44:18.422578Z"}}

…

chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.189Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb PUT targets <auto-key> {"targetId":48,"canonicalId":"namespaces/default/CollectionFile/collection_id|f:|ob:__name__asc","readTime":{"seconds":1625219499,"nanoseconds":102996000},"resumeToken":"CgkIlKa0t47E8QI=","lastListenSequenceNumber":487294,"lastLimboFreeSnapshotVersion":{"seconds":1625218548,"nanoseconds":704471000},"query":{"documents":["projects/confidential_information_bd/databases/(default)/documents/namespaces/default/CollectionFile/collection_id"]}}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.190Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb PUT targetDocuments <auto-key> {"targetId":0,"path":"namespaces\u0001\u0001default\u0001\u0001CollectionFile\u0001\u0001collection_id\u0001\u0001","sequenceNumber":487294}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.193Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb GET targetGlobal targetGlobalKey {"highestTargetId":276,"highestListenSequenceNumber":487289,"lastRemoteSnapshotVersion":{"seconds":1625219498,"nanoseconds":924245000},"targetCount":138}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.194Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb GET targetGlobal targetGlobalKey {"highestTargetId":276,"highestListenSequenceNumber":487289,"lastRemoteSnapshotVersion":{"seconds":1625219498,"nanoseconds":924245000},"targetCount":138}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.194Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb PUT targetGlobal targetGlobalKey {"highestTargetId":276,"highestListenSequenceNumber":487294,"lastRemoteSnapshotVersion":{"seconds":1625219499,"nanoseconds":102996000},"targetCount":138}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.196Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb PUT remoteDocuments ["namespaces","default","CollectionFile","collection_id"] {"unknownDocument":null,"noDocument":{"path":["namespaces","default","CollectionFile","collection_id"],"readTime":{"seconds":1625219499,"nanoseconds":102996000}},"document":null,"hasCommittedMutations":false,"readTime":[1625219499,102996000],"parentPath":["namespaces","default","CollectionFile"]}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.197Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb PUT collectionParents <auto-key> {"collectionId":"CollectionFile","parent":"namespaces\u0001\u0001default\u0001\u0001"}
chunk-vendors~1fb195ae.js:320 [2021-07-02T09:51:39.199Z]  @firebase/firestore: Firestore (8.6.3): SimpleDb GET remoteDocumentGlobal remoteDocumentGlobalKey {"byteSize":813812}

```

**Comment by var-const** [comment]
Thank you for these logs! Just to clarify, these logs are from running on Chrome, right?

I will take a closer look at this next week, but from a quick glance, a couple of things stand out:
- the path seems to be `documents/namespaces/default/CollectionFile/collection_id`. Is having `collection_id` as one of the identifiers intentional? (just checking in case this was supposed to be an interpolated string);
- when writing to persistent storage, forward slashes are replaced with `\u0001\u0001`. I'm not sure if this is correct -- I will check.

A couple of follow-up questions:
- Can you also post a log of accessing the same document on Windows when using Firefox? (IIUC, this works on Firefox, so I'd like to compare logs for the successful case and for the failing case)
- Can you please check if the problem still happens with persistence disabled?

**Comment by cristianpoleyJS** [comment]
Hi @var-const ,

Sorry for taking so long to respond.

> Thank you for these logs! Just to clarify, these logs are from running on Chrome, right?

Yes, these logs are in Chrome.

> - the path seems to be documents/namespaces/default/CollectionFile/collection_id. Is having collection_id as one of the identifiers intentional? (just checking in case this was supposed to be an interpolated string);

This is intentional, it is the document identifier in the _CollectionFile_ collection.

> - when writing to persistent storage, forward slashes are replaced with \u0001\u0001. I'm not sure if this is correct -- I will check.

Maybe this is the error, because in the Firefox logs I don't see them.

> - Can you also post a log of accessing the same document on Windows when using Firefox? (IIUC, this works on Firefox, so I'd like to compare logs for the successful case and for the failing case)

```
[2021-07-21T11:45:57.058Z] @firebase/firestore: Firestore (8.6.3): QueryEngine Using full collection scan to execute query: Query(target=Target(namespaces/default/CollectionFile/collection_id, orderBy: [__name__ (asc)]); limitType=F) chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.059Z] @firebase/firestore: Firestore (8.6.3): Connection WebChannel sending: {"database":"projects/project_id/databases/(default)","addTarget":{"documents":{"documents":["projects/project_id/databases/(default)/documents/namespaces/default/CollectionFile/collection_id"]},"targetId":14}} chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.083Z] @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"CURRENT","targetIds":[10],"resumeToken":"token","readTime":"2021-07-21T11:45:57.026305Z"}} chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.084Z] @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"resumeToken":"token","readTime":"2021-07-21T11:45:57.026305Z"}} chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.086Z] @firebase/firestore: Firestore (8.6.3): WatchChangeAggregator Detected inactive target 8 chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.086Z] @firebase/firestore: Firestore (8.6.3): WatchChangeAggregator Detected inactive target 12 chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.086Z] @firebase/firestore: Firestore (8.6.3): WatchChangeAggregator Detected inactive target 14 chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.087Z] @firebase/firestore: Firestore (8.6.3): MemoryPersistence Starting transaction: Get last remote snapshot version chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.088Z] @firebase/firestore: Firestore (8.6.3): MemoryPersistence Starting transaction: Apply remote event chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.090Z] @firebase/firestore: Firestore (8.6.3): MemoryPersistence Starting transaction: notifyLocalViewChanges chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.229Z] @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"REMOVE","targetIds":[8]}} chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.230Z] @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[12]}} chunk-vendors~1fb195ae.js:320:768
[2021-07-21T11:45:57.230Z] @firebase/firestore: Firestore (8.6.3): Connection WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[14]}} 
```

> - Can you please check if the problem still happens with persistence disabled?

Persistence was only being performed for Chrome, **_this was indeed generating the problem_**:
```javascript
if (!('MozAppearance' in document.documentElement.style)) {
    app.firestore().enablePersistence({ synchronizeTabs: true })
      .then(() => {
        resolvePersistence()
      })
      .catch((err) => {
        if (err.code === 'failed-precondition') {
          // Multiple tabs open, persistence can only be enabled
          // in one tab at a a time.
        } else if (err.code === 'unimplemented') {
          // The current browser does not support all of the
          // features required to enable persistence
        }
        resolvePersistence()
      })
  } else {
    resolvePersistence()
  }
```

I have removed this code and it works in both browsers, so the **error is because of persistence**.

Thank you very much for everything!

**Comment by var-const** [comment]
Thank you for the update! Would it be possible for you to enable persistence in Firefox and see if the same error happens as in Chrome? If possible, please share the resulting logs. If that's too much of a hassle, that's okay.

> This is intentional, it is the document identifier in the CollectionFile collection.

Just to clarify -- does your code actually use `collection_id` as an identifier? Or do you use a different identifier that you replaced with `collection_id` in the logs you posted?

**Comment by cristianpoleyJS** [comment]
Unfortunately I can't do that because for the users who reported the error, I would have to test it in production, sorry.

Yes, it is a real ID but I replaced it with `collection_id`.

All in all, sorry for not being able to give more information, the truth is that with the initial message + persistence configuration sometimes random documents return undefined.

Thanks!!!

**Comment by DellaBitta** [comment]
Checking in to see if you have any more information about this issue. Thanks!
