### ISSUE TITLE
v9 beta survey. Feedback wanted!

### ISSUE THREAD

**Issue by Feiyang1** [firebase/firebase-js-sdk#5005]
Hi all,

Thank you for using Firebase SDK v9.0 or v9.0 compat in beta. We'd like to hear what you think about them so far.

Please fill out this [survey](https://docs.google.com/forms/d/e/1FAIpQLScISkr_XCKnafLWZdc5vp4II4WaNQ5xR2cePT10QzaFgh8F8w/viewform) with your thoughts!

In case you missed it, here are our sessions from Google I/O: 

[Reducing bundle size: Previewing a new Firebase for the web](https://www.youtube.com/watch?v=r5eJQ3nPc6A) - a session by @davideast 

[Supercharge your web app with the modular Firebase JS SDK](https://www.youtube.com/watch?v=wR_iBb12gQs) - a workshop by @Feiyang1 

Thank you!

**Comment by DellaBitta** [comment]
Closing this issue since v9 has launched.
