### ISSUE TITLE
Stop using const enums in the public API

### ISSUE THREAD

**Issue by Feiyang1** [firebase/firebase-js-sdk#5012]
Some build tools (e.g. esbuild, vite) don't work with const enums because they compile Typescript in the `isolatedModules` mode. They compile files individually without type information, so they can't inline const enums, which eventually cause runtime errors.

Plus Javascript users can't use const enums.

Auth exports some const enums, e.g. `ProviderId`, `SignInMethod`. We should probably replace them with just plain object maps.

**Comment by BayanBennett** [comment]
Also, NextJS requires `isolatedModules` due to the way that they have `babel` configured.

Thank you for this change.
