### ISSUE TITLE
Audit v9 public APIs to eliminate naming inconsistencies for functions, types, etc.

### ISSUE THREAD

**Issue by Feiyang1** [firebase/firebase-js-sdk#5013]
Currently we have some inconsistent naming in v9 API. For example, the service types(the type of instances returned from `get` functions) are named differently in different packages.

`FirebaseFirestore` and `FirebaseDatabase` are prefixed with `Firebase`, while others are not (e.g. `Auth`, `Functions`).  And `StorageService` is different from all others.

We should review the entire API, find inconsistencies, come up with rules and remediate them.

**Comment by hsubox76** [comment]
It seems Performance also uses `FirebasePerformance`.

**Comment by Feiyang1** [comment]
Fixed by https://github.com/firebase/firebase-js-sdk/pull/5135
https://github.com/firebase/firebase-js-sdk/pull/5136 and
https://github.com/firebase/firebase-js-sdk/pull/5137
