### ISSUE TITLE
email verification from ___.web.app fails, while same verification from ___.firebaseapp.com succeeds

### ISSUE THREAD

**Issue by ultraGentle** [firebase/firebase-js-sdk#5021]
### [REQUIRED] Describe your environment

  * Operating System version: Any
  * Browser version: Any
  * Firebase SDK version: 8.5.3
  * Firebase Product: Auth

#### Steps to reproduce:
Microsoft Outlook threat detection flags verification links sent from `your-project.web.app` as malicious, because the action emails are sent from `your-project.firebaseapp.com`.  

To reproduce, built a sample project with email/password auth, hosted with Firebase hosting, and send a verification email to a Microsoft address that uses Microsoft "Advanced Threat Detection" (e.g., many corporate or university Outlook accounts).  Do this from `your-project.web.app` (this will fail) and then `your-project.firebaseapp.com` (this will succeed).  

Note that even if you ignore the "malicious link" warning and click through, email verification will actually fail if the action email was sent by the `.web.app` address and succeed if sent by the `.firebaseapp.com` address, despite all else being equal.

**Comment by ultraGentle** [comment]
Stackoverflow post on this topic: https://stackoverflow.com/questions/52637407/office-365-advanced-threat-protection-is-flagging-my-firebase-authentication-ema/67951933#67951933

**Comment by looptheloop88** [comment]
Hi @ultraGentle, thanks for the report. This kind of issue is best directed to [Firebase support](https://firebase.google.com/support), because it seems to be not an issue with the SDK.
