### ISSUE TITLE
V9.0.0-beta.3 cannot get string value form key

### ISSUE THREAD

**Issue by harrytran998** [firebase/firebase-js-sdk#5030]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs 11.2.3 
  * Browser version: 91.0.4472.101
  * Firebase SDK version: ^9.0.0-beta.3
  * Firebase Product: remote-config

#### Steps to reproduce:

I initialized and fetched data the firebase app successfully with RemoteConfig instance had `_storageCache` and `activeConfig`. In IndexedDB of Chrome --> Have values of that. 

But when I try to access the value like use `getString()` or `getAll()` like the code bellow, the RemoteConfigService always returns like default value ... Hope anyone can help me.

#### Relevant Code:

```typescript
import * as firebase from 'firebase/app';
import type { RemoteConfig } from 'firebase/remote-config';
import { fetchAndActivate, getRemoteConfig, getString } from 'firebase/remote-config';

export class RemoteConfigService {
  private instance: RemoteConfig;

  constructor(firebaseConfig: FirebaseConfigEnv) {
    firebase.initializeApp(firebaseConfig);
    const remoteConfig = getRemoteConfig(firebase.getApp());

    remoteConfig.settings.fetchTimeoutMillis = 5000;
    if (process.env.NODE_ENV === 'development') {
      // The default value of 12 hours
      // Firebase suggest 12h in production because avoid to hit the free quota limit
      remoteConfig.settings.minimumFetchIntervalMillis = 36000;
    }

    if (remoteConfig.lastFetchStatus === 'no-fetch-yet') {
      remoteConfig.defaultConfig = FirebaseDefaultConfig;
    }

    this.instance = remoteConfig;
  }

  public async fetchAndActiveConfig() {
    try {
      await fetchAndActivate(this.instance);
    } catch {
      console.log('Unable to fetch remote config. Cached or default values will be used');
    }
  }

  protected getRemoteConfigStringByKey(key: string) {
    const result = getString(this.instance, key);
    return result;
  }

  public getSonmthings() {
    console.log(this.instance);
    const xxx = this.getRemoteConfigStringByKey('somethings');
    return JSON.parse(xxx);
  }

}

```

**Comment by Feiyang1** [comment]
IIUC, you mean `_storageCache.activeConfig` has the correct value? 
Did you call `getRemoteConfigStringByKey ` without awaiting for `fetchAndActiveConfig()`? You should await for `fetchAndActivate()` before trying to get any value.

Also worth double checking if the key used in `getString()` matches the one in the remote config.

**Comment by harrytran998** [comment]
1. Yes, `_storageCache.activeConfig` has the correct value from the server.
2. I call `fetchAndActiveConfig()` in initializing the app. And it worked!
3. Yes, I already check the key of `getString()`

**Comment by harrytran998** [comment]
<img width="1025" alt="Screen Shot 2021-06-17 at 09 54 22" src="https://user-images.githubusercontent.com/24296018/122324089-6729e980-cf52-11eb-9dc3-538336090195.png">
Here is the instance value I log in `getSomething()` method

**Comment by harrytran998** [comment]
Oops, It's my bad. I think I just call `await fetchAndActivate()` one time in initializing the app. I try to do what you say and it worked! Thank for help
