### ISSUE TITLE
TypeError: e.auth.addAuthTokenListener is not a function

### ISSUE THREAD

**Issue by ilmatic** [firebase/firebase-js-sdk#5036]
* Operating System version: macOS 11.3.1
  * Browser version: Chrome 91.0.4472.106
  * Firebase SDK version: 9.0.0-beta.4
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Initialization fails with the error. `TypeError: e.auth.addAuthTokenListener is not a function`

I am working on a Chrome extension service worker, so I have to use the v9 beta, as that seems to be the only version where Fetch is implemented. 

#### Steps to reproduce:
Install firebase@9.0.0-beta.4. import and initialize firestore.

```javascript
import { initializeApp } from "firebase/app";
import { initializeAuth, indexedDBLocalPersistence } from "firebase/auth";
import { DocumentSnapshot, initializeFirestore } from "firebase/firestore";

const firebaseConfig = {/* config here */};

export const app = initializeApp(firebaseConfig);
export const auth = initializeAuth(app, {
	persistence: indexedDBLocalPersistence,
});
export const firestore = initializeFirestore(app, {});
```

**Comment by Feiyang1** [comment]
it's a [known issue](https://github.com/firebase/firebase-js-sdk/discussions/5029) with beta.4. Can you please downgrade to beta.2 for now? We should be releasing a new beta version tomorrow to fix this issue.

**Comment by luaz** [comment]
`TypeError: e.auth.addAuthTokenListener is not a function` happens on `firebase@8.6.7` as well.

**Comment by wu-hui** [comment]
@luaz That is also known: https://github.com/firebase/firebase-js-sdk/issues/5018, and should be fixed in next release.

**Comment by ilmatic** [comment]
@Feiyang1 this didn't end up getting fixed in the next couple of releases, and looking through issues I haven't been able to track it down again. Is there an existing issue to reflect this or should I open another? Currently this limitation is blocking the ability to use firebase at all in service workers for Chrome extensions. Thanks!
