### ISSUE TITLE
Wrong error code in firebase.auth().signInWithCredential() response

### ISSUE THREAD

**Issue by serhiipalash** [firebase/firebase-js-sdk#504]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS
  * Firebase SDK version: 4.8.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Wrong error code in `firebase.auth().signInWithCredential(...)` response if user already has one auth provider and try to login with another auth provider.

#### Steps to reproduce:

1) user has auth profile with one provider "facebook.com"
2) user try to login with "password" provider using `signInWithCredential` method
3) in response we get the error with code **auth/wrong-password**, not **auth/account-exists-with-different-credential**

#### Relevant Code:

```javascript
async function authenticate(providerId, email, password, token) {
  let credential

  if (providerId === 'facebook.com' && token) {
    credential = firebase.auth.FacebookAuthProvider.credential(token)
  } else if (providerId === 'password' && email && password) {
    credential = firebase.auth.EmailAuthProvider.credential(email, password)
  }

  if (credential) {
    try {
      await firebase.auth().signInWithCredential(credential)
    } catch (err) {
      if (err.code === 'auth/wrong-password') {
        console.log('Wrong password')
      } else if (err.code === 'auth/account-exists-with-different-credential') {
        console.log('Account exists with different credentials')
      }
    }
  }
}
```

**Comment by bojeil-google** [comment]
This is WAI. Check the error `message` of that code:
`The password is invalid or the user does not have a password.`

You can't sign in with a non-existing email/password and get a `auth/account-exists-with-different-credential`. When you sign in with email and password and the password doesn't exist, the error should be unique to that operation. A non-existing email and password is not a proof of identity like an OAuth credential.

If you want to check if an email already exists, you can use the `fetchProvidersForEmail` API. In that case it will return an array `['facebook.com']`. You can then tell the user they already have a facebook account with that email.

**Comment by serhiipalash** [comment]
Works. Thanks!

**Comment by serhiipalash** [comment]
Btw, @bojeil-google maybe you know how I can get current session auth provider id?
I know how to get list of user auth providers, but how to get currently active one?

**Comment by bojeil-google** [comment]
https://stackoverflow.com/questions/47225100/how-to-determine-if-the-user-signed-in-to-firebase-with-email-and-password-or-wi

**Comment by serhiipalash** [comment]
> https://stackoverflow.com/questions/47225100/how-to-determine-if-the-user-signed-in-to-firebase-with-email-and-password-or-wi

Thanks! 

`firebase.auth().currentUser.providerData[0].providerId` always is `facebook.com`.

I found this solution
```
import jwtDecode from 'jwt-decode'

firebase
    .auth()
    .currentUser.getIdToken()
    .then(token => {
        const user = jwtDecode(token)

        console.info('sign_in_provider: ', user.firebase.sign_in_provider)
    })
```

@bojeil-google do you know is there a feature request to make it simpler like in Android or iOS sdk?
Android: **FirebaseAuth.getInstance().getCurrentUser().getProviderId()**
iOS: **auth.currentUser?.providerID**

**Comment by bojeil-google** [comment]
We are planning to simplify this in the future.

**Comment by serhiipalash** [comment]
> We are planning to simplify this in the future.

Great! Thanks in advance! 👍
