### ISSUE TITLE
onAuthStateChanged fetching user details evern after signOut()

### ISSUE THREAD

**Issue by arunkumar413** [firebase/firebase-js-sdk#5041]
### [REQUIRED] Describe your environment

  firebase/auth Modular version 9 (Beta)

### [REQUIRED] Describe the problem

I'm declaring the getAuth() in a js module and using it in multiple modules.   When I use the `onAuthStateChanged` after signout in a different module,  it's still fetching the user.
#### Steps to reproduce:
```
firebaseAuth = getAuth()
firebaaseAuth.signOut()  
firebaseAuth.onAuthStateChanged

```

  When I use the `onAuthStateChanged` after signout it's still fetching the user.
#### Relevant Code:

```
javascript

export const firebaseAuth = getAuth();

firebaseAuth.signOut();

 firebaseAuth.onAuthStateChanged(function(user){
      setToken(user.accessToken)

}   
```

**Comment by looptheloop88** [comment]
Hi @arunkumar413, thanks for the report. I tried replicating the issue, but I wasn't able to. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample project that I can run locally to replicate the issue?

**Comment by arunkumar413** [comment]
Needs a bit more testing on my side. I'm not able to isolate the issue. It's happening on prod/dev app.
