### ISSUE TITLE
When document is deleted onSnapshot gives FirebaseError: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by bashmish** [firebase/firebase-js-sdk#5042]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Catalina 10.15.7
  * Browser version: Chrome Version 91.0.4472.106 (Official Build) (x86_64)
  * Firebase SDK version: 8.6.5
  * Firebase Product: firestore, cloud functions

### [REQUIRED] Describe the problem

1. Subscribe to subcollection updates using `onSnapshot`. Define error handler for it.
2. Call a cloud function which awaits deleting all subcollection items and then deletes document itself.
3. Client error handler is fired with `Uncaught Error in snapshot listener: FirebaseError: Missing or insufficient permissions.`

#### Relevant Code:

Partially pseudo code, so only for illustration purpose:

```javascript
// cloud function
exports.deleteDocument = runWith({ memory: '512MB', timeoutSeconds: 300 }).https.onCall((data, context) => {
  const doc = firestore().collection('collectionA').doc(data.id);
  await doc.collection('subcollectionB').get().then((qs) => Promise.all(qs.docs.map((s) => s.ref.delete())));
  await doc.delete();
});

// client
firestore.collection('collectionA').doc('myid').collection('subcollectionB').doc('subid').onSnapshot(
  { includeMetadataChanges: true },
  (s) => console.log(s),
  (e) => console.error(e) // Uncaught Error in snapshot listener: FirebaseError: Missing or insufficient permissions.
);
firebase.functions().httpsCallable('deleteDocument')({ id: 'myid' });
```

**Comment by looptheloop88** [comment]
Hi @bashmish, thanks for the report. I tried replicating the issue, but I wasn't able to. I used the code snippets you've shared and the Firestore collection was deleted successfully without any error. Also, the onSnapshot listener is getting fired as expected.

Make sure to use the latest updated SDK versions and Firebase Tools. Lastly, double check if you have the correct Firestore security rules.

**Comment by bashmish** [comment]
@looptheloop88 thanks for taking time to analyse this. I've been debugging this too and found a workaround. Indeed the rules are the cornerstone.

```diff
    match /collectionA/{rootID} {
      allow read: if resource == null || isAuthorised(resource.data)
      match /subcollectionB/{subID} {
-        allow read: if resource == null
-                    || isAuthorised(get(/databases/$(database)/documents/collectionA/$(rootID)).data)
+        allow read: if resource == null
+                    || !exists(/databases/$(database)/documents/collectionA/$(rootID))
+                    || isAuthorised(get(/databases/$(database)/documents/collectionA/$(rootID)).data)
```

Originally I expected `resource == null` to be sufficient, but `isAuthorised` for subcollection uses not the `resource`, but the main document itself. `isAuthorised` exact implementation is not important, but it failed ofc after component was deleted resulting in no read access.

Not sure if this is how Firestore's `onSnapshot` is supposed to handle such scenarios. Technically looks right, but I just didn't expect this to be so quickly respected in `onSnapshot` error handler.

Hope this issue helps other folks who run into this, it's hard to find any info about such scenarios anywhere else right now.
