### ISSUE TITLE
If we changed the firebase FCM configuration then push notifications is not working.

### ISSUE THREAD

**Issue by sachin-dane** [firebase/firebase-js-sdk#5048]
If we changed the firebase FCM configuration then push notifications is not working.

Explaination.

1.  Created sample angular project and hosted it on some www.abc.com
2.  Created firebase FCM project integrated that to angular project.
    Added following code to service worker file.

    firebase-messaging-sw.js

    importScripts('https://www.gstatic.com/firebasejs/7.6.0/firebase-app.js');
    importScripts('https://www.gstatic.com/firebasejs/7.6.0/firebase-messaging.js');
    firebase.initializeApp({
    apiKey: “from firebase config”,
    authDomain: “from firebase config”,
    databaseURL: “from firebase config”,
    projectId: “from firebase config”,
    storageBucket: “from firebase config”,
    messagingSenderId: “from firebase config”,
    appId: “from firebase config”,
    measurementId: “from firebase config”
    });
    const messaging = firebase.messaging();

3.  Once application run it successfully ask permission to browser to allow notification. I allowed it now push notification set to browser for www.abc.com domain.

4.  Due to some reason we have created another firebace fcm project, now fcm configuration is changed. Then we updated the configuration in angular project and as well as in backend.

5   But problem is now push notification is not working most of our prod user has already allowed to push notification is set to his broswer. now our configuration is changed push notification not working we have to ask user to remove notification setting from browser to www.abc.com domain. then it works. even though firebase is not requesting to allow / deny popup to ask permission when configuration is changed

6.  Please suggest the solution

**Comment by zwu52** [comment]
investigating..

**Comment by zwu52** [comment]
I tested with my test app and was getting a message after swapping to a different firebase project. 

@sachin-dane  What do you mean by "But problem is now push notification is not working". Could you provide more details  on the error message and send response you get?
