### ISSUE TITLE
Calling a cloud function yields to permission-denied error

### ISSUE THREAD

**Issue by ad-si** [firebase/firebase-js-sdk#5053]
### Describe your environment

  * Operating System version: macOS Catalina 10.15.7 19H1217 x86_64
  * Firebase SDK version: 8.6.8
  * Firebase Product: cloud functions

### Describe the problem

No matter how I try to call one cloud function from another, I always get following error:

```
HttpsErrorImpl: permission-denied
at new HttpsErrorImpl (/workspace/node_modules/@firebase/functions/dist/index.node.cjs.js:62:28)
at _errorForResponse (/workspace/node_modules/@firebase/functions/dist/index.node.cjs.js:157:12)
at Service.<anonymous> (/workspace/node_modules/@firebase/functions/dist/index.node.cjs.js:611:33)
at step (/workspace/node_modules/tslib/tslib.js:143:27)
at Object.next (/workspace/node_modules/tslib/tslib.js:124:57)
at fulfilled (/workspace/node_modules/tslib/tslib.js:114:62)
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'permission-denied',
  details: undefined
}
```

#### Steps to reproduce:

callable.js

```js
module.exports = functions
  .region('europe-west1')
  .https.onCall(data => { … })
```

main.js

```js
const admin = require('firebase-admin')
const functions = require('firebase-functions')
const firebase = require('firebase/app')
require('firebase/functions')

const fbConfig = JSON.parse(process.env.FIREBASE_CONFIG)
const app = firebase.initializeApp(fbConfig)

const func = app
  .functions('europe-west1')
  .httpsCallable('callable')

func(…)
```

I already tried:

- Write the callable as a `onRequest` function
- Create an extra web app in firebase to use its config for initializing the app
- Manually activate "Allow unauthenticated" in the GCP functions dashboard

However, the error stays the same.
The code seems to have worked in the past, which makes this even more surprising.

**Comment by looptheloop88** [comment]
Hi @ad-si, thanks for the report. I tried replicating the issue, but I wasn't able to. Would you mind sharing a [sample project](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally to reproduce the error? Also, have you tried removing the region and see if the issue persists?

**Comment by ad-si** [comment]
As I workaround I was able to get it running by making it a `onRequest` function and moving it to `us-central1`. Since there are apparently noteworthy differences between the different regions, this could very well be a region problem. I'll try to set up a sample project the upcoming days.

**Comment by looptheloop88** [comment]
Hi @ad-si, thanks for the confirmation. I'll close this issue for the meantime while you're creating the sample project. You may reopen it once it’s ready.

**Comment by ad-si** [comment]
Small update @looptheloop88: I didn't actually have to change any code, simply moving it to `us-central1` fixed it. Is `europe-west1` broken?

**Comment by looptheloop88** [comment]
Hi @ad-si, I'm not seeing any issues with `europe-west1` region. I just tried now and worked fine.

```
exports.someFunction = functions.region("europe-west1").https.onCall((data, context) => {});
```

```
firebase.app().functions('europe-west1').httpsCallable('someFunction').then(() => {});
```

You may want to check the best practices for changing the Firebase Cloud Function region [here](https://firebase.google.com/docs/functions/locations#best_practices_for_changing_region).
