### ISSUE TITLE
Firestore onSnapshot() fails to complete on app restart

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-js-sdk#5058]
* Operating System version: _____  iOS 14.4.2
  * Browser version: _____ Safari 14.4.2
  * Firebase SDK version: _____ 8.6.7
  * Firebase Product: _____ Firestore

#### Steps to reproduce:

When my app starts, a snapshot is started (using the `onSnapshot()` method) on the document containing the current's user data.
My issue is that when I restart the app, this snapshot will "sometimes" never return any value, even though there is a document.
The only solution then is to kill the app (double click on Home then swipe up the app screen) and start it again, then everything works fine again.

How I restart the app:

`window.location.assign(window.location.origin);`

Logs (the SDK's logs are mixed with the ones from my app, I removed the irrelevant ones from my app):

> LOG - [2021-06-22T14:33:15.403Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|377333871|null
> LOG - [2021-06-22T14:33:15.401Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|377333871|1
> LOG - [2021-06-22T14:33:15.360Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|965110029|null
> LOG - [2021-06-22T14:33:15.344Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|965110029|1
> LOG - [2021-06-22T14:33:15.179Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|291602727|null
> LOG - [2021-06-22T14:33:15.178Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|291602727|1
> LOG - [2021-06-22T14:33:15.177Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|__sak|null
> LOG - [2021-06-22T14:33:15.176Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|__sak|1
> LOG - [2021-06-22T14:33:15.174Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|591487729|null
> LOG - [2021-06-22T14:33:15.172Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|591487729|1
> LOG - [2021-06-22T14:33:15.170Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|290269970|null
> LOG - [2021-06-22T14:33:15.169Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|290269970|1
> LOG - [2021-06-22T14:33:15.167Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|709914748|null
> LOG - [2021-06-22T14:33:15.166Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|709914748|1
> LOG - [2021-06-22T14:33:15.165Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|__sak|null
> LOG - [2021-06-22T14:33:15.163Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|__sak|1
> LOG - [2021-06-22T14:33:15.161Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|185710931|null
> LOG - [2021-06-22T14:33:15.160Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|185710931|1
> LOG - [2021-06-22T14:33:15.158Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|272417711|null
> LOG - [2021-06-22T14:33:15.156Z]  @firebase/firestore:Firestore (8.6.7): SharedClientState|EVENT|272417711|1
> LOG - [2021-06-22T14:33:12.973Z]  @firebase/firestore:Firestore (8.6.7): SimpleDb|Opening database:firestore/[DEFAULT]/fireauthentest/main
> LOG - [2021-06-22T14:33:12.972Z]  @firebase/firestore:Firestore (8.6.7): IndexedDbPersistence|Starting transaction:updateClientMetadataAndTryBecomePrimary
> LOG - [2021-06-22T14:33:12.967Z]  @firebase/firestore:Firestore (8.6.7): FirestoreClient|Initializing OfflineComponentProvider
> LOG - [2021-06-22T14:33:12.949Z]  @firebase/firestore:Firestore (8.6.7): FirestoreClient|Received user=ZZNtKb3byiQsrHZ4I4A3IyfDZWL2
> LOG - [2021-06-22T14:33:12.947Z] backenduser.setusersnapshot - uid=ZZNtKb3byiQsrHZ4I4A3IyfDZWL2
> LOG - [2021-06-22T14:33:12.941Z] backendchat_stateless.getchatsbystate - ptcpuid=ZZNtKb3byiQsrHZ4I4A3IyfDZWL2, chatstate=10
> LOG - [2021-06-22T14:33:12.941Z] backendchat.getchats ptcpuid=ZZNtKb3byiQsrHZ4I4A3IyfDZWL2
> LOG - [2021-06-22T14:33:12.938Z] mylogin.mounted.onAuthStateChanged - user set
> LOG - [2021-06-22T14:33:12.194Z] app.mounted - version=dev_0.0.1555, OS detected=iOS, appversion=5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1

Notes regarding the logs:
- "mylogin.mounted.onAuthStateChanged - user set" is when `auth.onAuthStateChanged` is triggered with a valid user, hence the user is logged in
- "backenduser.setusersnapshot - uid=ZZNtKb3byiQsrHZ4I4A3IyfDZWL2" is when the snapshot is triggered

**Comment by wu-hui** [comment]
Hi @olivierkrener 

Thanks for reporting the issue and the logs.

The log does show there is a user signing in, however, the logs around snapshot listeners are no there. Can you check if there are more logs? 

If these are all the logs you have, is it possible for you to provide a mini-repo, along with instructions. I did a simple repo, and do not see the error.
