### ISSUE TITLE
FR: Support click_action when setBackgroundMessageHandler is defined

### ISSUE THREAD

**Issue by henrylearn2rock** [firebase/firebase-js-sdk#506]
* Operating System version: Windows 10 
  * Firebase SDK version: 4.9.1
  * Firebase Product: messaging

### Describe the problem
Trying to use `ServiceWorkerRegistration.getNotifications()` in `setBackgroundMessageHandler()` to reduce the number of notifications shown to the client [as shown here](https://developers.google.com/web/updates/2015/05/notifying-you-of-changes-to-notifications).  However, `click_action` no longer works because it is only supported in the generic `notification` obj in payload.  It would be great if we can still opt-in to use firebase messaging to handle the click action somehow because firebase messaging can handle the locating/creating window & message client logic.
#### Steps to reproduce:

1. use `setBackgroundMessageHandler()`, meaning the message can only use `data` field without `notification` field
2. can no longer define `notification.click_action`

#### Relevant Code:

https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging/src/controllers/sw-controller.ts#L171

**Comment by gauntface** [comment]
The expectation is that you'd implement this logic yourself with the API in the service worker:  

Add data to a ntofication: https://web-push-book.gauntface.com/chapter-05/04-common-notification-patterns/#adding-data-to-a-notification
Listen for a click event: https://web-push-book.gauntface.com/chapter-05/03-notification-behaviour/#notification-click-event
Open a window: https://web-push-book.gauntface.com/chapter-05/04-common-notification-patterns/#open-a-window
