### ISSUE TITLE
setBackgroundMessageHandler is deprecated but used in sample project

### ISSUE THREAD

**Issue by freerider7777** [firebase/firebase-js-sdk#5060]
Deprecated in docs:
[https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#setbackgroundmessagehandler](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#setbackgroundmessagehandler)

project:
[https://github.com/firebase/firebase-js-sdk/blob/master/integration/messaging/test/static/sw-base.js](https://github.com/firebase/firebase-js-sdk/blob/master/integration/messaging/test/static/sw-base.js)

**Comment by looptheloop88** [comment]
Hi @freerider7777, thanks for the report. We will update the deprecated code snippets, but we can't provide definite timelines or details.

**Comment by freerider7777** [comment]
But does it (deprecated method) still work well?

**Comment by zwu52** [comment]
It should work. But we recommend using `onBackgroundMessage`.

**Comment by zwu52** [comment]
Closing the ticket now. Feel free to open if there is any question.
