### ISSUE TITLE
Unable to handle messages when app is in the background

### ISSUE THREAD

**Issue by marosivanco** [firebase/firebase-js-sdk#5061]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 91.0.4472.114
  * Firebase SDK version: 9.0.0-beta.5
  * Firebase Product: messaging

### Describe the problem

https://firebase.google.com/docs/cloud-messaging/js/receive#web-v9_3
mentions `onBackgroundMessage` but the provided example is empty.
`firebase/messaging` module exports no such function.
I tried to call:
```javascript
messaging.onBackgroundMessage(handler)
```
but I get:
![image](https://user-images.githubusercontent.com/9110470/123098977-0444c080-d432-11eb-9398-e35f77f5db32.png)

I also tried to use `onMessage` function, but it does not seam to work in service-worker.

It is difficult to judge if the problem is in the incomplete documentation, TS interface, or functionality.

#### Relevant Code:

```javascript
import buildNotification from '@/notifications/buildNotification';
import { initializeApp } from 'firebase/app';
import { getMessaging, isSupported } from 'firebase/messaging';

const { apiKey, appId, messagingSenderId, projectId } = self.FIREBASE_CONFIG;
let messaging;

if (isSupported()) {
    if (!messaging) {
        messaging = getMessaging(initializeApp({ apiKey, appId, messagingSenderId, projectId }));
    }
    messaging.onBackgroundMessage(payload => {
        const { title, options } = buildNotification(payload, self.staticAssetUrl);
        return self.registration.showNotification(title, options);
    });

    self.addEventListener('notificationclick', event => {
        event.notification.close();
        event.waitUntil(self.clients.openWindow(event.notification.data.url));
    });
}

```

**Comment by marosivanco** [comment]
For desperate souls:
```javascript
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';
```
that is, use service-worker **specific** module: `firebase/messaging/sw`.

**Comment by looptheloop88** [comment]
Thanks for sharing this information, @marosivanco. Yes, the [`onBackgroundMessage`](https://firebase.google.com/docs/reference/js/v9/messaging_sw.md#onbackgroundmessage) method can be accessed through the sw entry point.

We will update our documentations and sample code snippets, however we can't provide definite timelines. I'll close this issue now.
