### ISSUE TITLE
remoteConfig.fetchAndActivate not working on Safari (Added to Home Screen) WebApp

### ISSUE THREAD

**Issue by faljabi** [firebase/firebase-js-sdk#5063]
* Operating System version: iOS 14.6
  * Browser version: Safari iOS 14.6
  * Firebase SDK version: 8.6.8
  * Firebase Product: Remote Config

I am facing the same exact error explained in https://github.com/firebase/firebase-js-sdk/issues/2373 I use remote config when the web application added to Home Screen on iOS.

```
try {
firebase.remoteConfig().fetchAndActivate()
    .then((res) => {
      // This is not printed
      console.log(res)
    })
    .catch((err) => {
      // This is not printed
      console.error(err)
    })
    .finally(() => {
      // This is not printed
      console.log('finally')
    })
}
catch(e) {
console.log('not even printing anything here');
}
```

**Comment by looptheloop88** [comment]
Hi @faljabi, thanks for the report. I tried replicating the issue, but I wasn't able to. Could you share a screenshot or the complete error logs that you're seeing?

Is this issue only happening in mobile Safari browser? Have you tried other browsers?
