### ISSUE TITLE
[Types] namespace is exported as `firebase.default`

### ISSUE THREAD

**Issue by ShaMan123** [firebase/firebase-js-sdk#5080]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: >=8.2.4
  * Firebase Product: typescript/app

#### Relevant Code:
When using in `.d.ts` files:
```typescript
/// <reference types="firebase" />
interface Test {
  UserCredential: firebase.default.auth.UserCredential
}
```
Should be:
```typescript
/// <reference types="firebase" />
interface Test {
  UserCredential: firebase.auth.UserCredential
}
```

![image](https://user-images.githubusercontent.com/34343793/123928239-66ec0e00-d996-11eb-84dd-c4b98da03a2f.png)

![image](https://user-images.githubusercontent.com/34343793/123928293-74a19380-d996-11eb-9ffa-bb65bc416055.png)

#### Motivation 
https://github.com/firebase/firebaseui-web/pull/853#issuecomment-871178409

**Comment by hsubox76** [comment]
I'm not really sure how firebaseui-web consumes TS files but it seems like Typescript at least at one point was not able to handle ESM imports: https://github.com/ajv-validator/ajv/issues/1381

I think the fix might be to use [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) in whatever project is consuming the types package, but it doesn't look like there's any .tsconfig in firebaseui-web that I can find, where it could be set?
