### ISSUE TITLE
getToken succeeds or fails randomly

### ISSUE THREAD

**Issue by schummar** [firebase/firebase-js-sdk#5081]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 91.0.4472.114
  * Firebase SDK version: 8.6.8
  * Firebase Product: cloud messaging

### [REQUIRED] Describe the problem
getToken seems to randomly fail without plausible explanation. I run it with the exact same config on the same device multiple times in a row (call deleteToken in between).

Some requests are successful, some fail, seemingly at random. I cannot make out any significant difference between failing and successful requests. Same config, request headers contain same  values for `x-goog-api-key` and `x-goog-firebase-installations-auth`
Request payloads have the same shape and same value for `applicationPubKey`.

The returned error is:
```
code: 401
message: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
status: "UNAUTHENTICATED"
```

#### Steps to reproduce:
- Call getToken
- Sometimes the function is successful, token is returned, messages arrive, all perfect. Sometimes the request fails.

#### Relevant Code:
```javascript
await messaging.getToken({
    vapidKey: publicVapidKey,
    serviceWorkerRegistration: await serviceWorkerRegistration,
})
```

#### Example reponse overview
To test it I'm running a loop of
- deleteToken()
- wait 2 minutes
- getToken()
- wait 30 seconds

And the result is:
![image](https://user-images.githubusercontent.com/2988557/123964696-010e7f00-d9b4-11eb-9635-6500fdc39257.png)

**Comment by dnimon** [comment]
I am also seeing this issue, although it occurs every time in our environment. Receiving the following error, and nothing has changed in our application in regards to firebase integration:

```
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

```

**Comment by renanfferreira** [comment]
@schummar have you found a solution?

**Comment by schummar** [comment]
No solution, only a not-so-great workaround.
I just retry until it works in 30s intervals. But that means it can take quite some time initial the subscription becomes active.

**Comment by renanfferreira** [comment]
In our case it always fails.

**Comment by sunildodiya** [comment]
Yes, we got this same error too, since last 4-5 hours. it was working correctly before.
![image](https://user-images.githubusercontent.com/1546975/124013669-393baf00-da00-11eb-91bd-339900fa8afb.png)

**Comment by akp111** [comment]
Getting this error message
`An error occurred while retrieving token.  FirebaseError: Messaging: A problem occurred while subscribing the user to FCM: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (messaging/token-subscribe-failed).
    at http://localhost:3000/static/js/vendors~main.chunk.js:4303:33
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:61747:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:61678:14)
    at fulfilled (http://localhost:3000/static/js/vendors~main.chunk.js:61633:24)`
    
    in both extension and react app. Any workaround?

**Comment by dambusm** [comment]
We are also getting this error a lot, with the first occurence

**Comment by jamesbrian0323** [comment]
![image](https://user-images.githubusercontent.com/50069715/124107141-8454d100-da97-11eb-9ec0-bba97197254d.png)

It was working correctly yesterday, but it's not working now on my react app.
I tried to delete the app from firebase and create it again but still fails.
@schummar Have you found a solution?

**Comment by dambusm** [comment]
We are also seeing this error a lot, first occurrence was at June 29, 2021 4:44:25 AM UTC. We have also made no changes in this timeframe.

**Comment by Jayaram7797** [comment]
We are also facing same issue since yesterday evening (Aroud 5PM IST). There is no problem for existing active subscribers, but this is affecting our new users and old users 
1]. Old users, whose token has expired 
2]. New users, whose new token is to be registered. 
We checked some of our partners implementing server side token registration ... it looks like its working fine for them. firebase team should atleast inform us if there is any update in this regard. Since yesterday no new subscribers for our website.

**Comment by legraphista** [comment]
Started implementing push notifications 2 days ago for our app and spent way too much debugging this thinking that it's an issue on our side :sweat_smile: 

Our calls usually fail 80% of the time. 
The workaround on our side was to retry `messaging.getToken` 5 times at 3 seconds intervals. If that fails, we notify the user to try again later

**Comment by deivisondfs2** [comment]
This also happens to me :(
Yesterday it was normal and today I'm getting this error too.
Does anyone have any updates or where can we try to get a status?
I just created a new account for test and entered the new credentials but the error remains.

**Comment by lesjames** [comment]
I'm getting a 401 on the call to registrations as well. Just noticed it yesterday. It's happening in production and no code has changed there.

**Comment by kyftball** [comment]
Same.  Getting 401.  It appeared to work until I unregistered the service worker during testing.  Now it continuously throws the same error. No code or api changes on my side

**Comment by gach87** [comment]
![image](https://user-images.githubusercontent.com/3605164/124147774-01168980-da5d-11eb-89f9-7108e0344cca.png)

No report in the status page neither

**Comment by ghanavel** [comment]
![image](https://user-images.githubusercontent.com/4058024/124158515-a4948800-dab7-11eb-870b-cbd3e9b55c72.png)

**Comment by ghanavel** [comment]
I am getting this issue since beginning , never given successful token, I tried with new vapidKey as well

**Comment by looptheloop88** [comment]
We are currently looking into this issue internally. We'll keep this thread posted for any updates.

**Comment by Jaimerojo** [comment]
I have the same issue since yesterday
[
![Captura de Pantalla 2021-07-01 a la(s) 12 20 50](https://user-images.githubusercontent.com/12600029/124179010-0bd61c00-da67-11eb-9199-c6d398f4bae5.png)
](url)

**Comment by schummar** [comment]
It seems by now all of our requests fail all the time. Yesterday it felt like 50/50. So is it possible some update/cert/whatever has been rolled out to the servers gradually in the last days?

**Comment by Stiveknx** [comment]
Another thing to add:

After many failures, I've managed to get 1 registration.
- Sending notifications, didn't fail, but also didn't reach the destination.
- If I try to generate a new token, I first get an FAIL to delete the current registration.
- Than, I get the same stuck problem, fails 90% of trying to get new tokens.

The fail to delete the current registration:
![Screenshot_20210701_184928](https://user-images.githubusercontent.com/497893/124193403-1f03de80-da9d-11eb-8d49-156cbd52803e.png)
![Screenshot_20210701_184856](https://user-images.githubusercontent.com/497893/124193404-1f9c7500-da9d-11eb-9dcc-7388dbc9e88e.png)


PS.: I've never called delete before.
If I get a new token again, and try to delete, same problem.

**Comment by sahejsingh** [comment]
copying from: https://github.com/firebase/firebase-js-sdk/issues/2364#issuecomment-871923515

I ran into this issue this morning. (1st Jul)

```
POST https://fcmregistrations.googleapis.com/v1/projects/my-project-id/registrations 401 (Unauthorized)
<call-stack>
index.html:630 Unable to get permission. FirebaseError: Messaging: A problem occurred while subscribing the user to FCM: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (messaging/token-subscribe-failed).
    at api.ts:67
    at tslib.es6.js:102
    at Object.next (tslib.es6.js:83)
    at r (tslib.es6.js:73)

```
here is how it happened
- created `client-1`, got notifications working.
- for some reason I happened to delete the `client-1` from firebase console.
- created `client-2`
- copied the new `firebaseConfig` from console.
- got the error now.
- Noticed, the `Web API Key` is the same for both the clients. there are not restrictions on the web api key.
- I have followed everything I could (unregister service worker)

Firebase JS Version: 8.6.8

scripts imported like so:
```
<script src="https://www.gstatic.com/firebasejs/8.6.8/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.6.8/firebase-messaging.js"></script>
var firebaseConfig = {
  // CONFIG COPIED FROM FIREBASE CONSOLE.
};

firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();


  messaging
    .getToken({ vapidKey: "MY_PUB_KEY" })
    .then((currentToken) => {
      console.log(currentToken)
    })
    .catch(function (err) {
      // handle error
    });
```

**Comment by dkensiski** [comment]
We have identified and believe we have resolved the issue.

**Comment by gach87** [comment]
Confirmed the resolution in multiple devices

**Comment by gach87** [comment]
![image](https://user-images.githubusercontent.com/3605164/124206529-93487d00-dab1-11eb-8298-9f34e445454c.png)
Now the error is sending messages to the devices, not getting the token

**Comment by ghanavel** [comment]
> We have identified and believe we have resolved the issue.

Today morning I Could see token.

**Comment by Jayaram7797** [comment]
Finally ... a sigh of relief ... thank you team firebase .. :)

**Comment by schummar** [comment]
I can confirm, that so far it looks good. I could not observe any more failures this morning.

**Comment by akp111** [comment]
@schummar Did you change anything on your end?
I am not getting the error message but I am also not able to generate the token

**Comment by schummar** [comment]
No changes, it just works now.

**Comment by akp111** [comment]
Thank you for informing

**Comment by marosivanco** [comment]
Any idea in which releases will it land? I am particularly interested in v9.0.0-beta...

**Comment by legraphista** [comment]
> Any idea in which releases will it land? I am particularly interested in v9.0.0-beta...

By the looks of it, the issue was backend related.
On my end, the errors have subsided without any change to my implementation (version 8.7.0)

**Comment by looptheloop88** [comment]
Per checking, the issue is now resolved. This is a backend issue and we didn't change anything in the current JS SDK.

**Comment by Jaimerojo** [comment]
finally works
