### ISSUE TITLE
FirebaseError: Messaging: A problem occured while subscribing the user to FCM: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential

### ISSUE THREAD

**Issue by sagar-chhatrola** [firebase/firebase-js-sdk#5083]
During messaging.getToken({vapidKey: "BKagOny0KF_2pCJQ3m....moL0ewzQ8rZu"});

Getting below error.

FirebaseError: Messaging: A problem occured while subscribing the user to FCM: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential

**Comment by looptheloop88** [comment]
Hi @sagar-chhatrola, thanks for the report. Could you please provide more details about the issue? What SDK version are you currently using? Do you have a sample project that you can share with us to replicate the issue?

Lastly, we highly suggest that you follow the template provided when filing an issue.

**Comment by looptheloop88** [comment]
Per checking, this is a duplicate of #5081.
