### ISSUE TITLE
npm install error: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by andrebaltieri** [firebase/firebase-js-sdk#51]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: N/A
  * Firebase Product: All

#### Steps to reproduce:
```
ionic start MyApp blank
cd MyApp
npm install firebase --save
```
Error:
**Cannot read property 'find' of undefined**

Complete Log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'firebase',
1 verbose cli   '--save' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 200 https://registry.npmjs.org/firebase 18ms (from cache)
7 silly pacote tag manifest for firebase@latest fetched in 41ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 silly resolveWithNewModule firebase@4.1.2 checking installable status
13 http fetch GET 200 https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz 15ms (from cache)
14 silly pacote remote manifest for base64url@https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz fetched in 32ms
15 http fetch GET 200 https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz 3ms (from cache)
16 silly pacote remote manifest for buffer-equal-constant-time@https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz fetched in 10ms
17 http fetch GET 200 https://registry.npmjs.org/dom-storage/-/dom-storage-2.0.2.tgz 5ms (from cache)
18 silly pacote remote manifest for dom-storage@https://registry.npmjs.org/dom-storage/-/dom-storage-2.0.2.tgz fetched in 10ms
19 http fetch GET 200 https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.9.tgz 5ms (from cache)
20 silly pacote remote manifest for ecdsa-sig-formatter@https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.9.tgz fetched in 13ms
21 http fetch GET 200 https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.9.3.tgz 2ms (from cache)
22 silly pacote remote manifest for faye-websocket@https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.9.3.tgz fetched in 14ms
23 http fetch GET 200 https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz 2ms (from cache)
24 silly pacote remote manifest for hoek@https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz fetched in 9ms
25 http fetch GET 200 https://registry.npmjs.org/isemail/-/isemail-1.2.0.tgz 3ms (from cache)
26 silly pacote remote manifest for isemail@https://registry.npmjs.org/isemail/-/isemail-1.2.0.tgz fetched in 17ms
27 http fetch GET 200 https://registry.npmjs.org/joi/-/joi-6.10.1.tgz 3ms (from cache)
28 silly pacote remote manifest for joi@https://registry.npmjs.org/joi/-/joi-6.10.1.tgz fetched in 20ms
29 http fetch GET 200 https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-7.4.1.tgz 4ms (from cache)
30 silly pacote remote manifest for jsonwebtoken@https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-7.4.1.tgz fetched in 34ms
31 http fetch GET 200 https://registry.npmjs.org/jwa/-/jwa-1.1.5.tgz 2ms (from cache)
32 silly pacote remote manifest for jwa@https://registry.npmjs.org/jwa/-/jwa-1.1.5.tgz fetched in 5ms
33 http fetch GET 200 https://registry.npmjs.org/jws/-/jws-3.1.4.tgz 4ms (from cache)
34 silly pacote remote manifest for jws@https://registry.npmjs.org/jws/-/jws-3.1.4.tgz fetched in 9ms
35 http fetch GET 200 https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz 2ms (from cache)
36 silly pacote remote manifest for lodash.once@https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz fetched in 5ms
37 http fetch GET 200 https://registry.npmjs.org/moment/-/moment-2.18.1.tgz 3ms (from cache)
38 silly pacote remote manifest for moment@https://registry.npmjs.org/moment/-/moment-2.18.1.tgz fetched in 40ms
39 http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.0.0.tgz 3ms (from cache)
40 silly pacote remote manifest for ms@https://registry.npmjs.org/ms/-/ms-2.0.0.tgz fetched in 6ms
41 http fetch GET 200 https://registry.npmjs.org/promise-polyfill/-/promise-polyfill-6.0.2.tgz 2ms (from cache)
42 silly pacote remote manifest for promise-polyfill@https://registry.npmjs.org/promise-polyfill/-/promise-polyfill-6.0.2.tgz fetched in 6ms
43 verbose stack TypeError: Cannot read property 'find' of undefined
43 verbose stack     at opts.integrity.digests.find.hash (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:262:33)
43 verbose stack     at Array.find (native)
43 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:261:15)
43 verbose stack     at emitNone (events.js:110:20)
43 verbose stack     at Transform.emit (events.js:207:7)
43 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
43 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
43 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
44 verbose cwd C:\Users\andre\dev\remindr
45 verbose Windows_NT 10.0.15063
46 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "firebase" "--save"
47 verbose node v8.0.0
48 verbose npm  v5.0.0
49 error Cannot read property 'find' of undefined
50 verbose exit [ 1, true ]

**Comment by jshcrowthe** [comment]
@andrebaltieri I tried to reproduce this on my machine and was unable to. My versions are as follows:

Node: v8.1.1
NPM: v5.0.3

From the stack trace you provided it looks like the error is happening in NPM itself. NPM 5 has had many issues (see https://github.com/npm/npm/issues/16991) so I'm thinking what you are seeing is part of that. Can you try updating your Node/NPM versions and try again?

**Comment by andrebaltieri** [comment]
@jshcrowthe I feel ashemed now! It worked, thanks!

**Comment by jshcrowthe** [comment]
No worries at all! Glad everything is working for you!
