### ISSUE TITLE
Streaming a collection will give an error when document created with TimeStamp Field

### ISSUE THREAD

**Issue by ibrahimxcool** [firebase/firebase-js-sdk#5106]
> The following NoSuchMethodError was thrown building
> StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(dirty, state:
> _StreamBuilderBaseState<QuerySnapshot<Map<String, dynamic>>, AsyncSnapshot<QuerySnapshot<Map<String, dynamic>>>>#f407c): The method
> 'toDate' was called on null. Receiver: null Tried calling: toDate()

On pressing the FAB ill add a doc with a field of firebase timestamp.

Now on Streaming the collection. I get this error for a split second. What I think the problem is.. Is that the document is created first and then the timestamp gets updated in the document.

[![enter image description here][1]][1]

    class XYZ extends StatelessWidget {
      const XYZ({Key? key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          home: Scaffold(
            floatingActionButton: FloatingActionButton(
              onPressed: () {
                FirebaseFirestore.instance.collection('Test').add({'time': FieldValue.serverTimestamp()});
              },
            ),
            body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
              stream: FirebaseFirestore.instance.collection('Test').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) return Center();
    
                snapshot.data!.docs.forEach((doc) {
                  print(doc.data()['time'].toDate());
                });
    
                return Container();
              },
            ),
          ),
        );
      }
    }

  [1]: https://i.stack.imgur.com/phi20.gif

**Comment by looptheloop88** [comment]
Hi @ibrahimxcool, this repository is for Firebase JS SDK. If you're using Flutter, you may file an issue on its GitHub page.
