### ISSUE TITLE
Improve error message in Database when AppCheck token is missing

### ISSUE THREAD

**Issue by Feiyang1** [firebase/firebase-js-sdk#5113]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 9.0.0-beta.6
  * Firebase Product: database, auth

### [REQUIRED] Describe the problem
When appcheck token is missing, database logs a warning "appcheck token is missing" before throwing an error "Error: Error: Client is offline."

The expected behavior: The error message should reflect the actual issue that AppCheck token is missing.
#### Steps to reproduce:

- Enforce AppCheck for Database in console
- Use database in client without initializing AppCheck

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by anshul2807** [comment]
I'm working on this issue.

**Comment by schmidt-sebastian** [comment]
@anshul2807 Thank you. Let us know if you need assistance.

**Comment by maneesht** [comment]
Closing this as `@firebase/database: FIREBASE WARNING: Missing appcheck token` should be enough.
