### ISSUE TITLE
firebase.database is undefined in 8.7.0

### ISSUE THREAD

**Issue by dready** [firebase/firebase-js-sdk#5119]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04.2 LTS
  * Browser version: Chrome 91
  * Firebase SDK version: 8.7.0
  * Firebase Product: database

#### Steps to reproduce:

Calling to firebase.database.enablingLogging will return the error: `Cannot read property 'enableLogging' of undefined`.

It seems like firebase.database is not there, although it has been imported correctly.

Downgrading to 8.6.8 fixed the problem. The changelog of firebase does not mention any breaking changes.

#### Relevant Code:

```javascript
import firebase from 'firebase/app';
import 'firebase/database';

firebase.database.enableLogging(true);
```

**Comment by looptheloop88** [comment]
Hi @dready, thanks for the report. I tried replicating the issue, but I wasn't able to. I was able to see the debug logs from Firebase Realtime Database in my browser's console.

Please try to delete the `node_modules` directory and the `package-lock.json` file, then do npm install again. You may also want to share a sample project that I can run locally to replicate the issue.

**Comment by dready** [comment]
@looptheloop88 thanks. Shamefully the `yarn.lock` file was the culprit. I tried removal of the node_modules several times, but the lock file was the missing peace.

thank you very much!
