### ISSUE TITLE
FR: Firebase Analytics don't detect Android and IOS

### ISSUE THREAD

**Issue by JulianValenciaGL** [firebase/firebase-js-sdk#5121]
### [REQUIRED] Describe your environment

  * Operating System version: macOs Big Sur
  * Expo version: 39
  * Firebase SDK version: ^8.7.0
  * Firebase Product: Analytics

### [REQUIRED] Describe the problem

I followed the guide from https://docs.expo.io/versions/latest/sdk/firebase-analytics/

Where I created a project in firebase console: https://console.firebase.google.com/

then, I installed:

* expo-firebase-analytics - ~2.5.0
* firebase - ^8.7.0
* expo-firebase-core - ^3.1.0

then, I updated my `app.json`  with:

```
{
"expo":{
   "ios": {
      "icon": "...",
      "buildNumber": "1",
      "supportsTablet": true,
      "bundleIdentifier": "...",
      "googleServicesFile": "./GoogleService-Info.plist"
},
    "android": {
      "icon": "...",
      "adaptiveIcon": {
        "foregroundImage": "...",
        "backgroundColor": "..."
      },
      "package": "...",
      "versionCode": ..,
      "permissions": []
    },
},
"web": {
      "config": {
        "firebase": {
          "apiKey": "...",
          "authDomain": "...",
          "projected": "...",
          "storageBucket": "...",
          "messagingSenderId": "...",
          "appId": "...",
          "measurementId": "..."
        }
      }
    }
}
```

then I did a test:

```
import * as Analytics from 'expo-firebase-analytics'

Analytics.logEvent('event-test', { test: 10 });

```

then I checked in https://console.firebase.google.com/ to see the devices, just detected the events comes from web, even when the test I did, was in IOS:

![image](https://user-images.githubusercontent.com/85369003/124625640-96da5c00-de43-11eb-8811-4434aa8b7512.png)

I tried to follow these guides:
*  https://blog.expo.io/using-firebase-analytics-with-expo-222ca84e4d33
* https://github.com/firebase/firebase-js-sdk/issues/2244

but doesn't work

**Comment by looptheloop88** [comment]
Hi @JulianValenciaGL, thanks for the report. This is working as intended, because you're still using the JS SDK of Google Analytics for Firebase and not Android or iOS.

**Comment by hsubox76** [comment]
I wanted to add that this expo-firebase-analytics package seems to be a wrapper package created by the Expo team that wraps the Firebase JS SDK, so you may get better help from the Expo community on how to do what you want. Given that, I believe Google Analytics detects the device from the User-Agent string, and the default one set by React Native and/or Expo looks like a web user agent. It might be good to talk to other Expo users about how to modify the User Agent for different mobile platforms?
