### ISSUE TITLE
signInWithRedirect() called from Android Chrome browser launches previously installed PWA

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-js-sdk#5122]
### [REQUIRED] Describe your environment

  * Operating System version: Android 7.0
  * Browser version: Chrome 91.0.4472.120
  * Firebase SDK version: 9.0.0-beta.6
  * Firebase Product: auth

### [REQUIRED] Describe the problem

[`signInWithRedirect()`](https://firebase.google.com/docs/reference/js/v9/auth#signinwithredirect) called from Android Chrome browser launches a previously installed (via "Add to home screen") PWA version of the app, and switches to it. Then we are using the PWA but the browser app is still running in parallel.

Because the installed PWA looks exactly like the browser version (except the missing url bar) it is quite confusing for users.

#### Steps to reproduce:

- open your PWA in Android Chrome 
- install it with "[Add to home screen](https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid&hl=en&oco=1)"
- stay in the browser, sign in using [`signInWithRedirect()`](https://firebase.google.com/docs/reference/js/v9/auth#signinwithredirect)
- choose your OAuth account
- see the previously installed PWA opening instead of staying in the browser

#### Relevant Code:

```typescript
// dynamically imported chunk in main thread

import { auth } from './authInit'
import {
    signInWithRedirect, OAuthProvider, browserPopupRedirectResolver
} from '@firebase/auth'

import type { UserCredential } from '@firebase/auth'


export function signInWithProvider(providerId: string): Promise<UserCredential> {
    const provider = new OAuthProvider(providerId)
    provider.addScope('profile')
    provider.addScope('email')
    return signInWithRedirect(auth, provider, browserPopupRedirectResolver)
}
```

**Comment by looptheloop88** [comment]
Hi @laurentpayot, thanks for the report. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to reproduce the issue?

**Comment by laurentpayot** [comment]
@looptheloop88 Sure, I created the [sscce-firebase](https://sscce-firebase.web.app) web app specially for this issue (and for future ones :wink:).  The GitHub repo is [there](https://github.com/laurentpayot/sscce-firebase).

Same bug with this app as well.

**Comment by looptheloop88** [comment]
Hi @laurentpayot, thanks for sharing the sample project. I was able to replicate the behavior, however I'm not sure if this is a bug or working as intended. Let me bring this matter to the attention of our engineers here, then update this thread if I have any information to share.

**Comment by laurentpayot** [comment]
@looptheloop88 please note that once the authentication done on the OAuth page in the browser, the installed PWA launch takes us back to an unauthenticated state and users have to go to thru the authentication process again. I doubt this is a desired behaviour…

**Comment by looptheloop88** [comment]
Hi @laurentpayot, thanks for patiently waiting. This behavior is working as intended and not a bug.

Per [WebAPKs on Android](https://developers.google.com/web/fundamentals/integration/webapks) documentation:

> When a Progressive Web App is installed on Android, it will register a set of intent filters for all URLs within the scope of the app. When a user clicks on a link that is within the scope of the app, the app will be opened, rather than opening within a browser tab.

You might need to update the [scope](https://developers.google.com/web/fundamentals/integration/webapks#using_scope_to_restrict_intent_filters) if you wish not to open the link (auth handler) in the app.
