### ISSUE TITLE
Significantly decreased performance with persistence enabled

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-js-sdk#513]
* Operating System version: any
  * Firebase SDK version: v4.9.1
  * Firebase Product: Firestore

Originally posted by @yankedev [here](https://github.com/firebase/firebase-js-sdk/issues/274#issuecomment-364432954), but in the other issue which tracks something else. I'm experiencing the same problem with my app, which loads faster in the incognito window/with cleared cache than when data is persisted in IndexedDB.

#### Steps to reproduce:

Uncomment `angularFire.enablePersistence()` in `app.module.ts` and reload the page:
https://stackblitz.com/edit/ionic-watdjp

Watch logs in the console.

**Comment by nicolasgarnier** [comment]
@mikelehen FYI since he was on the original issue :)

**Comment by mikelehen** [comment]
This is on my radar to investigate but I haven't gotten a chance yet.  Sorry for the delay!

**Comment by larssn** [comment]
Any status on this?

**Comment by wilhuff** [comment]
We made some significant speedups in #1055, but this hasn't made it into a release yet.

**Comment by wilhuff** [comment]
This was released as part of the Firebase JavaScript SDK 5.3.1.

**Comment by mikelehen** [comment]
If folks are still seeing unexpected performance issues, please open a new issue with details.  Thanks!
