### ISSUE TITLE
Vulnerability in hoek package used by firebase

### ISSUE THREAD

**Issue by rodrigopandini** [firebase/firebase-js-sdk#515]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04 LTS
  * Firebase SDK version: firebase@4.10.0
  * Firebase Product: firebase@4.10.0, firebase-admin@5.9.0  and firebase-functions@0.8.1

#### Steps to reproduce:
Vulnerability in `hoek` package used by `firebase`:
https://nodesecurity.io/advisories/566

#### Relevant Code:
```shell
npm install -g nsp 
npm install --save firebase
nsp check
``` 
Should output something like this:

```sh
$ nsp check
(+) 1 vulnerabilities found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ my@0.1.0 > firebase@4.10.0 > @firebase/firestore@0.3.3 >           │
│            │ grpc@1.9.1 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴────────────────────────────────────────────────────────────────────┘

error Command failed with exit code 1.
```

**Comment by nhodges** [comment]
@rodrigopandini 

If you walk down this dependency chain, the problem child is `node-pre-gyp` which depends on an outdated version of the `hawk` package (which depends on the problem package in question)

I've submitted a PR here: https://github.com/mapbox/node-pre-gyp/pull/349/files

Once that is merged, `grpc` can be updated, then firestorm, and so on and so forth.

**Comment by nhodges** [comment]
https://github.com/firebase/firebase-js-sdk/pull/566

**Comment by PezCoder** [comment]
@nhodges I wanted to understand if this is a really a security vulnerability for websites using firebase for client side only. 
Really appreciate any help. Details here:
https://stackoverflow.com/questions/50564246/is-hoek-prototype-pollution-vulnerable-for-firebase-package
