### ISSUE TITLE
Uncaught `auth/invalid-email` on `signInWithEmailAndPassword`

### ISSUE THREAD

**Issue by johannesgiani** [firebase/firebase-js-sdk#5164]
* Operating System version: macOS 11.3
  * Browser version: 91
  * Firebase SDK version: 8.7.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Although I catch errors in `signInWithEmailAndPassword` there is still an uncaught `auth/invalid-email`. So catching this error works, I can display the error message but I still see a `Uncaught  auth.esm.js?b7aa:66` in the console.

#### Steps to reproduce:

Error with code `auth/invalid-email` is thrown when calling `signInWithEmailAndPassword` with invalid mail, such as `test123` although there is a catch clause.

#### Relevant Code:

```javascript
    async function onSubmit() {
      try {
        await firebase
          .auth()
          .signInWithEmailAndPassword('badly-formatted', 'password');
      } catch (error) {
        if (error.code === 'auth/invalid-email' ||
            error.code === 'auth/user-disabled' ||
            error.code === 'auth/user-not-found' )
        {
           // display mail error
        } else if (error.code === 'auth/wrong-password') {
           // display password error
        } else {
          // display generic error
        }
      }
    }
```

**Comment by looptheloop88** [comment]
Hi @johannesgiani, thanks for the report. I tried replicating the issue, but I wasn't able to. I used the quickstart [sample project](https://github.com/firebase/quickstart-js/blob/master/auth/email-password.html#L57-L70) and the `signInWithEmailAndPassword()` method isn't throwing an uncaught error. See below:

```
{
  code: "auth/invalid-email",
  message: "The email address is badly formatted.",
  a: null
}
```

Would you mind sharing a sample project that I can use and run locally to replicate the issue?

**Comment by johannesgiani** [comment]
Hey @looptheloop88 . When I use the classic syntax with `then` and `catch` there are no errors. The `uncaught` is written as error to console with `async/await` syntax using `try` block. Weird?

**Comment by looptheloop88** [comment]
Per checking, this is actually a known behavior. You may want to check the detailed explanation [here](https://github.com/firebase/firebase-js-sdk/issues/1881#issuecomment-501886866).
