### ISSUE TITLE
v9 api has no equivalent to GetToken in firebase/messaging/sw & is therefore impossible to use in Chrome Extension

### ISSUE THREAD

**Issue by samdoeswork** [firebase/firebase-js-sdk#5169]
### [REQUIRED] Describe your environment

  * Operating System version: Windows10
  * Browser version: Chrome latest
  * Firebase SDK version: 9.0.0-beta.6
  * Firebase Product: Messaging

#### Steps to reproduce:

I am trying to use FCM to trigger onBackgroundMessage in a Chrome extension.

I found the API reference has methods specific to Service Workers (https://firebase.google.com/docs/reference/js/v9/messaging_sw) & was able to successfully call getMessaging in a chrome extension with manifest v3.

However there is no getToken() equivalent method - so it's not possible to target individuals.

In general I've spent hours trying to setup v9 api with Chrome Extensions manifest v3 and there is absolutely no documentation on this topic. 

#### Relevant Code:

Here is my best effort. I cannot get onBackgroundMessage to actually trigger in any Chrome Extension scenario (manifest v3) & additionally cannot access tokens.

```javascript

import { getMessaging, onBackgroundMessage} from "firebase/messaging/sw";
async initFCM() {
    const firebaseApp = initializeApp({ ... });
    const fcm = getMessaging(firebaseApp);
    onBackgroundMessage(this.fcm, (payload) => {
      console.log("Received background message ", payload); // never triggers
    });
  }

```

**Comment by zwu52** [comment]
@samdoeswork, thanks for reporting. Looking 👀

**Comment by zwu52** [comment]
@samdoeswork Sam, 
It was intentionally to left out `getToken` from the sw entry. Getting token in old version of sw was buggy. 
 
Now I have created a test extension with manifest 
```
...
  "browser_action": {
    "default_popup": "popup.html"
  },
  "background": {
    "page": "background.html"
  },
...
```
and I am able to get a token with by calling  getToken inside a popup script. Have you tried calling `getToken` that way? (if you could share a repo I could look that would be helpful too)
