### ISSUE TITLE
[database] FIREBASE WARNING: Invalid query string segment:

### ISSUE THREAD

**Issue by jc275** [firebase/firebase-js-sdk#517]
https://github.com/firebase/firebase-js-sdk/blob/5038cec639e69562f7b3eb1f0e281cf309c79c28/packages/database/src/core/util/libs/parser.ts#L54

@tonymeng This warning now appears during `firebase.initializeApp(config)` even where `config.databaseURL` does not include any `ns` query parameter.

**Comment by tonymeng** [comment]
I'll take a look

**Comment by benoj** [comment]
I have been seeing this too - the query has been running extremely slowly too. Could this be the cause of the slowdown?

The query is `admin.database().ref(`careers/listing-content/${organisation}`).once("value")`

and the data in this query only contains 800bytes of data but is taking over 2 seconds to return?

**Comment by Zjaaspoer** [comment]
> the query has been running extremely slowly too

seeing this too unfortunately

**Comment by ysk8** [comment]
<img width="382" alt="screen shot 2018-02-17 at 10 57 22" src="https://user-images.githubusercontent.com/4340660/36342786-650c0a88-13d1-11e8-8880-0076650fc56c.png">

I just get this too, but the info about the Warning is incomplete. The function run well, but there is some delay compeers to the nominal speed of Firebase.

**Comment by harsh183** [comment]
I've been getting this for a bit too on my server. What seems to be causing this? It also seems to cause some slowdowns as well.

**Comment by ArGaspar** [comment]
Im new on Firebase and im getting the error too can someone confirm that this function is ok?

`    if(event.data.child('paid').val()){
       
      return event.data.ref.parent.child('items').once('value').then((snapshot) => {
        snapshot.forEach((childSnapshot) => {

            var product = childSnapshot.key;
            var qty = childSnapshot.val().qty;
           console.info("product is :" + product + " and qty: " + qty);
            
          });
     });
}`

I can see the info log on firebase but it tooks more than two seconds and the warning is empty
`FIREBASE WARNING: Invalid query string segment:`

**Comment by mrgoodrich** [comment]
+1

**Comment by Ashok-Varma** [comment]
+1

**Comment by sejr** [comment]
+1 😦

**Comment by mrgoodrich** [comment]
I'm a Software Developer at Google and submitted another issue to investigate this problem a few hours ago. Sorry about the frustration, I wish I was familiar with this domain, and it probably won't help to submit more reports fyi. While a fix may have been made, it might not be present in npm or could have not actually fixed the problem. I will also consider contacting tonymeng (made a change earlier) tomorrow if we don't hear a response, since this seems significant.

**Comment by ayushmittal** [comment]
+1

**Comment by mrgoodrich** [comment]
After talking with support this doesn't seem as serious as I thought. The message is just a warning and "shouldn't have any impacts on the function's overall processing." I thought it was preventing changes to functions, but after viewing the function source in the Cloud Console I see the deployments still succeed. I'll keep you updated if I learn anything else.

**Comment by harsh183** [comment]
All my functions seem to work fine, and it was not preventing that. This is not a critical bug, but it creates a lot of high level warnings that drown out the other logs.

**Comment by kleeb** [comment]
+1

**Comment by mrgoodrich** [comment]
My functions are working again and I was just unlucky with experiencing another problem causing my functions to fail at the exact same time as this warning.

For anyone wanting to remove the warning, in case it has other associated problems, you can force a dependency of `"@firebase/database": 0.1.9`. I tested this earlier. Also, if they choose to add the bug fix to the next release, I assume 0.1.11+ will not have the warning.

**Comment by dmurawsky** [comment]
+1

**Comment by marudits** [comment]
+1

**Comment by egr-ext** [comment]
Hi, thaks for the support. So is the solution is to configure a package.josn like that ?:
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "firebase-admin": "~5.8.1",
    "firebase-functions": "^0.8.1",
    "@firebase/database": 0.1.9
  },
  "private": true
}

**Comment by jemshit** [comment]
Why is this closed ? @tonymeng

**Comment by egr-ext** [comment]
+1 I still have a lot of warning today.

**Comment by mertkahraman42** [comment]
+1

**Comment by lanchana** [comment]
+1

**Comment by alexanderkhitev** [comment]
+1

**Comment by tonymeng** [comment]
this issue has been auto-closed as the fix has been merged, it will be available in the next version of the sdk.

as for what the issue is, there's a bug in parsing the databaseURL which causes the warning to be logged every time a new connection is made. It should not impact any part of the SDK or connectivity as the query string isn't currently being used for anything.

**Comment by fethi16** [comment]
+1

**Comment by lfernando-silva** [comment]
+1

**Comment by mvillalba2016** [comment]
I have the same problem.

Do you know when will fix this issue ?

Thanks

**Comment by di9it** [comment]
you can ignore it until next update...
```
        if (parseInt(firebase.SDK_VERSION.replace('.', ''), 10) === 410) {
            console.ignoredYellowBox = ['FIREBASE WARNING: Invalid query string segment:'];
        } else {
            console.error('REMOVE ME!');
        }
```

**Comment by jamatsui** [comment]
+1

**Comment by kclay** [comment]
+1

**Comment by jshcrowthe** [comment]
Hey y'all!

Appreciate all the interest in having this resolved. As the fix has already been merged it'll be released in the next version of the SDK. If you are anxious for a workaround:

1. Consider downgrading to `@firebase/database@0.1.9`, this version does not contain the bug (and the associated query param support)
2. Look at the firebase@canary package (which will always contain the latest valid code). 

**NOTE: The NPM canary tag is experimental, if you do opt for the second workaround, make sure you get back onto a mainline release ASAP**

**Comment by kleeb** [comment]
how about 0.1.11-0 ?

**Comment by jshcrowthe** [comment]
@kleeb That will also work, that is the next staged version and wasn't released when I wrote the above comment. I'll revise it 😄

**Comment by mauriciovillalba** [comment]
Do you know when will be release the new version ?

**Comment by ryanflorence** [comment]
I've started getting this after making really minimal changes to only one cloud function, but getting the warning for a number of my functions now.

**Comment by lemartva** [comment]
Same error here any idea?

**Comment by jernejc** [comment]
+1

**Comment by salifukayta** [comment]
+1

**Comment by suenwl** [comment]
+1

**Comment by sennl** [comment]
+1

**Comment by amaini** [comment]
what is the command to downgarde the firebase  
is it npm install --save firebase@firebase/database@0.1.9  
please help

**Comment by kleeb** [comment]
0.1.11 has just been released

**Comment by kleeb** [comment]
The warning still occurs on 0.1.11 version

**Comment by jshcrowthe** [comment]
@kleeb can you please try clean installing your dependencies. I just tested this myself and it seems to be working. The behavior I found was the following:

- Complete database URLs, with no query params (i.e. `https://<PROJECT>.firebaseio.com`), **do not** trigger the warning
- Complete database URLs, with a query param set to a value (i.e. `https://<PROJECT>.firebaseio.com?foo=bar`) **do not** trigger the warning
- Complete database URLs, with a query param that is not set (`https://<PROJECT>.firebaseio.com?foo`) **do** trigger the warning _(NOTE: This is intended)_

**Comment by tjkang** [comment]
finally fixed it with 0.1.11 version!

**Comment by baymaxdev** [comment]
Warning has gone away completely on latest version.
```
"dependencies": {
    "firebase-admin": "^5.9.0",
    "firebase-functions": "^0.8.1",
  },
```

**Comment by kleeb** [comment]
@jshcrowthe 
I am always cleaning out.

I guess that firebase function cache didn't catch it minutes after the release. I redeployed right now and yes - now it is fixed. Thanks!

**Comment by effs12** [comment]
first run "npm uninstall @firebase/database"
then "npm uninstall @firebase/database@0.1.8" does the trick to me :)
