### ISSUE TITLE
"firebase/functions" has no exported member 'initializeFunctions'

### ISSUE THREAD

**Issue by AbobkerElaghel** [firebase/firebase-js-sdk#5170]
Environment
  * Operating System version: Windows 10 Home
  * Browser version: Version 91.0.4472.164 (Official Build) (64-bit) (Chrome)
  * Firebase SDK version: ^9.0.0-beta.6
  * Firebase Product: functions 
 
 Describe the problem
#### Steps to reproduce:
  import {initializeFunctions} from "firebase/functions";
 // Module '"firebase/functions"' has no exported member 'initializeFunctions'.ts(2305)
 // initializeFunctions function does not exists in the Module ( firebase/functions ) in the web 9 (beta)

**Comment by looptheloop88** [comment]
Hi @AbobkerElaghel, thanks for the report. I was able to reproduce the error. You may use the codes below to initialize your Cloud Functions:

```
import { getApp } from "firebase/app";
import { getFunctions } from "firebase/functions";

const functions = getFunctions(getApp());
```

**Comment by AbobkerElaghel** [comment]
Thank you @looptheloop88 for your informative replay.
Yeah, I did come to this solution just a little after a posted this issue, BUT, the thing that made me even doubt that the IntelliSense was broking, is that in the Official Google's firebase documentation for callable functions, it tells you to initialize the functions [in this way](https://firebase.google.com/docs/functions/callable#web-v9)  web-v9.
Thank you again for the reply. 

![Screenshot 2021-07-19 224840](https://user-images.githubusercontent.com/57757187/126226155-6d15f0fa-1f2f-4894-ae59-6f0ed256ecd3.png)

**Comment by looptheloop88** [comment]
Hi @AbobkerElaghel, the sample code snippet in this [documentation](https://firebase.google.com/docs/functions/callable#set_up_your_client_development_environment) is incorrect. Also, there's no `initializeFunctions` method in the [Functions package reference](https://firebase.google.com/docs/reference/js/v9/functions) for SDK v9. Please use the code snippet that I've mentioned while we are in the process of updating the documentations. Thank you.

**Comment by AbobkerElaghel** [comment]
Thank you @looptheloop88  for the clarification.
