### ISSUE TITLE
FR: Easier access to google calendar

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#519]
Currently firebase auth is not enough for easy access to a user's google calendar even though he's logged in via the google auth provider.

It would be great if Firebase could natively add easier support and documentation to integrate the google calendar scopes through the firebase authentication.

**Comment by bojeil-google** [comment]
Hey @mesqueeb, Firebase Auth only focuses on authentication and not authorization.
We only return the OAuth access token based on the provided OAuth scopes you requested which can include Google Calendar access. If you wish to use Google Calendar API, you should use their API directly. If you need continuous access to Google Calendar, you are better off using the Google Sign-in library for web: https://developers.google.com/identity/sign-in/web/sign-in

You can still use that to sign in with Firebase Auth using the returned Google ID token or Google Access token.

Can you elaborate more on your request? Do you need a mechanism to manage your OAuth access tokens via Firebase Auth? or are you looking into built-in support for the Calendar API via Firebase Auth? The latter is out of scope as this is an authentication library.

**Comment by mesqueeb** [comment]
Dear @bojeil-google Thank you for your elaborate answers always. 

I have a firebase app where users have tasks. I want a way to synchronize the tasks to show to their google calendar and view the calendar events from their existing calendar. 

I'm now researching for the past several ways the best way to take this approach.

**Comment by bojeil-google** [comment]
Hey @mesqueeb, it is unlikely we will have any dedicated APIs for Calendar, Gmail, Drive, Youtube, etc. The list is extremely long: https://developers.google.com/identity/protocols/googlescopes
In addition, Firebase Auth is not only meant to facilitate sign-in with Google. There are many other OAuth providers that we support and plan to support in the future.
It is clearly out of scope for what Firebase Auth is designed for. 

The most reasonable option would be the capability to manage OAuth access tokens which is currently not the focus of Firebase Authentication and not supported, but is in the realm of possibility. This would facilitate access to such APIs (not just Google but other OAuth providers). Currently, Firebase Auth only returns the initial OAuth access token on sign-in and discards the returned OAuth refresh token. You are also welcome to file an official feature request for that if you haven't already done so.

**Comment by mesqueeb** [comment]
@bojeil-google Currently every time a user who's logged into firebase can see their Firestore data, but then need to log in a second time through the _Javascript GAPI_ to get the access to their calendar via GAPI.

I followed [this guide](https://developers.google.com/google-apps/calendar/quickstart/js) and was able to get this example running on top of my firebase app, even after the firebase authentication. After the second login through GAPI a user's google calendar is visible, but I'm not sure how to have the firebase user _keep_ this consent to their google calendar, so they don't need to login to GAPI / give the consent every login to firebase or on every device.

After the initial connection to the user's google calendar via the GAPI call:
```js
      function handleGAPIClientLoad() {
        gapi.load('client:auth2', initClient);
      }
      function initGAPIClient() {
        gapi.client.init({
          apiKey: API_KEY,
          clientId: CLIENT_ID,
          discoveryDocs: DISCOVERY_DOCS,
          scope: SCOPES
        }).then(function () {
          // Listen for sign-in state changes.
          gapi.auth2.getAuthInstance().isSignedIn.listen(updateSigninStatus);
        });
      }
      function signInGAPI(event) {
        gapi.auth2.getAuthInstance().signIn();
      }
```
**What data should I save** into to the firebase user? (and where? maybe in their firestore data?)

The thing I need is that after they login to firebase they can still manage their google calendar events alongside their firestore data.

→ It's a task list app (tasks in firestore) that puts the tasks in between calendar events (cal events from GAPI)

**Comment by mesqueeb** [comment]
@bojeil-google I think I'd just need a _refresh-token_ that resembles the consent to the google calendar of a certain google account, and then save this _refresh-token_ and the google account to the Cloud Firestore.

Then step 2, every time a firebase user logs in:
1. a function retrieves the _refresh-token_ and google account address from Cloud Firestore.
2. GAPI makes a request with the _refresh-token_ and the correct gmail address to make sure these are valid, if valid gives a new _refresh-token_.
3. GAPI returns the updated calendar information.
4. The new _refresh-token_ is saved in the user's Cloud Firestore again.

This seems the logical approach, unless you have any advice for me.

Now it's just a matter of which GAPI function to refresh the token. And which token to save in the user's Cloud Firestore.

**Comment by bojeil-google** [comment]
By using GApi you don't need to manage the Google refresh token. They will do that for you securely without the need to host a server. You just use that library to get the calendar specific access token whenever you need it and make API calls to Google calendar API. If you want to manage the refresh token or need to make calendar API calls from your server or from Firebase cloud functions, GApi documents how to do that: https://developers.google.com/identity/sign-in/web/backend-auth

I am not really an expert on this and this repo is for Firebase JS specific issues. I recommend you post your questions on stackoverflow. You will get more knowledgable developers who know more about GApi and Google Calendar APIs.

**Comment by katowulf** [comment]
A couple examples of integrating Firebase with Google Calendar:

https://stackoverflow.com/questions/49182671/is-it-possible-to-add-events-to-a-users-google-calendar-via-firebase-server-sid/49183647#49183647
https://stackoverflow.com/questions/39914899/using-firebase-auth-to-access-the-google-calendar-api

**Comment by samtstern** [comment]
Thanks @bojeil-google and @katowulf for your input and @mesqueeb for the question.

I am going to close this issue since Google Calendar specific features will not be added to the Firebase JS SDK.  Feel free to continue discussing though.
