### ISSUE TITLE
Firebase Auth Popup requires "unsafe-inline" csp option for script-src rule

### ISSUE THREAD

**Issue by hakankaraduman** [firebase/firebase-js-sdk#5193]
* Operating System version: Windows 10
* Browser version: Google Chrome 91.0.4472.164 (Official Build) (64-bit)
* Firebase SDK version: 8.2.1
* Firebase Product: auth

Firebase auth modal uses inline style and inline script, and forces us to use "unsafe-inline" in our csp rules.

If you add a CSP without the option of "unsafe-inline" for the script-src rule, firebase auth popup doesn't work.

I read that this is not a best practice to allow "unsafe-inline" in the CSP and I would like to remove it, if firebase allows it.

**Comment by looptheloop88** [comment]
Hi @hakankaraduman, thanks for the report. I was able to reproduce the behavior you've reported when using Firebase Auth (e.g. signInWithPopup) with Content Security Policy (CSP).

Let me check this out with our engineers here or bring someone who can provide more context about this matter.

**Comment by prameshj** [comment]
As mentioned in https://github.com/firebase/firebase-js-sdk/issues/6716#issuecomment-1466695563, we now set a nonce around the inline JS to make CSP allowlisting easier. We will track removal of the inline code in this issue.

**Comment by DellaBitta** [comment]
Checking in to see if the resolution and thread of the other issue helps / pertains at all to this issue. Thanks!
