### ISSUE TITLE
[FCM] Loading Firebase configuration into Service Worker asynchronously leads to unexpected behaviour

### ISSUE THREAD

**Issue by Nico3010** [firebase/firebase-js-sdk#5201]
In the documentation https://firebase.google.com/docs/cloud-messaging/js/receive the firebase configuration is always static, but I want to load the configuration object with a simple fetch and then initialize the app and call firebase.messaging(). This results in "This site has been updated in the background" messages when sending push notifications to two Android test devices, so something probably went wrong.

* Firebase SDK version: 8.8.0
* Firebase Product: messaging

**Comment by gsakakihara** [comment]
Do you have a small code sample that reproduces this issue? Also, you mention Android devices. What are you testing this on? Chrome for Android or some other browser? Does this only happen on a certain combination of browser and platform or does this happen for multiple combinations of those?

**Comment by MaximilianNagel** [comment]
Sorry, I don't have a code sample right now. But I think I found the source of the problem. Apparently, a service worker won't receive events like fetch and push until it successfully finishes installing and becomes "active" (https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle). I guess fetching the config takes longer than activating the service worker. Push messages are delievered before firebase is set up and for this reason the associated fetch event listener is not yet active. Chrome decides to display the "This site has been updated in the background" default notification. Could this be an explanation?

**Comment by zwu52** [comment]
@MaximilianNagel 
Possibility. Without looking at some code I can't confirm this though. 

One thing to point out is that (you probably already know), Chrome (or any modern browser) doesn't allow silent pushes. In other word, when sw receives a push event without the app in foreground, you need to make an explicit `showNotification` call.

**Comment by MaximilianNagel** [comment]
Example code is now available in my repository 'notification-client'. There is a node.js server running on heroku (https://test-notifications-api.herokuapp.com), which sends the push messages, firebase config, etc. The client app is also running on firebase (https://test-notification-client.web.app/). The server sends a push message every 5 minutes automatically, but the client can also demand one. The button 'clear all tokens' removes the references to all tokens on the server side.

So to reproduce the issue you can do the following steps:
1. Go to https://test-notification-client.web.app/ with your smartphone
2. Press register
3. Close the app and wait for automatic notifications
4. 
Once the service worker is killed and starts up again when receiving push messages, you will receive the default browser notification (at least in chrome)


I have also played around with service worker events, but I couldn't fix the issue.

**Comment by zwu52** [comment]
Thanks for sharing. 
I think async loading might be the root cause. 
This might be related https://github.com/firebase/firebase-js-sdk/pull/3780. If your fetch takes more than 1s, the silent push checker would run, complete and show the warning. 

The solution I can think of other than having you moving away from dynamic loading to increase that wait time. If you run a experiment, what's the median complete time for the fetch.

**Comment by MaximilianNagel** [comment]
Unfortunately moving away from dynamic loading is not an option for me. How exactly do I increase the wait time?
