### ISSUE TITLE
Cloud functions will not be triggered - Firestore Emulator

### ISSUE THREAD

**Issue by polymer-coder** [firebase/firebase-js-sdk#5203]
This isn't a bug report, just something I need clarification on.

I was using the emulators today and I proceeded to delete a collection when I got the warning

> Cloud function triggers will not be executed

![image](https://user-images.githubusercontent.com/71771821/127190117-f1ff27aa-b3e2-4fb3-b290-79861f7ab77b.png)

I can't ever remember seeing this before. If I do want to trigger cloud functions `onDelete`, how would I go about that?

**Comment by yuchenshi** [comment]
Thanks for the question! Deleting entire collections is a new feature we've just added and we don't trigger cloud functions for technical limitations. This is similar to the case where you clear all data using the top-level red button. You can however manually delete individual documents within the collection and you'll have the option to trigger cloud functions from there.

Deleting data from the Emulator UI is meant for debugging only and we don't advise relying on the exact behavior there. If your app uses onDelete triggers extensively, we advise deleting documents in your app using client or admin SDKs. Please let us know if you have a specific use case in mind or you have any thoughts on how we can improve the documentation.

**Comment by polymer-coder** [comment]
@yuchenshi Thanks for the explanation! I do think the error message could be more informative. 

Perhaps "Due to techincal limitations the emulator will not trigger cloud functions but deletion on a per document basis remains unchanged" or something of the sort.
