### ISSUE TITLE
Node.js Client is fetching a bad Id token

### ISSUE THREAD

**Issue by YoavGenish** [firebase/firebase-js-sdk#5211]
### Describe your environment

  * Operating System version: win 10 Home
  * Browser version:  --
  * Firebase SDK version: Admin, Client [Latest]
  * Firebase Product: auth

### Describe the problem
While integration testing the `firebase-admin` sdk i've decided to use the client sdk to sign in a test user (which i created manually) get his id token, and then pass it to the pass suite.
Yet, i was getting this error:
```javascript
  errorInfo: {
    code: 'auth/argument-error',
    message: 'Firebase ID token has invalid signature. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
  },
  codePrefix: 'auth'
}
```
my code is fine, and i followed the documents.
When cheking the length of my token i was amazed to found out it was only 902 chars, and [JWT.io](https://jwt.io/) sais the signature is invalid!

### Reprocude:
the test suit: 
```javascript
describe("auth.middleware.services", () => {
  describe.only("userActionAccess", async () => {
    var token;
    before(async () => {
      token = await getToken({ email: "test@test.com", password: "test1234" });
    });
    it("should authenticate common user", async () => {
      req = {
        params: {
          uid: "Z5jf6UUgeckiVGw9V8I2wHevpZku",
        },
        headers: {
          authentication: token,
        },
      };
      res = {
        status: (status) => {
          return {
            send: (...args) => {
              return {
                status: status,
                body: args[0],
              };
            },
          };
        },
      };

      expect(await authMiddleware.userActionAccess(req, res)).to.return(200); //not a real [expect] the code fails before. 
    });
  });
});
```
the auth middleware:
```javascript
const admin = require("firebase-admin");
admin.initializeApp({ projectId: "todoapp-68338" });
async function userActionAccess(req, res, next) {
  try {
    const uid = req.params.uid;
    const token = req.headers.authentication || "";
    console.log(token.length);
    await admin
      .auth()
      .verifyIdToken(token)
      .then((decodedToken) => {
        if (uid != decodedToken.uid || decodedToken.admin !== true) {
          throw Error("Access unauthorized");
        }
        return next();
      })
      .catch((e) => {
        throw e;
      });
  } catch (e) {
    if (e.message === "Access unauthorized") return res.status(401).send(e.message);
    console.log(e);
    return res.status(500).send({ error: "Internal Server Error" });
  }
}

module.exports = { userActionAccess };
```
the `getToken()` method, which is bascilly vanilla js client side signing in a user.

```javascript
const firebase = require("firebase");
var firebaseConfig = {
  apiKey: "my_app_key",
  authDomain: "todoapp-68338.firebaseapp.com",
  projectId: "todoapp-68338",
  storageBucket: "todoapp-68338.appspot.com",
  messagingSenderId: "1050751488222",
  appId: "1:1050751488222:web:a10f00670a5fbd80bdb24f",
  measurementId: "G-1KM2TDTXRQ",
};

firebase.initializeApp(firebaseConfig);
async function getToken({ email, password }) {
  await firebase
    .auth()
    .signInWithEmailAndPassword(email, password)
    .then((result) => {
      // console.log(result);
    });
  const token = await firebase.auth().currentUser.getIdToken();
  console.log(token);
  return token;
}
module.exports = { getToken };
```
the app key is valid and passing. 

and again when running `npm test` for this method. the `admin-sdk` is not able to verify the token!

thank you so much for the help!

**Comment by looptheloop88** [comment]
Hi @YoavGenish, thanks for the report. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue? This is to make sure that we're using the same SDK versions.

**Comment by YoavGenish** [comment]
> Hi @YoavGenish, thanks for the report. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue? This is to make sure that we're using the same SDK versions.

Sure I'd love to. Could you please be more specific on what info is missing in order to reproduce this issue?

**Comment by looptheloop88** [comment]
> > Hi @YoavGenish, thanks for the report. Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue? This is to make sure that we're using the same SDK versions.
> 
> Sure I'd love to. Could you @looptheloop88 please be more specific about what info is missing to reproduce this issue?

It would help a lot if you could create and share a sample project or code repo that I can use to reproduce the error.

**Comment by YoavGenish** [comment]
### Well,
 i've been sitting on this problem for a few days now, and when i created the mini-project, it worked prefectly!
This only leads me to the concrete conclusion that i should stop writing code and presue a different carrer. 
i guess that problem is my project. I'll continute to inspect. In the meantime thanks for you help @looptheloop88 

I think i'll close the issue for now, and open a new one or reopen this one if needed.

![giphy (1)](https://user-images.githubusercontent.com/85452423/127664409-dafc2199-f27e-4007-958d-a6d29494c251.gif)
