### ISSUE TITLE
XHR Compat Lib not loaded doing firebase/app require

### ISSUE THREAD

**Issue by jshcrowthe** [firebase/firebase-js-sdk#522]
If a user trying to use the SDK leverages the `firebase/app` entrypoint (instead of `firebase`), the XHR compatibility library isn't loaded.

This results in the following code not working in node:

```
var firebase = require('firebase/app');
require('firebase/auth');
require('firebase/database');

var app = firebase.initializeApp({ ... });
```

_From https://github.com/firebase/firebase-js-sdk/issues/349#issuecomment-366119157_

**Comment by nessup** [comment]
I have this issue as well, and currently no way to get around it.

**Comment by jshcrowthe** [comment]
@nessup, just looking at this again, this has been resolved in the latest firebase versions. Are you still seeing this issue, and if so, can you open another issue with a repro?
