### ISSUE TITLE
updateEmail ignores Multiple Email address per account setting

### ISSUE THREAD

**Issue by marklundin** [firebase/firebase-js-sdk#5228]
* Operating System version: Windows
  * Browser version: Chrome 92
  * Firebase SDK version: 9.0.0-beta.1
  * Firebase Product: auth

Calling `updateEmail` will always throw the error `auth/email-already-in-use`  when the Account Email address setting is set to 'Allow creation of multiple accounts with the same email address' in the firebase console **and** an email address has been used before.

Only Anonymous and Email with Password sign in methods have been enabled.

Expected behavior
If the setting is configured to allow for multiple emails per account, this error should not be thrown even if another account has registered with this email address.

**Comment by looptheloop88** [comment]
Hi @marklundin, thanks for the report. I tried replicating this issue, but I wasn't able to. I have enabled the "Allow creation of multiple accounts with the same email address" option in the Account email address setting. The email address was successfully updated using `updateEmail()` of JS SDK v9 without any errors. I verified that it's working fine for both v8 and v9 SDKs.

The only difference is that I used the version `9.0.0-beta.8`. Would you mind trying to the update the SDK version that you're using and see if the issue persists?

```
import { getAuth, updateEmail } from "firebase/auth";
const auth = getAuth();
updateEmail(auth.currentUser, "user@example.com").then(() => {
  // Email updated!
  // ...
}).catch((error) => {
  // An error occurred
  // ...
});
```

**Comment by marklundin** [comment]
Thanks for checking this @looptheloop88. I have updated to `9.0.0-beta.8` but the issue still persists. 

I am creating accounts using the `signInWithCustomToken` method. I don't know if that executes in a different way. Also just to clarify; you're calling `updateEmail` against with an email address that already exists correct?

**Comment by looptheloop88** [comment]
Hi @marklundin,

Considering that I have the following users registered and listed in Authentication > Users page:

> user.one@gmail.com (Provider = Email/Password)
> user.two@gmail.com (Provider = Email/Password)

If **_user.one@gmail.com_** is currently logged in using Email/Password and you update its email address to **_user.two@gmail.com_**, it is expected that the `auth/email-already-in-use` error will be thrown, even though the "Allow creation of multiple accounts with the same email address" option in Account email address setting is enabled. Please note that this option allows users to create multiple accounts using multiple providers (e.g. Google, GitHub, Facebook, etc.) for the same email address.

For instance that _**user.one@gmail.com**_ is logged in using Google authentication and you update its email address to **_user.two@gmail.com_**, the email address will be successfully updated. You'll see the following in Authentication > Users page:

> user.two@gmail.com (Provider = Email/Password)
> user.two@gmail.com (Provider = Google)

Let me know if this is similar to your case.

**Comment by marklundin** [comment]
Thanks for looking into this @looptheloop88. The issue does seem similar to your first scenario. Let me provide some more detail in case I'm overlooking something.

Account One has been created using the `signInWithCustomToken` method and the `updateEmail` has been called with `user.one@gmail.com`

Account 2 is then created using the `signInWithCustomToken` method. At this stage, no email is associated with the account. Is it expected behaviour that calling `updateEmail` with `user.one@gmail.com` for this account will throw `auth/email-already-in-use` regardless of the "Allow creation of multiple accounts with the same email address" setting?

**Comment by looptheloop88** [comment]
> Thanks for looking into this @looptheloop88. The issue does seem similar to your first scenario. Let me provide some more detail in case I'm overlooking something.
> 
> Account One has been created using the `signInWithCustomToken` method and the `updateEmail` has been called with `user.one@gmail.com`
> 
> Account 2 is then created using the `signInWithCustomToken` method. At this stage, no email is associated with the account. Is it expected behaviour that calling `updateEmail` with `user.one@gmail.com` for this account will throw `auth/email-already-in-use` regardless of the "Allow creation of multiple accounts with the same email address" setting?

Yes, since the email address is already being used by Account 1.
