### ISSUE TITLE
Resource.data based security rules malfunction when using onSnapshot

### ISSUE THREAD

**Issue by willwillems** [firebase/firebase-js-sdk#5229]
### Describe your environment

  * Operating System version: MacOS 10.14.16
  * Browser version: Chrome latest, Firefox latest
  * Firebase SDK version: ^8.6.5
  * Firebase Product: Firestore

### Describe the problem
We're having some trouble using document data based rules. The collection onSnapshot listener is able to fetch data that it should not be able to. Getting one of the documents directly is not possible, simulating the query (for one of the documents in the collection) in the firebase console gives: "Simulated read denied".

Specifically, it seems that the line: `!('access' in resource.data && (resource.data.access.size() > 0))` is evaluating to true when accessing documents trough a `onSnapshot` listener on the parent collection. All the documents in the collection have an `access` array > 1.

#### Steps to reproduce:
Create a collection with documents that contain an `access` property, a string-filled array containing ID's that correspond to keys in the auth's custom claims map.

Accessing the documents individually works as intended, throwing access denied errors when trying to read. Accessing through an `onSnapshot` listener on the parent collection allows the user to read all the collections documents. This is not a cache issue, data updates live.

#### Relevant Code:

```javascript
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
  
    match /companies/{companyId}/{document=**} {
      allow read, write:
        if request.auth != null // if user not authenticated deny
        && request.auth.token.get(companyId, null) != null // if user not part of company at all deny
        && (
              !('access' in resource.data && (resource.data.access.size() > 0)) // has no access field
           || (resource.data.access.hasAny(request.auth.token.keys())) // or has token trough custom claim
           || (request.auth.token.get(companyId, null) == "admin") // or is company admin
        );
    }
    
    match /users/{userId}/{document=**} {
    	allow read, write: if request.auth != null && request.auth.uid == userId
    }
    
    
  }
}
```

If any other code or info would be helpfull I'll gladly provide it, I have no idea what's going one here 😅

**Comment by willwillems** [comment]
@wu-hui if there is anything I can do to help out in terms of making more clear what's going on, making this easier to reproduce etc. let me know

**Comment by wu-hui** [comment]
Hey @willwillems 

Sorry I have not been able to spend some time on this issue yet. Will look into this today.

**Comment by wu-hui** [comment]
Hey there,

So this is actually a known issue. Basically, the issue comes up with the `!('access' in resource.data)` pattern. I am bringing this up to the team owning this, but there is no ETA at this moment of when this can be fixed.

In the meantime, I suggest you to try to re-model your data and rules to avoid this pattern..to unblock yourself.

For googlers: this is tracked internally b/129293104

Closing this for now, will report back when this is fixed.

**Comment by willwillems** [comment]
@wu-hui thanks so much we were under the impression that we were likely misunderstanding something so this has already been super helpful. I do have one further question.

Could you confirm or deny that all security rules using `resource.data` in this manner malfunction?

I tried simply removing the line you talked about and not checking for existence of the `access` field but the problem persisted.

Even when I replace:
```
(
      !('access' in resource.data && (resource.data.access.size() > 0)) // has no access field
   || (resource.data.access.hasAny(request.auth.token.keys())) // or has token trough custom claim
   || (request.auth.token.get(companyId, null) == "admin") // or is company admin
)
```
with:
```
"mu3VLwuYjnlbtcLmyrvT" in resource.data.access
```
and make sure every record has that string in its `access` list, I can still only access them (all) directly but not through an `onSnapshot` listener on their parent collection.

Being able to keep the line `resource.data.access.hasAny(request.auth.token.keys())` would be enough for us to implement a basic version of our permission system but otherwise we'll have to rethink this for now.

Thanks for everything so far!

**Comment by willwillems** [comment]
Oh wow I didn't fully realise the impact this would have but unless I am missing something the statement "`resource.data` based rules malfunction when being used through `onSnapshot` on their parent collection" is true.

This means a rule including this:
```
resource.data.admin == true;
```

Also malfunctions, I've tried this and when setting all documents' admin property to true I can in fact access them all individually but not through a listener on their collection. This seems like a huge problem to me, am I doing something else wrong? If not how do people usually work around this?

**Comment by willwillems** [comment]
For others bumping into this, this is where it went wrong for us:

All our documents were accessible according to the rules so we figured we could just query on the general collection and get them all but you need to be explicit about your query.

Meaning: if your security rule checks for `admin == uid` you **need** to include `.where("admin", "==", uid)` even though all your documents may have admin == uid.
