### ISSUE TITLE
npm ERR! notarget No matching version found for firebase@^9.5.0.

### ISSUE THREAD

**Issue by llogaran** [firebase/firebase-js-sdk#5231]
environment:

  * Operating System version: __windows 10___
  * Browser version: _chrome Versión 92.0.4515.107____
  * Firebase SDK version: __9.5.0___
  * Firebase Product: __all___ (auth, database, storage, etc)

Describe the problem:

I updated npm, and then i can not deploy anymore to firebase, i tried to update firebase and and got ERROR:

PS C:\Users\xxxxx\Desktop\name-proyecto\nameproject> npm i firebase
npm ERR! code ETARGET
npm ERR! notarget No matching version found for firebase@^9.5.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxx\AppData\Roaming\npm-cache\_logs\2021-08-02T19_52_06_515Z-debug.log

**Comment by Feiyang1** [comment]
The current firebase version is `8.8.1`. Are you trying to use the Firebase Admin SDK, whose package name is `firebase-admin`

**Comment by llogaran** [comment]
I got this firebase version 9.5.0 when i updated npm. But i just installed the 8.8.1, and is working ok. 
Thanks for you attention!
