### ISSUE TITLE
Related to #4241; firebase esm support

### ISSUE THREAD

**Issue by andrewsuperlegit** [firebase/firebase-js-sdk#5234]
### [REQUIRED] Describe your environment

  * Operating System version: Kali Linux 2021.2
  * Browser version: Chrome 91.0.4472.164
  * Firebase SDK version: ^8.8.1
  * Firebase Product: app, auth

#### Steps to reproduce:
1. Follow these instructions:
https://firebase.google.com/docs/web/setup

with essentially a default webpack/babel configuration (included below)

2. Attempt to:
```javascript
import firebase from 'firebase/app';
import { GoogleAuthProvider } from 'firebase/auth';
```

3. Receive this error:
> ERROR in {script} 5:0-36
> Module not found: Error: Can't resolve 'firebase/app' in {location}
> Did you mean 'index.esm.js'?
> BREAKING CHANGE: The request 'firebase/app' failed to resolve only because it was resolved as fully specified
> (probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.

4. Google the problem, discover #4241 , agree with OP that adding this to my webpack config is a temporary hack:
```
resolve: {
  alias: {
    "firebase/app$": "firebase/app/dist/index.esm.js",
    "firebase/auth$": "firebase/auth/dist/index.esm.js",
  }
}
```

5. Realize that was created last december. So either the docs are wrong, or I'm doing something wrong somewhere that makes creating aliases in my webpack config essential, and it'd be cool to know which it is.

#### Relevant Code:

```javascript
config = {
	mode: "development",
	stats: "normal",
	entry: ["./public/scripts/start.js"],
	output: {
		path: __dirname + "/public/dist",
		filename: "packed.js"
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /(node_modules)/,
				use: {
					loader: "babel-loader",
					options: {
						presets: ["@babel/preset-env"]
					}
				}
```
##### Usage:

```javascript

async function authConfig() {
	const provider = new GoogleAuthProvider();
	try {
	    const result = await firebase.auth().signInWithPopup(provider);
	    // this is probably wrong but I never really got this far.
	    if (result) {
		ReactDOM.render(<App />, root);
	    }
	} catch (e) {
	    alert(e.message);
	        root.textContent = "you need to sign in with google, sorry";
	}
}

```

***
Really, I just need to know what to do in the meantime with this; like... if the docs are wrong, i can by all means take a stab at updating them if i know which repo they're in and if we confirm the problem. Totally willing to provide support.

**Comment by andrewsuperlegit** [comment]
Also just wanted to add that this seems related:

[Trying to deploy my Firebase cloud function that uses an expressjs server to render stuff and it's telling me ESM isn't supported?](https://stackoverflow.com/questions/68674718/trying-to-deploy-my-firebase-cloud-function-that-uses-an-expressjs-server-to-ren)

**Comment by Feiyang1** [comment]
v8 doesn't support esm(the exports field), but we are adding the support in v9, which is very close to be released. So keep an eye out for it!

In the meantime, the alias workaround should work, and I notice an obvious error in your code:
```
// wrong
import { GoogleAuthProvider } from 'firebase/auth';
```
v8 doesn't have named exports. To access `GoogleAuthProvider` in v8:

```
import firebase from 'firebase/app';
import 'firebase/auth';

const provider = new firebase.auth.GoogleAuthProvider();
```

Can you try it and see if it resolves the issue?
