### ISSUE TITLE
v9 - Firebase: Error (auth/emulator-config-failed) 

### ISSUE THREAD

**Issue by jeremytenjo** [firebase/firebase-js-sdk#5235]
Getting `Firebase: Error (auth/emulator-config-failed)` after the app re-renders. 

Using `"firebase": "^9.0.0-beta.8",`

Error name not documented in https://firebase.google.com/docs/auth/admin/errors

![image](https://user-images.githubusercontent.com/25231946/128029052-db849204-77ec-4de5-8f78-fdc471167da8.png)

Firebase context provider `firebase.js`

```js
import React, { createContext, useContext, useMemo } from 'react'
import { initializeApp } from 'firebase/app'
import { getFirestore } from 'firebase/firestore'
import { getAuth } from 'firebase/auth'

import firebaseConfig from './config'
import initializeEmulator from './initializeEmulator'

export const FirebaseContext = createContext(null)

export const FirebaseProvider = ({ children }) => {
  const firebaseApp = initializeApp(firebaseConfig)
  const auth = getAuth()
  const db = getFirestore()

  useMemo(() => {
    initializeEmulator({ auth, db })
  }, [])

  return (
    <FirebaseContext.Provider
      value={{
        firebaseApp,
        auth,
        db,
      }}
    >
      {children}
    </FirebaseContext.Provider>
  )
}

/**
 * @returns {{
 * firebaseApp
 * auth
 * db
 * }}
 */
const useFirebase = () => useContext(FirebaseContext)

export default useFirebase
```

`initializeEmulator.js`

```js
export default function initializeEmulator({ auth, db }) {
  if (process.env.NODE_ENV === 'development') {
    startAuthEmulator(auth)
    startFirestoreEmulator(db)
    styleEmulatorWarning()
  }
}

const startAuthEmulator = (auth) => {
  const testUser = {
    username: 'test@gmail.com',
    password: 'testpassword',
  }

  connectAuthEmulator(auth, 'http://localhost:9005')

  onAuthStateChanged(auth, (user) => {
    if (!user) {
      createUserWithEmailAndPassword(auth, testUser.username, testUser.password).then(
        () => {
          signInWithEmailAndPassword(auth, testUser.username, testUser.password)
        },
      )
    }
  })
}

const startFirestoreEmulator = (db) => {
  connectFirestoreEmulator(db, 'localhost', 9003)
}
```

**Comment by jbalidiong** [comment]
Hi @jeremytenjo, thanks for the report. I tried replicating, but I wasn't able to reproduce the error.
 
If I can replicate the issue, I can have a better look into it. Please share a [minimal, but complete](https://stackoverflow.com/help/mcve) sample of a project that I can run locally.

**Comment by sam-gc** [comment]
Thanks for reaching out-- that error is thrown when the SDK has already made network requests (and is therefore no longer able to initialize the emulator). The emulator should be connected once, right after auth is initialized.

(Error thrown here: https://github.com/firebase/firebase-js-sdk/blob/8893c82256d272e3b47a794aa5fabdf7e00f9cc1/packages-exp/auth-exp/src/core/auth/emulator.ts#L52)

**Comment by jeremytenjo** [comment]
> Thanks for reaching out-- that error is thrown when the SDK has already made network requests (and is therefore no longer able to initialize the emulator). The emulator should be connected once, right after auth is initialized.
> 
> (Error thrown here:
> 
> https://github.com/firebase/firebase-js-sdk/blob/8893c82256d272e3b47a794aa5fabdf7e00f9cc1/packages-exp/auth-exp/src/core/auth/emulator.ts#L52
> 
> )

Thanks for the reply, does `firebase/auth` provide a function that returns whether the auth emulator has been initialized?

**Comment by jeremytenjo** [comment]
> Thanks for reaching out-- that error is thrown when the SDK has already made network requests (and is therefore no longer able to initialize the emulator). The emulator should be connected once, right after auth is initialized.
> 
> (Error thrown here:
> 
> https://github.com/firebase/firebase-js-sdk/blob/8893c82256d272e3b47a794aa5fabdf7e00f9cc1/packages-exp/auth-exp/src/core/auth/emulator.ts#L52
> 
> )

Thanks @sam-gc , your comment is the solution to my problem.
