### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by nehal-karanjekar** [firebase/firebase-js-sdk#5243]
I am trying to import this library to use firebase feature import firebase from 'firebase/app';
It is giving below error 
"Uncaught SyntaxError: Cannot use import statement outside a module"
at line
{
function(module, exports) {

	import firebase from '@firebase/app';
	export { default } from '@firebase/app';

	var name = "firebase";
	var version = "8.8.1";
........
}

**Comment by nehal-karanjekar** [comment]
thank you for reply. I will discuss it with discord community

in my case importing firebase/app instead of the @ version :- both are not working
 with @ giving error on below line
 /***/ function(module, exports) {

	import { __values, __assign } from 'tslib';
	import { ErrorFactory, deepCopy, contains, deepExtend, createSubscribe, isBrowser, isNode } from '@firebase/util';
	import { ComponentContainer, Component } from '@firebase/component';
	import { Logger, setLogLevel, setUserLogHandler } from '@firebase/logger';

**Comment by looptheloop88** [comment]
I agree with @akauppi that this doesn't seem like a bug report. You may just follow the official way of importing the JS SDK into your app.

**Comment by ZeinMansor** [comment]
its an issue
I have been debugging this for two days now, I tried every thing possible
tried older versions and failed
used browserify and webpack and gloriously failed
I went so far with this and run the code in a Linux virtual machine, it simply  refuses to work
please someone fix it,  a have a huge amount of work to deliver
firebase version ^9.11.1
nodejs version v14.17.5

**Comment by akauppi** [comment]
@ZeinMansor You have my empathy, but seriously, nothing in the above is like a proper bug report.

**Comment by hsubox76** [comment]
Just to clear up any misunderstandings, the reason we are closing this bug is because it seems like a problem with your build pipeline/environment and not with Firebase. You will probably get that error trying to `import` any package. Your best hope is to talk to experts in whatever environment or runtime or build tool or compiler you are using. You can start with a google search for the exact phrase "cannot use import statement outside a module". There are many solutions depending on which environment you're in.

**Comment by ZeinMansor** [comment]
Thank you for your time responding
Even though the problem was solved
I still don't know what exactly the problem was
All i did was installing the latest version of the package on a fresh start
I apologize for my rudeness, and thanks for your support
Your sincerely
