### ISSUE TITLE
getToken returns error e.getComponent is not a function

### ISSUE THREAD

**Issue by dziudek** [firebase/firebase-js-sdk#5246]
### [REQUIRED] Describe your environment

  * Operating System version: mac OS Big Sur 11.4
  * Browser version: Chrome Version 92.0.4515.131 (Official Build) (x86_64)
  * Firebase SDK version: 8.8.1
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

During tests of the web push messaging we have discovered a strange problem - during calling `getToken()` method the following error occurs:

```
TypeError: e.getComponent is not a function
    at platformLoggerService.ts:55
    at platformLoggerService.ts:35
    at Array.map (<anonymous>)
    at X.getPlatformInfoString (platformLoggerService.ts:34)
    at generate-auth-token-request.ts:47
    at tslib.es6.js:102
    at Object.next (tslib.es6.js:83)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at p (tslib.es6.js:72)
```

Firstly I supposed that it can be some race condition, some unloaded libraries etc. But when I call in the JS console:

```js
firebase.messaging().getToken()
```

The same error occurs. Also this error occurs for:

```js
firebase.messaging().deleteToken()
```

The only solution is to revoke notifications and reload the website. The strangest part is that it occurs only on some accounts at our service and if I switch Chrome profile, for the same service account there is no problem - looks like some internal issue which happens after specific period of time. 

#### Steps to reproduce:

Unfortunately I do not know way to reproduce - the issue occurs only with specific accounts and on specific Chrome profile.

#### Relevant Code:

Below the simplified version of the code, to visualize where the error appears according to my debugging:

```js
class Custom_FCM {
    constructor() {
        if (!('Notification' in window)) {
            return;
        }

        this.init();
    }

    init () {
        try {
            const config = {
                'messagingSenderId': 'XXXXXXXXXX',
                'apiKey': 'XXXXXXXXXXXXXXXXXXX',
                'projectId': 'XXXXXXXXXXXXXXXXX',
                'appId': 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
            };

            firebase.initializeApp(config);
            this.messagingInstance = firebase.messaging();
            this.checkPermissions();

            this.messagingInstance.onTokenRefresh(() => {
                this.messagingInstance.getToken().then((refreshedToken) => {
                    console.log('[i] TOKEN REFRESH SEND!');
                }).catch((err) => {
                    console.log('Unable to retrieve refreshed token ', err);
                });
            });
        } catch (e) {
            console.log('Cannot initialize FCM');
        }
    }

    checkPermissions () {
        if (window.Notification.permission === 'granted') {
            this.messagingInstance.getToken().then(token => {
                console.log('[i] ACCEPTED PERMISSIONS INFO SENT');
                this.readyToListenForMessages();
            }).catch(error => {    
                console.log('getToken ERROR:', error); // <-- ERROR GOES HERE      
                this.checkStatus(true);
            });
        } else if (window.Notification.permission === 'default') {
            this.checkStatus();
        }
    }

    readyToListenForMessages () {
        this.messagingInstance.onMessage((payload) => {
            console.log('Message received. ', JSON.stringify(payload));
        });
    }
}
```

**Comment by looptheloop88** [comment]
Hi @dziudek, thanks for the report. Since this issue can't be reproduced consistently, I suggest that you reach out to [Firebase support](https://firebase.google.com/support). This doesn't seem to be a bug report on the SDK, rather an issue with the Firebase project level. You might have restrictions on the APIs that your project is using.
