### ISSUE TITLE
v9 - Firebase: Error (auth/user-cancelled) 

### ISSUE THREAD

**Issue by takashimamorino** [firebase/firebase-js-sdk#5253]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.5
  * Browser version: Google Chrome 92.0
  * Firebase SDK version: 9.0.0-beta.8
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Getting `Uncaught (in promise) FirebaseError: Firebase: Error (auth/user-cancelled).`

Error name not documented in https://firebase.google.com/docs/auth/admin/errors

![image](https://user-images.githubusercontent.com/44386888/128456452-ee3cae50-6ce5-491e-9ee6-16d34dbb7239.png)
![image](https://user-images.githubusercontent.com/44386888/128456589-3d0997fb-3b25-4957-bc59-f834fd4ea37d.png)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jbalidiong** [comment]
Hi @takashimamorino, thanks for the report. The `auth/user-cancelled` error that you’ve encountered means that **_“The user did not grant your application the permissions it requested”_**.
 
We are aware that not all authentication errors are listed in our documentations. For now, you may refer to the [TypeScript sources](https://github.com/firebase/firebase-js-sdk/blob/a831aec9ec82d146fef7a0f7cf2d31081bd08d4b/packages-exp/auth-exp/src/core/errors.ts#L323-L324) to see the description of the authentication error codes. I also added a feature request label to this issue thread. 
 
Lastly, you may also add a catch block for better error handling.
