### ISSUE TITLE
V9 Auth additionalUserInfo missing from login results

### ISSUE THREAD

**Issue by daveteu** [firebase/firebase-js-sdk#5257]
### [REQUIRED] Describe your environment

  * Operating System version: macos
  * Browser version: chrome
  * Firebase SDK version: 9.0.0-beta.6
  * Firebase Product: auth

### [REQUIRED] Describe the problem
The code below used to return user. additionalUserInfo, but now it's replaced with _tokenResponse.

This information contains additionalUserInfo.isNewUser which identifys new user registration. The information is now inside _tokenReponse, while `user.additionalUserInfo` is now `undefined`. 

**Is this permanent change or bug?** I cannot find documentation on this.

![image](https://user-images.githubusercontent.com/18649392/128664065-226e80e1-c236-4bbf-89a7-11380c7dc15b.png)

#### Relevant Code:

```

const auth = getAuth(firebase);

const async loginGoogleCredentials (tokenId) => {
  const credential = GoogleAuthProvider.credential(tokenId)
  return await signInWithCredential(auth, credential).catch(function(error) {
    return(error)
};
```
```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by MistaPidaus** [comment]
you have to import the function `getAdditionalUserInfo from firebase/auth` to get the `additionalUserInfo` data

**Comment by jbalidiong** [comment]
Hi @daveteu, thanks for the report. As mentioned by @MistaPidaus, you should first import the `getAdditionalUserInfo` to use it. I was able to get the details by using this snippet:

```
signInWithPopup(firebaseAuth, provider)
      .then((result) => {
        const details = getAdditionalUserInfo(result)
        console.log(result);
        console.log(details)
      })
      .catch((error) => {
        console.log(error);
      });
```

You can use this as a guide for your implementation.
