### ISSUE TITLE
v9 Modular: firebase getAuth method throwing error if Storage is disabled inside data:

### ISSUE THREAD

**Issue by codecycleteam** [firebase/firebase-js-sdk#5274]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS
  * Browser version: Chrome
  * Firebase SDK version: 9.0.0-beta.8
  * Firebase Product: auth, database

### [REQUIRED] Describe the problem
We are trying to use modular API in our Figma plugin code (https://www.figma.com/plugin-docs/intro/). 
In SDK 8, `firebase.auth()`  was not throwing any error. However, if I try to use module API in beta version with Figma plugin using `getAuth( firebaseApp )` , then it is giving me below error
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.
    at new BrowserLocalPersistence ... at _getInstance ...  at _initializeAuthInstance 
```

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by sam-gc** [comment]
Hi, thanks for the issue report. `getAuth()` initializes auth as a default with all the bells and whistles attached. If you're using the `getAuth()` for the browser environment (the default), `getAuth()` is a drop in replacement for this:

```js
initializeAuth(app, {
  popupRedirectResolver: browserPopupRedirectResolver,
  persistence: [indexedDBLocalPersistence, browserLocalPersistence, browserSessionPersistence],
});
```

You can customize this to get around the issue (I'm not sure what Figma actually supports, you'll have to play around with it):

```js
initializeAuth(app, {
  persistence: indexedDBLocalPersistence,
})
```
for example.

Here are the docs for `initializeAuth`: https://firebase.google.com/docs/reference/js/v9/auth.md#initializeauth
