### ISSUE TITLE
v9 signInWithPopup opens in top left instead of centre screen

### ISSUE THREAD

**Issue by ivanvanderbyl** [firebase/firebase-js-sdk#5275]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.5.1
  * Browser version: 92.0.4515.107
  * Firebase SDK version: 9.0.0-beta.8
  * Firebase Product: auth

### [REQUIRED] Describe the problem

After migrating from v8 to v9, using `signInWithPopup(auth, googleProvider)`, the popup opens in the top left corner of the screen. This is a regression from v8 where it opens in the centre of the screen, which is not configurable in v9.

#### Steps to reproduce:

- Call `signInWithPopup()`
- Observe the position of the popup that it opens.

#### Relevant Code:

```javascript
  const google = new GoogleAuthProvider()
  const auth = getAuth(firebaseApp)
  return signInWithPopup(auth, google)
```

**Comment by sam-gc** [comment]
Thanks for catching this! The PR I just linked should fix the issue :)

**Comment by ivanvanderbyl** [comment]
Thanks for the quick fix @sam-gc !
