### ISSUE TITLE
[FCM] Is there a way to subscribe a react (web) app to a topic?

### ISSUE THREAD

**Issue by pushpendra2011** [firebase/firebase-js-sdk#5289]
I am using FCM in my React application, I want to blast a push notification for all the web users whenever there is a change happening for one collection. I am unable to find anything for web app, I am aware that we can use `subscribeToTopic('topic')` for native apps, but if I want to achieve the same behavior for web app, is there a way to do so?

**Comment by jbalidiong** [comment]
Hi @pushpendra2011, thanks for the question. Unfortunately, `@firebase/messaging` does not have the method `subscribeToTopic`. This can be done with the Admin SDK. As mentioned in the [document](https://firebase.google.com/docs/cloud-messaging/js/topic-messaging), you can use the FCM Admin API to subscribe and unsubscribe devices from a topic.
 
```
admin.messaging().subscribeToTopic(registrationTokens, topic)
  .then((response) => {
    // See the MessagingTopicManagementResponse reference documentation
    // for the contents of the response.
    console.log('Successfully subscribed to topic:', response);
  })
  .catch((error) => {
    console.log('Error subscribing to topic:', error);
  });
```
 
Based on your use-case, you can add the code to subscribe topics at your own server and let the web app call the function for subscribing to topics.
