### ISSUE TITLE
disableWarnings on connectAuthEmulator is not working

### ISSUE THREAD

**Issue by numfin** [firebase/firebase-js-sdk#5297]
* Operating System version: WSL2/Ubuntu 20
  * Browser version: NodeJS 14
  * Firebase SDK version: ^9.0.0-beta.8
  * Firebase Product: auth

When using `connectAuthEmulator(auth, host, { disableWarnings: true })` on nodejs (with jest) i still getting `console.info WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.`
I looked into firebase code and there is `console.info` even with disableWarnings=true. Could you fix it please >_>

p.s. jest.spy(console.info) is not a solution

**Comment by sam-gc** [comment]
Hi @numfin, thanks for reaching out. This is working as intended. The `{disableWarnings: true}` flag only applies to the banner for now. (The same behavior is found in v8)

**Comment by numfin** [comment]
@sam-gc If its working why i still see console.info in nodejs program?

**Comment by sam-gc** [comment]
The `disableWarnings` flag only removes the banner that's attached to the DOM. At this time we do _not_ want to ever silence the `console.info` warning as well. This is for safety reasons so that it's impossible to be in emulator mode with no indication/warning at all.

**Comment by numfin** [comment]
@sam-gc  if I'm sure I want to remove console.warn for my tests, I don't have that option right now. I would like to take responsibility for my projects myself and use {disableWarnings} in my tests.
Personally, I don't need to be reminded that I am using an emulator. Instead, it's better to provide an accessible way to connect this emulator. I suppose the decision of the obligatory output to the console was made precisely due to the fact that the emulator is connected implicitly through the environment variables.

**Comment by numfin** [comment]
@sam-gc to understand my problem better, look at this screenshot:

![image](https://user-images.githubusercontent.com/8134947/129903278-5497de5b-a149-4697-a877-ce42699dd9f3.png)
