### ISSUE TITLE
token returned from createCustomToken() not working in REST call

### ISSUE THREAD

**Issue by oreporan** [firebase/firebase-js-sdk#53]
### Environment

  * Operating System version: Mac Sierra 10.12.5 
  * Firebase SDK version: 3.6.3
   * Firebase Admin SDK version: 4.2.1
  * Firebase Product: auth (auth, database, storage, etc)

### Problem
I would like to create a custom token using `createCustomToken()` , and then I need to make
a REST call using the API like : 
`http://firebase....com/.json?auth=<ACCESS_TOKEN>`
OR
`http://firebase....com/.json?access_token=<ACCESS_TOKEN>`
(I've tried both)
I am always getting 401, even when there are **no** rules on the firebase node I'm trying to reach (unprotected).

#### Steps to reproduce:
use the SDK to create a custom token
take this token and attempt to make a REST call to some firebase node
#### Relevant Code:
```javascript
const accessToken = await firebaseAdmin.auth().createCustomToken("SomeIssuer", { scopes: "SomeScope" });
 const axiousReq = await axios.get('http://firebase....com/.json?access_token=' + accessToken);
```

**Comment by jsayol** [comment]
I'm not 100% sure since I haven't used the REST API but I think you need to use the generated custom token to obtain a Firebase ID token. This might help: https://firebase.google.com/docs/reference/rest/auth/

**Comment by oreporan** [comment]
Thanks, I figured that might be the case but I couldn't find that section in the readme.
I'll check it out

**Comment by bojeil-google** [comment]
As @jsayol mentioned, you are using this incorrectly. Custom auth tokens are exchanged for Firebase ID tokens which you can then use to query the database.
