### ISSUE TITLE
Uncaught (in promise) FirebaseError: Firebase: Error (auth/account-exists-with-different-credential).

### ISSUE THREAD

**Issue by DominicTobias** [firebase/firebase-js-sdk#5304]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS
  * Browser version: Chrome 92
  * Firebase SDK version: 9.0.0-beta.7
  * Firebase Product: auth

### [REQUIRED] Describe the problem

After a redirect login to a social provider (`signInWithRedirect(auth, provider)`), if the user already has another provider linked we will get the error `auth/account-exists-with-different-credential`.

```ts
const auth = getAuth(firebaseApp)
getRedirectResult(auth).catch(err => {
  console.error(err)
})
```

We can handle that error to link accounts.

However internally Firebase throws the error anyway and breaks the app:

```
errors.ts:91 Uncaught (in promise) FirebaseError: Firebase: Error (auth/account-exists-with-different-credential).
    at createErrorInternal (assert.ts:95)
    at _createError (assert.ts:81)
    at _makeTaggedError (index.ts:257)
    at _performFetchWithErrorHandling (index.ts:148)
    at async _performSignInRequest (index.ts:187)
    at async _signInWithCredential (credential.ts:41)
    at async RedirectAction.onAuthEvent (abstract_popup_redirect_operation.ts:102)
```

![Screenshot 2021-08-15 at 14 10 41](https://user-images.githubusercontent.com/760314/129479829-227a9963-f527-4407-a737-d2c8d7d40e20.png)

#### Steps to reproduce:

- Try to connect to an oAuth account when there is already one on the account. Upon redirecting back Firebase will throw an error that I haven't managed to handle (tried ErrorBoundaries, try/catches etc). In development mode frameworks like Create React App and NextJS will display unhandled errors in the browser, blocking the UI.

#### Solution

Firebase shouldn't throw an unhandled error that we can't intercept handle ourselves. Gracefully handling `auth/account-exists-with-different-credential` is a legitimate use case to prevent unhandled mayhem.

Thanks!

**Comment by DominicTobias** [comment]
On a side note we are expected to link accounts by getting existing providers `fetchSignInMethodsForEmail(auth, email)` and using `linkWithCredential(result.user, credential)` after authenticating with one of them. However Firebase doesn't provide an idiomatic way to retrieve an email, only to retrieve a credential:

```ts
const credential = OAuthProvider.credentialFromError(err)
const email = err.customData?.email // No OAuthProvider.emailFromError(err) :(
```

That would be useful since the location of email has changed over time (from `err.email` to the above).

**Comment by sam-gc** [comment]
Hi, thanks for opening this issue. The problem is the SDK was asynchronously throwing the error in the initialization phase, and since initialization is a hanging promise, there was no way to catch that error. The PR I linked above removes this behavior; the error can instead be retrieved the standard way through `getRedirectResult()` as you've noted.

**Comment by DominicTobias** [comment]
Great, thanks!
