### ISSUE TITLE
Realtime DB Web Client is using the hostname specified by the emulator and ignoring the one specified by `useEmulator`

### ISSUE THREAD

**Issue by aameen951** [firebase/firebase-js-sdk#5312]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 OS Version 2009 (Build 19043.1165)
  * Browser version: Google Chrome: 92.0.4515.131 (Official Build) (64-bit)
  * Firebase SDK version: 8.9.1
  * Firebase Product: Realtime Database

### [REQUIRED] Describe the problem

I'm trying to run a web application built on top of firebase from my mobile phone on a local network.
I'm specifying the host `0.0.0.0` in `firebase.json` for the realtime database emulator to allow connections from other devices.
The problem is that the emulator is sending the hostname to the database web client and the client is trying to connect to 
`0.0.0.0` instead the hostname specified in `useEmulator` function.
This problem only happens if the web client switch from using WebSocket to long polling.

### Steps to reproduce:

1. Configure the emulators as follows:
```json
  "emulators": {
    "database": {
      "host": "0.0.0.0",
      "port": 43242
    },
    "hosting": {
      "host": "0.0.0.0",
      "port": 43243
    },
  }
```

2. Try to connect to the database from the browser as follows:
```js
var firebaseConfig = { ... };
firebase.initializeApp(firebaseConfig);
const db = firebase.database();
if(LOCAL_BUILD) {
    db.useEmulator("localhost", 43242);
}
firebase.database().ref('/path/to/ref').set(11);

```

3. Force the database client to use long polling. This step I don't know how to do reliably. I found that forcing the websocket connection to fail will cause it to connect using long polling.

4. It will try to connect to 0.0.0.0 instead of the host specified in `useEmulator`

```
GET http://0.0.0.0:43242/.lp?dframe=t&id=2&pw=tWZs40gsMV&ns=<project-name>-default-rtdb
```
### Expected behavior

The expected behavior is to use the hostname provided by useEmulator. The reason for that is because let say the client is a mobile phone on the local network (which is why I'm using the host 0.0.0.0), only the client knows what the hostname actually is. The server doesn't know what the hostname should be.

### Actual behavior

The database client is using the hostname sent by the database emulator and ignoring the one specified by `useEmulator`.

### Debugging

The first request made by the client is actually correct:
```
GET http://localhost:43242/.lp?start=t&ser=6488751&cb=1&v=5&ns=<project-id>-default-rtdb
```
However, in the response of this first request is the following:
```js
function pLPCommand(c, a1, a2, a3, a4) {
parent.window["pLPCommand1"] && parent.window["pLPCommand1"](c, a1, a2, a3, a4);
}
function pRTLPCB(pN, data) {
parent.window["pRTLPCB1"] && parent.window["pRTLPCB1"](pN, data);
}
pLPCommand('start','2','tWZs40gsMV');
pRTLPCB(0,[{"t":"c","d":{"t":"h","d":{"ts":1629204262274,"v":"5","h":"0.0.0.0:43242","s":"f8ejffJfoi89FFEjNE89"}}}]);
```

In this response, you can see the hostname being sent back. All requests after that is using the provided hostname and as a result failing.

### Relevant Code:
If the described behavior wasn't intentional for reasons I don't know about this is the code that is changing the host to received one:
https://github.com/firebase/firebase-js-sdk/blob/2c90aec16ee954f4547bf54831e7b7ac9d14087b/packages/database/src/realtime/Connection.ts#L388

It should skip overwriting the host if `useEmulator` was called.

**Comment by jbalidiong** [comment]
Hi @aameen951, thanks for bringing this to our attention. I was able to reproduce the behavior now. After further investigation and discussion with the team, it is caused by an existing issue. Please try the workaround at [firebase/firebase-tools#2870 (comment)](https://github.com/firebase/firebase-tools/issues/2870#issuecomment-738189582) and let me know if it works.

**Comment by aameen951** [comment]
I should have checked the issues before opening a new one, sorry about that.

Thanks!
