### ISSUE TITLE
Including tslib in dependencies instead of devDeps

### ISSUE THREAD

**Issue by ksnyde** [firebase/firebase-js-sdk#532]
[code reference](https://github.com/firebase/firebase-js-sdk/blob/master/packages/app/package.json#L20)

You include the `tslib` package as a dependency which is a runtime library for TS and I would say stands to reason that you do _not_ have a dependency but a _devDep_. This causes problems for any app which is trying to mimize size as now `tslib` is a required upstream dependency.

**Comment by ksnyde** [comment]
Just in case this helps, here's the stack trace I'm getting. I think the above, however, is pretty clear.
![2018-02-23_11-44-53](https://user-images.githubusercontent.com/980757/36613728-406d98d2-188f-11e8-8c21-0f54ee076b87.png)

**Comment by jshcrowthe** [comment]
Hey @ksnyde, I'd love to see a demo repo containing an example as I don't have enough going on here to really triage the problem.

In Typescript 2.1, they introduced the `--importHelpers` option (see [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#support-for-external-helpers-library-tslib)) which we enabled in the 4.10.1 release. This extracts all of the helper functions that typescript uses to implement things like async/await, Object.assign, etc. It actually reduces the size of our libraries by reducing the amount of duplicate helper functions littered throughout the codebase.

Require statements for `tslib` are automatically inserted when needed during Typescript compilation, and to ensure that the lib is available it needs to be listed as a dependency.

**Comment by ksnyde** [comment]
Wow. That's really interesting. I'll have to look into this more. Issue closed.
