### ISSUE TITLE
signInWithPopup (Twitter) not Working

### ISSUE THREAD

**Issue by samyoungnyc** [firebase/firebase-js-sdk#5322]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.15.7, iOS 14.7.1
  * Browser version: Chrome 92.0.4515.131, Safari 3.13.1, Brave 1.27.111
  * Firebase SDK version: 8.7.0
  * Firebase Product: auth

#### Steps to reproduce:
For a number of weeks the code below worked with no issues. In the last 2-3 days, I have noticed that `signInWithPopup` - there have been 3 different error messages I've gotten. I didn't record the first 2 because I figured it was an aberration. The error message I'm getting now is:

`{code: "auth/invalid-credential", message: "Error getting request token: 401 {\"errors\":[{\"code…s://my-app-url.firebaseapp.com/__/auth/handler", a: null}`

What's more strange is that I encountered these issues, went to sleep and it was working again. Then, sporadically - the problem reappeared. It has not worked for me for a number of hours at this point.

I have done things like cleared cache, tried on different computer, tried on phone. I haven't changed any API values either in Twitter or Firebase console.

#### Relevant Code:

```
import firebase from 'firebase/app';

var twitterProvider = new firebase.auth.TwitterAuthProvider();

try {
  const result = await firebase.auth().signInWithPopup(twitterProvider);
  return result
} catch(e) {
  console.log(e)
  console.log(e.message)
}

```

The output:
`console.log(e) result:` 
`{code: "auth/invalid-credential", message: "Error getting request token: 401 {\"errors\":[{\"code…s://my-app-url.firebaseapp.com/__/auth/handler", a: null}`

`console.log(e.message) result:` 
`Error getting request token: 401 {"errors":[{"code":32,"message":"Could not authenticate you."}]}. Return to: https://my-app-url.firebaseapp.com/__/auth/handle`

**Comment by jbalidiong** [comment]
Hi @samyoungnyc, thanks for the report. I tried replicating and I wasn't able to reproduce the error. I noticed that you are using an outdated SDK version, would you mind trying it out with the `version 8.9.1` which is the latest for the official release. I verified that it's working fine for both `version 8.7.0` and `version 8.9.1` SDKs. Would you mind trying to update the SDK version that you're using and see if the issue persists?
 
For a guide, here is the snippet that I used:
 
```
import firebase from 'firebase/app';
import 'firebase/auth';
 
const auth = firebase.auth();
 
const goSignInWithTwitter = async (e) => {
  const provider =  new firebase.auth.TwitterAuthProvider();
 
  auth.signInWithPopup(provider)
  .then((userCredential) => {
    const user = userCredential.user;
    console.log(user);
  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    console.log(error);
  });
} 
```

**Comment by samyoungnyc** [comment]
Hi, thank you for your in-depth reply. I have tried 8.9.1 and receive the same result.

I think that the issue is related to my Twitter account - although nothing adverse has been communicated to me regarding my account - their API support team is abysmal. 

Anyways, this doesn't look to be a Firebase issue so I am closing here.

Thanks again.
