### ISSUE TITLE
Firestore not return get() Promise 

### ISSUE THREAD

**Issue by bhram** [firebase/firebase-js-sdk#533]
### [REQUIRED] Describe your environment

  * Operating System version: react native
  * Firebase SDK version: ^4.9.1
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

the promise not return 'Loading' or 'Error'  , 
it's keep in promise not return any resolve or reject, in get() or set() or update()
when i try in reactjs web it's work fine but in react native not work !!!
*note the collection and doc is exists and it's work in web 

```javascript
 try {
    const snap = await firebase.firestore().collection('users').doc('test').get();
    console.log('Loading ');
  } catch (error) {
    console.log('Error');
  }
```

**Comment by mikelehen** [comment]
Is this Android? You're probably hitting https://github.com/firebase/firebase-js-sdk/issues/283.  Can you try the suggested workaround (at the beginning of your code, before you use Cloud Firestore):

```
const originalSend = XMLHttpRequest.prototype.send;
XMLHttpRequest.prototype.send = function(body) {
  if (body === '') {
    originalSend.call(this);
  } else {
    originalSend.call(this, body);
  }
};
```

There's a pull request to fix this in React Native, but it hasn't been merged yet: https://github.com/facebook/react-native/pull/17940
