### ISSUE TITLE
[Types][v9] Missing [api].app typings for Auth, Performance, and Remote Config 

### ISSUE THREAD

**Issue by sujishpatel** [firebase/firebase-js-sdk#5346]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _9.0.0-2021720181311_
  * Firebase Product: _auth, performance, remote-config_

### [REQUIRED] Describe the problem

I was wondering if there is a plan to include `[api].app`  typings for all v9 apis?

Currently auth, performance, and remote-config don’t have it available in their typings, but they do implement it. 

Normally I would assume a typing not being included means it is intended to be private, but it doesn’t follow your typical convention of using an underscore (`_`) to denote a private property/method.

#### Relevant Code:

```javascript
console.log({ auth: getAuth() });
console.log({ performance: getPerformance() });
console.log({ remoteconfig: getRemoteConfig() });
```
![Screen Shot 2021-08-22 at 2 34 30 AM](https://user-images.githubusercontent.com/2984350/130345111-443889fd-02a4-45b5-80e8-6e1060ec71e7.png)
```js
// Typescript Errors
getAuth().app // Property 'app' does not exist on type 'Auth'.ts(2339)
getPerformance().app // Property 'app' does not exist on type 'FirebasePerformance'.ts(2339)
getRemoteConfig().app // Property 'app' does not exist on type 'RemoteConfig'.ts(2339)
```

**Comment by hsubox76** [comment]
Thanks, I think this is an omission and it should be added to our typings files.
