### ISSUE TITLE
Travis CI Logs are difficult to read

### ISSUE THREAD

**Issue by jshcrowthe** [firebase/firebase-js-sdk#535]
We are currently using the `spec` reporter for our CI environment. While this is consistent with our development env, it makes errors hard to find.

Consider switching reporters to only capture errors for CI envs.

**Comment by yifanyang** [comment]
With this [code](https://github.com/firebase/firebase-js-sdk/compare/master...yifany-log-verbosity), the karma and mocha log for succeeded tests will not display in Travis CI environment. Local development still has the full log.

Here's an [example](https://travis-ci.org/firebase/firebase-js-sdk/jobs/452111875) of how log look like now. Also please check out comparison between [previous log when some tests failed](https://travis-ci.org/firebase/firebase-js-sdk/jobs/452094924) and [new log when some tests failed](https://travis-ci.org/firebase/firebase-js-sdk/jobs/452096265).

The total length of the log is reduced, but I'm not so sure if it makes debugging any easier. Let me know what you think. @Feiyang1
