### ISSUE TITLE
k.removeEventListener is not a function

### ISSUE THREAD

**Issue by ericmorgan1** [firebase/firebase-js-sdk#538]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 11.2.6
  * Firebase SDK version: Firebase 4.10.0 / @firebase/auth@0.3.4
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem

I am using Firebase within an [Expo](https://expo.io/) / React Native app.
For some reason, when I `import` [expo-three](https://github.com/expo/expo-three), I get this error:

`k.removeEventListener is not a function. (In 'k.removeEventListener("test", ca, b)', 'k.removeEventListener is undefined)`

Stack trace gives:
`<unknown> auth.js:25:348`
`<unknown> auth.js:25:157`
`<unknown> auth.js:289:8`
`...`

If I remove the import to the `expo-three` module, the error goes away.

I'm sorry, but I didn't have the technical expertise to debug it further.
I was a little confused because my `node_modules` has a `/firebase` and a `/@firebase` and I wasn't really sure how those dependencies were working or where I could find the unminified source for this version.

My package.json is `"firebase": "^4.2.0",`

I would be happy to test things out, or I will try to find the unminified version and see if I can figure out what's going on.

I know it's a completely unrelated library, but in the stack trace all the errors are firebase files.

#### Steps to reproduce:

Just `import ExpoTHREE from 'expo-three';` is causing the error for me.

I have used `expo-three` and `firebase` together in other applications without problems.
The `expo-three` versions appear to be the same across those applications.
Some of the `firebase` versions are different, but like I said, I'm not quite sure if I should be looking at `/firebase` or `/@firebase`.

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by bojeil-google** [comment]
Can you please test this in the latest version. `4.2.0` is too old and a lot happened since then, including open sourcing.

**Comment by ericmorgan1** [comment]
Hi @bojeil-google ,
Sorry, I made a mistake. I have `4.10.0` installed. My `package.json` was just set to `^4.2.0`.

**Comment by ericmorgan1** [comment]
Here is the minified function. I have no idea where it comes from, though. I've been searching for a long time.
So the fix should maybe just check `.removeEventListener` as well.
But I can't find where the original code for this is.

```
       ec = function () {
		if (!k.addEventListener || !Object.defineProperty)
			return !1;
		var a = !1,
		b = Object.defineProperty({}, "passive", {
				get: function () {
					a = !0
				}
			});
		k.addEventListener("test", ca, b);
		k.removeEventListener("test", ca, b);
		return a
	}
	();
```

**Comment by hiroga-cc** [comment]
I have a same problem.
I removed `k.removeEventListener("test", ca, b);` from .../node_modules/@firebase/auth/dist/auth.js line 25:348 and it work for me.

**Comment by rommelpe** [comment]
@ericmorgan1, I would like to check if you are still facing the issue. I tried to reproduce this in [expo](https://expo.io) using your existing [repro](https://github.com/ericmorgan1/expo-three-firebase), and it seems to be working fine using `firebase:^5.0.4`.
