### ISSUE TITLE
npm doc - readme missing

### ISSUE THREAD

**Issue by peterpeterparker** [firebase/firebase-js-sdk#5401]
### Describe the problem

Just in case it would be unknown, the documentation - README published to [npm](https://www.npmjs.com/package/firebase) is missing after the release of v9.

It displays a nice "TODO" 😉.

### Screenshot

<img width="1513" alt="Capture d’écran 2021-08-28 à 09 38 26" src="https://user-images.githubusercontent.com/16886711/131210542-785f5d25-dd15-48f8-a1ce-af18b2bd4ef2.png">

**Comment by Feiyang1** [comment]
Thanks for the report! It's already been addressed by https://github.com/firebase/firebase-js-sdk/pull/5383 and will be published  in the next release.
