### ISSUE TITLE
importScripts not working with firebase messaging v9.0.0

### ISSUE THREAD

**Issue by ansh-les** [firebase/firebase-js-sdk#5403]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 92.0.4515.159 (Official Build) (64-bit)
  * Firebase SDK version: 9.0.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
While setting up firebase messaging, In `firebase-messaging-sw.js`, `importScripts` throws an error when you try to import
`https://www.gstatic.com/firebasejs/9.0.0/firebase-app.js` or `https://www.gstatic.com/firebasejs/9.0.0/firebase-messaging.js`

Here's the error:
`firebase-messaging-sw.js:2 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://www.gstatic.com/firebasejs/9.0.0/firebase-app.js' failed to load. at http://localhost:8080/firebase-messaging-sw.js:2:6`

However, the earlier versions like `8.10.0` or even the compat version `https://www.gstatic.com/firebasejs/9.0.0/firebase-app-compat.js` works just fine.

#### Steps to reproduce:
1. Setup firebase-messaging v9.0.0 in your JS app as per the docs.
2. Paste this content in the `firebase-messaging-sw.js`
```js
/* eslint-disable no-undef */
self.importScripts('https://www.gstatic.com/firebasejs/9.0.0/firebase-app.js')
self.importScripts(
  'https://www.gstatic.com/firebasejs/9.0.0/firebase-messaging.js'
)

const config = {
  apiKey: 'API-KEY',
  authDomain: 'AUTH-DOMAIN',
  databaseURL: 'DATABASE-URL',
  projectId: 'PROJECT-ID',
  storageBucket: 'STORAGE-BUCKET',
  messagingSenderId: 'MESSAGING-SENDER-ID',
  appId: 'APP-ID',
}

const firebaseApp = initializeApp(config)
getMessaging(firebaseApp)
```
3. Run the project and open console

**Comment by jamesdaniels** [comment]
Unless you're [building module type service workers](https://web.dev/es-modules-in-sw/), using the `import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.0.0/firebase-app.js'` syntax, which are not widely supported. You'll want to use the `-compat` libraries via `importScripts`.

Here's a quick copy-paste from a demo app I built:

```ts
importScripts('https://www.gstatic.com/firebasejs/9.0.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.0.0/firebase-messaging-compat.js');

firebase.initializeApp({ ... });

const isSupported = firebase.messaging.isSupported();
if (isSupported) {
    const messaging = firebase.messaging();
    messaging.onBackgroundMessage(({ notification: { title, body, image } }) => {
        self.registration.showNotification(title, { body, icon: image || '/assets/icons/icon-72x72.png' });
    });
}
```

**Comment by ansh-les** [comment]
Thanks for the quick response James. 
It is working with the compat libraries.
