### ISSUE TITLE
There is no way of creating `CollectionReference<T>` or `DocumentReference<T>` with custom `T` type.

### ISSUE THREAD

**Issue by sarunint** [firebase/firebase-js-sdk#5421]
### [REQUIRED] Describe your environment

  * Operating System version: N/A (TypeScript typings related)
  * Browser version: N/A (TypeScript typings related)
  * Firebase SDK version: v9.0.0
  * Firebase Product: firestore

#### Steps to reproduce:

Currently, there is no way of creating `CollectionReference<T>` or `DocumentReference<T>` with custom `T` type.

#### Relevant Code:

This code currently does not compile in TypeScript.

```typescript
doc<{ field1: number; field2: string; }>(firestore, 'path', 'to', 'document');
```

**Comment by Feiyang1** [comment]
The references shouldn't be typed directly. You need to use `withConverter()` to type them instead.  It is by design, so that you can't type references arbitrarily which may not be safe at runtime.
