### ISSUE TITLE
Bug Report: After upgrading to `7.0.2`,  AngularFireMessaging.useServiceWorker doesnt work

### ISSUE THREAD

**Issue by naveedahmed1** [firebase/firebase-js-sdk#5426]
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome
  * Firebase SDK version: 9.x
  * Firebase Product: Messaging

### Describe the problem

After upgrading to `7.0.2`, below code doesn't work

```
constructor(private messaging: AngularFireMessaging) {
    navigator.serviceWorker.getRegistration().then((registration) => {
      messaging.useServiceWorker(registration);
    });
  }
```

It seems either `useServiceWorker` is no longer supported or there's some issue with exports.

#### Steps to reproduce:

In your Angular app, just add above code and you will notice that it throws error on line `useServiceWorker`.

I have also updated the imports to `@angular/fire/compat/*` as suggested here https://github.com/angular/angularfire/blob/master/docs/version-7-upgrade.md but it still throws error.

**Comment by jamesdaniels** [comment]
@naveedahmed1 `useServiceWorker` has been depreciated so maybe it didn't make it to v9/compat, I'd suggest moving to the AngularFire `SERVICE_WORKER` DI token https://github.com/angular/angularfire/blob/master/sample-compat/src/app/app.module.ts#L91

**Comment by naveedahmed1** [comment]
Thank you so much @jamesdaniels for the update. Just a quick question, will it allow us to use Angular Service Worker along with Firebase Worker?

At the moment we have below module imported in our `AppBrowserModule`

` ServiceWorkerModule.register('https://' + window.location.hostname.toLowerCase() + '/firebase-messaging-sw-v8.js', { enabled: true, registrationStrategy: 'registerImmediately' }),`

Then we concatenate Angular Service Worker (`ngsw-worker.js`) and Firebase Messaging Worker (`messaging-sw.js`) in to `combined-sw.js`
 
`concat dist/ngsw-worker.js src/messaging-sw.js -o dist/combined-sw.js`

And then we have a file with name `firebase-messaging-sw-v8.js` with below contents:

`importScripts('https://www.mustakbil.com/combined-sw.js');`

In our messaging service we are using `useServiceWorker` to ensure Firebase Messaging is using Angular SW using below code:

```
navigator.serviceWorker.getRegistration().then((registration) => {
      messaging.useServiceWorker(registration);
    });
```

Can you please guide what should be the approach for Firebase v9?

Does just adding below provider in our messaging module ensures that Firebase is using Angular SW (i.e. our combined worker)?

`    { provide: SERVICE_WORKER, useFactory: () => typeof navigator !== 'undefined' && navigator.serviceWorker?.register('firebase-messaging-sw-v8.js', { scope: '__' }) || undefined },`

**Comment by naveedahmed1** [comment]
So, here's what finally worked for me:

Update import in my messaging service

```
import { AngularFireModule } from '@angular/fire/compat';
import { AngularFireMessaging, SERVICE_WORKER } from '@angular/fire/compat/messaging';
```

Add below provider to my notifications module:

```
providers: [
    { provide: SERVICE_WORKER, useFactory: () => typeof navigator !== 'undefined' && navigator.serviceWorker?.getRegistration() || undefined },
  ]
```

Update imports in my firebase messaging service worker:

```
importScripts('https://www.gstatic.com/firebasejs/9.0.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.0.1/firebase-messaging-compat.js');

```

At the moment docs (https://github.com/angular/angularfire/blob/master/docs/messaging/messaging.md#setting-up-the-firebase-messaging-service-worker) suggest importing `firebase-app.js` and `firebase-messaging.js` whereas we should import `firebase-app-compat.js` and `firebase-messaging-compat.js`

Add ServiceWorkerModule in browser module:


`   ServiceWorkerModule.register('https://' + window.location.hostname.toLowerCase() + '/firebase-messaging-sw-v12.js', { enabled: true, registrationStrategy: 'registerImmediately' }),`

**Comment by jamesdaniels** [comment]
Yeah those docs are in need of upgrading. If you're feeling inclined feel free to send over a PR. 

FWIW I've been leaning towards using a separate scope and not combining ngsw & fcm service workers, but having them run independently. 

I'm going to close this as it seems to be isolated to AngularFire & a work around has been found.

**Comment by naveedahmed1** [comment]
Thanks @jamesdaniels, sure I will send over the PR.

I am not very clear about scope here, can you please guide what does `scope: '__' ` mean?

`{ provide: SERVICE_WORKER, useFactory: () => typeof navigator !== 'undefined' && navigator.serviceWorker?.register('firebase-messaging-sw.js', { scope: '__' }) || undefined },`
 
AFAIK Firebase Service Worker requires root scope and Angular SW also requires the same. I am not sure if we can have two workers in root scope.

**Comment by jamesdaniels** [comment]
I did this to avoid conflict with ngsw (mostly show they both show up in chrome devtools 😛), it doesn't appear to cause any trouble with correct functionality. Since firebase-messaging-sw doesn't handle any caching or proxying the scope doesn't matter AFAIK.
