### ISSUE TITLE
Firebase storage has no exported member 'useStorageEmulator'

### ISSUE THREAD

**Issue by pmackcode** [firebase/firebase-js-sdk#5435]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.5.2
  * Browser version: Firefox 89.0.2 (64-bit)
  * Firebase SDK version: 9.0.1
  * Firebase Product: storage, emulators

#### Steps to reproduce:

Try to import the storage emulator hook from a typescript react app, using the documentation here: https://firebase.google.com/docs/emulator-suite/connect_storage

When importing the `useStorageEmulator` hook I get an error that says there is no export with that name.

The error I get is: `Module '"../../../node_modules/firebase/storage/dist/storage"' has no exported member 'useStorageEmulator'.  TS2305`

I have tried with several different versions but all give me the same error. My understanding is that this was added for v9 of the sdk. The versions I have tried are: `9.0.0, 9.0.1 and ^9.0.0-beta.8`

#### Relevant Code:

Package.json
```json
{
...
"dependencies": {
  ...
    "firebase": "^9.0.1"
  }
}
```

React Component
```typescript
import { getStorage, useStorageEmulator } from "firebase/storage";
```

Any help will be greatly appreciated

**Comment by jamesdaniels** [comment]
Good catch, it's actually `connectStorageEmulator` now, since it conflicted with React naming conventions.

**Comment by jamesdaniels** [comment]
I've sent a PR into our doc site to address, thanks for reporting.

**Comment by pmackcode** [comment]
Ah makes sense, thanks for helping me with that.
