### ISSUE TITLE
Firebase v9 setDoc() doesn't resolve or reject when using emulator

### ISSUE THREAD

**Issue by theryan722** [firebase/firebase-js-sdk#5436]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome 92.0.4515.159
  * Firebase SDK version: v9.0.1 (modular) (Tested with both v9.0.1 and v9.0.0)
  * Firebase tools: v9.17.0
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
Calling setDoc() when testing local using the emulator writes the document, but the function neither resolves or rejects. I've tried wrapping setDoc() in a try/catch block, no errors.

I can read documents fine and other tasks, but writing is what doesn't resolve.

Eventually, if I leave the page open long enough, I get this error: 
![image](https://user-images.githubusercontent.com/11343869/131948902-d7cd6db3-c6c5-4513-b41c-acbff493f2c3.png)

and than this warning:
![image](https://user-images.githubusercontent.com/11343869/131949468-61fb4013-1cf1-4b8b-87b3-89c8c987aca8.png)

#### Steps to reproduce:
Use the new modular v9 api for firestore with the local emulator suite, and write to a document (existing or non-existing) using setDoc().
#### Relevant Code:
```
try {
    console.log('before');
    await setDoc(doc(firestore, '/test/test'), { hello: 'world!' });
    console.log('not running after');
} catch (e) {
    console.log('errored: ', e);
}
```

**Comment by laurentpayot** [comment]
@theryan722 see https://github.com/firebase/firebase-js-sdk/issues/5402

**Comment by ehsannas** [comment]
@schmidt-sebastian this seems to be a duplicate of #5402 . Assigning to you as you're looking into that.

**Comment by schmidt-sebastian** [comment]
@theryan722 Can you share your entire code snippet leading up the call? It would also be helpful if you share debug logs (via `setLogLevel('debug')`) but I can also obtain them once I can reproduce.

**Comment by theryan722** [comment]
Hey @schmidt-sebastian, here's the code before the try catch:

```
import { FirebaseApp, initializeApp } from 'firebase/app';
import { getFirestore, connectFirestoreEmulator, doc, setDoc, query } from "firebase/firestore";

const firebaseConfig = { MYCONFIGHERE };
const firebaseApp = initializeApp(firebaseConfig);
const firestore = getFirestore(firebaseApp);

connectFirestoreEmulator(firestore, 'localhost', 9152);
```

**Comment by schmidt-sebastian** [comment]
I am not able to reproduce. I see "not running after" printed in both Node and in the browser. I will need debug logs to investigate further.

**Comment by schmidt-sebastian** [comment]
Can you try to see if this has in fact been fixed by https://github.com/firebase/firebase-js-sdk/pull/5434? You can try by installing `firebase@next`.

**Comment by theryan722** [comment]
Jus tried it, the issue is still there for me :( None of the other workarounds worked either, such as the user who suggested adding a delay after the auth or using long polling. Could it be an issue with the firestore emulator? Everything works fine with I don't use the emulator.

**Comment by schmidt-sebastian** [comment]
I am not able to reproduce even with the Emulator. It would really help if you shared the Console logs that you can obtain by calling `setLogLevel('true')`.

**Comment by theryan722** [comment]
Nothing logs to the console even with `setLogLevel('true')` or `setLogLevel('verbose')`. The firestore functions `setDoc()`, `updateDoc()`, `addDoc()`, `deleteDoc()` just simply to not resolve/return/reject at all, but they do affect the database (e.g. the data IS being added/updated/deleted).

I've tested now with firebase version 9.0.2, and across macOS and Windows.


<img width="550" alt="Screen Shot 2021-09-13 at 3 47 02 PM" src="https://user-images.githubusercontent.com/11343869/133147050-53e9c1f1-773b-4346-8019-cb471d33f39a.png">

**Comment by schmidt-sebastian** [comment]
Oh sorry. It should be `setLogLevel('debug')`.

**Comment by theryan722** [comment]
Gotcha, I set both firebase and firestore log levels to debug. I have attached the resulting file of a fresh page load, with testing of setDoc() and some others.
[theryan722-console-logs.log](https://github.com/firebase/firebase-js-sdk/files/7157310/theryan722-console-logs.log)

**Comment by schmidt-sebastian** [comment]
Thank you for sending these logs. The SDKs seems to function normally, but we do not receive a response from the Emulator when we try to set the document. That caused the `setDoc` operation to hang.

Assigning this to firebase-tools.

**Comment by theryan722** [comment]
Thank you @schmidt-sebastian !

**Comment by yuchenshi** [comment]
@theryan722 Would you mind grabbing the logs from the Firestore Emulator? It should be in `firestore-debug.log` in the directory where you started `firebase emulators:start`, e.g. your project directory. (Not to be confused with any console logs in your app.)

**Comment by theryan722** [comment]
Hey @yuchenshi Here is the log file:
[firebase-debug.log](https://github.com/firebase/firebase-js-sdk/files/7164409/firebase-debug.log)

**Comment by yuchenshi** [comment]
`java.lang.IllegalArgumentException: Invalid pattern. Reason: [112:<eof>] Expected '}' at end of capture expression.`

The logs indicate some issues related to function triggers -- please double check the match expressions in your triggers (e.g. `onCreate`) to make sure the curly braces are correctly closed. Please also check the security rules just in case. Let us know what match expression triggered this and we can work on improving the error.

When in doubt, disable the functions emulator temporarily with `firebase emulators:start --only firestore` and I believe you'll see the writes go through.

**Comment by theryan722** [comment]
Hey, so I corrected the bracket, but was still having issues. I then also upgraded from 9.0.2-2021891633 to the 9.0.2, and it worked with the corrected brackets in the expressions.

Thank you so much! This was driving me crazy,
