### ISSUE TITLE
Regression on firestore.Timestamp when moving to v9

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#5441]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 91
  * Firebase SDK version: 9
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

This seems to be a regression when migrating from 8 to 9.

We have a typescript class that we use both in our client application and our server application.
That means that both firebase-js-sdk & firebase-admin call it.
More specifically, in the client app it's an angular service; but we also use this service when we populate the database during e2e testing with admin.firebase.

While upgrading from 8 to 9, we get in the admin/populate script the following error:
import Timestamp = firestore.Timestamp;
POPULATE ERROR: TypeError: Cannot read property 'Timestamp' of undefined

This error has been popping up now and then over the years already, see:
https://github.com/angular/angularfire/issues/2124#issuecomment-689266826
and since the last year or so, it had stabilized and the workaround continued to work.
However seems that moving to version 9 of the sdk makes it appear again.

Any ideas?

**Comment by jbalidiong** [comment]
Thanks for reporting this @LanderBeeuwsaert. We'll investigate this shortly.

**Comment by hsubox76** [comment]
Please let me know if I'm misunderstanding, but is it possible to use `import { Timestamp } from 'firebase/firestore'` or is that not an option for your use case?

**Comment by LanderBeeuwsaert** [comment]
Good idea, however when I do this:
![image](https://user-images.githubusercontent.com/1098243/132403178-5faf0deb-0b09-48de-82d5-c9a9a5ba3d93.png)
(using the client firestore timestamp together with the admin firestore)

I get: 
![image](https://user-images.githubusercontent.com/1098243/132403258-63da6703-28e2-44de-8f09-75cf0e011d39.png)

so If I then try:
![image](https://user-images.githubusercontent.com/1098243/132403323-9d7cf3f5-0ea7-492c-987a-66e31c4ff13c.png)
(using the admin firestore timestamp together with the admin firestore)

I get:
![image](https://user-images.githubusercontent.com/1098243/132403433-14a7b0d7-3d18-4f4f-a560-4d628007d80e.png)

**Comment by hsubox76** [comment]
> Unfortunately, using the objects from the Web SDK and Admin SDK interchangeably is not supported. You've been fortunate that so far it has worked but that was sheer luck.

From https://github.com/firebase/firebase-js-sdk/issues/4129

See the link for more info and possible future plans.

**Comment by jbalidiong** [comment]
I'll be closing this issue now. If you'd like to continue the discussion, I suggest going to the linked issue.
