### ISSUE TITLE
Expected type 'Tc2', but it was: an object

### ISSUE THREAD

**Issue by LyhourChhen** [firebase/firebase-js-sdk#5446]
### [REQUIRED] Describe your environment

  * Operating System version: macosx
  * Browser version: chrome
  * Firebase SDK version: 9.0.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
Can't update the document's base on firebase firestore update documents.
[link](https://firebase.google.com/docs/firestore/manage-data/add-data#update-data)
#### Relevant Code:

```javascript
 const userRef = doc(dbInstance, COLLECTION_NAME, propsData.id);
            console.log("ref", userRef);
            await updateDoc(userRef, {
              ...propsData,
            });
```

**Comment by jbalidiong** [comment]
Hi @LyhourChhen, thanks for reporting this issue. I tried replicating and I wasn't able to reproduce the same behavior. I've used the same version and used an object as a holder of data to pass in the `updateDoc()` method and I was able to update the document in Firestore. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

You can check out the code I use as reference:

   ```
 const goUpdateDocument = async (e) => {
        const washingtonRef = doc(firebaseFirestore, "cities", data.id);

//update data from specific ID
        await updateDoc(washingtonRef, {
        data,
        });
    }
```
