### ISSUE TITLE
v9.0.1 - Compilation error: "Expression expected"

### ISSUE THREAD

**Issue by selcukbeyhan** [firebase/firebase-js-sdk#5447]
Hello,

I use ionic with Angular in following configuration:
ionic info

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 12.2.4
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : 3.2.2
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.14
   OS     : macOS Big Sur

Dependency section from package.json:
"dependencies": {
    "@angular-devkit/architect": "^0.1202.4",
    "@angular-devkit/schematics": "^12.2.4",
    "@angular/common": "^9.1.13",
    "@angular/core": "^9.1.13",
    "@angular/fire": "6.0.0",
    "@angular/forms": "^9.1.13",
    "@angular/platform-browser": "^9.1.13",
    "@angular/platform-browser-dynamic": "^9.1.13",
    "@angular/router": "^9.1.13",
    "@angular/service-worker": "^9.1.13",
    "@capacitor/android": "^3.2.2",
    "@capacitor/core": "^3.2.2",
    "@capacitor/ios": "^3.2.2",
    "@ionic/angular": "^5.7.0",
    "@ionic/angular-toolkit": "^4.0.0",
    "@mrbatista/speech-recognition": "^1.0.3",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-pipes": "^10.0.0",
    "capacitor-firebase-auth": "^0.3.1",
    "core-js": "^2.6.12",
    "dayjs": "^1.10.6",
    "firebase": "^9.0.1",
    "google-libphonenumber": "^3.2.22",
    "jetifier": "^1.6.8",
    "npm": "^6.14.14",
    "rxjs": "6.5.5",
    "tslib": "^1.14.1",
    "videogular2": "^7.0.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.15",
    "@angular-devkit/core": "^9.1.15",
    "@angular/cli": "^9.1.15",
    "@angular/compiler": "^9.1.13",
    "@angular/compiler-cli": "^9.1.13",
    "@angular/language-service": "^9.1.13",
    "@capacitor/cli": "^3.2.2",
    "@commitlint/cli": "^8.1.0",
    "@commitlint/config-angular": "^8.1.0",
    "@types/core-js": "^2.5.5",
    "@types/googlemaps": "^3.43.3",
    "@types/node": "^12.20.19",
    "@webcomponents/webcomponentsjs": "^2.6.0",
    "codelyzer": "^5.2.2",
    "husky": "^4.3.8",
    "ts-node": "^8.10.2",
    "tslint": "^6.1.3",
    "typescript": "~3.8.3"
  }

I received following error:
> ng run app:build

ERROR in node_modules/firebase/node_modules/@firebase/firestore/dist/index.d.ts:26:28 - error TS1005: ']' expected.

26     [K in keyof T & string as `${Prefix}.${K}`]+?: T[K];
                              ~~
node_modules/firebase/node_modules/@firebase/firestore/dist/index.d.ts:26:47 - error TS1005: ';' expected.

26     [K in keyof T & string as `${Prefix}.${K}`]+?: T[K];
                                                 ~
node_modules/firebase/node_modules/@firebase/firestore/dist/index.d.ts:26:49 - error TS1109: Expression expected.

26     [K in keyof T & string as `${Prefix}.${K}`]+?: T[K];
                                                   ~
node_modules/firebase/node_modules/@firebase/firestore/dist/index.d.ts:26:50 - error TS1109: Expression expected.

26     [K in keyof T & string as `${Prefix}.${K}`]+?: T[K];
                                                    ~
node_modules/firebase/node_modules/@firebase/firestore/dist/index.d.ts:27:1 - error TS1128: Declaration or statement expected.

27 };
   ~

[ERROR] An error occurred while running subprocess ng.
        
        ng run app:build exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

thank you.

**Comment by jamesdaniels** [comment]
Your AngularFire and Typescript versions are too low to work with the new version of  Firebase.
