### ISSUE TITLE
linkWithCredential error: "code":400,"message":"Invalid id_token in IdP response:<token>, error: Id_token failed validation."

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#545]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.3
  * Firebase SDK version: 4.5.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Error:
```
> message: "{"error":
>     {"code":400,"message":"Invalid id_token in IdP response:<token>, error: Id_token failed validation."}
> }"
> code: "auth/internal-error"
```

#### Steps to reproduce:

Setup the below code:

#### Relevant Code:

```js
    googleyolo.hint(oneTapConfig)
      .then(credential => dispatch('linkAnonymousUser', credential.idToken))
    // then
    linkAnonymousUser(idToken){
      let credential = firebase.auth.GoogleAuthProvider.credential(idToken)
      let signInSuccess = user => {
        console.log('Signed into firebase with credential → ', credential)
        // do we have a user?
        let hasUser = Boolean(user !== null)
        if (hasUser) {
          window.db.collection('users').doc(user.uid).set(user)
            .then(_ => commit('user/updateState', user, {root: true}))
            .catch(error => dispatch('error', {error, note: 'add user to collection error'}))
        }
      }
      return firebase.auth().currentUser.linkWithCredential(credential)
        .then(user => signInSuccess(user))
        .catch(error => dispatch('error', {error, note: 'firebase linkWithCredential error'}))
    }
```

If I try with `firebase.auth().signInWithCredential(credential)` it works fine, but linking with credential seems to fail each time for me.
I also double checked: the user selected in Google yolo does not exist yet in the firebase auth console.

**Comment by bojeil-google** [comment]
I find it very unlikely that this is accurate. The error you are seeing should also manifest for signInWithCredential.  The error is thrown when the Firebase Auth backend fails to verify the Google ID token. One reason could be that the project you are using for one-tap is different than the Firebase project or something of the like. 

I also tested linkWithCredential with a Google ID token and it worked as expected. This is a commonly used API. If this is broken, then we should hear a lot of noise about this. 

Try outputting the ID token before you link it. Also try parsing it with jwt.io to confirm its payload.

**Comment by Kisepro** [comment]
I get the same error sometimes.
It seems to happen when the time between 2 log in is too short

**Comment by kioltk** [comment]
For those ho may strugling with it: 
If you checked all fingerprint on firebase settings and etc, make sure you did revokeAccess on logout too
```
await GoogleSignin.revokeAccess();
await firebase.auth().signOut();
```

**Comment by MeghaB** [comment]
Closing this, as there's been no additional activity.
