### ISSUE TITLE
@firebase/rules-unit-testing v2, equivalent to `firebase.initializeAdminApp(...)` is missing?

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-js-sdk#5457]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: N/A
  * Firebase SDK version: `"@firebase/rules-unit-testing": "^2.0.0",`
  * Firebase Product: firestore (rules)

### [REQUIRED] Describe the problem
After updating to `@firebase/rules-unit-testing` v2, some methods for initialization changed.
Since the documentation [here](https://firebase.google.com/docs/firestore/security/test-rules-emulator) is still based on the old v1, I can only guess the new methods based on the code's jsdoc.

So I tried to setup a test environment using
```typescript
firebaseTestEnvironment = await firebase.initializeTestEnvironment({
    projectId: TEST_FIREBASE_PROJECT_ID,
    firestore: {
      rules: rulesContent,
    },
  })
```
and create authenticated environments/db accesses using
```
const bobbyDb = firebaseTestEnvironment
    .authenticatedContext('bobby', {
      email: 'bobby@example.com',
      email_verified: true,
    })
    .firestore()
```

Now, in v1 there was the possibility to create an _admin app_ (to have access to Firestore like Cloud Functions have - I used these to setup/adjust data in firestore "without" (= with full permissions) authentication).
This was possible using `firebase.initializeAdminApp({ projectId: "my-test-project" });`.

As far as it seems, such a method is missing in v2 as there is only:
```
firebaseTestEnvironment.unauthenticatedContext()
firebaseTestEnvironment.authenticatedContext(...)
```
How can in v2 such an admin access be performed?

Note: it's not about unauthenticated access - but rather full admin access to Firestore.

#### Steps to reproduce:
See above.
#### Relevant Code:
See above.

**Comment by laurentpayot** [comment]
@sceee  There is a discussion there https://github.com/firebase/firebase-js-sdk/discussions/4715#discussioncomment-1262395

**Comment by sceee** [comment]
@laurentpayot thanks for the pointer.

I saw it in [this example](https://github.com/firebase/quickstart-testing/pull/209/files) mentioned in this discussion to do it this way:
```typescript
firebaseTestEnvironment.withSecurityRulesDisabled(async (context) => {
  await context.firestore().collection('XYZ')...
})
```

I will try if that works, thanks!
