### ISSUE TITLE
@firebase/rules-unit-testing v2: `FirebaseError: Function DocumentReference.set() called with invalid data.` occurs when trying to save Timestamp from `firebase-admin/firestore` using `withSecurityRulesDisabled(..)`

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-js-sdk#5462]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: N/A
  * Firebase SDK version:
  * * `firebase`: 9.0.1
  * * `firebase-admin`: 9.100.0-alpha.1
  * * `@firebase/rules-unit-testing`: 2.0.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
In a rules test, when using `withSecurityRulesDisabled` to execute setup steps in Firestore to pre-populate some data, if the data to be populated contains a `Timestamp` from `import { Timestamp } from 'firebase-admin/firestore'`, the request to store the data in Firestore using
```typescript
await firebaseTestEnvironment.withSecurityRulesDisabled(async (context) => {
    // myObj contains a property "time" that is a Timestamp from 'firebase-admin/firestore'
    await theRef.set(myObj)
})
```
fails with `FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom object (found in field time in document test/123456789)`

#### Steps to reproduce:
1. Create an object that contains a Timestamp from `firebase-admin`:
```
import { Timestamp } from 'firebase-admin/firestore'

const testData = {
    time: Timestamp.fromDate(new Date()) // Just for testing create a Timestamp from a Date here
}
```
2. Try to save this to Firestore using the `withSecurityRulesDisabled` from @firebase/rules-unit-testing:
```typescript
const rulesContent = fs.readFileSync(path.resolve(__dirname, '../../../firestore.rules'), 'utf8')

firebaseTestEnvironment = await firebase.initializeTestEnvironment({
  projectId: TEST_FIREBASE_PROJECT_ID,
  firestore: {
    rules: rulesContent,
  },
})

await firebaseTestEnvironment.withSecurityRulesDisabled(async (context) => {
    const adminDb = context.firestore()
    await adminDb.collection('test').doc('test').set(testData) // Throws the mentioned error
})
```

=> It seems that `@firebase/rules-unit-testing` does not consider the `Timestamp` from `firebase-admin` as valid value.
Probably this also applies to other _special_ types such as `FieldValue`, but I did not test this.

#### Relevant Code:
See above.

**Comment by wu-hui** [comment]
This is duplicate of https://github.com/firebase/firebase-js-sdk/issues/4129

Unfortunately, the `Timestamp` from admin cannot be used by the Firestore SDK. I have not yet been able to find cycles to address this. You would need to use `Timestamp` from Firestore to store the value in a document, sorry for the inconvenience.

**Comment by sceee** [comment]
> This is duplicate of #4129
> 
> Unfortunately, the `Timestamp` from admin cannot be used by the Firestore SDK. I have not yet been able to find cycles to address this. You would need to use `Timestamp` from Firestore to store the value in a document, sorry for the inconvenience.

Thanks for the answer. Puh, that's bad as the `Timestamp` from admin is from the production code, so it cannot be changed to the `Timestamp` from Firestore-js-sdk (as that's not part of the production dependencies).

So unfortunately, this makes it impossible to update to @firebase/rules-unit-testing v2 at the moment as far as I see.

**Comment by yuchenshi** [comment]
@sceee Thanks for bringing this up. Just want to let you know that Admin SDK code can [directly connect to the Firestore emulator](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks) and there is no need for `withSecurityRulesDisabled`. After pre-populating has finished, you may then use `@firebase/rules-unit-testing` separately for testing security rules. (If you don't need to mock users at all, e.g. for integration testing, then you don't even need `@firebase/rules-unit-testing` at all.)
