### ISSUE TITLE
FR: addDoc when precising the document id should setDoc instead of throwing an error

### ISSUE THREAD

**Issue by floriaaan** [firebase/firebase-js-sdk#5465]
* Operating System version: Windows 11 (dev channel)
  * Browser version: Chrome 93
  * Firebase SDK version: v9
  * Firebase Product: auth, storage, firestore, cloud functions, hosting

#### Steps to reproduce:

When you put a addDoc with even segments, it automatically puts another segment that bring Firestore to fail the document creation.

#### Relevant Code:

```javascript

const groupSubscriberRef = doc(
      firestore,
      `groups/${slug}/subscribers/${user.uid}`
    );
await addDoc(groupSubscriberRef, {
        fullName: user.fullName,
        photoUrl: user.photoUrl,
        uid: user.uid,
        createdAt: new Date().toISOString(),
      });
```

To fix, just simply change addDoc to setDoc, but I personally find it annoying to not permit this king of usage.

#### How to include this in the SDK:

If doc() path param (or pathSegments) have already 4 segments, don't push another segments to the path.

**Comment by wu-hui** [comment]
addDoc: https://firebase.google.com/docs/reference/js/firestore_.md#adddoc
setDoc: https://firebase.google.com/docs/reference/js/firestore_.md#setdoc

Please note that they are expecting different type of arguments. `addDoc` expects a `CollectionReference` and creates a new document with random ID with the given content,  while `setDoc` expects a `DocumentReference`, and does an replace to that document with the given content. They are not interchangable.
