### ISSUE TITLE
createUserWithEmailAndPassword does nothing.

### ISSUE THREAD

**Issue by Lalit64** [firebase/firebase-js-sdk#5466]
Hello Firebase Team. I have bumped into an issue when trying to use Firebase and Svelte-Kit. Whenever I try the "createUserWithEmailAndPassword" method it ends up doing nothing. Please help me out.

**Comment by sam-gc** [comment]
Hi @Lalit64, could you provide some more info about the issue? Specifically:
 1. What browser are you seeing this on?
 2. What version of the SDK are you using?
 3. A small snippet of code demonstrating the problem (i.e. how are you calling `createUserWithEmailAndPassword()`?)
