### ISSUE TITLE
FACTOR_ID static string returning "undefined" for PhoneMultifactorGenerator

### ISSUE THREAD

**Issue by devfmartell** [firebase/firebase-js-sdk#5480]
After we upgraded from V8 to V9 our MFA was not working anymore. 
We were using that static string (FACTOR_ID in the PhoneMultifactorGenerator) to do a check on the factorId property in the resolver's hint for MFA. Now the value of FACTOR_ID is undefined instead of "phone". Sample code below.

We are only allowing phone as a second factor, which is why this check is there. For now we hardcoded this as a string but we would like to keep using the static enum/string since it should always match the resolver's hint factor. 

Any idea why is this now undefined or if there is a fix in the near future?
firebase": "9.0.2

```import firebase from "firebase/compat/app";
import "firebase/compat/auth";

if ( this.resolver.hints[0].factorId === firebase.auth.PhoneMultiFactorGenerator.FACTOR_ID && this.recaptchaVerifier ) {}

**Comment by sam-gc** [comment]
Thanks for pointing this out! We are working on a fix
