### ISSUE TITLE
Auth.onAuthStateChange incorrectly typed

### ISSUE THREAD

**Issue by rickstaa** [firebase/firebase-js-sdk#5483]
### Describe your environment

  * Operating System version: Ubuntu 20.04
  * Browser version: Chrome - Version 93.0.4577.63 (Official Build) (64-bit), Firefox - 92.0 (64-bit)
  * Firebase SDK version: 9.02
  * Firebase Product: auth

### Describe the problem

I run into problems when using the [onauthstatechanged](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onauthstatechanged) function inside one of my typescript projects. Every time when I try to access the `acessToken` attribute inside the callback function, I receive the following error:

```bash
Property 'accesstoken' does not exist on type 'User'.
```

I think this is because the return type of the [onauthstatechanged](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onauthstatechanged) function is wrong. The return type is set to [NextOrObserver<User | null>](https://github.com/firebase/firebase-js-sdk/blob/d164cb905917546772f95ac30c9d49094b77e8ae/packages/auth/src/model/public_types.ts#L249-L253)  while the actual type that is returned is [NextOrObserver<UserImpl | null>](https://github.com/firebase/firebase-js-sdk/blob/d164cb905917546772f95ac30c9d49094b77e8ae/packages/auth/src/core/user/user_impl.ts#L55). I now use casting to solve this problem, but I think the type definitions in the `@firebase/auth` package and [SDK api documentation](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#nextorobserver:-observerany-|-a:-user-|-null-=-any) should be updated.

#### Steps to reproduce:

1. Clone [this example](https://github.com/rickstaa/onauthstatechanged-type-bug) repository.
2. Create a new firebase project and enable google, facebook and email authentication.
3. Add your firebase projects credentials to the `.env` file.
4. Install the dependencies using `npm install`.
5. Start the web server using `npm start`.
6. Uncomment line 95 in the `app.tsx` file.

#### Relevant Code:

```javascript
  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((user) => {
      if (user !== null) {
        console.log("logged in");
        console.log(user);
        // console.log(user.accesstoken); // NOTE: Uncomment to see Typescript error although accesstoken exists
      } else {
        console.log(user);
        console.log("not logged in");
      }
    });
    return unsubscribe;
  }, []);
```

**Comment by sam-gc** [comment]
Hi @rickstaa, thanks for reaching out. In this case this is expected behavior: `UserImpl` is an internal type that the SDK uses; it contains some fields (like `accessToken`) which are private implementation details. In this case, you can get the token by simply calling [`user.getIdToken()`](https://firebase.google.com/docs/reference/js/v8/firebase.User#getidtoken), which returns a promise that resolves with the token.

**Comment by rickstaa** [comment]
@sam-gc Thanks a lot for the explanation! I think I now better understand the codebase.
