### ISSUE TITLE
Firebase 4.10.x is no longer compatible with IE11

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [firebase/firebase-js-sdk#549]
Hi,

Since version 4.10.x, firebase.database query returns no results on IE11.
A return to version 4.09.x is firebase.database works well.

Is IE11 no longer supported in future releases?

**Comment by jshcrowthe** [comment]
Hey @Geoffrey-Pliez! Thanks for the report of this, support was not removed and I've fixed the issue in  #550. It'll be out in the next release!

**Comment by Geoffrey-Pliez** [comment]
ok thanks

**Comment by vincentwoo** [comment]
ETA on a release? This is kind of a big deal, didn't know there was an IE11 regression.
