### ISSUE TITLE
Firebase v9 breaks nodent with "bad" switch-case

### ISSUE THREAD

**Issue by peterbe** [firebase/firebase-js-sdk#5492]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.5
  * Browser version: n/a
  * Firebase SDK version: 9.0.2
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

I'm using [`preact-cli`](https://github.com/preactjs/preact-cli) which uses Babel to transform the compiled TypeScript to ES2015. Today, I decided to upgrade from Firebase v8 to v9. And now `npm run build` breaks with a mysterious error. 

Note! I'm not sure exactly *how* preact-cli uses Babel to compile. Nor do I really know or understand what [nodent](https://www.npmjs.com/package/nodent) is. 

#### Steps to reproduce:

```
npx preact-cli create typescript throwaway
cd throwaway
npm i firebase@9.0.2
npm i typescript@4.4.3

edit src/components/app.tsx # and add...
```
```js
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
const app = initializeApp({});
const db = getFirestore(app);
```
Now try to build:
```
▶ npm run build

> throwaway@0.0.0 build
> preact build

(node:66951) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /private/tmp/throwaway/node_modules/preact/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
 Build  [==                  ] 11% (0.9s) building(13448:6)	switch-case fall-through not supported - added break. See https://github.com/MatAtBread/nodent#differences-from-the-es7-specification
[BABEL] Note: The code generator has deoptimised the styling of /private/tmp/throwaway/node_modules/@firebase/firestore/dist/index.esm2017.js as it exceeds the max of 500KB.
✖ ERROR ../node_modules/@firebase/firestore/dist/index.esm2017.js 5152:431
Module parse failed: Unsyntactic break (5152:431)
File was processed with these loaders:
 * ../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
(Source code omitted for this binary file)
 @ ../node_modules/firebase/firestore/dist/index.esm.js 1:0-36 1:0-36
 @ ./components/app.tsx
 @ ./index.ts
```

#### Relevant Code:

Line 13448 in ./node_modules/@firebase/firestore/dist/index.esm2017.js is this:
```javascript
/** Applies a query target change from a different tab. */
// PORTING NOTE: Multi-Tab only.
async function va(t, e, n, s) {
    const i = B(t);
    if (i.qo)
    // If we receive a target state notification via WebStorage, we are
    // either already secondary or another tab has taken the primary lease.
    x("SyncEngine", "Ignoring unexpected query state notification."); else if (i.ko.has(e)) switch (n) {
      case "current":
      case "not-current":             // THIS HERE IS LINE 13448
        {
            const t = await yr(i.localStore), s = vn.createSynthesizedRemoteEventForCurrentChange(e, "current" === n);
            await ga(i, t, s);
            break;
        }

      case "rejected":
        await _r(i.localStore, e,
        /* keepPersistedTargetData */ !0), fa(i, e, s);
        break;

      default:
        F();
    }
}
```

If I manually change that to this:
```js
      case "current":
      case "not-current":
        {
            const t = await yr(i.localStore), s = vn.createSynthesizedRemoteEventForCurrentChange(e, "current" === n);
            await ga(i, t, s);
            // break;      // NOTE!
        }
        break;   // NOTE!
``` 

...then the build error goes away.

**Comment by peterbe** [comment]
I think this is the source file: https://github.com/firebase/firebase-js-sdk/blob/5f8b16808e147910c115b52f00b7c4953e252754/packages/firestore/src/core/sync_engine_impl.ts#L1435-L1449

**Comment by peterbe** [comment]
I'd be happy to help but I don't quite understand how the build system works when it generates the `dist/index.esm2017.js` but I think we need to tell it to not put a block around the two `await`s.

**Comment by Feiyang1** [comment]
I'm pretty sure it's a tooling issue with Babel, which translated async/await(in bracket) to ES2015 incorrectly. Are you able to change the target to `ES2017`, and see if you still get the same error?

**Comment by peterbe** [comment]
> I'm pretty sure it's a tooling issue with Babel, which translated async/await(in bracket) to ES2015 incorrectly. Are you able to change the target to `ES2017`, and see if you still get the same error?

Yes, I can change `tsconfig.json` to target `ES2017` but it's still producing the same error.

**Comment by Feiyang1** [comment]
You mentioned that `Babel` is used to transpile to ES2015. I meant if you can change the `Babel` config to target ES2017, or just disable Babel transpilation?

**Comment by solova** [comment]
Looks like the problem is [fast-async](https://github.com/MatAtBread/fast-async) plugin. 
I don't why `preact-cli` doesn't accept [PR ](https://github.com/preactjs/preact-cli/pull/1347)to remove this plugin. Now it´s not effective.
Also there are no answers here https://github.com/preactjs/preact-cli/issues/1591 

The default babel-config for preact-cli uses `fast-async`.
Something like this

`{
  "presets": [
    [
      "@babel/preset-env",
      {
        "bugfixes": true,
        "exclude": ["transform-regenerator", "transform-async-to-generator"]
      }
    ]
  ],
  "plugins": [
    ["module:fast-async", { "spec": true }],
    [
        "@babel/plugin-transform-react-jsx",
        {
            "pragma": "h",
            "pragmaFrag": "Fragment"
        }
    ]
  ]
}`

I tried to remove fast-async and firebase@9 works with this custom `.babelrc`.

`
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "bugfixes": true,
        "exclude": ["transform-regenerator"]
      }
    ]
  ],
  "plugins": [
    [
        "@babel/plugin-transform-react-jsx",
        {
            "pragma": "h",
            "pragmaFrag": "Fragment"
        }
    ]
  ]
}
`

For some reason in `preact-cli` typescript template `.babelrc` is in `src` folder. It's the wrong place for it. You must move it to the project root folder.

**Comment by schmidt-sebastian** [comment]
@Feiyang1 - Let me know if you just want us to update the code.

**Comment by rschristian** [comment]
@solova The PR you refer to isn't in a finished state, that's why it was never merged in.

https://github.com/preactjs/preact-cli/issues/1591 now has a solution, though I believe you can simplify it down a fair bit.

**Comment by peterbe** [comment]
I think we can close it. The culprit is this "fast-async" plugin apparently. Removing the plugin from your framework/toolset makes it possible to proceed and use Firebase SDK v9. 

I like that this issue exists for other people who might stumble into it.

**Comment by peterbe** [comment]
> @solova The PR you refer to isn't in a finished state, that's why it was never merged in.
> 

That PR seems a bit messy at this point but it appears to have good bones. Right?

> [preactjs/preact-cli#1591](https://github.com/preactjs/preact-cli/issues/1591) now has a solution, though I believe you can simplify it down a fair bit.

Yeah, that's the hack.
