### ISSUE TITLE
signInWithCredential does not resolve in iOS

### ISSUE THREAD

**Issue by roldyclark** [firebase/firebase-js-sdk#5497]
I am using firesbase-js-sdk with [capacitor](https://capacitorjs.com/). In iOS, Calling signInWithCredential successfully creates or logs in a user in Firebase, but the promise does not resolve. In the following code, neither .then or .catch blocks run. The promise hangs indefinitely.
```
export const googleLogin = async () => {
  // 1. Create credentials on the native layer
  const result = await FirebaseAuthentication.signInWithGoogle()
  // 2. Sign in on the web layer using the id token
  const credential = GoogleAuthProvider.credential(result.credential?.idToken)
  const auth = getAuth()
  await signInWithCredential(auth, credential)
    .then((response) => console.log(response))
    .catch((err) => console.log(err))
}
```
The promise is resolved as expected in the web app. I tested this on iOS 14.5 (iPhone 8, simulator) and iOS 14.7.1 (iPhone 8, physical).

Here is another discussion about it: https://github.com/robingenz/capacitor-firebase-authentication/issues/78

**Comment by roldyclark** [comment]
getDocs() does not resolve either. It seems Firebase JS SDK is not working in iOS capacitor apps.

**Comment by roldyclark** [comment]
FIXED! Here's the solution: https://harryherskowitz.com/2021/08/23/firebase-capacitor.html

**Comment by sam-gc** [comment]
I'd also recommend trying the Cordova-specific imports. Instead of importing everything from `firebase/auth`, update the imports to `firebase/auth/cordova`.

I'm going to go ahead and close this out
