### ISSUE TITLE
Firebase SDK v9 - Client offline errors using tenant

### ISSUE THREAD

**Issue by foxted** [firebase/firebase-js-sdk#5504]
### [REQUIRED] Describe your environment

  * Operating System version: 11.5
  * Browser version: Chrome 93
  * Firebase SDK version: 9.0.2
  * Firebase Product: auth, firestore

#### Steps to reproduce:

When using auth with a tenantId, cannot access firestore, the following error gets thrown: 

```FirebaseError: Failed to get document because the client is offline.```

#### Relevant Code:

```javascript
// Relevant snippet, not actual implemention

import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore, doc, getDoc } from 'firebase/firestore';

const app = initializeApp({
   // ...Firebase Config
});
const auth = getAuth(app);
auth.tenantId = 'some-tenant-id';

const firestore = getFirestore(app);

const document = getDoc(doc(firestore, 'collection', doc.id)); // <= This triggers the error.

```

This issue also happens using the compat mode (`firebase/compat/app`, etc.).

**Comment by foxted** [comment]
UPDATE: enabling `experimentalForceLongPolling` seems to solve the issue at least in compat mode.

**Comment by looptheloop88** [comment]
Hi @foxted, we really appreciate the update. The `experimentalForceLongPolling` setting or option can be a workaround to network reliability issues due to incompatibility with certain proxies, antivirus software, etc.

This issue seems fixed, so I'll close it now.
