### ISSUE TITLE
Storage: SDK V9, TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by VladRDV** [firebase/firebase-js-sdk#5510]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS BigSur Version: 11.5.2 
  * Browser version: Opera Version: 78.0.4093
  * Firebase SDK version: 9.0.2
  * Firebase Product:  storage

### [REQUIRED] Describe the problem
I am trying to migrate my webapp to Firebase SDK version 9
i am using auth, analytics and storage, auth and analytics work as expected, but when I am trying to upload image to Firebase storage this error shows up `TypeError: Cannot read property 'path' of undefined`

#### Steps to reproduce:
Try to upload any jpeg image to the storage
#### Relevant Code:

```javascript
// this is the segment, where this error occurs
uploadFile: ({fileName, file}) => {
	const firebaseStorage = () => getStorage();
	const firebaseStorageRef = ref(firebaseStorage, `Images/${fileName}`);
	return uploadBytes(firebaseStorageRef, file);
},
```
// NOTE: Providing app instance to getStorage makes no difference, the error still shows up

![storage-error](https://user-images.githubusercontent.com/19750070/133821004-24da4f0e-f771-4c06-b0f9-7969b3b255bc.png)

**Comment by hsubox76** [comment]
In your first line you're assigning an anonymous function to `firebaseStorage` that is never called, and you're passing that uncalled function to `ref`.
Instead I think you want
```
const firebaseStorage = getStorage(app);
```
And yes, app will be required.

**Comment by VladRDV** [comment]
My bad ... 
Thank you :)
