### ISSUE TITLE
`@firebase/rules-unit-testing` v2.0.0 does not provide `clearFirestoreData` function

### ISSUE THREAD

**Issue by exKAZUu** [firebase/firebase-js-sdk#5513]
### [REQUIRED] Describe your environment

  * Operating System version: any
  * Browser version: any
  * Firebase SDK version: `"@firebase/rules-unit-testing": "2.0.0",`
  * Firebase Product: `firestore emulator`

#### Steps to reproduce:

We cannot compile the following TypeScript code which we can compile and execute with `@firebase/rules-unit-testing v1.3.10` because `@firebase/rules-unit-testing v2.0.0` does not provide `clearFirestoreData` function.
But, we need to clear all the data on firestore emulator. How can we achieve that?

Note: a similar question exists on https://stackoverflow.com/questions/69060666/initializeadminapp-and-clearfirestoredata-method-no-longer-available-after-updat, but there is no answer.

```typescript
import * as firebase from '@firebase/rules-unit-testing';

beforeEach(async () => {
  await firebase.clearFirestoreData({
    projectId: process.env.FIREBASE_PROJECT_ID,
  });
}
```

**Comment by laurentpayot** [comment]
@exKAZUu I think what you are looking for is [`RulesTestEnvironment.clearFirestore()`](https://firebase.google.com/docs/rules/unit-tests#rut-v2-specific-methods).

**Comment by exKAZUu** [comment]
@laurentpayot Thanks! I missed the information.
