### ISSUE TITLE
[firebase web] Firebase SDK randomly crashes Chrome while loading website

### ISSUE THREAD

**Issue by mikron123** [firebase/firebase-js-sdk#5517]
I've created a platform which uses Firebase Analytics, Authentication and Firestore - The website crashes Chrome after a week or two randomly after running it perfectly fine. 
It's happening in the authentication stage (not sure if cause directly by Firebase Auth though) - After the crash, if I'll try to load it again, it will keep on crashing Chrome, unless I'll clean the website's cookies in Chrome.

It happened to me once while I was in the development environment, and I did confirm it happened only when the Firebase SDK was included, when I excluded it, it ran ok, when I included the firebase code back, it crashes again, until I cleaned the cookies.

Would love to hear any advice about how to analyze it, as it is so random, some users don't encounter it at all, for 1 user it happens every week or so. 

Attached is the Chrome crash report file of one of the crashes

[68c88653-7c42-4627-8024-e9ccdac3a418.zip](https://github.com/firebase/firebase-js-sdk/files/7192733/68c88653-7c42-4627-8024-e9ccdac3a418.zip)

**Comment by jbalidiong** [comment]
Hi @mikron123, thanks for reporting this behavior. I tested it on my sample project and I wasn't able to replicate it. I verified that it's working fine for `v9` SDK. If you could provide me with a reproducible code, it will help me have a better look into it.

**Comment by mikron123** [comment]
Hi @jbalidiong, that's the thing, it happens randomly, I cannot replicate it. It's the same code running without any change, then after a week or so with only a few users, it crashes Chrome (Don't have info about other browsers)
The tested code was once the most simple Analytics and Auth initialization.  

Version used: 8.3.1

**Comment by jbalidiong** [comment]
I noticed that you're still using the `v8`. The only difference is that I used the `version 9.0.2`. Would you mind trying to update the SDK version that you're using and see if the issue persists? Just FYI, going forward, any fixes will be in version 9+. For minimal change, you can use the import paths `require('firebase/compat/app')` and `require('firebase/compat/auth')`. You can also check the [documentation](https://firebase.google.com/docs/web/modular-upgrade) about upgrading from version 8 to the modular Web SDK for further information.

**Comment by mikron123** [comment]
> I noticed that you're still using the `v8`. The only difference is that I used the `version 9.0.2`. Would you mind trying to update the SDK version that you're using and see if the issue persists? Just FYI, going forward, any fixes will be in version 9+. For minimal change, you can use the import paths `require('firebase/compat/app')` and `require('firebase/compat/auth')`. You can also check the [documentation](https://firebase.google.com/docs/web/modular-upgrade) about upgrading from version 8 to the modular Web SDK for further information.

Thanks, we're going to upgrade and see.
