### ISSUE TITLE
Listener added with onChildAdded is not fired when adding a new value in Realtime Database when using Vue

### ISSUE THREAD

**Issue by harveylee** [firebase/firebase-js-sdk#5523]
vue: 3.2.10
firebase: 9.0.2

I have a database reference defined as a property of a reactive object in Vue 3.

e.g. something like:
```ts
import { ref, getDatabase, onChildAdded } from 'firebase/database'
import { reactive } from 'vue'

const state = reactive({
  get dbRef () {
    const db = getDatabase()
    return ref(db, 'mypath')
  },

  listen () {
    onChildAdded(this.dbRef, data => {
      console.log('New data at mypath')
      // populate a list
    })
  }
})
```

On app start when `listen()` is first called, the list is properly populated. However, an item is added at `mypath`, the listener fails to fire and instead I get this error:

`Uncaught TypeError: newChildren.insert is not a function` at
https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/database/src/core/snap/IndexMap.ts#L147

It seems the reason is because Vue converts the database reference to a Proxy, which causes this reference equality test to fail and subsequently branch into the wrong part of the code:
https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/database/src/core/snap/IndexMap.ts#L120

It seems like perfectly reasonable code to me, but just posting this here in case it might help others.

My workaround is to use the [`markRaw` Vue API](https://v3.vuejs.org/api/basic-reactivity.html#markraw) to prevent Vue from converting the database reference into a reactive proxy:
i.e. `return markRaw(ref(db, 'mypath'))`

**Comment by jbalidiong** [comment]
Hi @harveylee, thanks for the report. I was able to reproduce this behavior. If Vue is converting one of our Firebase objects (e.g. database reference) into a proxy, it is expected that you may experience issues when passing it back to the function. It also seems that Vue provides a utility function to get the raw object out of the proxy.

I’m going to close this issue now, but you may reopen it if you think something needs to be changed.

**Comment by boosh** [comment]
This has started happening to me too and `markRaw` doesn't fix it
