### ISSUE TITLE
Firestore Error Codes

### ISSUE THREAD

**Issue by gauntface** [firebase/firebase-js-sdk#553]
I just hit a scenario where I'd like to identify a specific error in firestore, but the error code is `6`.

1. Is this a stable error code?
1. Is there a reason this isn't a string like other SDKs?

**Comment by mikelehen** [comment]
Error codes are supposed to be strings from this list: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/util/error.ts#L27

If you're somehow getting a numeric error code, please tell us how. :-)

**Comment by merlinnot** [comment]
A little snipet:
```ts
const FIRESTORE_TOO_MANY_CONCURRENT_TRANSACTIONS = 10;
const FIRESTORE_EXPECTED_ERROR_CODES = [
  FIRESTORE_TOO_MANY_CONCURRENT_TRANSACTIONS,
];

try {
  await admin.firestore().runTransaction(async transaction => {
    const someSnapshot = await transaction.get(someRef);
    const update = computeUpdate(someSnapshot, someData);

    transaction.update(someRef, update);
  });
} catch (error) {
  if (!FIRESTORE_EXPECTED_ERROR_CODES.includes(error.code)) {
    ...
  }
}
```

**Comment by mikelehen** [comment]
admin.firestore() is actually a different codebase (sorry).  If that's where this issue is occurring, can you log a bug against https://github.com/googleapis/nodejs-firestore ?

**Comment by merlinnot** [comment]
Oh, you're right :) I missed that, but maybe @gauntface actually gets these codes in js SDK.
