### ISSUE TITLE
Hitting `KeyIndex.isDefinedOn not expected to be called.` when running on Node.

### ISSUE THREAD

**Issue by AlastairTaft** [firebase/firebase-js-sdk#5544]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur Version 11.2.3 (Apply M1) 
  * Browser version: Node.js v14.17.3
  * Firebase SDK version: 9.1.0
  * Firebase Product: database

### [REQUIRED] Describe the problem
When querying a list of records when using Node cannot use `orderByKey()`.

#### Steps to reproduce:

See sample code.

#### Relevant Code:

```javascript
var admin = require("firebase-admin")
var {
  ref,
  query,
  orderByKey,
  onValue,
} = require('firebase/database')
var serviceAccount = require("./serviceAccountKey.json")
var app = admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "*********",
})
const db = app.database()
const queryInstance = query(
  ref(
    db, 
    `chat/threads`
  ), 
  orderByKey(),
)
onValue(queryInstance, (snapshot) => {
   // .... 
})
```

Problem is in file `node_modules/@firebase/database/dist/index.node.cjs.js` line `4270`

```js
KeyIndex.prototype.isDefinedOn = function (node) {
  // We could probably return true here (since every node has a key), but it's never called
  // so just leaving unimplemented for now.
  throw util.assertionError('KeyIndex.isDefinedOn not expected to be called.'); 
};
```

If you do `return true` in here instead the code works.

**Comment by jbalidiong** [comment]
Hi @AlastairTaft, thanks for reporting. According to https://github.com/firebase/firebase-js-sdk/issues/4129#issuecomment-735992696

> Unfortunately, using the objects from the Web SDK and Admin SDK interchangeably is not supported.

I suggest if you'll start by initializing the admin, you should also use the `admin.database()`. You can check this snippet for guide:

```
    const users = db.ref('users');
    let response = [];

     users.orderByKey().on('value', (snapshot) => {
               // ..........
 });
```
