### ISSUE TITLE
Firebase Auth for Web SDK 9 not working in Incognito and is returning wrong error (SSR Node.js)

### ISSUE THREAD

**Issue by arneesh** [firebase/firebase-js-sdk#5546]
### Environment

  * Operating System version: MacOS Mojave
  * Browser version: Version 94.0.4606.61 (Official Build) (x86_64)
  * Firebase SDK version: 9.1.0
  * Firebase Product: auth

### Problem

Firebase auth for web SDK 9 is not working in incognito mode for Node.js-based SSR application.
It runs perfectly in the regular chrome tab but when I run it in incognito then it throws "wrong-password" error, which is completely wrong and doesn't let the user sign in to the application.
Login Method that I am using: `signInWithEmailAndPassword()`

The Error that gets thrown:

```javascript
Error FirebaseError: Firebase: Error (auth/wrong-password).
    at v (index-80a96710.js:473)
    at h (index-80a96710.js:444)
    at R (index-80a96710.js:973)
    at async L (index-80a96710.js:985)
    at async ot (index-80a96710.js:4574)
```

#### Steps to reproduce:
1. Create any SSR app that is running on node.js. Open Incognito mode on Chrome. Use `signInWithEmailAndPassword()` method to sign in to the app. A wrong password error will be thrown.

**Comment by arneesh** [comment]
### The above issue is in turn causing other problems.  When the `wrong-password` error gets shown to a user over and over even when they are entering the correct password, they keep trying to enter the password again and again, and eventually their account gets disabled.

```javascript
Error FirebaseError: Firebase: Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later. (auth/too-many-requests).
    at m (index-80a96710.js:452)
    at R (index-80a96710.js:970)
    at async L (index-80a96710.js:985)
    at async ot (index-80a96710.js:4574)
```

**Comment by arneesh** [comment]
The same issue is occuring in regular browser window too, not just Incognito.

**Comment by sam-gc** [comment]
Hi @arneesh, I suspect what is happening is that the SSR step is executing the `signInWithEmailAndPassword` with an email but not a password, so even if the code on the client executes correctly it sends erroneous requests from Node. Do you gate the sign-in logic to the browser-only platform?
