### ISSUE TITLE
Firebase auth unable to load on IOS with extensions

### ISSUE THREAD

**Issue by Herobone** [firebase/firebase-js-sdk#5548]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 15.0
  * Browser version: Safari 15.0
  * Addon: Firefox Focus Content Blocker
  * Firebase SDK version: 9.0.2
  * Firebase Product: auth

### Describe the problem

Whenever you load a page that uses the firebasee auth sdk, shortly after calling `getAuth` for the first time, it will crash (Webpack frames collapse).
The problem is that the contentblocker by Firefox Focus blocks the source url of gapi. When you call `getAuth` in the background the function `auth._initializeWithPersistence` (look [here](https://github.com/firebase/firebase-js-sdk/blob/316638a5bfefc191e2e171b86bd92965cd285f89/packages/auth/src/core/auth/initialize.ts#L86)) gets called but the promise gets ignored. There is even an eslint ignore statement. The comments say that it needs to be ignored in order to let it initialize in the background.
But since the promise gets ignored there is no way to catch if there was an error. It would be nice to add some way of detecting that failed initialisation to promt the user to disable the contentblocker.

I know this might just be a "me-problem" but iOS 15 added Extensions to Safari and there might be some extensions out there that will start to block resources like this more often.

#### Steps to reproduce:
 - Activate Firefox Focus in the Content Blocker Menu in Safari
 - Visit a site that uses firebase auth
 - Error can be catched via the Developer Console on a Mac
 This is the error thrown:
```
[Info] Content blocker prevented frame displaying https://sober-sailor-beta.web.app/ from loading a resource from https://apis.google.com/js/api.js?onload=__iframefcb325795 (2.b013f127.chunk.js, line 2)
[Error] Unhandled Promise Rejection: FirebaseError: Firebase: Error (auth/internal-error).
	(anonyme Funktion)
	rejectPromise
	rejectPromiseWithFirstResolvingFunctionCallCheck
	(anonyme Funktion) (2.b013f127.chunk.js:2:139747)**
```
#### Relevant Code:

```javascript
const auth = getAuth(firebaseApp);
```

**Comment by jbalidiong** [comment]
Hi @Herobone, thanks for reaching out. Would you mind sharing a small but complete example demonstrating the issue?

**Comment by sam-gc** [comment]
Thanks for filing this! On mobile browsers the SDK will preemptively load libraries needed for popup and redirect. This is necessary for seamless user interaction on mobile, but in cases like yours it can cause problems. If you want to avoid this issue, you can manually initialize Auth without the popup/redirect resolver (**note:** this will prevent popup/redirect actions, or you'll need to pass the resolver directly to those functions). For example,

```js
import {initializeAuth, indexedDBLocalPersistence, browserLocalPersistence} from 'firebase/auth';

const auth = initializeAuth(app, {
  persistence: [indexedDBLocalPersistence, browserLocalPersistence],
  /* popupRedirectResolver: undefined */
});
```

I'm going to close this out for now: the SDK is working as expected and there is a standard workaround for the issue you're experiencing.
