### ISSUE TITLE
DataSnapshot forEach method should be able to return void

### ISSUE THREAD

**Issue by Francescu** [firebase/firebase-js-sdk#555]
Code from the doc doesn't use the `return boolean`  from the `forEach` function when it doesn't want to interrupt the enumeration.

# Example
```javascript
var query = firebase.database().ref("users").orderByKey();
query.once("value")
  .then(function(snapshot) {
    snapshot.forEach(function(childSnapshot) {
      // key will be "ada" the first time and "alan" the second time
      var key = childSnapshot.key;
      // childData will be the actual contents of the child
      var childData = childSnapshot.val();
  });
});
```
# Problem
This code is not valid with the current Typescript definitions.
```
export interface DataSnapshot {
  forEach(action: (a: DataSnapshot) => boolean): boolean;
}
```
# Proposal
I'm new to Firebase so I'd be careful there. But it seems that adding to the closure return type `|void` would fix the issue. I can provide a PR, if you're OK with this solution.

```
export interface DataSnapshot {
  forEach(action: (a: DataSnapshot) => boolean|void): boolean;
}
```

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over @Francescu. We should indeed update the types. If you want to take a stab at this, I would be more than welcome to review your PR. 

Take a look here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database-types/index.d.ts

**Comment by Crazometer** [comment]
https://github.com/firebase/firebase-js-sdk/blob/master/packages/database-types/index.d.ts#L78 Can be changed to Promise<DataSnapshot>

**Comment by jshcrowthe** [comment]
Closing this as it seems things have been taken care of. Thanks!
