### ISSUE TITLE
createUserWithEmailAndPassword() method return wrong response. SSR

### ISSUE THREAD

**Issue by arneesh** [firebase/firebase-js-sdk#5556]
### Environment

  * Operating System version: MacOS Mojave
  * Browser version: Version 94.0.4606.61 (Official Build) (x86_64)
  * Firebase SDK version: 9.1.0
  * Firebase Product: auth

### Problem
I am using Vue-Node.js based SSR application. `createUserWithEmailAndPassword()` method return wrong response. When you create a user using a completely new email address, the account gets created perfectly but it returns `Firebase: Error (auth/email-already-in-use)` which is incorrect, if you check your Firebase Auth the new user is created there and the email is completely new and not one that was already in use.

This gets returned:

```javascript
Error FirebaseError: Firebase: Error (auth/email-already-in-use).
    at createErrorInternal (index-80a96710.js?8d8a:473)
    at _createError (index-80a96710.js?8d8a:447)
    at _makeTaggedError (index-80a96710.js?8d8a:1027)
    at _performFetchWithErrorHandling (index-80a96710.js?8d8a:963)
    at async _performSignInRequest (index-80a96710.js?8d8a:985)
    at async createUserWithEmailAndPassword (index-80a96710.js?8d8a:4938)
```

#### Steps to reproduce:

Create any SSR app that is running on Node.js. Use the firebase auth's `createUserWithEmailAndPassword()`.

**Comment by sam-gc** [comment]
Hi @arneesh, thanks for reaching out. I suspect what's happening here is that your `createUserWithEmailAndPassword()` call is executed first in Node (this is a totally valid use case; Node will make the network call) and then again in the browser when the page loads. In this case, the behavior is totally expected: `createUserWithEmailAndPassword()` assumes that the user does not exist yet. If this is the issue, you'll need to gate that call with a platform check to ensure it only runs once.

Would you mind sharing a small but complete example demonstrating the issue?

**Comment by arneesh** [comment]
Hey @sam-gc 
I see what you mean, initially, I thought that this might be happening which is why I ran my app in the client-only mode without SSR and still got the same response. Even in my SSR app, I am making the request after the page has already loaded via `user action` in the browser so it should not cause any issues. I even added a type check for window element just in case:  like this ->

```javascript
    let resp;
    if(typeof window === "undefined") {
      //do nothing
      console.log("do nothing")
    } else {
      resp = await createUserWithEmailAndPassword(auth, email, password);
    }
```

Let me know what you think? If you still think this might be the case then I will create a small sample repository for your reference.

**Comment by sam-gc** [comment]
It might be worth checking in the developer tools of your browser to see if the network call is made more than once. If the issue persists and you can verify only one network call to that endpoint is being made, a small sample repository would be ideal
