### ISSUE TITLE
TenentId mismatch in multi-tenant flow: auth/tenant-id-mismatch

### ISSUE THREAD

**Issue by xil222** [firebase/firebase-js-sdk#5558]
Describe your environment
  * Operating System version: macOS 11.6
  * Browser version: chrome Version 94.0.4606.61 
  * Firebase SDK version: v9.1.0
  * Firebase Product: auth
  
To reproduce
Finding the issue when testing in IAP https://team.git.corp.google.com/cicp-eng/cicp-iap-js/
Go to https://ciap-multi-tenant.uc.r.appspot.com
Switch to FirebaseUI mode by Go to FirebaseUI
1. pick tenant a, sign up or sign in with email.
![Screen Shot 2021-09-29 at 2 32 00 PM](https://user-images.githubusercontent.com/22864922/135351616-dacf1b87-9419-45d7-bfd4-3b54709a3fd6.png)
2. pick tenant a, sign in with google, you get widget always loading
![Screen Shot 2021-09-29 at 2 47 56 PM](https://user-images.githubusercontent.com/22864922/135353307-cbbcfe01-2f04-4215-bf27-57b2d2a30f4f.png)

To proceed, require access to the GCP project ciap-multi-tenant
ping me @xinxinxin if need access.

Things work fine with single tenant flow, these issues only come up in multi-tenant flow.

**Comment by sam-gc** [comment]
Hi, thanks for filing this. We will look into this, but in the meantime please keep in mind that the v9 SDK remains in Beta for Google Cloud Identity Platform features (which includes IAP support)
