### ISSUE TITLE
Incorrect Typings for database.Reference.path

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-js-sdk#556]
The `path` field of the `database.Reference` type is defined to be a string in our type defs:

```
export interface Reference extends Query {
  child(path: string): Reference;
  key: string | null;
  onDisconnect(): OnDisconnect;
  parent: Reference | null;
  path: string;
  ...
```

But in reality this takes on an object value:

```
Path { pieces_: [ 'foo' ], pieceNum_: 0 }
```

**Comment by mikelehen** [comment]
Where are you seeing that?  It should definitely be a string in our public API (but we do have an internal Path class used for our internal implementation)

**Comment by schmidt-sebastian** [comment]
The `path` property is internal and should not have been exposed in the public types. Since this is technically breaking, I will remove it in the next major release.
