### ISSUE TITLE
TypeError: (0, _storage.useStorageEmulator) is not a function. 

### ISSUE THREAD

**Issue by umrashrf** [firebase/firebase-js-sdk#5571]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur v11.6 M1 arm64
  * Browser version: Expo iPhone Client
  * Firebase SDK version: 9.1.1
  * Firebase Product: storage, emulators (auth, database, storage, etc)

### [REQUIRED] Describe the problem

This piece of code in index.js file results into this error.

```python
if (__DEV__) {
   const storage = getStorage();
   useStorageEmulator(storage, "localhost", 9199);
}
```

#### Steps to reproduce:

1. expo init
2. Install firebase 9.1.1
3. Use strorage emulator using Web 9 syntax

#### Relevant Code:
```javascript
if (__DEV__) {
   const storage = getStorage();
   useStorageEmulator(storage, "localhost", 9199);
}
```

#### Relevant Logs

```
[Sun Oct 03 2021 13:05:56.927]  BUNDLE  ./index.js 

[Sun Oct 03 2021 13:05:57.895]  INFO     WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.
[Sun Oct 03 2021 13:05:57.896]  ERROR    TypeError: (0, _storage.useStorageEmulator) is not a function. (In '(0, _storage.useStorageEmulator)(storage, "localhost", 9199)', '(0, _storage.useStorageEmulator)' is undefined)
[Sun Oct 03 2021 13:05:57.896]  LOG      Running "main" with {"rootTag":171,"initialProps":{}}
[Sun Oct 03 2021 13:05:57.900]  ERROR    Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

**Comment by jbalidiong** [comment]
Hi @umrashrf, thanks for reaching out. I tried connecting my sample project to an emulator and I was able to use it as intended. However, there is a difference in our code. I've used the `connectStorageEmulator()` as stated in the [reference for the JS SDK](https://firebase.google.com/docs/reference/js/storage.md#connectstorageemulator). Here is the snippet for guidance:

```
    if(__DEV__){
      firebaseStorage = getStorage();
      firebaseStorageDev = connectStorageEmulator(firebaseStorage, 'localhost', 9199);
      console.log('In dev environment and using emulator')
    }
```

I suggest updating the method you're using and check if the issue persists. Also, I noticed that the documentation and JS reference are inconsistent. Here's the internal bug (b/201989497) for reference.
