### ISSUE TITLE
firestore: modular doc method returns wrong type (typescript)

### ISSUE THREAD

**Issue by thdk** [firebase/firebase-js-sdk#5572]
### [REQUIRED] Describe your environment

  * Operating System version: Linux desktop 5.11.0-36-generic 40~20.04.1-Ubuntu SMP  x86_64 GNU/Linux

  * Browser version: n.a.
  * Firebase SDK version: 9.1.1
  * Firebase Product: firestore

#### Steps to reproduce:

Compile the typescript code below using firebase 9.1.1

#### Relevant Code:

```javascript
import {
    doc,
} from "firebase/firestore";

import * as types from "@firebase/firestore-types";

import { initializeTestEnvironment } from "@firebase/rules-unit-testing";

initializeTestEnvironment({})
   .then((testEnv) => {
       const firestore = testEnv.unauthenticatedContext().firestore();

       // error on below line: Type 'DocumentReference<DocumentData>' is missing the following properties from type 'DocumentReference<DocumentData>': collection, isEqual, set, update, and 3 more.ts(2740)
       const docRef: types.DocumentReference = doc(firestore, "books/foo");
   });
```
When I navigate to the typescript declaration file for `doc` I see the following signatures:
```javascript
    function doc(firestore: types.FirebaseFirestore, path: string, ...pathSegments: string[]): DocumentReference<DocumentData>;
    function doc<T>(reference: types.CollectionReference<T>, path?: string, ...pathSegments: string[]): DocumentReference<T>;
    function doc(reference: types.DocumentReference<unknown>, path: string, ...pathSegments: string[]): DocumentReference<DocumentData>;
```
As you can see the return type in the declaration file is `DocumentReference` which gets imported from `@firebase/firestore` while in other places in the same declaration file `types.DocumentReference` is used where `types` is imported from `@firebase/firestore-types`.

I would think that the types from `@firebase/firestore-types` should be compatible with those in `firebase/firestore`.

**Comment by Feiyang1** [comment]
`@firebase/firestore-types` are compat types. They are compatible with `firebase/firestore` in the sense that they are accepted in functions exported from `firebase/firestore`, but the types from the 2 packages are not compatible(you can't assign them to each other). Can you use `DocumentReference` from `firebase/firestore` instead?

**Comment by thdk** [comment]
Hi thank you for your reply. 

I have change my code now back to using `DocumentReference` from `firebase/firestore`. The reason I had started using `@firebase/firestore-types` package for my types was this comment here https://github.com/firebase/firebase-js-sdk/issues/5550#issuecomment-928453315. 

I only needed that one `FirebaseFirestore` type but got too enthusiast and started using `CollectionReference` and `DocumentReference` as well.
