### ISSUE TITLE
loading libraries locally throws "Component auth has not been registered yet"

### ISSUE THREAD

**Issue by klapauciusisgreat** [firebase/firebase-js-sdk#5597]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs BigSur
  * Browser version: 94.0.4606.81
  * Firebase SDK version: 9.1.2
  * Firebase Product: auth 

### [REQUIRED] Describe the problem
I'm writing a chrome extension and run a background script as a service worker.

When loading libraries from gstatic, I can initialize the auth object. When loading a local copy, I get this error however:
```
firebase-app.js:553 (anonymous function)

Uncaught Error: Component auth has not been registered yet
```

when executing
```
const auth = initializeAuth(firebaseApp, {persistence: indexedDBLocalPersistence});
```

I want to load the load the libraries partly because it may be faster and I can tree-shake the javascript, but mostly because I want to experiment with the code (see issue #5588 why).

#### Steps to reproduce:

 - initialize firebase app
 - initializeAuth

 - I also got the same error when initializing via getAuth() IIRC.

Thanks for letting me know how I'm holding it wrong!

Also: This is not a super new regression, I saw the same issue with 9.0.1

#### Relevant Code:

```javascript
import { initializeApp } from './firebase-app.js';
import { initializeAuth, indexedDBLocalPersistence, onAuthStateChanged, getIdToken, signOut, GoogleAuthProvider, signInWithPopup } from "./firebase-auth.js";

const firebaseApp = initializeApp({
    apiKey: "xxx",
    authDomain: "xxx",
    projectId: "xxx",
    storageBucket: "xxx",
    messagingSenderId: "xxx",
    appId: "xxx",
    measurementId: "xxx"
});

const auth = initializeAuth(firebaseApp, {persistence: indexedDBLocalPersistence}); // <--- this breaks when loading libraries locally
const provider = new GoogleAuthProvider();
```

**Comment by treeder** [comment]
I'm having the same problem using these modules with the CDN.

**Comment by treeder** [comment]
I took some advice from elsewhere to allow sharing of firebase things in other modules by putting the firebase init into a separate file, then export it to let other modules import it. So I have `firebase.js` that looks like this: 

```js
import { initializeApp } from 'https://cdn.jsdelivr.net/npm/firebase@^9.1.2/firebase-app.js/+esm' 
import { getAuth } from 'https://cdn.jsdelivr.net/npm/firebase@^9.1.2/firebase-auth.js/+esm' 

// Initialize Firebase
console.log("config", firebaseConfig)
const app2 = initializeApp(firebaseConfig);
const auth2 = getAuth(app2);

export { app2, auth2 };
```

Simply trying to import that file throws an error on the `getAuth()` line. "Component auth has not been registered yet". 

Importing like this:

```html
<script type="module">
import {app2} from '/components/firebase.js'
</script>
```

**Comment by hsubox76** [comment]
@treeder Are you also using this in a service worker or Chrome extension, and if not, what environment and browser?

**Comment by hsubox76** [comment]
Thanks! So the issue here is that these v9 CDN scripts are built to only be used from our gstatic CDN, such as
```
import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.1.2/firebase-app.js'
```
and in both cases here, they are not. The original user was using local files, and the second user is using a different CDN (jsdelivr).

The `firebase-auth.js` file imports some functions from `firebase-app.js`, specifically from `https://www.gstatic.com/firebasejs/[version]/firebase-app.js`. If you are using `initializeApp` from a different firebase-app.js file, auth will register itself with the gstatic version of firebase-app (which is treated as a separate, if identical, module) and not with yours, and `getAuth(app)` will not find it.

If you want to use native browser modules to load Firebase in other environments, you will need to build your own scripts for the preferred environment. I don't think there's any way to use those files from a CDN like jsdelivr or unkpg unfortunately.

**Comment by treeder** [comment]
Well what do ya know, that worked. :) Thanks!

Any chance gstatic supports semver versioning like jsdelivr and others? Like the ^9.1.2 I had in my imports, which is really the only reason I was trying to use jsdelivr.

**Comment by hsubox76** [comment]
No, they're just direct static urls.

**Comment by klapauciusisgreat** [comment]
Sorry for the late reply: 

the reason I use local paths is that a chrome extension with manifest v3 requires it. At least, I have not found a way to make

```import {x, y, z} from "/firebase/app/``` work.

I will look into into module bundlers and "building my own scripts". Is there a good documentation for this, @hsubox76 ?

Also, let me know what additional information you need. This is a pretty bog-standard chrome extension based on manifest v3, but since v3 extensions don't have access to window, I suspect I need to modify it by creating a whole new window for the background thread.

Thanks!
