### ISSUE TITLE
Push notification does not arrive OR arrive generic notification message

### ISSUE THREAD

**Issue by Kachyz** [firebase/firebase-js-sdk#5603]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.15.7
  * Browser version: Chrome 94.0.4606.71 (Official Build) (x86_64)
  * Firebase SDK version: firebase@8.9.1
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

Trying to start a service worker (web) sending app information through parameters not working , however if app information is set inside SW file everything works as expected.

#### Steps to reproduce:

* Call `navigation.serviceWorker.register` method with app information as params
```js
// qsConfig is an object with configuration info like 'apiKey', 'projectId', etc...
const swUrl = `${location.pathname}firebase-messaging-sw.js?${qsConfig}&appName=${appName}`;
navigator.serviceWorker.register(swUrl);
```
* SW starts
![image](https://user-images.githubusercontent.com/13111040/136842488-a66b1df7-59e9-463c-a7ff-aff6e46ea673.png)
* Send a push notification from postman with required information
* Two scenarios, notification is not received or generic notification "This site has been updated in the background" is displayed

**NOTE**
If firebase information is hardcoded inside `firebase-messaging-sw.js` file, push notification feature works as expected.

#### Relevant Code:
firebase-messaging-sw.js
```javascript
importScripts('https://www.gstatic.com/firebasejs/8.3.2/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.3.2/firebase-messaging.js');

// This method extracts information from params and returns an object or null if there is no data
const firebaseConfig = getFirebaseConfigFromSearchParams(location.search);

// firebaseConfig has connection information
if (firebaseConfig) {
  console.log('[firebase-messaging-sw.js] Received config: ', firebaseConfig);

  const { appName, config } = firebaseConfig;
  let app = firebase.apps.find((app) => app.name === appName);

  if (!app) {
    app = firebase.initializeApp(config, appName);
  }

  const messaging = firebase.messaging(app);
  messaging.onBackgroundMessage(function (payload) {
    console.log('Received background message ', payload);

    // Customize notification here
    const { notification: { body = 'body', title = 'title' } } = payload;
    const notificationOptions = {
      body,
      icon: '/firebase-logo.png',
    };
    try {
      return self.registration.showNotification(title, notificationOptions);
    } catch (err) {
      console.error(err);
    }
  });
}

```

JS file that calls SW
```javascript
if ('serviceWorker' in navigator) {
  const swUrl = `${location.pathname}firebase-messaging-sw.js?${qsConfig}&appName=${appName}`;
  navigator.serviceWorker.register(swUrl);
}
```

-----
firebase-messaging-sw.js (working version, but doesn't look into sent parameters)
```javascript
importScripts('https://www.gstatic.com/firebasejs/8.3.2/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.3.2/firebase-messaging.js');

const app = firebase.initializeApp({
  apiKey: "correctData",
  authDomain: "correctData",
  databaseURL: "correctData",
  projectId: "correctData",
  storageBucket: "correctData",
  messagingSenderId: "correctData",
  appId: "correctData"
});

const messaging = firebase.messaging(app);

messaging.onBackgroundMessage(function (payload) {
  console.log('Received background message ',payload);
  // Customize notification here
  const { notification: {body = 'body', title = 'title' }} = payload;
  const notificationOptions = {
    body,
    icon: '/firebase-logo.png',
  };

  try {
    return self.registration.showNotification(title, notificationOptions);
  } catch (err) {
    console.error(err)
  }
});

```

**Comment by hsubox76** [comment]
Are you sure that once you've extracted `firebaseConfig.config` from the query parameters, it doesn't have any extra whitespace or quotes or hidden characters or anything? Can you do a deepequal check in your code between the hardcoded config and the one you extract from the query parameters? It seems like there must be some difference.

**Comment by jbalidiong** [comment]
Thanks for the update, it looks like the initial issue was already solved. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
