### ISSUE TITLE
getRedirectResult(auth) still returns a UserCredential with a NONnull user after signing in or signing out (no redirect operation was called)

### ISSUE THREAD

**Issue by koroman17** [firebase/firebase-js-sdk#5610]
First I sign in 
```
const provider = new GoogleAuthProvider();
signInWithRedirect(auth, provider);
```
then I get a UserCredential with a NONnull user (of course)
```
const handleGetRedirectResult = async () => {
	try {
		const result = await getRedirectResult(auth);
		console.log(result);
	} catch (error) {
		console.log(error);
	}
};
handleGetRedirectResult()
```
then I run the same function again 
```
handleGetRedirectResult()
```
I still get a UserCredential with a NONnull user @@

then I sign out
```
signOut(auth)
```
then I run the function again
```
handleGetRedirectResult()
```
I still get a UserCredential with a NONnull user again @@ 
I think firebase has saved the redirect data somewhere and hasn't deleted it after first `getRedirectResult(auth)` that when I run `handleGetRedirectResult()` again, it still returns a UserCredential with a NONnull user even that I have signed out

**Comment by JGSolutions** [comment]
still getting null with 9.2.0 version

**Comment by sam-gc** [comment]
@JGSolutions, do you mean getting nonnull? The PR linked above (https://github.com/firebase/firebase-js-sdk/pull/5617) makes it so that it will return `null` on subsequent calls (as is expected)

**Comment by JGSolutions** [comment]
Yes! In version 8 was getting user and credientials objects with properties. And now they are null. If that is expected then not sure why but broke my login process
