### ISSUE TITLE
Cloud Messaging - No callback received when permissions are silently blocked

### ISSUE THREAD

**Issue by Whip** [firebase/firebase-js-sdk#5611]
* Operating System version: Windows 10
  * Browser version: Chrome 94
  * Firebase SDK version: 9.1.2
  * Firebase Product: cloud messaging

I'm implementing Cloud messaging push notifications on my project following the guides on Firebase Docs. Here's my code

```
const firebase = await import("https://www.gstatic.com/firebasejs/9.1.2/firebase-app.js");
const firebaseCM = await import("https://www.gstatic.com/firebasejs/9.1.2/firebase-messaging.js");
const fireApp = firebase.initializeApp(firebaseConfig);
const messaging = firebaseCM.getMessaging();

firebaseCM.getToken(messaging, {vapidKey: 'MYKEY'}).then((currentToken) => {
	if(currentToken){
		console.log(currentToken);
	} else {
		console.log('No registration token available. Request permission to generate one.');
	}
}).catch((err) => {
  console.log('An error occurred while retrieving token. ', err);
});
```

It works normally but in case when notification permissions are silently blocked by Chrome, I do not receive any callback. None of the console logs are triggered. Is there a function not covered in docs to handle this case?

**Silent blocking of Permissions**
Chrome will automatically block notification permissions if it was studied that you typically don't allow notifications. You don't receive a permissions prompt and instead in the URL bar, on the right side you'll see _Notifications blocked_.

![184](https://user-images.githubusercontent.com/11595460/137262056-0e278661-5cc3-4831-bf59-2fbec3370880.jpg)

**Comment by zwu52** [comment]
Chrome doesn't yet support this API. Feel free to file a feature request on Chrome.

**Comment by Whip** [comment]
I will contact Chrome team about this.
