### ISSUE TITLE
Latest Workbox and Firebase compatibility problem with IDB library

### ISSUE THREAD

**Issue by fxbit** [firebase/firebase-js-sdk#5613]
### [REQUIRED] Describe your environment

  * Operating System version: Windows - node 14
  * Firebase SDK version: 9.1.2
  * Firebase Product: Messaging

### [REQUIRED] Describe the problem
The firebase is using very old IDB library (v3.0.2 - 3 years old).  
The workbox is using v6.0.0+ (the latest one is v6.1.4) and this breaking the firebase.

In building we see the error messages :
```
WARNING in ./node_modules/@firebase/messaging/dist/index.esm2017.js 127:21-27
export 'openDb' (imported as 'openDb') was not found in 'idb' (possible exports: deleteDB, openDB, unwrap, wrap)

WARNING in ./node_modules/@firebase/messaging/dist/index.esm2017.js 194:10-18
export 'deleteDb' (imported as 'deleteDb') was not found in 'idb' (possible exports: deleteDB, openDB, unwrap, wrap)

WARNING in ./node_modules/@firebase/messaging/dist/index.esm2017.js 196:10-18
export 'deleteDb' (imported as 'deleteDb') was not found in 'idb' (possible exports: deleteDB, openDB, unwrap, wrap)
```

Runtime error:
```
instrument.js?ea14:109 Firebase TypeError: (0 , idb__WEBPACK_IMPORTED_MODULE_2__.openDb) is not a function
    at getDbPromise (index.esm2017.js?f8e1:243)
    at dbGet (index.esm2017.js?f8e1:259)
    at getTokenInternal (index.esm2017.js?f8e1:487)
    at async FireBaseNotification (PWA.ts?bb4f:26)
    at async eval (PWA.ts?bb4f:119) Error: Stack
    at Function.Log (DebugEx.ts?46d9:114)
    at Function.TraceError (DebugEx.ts?46d9:203)
    at FireBaseNotification (PWA.ts?bb4f:42)
    at async eval (PWA.ts?bb4f:119)
```

I don't know if is possible to support both version of IDB or update to the latest (this mean dropping ie11) or be able to override somehow the internal functions that wrap the IDB and support externally the newer IDB.

I found that the idb usage is mainly in :
```
/packages/messaging/src/internals/idb-manager.ts
```

#### Steps to reproduce:
You can add in any projects that is having firebase the idb with strict version of 6.1.4. 
This will force the library to be in the latest one and see the same errors without need to add workbox.

#### Relevant Code:

```console
npm install --save idb@6.1.4
```

**Comment by hsubox76** [comment]
Thanks for the heads up, by the way, we have stopped supporting IE so we can definitely look into upgrading `idb` or possibly just using the native IndexedDB API directly.
