### ISSUE TITLE
usePublicVapidKey not defined in firebase.messaging namespace, causing build error

### ISSUE THREAD

**Issue by jenperson** [firebase/firebase-js-sdk#562]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS 10.13.3
  * Firebase SDK version: 10.4.1
  * Firebase Product: Messaging (auth, database, storage, etc)

#### Steps to reproduce:
Steps to Reproduce the bug:
1. Set up Firebase web app using Typescript for FCM
2. Try to call messaging.usePublicVapidKey("key_here1234");
3. Get error: [ts] Property 'usePublicVapidKey' does not exist on type 'Messaging'.
#### Relevant Code:

Define usePublicVapidKey in firebase.messaging namespace
https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L464

**Comment by abehaskins** [comment]
Looks like it's declared correctly in [@firebase/types-messaging](https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging-types/index.d.ts#L37) but didn't make it to the `firebase` package's `index.d.ts` so we just need to move that over.

**Comment by jshcrowthe** [comment]
Thanks for the report @jenperson and the fix @abehaskins this'll go out in the next release 😄
