### ISSUE TITLE
Firebase Storage getDownloadURL doesn't finish running

### ISSUE THREAD

**Issue by ulbqb** [firebase/firebase-js-sdk#5628]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 11.6
  * Browser version: No Browser
  * Firebase SDK version: 9.1.3
  * Firebase Product:Storage
  * Nodejs version: 14.18.0

### [REQUIRED] Describe the problem
When I try to get the Storage DownloadURL with Nodejs, the getDownloadURL function works fine, but Nodejs doesn't finish running.
firebase-js-sdk should support the Nodejs environment.
https://firebase.google.com/docs/web/environments-js-sdk

#### Steps to reproduce:
Run the following code in Nodejs (14.18.0).
In my environment, Download URL is output normally, but Nodejs execution does not finish.
#### Relevant Code:

```javascript
'use strict'
const { initializeApp } = require('firebase/app')
const { getStorage, ref, getDownloadURL } = require('firebase/storage')

initializeApp(
  {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: ''
  }
)

!(async () => {
  const storage = getStorage()
  const pathReference = ref(storage, 'sample.txt')
  const url = await getDownloadURL(pathReference)
  console.log(url)
})()
```

**Comment by jbalidiong** [comment]
Hi @ulbqb, thanks for reporting this behavior. I tried following the steps you've provided to replicate the issue, however, I was able to get the download url. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by LeMimit** [comment]
Hello ! 

I see the same problem with the functions of storage library called with mocha to test the security rules (`@firebase/rules-unit-testing`).

I tested the function `listAll` and `deleteObject`. Same problem with both.
I have to wait around 2 minutes after the test finishes to see the process finish.
