### ISSUE TITLE
Getting "Failed to minify" error while add firebase 9.1.3 in react js application

### ISSUE THREAD

**Issue by DelliBabuG** [firebase/firebase-js-sdk#5630]
Hi,

I tried to implement FCM in my react js application, i added firebase NPM and implemented the push notification feature in development. In development everything is worked fine.
When i build the code for production that time the build is getting failed and returning the below error

**Failed to compile.
Failed to minify the code from this file:
./node_modules/@firebase/util/dist/index.esm2017.js:88** 

My react js version -16.13.1, Firebase version - 9.1.3

Please help me to fix the issue

![issue](https://user-images.githubusercontent.com/58594975/137744398-41d48b95-0e50-497d-8a4a-a79bd04f4232.PNG)

**Comment by jbalidiong** [comment]
Hi @DelliBabuG, thanks for reporting this behavior. I tried replicating, but I wasn't able to reproduce the error and able to finish build. A reproducible example would be ideal, but in the mean time, could you share a few more details?
