### ISSUE TITLE
Lighthouse Report Issue with auth iframe

### ISSUE THREAD

**Issue by StefanBratanov** [firebase/firebase-js-sdk#5631]
### [REQUIRED] Describe your environment

  * Operating System version: 10
  * Browser version: Chrome 94.0.4606.81
  * Firebase SDK version: 9.1.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Hi, i am running into a Lighthouse issue stating that iframe element does not have a title. Please refer to the attached image. Can you please advise? I am using facebook, google, twitter as social sign ins which open a popup so it may be issue with that.

![image](https://user-images.githubusercontent.com/14827647/137748372-917d2640-68d8-4b23-a1d2-b37879fde0e0.png)

#### Steps to reproduce:
Run a Lighthouse Report on website using Firebase auth and facebook, google, twitter as social sign ins.

**Comment by StefanBratanov** [comment]
Hi, i upgraded to latest version 9.2.0 and wanted to let you know i get a different lighthouse issue:

![image](https://user-images.githubusercontent.com/14827647/139527895-5497b0ed-d14e-4325-a4b9-90ae730fc17e.png)

**Comment by sam-gc** [comment]
There's nothing in that iframe that will ever need to be interacted with. I'm not sure how to indicate to lighthouse that this is intentional. I will do some digging

**Comment by StefanBratanov** [comment]
> There's nothing in that iframe that will ever need to be interacted with. I'm not sure how to indicate to lighthouse that this is intentional. I will do some digging

Thank you! Are you able to replicate the lighthouse issue in your environment? It may be an issue on my side.

**Comment by sam-gc** [comment]
I am able to replicate, a fix is on the way!
