### ISSUE TITLE
How to pass authentication information when using firestore to query data?

### ISSUE THREAD

**Issue by realkimmy** [firebase/firebase-js-sdk#5637]
### [REQUIRED] Describe your environment

  * Operating System version: macos
  * Browser version: chrome
  * Firebase SDK version: 9.1.3
  * Firebase Product: database 

### [REQUIRED] Describe the problem

My application is deployed on `vercel`, how to pass the `token` information when I call the interface service to query the data in `firestore`?

#### Relevant Code:

```javascript
export default async (request, response) => {
  try {
    const querySnapshot = await getDocs(query(collection(db, "banners")));
    const result = [];
    querySnapshot.forEach((doc) =>
      result.push({ docId: doc.id, ...doc.data() })
    );
    response.status(200).json({
      code: 20000,
      data: result,
    });
  } catch (e) {
    response.status(500).json({
      code: 20001,
      message: "error",
      error: e,
    });
  }
};
```

![screenshot-20211019-171026](https://user-images.githubusercontent.com/19725091/137879681-2047eb14-1e4d-4017-a236-a13f3697eee9.png)

**Comment by realkimmy** [comment]
@hsubox76 My rules

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

**Comment by realkimmy** [comment]
@hsubox76 This API service was successfully called using postman.

![screenshot-20211021-092706](https://user-images.githubusercontent.com/19725091/138195597-ad7ed0b3-a04a-45d1-bdef-354c928c4e41.png)

**Comment by realkimmy** [comment]
You are right, my service is deployed on vercel with a serverless function, and the service is stateless. I will migrate the service from the node side to the browser environment to test it.

**Comment by realkimmy** [comment]
`https://store.gitterapp.com/login.html`
`https://store.gitterapp.com/store.html`

The code has been migrated to the browser environment. After testing, it is found that: Open the first URL, then click the login button, refresh the page, you can get the data, and open the second URL can not get the data. The error message is as follows::

```
FirebaseError: Missing or insufficient permissions.
    at chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:613
    at dn (chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:613)
    at Pr.onMessage (chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:1229)
    at chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:1229
    at chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:1229
    at chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:1573
    at chunk-vendors.533310a8.js?__WB_REVISION__=637a8058f41606b0233a:1573
```

**Comment by schmidt-sebastian** [comment]
You need to load the Firebase Auth SDK on every page that uses Firestore. It automatically registers itself with Firestore (once you call `getAuth()` or `initializeAuth()`) and will provide the authorization information from the current session, which could be from a different page under the same origin. You should not have to manually pass any token data.
