### ISSUE TITLE
signInWithPhoneNumber is not exported in React Native

### ISSUE THREAD

**Issue by byCedric** [firebase/firebase-js-sdk#5638]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11 Pro (21H2) / MacOS BigSur (11.6)
  * Browser version: Expo 42 - RN 0.63.3  / Expo 43 (beta) - RN 0.64.2
  * Firebase SDK version: 9.1.3
  * Firebase Product: auth

#### Steps to reproduce:
It looks like the `signInWithPhoneNumber` and/or other methods and classes like `PhoneAuthProvider` are not exported in React Native environments.

At Expo, we have a native library to have a working recaptcha ([as mentioned in the docs](https://docs.expo.dev/versions/latest/sdk/firebase-recaptcha/)). But without these methods, we won't be able to let people use this way of authentication.

(Disclaimer, I work for Expo)

#### Relevant Code:

```javascript
import { signInWithCredential, signInWithPhoneNumber, PhoneAuthProvider } from 'firebase/auth';

// This seems to work fine in Expo/RN
typeof signInWithCredential === 'function'

// These methods are missing
typeof signInWithPhoneNumber === 'undefined'
typeof PhoneAuthProvider  === 'undefined'
```

I [also made a Snack](https://snack.expo.dev/@bycedric/firebase-phone-exports-missing) so you can see the differences between web and android/ios. On web, all 3 types are functions but on android/ios, only the first one is a function.

**Comment by sam-gc** [comment]
@edi The phone auth symbols and functionality are now exported as of the latest release (`9.2.0`)

**Comment by luklew** [comment]
I upgraded to 9.2.0 and get error:

`verifier._reset is not a function`

I am using the expo provided example.

**Comment by sam-gc** [comment]
@luklew I think this is the same issue as https://github.com/firebase/firebase-js-sdk/issues/5688. The ReCaptcha verifier that expo exports will need to be updated to expose a `_reset()` function. In v8 this was named `reset()`. In both cases it's an internal undocumented method (which is why in v9 it was updated to follow our internal naming scheme).

Tagging @byCedric for visibility

**Comment by luklew** [comment]
> @luklew I think this is the same issue as #5688. The ReCaptcha verifier that expo exports will need to be updated to expose a `_reset()` function. In v8 this was named `reset()`. In both cases it's an internal undocumented method (which is why in v9 it was updated to follow our internal naming scheme).
> 
> Tagging @byCedric for visibility

Will that be a quick enough job or should we all downgrade for now?

**Comment by edi** [comment]
@luklew you can work around this by simply adding the following to your code:

`verifier._reset = () => {}`

**Comment by luklew** [comment]
> @luklew you can work around this by simply adding the following to your code:
> 
> `verifier._reset = () => {}`

@edi  where would I add this? Thanks.

**Comment by edi** [comment]
@luklew Inside the method you're passing phone number the verifier for sending the SMS.
So, you pick up the user's number, and you pass the recaptcha verifier towards a method which calls the following:

`provider.verifyPhoneNumber(number, verifier)`

Somewhere before this line, you should add the following: 

`verifier._reset = () => {}`

**Comment by luklew** [comment]
@edi 

Here is my example: 
```
const verificationId = await phoneProvider.verifyPhoneNumber(
                phoneNumber,
                recaptchaVerifier.current
              );
              recaptchaVerifier.current._reset = () => {}
```

Didnt work for me

**Comment by luklew** [comment]
> @luklew Inside the method you're passing phone number the verifier for sending the SMS. So, you pick up the user's number, and you pass the recaptcha verifier towards a method which calls the following:
> 
> `provider.verifyPhoneNumber(number, verifier)`
> 
> Somewhere before this line, you should add the following:
> 
> `verifier._reset = () => {}`

@edi Im getting another error now:

`undefined is not an object (evaluating auth.tenantId)`

**Comment by edi** [comment]
A different issue requires a different thread. Also, without an actual snack to check, it's hard to figure out. For me, it works. Open a different thread with all the details, and hopefully others will answer, otherwise, downgrade to 41 / 42 and be done with it.
