### ISSUE TITLE
intellisense/autocomplete no longer working with v9

### ISSUE THREAD

**Issue by MergeCommits** [firebase/firebase-js-sdk#5649]
###  Describe your environment

  * Operating System: Windows 10
  * Firebase SDK version: 9.1.3
  * IDE: Webstorm and VSCode

### Describe the problem
Not sure if this is entirely related to Firebase itself.

With v9, no intellisense is provided for the firebase module. If I write out the import paths manually it does work, but no suggestions are given when writing out function names.

I think it might be happening due to the `firebase/*` paths being re-exports of the `@firebase/*` paths making the IDE not index the modules correctly, however I haven't been able to find any workarounds for this yet.

#### Steps to reproduce:

- Create a new project with firebase.
- Start writing our `initializeApp` or some other exported function.
- Intellisense either comes up with nothing or suggests the equivalent function in the compat section.

**Comment by Feiyang1** [comment]
I'm aware that Webstorm has some issues with auto-completion with v9, but I have not heard any issues from VSCode. Can you please clarify if it's only an issue with Webstorm?

**Comment by Feiyang1** [comment]
Can you please try 9.2.0 to see if the situation improved? We made a change in this release, which I hope to solve the issue.

**Comment by MergeCommits** [comment]
Tried this again with `^9.5.0` and it now seems to be working in both IDEs.

**Comment by MergeCommits** [comment]
I tried this with both `9.5.0` and `9.6.1` and it seems to have randomly stopped working again.
