### ISSUE TITLE
GoogleAuthProvider blocked by API key restrictions because it's not setting referrer

### ISSUE THREAD

**Issue by jmeistrich** [firebase/firebase-js-sdk#5657]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 11.6
  * Browser version: Chrome 94
  * Firebase SDK version: 9.1.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Signing in with Google failed with the error: "auth/requests-from-referer-\<empty\>-are-blocked."

It looks like in v9 it is not setting the referer on the fetch requests to [identitytoolkit.googleapis.com](identitytoolkit.googleapis.com), while it did in v8. Inspecting the network requests between them, in v8 referer was set to the hostname while in v9 it's "" (empty string).

This is a breaking bug which requires downgrading back to v8 or removing the API restrictions (which seems bad). I did manage to hack in a solution it by fixing the request with a service worker (see Workaround at the end).

#### Steps to reproduce:
1. In the Google Cloud Console, set API key restrictions to have HTTP referrer restrictions on your domain name
2. Sign in with Google in Firebase
#### Relevant Code:

```javascript
// Setup
import { initializeApp } from "firebase/app";
import { signInWithPopup, GoogleAuthProvider, getAuth } from "firebase/auth";
const config = { /* ...*/ }
const firebaseApp = initializeApp(config);
const auth = getAuth(firebaseApp);
const provider = new GoogleAuthProvider();
provider.addScope('email');
provider.addScope('profile');
provider.setCustomParameters({
    prompt: 'consent'
});

// Failure here:
const userCredential = await signInWithPopup(auth, provider);
```

#### Workaround:
1. As suggested in a similar but I think unrelated issue (https://github.com/firebase/firebase-js-sdk/issues/3832#issuecomment-775353454) you can remove the API restrictions, but that is not a great solution.
2. I solved it by adding this to our service worker to fix the request:
```javascript
self.addEventListener('fetch', function (event) {
    var urlObj = new URL(event.request.url);
    if (urlObj.origin === 'https://identitytoolkit.googleapis.com') {
        event.respondWith(fetch(new Request(event.request, { referrer: location.hostname })));
    }
});
```

**Comment by jmeistrich** [comment]
I'm not sure how to provide a sample project since it requires the configuration of client IDs? But it happens with the code I included in the original post, just the basic signInWithPopup of the Google auth provider.

The thing that causes the issue is the API Key restrictions in Google Cloud. Here's a screenshot of what our restrictions look like:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1284492/139797460-1c187ec8-986e-477b-aa9e-4797f345620d.png">

Removing the restrictions fixes it, as does the hack in the Service Worker that I shared. 

I inspected the network calls and it looks like v9 has a new call to  https://identitytoolkit.googleapis.com/v1/projects which does not include the "referer" header. That causes the "auth/requests-from-referer-<empty>-are-blocked" error because of the API Key restrictions.

**Comment by sam-gc** [comment]
Thanks for the further explanation @jmeistrich, I think this is enough to go on. I'm going to try to reproduce the issue and go from there.

**Comment by sam-gc** [comment]
@jmeistrich I can't seem to reproduce this. When setting up API key restrictions, I can get both v8 and v9 to fail when the domain isn't listed, and I can get both to work when the domain is listed (it works in v9 even though the referer header isn't set). As an aside, I'm not sure it is related to the referer header: your snippet is setting a header called "referrer" which, while technically the correct spelling, is not the correct header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer).

Just to double check: are you seeing this behavior on `localhost`? In that case you'll need to list `localhost` in the API key restriction list.

If the issue persists, please reach out to [Firebase Support](https://firebase.google.com/support) directly; there may be something going on with the configuration of your project specifically.

**Comment by jmeistrich** [comment]
Thanks for looking into it @sam-gc! I am seeing this behavior in production. 

If you can't reproduce this and it doesn't affect anyone else it must be something specific to our project. We are happy enough with the service worker workaround for now, but I will reach out to Firebase Support and see if they have any guidance.

**Comment by sam-gc** [comment]
Sounds good, please reach out to the Support team. It's possible the issue has something to do with your project's configuration, in which case Support is best equipped to investigate. I'm going to close this issue for now but if you find anything else please feel free to comment/reopen.
