### ISSUE TITLE
"Could not reach Cloud Firestore backend" after upgrading to v9

### ISSUE THREAD

**Issue by Kojon74** [firebase/firebase-js-sdk#5667]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 9.1.3
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

I just started updating my code from Firebase v8 to v9 and then started running into this issue (which is weird because it was just working before I upgraded to v9 so I'm pretty sure it's not a network issue)

It seems like some firebase features do work, for eg the onAuthStateChange from firebase.auth, but whenever I try and run a Firestore command it seems to get stuck.

```
[2021-10-26T06:31:58.335Z]  @firebase/firestore:, Firestore (9.1.3): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
at node_modules/@firebase/util/dist/index.esm2017.js:1737:21 in stringLength
at node_modules/@firebase/util/dist/index.esm2017.js:1881:0 in <global>
at http://192.168.0.63:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:127402:19 in F
at node_modules/@firebase/firestore/dist/index.rn.js:10137:8 in <global>
at http://192.168.0.63:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:139150:48 in <unknown>
at node_modules/@firebase/firestore/dist/index.rn.js:10653:10 in <global>
at node_modules/@firebase/firestore/dist/index.rn.js:14006:24 in <global>
at node_modules/@firebase/firestore/dist/index.rn.js:14048:19 in cancel
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```

#### Relevant Code:

```javascript
// Initialization
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

const firebaseApp = initializeApp({
// Initialization keys go here
});

const auth = getAuth();
const db = getFirestore();
const storage = getStorage();

export { auth, db, storage };

/////////////////////////////////////////////////////// IN A SEPARATE FILE ///////////////////////////////////////////////////////
import { onAuthStateChanged } from "firebase/auth";
import { auth, db } from "./firebase";
import {
  addDoc,
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  updateDoc,
  where,
} from "firebase/firestore";

const SomeComponent = () => {
// other stuff
useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      (async () => {
        if (user) {
          let _userDoc;
          try {
            _userDoc = await getDocs(collection(db, "users"));
            // _userDoc = await getDoc(doc(db, "users", user.uid));
          } catch (e) {
            console.error(e);
          }
          console.log("bello");
          if (_userDoc.exists()) {
            setUserDoc(_userDoc);
            const userProdSnap = await getDocs(
              collection(_userDoc, "userProducts")
            );
            let curUserProducts = [];
            userProdSnap.forEach((doc) => curUserProds.push(doc.data()));
            setUserProducts(curUserProducts);
          } else {
            console.error("ERROR: user document doesn't exist");
          }
        }
      })();
    });
    return unsubscribe;
  }, []);
}
```

**Comment by Shashank-Prasanna** [comment]
That's so strange, I tried that and it didn't work
Code: 
` await console.log('Initializing Firebase App...')
    const firebaseApp = await initializeApp({
      apiKey: "xxxxxxxxxxx",
      authDomain: "xxxxxx",
      projectId: "xxxxxx",
    })
    console.log('App Initialized, Initializing Firestore...')
    db = await initializeFirestore(firebaseApp, {useFetchStreams: false, experimentalForceLongPolling:true})`

this still throws the error. Why?

**Comment by angusryer** [comment]
@Shashank-Prasanna & @edi I hadn't replied back, but `experimentalForceLongPolling: true` did not work for me. I also tried `experimentalAutoDetectLongPolling: true` just in case. For context, I'm running solely on an iOS emulator at the moment.

I ended up extending the `FirestoreSettings` interface like so:

``` typescript
// `FirestoreSettings` itself extends `PrivateSettings` which contains `useFetchStreams`.
const firestoreSettings: FirestoreSettings & { useFetchStreams: boolean } = {
	useFetchStreams: false
};

export const fsdb = initializeFirestore(app, firestoreSettings);
```

And with that I'm no longer getting the original error.

**Comment by Shashank-Prasanna** [comment]
> @Shashank-Prasanna & @edi I hadn't replied back, but `experimentalForceLongPolling: true` did not work for me. I also tried `experimentalAutoDetectLongPolling: true` just in case. For context, I'm running solely on an iOS emulator at the moment.
> 
> I ended up extending the `FirestoreSettings` interface like so:
> 
> ```ts
> // `FirestoreSettings` itself extends `PrivateSettings` which contains `useFetchStreams`.
> const firestoreSettings: FirestoreSettings & { useFetchStreams: boolean } = {
> 	useFetchStreams: false
> };
> 
> export const fsdb = initializeFirestore(app, firestoreSettings);
> ```
> 
> And with that I'm no longer getting the original error.

I tried this but the original error comes up and I also get another error: 
`Type annotations can only be used in TypeScript files`

Here's my full code: 
```js
import { initializeApp } from 'firebase/app'
import { initializeFirestore } from 'firebase/firestore'

console.log('config.js')
const firebaseApp = initializeApp({
  apiKey: "xxxxxxxx",
  authDomain: "xxxxxxxx",
  projectId: "xxxxxxxx",
})


console.log('DB initialized')

const firestoreSettings: FirestoreSettings & { useFetchStreams: boolean} ={
  useFetchStreams: false,
}

const db = initializeFirestore(firebaseApp, firestoreSettings)

export default db
```

**Comment by angusryer** [comment]
Right @Shashank-Prasanna you'll have to remove the type defs if you're not using Typescript:

``` javascript
const firestoreSettings = {
  useFetchStreams: false
}
```

When testing this using the web, I also do not get the error. I haven't tested on an Android device.

**Comment by Shashank-Prasanna** [comment]
@angusryer The odd thing is that this works only in a web browser... when I use the React Native web app on my iOS phone (with expo and expo go), the error still arises. Perhaps it is related to this warning I always receive? 

```
[2021-10-31T14:15:43.953Z]  @firebase/firestore: Firestore (9.2.0): Connection WebChannel transport errored: 
me {type: 'c', target: Y, g: Y, defaultPrevented: false, status: 1}
defaultPrevented: false
g: Y {s: false, o: undefined, i: kb, R: Y, J: null, …}
status: 1
target: Y {s: false, o: undefined, i: kb, R: Y, J: null, …}
type: "c"
[[Prototype]]: qc
```
I never receive this error in a web browser, yet I do on iOS (haven't tested on Android)

**Comment by schmidt-sebastian** [comment]
`useFetchStreams` is now disabled for React Native if you install version 9.2.0. If this does not solve your issue, we can add this flag to the official type definitions, which should make it easier to use.
