### ISSUE TITLE
Incorrect assumption in `successor` and `predecessor` functions 

### ISSUE THREAD

**Issue by mortenbekditlevsen** [firebase/firebase-js-sdk#5670]
https://github.com/firebase/firebase-js-sdk/blob/1048c4f2dc1338f0df2237e0d2f5a7afd82bba84/packages/database/src/core/util/NextPushId.ts#L100

The functions assume that the key that is used as input is created in the style of `nextPushId`, while in fact the key may be any valid RTDB key.

See discussion and solution (work in progress) for the iOS SDK here:

https://github.com/firebase/firebase-ios-sdk/issues/8790

**Comment by maneesht** [comment]
Closing this as it was fixed in #6706
