### ISSUE TITLE
Error on pageload when optimization is on and FirebaseAuth is used

### ISSUE THREAD

**Issue by AkhetAten** [firebase/firebase-js-sdk#5674]
### Describe your environment

  * Operating System version: Windows 10/macOS
  * Browser version: Firefox (93) / Chrome (95)
  * Firebase SDK version: 9.1.3
  * Firebase Product: auth

#### Steps to reproduce:
[AngularFireTryOut.zip](https://github.com/firebase/firebase-js-sdk/files/7431883/AngularFireTryOut.zip)

When building the attached sample with `optimization=true` the resulting application fails to run with the error shown below.
![grafik](https://user-images.githubusercontent.com/93245643/139204456-8bb2e19e-2aab-4391-9b73-d9c5f21780ad.png)

When building with `optimization=false` the application is running fine.
However i would expect not such an impact because of the optimization.

**Comment by AkhetAten** [comment]
I can only say for sure that this didn't happen with firebase 8.9.1, as this was the version I migrated from.

**Comment by AkhetAten** [comment]
I wanted to ask if there is some new information about this issue. Although we can workaround it with providing the application without optimized code, it has been observed that the performance is not as good as with the optimized code (especially on mobile devices). As we are using firebase in public platform, we do not want risk losing customers because of decreasing performance.

**Comment by Keithcat767** [comment]
Also hoping for an update on this issue. Releasing without optimization isn't an option for us. We also upgraded from 8.9.1 to 9.1.3 and are experiencing the exact errors. Thanks!

**Comment by hsubox76** [comment]
We're trying to get some information on how Angular optimization works so we can try to understand what's happening. Our bundles seem to be fine before going through the process, so either there is something wrong with the optimization process, or there could be something wrong with our code that breaks only when put through the optimization process, but we need to talk to some teams to get more insight into what happens in that process to figure out which it is and what's happening.

**Comment by hsubox76** [comment]
Does this fix work for anyone else? I was under the impression other users were using the default configuration.

**Comment by AkhetAten** [comment]
So far this issue seems to be solved in the example project I provided here. I will have a look at our core application if it will also solve the issue there and will report back here.

**Comment by AkhetAten** [comment]
After checking with our full application it seems that this flag really changes the issue. After setting it to true, optimization is working. Thanks for the hint

**Comment by hsubox76** [comment]
I'll close this issue since it seems to be something in Angular and there's a workaround, but it doesn't seem right that the extractLicenses option should affect whether the code works or not, so it may be a good idea to file an issue with the Angular CLI repo (https://github.com/angular/angular-cli) providing your example project and noting it works when extractLicenses=true but not false, and see if they can shed any light on it. Let us know if the Angular team finds there's something wrong with the Firebase code and I will reopen the issue.

**Comment by Keithcat767** [comment]
Sorry for the delay, confirming setting extractLicenses to false fixed our issue as well.
