### ISSUE TITLE
Firestore snapshot returns incomplete data from previous get requests

### ISSUE THREAD

**Issue by ghinda** [firebase/firebase-js-sdk#5682]
### Describe your environment

  * Browser version: Chromium 94
  * Firebase SDK version: `9.2.0`
  * Firebase Product: Firestore

### Describe the problem

Snapshot returns incomplete query data, if other get requests for the same data are running before the snapshot is attached.

Even with no persistence enabled, the snapshot `metadata.fromCache` will return true for the specific query.

#### Steps to reproduce:

* Make a get request to a document by id.
* Attach a snapshot for a list of documents **that includes the previously requested document**.
* The first snapshot callback will only contain the already-requested document **and not the full query result**.
* The snapshot result will have `metadata.fromCache` even if persistence is not enabled.

The snapshot callback will fire multiple times, eventually containing the full query result.
The Firestore SDK is probably trying to be efficient here and return the already retrieved results first.
But, this breaks the assumption that the first snapshot should [contain added events for all existing documents that match the query](https://firebase.google.com/docs/firestore/query-data/listen#view_changes_between_snapshots) as described in the docs.

#### Relevant Code:

```javascript
// get document by id
getDoc(doc(collection(db, 'users'), '1'))

// attach snapshot to query that should return more users, but also contains user.id=1
onSnapshot(allUsersQuery, (snapshot) => {
  // snapshot.metadata.fromCache will be true,
  // even if offline persistence is not enabled
  console.log(snapshot.metadata.fromCache === true)

  // docs will only contain the already-requested document on the first callback,
  // and not the full query result
  console.log(snapshot.docs.length === 1)
})
```

**Comment by jbalidiong** [comment]
Hi @ghinda, thanks for reaching out. While replicating, both console logs return false on my app and get all the data on the snapshot. A reproducible example would be ideal, but in the meantime, could you share a few more details?

Also, I would suggest creating a blank project, import Firebase, implement Firestore and check if the behavior is replicable.

**Comment by schmidt-sebastian** [comment]
Hi @ghinda (and @jbalidiong). I think what is being described here is not a bug, but rather how our SDK functions.  The first snapshot will be raised once any document content is available - this might be before the server responds if there are any document in the cache that match the query. This cache includes all currently active queries even if the cache is only kept in memory (and you have not opted into disk persistence). As the backend starts returning results, documents are then added to the next snapshot. All documents will cause an ADDED change once, but it is correct that this can happen over multiple snapshots. 

I agree that the documentation here might be misleading, but it really boils down to what your (or our?) definition of "existing" includes. In this case, our definition of existing includes results from cache. We can improve the wording if that would be helpful.
