### ISSUE TITLE
verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined)

### ISSUE THREAD

**Issue by wahas-mughal** [firebase/firebase-js-sdk#5688]
* Operating System version: Windows 20H2 
  * Browser version: CCleaner Browser 94.0.12470.84 (Official Build) (64-bit)
  * Firebase SDK version: 9.2.0
  * Firebase Product: AUTH
  * Expo SDK: 43
  * Node: 12.13.1

I'm implementing firebase phone auth but getting the below error:

 **verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined)** when getting token

      const auth = getAuth();
      const phoneProvider = new PhoneAuthProvider(auth);

      const id = await phoneProvider.verifyPhoneNumber(
        this.state.phoneNumber, //valid
        this.recaptchaVerifier.current //valid
      ); // throughs the message here
      
     //not reaching here
     console.log(id)

Although right after it, I'm receiving the OTP. But not getting token, required to complete the OTP verification.

**STEPS TO REPRODUCE:**

Installation:
`expo install firebase`

Code:
```
    const auth = getAuth();
    const phoneProvider = new PhoneAuthProvider(auth);    
    const id = await phoneProvider.verifyPhoneNumber(
     this.state.phoneNumber,
     this.recaptchaVerifier.current
 ); // throughs the message here
```

**Comment by sam-gc** [comment]
I think this issue should probably be raised with Expo. In v9, there is an expectation that the RecaptchaVerifier has an internal method called `_reset()`. As I understand it, Expo exports a RecaptchaVerifier that works with our libraries (the `RecaptchaVerifier` class that Firebase exports does not work in React Native). Please reach out to the Expo maintainers.

**Comment by Ahmed-Ibrahim-Anter** [comment]
can anyone improve me if any way to solve this problem I tried everything but in the end give me this error? verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined)
