### ISSUE TITLE
linkWithCredential() with Google credentials unlinks the existing linked facebook account

### ISSUE THREAD

**Issue by anthofo** [firebase/firebase-js-sdk#569]
# Describe your environment

  * Operating System version: windows 10
  * Firebase SDK version: 4.9.0
  * Firebase Product: auth

# Describe the problem

## Steps to reproduce:
I have an existing user with an verified email (gmail) / password credentials.

Differents possible scenarios:

### Scenario A google -> facebook or facebook-> google linkWithPopup() [WORKING]

- User first sign-in with email / password
- Then, user links his account with facebook by using the linkWithPopup() method with Facebook provider
- Finally, user links his account with google by using the linkWithPopup() method with Google provider

Now the user has his account linked with email / google / facebook : 

![capture01](https://user-images.githubusercontent.com/3809685/37541179-dc287a28-2959-11e8-8cab-33659df35b1c.JPG)

Note that linking google first then facebook produces the same reult

### Scenario B google -> facebook linkWithCredential() [WORKING]

- User is not signed-in but has an existing verified email / password
- User sign-in with google with the signInWithPopup() method  and is automatically logged in
- User logout, then sign-in with facebook with the signInWithPopup()
- I get an `auth/account-exists-with-different-credential` error
- I save the credential then ask the user to sign-in with his email / password first
- Once logged-in, I use the previously saved facebook credential:

```javascript
auth.signInWithEmailAndPassword(user.email, user.password)
    .then(user => user.linkWithCredential(pendingCred))
```

Now the user has his account linked with email / google / facebook : 

![capture01](https://user-images.githubusercontent.com/3809685/37541179-dc287a28-2959-11e8-8cab-33659df35b1c.JPG)

### Scenario C facebook-> google linkWithCredential() [WEIRD BEHAVIOR]

The weird thing happens when we reverse google and facebook in scenario B:
- User is not signed-in but has an existing verified email / password
- User sign-in with facebook with the signInWithPopup() method
- I get an `auth/account-exists-with-different-credential` error
- I save the credential then ask the user to sign-in with his email / password first
- Once logged-in, I use the previously saved facebook credential. Facebook is now linked:
![capture02](https://user-images.githubusercontent.com/3809685/37541747-ffadcc8a-295b-11e8-9cc3-bde1975fc4e8.JPG)
- User logout, then sign-in with google with the signInWithPopup()
- No error is thrown, the user is automatically logged in and the google account has been linked.
- **The issue is that the facebook account has now been unlinked and I don't really understand why**:
![capture03](https://user-images.githubusercontent.com/3809685/37541914-94331068-295c-11e8-99c6-24b34e756240.JPG)

I can't figure out if it's a bug of if I'm misusing the API. The weird thing is that it works in the google -> facebook way :s

**Comment by wti806** [comment]
Hi, @anthofo This is the expected behavior. Since the email address is a gmail email account, it's considered to be owned by Google. So when you sign in with google, you will notice that emailVerified is true. But with facebook, we don't know if you own the gmail account. In that case, the unverified email account in unlinked.

**Comment by anthofo** [comment]
Hi thanks for the answer. The email address was already verified (emailVerified: true) before the account was linked to google or facebook. After checking it, the user is still `emailVerified: true` after beeing linked to facebook.
Do I need to do something special to flag the facebook account as `verified` and don't lose it after google-linking ?

**Comment by wti806** [comment]
Yes, in your case, email provider is not unlinked since the email is verified already but facebook provider is unlinked.  If you want to keep the facebook provider, instead of sign in, you have to use linkWithPopup/redirect.

**Comment by bojeil-google** [comment]
Seems similar to https://github.com/firebase/firebase-js-sdk/issues/340

**Comment by pritamb1** [comment]
hello @anthofo even I am facing this issue, what firebase tells is that getcredential and then link with credential but upto siginwithcredential but in that case the getcurrentuser will always return null. I dont understand how do we achieve a smooth login, where the user can login smoothly with any auth provider and the user need not do anything to link the accounts but it links by itself. Do you already have a solution?

**Comment by pritamb1** [comment]
@anthofo Thanks! If the user tries to login via Facebook, I will get an error that the user account already exists but with different auth provider, is there any way that when I get this error I can login the user via google without prompting anything from User and then I silently Link the Facebook account.

**Comment by yuchenshi** [comment]
To summarize here, if the email has been verified, the Facebook account should not be unlinked -- there was a bug on the backend that was fixed earlier: https://github.com/firebase/firebase-js-sdk/issues/1249#issuecomment-505623644

If the email address is not verified, then unlinking is the expected behavior here (see https://github.com/firebase/firebase-js-sdk/issues/340#issuecomment-624970505 ). It's also worth noting that logging in with Facebook alone does not automatically set the email to verified -- see https://github.com/firebase/firebase-js-sdk/issues/340#issuecomment-624970505 for why.
