### ISSUE TITLE
maxretry error with database transaction and the emulator

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-js-sdk#5696]
### Describe your environment

  * Operating System version: OS X
  * Browser version: Chrome (latest)
  * Firebase SDK version: 8.7.1
  * Firebase Product: database and emulator

###Describe the problem

#### Steps to reproduce:

From time to time, transactions in our unit tests are failing with the error `maxretry`

basically a code like:

```js
let execution = 0;

ref.transaction((value) => {
    console.log('transaction', execution);
    execution += 1;
    if (!value) {
        // RTDB always run the transaction with null once
        // https://groups.google.com/g/firebase-talk/c/Lyb0KlPdQEo/m/R2GhwNOiAgAJ
        console.log('return previous value', value);
        return value;
    }

    console.log('return new value');
    return somethingWithTheValue(value)
});
```

when run with the emulator results often (not always) with the following log:

```
...
return previous value null
transaction 23
return previous value null
transaction 24
return previous value null
```

and then it fails with:

```
Error: maxretry
          at node_modules/@firebase/database/dist/index.node.cjs.js:12076:52
          ...
```

It doesn't always happen; but it seems caused by concurrent execution of our tests (we use jest); which seems to put firebase into an infinite loop.

**Comment by jbalidiong** [comment]
Hi @SamyPesse, thanks for reaching out. Would you mind trying to update the SDK version that you're using and see if the issue persists? Just FYI, going forward, any fixes will be in version 9+. For minimal change, you can use the import paths require('firebase/compat/app') and require('firebase/compat/database'). You can also check the documentation about upgrading from version 8 to the modular Web SDK for further information.

**Comment by SamyPesse** [comment]
Hi @jbalidiong, it's also happening with firebase 9.3.0.

It doesn't always happen; but the more we increase the odds of concurrency in our tests (nothing crazy, like max 2 / 3 operations at the same time), the more it happens.

**Comment by jbalidiong** [comment]
Thanks for trying it with the latest SDK version. A reproducible example would be ideal, but in the meantime, could you share a few more details?

**Comment by jbalidiong** [comment]
To clarify, you are encountering the behavior when the same ref is use for the concurrent transaction?
