### ISSUE TITLE
Can no longer get `credential` (of type `AuthCredential`) from a `UserCredential` interface

### ISSUE THREAD

**Issue by varbrad** [firebase/firebase-js-sdk#5712]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 11.4
  * Browser version: Firefox 94.0.1
  * Firebase SDK version: 9.1.2
  * Firebase Product: auth

#### Steps to reproduce:
Calling `signInWithEmailAndPassword` returns a `UserCredential` that no longer allows us to pluck the `AuthCredential` from.

#### Relevant Code:
```typescript
const userCredential = await firebaseApp
          ?.auth()
          .signInWithEmailAndPassword(user.email, data.oldPassword)
const authCredential = userCredential?.credential
```

The above code used to work just fine in Firebase SDK 8. We are attempting to upgrade to Firebase SDK 9, but see no way of getting the `credential` off the return value of the function in order to trigger the `reauthenticateWithCredential` function afterwards (Specifically we are implementing a change-password flow here).

I'm unsure if this is a mistake/omission on the interfacebecause the documentation still mentions that the `UserCredential` interface should expose an `AuthCredential`, of it the way to do this flow has changed.

<img width="969" alt="Screenshot 2021-11-09 at 09 38 10" src="https://user-images.githubusercontent.com/11805775/140899839-5a2e93fa-6bc7-4d16-bb29-74d89463c736.png">

**Comment by varbrad** [comment]
For anyone else encountering this. I've been able to work around it via;

```typescript
const authCred = EmailAuthProvider.credential(email, oldPassword)
const authUser = (await signInWithCredential(this.auth(), authCred)).user
await reauthenticateWithCredential(authUser, authCred)
```

**Comment by sam-gc** [comment]
With your upgrade, are you using the modular version or the compatibility layer? The modular version does not expose a credential on the [`UserCredential` object](https://firebase.google.com/docs/reference/js/auth.usercredential); you need to call a provider's `credentialFromResult` static method (for example, [`GoogleAuthProvider.credentialFromResult()`](https://firebase.google.com/docs/reference/js/auth.googleauthprovider#googleauthprovidercredentialfromresult)). For email/password, in v8 that `credential` field should always be `null` in any case.

The v9 compatibility layer (i.e. `firebase/compat/auth` should return a `UserCredential` with a `credential` field). If it's not there, then there's a bug

**Comment by varbrad** [comment]
@sam-gc I am attempting to move over to the modular version. I have indeed just decided to use the approach taken above (and is the approach you mentioned), which seems to be working for our application.

If, as you say, the `UserCredential` object no longer exposes a `credential: AuthCredential`, then the documentation should be changed to reflect this. The link you provided still mentions that it returns an `AuthCredential` (as it did in v8).

Also - regarding the `credential` being `null`, our password change functionality definitely works and we've not had any reports from our ~20k users of it ever not working, so weird one there!

Thanks! :)

**Comment by sam-gc** [comment]
Thanks for the note and point out the docs. The linked PR should update the docs. [`EmailAuthProvider`](https://firebase.google.com/docs/reference/js/auth.emailauthprovider) doesn't provide a `credentialFromResult` method in v9, so I'd still suggest following this method: https://github.com/firebase/firebase-js-sdk/issues/5712#issuecomment-964108802.

I'm going to close this one out for now, but please reopen or comment if you're still running into issues.
