### ISSUE TITLE
Error happens when running firebase auth SDK via cypress

### ISSUE THREAD

**Issue by konti-kun** [firebase/firebase-js-sdk#5714]
### [REQUIRED] Describe your environment 
 * Operating System version: macOS 12.0.1
  * Browser version: chrome 95
  * Firebase SDK version: 9.1.0 - 9.4
  * Firebase Product: auth

### [REQUIRED] Describe the problem
After I changed the firebase SDK version to 9, all tests in cypress started to give errors.
The firestore is working correctly and there is no problem.

I checked the request and response with the dev tool, and it looks like the request header is broken and that's why it's returning 403 Forbidden.

<img width="966" alt="screenshot" src="https://user-images.githubusercontent.com/34307591/140944330-f127e5ea-b6ef-4d53-9ac5-337ed40817ad.png">

#### Steps to reproduce:
v6.9.1 and v8.7.8 cypress reproduced it.

**Comment by sam-gc** [comment]
@konti-kun does the app work normally (i.e. when you're clicking around, not using Cypress)? It looks like the headers are attached with JS Object methods, which is very odd.

**Comment by konti-kun** [comment]
Yes, it works normally.
Perhaps the problem is caused by the compatibility between the proxy in cypress and the auth sdk.

I reverted to v8 and this problem stopped happening.

**Comment by sam-gc** [comment]
I'm not familiar with Cypress, what do you mean by "the proxy in cypress and the auth SDK"? Are you using the emulator (I assume you are based on the request path).

**Comment by konti-kun** [comment]
In cypress, it seems that all http communication is run through a proxy in cypress in order to assert and mock http communication.

https://glebbahmutov.com/blog/cy-route-vs-route2/

I guessed that the v9 SDK does not work due to this mechanism.

> Are you using the emulator (I assume you are based on the request path).
I run test on both real firebase project and emulator, and it happened in both environments.

**Comment by konti-kun** [comment]
I coded and tested a simple app and a simple test with cypress.
Then, the strange http header did not occur, so I try to find out more about the condition of occurrence.

**Comment by konti-kun** [comment]
When I removed the experimentalFetchPolyfill config in cypress, it worked fine.
https://docs.cypress.io/guides/references/experiments#Configuration

It is a setting that rewrites window.fetch to unfetch(https://github.com/developit/unfetch), which is not necessary in the newer version of cypress.
