### ISSUE TITLE
Firebase Auth bundle size

### ISSUE THREAD

**Issue by dmitry-zaets** [firebase/firebase-js-sdk#5719]
* Operating System version: any
  * Browser version: any
  * Firebase SDK version: 9
  * Firebase Product: auth
  * Build System: clean webpack setup copied from official Firebase documentation - [Using Firebase with webpack](https://firebase.google.com/docs/web/module-bundling#using_firebase_with_webpack)

Here is a [repo with all the source code](https://github.com/dmitry-zaets/webpack-firebase-auth-9 ) 

#### Steps to reproduce:
Started with migration from v8 to v9, but also reproduced it in a default create-react-app and the simplest webpack setup, proposed in the article. 
Looks like the module `node_modules/firebase/auth/dist/auth/index` is just re-exporting the whole firebase auth by `export * from '@firebase/auth';` and the tree shaking doesn't really work.
Not sure though if it's an issue with the `auth` package, build setup, or anything else. Would appreciate any help.

#### Relevant Code:
`./src/index.js`
```js
import { initializeApp } from 'firebase/app'
import { getAuth, onAuthStateChanged } from 'firebase/auth'

const firebaseApp = initializeApp({})

const auth = getAuth(firebaseApp)
onAuthStateChanged(auth, user => {})
```

`./webpack.config.js`
```js
const path = require('path')
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer')
  .BundleAnalyzerPlugin

module.exports = {
  // The entry point file described above
  entry: './src/index.js',
  // The location of the build folder described above
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  // Optional and for development only. This provides the ability to
  // map the built code back to the original source format when debugging.
  devtool: 'eval-source-map',
  plugins: [new BundleAnalyzerPlugin()]
}
```

`./package.json`
```json
{
  "name": "test-package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode=development"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "firebase": "^9.4.0"
  },
  "devDependencies": {
    "webpack": "^5.63.0",
    "webpack-bundle-analyzer": "^4.5.0",
    "webpack-cli": "^4.9.1"
  }
}
```

#### Screenshot form the bundle analyzer:
![image](https://user-images.githubusercontent.com/2580555/141280694-a612ea5b-7b22-4447-bc3c-5d0affc130aa.png)

Related to: https://github.com/firebase/firebase-js-sdk/issues/4916

**Comment by jbalidiong** [comment]
Hi @dmitry-zaets, thanks for reaching out. According to the attached issue:

> firebase is the umbrella package that you install to get all firebase product SDKs. It has no implementation, and delegates everything to the scoped packages. For example, firebase/app delegates to @firebase/app, firebase/firestore delegates to @firebase/firestore. That said, it's just how we package our SDKs, and you shouldn't need to know or care.

https://github.com/firebase/firebase-js-sdk/issues/4916#issuecomment-846156045

>Keep in mind the total package size in v9 is not very meaningful because you won't include the entire package in your app. The size of firebase you will include in your app depends on what you import.

I tested it with v8 and v9 and overall, v9 has a much smaller compiled sizes than v8. With v9, the package `firebase` should have negligible size and the result will vary on how much you import.

**Comment by dmitry-zaets** [comment]
As you can see in the example, I've imported only 3 items:

```js
import { initializeApp } from 'firebase/app'
import { getAuth, onAuthStateChanged } from 'firebase/auth'
```

But even if I import them directly from the @firebase/** packages, the size remains the same.

**Comment by hsubox76** [comment]
Looks like this has been addressed in the other issue you linked to: https://github.com/firebase/firebase-js-sdk/issues/4916#issuecomment-970534166
