### ISSUE TITLE
User in firebase analytics is most of the time counted twice

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#5721]
* Firebase SDK version: 9.1.3 but has been happening since firebase analytics came out
  * Firebase Product: analytics

### [REQUIRED] Describe the problem

Our angular application uses quite some firebase products.
One of these is firebase analytics/angularFireAnalytics
We've been using analytics since it came out and always have had this issue, but only now found the time to actually try to see what the reason can be.
Most of the users in firebase analytics are counted 2 times, not all of them, but +-60% of them.

We know this basically because:
- logging in ourselves will show the location we are logging in to as  1 "dot" on the map with 2 users.
- this while normal google analytics (where we also log to until now to have a more correct user count) only shows 1 user there.

Our setup of analytics is really basic, not doing anything special.

Also, if I login in another browser, at that time the count for my user becomes 3.
Logging in to a third browser, at that time the count for my user becomes 4.
So it seems that somehow the first session is counted twice. Maybe once for the "connection" and once for the login?

Any idea why this is happening?

**Comment by jbalidiong** [comment]
HI @LanderBeeuwsaert, thanks for reaching out. I followed the steps to replicate the behavior but I wasn't able to experience  the user being counted twice (also tried multiple browsers but it doesn't affect the analytics data). I would recommend [debugging](https://firebase.google.com/docs/analytics/debugview#web) the logEvent() and see if it is causing the user be counted twice. If you see in the logs that the SDK is firing the logEvent() twice then it is definitely a bug. If the logs show that you trigger the logEvent once and received the user count twice, it may be an issue on the backend. In that case, you may want to file a ticket via [Firebase support channel](https://firebase.google.com/support). I verified that it's working fine for the latest SDK.
