### ISSUE TITLE
Firestore onSnapshot() or get() stucked on app restart - same as 5058

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-js-sdk#5724]
Same as https://github.com/firebase/firebase-js-sdk/issues/5058

I am creating a new issue as 5058 is locked.

My setup has slightly evolved but the issue is exactly the same:
Operating System version: _____ iOS 15.0
Browser version: _____ Safari 15.0
Firebase SDK version: _____ 9.2.0
Firebase Product: _____ Firestore, using the compat version

After restarting my app, a call to get() or onSnapshot() will never return a document that I know exist. Killing the app and starting from scratch will work.

The problem **only occurs on iOS**, all the other platforms I have tried work as expected:
- Windows 10 - Firefox, Chrome, Edge
- Ubuntu - Chrome, Opera
- Mac - Safari
- Android - Chrome

And here are the logs I have now:

> LOG - [2021-11-11T18:17:48.490Z]  @firebase/firestore:Firestore (9.2.0): SimpleDb|Opening database:firestore/[DEFAULT]/fireauthentest/main
> LOG - [2021-11-11T18:17:48.489Z]  @firebase/firestore:Firestore (9.2.0): IndexedDbPersistence|Starting transaction:updateClientMetadataAndTryBecomePrimary
> LOG - [2021-11-11T18:17:48.480Z]  @firebase/firestore:Firestore (9.2.0): FirestoreClient|Initializing OfflineComponentProvider
> LOG - [2021-11-11T18:17:48.441Z]  @firebase/firestore:Firestore (9.2.0): FirestoreClient|Received user=ZZNtKb3byiQsrHZ4I4A3IyfDZWL2

Fyi, I can now reproduce the issue on my app (but not on a mini repo unfortunately) so I can try to pull more info or logs for you if you tell me how to get them

**Comment by ehsannas** [comment]
Hi @olivierkrener , Thanks for reporting.

Are you seeing this issue only when using Safari 15 on iOS? There was an issue specific to Safari 15 that just got fixed (https://github.com/firebase/firebase-js-sdk/issues/5716).

**Comment by olivierkrener** [comment]
Yes I am using Sarai 15 on iOS but note that #5058 was on Safari 14.4.2 and was showing exactly the same issue. In what release will #5716 be merged so I can test it?

**Comment by ehsannas** [comment]
This particular issue also existed in Safari 14 (https://github.com/firebase/firebase-js-sdk/issues/4076). It is a bug in Safari; we placed a workaround for Safari 14 in late July, and we added the same workaround for Safari 15 a couple of days ago. #5716 should be picked up by the next release.

**Comment by olivierkrener** [comment]
This sounds great. I will be monitoring the release notes.

I see in the comment that calling `firestore.terminate()` before reloading the app seems to solve the issue. Is it worth me trying?

**Comment by ehsannas** [comment]
I think it's worth trying to see if this workaround works for you while you wait for the next release.

**Comment by olivierkrener** [comment]
I can confirm that this workaround works on my two test iOS devices (running on Safari 12 and 15)
