### ISSUE TITLE
FirebaseError: appCheck/fetch-status-error on Chrome

### ISSUE THREAD

**Issue by vincekruger** [firebase/firebase-js-sdk#5726]
### Describe your environment

  * Operating System version: macOS 12.0.1
  * Browser version: Chrome 95.0.4638.69 (Official Build) (arm64)
  * Firebase SDK version: 9.4.0
  * Firebase Product: app-check

### Describe the problem

Firebase app-check with Recaptcha3 is not working in **Chrome** - App attestation fails always because there is a javascript error with Recaptcha.  Is this a known bug?

I've tested in the below browsers and the example code is working just fine.
- Safari
- Edge
- Firefox
- Safari iPhone

#### Error

```log
recaptcha__en.js:147 Uncaught TypeError: Cannot read properties of undefined (reading '__wrapper_2__')
    at Array.<anonymous> (recaptcha__en.js:147)
    at S.<computed> (recaptcha__en.js:339)
    at XMLHttpRequest.onreadystatechange (<anonymous>:44:15)

[2021-11-11T20:32:49.682Z]  https://www.gstatic.com/firebasejs/9.4.0/firebase-app.js-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).
    at exchangeToken (client.ts:72)
    at async getToken$2 (internal-api.ts:121)
    at async Promise.all (index 1)
    at async PersistentConnection.establishConnection_ (PersistentConnection.ts:882)
```

#### Steps to reproduce:

hit the 'call database' button and check out the console

#### Relevant Code:

```html
<html>

<head>
  <script type="module">
    // Import the functions you need from the SDKs you need
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-app.js";
    import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-analytics.js";
    import { initializeAppCheck, ReCaptchaV3Provider } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-app-check.js";
    import { getDatabase, ref } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-database.js";
    // TODO: Add SDKs for Firebase products that you want to use
    // https://firebase.google.com/docs/web/setup#available-libraries

    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
      /* config */
    };

    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    const analytics = getAnalytics(app);
    const database = getDatabase(app);
    const appCheck = initializeAppCheck(app, {
      provider: new ReCaptchaV3Provider('{site-key}'),

      // Optional argument. If true, the SDK automatically refreshes App Check
      // tokens as needed.
      isTokenAutoRefreshEnabled: false
    });

    function addBtnListener() {
      document
        .getElementById("btn-database")
        .addEventListener("click", () => {
          console.log("Calling database");
          ref(database, "test")

        });
    }
    window.addEventListener("DOMContentLoaded", () => {
      addBtnListener();
    });
  </script>
</head>

<body>
  <button id="btn-database">Call database</button>
</body>

</html>
```

**Comment by hsubox76** [comment]
The first error is outside of the Firebase code, in the recaptcha__en script downloaded by recaptcha. If recaptcha isn't able to work properly, it would lead to not being able to exchange a valid token with the app check endpoint. I'm not sure if there's an error in the recaptcha code, and I can't find that specific error message in any search, but some people who have had recaptcha errors reported that upgrading their version of chromium fixed it?

Either way, a bug in recaptcha's code is outside the scope of this repo but I'll keep this open for now so we can make sure that's what it is, and look into reporting it to the recaptcha team if necessary.

**Comment by vincekruger** [comment]
I've done some more testing...

I created an HTML page with just ReCaptcha and triggered a token refresh successfully which leads me to believe there isn't an issue with the Recaptcha script.  I'm also using the latest Chromium version: Version 95.0.4638.69 (Official Build) (arm64)

The only time this issue shows itself is when it's used in conjunction with AppCheck.

**Comment by hsubox76** [comment]
Odd, I'm not able to reproduce this using your example html file above. I have the same version of Chrome as you do except it's x86_64 instead of arm64. It seems unlikely that's the difference but unfortunately I can't test on arm64 to find out. Are you able to test on an x86_64 Mac?

I'm not sure what else it could be, does clearing cache or anything help?

For the exchange endpoint request returning the 403 (url should be `https://content-firebaseappcheck.googleapis.com/v1beta/projects/appcheck-testing/apps/[appId]:exchangeRecaptchaToken?key=[API key]`) what payload did it send to the endpoint?  It should be something like:

```
{ recaptcha_token: [recaptcha token string] }
```

Is the string undefined or anything weird?

**Comment by vincekruger** [comment]
It's a Chrome arm64 issue.  What a bug to find.
Alright, so that means is not AppCheack. :). Good to know.
