### ISSUE TITLE
Missing type declarations in Auth interface

### ISSUE THREAD

**Issue by gonzaloriestra** [firebase/firebase-js-sdk#573]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 17.10
  * Firebase SDK version: 4.11.0
  * Firebase Product: Auth

#### Steps to reproduce:

If you try to use the Auth function [createUserAndRetrieveDataWithEmailAndPassword](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserAndRetrieveDataWithEmailAndPassword), Typescript complaints about it: `Property 'createUserAndRetrieveDataWithEmailAndPassword' does not exist on type 'Auth'`.

#### Relevant Code:

In [firebase/index.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts) the function `createUserAndRetrieveDataWithEmailAndPassword` should be defined in the Auth interface, as it is in [auth-types/index.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts).

**Comment by gonzaloriestra** [comment]
The function `signInAndRetrieveDataWithEmailAndPassword` is also missing.

**Comment by bojeil-google** [comment]
It is right here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L280

**Comment by gonzaloriestra** [comment]
@bojeil-google Thanks, but shouldn't it be also defined in [firebase/index.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts)?

**Comment by bojeil-google** [comment]
Ah, i had forgotten about this file. There are a bunch of missing APIs there. Ok, will look into adding the missing APIs.

**Comment by Splaktar** [comment]
Looks like this got solved in https://github.com/firebase/firebase-js-sdk/commit/9d00c6f0c57f8ddd73a740766918eece7a53c6aa

**Comment by gonzaloriestra** [comment]
@Splaktar I just added one function, but as bojeil-google said, there are more pending functions to add, like `signInAndRetrieveDataWithEmailAndPassword`.

**Comment by bojeil-google** [comment]
The missing ones should be available now.
