### ISSUE TITLE
FR: when .update is used with a withConverter handle typing similar to how it works with .set with the merge=true option.

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [firebase/firebase-js-sdk#5737]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04.5 LTS
  * Browser version: Version 94.0.4606.61 (Official Build) (64-bit)
  * Firebase SDK version: @firebase/firestore": "1.18.0"
  * Firebase Product: firestore

I'm using the withConverter feature to cast my firestore data to my own types. The problem is, I can put arbitrary data into my firestore documents with a .update call. 

It seems that the feature I would like is actually somewhat supported through using a .set call with the merge=true option as described here: https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FirestoreDataConverter#tofirestore. The reason I'm apprehensive about using this, is that simply forgetting to write this merge=true option results in critical data loss.

It also seems reasonable that updating firestore data should be schemaless. But after adding a custom converter I think it would be reasonable to expect to only be able to update with fields that respect the given data model supplied.

I found issue https://github.com/firebase/firebase-js-sdk/issues/2842 which seems to suggest that the reason being that update does not accept custom objects. I don't think I see any issues about why we can't run this object through the converter, which should then take a Partial<T> as described in the above link?

**Comment by thebrianchen** [comment]
@JoachimKoenigslieb The `updateDoc()` function in v9 ([link](https://firebase.google.com/docs/reference/js/firestore_lite.md#updatedoc)) uses a new `UpdateData type ([link](https://firebase.google.com/docs/reference/js/firestore_lite.md#updatedata)) that does type checking and supports Field Values.

I'm going to mark this issue as closed, but feel free to ask any other questions you may have!

**Comment by JoachimKoenigslieb** [comment]
Thats just beautiful! A good reason to upgrade I guess... Thanks for the good work!
