### ISSUE TITLE
Confusing error types

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-js-sdk#5754]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.10
  * Browser version: Chrome 96.0.4664.45 64b
  * Firebase SDK version: 9.5.0
  * Firebase Product: firestore, auth, storage

### [REQUIRED] Describe the problem

To handle Firebase errors in a generic way I had to do dangerous type assertions to calm TypeScript down.

Firestore is a part of Firebase but, _according to TypeScript_,  `FirestoreError` is _not_ a `FirebaseError`.
But `AuthError` _is_ a `FirebaseError`, just like `StorageError` (looks like at least).
But `StorageError` has a special attribute `serverResponse`, not nested into `customData` like `AuthError` does…
Wat?

Here are the incriminated TypeScript interfaces:

```typescript
/** An error returned by a Firestore operation. */
export declare class FirestoreError extends Error {
    /**
     * The backend error code associated with this error.
     */
    readonly code: FirestoreErrorCode;
    /**
     * A custom error description.
     */
    readonly message: string;
    /** The custom name for all FirestoreErrors. */
    readonly name: string;
    /** The stack of the error. */
    readonly stack?: string;
    private constructor();
}
```

```typescript
/**
 * Interface for an `Auth` error.
 *
 * @public
 */
export declare interface AuthError extends FirebaseError {
    /** Details about the Firebase Auth error.  */
    readonly customData: {
        /** The name of the Firebase App which triggered this error.  */
        readonly appName: string;
        /** The email address of the user's account, used for sign-in and linking. */
        readonly email?: string;
        /** The phone number of the user's account, used for sign-in and linking. */
        readonly phoneNumber?: string;
        /**
         * The tenant ID being used for sign-in and linking.
         *
         * @remarks
         * If you use {@link signInWithRedirect} to sign in,
         * you have to set the tenant ID on the {@link Auth} instance again as the tenant ID is not persisted
         * after redirection.
         */
        readonly tenantId?: string;
    };
}
```

```typescript
/**
 * An error returned by the Firebase Storage SDK.
 * @public
 */
export declare interface StorageError {
    /**
     * A server response message for the error, if applicable.
     */
    serverResponse: string | null;
    code: string;
    customData?: Record<string, unknown>;
    name: 'FirebaseError';
    message: string;
    stack?: string;
}
```

```typescript
export declare class FirebaseError extends Error {
    readonly code: string;
    customData?: Record<string, unknown> | undefined;
    readonly name = "FirebaseError";
    constructor(code: string, message: string, customData?: Record<string, unknown> | undefined);
}
```

So two little requests :pray:

1. Could it be possible for `FirestoreError` to actually be a `FirebaseError` just like other Firebase errors?
2. Would it be possible for all `FirebaseError`, including `StorageError`, to simply have `code`, `name`, `message` and `stack` attributes, and all other error details nested into `customData` (as it was done for `AuthError`)? 

That would make my day. 

Cheers,
Laurent

**Comment by wu-hui** [comment]
Hey @laurentpayot 

Thanks for the request. We will look into this and see if we can improve.

**Comment by schmidt-sebastian** [comment]
PR is pending review (but almost everyone is out for the holidays)
