### ISSUE TITLE
400 Error on signInWithEmailAndPassword and initializing firebase app in React

### ISSUE THREAD

**Issue by dhmi19** [firebase/firebase-js-sdk#5759]
### [REQUIRED] Describe your environment

  * Operating System version: Linux/Arm 64   
  * Browser version: Chrome Version 96.0.4664.55 (Official Build) (x86_64)
  * Firebase SDK version: 9.4.0
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem

I am trying to sign in a user given an email and an access code. Before calling the firebase signInWithEmailAndPassword() function, I initialize a firebase app using initializeApp(firebaseConfig) and then I call getAuth(firebaseApp) to get my auth object. However, I get the following error when I call getAuth():
![image](https://user-images.githubusercontent.com/57159970/143307723-eb43970a-1f10-4625-91c2-e156962910d2.png)
![image](https://user-images.githubusercontent.com/57159970/143307764-7c58c1b8-08f6-45a8-ad33-ca9bfdcfe30c.png)

Perhaps there is something wrong with the way I am initializing the firebase app or calling getAuth()? 

#### Relevant Code:

```javascript
const firebaseConfig = {
    apiKey: "...",
    authDomain: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
    appId: "...",
  };

const onSetPasswordClick = async () => {
    if (newPassword !== confirmNewPassword) {
      // TODO: handle user fields verification
    } else {
      console.log("onSetPasswordClick called");
      try {
        const firebaseApp = firebase.initializeApp(firebaseConfig);
        const auth = getAuth(firebaseApp);
        console.log("Initialized firebase app");
        // try to login the user to get the currentUser from firebase-auth
        await signInWithEmailAndPassword(auth, userEmail, accessCode);
        console.log("Signed in with email and password");
... 
} 
```

**Comment by sam-gc** [comment]
@dhmi19 I edited your comment to remove your project details; you may want to delete your initial comment revision.

If you look at the error response that the server sends back, what does it say?

**Comment by dhmi19** [comment]
Hey, sorry about the late reply. Here is the response I get from the POST request I mentioned above:
![image](https://user-images.githubusercontent.com/57159970/144778863-d87c7db3-98a9-4833-b412-94224fa9235c.png)

The error message is "USER_NOT_FOUND" but I am pretty sure the userEmail and accessCode are correct fields.
