### ISSUE TITLE
Firestore persistence dont work

### ISSUE THREAD

**Issue by TheOneWayTruth** [firebase/firebase-js-sdk#5766]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome Version 96.0.4664.45 (Offizieller Build) (64-Bit)
  * Firebase SDK version: 9.5.0
  * Firebase Product: firestore 
  * Framework: VueJS

#### Steps to reproduce:
Start a web App with Firestore, get offline, get online again.
#### Relevant Code:
Firebase:
```javascript
const firebaseApp = initializeApp(firebaseConfig, { useFetchStreams: false, experimentalForceLongPolling: true });

const db = getFirestore(firebaseApp)
enableIndexedDbPersistence(db)
```

```chrome
POST https://firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel... net::ERR_INTERNET_DISCONNECTED

@firebase/firestore: Firestore (9.5.0): Connection WebChannel transport errored: Vd {type: 'c', target: Y, g: Y, defaultPrevented: false, status: 1}

GET https://www.google.com/images/cleardot.gif?zx=85djm29rybv6 net::ERR_INTERNET_DISCONNECTED
```
maybe an issue with my service worker?

registerServiceWorker.js
```javascript
import { Workbox } from "workbox-window";

if ("serviceWorker" in navigator) {
  let wb = new Workbox(`${process.env.BASE_URL}service-worker.js`);
  wb.register();
}
```
service-worker.js
```javascript
import { precacheAndRoute } from 'workbox-precaching';
precacheAndRoute(self.__WB_MANIFEST);
```

**Comment by jbalidiong** [comment]
Hi @TheOneWayTruth, thanks for reaching out. Following your steps to replicate, I wasn't able to reproduce the issue. I tried logging the Firestore data while offline and I was able to get it.

If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.
