### ISSUE TITLE
Can't import the named export 'openDb'

### ISSUE THREAD

**Issue by dkrefta** [firebase/firebase-js-sdk#5775]
Hey guys, I trying to use the  
`import { getAnalytics } from "firebase/analytics";`
but I'm getting this error:

```
Failed to compile.
Can't import the named export 'openDb' (imported as 'openDb') from default-exporting module (only default export is available)
node_modules/@firebase/installations/dist/esm/index.esm2017.js
```

:( 

obs: I'm using webpack not create-react-app

"firebase": "^9.5.0",
"@babel/core": "^7.12.3",
 "webpack": "5.3.2",
 "react": "^17.0.1",

**Comment by abdo643-HULK** [comment]
getAnalytics runs "registerAnalytics()" as a sideeffect when importing something. The solution is to dynamically import analytics.

**Comment by hsubox76** [comment]
Can you provide a minimal reproduction of this error?

**Comment by dkrefta** [comment]
I solved the problem by doing the downgrade of the firebase :)
