### ISSUE TITLE
REACT NATIVE - Depracted/extracted AsyncStorage from native core

### ISSUE THREAD

**Issue by JaennPB** [firebase/firebase-js-sdk#5788]
Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 9.5.0
  * Firebase Product: (auth)

Describe the problem

I get this warning while using firebase in react native. I think fire base has to import AsyncStorage from @react-native-async-storage/async-storage instead of react-native. *** please fix!!!!

AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from @react-native-async-storage/async-storage instead of react-native. See https://github.com/react-native-async-storage/async-storage

**Comment by jbalidiong** [comment]
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/1847
