### ISSUE TITLE
Is it possible to use firebase analytics in Next.js(React) app?

### ISSUE THREAD

**Issue by deadly8** [firebase/firebase-js-sdk#5796]
I have configured firebase

```
import firebase from 'firebase/app'
import 'firebase/analytics'
    export const firebaseStart = () => {
      if (typeof window !== "undefined" && !firebase.apps.length) {
        firebase.initializeApp({
          apiKey: FIREBASE_API_KEY,
          authDomain: FIREBASE_AUTH_DOMAIN,
          projectId: FIREBASE_PROJECT_ID,
          storageBucket: FIREBASE_STORAGE_BUCKET,
          messagingSenderId: FIREBASE_MESSAGING_SENDER_ID,
          appId: FIREBASE_APP_ID,
          measurementId: FIREBASE_MEASURMENT,
        })
      }
    }
```

firebaseStart() method initialized in app.tsx

and when I try to log event,

`firebase.analytics().logEvent('test 2')`
I have such an error

Server Error FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).

I cannot find examples of usages firebase analytics in Next.js apps.

If I call analytics like this

```
if (typeof window !== "undefined") {
    firebase.analytics().logEvent('test 2')
  }
```
everything works fine

**Comment by jbalidiong** [comment]
Hi @deadly8 , thanks for the report. I tried replicating, but I wasn't able to reproduce the error.
 
If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by hsubox76** [comment]
In your code you call `firebase.initializeApp()` based on a conditional (window !== undefined). So if window isn't defined, you don't initializeApp, and firebase.analytics won't be able to find the initialized app. You can't call firebase.analytics() if firebase.initializeApp() hasn't been called first so if you're going to use a conditional, put them together in the same conditional.
