### ISSUE TITLE
OAuthProvider.addScope - Scope is ignored when calling AzureAD for authorization

### ISSUE THREAD

**Issue by vsspt** [firebase/firebase-js-sdk#5804]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 96.0.4664.45 (Official Build) (64-bit)
  * Firebase SDK version: 9.5.0 and 9.6.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
My goal is to Authenticate users from Azure AD, using an OpenID connection to an Azure AD instance, based on this [guide](https://cloud.google.com/identity-platform/docs/web/oidc).

This is used by an React application that uses the JS SDK:
```javascript
const firebaseConfig = {
  apiKey: "AIzaSyBB-44iJwFPdNtiAMxxxxxxx",
  authDomain: "xxx.firebaseapp.com",
  databaseURL: "https://xxx-default-rtdb.firebaseio.com",
  projectId: "xxx",
  storageBucket: "xxx.appspot.com",
  messagingSenderId: "2323123223",
  appId: "1:9232323eb:f5aa8e54b9ee829c694459"
};

const app = initializeApp(firebaseConfig);
const auth = getFirestoreAuth(app);

const loginExternalProvider = async (user: string, providerId: string) => {
  const provider = new OAuthProvider(providerId);
  provider.addScope('my-custom-scope');
  
  provider.setCustomParameters({
    login_hint: user,
  });

  await signInWithRedirect(auth, provider);
};

getRedirectResult(auth)
      .then(result => {
        if (result) {
          const user = result.user;
          const credential = OAuthProvider.credentialFromResult(result);
          const accessToken = credential?.accessToken;
          });
        }
      });
```

The above works perfectly, and i'm able to get the AccessToken from AzureAd.

BUT, the JWT token that is generated does not have the requested Custom Scope, but instead have the following scopes: "email openid profile".

#### Steps to reproduce:
When looking at the Network Tab, i can see the following requests (keys changed for security reasons):

1 - https://xxx.com/api/v1/security/identity-providers?account=xxx@xxx.com&redirectUri=https://xxx.com/auth/callback&state=e30=
2 - https://identitytoolkit.googleapis.com/v1/projects?key=Xsddsd22
3 - https://xxx.firebaseapp.com/__/auth/handler?apiKey=Xsddsd22&appName=[DEFAULT]&authType=signInViaRedirect&redirectUrl=https://xxx.com/auth/login&v=9.6.0&providerId=oidc.azure-dev&customParameters={"login_hint":"xxx@xxx.com"}&scopes=my-custom-scope
4 - https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=Xsddsd22&cb=23232323
5 - https://www.googleapis.com/identitytoolkit/v3/relyingparty/createAuthUri?key=Xsddsd22
6 - https://login.microsoftonline.com/22323a-ads-422-232c-sds233/oauth2/v2.0/authorize?response_type=code&client_id=sdsdsdda-ads-422-232c-fgfgfgfg&redirect_uri=https://xxx.firebaseapp.com/__/auth/handler&state=a_state&scope=openid email profile&nonce=e9fd6860edd648&login_hint=xxx@xxx.com&context_uri=https://xxx.com

When looking at **Request 3**, you can see that the requested **_my-custom-scope_** was included in the scopes _**attribute**_.
BUT, when the call to Microsoft is done (**Request 6**), the requested scopes are "_**openid email profile**_", i.e., the requested **_my-custom-scope_** was not included in the call. 

#### Expected behavior:
When specifying a Scope, the specified Scope should be sent to the external Identity Provider.

**Comment by jbalidiong** [comment]
Hi @vsspt, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the behavior. I tried adding the custom scope: `provider.addScope('calendars.read');` and it is still included in the **Request 6**.

<img width="313" alt="Screen Shot 2021-12-14 at 4 08 45 PM" src="https://user-images.githubusercontent.com/88189393/145958188-a5298dbc-1c82-47e8-9df7-4227f261252a.png">
 
If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by vsspt** [comment]
@jbalidiong,

For our Use Case, we need to be able to add a Custom Scope created in Microsoft Azure AD.

As such, instead of using the Scope _**calendars.Read**_, could you please do:
`provider.addScope('my-custom-scope');`

When injecting the Custom scope, it will be ignored, and the other profiles will be injected:
`scope: email openid profile User.Read`

What would i like to achieve?
- Ideally, i would like to be able to override the default scopes, and that the custom scopes would be injected, something like:

```javascript
provider.addScope('my-custom-scope');
provider.removeDefaultScopes();
```
Which would result in:
`scope: my-custom-scope`

Thank you!

**Comment by jbalidiong** [comment]
@vsspt, thanks for clarifying the issue. I tried using a custom scope: `api://..../my-scope` and it is still present in both Request 3 and 6. 

`scope: profile api://...../my-scope openid User.Read
`

**Comment by vsspt** [comment]
Strange, as i mentioned, i do see it on Request3, but not in Request6.

Could you please confirm that you have used an OIDC connection, using the Code flow Grant Type?

![image](https://user-images.githubusercontent.com/9887811/146052888-36974ec4-7305-450f-9861-f0b733060788.png)

If so, what do you think could be the problem?
The code i'm using is literally the one i pasted above !!!

**Comment by jbalidiong** [comment]
@vsspt, I don't see the OIDC provider on my end. I'm uncertain as to the cause of this inconsistent behavior. It may be more of a settings issue rather than an SDK. I highly recommend to file a ticket in the [Firebase support channel](https://firebase.google.com/support) to further investigate the issue.
