### ISSUE TITLE
Property 'ReCaptchaEnterpriseProvider' does not exist on appCehck

### ISSUE THREAD

**Issue by orbachar** [firebase/firebase-js-sdk#5806]
### [REQUIRED] Describe your environment

  * Operating System version: Osx
  * Browser version: Chrome
  * Firebase SDK version: 8.10.0
  * Firebase Product: app-check

I am trying to initialize App Check with Recaptcha enterprise as described here: (web version 8) 
https://firebase.google.com/docs/app-check/web/recaptcha-enterprise-provider

but I am getting this error: 'Property 'ReCaptchaEnterpriseProvider' does not exist on type 'typeof appCheck'.

![image](https://user-images.githubusercontent.com/57751360/145415961-a7bb23cd-f5d4-4d87-b7b0-d451b1a72d7f.png)

when trying to run while ignoring the typescript error I am getting: 
'appCheck.ReCaptchaEnterpriseProvider is not a constructor'

code to reproduce:
```javascript
        import 'firebase/app-check';

    // Initialize Firebase
        firebase.initializeApp(firebaseConfig);


        const appCheck = firebase.appCheck();
        appCheck.activate(
            new firebase.appCheck['ReCaptchaEnterpriseProvider'](
                appCheckRecaptchaKey
            ),
            true // Set to true to allow auto-refresh.
        );

```

**Comment by jbalidiong** [comment]
Hi @orbachar, thanks for reaching out. I tried replicating and I was able to reproduce the error. I noticed that you are using an outdated SDK version, would you mind trying it out with the `v9.6.1` which is the latest for the official release. I verified that it's working fine for `v9.6.1` SDKs. 

I'm going to close this one out for now, but please reopen or comment if you're still running into issues.

**Comment by orbachar** [comment]
@jbalidiong yes it works with version 9, thanks
