### ISSUE TITLE
Double query on the same path triggers child_removed

### ISSUE THREAD

**Issue by petrot** [firebase/firebase-js-sdk#5807]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12.0.1
  * Browser version: Brave 1.32.113
  * Firebase SDK version: 9.6.0
  * Firebase Product: database

#### Steps to reproduce:

I have an Angular app, where I use the new modular Firebase code. I list various records based on their timestamp.

1) I have a monthly view with continuous watch (with stateChanges)
2) I have a yearly query (it runs only once)

The main view is the monthly view, the query works perfectly when I change the month value. But when I generate a yearly report for the previous years with the 2nd query, the 1st subscription triggers stateChanges with child_removed events. Seems like both query uses the same stream and the yearly report clears the monthly values..

Is it normal? Or is it a bug?

#### Relevant Code:

```javascript

import { Database, endAt, get, objectVal, orderByChild, query, ref, startAt, stateChanges } from '@angular/fire/database';

// Monthly query
stateChanges(
  query(
    ref(this._database, `/wallets/${walletId}/records`),
    ...[
      orderByChild('ts'),
      startAt(currentMonth.start),
      endAt(currentMonth.end),
    ]
  )
)

// Yearly query, run once inside rxjs from() to convert into stream
get(
  query(
    ref(this._database, `/wallets/${walletId}/records`),
    ...[
      orderByChild('ts'),
      startAt(dayjs(year).startOf('year').valueOf()),
      endAt(dayjs(year).endOf('year').valueOf()),
    ]
  )
)
```

**Comment by jbalidiong** [comment]
Hi @petrot, thanks for reporting this behavior. I tried replicating the issue, however I wasn't able to experience the same behavior. A reproducible example would be ideal, but in the meantime, could you share a few more details like logs to help us to further investigate it.

**Comment by petrot** [comment]
I think I have this problem.. https://stackoverflow.com/questions/48139076/firebase-caching-ruins-order-of-retrieved-children/48140197#48140197

**Comment by jbalidiong** [comment]
@petrot, are you also getting the same behavior if you use `get()` instead of `stateChange()` for the first query?
