### ISSUE TITLE
onMessage payload `click_action` and `icon` not received because `propagateNotificationPayload`

### ISSUE THREAD

**Issue by rockmandash** [firebase/firebase-js-sdk#5824]
### [REQUIRED] Describe your environment

  * Operating System version:  macOS 12.0.1
  * Browser version:  Chrome 96
  * Firebase SDK version:  9.6.1
  * Firebase Product:  cloud messaging

### [REQUIRED] Describe the problem

This function removes `click_action` and `icon` when `onMessage` is called by foreground app.

https://github.com/firebase/firebase-js-sdk/blob/8d415c6b4acfac1784404bd652316df6d42055e1/packages/messaging/src/helpers/externalizePayload.ts#L39-L63

And the `image` is not supported on macOS 12, which makes the code very confusing.

**Comment by zwu52** [comment]
@rockmandash  I assume you are sending through the [legacy send API](https://firebase.google.com/docs/cloud-messaging/http-server-ref) since `click_action` and `icon` has been deprecated after v1 Send. I can make a PR to fill them in

I

**Comment by rockmandash** [comment]
@zwu52 I did not utilize a legacy API, thus my payload is as follows:

```json
{
  "message": {
    "token": "",
    "notification": {
      "title": "",
      "body": ""
    },
    "webpush": {
      "fcm_options": {
        "link": ""
      },
      "notification": {
        "icon": ""
      }
    }
  }
}
```

The FCM backend formats the `webpush.fcm_options.link` to `click_action` automatically.

For firebase-messaging-sw.js, my payload works normally in background mode without doing anything.

However when it comes to foreground messages, these two payloads are lost, which is why I created this problem.

**Comment by zwu52** [comment]
I see. as stated previously, [v1 API](https://www.colorhexa.com/cfbd85) deprecated the two fields for webpush. I don't know the use case but you could consider put the key value pairs in the `data` field

**Comment by guiiamorim** [comment]
I'm also having this issue, I cant see any of the fcm_options on the event handlers provided by the sdk. For the link to appear I have to make my own `notificationclick` event handler on the service worker:
![image](https://user-images.githubusercontent.com/9733153/166444871-fc1b8475-d38a-41f7-ad39-8f258adf5950.png)
Also, if I add an event listener on the `push` event I can retrieve the click_action parsing the event data to json. Someone found a solution for this?

**Comment by guimap** [comment]
@guiiamorim the code 
![image](https://user-images.githubusercontent.com/9733153/166444871-fc1b8475-d38a-41f7-ad39-8f258adf5950.png) 
works for you ? For me, this event never reach, because this code 
https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging/src/listeners/sw-listeners.ts#L121

**Comment by DellaBitta** [comment]
It looks like an attempted fix was merged in. Could you check to see if it fixes this issue? Thanks!
