### ISSUE TITLE
[AppCheck] firestore missing or insufficient permissions after a while 

### ISSUE THREAD

**Issue by orbachar** [firebase/firebase-js-sdk#5842]
* Browser version: Chrome 
  * Firebase SDK version: 9.6.1
  * Firebase Product: app check

Hey, 
I am using app check with reCAPTCHA Enterprise and Cloud Firestore enforced on my webapp. 
I also set the token TTL to 30 minutes. 

I noticed that after a while when the browser idle, I am getting "FirebaseError: Missing or insufficient permissions."  and can't query the DB anymore.

![image](https://user-images.githubusercontent.com/57751360/147581590-8bb8b65a-ac9d-45e9-a129-6a3dad13d37c.png)

refresh fixes it..
so I believe it is because the token isn't valid anymore, although I enabled auto refresh.

this is the code I am using

```
        const appCheck = initializeAppCheck(app, {
            provider: new ReCaptchaEnterpriseProvider(appCheckRecaptchaKey),
            isTokenAutoRefreshEnabled: true // Set to true to allow auto-refresh.
        });

```

![image](https://user-images.githubusercontent.com/57751360/147581949-c314be02-1b9e-4374-8492-d144fc64e34e.png)

**Comment by orbachar** [comment]
attaching logs:

![image](https://user-images.githubusercontent.com/57751360/148463759-cfb7fb97-2c69-4fd1-a962-fcd2f33e098c.png)
![image](https://user-images.githubusercontent.com/57751360/148463768-d8516d71-befe-4c3c-83db-6fa1900259c2.png)

**Comment by ehsannas** [comment]
Thanks @orbachar . I want to make sure this is indeed an AppCheck issue (rather than an Authentication issue). Can you please confirm that if you **_turn off_** AppCheck enforcement for Firestore in the Firebase Console, the issue does not occur anymore?

**Comment by orbachar** [comment]
yes, I did that again today just to make sure - with AppCheck unenforced for Firestore, it doesn't happen. if I turn on appCheck again, the errors return after some idle time

**Comment by ehsannas** [comment]
Thanks for confirming @orbachar.

**Comment by ehsannas** [comment]
@orbachar I was able to reproduce this issue. I'll continue to look into fixing this.
