### ISSUE TITLE
Slow firestore retrieval speeds after upgrading from 8 to 9/compat - most time spent in webchannel-wrapper

### ISSUE THREAD

**Issue by odeniso** [firebase/firebase-js-sdk#5845]
* Operating System version: Mac OS
  * Browser version: Chromium
  * Firebase SDK version: 9.6.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
We have upgrader our firebase app to use the v9/compat SDKs, and have noticed much slower document retrievals from firestore.
On the latest version of firebase v8 (8.9.1), this is not noticeable, but upgrading it to any version of v9 (up until 9.6.1), causes the issue to come up.

What is being done is getting around 300 documents, each around  20kb. This is done frequently (~1 per second), via onSnapshot handlers, or by getting the documents for a query directly. After the upgrade, this is has become a lot slower. 

A performance recording indicates that the time is all spent in `@firebase/webchannel-wrapper`, and that JS Heap memory consumption repeatedly hits 2GB, then crashes back down to 200MB, then back up to 2GB.

https://github.com/firebase/firebase-js-sdk/issues/4416 
^ this seemed to be a similar issue, and setting `experimentalForceLongPolling` to true does relieve the issue a little bit, but it doesn't come close to the retrieval speeds we were seeing before upgrading to v9/compat.

I understand this is a pretty vague description, but I am a little lost as to how to dig deeper into the issue. I would be very grateful for any recommendations, and to supply any further information.

**Comment by thebrianchen** [comment]
@odeniso Is it possible for you reproduce this in a sample app? Otherwise it would be hard for us to know dig deeper and see what is going on. Thanks!
