### ISSUE TITLE
Setting languageCode does not change the language of email templates

### ISSUE THREAD

**Issue by codingedgar** [firebase/firebase-js-sdk#5846]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur
  * Browser version: Chrome 95
  * Firebase SDK version: 9.5.0
  * Firebase Product: auth

#### Steps to reproduce:

Setting languageCode does not work

I want to send an email Verification email in multiple langs, but no matter what lang i set the auth instance with, the email is only send with the la guage I set in Firebas Console > Authentication > Template > Language; If i set it to Swedish or any lang it is always sent in that language.

https://github.com/firebase/firebaseui-web/issues/487 seems to be related, in this issue some folks say setting a delay might help, i place some delays between setting the languageCode and sending the email but it didn't work.

#### Relevant Code:
Following https://github.com/firebase/snippets-web/blob/1c4c6834f310bf53a98b3fa3c2e2191396cacd69/snippets/auth-next/index/auth_set_language_code.js
```javascript

import { getAuth, sendEmailVerification } from "firebase/auth";

function resendEmail(user) {
 const auth = getAuth();
 auth.languageCode = 'it';
 sendEmailVerification(user)
}
```

**Comment by codingedgar** [comment]
Also which locales can be used in the languageCode? I can't find any list in the firebase docs

**Comment by jbalidiong** [comment]
Hi @codingedgar, thanks for reaching out to us. Currently, you can have multilingual emails only if you use the standard template provided by Firebase. If you have a customized template you can reset it in the console. To send locale specific mails you should manually call the function to use the device language or set it with a string. Here is a sample snippet for v9:

```
import { getAuth } from "firebase/auth";

const auth = getAuth();
auth.languageCode = 'fr';
// To apply the default browser preference instead of explicitly setting it.
// auth.useDeviceLanguage();
```
You can check the list of supported language code [here](https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md). To help you on setting the language, you can use the `useDeviceLanguage()` to apply the browser preference. Using this code, I was able to get the email verification in French (the template language in the console is set to English).

I'll be closing this for now. If the issue persists, feel free to comment and reopen this issue.

**Comment by codingedgar** [comment]
> Hi @codingedgar, thanks for reaching out to us. Currently, you can have multilingual emails only if you use the standard template provided by Firebase. If you have a customized template you can reset it in the console. To send locale specific mails you should manually call the function to use the device language or set it with a string. Here is a sample snippet for v9:
> 
> 
> 
> ```
> 
> import { getAuth } from "firebase/auth";
> 
> 
> 
> const auth = getAuth();
> 
> auth.languageCode = 'fr';
> 
> // To apply the default browser preference instead of explicitly setting it.
> 
> // auth.useDeviceLanguage();
> 
> ```
> 
> You can check the list of supported language code [here](https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md). To help you on setting the language, you can use the `useDeviceLanguage()` to apply the browser preference. Using this code, I was able to get the email verification in French (the template language in the console is set to English).
> 
> 
> 
> I'll be closing this for now. If the issue persists, feel free to comment and reopen this issue.

Thanks a lot for your answer, i am using Firebase default templates, setting languageCode to a string does *not* work.

Using the browser language is not part of my business logic, as the lang is set by the user in-app-settings in my app.

**Comment by codingedgar** [comment]
> Hi @codingedgar, thanks for reaching out to us. Currently, you can have multilingual emails only if you use the standard template provided by Firebase. If you have a customized template you can reset it in the console. To send locale specific mails you should manually call the function to use the device language or set it with a string. Here is a sample snippet for v9:
> 
> ```
> import { getAuth } from "firebase/auth";
> 
> const auth = getAuth();
> auth.languageCode = 'fr';
> // To apply the default browser preference instead of explicitly setting it.
> // auth.useDeviceLanguage();
> ```
> 
> You can check the list of supported language code [here](https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md). To help you on setting the language, you can use the `useDeviceLanguage()` to apply the browser preference. Using this code, I was able to get the email verification in French (the template language in the console is set to English).
> 
> I'll be closing this for now. If the issue persists, feel free to comment and reopen this issue.

I verified my code once more, and it seems i made a mistake somewhere, it is working with both methods now, thank you 🙏 🤩 😍

**Comment by laffe** [comment]
@jbalidiong Could you look over my code? I cant see any issues, but it doesnt seem to work.
`<script type='module'>
    import { getAuth, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js";
    
    recoveryButton.addEventListener('click', recovery);
    function recovery() {
        var email = emailField.value;
        const auth = getAuth();
        auth.languageCode = window.location.pathname.split('/')[1];
        // also triedauth.languageCode = 'en';
        sendPasswordResetEmail(auth, email)
            .then(() => {
                // Password reset email sent!
                // ..
                window.location.replace('./email-sent')
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                // ..
            });

    }

</script>`

**Comment by laffe** [comment]
@jbalidiong Could you look over my code? I cant see any issues, but it doesnt seem to work.
`<script type='module'>
    import { getAuth, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js";
    recoveryButton.addEventListener('click', recovery);
    function recovery() {
        var email = emailField.value;
        const auth = getAuth();
        auth.languageCode = window.location.pathname.split('/')[1];
        //also tried auth.languageCode = 'en';
        sendPasswordResetEmail(auth, email)
            .then(() => {
                // Password reset email sent!
                // ..
                window.location.replace('./email-sent')
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                // ..
            });
    }
</script>`

**Comment by laffe** [comment]
@jbalidiong Could you look over my code? I cant see any issues, but it doesnt seem to work.
`<script type='module'>
    import { getAuth, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js";
    recoveryButton.addEventListener('click', recovery);
    function recovery() {
        var email = emailField.value;
        const auth = getAuth();
        auth.languageCode = window.location.pathname.split('/')[1];
        //also tried auth.languageCode = 'en';
        sendPasswordResetEmail(auth, email)
            .then(() => {
                // Password reset email sent!
                // ..
                window.location.replace('./email-sent')
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                // ..
            });
    }
</script>`

**Comment by laffe** [comment]
<script type='module'>
    import { getAuth, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js";
    recoveryButton.addEventListener('click', recovery);
    function recovery() {
        var email = emailField.value;
        const auth = getAuth();
        auth.languageCode = window.location.pathname.split('/')[1];
        //also tried auth.languageCode = 'en';
        sendPasswordResetEmail(auth, email)
            .then(() => {
                // Password reset email sent!
                // ..
                window.location.replace('./email-sent')
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                // ..
            });
    }
</script>

**Comment by laffe** [comment]
`<script type='module'>
    import { getAuth, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js";
    recoveryButton.addEventListener('click', recovery);
    function recovery() {
        var email = emailField.value;
        const auth = getAuth();
        auth.languageCode = window.location.pathname.split('/')[1];
        //also tried auth.languageCode = 'en';
        sendPasswordResetEmail(auth, email)
            .then(() => {
                // Password reset email sent!
                // ..
                window.location.replace('./email-sent')
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                // ..
            });
    }
</script>`

**Comment by laffe** [comment]
Could you also look over my code? I cant see any errors, and it sends the email like it should, but doesnt change the email template.
`<script type='module'>
    import { getAuth, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js";

    recoveryButton.addEventListener('click', recovery);
    function recovery() {
        var email = emailField.value;
        const auth = getAuth();
        auth.languageCode = window.location.pathname.split('/')[1];
        //also tried auth.languageCode = 'en';
        sendPasswordResetEmail(auth, email)
            .then(() => {
                // Password reset email sent!
                // ..
                window.location.replace('./email-sent')
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                // ..
            });
    }
</script>`
