### ISSUE TITLE
auth().signInWithPopup failing for Chrome 96, Firefox 95 & Edge 96

### ISSUE THREAD

**Issue by MdYeasinSamadArnob** [firebase/firebase-js-sdk#5849]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10_
  * Browser version: Chrome 96, Firefox 95 & Edge 96
  * Firebase SDK version: 8.7.1
  * Firebase Product: (Google  auth)

#### Steps to reproduce:

I developed a web app where firebase google auth was used and with a popup sign in was done. It was working properly in production also. But suddenly yesterday at 12 noon popup window is showing blank. I tested in other browsers and found that only  in Opera and Brave browser it was working. Chrome 96, Firefox 95 & Edge 96 showing just blank screen. Another caveat I found is that in localhost:3000 all popups are working in all browsers but in production only in opera nd brave it working.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
function Login() {
  const [{user},dispatch]=useStateValue();
  const signin = () => {
    auth
      .signInWithPopup(provider)
      .then((result) => {
        console.log(result);
        dispatch({
          type:actionTypes.SET_USER,
          user:result.user,
        })

      })
      .catch((error) => {
        alert(error.message);
      });
  };
```

### Error Message
Object { code: "auth/cancelled-popup-request", message: "This operation has been cancelled due to another conflicting popup being opened.", a: null, stack: "" }
​
a: null
​
code: "auth/cancelled-popup-request"
​
message: "This operation has been cancelled due to another conflicting popup being opened."
​
stack: ""
​

**Comment by sam-gc** [comment]
Please upgrade to the latest version of the JS SDK (the current major version number is `9`). You'll likely want to use the compatibility layer to avoid having to migrate everything to the new modular syntax: https://firebase.google.com/docs/web/modular-upgrade#about_the_compat_libraries
