### ISSUE TITLE
addDoc() function of firestore is not returning either success or error.

### ISSUE THREAD

**Issue by Kumar2106** [firebase/firebase-js-sdk#5852]
I am coding a cross platform Application in React Native, and trying to save data in firestore, i have read the documentation and coded according to that but when the addDoc() is coded it is neither returning success nor error. I have tried different methods but nothing solved the issue.

#### Steps to reproduce:
This is the console output upon running the code.

[15:29:08] Inside write data
[15:29:08] Inside try block
[15:29:10] Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
[15:29:10] (Saw setTimeout with duration 3299590ms)
[15:29:10] User id in createUserWithEmailAndPassword function Sc8ZaMki8ZOlc0ph9vddNu2CYpA2

#### Relevant Code:

```
wirteData = async()=>{
    console.log("Inside write data");
    const app = initializeApp(config);
    const db = getFirestore();
    try{
      console.log("Inside try block")
      const docRef = await addDoc(collection(db, "UsernameToUserId"),{
        first:"Ada",
        last: "Lovelace",
        boran:"1815"
      });
      console.log("Document writtent with iId: ", docRef.id);
    }
    catch(e){
      console.log("Error adding document",e);
    }
  }

```
As from the log you can see that the function is being called but the addDoc is not getting executed i don't know why.

**Comment by raulbarboz** [comment]
Hello friends.
I'm having same problem, when I try to set, push, or even in firestore with addDoc it gives me to loong to save and respond.
Sometimes the response doesn't occurs.

Here is my code:

First Try: with v9 firestore
/*export const start_add_checkout = (checkout) => {
  return async (dispatch) => {
    const newPostKey = push(child(ref(database), 'checkout')).key;
    console.log(newPostKey)
    await set(ref(database, `checkout/${newPostKey}`), {
      prods: checkout,
      status : 'cart',
      userId: ''
    });
    return dispatch(add_checkout({
      id: newPostKey,
      prods: checkout,
      status: 'cart',
      userId: '',
    }))
  }
}*/

Second try with v9 compat real time database:
export const start_add_checkout = (checkout) => {
  return (dispatch) => {
    console.log('chamou')
    db.ref('checkoutabs/asds123').set({
      prods: checkout,
      status: 'cart',
      userId: 'asd',
    }, (error) => {
      if (error) {
        // The write failed...
        console.log(error)
        return
      } else {
        // Data saved successfully!
        console.log('saved')
        return dispatch(add_checkout({
          id:'lalalal0190939',
          prods: checkout,
          status: 'cart',
          userId: '',
        }))
      }
    });
  }
}

**Comment by dconeybe** [comment]
@raulbarboz This issue is regarding Firestore, which, although similar to Realtime Database, is a completely different product. Please kindly open a new issue for this problem you are experiencing with Realtime Database.

**Comment by frank505** [comment]
experiencing same thing on v9 @Kumar2106 have you resolved this?

**Comment by dconeybe** [comment]
@frank505 If you have a reproducible scenario, could you open a new GitHub issue for this? In particular, please fill out the issue template completely so that we can maximally assist you. If at all possible, please provide your reproducible scenario (e.g. a GitHub repository) so that the Firestore engineers can reproduce and debug.

**Comment by frank505** [comment]
@dconeybe i just realized my error, i initially thought i had a firestore DB i only realized after downgrading v7 and i was still experiencing the same thing , thanks :) once again for all the work and effort you and the team have put into this package :).

**Comment by dconeybe** [comment]
@frank505 Excellent! Thank you for sharing.
