### ISSUE TITLE
"There was an error checking your user" logging via GitHub in Firefox v92.0

### ISSUE THREAD

**Issue by firepacket** [firebase/firebase-js-sdk#5898]
I cannot login to VirusTotal with Github while logged into Github, and granting access with the popup, using Firefox v92 I get this error : **_There was an error checking your user_**

Works fine with Chrome all same plugins.

How do I fix this? Clicking on "Continue with Github" brings me to the same page:

![virustotal](https://user-images.githubusercontent.com/3860274/149812632-8fec0d05-9092-4940-886a-e60a96d5bc54.jpg)

**Comment by hsubox76** [comment]
Sorry, did you mean to file this issue in the Firebase JS SDK repo? This doesn't seem related to Firebase. Are you the developer of this app and using Firebase Auth?

**Comment by firepacket** [comment]
Wow, please forgive me.
