### ISSUE TITLE
There is no way to get the key of the latest element on a collection as it was possible on v8

### ISSUE THREAD

**Issue by danielo515** [firebase/firebase-js-sdk#5899]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12
  * Browser version:  Chrome
  * Firebase SDK version:  9
  * Firebase Product: database 

#### Steps to reproduce:

If you use a query to get the last child of a database slice, when you access the key of the result you get the key of the parent route instead of the key of the lastChild of the query result.

#### Relevant Code:

This code not work on the V9 version:

```javascript
   const dbRef = child(db, 'all');
    const last = await get(query(dbRef, orderByKey(), limitToLast(1)));
     console.log(last.key) // ===> all
```

The "equivalent" version on the v8 version works as expected:

```javascript
    const all = db.child('all');
    const last = await all.orderByKey().limitToLast(1).once('child_added');
    console.log(last.key) // ===> -MUrxxxxxUJty0wEB3q
```

**Comment by danielo515** [comment]
As a workaround I'm using this utility:

```ts
const childOnce = (query: Query) => {
  return new Promise<DataSnapshot>((resolve) => {
    onChildAdded(
      query,
      (snapshot) => {
        resolve(snapshot);
      },
      { onlyOnce: true },
    );
  });
};
```

**Comment by jbalidiong** [comment]
Thanks for reaching out @danielo515. To confirm, the workaround that you've provided is the correct method to get the key instead of the first code snippet. To add information:

```
   const dbRef = child(db, 'all');
    const last = await get(query(dbRef, orderByKey(), limitToLast(1)));
     console.log(last.key) // ===> all
```

The snippet above will give you the snapshot of the parent. While the snippet for `v8` gives you the DataSnapshot of the latest child added.

```
    const all = db.child('all');
    const last = await all.orderByKey().limitToLast(1).once('child_added');
    console.log(last.key) // ===> -MUrxxxxxUJty0wEB3q
```

I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
