### ISSUE TITLE
[Messaging] onTokenRefresh never triggers

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-js-sdk#59]
### [REQUIRED] Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: 4.1.2
  * Firebase Product: messaging

### [REQUIRED] Describe the problem
I've noticed that nothing ever gets _next_'ed into `tokenRefreshObserver_`, meaning that the function or observer passed to `firebase.messaging.Messaging#onTokenRefresh()` never gets triggered.

See: [src/messaging/controllers/window-controller.ts#L72-L75](https://github.com/firebase/firebase-js-sdk/blob/fd0728138d88c454f8e38a78f35d831d6365070c/src/messaging/controllers/window-controller.ts#L72-L75)

Is there some process missing that would receive token updates and trigger `onTokenRefresh()`?

#### Steps to reproduce:
n/a

#### Relevant Code:
See linked file.

**Comment by samtstern** [comment]
eval

**Comment by jshcrowthe** [comment]
eval

**Comment by jsayol** [comment]
I just found [this Stackoverflow answer](https://stackoverflow.com/a/42141247/4712781) by @gauntface from a few months ago addressing this. In short, in case anyone else stumbles upon this in the future: `onTokenRefresh()` is currently not used.

Closing this issue, sorry for the noise!
