### ISSUE TITLE
FR: transactions and bulkwrites doesnt use compositional api

### ISSUE THREAD

**Issue by Fuzzyma** [firebase/firebase-js-sdk#5907]
### [REQUIRED] Describe your environment

  * Operating System version: win10
  * Browser version: FF 96.0.1 (64-Bit)
  * Firebase SDK version: 9.6.3
  * Firebase Product: firestore

#### Steps to reproduce:

v9 offers a nice way of using a compositional API to enable treeshaking:

```js
import { doc, setDoc } from "firebase/firestore"; 

await setDoc(doc(db, "cities", "new-city-id"), data);
```

However, as soon as I want to use a transaction or writeBatch, the old API is back:

**Transactions:**
```js
import { runTransaction } from "firebase/firestore";

try {
  await runTransaction(db, async (transaction) => {
    // why not getDoc(sfDocRef) or at least getDoc(sfDocRef, transaction)?
    const sfDoc = await transaction.get(sfDocRef);
    if (!sfDoc.exists()) {
      throw "Document does not exist!";
    }

    const newPopulation = sfDoc.data().population + 1;
    // why not updateDoc(sfDocRef) or at least updateDoc(sfDocRef, transaction)?
    transaction.update(sfDocRef, { population: newPopulation });
  });
  console.log("Transaction successfully committed!");
} catch (e) {
  console.log("Transaction failed: ", e);
}
```

**Write batchs**
```js
import { writeBatch, doc } from "firebase/firestore"; 

// Get a new write batch
const batch = writeBatch(db);

// Set the value of 'NYC'
const nycRef = doc(db, "cities", "NYC");
// Why not setDoc(nycRef, {name: "New York City"}, batch)
batch.set(nycRef, {name: "New York City"});

// Update the population of 'SF'
const sfRef = doc(db, "cities", "SF");
// Why not updateDoc(sfRef, {"population": 1000000}, batch)
batch.update(sfRef, {"population": 1000000});

// Delete the city 'LA'
const laRef = doc(db, "cities", "LA");
// Why not deleteDoc(laRef, batch)
batch.delete(laRef);

// Commit the batch
await batch.commit();

// even better this could be:
writeBatch(db, (batch) => {
  // updateDoc(..., batch) or updateDoc(...) with implicit scoping
})
```

This feels like a logical step to do but for some reason, I am forced to use the methods on the transaction/batch.

**Comment by ehsannas** [comment]
Thanks for reporting this @Fuzzyma . Measurements showed that size savings by tree shaking for these methods were negligible, and so there was a conscious choice to keep these APIs intact.

**Comment by Fuzzyma** [comment]
For me this is about consistency and not about size. In the end, I now use 2 different APIs for the same thing.

Additionally wrapping the functions to provide extra functionality is super easy when these are just functions and not methods on a class (which I need to monkey patch instead)
