### ISSUE TITLE
Firebase version 9 upgrade leads to auth/network-request-failed error in Electron / node

### ISSUE THREAD

**Issue by PabloDotcom** [firebase/firebase-js-sdk#5910]
* Operating System version: macOS Big Sur version 11.4
  * Browser version: Chrome Version 96.0.4664.110 (Official Build) (x86_64)
  * Firebase SDK version: 9.6.3
  * Firebase Product: auth

Hi, I'm in a middle of updating firebase library in my app. App is targeted into many builds: web, embedded apps, electron.

Currently I have version: 7.21.0. -> works fine (web build and Electron build)
Tried to upgrade to version 8.10.0 -> also works fine on both (web build and Electron build)

Attempt with version 9.0.0 and 9.6.3 (with required changes applied in code) works fine in web browser.
Problem is with Electron build that in runtime ends with error:

```javascript
FirebaseError: Firebase: Error (auth/network-request-failed).
    at createErrorInternal (/Users/pablo/repos/ng-13/my-application/node_modules/@firebase/auth/dist/node/index-bb2c0266.js:506:55)
    at _fail (/Users/pablo/repos/ng-13/my-application/node_modules/@firebase/auth/dist/node/index-bb2c0266.js:477:31)
    at /Users/pablo/repos/ng-13/my-application/node_modules/@firebase/auth/dist/node/index-bb2c0266.js:1048:21
    at step (/Users/pablo/repos/ng-13/my-application/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/pablo/repos/ng-13/my-application/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/pablo/repos/ng-13/my-application/node_modules/tslib/tslib.js:115:69)
```

code looks like: 

```typescript
const app$ = concat(this.realTimeToken$, NEVER).pipe(
            finalize(async () => {
                try { await deleteApp(app); } catch (err) { }
            }
            ),
            switchMap(firebaseAuthTokenV4 => {
                const auth = getAuth(app);
                return signInWithCustomToken(auth, firebaseAuthTokenV4);
            }),
            switchMap(() => onConnected$),
            mapTo(app),
        );
```

`signInWithCustomToken` method invocation throws that error.

Idk, to what it's really related. Any help welcome :)

**Comment by sam-gc** [comment]
@PabloDotcom thanks for reaching out. I suspect what's happening is that your electron app is using the _node_ distribution in a client context (i.e. within the DOM). Is this correct (i.e. this code you've posted is running in the webview)? If so, (I'm not familiar with electron), you'll need to find a way to point your build at the _browser_ distribution instead of the node distribution.

This is different than v8 and earlier as we separate out the platforms in order to minimize included code. The old library would dynamically detect if it was in Node and act accordingly. In v9, you need to make sure you're building with the correct targets

**Comment by PabloDotcom** [comment]
@sam-gc thanks for reply. It's not a case. This part of code is running in so called "main process" of Electron app. It's a nodeJS process and it's expected (and was working on firebase version 7 and 8 as mentioned before). So stack trace that is using node dist ( `/Users/pablo/repos/ng-13/my-application/node_modules/@firebase/auth/dist/node/index-bb2c0266.js`) is expected and totally fine... Weird part is that I'm getting error from your API as `auth/network-request-failed error`. Looks like payload, headers, something is transformed on its way to fetch?

**Comment by sam-gc** [comment]
@PabloDotcom I'm able to get `signInAnonymously` working in the electron quickstart no problem. Would you mind trying `signInAnonymously` or `signInWithEmailAndPassword` so we can determine whether or not it's a systemic networking issue for you or something specific to `signInWithCustomToken`?

Thanks!

**Comment by sam-gc** [comment]
Would it be possible to see the (**redacted of sensitive information**) network details of those calls that are failing?
 1. Is a call made in the first place
 2. What are the headers?
 3. What is the response payload?

Otherwise this will be very difficult to remedy as we can't reproduce the issue on our end.

**Comment by PabloDotcom** [comment]
@sam-gc sorry for not responding that long. I've found the issue. It was related how **navigator** was mocked in main process of electron by my team mate. In general it was mocked like, let say: global.navigator = 'Electron/Windows';
should be: global.navigator = { onLine: true, userAgent: 'Electron/Windows' } as Navigator;

Because of that your util function that checks for navigator existence and for truthy of navigator.onLine throwed an error. But this error was shadowed by default error on higher level, I guess. That's why I was seeing Error (auth/network-request-failed) not a root cause... Maybe it will help you guys improve error handling a little. Anyway, thanks for quick responses from you!
