### ISSUE TITLE
Can't find variable: IDBIndex   , i am using firebase messages in expo

### ISSUE THREAD

**Issue by 10mayje** [firebase/firebase-js-sdk#5912]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @10mayje, thanks for reporting and using our template. However, I don't see fields populated - including your issue. With that said, please file a new ticket with your issue. I'll be closing this now.
