### ISSUE TITLE
React Native Firebase auth working on Android but not IOS device / simulator

### ISSUE THREAD

**Issue by chitianhao** [firebase/firebase-js-sdk#5921]
My project is Expo managed. The auth and login are working completely fine when I test it on the web browser and Android. But when I use a physical device or IOS simulator, it doesn't work.

signInWithEmailAndPassword() won't return anything but timeout and then the app crash. Any ideas? Thanks in advance!

**Comment by sam-gc** [comment]
Hi @chitianhao, we're unable to reproduce this on our end. Would you mind sharing more specific details:
 * Version numbers of Firebase/Expo/RN/etc
 * A small code snippet demonstrating the issue
 * The error code you see when the app crashes/times out

**Comment by chitianhao** [comment]
Here are the version numbers:
    "expo": "^44.0.4",
    "firebase": "^9.6.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "^0.66.4",

The code snippet
```
import React, { Component } from "react";
import { View, Button, TextInput } from "react-native";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";

export default class Login extends Component {
  constructor(props) {
    super(props);
    this.state = {
      email: "",
      password: "",
    };
    this.onSignIn = this.onSignIn.bind(this);
  }

  onSignIn() {
    const auth = getAuth();
    signInWithEmailAndPassword(auth, this.state.email, this.state.password)
      .then((userCredential) => {
        console.log(userCredential);
      })
      .catch((error) => {
        console.log(error);
      });
  }

  render() {
    return (
      <View>
        <TextInput
          placeholder="email"
          autoCapitalize="none"
          onChangeText={(email) => this.setState({ email })}
        />
        <TextInput
          placeholder="password"
          autoCapitalize="none"
          secureTextEntry={true}
          onChangeText={(password) => this.setState({ password })}
        />
        <Button onPress={() => this.onSignIn()} title="Sign In" />
      </View>
    );
  }
}
```

When I sign in with IOS, the app didn't respond and silently crashed after a while. And it seems to be a timeout for me. Is there any special config setup required to set up on the console for IOS to work?

**Comment by chitianhao** [comment]
This problem is actually fixed by some version number change.
