### ISSUE TITLE
Missing `PhoneMultiFactorInfo` type in v9

### ISSUE THREAD

**Issue by addisonElliott** [firebase/firebase-js-sdk#5922]
### Describe your environment

  * Operating System version: Google Chrome
  * Browser version: 97.0.4692.99 (64-bit)
  * Firebase SDK version: 9.6.4
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Since v9, the `PhoneMultiFactorInfo` is not exported from `firebase/auth`. This type is accessible in v8 `firebase.auth.PhoneMultiFactorInfo`.

In v9, there's still an `enrolledFactors` item that is of the type `PhoneMultiFactorInfo`. I know this because I do `enrolledFactors[0].phoneNumber` and it is still returning the 2FA phone number. It's just that the type is missing in the SDK.

See here for v8: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L376-L378

Not present in v9 public types: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/model/public_types.ts

**Comment by sam-gc** [comment]
Hi @addisonElliott, thanks for filing this. The linked PR will add the missing interface

**Comment by addisonElliott** [comment]
Thanks for the speedy response!
