### ISSUE TITLE
Dom exception in brave browser for messaging

### ISSUE THREAD

**Issue by benoist** [firebase/firebase-js-sdk#594]
Operating System version
OSX Brave Browser | 0.21.24
V8 | 6.5.254.36

Firebase SDK version: 4.12.0
Firebase Product: messaging

Reproducing the issue on StackBlitz was not possible because the service worker file is not found.

Calling messaging.getToken() after requesting the permissions and granting it throws the following error:   Registration failed - push service not available

**Comment by mmermerkaya** [comment]
It seems like [Brave Browser](https://github.com/brave/browser-laptop) is an [Electron](https://github.com/electron/electron) app (using their own [fork of Electron](https://github.com/brave/muon)).

Electron does not support Push API yet (https://github.com/electron/electron/issues/6697), which means Firebase Messaging won't work on Electron apps.
