### ISSUE TITLE
npm shows firebase 8 as latest version

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-js-sdk#5949]
https://www.npmjs.com/package/firebase

**Comment by hsubox76** [comment]
Thank you for the heads up. We released a new version of v8 because of the node-fetch security update and unfortunately it also became the default version of firebase on npm.

The `latest` tag should be pointing to 9.6.5 now, so `npm install firebase` will grab that instead of 8.10.1. I'm not sure how to fix this info on npm's webpage but will look into it.

**Comment by markgoho** [comment]
@hsubox76 `firebase` package looks good!

I'm not sure what other packages may be affected, but it looks like `@firebase/rules-unit-testing` is also pointing to an older major version:

``` bash
npm view @firebase/rules-unit-testing dist-tags
 
{
  next: '1.3.16-2022028193537',
  latest: '1.3.16',
  canary: '2.0.2-canary.6555aa70f',
  'eap-auth-emulator': '1.0.4-eap-auth-emulator.df41ee388',
  'firestore-bundles-alpha': '1.0.6-alpha.96ae6a5fe',
  'eap-firestore-debug': '1.1.3-1.0.0-eap-firestore-debug.9c6096f43',
  BundlePrerelease: '1.1.4-BundlePrerelease.b662f8c0a',
  longpoll: '1.1.7-longpoll.66863f547',
  'eap-storage-emulator': '1.2.2-eap-storage-emulator.ed256f582',
  'exp-types-exploration': '1.3.14-8.9.1-exp-types-exploration.635c9e3fd',
  pr5646: '2.0.1-pr5646.2abc5e854'
}
```

**Comment by hsubox76** [comment]
I've updated `@firebase/rules-unit-testing` first as I think people may install that separately. The other `@firebase` packages shouldn't be npm installed on their own anyway but as transitive dependencies of the main `firebase` install (which specifies pinned version numbers) but sometimes people install them for workarounds and other edge cases so I'll try to get to them one by one.

Everything should be automatically updated back to v9 by this week's release (likely Thursday Feb 3), including the npm web pages, but I'll see if I can fix the `latest` tags before then.

**Comment by markgoho** [comment]
thank you @hsubox76 -- yes we install the unit-testing lib as a standalone package

looking good now:
``` bash
npm view @firebase/rules-unit-testing dist-tags
 
{
  next: '1.3.16-2022028193537',
  latest: '2.0.2',
  canary: '2.0.2-canary.aaeab08ac',
  'eap-auth-emulator': '1.0.4-eap-auth-emulator.df41ee388',
  'firestore-bundles-alpha': '1.0.6-alpha.96ae6a5fe',
  'eap-firestore-debug': '1.1.3-1.0.0-eap-firestore-debug.9c6096f43',
  BundlePrerelease: '1.1.4-BundlePrerelease.b662f8c0a',
  longpoll: '1.1.7-longpoll.66863f547',
  'eap-storage-emulator': '1.2.2-eap-storage-emulator.ed256f582',
  'exp-types-exploration': '1.3.14-8.9.1-exp-types-exploration.635c9e3fd',
  pr5646: '2.0.1-pr5646.2abc5e854'
}
```

**Comment by hsubox76** [comment]
I think I've now fixed the `latest` tag for every package it was overwritten for on Friday.

**Comment by hsubox76** [comment]
Any remaining issues should be gone with the 9.6.6 release yesterday.
