### ISSUE TITLE
FR: Async Storage has been extracted from react-native core

### ISSUE THREAD

**Issue by Befkadu1** [firebase/firebase-js-sdk#5953]
### [REQUIRED] Describe your environment

  * Operating System version: "expo": "43.0.2" (React native)
  * Browser version: _____
  * Firebase SDK version: 9.6.5
  * Firebase Product: auth (auth, database, storage, etc)

#### Relevant Code:
AsyncStorage will be removed from  react-native core in the future release. It should be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. One of the issues is created [here](https://github.com/firebase/firebase-js-sdk/blob/e80d18d6537b2c60bcb930dad347ea35f418b0c8/packages/auth/index.rn.ts#L63)

See https://github.com/react-native-async-storage/async-storage for more information regarding AsyncStorage. Here the warning log is attached below.
![Screenshot 2022-01-30 at 02 42 54](https://user-images.githubusercontent.com/22968497/151683528-5dab2b87-bf41-42ab-9f0a-be99a4781e41.png)

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by sam-gc** [comment]
This should already be fixed in `9.6.5`: https://firebase.google.com/support/release-notes/js#version_965_-_january_27_2022

How are you initializing the SDK?

**Comment by Befkadu1** [comment]
We can solve it by importing the latest `AsyncStorage` from `@react-native-async-storage/async-storage`
```
import AsyncStorage from "@react-native-async-storage/async-storage";
....
return AsyncStorage.getItem(...args); //line 63
...
 return AsyncStorage.setItem(...args); //line 67
 ....
 return ReactNative.AsyncStorage.removeItem(...args);  //line 71
```

**Comment by sam-gc** [comment]
@Befkadu1 please try manually initializing the SDK using this function: https://github.com/firebase/firebase-js-sdk/blob/6555aa70fca3849c17d09065a9cba56f0c372932/packages/auth/src/platform_react_native/persistence/react_native.ts#L35

```js
initializeAuth(app, {
  persistence: getReactNativePersistence(/* your library */);
});
```

**Comment by Befkadu1** [comment]
@sam-gc it looks it works with this 
```
const firebaseApp = initializeApp(config);
const Firebase =  initializeAuth(firebaseApp);
```

I have no idea with this one  `persistence: getReactNativePersistence(/* your library */);` though. I would be glad if you have some kinda docs

**Comment by sam-gc** [comment]
Your snippet will not have persistence (it will just use in-memory). For example:

```js
// This is from your snippet up above:
import AsyncStorage from "@react-native-async-storage/async-storage";

import {getReactNativePersistence, initializeAuth} from 'firebase/auth/react-native';

initializeAuth(app, {
  persistence: getReactNativePersistence(AsyncStorage);
});
```

See also: https://github.com/firebase/firebase-js-sdk/issues/1847

Unfortunately we don't have any documentation about this at the moment; it's a relatively recent fix/update.

**Comment by hsubox76** [comment]
I'll look into making sure `getReactNativeLocalPersistence()` gets added to the docs. 
While we don't have that specifically yet, here's the signature for `initializeAuth()` in general, which shows how to provide persistence object(s).
https://firebase.google.com/docs/reference/js/auth.md#initializeauth

**Comment by Befkadu1** [comment]
@sam-gc Thanks a lot, it works awesome
