### ISSUE TITLE
Cannot use multiple apps with same Firebase project. FR: Allow for multiple Services IDs in Sign in with Apple in one Firebase project.

### ISSUE THREAD

**Issue by ansh** [firebase/firebase-js-sdk#5961]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 12.1
  * Browser version: React Native (using Expo Managed Project)
  * Firebase SDK version: 9.6.5
  * Firebase Product: auth (Sign in with Apple)

### [REQUIRED] Describe the problem
Firebase Auth only for one Service ID in the project (as shown below)
<img width="971" alt="CleanShot 2022-02-02 at 00 51 36@2x" src="https://user-images.githubusercontent.com/8207733/152122138-87bbf89b-4924-454a-8c29-3d5f90c259c9.png">

However, the Service ID when testing on an React Native Expo Managed project is `host.exp.Exponent` as Sign in with Apple is registered via Expo. But, it should be `com.myapp.name` instead. However, due to Firebase's limitation, I have to choose to make my app work only in testing or production, or create different apps for testing and production, which is absurd. If I don't do that I'll get the error like the one below:
<img width="929" alt="CleanShot 2022-02-02 at 00 54 47@2x" src="https://user-images.githubusercontent.com/8207733/152122604-e694f669-5ab0-4c78-8d91-3b035c57c2fc.png">

Similarly, if I have two apps, a React Web App and a React Native app and wanted to use the same Firebase project (an obvious use-case since you would want users to have the same account on web or mobile), I could simply not do that since Firebase only allows for one service ID for Sign in with Apple. 

This issue was brought up before #2854 but was shut down due to a lack of understanding from those who participated in the issue. This is not a limitation of Expo and would occur even if I was not using a managed Expo project and just pure React Native with a React Web App.

#### Steps to reproduce:
1. Create two apps, one in React and one with React Native
2. Implement Sign in with Apple following the official Firebase documentation on both
3. It won't work on both platforms simultaneously, and only on one, since they will both have to have different Service IDs

#### Relevant Code:
This code is just basic code to sign in with apple in TypeScript. It is not super relevant since this issue is on the firebase web UI and only on Firebase's side. But, I am including it just in case.
```javascript
  const signInWithApple = async () => {
    const nonce = Math.random().toString(36).substring(2, 10);

    try {
      const hashedNonce = await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, nonce);
      const appleCredential = await AppleAuthentication.signInAsync({
        requestedScopes: [
          AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
          AppleAuthentication.AppleAuthenticationScope.EMAIL
        ],
        nonce: hashedNonce
      });
      const { identityToken } = appleCredential;
      const provider = new OAuthProvider('apple.com');
      const credential = provider.credential({
        idToken: identityToken!,
        rawNonce: nonce
      });
      signInWithCredential(firebaseAuth, credential);
    } catch (error: any) { 
      Alert.alert(error.name, error.message)
    }
};
```

**Comment by jbalidiong** [comment]
Hi @ansh, thanks for this feature request. I've added this to our internal tracker (b/184875360). Based on the description, this is more of a product feature request than SDK. I highly recommend to file a ticket in the [Firebase support channel](https://firebase.google.com/support) to further check the status of this feature request.

**Comment by ansh** [comment]
Hi @jbalidiong, thank you for the quick response. I agree that this could be a feature request, but in my eyes, it is really a bug. We should be able to support multiple apps on the same Firebase project, and we can for all other Auth providers besides Apple due to this limitation.

I have not looked into the Google Cloud documentation but from what I understand Firebase just uses Google Cloud under the hood. There may be a way to add more Service IDs in Google Cloud Console? Do you know where I could begin finding this stuff? If that is the case, then this is definitely a bug. Because I can add multiple Credentials in Google Cloud for Sign in With Google!
