### ISSUE TITLE
Issue with onUpdate change object

### ISSUE THREAD

**Issue by Sbasu2512** [firebase/firebase-js-sdk#5972]
Hey, I have been having issues with onUpdate, not per se the function but the change object it receives, below is the data I am receiving
`
{"account_status":{"stringValue":"active"},"company_account":{"mapValue":{"fields":{"id":{"stringValue":"qwertsdfsdgfdwetre"}}}},"domain":{"stringValue":"shipping"}}"
`

why am I getting stringValue, mapValue? And how to remove it?

**Comment by hsubox76** [comment]
Are you referring to the `firebase-functions` trigger? https://firebase.google.com/docs/reference/functions/providers_firestore.documentbuilder.html#onupdate

If so, I think this is the repo you are looking for: https://github.com/firebase/firebase-functions
