### ISSUE TITLE
Collection group index not working in firebase emulator

### ISSUE THREAD

**Issue by Albertbol** [firebase/firebase-js-sdk#5976]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Monterey version 12.1
  * Browser version: _____
  * Firebase SDK version: 9.6.5
  * Firebase Product: firestore index

#### Steps to reproduce:
1. Create a collection with many documents (35k documents in my case), containing a field that has an array of strings in it.
2. Run array-contains-any query against this collection group to get an error and create an index from the error message for the collection group.
3. Run query against production firestore, performance is in milliseconds as it should be.
4. Run firebase firestore:indexes > ../firestore.indexes.json in firebase root folder 
5. Add  to firebase.json:
```
//firebase.json
"firestore": {
    "indexes": "firestore.indexes.json"
  },
```
6. Start firebase emulator and run query, it takes around 15 seconds in my case.
#### Relevant Code:

```
//firestore.indexes.json
{
  "indexes": [],
  "fieldOverrides": [
    {
      "collectionGroup": "allIcons",
      "fieldPath": "tags",
      "indexes": [
        {
          "order": "ASCENDING",
          "queryScope": "COLLECTION"
        },
        {
          "order": "DESCENDING",
          "queryScope": "COLLECTION"
        },
        {
          "arrayConfig": "CONTAINS",
          "queryScope": "COLLECTION"
        },
        {
          "arrayConfig": "CONTAINS",
          "queryScope": "COLLECTION_GROUP"
        }
      ]
    }
  ]
}
```

**Comment by lisajian** [comment]
Hey @Albertbol, thanks for filing the issue! Would you mind filing this in https://github.com/firebase/firebase-tools? It sounds like an issue more appropriate for that repo and we can get this in front of a more appropriate audience

**Comment by Albertbol** [comment]
Hey @lisajian 
Its done https://github.com/firebase/firebase-tools/issues/4129

**Comment by lisajian** [comment]
Thank you!
