### ISSUE TITLE
Could not reach Cloud Firestore backend after upgrading to v9, but only in some projects

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-js-sdk#5977]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 97
  * Firebase SDK version: 9.6.5
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

After upgrading to Firebase v9 from v8, I'm encountering the following error in 2 of 4 environments:

```
@firebase/firestore: Firestore (9.6.5): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

Here are the environments and results:

GCP Project ID | GCP Firestore Region | After upgrading to v9
-- | -- | --
Firebase Emulator | None (local) | Works fine
{project}-dev | us-central | Works fine
{project}-prod | us-central | Could not reach Cloud Firestore backend
{project}-prod-ca | northamerica-northeast1 | Could not reach Cloud Firestore backend

The code in all 4 environments are identical and the CI/CD pipeline for the 3 GCP projects are identical. It's particularly noteworthy that `{project}-dev` works fine while `{project}-prod` and `{project}-prod-ca` don't.

#### Steps to reproduce:

To see the results, I created these 2 test pages. They both use SDK v9:

{project}-dev: https://student-dev.examind.io/firestore
{project}-prod-ca: https://student-ca.examind.io/firestore

You will notice that `{project}-dev` loads firestore data just fine, while `{project}-prod-ca` doesn't and outputs this to the console after 10 seconds:

![image](https://user-images.githubusercontent.com/504505/152628934-2fe2b562-2617-4d4c-a9c3-87db1a699f85.png)

There are a couple of related issues (https://github.com/firebase/firebase-js-sdk/issues/5667, https://github.com/firebase/firebase-js-sdk/issues/5932), but seeing different results in different projects with the same codebase may be a unique opportunity to troubleshoot this.

#### Relevant Code:

```javascript
const query = collection(db, 'path-to-collection');
onSnapshot(query, snap => {
  console.log('Do something');
});
```

**Comment by dconeybe** [comment]
@johnnyoshika Thank you for the detailed report. This is indeed odd behavior. Would you by any chance be able to share the source code for those web pages so that I could reproduce myself? Also, would you be able to modify those pages to enable Firestore debug logging? 

Enable debug logging by calling [setLogLevel](https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel):
```js
firebase.firestore.setLogLevel('debug');
```

In the meantime, I'll look into what I can from my end.

**Comment by johnnyoshika** [comment]
@dconeybe Thanks for the follow up. I've enabled debug logging. I've also created simpler test pages so that I can share the source code.

New test pages:

https://student-dev.examind.io/firestore5 (works fine)
https://student-ca.examind.io/firestore5 (Could not reach Cloud Firestore backend)

Source (React Component):

```
import { db } from '@foo/web/dist/config/firebase'; // Configured firestore instance that comes from a shared monorepo package
import { doc, onSnapshot, setLogLevel } from 'firebase/firestore';
import { useEffect, useState } from 'react';

setLogLevel('debug');

const Firestore5 = () => {
  const [document, setDocument] = useState<any>(undefined);

  useEffect(() => {
    onSnapshot(doc(db, 'widgets', 'one'), snap => {
      if (snap.exists()) setDocument(snap.data());
    });
  }, [setDocument]);

  if (!document) return null;

  return <div>{document.name}</div>;
};

export default Firestore5;
```

I also created a version where a new Firebase app is instantiated with only Firestore enabled. The test site is here but the results are the same:

https://student-dev.examind.io/firestore6 (works fine)
https://student-ca.examind.io/firestore6 (Could not reach Cloud Firestore backend)

Source (React Component):

```
import { initializeApp } from 'firebase/app';
import {
  doc,
  getFirestore,
  onSnapshot,
  setLogLevel,
} from 'firebase/firestore';
import { useEffect, useState } from 'react';

const app = initializeApp({
  apiKey: 'redacted',
  authDomain: 'redacted',
  projectId: 'redacted',
  storageBucket: 'redacted',
  messagingSenderId: 'redacted',
  appId: 'redacted',
});

const db = getFirestore(app);

setLogLevel('debug');

const Firestore6 = () => {
  const [document, setDocument] = useState<any>(undefined);

  useEffect(() => {
    onSnapshot(doc(db, 'widgets', 'one'), snap => {
      if (snap.exists()) setDocument(snap.data());
    });
  }, [setDocument]);

  if (!document) return null;

  return <div>{document.name}</div>;
};

export default Firestore6;

```

**Comment by dconeybe** [comment]
Very interesting. I can easily reproduce with those links that you sent. Nothing obvious jumps out to me from the debug logs, which isn't too surprising since the "Could not reach Cloud Firestore backend" errors are pretty generic. Are you by chance able to generate the HTML and JavaScript with minification and obfuscation disabled? That way I could set breakpoints and step through some code.

**Comment by johnnyoshika** [comment]
@dconeybe Yes, I'll re-build with sourcemaps included. I'll let you know when it's ready.

**Comment by johnnyoshika** [comment]
@dconeybe Updated with source maps. The `firestore6` pages will be easiest to debug as they don't rely on a separate package in the monorepo.

Looking for the `Firestore/index.tsx` file in dev tools will allow you to put breakpoints in the code:

![image](https://user-images.githubusercontent.com/504505/152927609-a5c3fec5-6e2b-49c6-8083-f6aa01c8c33b.png)

**Comment by schmidt-sebastian** [comment]
Debugged this @ehsannas:

Current theory is that this has to do with AppCheck enforcement. In https://student-ca.examind.io/firestore5 we see that we open a connection (connection 1), then we get a new AppCheck token and open connection 2. We keep getting responses on connection 1 but ignore those since connection 2 is the connection we are now listening on. So there seems to be some problem with the AppCheck token refresh that we have to look into.

Does the `-dev` project use AppCheck? Do you see the same behavior with v9.6.4? We changed the AppCheck handling logic with 9.6.5

**Comment by johnnyoshika** [comment]
@schmidt-sebastian The 2 environments `-dev` and `-ca` should be identical, so AppCheck is enabled in `-dev`. Here are the AppCheck settings for both projects:

![image](https://user-images.githubusercontent.com/504505/153074529-fce56220-88a8-421c-a350-7b91ec21d5a9.png)

The codebase is also identical, but this morning an automatic deployment was triggered for `-dev` that wiped out the firestore tests pages there. They should now be fixed and you can access the test `-dev` pages again.

I just tried `v9.6.4` in `-ca`, but I'm getting a strange `Component app-check has not been registered yet` error after deploying there, so I reverted back to `v9.6.5`.

Test pages:

https://student-dev.examind.io/firestore5 (works fine)
https://student-ca.examind.io/firestore5 (Could not reach Cloud Firestore backend)

https://student-dev.examind.io/firestore6 (works fine)
https://student-ca.examind.io/firestore6 (Could not reach Cloud Firestore backend)

**Comment by johnnyoshika** [comment]
@schmidt-sebastian You may find this one other piece of information interesting. Here is another test page:

https://moderator-ca.examind.io/firestore

It uses the same Firestore backend as https://student-ca.examind.io/firestore at `northamerica-northeast1` and it works fine. It even uses the same monorepo package to configure the firestore instance (e.g. `const db = getFirestore(app)`). The only difference is that indexed DB persistence is not enabled in `moderator-ca.examind.io` while it is in `student-ca.examind.io`.

Note however, that indexed DB persistence IS enabled on `student-dev.examind.io`, so it doesn't look like the problem is isolated to offline persistence.

**Comment by johnnyoshika** [comment]
@schmidt-sebastian The most bizarre thing just happened. It was becoming a pain to run the deployment through my CI/CD pipeline with every change I'm experimenting with, so I deployed the `-ca` site manually with the Firebase CLI as follows:

```
firebase deploy --only hosting
```

Surprisingly Firestore worked when I deployed that way. Then I rolled back to a previous deployment that went through my CI/CD pipeline and once again I was faced with `Could not reach Cloud Firestore backend`.

The CI/CD pipeline I'm using is GitHub Actions and this is the action that I'm using: https://github.com/FirebaseExtended/action-hosting-deploy

Everything is hosted at Firebase, so I'm not sure if you're able to access these deployment artifacts or not:

![image](https://user-images.githubusercontent.com/504505/153140128-41596339-b7a6-4693-a472-dd644227b48f.png)

Note again that deploying the site to `-dev` using Github Actions doesn't pose any problems, so this is all still a mystery.

**Comment by johnnyoshika** [comment]
@schmidt-sebastian I'd be happy to hop in a meeting and screen share if that'll be helpful. I've been trying all kinds of different permutations to try and figure out what's happening, but I'm completely stumped. If I can't resolve this soon I fear that I'll have to take the painful steps to revert back to version 8 of the SDK.

Other things I've tried:

* Firebase Web SDK v9.5.0 (before AppCheck was introduced for Cloud Firestore) -> still the same problem
* Disabling AppCheck (i.e. removing this code: `initializeAppCheck(app, ...)` -> still the same problem

My observation is still the same: 2 almost identical projects (`-dev` and `-ca`), yet one exhibits problems while the other doesn't.

The only difference between `-dev` and `-ca` is the Firestore region. Note: we have another project with Firestore in the same region as `-dev` that exhibit the same behavior as `-ca` but I don't have the luxury to experiment with that one because we have real users there.

**Comment by johnnyoshika** [comment]
@schmidt-sebastian and team, unfortunately I had to revert my projects back to Firebase Web SDK v8. I'd still like to help you solve this problem, so all of my offers above stand. I'd also be happy to redeploy v9 into these projects for short periods at a time. I'll be watching this thread for any messages. Thanks for your help!

**Comment by schmidt-sebastian** [comment]
We will be fixing the AppCheck issue shortly. If the connection issues still persist afterwards, we can take another look at your project. Right now, we would like to reduce the noise on this reproduction and remove the additional requests issued by AppCheck.

**Comment by johnnyoshika** [comment]
@schmidt-sebastian that sounds very promising 👍

**Comment by johnnyoshika** [comment]
@schmidt-sebastian Any update on this? I'm keen to get my apps upgraded to Web SDK v9.

**Comment by jlanche** [comment]
I would like to add that this also appears to be an issue with local connections using the emulators. I'm using AngularFire but the  logs are identical to @johnnyoshika 's. I'll paste below. Frankly, I hadn't used the emulators in a while so I can't say for sure what version specifically started causing this in my setup but my current version 9.6.7 connects to production resources just fine. It's only when using the emulators that it fails.
![Screenshot 2022-02-21 143540](https://user-images.githubusercontent.com/98774415/155018910-be054262-6e3a-4dcb-9062-ed82510e2317.png)

**Comment by johnnyoshika** [comment]
@jlanche Very strange. My experience is the opposite. My apps connect to the emulator just fine and also to one of the 3 production projects, but fails on 2 of the production projects.

**Comment by jlanche** [comment]
> @jlanche Very strange. My experience is the opposite. My apps connect to the emulator just fine and also to one of the 3 production projects, but fails on 2 of the production projects.

It is odd. The only common denominator in our setups is the sdk. Unfortunately I can't downgrade at this point without downgrading both AngularFire and Angular itself which had some migration work involved. So I'm in a bit of a bind. I also tried several earlier v9 versions of the sdk but no luck.

**Comment by johnnyoshika** [comment]
@jlanche You may be running into a problem I run into often with Windows 10 and Chrome. I didn't mention this problem in this issue because it's been happening since SDK v8. Often the connector with Firestore's Emulator times out using Chrome-like browsers, which includes Edge. Have you tried using Firefox? It's much more reliable for me when using the Emulator.

Note that this doesn't seem to be a problem when using a Mac.

**Comment by schmidt-sebastian** [comment]
The AppCheck issue has been resolved. If you still have problems, please share your debug logs. It would also help if you try with `experimentalForceLongPolling` (https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Settings#experimentalforcelongpolling)

**Comment by johnnyoshika** [comment]
@schmidt-sebastian Great news, I'll try it soon. In what version of the SDK was it resolved?

**Comment by ehsannas** [comment]
The App Check fix should be in [v3.4.5](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/CHANGELOG.md#firebasefirestore)

**Comment by patrickk** [comment]
Using firebase v9.6.7 and still getting this error intermittently - wasn't [v3.4.5](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/CHANGELOG.md#firebasefirestore) included in v9.6.7 @ehsannas @schmidt-sebastian?

**Comment by voraciousdev** [comment]
Still running into this in `v9.6.8`.

**Comment by voraciousdev** [comment]
@schmidt-sebastian I am still running into this error as of `v9.6.9` in my local emulator. Things are working fine when I connect directly to my remote Firestore instance though.

**Comment by juane1000** [comment]
> @schmidt-sebastian I am still running into this error as of `v9.6.9` in my local emulator. Things are working fine when I connect directly to my remote Firestore project though.

Unfortunately, I am too as well. Latest firebase sdk "9.6.10". Works fine in production but emulators give me the error. I am also getting the "FirebaseError: Failed to get document because the client is offline." error when trying to read data. Writing seems to just not throw an error but just hangs while logging those errors shown by the OP.

**Comment by ehsannas** [comment]
@juane1000 @voraciousdev @patrickk 

I'm not able to reproduce this issue locally (although I'm on a Mac and not using AngularFire). I'm trying to better understand if there's a common usage pattern here.
- Are you all experiencing "Could not reach Cloud Firestore backend" error when **using the emulator**?
- Are you using Windows?
- Are you using AngularFire?
- Are you using SDK 9.6.9 or higher?

**Comment by juane1000** [comment]
@ehsannas 

I have done some isolated testing using the cdn sdk v9.6.10 with no framework and I can connect to the emulators. Reading data was no problem as well. This was also behind authenticated requirements.

Then I created a simple Angular project and used the vanilla sdk (9.6.10) via npm and this also worked correctly when reading data. 

Regarding my original setup, the one with the issue of the OP, I realized that the imports from AngularFire that take the configuration json objects for the individual firebase services were not changed to use the compatibility layer. And as I'm using the compatibility layer to maintain the old API, this caused a mismatch. Long Story short, it got rid of the original error of this thread. Unfortunately it lead to an permissions error that prevented the data from being retrieved. I suspect this is part of the ongoing issues the AngularFire library is working through since v9 sdk switch.

That being said, my remaining permissions error likely falls out of purview of this thread. I will go to the AngularFire repo to report this further. All seems in order with the latest sdk on my end 👍

**Comment by grabcode** [comment]
Hi everyone,

Thank you so much for this comprehensive issue report @johnnyoshika.

My company have been facing the same error yesterday as we were deploying from QA to LIVE. We have been hard at work migrating our V8 Firebase app to a fully modular V9.

In our case, that error had nothing to with Firestore itself, whether it is `experimentalAutoDetectLongPolling` or anything else.

Instead, we've realised, just a few minutes ago, that our [Segment](https://segment.com/) setup had Full Story as a destination. And for whatever wrong reason (saving either money or time or both), we didn't have the exact same setup on our QA Segment.

And when using our LIVE Segment setup and disabling the Full Story destination, our issue was gone.

We are pushing the investigation a little further as I share this report. If you have any clue as to why Firestore would be affected by a 3rd party library (FullStory) loaded by another 3rd party library (Segment).

Please note that I love what Segment and FullStory are doing. It is simply unfortunate to waste so much good time in debugging colliding dependancies.

Alex from Upflowy.com

**Comment by johnnyoshika** [comment]
> @johnnyoshika I know you mentioned that you have experienced this error in production. Is that still the case with the latest SDK (9.6.10)?

I just tried it now and I got the same error. This is with my `{project}-prod-ca` project in the `northamerica-northeast1` region:

![image](https://user-images.githubusercontent.com/504505/161339534-1d344a1e-7b43-459a-9989-254a70573033.png)

@schmidt-sebastian The original project is still there. Any thoughts?

**Comment by johnnyoshika** [comment]
Out of curiosity, I disabled AppCheck to see if it will solve the problem, but it did not.

**Comment by ehsannas** [comment]
We realized this issue has nothing to do with AppCheck. (the AppCheck fix was still an important one, and it has been released).

**Comment by ehsannas** [comment]
Unfortunately unless we have a way to reproduce this issue, there's next to no progress we can make on it.

**Comment by johnnyoshika** [comment]
@ehsannas my offer still stands. I'd be happy to screen share with you. I can even temporarily give you access to our GCP environment.

**Comment by voraciousdev** [comment]
@ehsannas I have created an example project that consistently reproduces the error for me. https://github.com/voraciousdev/firestore-connection-error

**Comment by johnnyoshika** [comment]
@ehsannas What do you think about a screenshare? We can hop on a call, I can share my screen, and show you step by step how I reproduce this problem using Firestore in the cloud. You can pick a time here in my calendar: https://examind.io/meetjohnny

**Comment by patrickk** [comment]
@ehsannas apologies, didn't see your comment until today. 

- Are you all experiencing "Could not reach Cloud Firestore backend" error when using the emulator? **No emulator**
- Are you using Windows? **Nope, mac/linux** 
- Are you using AngularFire? **Nope**
- Are you using SDK 9.6.9 or higher? **Yes**
- Would you be able to provide a minimal repository that we can clone to reproduce the issue? **Unfortunately, it's a private repo**

After some of our engineers spent days with support at SADA/Google, nothing really came to resolution. 

However,  setting `experimentalAutoDetectLongPolling` ended up working for us. 

We do have Fullstory on our app as well (saw in another comment that may have caused some issues) but for us it seemed fine.

**Comment by Applicafroguy** [comment]
I have the same issue, but the logs are identical to @johnnyoshika, since I upgraded to V9, I am using the modular.

My OS
-----------
Linux

My Project Setup
-------------------------
Angular: 13.2.1
AgularFire: 7.3.0
Firebase: 9.6.10

Problem
-----------
It works locally with no issues, everything works fine, but when I deploy it to production I get this error
`Firestore (9.6.10): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds. This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.`

What works for me
--------------------------

```
@NgModule({
       imports: [
              provideFirebaseApp(() => initializeApp(environment.firebase)),
              provideFirestore(() => {
       
             const firestoreSettings: FirestoreSettings & { useFetchStreams: boolean } = {
                  useFetchStreams: false, /* this might not be doing anything*/
                  experimentalAutoDetectLongPolling: true /* This line fixed my issue*/
             };
            const app = getApp();  // Gets current app
            const firestore = initializeFirestore(app, firestoreSettings) // not using getFirestore();
            if (environment.emulatorEnabled) {
                 connectFirestoreEmulator(firestore, 'localhost', 6500);
            }

           enableIndexedDbPersistence(firestore);
           return firestore;
          }),
       ]
))

```

**Comment by johnnyoshika** [comment]
After seeing some people mention FullStory, it made me wonder if some of our dependencies are causing this problem. We don't use FullStory, but we use LogRocket which has similar session recording capabilities. I disabled LogRocket and magically everything started working with Firebase Web SDK 9.6.10. No more `Could not reach Firestore backend` error. As soon as I enabled LogRocket again, the error came back.

So it seems that in our case, the combination of Firebase Web SDK v9+ with LogRocket is causing the Firestore error. I can't really disable LogRocket as we rely on it, so I had to roll back to Firebase Web SDK v8 for now, but it's promising to find the source (or the combination of sources) of the problem.

Any idea why FullStory or LogRocket would impact Firestore?

**Comment by Applicafroguy** [comment]
> After seeing some people mention FullStory, it made me wonder if some of our dependencies are causing this problem. We don't use FullStory, but we use LogRocket which has similar session recording capabilities. I disabled LogRocket and magically everything started working with Firebase Web SDK 9.6.10. No more `Could not reach Firestore backend` error. As soon as I enabled LogRocket again, the error came back.
> 
> So it seems that in our case, the combination of Firebase Web SDK v9+ with LogRocket is causing the Firestore error. I can't really disable LogRocket as we rely on it, so I had to roll back to Firebase Web SDK v8 for now, but it's promising to find the source (or the combination of sources) of the problem.
> 
> Any idea why FullStory or LogRocket would impact Firestore?

My project also uses LogRocket, after turning it off and removing
`experimentalAutoDetectLongPolling`
it does not work, but I need LogRocket, I could use Microsoft Clarity, but LogRocket is very reliable

**Comment by johnnyoshika** [comment]
@Applicafroguy interesting. So it's not LogRocket that's causing your problem. Note that all of my results are without `experimentalAutoDetectLongPolling`.

**Comment by Applicafroguy** [comment]
> @Applicafroguy interesting. So it's not LogRocket that's causing your problem. Note that all of my results are without `experimentalAutoDetectLongPolling`.

Yes, LogRocket is not coursing my issue.

**Comment by ehsannas** [comment]
Thanks @voraciousdev , if [this](https://github.com/voraciousdev/firestore-connection-error) is a consistent repro, that'll help with the investigation tremendously.

@johnnyoshika Thanks a lot for the offer. I'll first try David's repository to see if I can consistently reproduce it. If not, I'll get in touch to have a meeting with you.

**Comment by johnnyoshika** [comment]
I upgraded [logrocket](https://www.npmjs.com/package/logrocket) from version 2.0.0 to version 2.2.1 and the problem completely went away. So I can say confidently that the initial problem I posted (firebase v9 can't reach cloud firestore) was due to logrocket and not firebase. I'm closing this issue.

**Comment by c10r** [comment]
I'm having this same issue and I don't use logrocket at all. Any updates on the repro helping?

**Comment by johnnyoshika** [comment]
@c10r have your tried testing with all your dependencies removed? If you find that that works, you can start adding your dependencies one by one to isolate the problematic one.

**Comment by johnnyoshika** [comment]
@voraciousdev Oh I see. I had a look at your comments and it looks like your problem is different than mine. My problem was never about the emulator, except in Windows with more than 1 tab open.

**Comment by danieljpalmer** [comment]
Just chiming in to say that removing Logrocket also solved this problem on my project (9.6.5).

**Comment by johnnyoshika** [comment]
@danieljpalmer That's really interesting. What version of logrocket were you using? My problem went away when I upgraded to logrocket version 2.2.1.

**Comment by danieljpalmer** [comment]
@johnnyoshika I was on a very old version:

`nuxt-logrocket` version `0.0.3`, which was depending on `logrocket` version `1.3.0`. We haven't used Logrocket much so I almost forgot it was in our repo.

Easy fix was just to remove it, but I will try re-implementing it with everything updated next week and see if that works!

**Comment by MorenoMdz** [comment]
> @jlanche You may be running into a problem I run into often with Windows 10 and Chrome. I didn't mention this problem in this issue because it's been happening since SDK v8. Often the connector with Firestore's Emulator times out using Chrome-like browsers, which includes Edge. Have you tried using Firefox? It's much more reliable for me when using the Emulator.
> 
> Note that this doesn't seem to be a problem when using a Mac.

For context, I am having issues accessing Firestore on the emulator only when importing a bigger seed, basically starting the emulator with a clone of our prod db. If I run using my local development seed which is much smaller it works fine.

The emulator loads normally, but the UI show almost no documents, a few collections show one or two documents. The weird thing is that sometimes trying to access it via Safari instead of chrome, do load all documents, but 95% of the time it shows only the collections and not the documents.

**Comment by maxirozay** [comment]
I have this error randomly less than half of the time with firebase `9.9.0` **only when I'm signed in** (with link authentication).

**Debug log**: Connection WebChannel received error: {"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.  See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}

**Error**: @firebase/firestore: Firestore (9.9.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unauthenticated]: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

So I don't know if it is the same issue or I should open another issue but this looks like an firebase/auth issue.

**Comment by voraciousdev** [comment]
So, I just found out why I was running into this problem with the emulator specifically... 

In my local configuration, I was using the following values to initialize Firestore.

```js
connectFirestoreEmulator(
  getFirestore(),
  'http://localhost',
  4321,
  )
```

It turns out, you can't include the protocol though, so removing it finally allowed me to connect again.

```js
connectFirestoreEmulator(
  getFirestore(),
  'localhost',
  4321,
  )
```

I'm nearly positive I was using the same values in v8, so I'm thinking this might be a breaking change in v9.

**Comment by aliexalter** [comment]
```
 LOG  [DEFAULT]
 LOG  [DEFAULT]
 LOG  [2022-08-25T10:41:52.258Z]  @firebase/firestore: Firestore (9.4.1): MemoryPersistence Starting transaction: Allocate target
 LOG  [2022-08-25T10:41:52.261Z]  @firebase/firestore: Firestore (9.4.1): MemoryPersistence Starting transaction: Execute query
 LOG  [2022-08-25T10:41:52.262Z]  @firebase/firestore: Firestore (9.4.1): QueryEngine Using full collection scan to execute query: Query(target=Target(users/8yhm2cG1xxSDFnVHkuiI8W6PcEH2, orderBy: [__name__ (asc)]); limitType=F)
 LOG  [2022-08-25T10:41:52.266Z]  @firebase/firestore: Firestore (9.4.1): Connection Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel {"httpSessionIdParam":"gsessionid","initMessageHeaders":{"X-Goog-Api-Client":"gl-js/ fire/9.4.1","Content-Type":"text/plain","X-Firebase-GMPID":"1:9790000634:web:a19a11ebXXXXb47ea3f2db","Authorization":"Bearer eyJhbGciOi"},"messageUrlParams":{"database":"projects/myproject-3f750/databases/(default)"},"sendRawJson":true,"supportsCrossDomainXhr":true,"internalChannelParams":{"forwardChannelRequestTimeoutMs":600000},"forceLongPolling":false,"detectBufferingProxy":false}
 LOG  [2022-08-25T10:41:52.286Z]  @firebase/firestore: Firestore (9.4.1): Connection Opening WebChannel transport.
 LOG  [2022-08-25T10:41:52.287Z]  @firebase/firestore: Firestore (9.4.1): Connection WebChannel sending: {"database":"projects/myproject-3f750/databases/(default)","addTarget":{"documents":{"documents":["projects/myproject-3f750/databases/(default)/documents/users/8yhm2cG1xxSDFnVHkuiI8W6PcEH2"]},"targetId":8}}
 LOG  [2022-08-25T10:41:52.969Z]  @firebase/firestore: Firestore (9.4.1): Connection WebChannel transport opened.
 LOG  [2022-08-25T10:42:02.293Z]  @firebase/firestore: Firestore (9.4.1): OnlineStateTracker Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
 LOG  [2022-08-25T10:42:02.299Z]  @firebase/firestore: Firestore (9.4.1): MemoryPersistence Starting transaction: Release target
 🛑 ERROR  [FirebaseError: Failed to get document because the client is offline.]
 LOG  [DEFAULT]
 LOG  [2022-08-25T10:42:02.324Z]  @firebase/firestore: Firestore (9.4.1): Connection WebChannel sending: {"database":"projects/myproject-3f750/databases/(default)","removeTarget":8}
 LOG  [2022-08-25T10:43:02.358Z]  @firebase/firestore: Firestore (9.4.1): Connection WebChannel transport closed
 LOG  [2022-08-25T10:43:02.360Z]  @firebase/firestore: Firestore (9.4.1): PersistentStream stream callback skipped by getCloseGuardedDispatcher.

```

**Comment by aliexalter** [comment]
Same code running on ios not giving error but when run on android it give error 🤔 and error is not in code its from firebase. Run on both android simulator and device.

**Comment by 0x80** [comment]
I have been banging my head against the wall over this issue. I had upgraded several dependencies and could for the life of me not figure out where things went wrong.

Eventually I tracked it down to @chakra-ui/react@2.3. If I install 2.0 I don't get this Firebase error. 

This is of course only anecdotal evidence. I don't have the time or energy to create a reproducible example right now. I hope it helps anyway.

**Comment by AdditionAddict** [comment]
The problem is `getFirestore()` in v9's new API seems to ignore the `experimentalAutoDetectLongPolling` even if set via `provideFirebaseApp(() => initializeApp(...etc including experimentalAutoDetectLongPolling)`
Solution https://github.com/firebase/firebase-js-sdk/issues/5977#issuecomment-1093533220 worked.

**Comment by trantrungdung908** [comment]
Help me in in version: 9.6.11 i got an issue too 
![image](https://user-images.githubusercontent.com/68800136/193195566-42cfbb9c-b09e-40d5-8e53-323281a1a0d4.png)
But i got error " FirebaseError: initializeFirestore() has already been called with different options. To avoid this error, call initializeFirestore() with the same options as when it was originally called, or call getFirestore() to return the already initialized instance."

**Comment by tom-andersen** [comment]
@trantrungdung908 Could you share a repo with a reproducible problem? I would like to investigate this further, but I am having trouble recreating problem.
