### ISSUE TITLE
 ERROR in node_modules/@firebase/firestore/dist/index.d.ts:26:28 - error TS1005: ']' expected.

### ISSUE THREAD

**Issue by nikage** [firebase/firebase-js-sdk#5978]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@firebase/firestore@3.4.4` for the project I'm working on.

Google research gave me only this issue without an approved answer.
https://stackoverflow.com/questions/69952468/module-angular-fire-auth-has-no-exported-member-angularfireauth-ts2305
The only suggestion to address the issue is to use typescript 4.1.1 and higher.

I'm using typescript 4.5.5.

Here is the diff as a temporarily workaround my problem:

```diff
diff --git a/node_modules/@firebase/firestore/dist/index.d.ts b/node_modules/@firebase/firestore/dist/index.d.ts
index 6d2e565..1b8feac 100644
--- a/node_modules/@firebase/firestore/dist/index.d.ts
+++ b/node_modules/@firebase/firestore/dist/index.d.ts
@@ -24,7 +24,7 @@ export declare function addDoc<T>(reference: CollectionReference<T>, data: WithF
  * to a dot.
  */
 export declare type AddPrefixToKeys<Prefix extends string, T extends Record<string, unknown>> = {
-    [K in keyof T & string as `${Prefix}.${K}`]+?: T[K];
+    [K in keyof T & string]+?: T[K];
 };
 /**
  * Returns a special value that can be used with {@link (setDoc:1)} or {@link
```

I'm not sure what's wrong with that "**as `${Prefix}.${K}`**" expression. Any ideas?

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by FanchenBao** [comment]
I had the same issue, and the patch from @nikage worked for me. However, after I upgraded my TypeScript from `4.0.5` to `4.5.5`, the error went away. But I noticed that @nikage was already using `4.5.5`. So that is strange.

**Comment by dconeybe** [comment]
@nikage Hmm that's odd. Upgrading TypeScript to 4.5.5 should have fixed this. Could you provide a reproduction app, such as in a GitHub repository that I could clone? Then I could reproduce the issue for myself and do some more research.

**Comment by igorasilveira** [comment]
I'm also experiencing this using Typescript `@4.5.5` 😞

**Comment by dconeybe** [comment]
Could someone provide a GitHub repository that I can clone to reproduce this issue?

**Comment by igorasilveira** [comment]
@dconeybe I can actually no longer replicate. I also upgraded Typescript again, as the project itself was using a different version than global. So now with `typescript@4.5.5` it does work.

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know.

**Comment by nikage** [comment]
In my case, I discovered a subdirectory with angular project inside which uses typescript 3.9.0. So this no longer is an issue. 

Thanks for all of your support!
