### ISSUE TITLE
INTERNAL UNHANDLED ERROR:  TypeError: the given value is not a Promise

### ISSUE THREAD

**Issue by Denn-is** [firebase/firebase-js-sdk#5984]
#### ENVIRONMENT

  * Operating System version: macOS Monterey, 12.1
  * Browser version: Chrome Version 98.0.4758.80 (Official Build) (x86_64)
  * Firebase SDK version: 9.6.6
  * Firebase Product: error with Firestore (9.6.6), also using auth, storage, hosting

#### Steps to reproduce:
- UPDATE: error also appears in the hosted version, just takes a lot longer to show up [old: error occurs only in the TEST environment (yarn start), not in the hosted version (yarn build -> firebase deploy)], console output of the error ("internal unhandled error") posted below
- it's difficult to find or reproduce, because it occurs irregular (sometimes with 10 seconds, sometimes after 5 minutes), relevant code is posted below
- reloading the page does solve it (F5), it does not seem to be triggered by re-rendering pages (useEffects, ...)
- side note: used to work with v8 -> no problems, this occurred after updating to v9 (compat, ...)

#### ERROR
[2022-02-09T06:28:32.918Z]  @firebase/firestore: Firestore (9.6.6): INTERNAL UNHANDLED ERROR:  TypeError: the given value is not a Promise
    at qd.k.abort (http://localhost:3000/static/js/bundle.js:62555:20)
    at X.k.abort (http://localhost:3000/static/js/bundle.js:62730:57)
    at P (http://localhost:3000/static/js/bundle.js:61953:34)
    at M.k.cancel (http://localhost:3000/static/js/bundle.js:61919:3)
    at Ac (http://localhost:3000/static/js/bundle.js:62978:22)
    at Jd (http://localhost:3000/static/js/bundle.js:62982:3)
    at Ic (http://localhost:3000/static/js/bundle.js:62948:3)
    at Y.close (http://localhost:3000/static/js/bundle.js:63349:3)
    at Yr.Si (http://localhost:3000/static/js/bundle.js:45641:19)
    at Yr.close (http://localhost:3000/static/js/bundle.js:45445:10)

Unhandled promise rejection TypeError: the given value is not a Promise
    at qd.k.abort (fetchxmlhttpfactory.js:283:1)
    at X.k.abort (xhrio.js:794:1)
    at P (channelrequest.js:1270:1)
    at M.k.cancel (channelrequest.js:1115:1)
    at Ac (webchannelbase.js:794:1)
    at Jd (webchannelbase.js:808:1)
    at Ic (webchannelbase.js:708:1)
    at Y.close (webchannelbasetransport.js:214:1)
    at Yr.Si (index.esm2017.js:10868:1)
    at Yr.close (index.esm2017.js:10687:1)

#### Relevant CODE:
assuming it is a problem with a snapshot listener:
```
  useEffect(() => {
    console.log("useEffect from Items");
    onSnapshot(collection(firestore, "items"), (snapshot) =>
      setItemsAll(snapshot.docs.map((doc) => doc.data()) as IItem[])
    );
  }, []);
```

assuming it is an update problem:
```
firestore
      .collection("items")
      .doc(item.identifiers.id)
      .update({
        ["userSelections"]: itemHere.userSelections,
      })
      .catch((err) => console.log(err));
```

assuming it is a set problem:
```
export default function ServiceOneDocSetToFS<T>(
  collection: string,
  docId: string,
  data: IItem | ISelectionsInUser | IUserProfileAndSettings | IDomain
): Promise<void> {
  return firestore.collection(collection).doc(docId).set(data);
  // .then(() => {
  //   console.log("Document successfully written!");
  // })
  // .catch((error) => {
  //   console.error("Error writing document: ", error);
  // });
}
```

assuming it is some problem with the config (tried both "old" and "new" imports, problem occurs in both):
```
// imports old
import firebase from "firebase/compat/app";
import "firebase/compat/auth";
import "firebase/compat/firestore";
import "firebase/compat/storage";

// import { initializeApp } from "firebase/app";
// import { getAnalytics } from "firebase/analytics";
// import { getAuth, onAuthStateChanged } from "firebase/auth";
// import { getStorage } from "firebase/storage";
// import { getFirestore } from "firebase/firestore";
// https://firebase.google.com/docs/web/setup#available-libraries

const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_KEY,
  authDomain: process.env.REACT_APP_FIREBASE_DOMAIN,
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_FIREBASE_SENDER_ID,
  appId: process.env.REACT_APP_FIREBASE_APP_ID,
};

// Initialize Firebase
// export const firebaseApp = initializeApp(firebaseConfig);
// export const analytics = getAnalytics(firebaseApp);
// export const storage = getStorage(firebaseApp);
// export const auth = getAuth(firebaseApp);
// export const firestore = getFirestore();

// Initialize Firebase old
const app = firebase.initializeApp(firebaseConfig);

// Exports old
export const auth = app.auth() as firebase.auth.Auth;
export const storage = firebase.storage() as firebase.storage.Storage;
export const firestore = firebase.firestore() as firebase.firestore.Firestore;
export { app };
export { firebase };
```

**Comment by schmidt-sebastian** [comment]
Thank you for filing this issue. I think it will be tough for us to solve this issue. We might need a small reproduction that makes this problem reproducible. The error itself is thrown by Chrome's JS engine: https://github.com/chromium/chromium/blob/64a0458a0463e616d5a37dbab9763fc6ab6d3e91/third_party/blink/renderer/bindings/core/v8/script_promise.cc#L219

If you are able to create a small sample app then we can take another look. I will also contact the WebChannel team to see if they have encountered this before.

**Comment by schmidt-sebastian** [comment]
Internal bug: b/218892492

**Comment by schmidt-sebastian** [comment]
Do you not see this problem if you do not include the Storage SDK?

**Comment by Denn-is** [comment]
Exactly!
