### ISSUE TITLE
Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker

### ISSUE THREAD

**Issue by daedwards767** [firebase/firebase-js-sdk#6013]
[REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home 19043.1526
  * Browser version: 98.0.4758.82 (Official Build) (64-bit)
  * Firebase SDK version: ^9.0.0-beta.1
  * Firebase Product: messaging

[REQUIRED] Describe the problem
Calling messaging getToken sometimes throws the error: `Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker`

This occurs when a user has not yet registered the service worker i.e. it is their first visit to the web app or their first usage of a feature that involves the use of the service worker -> since getToken does not register the SW until that point.

It seems there may be a race condition where the service worker may or may not be ready when  
`const subscription = await swRegistration.pushManager.getSubscription();` is called here https://github.com/firebase/firebase-js-sdk/blob/f5a17143b1930b7b7b45d431ad21f50b236e4f80/packages/messaging/src/internals/token-manager.ts#L159

Other online sources here https://stackoverflow.com/questions/42063006/failed-to-subscribe-the-user-domexception-subscription-failed-no-active-serv and here https://github.com/bradtraversy/node_push_notifications/issues/1#issuecomment-389413687 seem to solve this issue with the line `await navigator.serviceWorker.ready;` to wait for the service worker to be ready, 

This may be connected to issue 5797 here https://github.com/firebase/firebase-js-sdk/issues/5797.

#### Steps to reproduce:

Caveat: in most cases the steps below will not trigger the issue, it will only occur when the service worker is not ready

1. Clear cache & remove notification permission
2. Add firebase-messaging-sw.js to root of domain
3. Call firebase initializeApp
4. Call firebase getMessaging
5. Ask and approve browser notification permission
6. Add firebase onMessage listener
7. Call firebase await getToken(messaging, { vapidKey: <VAPID_KEY> })

#### Relevant Code:

```javascript
const supported = await isSupported()
  if (!supported) {
      throw new Error(NOTIFICATIONS_NOT_SUPPORTED)
  }
  const messaging = getMessaging();
  const messagingToken = await getToken(messaging, {vapidKey})
```

**Comment by jbalidiong** [comment]
Hi @daedwards767, thanks for reaching out. We'll try to investigate this and see what we can find.

**Comment by jbalidiong** [comment]
I tried replicating and I wasn't able to reproduce the same behavior. I noticed that you are using an outdated SDK version, would you mind trying it out with the version 9.6.7 which is the latest for the official release. Would you mind trying to update the SDK version that you're using and see if the issue persists? If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.
