### ISSUE TITLE
Firebase `getAnalytics()` throws `Error: Component analytics has not been registered yet`

### ISSUE THREAD

**Issue by ky28059** [firebase/firebase-js-sdk#6019]
### Describe your environment

  * Operating System version: Windows 10 20H2
  * Browser version: Chrome 98.0.4758.102
  * Firebase SDK version: 9.6.7
  * Firebase Product: analytics

### Describe the problem

In a NextJS app, attempting to create an `Analytics` object with `getAnalytics(FirebaseApp)` throws `Error: Component analytics has not been registered yet`. Strangely, the other SDKs being used (auth, functions, firestore) function as expected; only analytics throws this unregistered error.

![image](https://user-images.githubusercontent.com/60120929/154779146-81b93091-a2ee-4dd2-a082-37816f178972.png)

Logging the value of `firebase._container.providers.get()` for a non-affected SDK (in this case, functions) shows that the component has registered properly, but for analytics the component is `null`.

<img src="https://user-images.githubusercontent.com/60120929/154779277-6f85b985-97bf-448a-9929-9c36f4f275e8.png" height="700px"> <img src="https://user-images.githubusercontent.com/60120929/154779304-85b73300-6b57-4ab6-aeab-e84ddb2b36ba.png" height="700px">

#### Steps to reproduce:

Create a new NextJS project with reactfire and the Firebase SDKs, then attempt to create an analytics provider in `npm run dev`.
The code I am attempting to execute:
```tsx
import {ReactNode} from 'react';
import { useFirebaseApp, useInitFirestore, AuthProvider, FunctionsProvider, FirestoreProvider, AnalyticsProvider } from 'reactfire';
import { getFirestore, initializeFirestore, enableIndexedDbPersistence, connectFirestoreEmulator } from 'firebase/firestore';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator } from 'firebase/functions';
import { getAnalytics } from 'firebase/analytics';


export default function FirebaseProviders(props: {children: ReactNode}) {
    const firebase = useFirebaseApp();

    // Initialize SDKs
    const auth = getAuth(firebase);
    const functions = getFunctions(firebase);
    const analytics = getAnalytics(firebase);
    const firestore = getFirestore(firebase);

    // Set up emulators on dev build
    if (process.env.NODE_ENV !== 'production') {
        connectAuthEmulator(auth, 'http://localhost:9099');
        connectFunctionsEmulator(functions, 'localhost', 5001);
        connectFirestoreEmulator(firestore, 'localhost', 8080);
    }

    return (
        <AuthProvider sdk={auth}>
            <FunctionsProvider sdk={functions}>
                <FirestoreProvider sdk={firestore}>
                    <AnalyticsProvider sdk={analytics}>
                        {props.children}
                    </AnalyticsProvider>
                </FirestoreProvider>
            </FunctionsProvider>
        </AuthProvider>
    )
}
```
which is rendered within `_app.tsx` like so:
```tsx
import {AppProps} from 'next/app';
import {FirebaseAppProvider} from 'reactfire';
import FirebaseProviders from '../components/firebase/FirebaseProviders';
import {fbconfig} from '../firebase/config';


export default function App({ Component, pageProps }: AppProps) {
    // ...

    return (
        <FirebaseAppProvider firebaseConfig={fbconfig}>
            <FirebaseProviders>
                {/* ... */}
            </FirebaseProviders>
        </FirebaseAppProvider>
    );
}
```

**Comment by hsubox76** [comment]
1) Does this error happen if reactfire is not part of the app?
2) Is there an earlier version of Firebase where the error doesn't happen?

**Comment by Jbz797** [comment]
Same problem with AngularFire, need to come back to 9.6.6 to make it work.

**Comment by ky28059** [comment]
![image](https://user-images.githubusercontent.com/60120929/154813531-07ba6684-b9e6-4859-82af-b09675cd1fe8.png)

Interestingly enough, for me reverting to `9.6.6` instead gives `Component auth has not been registered yet`.

**Comment by erikmetzinfo** [comment]
Same issue here, but on my end it is also with function, app-check and storage.
auth and firestore is working

"firebase": "^9.6.6"
"reactfire": "^4.2.1"

```
export const FirebaseProvider = ({ children }: { children: JSX.Element }): JSX.Element => {
  const firebaseConfigEnv = process.env.NEXT_PUBLIC_FB_CONFIG;

  return (
    <FirebaseAppProvider firebaseConfig={firebaseConfig}>
      {children}
    </FirebaseAppProvider>
  );
};
```
`const app = useFirebaseApp();`
`const functions = getFunctions(app)`
 --> Uncaught Error: Service functions is not available

`const appCheck = initializeAppCheck(app, {provider: new ReCaptchaV3Provider(process.env.NEXT_PUBLIC_FB_APP_CHECK_PUBLIC_KEY), isTokenAutoRefreshEnabled: true,});`
 --> Error: Component app-check has not been registered yet

`const storage = getStorage(app)`
 --> Error: Service storage is not available

**Comment by erikmetzinfo** [comment]
Quickfix for me was uninstalling firebase package and re-installing, works for local and production.

**Comment by MaciejCaputa** [comment]
> Quickfix for me was uninstalling firebase package and re-installing, works for local and production.

I also tried that, any multiple combinations of reactfire and firebase versions. Does somebody have an idea how to fix it?

**Comment by hsubox76** [comment]
Has anyone reported this issue in the [reactfire repo](https://github.com/FirebaseExtended/reactfire/issues)? They may be able to pinpoint the issue better. If anyone is experiencing the same issue in an app that is not using reactfire, feel free to update in this thread.

**Comment by hosseini44444** [comment]
This is how I resolved the issue:

```tsx
import { useCallback } from 'react';
import { getAnalytics } from 'firebase/analytics';
import { useInitAnalytics, AnalyticsProvider } from 'reactfire';

interface Props {
    children: JSX.Element;
}

export const Provider = ({ children }: Props) => {
    const { status, data: analytics } = useInitAnalytics(async (app) => {
        const analytics = getAnalytics(app);
        return analytics;
    });

    const FbAnalyticsProvider = useCallback(
        ({ children }: Props) =>
            status === 'success' ? (
                <AnalyticsProvider sdk={analytics}>
                    {children}
                </AnalyticsProvider>
            ) : (
                children
            ),
        [status, analytics],
    );

    return <FbAnalyticsProvider>{children}</FbAnalyticsProvider>;
};
```

**Comment by bageren** [comment]
Same issue here with Angular. Using  firebase 9.8.0 and @angular/fire 7.3.0. So far I've only seen Functions throwing this error.

**Comment by bageren** [comment]
@hsubox76 Thanks, it seems to be working for me now. I had already tried deleting node_modules, so I guess it was deleting my yarn.lock that did the trick.

**Comment by hsubox76** [comment]
I'm going to close this but if anyone is still having problems that the above suggestions do not fix, let me know and I will reopen it.
