### ISSUE TITLE
Upgrading firebase causes cryptic, optimized error to be raised with same code

### ISSUE THREAD

**Issue by fxfactorial** [firebase/firebase-js-sdk#602]
I tried bumping my firebase js-sdk from `4.11.0` to `4.12.0` but now I get this error in the browser when this code runs: 

<img width="964" alt="screen shot 2018-03-28 at 2 20 49 pm" src="https://user-images.githubusercontent.com/3036816/38057165-61740142-3293-11e8-9da1-d5adc414b897.png">

```js
import * as firebase from 'firebase';
const config = {...}
if (!firebase.apps.length) {
  firebase.initializeApp(config);
}
```

thanks, also how can I get non google closure optimized firebase?

**Comment by jshcrowthe** [comment]
Hey @fxfactorial, I have tried to reproduce this behavior and did not see the issue you mentioned. Can you create a full reproduction of the issue that I can look at?

**Comment by fxfactorial** [comment]
@jshcrowthe I think i figured it out, i think this craps out on `.webStorageSupport` and i think that is because I tried using firebase auth in an incognito mode browser. 

I'm not sure if docs or someone should mention firebase auth and when browser is incognito
