### ISSUE TITLE
enableIndexedDbPersistence does not existing in firebase/firestore/lite

### ISSUE THREAD

**Issue by JonathanMSifleet** [firebase/firebase-js-sdk#6022]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11 Insider build 22557.1
  * Browser version: Chrome 98.0.4758.102
  * Firebase SDK version: 9.6.7
  * Firebase Product: Firestore database

### [REQUIRED] Describe the problem
[Firestore documentation](https://firebase.google.com/docs/firestore/solutions/firestore-lite#import_firestore_lite) code example includes 'enableIndexedDbPersistence' as a method that can be imported from "firebase/firestore/lite", but the documentation states that you cannot use that feature, so the code example must be outdated. This may well be the wrong place to raise an issue such as this but I'm not sure where to do that. 

#### Steps to reproduce:
Import 'enableIndexedDbPersistence' from 'firebase/firestore/lite'.

#### Relevant Code:

```javascript
import { enableIndexedDbPersistence, getFirestore } from 'firebase/firestore/lite';

//  enableIndexedDbPersistence not found in 'firebase/firestore/lite'
```

**Comment by jbalidiong** [comment]
Hi @JonathanMSifleet, thanks for the report. I was able to reproduce the behavior now. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by jbalidiong** [comment]
Just an update, this is working as intended. For size and speed, Firestore Lite omits these features from the standard Firestore SDK and persistence helpers like enableIndexedDBPersistence are not included. You can check our [documentation](https://firebase.google.com/docs/firestore/solutions/firestore-lite#api_features_not_supported_by_firestore_lite) to know more of the features omitted in Firestore Lite.

**Comment by JonathanMSifleet** [comment]
The issue wasn't that it's not included, its that the documentation should have it removed from the 'lite' example

**Comment by jbalidiong** [comment]
We've updated our document snippet to prevent developers from getting confuse and receive the same error.
