### ISSUE TITLE
Firestore onSnapshot not working 

### ISSUE THREAD

**Issue by shaponpal6** [firebase/firebase-js-sdk#6023]
Firestore onSnapshot not working anyway. I try several way and try to catch error but this function not triggering. I m using react now.

```
import { getFirestore, collection, doc, query, where, onSnapshot } from "firebase/firestore";
    const unsub = onSnapshot(doc(getFirestore(), "chatUsers", "IHKwwvl9TFMF8LDOF7G2sNBvA5t1"), (doc) => {
            console.log("Current data: ", doc.data());
    });
    unsub()
    const q = collection(getFirestore(), "chatUsers");
    console.log('qqqq :>> ', q);
    const unsubscribe = onSnapshot(q, { includeMetadataChanges: true }, (snapshot) => {
      console.log('snapshot :>> ', snapshot);
      snapshot.docChanges().forEach((change) => {
        console.log('change :>> ', change);
        if (change.type === "added") {
            console.log("New city: ", change.doc.data());
        }
        if (change.type === "modified") {
            console.log("Modified city: ", change.doc.data());
        }
        if (change.type === "removed") {
            console.log("Removed city: ", change.doc.data());
        }
      });
    }, (error) => {
      console.log('error :>> ', error);
    });
    unsubscribe();
```

**Comment by ehsannas** [comment]
@shaponpal6 Can you please be more specific about 
  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Specify which part of your code is not working and in what way?
  * Are you properly connected to Firestore? (e.g. does `getDoc` work?)
  * Include logs from your browser's developer console.
  * Enable [debug log](https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel) messages and include those.

Thanks

**Comment by ehsannas** [comment]
@Aoyetibo557 Can you please provide details about how to reproduce the issue?

Simply following the instructions here https://firebase.google.com/docs/firestore/query-data/listen works fine when using `onSnapshot`.

If you are using Firestore with React, I recommend checking out https://github.com/FirebaseExtended/reactfire

**Comment by marcelgundermann** [comment]
Hey @ehsannas I've created a Stackblitz with the error above: https://stackblitz.com/edit/bug6023-firebase-js-sdk?file=src%2FApp.tsx&terminal=dev

```
import { useEffect } from 'react';
import './App.css';
import { onSnapshot, setLogLevel } from 'firebase/firestore';
import { firestore, fooColl } from '../firebase';
import { doc, getDoc } from 'firebase/firestore/lite';

setLogLevel('debug');

function App() {
  const fetchDoc = async (): Promise<void> => {
    const docRef = doc(fooColl, 'bar');
    const document = await getDoc(docRef);
    console.log(document.data());
  };

  useEffect(() => {
    // Get data once is working
    fetchDoc();

    // Error
    onSnapshot(doc(firestore, 'foo', 'bar'), (snapshot) => {
      console.log(snapshot);
    });
  });

  return <div>Foo</div>;
}

export default App;
```


Error in console:
```
Uncaught FirebaseError: Expected type 'dc2', but it was: a custom an object
```


Operating System version: macOS Monterey 12.3 
Browser version: 100.0.4896.60 (arm64)
Firebase SDK version: 9.6.10

**Comment by marcelgundermann** [comment]
Ok.. got it. The error `Uncaught FirebaseError: Expected type 'dc2', but it was: a custom an object` appears if you **mix** the imports `firebase/firestore/lite` and `firebase/firestore`.

@shaponpal6 @Aoyetibo557 Correct your firebase imports in your project, after that everything should work as expected.
