### ISSUE TITLE
Error on OEM Android 7 running Chrome 51

### ISSUE THREAD

**Issue by jacobg** [firebase/firebase-js-sdk#6034]
In the Android emulator running Android 7 with Chrome 51 (OEM), the firebase js sdk throws an error:
`Uncaught SyntaxError: Unexpected token function`

It's somewhere on the following line of the webpack bundle:
```javascript
 function getRemoteConfig(r=Object(u["d"])()){r=Object(d["g"])(r);const a=Object(u["b"])(r,b);return a.getImmediate()}async function activate(r){const a=Object(d["g"])(r),[o,l]=await Promise.all([a._storage.getLastSuccessfulFetchResponse(),a._storage.getActiveConfigEtag()]);return!!(o&&o.config&&o.eTag&&o.eTag!==l)&&(await Promise.all([a._storageCache.setActiveConfig(o.config),a._storage.setActiveConfigEtag(o.eTag)]),!0)}function ensureInitialized(r){const a=Object(d["g"])(r);return a._initializePromise||(a._initializePromise=a._storageCache.loadFromStorage().then(()=>{a._isInitializationComplete=!0})),a._initializePromise}async function fetchConfig(r){const a=Object(d["g"])(r),o=new RemoteConfigAbortSignal;setTimeout(async()=>{o.abort()},a.settings.fetchTimeoutMillis);try{await a._client.fetch({cacheMaxAgeMillis:a.settings.minimumFetchIntervalMillis,signal:o}),await a._storageCache.setLastFetchStatus("success")}catch(l){const r=hasErrorCode(l,"fetch-throttle")?"throttle":"failure";throw await a._storageCache.setLastFetchStatus(r),l}}function getBoolean(r,a){return getValue(Object(d["g"])(r),a).asBoolean()}function getNumber(r,a){return getValue(Object(d["g"])(r),a).asNumber()}function getString(r,a){return getValue(Object(d["g"])(r),a).asString()}function getValue(r,a){const o=Object(d["g"])(r);o._isInitializationComplete||o._logger.debug(`A value was requested for key "${a}" before SDK initialization completed. Await on ensureInitialized if the intent was to get a previously activated value.`);const l=o._storageCache.getActiveConfig();return l&&void 0!==l[a]?new Value("remote",l[a]):o.defaultConfig&&void 0!==o.defaultConfig[a]?new Value("default",String(o.defaultConfig[a])):(o._logger.debug(`Returning static value for key "${a}". Define a default or remote value if this is unintentional.`),new Value("static"))}
```

The `.browserslistrc` is set to:
```
iOS >= 11
ChromeAndroid >= 44
Chrome >= 44

[development]
last 1 chrome version
```

**Comment by jacobg** [comment]
If `firebase` and `@firebase` are configured in webpack as dependencies needing to be transpiled, then it resolve this issue. Using vue.js, that means adding the following to `vue.config.js`:
```
  transpileDependencies: [
    'firebase',
    '@firebase'
  ],
```

**Comment by jbalidiong** [comment]
Hi @jacobg, thanks for reaching out. A reproducible example would be ideal, but in the meantime, could you share a few more details?

**Comment by jacobg** [comment]
Hi @jbalidiong, Well the published firebase javascript assets contain async-await syntax, was introduced in Chrome 55. Android 7 ships with Chrome 51, so if the user hasn't updated Chrome (and I actually have customers who haven't), then it will fail. I was able to work around it by transpiling it on my own. You may want to either transpile it in the original package, or make it more clear to your users what is the minimum requirement.

**Comment by jbalidiong** [comment]
Please share a minimal, but complete sample of a project that I can run locally. If I can replicate the issue, I can have a better look into it.

**Comment by jacobg** [comment]
I have a workaround for it, so I don't feel pressed to spend much more time on this. I'm not quite sure what you need a sample from me for. It's not like a particular use case that repros this. You can just take any application using firebase js, and run it in Chrome 55.

**Comment by hsubox76** [comment]
In version 9 we moved to providing esm2017 bundles as the default. ESM 5 bundles are still available, but you need to configure your bundler to prioritize the "esm5" field in package.json above "browser", "main", etc. In webpack I think this is still done with [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields). I think we may want to add this info to the [Supported Environments page](https://firebase.google.com/docs/web/environments-js-sdk).
