### ISSUE TITLE
signInWithRedirect fails to throw "auth/account-exists-with-different-credential"

### ISSUE THREAD

**Issue by joseph1125** [firebase/firebase-js-sdk#6051]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 15.3.1
  * Browser version: Safari 15.3.1
  * Firebase SDK version: 9.6.7
  * Firebase Product: auth

### [REQUIRED] Describe the problem
signInWithRedirect fails to throw "auth/account-exists-with-different-credential" error when user chooses to login via facebook / apple
#### Steps to reproduce:
- User clicks the "sign in with facebook" button
- Login via an email that is already registered via a different provider
- Firebase redirect back to app login page without any error being thrown
#### Relevant Code:

```javascript
try {
      const { signInWithRedirect, getRedirectResult } = await import(
        "@firebase/auth"
      );
      await signInWithRedirect(auth, provider);
      const result = await getRedirectResult(auth);
} catch (error) {
      console.error(error);
     // no error message is shown
}
```

**Comment by sam-gc** [comment]
Which other provider is the email associated with?

**Comment by jakemccloskey** [comment]
I've experienced this issue when the user is associated with the password provider and then tries to login via microsoft with the same email.

**Comment by joseph1125** [comment]
@sam-gc I've experienced in both FacebookProvider and Apple Provider

**Comment by sam-gc** [comment]
@jakemccloskey, this is likely working as intended: if the email/password account **is not verified**, then when someone signs in with a Microsoft account with that same email, the Microsoft account is taken to be the source of truth and overwrites the email/password account.

@joseph1125 this is rather odd -- do you have the multiple accounts per email option set on the account?

**Comment by sam-gc** [comment]
More information about this phenomenon can be found here: https://firebase.google.com/docs/auth/users#verified_email_addresses

**Comment by jakemccloskey** [comment]
@sam-gc Thanks for the response. The problem I faced is that the behavior you described is not happening. The Microsoft account is not overwriting the email/password account and it's also not throwing an error. Happy to create a separate issue if you think this is unrelated.

**Comment by joseph1125** [comment]
> @jakemccloskey, this is likely working as intended: if the email/password account **is not verified**, then when someone signs in with a Microsoft account with that same email, the Microsoft account is taken to be the source of truth and overwrites the email/password account.
> 
> @joseph1125 this is rather odd -- do you have the multiple accounts per email option set on the account?

It was set as "prevent creation of multiple accounts with the same email address". However, the error will be thrown if I changed to use siginInWithPopup, so that I can alert user to change back to the original provider to login.

After I asked the user, turns out the email the users use is gmail.com, it should be assigned as GoogleProvider

**Comment by sam-gc** [comment]
I'm unable to reproduce this. Would you mind checking the network request you would expect to see fail with this error? It would be to the endpoint `signInWithIdp`. Specifically, in the response, look for a field called `needConfirmation`. If that field is present, the SDK should error. If it's not present, something else is going on that's unrelated to the SDK. (For more context, see the docs for the REST endpoint: https://cloud.google.com/identity-platform/docs/use-rest-api#section-sign-in-with-oauth-credential)

**Comment by joseph1125** [comment]
> I'm unable to reproduce this. Would you mind checking the network request you would expect to see fail with this error? It would be to the endpoint `signInWithIdp`. Specifically, in the response, look for a field called `needConfirmation`. If that field is present, the SDK should error. If it's not present, something else is going on that's unrelated to the SDK. (For more context, see the docs for the REST endpoint: https://cloud.google.com/identity-platform/docs/use-rest-api#section-sign-in-with-oauth-credential)

The needConfirmation is present and the value is true, however, no error is thrown

**Comment by sam-gc** [comment]
Unfortunately with these conditions (email first, followed by Facebook) I can't reproduce this. Do you see this issue on other browsers or only iOS/Safari?

**Comment by joseph1125** [comment]
only on iOS and safari, never mind, I may have found a way to workaround this issue

**Comment by joseph1125** [comment]
unfortunately, the workaround is not working

**Comment by joseph1125** [comment]
I just double checked, confirmed iOS Safari and Android Chrome also suffers the same issue

**Comment by sam-gc** [comment]
@joseph1125, thanks for the updates. I'm unable to reproduce this issue still. One thing I want to double check -- are you calling `getRedirectResult()` _after_ the redirect completes? From your code snippet, it's called directly after you call `signInWithRedirect()`. In that code snippet, the following line will never be called. Instead, you need to follow a pattern like:

```js
function onSignInClick() {
  signInWithRedirect(auth, new FacebookAuthProvider());
}

async function onPageLoad() {
  try {
    const resultOrNull = await getRedirectResult(auth);
  } catch (e) {
    console.log(e);
  }
}
```

In other words, the `getRedirectResult()` call needs to be on a separate code path

**Comment by joseph1125** [comment]
> @joseph1125, thanks for the updates. I'm unable to reproduce this issue still. One thing I want to double check -- are you calling `getRedirectResult()` _after_ the redirect completes? From your code snippet, it's called directly after you call `signInWithRedirect()`. In that code snippet, the following line will never be called. Instead, you need to follow a pattern like:
> 
> ```js
> function onSignInClick() {
>   signInWithRedirect(auth, new FacebookAuthProvider());
> }
> 
> async function onPageLoad() {
>   try {
>     const resultOrNull = await getRedirectResult(auth);
>   } catch (e) {
>     console.log(e);
>   }
> }
> ```
> 
> In other words, the `getRedirectResult()` call needs to be on a separate code path

Confirmed, I called the `await getRedirectResult(auth)` on page mount
By The Way, I fixed my workaround and now it is working.
