### ISSUE TITLE
linkWithCredential returns TypeError: credential._linkToIdToken is not a function

### ISSUE THREAD

**Issue by ookil** [firebase/firebase-js-sdk#6053]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Monterey 12.1
  * Browser version: Chrome
  * Firebase SDK version: 9.6.7
  * Firebase Product: auth

#### Steps to reproduce:
 Trying to follow linking multiple providers to one account but there's problem with `linkWithCredential`

#### Relevant Code:
I'm storing credentials like so: 
```javascript
const credential = OAuthProvider.credentialFromError(error);
sessionStorage.setItem('credential', JSON.stringify(credential));
```
Then when I try to use:
```javascript
const credential = OAuthProvider.credentialFromJSON(sessionStorage.getItem('credential'));
linkWithCredential(authUser, credential);
```
I get:
```javascript
TypeError: credential._linkToIdToken is not a function
    at _link$1 (link_unlink.ts:66:1)
    at async handleLinkAccounts (index.tsx:223:1)
    at async index.tsx:252:1
```

**Comment by FSL89** [comment]
Hi,

I'm not sure if this helps your case, but I just had a similar experience with linkWithCredential(auth.currentUser, credential).

What I did was creating a new AuthCredential by using the AuthProvider.credential() function.

My example:
`const pending = await FacebookAuthProvider.credential(credenial.value.accessToken)`
Notice that I only used the accessToken from the credential object. After that, I could use the linkWithCredential function without the mentioned error.

`const link = await linkWithCredential(auth.currentUser, pending)`

**Comment by sam-gc** [comment]
@ookil I'm unable to reproduce this. Have you verified that the credential returned from `OAuthProvider.credentialFromError` is populated (not null)? Similarly when you call `credentialFromJSON`, does `credential` end up containing the right information?

**Comment by ookil** [comment]
@FSL89 it was giving me the same problem
@sam-gc it was populated in both cases. But I was able to solve this. Looks like the problem comes from stringifying the `credential`, because when I stringify whole `error` and then parse it and use `credentialFromError` everything works as supposed.
