### ISSUE TITLE
Function WriteBatch.set() called with invalid data. Unsupported field value: a custom object (Reference type)

### ISSUE THREAD

**Issue by hoangdevelopers** [firebase/firebase-js-sdk#6057]
Unable to add the Reference type class of the SDK for the browser to firestore.

Steps
```
import firebase from "firebase/app";  
const app = firebase.initializeApp({});
 const firestore = app.firestore(); 
const batch = firestore.batch(); 
batch.update(orderRef, {
 userId: firestore.doc(userId),
});
```
this is my code
https://gist.github.com/hoangdevelopers/3339090aeb24d4b484456945d75df008
https://gist.github.com/hoangdevelopers/69b8ba34ece959d17a080b6f2e35f16b
then I got exception "Function WriteBatch.set() called with invalid data. Unsupported field value: a custom object"

**Comment by hoangdevelopers** [comment]
[](https://stackoverflow.com/posts/71406230/timeline)0


I don't know why batch validate input should be a pure object. I tried to push reference type id inside nested object then it work well, yeah I know it already is a trick, but it works.

change:

```
batch.update(docRef, {
  user: firestore.collection('users').doc(userId)
})
```

to:

```
batch.update(docRef, {
  user: {
    id: firestore.collection('users').doc(userId)
  }
})
```

**Comment by dconeybe** [comment]
@hoangdevelopers I'm not able to reproduce the issue you are experiencing. 

Could you confirm the version of the Firebase SDK that you are using?

Also, is there a stack trace or any additional information you can provide about the error?

Finally, are you able to write a small app that I could use to reproduce? If not, that's okay and I'll do my best but if you can that would be very helpful.
