### ISSUE TITLE
Couldn't getToken firebase version 9 React/Next JS

### ISSUE THREAD

**Issue by dasrajan** [firebase/firebase-js-sdk#6063]
Environment

  * Operating System version: mac OS
  * Browser version: Chome 99.04
  * Firebase SDK version: 9.6.8
  * Firebase Product: getToken/ messaging
  * React JS , Next JS

Version 9.6.8
**Couldn't get token from getToken**

Error on API while requesting token

POST https://firebaseinstallations.googleapis.com/v1/projects/{project_id}/installations 400

FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument." (installations/request-failed).

i was implementing firebase messaging with ver 9 and always throws the same error irrespective of whatever browser is being used 

#### Relevant Code:

` Notification.requestPermission()
    .then((res: any) => {
        getToken(messaging,{ vapidKey: process.env.FIREBASE_VAPID })
            .then((firebaseToken: any) => {
                resolve(firebaseToken)
            })
    })
    .catch((err: any) => {
        reject(err);
    });`

**Comment by jbalidiong** [comment]
Hi @dasrajan, thanks for the report. I tried replicating, but I wasn't able to reproduce the error. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

For a guide, here is the snippet that I used:

```
//requesting notification permission from browser
          const status = await Notification.requestPermission()
          console.log(status)
          if (status === 'granted') {
            //getting token from FCM
            const fcm_token = await getToken( messaging, {
              vapidKey: 'VAPID_KEY'
            })
            if (fcm_token) {
              console.log('fcm token', fcm_token)
              //return the FCM token after saving it
              return fcm_token
            }
          }
```

**Comment by dasrajan** [comment]
Hello @jbalidiong  thanks for the response, i tried to use your snippet too. it turns out that it works on development environment but not on localhost as it is not in https.

giving error 
Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument.

**Comment by hsubox76** [comment]
What is the body of the failed POST request?

**Comment by dasrajan** [comment]
> What is the body of the failed POST request?

Request URL => https://firebaseinstallations.googleapis.com/v1/projects/{project_id}/installations
Payload =>
{
"fid":FID,
"authVersion":"FIS_v2",
"appId":APPID,
"sdkVersion":"w:0.5.5"
}

**Comment by maniflames** [comment]
I'm not sure if it's better to open a new issue or slide in here but I am running into a very similar issue. All my credentials are 100% correct as they are now just copied from the console and pasted into place without any additional quote marks or whitespace but no matter the browser I receive an auth error. 

`FirebaseError: Installations: Create Installation request failed with error "403 PERMISSION_DENIED: The caller does not have permission" (installations/request-failed)`

The request and payload are:

https://firebaseinstallations.googleapis.com/v1/projects/<appId>/installations
```json
{
	"appId": <appId>,
	"authVersion": "FIS_v2",
	"fid": <fid>
	"sdkVersion": "w:0.5.6"
}
```

There are no restrictions on the app, still working on localhost (no SSL)

**Comment by hsubox76** [comment]
This is a different error, can you open a new issue? When you do, can you also show the code you are using to call Firebase messaging?

Also have you put any API restrictions on your API key using the Google Cloud console? If so, you might want to make sure you're allowing the Firebase Installations API. See https://stackoverflow.com/questions/58495985/firebase-403-permission-denied-firebaseerror-installations-requests-are-blo

**Comment by dasrajan** [comment]
> Hey @dasrajan. We need more information to resolve this issue but there hasn't been an update in 5 weekdays. I'm marking the issue as stale and if there are no new updates in the next 5 days I will close it automatically.
> 
> If you have more information that will help us get to the bottom of this, just add a comment!

Hello @hsubox76 i reverified the appId and it's still the same on localhost but it's working on production. is it because of SSL restriction blocking API calls or any other specific reason?

**Comment by hsubox76** [comment]
No, I think the other user has a separate error and separate issue. How are you providing your Firebase config object that you pass to `initializeApp()`? Are you hardcoding it into your source code or are you supplying your API key, projectId, etc. through environment variables? Could the environment variables be different on localhost? If none of this helps, can you provide a repo that contains a minimal reproduction of the error?
