### ISSUE TITLE
FR: Allow override the default *.googleapis.com hostname when calling API

### ISSUE THREAD

**Issue by sunset1234321** [firebase/firebase-js-sdk#6065]
Similar to https://github.com/firebase/firebase-android-sdk/issues/905

Request is:
Hope the sdk could allow a proxy server domain to be set.

Reason:
since the  default *.googleapis.com hostname is blocked in china,       which my proxy server could be deployed in an environment that has access to *.googleapis.com

**Comment by zymotik** [comment]
Duplicate of #1641
