### ISSUE TITLE
Updating persistence type with v9

### ISSUE THREAD

**Issue by tiagotwistag** [firebase/firebase-js-sdk#6067]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.3.1
  * Browser version: React-native 0.64.3
  * Firebase SDK version: 9.6.5
  * Firebase Product: auth

### [REQUIRED] Describe the problem
After upgrading from v8 to v9 I'm no longer able to change the auth persistence type on the go, as of v8 I was able to set a persistence type to none(inMemoryPersistence) and from there to local(browserLocalPersistence) and everything work as expected but since v9 If I go to persistence type none I'm not able to go back to local, I say that because if I set it to none and after to local and close the app the authentication is lost. On the other hand, if I trigger it to only set the persistence type to local everything works as expected, So I believe the issue comes from going to none first.

#### Steps to reproduce:

1. Set persistence to none
2. Login
3. Update persistence to local
4. Close & reopen the app

#### V8
Update to none
```javascript
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.NONE);
```
Update to local
```javascript
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);
```

#### V9
Update to none
```javascript
setPersistence(inMemoryPersistence)
```
Update to local
```javascript
setPersistence(browserLocalPersistence)
```

**Comment by tiagotwistag** [comment]
Hi @sam-gc, thank you for taking the time to get into it, I'm initializing the auth using getAuth.
Related to the localstorage, I'm using the SDK in a different environment(React-native 0.64.3), but I went and verified the async storage and if I don't trigger a from none to local storage I have the data stored there but if for some reason I go to none and then back to storage it returns null

**Comment by tiagotwistag** [comment]
Hey @sam-gc any update?

**Comment by supermisha** [comment]
@sam-gc @jbalidiong any news on this? Thanks folks!!

**Comment by tiagotwistag** [comment]
Hey once again @sam-gc is there anything we can do to get this one fixed?

**Comment by sam-gc** [comment]
Hi @tiagotwistag, my apologies for missing your earlier response. I missed that you were using react native. For v8, LOCAL persistence (it was an enum) simply used the correct react native local persistence internally. In v9, since everything is modular, when you call `setPersistence()` you're actually passing in a persistence object. React Native doesn't work with localStorage across sessions, if I understand correctly. 

In your case, you'll need to call `setPersistence()` with the response you obtain from [`getReactNativeLocalPersistence()`](https://firebase.google.com/docs/reference/js/auth#getreactnativepersistence). If you want to initialize the Auth library with this persistence from the beginning, you'll have to use `initializeAuth()` with the `persistence` field defined as discussed in this doc: https://firebase.google.com/docs/auth/web/custom-dependencies.

Please investigate if this fixes the issue and report back :)

**Comment by tiagotwistag** [comment]
Hey @sam-gc, thank you once again for the follow up, I just tested it and seems that now going to local is not working, I might be missing something, here is the code I'm using

```js
export const setAuthenticationPersistence = type => {
  return setPersistence(
    auth,
    type === 'none'
      ? inMemoryPersistence
      : getReactNativePersistence(AsyncStorage),
  );
};
```

This code is later called by a react useEffect
```jsx
  useEffect(() => {
    if (userIsAuthenticated) {
      setAuthenticationPersistence(hasMissingAuthSteps ? 'none' : 'local');
    }
  }, [userIsAuthenticated, hasMissingAuthSteps]);
```

Just to give some more context, with the previous code
```js
export const setAuthenticationPersistence = type => {
  return setPersistence(
    auth,
    type === 'none' ? inMemoryPersistence : browserLocalPersistance,
  );
};
```

going local would work, the issue would be going inMemory first and then jumping to local, that would break the persistence for some reason

**Comment by sam-gc** [comment]
Thanks for these snippets @tiagotwistag, would you mind trying one more thing? Store the result of `getReactNativeLocalPersistence` as a singleton and use that object that you create once instead of calling `getReactNativeLocalPersistence` every time your `setAuthenticationPersistence` function is called

**Comment by tiagotwistag** [comment]
Did some quick tests and doing the follow:
```js
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  getReactNativePersistence,
  reactNativeLocalPersistence,
} from 'firebase/auth/react-native';

const testPer = getReactNativePersistence(AsyncStorage);

export const setAuthenticationPersistence = type => {
  return setPersistence(auth, type === 'none' ? inMemoryPersistence : testPer);
};
```
Produces the same results as before, but if I do the follow:
```js
import {
  getReactNativePersistence,
  reactNativeLocalPersistence,
} from 'firebase/auth/react-native';

export const setAuthenticationPersistence = type => {
  return setPersistence(
    auth,
    type === 'none' ? inMemoryPersistence : reactNativeLocalPersistence,
  );
};
```
Works perfectly fine, going trough the package code my guess is that if I call getAuth it does get initialized with the default reactNativeLocalPersistence and changing it after creates this inconsistency of not using the same storage after updating the persistence, correct?
```js
export const reactNativeLocalPersistence: Persistence =
  getReactNativePersistence({
    getItem(...args) {
      // Called inline to avoid deprecation warnings on startup.
      return ReactNative.AsyncStorage.getItem(...args);
    },
    setItem(...args) {
      // Called inline to avoid deprecation warnings on startup.
      return ReactNative.AsyncStorage.setItem(...args);
    },
    removeItem(...args) {
      // Called inline to avoid deprecation warnings on startup.
      return ReactNative.AsyncStorage.removeItem(...args);
    },
  });

export {getReactNativePersistence};

export function getAuth(app: FirebaseApp = getApp()): Auth {
  const provider = _getProvider(app, 'auth');

  if (provider.isInitialized()) {
    return provider.getImmediate();
  }

  return initializeAuth(app, {
    persistence: reactNativeLocalPersistence
  });
}
```

**Comment by tiagotwistag** [comment]
Hey @sam-gc can you just give a quick look to it and see if what I just said makes sense? and if so, you can close the ticket, thanks for help 👐

**Comment by sam-gc** [comment]
Hi @tiagotwistag, my apologies for the delayed reply. Yes, the way you described it is correct. You can either use `getReactNativePersistence` and use `initializeAuth`, or you can use `getAuth` with the default `reactNativeLocalPersistence`. Thanks for digging into it!
