### ISSUE TITLE
Uploading file to Firebase Storage cannot be opened

### ISSUE THREAD

**Issue by ElihuJ** [firebase/firebase-js-sdk#6089]
I have been following the documentation on how to upload files (Writing from memory) [Google Documentation](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-code-sample)[](https://i.stack.imgur.com/9hZMC.png)

So I have the following:

```javascript
await admin.storage().bucket().file("test.txt").save("Some text");
```
After this I can see my file successfully uploaded to my bucket:

<img width="1020" alt="Screen Shot 2022-03-20 at 5 01 15 pm" src="https://user-images.githubusercontent.com/30395400/159152812-3f961e6d-0cc8-4764-8c85-cc2912a10994.png">

but whenever I try to open it, it gives me an undefined URL:

https://console.firebase.google.com/project/my-project/storage/my-project.appspot.com/undefined

Which causes a redirect and I can't open the file from the the firebase console, I have also tried to make sure the file is public by running this right after the creation of the file:

```javascript
await admin.storage().bucket().file("test.txt").makePublic();
```

I have tried this from my firebase functions emulator as well as deploying it to production
Maybe I'm missing something silly here but I can't spot it

SO Link: https://stackoverflow.com/questions/71544472/how-to-upload-file-with-content-to-firebase-storage-bucket-from-firebase-functio

=================
Question originally raised on https://github.com/googleapis/nodejs-storage/issues/1818 but asked to redirect this issue in this space instead

**Comment by hsubox76** [comment]
Sorry to redirect you again but it sounds like you're using `firebase-admin`? This is actually the correct repo: https://github.com/firebase/firebase-admin-node
