### ISSUE TITLE
Implicit global variable

### ISSUE THREAD

**Issue by mochiya98** [firebase/firebase-js-sdk#609]
### Describe the problem
/packages/polyfill/src/polyfills/promise.ts line:35
`Promise = ` is implicit global variable.
It causes problems using webpack("use strict") on IE11.
`SCRIPT5042: Variable undefined in strict mode`
```javascript
// Polyfill Promise
if (typeof Promise === 'undefined') {
  // HACK: TS throws an error if I attempt to use 'dot-notation'
  __global[
    'Promise'
  ] = Promise = require('promise-polyfill') as PromiseConstructor;
}
```
This is an unnecessary code.
Maybe __global['Promise'] performs all.

### Environment
  * Operating System version: Win10 x64 1709
  * Firebase SDK version: 3.17.7
  * Firebase Product: Polyfill
  * Internet Explorer version: 11.248.16299.0

**Comment by jshcrowthe** [comment]
The corresponding PR has been merged! Thanks for this 👍
