### ISSUE TITLE
Firestore object not consistent between server-side and client-side in Next.js

### ISSUE THREAD

**Issue by pimoens** [firebase/firebase-js-sdk#6095]
### [REQUIRED] Describe your environment

  * Operating System version: Microsoft Windows 10 Pro
  * Browser version: 
     - Google Chrome Version 99.0.4844.82 (Official Build) (64-bit)
     - Brave Browser Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)
  * Firebase SDK version: ^9.6.9
  * Firebase Product: Firestore

#### Steps to reproduce:

I am creating a Next.js ("next": "12.1.0", "react": "17.0.2") application using Firebase as datastore.

After initialization of the `FirebaseApp` with the correct configuration and accessing Firestore using `getFirestore(FirebaseApp)`, the resulting object contains the correct settings and config. However, when attempting to access Firestore through a React Hook, the Firestore object seems to have changed.

When debugging the source code by simply adding a `console.log` statement the output in the terminal (server-side) seems to be different than the output in the browser (client-side).

Output terminal (correct behavior):
```
Firestore {
  ...
  _databaseId: DatabaseId {
    projectId: 'algofi-liquidation-dashb-44465',
    database: '(default)'
  },
  ...
}
```

Output browser:
```
gc {
   type: "firestore",
   ...
   _databaseId: vt
      database: "(default)"
      projectId: undefined
      isDefaultDatabase: (...)
   ...
}
```

This results in the Firebase connection to fail with the following error: `The project undefined does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database.`

#### Relevant Code:
firebase.config.js
```javascript
import { initializeApp } from "firebase/app"
import { getFirestore } from "firebase/firestore"

const firebaseConfig = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID
};

const firebase = initializeApp(firebaseConfig);
const firestore = getFirestore(firebase);
export default firestore;
```

index.js
```javascript
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { collection } from "firebase/firestore"
import { useCollection } from "react-firebase-hooks/firestore";
import firestore from '../firebase.config'

export default function Home() {
    console.log(firestore);
    const [accounts, accountsLoading, accountsError] =
        useCollection(collection(firestore, "accounts"),{}
        );

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                {accountsError && <strong>Error: {JSON.stringify(accountsError)}</strong>}
                {accountsLoading && <span>Loading..</span>}
                {accounts && accounts.docs.map((account) => (
                    <div key={account.get('storage_account')}>
                        {JSON.stringify(account)}
                    </div>
                ))}
            </main>
        </div>
    )
}
```

**Comment by pimoens** [comment]
Hi @ehsannas , I was unable to reproduce the issue in codesandbox.io, but was unsuccessful.

I can reproduce the issue on my own system (node: v16.14.2, npm: 8.5.0) by running:
`npx create-next-app`

Replacing `pages/index.js` by the code snippet in the original post.
Adding `firebase.config.js` with the content in the code snippet in the original post.

`package.json`
```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "firebase": "^9.6.9",
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-firebase-hooks": "^5.0.3"
  }
}
```

And finally running `npm run dev`

I will attempt to set it up in a sandbox, and dig into the differences between the sandbox environment and my local environment. Thanks in advance for the support!

**Comment by pimoens** [comment]
Interesting enough, I can't reproduce it on my Linux machine either with the same node and npm versions :/

**Comment by pimoens** [comment]
I actually pinpointed the issue..

If I insert the configuration directly instead of using the `process.env` variables it seems to work as expected.

**Comment by ehsannas** [comment]
Can you inspect the `process.env.FIREBASE_API_KEY` and other variables to ensure they have a valid value? I suspect this is not a Firestore issue.

**Comment by jamesdaniels** [comment]
I'd recommend that you lean on [Next.js's `publicRuntimeConfig`](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration), rather than rolling your own.\

```ts
const { publicRuntimeConfig: { firebaseConfig } } = getConfig();
const firebase = initializeApp(firebaseConfig);
const firestore = getFirestore(firebase);
export default firestore;
```

Also check out [reactfire](https://github.com/FirebaseExtended/reactfire) while you're playing around with Next.js, we have some improvements coming along for Next.js developers specifically.
