### ISSUE TITLE
9.6.9 new Firestore error when using batch.set: TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by acoyfellow** [firebase/firebase-js-sdk#6096]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04.1 LTS 
  * Browser version: Chrome Version 99.0.4844.74 (Official Build) (arm64)
  * Firebase SDK version: 9.6.9
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
I cannot batch.set data in 9.6.9.

#### Steps to reproduce:
I'm getting an error on a codebase that has been running smoothly for a while. I noticed that when updating from 9.6.8 to 9.6.9, i get:
```
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.fromString (index.esm2017.js:1084:19)
    at hc2 (index.esm2017.js:16125:22)
    ...
```
Rolling back to `9.6.8` fixes the issue for me with no code change, so I'm fairly certain there is something specific with the latest `9.6.9` version.

#### Relevant Code:
I've isolated the problem down to:
```javascript
const newRef = doc(firestore, "collectionName", colKey, "subColName", subColKey);
await batch.set(newRef, data); // this is when the above error gets thrown
```
It seems that it's potentially isolated to the format of the `ref` and/or `batch` function? I'm not sure. 

I can try to put together a full repro soon, but that's all I have time to share for now. Thank you.

**Comment by ehsannas** [comment]
Hi @acoyfellow . It seems that you are not awaiting the right API call. For batches, you can perform many `set` calls, and then do a `commit`.

```js
// your code snippet:
await batch.set(newRef, data); // this is when the above error gets thrown

// updated:
batch.set(newRef, data);
await batch.commit();
```

Please refer to the reference [here](https://firebase.google.com/docs/reference/js/firestore_.writebatch.md#writebatch_class) for the WriteBatch class. Let me know if you still face any issues after using the updated code.

**Comment by acoyfellow** [comment]
@ehsannas doh - I'm sorry. The pseudo-code exampe I shared is not accurate. I am using batch correctly in the actual codebase.

Updated example:
```js
const newRef = doc(firestore, "collectionName", colKey, "subColName", subColKey);
batch.set(newRef, data); // this is when the above error gets thrown
await batch.commit()
```

**Comment by ehsannas** [comment]
@acoyfellow Thanks for the update. I'm not able to reproduce this using 9.6.9 personally.

I'm running the following in an empty html page:
```js
    const docRef = doc(db, "collectionName", "colKey", "subColName", "subColKey");
    const batch = writeBatch(db);
    batch.set(docRef, {"foo": "bar"});
    await batch.commit();
    const snap = await getDoc(docRef);
    console.log(snap.data());
```

Also, for 9.6.8 -> 9.6.9 , firestore version changed from 3.4.5 -> 3.4.6. Looking at the [CHANGELOG](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/CHANGELOG.md#346) (and the code that went into that release), I don't see any Firestore code changes.

Would you be able to provide a repro?
