### ISSUE TITLE
 Restrict Firebase data modification not work

### ISSUE THREAD

**Issue by lucapu88** [firebase/firebase-js-sdk#6103]
* Operating System version: Linux
  * Browser version: 99.0.4844.74
  * Firebase SDK version: 9.6.5
  * Firebase Product: all

Hi I am having this problem, it may be that I am doing something wrong because I am inexperienced.
I have carried out the procedure to allow the saving / setting calls of my realtime database only from a certain url.
The procedure I did is this:

visited https://console.developers.google.com/apis
i went to my firebase project and credentials
In API Keys, I selected the browser key associated with my Firebase project.
In "Accept requests from these HTTP referrers (websites), I only added my app URL.

Now if I understand correctly, when I do a get or a set it should only work if I do it from my site right?
Instead of my local it works the same ... if I make get and set calls from my local environment I can still make them!
Why? where am i wrong?

This is my project if it can be useful:
https://github.com/lucapu88/speed-typer-game

**Comment by hsubox76** [comment]
I'm not sure if the API key restrictions should block realtime database get/set access and I will check on that. In the meantime, take a look here: https://stackoverflow.com/questions/70175022/setting-http-referer-restriction-on-firebase-api-key-does-not-make-a-difference

I think the second answer is correct in that this isn't a very secure way to block unauthorized calls. For security purposes, the best combo would be App Check (if you don't want anything outside your official app to access your database endpoints) and Security Rules (prevent unauthorized users from writing/reading specified paths in the database, whether they are using your app or not).
