### ISSUE TITLE
I got this error help me please.

### ISSUE THREAD

**Issue by vtn-dev2016** [firebase/firebase-js-sdk#6109]
### [REQUIRED] Describe your environment

  * Operating System version: macos
  * Browser version: _____
  * Firebase SDK version: "^9.6.10",
  * Firebase Product: auth (signInWithPhoneNumber)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```
<img width="684" alt="Screen Shot 2565-03-31 at 15 16 42" src="https://user-images.githubusercontent.com/30209508/161010984-bfd9697a-de22-44c5-b74f-6077123c60e8.png">

**Comment by hsubox76** [comment]
Can you show the line of code where you call `signInWithPhoneNumber`? Perhaps there's a missing argument.

**Comment by vtn-dev2016** [comment]
<img width="687" alt="Screen Shot 2565-04-01 at 10 36 23" src="https://user-images.githubusercontent.com/30209508/161190429-cfd16e68-c54f-4fbe-8aec-faa0cc7135c2.png">

here my code

**Comment by hsubox76** [comment]
Can you console.log the value of `phoneNumber` on the line right before `signInWithPhoneNumber` is called? I notice in your initial post there seems to be a log of an object ("On Clicked Signin") which has a property where `phoneNumber` is spelled wrong (`phonenNumber`). If you're passing that object directly into `onSignIn()` it may cause `phoneNumber` to be undefined here.

**Comment by vtn-dev2016** [comment]
oh I got it thank you
