### ISSUE TITLE
Unable to update custom claims after setting them with createCustomToken 

### ISSUE THREAD

**Issue by MathiasGilson** [firebase/firebase-js-sdk#6113]
# Details

If you use the function `createCustomToken` to sign in the user and setting his custom claim, updating the custom claims later using the function `setCustomUserClaims` will not update the claims even after forcing the idToken to refresh using the function `firebase.auth().currentUser.getIdTokenResult(true)`

# How to reproduce?

Sign in the user on firebase using a custom token generated with the function `createCustomToken` including the custom claims

```ts
  firebase.auth().createCustomToken(uid, {myClaim: "test"}).then((customToken) => console.log(customToken))
```

Sign in the user on the frontend using the custom token

```ts
   // copy paste the customToken manually for testing
   firebase.auth().signInWithCustomToken(customToken)
```

Update the claim on the backend using `setCustomUserClaims`

```ts
   firebase.auth().setCustomUserClaims(uid, {myClaim: "updateTest"})
```

Refresh the idToken on the frontEnd and log the custom claims

```ts
   firebase.auth().currentUser
       .getIdTokenResult(/*force refresh*/ true)
       .then((idTokenResult) => {
          console.log(`custom claims`, idTokenResult.claims)
       })
```

You should see that the claim is still `{ myClaim: "test" }` instead of ` { myClaim: "updateTest" }`

# How to work around this issue?

Setting the custom claims separately at sign in instead of using the function `createCustomToken` to set them will allow you to edit these claims later.

Working code:

```ts
firestore
    .doc(`users/${uid}`)
    .get()
    .then((clientSnapshot) => {
      // give user the claims he has
      const { permissions = {} } = clientSnapshot.data()
     // use setCustomUserClaims to set the claims
      return auth.setCustomUserClaims(uid, { permissions })
    })
    // generate the custom token
    // ⚠️ don't use createCustomToken to set permission as you won't be able to update them
    .then(() => auth.createCustomToken(uid))
    .then((customToken) => {
      // send the custom token to the frontend to sign the user in
      return res.status(200).json({ customToken })
    })
```

**Comment by sam-gc** [comment]
Hi @MathiasGilson, thanks for filing this. Please see the *Note* under this section of the docs: https://firebase.google.com/docs/auth/admin/custom-claims#set_and_validate_custom_user_claims_via_the_admin_sdk

The relative priority of claims set by `createCustomToken` is higher than that of `setCustomUserClaims`. Can you verify whether or not this situation (i.e. the particular order/setup described in the note) applies to your use case?

**Comment by MathiasGilson** [comment]
Hello @sam-gc, yes you are right I didn't see that note. Thank you for pointing it out.

It's not a bug then but I think this issue will help of someone end up in the same situation.
