### ISSUE TITLE
No response from setDoc()

### ISSUE THREAD

**Issue by SaadJamilAkhtar** [firebase/firebase-js-sdk#6117]
## Environment

Operating System version: mac OS v12.2.1 
Browser version: Chome 99.0.4844.83
Firebase SDK version: 9.6.10
Firebase Product: firestore
React JS v 18.0.0
Version 9.6.10

Couldn't get response from addDoc()

Responses from storage is fine but there is no response from firebase firestore on addDoc() or setDoc(), the process starts but never returns a response and no data is added to firestore

**Comment by jbalidiong** [comment]
Hi @SaadJamilAkhtar, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the error.
 
If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by SaadJamilAkhtar** [comment]
There was an issue with my configuration. The issue is resolved. Thanks for the response.
