### ISSUE TITLE
Firebase Auth not working properly with React 18

### ISSUE THREAD

**Issue by semihraifgurel** [firebase/firebase-js-sdk#6119]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Monterey 12.3.1
  * Browser version: Chrome 100.0.4896.60
  * Firebase SDK version: 9.6.10
  * Firebase Product: auth

#### Steps to reproduce:

There were no problems when using React 17. Upgrading to React 18, every time we open the page, the user acts as if he is not logged in. Refreshing the page logs out directly.
#### Relevant Code:

```javascript
// src/index.js
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter as Router } from 'react-router-dom';
import './styles/styles.scss';
import App from './App/App';
import reportWebVitals from './reportWebVitals';
import { ThemeContextProvider } from './contexts/themeContext';
import './i18n';
import { AppContextProvider } from './contexts/appContext';
import { AuthContextProvider } from './contexts/authContext';

const container = document.getElementById('root');
const root = createRoot(container);
root.render(
	<Router>
		<React.StrictMode>
			<AppContextProvider>
				<ThemeContextProvider>
					<AuthContextProvider>
						<App />
					</AuthContextProvider>
				</ThemeContextProvider>
			</AppContextProvider>
		</React.StrictMode>
	</Router>,
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

```javascript
import {
	initializeAuth,
	GoogleAuthProvider,
	browserLocalPersistence,
	indexedDBLocalPersistence,
	browserSessionPersistence,
	browserPopupRedirectResolver,
} from 'firebase/auth';
import app from './firebaseApp';

const auth = initializeAuth(app, {
	persistence: [indexedDBLocalPersistence, browserLocalPersistence, browserSessionPersistence],
	popupRedirectResolver: browserPopupRedirectResolver,
});
const googleProvider = new GoogleAuthProvider().setCustomParameters({
	prompt: 'select_account',
});

const actionCodeSettings = {
	url: process.env.REACT_APP_URL,
};

export { googleProvider, actionCodeSettings };
export default auth;
```

**Comment by jbalidiong** [comment]
Hi @semihraifgurel, thanks for reaching out. I tried replicating and I wan't able to reproduce the same behavior. I've added  `onAuthStateChanged()` method to verify if there are no users if I press the refresh button and I was able to get the user as expected. Can you verify if the user will be null after page reload in the `onAuthStateChanged()`?

**Comment by AndrewHenderson** [comment]
I'm experiencing this as well.

After logging in, a page refresh causes the `onAuthStateChanged` callback to pass `null` as the value.

Here is my reduced code.

```jsx
const app = initializeApp(config);
const auth = initializeAuth(app);

const LoginScreen = () => {
  const handleSubmit = (values) => {
    signInWithEmailAndPassword(auth, values.email, values.password);
  };
  
  const handleAuthStateChange = async (userCredential) => {
    console.log(userCredential);
  };

  useEffect(() => {
    return onAuthStateChanged(auth, handleAuthStateChange);
  }, []);
  
  …
}
```

**Comment by AndrewHenderson** [comment]
Updating Chrome resolved this issue for me.

Check your application's IndexedDB. It should have the following two databases defined.

<img width="631" alt="Screen Shot 2022-04-21 at 12 23 02 PM" src="https://user-images.githubusercontent.com/1031565/164537789-55e43a78-7168-4c7c-ac9c-8a6cafb0f8ea.png">

For some reason, Chrome's IndexedDB was not working properly for me.

It would be helpful if there was error logging when attempting to write to IndexedDB. This was failing silently in Firebase, so I had no idea why persistence was not working.

**Comment by Paul-Todd** [comment]
I commented in #6175 that I am seeing a similar issue as well. Still hav'nt been able to track it down to one thing but removing the InitializeAuth code and replacing it with

`
this.firebase = initializeApp(firebaseConfig); 
this.auth = getAuth(this.firebase);
`

fixed it for me at least

**Comment by sam-gc** [comment]
@AndrewHenderson, I replied to @Paul-Todd here: https://github.com/firebase/firebase-js-sdk/issues/6175#issuecomment-1121326289

The issue in your cases is that you're using `initializeAuth()` without the `persistence` field set in the dependencies map you pass in. Without `persistence` set, the library defaults to in-memory (this is unrelated to the problem this issue is reporting). Please see the linked comment for more elaboration.

**Comment by semihraifgurel** [comment]
I have examined in detail for a long time and there is no problem in firebase. It was caused by the mistakes we made in React 17 after switching to React 18 but that we were not aware of.
