### ISSUE TITLE
Chrome extension Service worker "ReferenceError : XMLHttpRequest is not defined" Firestore

### ISSUE THREAD

**Issue by rendomnet** [firebase/firebase-js-sdk#6124]
I'm using **Firebase Firestore** inside my Chrome extension background script(Version 3 Service worker) and as I understood it uses XMLHttpRequest which background scripts are not supporting.

`@firebase/firestore:  Connection WebChannel transport errored`

Right now it gives this error.
`ReferenceError : XMLHttpRequest is not defined`

But Firebase Realtime Database is working

**Comment by rendomnet** [comment]
Firebase Firestore is not working
Firebase Database is working.

**Comment by jbalidiong** [comment]
Hi @rendomnet, thanks for reaching out. A reproducible example would be ideal, but in the meantime, could you share a few more details and logs with [logging enabled](https://firebase.google.com/docs/reference/node/firebase#setloglevel)?

**Comment by rendomnet** [comment]
@jbalidiong Chrome Extension Manifest V3 are using Service workers
`Workers no longer provide XMLHttpRequest, but instead support the more modern [fetch()](https://developer.mozilla.org/docs/Web/API/Fetch_API).`
So because of this Firebase Firestore stopped working.
But Google is forcing Extension authors to move to new Manifest V3 wich no longer provide XMLHttpRequest, and Firestore is using XMLHttpRequest.

https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#workers

**Comment by jbalidiong** [comment]
If you're using v8, it uses `XMLHttpRequest` instead of `fetch` which is not available in the service worker. Using v9 web SDK will let you use Firebase inside the service worker. Would you mind trying to update the SDK version you're using and see if the issue will persist?

**Comment by rendomnet** [comment]
@jbalidiong yes this is working. Thank you very much!
