### ISSUE TITLE
Expo: Auth-types: main not found

### ISSUE THREAD

**Issue by alex-wrede-cap** [firebase/firebase-js-sdk#6130]
* Operating System version: Mac osx 12.2.1
  * Browser version: newest opera / newest ios on 08.04.22
  * Firebase SDK version: 9.6.10
  * Firebase Product: auth-types

I am trying to use  `EmailAuthProvider.credential(mail, password);` . No error is raised in the IDE (VsCode).
On build my iOS Emulator crashes with following message:
 `While trying to resolve module `@firebase/auth-types` from file `/Users/xxxx/xxxx/project/app/contexts/Auth.tsx`, the package `/Users/xxxx/xxxx/project/node_modules/@firebase/auth-types/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/xxxx/xxxx/project/node_modules/@firebase/auth-types/index`. Indeed, none of these files exist:`

Does anybody know what to do? I've already reinstalled everything, upgraded and so on...

FYI: I need it for adding the mail auth type to my logged in user. Unfortunately I really don't have any chance of doing something else 😢

**Comment by lisajian** [comment]
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: [b/228615404](https://b.corp.google.com/issues/228615404))

**Comment by sam-gc** [comment]
Hi @alex-wrede-cap, would you please share a small sample of code demonstrating the issue? In particular, please also include the way you import the library. Also, what SDK bundler are you using?
