### ISSUE TITLE
firestore random misfire

### ISSUE THREAD

**Issue by dsl400** [firebase/firebase-js-sdk#6145]
### [REQUIRED] Describe your environment

  * Operating System version: windows 10, linux mint
  * Browser version: chrome  windows 100.0.4896.88 (Official Build) (64-bit) ,
                                chrome linux mint Version 99.0.4844.51 (Official Build) (64-bit)
  * Firebase SDK version: 10.5.0
  * Firebase Product: firestore 

### [REQUIRED] Describe the problem

I do not really know how to explain this... 

My client is using the same computers 24/7 on this application and randomly a specific feature of the application that was added a few week ago is missing and the application does not work properly.

I cleaned the application local storage, closed the tab and opened another one.
Log back in with the same username and the PROFILE (user profile document for this specific user) does not load 
The document is not deleted because I can see it in the firebase console
In the same application on my pc the the PROFILE appears in the users list
In the client pc the PROFILE does not apear in the user list
After any modification of the PROFILE it is now available in the client pc

The "missing document" behavior started to appear in other places too.
In the attached image you can see a screenshot on the top is the client screen via remote desktop and on the bottom is my screen.
both rendering the same list with the same filter

I've been experiencing this problem in the past weekly.

My guess is that it has something to do with the offline persistence.

Please advice on what steps are needed to find this bug

![image](https://user-images.githubusercontent.com/4988046/163247293-574d53b6-73c7-4dc7-9982-1df115b5260e.png)

![err_1](https://user-images.githubusercontent.com/4988046/163249124-dba856fa-ef72-4df6-bc2c-9a7af4db9c32.PNG)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by ehsannas** [comment]
Hi @dsl400 , are you able to provide a way for us to reproduce this problem?

**Comment by dsl400** [comment]
The strange behaviour has 2 key elements:
Offline persistance and long term use.

I will try to create a stackblitz project however I cannot reproduce the
long term usage.

If you can, give me some ideas on what traps ( try catch blocks ) I can
implement to gather more information and I will post the results here
