### ISSUE TITLE
Intercepting the signInWithEmailAndPassword

### ISSUE THREAD

**Issue by Pixelatex** [firebase/firebase-js-sdk#618]
### [REQUIRED] Describe your environment

  * Firebase Product: auth

### [REQUIRED] Describe the problem

I'm using the signInWithEmailAndPassword but I'd need to intercept the login to be able to fetch the role and check if the user is allowed access to the application.

The flow would go something like this:

signInWithEmailAndPassword --> signin --> wait --> check for role --> return true/false based on the role permissions.

All the solutions talk about limiting what data the user can read but in this case it's pure about authentication and after searching through documentation, the firebase slack, stackoverflow,... I still can't find any way to make this work.

**Comment by bojeil-google** [comment]
You enforce this after sign in via the ID token and security rules.
Look up how to set custom user attributes that define rules: https://firebase.google.com/docs/auth/admin/custom-claims

If you want to know ahead of time, you can use the Admin SDK to lookup the user by email and check the role of that user. However, that is still not secure as someone can bypass this check on the client and still sign in. You have to enforce this from the security rule.

If you want a lambda function to block sign in based on some logic you run, then you should file a feature request for it via official channels: https://firebase.google.com/support/

**Comment by samtstern** [comment]
Closing because I think @bojeil-google answered this completely and it's been a while.
