### ISSUE TITLE
Unable to add or retrieve documents via Firestore (React Native)

### ISSUE THREAD

**Issue by Luckygirlllll** [firebase/firebase-js-sdk#619]
### [REQUIRED] Describe your environment

  * Operating System version:  IOS (React Native), Android  (React Native)
  * Firebase SDK version: 4.12.0
  * Firebase Product: Firestore

Unable to add or retrieve documents via Firestore, there is no errors, no exception, but nothing is happened 

#### Steps to reproduce:

  Add  `npm install firebase@4.12.0 --save  ` to the react native project
  Add the code below to the project 
  Nothing is happening (collections and documents were not created) 

#### Relevant Code:
```
import * as firebase from 'firebase'
import firestore from 'firebase/firestore'

var config = {
  apiKey: "xxxxxxxxxxxxxxxxxx",
  authDomain: "xxxxxxxxxxxxxxxxxx",
  databaseURL: "xxxxxxxxxxxxxxxxxx",
  projectId: "xxxxxxxxxxxxxxxxxx",
  storageBucket: "xxxxxxxxxxxxxxxxxx",
  messagingSenderId: "xxxxxxxxxxxxxxxxxx"
};

firebase.initializeApp(config);

var db = firebase.firestore();

var docRef = db.collection('users').doc('alovelace');

var setAda = docRef.set({
    first: 'Ada',
    last: 'Lovelace',
    born: 1815
})
```

**Comment by mikelehen** [comment]
You may be running into https://github.com/firebase/firebase-js-sdk/issues/283.  There was a fix made in react native but I don't think it's been released yet.  You can try the workaround in https://github.com/firebase/firebase-js-sdk/issues/283#issuecomment-345884425 and see if that solves the issue for you.

**Comment by Luckygirlllll** [comment]
@mikelehen I have already tried solutions from #283, it didn't help me, besides of that, I'm not using expo, I'm using pure react native. and in my case Firestore don't work both in Android and IOS.

**Comment by mikelehen** [comment]
Is this tracking a different issue than https://github.com/firebase/firebase-js-sdk/issues/638 ?  If not, can we close this issue?  I'm inclined to use https://github.com/firebase/firebase-js-sdk/issues/638 as the primary tracking issue since it has your logs.

**Comment by akhilnayak0206** [comment]
Use react-native-firebase :: https://rnfirebase.io/docs/v5.x.x/installation/initial-setup
Make sure to follow the documentation.
Hope this helps!!
