### ISSUE TITLE
FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 404. (appCheck/fetch-status-error)

### ISSUE THREAD

**Issue by ohjs88** [firebase/firebase-js-sdk#6198]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Catalina
  * Browser version: Chorome 100.0.4896.127
  * Firebase SDK version: 9.7.0
  * Firebase Product: app-check

#### Steps to reproduce:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/53819041/165966445-8941958b-69b4-4bbc-aa0b-0e59bc51a1d0.png">

The appcheck library spits the error log indefinitely.

FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 404. (appCheck/fetch-status-error)
FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 404. (appCheck/fetch-status-error)
FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 404. (appCheck/fetch-status-error)
...

The Chrome "Network" tab displays only one 404 message.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/53819041/165967832-50a76481-d718-44bf-b865-f5a6a4115c3d.png">

I can't do anything about it. Please help me

#### Relevant Code:

```javascript
const firebaseapp = initializeApp(firebaseConfig);
const appCheck = initializeAppCheck(firebaseapp, {
  provider: new ReCaptchaV3Provider("my-key"),
  isTokenAutoRefreshEnabled: true,
});
```

**Comment by DavidDomkar** [comment]
Same problem here. I solved it by downgrading to 9.6.11.

**Comment by semihraifgurel** [comment]
Yes @DavidDomkar, you're right, it doesn't give an error when you do what you say. I guess the problem is in firebase.

**Comment by hollandzone** [comment]
I encounter same issue

**Comment by haofiltered** [comment]
Same issue here. Seems like google didn't do a data migration, `/v1/...` returns 404. 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/28816747/166252675-2c8a35a2-ca16-41b3-b8e7-8337e3c2fe15.png">

**Comment by actuallymentor** [comment]
Running into this issue, downgrading to `9.6.11` not working for me.

Do I understand correctly this is an issue on the GCP backend?

*Ps. are you telling me Firebase has no CI that tests their infra before merging updates?*

**Comment by actuallymentor** [comment]
Additional debugging info. I'm seeing 404s on:

```
https://content-firebaseappcheck.googleapis.com/v1/projects/PROJECT_NAME/apps/x:xxxxxxxxxxx:web:xxxxxxxxxxx:exchangeDebugToken?key=xxxxxxxxxxxx
```

My production system seems to be fine, but the debug tokens just stopped working. Not that this is both *BEFORE* and *AFTER* upgrading to `9.7`.

**Comment by clive-h-townsend** [comment]
> 

I believe the issue is in `9.7`... You need to go down to `9.6.11`

**Comment by actuallymentor** [comment]
> I believe the issue is in 9.7... You need to go down to 9.6.11

I repeat: it happens in both versions for me :)

**Comment by hsubox76** [comment]
We've completed fixes on the backend and any requests going forward should no longer be seeing this issue. Please update if you continue to see the issue.

**Comment by actuallymentor** [comment]
> We've completed fixes on the backend and any requests going forward should no longer be seeing this issue. Please update if you continue to see the issue.

Confirmed fixed. Thank you.

**Comment by ohjs88** [comment]
Confirmed fixed. Thank you.
