### ISSUE TITLE
Firebase auth does not expire with custom jwt

### ISSUE THREAD

**Issue by rahulserver** [firebase/firebase-js-sdk#6201]
### [REQUIRED] Describe your environment

  * Operating System version: MAC Os Monterey (v12.3.1)
  * Browser version: Chrome Version 101.0.4951.41 (Official Build) (x86_64) 
  * Firebase SDK version: 8.10.0
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
I am authenticating via custom jwt `await firebase.auth().signInWithCustomToken(token);`
The token is supposed to expire in 1 hour. But after 1 hour, the firebase authentication still lasts and I am able to make calls to firestore collection that need the `request.auth.uid`. 
Note that I am not calling above code ( `signInWithCustomToken`) on every refresh. The code performs a logout only when any endpoint returns `unauthenticated` or `unauthorized` (or equivalent) error codes. 

I would expect the firebase auth to handle this jwt expiry verification behind the scenes. Or atleast firestore should somehow check if the firebase auth instance used to make calls to read/write collections is properly authenticated or not. 

#### Steps to reproduce:

Any custom jwt (with one hour expiry ) can be used and a read/write to firestore collection that needs `request.auth!=null` can be performed after jwt expires.
#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
`await firebase.auth().signInWithCustomToken(token);`
```

**Comment by sam-gc** [comment]
Hi @rahulserver, the JS SDK will automatically refresh the user's token after 1 hour (this is to ensure there is a consistent connection for Firestore / RTDB / etc). You would need to [revoke the user's refresh token](https://firebase.google.com/docs/auth/admin/manage-sessions) if you don't want the token to last beyond an hour.

Please let us know if this answers your question and/or close this issue.
