### ISSUE TITLE
`signInWithPopup` / `linkWithPopup` hanging on a blank white screen, not calling callbacks

### ISSUE THREAD

**Issue by schlosser** [firebase/firebase-js-sdk#6206]
### [REQUIRED] Describe your environment

  * Operating System version: Android version 12
  * Browser version: Facebook Browser (Messenger app or Facebook app)
  * Firebase SDK version: v9.2.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

When using `signInWithPopup` or `linkWithPopup`, we're seeing a blank white page on our `__/auth/handler` screen, with no callbacks being called locally. Currently, this only reproduces on a Pixel phone (tested multiple phones) in the Facebook embedded browser. My best theory is that the popup is blocked but that is not being detected properly. We are using a custom domain for that handler page, but it works in all other situations / devices.

#### Steps to reproduce:

1. Open https://ambrook.com in the Facebook embedded browser on a pixel device
2. Menu => Login
3. Login with Google / Facebook
4. See hanging white page

#### Relevant Code:

We're using `signInWithPopup()` from the `v9`.

**Comment by schlosser** [comment]
Thanks for the update! We're implementing a workaround that uses `userAgent` to use `linkWidthRedirect` selectively. Do you have any additional context around which kinds of in-app browsers fail here, or on which devices from other folks that have reported this? Right now we're using `*WithRedirect` on all in-app browsers, using code like this:

```js
const isInAppBrowser = () => {
  if (typeof window === undefined) return false;
  const rules = [
    'WebView',
    '(iPhone|iPod|iPad)(?!.*Safari/)',
    'Android.*(wv|.0.0.0)',
  ];
  const regex = new RegExp(`(${rules.join('|')})`, 'ig');
  return !!window.navigator?.userAgent?.match(regex);
};
```

But I'd love to reduce this to only match browsers that will "fail poorly" this way.

**Comment by sam-gc** [comment]
Apps have a lot of leeway in how in-app browsers are configured. It's really pretty random whether or not popup/redirect are going to work properly, depending on the app. There's not a whole lot we can do to mitigate it unfortunately, and I don't have a good rule for determining when it would work and when it wouldn't (otherwise it'd be possible to address the issue in the SDK itself).

I'm going to close this out for now as this is (unfortunately) expected behavior.
