### ISSUE TITLE
web v9 credentialFromError always null

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#6212]
* Operating System version: windows 8.1
  * Browser version: latest chrome
  * Firebase SDK version: 9.6.11
  * Firebase Product: auth (auth, database, storage, etc)

```
(async () => {
	const provider = new GoogleAuthProvider();
	provider.addScope('profile');
	provider.addScope('email');
	try{
		const result = await signInWithPopup(getAuth(getApp()), provider);
	} catch(error) {//pop up blocked for example
		const credential = GoogleAuthProvider.credentialFromError(error);//credential is null. How can I get it to be not null??
	       //what error do I need to simulate to make credential not null??
}
})()
```

**Comment by marcusx2** [comment]
The issue seems to be that the error's `customData` is supposed to have a `_tokenResponse` property, but it doesn't. Is this a bug? Or is the _tokenResponse only present on certain errors? Is the _tokenReponse serializable? Can I JSON.stringify it?

**Comment by sam-gc** [comment]
Hi @marcusx2, you will only be able to get a credential from an error in very specific circumstances (for example, for the `auth/account-exists-with-different-credential` errors). Outside of that, the error will not contain a credential---for example your comment mentions "popup blocked" errors.

**Comment by marcusx2** [comment]
@sam-gc How can I even get this error? I am trying to log in with wrong credentials. I'm not able to sign in as expected, but I don't get the error, the popup simply says the credentials are wrong until I type the correct credentials and I sign in correctly. How can I emulate this error? Thanks!

**Comment by sam-gc** [comment]
That error occurs when you use one provider to sign in with an email account that's already been used to sign in with a different provider. For example, if you first sign in with a GitHub provider using email foo@bar.test, then you try to sign in with a Facebook provider using the same email (foo@bar.test), the SDK will throw an account-exists-with-different-credentials error.

**Comment by marcusx2** [comment]
Thanks. Quick question, how can credentialFromResult ever return null? Only if the userCredential is null?

**Comment by sam-gc** [comment]
`credentialFromResult` will return `null` if the credential passed in was obtained from a different provider (so for example, if you obtain a `UserCredential` from the phone auth sign in flow, then you call `GoogleAuthProvider.credentialFromResult()` with that credential, it will yield `null`.

**Comment by marcusx2** [comment]
> That error occurs when you use one provider to sign in with an email account that's already been used to sign in with a different provider. For example, if you first sign in with a GitHub provider using email [foo@bar.test](mailto:foo@bar.test), then you try to sign in with a Facebook provider using the same email ([foo@bar.test](mailto:foo@bar.test)), the SDK will throw an account-exists-with-different-credentials error.

I am not being able to get this error. I have a gmail account as one of the users. I tried signInWithEmailAndPassword using the same email and password of the gmail account. Instead of getting the error you described, I get `Firebase: Error (auth/wrong-password).`. T_T

**Comment by sam-gc** [comment]
Whether or not you get that error depends on multiple factors, including:
1) The provider
2) Whether or not the email is verified
3) The order of the sign-in operations

Please take a look at this documentation, it should hopefully make the behavior more clear: https://firebase.google.com/docs/auth/users#verified_email_addresses
