### ISSUE TITLE
FirebaseError: AppCheck: Fetch server (appCheck/fetch-status-error)

### ISSUE THREAD

**Issue by mehmet-cpu** [firebase/firebase-js-sdk#6239]
* Operating System version: Lenovo i5
  * Browser version: Chrome 101.0.4951.54 (Official Build) (64)
  * Firebase SDK version: 9.7.0
  * Firebase Product:  app-check

I have two websites connected to a project in Firebase console, both are logged in with phone registration, I designed my first website with v8 codes and it works fine. I wrote my second website with v9 codes and it works perfectly, but when I deploy my website and observe the login page through the console, "Failed to load resource: the server responded with a status of 403 () " and " FirebaseError: AppCheck: Fetch server (HTTP status: 403 . (appCheck/fetch-status-error))" errors. I can't login with real phone number but i can login with test number. When I examined the Google console, I saw that OAuth 2.0 Client IDs were generated for my first website connected to my project, and I noticed that there was no such result for my second website. I created "OAuth 2.0 Client IDs" for my second website and added my website's firebase url extensions. I expected the result to change, but found that I kept getting the same errors. At the root of this question I'm thinking of a PERMISSION DENIED situation and I've reconsidered all the uids, it's in my first and second websites but I haven't noticed a faulty situation so far. What could be the reason for such a situation?

#### Steps to reproduce:
Failed to load resource: the server responded with a status of 403 () "https://content-firebaseappcheck.googleapis.com/v1/projects/myapp075/apps/1:********************:web:***********************a:exchangeRecaptchaV3Token?key=********************************"
[2022-05-06T04:26:27.211Z]  https://www.gstatic.com/firebasejs/9.7.0/firebase-app.js-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).
    at exchangeToken (client.ts:75:25)
    at async ReCaptchaV3Provider.getToken (providers.ts:78:16)
    at async getToken$2 (internal-api.ts:140:13)
    at async Refresher.operation (internal-api.ts:272:18)
    at async Refresher.process (proactive-refresh.ts:77:7)
#### Relevant Code:

```
        <script type="module">

            
            import { initializeApp } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-app.js";
            import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-analytics.js";
            import { getAuth, onAuthStateChanged , RecaptchaVerifier, signInWithPhoneNumber } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-auth.js";
            import { getFirestore, doc, getDoc, setDoc, updateDoc, Timestamp } from  "https://www.gstatic.com/firebasejs/9.7.0/firebase-firestore.js";
            import { initializeAppCheck, ReCaptchaV3Provider } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-app-check.js";

            const firebaseConfig = {
                apiKey: "********",
                authDomain: "***",
                databaseURL: "***",
                projectId: "**",
                storageBucket: "**",
                messagingSenderId: "**",
                appId: "**",
                measurementId: "**"
            };

            const firebaseApp = initializeApp(firebaseConfig);
            const analytics = getAnalytics(firebaseApp);
            const db = getFirestore(firebaseApp);


            const appCheck = initializeAppCheck(firebaseApp, {
                provider: new ReCaptchaV3Provider('******************************************'),
                isTokenAutoRefreshEnabled: true
            });
            const auth = getAuth(firebaseApp);

            window.recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', {}, auth);
            recaptchaVerifier.render().then((widgetId) => {
                window.recaptchaWidgetId = widgetId;
            });


            window.myPhoneSend5 = async()=>{
                phoneNumber = document.getElementById("phoneNumberInput").value;
                const appVerifier = window.recaptchaVerifier;

                if(phoneNumber == "") {
                    alert("Please write the phone number");
                }else {              
                    signInWithPhoneNumber(auth, phoneNumber, appVerifier)
                    .then((confirmationResult) => {
                        window.confirmationResult = confirmationResult;
                        document.getElementById("pgndrld").style.display = "block";
                    }).catch(() => {
                        grecaptcha.reset(window.recaptchaWidgetId);
                    });

                }
            }

        </script>
```

**Comment by mehmet-cpu** [comment]
iI solved the problem, I was having this problem for two missing reasons.
First, I did not add the domains of my second website in the "Authorized domains" section of the Firebase Console.
The second reason is that I filled in the new "Client ID for Web application" incorrectly that I created in the "OAuth 2.0 Client IDs" section for my second website in my project on the Google Console where my two websites are connected.

**Comment by mehmet-cpu** [comment]
> * Operating System version: Lenovo i5
> * Browser version: Chrome 101.0.4951.54 (Official Build) (64)
> * Firebase SDK version: 9.7.0
> * Firebase Product:  app-check
> 
> I have two websites connected to a project in Firebase console, both are logged in with phone registration, I designed my first website with v8 codes and it works fine. I wrote my second website with v9 codes and it works perfectly, but when I deploy my website and observe the login page through the console, "Failed to load resource: the server responded with a status of 403 () " and " FirebaseError: AppCheck: Fetch server (HTTP status: 403 . (appCheck/fetch-status-error))" errors. I can't login with real phone number but i can login with test number. When I examined the Google console, I saw that OAuth 2.0 Client IDs were generated for my first website connected to my project, and I noticed that there was no such result for my second website. I created "OAuth 2.0 Client IDs" for my second website and added my website's firebase url extensions. I expected the result to change, but found that I kept getting the same errors. At the root of this question I'm thinking of a PERMISSION DENIED situation and I've reconsidered all the uids, it's in my first and second websites but I haven't noticed a faulty situation so far. What could be the reason for such a situation?
> 
> #### Steps to reproduce:
> Failed to load resource: the server responded with a status of 403 () "https://content-firebaseappcheck.googleapis.com/v1/projects/myapp075/apps/1:********************:web:***********************a:exchangeRecaptchaV3Token?key=********************************" [2022-05-06T04:26:27.211Z] https://www.gstatic.com/firebasejs/9.7.0/firebase-app.js-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error). at exchangeToken (client.ts:75:25) at async ReCaptchaV3Provider.getToken (providers.ts:78:16) at async getToken$2 (internal-api.ts:140:13) at async Refresher.operation (internal-api.ts:272:18) at async Refresher.process (proactive-refresh.ts:77:7)
> 
> #### Relevant Code:
> ```
>         <script type="module">
> 
>             
>             import { initializeApp } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-app.js";
>             import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-analytics.js";
>             import { getAuth, onAuthStateChanged , RecaptchaVerifier, signInWithPhoneNumber } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-auth.js";
>             import { getFirestore, doc, getDoc, setDoc, updateDoc, Timestamp } from  "https://www.gstatic.com/firebasejs/9.7.0/firebase-firestore.js";
>             import { initializeAppCheck, ReCaptchaV3Provider } from "https://www.gstatic.com/firebasejs/9.7.0/firebase-app-check.js";
> 
>             const firebaseConfig = {
>                 apiKey: "********",
>                 authDomain: "***",
>                 databaseURL: "***",
>                 projectId: "**",
>                 storageBucket: "**",
>                 messagingSenderId: "**",
>                 appId: "**",
>                 measurementId: "**"
>             };
> 
>             const firebaseApp = initializeApp(firebaseConfig);
>             const analytics = getAnalytics(firebaseApp);
>             const db = getFirestore(firebaseApp);
> 
> 
>             const appCheck = initializeAppCheck(firebaseApp, {
>                 provider: new ReCaptchaV3Provider('******************************************'),
>                 isTokenAutoRefreshEnabled: true
>             });
>             const auth = getAuth(firebaseApp);
> 
>             window.recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', {}, auth);
>             recaptchaVerifier.render().then((widgetId) => {
>                 window.recaptchaWidgetId = widgetId;
>             });
> 
> 
>             window.myPhoneSend5 = async()=>{
>                 phoneNumber = document.getElementById("phoneNumberInput").value;
>                 const appVerifier = window.recaptchaVerifier;
> 
>                 if(phoneNumber == "") {
>                     alert("Please write the phone number");
>                 }else {              
>                     signInWithPhoneNumber(auth, phoneNumber, appVerifier)
>                     .then((confirmationResult) => {
>                         window.confirmationResult = confirmationResult;
>                         document.getElementById("pgndrld").style.display = "block";
>                     }).catch(() => {
>                         grecaptcha.reset(window.recaptchaWidgetId);
>                     });
> 
>                 }
>             }
> 
>         </script>
> ```
i solved the problem, I was having this problem for two missing reasons.
First, I did not add the domains of my second website in the "Authorized domains" section of the Firebase Console.
The second reason is that I filled in the new "Client ID for Web application" incorrectly that I created in the "OAuth 2.0 Client IDs" section for my second website in my project on the Google Console where my two websites are connected.

**Comment by jbalidiong** [comment]
Hi @mehmet-cpu, thanks for reaching out. I noticed that you've already fixed the issue you've raised on App Check. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.

**Comment by mehmet-cpu** [comment]
Thank you bro 🖖

6 May 2022 Cum 18:40 tarihinde jbalidiong ***@***.***> şunu
yazdı:
