### ISSUE TITLE
Call to getRedirectResult after authenticating is very slow

### ISSUE THREAD

**Issue by marksalpeter** [firebase/firebase-js-sdk#6240]
### [REQUIRED] Describe your environment

  * Operating System version: OS X Mojave 
  * Browser version: all
  * Firebase SDK version: latest
  * Firebase Product: auth

### [REQUIRED] Describe the problem
getRedirectResult Is so slow that it causes the need for a loading spinner to run for a few seconds after authentication. This is providing quite a bad and unprofessional looking user experience. 

#### Steps to reproduce:
1. Call getRedirectResult
2. Wait several seconds when there’s no need

#### What I would like to see instead
1. After a successful auth, the user is redirected immediately to a successful auth url
2. After an unsuccessful auth the user is redirected to a page displaying an error message

Surely there must be a simple way to do this. Perhaps it’s configurable on the back end and I’m just missing something? It’s so obviously how the redirect style of authentication needs to work that it’s in the oAuth design spec. Anything short of this is delivering a glitchy looking, hacked together user experience.

**Comment by sam-gc** [comment]
Hi @marksalpeter, would you please share a code snippet demonstrating this behavior?

As an aside---the redirect flow goes through an intermediate URL (https://<your-project\>.firebaseapp.com/__/auth/handler) on the way in and out from the OAuth flow. It is this handler that actually performs the OAuth. The JS SDK obtains the credentials from that domain in a different manner. This is how we can make the code be so seamless.

If we can't determine an obvious solution to the delay you're seeing, you may want to manually sign in with your OAuth provider outside of the Firebase SDK, then call [`signInWithCredential()`](https://firebase.google.com/docs/reference/js/auth.md#signinwithcredential), as described in these docs: https://firebase.google.com/docs/auth/web/google-signin#advanced:-handle-the-sign-in-flow-manually
