### ISSUE TITLE
The `accessToken` property is missing in the `User` interface

### ISSUE THREAD

**Issue by levensta** [firebase/firebase-js-sdk#6241]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Firefox 100.0
  * Firebase SDK version: 9.7.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
The `accessToken` property is present in the User obj but is missing from the [User interface](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L21-L81) and also the [documentation](https://firebase.google.com/docs/reference/js/auth.user)

#### Steps to reproduce:
The User object from `UserCredential` contains the necessary `accessToken` property, but to get it, you need to convert the `UserCredential` type to `any`

#### Relevant Code:
```typescript
createUserWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    const { user } = userCredential;
    // TS2339: Property 'accessToken' does not exist on type 'User'.
    console.log(user.accessToken);
  });
```

**Comment by sam-gc** [comment]
Hi @levensta, thanks for reaching out--

There are 3 tokens at play here:
1. The Firebase ID token (publicly exposed via `user.getIdToken()`). 
2. The Firebase refresh token (not exposed to client code via interface, and won't ever be made easily accessible)
3. OAuth providers' `accessToken` field. This is provided by the OAuth credential itself but is not stored on the User object

Which of these are you trying to use?

**Comment by JGSolutions** [comment]
How can we get an expired accessToken through the firebase Auth?
