### ISSUE TITLE
Packagephobia crashes on `@firebase/firestore` and `firebase` 9.8.0

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-js-sdk#6249]
### [REQUIRED] Describe your environment

  * Operating System version: --
  * Browser version: --
  * Firebase SDK version: 9.8.0
  * Firebase Product: firestore

#### Steps to reproduce:

Visit `packagephobia.com` and enter `firebase` or `@firebase/firestore`.

Alternatively, visit https://packagephobia.com/result?p=%40firebase%2Ffirestore

**Expected:**

- I get information about the package

**Actual:**

- 500 or other error

PackagePhobia is a useful tool for checking eg. the size of new releases. I use it often.

This could be a problem at their end, of course, but it would also make sense to have good results for any Firebase releases, so I filed the bug here. Maybe you can be in touch with them. Perhaps there's something in the `@firebase/firestore` package that they cannot parse.

`@firebase/auth` and `@firebase/app` work fine.

**Comment by cherylEnkidu** [comment]
Hi akauppi,

Thanks for reporting this! We'll consider looking at it in the future if there is a lot of demand for it.

**Comment by bsplosion** [comment]
This appears to be fixed on their end now.
