### ISSUE TITLE
onAuthStateChanged error callback never triggers

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#6254]
I can only catch errors if I do something like `signInWithEmailAndPassword(auth, email, password).catch((error) => {});`. However if I remove the catch and try to catch the error on the error callback of [onauthstatechanged](https://firebase.google.com/docs/reference/js/auth#onauthstatechanged), it doesn't work. The error callback never runs.

**Comment by sam-gc** [comment]
Hi @marcusx2, thanks for bringing this to our attention. The `error` and `completed` parameters are not used by the SDK and we will update our docs to note that it is deprecated.

**Comment by marcusx2** [comment]
Really? Is this true for every similar method of the API? For example, this [method overload](https://firebase.google.com/docs/reference/js/firestore_.md#onsnapshot) of onSnapshot also has the `error` and `completed` parameters

**Comment by hsubox76** [comment]
No, `onSnapshot()`'s error method does work as described in the docs there. The `complete` method does not, as also documented there (although in that signature it should say `complete` instead of `onCompletion`).

FYI the overload you've linked to actually doesn't take the error handling function directly as a param, it takes an `Observer` as the second param, which can have an `error` property with an error function. There's also an [additional overload here](https://firebase.google.com/docs/reference/js/firestore_.md#onsnapshot_4) that takes an error handling function directly as the 4th param (referred to in the docs as `onError`). These both do the same thing, the Observer signature is just there if users have a preference for the Observer pattern.

**Comment by MerovingianByte** [comment]
> FYI the overload you've linked to actually doesn't take the error handling function directly as a param, it takes an `Observer` as the second param, which can have an `error` property with an error function. 

Can you show me a quick example of error handling using the onauthstatechanged based on [this tutorial](https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user)? Very much appreciated, thanks!

**Comment by marcusx2** [comment]
> FYI the overload you've linked to actually doesn't take the error handling function directly as a param, it takes an Observer as the second param, which can have an error property with an error function.

Can you show me a quick example? Thank you for your time.

**Comment by sam-gc** [comment]
These two are equivalent:

```js
function onNext(snap) { ... }
function onError(error) { ... }

onSnapshot(docRef, {/* options object */}, onNext, onError);
onSnapshot(docRef, {next: onNext, error: onError});
```

Note that in the first example, you pass a [SnapshotListenOptions](https://firebase.google.com/docs/reference/js/firestore_.snapshotlistenoptions.md#snapshotlistenoptions_interface) object that isn't present in the second example. In the second example, that second parameter is instead an observer (an object containing a snapshot callback and an error callback).

**Comment by marcusx2** [comment]
@sam-gc Oh sorry I think I misread what @hsubox76 said. So you can't do error handling with onAuthStateChanged at all?

**Comment by sam-gc** [comment]
That's correct. You should catch the errors as they occur from the sign in functions themselves

**Comment by marcusx2** [comment]
@sam-gc Why is using the onAuthStateChanged the recommended way then? The docs say "The recommended way to get the current user is by setting an observer on the Auth object:", but you can't even catch any errors using it.

**Comment by sam-gc** [comment]
Yes, the recommended way for obtaining the current user is through that method. You can also obtain the user from the result of any of the authentication methods. You can think of `onAuthStateChanged` as the source of truth for the current user (or lack thereof) as it will react to any changes across the SDK. On the other hand, errors will always be local to the place where they're thrown (as they'd be significantly less useful if they were piped through a global context like `onAuthStateChanged`)

**Comment by hsubox76** [comment]
Docs have been updated. https://firebase.google.com/docs/reference/js/auth.md#onauthstatechanged
