### ISSUE TITLE
Missing usePublicVapidKey in firebase.messaging when import from firebase/app module

### ISSUE THREAD

**Issue by 6r1anchen** [firebase/firebase-js-sdk#628]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.4
  * Firebase SDK version: 4.12.1
  * Firebase Product: messaging

#### Steps to reproduce:

1. `yarn install firebase`
2. Import core module `firebase/app` and optional `firebase/messaging` in `ts` file
3. Try to use `usePublicVapidKey` method of `firebase.messaging.Messaging`
4. Get `tsc`(v2.4.2) error message: 
`Property 'usePublicVapidKey' does not exist on type 'Messaging'.`

If I changed to `import * as firebase from 'firebase'`, then it will use firebase/index.d.ts, which includes `usePublicVapidKey` under `Messaging` interface.
I was trying to follow the documentation from [here](https://github.com/firebase/firebase-js-sdk/tree/master/packages/firebase) to only include necessary service module from `firebase`.
Is the documentation update to date in this case?

#### Relevant Code:

```typescript

import * as firebase from 'firebase/app';
import 'firebase/messaging';

firebase.initializeApp({});
const messaging = firebase.messaging();
messaging.usePublicVapidKey("key");

```

There is no `usePublicVapidKey` defined in [firebase/app/index.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/app/index.d.ts#L505)

Related to #562 and PR #563

**Comment by zhouheidz** [comment]
I also have this error for a few weeks now.

**Comment by jshcrowthe** [comment]
Hey there! Can you reproduce this behavior using the `firebase@next` tag on NPM?

**Comment by jshcrowthe** [comment]
Gotcha. I think this issue will be fixed in the next release (so you can continue relying on the `firebase/app` entrypoint)

Thanks!

**Comment by 6r1anchen** [comment]
@jshcrowthe Sorry for late replay. Thanks for information.
Works as expected with `firebase@4.13.1`.
