### ISSUE TITLE
httpsCallable error code format change from v8 to v9 should be warned loudly

### ISSUE THREAD

**Issue by qqpann** [firebase/firebase-js-sdk#6281]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

v8:
https://github.com/firebase/firebase-js-sdk/blob/919413cd06478365e306476c8eb2ad2aa1f2d3ee/packages/functions/test/callable.test.ts#L50

v9:
https://github.com/firebase/firebase-js-sdk/blob/cdada6c68f9740d13dd6674bcb658e28e68253b6/packages/functions-compat/src/callable.test.ts#L40

The change of error code format (it attaches "functions/" at the beginning since v9) is not mentioned in the v8 v9 migration guide. It should be well announced in the documentation.
Otherwise, if a user relies on the error code string in their app, the upgrade will cause a crush (like me 😢 ).

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by ishowta** [comment]
On the other hand, error code in firestore does not have a prefix, which seems inconsistent with functions one.

**Comment by hsubox76** [comment]
That can be done, but we need to keep the non-prefixed type around as a param type for the FunctionsError constructor here: https://github.com/firebase/firebase-js-sdk/blob/cdada6c68f9740d13dd6674bcb658e28e68253b6/packages/functions/src/error.ts#L61

Seems like there's [a fancy Typescript way](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) of making a type that extends that type and adds the prefix, which can be used as the public type for FunctionsError. Feel free to make a PR or I will try to get to it when I can.

> On the other hand, error code in firestore does not have a prefix, which seems inconsistent with functions one.

I think we try to wrap every error thrown by an SDK in the appropriate custom error wrapper for that product, but we may have missed some or not caught some errors that aren't thrown directly by the SDK code.
