### ISSUE TITLE
Cordova Google Auth fails the first time round to produce a result (subsequent times work)

### ISSUE THREAD

**Issue by jpike88** [firebase/firebase-js-sdk#6282]
### [REQUIRED] Describe your environment

CORDOVA iOS

#### Steps to reproduce:
signInWithRedirect correctly created a popup and lets me sign into Google, but first time round getRedirectResult fails with a null result.

For some reason jogging it a second time works.

Spent a lot of time trying to diagnose the issue but unable to. It's almost definitely an issue with the firebase library though, as if I refresh the 'browser', the problem happens again.

Investigating behaviour of related Cordova plugins seem to show consistent behaviour, it's likely a problem with the state management of the firebase Cordova auth popup redirect handling logic. Jogging signInWithRedirect once returns a null result, which always happens the first time it runs and seems to create the conditions for subsequent calls to work.  

The below code snippet shows how I've placed a workaround in there to 'jog' it the second time round, and it returns a proper result that time.

```javascript

import {
	getRedirectResult,
	signInWithRedirect,
	GoogleAuthProvider,
} from '@firebase/auth/cordova';

       const auth = getAuth(Environment.firebaseInstance);
	const provider = new GoogleAuthProvider();
	await signInWithRedirect(auth, provider);
	const result = await getRedirectResult(auth);

	if (!result) {
		// jog it again because firebase is deciding that there is no result the first time
		await signInWithRedirect(auth, provider);
		result = await getRedirectResult(auth);
	}
```

**Comment by jbalidiong** [comment]
Hi @jpike88, thanks for reaching out. I have a limited knowledge on Cordova, could you provide a minimal repro or similar that recreates the behavior? If so we can probably sort it out fairly quickly. But we'd likely need to be able to run it locally to tinker with the logs and timing of things to determine what's failing.

**Comment by jpike88** [comment]
I've spent an ungodly amount of time trying to untangle the spaghetti and deprecated plugins in your Cordova implementation, and am now using https://github.com/russmedia-digital/cordova-plugin-google-signin instead. It works like a charm, you guys could learn a thing about how it's been implemented.

**Comment by jbalidiong** [comment]
Thanks for the feedback with our documentation. I'll communicate this with our engineers, we’ll check the docs affected especially if there are deprecated plugins. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
