### ISSUE TITLE
Can't disable page_view auto-logging

### ISSUE THREAD

**Issue by klocus** [firebase/firebase-js-sdk#6284]
### Describe your environment

  * Operating System version: macOS 12.13.1
  * Browser version: Chrome/100.0.4896.127
  * Firebase SDK version: 9.8.1
  * Firebase Product: Analytics

### Describe the problem
I'm creating a single page web app, so I don't want sending the auto-events with page title. Despite disabling the automatic logging of "page_view", this event is still sent.

#### Steps to reproduce:
Just try disable auto-logging `page_view`. 

#### Relevant Code:

```javascript
this.firebase = initializeApp(ApplicationConfig.firebase);
initializeAnalytics(this.firebase, {
  config: {
    send_page_view: false // disable auto-logging
  }
});
this.analytics = getAnalytics(this.firebase);
```

**Comment by jbalidiong** [comment]
Hi @klocus, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the same behavior. I tried using the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) to see if I'm logging the `page_view` automatically. Can you confirm if you're seeing the logs for `page_view` with the parameter `send_page_view` set to false?

**Comment by klocus** [comment]
Hi @jbalidiong , thanks for reply. I noticed that after my "manual" page_view log event, there is also second one with the page title from the `<title>` tag.

![Zrzut ekranu 2022-05-20 o 18 10 22](https://user-images.githubusercontent.com/2962987/169569881-59b779f6-cfc1-4193-99f3-65325d9c10e5.png)

![Zrzut ekranu 2022-05-20 o 18 10 48](https://user-images.githubusercontent.com/2962987/169569900-00cdcea7-3988-4e1c-9fb6-236a7d084e47.png)

**Comment by jbalidiong** [comment]
I was able to reproduce the behavior now. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by dwyfrequency** [comment]
@jbalidiong can you add the code you used to replicate this issue?

**Comment by dwyfrequency** [comment]
@klocus are you using react for this as well? If so, I believe this has to do with `React.StrictMode` https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects. Per React's documentation, 

```
Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:

- Class component constructor, render, and shouldComponentUpdate methods
- Class component static getDerivedStateFromProps method
- Function component bodies
- State updater functions (the first argument to setState)
- Functions passed to useState, useMemo, or useReducer

Note: This only applies to development mode. Lifecycles will not be double-invoked in production mode.
```

If you move your logEvent outside of strict mode or run it in production, you should see it only being called once.

**Comment by klocus** [comment]
@dwyfrequency I'm using Angular.
