### ISSUE TITLE
No 2FA prompts on iPhone when signing in to a Google account

### ISSUE THREAD

**Issue by rorencio** [firebase/firebase-js-sdk#6285]
### Describe your environment

  * Operating System version: Any
  * Browser version: Any
  * Firebase SDK version: 9.8.1
  * Firebase Product: auth

#### Steps to reproduce:

1) Setup an auth system with Google as a sign in provider. 
2) Get an user that has 2FA enabled using Google prompts (Tap Yes to allow sign-in) on an iPhone.
3) Try to sign in into the Firebase app on any device (use incognito mode to force a new sign-in).
4) You'll see that no prompt appears on the iPhone, it directly asks for a backup code (if not other 2FA methods configured).

This only happens when signing in directly to the Firebase app, but not when signing in to Google normally. It works perfectly for users owning an Android phone with 2FA enabled via prompts.

#### Relevant Code:
This is the code I use for setting up the auth provider:
```javascript
      const provider = new GoogleAuthProvider()
      provider.setCustomParameters({ hd: 'example.org' })
      signInWithRedirect(auth, provider)
```

**Comment by sam-gc** [comment]
Does this happen outside of incognito mode? I'm wondering if incognito mode prevents the Google page from knowing that it's on an iOS device.

**Comment by rorencio** [comment]
It happens on **any device running any OS**, regardless if incognito mode is being used or not, when the user has to perform a fresh sign in. It even happens on desktop computers. The purpose of the iPhone may only be to confirm the sign-in (Tap Yes to allow sign-in).

**Comment by sam-gc** [comment]
I see, thanks for the clarification.

**Comment by rorencio** [comment]
It seems to be working now, but I am not 100% sure. I've changed a setting for my application in Google Admin, under Security > API Controls > App Access Control (https://admin.google.com/u/3/ac/owl/list?tab=apps).

I have marked my application as Trusted:
![imatge](https://user-images.githubusercontent.com/12188187/170095900-184bb8cf-cf53-4ce0-a62f-f68ba5140ae9.png)

**Comment by sam-gc** [comment]
Thanks for the update. I suspect that this is related to the Google Sign In side instead of the Firebase JS SDK side, but that's just a hunch. Since the issue appears to have resolved itself, I'm going to go ahead and close out this issue. If the broken behavior recurs, please reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) as it may have something specifically to do with project configuration
