### ISSUE TITLE
providerId is null on signInWithPopup

### ISSUE THREAD

**Issue by sushant-at-nitor** [firebase/firebase-js-sdk#6286]
### Describe your environment

  * Operating System version: Windows WSL
  * Browser version: Brave
  * Firebase SDK version: 9.8.1
  * Firebase Product: auth

#### Steps to reproduce:
- Enable web flow for firebase project
- initialize firebase app
- Sign in using google provider with `signInWithPopup`
#### Relevant Code:

```javascript
const googleAuthProvider = new GoogleAuthProvider();
const response = await signInWithPopup(
      getAuth(AppFirebase.firebaseApp),
      googleAuthProvider,
    );
```

![image](https://user-images.githubusercontent.com/33436891/169656438-28b239d3-da7a-487b-8334-e8dca4019b16.png)

**Comment by sam-gc** [comment]
Hi @sushant-at-nitor, does this happen in other browsers aside from Brave?

**Comment by sushant-at-nitor** [comment]
yes it does, I checked on Edge

**Comment by sam-gc** [comment]
Can you share a longer example? (I.e. how are you importing these symbols)

Does the URL of the handler have a providerId parameter?

**Comment by sushant-at-nitor** [comment]
The URL does not have `providerId`

https://example1-app.firebaseapp.com/__/auth/handler?apiKey=<apiKey>&appName=%5BDEFAULT%5D&authType=signInViaPopup&redirectUrl=http%3A%2F%2Flocalhost%3A9001%2F&v=9.8.1&eventId=5061736319

-firebase.ts
```javascript
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAnalytics } from "firebase/analytics";
import { getStorage } from "firebase/storage";
import { getAuth } from "firebase/auth";

// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: <api-key>,
  authDomain: "example1-app.firebaseapp.com",
  projectId: "example1-app",
  storageBucket: "example1-app.appspot.com",
  messagingSenderId: <messagingSenderId>,
  appId: <appId>,
  measurementId: <measurementId>,
};

const firebaseApp = initializeApp(firebaseConfig);
const firestoreDb = getFirestore(firebaseApp);
const firebaseAnalytics = getAnalytics(firebaseApp);
const firebaseStorage = getStorage(firebaseApp);
const firebaseAuth = getAuth(firebaseApp);

export default {
  firebaseAnalytics,
  firebaseApp,
  firestoreDb,
  firebaseStorage,
  firebaseAuth,
};

```
- login.tsx

```javascript

import { GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import FirebaseApp from './firebase';

export const Login = () => {
  const login = async () => {
    const googleAuthProvider = new GoogleAuthProvider();
    const response = await signInWithPopup(
      firebaseAuth,
      googleAuthProvider,
    );
  };
}
```

**Comment by sam-gc** [comment]
The only thing I can think of is that this branch isn't getting triggered:
https://github.com/firebase/firebase-js-sdk/blob/71d521627cea3ef178735b663ab3baea7efc83e3/packages/auth/src/core/util/handler.ts#L77-L79

But I have no idea why, since you're importing everything from the same package and `signInWithPopup`/`GoogleAuthProvider` are imported in the same file

**Comment by sushant-at-nitor** [comment]
This is resolved, as I am using a micro frontend setup. I need to initialize the app for every frontend explicitly
