### ISSUE TITLE
FR: Strong typing `query`, `orderBy` and `where`

### ISSUE THREAD

**Issue by tianhuil** [firebase/firebase-js-sdk#6288]
Can we incorporate strong typing into `query`, `orderBy` and `where`?   For example, I would like `query` and `where` to automatically work for these:

```ts
const col = ... as CollectionReference<{s: string; o: {n: number}; a: number[]}>

query(col, where('s', 'in', ['a', 'b'])) // is correctly typed
query(col, where('o', '==', {n: 2})) // is correctly typed
query(col, where('a', 'array-contains', 2)) // is correctly typed
query(col, where('a', 'array-contains-any', [2, 3])) // is correctly typed

query(col, where('s', '==', 2)) // is *incorrectly* typed
query(col, where('s', '==', ['a'])) // is *incorrectly* typed
```

The `update` function already has strong typing (through `UpdateData`).  Ideally, we would have the same strong typing for `where`.  I've created a thin layer that implements strong typing `query`, `orderBy` and `where` to demonstrate this: https://github.com/tianhuil/firebase-proto

It has type assertions to verify correctness ([see this file](https://github.com/tianhuil/firebase-proto/blob/main/assert/where.ts))

Would you be open to me adding this directly to firebase?

### [REQUIRED] Describe your environment

  * Operating System version: N/A
  * Browser version: N/A
  * Firebase SDK version: N/A
  * Firebase Product: database

### [REQUIRED] Describe the problem
See above

#### Steps to reproduce:
See above

#### Relevant Code:
See above

Sorry for the cross-post with https://github.com/firebase/firebase-js-sdk/discussions/6287

**Comment by ehsannas** [comment]
Thanks @tianhuil for the suggestion and for your code sample. We are going to take note of this and prioritize against other projects. Googlers, follow b/233781280 for further work.
