### ISSUE TITLE
app.functions() service causes app.delete() to fail

### ISSUE THREAD

**Issue by ampatspell** [firebase/firebase-js-sdk#630]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 10.12.6
  * Firebase SDK version: 4.12.1
  * Firebase Product: functions

### [REQUIRED] Describe the problem

```
Uncaught (in promise) TypeError: Cannot read property 'delete' of undefined
    at firebaseApp.js:79
    at Array.map (<anonymous>)
    at firebaseApp.js:78
```

```javascript
FirebaseAppImpl.prototype.delete = function() {
  ...
  services.map(...
    return service.INTERNAL.delete();
}
```

`functions/src/api/service.ts` is missing `INTERNAL.delete()`

#### Steps to reproduce:

```javascript
document.addEventListener('DOMContentLoaded', function() {
  let app = firebase.app();
  let functions = app.functions();
  app.delete();
});
```

**Comment by hsubox76** [comment]
I think this was fixed by https://github.com/firebase/firebase-js-sdk/pull/1687.
