### ISSUE TITLE
Auth: migration from localstorage to indexedDb not good when used in iframe

### ISSUE THREAD

**Issue by RomainVialard** [firebase/firebase-js-sdk#631]
### [REQUIRED] Describe your environment

  * Firebase SDK version: 4.12.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Between SDK version 4.11 & 4.12, it was decided to migrate auth storage from localstorage to indexedDb (see PR #530).

I am using the Firebase JS SDK inside an **iframe** and this migration is causing issues when trying to authenticate to Firebase (using method signInWithCustomToken() but I'm assuming the issue happens with all sign-in methods as it is related to client side storage).

Specifically, between 4.11 & 4.12, authentication now fails with an indexedDb error if:
- In Chrome: third-party cookies are blocked (not default)
- In Safari: cookies are set to "Allow from websites I visit". Switching to "Always allow" fixes the issue (but default setting is "Allow from websites I visit")

Error thrown by Safari:
SecurityError: IDBFactory.open() called in an invalid security context

**Comment by bojeil-google** [comment]
Thanks for reporting. We'll look into the errors when indexedDB is not functional.

**Comment by bojeil-google** [comment]
We will add a fallback to localStorage when indexedDB fails to open with an error.

Regarding Safari iframes, you are expected to have visited the site in a top level window as you mentioned. This is a limitation that Safari set. Safari also uses intelligent tracking (to protect privacy) and will clear cookies and data in your iframe after a certain period of time. There are a lot of issues which even localStorage won't solve.

There are many reasons we switched to `indexedDB`, and one major reason is the compatibility with service workers which all major modern browsers are now supporting including Apple which [has finally started supporting them](https://dev.to/ben/safari-now-supports-service-workers-and-what-that-means-to-me-at-least-3oi7). Going forward, Auth must be compatible with service workers.

**Comment by RomainVialard** [comment]
Thank you!

**Comment by dfischer** [comment]
Confirming I am seeing the same issue

**Comment by vieira** [comment]
Hello,

Has this been fixed in 4.13?

Thanks.

**Comment by wti806** [comment]
Yes. It should be fixed in 4.13.

**Comment by jshcrowthe** [comment]
Closing as it seems this has been fixed.
