### ISSUE TITLE
FirebaseError: Firebase: Error (auth/network-request-failed) while rendering recaptcha

### ISSUE THREAD

**Issue by TommyLeong** [firebase/firebase-js-sdk#6314]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Monterey 12.0.1 (21A559)
  * Browser version: Version 101.0.4951.64 (Official Build) (x86_64)
  * Firebase SDK version: "firebase": "^9.8.2"
  * Firebase Product: Auth

### [REQUIRED] Describe the problem
Trying to setup auth sign in using `signInWithPhoneNumber`, therefore required to setup reCAPTCHA in my web (next.js) project. I've managed to render it out, and able to receive SMS too.

However Im constantly receiving following error after some time. (Regardless before or after I tell that I'm not a Robot)
```
Uncaught (in promise) FirebaseError: Firebase: Error (auth/network-request-failed).
    at createErrorInternal (index-ccf9d100.js?940a:474:1)
    at _createError (index-ccf9d100.js?940a:448:1)
    at eval (index-ccf9d100.js?940a:7220:1)
```

#### Steps to reproduce:
1. Launch web
2. Recaptcha shows up
3. Leave the website there, say for about 20 - 30 seconds. 
4. Error shows up

![image](https://user-images.githubusercontent.com/9990179/170979392-3b314fbf-c46a-42db-a77d-568a1281c87a.png)

One thing I noticed is, if I do not execute the code `recaptchaVerifier.render()`, I will never hit this error. However, the recaptcha will not appear too.

#### Relevant Code:

```
try {
      window.recaptchaVerifier = new RecaptchaVerifier(
        'recaptcha-container',
        {
          size: 'normal',
          callback: async (response) => {
            // reCAPTCHA solved, allow signInWithPhoneNumber.
            // ...
            const appVerifier = window.recaptchaVerifier;

            await signInWithPhoneNumber(auth, phoneNumber, appVerifier)
              .then((confirmationResult) => {
                // SMS sent. Prompt user to type the code from the message, then sign the
                // user in with confirmationResult.confirm(code).

                console.log('should received SMS now');
                console.log('confirmationResult');
                console.log(confirmationResult);
              })
              .catch((error) => {
                console.log('Error; SMS not sent');
                console.log(error);
                grecaptcha.reset(window.recaptchaWidgetId);
                // Error; SMS not sent
                // ...
              });
          },
          'expired-callback': (response) => {
            // Response expired. Ask user to solve reCAPTCHA again.
            // ...
            console.log('reset captcha');
            grecaptcha.reset(window.recaptchaWidgetId);
          },
        },
        auth,
      );
    } catch (e) {
      console.log('verifier setup error');
      console.log(e);
    }

    try {
      recaptchaVerifier.render().then((widgetId) => {
        console.log('recaptchaVerifier.render()');
        console.log(widgetId);
        window.recaptchaWidgetId = widgetId;
      });
    } catch (e) {
      console.log('verifier render error');
      console.log(e);
    }

```

**Comment by TommyLeong** [comment]
I kind of "_resolved_" this issue by changing (copied from internet) my code as per following. Can't tell what's the major difference, aside from how `recaptchaVerifier` is being rendered.

**Before** 
I was creating `RecaptchaVerifier` directly on `window`
```
window.recaptchaVerifier = new RecaptchaVerifier(
        'recaptcha-container',
        {
```

**After**
Assigning it into variable, and render it.
```
const recaptchaVerifier = new RecaptchaVerifier(
      'recaptcha-container',
      {
```

Appreciate if someone could point out the exact issue. Thanks.
---

**Full sample code:**
```
const recaptchaVerifier = new RecaptchaVerifier(
      'recaptcha-container',
      {
        size: 'normal',
        callback: async (response) => {
          console.log(response);

          const appVerifier = recaptchaVerifier;
          console.log('appVerifier');
          console.log(appVerifier);

          await sendSmsToUser(auth, phoneNumber, appVerifier);
        },
      },
      auth,
    );
    let recaptchaWidgetId;
    recaptchaVerifier
      .render()
      .then((widgetId) => {
        recaptchaWidgetId = widgetId;
      })
      .catch(console.error);
```

**Comment by sam-gc** [comment]
Hi @TommyLeong, I can't reproduce this. I'm wondering if it has to do with the page re-rendering you mention in https://github.com/firebase/firebase-js-sdk/issues/6315 ? I'm wondering if it's an issue in next... Are you doing any form of SSR?

**Comment by TommyLeong** [comment]
Hi @sam-gc. Yes, using Next.js framework `"next": "12.1.5"`. Is SSR. 

I can identify the NETWORK_REQUEST_FAILED is thrown by a Promise within ReCaptchaLoaderImpl. But im not sure why, maybe because after 30 seconds, it is expired? (but im not verifying yet, just loaded the page and leave the verifier there)

**Line 7220**
![image](https://user-images.githubusercontent.com/9990179/171310686-3c2d2b1c-2a3b-44ed-9368-e0f46edb84bc.png)

**Comment by sam-gc** [comment]
Thanks for the extra info. I'm not super familiar with Next.js, but I suspect what's happening is the network request is failing in the SSR step (since reCAPTCHA requires a DOM environment to load, the load is timing out). Because of the delay, this would only manifest after page load when the timer runs out 30 seconds later (again, if I'm correctly understanding how Next.js works).

The `auth.settings.appVerificationDisabledForTesting` makes the SDK totally bypass reCAPTCHA, meaning this code will never run. It is not for use in production however.

**Comment by TommyLeong** [comment]
Alright, since the reCAPTCHA is somehow loaded. Would you agree that this error message can be ignored? 

After all,
1. reCAPTCHA is still loaded, user could still proceed with it
2. The SDK is trying to load reCAPTCHA in DOM env. No communication to any server behind scene, so technically it's not a "network-request-failed"

**Comment by sam-gc** [comment]
https://github.com/firebase/firebase-js-sdk/blob/497d34c8472a19cb8baca56985c98346e5a4727d/packages/auth/src/platform_browser/strategies/phone.ts#L245-L247
Yes, this is expected
