### ISSUE TITLE
FirebaseError: Firebase: Error (auth/argument-error) whenever screen is re-rendering

### ISSUE THREAD

**Issue by TommyLeong** [firebase/firebase-js-sdk#6315]
### [REQUIRED] Describe your environment

- Operating System version: MacOS Monterey 12.0.1 (21A559)
- Browser version: Version 101.0.4951.64 (Official Build) (x86_64)
- Firebase SDK version: "firebase": "^9.8.2"
- Firebase Product: Auth

### [REQUIRED] Describe the problem
Related to #6314. 
After user verified the recaptcha, received SMS and validate the OTP from firebase, the website tends to do a re-render to hide certain stuff (it's just my web logic). 

This action cause a re-rendering in the web, which means `new RecaptchaVerifier()` is being fired again. On the subsequent firing, the method keeps throwing this `argument-error` by this method `validateStartingState()` from Firebase. 

After diving into the code, what happened is the `<div id="recaptcha-container">` I've declared to render the captcha has 2 extra child of `<div></div><div></div>` inside, which caused `!this.container.hasChildNodes()` to return false.

![image](https://user-images.githubusercontent.com/9990179/171140408-000caf4d-9ffa-4c4f-9387-0d825d9ea9c7.png)

#### Steps to reproduce:
Explain as per above.

1. Render the recaptcha 1st time
2. Re-render the recaptcha again on 2nd time
3. Issue reproduce

#### Relevant Code:

```
const recaptchaVerifier = new RecaptchaVerifier(
      'recaptcha-container',
      {
        size: 'normal',
        callback: async (response) => {
          console.log(response);

          const appVerifier = recaptchaVerifier;
          console.log('appVerifier');
          console.log(appVerifier);

          await sendSmsToUser(auth, phoneNumber, appVerifier);
        },
      },
      auth,
    );
    let recaptchaWidgetId;
    recaptchaVerifier
      .render()
      .then((widgetId) => {
        recaptchaWidgetId = widgetId;
      })
      .catch(console.error);
```

**Comment by TommyLeong** [comment]
**An update**
while reporting this issue, I've identified a solution to overcome this, would appreciate someone to point if this is an appropriate solution.

**Temp Solution**
On every pre rendering of the recaptcha code, I overwrite the HTML by locating the Id. Sample code as per below.
```
document.getElementById('recaptcha-container').outerHTML =
      '<div id="recaptcha-container"></div>';

const recaptchaVerifier = new RecaptchaVerifier(
      'recaptcha-container',
....rest of the code....
);

```

**Comment by sam-gc** [comment]
Hi @TommyLeong, thanks for this. This is expected behavior -- when re-rendering the verifier is not removed and so the div is not empty. The correct behavior is to make sure that the div is empty when you do render the verifier (i.e. through the logic you've mentioned)

**Comment by TommyLeong** [comment]
Hi @sam-gc , thanks for replying. I see, meaning I should always make sure within the `<div id="recaptcha-container"></div>` is empty when I render the verifier?

**Comment by sam-gc** [comment]
Yep exactly
