### ISSUE TITLE
InvalidStateError and UnknownError on Firefox when opening IndexedDB 

### ISSUE THREAD

**Issue by kmjennison** [firebase/firebase-js-sdk#633]
### [REQUIRED] Describe your environment

  * Operating System version: Firefox 59.0.2
  * Firebase SDK version: 4.12.1
  * Firebase Product: auth

#### Steps to reproduce:

We're seeing errors in production that are preventing users from signing in. The errors are affecting exclusively Firefox users (not Chrome) and occurring at the [`onerror` event](https://github.com/firebase/firebase-js-sdk/blob/1b3ba41f7c5207907a32601e552168e29281948e/packages/auth/src/storage/indexeddb.js#L183) for initializing IndexedDB.

The errors are:
`UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.`
and
`InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

The `InvalidStateError` might be caused by private browsing mode in Firefox, as discussed in #627. However, none of the affected users have said they're using private browsing, and the volume of errors is higher than I'd expect if it's the sole cause. I'm not sure what else might be causing it.

I have not been able to reproduce the `UnknownError` and don't know what might be causing it.

Both errors have affected users on Firefox 58, 59, and 60. Some users have cleared their local site data and report that the problem persists.

The errors began when we upgraded from Firebase 4.10.0 to 4.12.0. We're now using 4.12.1.

Our app [initializes Firebase](https://github.com/gladly-team/tab/blob/master/web/src/js/authentication/firebaseConfig.js#L11) [here](https://github.com/gladly-team/tab/blob/master/web/src/index.js#L45). We're also using [firebaseui-web-react](https://github.com/firebase/firebaseui-web-react).

I apologize for not having steps to reproduce. If this is better suited for a support ticket, let me know.

**Comment by kmjennison** [comment]
@bojeil-google Might be a duplicate, but I'm skeptical that private browsing is the sole cause because of the high number of our app's users that are affected by it, none of whom have reported using private browsing.

In addition, I'm not seeing an `UnknownError` in Firefox private browsing, though that could be a distinct issue.

**Comment by kmjennison** [comment]
This is fixed in 4.13.0. Thanks!

**Comment by bojeil-google** [comment]
Thanks for confirming.
