### ISSUE TITLE
auth/handler.js not returning (ERR_EMPTY_RESPONSE) firebase library code in some users chrome browsers

### ISSUE THREAD

**Issue by jay-crest** [firebase/firebase-js-sdk#6337]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11 Pro 21H2
  * Browser version: chrome 102.0.5005.63
  * Firebase SDK version: ^9.8.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem
We are using SAML and when user click signin button we are invoking `signInWithRedirect(auth, samlProvider);`. But in some users chrome browsers https://[PROJECT-ID].firebaseapp.com/__/auth/handler.js is not returning firebase library code and because of that on SSO URL (octa) we are getting fireAuth is not defined error.

#### Relevant Code:
`import { initializeApp } from 'firebase/app';
import {
    getAuth,
    signInWithRedirect,
    signOut,
    SAMLAuthProvider,
    onIdTokenChanged
} from 'firebase/auth';
const firebaseConfig = {
    apiKey: process.env.REACT_APP_FIREBASE_APIKEY,
    authDomain: process.env.REACT_APP_FIREBASE_AUTHDOMAIN,
};

const firebaseApp = initializeApp(firebaseConfig);

const samlProvider = new SAMLAuthProvider(process.env.REACT_APP_FIREBASE_PROVIDERNAME!);

export const auth: any = getAuth(firebaseApp);

export const signInWithSamlRedirect = () => signInWithRedirect(auth, samlProvider);

export const signOutUser = async () => await signOut(auth);

export const onIdTokenChangedListener = (callback : (user: any) => void) => onIdTokenChanged(auth, callback);`

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jay-crest** [comment]
Hi @jbalidiong , Thanks for replying. I have hosted sample app on [https://login-test-47980.web.app/](url). It is working fine in my chrome browser.(version same as my collegue) but in some of my collegues chrome browser (102.0.5005.63 (Official Build) (64-bit)). It is generating error (no response) at [https://palo-alto-automation-portal.firebaseapp.com/__/auth/handler.js](url). Refer to below image. Seems like it is only in the chrome browser it is working fine in other browsers.
![image](https://user-images.githubusercontent.com/107025210/172444330-1bdc9460-e554-4df6-a807-93839329e500.png)

**Comment by sam-gc** [comment]
Hi @jay-crest, just have a couple more questions--

 1. Can you compare the handler URL from the browser it does work on to the browser it doesn't? On the browser that does work, this may require a little work to ensure you can capture the URL. You can use the "preserve log" checkbox: https://stackoverflow.com/questions/10987453/how-to-use-chromes-network-debugger-with-redirects
 2. For the user who sees the error, do they have third-party cookies disabled (or any other non-default flags set) in their browser?

**Comment by jay-crest** [comment]
Hi @sam-gc 
1 - It is same handler URL that we are hitting for both the cases. In my case i can access [https://palo-alto-automation-portal.firebaseapp.com/__/auth/handler.js](https://github.com/firebase/firebase-js-sdk/issues/url) but in the collegue chrome browser it can't be accessed. (Empty Response) and due to which the other redirects can't be done.
2 - They don't have any different setting on their browser. We have gone through reset settings and reinstalling the chrome browser as well.

**Comment by jay-crest** [comment]
@sam-gc  Issue is now resolved as those users have installed some plugins that was blocking the request to handler. Thanks for taking a look at it.
