### ISSUE TITLE
NotFoundError on Firefox when opening IndexedDB 

### ISSUE THREAD

**Issue by kmjennison** [firebase/firebase-js-sdk#634]
### [REQUIRED] Describe your environment

  * Operating System version: Firefox 59.0.2
  * Firebase SDK version: 4.12.1
  * Firebase Product: auth

#### Steps to reproduce:

We're seeing this error:
`NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.`

The error is affecting exclusively Firefox users (not Chrome) and occurring at the [onerror event](https://github.com/firebase/firebase-js-sdk/blob/1b3ba41f7c5207907a32601e552168e29281948e/packages/auth/src/storage/indexeddb.js#L183) for initializing IndexedDB. #633 is potentially related.

It looks like this happens when the Firebase IndexedDB exists but is missing the object store. To reproduce:

1. Go to https://kmjennison.github.io/firebase-idb-debug/ and open your dev console
2. Click "Create DB without object store"
3. Click "Initialize Firebase". You should see the error. At this point, the error will persist until you manually delete the DB or clear site data.

I'm unsure how the DB state became unsound for some users. In theory, Firebase could have opened the database in one window, and then Firebase initialized in another window before the first window finished creating the object store.

A fix for this could delete and recreate the database when encountering this error (code [here](https://github.com/kmjennison/firebase-js-sdk/pull/1/files)):

1. Go to https://kmjennison.github.io/firebase-idb-debug/ and open your dev console
2. Click "Create DB without object store"
3. Click "Initialize **modified** Firebase", which recreates the DB. You should not see any error.

If this error is affecting others and the approach to a fix looks okay, I'm happy to add tests and send a PR.

**Comment by bojeil-google** [comment]
Hey @kmjennison, thank you for reporting and investigating this.Your solution was extremely helpful. I am working on incorporating your fix and fixing the other reported issues. I will try to get it in asap. As for the other `indexedDB` issues, it is hard to tell in certain browser modes when `indexedDB` is available and when it is not without trying to open it and testing read/write access. We will add a mechanism to fallback to `localStorage` when that happens. Different browsers have different implementations of private browsing in desktop/mobile, etc. Those also may change whether the page is in a iframe or a top level window. I think the solution I described should work in majority of use cases (OAuth popup/redirect sign-in may break though when 3rd party cookies/data are disabled) but we will need to run more tests to ensure the other APIs work without generating unrecoverable errors.

**Comment by kmjennison** [comment]
@bojeil-google Do you have an ETA on the next release with these fixes?

**Comment by bojeil-google** [comment]
There was a problem with the build process. @jshcrowthe should be able to provide an answer.

**Comment by jshcrowthe** [comment]
Provided the fix has been submitted to master it should be picked up in a release next week. Thanks for your help @kmjennison 👍 

Additionally, if the fix is in master, you can check the `firebase@canary` channel on NPM for the latest code to see if the issue has been fixed. The tag is highly volatile and should not be used in production, but would serve for fix, vetting purposes.

**Comment by kmjennison** [comment]
@jshcrowthe Thanks for the update! I'll check out the canary channel.

**Comment by kmjennison** [comment]
This does seem be fixed in 4.13.0. Thanks for the quick turnaround!

**Comment by jshcrowthe** [comment]
No problem! Thanks for following up 😄
