### ISSUE TITLE
[@firebase/rules-unit-testing] emulator can't find resource in storage

### ISSUE THREAD

**Issue by Michael-fore** [firebase/firebase-js-sdk#6341]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Using 
  * Firebase SDK version: "@firebase/rules-unit-testing": "^2.0.2"
  * Firebase Product: storage, emulator

### [REQUIRED] Describe the problem

For some reason when I try and `getBytes` a file that I know is in the emulator, the `resource` value in my storage.rules is null.
I have triple checked that the projectid between @firebase/rules-unit-testing & the firebase emulators are the same.

I have also tried passing in the bucket into .storagte() to no avail.

I am not using the admin pkg to access the files, just @firebase/rules-unit-testing

#### Relevant Code:

```javascript
//curl http://localhost:5000/__/firebase/init.js          output
var firebaseConfig = {
  "projectId": "teamup-e89dd",
  "appId": "..",
  "storageBucket": "..",
  "locationId": "..",
  "apiKey": "..",
  "authDomain": "..",
  "messagingSenderId": ".."
};

const project_settings = {
    projectId: 'teamup-e89dd',
    storage: {
        host:'localhost',
        storageBucket:'UserFiles',
        port:5002,
        rules: fs.readFileSync("../../front/storage.rules", "utf8"),
      },
  };

  it('Should allow anyone to read the file.', async function(){
            var user_data = await getUserData();
            var files = user_data.data().docs
            const url =  'UserFiles' + getPublicFile(files).path

            var testEnv = await initializeTestEnvironment(project_settings)
            const storage = testEnv.authenticatedContext("test_user").storage();
            const storageRef = storage.ref(url)
            
            await assertSucceeds(
                getBytes(storageRef)
                );
```

**Comment by Michael-fore** [comment]
![image](https://user-images.githubusercontent.com/4061343/172512150-b898f2e8-024e-4cb7-9dc2-2f47192e5a2e.png)

the path is `UserFiles/1234/063790236130.284000000_Public.png`

**Comment by jbalidiong** [comment]
Hi @Michael-fore, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the error. I noticed that in the project_setting, you're setting the storage bucket. Unfortunately, using that snippet will not acknowledge the storage bucket and will use the projectId as the default bucket URL.

Here is the snippet I'm using:

```
const project_setting = {
projectId: 'helloWorld',
storage:{
     host: 'localhost',
     port: 5002
}
}

    initializeTestEnvironment(projectSetting)
  .then((testEnv)=>{
    const sam = testEnv.authenticatedContext("sam");
    console.log(sam);
    const storageRef = ref( sam.storage(), 'images/item.jpeg') 
    const refData = getBytes(storageRef)
    console.log(refData);

    assertSucceeds(
      console.log(getBytes(storageRef))
      );
  })
```

Using the snippet, I was able to run it without encountering any issues. Would you mind updating the code snippet you're using and see if the issue persists? Also, I tried running the `firebase emulators:start` to enable the UI and verify if the files are existing.

**Comment by Michael-fore** [comment]
@jbalidiong  thanks for getting back to me

 I tried it without that line and it still isn't finding it. It is work noting that this isn't the default bucket.
this is how i am creating the file too

 ```javascript
var bucket = storage.bucket('UserFiles');
const doc = createDoc(body);
var file =  bucket.file(path);
await file.save(body.doc)
```
![image](https://user-images.githubusercontent.com/4061343/172895612-d2d8435d-9321-4f86-85dd-7dfd2f0ed582.png)

**Comment by Michael-fore** [comment]
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{bucket}/{uid}/{name} {
      allow read: if 
        debug(resource)
        && resource.metadata.accessType == 'public'
        ;
      allow read, write: if debug(resource) && resource.metadata.accessType == 'private'
                  && request.auth.uid == uid;
    }
  }
}
```
i get this from the emulator log

```
path_value {
  segments {
    simple: "UserFiles"
  }
  segments {
    simple: "1234"
  }
  segments {
    simple: "063790236130.284000000_Public.png"
  }
}

null_value: NULL_VALUE
```

**Comment by Michael-fore** [comment]
And i created the file with `const { getStorage} = require('firebase-admin/storage');`

**Comment by Michael-fore** [comment]
I upgraded all my pkgs and it started working
