### ISSUE TITLE
Typo in GtagConfigParams

### ISSUE THREAD

**Issue by piotrponikowski** [firebase/firebase-js-sdk#6349]
I was checking typings of GtagConfigParams, and looks like there is a typo in:
https://github.com/firebase/firebase-js-sdk/blob/11d37eddc47d8f0ca07915135af183bc10a06814/packages/analytics/src/public-types.ts#L73

My first thought was, that this param is really named `allow_google_signals?`, however checked with docs and correct name is just `allow_google_signals`: https://developers.google.com/analytics/devguides/collection/gtagjs/display-features

Another attribute for comparison looks ok: https://github.com/firebase/firebase-js-sdk/blob/11d37eddc47d8f0ca07915135af183bc10a06814/packages/analytics/src/public-types.ts#L78

**Comment by hsubox76** [comment]
I don't understand, are you talking about the question mark? That's not part of the param name, that's Typescript for "optional".

**Comment by dwyfrequency** [comment]
[Merged a PR for this ](https://github.com/firebase/firebase-js-sdk/pull/6350)
