### ISSUE TITLE
[Email Link Authentication] catch block will not trigger 

### ISSUE THREAD

**Issue by indraraj26** [firebase/firebase-js-sdk#6353]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version:  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'
  * Firebase SDK version: "firebase": "^9.5.0" with @angular/fire 7.3.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Catch block will not trigger if you click on previous link. It should throw something invalid code etc.

#### Relevant Code:

``` 
firebase.auth().signInWithEmailLink(email, window.location.href)
    .then((result) => {
      // Clear email from storage.
      window.localStorage.removeItem('emailForSignIn');
      // You can access the new user via result.user
      // Additional user info profile not available via:
      // result.additionalUserInfo.profile == null
      // You can check if the user is new or existing:
      // result.additionalUserInfo.isNewUser
    })
    .catch((error) => {
      // Some error occurred, you can inspect the code: error.code
      // Common errors could be invalid email and invalid or expired OTPs.
    });
```

![image](https://user-images.githubusercontent.com/23274631/173248923-e983c258-0f9a-40d6-9331-2a9c4b7e9917.png)

**Comment by jbalidiong** [comment]
Hi @indraraj26, thanks for reaching out.  I tried replicating, but I wasn't able to reproduce the same behavior and I was able to get the error message. I noticed that you're not checking the value of the variable error. You can try the snippet below:

```
const authInstance = app.auth();

authInstance.onAuthStateChanged((user) => {
      if (user) {
        console.log('user signed in')
      }
    });

if(authInstance.isSignInWithEmailLink(window.location.href)){
      let email = window.localStorage.getItem('emailForSignIn');
      if (!email) {
        // User opened the link on a different device. To prevent session fixation
        // attacks, ask the user to provide the associated email again. For example:
        email = console.log('Please provide your email for confirmation');
      }

      authInstance.signInWithEmailLink(email, window.location.href)
      .then((result) => {
        // Clear email from storage.
        window.localStorage.removeItem('emailForSignIn');
        // You can access the new user via result.user
        // Additional user info profile not available via:
        // result.additionalUserInfo.profile == null
        // You can check if the user is new or existing:
        // result.additionalUserInfo.isNewUser
      })
      .catch((error) => {
        // Some error occurred, you can inspect the code: error.code
        // Common errors could be invalid email and invalid or expired OTPs.
        console.log(error.message);
      });
    }
```
Using the snippet, you'll see in the developer console the error message when clicking the previous link. It will return : `Firebase: The action code is invalid. This can happen if the code is malformed, expired, or has already been used. (auth/invalid-action-code).` I'll be closing this for now. If the issue persists, feel free to comment and reopen this issue.
