### ISSUE TITLE
"reloadUserInfo" is not defined in the type of User.

### ISSUE THREAD

**Issue by kenji7157** [firebase/firebase-js-sdk#6364]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS 12.4
  * Browser version: Chrome 102
  * Firebase SDK version: 9.8.1
  * Firebase Product: auth
 

### [REQUIRED] Describe the problem

`reloadUserInfo` is not defined in [type of User](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L21).  `reloadUserInfo` should be added to [type of User](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L21) .

<img width="646" alt="image" src="https://user-images.githubusercontent.com/18192657/174015285-c2788e3a-9a7c-4243-913e-28e75e013058.png">

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by kenji7157** [comment]
Hi, @sam-gc , I', thinkng of reloadUserInfo. When I checked the value of the second argument of onAuthStateChanged on the console, reloadUserInfo was output.However, I am getting an error in the editor.

> reloadUserInfo is not a field on user
The type of the second argument of onAuthStateChanged is User, isn't it? Why can I output the value of reloadUserInfo when the second argument of onAuthStateChanged is user type?

**Comment by kenji7157** [comment]
I think that The second argument of onAuthStateChanged is wrong, or ReloadUserInfo should be added to type of User.

**Comment by kenji7157** [comment]
I think the type of the second argument of onAuthStateChanged is wrong or you need to add ReloadUserInfo to the type of User.

**Comment by sam-gc** [comment]
`reloadUserInfo` is marked private and is not intended for use by developers. It's used to synchronize multi-factor operations.
https://github.com/firebase/firebase-js-sdk/blob/af923486662bc9449cca122b55840b045c9b4a5a/packages/auth/src/core/user/user_impl.ts#L122

What field specifically are you looking for in that interface? Almost all of these fields are available on the `User` instance itself.
https://github.com/firebase/firebase-js-sdk/blob/cdada6c68f9740d13dd6674bcb658e28e68253b6/packages/auth/src/api/account_management/account.ts#L66-L79
