### ISSUE TITLE
rtdb(types): DataSnapshot#forEach - action parameter has null key

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-js-sdk#6368]
### [REQUIRED] Describe your environment

  * Operating System version: N/A
  * Browser version: N/A
  * Firebase SDK version: 9.8
  * Firebase Product: database

### [REQUIRED] Describe the problem

When using `DataSnapshot#forEach` the parameter available to the action closure is a `DataSnapshot` which is correct, but the `key` property of this value has the type `string | null`, but as its a child of the iterating snapshot it can't be the root node so its key can never be `null`.

#### Steps to reproduce:

```js
const node = await getDatabase().ref().get()
node.forEach(child => {
   const key = child.key
   // key is possibly null so have to cast etc.
})
```

#### Relevant Code:

https://github.com/firebase/firebase-js-sdk/blob/efe2000fc499e2c85c4e5e0fef6741ff3bad2eb0/packages/database-types/index.d.ts#L25

https://github.com/firebase/firebase-js-sdk/blob/efe2000fc499e2c85c4e5e0fef6741ff3bad2eb0/packages/firebase/compat/index.d.ts#L5821-L5823

https://github.com/firebase/firebase-js-sdk/blob/efe2000fc499e2c85c4e5e0fef6741ff3bad2eb0/packages/database-compat/src/api/Reference.ts#L167

#### Fix

Happy to do a PR for this - I just remember it being a bit complicated [last time](https://github.com/firebase/firebase-js-sdk/issues/6071#issuecomment-1074261971) I did this. Is the info in that issue still correct - the function signature in the above 3 places just needs to be changed?

Would changing the function signature to `forEach(action: (a: DataSnapshot & { key: string }) => boolean | void): boolean;` be OK for a fix?

**Comment by maneesht** [comment]
That syntax doesn't quite match v9, but your suggestions should work. For v9, you still need to update https://github.com/firebase/firebase-js-sdk/blob/d87d3a8b8cd68e757be6628a72538bfd303e78d1/packages/database/src/api/Reference_impl.ts#L397

**Comment by maneesht** [comment]
If you could create a PR addressing this, that would be great

**Comment by maneesht** [comment]
If you're looking at the root, then:
```typescript
import { getDatabase } from 'firebase/database';
const rootSnapshot = await get(ref(getDatabase()));
rootSnapshot.forEach(node => {
  console.log(node.key);
});
```
Out of curiosity, are you using v9-compat? (The non-modular version of firebase database)

**Comment by maneesht** [comment]
@rhodgkins thank you for your contribution. However, we will have to rollback this change as it is causing a compilation error with AngularFire. We will add this back on the next major release. Until then, I will reopen this for tracking purposes.

**Comment by maneesht** [comment]
Closing this as it was part of the 10.0 release: https://firebase.google.com/support/release-notes/js#realtime-database
