### ISSUE TITLE
Getting "Client is offline" error reading from Realtime Database after upgrading to 11.0.0

### ISSUE THREAD

**Issue by Hivemind9000** [firebase/firebase-js-sdk#6390]
Environment:

Firebase SDK version: 11.0.0
Firebase Product: database
Node.js version: 14

Problem:

After upgrading to 11.0.0 I started to get the error "Client is offline" when reading from the Realtime Database. The cloud function that threw the issue had not been changed for months. When I reverted back to 10.2.0 (the version I was on previously) the problem disappeared.

The relevant line of code was:
```
const sysCtlDS = await admin.database().ref('/system/directive/status').get();
```

I tried a solution from Stackoverflow, but instead of getting the "Client is offline" error, the cloud function just hung on that request and timed out.
```
const sysCtlDS = await admin.database().ref('/system/directive/status').once('value');
```

Any ideas as to why this is occurring?

**Comment by maneesht** [comment]
This may be fixed by #6340

**Comment by maneesht** [comment]
@Hivemind9000 - can you please try this on the latest version of the admin SDK?

**Comment by Hivemind9000** [comment]
Thanks @maneesht it seems to be working now (not hanging) using:

`const sysCtlDS = await admin.database().ref('/system/directive/status').once('value');`

firebase-admin 11.0.1
firebase-functions 3.22.0
