### ISSUE TITLE
unresolved get cause onValue to not be called on child path

### ISSUE THREAD

**Issue by christophe-g** [firebase/firebase-js-sdk#6397]
### Describe your environment

  * Operating System version: linux
  * Browser version: chrome latest 
  * Firebase SDK version: JS SDK v9.8.4
  * Firebase Product: 

### Describe the problem

`onValue` callback function on node for which a get on a parent has not yet resoved will never be called. This is pretty bad as `get` seems to have unpredictable side-effect. 

get should not have ANY side-effect. 

Possibly related to https://github.com/firebase/firebase-js-sdk/issues/6038. Took me ages to identify the reason for some part of my app failing while transitionning to v9. 

Work around for now: avoid any use of get, replace by a thenable `onValue ... {onlyOnce: true}`

#### Steps to reproduce:
[go there - possibly adjust the `ms` property](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7IHJlbW92ZSwgc2V0LCBnZXREYXRhYmFzZSwgcmVmLCBjaGlsZCwgb25WYWx1ZSwgZ2V0IH0gZnJvbSAnZmlyZWJhc2UvZGF0YWJhc2UnO1xuaW1wb3J0IHsgaW5pdGlhbGl6ZUFwcCwgU0RLX1ZFUlNJT04gfSBmcm9tIFwiZmlyZWJhc2UvYXBwXCJcbiAgICBcbmNvbnN0IGZpcmViYXNlQ29uZmlnID0ge1xuICBhcGlLZXk6ICdBSXphU3lEVFAtZWlRZXpsZUZzVjJXZGRGQkFoRl9XRXp4Xzh2X2cnLFxuICBhdXRoRG9tYWluOiAncG9seW1lcmZpcmUtdGVzdC5maXJlYmFzZWFwcC5jb20nLFxuICBkYXRhYmFzZVVSTDogJ2h0dHBzOi8vcG9seW1lcmZpcmUtdGVzdC5maXJlYmFzZWlvLmNvbScsXG59XG5cbmluaXRpYWxpemVBcHAoZmlyZWJhc2VDb25maWcpOyBcbmNvbnN0IHBhdGggPSAnL3Rlc3QnXG5jb25zdCByID0gcmVmKGdldERhdGFiYXNlKCksIHBhdGgpXG5jb25zdCBjaGlsZHMgPSBbJ2MxJywgJ2MyJywgJ2MzJ11cbmNvbnN0IHdhaXQgPSAobWlsaXNlYykgPT4ge1xuICByZXR1cm4gbmV3IFByb21pc2UocmVzb2x2ZSA9PiB7XG4gICAgICBzZXRUaW1lb3V0KCgpID0-IHsgcmVzb2x2ZSgpIH0sIG1pbGlzZWMpO1xuICB9KVxufVxuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgcCB7IGNvbG9yOiBibHVlIH1cbiAgICAgIC5mYWlsZWQge2NvbG9yOiByZWR9XG4gICAgICBgO1xuXG4gIEBwcm9wZXJ0eSgpIGNhbGxiYWNrVmFsdWVzID0gW107XG4gIEBwcm9wZXJ0eSgpIG1zID0gMzIwXG5cbiAgY29uc3RydWN0b3IoKSB7XG4gICAgc3VwZXIoKVxuICAgICAgIHRoaXMucmVsb2FkKClcbiAgICBcbiAgfVxuICBcbiAgcmVsb2FkKCkge1xuICAgIHRoaXMub25HZXQoKSAgICBcbiAgICB0aGlzLm9uVmFsdWUoKVxuICB9XG4gICAgICAgIFxuICBhc3luYyBvbkdldCgpIHtcbiAgICBQcm9taXNlLmFsbChcbiAgICAgIGNoaWxkcy5jb25jYXQoY2hpbGRzLCBjaGlsZHMsY2hpbGRzLGNoaWxkcywgY2hpbGRzKS5tYXAoYyA9PiBnZXQoY2hpbGQocixjKSlcbiAgICAgICAgLnRoZW4oKCkgPT4gdGhpcy5hZGRUbygxKSlcbiAgICAgKSlcbiAgICAgLnRoZW4oKCkgPT4gdGhpcy5hZGRUbygnRG9uZScpKVxuICB9IFxuICBcbiAgYXN5bmMgb25WYWx1ZSgpIHtcbiAgICAvLyBhZGp1c3Qgd2FpdCBpZiBuZWVkZWRcbiAgICBhd2FpdCB3YWl0KHRoaXMubXMpICAgIFxuICAgIFxuICAgIFByb21pc2UuYWxsKFxuICAgICAgIGNoaWxkcy5tYXAoYyA9PiBvblZhbHVlKGNoaWxkKHIsIGMgKycvYS9iJyksIHNuYXAgPT4gdGhpcy5hZGRUbyhjKSkpXG4gICAgICBcbiAgICAgKVxuICB9XG4gIFxuICBhZGRUbyh2YWx1ZSkge1xuICAgIHRoaXMuY2FsbGJhY2tWYWx1ZXMgPSB0aGlzLmNhbGxiYWNrVmFsdWVzLmNvbmNhdCh2YWx1ZSlcbiAgfVxuICBcbiAgcmVuZGVyKCkge1xuICAgIGNvbnN0IG9uQ2hhbmdlID0gKGUpID0-IHtcbiAgICAgIHRoaXMuY2FsbGJhY2tWYWx1ZXMgPSBbXVxuICAgICAgdGhpcy5tcyA9IGUudGFyZ2V0LnZhbHVlXG4gICAgICB0aGlzLnJlbG9hZCgpICAgIFxuICAgIH1cbiAgICBcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgPGgyPkNoZWNraW5nIEZpcmViYXNlIGNhbGxiYWNrczwvaDI-XG4gICAgIDxwPlNESyBWZXJzaW9uOiAke1NES19WRVJTSU9OfTwvcD5cbiAgICAgXG4gICAgIDxwPldoYXQgeW91IHNob3VsZCBzZWUgaXM6IDwvcD5cbiAgICAgPGNvZGU-YzEsYzIsYzMsMSwxLDEsMSwxLDEsMSwxLDEsMSwxLDEsMSwxLDEsMSwxLDEsRG9uZTwvY29kZT5cbiAgICAgPHA-QnV0cyBzb21ldGltZXMgb25WYWx1ZSBpcyBub3QgY2FsbGVkLCBhbmQgdGhlIG91dHB1dCBpcyA6IDwvcD4gICBcbiAgICAgPGNvZGU-MSwxLDEsMSwxLDEsMSwxLDEsMSwxLDEsMSwxLDEsMSwxLDEsRG9uZTwvY29kZT5cbiAgICAgPCEtLWRpdj5cbiAgICAgICAgPGxhYmVsIGZvcj1cImlucHV0XCI-YWRqdXN0IHdhaXQgYmV0d2VlbiAxMDAgdG8gNDAwPC9sYWJlbD5cbiAgICAgICAgPGlucHV0IGlkPVwiaW5wdXRcInN0ZXA9XCIyMFwiIHR5cGU9XCJudW1iZXJcIiAudmFsdWU9JHt0aGlzLm1zfSBAaW5wdXQ9JHtvbkNoYW5nZX0-PC9pbnB1dD48L2Rpdi0tPiAgIFxuICAgIDxwPlJlbG9hZCB0aGUgYnkgY2hhbmdpbmcgdGhlIGNvZGUsIG9yIHByZXNzIHRoZSByZWxvYWQgaWNvbiB0b3AgcmlnaHQuIFlvdSBtaWdodCBuZWVkIHRvIGFkanVzdCBtcyBwcm9wZXJ0eSwgZGVwZW5kaW5nIG9uICB5b3VyIG5ldHdvcmsuPC9wPlxuICAgIDxoMz5PdXRwdXQ6IDwvaDM-IFxuICAgIDxjb2RlPiR7dGhpcy5jYWxsYmFja1ZhbHVlcy50b1N0cmluZygpfTwvY29kZT5cbiAgICAke3RoaXMucmVuZGVyQ2hlY2soKX1cbiAgICAgICAgYDtcbiAgfVxuICByZW5kZXJDaGVjaygpIHtcbiAgICBpZiAoIXRoaXMuY2FsbGJhY2tWYWx1ZXMubGVuZ3RoKSB7cmV0dXJuICcnfVxuICAgIGlmICh0aGlzLmNhbGxiYWNrVmFsdWVzLmluY2x1ZGVzKCdjMScpIHtyZXR1cm4gaHRtbGA8aDQgY2xhc3M9XCJva1wiPlRlc3Qgb2s8L2g0PmB9XG4gICAgcmV0dXJuIGh0bWxgPGg0IGNsYXNzPVwiZmFpbGVkXCI-VGVzdCBGYWlsZWQgLSBvblZhbHVlIGlzIG5ldmVyIGNhbGxlZDwvaDQ-YFxuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

The test case is fragile as it depends on race conditions. So please adjust the `ms` wait property to see the test fail.

**Comment by christophe-g** [comment]
Any news on this? 

Can you reproduce the faulty behavior ?

**Comment by maneesht** [comment]
@christophe-g I was able to reproduce the issue. I am looking into it.

**Comment by maneesht** [comment]
@christophe-g we were able to reproduce this with once as well. Can you provide an example where the correct behavior is observed with once?

**Comment by nauzilus** [comment]
Thanks for looking into this @maneesht . Not sure if you still need examples, but I have consistently repeatable demos in stackblitz showing the change in behaviour between 9.8.3, 9.8.4, and 9.8.4 with the workaround mentioned:
* [9.8.3](https://stackblitz.com/edit/react-ts-tyeaad?file=App.tsx)
* [9.8.4](https://stackblitz.com/edit/react-ts-vgcozz?file=App.tsx)
* [9.8.4 with workaround](https://stackblitz.com/edit/react-ts-je6the?file=App.tsx)

The defect is triggered when there's a `get` and an `onValue` _after_ the connection has already been established, so there's a dummy query just to get firebase connected before rendering the test component. 9.8.3 the `once` and `live` values both populate but in 9.8.4 only `once` is populated.

**Comment by maneesht** [comment]
@nauzilus - thanks for the thorough examples. We were able to create a test case to prevent this from happening again. The fix should be in soon.
