### ISSUE TITLE
`onChildAdded` events not working in Database v9.8.4 SDK

### ISSUE THREAD

**Issue by rorencio** [firebase/firebase-js-sdk#6416]
### Describe your environment

  * Operating System version: macOS 12.4
  * Browser version: Chrome 103
  * Firebase SDK version: 9.8.4
  * Firebase Product: database

### Describe the problem
After upgrading to version 9.8.4, `onChildAdded` events do not fire. 

#### Steps to reproduce:
Update to version 9.8.4, without changing the source code.

#### Relevant Code:
```javascript

  id.then((id) => {
    ref = ref(db, `path/${id}/other_path}`)
    onChildAdded(query(ref, limitToLast(1)), (snapshot) => {
      [...]
    }

```

**Comment by jbalidiong** [comment]
Hi @rorencio, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the same behavior.
 
If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by jbalidiong** [comment]
Thanks for the update, I've run a simple code and it is working fine on my end. I'm uncertain as to the cause of this inconsistent behavior. Let's leave the issue open for now, in case some of our engineers have an idea what caused this. Feel free to add more details. Thanks!

**Comment by hsubox76** [comment]
This seems to be the only PR added in the 9.8.4 release, I'm not sure if anything in that would cause this effect. https://github.com/firebase/firebase-js-sdk/pull/6273

**Comment by maneesht** [comment]
@rorencio - do you know if you were using `get()` in combination with `onChildAdded`? There was a bug where if a listener was called on a child path of a pending `get` then the listener's events [wouldn't fire](https://github.com/firebase/firebase-js-sdk/issues/6397). 
Or, if you know the last working version of this?

**Comment by rorencio** [comment]
Yes, that was totally my case as well! I've tried with the lastest version and it seems to work fine now! Thank you very much!
