### ISSUE TITLE
I suspect the esm packaging is not quite right

### ISSUE THREAD

**Issue by richtera** [firebase/firebase-js-sdk#6417]
I am using version 9.8.4
and I am trying to import it into my jest script using ts-jest.
The problem is that the esm source code has unnamed function declarations rather than arrow functions.
For example: 
```javascript
   } catch (n) {
        M("RemoteStore", "Failed to remove targets %s: %s ", e.targetIds.join(","), n), 
        await Au(t, n);
    } else if (e instanceof Is ? t.wu.Ut(e) : e instanceof Ts ? t.wu.zt(e) : t.wu.Gt(e), 
    !n.isEqual(ct.min())) try {
        const e = await vo(t.localStore);
        n.compareTo(e) >= 0 && 
        // We have received a target change with a global snapshot if the snapshot
        // version is not equal to SnapshotVersion.min().
        await 
        /**
 * Takes a batch of changes from the Datastore, repackages them as a
 * RemoteEvent, and passes that on to the listener, which is typically the
 * SyncEngine.
 */
        function(t, e) {
            const n = t.wu.Yt(e);
            // Update in-memory resume tokens. LocalStore will update the
            // persistent view of these when applying the completed RemoteEvent.
                        return n.targetChanges.forEach(((n, s) => {
                if (n.resumeToken.approximateByteSize() > 0) {
                    const i = t.hu.get(s);
                    // A watched target might have been removed already.
                                        i && t.hu.set(s, i.withResumeToken(n.resumeToken, e));
                }
            })), 
            // Re-establish listens for the targets that have been invalidated by
            // existence filter mismatches.
            n.targetMismatches.forEach((e => {
                const n = t.hu.get(e);
                if (!n) 
```
inside of node_modules/@firebase/firestore/dist/index.esm2017.js.
ts-jest just says
![image](https://user-images.githubusercontent.com/708186/177783901-c631c82b-dd1e-45ab-aa78-6c32332d5d45.png)
Since it's translating the sources the line number is not correct it's more like 13487.

### [REQUIRED] Describe your environment

  * Operating System version: WSL2 unbuntu
  * Browser version: n/a
  * Firebase SDK version: 9.8.4
  * Firebase Product: firestore

When trying to translate the ESM using ts-jest I get a typescript error complaining about unnamed functions.
When trying to use babel-jest instead it doesn't show an error but still fails:
![image](https://user-images.githubusercontent.com/708186/177784541-00f2ead7-75be-41a6-a629-a902a7d971e8.png)

#### Steps to reproduce:
Write a typescript test file importing either firebase/firestore or `@firebase/firestore`.

#### Relevant Code:

```javascript
import { Timestamp } from '@firebase/firestore';
```

**Comment by hsubox76** [comment]
Can you tell me more about your setup? I tried to reproduce this by copying the first "ts-jest starter" project I found on Github: https://github.com/szebrowski/ts-jest-starter, installing Firebase, and adding `import {Timestamp} from 'firebase/firestore'` in both the src file and the test file, and everything seems to run fine. Let me know if I can change something in the tsconfig or jest config to get the same error.

**Comment by richtera** [comment]
Let me clone that project and try. Did you happen to create a fork?

**Comment by richtera** [comment]
I am still getting the error, but can't quite figure out how to extract enough of the code to reproduce it yet. I am suspecting either babel or tsc is complaining about unnamed functions which should not really exists in es2017 sources. Are you sure the module compile is correct? Since the module is now esm and node doesn't read the esm natively (we have to use v14 because of express and spdy) jest has to use ts-jest or babel-jest to transpile that file.

**Comment by richtera** [comment]
I stripped my project from real code and put it here https://github.com/getselfstudy/firebase-sdk-jest-test
To use it checkout, `yarn` then `yarn test` (which has the failure) and `yarn test:integration` which seems to work ok.
It uses ts-jest; if you switch to babel-jest it will hide the error but still fail with a similar error. The project uses a nx.dev monorepo and a custom jsdom environment to allow the firebase emulator connection from the UI jest's.

You should see this kind of output:
```text
$ yarn test

    ✔  nx run bigquery:test  [existing outputs match the cache, left as is]
    ✔  nx run functions:test  [existing outputs match the cache, left as is]

    ✖  nx run react-ui:test
 FAIL   react-ui  libs/react-ui/src/lib/cards/UserProfileSettings/UserProfileSettings.spec.tsx
  ● Test suite failed to run
       
           Jest encountered an unexpected token
       
           Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
       
           Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
       
           By default "node_modules" folder is ignored by transformers.
       
           Here's what you can do:
            • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
            • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
            • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
            • If you need a custom transformation specify a "transform" option in your config.
            • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
       
           You'll find more details and examples of these config options in the docs:
           https://jestjs.io/docs/configuration
           For information about custom transformations, see:
           https://jestjs.io/docs/code-transformation
       
           Details:
       
           /home/andy/Development/nx-test/node_modules/@firebase/firestore/dist/index.esm2017.js:13237
                           function (t, e) {
                           ^^^^^^^^
       
           SyntaxError: Function statements require a function name
       
             2 | import { cleanup, render } from '@testing-library/react';
             3 | import '@testing-library/jest-dom/extend-expect';
           > 4 | import { Timestamp } from '@firebase/firestore';
               | ^
             5 | import { UserProfileSettings } from './UserProfileSettings';
             6 |
             7 | afterEach(cleanup);
       
             at Runtime.createScriptFromCode (../../node_modules/jest-runner/node_modules/jest-runtime/build/index.js:1796:14)
             at Object.<anonymous> (src/lib/cards/UserProfileSettings/UserProfileSettings.spec.tsx:4:1)
       
Test Suites: 1 failed, 1 total
       Tests:       0 total
       Snapshots:   0 total
       Time:        1.53 s
       Ran all test suites.
```

**Comment by richtera** [comment]
@hsubox76 I posted a sample repo with my setup. I am not sure if you saw the notification over the weekend. This does reproduce the error pretty easily.

**Comment by hsubox76** [comment]
It seems to be a problem with Jest's resolver. Here's a description of the problem in another Jest library, jest-preset-angular, and a fix. https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting/#resolver-needed-for-some-javascript-library-or-nested-dependencies

I adapted the fix to your repo and it seems to work. I created the `jest.resolver.js` file just as described in that link and put it in your `libs/react-ui` folder. I then changed `jest.preset.js` at the top of your directory to add a link to the resolver:

```
const nxPreset = require('@nrwl/jest/preset').default;

module.exports = {
  ...nxPreset,
  resolver: '<rootDir>/jest.resolver.js',
};
```

This seems to fix the problem. I'm not sure why it works, because I'm not very familiar with Jest, but it seems to be a known issue and this fix works on this repro.

**Comment by drewhoffer** [comment]
Oh my god. I love you guys.
```
  Admin Table tests
    ✓ Should render a table (48 ms)
```


In case anyone is wondering how to deal with the Jest Nextjs Firebase SyntaxError: Cannot use import statement outside a module. Try this https://github.com/firebase/firebase-js-sdk/issues/6417#issuecomment-1182323550. Then in your `jest.config.js` add a link to the resolver you will be using. 
```
  resolver: "<rootDir>resolver.js", // or <rootDir>/path/to/your/resolver.js
```

Then (im using @hookforms as well) 

```
//TODO: clean this file up
module.exports = (path, options) => {
  // Call the defaultResolver, so we leverage its cache, error handling, etc.
  return options.defaultResolver(path, {
    ...options,
    // Use packageFilter to process parsed `package.json` before
    // the resolution (see https://www.npmjs.com/package/resolve#resolveid-opts-cb)
    packageFilter: (pkg) => {
      const pkgNamesToTarget = new Set([
        "@firebase/auth",
        "@firebase/storage",
        "@firebase/functions",
        "@firebase/database",
        "@firebase/auth-compat",
        "@firebase/database-compat",
        "@firebase/app-compat",
        "@firebase/firestore",
        "@firebase/firestore-compat",
        "@firebase/messaging",
        "@firebase/util",
        "firebase/app",
        "firebase",
      ]);

      if (pkgNamesToTarget.has(pkg.name)) {
        // console.log('>>>', pkg.name)
        delete pkg["exports"];
        delete pkg["module"];
      }

      // https://github.com/react-hook-form/resolvers/issues/396#issuecomment-1114248072
      // jest-environment-jsdom 28+ tries to use browser exports instead of default exports,
      // but @hookform/resolvers only offers an ESM browser export and not a CommonJS one. Jest does not yet
      // support ESM modules natively, so this causes a Jest error related to trying to parse
      // "export" syntax.
      //
      // This workaround prevents Jest from considering @hookform/resolvers module-based exports at all;
      // it falls back to CommonJS+node "main" property.
      if (pkg.name === "@hookform/resolvers") {
        delete pkg["exports"];
        delete pkg["module"];
      }
      return pkg;
    },
  });
};
```

@richtera / @hsubox76 , if you guys ever get stuck debugging anything else. Give me a shout. IOU guys for this one.

**Comment by richtera** [comment]
@hsubox76 Thank you this worked. Sorry it took me a while to get all my other ESMs to work the same way, but this is the right solution.
