### ISSUE TITLE
Unlinking a credential on an firebase user does not update isAnonymous as expected

### ISSUE THREAD

**Issue by phildowflux** [firebase/firebase-js-sdk#6419]
### Describe your environment

  * Operating System version: macOS 12.4
  * Browser version: Chrome Version 102.0.5005.115
  * Firebase SDK version: 9.8.1
  * Firebase Product: auth

### Describe the problem

Cross-posting from https://github.com/firebase/flutterfire/issues/4902

I have an anonymous user where `isAnonymous` is true. I "upgrade" that user to a non-anonymous one by linking them with a credential. Now isAnonymous is false. This is the only credential I link them to. I later unlink that same credential so that the user no longer has any credentials, but isAnonymous continues to be false. I expect isAnonymous to be true again.

Separately but perhaps related, the email field for the user continues to show the linked credential's value, although I expect it to be cleared after unlinking the credential.

#### Steps to reproduce:

- Create anonymous user object
- Link to email credentials using linkWithCredential and an EmailAuthProvider
- Unlink that credential with unlink and the providerId for that credential
- isAnonymous is still false

#### Relevant Code:

```javascript
const firebaseUser = FirebaseConnector.getInstance().firebaseApp.auth().currentUser;
const providerId = "password"; // in this case

firebaseUser.unlink(providerId);

firebaseUser.isAnonymous; // == false, expect true
```

**Comment by sam-gc** [comment]
Hi @phildowflux, thanks for reaching out. This is expected behavior. Once the isAnonymous bit is set to false, it will never be set back to true, even if you unlink all providers.

See also: https://stackoverflow.com/a/65431666/19129568
