### ISSUE TITLE
After unlinking a credential, attempting to link that credential again throws auth/requires-recent-login

### ISSUE THREAD

**Issue by phildowflux** [firebase/firebase-js-sdk#6420]
### Describe your environment

  * Operating System version: macOS 12.4
  * Browser version: Chrome Version 102.0.5005.115
  * Firebase SDK version: 9.8.1
  * Firebase Product: auth

### Describe the problem

I have an anonymous user. I link that user to an EmailAuthProvider credentials. I later unlink those credentials as part of error handling during user signup (unrelated). This already does not behave as expected, see https://github.com/firebase/firebase-js-sdk/issues/6419. I allow the user to try to sign up again using the same EmailAuthProvider credentials, and firebase throws an auth/requires-recent-login. The problem should be obvious. I have unlinked that users's credentials. They cannot sign in again. I am now left with an Auth user that seems to be in an invalid state.

[Edit]

Please note that some time has passed between unlinking the credential and trying to link it again, but either way I'm still left with what seems to be an invalid Auth object.

#### Steps to reproduce:

- Create anonymous user object
- Link to email credentials using linkWithCredential and an EmailAuthProvider
- Unlink that credential with unlink and the providerId for that credential
- Try again to link to email credentials using linkWithCredential and an EmailAuthProvider
- Firebase throws auth/requires-recent-login error

#### Relevant Code:

```javascript
// Assuming previously created anonymous user linked with an EmailAuthProvider
// Unlink provider

const firebaseUser = FirebaseConnector.getInstance().firebaseApp.auth().currentUser;
const providerId = "password"; // in this case

firebaseUser.unlink(providerId);

// Try linking provider again [Edit] after some time has passed

const credential = firebase.auth.EmailAuthProvider.credential("...",  "...");
firebaserUser.linkWithCredential(credential); 
// throws auth/requires-recent-login 

```

**Comment by sam-gc** [comment]
Hi @phildowflux, thanks for reaching out. This is expected behavior. Once the isAnonymous bit is set to false, it will never be set back to true, even if you unlink all providers.

See also: https://stackoverflow.com/a/65431666/19129568

**Comment by phildowflux** [comment]
Thanks @sam-gc for the quick response. This is very unfortunate behavior. This may be Firebase working as expected but it does not match user expectations for how Auth should work. Well, at least it doesn't match my expectations :)

We unlink the only provider as part of rolling back changes to the Auth object in case other steps in the sign up process fail. Normally I think we could just sign the user out of the auth object and start with a fresh one, but the design of our system requires us to preserve the previously anonymous auth object because we associate it with anonymous user activity on the platform. We cannot start with a new auth object as far as I understand it.

I am looking at other approaches like signing in the Auth object last instead of first in our signup process so that if other steps fail, at least we can roll those back without ending up with this invalid Auth object, but that comes with its own set of difficulties. We'll see.

Thank you again for the prompt response.

**Comment by sam-gc** [comment]
I see, thanks for expanding on your use case. From the Firebase Auth perspective, yes unfortunately you may need to wait until the last step in case there needs to be a rollback. I agree the behavior is not great, but updating it would be fairly significant breaking change to the existing behavior so I don't know how likely it is that we'll be able to update it. Still, we've made note of this issue and we're tracking some others like it, in case we're able to find a path forward and prioritize updating the way this flow works.
