### ISSUE TITLE
`auth/invalid-value-(email),-starting-an-object-on-a-scalar-field` on `createUserWithEmailAndPassword`

### ISSUE THREAD

**Issue by c-hristian** [firebase/firebase-js-sdk#6426]
### [REQUIRED] Describe your environment

  * Operating System version: macOS monterey 12.1 (21C52)
  * Browser version: Chrome Version 103.0.5060.53 (Official Build) (arm64)
  * Firebase SDK version: 9.9.0
  * Firebase Product: auth 

Note: This is from an expo react application running on an iphone. I wouldn't think it would matter but here are some other environment versions.
 * iphone 12
 * iOS 14.8
 * expo 45.0.6

#### Relevant Code:

```javascript
// initializing firebase 

import Constants from 'expo-constants';

import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import 'firebase/compat/firestore';
import 'firebase/compat/storage';

const app = firebase.initializeApp(Constants.manifest?.extra.firebaseConfig);
const auth = app.auth();
const db = app.firestore();

export {app, db, auth};

----------------------------------------------

// creating user where the error is caught and returned

async function createAccount(email, password, setLoading, store) {
  console.log(email);
  console.log(password);
  
  return auth
    .createUserWithEmailAndPassword(auth, email, password)
    .then(AuthCredential => store.dispatch(firebaseLogin(AuthCredential)))
    .catch(err => {
      setLoading(false);
      console.log(err.code);
      console.log(err.message);
      console.log('cre', {err});
      Alert.alert('Caution', 'Something Went Wrong!. Try Again.');
    });
}
```
console log error screenshot
<img width="697" alt="image" src="https://user-images.githubusercontent.com/108954694/178060394-a1e79f86-9cc9-41e1-be0b-b33a39cc4743.png">

**Comment by c-hristian** [comment]
I have double checked the auth api error code docs and this error is not listed
https://firebase.google.com/docs/auth/admin/errors

**Comment by sam-gc** [comment]
Hi @c-hristian, thanks for reaching out. The issue appears to be that you're using the compat libraries (which use v8-style monolithic libraries) with v9-function calls. Specifically:

```js
auth.createUserWithEmailAndPassword(auth, email, password)
```

Since you're using the compatibility layer, you should instead do:
```js
auth.createUserWithEmailAndPassword(email, password)
```
which matches the [function definition](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#createuserwithemailandpassword).

I'm going to close this issue out for now, but please respond/reopen if that doesn't fix your issue.
