### ISSUE TITLE
TTP Error: 400, Invalid value at 'queue.retry_config.max_backoff'

### ISSUE THREAD

**Issue by scole954387** [firebase/firebase-js-sdk#6427]
Good evening.  I just uploaded my functions without error and received the notice that firebase needed to be updated.  I proceeded with the update via npm.

Immediately after the update I went to upload the functions again just to ensure everything still works and this time it failed. No changes were made to the function being uploaded.  It worked right before but not after the upgrade.

Any idea what's on the go?  Thanks.

Here's the error:
`i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/shannoncole/Development/Skip2Quick/functions (711.79 KB) for uploading
i  functions: ensuring required API cloudtasks.googleapis.com is enabled...
✔  functions: required API cloudtasks.googleapis.com is enabled
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 16 function processSalesReceiptReport(us-central1)...
i  functions: updating Node.js 16 function processExpenseReport(us-central1)...
i  functions: updating Node.js 16 function salesReceiptAdded(us-central1)...
i  functions: updating Node.js 16 function expenseAdded(us-central1)...
HTTP Error: 400, Invalid value at 'queue.retry_config.max_backoff' (type.googleapis.com/google.protobuf.Duration), Field 'maxBackoff', Invalid duration format, failed to parse seconds
Invalid value at 'queue.retry_config.min_backoff' (type.googleapis.com/google.protobuf.Duration), Field 'minBackoff', Invalid duration format, failed to parse seconds
Invalid value at 'queue.retry_config.max_retry_duration' (type.googleapis.com/google.protobuf.Duration), Field 'maxRetryDuration', Invalid duration format, failed to parse seconds
HTTP Error: 400, Invalid value at 'queue.retry_config.max_backoff' (type.googleapis.com/google.protobuf.Duration), Field 'maxBackoff', Invalid duration format, failed to parse seconds
Invalid value at 'queue.retry_config.min_backoff' (type.googleapis.com/google.protobuf.Duration), Field 'minBackoff', Invalid duration format, failed to parse seconds
Invalid value at 'queue.retry_config.max_retry_duration' (type.googleapis.com/google.protobuf.Duration), Field 'maxRetryDuration', Invalid duration format, failed to parse seconds
✔  functions[expenseAdded(us-central1)] Successful update operation.
✔  functions[salesReceiptAdded(us-central1)] Successful update operation.

Functions deploy had errors with the following functions:
        processExpenseReport(us-central1)
        processSalesReceiptReport(us-central1)
i  functions: cleaning up build files...
Error: There was an error deploying functions:
- Error Failed to upsert task queue function processExpenseReport in region us-central1
- Error Failed to upsert task queue function processSalesReceiptReport in region us-central1`

**Comment by arthurgubaidullin** [comment]
Same problem.

**Comment by hsubox76** [comment]
Since you're having issues on functions deploy, it looks like the repo you're looking for is https://github.com/firebase/firebase-tools
