### ISSUE TITLE
`signInWithPhoneNumber()`error - "TypeError: Cannot read properties of undefined (reading 'settings')"

### ISSUE THREAD

**Issue by russellwheatley** [firebase/firebase-js-sdk#6445]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 12.4
  * Browser version: Chrome 103.0.5060.114 (latest)
  * Firebase SDK version: 9.9.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Encountering error when trying to use `signInWithPhoneNumber()`.

```
TypeError: Cannot read properties of undefined (reading 'settings')
```

Screenshot of where in source code:
<img width="723" alt="Screenshot 2022-07-19 at 09 08 18" src="https://user-images.githubusercontent.com/16018629/179700363-60fe8bf9-d8e8-4122-a3a6-a90a96b4d15a.png">

#### Steps to reproduce:
Run the following code. I reproduced using rollup.js as the bundler:

```js
import { initializeApp } from 'firebase/app';

import { signInWithPhoneNumber,  initializeAuth } from 'firebase/auth';

var config = {
 // INSERT YOUR OWN FIREBASE CONFIG
}

const app = initializeApp(config);


const auth = initializeAuth(app);

// set "appVerificationDisabledForTesting"
auth.settings.appVerificationDisabledForTesting = true;

function testRecaptcha(){
  const id = 'ff-container';
  const element = document.createElement("div");
  element.setAttribute("id", id);
  document.body.appendChild(element);

  const recaptchaVerifier = new RecaptchaVerifier(id, {
    size: 'normal',
    theme:'light',
    callback: function(response) {
      console.log('Response', response);
    },
    'error-callback': function(error) {
      console.log('Error', error);
    },
    'expired-callback': function() {
      console.log('Expired');
    }
  });
  
  signInWithPhoneNumber(auth, '+111222444', recaptchaVerifier).then((response)=>{
    console.log('Response', response);
  }).catch((e)=> {  console.log('Error ', e); });

}

testRecaptcha();
```

This is also an issue on FlutterFire which I help to maintain: https://github.com/firebase/flutterfire/issues/9097

**Comment by russellwheatley** [comment]
Thanks! That was it. You may want to update the documentation [here](https://firebase.google.com/docs/reference/js/auth.recaptchaverifier#recaptchaverifierconstructor) as it says:

*"If none is provided, the default Firebase [Auth](https://firebase.google.com/docs/reference/js/auth.auth.md#auth_interface) instance is used. A Firebase [Auth](https://firebase.google.com/docs/reference/js/auth.auth.md#auth_interface) instance must be initialized with an API key, otherwise an error will be thrown."*

When it appears it will error when `auth` instance is not provided.

**Comment by hsubox76** [comment]
@sam-gc Was it intended for the `RecaptchaVerifier` constructor to supply the default auth instance if no 3rd argument is provided? I don't see a default `getAuth()` anywhere else in the auth code so I'm guessing not. I can update the comment if that's the case.

**Comment by sam-gc** [comment]
Ah yeah good catch, it's always expected to pass the auth instance. I just sent out https://github.com/firebase/firebase-js-sdk/pull/6460

**Comment by DellaBitta** [comment]
I'm closing this issue for now since it seems like the docs have been updated. Please @ message me if that's incorrect, or open a new issue that refers to this one. Thanks!
