### ISSUE TITLE
page_location and page_title parameters were sent with custom events

### ISSUE THREAD

**Issue by haoxi911** [firebase/firebase-js-sdk#6446]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11
  * Browser version: Chrome 103
  * Firebase SDK version: 9.9.0
  * Firebase Product: analytics

### [REQUIRED] Describe the problem

`page_location` and `page_title` parameters were sent with custom events even `send_page_view` has been disabled.

#### Steps to reproduce:

1. Initialize Firebase Analytics with `send_page_view` set to `false`.
2. Send a custom event.
3. Observe parameters of the custom event in GA dashboard, `page_location` and `page_title` were included.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/12502170/179783852-8bc548fb-767b-4286-b72b-af1bb55adafe.png">

#### Relevant Code:

```javascript
const firebaseConfig = {
  ...
};
const firebase = initializeApp(firebaseConfig);
const analytics = initializeAnalytics(firebase, { config: {send_page_view: false} });

logEvent(analytics, 'test_event');
```

#### Problem:

I am working on a SPA web app, so I set `send_page_view` to `false` to suspend `page_view` events, and I also sent `screen_view` manually in my router component. The problem is that I am updating `document.title` while route changes, so my `document.title` will be similar as `screen_name`, and because of this bug, GA is collecting both and messing up the report.

See below, those with `| Picture Keeper` are the document titles which were collected via `page_title` parameter in my custom events, and those without the suffix are the `screen_name` I explicitly sent via `screen_view` events.

![image](https://user-images.githubusercontent.com/12502170/179793822-934163f6-834e-477c-bf5a-536eb5ddc928.png)

Of course, I can set `document.title` to an empty string to work it around, but I am wondering if there is a better way, or if it is a bug in SDK or gtag.js.

**Comment by hsubox76** [comment]
Can you test if it works the same if you use gtag.js by itself without Firebase? If so, you can try to bring it up with the gtag team or GA team. If not, let us know and we will look into it.
