### ISSUE TITLE
Firestore FirebaseError Resource Exhausted: Quota Exceeded, Quota has not been exceeded and caching is disabled (WEB)

### ISSUE THREAD

**Issue by iocuydi** [firebase/firebase-js-sdk#6455]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome 103.0.5060.114 
  * Firebase SDK version: 8.0.1
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
We use firestore in our web app. It does not use offline persistence and never has.

Certain users are experiencing this quota error anytime a firestore read is made. They use corporate issue laptops that were recently replaced, and after the replacement they are getting this error (Firestore FirebaseError Resource Exhausted: Quota Exceeded). We also use firebase database, auth, storage, and functions, and these work without issue. Our other customers without the managed devices are not experiencing any errors, the read quota is definitely not exhausted.

We previously had to enable experimentalForceLongPolling with this same customer to make firestore work on their managed laptops before. After doing this, it worked for the past year without issue until today.

Perhaps the wrong error message is being thrown? Are there any recommended steps to take to see whether this is an IT firewall issue? Maybe ping certain addresses and see if it's blocked? It seems that this is related to the corporate network but it is hard to troubleshoot with this error message.

**Comment by tom-andersen** [comment]
We have a test page to identify network problems. Try opening this page on the corporate laptop and see if tests pass.

https://debug-my.firebaseapp.com/
