### ISSUE TITLE
Notification does not show icon.

### ISSUE THREAD

**Issue by NorbertBodziony** [firebase/firebase-js-sdk#6466]
### [REQUIRED] Describe your environment

  * Operating System version: macOs 12.3
  * Browser version: None
  * Firebase SDK version: v10.2.0
  * Firebase Product: FCM (auth, database, storage, etc)

#### Steps to reproduce:
Icon passed via `notification` does not show on device. Notification itself works. 
Notification triggered via test firebase UI works and shows correct image.

#### Relevant Code:

```javascript
await messaging.sendToDevice(token, {
      data: data,
      notification: { ...notification, icon: 'https://synthetify.io/icons/sny.png' },
    })
```

**Comment by jbalidiong** [comment]
Hi @NorbertBodziony, thanks for reaching out. I was able to reproduce the behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

I've added this to our internal tracker (b/241885017).
