### ISSUE TITLE
FR: Firestore Rate Limiting

### ISSUE THREAD

**Issue by sbnon** [firebase/firebase-js-sdk#647]
In order to protect against malicious users, I would like to be able to specify rate limiting rules in Firestore.

Ideally, I want Firestore to tally usage data for signed-in users and expose it in rules on `request.auth`. I could then use that to rate limit.

For instance, I want to be able to write something like the following in my rules:

```
allow read if: request.auth.usage.last1Minute.readOps < 400 && request.auth.usage.last1Day.readOps < 5000
```

(where readOps, writeOps, deleteOps, would all be accumulated and exposed at various time frames)

or, alternatively:

```
allow read if: request.auth.usage.last1Minute.cost < 0.02 && request.auth.usage.last1Day.cost < 0.15
````

(where "cost" is the dollar cost accumulated by the user in the periodaccording to the Firestore billing rules)

**Comment by mcdonamp** [comment]
There are solutions you can do for per-user rate limiting using Rules (e.g. http://jsfiddle.net/firebase/VBmA5/)

We've discussed exposing this information, but at present we don't expose quota, rate limiting, or billing metrics. There are likely better ways of configuring these things than Rules (which are primarily for authN/Z, resource definition, type validation). The worry about exposing them is having a proliferation of different config files (`firestore.quota`, `firestore.billing`, `firestore.rules`, etc.) that confuse users unnecessarily.

**Comment by mcdonamp** [comment]
I'll file an internal bug on this and close this out, as the `js-sdk` repo is likely not the right place to track implementation.

**Comment by sbnon** [comment]
Thank you for the response and the demo link. I need to be able to handle bursts though (e.g. allow you to create 100 "messages" at once but not more than 1000 messages in a day) so I don't think that approach would be feasible for me.

I think incorporating usage data in Rules would be both very natural and powerful. It's where I can control access and rate limiting seems like a natural part of that. Also having it as part of Rules would give you the power to customize the rates by things like whether the user has a validated email address, whether the the user is an "admin/moderator" or has other user attributes.

**Comment by mcdonamp** [comment]
I agree that there are definitely cases where it makes sense to have conditions referencing limits as well as other properties (e.g. trusted vs untrusted IPs or users).

There a long list of things developers likely need to do:

- authentication
  - IP based (including GeoIP for region locking)
  - **user based**
- **authorization**
- auditing
- **schema validation**
  - potentially including PII (or other) annotations
- **index management**
- quota
  - absolute threshold
  - **rate limiting**
- billing
- metrics export
- triggering
  - call a webhook or a Cloud Function
- alerting
- **business logic**

Those in **bold** are things we feel like we have a plausible story around in Rules today (not perfect, plausible). Others are things we clearly need to think harder about and invest more in.

**Comment by jaschaio** [comment]
@mcdonamp has there been an update for this? Is this issue being tracked anywhere else? I couldn't find a way to rate limit create requests.

**Comment by nicholmikey** [comment]
@mcdonamp Anything new on this front? I'm in a case now where I want to prevent users from over-using an API, but i'm terrified of doing a firestore read/write for every API call due to the cost.

**Comment by agcty** [comment]
Any updates?

**Comment by mcdonamp** [comment]
Unfortunately not. We'll definitely let folks know if there are updates though.

**Comment by Ornias1993** [comment]
This means firestore is basically unusable for opensource in the current state.
Yeay for users being able to "request bomb" you daily usage limit instead of a DDOS.

Should we rebrand: DDOS by Google?

**Comment by Hinaser** [comment]
Bump.
I am currently designing data-model through firestore, and considering how to prevent burst access from malicious users on the internet.
It is really great if security rules have abilities to restrict such burst traffic.

At this time, when we need to read/write data on firestore for service in production, we must access to data through cloud-functions only for rate-limiting.
