### ISSUE TITLE
Firestore ArrayUnion error

### ISSUE THREAD

**Issue by ns200310** [firebase/firebase-js-sdk#6472]
Dear team,
I'm facing an issue in the latest firebase js SDK version (Version 9.9.1) as follows,
When I try to update an array in the Firebase Firestore through the ArrayUnion function which has been provided in the official documentation (https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array), it works for the arrays that are in the root of the document but, if the relevant array is located inside of a map value rather than adding new elements to the array it updates the array by resetting the whole array. for your reference please check the below example. Thank you.

###  Code
`updateDoc(doc(db,"ABC","ABC"),{
           abc:{
pqr:arrayUnion({arrayId:arrayId, item:item})
} 
   }).then().catch()`

**Comment by hsubox76** [comment]
You need to use dot notation when updating nested properties: https://firebase.google.com/docs/firestore/manage-data/add-data#update_fields_in_nested_objects

In your example that would be something like:
`updateDoc(doc(db,"ABC","ABC"),{ "abc.pqr": arrayUnion({arrayId:arrayId, item:item})  })`
