### ISSUE TITLE
Getting error when SignOut on react native

### ISSUE THREAD

**Issue by albinr3** [firebase/firebase-js-sdk#6473]
All works ok, sign in, signup, even the database, but when I am trying to sign out this error show up:

[TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "@firebase/util").getModularInstance(auth).signOut')]

I am using firebase 9.9.1

This is my firebase file:

```
import { initializeApp, getApps} from 'firebase/app';
import {initializeAuth, getAuth} from 'firebase/auth';
import { initializeFirestore } from 'firebase/firestore';
import { getReactNativePersistence } from 'firebase/auth/react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {REACT_APP_APIKEY, 
    REACT_APP_AUTHDOMAIN,
    REACT_APP_PROJECTID,
    REACT_APP_STORAGEBUCKET,
    REACT_APP_MESSAGINGSENDERID,
    REACT_APP_APPID

} from "@env"
// Firebase config
const firebaseConfig = {
  apiKey: REACT_APP_APIKEY,
  authDomain: REACT_APP_AUTHDOMAIN,
  projectId: REACT_APP_PROJECTID,
  storageBucket: REACT_APP_STORAGEBUCKET,
  messagingSenderId: REACT_APP_MESSAGINGSENDERID,
  appId: REACT_APP_APPID,
  
};
// initialize firebase

let firebaseApp;
let auth;

if (getApps().length < 1) {
   firebaseApp = initializeApp(firebaseConfig);
   auth = initializeAuth(firebaseApp, {
    persistence: getReactNativePersistence(AsyncStorage),
});
}  else {
    auth = getAuth();
}

export default auth;
export const database = initializeFirestore(firebaseApp, {
    experimentalForceLongPolling: true,
  });
```
This is when I am calling the function:

```
import { signOut } from 'firebase/auth';
 import {database, auth} from '../config/firebase';

  const onSignOut = () => {
    try {
      signOut(auth).then(()=> console.log("signout"))
    } catch (error) {
      console.log('Error logging out: ', error)
    }
  };
```

**Comment by hsubox76** [comment]
At first glance, you seem to be importing 2 versions of `firebase/auth`. `firebase/auth/react-native` is a complete Firebase Auth package, not an add-on. You can import all the auth methods you need from it.

Instead of
```
import {initializeAuth, getAuth} from 'firebase/auth';
import { getReactNativePersistence } from 'firebase/auth/react-native';
```
try
```
import { initializeAuth, getAuth, getReactNativePersistence } from 'firebase/auth/react-native';
```
Also make the same changes to your import of `signOut` and anywhere else you use `firebase/auth`.

**Comment by albinr3** [comment]
I finally found the problem, it was my mistake.

As you can see in my firebase file, I export the "auth" as default, but when I am trying to import it, I am importing inside the curly braces {auth}, but It must be outside due it is default. I fixed that and the problem is fixed.

this is the right way:

`import auth, {database} from '../config/firebase';`
