### ISSUE TITLE
Timestamp from admin sdk and client sdk are not compatible

### ISSUE THREAD

**Issue by danielo515** [firebase/firebase-js-sdk#6476]
### [REQUIRED] Describe your environment

  * Operating System version: Macos
  * Browser version: Chrome
  * Firebase SDK version:  9.8.3 (client) 11.0.0 (admin)
  * Firebase Product:  firestore

#### Steps to reproduce:

1. Load any document that has a timestamp using the admin-sdk
2. Do any check on the timestamp value and see the types are not compatible

#### Relevant Code:

```typescript
import * as admin from 'firebase-admin';
import { Timestamp } from 'firebase/firestore';

const db = admin.firestore();

async function checkTimestamp() {
  const docsRefs = (await db.collection('logs').get()).docs;
  const docs = docsRefs.map((doc) => {
    const data = doc.data();
    return data.timestamp instanceof Timestamp
  });
  console.dir(docs); // They are all false
}

checkTimestamp();

```
I can easily do a conversion between them doing `Timestamp.fromDate(data.timestamp.toDate())`, but I wanted to confirm that this is the expected behavior and  that there is no other workaround.

**Comment by MarkDuckworth** [comment]
Hi @danielo515, I would also expect `data.timestamp instanceof Timestamp` to return false. Although `data.timestamp` may be an instance of `Timestamp` defined in the firebase-admin package, it is not an instance of `Timestamp` defined in 'firebase/firestore' package. There may be further relevant information in this documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof.

If you need any additional help, please provide us more information about your use case.

**Comment by danielo515** [comment]
Hello @MarkDuckworth .
My use-case was just re-using client side validation logic (built using zod) on some local scripts used to verify and update data.
I really wish the admin-sdk and client sdk share the same data-types and data constructors for what I consider to be the same type, but I understand that there may be some edge cases that I am not aware.
For now, I am just OK with my existing workaround.
Thanks!

**Comment by MarkDuckworth** [comment]
Thanks for the information on your use case. I had a discussion with my team about this today. It's not something that we currently have plans to address, however it is on our radar. Given that you also have an acceptable workaround, I'm going to close this issue. Please reach out if you have follow up concerns.
