### ISSUE TITLE
FR add "sideEffects" flag to package.json

### ISSUE THREAD

**Issue by EECOLOR** [firebase/firebase-js-sdk#648]
### Describe your environment

The OS is not relevant, SDK version is 4.6.2 and the product I think is irrelevant too.

### Describe the problem

Most of the firebase library is included in builds while a lot could be chopped away. Webpack (and some other utilities) have a mechanism that allows them to significantly reduce the size of big libraries, also known as tree-shaking.

To automatically enable that for webpack a setting needs to be added to the `package.json` called `sideEffects`. You can read more about that here: https://github.com/webpack/webpack/tree/master/examples/side-effects

I could probably achieve a similar effect by depending on separate modules like `@firebase/app` but this might help the internet (page speeds) and developers that are not paying a lot of attention to minimized module sizes.

**Comment by EECOLOR** [comment]
Some extra info: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by jshcrowthe** [comment]
Hey @EECOLOR,

We are actively looking in to how we can make Firebase better lend itself to tree-shaking scenarios. Unfortunately with how the SDK is currently structured, we can't set the `sideEffects` flag to `true`. In order for us to set that flag, we would need to change some fundamental things about the SDK that would impact a lot of users.
