### ISSUE TITLE
Updating to 9.8.0 throws an error on compilation

### ISSUE THREAD

**Issue by janswist** [firebase/firebase-js-sdk#6492]
I try to update code to 9.9.1, but get this problem. The latest version working for me is 9.7.0. When trying to update to 9.8.0 or higher I get this error below:

```
error  in ./node_modules/idb/build/index.js

Module parse failed: Unexpected token (83:4)
You may need an appropriate loader to handle this file type.
| }
| replaceTraps((oldTraps) => ({
|     ...oldTraps,
|     get: (target, prop, receiver) => getMethod(target, prop) || oldTraps.get(target, prop, receiver),
|     has: (target, prop) => !!getMethod(target, prop) || oldTraps.has(target, prop),

 @ ./node_modules/@firebase/app/dist/esm/index.esm2017.js 5:0-29
 @ ./node_modules/firebase/app/dist/index.esm.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

```

**Comment by hsubox76** [comment]
It sounds like possibly your build config doesn't support some ESM2017 features? I can't tell you more without knowing how your project is set up. What build tooling are you using? Are you using a framework?

**Comment by janswist** [comment]
> It sounds like possibly your build config doesn't support some ESM2017 features? I can't tell you more without knowing how your project is set up. What build tooling are you using? Are you using a framework?

Sorry, I didn't got notification about your message. Only about the thread being closed 😄 

I'm using Vue.js 2.x. if something
