### ISSUE TITLE
Unable to send Firebase Cloud Messages to Firefox. Authentication Error.

### ISSUE THREAD

**Issue by kosso** [firebase/firebase-js-sdk#6523]
* Operating System version: macOS 12.1 
  * Browser version: Firefox 103.0.2 & Chrome 103.0.5060.134
  * Firebase SDK version: 9.9.1
  * Firebase Product: cloud messaging

Testing Firebase cloud messaging works perfectly as expected when using a token created in Chrome. 

However when using a token created in Firefox, any attempts to send a message fails with an authentication error. 
Using the Cloud Messaging API (Legacy) via Curl results in an error : `AuthenticationError`. 
Using the Firebase Cloud Messaging API (V1) via the `firebase-admin` package and NodeJS results in the error: 
```
"error": {
                "code": "messaging/third-party-auth-error",
                "message": "Auth error from APNS or Web Push Service"
            }
```

#### Steps to reproduce:

- Configure and serve the following index.html. 
- Create `firebase-messaging-sw.js` in the web root and edit with Firebase credentials.
- When visiting the page, allow notifications when asked. Do this for Chrome and Firefox.
- Use the tokens provided to send a Cloud message.  
- Attempt to send the message using both API versions. 

*Expected result*
- Notifications should arrive for both Chrome and Firefox. 

*Actual result*
- Chrome receives the notification. 
- Firefox does not, and the sending methods fail with an auth error.

#### Relevant Code:

**Browser index.html**

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <style>
            p {
                margin: 20px;
            }
        </style>
    </head>
    <body>
        <script type="module">
            // Import the functions you need from the SDKs you need
            import { initializeApp } from "https://www.gstatic.com/firebasejs/9.9.1/firebase-app.js";
            import {
                getMessaging,
                getToken,
                onMessage,
            } from "https://www.gstatic.com/firebasejs/9.9.1/firebase-messaging.js";

            const firebaseConfig = {
                apiKey: ".....",
                authDomain: ".....",
                projectId: ".....",
                storageBucket: ".....",
                messagingSenderId: ".....",
                appId: ".....",
                vapidKey: "<Generated Key Pair from Web Push Certificates section in Firebase Console>"
            };

            const app = initializeApp(firebaseConfig);

            window.messaging = getMessaging();
            window.messaging.onMessageHandler = console.log;
            getToken(window.messaging, { vapidKey:firebaseConfig.vapidKey }).then((token) => {
                const p = document.createElement("p");
                p.appendChild(document.createTextNode(token));
                document.querySelector("html").appendChild(p);
            });
        </script>
    </body>
</html>
```

**Service Worker** : firebase-messaging-sw.js

```
importScripts('https://www.gstatic.com/firebasejs/9.9.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.9.1/firebase-messaging-compat.js');

// Firebase Cloud Messaging Service Worker.
if (firebase.messaging.isSupported()){
    // ARTest config
    firebase.initializeApp({
        <FIREBASE CREDENTIALS>
    });
    const messaging = firebase.messaging();
}
```

**Server : index.js**

```
const firebase = require("firebase-admin");
const serviceAccount = require("./SERVICE_ACCOUNT_CREDENTIALS.json");
const app = firebase.initializeApp({
    credential: firebase.credential.cert(serviceAccount),
});

firebase
    .messaging(app)
    .sendMulticast({
        tokens: [
            "<CHROME TOKEN>",
            "<FIREFOX TOKEN>"
        ],
        data: {
            test: "Test Data",
        },
        webpush: {
            notification: {
                body: "Hello!",
                title: "notification_new_message",
            },
        },
    })
    .then((response) => {
        console.log(JSON.stringify(response, null, 4));
    });
```

**Result:** 

```
{
    "responses": [
        {
            "success": true,
            "messageId": "projects/<PROJECT-NAME>/messages/<MESSAGE ID>"
        },
        {
            "success": false,
            "error": {
                "code": "messaging/third-party-auth-error",
                "message": "Auth error from APNS or Web Push Service"
            }
        }
    ],
    "successCount": 1,
    "failureCount": 1
}
```

**Alternative Legacy Curl request:** 

```
curl -X POST -H "Authorization: key=<SERVER KEY FROM Firebase Console>" -H "Content-Type: application/json" -d '{
  "notification": {
    "title": "Test Notification",
    "body": "Firebase Cloud Messaging for Web using JavaScript"
  },
  "to": "<FIREFOX TOKEN>"
}' "https://fcm.googleapis.com/fcm/send"
```

**Result: ** 

```
{"multicast_id":<MULTICAST_ID>,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"AuthenticationError"}]}
```

**Comment by vietnogi** [comment]
Is it working fine on chrome for you?

**Comment by kosso** [comment]
Yes. As stated, Chrome works. Firefox fails on the send itself. 

ie: It's not an issue of it being received or not.

**Comment by cnpatric** [comment]
Same issue here, token generated by firefox will not be accepted.

**Comment by jbalidiong** [comment]
Hi @kosso, thanks for raising this issue with us. We are actually receiving similar reports about Firebase Authentication errors from APNS or Web Push Service when sending notifications using a Firefox-generated token which is not happening in Chrome. There is already an open bug for this (b/241368946) and our investigation shows that this could be a backend issue, so it's suggested that you file a ticket via the Firebase Support channel instead. You may also share the same details or this issue link when you log a ticket so that our support team could help you better.

**Comment by williamOnsare** [comment]
Also experiencing the same issue of push notifications not being received on Firefox (even when using the Firebase console to send test message) while it works on Chrome

**Comment by SealinGp** [comment]
same issue here, any progress ?

**Comment by cnpatric** [comment]
I wrote firebase support and they said they will update me if they figure out whats going on, I'll update here too if I get any useful response but for now it seems like the only thing we can do is wait.

@jbalidiong could we get a full url to the bug ticket or is that ticket internal only?

**Comment by kosso** [comment]
I have also got in touch with Firebase support, who has got back to me. 
I've filled them in with all the testing code and info I can think of, as well as pointing them here. 

Interestingly, they asked me to send copies of the browser errors. 

I've informed them that the errors are coming via the `firebase-admin` package server request, not the browser. 

Obtaining FCM tokens from Firefox isn't the issue. That part works fine. It appears the backend's ability to use them is the issue.

**Comment by kosso** [comment]
In other news/FWIW: I have just successfully sent and received test notification payloads to Chrome and Firefox using the `web-push` NPM package, only using the VAPID keys, without Firebase or GCM. 

So, Firefox doesn't appear to be the problem.

**Comment by cnpatric** [comment]
Just FYI: Firebase support answered to my ticket and they rolled out changes and say this issue should now be fixed

**Comment by kosso** [comment]
I can confirm this issue is now fixed.  The test above now works for both Chrome and Firefox. 
No package updates were needed on my end. 

👍🏼
