### ISSUE TITLE
signInWithEmailAndPassword never resolves nor reject

### ISSUE THREAD

**Issue by Mocsa1974** [firebase/firebase-js-sdk#6540]
* Operating System version: IOS 15
  * Browser version: IOS Simulator
  * Firebase SDK version: 9.9.2
  * Firebase Product: auth
  * Angular version: 14.1.0

Import { initializeApp} from 'firebase/app';
import {getAuth, signInWithEmailAndPassword' from 'firebase/auth';

login() {
 const app = initializeApp(environment.fbconfig);
 const auth = getAuth(app);
signInWithEmailAndPassword(auth,'myemail','mypassword').then(user => alert('logged in ').catch(err=>console.log('error);
}

signInWithEmailAndPassword never resolves and catch nevewr triggered.

Aon web or on an android device it works perfectly.

**Comment by Mocsa1974** [comment]
if i used initalizeAuth(app,{persistence:indexedDBLocalPersistence}); it works on IOS but on Ipad not.

**Comment by IshuSingh1** [comment]
Hi, 
I am still a beginner in React. But from my understanding, now signInWithEmailAndPassword is a child function of getAuth in 9.9.2. 
So your code should look something like this: 
firebase.js
![image](https://user-images.githubusercontent.com/47675131/185288757-f0aa3c2c-bbd1-48d2-b5af-1608c3856c59.png)

Login function:
After importing `getAuth` as `auth` 
![image](https://user-images.githubusercontent.com/47675131/185288915-eb77b6a5-9647-408a-a551-178dcc3b94dc.png)

**Comment by Mocsa1974** [comment]
One nore thing. Our spp is an ionic6 hyrid app eith cordova. No capacitor.

**Comment by Mocsa1974** [comment]
> Hi, I am still a beginner in React. But from my understanding, now signInWithEmailAndPassword is a child function of getAuth in 9.9.2. My apologies if it does not work with Angular So your code should look something like this: firebase.js ![image](https://user-images.githubusercontent.com/47675131/185288757-f0aa3c2c-bbd1-48d2-b5af-1608c3856c59.png)
> 
> Login function: After importing `getAuth` as `auth` ![image](https://user-images.githubusercontent.com/47675131/185288915-eb77b6a5-9647-408a-a551-178dcc3b94dc.png)

Exactly.
But i think signInWithEmailAndPassword need to be imported from firebase/auth.
It seems than signInWithEmailAndPassword stuck in an "infinite loop" on firebase backend.
Neither "than" nor "catch" never triggered.

On Iphone , web, android it work fine. But on Ipad not.

**Comment by Mocsa1974** [comment]
After Downgrade firebase from 9.9.2 to 8.10.1 it works fine on Ipad too.

**Comment by hsubox76** [comment]
I just noticed you mentioned you were using Cordova. Have you tried using the cordova version of Auth? `firebase/auth/cordova` instead of `firebase/auth`, like:

```
import {getAuth, signInWithEmailAndPassword} from 'firebase/auth/cordova';
```
