### ISSUE TITLE
AppCheck not compatible with custom domains

### ISSUE THREAD

**Issue by grmatthews** [firebase/firebase-js-sdk#6556]
https://github.com/firebase/firebase-js-sdk/issues/6278 is not fixed, and the issue is closed to comments.

The browser console error I am getting is:

@firebase/app-check: FirebaseError: AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. (appCheck/fetch-status-error).

The custom domain setup I have performed is:
- I have a domain, jobsforjoe.com pointed at my Firebase app
- Under Firebase Console / Hosting / Domains , I have 2 additional entries:
   -- jobsforjoe.com  --- Connected (Custom)
   -- www.jobsforjoe.com --- Connected (Redirect -> jobsforjoe.com)
- Under Firebase Console / Authentication / Settings / Authorized Domains I have 'jobsforjoe.com  Custom'

Is this still a bug or is there something else I should be checking?

**Comment by hsubox76** [comment]
What provider are you using for AppCheck? ReCAPTCHA, ReCAPTCHA Enterprise, or custom? If you're using one of the ReCAPTCHAs, did you add all your domains in your ReCAPTCHA console?

**Comment by grmatthews** [comment]
ReCaptcha v3 (normal, not enterprise), and yes I checked the ReCaptcha keys provided are correctly configured in my app.

app code
------------

const appCheck = initializeAppCheck(app, {
    // This key doesn't need to be protected - it's the 'Site key' from Google.com recaptcha setup
    provider: new ReCaptchaV3Provider("<sharable recaptcha key>"),

    // Optional argument. If true, the SDK automatically refreshes App Check
    // tokens as needed.
    isTokenAutoRefreshEnabled: true,
})

**Comment by grmatthews** [comment]
Can close this. I added jobsforjoe.com to the ReCaptcha config, and it now works.

Would be good if there was a succinct list of steps to set this up, e.g.
1. Point domain via domain name register to Firebase app.
2. Add custom domain under Firebase Console / Hosting / Domains
3. Add custom domain under Firebase Console / Authentication / Settings / Authorized Domains
4. Ensure ReCaptchav3 has custom domain added, as well as base Firebase app domain

Potentially Google could also make steps 2+3 into 1 step?
