### ISSUE TITLE
Upgrade from 9.8.4 to 9.9.3 causes "No Firebase App '[DEFAULT]' has been created" (app/no-app)

### ISSUE THREAD

**Issue by Slapbox** [firebase/firebase-js-sdk#6571]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 7
  * Browser version: Electron 18.3.x
  * Firebase SDK version: 9.9.0 through 9.9.3
  * Firebase Product: database AND storage

### [REQUIRED] Describe the problem

Code that works perfectly in `9.8.4` throws an error in `9.9.0` and `9.9.3` with the message:

> Error: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)

Interestingly, this seems to happen despite initial sync with Firebase seeming to work as intended.

#### Steps to reproduce:

Apparently just call `getStorage()`, imported from `'firebase/storage'`, or `getDatabase()`, imported from `'firebase/database'` 

(of course, after initializing the app with `initializeApp(config)`, imported from `'firebase/app'`)

Reverting to `9.8.4` instantly resolves the issue.

#### Relevant Code:

`getStorage()`

and

`getDatabase()`

Both throw the same error.

**Comment by Slapbox** [comment]
#### Additional info:

We were affected by #6036, and I'm guessing that the fix to that issue is what's causing the new issue. @maneesht

**Comment by maneesht** [comment]
@Slapbox My suspicion is that you may have two different versions of `@firebase/app` and/or `@firebase/database`. Can you run an `npm ls @firebase/database` and `npm ls @firebase/auth`?

**Comment by maneesht** [comment]
For reference - https://github.com/firebase/firebase-js-sdk/issues/6388

**Comment by Slapbox** [comment]
That was indeed the issue! Thanks so much and sorry for the issue clutter!
