### ISSUE TITLE
Error in Internet Explorer 11 (Messaging)

### ISSUE THREAD

**Issue by metalgigio** [firebase/firebase-js-sdk#658]
**Description of the Issue:**

Internet Explorer 11 fire a javascript error that obviously stop every following javascript

file: webpack:///messaging/dist/esm/src/helpers/base64-to-array-buffer.js
line: 17
Error (in italian): L'oggetto non supporta la proprietà o il metodo 'repeat'

**Environment Configuration:**

Operating System version: Windows 10
Firebase SDK version: 4.12.1
Firebase Product: Messaging

**Comment by mmermerkaya** [comment]
Messaging is not supported by IE 11, because IE 11 does not support service workers.

For more information please see: https://firebase.google.com/docs/cloud-messaging/js/client

**Comment by metalgigio** [comment]
Yes, i know isn't supported, but as i wrote that error broke all the js. So entire js doesnt work in ie11 since is, as best practice, minified all in one file.

**Comment by mmermerkaya** [comment]
I'd either not include messaging in your ES5 build, or add the necessary polyfills to make your code work in IE 11.

I'll investigate this and check if we call base64ToArrayBuffer if the app is running in an unsupported browser.

**Comment by metalgigio** [comment]
Well, ur right i should use polyfills but i prefer keep low js size since ie11 doesn not support messaging even with a polyfills.
For the record, or if someone needed too, I solved enclosing all messaging code like this:

```
if ('serviceWorker' in navigator) {
    var config = {
     ...
    };
    firebase.initializeApp(config);
    ...
}
```
