### ISSUE TITLE
techlabz sale and repair

### ISSUE THREAD

**Issue by techlabz123** [firebase/firebase-js-sdk#6593]
Instructions to Change the Default Framework Text style on Windows 11
Windows 11 is really smooth contrasted with Windows 10, yet [computer repairs UK](https://www.techlabz.uk/) imagine a scenario where you conclude that you could do without the text style, or simply need something else. This is the way you can utilize the library to change Windows 11's framework text style.
Step by step instructions to Make A REG Document to Change the Default Framework Textual style
Caution: Be cautious when altering the vault. Heedlessly erasing keys or altering values can break Windows 11. Assuming you cautiously adhere to our guidelines, you'll be okay.
Windows 11 doesn't uphold changing the default framework textual style through any of the typical means: you can't do it in the Text styles window, there is nothing in Openness elements, and there isn't so much as a heritage choice in the Control Board. That implies we'll need to adjust the Windows Vault.
Find or Introduce the Textual style You Need
The main thing you want to do is recognize which textual style you need. You can see the text styles that are now introduced on your PC by going to the Text styles window.
Click the Beginning button, type "textual style settings" into the hunt bar, then click "Text styles Settings." On the other hand, you can open the Settings application and explore to Personalization > Text styles
Open the Beginning Menu, look for "text style settings," then, at that point, open it.
Look at the introduced text styles and check whether anything requests to you. Assuming not a single one of them do, you can definitely relax — you can constantly introduce more text styles.
We want to get the appropriate name of the textual style we need to utilize first. Look down in the text styles window until you track down it, then, at that point, note the name. Suppose for instance we need to involve the most dubious textual style on the planet: Comic Sans. The appropriate name is "Funny Sans MS" in our model.
Find the text style you need, then, at that point, observe the appropriate name.
Make the REG Record
You can change the library straightforwardly utilizing the Vault Supervisor (Regedit), or you can compose a pre-characterized vault document (REG record) that will consequently apply specific changes when you double tap it. Since this specific library hack requires changing various lines, it is more proficient to simply compose a REG document than to physically go through the vault.
You'll require a plain content tool for this step. Notebook will in all actuality do fine and dandy if you have no particular program you need to utilize.
Open up Scratch pad, then, at that point, glue the accompanying text into the window:
Windows Vault Proofreader Form 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts]
"Segoe UI (TrueType)"=""
"Segoe UI Striking (TrueType)"=""
"Segoe UI Striking Italic (TrueType)"=""
"Segoe UI Italic (TrueType)"=""
"Segoe UI Light (TrueType)"=""
"Segoe UI Semibold (TrueType)"=""
"Segoe UI Image (TrueType)"=""
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Font Substitutes]
"Segoe UI"="NEW-Textual style"
Change out "NEW-Textual style" for the legitimate name of whichever textual style you need. This is what it resembles for our Comic Sans model:
A model REG document that will change the default framework text style to Comic Sans.
Whenever you have it finished up suitably go to the upper left-hand side and snap Record > Save As. Name the record anything you desire (preferably something legitimate), then put ".reg" toward the end. It is significant that you utilize the ".reg" record augmentation — it won't work in any case. Click "Save," and you're finished.
Utilize the REG Document to Change the Default Framework Textual style
All you really want to do presently is double tap the REG record you made. You'll get an admonition popup that utilizing a dishonest REG record can hurt your PC.
You can believe this REG document since we composed it, and you've seen all that it does. By and large, you shouldn't believe irregular REG documents you track down on the web without really looking at them first. Feel free to click "Yes," then restart your PC. At the point when it gets done with restarting, you'll utilize another default framework textual style.
Change the Default Framework Textual Style Back to Segoe
Obviously, you're not for all time stayed with the new text style once you transform it. You can undoubtedly transform it back whenever. You really want to make one more REG record very much as we did previously, with the exception of you'll utilize different code. Reorder the accompanying into your second REG record:
Windows Vault Manager Variant 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts]
"Segoe UI (TrueType)"="segoeui.ttf"
"Segoe UI Dark (TrueType)"="seguibl.ttf"
"Segoe UI Dark Italic (TrueType)"="seguibli.ttf"
"Segoe UI Striking (TrueType)"="segoeuib.ttf"
"Segoe UI Striking Italic (TrueType)"="segoeuiz.ttf"
"Segoe UI Emoticon (TrueType)"="seguiemj.ttf"
"Segoe UI Noteworthy (TrueType)"="seguihis.ttf"
"Segoe UI Italic (TrueType)"="segoeuii.ttf"
"Segoe UI Light (TrueType)"="segoeuil.ttf"
"Segoe UI Light Italic (TrueType)"="seguili.ttf"
"Segoe UI Semibold (TrueType)"="seguisb.ttf"
"Segoe UI Semibold Italic (TrueType)"="seguisbi.ttf"
"Segoe UI Semilight (TrueType)"="segoeuisl.ttf"
"Segoe UI Semilight Italic (TrueType)"="seguisli.ttf"
"Segoe UI Image (TrueType)"="seguisym.ttf"
"Segoe MDL2 Resources (TrueType)"="segmdl2.ttf"
"Segoe Print (TrueType)"="segoepr.ttf"
"Segoe Print Strong (TrueType)"="segoeprb.ttf"
"Segoe Content (TrueType)"="segoesc.ttf"
"Segoe Content Strong (TrueType)"="segoescb.ttf"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Font Substitutes]
"Segoe UI"=-
Then, at that point, save it, very much as we did previously. Run the REG document, click "Yes" at the advance notice, and afterward restart your PC. Your framework textual style will have returned to ordinary.
The REG document to reestablish the framework text style to the [laptop repair UK](https://www.techlabz.uk/service/laptop-repair) default text style will constantly be something similar, independent of what textual style you chose already. Since it is consistently something very similar, we've included it here, in the event that you would rather not make another yourself.

**Comment by rizafran** [comment]
Closing this ticket since the issue stated seems unrelated to Firebase SDK.
