### ISSUE TITLE
FirebaseError: Firebase Storage: An unknown error occurred

### ISSUE THREAD

**Issue by yumietzk** [firebase/firebase-js-sdk#6600]
### My environment

  * Operating System: macOS
  * Browser: Chrome
  * Firebase SDK version: v9
  * Firebase Product: Storage

### The problem

I have an unknown error when trying to upload images to Cloud Storage while specifying metadata for the files and monitoring upload progress.

```javascript
const imagesRef = ref(storageRef, `${path}`);
 
const metadata = {
     contentType: "image/jpeg",
};
 
const uploadTask = uploadBytesResumable(imagesRef, file, metadata);
 
uploadTask.on(
     "state_changed",
     (snapshot) => {
       const currentProgress = Math.round(
         (snapshot.bytesTransferred / snapshot.totalBytes) * 100
       );
       setProgress(currentProgress);
     },
     (error) => {
       console.error(error);
       toast.error("Error uploading file", { position: "top-right" });
       setProgress(-1);
     },
     () => {
       getDownloadURL(uploadTask.snapshot.ref)
         .then((url) => handleFinish(url, file.name))
         .catch((err) => console.error(err))
         .finally(() => {
           setFile(null);
           setProgress(-1);
         });
    }
);
```

The unknown error:
![error](https://user-images.githubusercontent.com/61277579/190190539-a1eeb8be-dc68-4ff7-8e65-05aff587f7f9.jpeg)

However, in Firebase Storage, it seems like images are uploaded as I can see them although the file type that I try to specify as “image/jpeg” remains the default one as “application/octet-stream”: 
![image1](https://user-images.githubusercontent.com/61277579/190194582-c8337996-6f81-41f5-8fde-44e28109b9ba.jpeg)

### Solution that I tried (Failed)

Since there is no detailed explanation to solve this error [here](https://firebase.google.com/docs/storage/web/handle-errors), I tried to implement the feature to upload images in the simplest way first using uploadBytes() method.

```javascript
const imagesRef = ref(storageRef, `${path}`);
 
const metadata = {
     contentType: "image/jpeg",
};
 
uploadBytes(imagesRef, file, metadata).then((snapshot) => {
     console.log("Uploaded a blob or file!");
});
 
// const uploadTask = uploadBytesResumable(imagesRef, file, metadata);
 
// uploadTask.on(
//   "state_changed",
//   (snapshot) => {
//     const currentProgress = Math.round(
//       (snapshot.bytesTransferred / snapshot.totalBytes) * 100
//     );
 //     setProgress(currentProgress);
//   },
//   (error) => {
//     console.error(error);
//     toast.error("Error uploading file", { position: "top-right" });
//     setProgress(-1);
//   },
//   () => {
//     getDownloadURL(uploadTask.snapshot.ref)
//       .then((url) => handleFinish(url, file.name))
//       .catch((err) => console.error(err))
//       .finally(() => {
//         setFile(null);
//         setProgress(-1);
//       });
//   }
// );
```

 This works perfectly. There is no error, and I see the uploaded images in Firebase Storage whose file type changes to “image/jpeg” as expected (image2):
![image2](https://user-images.githubusercontent.com/61277579/190194732-f3668f07-7faf-4bef-a141-55ced002b205.jpeg)

However, when switching the method to uploadBytesResumable() method, the unknown error shows up again.
I am not sure if this is the error from the uploadBytesResumable() method, or if this is because of my environment, or if there are other problems.

For now, there is no clear solution other than just not using the uploadBytesResumable() method.

**Comment by maneesht** [comment]
@yumietzk - when you use `getDownloadURL`, does the network tab report any errors?

**Comment by yumietzk** [comment]
@maneesht Thank you for the comment! Actually, now that I developed the site more, I tried to set the function as the original code with `uploadBytesResumable ` and `getDownloadURL`. Then it all works. So, I am not sure what the problem was. The error might sometimes happen for unknown reasons, and the cause might be something in my environment.
