### ISSUE TITLE
v9 docs for `getRedirectResult` need to be updated to reflect `null` return value  

### ISSUE THREAD

**Issue by fastfedora** [firebase/firebase-js-sdk#6616]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12.5.1
  * Browser version: Chromium 102.0.5005.63
  * Firebase SDK version: 9.10.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

In v8, `getRedirectResult` returned a `UserCredential` with a null user if no redirect operation was called. In v9, it now returns `null`. While the method signature was changed for the v9 documentation, [the description](https://firebase.google.com/docs/reference/js/auth#getredirectresult) still says that a `UserCredential` will be returned with a null user, which is confusing. It was only after looking at the PR #5617, which made the actual change, that I could verify the new behavior.

This also should be added to the [upgrade instructions](https://firebase.google.com/docs/web/modular-upgrade) for moving from v8 to v9, as this can break existing code if it is not changed.

**Comment by dwyfrequency** [comment]
The doc string has been update.
