### ISSUE TITLE
firebase.auth().currentUser.metadata.lastSignInTime is not updating on next time user signs in if not much time has passed.

### ISSUE THREAD

**Issue by serhiipalash** [firebase/firebase-js-sdk#662]
* Operating System version: Mac Os
  * Firebase SDK version: 4.12.1
  * Firebase Product: auth

Bug: `firebase.auth().currentUser.metadata.lastSignInTime` is not updating on next time user signs in if not much time has passed.

It looks strange when I login first time, then logout, then login again and then I see that my user `lastSignInTime` is not current session sign in time, but previous one.

<img width="680" alt="screen shot 2018-04-10 at 10 23 54 pm" src="https://user-images.githubusercontent.com/14208343/38580545-e3c1db7c-3d12-11e8-8ede-d3354364e495.png">

Test example: https://fir-last-sign-in-time-bug.firebaseapp.com/ with auth in Firebase project https://console.firebase.google.com/u/0/project/fir-last-sign-in-time-bug

Test example code: https://github.com/serhiipalash/firebase-last-sign-in-time-bug

Why is it important. 
Before authenticate user into our app, we need to know is this login first one, to redirect user on /onboarding, or it is not the first one login. To find this info the reasonable way we can compare 

```
firebase.auth().currentUser.metadata.lastSignInTime === firebase.auth().currentUser.metadata.creationTime
```

But these timestamps work in strange way and we have to use async and time expensive function to find the same result

```
firebase
      .auth()
      .currentUser.getIdToken()
      .then(jwtToken => {
        const session = jwtDecode(jwtToken);

        const isFirstTimeSignIn = session.auth_time === firebase.auth().currentUser.metadata.creationTime

        console.info("Is this first time user signs in ", isFirstTimeSignIn); 
      })
      .catch(err => console.log("err: ", err));
```

It takes 0.5-1 second each time user signs in.

It is very important for us to allow users to enter the app as faster as possible. Can you please fix `firebase.auth().currentUser.metadata.lastSignInTime` behavior, so then we can minimize our app start time using sync values comparison instead of async very long function?

Thanks in advance!

P.S. You can check test example console logs for more info
P.P.S. I know that for native SDKs there is isNewUser method on User object. Maybe you can add the same for Web SDK?

Serhii

**Comment by wti806** [comment]
@serhiipalash The lastSignInTime will not be updated if you try to sign in in 2 mins  to reduce the database load for our backend. So you are right, this field is not 100% accurate. It could have a 2mins margin of error.

**Comment by serhiipalash** [comment]
@wti806 is it possible to use fins is current login is the first one in some faster way then with `.getIdToken()` and then `jwtDecode(token)`?

**Comment by wti806** [comment]
You can use this method which returns a `UserCredential` object. https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInAndRetrieveDataWithCredential

And check `userCredential.additionalUserInfo.isNewUser` field.

**Comment by serhiipalash** [comment]
Thanks!
Will `signInAndRetrieveDataWithCredential` be longer then regular `signInWithCredential`?
