### ISSUE TITLE
Firebase Storage Emulator breaks on update 

### ISSUE THREAD

**Issue by callum-gander** [firebase/firebase-js-sdk#6621]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04 LTS (wsl2)
  * Browser version: 105.0 (64-bit) (this is an issue across browsers)
  * Firebase SDK version: 9.9.3 updating to 9.10.0 as well as firebase-tools 10.9.2 updating to 11.9.0
  * Firebase Product: storage

### [REQUIRED] Describe the problem

When I update, connect my emulators as usual using the below configuration that works fine with the prior versions, whenever I try to upload files using uploadBytesResumable I get a (storage/unknown) error. This doesn't seem to affect auth as auth still works fine with the emulators, this is just a storage API issue.

#### Steps to reproduce:

1. updating from the versions as specified at top
2. try upload
3. fails with the storage/unknown error

#### Relevant Code:

The config
```
import { initializeApp } from "firebase/app";
import "firebase/compat/analytics";
import { getAuth, connectAuthEmulator } from "firebase/auth";
import { getStorage, connectStorageEmulator } from "firebase/storage";
import { getFunctions, connectFunctionsEmulator } from "firebase/functions";

const firebaseConfig = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID,
    measurementId: process.env.FIREBASE_MEASUREMENT_ID,
};

// Initialize Firebase

const firebase = initializeApp(firebaseConfig);

const storage = getStorage(firebase);
const auth = getAuth(firebase);

if (process.env.NODE_ENV === "development") {
    connectStorageEmulator(storage, "localhost", 9199);
    console.log("RUNNING EMULATED FIREBASE");
    connectAuthEmulator(auth, "http://localhost:9099", {
        disableWarnings: true,
    });
    connectFunctionsEmulator(auth, "http://localhost:5001");
}

export { storage, auth };

```
No more code is attached as this definitely is an internal firebase issue not with my code as it works fine with a prior version

**Comment by callum-gander** [comment]
Any updates on whether this is being looked into?

**Comment by Yuangwang** [comment]
Hi, this looks like the same issue as https://github.com/firebase/firebase-tools/issues/4927, could you try updating to the lates firebase-tools version again? That should fix your issue.

I'll close this issue for now but please try it out and we can reopen if you're still having issues.
