### ISSUE TITLE
"Registration failed - push service error" after upgrade to v9 compat

### ISSUE THREAD

**Issue by ElVisPL** [firebase/firebase-js-sdk#6627]
### Describe your environment

  * Operating System version: Windows, MacOS
  * Browser version: Chrome, different versions
  * Firebase SDK version: 9.9.4
  * Firebase Product: Firebase Messaging (push notifications)

#### Steps to reproduce:
This is something that we couldn't reproduce, but after upgrading to v9 compat we started to receive many Honeybadger reports about error: `Registration failed - push service error` - no more details provided. We weren't receiving those for version 8

Is this something expected - like Firebase Messaging >9 started to throw some errors that were not being thrown before?

![image](https://user-images.githubusercontent.com/3405010/192213118-60dc7335-68b3-4ffa-a192-310aeab2a8c0.png)

**Comment by zwu52** [comment]
"Is this something expected - like Firebase Messaging >9 started to throw some errors that were not being thrown before?" >>> not that we know of.  this might have to do with Chrome's rollout of the notification permission mechanism where some permissions are removed based on user behaviors
