### ISSUE TITLE
Not able to initialize Firestore under Cypress

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-js-sdk#6631]
### [REQUIRED] Describe your environment

  * Operating System version: __mac 12.6___
  * Browser version: __safari 16.0; Cypress 10.8.0___
  * Firebase SDK version: __@firebase/firestore 3.4.5 or 3.5.0___
  * Firebase Product: __Firestore___ (auth, database, storage, etc)

### [REQUIRED] Describe the problem

Developing my web app, everything works smooth in normal browser instance (see pic 1), but when the same app is loaded under Cypress (10.8.0), the handshake with Firebase Emulator fails.

I cannot see anything in the logs that would provide a clue, why. Should do a minimum-reprodicing-version so that application complexities can be ruled out.

#### Steps to reproduce:

- *tbd. Will provide a link to minimum reproducible repo*

### Pictures

![image](https://user-images.githubusercontent.com/1297734/192568970-9bee9b9a-1c68-454d-be1a-7d822bee9b6e.png)

*Log in normal browser (Safari; Chrome also works)*

![image](https://user-images.githubusercontent.com/1297734/192569124-75af215f-77d4-465b-bac0-73f56067d8bf.png)

*Log in Cypress*

**Comment by MarkDuckworth** [comment]
@akauppi, can you update your emulator (firebase-tools) and let me know if that helps you? A security update was released in 3.5.0 which changed how the SDK authenticates to the back end. This is likely the source of your issue.

**Comment by akauppi** [comment]
I was a bit hasty in writing this. 10 minutes later had found https://github.com/cypress-io/cypress/issues/2374 

It's now fixed, by using `experimentalForceLongPolling` when running under Cypress.

**Comment by akauppi** [comment]
@MarkDuckworth  I had tried it also with 3.5.0 (mentioned in the ticket). As you can see above, I don't think it's related to any new things. The Cypress issue has been created in 2018.

What Firestore could do, ... *knock knock* is see if `window.Cypress` is truthy and long polling is *not* enabled. Give a warning that nudges people in the right direction. Maybe.
