### ISSUE TITLE
Firebase Auth is failing on Safari 16.1 (destructuring error)

### ISSUE THREAD

**Issue by koush** [firebase/firebase-js-sdk#6636]
* Operating System version: MacOS 13 or iOS 16
  * Browser version: Safari 16.1
  * Firebase UI version: Latest
  * Firebase SDK version: Latest

### [REQUIRED] Describe the problem

Firebase UI does not work with Safari on Mac or iPhone.

#### Steps to reproduce:

1. Go to https://fir-ui-demo-84a6c.firebaseapp.com/. This is the project's own login demo page.
2. Try to log in on Mac or iPhone.
3. Login hangs.

Additionally: these steps work fine with Chrome on the same Mac.

#### Relevant Code:

N/A

Seen in console:

`TypeError: Right side of assignment cannot be destructured`

```
 async onAuthEvent(event: AuthEvent): Promise<void> {
    // this line
    const { urlResponse, sessionId, postBody, tenantId, error, type } = event;
    if (error) {
      this.reject(error);
      return;
    }
```

The event it is receiving seems to be a window Message event, and not the JSON contained within `data` which is what contains the fields to be destructured.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/73924/192711226-75e5206d-0cd0-4107-9ed0-eb72a8f981a6.png">

Crosspost from https://github.com/firebase/firebaseui-web/issues/977

I believe the bug is in the js sdk as the relevant file is in this source file:
https://github.com/firebase/firebase-js-sdk/blob/b6c231a282313aeda59c447c24f71fdad35240bc/packages/auth/src/core/strategies/abstract_popup_redirect_operation.ts#L86

From my understanding of the stack trace, I think the js sdk uses iframes to communicate, and there's some sort of message passing failure happening.

**Comment by prameshj** [comment]
I see this with Safari 16.0 too.. But the [modular demo app](https://github.com/firebase/firebase-js-sdk/tree/master/packages/auth/demo) and the [auth-compat demo app](https://github.com/firebase/firebase-js-sdk/tree/master/packages/auth-compat/demo) from firebase-js-sdk are working ok for me. 

Closing this and leaving the firebaseui issue open.

**Comment by mmmulani** [comment]
we're seeing the same issue with Safari 16.1 beta and we don't use firebaseui, only standard firebase-js-sdk.

**Comment by koush** [comment]
> we're seeing the same issue with Safari 16.1 beta and we don't use firebaseui, only standard firebase-js-sdk.

I ended up using a workaround by managing the auth redirects myself. This also provides an offramp for firebase, if you're only using the js sdk for auth. https://github.com/firebase/firebaseui-web/issues/977#issuecomment-1272388412

**Comment by sww314** [comment]
This should still be open. We are still seeing the issue.

**Comment by samsargent** [comment]
Can also confirm we're seeing this with just the firebase-js-sdk (not using firebaseui). 

If it helps, switching to`signInWithPopup` works. `signInWithRedirect` doesn't work.
