### ISSUE TITLE
Unable to send Firebase Cloud Messages to Edge, Authentication Error

### ISSUE THREAD

**Issue by kbuckinx** [firebase/firebase-js-sdk#6641]
* Operating System version: Windows 10
  * Browser version: Edge 18
  * Firebase SDK version: 8.10.0
  * Firebase Product: messaging

#### Steps to reproduce:
This appears to be a similar issue as https://github.com/firebase/firebase-js-sdk/issues/6523 

I can show push notifications in Chrome, but the same application doesn't show push notifications when embedded as a PWA in a Universal Windows Platform wrapper (UWP). This used to work.

When sending a messaging to a token generated in Edge running inside the UWP, through the legacy api via https://fcm.googleapis.com/fcm/send, I get the error message: `AuthenticationError`. When sending the same message using the same authorisation header to a token generated in Chrome, the message arrives successfully. 

#### Relevant Code:

```javascript
```

**Comment by jbalidiong** [comment]
Hi @kbuckinx, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the error. Please ensure that you've included the VAPID Key that will be used for token generation. Web Push certificates are required for third party web browsers like Firefox, Edge, etc.

I'll be closing this for now. If the issue persists, feel free to comment and reopen this issue.
