### ISSUE TITLE
[AppCheck] Support AppCheck in Worker

### ISSUE THREAD

**Issue by thomasdao** [firebase/firebase-js-sdk#6645]
### [REQUIRED] Describe your environment

  * Operating System version: Mac Monterey 12.5
  * Browser version: Chrome 105.0.5195.125
  * Firebase SDK version:  9.10.0
  * Firebase Product: AppCheck

### [REQUIRED] Describe the problem
Most of Firebase products support `Worker` (for example `Firestore`, `Auth`), however AppCheck does not. My app is already integrating Firebase in worker to optimize performance, however since AppCheck cannot be used in `Worker`, I can't integrate it.

It would be great to support AppCheck in Worker :)

#### Relevant Code:

```javascript
// In Worker
const appCheck = initializeAppCheck(app, {
    provider: new ReCaptchaV3Provider('captcha_id'),
    isTokenAutoRefreshEnabled: true
})
```

Error:
```
Worker caught an error: ReferenceError: document is not defined
    at makeDiv (index.esm2017.js:1037:1)
    at initializeV3 (index.esm2017.js:982:1)
    at ReCaptchaV3Provider.initialize (index.esm2017.js:1161:1)
    at _activate (index.esm2017.js:1444:1)
    at initializeAppCheck (index.esm2017.js:1400:1)
```

The error here is because document is not available in Worker, it is unable to create a div and append to the DOM.

**Comment by laurentpayot** [comment]
+1, I was about to implement AppCheck but I’m also using Firebase in a web worker. OAuth was already tricky with workers. If AppCheck does not support them that’s really a problem because the whole app initialization cannot be offloaded to a worker :confused: 

If it is impossible to make `initializeAppCheck` work in both main thread and worker environments, would it be possible at least to have a similar function meant to be used in a worker environment that would return the html node that needs to be added in the main thread html? Then we could simply use this html like we want, and send it to the main thread via a message and add it to the document our own way.

**Comment by hsubox76** [comment]
Hm, well, App Check comes with two buiilt-in providers based on Recaptcha, RecaptchaV3Provider and RecaptchaEnterpriseProvider, and these both are based on Recaptcha, which I don't think can work in a worker. However, App Check also provides a CustomProvider, that can use some other custom mechanism for attestation (that you would have to implement).

https://firebase.google.com/docs/app-check/web/custom-provider

Possibly if you want to keep using Recaptcha but want to modify the code so the worker is telling the main thread to load the recaptcha scripts and render the widget, you can also use CustomProvider but copy in a lot of our code for RecaptchaV3Provider and modify the parts you need? Let me know if CustomProvider doesn't provide enough functionality for you to do something like this.

**Comment by thomasdao** [comment]
@hsubox76 thanks for replying! 

> Possibly if you want to keep using Recaptcha but want to modify the code so the worker is telling the main thread to load the recaptcha scripts and render the widget, you can also use CustomProvider but copy in a lot of our code for RecaptchaV3Provider and modify the parts you need? 

This sounds scary, especially if in the future this `Recaptcha` module get updated, it would be pretty hard to upgrade.

**Comment by laurentpayot** [comment]
@thomasdao @hsubox76 I could make AppCheck work in my Firebase-dedicated web worker.
I had to initialize AppCheck in the main thread with Recaptcha, get the AppCheck token with [`getToken()`](https://firebase.google.com/docs/reference/js/app-check#gettoken), post a message with this token to the worker, then inside the worker use the [`CustomProvider`](https://firebase.google.com/docs/reference/js/app-check.customprovider) class to initialize AppCheck with this token. Below is an example.

In your main thread:
 ```javascript
const AppCheck = initializeAppCheck(app, {
  provider: new ReCaptchaV3Provider('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
  isTokenAutoRefreshEnabled: true
})
const appCheckToken = await getToken(appCheck)
myWorker.postMessage(appCheckToken)
```

In your worker:
```javascript
initializeAppCheck(app, {
  provider: new CustomProvider({ getToken: () => Promise.resolve(appCheckToken) })
})
```

**Comment by thomasdao** [comment]
@laurentpayot thanks for sharing, great approach! However after I tried this, I found another unrelated blocker that `ReCaptchaV3Provider` doesn't support Electron app, so it's likely that I have to abandon `AppCheck` for the moment.
