### ISSUE TITLE
Uncaught TypeError: can't access property "__FIREBASE_DEFAULTS__", process.env is undefined

### ISSUE THREAD

**Issue by bcspragu** [firebase/firebase-js-sdk#6662]
### Describe your environment

  * Operating System version:  Arch Linux, Kernel 5.19.13
  * Browser version: Firefox Developer Edition 106.0b8
  * Firebase SDK version: 9.11.0
  * Firebase Product: the issue is in `util`

#### Steps to reproduce:
1. Use the Firebase JS client SDK in an environment where `process` is defined, but `process.env` isn't, like Nuxt 3 in the browser.
2. Observe the following error in the console:

```
Uncaught TypeError: can't access property "__FIREBASE_DEFAULTS__", process.env is undefined
```

**Comment by adinvadim** [comment]
Which release has this closed issue? Or is it not released yet?

**Comment by bcspragu** [comment]
Poking around the repo, it looks like it hasn't been released yet. Seems like some automated process will ship out `1.7.1` of `@firebase/util`, and [this directory](https://github.com/firebase/firebase-js-sdk/tree/master/.changeset) will get emptied out. [The changelog](https://github.com/firebase/firebase-js-sdk/blob/master/packages/util/CHANGELOG.md) will likely also get updated.

**Comment by hsubox76** [comment]
We will release this week, we are aiming for tomorrow to try to get this out quicker (releases are normally on Thursday) but it's not guaranteed.

**Comment by iscekic** [comment]
I just hit this issue after upgrading to `firebase@9.11.0` - downgraded to `9.10.0` for the time being.

**Comment by hsubox76** [comment]
The fix has been released in 9.12.0.

**Comment by kai-oswald** [comment]
Just wanted to let you know this fixed the issue I had in a nuxt3 app. Thank you👍🏼

**Comment by Santoshah** [comment]
This still breaks SSR. `9.12.0`

https://github.com/firebase/firebase-js-sdk/issues/6677#issuecomment-1275470713
