### ISSUE TITLE
Double Push Notifications (v9.11): Getting two notifications on onBackgroundMessage 

### ISSUE THREAD

**Issue by nisar-snsw** [firebase/firebase-js-sdk#6670]
### Describe your environment

  * Operating System version: Mac
  * Browser version: Firefox (105.0.1 (64-bit)), Chrome (104.0.5112.101)
  * Firebase SDK version: v9.11
  * Firebase Product: firebase-js-sdk

### Describe the problem
On sending a test notification message from Firebase Console > Cloud Messaging > Compose notification I get two push notifications. The code just has the onBackgroundMessage handler in the service worker. I'm not sure why two notifications are sent by FCM console.

#### Relevant Code:
This is the `onBackgroundMessage` handler code:
```javascript
// Show notification when the app is in the backgound
onBackgroundMessage(messaging, function ({ notification }) {
  if (notification && notification.title) {
    const notificationTitle = notification.title;
    const notificationOptions = {
      body: notification.body,
    };

    return self.registration?.showNotification(
      notificationTitle,
      notificationOptions
    );
  }
});
```

#### Steps to reproduce:
1. Clone the [repo](https://github.com/nisar-snsw/fcm-push). 
2. Update the firebase config details with your config information in:
    **src/firebase.ts**
```
const vapidKey = "your-vapid-key";

const firebaseConfig = {
    apiKey: "",
    authDomain: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: "",
    measurementId: "",
  };
```
**src/service-worker.ts**
```
const appConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: "",
  vapidKey: "",
};
```

    
3. Build and run
```
npm install
npm run build
serve -s build
```
4. Open the browser and navigate to http://localhost:3000
5. Click on `Get FCM Token` button and provide browser permissions to show notifications.
6. Copy the device token from the console logs of the browser
7.  Using the device token, send a test notification message from Firebase Console > Cloud Messaging > Compose notification.
8. You will receive two notifications.

**Comment by nisar-snsw** [comment]
Any update on this?

**Comment by jbalidiong** [comment]
Hi @nisar-snsw, thank for bringing this to our attention. I tried replicating and I wasn't able to reproduce the same behavior. It tried your repro code and I only received the notification once. What browser are you encountering the issue? Can you time the code block for `showNotification()`, I'm wondering if this is running slow on your machine.

**Comment by nisar-snsw** [comment]
We are seeing this behaviour on these browsers:
**MacOS**
- Chrome (Version 104.0.5112.101 (Official Build) (arm64))
- Edge (Version 105.0.1343.25 (Official build) (arm64))
- Firefox (Version 105.0.3 (64-bit))

**Windows**
- Chrome (Version 106.0.5249.119 (Official Build) (64-bit))

It is not just my machine, I asked a set of my team members and they all received two notifications.

I'll work on the following and get back
>  Can you time the code block for showNotification(), I'm wondering if this is running slow on your machine.

**Comment by nisar-snsw** [comment]
@jbalidiong - 
I sent few push notifications one after the other keeping the application minimised to trigger the onBackgroundMessage handler.

Here are `timings` of `shownotification` `block code`:
showNotification: 0.206787109375 ms
showNotification: 0.464111328125 ms
showNotification: 0.309814453125 ms
showNotification: 0.175048828125 ms
showNotification: 0.333984375 ms
showNotification: 0.3369140625 ms

The code block timed as follows:
```
onBackgroundMessage(messaging, function ({ notification }) {
  if (notification && notification.title) {
    const notificationTitle = notification.title;
    const notificationOptions = {
      body: notification.body,
    };

    console.time("showNotification");
    const voidPromise =  self.registration?.showNotification(
      notificationTitle,
      notificationOptions
    );
    console.timeEnd("showNotification");
    return voidPromise;
  }
}
```

Please let me know if you need any other details?

**Comment by jbalidiong** [comment]
Hi @nisar-snsw, I still can't replicate the same behavior. Let me consult this to one of our engineers so we can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by nisar-snsw** [comment]
@jbalidiong - Any update?

**Comment by jbalidiong** [comment]
Apologies for the delayed response. Upon checking the run time of `showNotification()`, this should not affect how you receive the payload. We're still checking other possible reasons why you're encountering this behavior. I'll provide an update or bring someone here that can provide more context about it.

**Comment by nisar-snsw** [comment]
@jbalidiong - We are almost closer to our feature completion. This is a show stopper for us, can we get this moving please?

**Comment by zwu52** [comment]
Can't seem to reproduce. I am not sure what the culprit is for this behavior. Have you checked if there might be a duplicate sw registered that's intercepting the push events (unsure how that would happen).

**Comment by nisar-snsw** [comment]
@zwu52 -  The [sample code](https://github.com/nisar-snsw/fcm-push) I have is how I have configured the service worker and FCM. Do you know how to check for a duplicate service worker?

**Comment by zwu52** [comment]
you could inspect from the browser debugging tool. It's under application>>service worker

**Comment by Ianmward** [comment]
I reproduced this in my environment and spent some time investigating.
I can confirm that in my environment, the onBackgroundMessage is called only once, but in the Notifications recorder 2 Notifications are displayed.
![2022-11-23_10-27-16](https://user-images.githubusercontent.com/8584759/203443233-3ea55ada-b61c-49e7-bfaf-0c9dd802d0c8.png)

**Comment by zwu52** [comment]
I think I found the culprit [here](https://github.com/firebase/firebase-js-sdk/blob/091e8676f55f2b757f8d18ed2197b0edd5f66386/packages/messaging/src/listeners/sw-listeners.ts#L88). The SDK has this functionality: when a message has a notification payload, SDK automatically displays the notification with the information encoded in `message.notification`.  So when calling `showNotification` in `onBackgroundMessage`, one ends up seeing 2 displayed. 

I can think of two fixes:
1. delete the line in the SDK that calls `showNotification` and have everyone calls `showNotification` in `onBackgroundMessage`. Pro: we can have a consistent documentation that tells everyone to always implement `onBackgroundMessage` and calls `showNotification`. Con:The issue is that this breaks the use cases for people who doesn't import and implement `onBackgroundMessage`. 
2. Modify the documentation and states: if you have notification payload, don't call `showNotification`  in `onBackgroundMessage` and just let SDK handles the display. Pro: non-breaking. Con: adds complexity to the documentation. 

I am inclining going with 2. Any concerns or comments please let me know.

For now, I think folks who are sending with notification payload, either don't call `showNotification` or put the data in the `data` payload if you wish to customize your display notification.

**Comment by nisar-snsw** [comment]
@zwu52 - Thank you so much, I'll work on the second suggestion and provide my feedback shortly.

**Comment by nisar-snsw** [comment]
@zwu52 - I tested the second suggestion by commenting the below method and it works and only one notifications shows up now:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/111418911/203916641-1976a986-6178-4764-ac5d-582fd180ce28.png">

However, I'm  wondering how can I show an **icon** if I do not call the `showNotification` method:
```
// Show notification when the app is in the background
onBackgroundMessage(messaging, function ({ notification }) {
  if (notification && notification.title) {
    const notificationTitle = notification.title;
    const notificationOptions = {
      body: notification.body,
      icon: logo,
    } as NotificationOptions;

    self.registration?.showNotification(notificationTitle, notificationOptions);
  }
});
```
Is that something that can be sent from the backend?

**Comment by nisar-snsw** [comment]
@zwu52  - Did you get a chance to look at my last comment?

**Comment by zwu52** [comment]
Apologies on the delay.

In the legacy HTTP send, you could specify icon in the send request https://firebase.google.com/docs/cloud-messaging/http-server-ref. But looks like V1 send doesn't support `icon` ATM https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages. Please file a feature request here on github to Firebase so we have an record.

For now, I think if you are interested in having icon, you can work around by not sending a `notification` payload so the SDK doesn't automatically show a notification; instead, you can put your downstream payload in the `data` payload and parse it in your app and call showNotification in the onBackgroundMessage callback

**Comment by nisar-snsw** [comment]
@zwu52 - Thank you, do you have some sample code on this:
> For now, I think if you are interested in having icon, you can work around by not sending a notification payload to the SDK so that it doesn't automatically show a notification; instead, you can put your downstream payload in the data payload and parse it in your app and call showNotification in the onBackgroundMessage callback

**Comment by dassoukhi** [comment]
Hello, please have you found a solution to this problem, I want to use the click_action and it's also impossible without showNotification, otherwise I have duplicate notifications

**Comment by joselel** [comment]
Tenia este problema y buscando logre resolverlo asi

1. Estaba enviando objetos de 'notificación' y 'datos' en mi carga útil.
2. Eliminar 'notificación' y dejar solo 'datos' resolvió el problema.

estuve investigando y para llegar a esa respuesta la encontre en stackoverFlow al igual que en la documentacion:
adjunto los links:

https://stackoverflow.com/questions/66697332/firebase-web-push-notifications-is-triggered-twice-when-using-onbackgroundmessag

https://firebase.google.com/docs/cloud-messaging/concept-options?hl=es-419#notifications_and_data_messages

**Comment by nisar-snsw** [comment]
@dassoukhi - The problem was solved using the data object instead of notification in the payload:

**Backend**
```
public async sendNotification(
    notificationId: string,
    body = 'Message from Agent'
  ): Promise<void> {
    const message = {
      token: notificationId,
      data: {
        title: 'Notifciation title',
        body,
      },
    } as Message;

    const messaging = getMessaging();
    await messaging.send(message);
  }
```

**Front-end**

```
// Show notification when the app is in the backgound
onBackgroundMessage(messaging, function ({ data }) {
  if (data && data.title) {
    const notificationTitle = data.title;
    const notificationOptions = {
      body: data.body,
    };

    self.registration?.showNotification(notificationTitle, notificationOptions);
  }
})
```

**Comment by nisar-snsw** [comment]
@zwu52 - I'm closing this issue. Thank you for your assistance.
