### ISSUE TITLE
Windows 11 - Authentication hangs

### ISSUE THREAD

**Issue by neetcode-gh** [firebase/firebase-js-sdk#6689]
### Describe your environment

  * Operating System version: Windows 11
  * Browser version: All major browsers
  * Firebase SDK version: 9.8.4
  * Firebase Product: auth

### Describe the problem
Multiple users of mine have had an issue signing in with Firebase auth providers, all of them recently upgraded to Windows 11. When they attempt to sign in, a popup opens but instead of redirecting them to the Auth provider it just hangs at my domain (`https://my-domain/__/auth/handler?apiKey=...`)

#### Steps to reproduce:
The error message in the user's console:
```
FirebaseError: Firebase: This operation has been cancelled due to a conflicting popup being opened. 
(auth/cancelled-popup-request).
```

Interestingly, I asked the user to try signing in to another site which I know also uses firebase Auth, and they had the same issue. I suspect there's some strange interaction going on between windows 11 and firebase.

#### Relevant Code:
I am using [angular fire](https://github.com/angular/angularfire) which is a wrapper around the firebase sdk (version: `"@angular/fire": "^7.4.1", "firebase": "^9.8.4",`).

```javascript
import { AngularFireAuth } from '@angular/fire/compat/auth';
import firebase from 'firebase/compat/app';

...

constructor(private auth: AngularFireAuth) {}

loginGoogle(): Promise<void> {
    return this.loginWithProvider(new firebase.auth.GoogleAuthProvider());
}

loginWithProvider(provider: firebase.auth.AuthProvider): Promise<void> {
  return this.auth.signInWithPopup(provider);
}
```

I also tried logging in with redirect instead of popup, but the issue persisted
```javascript
loginWithProvider(provider: firebase.auth.AuthProvider): Promise<void> {
    return this.auth.signInWithRedirect(provider);
  }
```

**Comment by renkelvin** [comment]
Hi @neetcode-gh , thanks for reporting this. Do you receive any error message when "tried logging in with redirect instead of popup"?

**Comment by neetcode-gh** [comment]
> Hi @neetcode-gh , thanks for reporting this. Do you receive any error message when "tried logging in with redirect instead of popup"?

Sorry about the delay, I'll add the error messages as soon as I get it from the user.

**Comment by neetcode-gh** [comment]
> Hi @neetcode-gh , thanks for reporting this. Do you receive any error message when "tried logging in with redirect instead of popup"?

Using `signInWithRedirect` just redirects to the auth handler url (`https://my-domain/__/auth/handler?apiKey=...`) and there aren't any errors in the console.

I'm not sure what could be causing this, it happens on any browser for users on Windows 11. There doesn't seem to be an adblocker or pop up blocker affecting anything. And users have the same issue on other sites also using firebase auth.

**Comment by rosalyntan** [comment]
Hi @neetcode-gh, thank you for the additional info! A follow-up question: is this issue affecting all of your users on Windows 11, or just a subset of them?
