### ISSUE TITLE
using query() function to build queries in seperate variable doesn't work

### ISSUE THREAD

**Issue by newtonharry** [firebase/firebase-js-sdk#6715]
### Describe your environment

  * Operating System version: Ubuntu Linux
  * Browser version: Firefox 105.0.3
  * Firebase SDK version: 9
  * Firebase Product: firestore (auth, database, storage, etc)

### Describe the problem

When building a query to retrieve documents, initializing the query to a variable and then using the variable in a getDoc or getDocs function returns nothing. When the query is built inside of the getDoc or getDocs function it then starts working.

#### Steps to reproduce:
Just initialize the Firebase app and Frestore as usual and create a variable to hold the query builder. Use that query in either a getDoc or getDocs function. 

#### Relevant Code:

Here is an example function which I  myself had in my code.

This code did not work for me and the userDoc variable returned nothing after executing the getDocs function.

```javascript

export async function getUserWithUsername(username: string) {
   const q = query(
        collection(firestore, "users"),
        where("username", "==", username),
        limit(1)
      );
  const userDoc = (
    await getDocs(q)
  ).docs[0];
  return userDoc;
}

```

This implementation returns data
```javascript
export async function getUserWithUsername(username: string) {
  const userDoc = (
    await getDocs(
      query(
        collection(firestore, "users"),
        where("username", "==", username),
        limit(1)
      )
    )
  ).docs[0];
  return userDoc;
}

```

**Comment by dconeybe** [comment]
I tried to reproduce the behavior you described but I was not able to. Namely, running both queries returned the expected documents (none of them returned an empty result set).

I created a test app: https://github.com/dconeybe/JsIssue6715TestApp. Could you take a look and see if you can reproduce your issue with it?

**Comment by newtonharry** [comment]
Looks like its no longer an issue for me. There might've been some other issue with my code which I'm still not sure how it occurred. It could have perhaps been due to some undefined behavior in JavaScript as the issue was immediately fixed for me given the solution I arrived at. Apologies for wasting your time.

**Comment by dconeybe** [comment]
Glad your issue is resolved!
