### ISSUE TITLE
After signout , this message appear

### ISSUE THREAD

**Issue by thanhtutzaw** [firebase/firebase-js-sdk#6717]
### [REQUIRED] Describe your environment

  * Operating System version: Window 10
  * Firebase SDK version: v9.8
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
`Uncaught Error in snapshot listener: FirebaseError: Missing or insufficient permissions.`
When logout this message appear . Logout means nevigate to login page . Error message is just in console. Not big problem but I want to understand more ...  When I delete onsanapshot  the error not displayed also no data displayed.  
#### Steps to reproduce:
React Todo app with Firebase auth and Firestore

#### Relevant Code:

```javascript
`useEffect(() => {
    let unsubscribe
      onAuthStateChanged(auth, (user) => {
        if (user) {
          const q2 = query(
            collection(db, "users/" + user.uid + "/todos"),
            orderBy("timeStamp", "desc")
          );
          unsubscribe = onSnapshot(q2, (snapshot) => {
            settodos(
              snapshot.docs.map((doc) => ({
                id: doc.id,
                ...doc.data(),
              }))
            );
          });
        }
        else{
          settodos([])
        }
      })
    // }
    return unsubscribe;
  }, []);`
```

**Comment by dconeybe** [comment]
Please check your security rules. It sounds like they are written to only allow access from authenticated users. If you want to allow access to unauthenticated users you may need to relax your security rules. See https://stackoverflow.com/questions/46590155/firestore-permission-denied-missing-or-insufficient-permissions for an example.

**Comment by thanhtutzaw** [comment]
Anything wrong with my rules ? I want to give access their own data only .
`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId}/todos/{documents=**} {
      allow read,create,update, delete: if request.auth != null;
    }
  }
}`

**Comment by thanhtutzaw** [comment]
Solved : I called unsub again  in
`if (user) {
      }
      else {
        unsubscribe()
      }
    })
    return () => unsubscribe;`
