### ISSUE TITLE
Typescript Error: TS1005

### ISSUE THREAD

**Issue by Hamad-98** [firebase/firebase-js-sdk#6731]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs 12.6
  * Browser version: Version 106.0.5249.120 (Official Build) (64-bit)
  * Firebase SDK version: 9.12 ( I just upgraded to this version)
  * Firebase Product: All

### [REQUIRED] Describe the problem
-Trying to use Firebase SDK in staging app, but it keeps giving me a TS Issue (please see screenshot attached)
-I am using Typescript version: 3.9.7 ( have to stay on this version or else build will faill)
![unknown](https://user-images.githubusercontent.com/82972172/198375160-e63ca20f-956c-4e11-86ba-9e90cab5883a.png)

**Comment by dwyfrequency** [comment]
You'll need to update your `tsconfig.json` to something like the below. This is just an example so research what best fits your situation.   

```
{
  "compilerOptions": {
      // ... other TS settings
    "skipLibCheck": true,
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```
