### ISSUE TITLE
Sometimes old AppCheck tokens continue to be returned.

### ISSUE THREAD

**Issue by ishowta** [firebase/firebase-js-sdk#6734]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: 9.12.0
  * Firebase Product: appcheck

### [REQUIRED] Describe the problem

If certain conditions are met, even if `getToken` is executed with forceRefresh, `getToken` will only return the same token, and if more than 1 hour, the token's expiration time, elapses, the application will crash due to the token expiration.
It is a small project, but according to sentry it appears to be occurring several times a day.

Debugging the internal code showed that the `exchangeTokenPromise` doesn't cleared and kept returning the `exchangeTokenPromise` return value.

related pull request: https://github.com/firebase/firebase-js-sdk/pull/6617

Translated with www.DeepL.com/Translator (free version)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by hsubox76** [comment]
Thanks for figuring this out and providing a solution. Let me look into it and see if that's the best solution or if there's a simpler option. Either way we'll try to get a fix out next release.
