### ISSUE TITLE
FR:Expired accessToken through the firebase Auth

### ISSUE THREAD

**Issue by JGSolutions** [firebase/firebase-js-sdk#6737]
* Operating System version: Doesn't matter
  * Browser version: Chrome 107
  * Firebase SDK version: Latest
  * Firebase Product: auth

Problem:

In my app I would like to use some google fitness api which requires an access token. When I login in to my app using firebase auth Google Provider I get the accessToken. But after an hour it expires and even if i refresh the with user currently logged in i do not get an updated token.

Can this feature be implemented? Or is there a way to get an updated fresh token?

**Comment by klevindoda** [comment]
+1 This is a really important feature for Microsoft access token too since it is used to access the Graph API.

**Comment by JGSolutions** [comment]
Any progress on this?

**Comment by prameshj** [comment]
Hi @JGSolutions , are you referring to https://firebase.google.com/docs/reference/js/auth.user.md#usergetidtoken? Does using this method with forceRefresh: true, not return a valid, refreshed idToken?

**Comment by DellaBitta** [comment]
Hi @JGSolutions, checking in to see if you've been able to test setting forceRefesh to true.

Thanks!

**Comment by JGSolutions** [comment]
Unfortunately i haven't been working on this project that needs it. Maybe in the future. You could close this ticket but will save this link which I am sure will be needed in the future :)

**Comment by Xiaoshouzi-gh** [comment]
Feel free to contact us again.  Resolving this for now.
