### ISSUE TITLE
not catching error from addDoc (firestore)

### ISSUE THREAD

**Issue by ISLEMNEDDAR** [firebase/firebase-js-sdk#6738]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 13.0
  * Browser version: google chrome latest stable
  * Firebase SDK version: 9.12.1
  * Firebase Product: firestore

the errors from addDoc() are not returned in the catch block

#### Steps to reproduce:
try this code for example : 
try{
            const result = addDoc(collection(FirebaseConfig.db,
                    CollectionsFireStore.notes),
                {...note})
            result.catch(err => {
                console.log(err)
            })
        }catch (err){
            console.log(err)
            throw new FirebaseError('fdf', 'fdsfs')
        }

the result is : 
`[2022-10-30T23:40:41.908Z]  @firebase/firestore: Firestore (9.12.1): FirebaseError: [code=resource-exhausted]: Quota exceeded.@ logger.ts:115 
[2022-10-30T23:40:41.908Z]  @firebase/firestore: Firestore (9.12.1): Using maximum backoff delay to prevent overloading the backend. logger.ts:115 `

i dont understand why i can't get the error in the catch block

**Comment by cherylEnkidu** [comment]
Hi @ISLEMNEDDAR 

You can try adding `await`, so the code would look like:

```javascript
try{
  const result = await addDoc(collection(FirebaseConfig.db, CollectionsFireStore.notes), {...note})
} catch (err) {
  console.log(err)
}
```
