### ISSUE TITLE
currentUser is still null even after firebaseAuth.onAuthStateChanged() is handled

### ISSUE THREAD

**Issue by theahura** [firebase/firebase-js-sdk#6752]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20
  * Browser version: Version 97.0.4692.99 (Official Build) (64-bit)
  * Firebase SDK version: 9.6.8
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Question originally asked on SO: https://stackoverflow.com/questions/74294927/

The correct way to identify when a user is authenticated from a cold start when using the firebase auth package is to use the [onAuthStateChanged](https://firebase.google.com/docs/reference/js/auth.md#onauthstatechanged) function, like so:

```js
firebaseAuth.onAuthStateChanged(firebase.getAuth(), (user) => {
  if (user) {
    // User is signed in.
  } else {
    // No user is signed in.
  }
});
```

firebase also provides [getAuth](https://firebase.google.com/docs/reference/js/auth.md#getauth) as a way to get the current auth state.

It seems like even after `onAuthStateChanged` is registered and handled, firebase.getAuth() does not reflect the new state. For example:

```js
let globalAuthHandler;
const isAuthed = () => return new Promise((resolve, reject) => {
  globalAuthHandler = resolve;
})

firebaseAuth.onAuthStateChanged(firebase.getAuth(), (user) => {
  if (user) {
     globalAuthHandler()
  }
});

(() => {
  await isAuthed();
  // returns null, even though this could only occur once the state is logged in
  console.log(firebaseAuth.getAuth().currentUser) 
})()
```

I'm aware that onAuthStateChanged and getAuth operate differently, but this seems like enough of a break in user expectation that it feels like a bug, even if its WAI.

**Comment by hsubox76** [comment]
I'll let the auth team handle this but to save some confusion, I changed the issue title to clarify for them that `currentUser` is the property you are having trouble with.

**Comment by sam-gc** [comment]
Hi @theahura,

There is a bug in your snippet -- 

> ```js
> const isAuthed = () => return new Promise((resolve, reject) => {
>  globalAuthHandler = resolve;
> })
> ```

`isAuthed` here is defined as an inline function so it should not use the return syntax.

I've reworked your snippet to make it compile, and it works as expected:
```js
let globalAuthHandler;
const isAuthed = () => new Promise((resolve, reject) => {
  globalAuthHandler = resolve;
})

firebaseAuth.onAuthStateChanged(firebaseAuth.getAuth(), (user) => {
  if (user) {
     globalAuthHandler()
  }
});

(async () => {
  await isAuthed();
  // This only prints if there is a current user logged in
  console.log(firebaseAuth.getAuth().currentUser) 
})()
```

If the question is specifically about why `getAuth().currentUser` isn't immediately available, it's because the auth library can be used for things like sign in before all of the state is settled from storage. In general you _should not_ rely on the `currentUser` property and instead use the state listeners.

**Comment by theahura** [comment]
The bug was a fatfinger, but I appreciate the fix. 

I rewrote a more complete version of the snippet above:
```js
const app = firebase.initializeApp({...});

export const signIn = async (email, password) => {
  try {
    console.log('Signing in');
    const userCredential = await firebaseAuth.signInWithEmailAndPassword(
      firebaseAuth.getAuth(),
      email,
      password,
    );
    return userCredential;
  } catch (error) {
    console.log('error');
  }
};

let globalAuthHandler;
const isAuthed = new Promise((resolve, reject) => {
  globalAuthHandler = resolve;
});

firebaseAuth.onAuthStateChanged(firebaseAuth.getAuth(app), (user) => {
  if (user) {
    globalAuthHandler();
  }
});

(async () => {
  await signIn('user', 'pass');
  isAuthed.then(() => {
    console.log(firebaseAuth.getAuth().currentUser);
  });
})();
```

and it looks like this does work as expected. I guess something else must be going on in my actual application code :thinking: thanks for the quick response, apologies for the incorrect bug report

**Comment by sam-gc** [comment]
No worries, thanks for following up! Feel free to reopen if you start seeing an issue again
