### ISSUE TITLE
Getting firestore connection timeout error for small number of users

### ISSUE THREAD

**Issue by surafelbm** [firebase/firebase-js-sdk#6753]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs Monterey
  * Browser version: Chrome 107.0.5304.87
  * Firebase SDK version: ^9.12.0
  * Firebase Product: auth, firestore

### [REQUIRED] Describe the problem
Getting firebase connection timeout error every now and then 

```
@firebase/firestore: Firestore (9.12.0): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend."
```

we are using `"react-fullstory": "^1.4.0"` to track user activities and user error and we are seeing this error happen to about 1-2 % of users trying to access our page, the error was previously happening for about 5-6% of our users and we were using an older version of firebase sdk 7 and we upgraded that to version 9 the number went down but we are still getting the error for a small number of users.

The app starts working normally if you reload the page once you get the error but that's inconvenient for our users.

Looked at similar issues here and tried different suggestions like setting `experimentalForceLongPolling` to `true` but still same result.

**Comment by milaGGL** [comment]
Hi @surafelbm, thank you for reporting this issue. I will be looking into this.  In the mean time, could you please provide steps to reproduce the problem and [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), so that we can quickly reproduce the issue in same environment your code is executing in and start investigating?

**Comment by surafelbm** [comment]
@milaGGL , yeah but that's the thing tho I am not able to reproduce it on my local machine the only time I am able to reproduce it is if I purposely throttle down my browser speed, and this is also only happening like 2-3 times out of 90-100 users and we are pretty sure they have a stable connection because all of the fulltstory logging are coming in and the second they do a refresh it starts working, i can still post the code for how we are making the request?

**Comment by milaGGL** [comment]
Totally, when the error is happening on only part of the users, it would be quite hard to reproduce. And purposely slowing the connection speed might produce the same error for a different reason. 

Would it be possible to enable logging with [firebase.firestore.setLogLevel('debug') ](https://firebase.google.com/docs/reference/js/firestore_#setloglevel ), and have one of your users capture the log output from the console? You can paste it here (redacting any sensitive information) or email it to me at [milamamat@google.com](mailto:milamamat@google.com).

As you have mentioned tracking user error, would it be possible to track the error patterns? Is it happening to the same users repeatedly, or the issue is bothering different users from time to time?

**Comment by surafelbm** [comment]
> Totally, when the error is happening to only part of the users, it would be quite hard to reproduce. And purposely slowing the connection speed might produce the same error for a different reason.
> 
> Would it be possible to enable logging with [firebase.firestore.setLogLevel('debug') ](https://firebase.google.com/docs/reference/js/firestore_#setloglevel), and have one of your users capture the log output from the console? You can paste it here (redacting any sensitive information) or email it to me at [milamamat@google.com](mailto:milamamat@google.com).
> 
> As you have mentioned tracking user error, would it be possible to track the error patterns? Is it happening to the same users repeatedly, or the issue is bothering different users from time to time?

There is no pattern currently, its happening randomly, but I will try getting debug logs from our users and report back here in a day or two, thanks.

**Comment by danieljpalmer** [comment]
@milaGGL

I am also having this exact issue. It is very randomly affecting users - haven't been able to identify a pattern, except for the fact that it appears to only be happening in Google Chrome. The same users are fine in Mozilla Firefox.

**Comment by milaGGL** [comment]
Hi @danieljpalmer, have you tried out the [experimentalForceLongPolling](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Settings#optional-experimentalforcelongpolling) and/or [experimentalAutoDetectLongPolling](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Settings#optional-experimentalautodetectlongpolling). This should be able to help the users with proxy related connection issue.

If it didn't work, could you please enable logging with [firebase.firestore.setLogLevel('debug') ](https://firebase.google.com/docs/reference/js/firestore_#setloglevel), and get the log output from a user? This would be super helpful to reproduce the error and debug on our end.

**Comment by surafelbm** [comment]
@milaGGL, how can we view the logs when the app is deployed to production? I have enabled this option `firebase.firestore.setLogLevel('debug')` and I can see the firebase logs on the browser console locally but I don't see the logs when the app is deployed to production, which is where we need it to catch the logs in production.

**Comment by milaGGL** [comment]
@surafelbm, since it is hard to reproduce the problem in production app by yourselves, you would need to work with a user who is experiencing it, walk them through opening the web console and copying&pasting the debug log into an email or a file for you.
