### ISSUE TITLE
Auth not being persisted  for Firebase V8

### ISSUE THREAD

**Issue by sahenrai** [firebase/firebase-js-sdk#6768]
### [REQUIRED] Describe your environment

  * Operating System version: ___MacOS Monterey 12.2.1
  * Firebase SDK version: __8.x.x___
  * Firebase Product: __Auth___ (auth, database, storage, etc)
  * React Native: 69.4
  * Expo: 46.0.8

### [REQUIRED] Describe the problem

Out of nowhere, the firebase web auth library on version 8 is no longer persisting sign in, despite working for months before. 

React Native: 69.4

Firebase Web Library 8: Multiple versions tested

Expo: 46.0.8

Does anyone else have experience with this, thank you!

Tried many versions of the library, updating to version 9, and trying different simulators.

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem

//In first page

componentDidMount(){

  console.log(auth.currentUser)
  firebase.auth().onAuthStateChanged((user) => {
    if (user) {
      Actions.moodtags();
      var uid = user.uid;
      // ...
    } else {
      // User is signed out
      // ...actions

    }
  });



}


//In firebase initialization code
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);

```

**Comment by jbalidiong** [comment]
Hi @sahenrai, thank for reaching out. I noticed that you're still using the v8. Would you mind trying to update the SDK version that you're using and see if the issue persists? Just FYI, going forward, any fixes will be in version 9+. Also, you can use Async Storage with the modular SDK and use the [getReactNativePersistence()](https://firebase.google.com/docs/reference/js/auth.md#getreactnativepersistence) function.
