### ISSUE TITLE
FR: Analytics consent mode: set ad_storage and analytics_storage 

### ISSUE THREAD

**Issue by coleridge72** [firebase/firebase-js-sdk#6770]
It seems there is no way currently to set ga4 properties `ad_storage` and `analytics_storage` within the SDK.

Specifically I'm looking for a way to keep minimal analytics enabled but disable all cookies. 

Angularfire discussion: https://github.com/angular/angularfire/issues/2866
SO: https://stackoverflow.com/questions/71453414/how-to-configure-firebase-for-consent-and-data-compliance-on-web
Consent mode docs: https://support.google.com/analytics/answer/9976101?hl=en

**Comment by hsubox76** [comment]
Does `setConsent()` not work? https://firebase.google.com/docs/reference/js/analytics.md#setconsent It should allow setting ad_storage, analytics_storage etc.  https://firebase.google.com/docs/reference/js/analytics.consentsettings.md#consentsettings_interface

I'm not sure what the equivalent syntax in AngularFire would be if that's what you're using.
