### ISSUE TITLE
Firestore Composite Index error does not give a link anymore

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-js-sdk#6788]
### [REQUIRED] Describe your environment

  * Operating System version: Pop!_OS 22.04 LTS
  * Browser version: Vivaldi 5.5.2805.42 (Stable channel) stable (64-bit)
  * Firebase SDK version: 9.12.1
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
When an index for a query is missing, usually there will be an error in the console, along with the link to create the missing index.
But now the link is not showing anymore. Only a non-descriptive error message:
`@firebase/firestore: Firestore (9.12.1): Uncaught Error in snapshot listener: {"code":"failed-precondition","name":"FirebaseError"}
rE @ firebase.3fde6770.js:346`

The error is gone after I created the composite index manually.

#### Steps to reproduce:
1. Query data from Firestore using a query that will need a composite index, but don't create the index yet
2. The error above will show.

#### Relevant Code:
No code is needed.

**Comment by dconeybe** [comment]
This was fixed in 9.14.0, which was released just 2 days ago: https://firebase.google.com/support/release-notes/js#version_9140_-_november_10_2022
