### ISSUE TITLE
https://youtu.be/LLVBYqn4vZ0

### ISSUE THREAD

**Issue by Seetheeda** [firebase/firebase-js-sdk#6789]
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jbalidiong** [comment]
Good day, I'm not sure what the issue here is. Could you file a new issue with the details on the template so we can assist you further? Thanks!
