### ISSUE TITLE
Fetching 2 data makes firebase read increased from 16 to 164

### ISSUE THREAD

**Issue by thanhtutzaw** [firebase/firebase-js-sdk#6790]
Posted in here too https://github.com/gladly-team/next-firebase-auth/issues/580#issue-1446747852
I noticed today firestore increased  read from 16 to 164  ( get all (just 2data) from one user ) and (get single data with 
dynamic-route)

using these library

1. [next-firebase-auth](https://github.com/gladly-team/next-firebase-auth) (cookies)
2. nextjs , **SSR** , dynamic Route
3. firebase , firestore , firebase admin

![Screenshot (90)](https://user-images.githubusercontent.com/71011043/201517880-34e4b490-d39f-4b82-ad6d-cba253e45432.png)

**Comment by ehsannas** [comment]
Hi @thanhtutzaw ! Unfortunately we won't be able to dig into implementation of third party packages. If the third party package uncovers an underlying Firestore issue I'd be happy to help investigate using a minimal reproduction application.

**Comment by thanhtutzaw** [comment]
Why my read is still increasing , there is only two data . I think this is side effect of SSR (Server side Rendering)
 
![Screenshot (91)](https://user-images.githubusercontent.com/71011043/201802061-3fd8eaef-0a90-48cd-8c1f-4e2aca26271c.png)
