### ISSUE TITLE
signInWithCustomToken hangs indefinitely

### ISSUE THREAD

**Issue by mikesol** [firebase/firebase-js-sdk#6791]
### [REQUIRED] Describe your environment

  * Operating System version: iOS version 15
  * Browser version: WKWebView on iOS 15
  * Firebase SDK version: 9.14.0
  * Firebase Product: Auth

#### Steps to reproduce:

```javascript
const userCredential = await signInWithCustomToken(auth, token); // this hangs indefinitely on my iOS device when being called from capacitor's webview
```

#### Solution

My quick-fix solution was to downgrade to the SDK v8.10.1, which works fine.

**Comment by prameshj** [comment]
Hi @mikesol, can you post your entire code sample/imports etc? We aren't able to repro this with our demo app in the auth/ folder.

**Comment by mikesol** [comment]
Hi, apologies for the delay. While it happens consistently on my app, I unfortunately don't have time to whittle it down to a small repro as it requires a custom-token flow that's linked to being on either iOS or Android & having access to the native APIs through Capacitor.

What I can say, though, is that the hang is in the network request (as opposed to some sort of infinite loop) and that downgrading works fine.

If someone from the Firebase team has time to download an app and is ok navigating through a production code base, our code base is open source & I can make a branch based off of firebase9 (it'll take me a while to convert everything back), but I'm not sure if this is useful.

**Comment by sam-gc** [comment]
Hi @mikesol, yes if you can point us to the relevant bit of code in your app that will help us debug

**Comment by sam-gc** [comment]
Additionally, can you verify you are importing the Auth methods from `'firebase/auth/react-native'`? That will ensure you're using the right code for your platform.
