### ISSUE TITLE
Flutter web - Failed to obtain exclusive access to the persistence layer when initialised with synchronizeTabs: true

### ISSUE THREAD

**Issue by pldelattre** [firebase/firebase-js-sdk#6792]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs Monterey 12.6.1
  * Browser version: Chrome 107.0.5304.110 and Safari 16.1
  * Firebase SDK version: 9.11
  * Firebase Product: firestore 

### [REQUIRED] Describe the problem

I have built a flutter web app with persistence enabled and synchronizeTabs: true. 
It works when opening the first chrome tab but it fails when loading the app on another tab with the following error in chrome console. 

> @firebase/firestore: Firestore (9.11.0): Error enabling offline persistence. Falling back to persistence disabled: FirebaseError: [code=failed-precondition]: Failed to obtain exclusive access to the persistence layer. To allow shared access, multi-tab synchronization has to be enabled in all tabs. If you are using `experimentalForceOwningTab:true`, make sure that only one tab has persistence enabled at any given time.

#### flutter packages 
```
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
```

#### Flutter code  to reproduce:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
 
  if (kIsWeb) {
    await FirebaseFirestore.instance
        .enablePersistence(const PersistenceSettings(synchronizeTabs: true));
  }

  runApp(const MyApp());
}
```

**Comment by ehsannas** [comment]
Hey @pldelattre , Since web applications using the JS SDK directly are not facing this issue, this is likely an issue in the Flutter layer. I would start by filing an issue in the [FlutterFire](https://github.com/firebase/flutterfire) repo and waiting for their investigation. If there's anything that can be changed/improved in the JS SDK, we'd be happy to help make it happen.

**Comment by pldelattre** [comment]
Hi @ehsannas , I did open a issue on flutterfire here: https://github.com/firebase/flutterfire/issues/9929
Issue was closed because they believe it is a JS SDK related issue.

**Comment by ehsannas** [comment]
The FlutterFire issue has been re-opened. I'll wait for the investigation from the Flutter team. I'd be happy to help if any issue is found in the underlying (firebase-js-sdk) SDK.

**Comment by pldelattre** [comment]
Issue has been fixed in flutterfire repo thanks to the following PR : 
https://github.com/firebase/flutterfire/pull/10024
