### ISSUE TITLE
singInWithCustomToken not working in Firefox with third party cookies disabled

### ISSUE THREAD

**Issue by mwisniewski2000** [firebase/firebase-js-sdk#6801]
### [REQUIRED] Describe your environment

  * Operating System version: macOs Monterey 12.4
  * Browser version: Firefox 107.0 (64-bit)
  * Firebase SDK version: 9.14.0
  * Firebase Product: auth

#### Steps to reproduce:
When user blocks all third party cookies on Firefox browser and tries to login with `signInWithCustomToken`  this error shows: `FirebaseError: Firebase: Error (auth/network-request-failed).`, while when we block third party cookies on chrome everything works perfectly.
Is there some way to make it work, or is it just impossible with third party cookies blocked in firefox?
<img width="516" alt="Screenshot 2022-11-15 at 19 51 16" src="https://user-images.githubusercontent.com/108661625/202186840-69549311-5a41-4603-93d6-151e5bc0da81.png">
<img width="722" alt="Screenshot 2022-11-15 at 19 50 45" src="https://user-images.githubusercontent.com/108661625/202186991-f37d2953-e086-428b-8543-43e78e9b2706.png">
#### Relevant Code:

```javascript
await signInWithCustomToken(auth, token);
```

**Comment by sam-gc** [comment]
This is odd, can you check the network panel to see if Firefox is directly blocking the relevant API call? `signInWithCredential` translates to a straightforward REST call.

**Comment by mwisniewski2000** [comment]
> This is odd, can you check the network panel to see if Firefox is directly blocking the relevant API call? `signInWithCredential` translates to a straightforward REST call.

In Firefox network tab I can't see any request at all.  In chrome with disabled third party cookies I can see this `accounts:signInWithCustomToken` request.

**Comment by prameshj** [comment]
> In Firefox network tab I can't see any request at all. In chrome with disabled third party cookies I can see this accounts:signInWithCustomToken request.

Interesting, that looks like Firefox might be blocking the network request from happening. Any console logs that hint what might be going on?

**Comment by mwisniewski2000** [comment]
> > In Firefox network tab I can't see any request at all. In chrome with disabled third party cookies I can see this accounts:signInWithCustomToken request.
> 
> Interesting, that looks like Firefox might be blocking the network request from happening. Any console logs that hint what might be going on?

Just this error I attached in description :(

**Comment by abilicz** [comment]
Its basically this part of code throwing operation insecure:
` this._heartbeatsCachePromise = this._storage.read().then(result => {
            this._heartbeatsCache = result;
            return result;
        });
    }`
and this promise rejects before making the actual request inside `getHeartbeatsHeader`
I guess Firefox when third party cookies are blocked is preventing reading and writing to IndexedDB?

**Comment by abilicz** [comment]
Ok, I think a root cause of the issue is https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#security. 
So here https://github.com/firebase/firebase-js-sdk/blob/master/packages/util/src/environment.ts#L143
accessing `indexedDB` throws an error which isn't handled
![Screen Shot 2022-11-30 at 9 38 50 PM](https://user-images.githubusercontent.com/35853229/204903202-3c9bc578-c86d-4957-9ee8-6b457b7a37ed.png)

**Comment by mwisniewski2000** [comment]
I'll close this issue, as it is resolved in this pr: https://github.com/firebase/firebase-js-sdk/pull/6841 .
