### ISSUE TITLE
Unit testing storage rules with firestore cross service rules doesn't work

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-js-sdk#6803]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11
  * Browser version: Chrome
  * Firebase SDK version: @firebase/rules-unit-testing@2.0.5
  * Firebase Product: storage, firestore

#### Steps to reproduce:

Create a storage rule that uses firestore via cross-service security rule then write a unit test using the `@firebase/rules-unit-testing` library.

#### Relevant Code:

Reference firestore from storage rules using [cross service rules](https://firebase.blog/posts/2022/09/announcing-cross-service-security-rules). Example:

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /courses/{courseId}/files/{fileName} {
      allow get: if isCourseEditor(courseId);
    }
  }

  function isCourseEditor(courseId) {
    return getCourse(courseId).editors[request.auth.uid].exists;
  }

  function getCourse(courseId) {
    return firestore.get(/databases/(default)/documents/courses/$(courseId)).data;
  }
}
```

Create a unit test with with the help of the `@firebase/rules-unit-testing` library:

```
    await testEnv.withSecurityRulesDisabled(async context => {
      const storage = context.storage();
      const storageRef = storage.ref(
        `courses/course1/files/sample.txt`,
      );
      const firestore = context.firestore();
      const firestoreRef = firestore.doc(`courses/course1`);

      await Promise.all([
        storageRef.put(sample()),
        firestoreRef.set({
          editors: { user1: { exists: true } },
        }),
      ]);
    });

    const ref = testEnv
      .authenticatedContext('user1')
      .storage()
      .ref('courses/course1/files/sample.txt');

    await assertSucceeds(ref.getDownloadURL());
```

That test fails because the firestore document saved by `@firebase/rules-unit-testing` doesn't go into the same repository as the firestore referenced inside storage.rules via `firestore.get()`.

The temporary workaround is to use the deprecated `@firebase/testing` library for saving the firestore document so storage.rules' `firestore.get()` can retrieve it.

**Comment by tom-andersen** [comment]
Thank you for reaching out. I will take a closer look to see if I can reproduce the problem.

> ...the firestore document saved by @firebase/rules-unit-testing doesn't go into the same repository as the firestore referenced inside storage.rules via firestore.get()

What repository does the document go to?

**Comment by johnnyoshika** [comment]
@tom-andersen I'm not sure. How can I check that?

When I use `@firebase/rules-unit-testing`, the firestore document that's created is visible in the Emulator UI (at http://localhost:4000/). which seems to be the same place where firestore.get() looks inside of storage.rules. When using `@firebase/rules-unit-testing` on the other hand, firestore documents created inside `withSecurityRulesDisabled` are not visible in the Emulstor UI (at http://localhost:4000/).

This is the error message I get because the firestore document can't be found.

```
FirebaseError: Firebase Storage: User does not have permission to access 'courses/course1/files/sample.txt'. (storage/unauthorized)
```

**Comment by johnnyoshika** [comment]
This is my test environment setup:

```
let testEnv = await initializeTestEnvironment({
    projectId: 'demo-foo',
    storage: {
      rules: fs.readFileSync('../storage.rules', 'utf8'),
    }
  });
```

I've also tried this:

```
let testEnv = await initializeTestEnvironment({
    projectId: 'demo-foo',
    storage: {
      rules: fs.readFileSync('../storage.rules', 'utf8'),
    },
    firestore: {
      host:'localhost',
      port:8080
    }
  });
```

And also:

```
let testEnv = await initializeTestEnvironment({
    projectId: 'demo-foo',
    storage: {
      rules: fs.readFileSync('../storage.rules', 'utf8'),
    },
    firestore: {
      rules: fs.readFileSync('../firestore.rules', 'utf8'),
      host:'localhost',
      port:8080
    }
  })
```

**Comment by johnnyoshika** [comment]
Just a little more info.

This is the script I'm running:

```
firebase emulators:exec 'npm run test:local' --project demo-foo --only 'firestore,storage'
```

`test:local` is defined as this in my npm scripts:

```
"test:local": "jest --watch --runInBand --rootDir=../",
```

Not sure if this matters, but I'm running this on Windows 11. I'll try this on a Mac a little later.

**Comment by johnnyoshika** [comment]
@tom-andersen Well this is embarrassing. The project ID specified in initializeTestEnvironment didn't match the project ID specified when running the emulator (--project flag for firebase emulators:exec) which was causing the problem. In the examples I showed above they matched, but they didn't in my codebase and that was the problem.

Closing, thanks for your help.

**Comment by tom-andersen** [comment]
Thank you for the update! I was very concerned about us introducing a regression.
