### ISSUE TITLE
Firebase auth Email address verification takes forever to send

### ISSUE THREAD

**Issue by jmw11x** [firebase/firebase-js-sdk#6816]
### [REQUIRED] Describe your environment

  * Operating System version: ___windows mac__
  * Browser version: __ all ___
  * Firebase SDK version: __ any___
  * Firebase Product: ___auth__ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
when you send a verification email it takes forever to send despite successful function execution.

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```
sendVerfication(cred.user);
function sendVerfication(user){
     
    user.sendEmailVerification().then(function(){
           console.log('verification sent')
        }).catch((e) =>{
            alert(e);
        });
}
it executes and runs. Takes up to a half hour to send a single email. Ready to remove firebase on all projects and never come back.

**Comment by jmw11x** [comment]
google bot needs to add need attention unless firebase is willing to lie to customers about the functionality of the products they release.

**Comment by sam-gc** [comment]
Hi @jmw11x, sorry to hear you're seeing long email send times. Have you filed a ticket with [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) yet? Fixing this issue may require more details about your specific project and use case

**Comment by jmw11x** [comment]
yes I did.

**Comment by prameshj** [comment]
Hi Jacob, is it ok to follow up on the support case, where we might have additional details? I am closing this issue, feel free to reopen if needed. Thanks!
