### ISSUE TITLE
[ERROR] firebase signInWithRedirect not working on IOS

### ISSUE THREAD

**Issue by taishi55** [firebase/firebase-js-sdk#6831]
### [REQUIRED] Describe your environment

  * Operating System version: _IOS 16.1.1____
  * Browser version: __Safari___
  * Firebase SDK version: __9.12.1___
  * Firebase Product: ___auth__ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
`Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.`
#### Steps to reproduce:
`await signInWithRedirect(auth, provider);`

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by khanhle292** [comment]
+1 
I am having the same problem with macOS 13.0._ , I couldn't login by chrome and safari

**Comment by si1k** [comment]
+1 Same issue - specific to `signInWithRedirect` using iPhone - same issue occurs both in simulator and physical device. 

Quick workaround that is working for me is swapping to `signInWithPopup`

**Comment by prameshj** [comment]
Is this happening only on iOS versions 16.1 and later? If yes, this is likely related to https://github.com/firebase/firebase-js-sdk/issues/6716

**Comment by taishi55** [comment]
@prameshj it seems the same issue. I will close here. Look #6716 for the future update

**Comment by taishi55** [comment]
The main issue seems `signInWithRedirect ` is using an experimental technology `CSP: require-trusted-types-for`. 
Please look at [CSP: require-trusted-types-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for)
