### ISSUE TITLE
[ERROR] reset the reCAPTCHA is not working

### ISSUE THREAD

**Issue by taishi55** [firebase/firebase-js-sdk#6832]
### [REQUIRED] Describe your environment

  * Operating System version: Chrome
  * Browser version: 1.45.116
  * Firebase SDK version: 9.12
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem

_reset the reCAPTCHA is not working_
`grecaptcha is not defined`

#### Steps to reproduce:

`grecaptcha.reset(window.recaptchaWidgetId);`
#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by taishi55** [comment]
it seems `grecaptcha ` function will be declared globally by reCAPTCHA API not Firebase.  Without resetting, it works fine.

**Comment by prameshj** [comment]
Can you share more info on the rest of your code? Are you trying this with Phone MFA?

**Comment by taishi55** [comment]
@prameshj Yes, I was trying to implement Phone MFA. 

When a user resends a temporary code to their phone number, `grecaptcha.reset(window.recaptchaWidgetId);` should be triggered before they get tested by Recaptcha. However, `grecaptcha` is not a firebase module, and it is not accessible via import. This caused `undefined error`

**Comment by prameshj** [comment]
Are you using an instance of RecaptchaVerifier for this? If yes, can you try "recaptchaVerifier.clear()", where `recaptchaVerifier = new RecaptchaVerifier(id, params, authInstance)`;

This is how the demo app does it - https://github.com/firebase/firebase-js-sdk/blob/d8af08febfd4507a28bcda38d475b8010ef20f92/packages/auth/demo/src/index.js#L475

Defining grecaptcha variable should end up becoming defined once the recaptcha script has loaded.. but I am having some trouble getting that to call reset - https://github.com/firebase/firebase-js-sdk/compare/grecaptcha

Please let me know if the verifier.clear approach works.

**Comment by taishi55** [comment]
thanks!
