### ISSUE TITLE
verifyBeforeUpdateEmail is missing in version 9

### ISSUE THREAD

**Issue by stanlaktionov** [firebase/firebase-js-sdk#6843]
* Operating System version: Windows 10
  * Browser version: Version 108.0.5359.71 (Official Build) (64-bit)
  * Firebase SDK version: JavaScript — version 9
  * Firebase Product: auth

I need to implement the following flow of email update:
1. User enters new email
2. Verification email message is sent to new email
3. User redirects back to application
4. Email is updated

Currently there is no `verifyBeforeUpdateEmail` method in v9. What can I use instead?

**Comment by jbalidiong** [comment]
Hi @stanlaktionov, thanks for reaching out. There is a verifyBeforeUpdateEmail as documented in the [reference doc](https://firebase.google.com/docs/reference/js/auth.md#verifybeforeupdateemail) for v9. To help you with the modular version, you can follow this code line:

```
 import { getAuth, verifyBeforeUpdateEmail} from 'firebase/auth';

const actionCodeSettings = {
  url: 'https://www.example.com/?email=user@example.com',
  iOS: {
     bundleId: 'com.example.ios'
  },
  android: {
    packageName: 'com.example.android',
    installApp: true,
    minimumVersion: '12'
  },
  handleCodeInApp: true
};
await verifyBeforeUpdateEmail(user, 'newemail@example.com', actionCodeSettings);
// Obtain code from the user.
await applyActionCode(auth, code);


```

This should let you use the `verifyBeforeUpdateEmail()` method on the SDK v9. If the issue persists, feel free to comment and reopen this issue.
