### ISSUE TITLE
can't use ESM in firebase-messaging-sw.js file

### ISSUE THREAD

**Issue by Angryman18** [firebase/firebase-js-sdk#6844]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 22.10
  * Browser version: Version 107.0.5304.121 (Official Build) (64-bit)
  * Firebase SDK version: 9.2
  * Firebase Product: messaging (auth, database, storage, etc)

### [REQUIRED] Describe the problem
hi In my React app (CRA) i put the firebase-messaging-sw.js in public folder but there im not able use any import staff. altough its now a normal javascript file but i see on firebase documentation they have use import statement and improting config from firebase config which i dont have access in public folder. i see some other methods with importScripts but i dont think thats a convenient way of handling? what is process to use and where to put firebase-messaging-sw.js file? thanks

here is the screenshot from the docs
![Screenshot from 2022-12-02 15-02-41](https://user-images.githubusercontent.com/63530626/205271417-4b83baf2-5566-4436-b3ef-ba0490eb1fb8.png)

#### Steps to reproduce:

  What happened? How can we make the problem occur?
  This could be a description, log/console output, etc.
just create a react app and add firebase config. install firebase package. add firebase-messaging-sw.js in public folder. 

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jbalidiong** [comment]
Hi @Angryman18, thanks for reaching out. Currently, service worker doesn't yet support modularization. To use the v9 of the SDK, please use the compat version when importing the script. With that, I'll be closing the ticket now.  If the issue persists, feel free to comment and reopen this issue.
