### ISSUE TITLE
Firestore Emulator not sending requests in (9.13.0)

### ISSUE THREAD

**Issue by millansingh** [firebase/firebase-js-sdk#6852]
### [REQUIRED] Describe your environment

  * Operating System version: MacOs 12.1
  * Browser version: Google Chrome--Version 107.0.5304.110 (Official Build) (x86_64)
  * Firebase SDK version: 9.13.0
  * Firebase Product: firestore/emulator

#### Steps to reproduce:
I have been working with Firebase on a project for a while now, and until now, I've just interacted directly with the production database. Well, I wanted to set up my environment to use the emulators in local development, and herein lies the problems...

The Auth emulator seems to be working fine (and my functions seem to run fine too), but the firestore emulator setup is just not working. The first issue I encountered was an issue where Firestore just quit entirely if I tried to use it on the server side in Nuxt.js 2 (here's a SO post I made for it if you're curious: https://stackoverflow.com/questions/74652320/firestore-has-already-been-started-and-cannot-be-changed-nuxt-2-firebase-emul). I was able to get around the issue right now by simply limiting the firebase plugin code to running on client only, so that's fine for now (but concerning obv).

The issue I'm dealing with now, however, is that I can't seem to write to the Firestore database from my web app when using the emulator. I get these strange warnings after a little while that say "VM23910:106 [2022-12-05T03:53:29.808Z]  @firebase/firestore: Firestore (9.13.0): Connection WebChannel transport errored:" and nothing shows up in the "requests" tab of the Firestore emulator, indicating that a request isn't even being triggered as far as I can tell. These warnings continually pile up every ~40 secs it seems.

Note that this code works perfectly fine using the full Firebase production database and skipping the emulators.

#### Relevant Code:

```javascript
// firebase.client.js (Nuxt plugin to set up Firebase and make it available to pull into other Service files elsewhere).
const app = initializeApp(firebaseConfig);

const auth = getAuth(app);
const db = getFirestore(app);
export const services = { auth, db };

export default (context) => {
    if (context.env.appEnv === 'dev') {
        console.log('dev', parseInt(context.env.firestorePort))

        connectFirestoreEmulator(db, 'http://localhost', parseInt(context.env.firestorePort));
        connectAuthEmulator(auth, `http://localhost:${context.env.authPort}`);
    }
}
```

```javascript
// A chunk of one of my Service files which is supposed to create a user's profile (note that I've tried both updateDoc and setDoc with the same results. A basic profile object is created on creating a user, so there's really no need to use setDoc.
import { services } from "~/plugins/firebase.client";

const { auth, db } = services;

export const createUserProfile = (uid, userProfile) => {
    const userRef = doc(db, 'users', uid);
    console.log(userRef);
    return updateDoc(userRef, userProfile);
}
```

Firestore log:

```
Dec 04, 2022 8:39:02 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketServer start
INFO: Started WebSocket server on ws://127.0.0.1:9150
API endpoint: http://127.0.0.1:8080
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=127.0.0.1:8080

Dev App Server is now running.

Dec 04, 2022 8:39:03 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel
INFO: Connected to new websocket client
Dec 04, 2022 8:39:03 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel
INFO: Connected to new websocket client
Dec 04, 2022 8:39:10 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Dec 04, 2022 8:39:10 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Dec 04, 2022 8:39:11 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Dec 04, 2022 8:39:24 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler channelClosed
INFO: Websocket client disconnected
Dec 04, 2022 8:39:24 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel
INFO: Connected to new websocket client
Dec 04, 2022 8:39:26 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler channelClosed
INFO: Websocket client disconnected
Dec 04, 2022 8:39:26 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel
INFO: Connected to new websocket client
Dec 04, 2022 8:39:26 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Dec 04, 2022 8:39:26 PM com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreListenHandler onClose
INFO: channel closed

```

**Comment by MarkDuckworth** [comment]
I'm not too familiar with Nuxt, but I'll try to help you diagnose. What version of Node.js are you using in your Nuxt environment? Just a hunch, can you attempt to replace `localhost` with `127.0.0.1` where you connect to the emulator? Finally, do you have any log output from the SDK? You can control logging verbosity with [setLogLevel(...)](https://firebase.google.com/docs/reference/js/firestore_.md#setloglevel).

**Comment by millansingh** [comment]
Thanks @MarkDuckworth. I enabled the extra logging, and this error showed up shortly after attempting a get operation on a Firestore document:

2022-12-07T05:39:03.367Z]  @firebase/firestore: Firestore (9.13.0): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

I changed the localhost to 127.0.0.1 with no changes. When I run the emulators, there are no errors indicated in the terminal. Also, I should note that I get the offline error above when attempting a get operation (and shortly after get the error I included in the OP), but when attempting an update/set, I don't get this error in the console, though I get the one I had posted in the OP.

**Comment by millansingh** [comment]
@MarkDuckworth that seems to have fixed the issues with not being able to connect to the Firestor emulator. I'm still dealing with the issue of not being able to use Firebase on the server in Nuxt, but I'm not sure if that's an issue with Firebase or with Nuxt.
