### ISSUE TITLE
FCM for Tizen Tv Application :An error occurred while retrieving token.  DOMException in Tizen tv

### ISSUE THREAD

**Issue by pratappokala** [firebase/firebase-js-sdk#6861]
We are working on Tizen App for Smart TVs for our customer and would like to integrate FCM, Would like to integrate Firebase cloud messaging feature. I followed all the steps provided by firebase using Javascript. working fine in browser getting token,But in tizen tv, I am unable to get the Token and ended up with the below error.

 [Deprecation] Permission for the Notification API may no longer be requested from a cross-origin iframe. You should consider requesting permission from a top-level frame or opening a new window instead. See https://www.chromestatus.com/feature/6451284559265792 for more details.
SubscribeUsers 
iframe-k6.html:28 Registration successful, scope is: https://otvplayer.nagra.com/internal/playground/fcm-iframe/
 granted
 An error occurred while retrieving token.  DOMException

<img width="1195" alt="FCM-TIZENTV-ERROR" src="https://user-images.githubusercontent.com/110607713/206363451-454970ba-de8f-45fa-a715-51a134ab26fc.png">

**Comment by sureshsu** [comment]
@jbalidiong , kindly let us know if have any input for this .

**Comment by zwu52** [comment]
I am unfamiliar with what Tizen TV. Is your app running in a browser instance? please provide more info and consider sharing a minimal reproducible repo.

**Comment by sureshsu** [comment]
@zwu52 , @jbalidiong , Yes sample app runs in browser instance (Chromium) of TV. The Web Chromium version of TV based on year model can checked here: https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html. We are trying it in 2021 model year (which has Chromium M76)

Sample app , is kept here: https://github.com/sureshsu/fbase/tree/main/fcm-test/public
You can also view directly load it browser: https://sureshsu.github.io/fbase/fcm-test/public/fcm.html

**Comment by pratappokala** [comment]
Hi @google-oss-bot , please find below details
sample app runs in browser instance (Chromium) of Tizen TV. The Web Chromium version of TV based on year model can checked here: https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html. We are trying it in 2021 model year (which has Chromium M76).

Sample app , is kept here: https://github.com/sureshsu/fbase/tree/main/fcm-test/public
If no TV available, it can be run using Tizen studio simulator/emulator.
You can also view directly load it browser: https://sureshsu.github.io/fbase/fcm-test/public/fcm.html

Note:Please conform FCM will work on Tizen tv or Not.

**Comment by zwu52** [comment]
Apologies for getting back late on this, based on the error message and the link provided, it appears that the issue you're encountering is related to requesting permission for the Notification API from a cross-origin iframe. Unfortunately, at the moment, the team is experiencing staffing constraints, and we regret to inform you that we do not have the capacity to debug this particular issue for you.
