### ISSUE TITLE
auth/argument-error when trying to create a EmailAuthProvider.credentialWithLink

### ISSUE THREAD

**Issue by israelidanny** [firebase/firebase-js-sdk#6868]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12.6 Monterey (M1)
  * Browser version: Chrome 
  * Firebase SDK version: 107.0.5304.110 (
  * Firebase Product: auth

Trying to create just a basic credential with link ends up with:
```
Firebase: Error (auth/argument-error).
```

#### Steps to reproduce:
I'm not doing anything special, just running the function.
Doing the same via `sendSignInLinkToEmail` works, but I am trying to then make the second step about linking credentials.
#### Relevant Code:

```javascript
const credential = EmailAuthProvider.credentialWithLink(
        'my@gmail.com',
        window.location.href
      );
```

**Comment by bhparijat** [comment]
Hi, can you please log the value of `window.location.href` and see what the value is.

**Comment by israelidanny** [comment]
I mean, it's 'https://mydomainhere.com/myproperpage' (where mydomain and mypage are the correct addresses). Just verified this, and for what it's worth I ALSO tried to enter a manual URL, and also this very same URL works with `sendSignInLinkToEmail`.

**Comment by bhparijat** [comment]
The firebase docs mention that this can be used for reAuth after the operation `sendSigninWithEmailLink` operation
