### ISSUE TITLE
HeartbeatService throws error ONLY on Safari (IndexedDB issue?)

### ISSUE THREAD

**Issue by OrhanTozan** [firebase/firebase-js-sdk#6871]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 13.0.1
  * Browser version: Safari 16.1
  * Firebase SDK version: 9.15.0 (compat version, not modular)
  * Firebase Product: app

### [REQUIRED] Describe the problem

When starting my Firebase app up in Safari, I get the following error:

It has to do with the HeartBeatService

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/16029639/206680063-801e9f95-a4e7-4b4f-b000-88eb6b4b3941.png">

I went on research and got the following findings:
- The error happens in this function: https://github.com/firebase/firebase-js-sdk/blob/734fdcd91223b54cf1dd932f2d6b6b9d7d6f699b/packages/app/src/heartbeatService.ts#L82
- The error "UnknownError: Error looking up record in object store by key range" is mentioned in the IndexedDB repo, in these two lines:
https://github.com/WebKit/WebKit/blob/eb072c37fe4eb37704d87b163dd4e9318cd83c5d/Source/WebCore/Modules/indexeddb/server/SQLiteIDBBackingStore.cpp#L2177 and 
https://github.com/WebKit/WebKit/blob/eb072c37fe4eb37704d87b163dd4e9318cd83c5d/Source/WebCore/Modules/indexeddb/server/SQLiteIDBBackingStore.cpp#L2337

So my bet: it is an issue with IndexedDB on Safari

**Comment by OrhanTozan** [comment]
@hsubox76 

- There is a firebase-heartbeat-database indexedDB, but it has no rows:  <img width="1407" alt="image" src="https://user-images.githubusercontent.com/16029639/206858865-5cfa9047-35b7-4bbb-b05b-d1aaa5b8ca63.png">
- I can't reproduce the issue when launched in a Safari Private Window. If that's the case, you would think that emptying the caches from a normal Window would fix the issue, but no... Develop -> Empty Caches doesn't resolve the issue.
- I can't reproduce it on https://fir-ui-demo-84a6c.firebaseapp.com
- The site where I am reproducing it, is: [what.how](what.how). Perhaps you can reproduce it there?

**Comment by OrhanTozan** [comment]
I think it might only occur when you have Crisp chat in your web app.

**Comment by mmmulani** [comment]
we have a bunch of reports of this issue.

@hsubox76 it doesn't seem to be a consistent issue though, users have reported that restarting Safari fixes the problem

in that case, it would be nice if firebase caught/exposed the issue somehow to the application? Just so that we can recover from it in a nicer fashion

**Comment by hsubox76** [comment]
Sure, I may be able to add a `catch` to https://github.com/firebase/firebase-js-sdk/blob/a9762691db1114a3453c82005634c12d56bb0880/packages/app/src/heartbeatService.ts#L72

Do you think it would be all right to have it `console.log` the error if it catches it? I do want to make sure it's surfaced and not swallowed, but I don't want to clutter Sentry logs with `console.error` or `console.warn`. Is `console.log` ok? I think `console.debug` is too invisible (the user would have to deliberately turn debug logging on).

**Comment by mmmulani** [comment]
`console.log` is definitely fine, and even `console.error` could be good to be honest, since this could end up being somewhat fatal?

thanks for the fast response btw!
