### ISSUE TITLE
Invalid Error Message during signWithPopup call

### ISSUE THREAD

**Issue by sgnagnarella** [firebase/firebase-js-sdk#6876]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12.6.1
  * Browser version: Chrome 108.0.5359.98
  * Firebase SDK version: 9.1.3
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
When the signWithPop call for Google Login cannot retrieve the config from the server (API key does not have API access), it will show an incorrect error referring to the localhost domain not being allowlisted.

#### Steps to reproduce:
1) Restrict your Web Project API key so it cannot access any API in pantheon: https://pantheon.corp.google.com/apis/credentials?authuser=0&project=
2) Try to initiate a login with Google calling linkWithPopup
3) You can see two errors in the console, one saying that it cannot retrieve configs and it will use defaults. The next error shown (incorrect) says that the localhost domain is not authorized and needs to be added.
#### Relevant Code:

```javascript
import { getAuth, GoogleAuthProvider, signInWithPopup } from "firebase/auth";

const LoginWithGoogle = () => {
  const provider = new GoogleAuthProvider();

  const loginWithGoogle = () => {
    const auth = getAuth();
    signInWithPopup(auth, provider)
      .then((result) => {
        // This gives you a Google Access Token. You can use it to access the Google API.
        //const credential = GoogleAuthProvider.credentialFromResult(result);
        //const token = credential.accessToken;
        // The signed-in user info.
        const user = result.user;
        console.log(user);
        // ...
      })
      .catch((error) => {
        // Handle Errors here.
        const errorCode = error.code;
        const errorMessage = error.message;
        // The email of the user's account used.
        const email = error.customData.email;
        // The AuthCredential type that was used.
        //const credential = GoogleAuthProvider.credentialFromError(error);
        // ...
        console.log(errorCode, errorMessage, email);
      });
  };

  return (
    <button type="button" onClick={loginWithGoogle}>
      Login with Google
    </button>
  );
};

export default LoginWithGoogle;

```
<img width="1356" alt="Screen Shot 2022-12-11 at 5 59 59 PM" src="https://user-images.githubusercontent.com/1821304/206935088-afb92fac-a1a1-4768-b741-499e4407c94e.png">

**Comment by jbalidiong** [comment]
Hi @sgnagnarella, thanks for bringing this to our attention. I was able to replicate the behavior. I've raised this to our Auth team. I'll update this thread if I have any information to share.

**Comment by bhparijat** [comment]
Just to confirm, was localhost allowlisted for the default project being mentioned here?

**Comment by sgnagnarella** [comment]
yes, it was allowed by default. The error went away when I remembered I had been changing the API Key access settings and I rolled it back to "non-restricted".

**Comment by bhparijat** [comment]
Thanks!

**Comment by prameshj** [comment]
The issue here is that the error with the restricted API key is somewhat misleading - instead of logging that the config could not be fetched, it states that "localhost" is an unauthorized domain. The error will persist even if "localhost" is added to the authorized domains list, because the actual error is - 1) iframe tried to fetch authorized domains to do origin validation 2) this failed due to api key restriction 3) iframe logged the warning that origin validation failed (but the reason is incorrect).

**Comment by prameshj** [comment]
We can try to improve this error message in the same bug b/262274759 - since it touches the same code.

**Comment by bhparijat** [comment]
This should be fixed now.
