### ISSUE TITLE
Incorrect help in error message

### ISSUE THREAD

**Issue by sgnagnarella** [firebase/firebase-js-sdk#6877]
### [REQUIRED] Describe your environment

* Operating System version: MacOS 12.6.1
* Browser version: Chrome 108.0.5359.98
* Firebase SDK version: 9.1.3
* Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem
Error message shows the incorrect help to allowlist a domain for OAuth Operations.
The help points to **Firebase console -> Auth section -> Sign in method tab.** however that configuration has been moved to **Firebase console -> Authentication -> Settings -> Authorized Domains**
<img width="1356" alt="Screen Shot 2022-12-11 at 5 59 59 PM" src="https://user-images.githubusercontent.com/1821304/206935395-30f163d5-9db4-4ebf-b8a6-f68e61924d30.png">
<img width="1093" alt="Screen Shot 2022-12-11 at 6 30 35 PM" src="https://user-images.githubusercontent.com/1821304/206935396-656f6f12-f4a4-447c-8b54-7785c8ff9b27.png">

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by prameshj** [comment]
Internal tracking bug - b/262274759

**Comment by bhparijat** [comment]
This issue has been fixed and so will close the bug.
