### ISSUE TITLE
 [cloud_firestore] FR: Source option for onSnapshot()

### ISSUE THREAD

**Issue by michalkubizna** [firebase/firebase-js-sdk#6880]
it's possible to pass "source" to GetOptions in the get() calls to make it retrieve the cache-only updates.

Implement the same feature for the real-time listener.

Use case:
I’d like to create a comment section. A real-time listener doesn’t work with pagination in a dynamic collection like that since the moment comments are deleted or added the start value changes for each listener resulting in an inconsistent state.

A solution is to implement pagination using one-time get calls but that forces me to implement my own caching or state management solution to update the local data on the user’s device when they make changes (e.g add, delete, or like a comment). It’s a shame because Firestore implements its own caching solution and listening to the local cache would update fetched data with the user’s updates automatically.

**Comment by dconeybe** [comment]
@michalkubizna Thank you for this feature request. We have received this request before; therefore, I will close this issue in favor of the canonical issue tracking this feature request: https://github.com/firebase/firebase-js-sdk/issues/3789. To summarize, we agree that this feature adds value and would like to implement it, but it hasn't yet received the necessary priority to be implemented. I'll re-raise it and see how it fits into our 2023 priorities.
