### ISSUE TITLE
Incorrect downloadToken used to access storage item

### ISSUE THREAD

**Issue by steveoh** [firebase/firebase-js-sdk#6882]
### [REQUIRED] Describe your environment

  * Operating System version: mac os 11.6.8
  * Browser version: chrome 108.0.5359.98 
  * Firebase SDK version: 9.15.0
  * Firebase Product: storage

### [REQUIRED] Describe the problem

i'm using an upstream package called reactfire to use this lib with hooks etc for react. I'm trying to debug an issue where the `downloadToken` for an image is not correct when using the [useStorageDownloadURL](https://github.com/FirebaseExtended/reactfire/blob/a359de4627cd5bcfe60d87d52b23465fc412462d/src/storage.tsx#L29-L34) hook. This appears to ultimately call into the firebase-js-sdk and the ref's [getDownloadURL](https://github.com/firebase/firebase-js-sdk/blob/master/packages/storage-compat/src/reference.ts#L221) method. This then calls into another [getDownloadURL](https://github.com/firebase/firebase-js-sdk/blob/master/packages/storage/src/implementation/requests.ts#L234) in storage. Then [downloadURLHelper](https://github.com/firebase/firebase-js-sdk/blob/master/packages/storage/src/implementation/requests.ts#L83) get's involved and finally [downloadUrlFromResourceString](https://github.com/firebase/firebase-js-sdk/blob/37f31c57b62bc6486bc08d9e5c64e2c32d25cb0a/packages/storage/src/implementation/metadata.ts#L156) constructs the url. 

What i'm finding is that getDownloadUrl is not using the correct token. It's like it gets cached or it's not getting set properly. 

As you can see here

<img width="379" alt="image" src="https://user-images.githubusercontent.com/325813/207226665-6815e304-bdd2-41b2-b1d8-566682efe623.png">

The token used from downloadTokens in the request is quite different from what was returned from the server.

#### Steps to reproduce:

1. Upload an image.
1. Request the images url to show it on the web
1. Delete the image
1. Upload a new image to the same storage location 
1. Request the images url to show it on the web
1. Request fails with a 403 since the wrong access token was used

#### Relevant Code:

```javascript
// I can provide code but it's a few levels away from the source...
```

refs #https://github.com/FirebaseExtended/reactfire/issues/565

**Comment by maneesht** [comment]
I tried the following and couldn't reproduce. Am I missing something?
```javascript
    const myRef = ref(storage, 'storage.txt');
    await uploadBytes(myRef, file);
    await getDownloadURL(myRef);
    await deleteObject(myRef);
    await uploadBytes(myRef, file2);
    console.log(await getDownloadURL(myRef));
```

**Comment by steveoh** [comment]
I do not think you are missing anything. Boiled down that's basically what i'm doing.

It's hard for me to understand how this is happening.

**Comment by steveoh** [comment]
Seems to work without the react fire hooks so I'll stick with that.
