### ISSUE TITLE
Document data() in onSnapshot handler returns undefined until clear browser cache

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-js-sdk#6884]
* Operating System version: MacOS 12.6
  * Browser version: Safari 15.5 + Chrome 108
  * Firebase SDK version: 9.13 - 9.15
  * Firebase Product: firestore

#### Steps to reproduce:

I am porting a codebase from Firebase web v8 to v9 and I’m running into a problem with the Firestore `onSnapshot` handler. The snapshot passed to the handler returns `undefined` when calling `.data()` on it, yet the document reference for sure exists in the database.

I discovered that if I clear the browser cache, the correct data is returned from the `[snapshot.data](https://snapshot.data/)()` but, after a page refresh the issue with undefined data returns again.

I have no idea how this is possible or what to try next since there are no errors. I know there is a setting for persistence but I am sure I haven’t enabled it and it is disabled by default. The observation is the same on Chrome and Safari.

I found that if I downgrade to 9.12 everything works again. From 9.13 to 9.15 things are broken for me.

#### Relevant Code:

It's not easy for me to share a reproducible example. The code that handles firestore is part of a (public) mobx-based package, and the problem occurs applying it inside a (private) Next.js v12 application.  I realize this adds a lot of variables, but that's all I have for now. 

The package's (limited) tests all seem to work fine.

Here are the parts that [subscribe the handler](https://github.com/0x80/firestore-mobx/blob/332ae6a9f599f045fcd74f56c0395c3e61709d18/src/document.ts#L458) and [the hander itself](https://github.com/0x80/firestore-mobx/blob/332ae6a9f599f045fcd74f56c0395c3e61709d18/src/document.ts#L297), but this part of the code is very straightforward, so I don't see how that could be causing issues.

**Comment by 0x80** [comment]
My earlier assessment that older versions of Firebase still worked seemed to be incorrect. I am now experiencing the same problem also with older versions of 9.

I have noticed that whenever the snapshot data() returns undefined the `snapshot.metadata.fromCache` is set to `true`...

**Comment by 0x80** [comment]
The problem was located! It turned out to be related to a mechanism we use to ochastrate a maintenance time window. A flag is read from the database and used to toggle the database connection via `enableNetwork()`/`disableNetwork()`.

**Comment by ehsannas** [comment]
Thanks for reporting @0x80.

I also noticed something that is worth pointing out: When upgrading from v8 to v9, there was a subtle change to the way developers should check for existence on snapshots (change from property to a method). Reference: https://firebase.google.com/docs/web/modular-upgrade#exists-update

You'll need to use `snapshot.exists()` rather than `snapshot.exist`. In v9, `snapshot.exist` is always truthy and it returns true even if the snapshot data is undefined. (I see this usage which is incorrect: https://github.com/0x80/firestore-mobx/blob/332ae6a9f599f045fcd74f56c0395c3e61709d18/src/document.ts#L299).

**Comment by 0x80** [comment]
@ehsannas Thanks for pointing that out! I had replace the properties for function calls in my application code but seem to have forgotten about these 😮

**Comment by 0x80** [comment]
@ehsannas hmm that doesn't seem to be my v9 branch though...  https://github.com/0x80/firestore-mobx/blob/0360b6fbdb236f074063f276a0063fc38c03e1a5/src/document.ts#L255

**Comment by 0x80** [comment]
TIL; It is essential to call exists() before data(), because if data is called on a non-existent document from a collection that has database rules attached to it, it can cause a permissions error.

In the meantime, we have also improved the enable/disableNetwork logic to only call disable when the maintenance lock activates, and not interact with that API on a regular page load. So although it worked for us in v8, our logic surrounding this was dodgy. 

I will stop posting now. Everything is working 💯 🙌

**Comment by ehsannas** [comment]
No worries! Happy to hear that.
