### ISSUE TITLE
In 9.15.0, production build leads to "ERROR Error: Uncaught (in promise): Error: Service storage is not available"

### ISSUE THREAD

**Issue by jnizet** [firebase/firebase-js-sdk#6894]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 12.6
  * Browser version: Chrome 108.0.5359.94
  * Firebase SDK version: 9.15.0
  * Firebase Product: storage  (I guess)

### [REQUIRED] Describe the problem

Sorry I haven't tried to create a repro yet.
I have an Angular app using Firebase that builds and runs fine with Firebase 9.14.0. The exact same code with Firebase 9.15.0 still runs fine with a development build (ng serve), but fails immediatealy with a production build (ng serve -c production). The browser console shows the following message:

```
Error: Service storage is not available
    at tr.getImmediate (main.js:1:934936)
    at Gr (main.js:1:254374)
    at main.js:1:308184
    at main.js:1:307599
```

**Comment by hsubox76** [comment]
It seems like a problem where the storage component wasn't loaded correctly, or was loaded in a different namespace than the main app instance. Unfortunately there could be a lot of reasons for this and I can't narrow it down without more information or a repro.

**Comment by jnizet** [comment]
Nevermind. While trying to isolate the issue and reproduce it in another repo, I finally realized that the only difference between the actual project where I had the bug and the repro where I couldn't reproduce it was yarn's lock file. Removing it and regenerating it in my actual project made the bug disappear.

Sorry for the false alarm.
