### ISSUE TITLE
CORS error for accessing to firebase with latest SDK

### ISSUE THREAD

**Issue by TristanWYL** [firebase/firebase-js-sdk#6900]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Monterey 12.4
  * Browser version: Chrome Version 108.0.5359.124 (Official Build) (x86_64)
  * Firebase SDK version: 9.14.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Recently we are trying to use latest firebase SDK. The old sdk (8.7.0) can work normally when calling signInWithCustomToken, but abnormally for new SDK.

To be specific, 
- old sdk version was using the endpoint `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken` which does return access-control-allow-origin: <our domain name>

![Screenshot 2022-12-19 at 6 13 56 PM](https://user-images.githubusercontent.com/27753210/208402134-35bdc625-63f6-4ea7-9e92-3dfc84643632.png)

- the new sdk uses `https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken` which doesn’t return any access control headers.
![Screenshot 2022-12-19 at 6 14 16 PM](https://user-images.githubusercontent.com/27753210/208402211-10931964-cf30-4cdb-8d87-b6e1c9118943.png)

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by TristanWYL** [comment]
Actually, lots of accesses to firebase have the same problems with latest SDK. So it should be the config problems?

![image](https://user-images.githubusercontent.com/27753210/208571691-da856ab5-47f9-47eb-b362-422847df659a.png)

**Comment by jbalidiong** [comment]
Hi @TristanWYL, thanks for reaching out and apologies for the delayed response. I tried replicating the behavior but I wasn't able to experience the same on the latest version. Can you provide a minimal, but complete sample of a project that I can run locally.

**Comment by TristanWYL** [comment]
This issue is caused because we added a X-Authorization in the request header. Remove the X-Authorization and the issue is fixed. So I will close this issue. Thx @jbalidiong

**Comment by biharygergo** [comment]
Hey @TristanWYL, 

I believe I'm running into this same issue. My app is running inside Zoom and I see CORS issues when the SDK tries to connect to identitytoolkit or other Google APIs. Did you manage to solve this issue? Thanks!
