### ISSUE TITLE
signInWithPopUp() firebaseapp.com/__/auth/handler is not render any content (blank screen)

### ISSUE THREAD

**Issue by AlexVFornazieri** [firebase/firebase-js-sdk#6903]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Brave 1.46.144 Chromium: 108.0.5359.128 / Firefox 108.0.1
  * Firebase SDK version: 9.8.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Maybe not is a issue specifically with firebase SDK because it's working normally with emulator

The popup opened by signInWithPopUp() with GoogleAuthProvider in URL "<my_app_id>.firebaseapp.com/__/auth/handler" is not render any content (blank screen), no errors shows up in both console. That's currently happening with all my Firebase projects, including one that I tested a few days ago, it was working, and I didn't do any new deployment.

#### Steps to reproduce:
Create a Firebase App, setup Authentication, and do a signInWithPopUp() using Google like described in docs
https://firebase.google.com/docs/auth/web/google-signin

<img src="https://user-images.githubusercontent.com/13385315/209016121-4a6c114a-f044-4317-8379-8042571d7216.png" width="400" />

**Comment by jbalidiong** [comment]
Hi @AlexVFornazieri, thanks for bringing this to our attention. I tried replicating, but I wasn't able to reproduce the error.
 
If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by AlexVFornazieri** [comment]
Hi @jbalidiong , thanks a lot for help!

I was going make exemple and had a ideia to test it in another computer (a linux one), and works! Sounds a problem with my OS that affects all browsers, they not able to redirect to accounts.google from "/__/auth/handler".

I will try stop some process to find out which one is causing; solving I comment here;
But how not is a problem with SDK I will close that issue.
