### ISSUE TITLE
Testing if queries are the same using queryEqual function doesn't work if the order of where clauses is changed

### ISSUE THREAD

**Issue by thefunkman** [firebase/firebase-js-sdk#6909]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 20.04 LTS on 5.10.16.3-microsoft-standard-WSL2
  * Browser version: Chrome 108.0.5359.125 (Official Build) (64-bit) (cohort: Stable) 
  * Firebase SDK version: 9.15.0
  * Firebase Product: firestore

### Describe the problem
Firebase has a function called queryEqual which tests whether two queries are the same. It returns true if the provided queries point to the same collection and apply the same constraints. However, this function seems to be sensitive to the order of where clauses in the query, which I don't think should be the case, at least in the example below.

#### Steps to reproduce:

```javascript
const citiesRef = collection(db, "cities");
        
// These two queries are equivalent
const q1 = query(citiesRef, where("state", "==", "CA"), where("population", ">", 10000));
const q2 = query(citiesRef, where("population", ">", 10000), where("state", "==", "CA"));

console.log(queryEqual(q1, q2));
```
>console output: false

**Comment by milaGGL** [comment]
Hi @thefunkman, thank you for reporting this. This is an intended behaviour on query equality. 

Firestore SDKs do not consider query(a==1 && b >1) to be the same as query(b >1 && a==1). If compound queries with same fields but different order are considered to be the same, it'd need to add sorting scheme for filters and always apply the sorting before anything else to all queries. The more number of fields it uses and more complex it gets (ie, using in, not in, and other aggregations currently under development),  the more computationally expensive it becomes to determine true equality of queries. 

Thank you again for reporting this, and I wonder what is the use case in this query equality.
