### ISSUE TITLE
Force refresh of IdToken should persist

### ISSUE THREAD

**Issue by abagshaw** [firebase/firebase-js-sdk#691]
Firebase SDK: v4.12.1
Firebase Product: Auth

---

After calling `firebase.auth().currentUser.getIdToken(true)` to retrieve an updated token, I would expect subsequent calls to `firebase.auth().currentUser.getIdToken()` (i.e. without the `true` to force refresh) to return the updated token. Unfortunately it appears that the new refreshed token is not saved and the old one persists. Can this be fixed?

Thanks!

**Comment by wti806** [comment]
@abagshaw I've tested our test app and it works fine for me. Did you check the exp timestamp to see if it's refreshed?

**Comment by tiswrt** [comment]
i'm facing the same issue. sometimes it is new, sometimes it returns the old token

**Comment by bojeil-google** [comment]
This is also not reproducible on my end, either. Please provide an MVCE.
