### ISSUE TITLE
firebase/remote-config doesn't work in mv3 chrome extensions (service worker)

### ISSUE THREAD

**Issue by olso** [firebase/firebase-js-sdk#6911]
### [REQUIRED] Describe your environment

  * Operating System version: unrelated
  * Browser version: unrelated
  * Firebase SDK version: 9.15.0
  * Firebase Product: remote-config

#### Relevant Code:

`window` is not present in service workers

Guards like these prevent usage (check for `window`) in service workers (e.g. new chrome extension mv3 background pages)

https://github.com/firebase/firebase-js-sdk/blob/master/packages/remote-config/src/register.ts#L71

and also usage like

https://github.com/firebase/firebase-js-sdk/blob/f84cacd709456d4d8925343f8d6a737b7db71c61/packages/remote-config/src/client/rest_client.ts#L76

What should be done is to use

https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

https://github.com/firebase/firebase-js-sdk/blob/06dc1364d7560f4c563e1ccc89af9cad4cd91df8/packages/util/src/global.ts

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by dwyfrequency** [comment]
Could you share a minimal repo to reproduce this error?
