### ISSUE TITLE
Improve withFunctionTriggersDisabled error message when Cloud Functions emulator is not running

### ISSUE THREAD

**Issue by taeold** [firebase/firebase-js-sdk#6917]
Transferring https://github.com/firebase/firebase-tools/issues/3686

[REQUIRED] Steps to reproduce
Use withFunctionTriggersDisabled to run something while the Cloud Functions emulator is not running (for example, because you mistakenly started the emulator suite with --only firestore instead of --only firestore,functions).

[REQUIRED] Expected behavior
A specific error message saying that the emulator could not be reached or something like that, .e.g: Ensure the Cloud Functions emulator is running.

[REQUIRED] Actual behavior
A generic and misleading error message saying HTTP Error 400 when disabling functions triggers, are you using firebase-tools 8.13.0 or higher?

**Comment by dwyfrequency** [comment]
Thank you for logging this issue. Would any of you be able to create a minimal repo to replicate this? It would greatly expedite our ability to see your issue and diagnose any potential pitfalls.
