### ISSUE TITLE
Login issues on Safari for Appengine preview URLs

### ISSUE THREAD

**Issue by nwaughachukwuma** [firebase/firebase-js-sdk#6922]
### Describe your environment

- Operating System version: Mac OS 13.0.1 
- Browser version: Safari 16.1
- Firebase SDK version: 9.15.0
- Firebase Product: auth

### Describe the problem

I've seen and followed all the suggestions in #6716 and got manual login with one tap working for the `serving/promoted` App Engine URL but not the Preview URLs, which are seemingly peculiar. Adding a particular Preview URL to Authorized JavaScript Origins on `credentials/oauthclient` on GCP solves the issue, but since we dynamically generate the URLs in pull requests, it's a chore to add each one every time. Also, using wildcards is off the table.

<img width="411" alt="Screenshot 2023-01-03 at 3 42 59 PM" src="https://user-images.githubusercontent.com/20521315/210350810-31024577-9580-4fe3-a0e1-4d170e843ff9.png">

Any idea how to fix this?

**Comment by prameshj** [comment]
Is it possible to use signInWithPopup instead? Or make the origin allowlisting part of a CI step that generates the URLs too?

**Comment by nwaughachukwuma** [comment]
> Is it possible to use signInWithPopup instead?

Safari Blocks popup on cross-origins

> Or make the origin allowlisting part of a CI step that generates the URLs too?

Is there an API for populating Authorized Javascript Origins? Please rephrase so I understand what you mean.

**Comment by prameshj** [comment]
>> Or make the origin allowlisting part of a CI step that generates the URLs too?
> Is there an API for populating Authorized Javascript Origins? Please rephrase so I understand what you mean.

I was thinking of doing this programatically with an API/CLI, but I realize this is not exposed.

I think manual allowlisting is the option here, unfortunately.
