### ISSUE TITLE
(firebase/auth) Error: INTERNAL ASSERTION FAILED: Pending promise was never set

### ISSUE THREAD

**Issue by michalzaq12** [firebase/firebase-js-sdk#6923]
### [REQUIRED] Describe your environment

  * Operating System version: Android / Mac OS X
  * Browser version: numerous
  * Firebase SDK version: v9 (9.9.4)
  * Firebase Product: auth

### [REQUIRED] Describe the problem

An unhandled error is reported when using signInWithPopup with the Google / Apple provider:

```
Error: INTERNAL ASSERTION FAILED: Pending promise was never set
```

**Error sources:**
https://github.com/firebase/firebase-js-sdk/blob/1625f7a95cc3ffb666845db0a8044329be74b5be/packages/auth/src/core/strategies/abstract_popup_redirect_operation.ts#L105

https://github.com/firebase/firebase-js-sdk/blob/1625f7a95cc3ffb666845db0a8044329be74b5be/packages/auth/src/core/strategies/abstract_popup_redirect_operation.ts#L79

---
It seems to be the same issue as from the `firebaseui` package -> [ISSUE](https://github.com/firebase/firebaseui-web/issues/947)

**Comment by prameshj** [comment]
Can you try if this happens with the latest - v9.15?

Pending promise is set part of the popup execute function - https://github.com/firebase/firebase-js-sdk/blob/1625f7a95cc3ffb666845db0a8044329be74b5be/packages/auth/src/core/strategies/abstract_popup_redirect_operation.ts#L72, we await for this execute function in https://github.com/firebase/firebase-js-sdk/blob/1625f7a95cc3ffb666845db0a8044329be74b5be/packages/auth/src/platform_browser/strategies/popup.ts#L216
