### ISSUE TITLE
Problem to throw firestore error when Emulators is down

### ISSUE THREAD

**Issue by molavec** [firebase/firebase-js-sdk#6924]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 12.6 - BuildVersion: 21G115
  * Browser version: Versión 108.0.5359.124 (Build oficial) (x86_64)
  * Firebase SDK version: 9.15.0
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

When trying to force an error, shutting down de emulator, instead throw error the API just print error in console. It doesn't permit execution of proper action in the code to manage error in UI.

#### Steps to reproduce:
1. Stop Emulators
2. Make a call to create a new document.
3. Check catch and console logs. 

![image](https://user-images.githubusercontent.com/12848649/210407130-a00f7384-e1fe-475d-8df9-c4449458aded.png)

#### Relevant Code:

```typescript
const createParameter = async (parameter: ParameterType) => {
  try {
    console.log('Inside createParameter');
    const docRef = await addDoc(collection(db, 'parameters'), parameter);
    console.log('after addDoc');
    console.log("Document written with ID: ", docRef.id);
    parameter.id = docRef.id;
    return parameter;
  } catch (error) {
    console.log('ERROR: DATABASE CONNECTION', error);
    throw error;
  }
}
```

**Comment by cherylEnkidu** [comment]
Hi, 

This is an intend behaviour, since the SDK offers latency compensation so even the request sent when the network is unavailable, it will retry later by itself. 

If you need an exception for connection error, you can choose to use transaction or read/write with "server" option.

**Comment by molavec** [comment]
Thank you, @cherylEnkidu. I thought it could be default behaviour, but I did not find an explicit description in documentation.

> If you need an exception for connection error, you can choose to use transaction or read/write with "server" option.

Where should I choose transaction or add server option? Sorry. I can't find it.

Here about [transactions](https://firebase.google.com/docs/firestore/manage-data/transactions#transaction_failure) tell when a transaction fail, but say nothing about connection.
```
Transaction failure
A transaction can fail for the following reasons:

* The transaction contains read operations after write operations. Read operations must always come before any write operations.
* The transaction read a document that was modified outside of the transaction. In this case, the transaction automatically runs again. The transaction is retried a finite number of times.
* The transaction exceeded the maximum request size of 10 MiB.

Transaction size depends on the sizes of documents and index entries modified by the transaction. For a delete operation, this includes the size of the target document and the sizes of the index entries deleted in response to the operation.

A failed transaction returns an error and does not write anything to the database. You do not need to roll back the transaction; Cloud Firestore does this automatically.
```

Do you have a good pattern to alert users when there is a connection failure? Maybe keep some watch a state over Firestore global instance?

**Comment by cherylEnkidu** [comment]
Hi,

Unfortunately we are not planned to expose the status of internet connection to public. If you want to monitor the condition, you can test the general internet connection on your App
