### ISSUE TITLE
Resource detection for 2nd gen of Cloud Functions is detected as CloudRun resource

### ISSUE THREAD

**Issue by dan-wu-open** [firebase/firebase-js-sdk#6925]
### [REQUIRED] Describe your environment
  * Firebase SDK version: 4.1.1
  * Firebase Product: logger

### [REQUIRED] Describe the problem
Gen-2 functions using the functions logger is not showing up under the "Cloud Function" resource type, but instead the "Cloud Run Revision" resource type

#### Steps to reproduce:
1. Deploy a gen-2 function using the logger from firebase-functions@4.1.1

I found similar issues with the googleapis logging libraries
- https://github.com/googleapis/java-logging/pull/1045
- https://github.com/googleapis/google-cloud-go/issues/6367

Is the firebase logger not using the Node version of [this package](https://github.com/googleapis/nodejs-logging)?

**Comment by hsubox76** [comment]
I think you're looking for https://github.com/firebase/firebase-functions ? Let me know if not and I'll reopen this.
