### ISSUE TITLE
Function statements require a function name (at firebase_firestore.js... )

### ISSUE THREAD

**Issue by qdubois** [firebase/firebase-js-sdk#6926]
### [REQUIRED] Describe your environment

  * Operating System version: OS X 13.1
  * Browser version: Chrome 108.0.5359.124
  * Firebase SDK version: 9.15
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
After upgrading my dependencies and installing them again (using pnpm i). I cannot launch my dev server (using vite)
I get the following error:

error { target: Window, isTrusted: true, message: "SyntaxError: function statement requires a name", filename: "http://localhost:3333/node_modules/.vite/deps/firebase_firestore.js?v=f3721b60", lineno: 13750, colno: 16, error: SyntaxError, srcElement: Window, eventPhase: 0, bubbles: true, … }
localhost:3333:15:17

#### Steps to reproduce:

Create an empty vite project ( pnpm create vite)
add Firebase ( pnpm i firebase )
Add  the following code in the script section of the src/App.vue file
```
import { initializeApp } from 'firebase/app'
import { getFirestore } from 'firebase/firestore'


const FIREBASE_CONFIG = { // UPDATE BY. A REAL firebase config info
  apiKey: "XXX-XXXXX",
  authDomain: "XX.XXX",
  projectId: "XX-XXXX",
  storageBucket: "XXX.XXXX",
  messagingSenderId: "XXX",
  appId: "XXXX",
}

const fb = initializeApp(FIREBASE_CONFIG)
// // Initialize Firebase
const db = getFirestore(fb)

```

Here is the console output: 
error { target: Window, isTrusted: true, message: "SyntaxError: function statement requires a name", filename: "http://localhost:3333/node_modules/.vite/deps/firebase_firestore.js?v=f3721b60", lineno: 13750, colno: 16, error: SyntaxError, srcElement: Window, eventPhase: 0, bubbles: true, … }
localhost:3333:15:17

**Comment by scrodde** [comment]
I got the same issue and fixed it temporarily by excluding firebase in vite's optimizeDeps like this:

```typescript
import { sveltekit } from "@sveltejs/kit/vite";
import pkg from "./package.json";

/** @type {import('vite').UserConfig} */
const config = {
  optimizeDeps: {
    exclude: ["firebase", "firebase/app", "firebase/auth", "firebase/firestore", "firebase/analytics"],
  },
  define: {
    __VERSION: JSON.stringify(pkg.version),
  },
  plugins: [sveltekit()],
};

export default config;
```

Related
- [firebase/firebase-js-sdk/issues/5900](https://github.com/firebase/firebase-js-sdk/issues/5900)
- [vitejs/vite/issues/6546](https://github.com/vitejs/vite/issues/6546)
- [rollup/issues/4105](https://github.com/rollup/rollup/issues/4105)

**Comment by qdubois** [comment]
Thanks a lot !! it's working.

**Comment by JMSafadi** [comment]
> 

It works. Than you!!!

**Comment by TheJeagle** [comment]
sorry but where can you find the file I need to change?
where do I find 
optimizeDeps: {
    exclude: ["firebase", "firebase/app", "firebase/auth", "firebase/firestore", "firebase/analytics"],
},
?

**Comment by adamgajzlerowicz** [comment]
I spent a full day debugging this. I thought it's a problem with my code 😂 


Fix is working. Thank you so much!

> ```ts
>     exclude: ["firebase", "firebase/app", "firebase/auth", "firebase/firestore", "firebase/analytics"],
> ```

**Comment by alexruimy** [comment]
The fix did not work for me. When applied, I now get this error:

```
VM9:1 Error: Service storage is not available
    at Provider.getImmediate (provider.ts:130:15)
    at getStorage (api.ts:331:43)
    at default (firebase.dev.ts:11:28)
    at initialize (index.ts:8:16)
    at auth.ts:9:43
eval @ VM9:1
127.0.0.1/:1 Uncaught (in promise) Error: Service storage is not available
    at Provider.getImmediate (provider.ts:130:15)
    at getStorage (api.ts:331:43)
    at default (firebase.dev.ts:11:28)
    at initialize (index.ts:8:16)
    at auth.ts:9:43
start.js:45 Uncaught (in promise) Error: Service storage is not available
    at Provider.getImmediate (provider.ts:130:15)
    at getStorage (api.ts:331:43)
    at default (firebase.dev.ts:11:28)
    at initialize (index.ts:8:16)
    at auth.ts:9:43
```

**Comment by rlindner81** [comment]
@scrodde Thanks for the workaround.
@qdubois I think this is a bug in vitejs not in the firebase sdk. They marked a similar [issue](https://github.com/vitejs/vite/issues/6546) as resolved, but as of vite 4.0.4 this still happens.

**Comment by rdani95** [comment]
> The fix did not work for me. When applied, I now get this error:
> 
> ```
> VM9:1 Error: Service storage is not available
>     at Provider.getImmediate (provider.ts:130:15)
>     at getStorage (api.ts:331:43)
>     at default (firebase.dev.ts:11:28)
>     at initialize (index.ts:8:16)
>     at auth.ts:9:43
> eval @ VM9:1
> 127.0.0.1/:1 Uncaught (in promise) Error: Service storage is not available
>     at Provider.getImmediate (provider.ts:130:15)
>     at getStorage (api.ts:331:43)
>     at default (firebase.dev.ts:11:28)
>     at initialize (index.ts:8:16)
>     at auth.ts:9:43
> start.js:45 Uncaught (in promise) Error: Service storage is not available
>     at Provider.getImmediate (provider.ts:130:15)
>     at getStorage (api.ts:331:43)
>     at default (firebase.dev.ts:11:28)
>     at initialize (index.ts:8:16)
>     at auth.ts:9:43
> ```

@alexruimy Add `'firebase/storage'` to the exclude array. It should look like this

```
  optimizeDeps: {
    exclude: [
      'firebase',
      'firebase/app',
      'firebase/auth',
      'firebase/firestore',
      'firebase/analytics',
      'firebase/storage'
    ]
  }
```

**Comment by alexruimy** [comment]
> @alexruimy Add `'firebase/storage'` to the exclude array. It should look like this

Thank you, adding `firebase/storage` and `firebase/functions` did resolve the issue.


```
exclude: [
      'firebase',
      'firebase/app',
      'firebase/auth',
      'firebase/firestore',
      'firebase/analytics',
      'firebase/functions',
      'firebase/storage'
    ]
```

**Comment by bczak** [comment]
Still not workinh with this config:
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  build: {
    minify: false,
  },
  optimizeDeps: {
    exclude: [
      'firebase',
      'firebase/app',
      'firebase/auth',
      'firebase/firestore',
      'firebase/analytics',
      'firebase/functions',
      'firebase/storage'
    ]
  }
});

**Comment by alexruimy** [comment]
> Still not workinh with this config:
> 

I found that I also had to add those plugins to `ssr` in `vite.config.js`

```ssr: {
    noExternal: [],
    exclude: [
      'firebase',
      'firebase/app',
      'firebase/auth',
      'firebase/firestore',
      'firebase/analytics',
      'firebase/functions',
      'firebase/storage'
    ]
  },```

**Comment by Najidnadri** [comment]
I still got this error despite the above the solutions
```
provider.ts:130 Uncaught Error: Service firestore is not available
```

Things I tried:
1. delete & re-install package-lock with `node-modules`
2. modify the vite config file as follow : 
```  
optimizeDeps: {
    exclude: ["firebase", "firebase/app", "firebase/auth", "firebase/firestore", "firebase/analytics", "firebase/storage", "firebase/functions"],
  }
```

My dependencies:
```
  "dependencies": {
    "firebase": "^9.15.0",
    "vue": "^3.2.41",
    "vue-router": "^4.1.5",
    "vuex": "^4.0.2"
  },
```

Did I miss anything?

**Comment by bczak** [comment]
found solution. Downgrade vite and vite react plugin to 3.2.5 ad it works

**Comment by seanmartinlewis** [comment]
@qdubois I get this same issue and nothing on this thread resolves my problems.

**Comment by Najidnadri** [comment]
Not sure if its related to Vuejs or any other frameworks, However I got it working by just downgrading my firebase to `^9.13.0` and without using the above modifications. 

 package.json
```
  "dependencies": {
    /* other dependencies */
    "firebase": "^9.13.0",
    "vue": "^3.2.41"
  },
  "devDependencies": {
    /* other dependencies */
    "vite": "^4.0.0"
  }
```

vite.config.js
```
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
});
```

firebase.js
```
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  /*firebase configurations*/
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const analytics = getAnalytics(app);
const db = getFirestore(app);
const storage = getStorage(app);
const auth = getAuth(app);

export {
    db,
    storage,
    auth
}
```

Please also try to reinstall your `package.lock` & `node_modules`

**Comment by MuhammedShahirMS** [comment]
> @qdubois I got the same issue and fixed it temporarily by excluding firebase in vite's optimizeDeps like this:
> 
> ```ts
> import { sveltekit } from "@sveltejs/kit/vite";
> import pkg from "./package.json";
> 
> /** @type {import('vite').UserConfig} */
> const config = {
>   optimizeDeps: {
>     exclude: ["firebase", "firebase/app", "firebase/auth", "firebase/firestore", "firebase/analytics"],
>   },
>   define: {
>     __VERSION: JSON.stringify(pkg.version),
>   },
>   plugins: [sveltekit()],
> };
> 
> export default config;
> ```
> 
> Related
> 
> * [firebase/firebase-js-sdk/issues/5900](https://github.com/firebase/firebase-js-sdk/issues/5900)
> * [vitejs/vite/issues/6546](https://github.com/vitejs/vite/issues/6546)
> * [rollup/issues/4105](https://github.com/rollup/rollup/issues/4105)

Thank you so much.. 
     I had to exclude only "firebase/firestore" as I encounter this problem only when importing firestore methods to my Firebase config file. (The Problem does not happen with getAuth method of Firebase Authorization).

**Comment by MuhammedShahirMS** [comment]
> @qdubois I got the same issue and fixed it temporarily by excluding firebase in vite's optimizeDeps like this:
> 
> ```ts
> import { sveltekit } from "@sveltejs/kit/vite";
> import pkg from "./package.json";
> 
> /** @type {import('vite').UserConfig} */
> const config = {
>   optimizeDeps: {
>     exclude: ["firebase", "firebase/app", "firebase/auth", "firebase/firestore", "firebase/analytics"],
>   },
>   define: {
>     __VERSION: JSON.stringify(pkg.version),
>   },
>   plugins: [sveltekit()],
> };
> 
> export default config;
> ```
> 
> Related
> 
> * [firebase/firebase-js-sdk/issues/5900](https://github.com/firebase/firebase-js-sdk/issues/5900)
> * [vitejs/vite/issues/6546](https://github.com/vitejs/vite/issues/6546)
> * [rollup/issues/4105](https://github.com/rollup/rollup/issues/4105)

Thank you so much..
I had to exclude only "firebase/firestore" as I encounter this problem only when importing firestore methods to my Firebase config file. (The Problem does not seem to happen with Firebase Authorization).

**Comment by MicahBala** [comment]
Thanks, got the same error and the solution on this thread help me out.
