### ISSUE TITLE
Firebase JS SDK 9.15.0 TypeScript typings don't work

### ISSUE THREAD

**Issue by TomasHubelbauer** [firebase/firebase-js-sdk#6928]
I am reporting an issue (not a feature request) related to the code in this repository, not a technical question or general Firebase discussion.

### Environment

  * Operating System version: macOS
  * Browser version: N/A
  * Node version: 19.3.0
  * Firebase SDK version: 9.15.0
  * Firebase Product: initializeApp & FCM

#### Steps to reproduce:

1. Create a Next app using `npx create-next-app` with TypeScript
2. Follow https://firebase.google.com/docs/web/setup to install the Firebase SDK
3. Copy over the snippet including `import { initializeApp } from 'firebase/app';` to a client-side component (`pages` directory)
4. Notice that VS Code reports an error:

> Module '"firebase/app"' has no exported member 'initializeApp'.

When Ctrl-clicking through `firebase/app` I am taken to `node_modules/firebase/app/dist/app/index.d.ts` which has this export:

```js
export * from '@firebase/app';
```

Ctrl-clicking on `@firebase/app` does nothing at this point.

Changing the code to say `import firebase from 'firebase/app';`, and attempting to access `firebase.` to see the inferred type and its members, the TypeScript language service in VS Code provides nothing at all, as if the type was `unknown`.

Compiling the application and running it in development mode, at runtime in the browser, the `import` is resolved correctly and everything works.

I think there is a typing issue which prevents TypeScript from picking up the types for the Firebase SDK.

#### Relevant Code:

```javascript
import { initializeApp } from 'firebase/app';

// TODO: Replace the following with your app's [Firebase project configuration](https://firebase.google.com/docs/web/learn-more#config-object)
const firebaseConfig = {
  //...
};

const app = initializeApp(firebaseConfig);
```

**Comment by hsubox76** [comment]
Hm, I followed the steps you gave (thanks for the detailed steps) but can't seem to reproduce this. Is this the correct place to put the code? (pages/test.tsx)

![Screenshot 2023-01-09 at 9 57 26 AM](https://user-images.githubusercontent.com/10716545/211375570-fc4e8e97-c0bd-4c4c-a362-306352b0ea93.png)

**Comment by TomasHubelbauer** [comment]
Sorry, I did not realize this was the case, but this was a bit more involved. I thought I reduced my actual application repository into a reproduction with those steps, but I made a mistake and now upon another look, I found this had to do with how my application, which uses PNPM and its workspaces feature was set up. I nailed it down to `"preserveSymlinks": true` in my `tsconfig.json`. When I turned that off, the imports started working and they were resolving to the right paths.

**Comment by TomasHubelbauer** [comment]
Reopening as I have finally managed to get a repro case:
https://github.com/TomasHubelbauer/firebase-firebase-js-sdk-6928

**Comment by krieu** [comment]
Hi, 
You may have already solved it, but I had the same issue and I solved it by adding the below settings to my `.npmrc` .
I think it probably has something to do with firebase being a monorepo.

```
public-hoist-pattern[]=@firebase*
```

**Comment by TomasHubelbauer** [comment]
Thanks a lot for the hint! I will try it and report back if it worked in my case.

**Comment by TomasHubelbauer** [comment]
Yep, worked! Thanks again.
