### ISSUE TITLE
Realtime Database get() function does not close the connection

### ISSUE THREAD

**Issue by igalci** [firebase/firebase-js-sdk#6932]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Firefox 108
  * Firebase SDK version: 9
  * Firebase Product: realtime database

### [REQUIRED] Describe the problem

According to the documentation, `If you need the data only once, you can use get() to get a snapshot of the data`.

However, it keeps the WS connection open and those can add up quick towards the `simultaneous connections` limit of my plan.

All I need is to get a user attribute that I don't think should be in the `custom claims`, as its less important.

Maybe Realtime Database is not the right product for my use case? Would Firestore be better?

#### Steps to reproduce:
Implement the get() function as shown in the demo on the official website.

#### Relevant Code:

```javascript
import { getDatabase, ref, child, get } from "firebase/database";

const dbRef = ref(getDatabase());
get(child(dbRef, `users/${userId}`)).then((snapshot) => {
  if (snapshot.exists()) {
    console.log(snapshot.val());
  } else {
    console.log("No data available");
  }
}).catch((error) => {
  console.error(error);
});
```

**Comment by jbalidiong** [comment]
Hi @igalci, thanks for reaching out. I was able to reproduce the behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by igalci** [comment]
I actually switched to the Firestore database and it seems to work fine with a one-time get() function.

**Comment by jbalidiong** [comment]
Apologies for the delayed response @igalci, it is great that Firestore database is currently working for your use case. On the other hand, using `get()` should not behave differently from `once` in this respect. You can try and close the connection before the SDK does that by calling `goOffline` explicitly and then of course call `goOnline` when you need it to be connected again.

I'll be closing this issue now. If the issue persists, feel free to comment and reopen this issue.
