### ISSUE TITLE
Cloud Storage pause in uploadBytesResumable not work with vue.js

### ISSUE THREAD

**Issue by benixal** [firebase/firebase-js-sdk#6935]
* Operating System version: Ubuntu 22.04.1 LTS
  * Browser version: google chrome 108.0.5359.124 (Official Build) (64-bit)
  * Firebase SDK version: 9.15.0
  * Firebase Product: Cloud Storage

### the problem
pause method in uploadBytesResumable not work with vue.js
when use pause
it says : 

> Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)

but with firebase@9.7.0 there is no problem
**Live DEMO** : [https://stackblitz.com/edit/vue-qtohv9](https://stackblitz.com/edit/vue-qtohv9)

**Comment by maneesht** [comment]
I was able to reproduce this. Looking into it.
