### ISSUE TITLE
FR: Support offline persistence for node

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-js-sdk#6945]
For the avoidance of doubt Im referring to [this feature](https://firebase.google.com/docs/firestore/manage-data/enable-offline?authuser=0).

The main reason we need it is to avoid the additional costs due reconnection as described [here](https://firebase.google.com/docs/firestore/pricing?authuser=0#listens)

So would also be happy if was just an in-memory cache to enable the 30 minute reconnect rule whilst app is running.

**Comment by tom-andersen** [comment]
Thank you for the suggestion!

Currently, this SDK relies on IndexedDB for offline persistence. The limitation comes from the fact that unlike major browsers, NodeJS does not have IndexedDB support. We are investigating offering other persistence options.

I will be sure to share your request with the team. Requests from the community help influence priority of future feature development.

**Comment by tom-andersen** [comment]
@nbransby You may want to try [indexeddbshim](https://github.com/indexeddbshim/IndexedDBShim). We use this in our (tests)[https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/test/util/node_persistence.ts].

**Comment by tom-andersen** [comment]
Work around given.
