### ISSUE TITLE
Local debug for app check web fails

### ISSUE THREAD

**Issue by arisAlexis** [firebase/firebase-js-sdk#6946]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 11
  * Browser version: Chrome
  * Firebase SDK version: 11.20.0
  * Firebase Product: app check (auth, database, storage, etc)

#### Steps to reproduce:

Firebebase Web app (made with Flutter) with App Check Enabled running locally with emulators. App is registed on the Console with Recaptcha v3. The debug token is everytime different one using Chrome which in itself very inconvenient because we cannot add the debut token to the console everytime we hit debug. The app check fails. It is specifically written in the documentation that adding localhost to recaptcha should not be done because anybody can access your app through their localhost. Also, shouldn't recaptcha not be required if it's a local debug?

#### Relevant Code:

"AppCheck: Fetch server returned an HTTP error status. HTTP status: 403. ."

**Comment by hsubox76** [comment]
I'm sorry, I'm having a really time following your setup and some of it is very confusing. You shouldn't need recaptcha and you shouldn't be getting a different debug token every time. Can you share the code you're using? Even better would be a minimal repro if possible.

**Comment by arisAlexis** [comment]
Actually the documentation should be updated. self.FIREBASE_APPCHECK_DEBUG_TOKEN = true in index.html gives a different debug token each time. You need to create a fixed one from the console and put it manually but this is written anywhere in the docs.
