### ISSUE TITLE
Missing React Native 0.71.0 AsyncStorage support

### ISSUE THREAD

**Issue by MaximilianCroissant** [firebase/firebase-js-sdk#6947]
Async Storage got removed from react-native in 0.71.0 and @react-native-community/async-storage is deprecated.
Persistence should make use of react-native-async-storage/async-storage.

**Comment by jbalidiong** [comment]
Hi @MaximilianCroissant, thanks for reaching out. This seems to be similar to this one: https://github.com/firebase/firebase-js-sdk/issues/6493. If this is similar to what you want to fix, you have to import the `AsyncStorage` yourself from `@ract-native-async-storage/async-storage` and then pass it to `getReactNativePersistence()`, and then pass that to `initializeAuth()`, per Sam's comment there.

**Comment by MaximilianCroissant** [comment]
Ah, thanks.
Sorry about that, seems like I've overlooked it. 
This will be necessary for all projects using react native 0.71.0, since they removed the previous async storage dependencies completely. There is no more warning or anything (at least from my end), auth persistance is just not working. Maybe helpful for others to know.
