### ISSUE TITLE
@firebase/firestore: Firestore (9.15.0): Connection WebChannel transport errored: nv {type: 'c', target: nm, g: nm, defaultPrevented: false, status: 1}

### ISSUE THREAD

**Issue by incogiscool** [firebase/firebase-js-sdk#6948]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS Monterey (but error persists on website hosted on Netlify -- works fine on localhost)
  * Browser version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/
  * Firebase SDK version: 9.15.0
  * Firebase Product: Firestore

#### Steps to reproduce:
When I try and create a doc on the local host, it works fine, but when I try and create one on a hosted site (using netlify), I get this error in the console: `@firebase/firestore: Firestore (9.15.0): Connection WebChannel transport errored: nv {type: 'c', target: nm, g: nm, defaultPrevented: false, status: 1}`

I've seen that people have tried to solve this error with `experimentalForceLongPolling`, but I couldn't figure out how to input it within the code on the latest version.

#### Relevant Code:

Here is the firebase.ts code
```javascript
// Initialize Firebase
let firebaseApp: FirebaseApp;
try {
  firebaseApp = getApp();
} catch (e) {
  firebaseApp = initializeApp(firebaseConfig);
}

export const auth = getAuth(firebaseApp);
export const googleProvider = new GoogleAuthProvider();
export const database = getFirestore(firebaseApp);
```
Here is setting the doc code:
```javascript
      console.log("setting doc");

      const dbParams: DBFetchType = {
        //@ts-ignore
        uid: auth.currentUser.uid,
        firstName: signUpDetails.firstName,
        lastName: signUpDetails.lastName,
        plan: "free-plan",
        workspaces: ["Workspace 1"],
        charactersUsed: 0,
        favorites: [],
      };

      await setDoc(
        doc(
          database,
          "users",
          //@ts-ignore
          auth.currentUser.uid
        ),
        dbParams
      );

      console.log("set doc");
```

Here is pic of the full log:
<img width="466" alt="Screen Shot 2023-01-16 at 12 14 09 AM" src="https://user-images.githubusercontent.com/94598096/212564648-9e0fbd1a-3c77-462d-b356-c4058b9769c6.png">

Need help with this ASAP

Thanks in advance for any help!

**Comment by tom-andersen** [comment]
To enable Long Polling, use `initializeFirestore`:

```
export const database = initializeFirestore(firebaseApp, {
    experimentalAutoDetectLongPolling: true,
    experimentalForceLongPolling: true
});
```

**Comment by incogiscool** [comment]
This is the error I run into when using `initializeFirestore()`:
![image](https://user-images.githubusercontent.com/94598096/213783239-3a0306e3-9f04-4300-b16b-1725c8353712.png)

**Comment by tom-andersen** [comment]
The `firebaseApp` object keeps track of Firestore instances. Whenever `getFirestore` of `initiliazeFirestore` is called, it will return the previously instantiated Firestore object.

On a given `firebaseApp` object, you should only call `initiliazeFirestore` once. Subsequent calls to `getFirestore` will return the same Firestore object with the same settings as given to `initializeFirestore`.

I suspect you have many calls to `getFirestore`. Maybe you should leave them as they were before. But instead add an `initliazeFirestore` right after you `initializeApp`, such that `initliazeFirestore` is only called once, before any call the `getFirestore`.

**Comment by incogiscool** [comment]
@tom-andersen 
I did some experimenting and I tried to put this instead of just getFirestore() or initializeFirestore():
```javascript
try {
 console.log("initializing database");
 database = initializeFirestore(firebaseApp, { experimentalForceLongPolling: true, });
 console.log("database initialized");
} catch (e) { 
console.log("getting database");
 database = getFirestore(firebaseApp);
 console.log("database got");
}
```
This is sort of working. When I write to the database from the client for the first time, it gives the same error, but If I reload the page it works. Even if I reload the page, leave the site, and come back, it works. It seems that the initial first render doesn't allow it to work.

Any idea why this is happening?

**Comment by Malik-Usman17** [comment]
I tried this code and right now somehow it worked.

`const app = initializeApp(firebaseConfig);

const db = getFirestore(app);  (instead of this line, I tried the below line of code.)

const db = initializeFirestore(app, {
  experimentalForceLongPolling: true
})
`

**Comment by incogiscool** [comment]
Turns out it was a redirect issue where Nextjs would use states (and useEffects()) and redirects from other components (idk why). Thanks for everyone who responded!
