### ISSUE TITLE
Firestore indexedDBPersistence fails inside of WebWorker

### ISSUE THREAD

**Issue by ebeloded** [firebase/firebase-js-sdk#6962]
### [REQUIRED] Describe your environment

```
  System:
    OS: macOS 13.1
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
  npmPackages:
    firebase: 9.16.0 => 9.16.0 
```

### [REQUIRED] Describe the problem

I am trying to run Firebase Auth and Firestore inside of Web Worker. Firebase Auth with `indexedDBLocalPersistence` works. However, trying to enable IndexedDB persistence for Firestore fails with the following error:

For `enableIndexedDbPersistence(firestore)`:

> @firebase/firestore: Firestore (9.16.0): IndexedDbPersistence LocalStorage is unavailable. As a result, persistence may not work reliably. In particular enablePersistence() could fail immediately after refreshing the page.

For `enableMultiTabIndexedDbPersistence(firestore)`:

> Uncaught (in promise) FirebaseError: IndexedDB persistence is only available on platforms that support LocalStorage.

Naturally, `localStorage` is not available inside of a WebWorker. Does it mean that Firestore persistence cannot be enabled?

#### Relevant Code:

```javascript
// worker.js
export const firestore = getFirestore(app)

enableIndexedDbPersistence(firestore)
// or enableMultiTabIndexedDbPersistence(firestore)
```

**Comment by MarkDuckworth** [comment]
@ebeloded, thanks for bringing this to our attention. I spoke with the team and determined that `localStorage` is needed for multi tab persistence, but we have a follow up investigation to determine if `localStorage` needs to be required when not using multi-tab. For now, it sounds like persistence will not be supported in a web worker. I'm leaving this open while we determine if this is a behavior we can change when not using multi-tab.

**Comment by laurentpayot** [comment]
@ebeloded in my web worker I use the [`forceOwnership`](https://firebase.google.com/docs/reference/js/firestore_.persistencesettings#persistencesettingsforceownership) option:

```javascript
const db = getFirestore(app)

enableIndexedDbPersistence(db, { forceOwnership: !globalThis.localStorage }) // forceOwnership for web worker
.then(() => console.log("Offline persistence enabled"))
.catch(error => {
    switch (error.code) {
        case 'failed-precondition':
            console.log("Offline persistence already enabled in another tab")
            break
        case 'unimplemented':
            console.log("Offline persistence not supported by browser")
            break
        default:
            console.error(error)
    }
})
```

Is it useful to you?

**Comment by ebeloded** [comment]
Yes! Thank you. I didn't know about the forceOwnership option.

**Comment by laurentpayot** [comment]
By the way, since `enableIndexedDbPersistence()` is deprecated, here is how I do now:

```javascript
const db = initializeFirestore(app, {
    localCache: persistentLocalCache({
        tabManager: persistentSingleTabManager({
            // forceOwnership for web worker
            forceOwnership: !globalThis.localStorage
        })
    })
})
```

Hope it helps issues like #7364.
