### ISSUE TITLE
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore

### ISSUE THREAD

**Issue by ctykaya** [firebase/firebase-js-sdk#6963]
### [REQUIRED] Describe your environment

  * Operating System version: Mac 13.0.1
  * Browser version: Version 109.0.5414.87 (Official Build) (arm64)
  * Firebase SDK version: 9.16.0
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem
When trying to build nextJS App with npm run build commend. An error throws in the collecting page data part.

#### Steps to reproduce:
Cannot reproduce the error. Here is the console logs

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/23)[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/categories". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/campaigns/add". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/admins/add". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/admins/[id]". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/dashboard". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/campaigns". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/notifications". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/admins". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/stores". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/categories/[product]/[...params]". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/stores/add". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/categories/add". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/options". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/orders". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/categories/edit". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/campaigns/[id]". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/stores/[id]". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/customers". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Error occurred prerendering page "/customers/[id]". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
info  - Generating static pages (23/23)

> Build error occurred
Error: Export encountered errors on following paths:
        /admins
        /admins/[id]
        /admins/add
        /campaigns
        /campaigns/[id]
        /campaigns/add
#### Relevant Code:
This project works fine before but I cannot figure it out whats cause this error. Could you please help. 

Here is the implementation of firebase  in config folder.
// Import the functions you need from the SDKs you need
```
import { FirebaseApp, FirebaseOptions, initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";

const adminConfig = {
  apiKey: "**",
  authDomain: "***",
  projectId: "***",
  storageBucket: "***",
  messagingSenderId: "***",
  appId: "***",
  measurementId: "***"
};

// Initialize Firebase
export const app = initializeApp(adminConfig);
// const analytics = getAnalytics(app);
export const auth = getAuth()
export const initializeSecondApp = (config: FirebaseOptions, name: string): FirebaseApp => {
  let secondApp = initializeApp(config, name)
  return secondApp
}
export const db = getFirestore(app);
```

**Comment by MarkDuckworth** [comment]
Hi @ctykaya, can you tell us more about how you are calling the `collection(...)` function on the line(s) that are throwing? What are the arguments you pass and how were they generated? Maybe provide a snippit from your code?

Thanks,
Mark

**Comment by ctykaya** [comment]
@MarkDuckworth  sure.
Here is my campaigns context 
```
  import { createContext, Dispatch, SetStateAction, useContext, useEffect, useState } from 'react'
  import { Timestamp, collection, doc, getDocs, setDoc, QueryDocumentSnapshot, query, orderBy, deleteDoc, Firestore, updateDoc, FirestoreDataConverter } from "firebase/firestore";
  import { useAuth } from './AuthContext';
  import { Campaign } from "../types/campaign";
  import { Item } from '../types/item';
  
  interface CampaignContextProps {
      getCampaigns?: () => Promise<void>,
      getCampaignById?: (id: string) => Campaign,
      handleSave?: (campaigns: Campaign[]) => Promise<void>,
      addCampaign?: (campaign: Campaign) => Promise<Campaign>,
      updateCampaign?: (campaign: Campaign) => Promise<void>,
      deleteCampaign?: (documentId: string) => Promise<void>,
      campaigns: Campaign[],
      setCampaigns?: Dispatch<SetStateAction<Campaign[]>>
      loading: boolean
  
  }
  const CampaignsContext = createContext<CampaignContextProps>({ campaigns: [], loading: false })
  
  export const useCampaigns = () => useContext(CampaignsContext)
  
  export const CampaignsContextProvider = ({ children }: { children: React.ReactNode }) => {
      const { brandDb: db } = useAuth()
  
      const converter: FirestoreDataConverter<Campaign> = {
          toFirestore: (data: Campaign) => data,
          fromFirestore: (snap: QueryDocumentSnapshot) => snap.data() as Campaign
      }
      const campaignRef = collection(db, "campaigns").withConverter<Campaign>(converter)
  
      const [campaigns, setCampaigns] = useState<Campaign[]>([])
      const [loading, setLoading] = useState(true)
  
  
      async function addCampaign(campaign: Campaign): Promise<Campaign> {
          setLoading(true);
          let documentId = doc(collection(db, 'campaigns')).id;
          let newCampaign: Campaign = {
              id: documentId,
              ...campaign
          };
  
          let ref = doc(db, "campaigns", documentId)
          await setDoc(ref, newCampaign);
          setCampaigns([...campaigns, newCampaign])
          setLoading(false);
          return newCampaign
      }
  
      function getCampaignById(id: string): Campaign {
          return campaigns.find(x => x.id == id)
      }
  
      async function getCampaigns() {
          setLoading(true);
  
          let q = query(campaignRef, orderBy("order", "asc"))
          let snapshot = await getDocs(q)
          let data = snapshot.docs.map((campaigns) => campaigns.data())
          setCampaigns(data)
          console.log("Campaigns Data", data)
          setLoading(false)
      }
  
      async function updateCampaign(campaign: Campaign): Promise<void> {
          let documentRef = doc(db, "campaigns", campaign.id);
          setLoading(true)
          console.log("converted", converter.toFirestore(campaign))
          await updateDoc(documentRef, converter.toFirestore(campaign))
          let newCampaigns = campaigns.map(x => {
              return x.id == campaign.id ? campaign : x
          })
          setCampaigns(newCampaigns)
          setLoading(false)
          console.log("updateCampaign result")
      }
  
  
      async function deleteCampaign(documentId: string): Promise<void> {
          let ref = doc(db, "campaigns", documentId)
          await deleteDoc(ref)
          setCampaigns((prev) => prev.filter(x => x.id != documentId))
      }
  
      useEffect(() => {
          getCampaigns();
      }, [])
  
     return (
        <CampaignsContext.Provider value={{
            campaigns,
            setCampaigns,
            getCampaignById,
            loading,
            updateCampaign,
            deleteCampaign,
            addCampaign
        }}>
            {children}
        </CampaignsContext.Provider>
    )
  }
```

**Comment by MarkDuckworth** [comment]
Thanks @ctykaya. I need to know how the db was generated in `useAuth()`. The reason I'm asking is this error indicates that the `db` argument is either not a Firestore instance, or it is an instance from a different build or version of the library. You may want to validate that before sharing any additional details of your code.

**Comment by ctykaya** [comment]
@MarkDuckworth 
Ok here is the useAuth. When I first run the app everything works fine. When try to build the app these errors throws or when refresh the page also these errors throws. 

I am storing the config information of the app on the main admin project. When user logged in they fetch the config of their project and then initialize the second app.
I create the db instance in setSecondAppWithConfig method. Here is the code

```
import React, { createContext, ReactNode, useContext, useEffect, useRef, useState } from 'react'
import {
  onAuthStateChanged,
  signInWithEmailAndPassword,
  signOut,
  UserCredential,
  getIdToken
} from 'firebase/auth'
import { auth, db, initializeSecondApp, app } from '../../config/firebase'
import { User } from '../types/user'
import { Nullable } from '../types/nullable'
import {
  doc, getDoc, setDoc,
  QueryDocumentSnapshot, getFirestore, Firestore, FirestoreDataConverter
} from "firebase/firestore";
import { FirebaseOptions } from '@firebase/app'
import { useRouter } from 'next/router'
import { FirebaseStorage, getStorage, uploadBytes, ref, getDownloadURL, deleteObject } from "firebase/storage";
import { Admin } from '../types/admin'
import {
  getFunctions,
  httpsCallable,
} from "firebase/functions";
import {
  User as fbUser
} from "firebase/auth";
import { useAdmin } from './AdminContext'

interface AuthContextProps {
  signUp?: (email: string, password: string, admin: Admin) => Promise<void>,
  login?: (email: string, password: string) => Promise<UserCredential>,
  logout?: () => void,
  deleteUser?: (userId: string) => void,
  uploadFile?: (file: File) => Promise<Nullable<string>>,
  deleteFile?: (file: File) => Promise<void>,
  deleteImageFromUrl?: (url: string) => Promise<void>,
  reSizeImage?: () => void,
  getToken?: () => Promise<string>,
  brandDb?: Firestore,
  adminDb?: Firestore,
  bucket?: FirebaseStorage,
  user?: Nullable<User>
}

const AuthContext = createContext<AuthContextProps>({})

export const useAuth = () => useContext(AuthContext)

export const AuthContextProvider = ({ children }: { children: React.ReactNode }) => {

  const { getAdmins, setAdmins, setAdmin } = useAdmin();
  const [brandDb, setBrandDb] = useState<Firestore>()
  const [storage, setStorege] = useState<FirebaseStorage>()
  const router = useRouter()
  const [user, setUser] = useState<Nullable<User>>()
  const [loading, setLoading] = useState(true)
  const [brand, setBrand] = useState<string>("")
  const functions = getFunctions(app);


  const converter: FirestoreDataConverter<Admin> = {
    toFirestore: (data: Admin) => data,
    fromFirestore: (snap: QueryDocumentSnapshot) => snap.data() as Admin
  }



  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (user) => {

      if (!user) {
        console.log("No User", user?.uid)
        setLoading(false)
        router.push("/login")
        return
      }
      console.log("User Name", user?.uid)
      await setSecondAppWithConfig(user.uid);
      setLoading(false)
      router.push("/dashboard")
    })

    return () => {
      console.log("UnMounted", "AuthContextProvider")
      unsubscribe()
    }
  }, [])

  useEffect(() => {

    if (brand) {
      getAdmins(brand);
      if (auth.currentUser != null) {
        console.log("CurrentUser not null to dashboard...");
      } else {
        console.log("Current User is null to login...")
      }
    }
  }, [brand])


  const setSecondAppWithConfig = async (userId: string) => {
    let docRef = doc(db, "users", userId)
    let document = await getDoc(docRef)
    let brand = document.data()["brand"] as string
    setAdmin(document.data() as Admin);
    setBrand((prev) => brand);
    let brandRef = doc(db, "brands", brand)
    let secondAppConfigDocument = await getDoc(brandRef)
    let secondAppConfig = secondAppConfigDocument.data() as FirebaseOptions
    let secondApp = initializeSecondApp(secondAppConfig, brand)

    setBrandDb(getFirestore(secondApp)) // <== This line create db instance

    let bucket = getStorage(secondApp, "gs://" + secondAppConfig.storageBucket);
    setStorege(bucket)
  }

  const login = (email: string, password: string) => {
    return signInWithEmailAndPassword(auth, email, password)
  }

  const logout = async () => {
    setUser(null)
    await signOut(auth)
  }

  const getToken = () => {
    return auth.currentUser.getIdToken();
  }

  return (
    <AuthContext.Provider value={{
      user,
      login,
      signUp,
      logout,
      brandDb: brandDb,
      adminDb: db,
      deleteImageFromUrl,
      bucket: storage,
      getToken,
      deleteUser,
      uploadFile,
      deleteFile: deleteFileFromBucket
    }}>
      {children}
    </AuthContext.Provider>
  )
}
```

**Comment by MarkDuckworth** [comment]
Thanks for providing that.\! I would confirm that `brandDb` is being set to the value you expect. Maybe set a breakpoint or add a `console.log` before you call `collection(db, "campaigns")` and ensure db is set to the expected value. Ensure `setSecondAppWithConfig` is being called as expected and that the Firestore DB is being initialized.

The next step may be to create a [minimal reproduce-able example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by ctykaya** [comment]
@MarkDuckworth  thanks for help I put the const converter into the methods and problem is fixed.

**Comment by MarkDuckworth** [comment]
Glad you got it fixed!
