### ISSUE TITLE
Auth - setCustomParameters - Localization issue for Facebook UI using locale custom parameters before signInWithPopup (v9.16.0)

### ISSUE THREAD

**Issue by mexysfr** [firebase/firebase-js-sdk#6972]
### Describe your environment

  * Operating System version:  macOS
  * Browser version: Chrome Version 109.0.5414.87 (Official Build) (x86_64)
  * Firebase SDK version: 9.16.0
  * Firebase Product:  auth
  * Additionnal info : Next.js v13 / next-i18next

#### Steps to reproduce:
Hello !
Thanks for this awesome lib and the mountain of work that is done here.

I'm currently building an application using Next.js and configuring social authentication.

I can't find any solution for my problem : localization for facebook UI using `signInWithPopup` function.
Below you'll find the incriminated code. It's actually working for Google (using `hl`), Twitter (using `lang`) and Apple (using `locale`) custom parameters.

Any help or direction to take would be much appreciated !

#### Relevant Code:

```ts
//myFunctions.ts
import { FacebookAuthProvider } from 'firebase/auth'
import { i18n } from 'next-i18next'
import { auth } from './firebase'

const signInWithFacebook = async () => {
    try {
      const provider = new FacebookAuthProvider()
      provider.addScope('email')
      provider.setCustomParameters({
        locale: i18n?.language ?? 'en',
       //also tested hardcoded as follow : locale : 'es_ES' but get the same (non)result
      })
      const { user } = await signInWithPopup(auth, provider)
      console.log(user)
    } catch (error) {
      console.log(error)
    }
  }
```

```ts
//firebase.ts
import { getApps, initializeApp } from 'firebase/app'
import { getAuth } from 'firebase/auth'

const firebaseConfig = {
  apiKey: ...
}

if (!getApps().length) {
  initializeApp(firebaseConfig)
}

export const auth = getAuth()
```

**Comment by prameshj** [comment]
Hi @mexysfr , the custom parameters configured in the code snippet will be directly constructed into a URL param for the facebook login URL.

I am not sure if "locale" is a supported param in the facebook URL, I found some stackoverflow answers stating this might be "locale2" - https://stackoverflow.com/a/12075154, but you might want to check the facebook docs.

**Comment by mexysfr** [comment]
Hi @prameshj 

Thanks for your answer. I've retried with :
```
locale: 'es_ES'
locale: 'es'
locale2: 'es_ES'
locale2: 'es'
``` 
I've also add `auth.languageCode = 'es'` before calling `signInWithPopup()` but nothing changed.

I'm wondering if this even possible, reading this article : https://developers.facebook.com/docs/javascript/internationalization/
At the end of it, it seems that Facebook is determining the user locale whatever the one that has been set programmatically for Facebook login

**Comment by prameshj** [comment]
> At the end of it, it seems that Facebook is determining the user locale whatever the one that has been set programmatically for Facebook login

This is probably the case. Closing this, since the facebook user locale parameters cannot be manipulated using the firebase SDK API.
