### ISSUE TITLE
Use Renovate or Dependabot

### ISSUE THREAD

**Issue by mmermerkaya** [firebase/firebase-js-sdk#698]
Let's consider using [Renovate](https://renovateapp.com/) or [Dependabot](https://dependabot.com/) (or any other alternative) to let us know when we can safely update our dependencies. Both of these (claim to) support Lerna and Yarn workspaces.

CC @gauntface, I saw a testimonial from you on Renovate's website :)

**Comment by gauntface** [comment]
Over to Josh for this.
I'm personally a fan and the few folks I've seen used renovate on Googlechrome repos have been happy with it.

**Comment by jshcrowthe** [comment]
I'm a fan of Renovate, but we need to address some permissions issues in the broader firebase org before we could enable it.

I'll keep this open for now.

**Comment by hsubox76** [comment]
Seems to be addressed now that we have added Gardener auto-updates: https://github.com/firebase/firebase-js-sdk/pull/1599
