### ISSUE TITLE
Auth/network-request-failed error Remix running on Cloudflare Pages

### ISSUE THREAD

**Issue by JorritSalverda** [firebase/firebase-js-sdk#7028]
### [REQUIRED] Describe your environment

  * Operating System version: Cloudflare Pages
  * Browser version: n/a
  * Firebase SDK version: 9.17.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

I'm running a Remix site on Cloudflare Pages (with compatibility date _2023-02-08_). When running it locally with the _wrangler_ emulator I can manage to log in using `signInWithEmailAndPassword` from `firebase/auth`. However when deploying it to Cloudflare Pages I get an `FirebaseError: Firebase: Error (auth/network-request-failed).` error when `signInWithEmailAndPassword` is executed.

This happens pretty much instant. The POST request to my site has timestamp 1676213902393, the failure of `signInWithEmailAndPassword` happens at timestamp 1676213902398 (5ms later?). It seems the outbound request is refused somehow. Does this request use _fetch_ or some other way of communication than regular http requests?

#### Relevant Code:

I have file `auth.server.ts` with the relevant code (the `server.ts` extension it ensures it runs server-side in a Cloudflare Worker I believe).

```typescript
import type { AppLoadContext, SessionStorage } from "@remix-run/cloudflare";
import type { Auth } from "firebase/auth";
import { signInWithEmailAndPassword } from "firebase/auth";
import { createUserSession } from "./session.server";

async function signIn(context: AppLoadContext, email: string, password: string, redirectTo: string) {
  // this line throws FirebaseError: Firebase: Error (auth/network-request-failed).
  const { user } = await signInWithEmailAndPassword(context.auth as Auth, email, password);

  return await createUserSession(context.sessionStorage as SessionStorage, user, redirectTo);
}
```

And the `server.js` file initiates the firebase app and getAuth.

```javascript
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import * as build from "@remix-run/dev/server-build";
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";

const handleRequest = createPagesFunctionHandler({
  build,
  mode: process.env.NODE_ENV,
  getLoadContext: (context) => {
    ...

    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
      apiKey: context.env.FIREBASE_API_KEY,
      authDomain: context.env.FIREBASE_AUTH_DOMAIN,
      projectId: context.env.FIREBASE_PROJECT_ID,
      storageBucket: context.env.FIREBASE_STORAGE_BUCKET,
      messagingSenderId: context.env.FIREBASE_MESSAGING_SENDER_ID,
      appId: context.env.FIREBASE_APP_ID,
      measurementId: context.env.FIREBASE_MEASUREMENT_ID
    };

    // Initialize Firebase
    const firebaseApp = initializeApp(firebaseConfig);
    const auth = getAuth(firebaseApp);

    return { ...context.env, sessionStorage, firebaseApp, auth }
  },
});
```

**Comment by prameshj** [comment]
> Does this request use fetch or some other way of communication than regular http requests?


It uses fetch - https://github.com/firebase/firebase-js-sdk/blob/c8a6e08b01a52b3eca77ca9da8989dac2e77a972/packages/auth/src/api/index.ts#L118, https://github.com/firebase/firebase-js-sdk/blob/c8a6e08b01a52b3eca77ca9da8989dac2e77a972/packages/auth/src/core/util/fetch_provider.ts#L39-L49


I wonder if the request headers are matching some CloudFlare rule causing it to drop the request. Is it possible to get a packet capture/logs to investigate?

Also, I am curious about the use-case. Is it deloying the emulator on a CloudFlare page (versus on localhost) to centrally try out the SDK against the backend emulator?
