### ISSUE TITLE
Uncaught (in promise): TypeError: Illegal invocation in channelrequest.js

### ISSUE THREAD

**Issue by Memaguer** [firebase/firebase-js-sdk#7034]
### Environment

  * Operating System version: Windows NT 10.0; Win64; x64
  * Browser version: Chrome/100.0.4896.127
  * Firebase SDK version: 9.0.0
  * Firebase Product: firestore

### Problem
I have been following up on some errors in my portal and on 3 occasions this error has appeared
```
Error: Uncaught (in promise): TypeError: Illegal invocation
TypeError: Illegal invocation
    at ce (https://portal.com/vendor.js:1:44015)
    at di.close (https://portal.com/vendor.js:1:53382)
    at Tg.Jr (https://portal.com/vendor.js:1:224245)
    at Tg.close (https://portal.com/vendor.js:1:221215)
    at https://portal.com/vendor.js:1:227517
    at Generator.next (<anonymous>)
    at t (https://portal.com/vendor.js:1:3202475)
    at h (https://portal.com/vendor.js:1:3202677)
    at https://portal.com/vendor.js:1:3202736
    at new h (https://portal.com/polyfills.js:1:29462)
```
I honestly couldn't produce the error myself but it seems that the error is in this piece of code

![image](https://user-images.githubusercontent.com/15709839/218548424-9f7b5581-f762-402a-97ac-10f476708672.png)

Path: `webpack:///./node_modules/@firebase/webchannel-wrapper/node_modules/google-closure-library/closure/goog/labs/net/webchannel/channelrequest.js`

This error has occurred at the loading time of the web page and I think it's an internal error handling issue.

**Comment by milaGGL** [comment]
Hi @Memaguer, thank you for reporting this issue. I am looking into the it.

Could you please delete the node_modules, re-create it and try running the app again? 

If the problem still exists, could you please check what does and "sendBeacon" and  "this" refers to in the code snippet? It might have lost the context to them somehow.

**Comment by samatcolumn** [comment]
We have also seen this error pretty frequently in our Sentry reports, but I can't reproduce it and I can't even figure out if it's having an adverse user effect. Note that we're using Firestore 8.3.3 (old, I know) and I recognize this stack trace is unhelpful but here it is anywyay:

![image](https://user-images.githubusercontent.com/98708721/220795566-f1d74fd9-98f4-491b-8b2d-3d70ee40df45.png)

**Comment by milaGGL** [comment]
Hi @Memaguer , @samatcolumn. Me and my colleague from WebChannel team are looking into the error, but it is hard to track down the root cause.  

I understand this is nearly impossible, but would you be able to create a minimal reproducible example? This will be super helpful with the debugging process on our end. 

If not, is there any pattern shown in Sentry reports related to this error? Any info that can help us narrow it down will be greatly appreciated. 

This is a long long shot, but debug log might be able to provide us with some insights. Could you enable logging with [firebase.firestore.setLogLevel('debug') ](https://firebase.google.com/docs/reference/js/firestore_#setloglevel), and have one of your users capture the log output from the console when they notice this error?

**Comment by milaGGL** [comment]
A try catch block is going to be added for debugging purposes. Internal users please see b/271633820.

**Comment by samatcolumn** [comment]
@milaGGL thank you for the response! I am not currently able to create a minimal example, but if I do figure out how to reproduce this I will let you know.

The only pattern I can see is that users who experience this error experience a lot of other errors. In particular I see that they are unable to load some data from Firestore. So it could be related to their network configuration (maybe blocking HTTP/2 or WebChannel?)

**Comment by milaGGL** [comment]
@samatcolumn, thanks for looking into the pattern. That might be the reason! The users who are experiencing these issue might be behind proxies.

Could you please try enabling the [long polling](https://github.com/firebase/firebase-js-sdk/issues/1674#issue-430655654) in Firestore? If this can significantly decrease the number of errors logged, we can confirm that it is the connection problem. Or, if possible, you can ask a user who is experiencing the error to diagnose their network via this link: https://debug-my.firebaseapp.com/.  When there is a proxy issue, user is supposed to see some "FAILED" flag at the end of the page, similar to this:
```
All tests done.
1: webchannel.googleapis.com with default options: FAILED (75864ms)
2: webchannel.googleapis.com with detectBufferingProxy: SUCCEEDED (1380ms)
3: webchannel.googleapis.com with forceLongPolling: SUCCEEDED (1183ms)
4: webchannel.sandbox.google.com with default options: FAILED (75996ms)
5: webchannel.sandbox.google.com with detectBufferingProxy: SUCCEEDED (1406ms)
6: webchannel.sandbox.google.com with forceLongPolling: SUCCEEDED (1194ms)
7: Firestore listen test with default options: FAILED (76002ms)
8: Firestore listen test with detectBufferingProxy: SUCCEEDED (1414ms)
9: Firestore listen test with forceLongPolling: SUCCEEDED (529ms)
```

**Comment by samatcolumn** [comment]
@milaGGL did you mean to let the oss-bot close this issue? IMO it has not been fully resolved.

**Comment by milaGGL** [comment]
Hi @samatcolumn, google-oss-bot will automatically close issues with no user side updates for 10 consecutive weekdays. Please feel free to re-open the issue when there are new information. 

> @samatcolumn, thanks for looking into the pattern. That might be the reason! The users who are experiencing these issue might be behind proxies.
> 
> Could you please try enabling the [long polling](https://github.com/firebase/firebase-js-sdk/issues/1674#issue-430655654) in Firestore? If this can significantly decrease the number of errors logged, we can confirm that it is the connection problem. Or, if possible, you can ask a user who is experiencing the error to diagnose their network via this link: https://debug-my.firebaseapp.com/. When there is a proxy issue, user is supposed to see some "FAILED" flag at the end of the page, similar to this:
> 
> ```
> All tests done.
> 1: webchannel.googleapis.com with default options: FAILED (75864ms)
> 2: webchannel.googleapis.com with detectBufferingProxy: SUCCEEDED (1380ms)
> 3: webchannel.googleapis.com with forceLongPolling: SUCCEEDED (1183ms)
> 4: webchannel.sandbox.google.com with default options: FAILED (75996ms)
> 5: webchannel.sandbox.google.com with detectBufferingProxy: SUCCEEDED (1406ms)
> 6: webchannel.sandbox.google.com with forceLongPolling: SUCCEEDED (1194ms)
> 7: Firestore listen test with default options: FAILED (76002ms)
> 8: Firestore listen test with detectBufferingProxy: SUCCEEDED (1414ms)
> 9: Firestore listen test with forceLongPolling: SUCCEEDED (529ms)
> ```

I wonder if you have deployed the `experimentalForceLongPolling` in your app. Are any pattern changes on the error log?

**Comment by samatcolumn** [comment]
@milaGGL we did not feel comfortable enabling `experimentalForceLongPolling` in our app in production (it's experimental) and we have not been able to reproduce this in a test environment yet.

> google-oss-bot will automatically close issues with no user side updates for 10 consecutive weekdays.

This is only true if you leave the labels in the "needs info" or awaiting response date. If you're wondering how I know this ... it's because [I am the original author of the oss bot](https://github.com/samtstern) :-)
