### ISSUE TITLE
Publish lighter modules

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-js-sdk#704]
I'm posting this issue since it can be resolved by a PR on this repository.

We are reaching limit during our cloud function deployments: `Build failed: size of uncompressed sources and installed modules (566 MiB) exceeds the limit (500 MiB)`

Our `node_modules` weight 608 MiB. 228 MiB are Google/Firebase modules.

Here is a list of the 10 bigger modules (using `du -sh functions/node_modules/* | gsort -h`): 

```
 11M	functions/node_modules/firebase-admin
 11M	functions/node_modules/slate-react
 14M	functions/node_modules/nodejieba
 23M	functions/node_modules/@firebase
 27M	functions/node_modules/sharp
 34M	functions/node_modules/googleapis
 46M	functions/node_modules/grpc
 67M	functions/node_modules/google-gax
 93M	functions/node_modules/@google-cloud
```

I think these modules can be published as lighter versions **without impacting usage**.

- Don't publish the `coverage` folders

For example, the coverage folders for the firebase core modules weight 5 MiB.
```
2.5M	functions/node_modules/@firebase/database/coverage
2.7M	functions/node_modules/@firebase/firestore/coverage
```

- Use a common `grpc` dependency

When running `npm ls grpc`, NPM found different version of GRPC, which is a big module:

```
├─┬ @google-cloud/pubsub@0.16.4
│ └─┬ google-gax@0.14.5
│   └── grpc@1.7.3
├─┬ firebase@4.12.1
│ └─┬ @firebase/firestore@0.3.7
│   └── grpc@1.10.0
└─┬ firebase-admin@5.12.0
  └─┬ @google-cloud/firestore@0.13.1
    ├─┬ @google-cloud/common-grpc@0.6.0
    │ └── grpc@1.9.1
    └─┬ google-gax@0.16.1
      └── grpc@1.10.1
```

**Comment by jshcrowthe** [comment]
Hey @SamyPesse appreciate the issue! We actually merged a PR to this effect recently (see https://github.com/firebase/firebase-js-sdk/pull/695) that addresses the bloat you mentioned.

**Comment by SamyPesse** [comment]
@jshcrowthe Thanks 👍 

Concerning `grpc`, is there anything that can be done to prevent having multiple versions (the module weights 45 MiB) ? At least for the `firebase-admin` and `firebase` modules.

**Comment by liamdanielduffy** [comment]
@jshcrowthe do have any update on the issue regarding multiple versions of `grpc`?
