### ISSUE TITLE
Build fails:  error yargs@17.2.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.15.0"

### ISSUE THREAD

**Issue by TheNotary** [firebase/firebase-js-sdk#7042]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Montey
  * Browser version: 109
  * Firebase SDK version: 9.17.1
  * Firebase Product: build script

#### Steps to reproduce:

Follow instructions in readme to:
1. Install the referenced version of node in the readme`10.15.0`
2. run yarn
3. See that you are presented with an error message 

> error yargs@17.2.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.15.0"

#### Relevant Code:

```javascript
$ yarn
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error yargs@17.2.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
$ node -v
v10.15.0
$ yarn -v
1.22.19
$ java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
```

**Comment by hsubox76** [comment]
Are you trying to build the JS SDK itself? We don't support Node versions older than 12 for building the JS SDK. Since it's not end consumption of the SDK itself, the build process doesn't support as wide a variety of environments.

**Comment by TheNotary** [comment]
The steps I described above are what's in the readme currently.  Which version of node do you think would be better to point to than `10.15.0`.  I've tried a couple but run into more errors while building the JS SDK so am not sure whether pointing to the latest lts of node `v18.12.0` is an improvement, but it was a thought I had.

**Comment by dwyfrequency** [comment]
I use v16.15.1 and it works well. Try using the lts version and see if that works correctly, if not fall back to the version I previously mentioned. In the meantime, we'll update the readme to avoid this future confusion.

**Comment by TheNotary** [comment]
Thanks @dwyfrequency, that gets me past the first `yarn` command, but `yarn build` starts moving along smoothly, but then terminates with a stack trace:

<blockquote>
API Extractor completed successfully
lerna info run Ran npm script 'build' in '@firebase/remote-config-compat' in 7.4s:
$ rollup -c
lerna info run Ran npm script 'build' in '@firebase/performance-compat' in 7.2s:
$ rollup -c
lerna info run Ran npm script 'build' in '@firebase/analytics-compat' in 7.7s:
$ rollup -c
lerna ERR! yarn run build exited 1 in '@firebase/database'
lerna ERR! yarn run build stdout:
$ rollup -c rollup.config.js && yarn api-report
$ TS_NODE_COMPILER_OPTIONS='{"module":"commonjs"}' ts-node ../../repo-scripts/prune-dts/extract-public-api.ts --package database --packageRoot . --typescriptDts ./dist/src/index.d.ts --rollupDts ./dist/private.d.ts --untrimmedRollupDts ./dist/internal.d.ts --publicDts ./dist/public.d.ts && yarn api-report:api-json
Configuring API Extractor for database
/var/folders/w3/vxjq5_0n3db5j6___mnfdcm80000gp/T/tmp-95663-RvTAWwmLpYf3/api-extractor.json
Analysis will use the bundled TypeScript version 4.1.6
Generated rollup DTS
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:

src/index.ts → dist/index.esm5.js...
created dist/index.esm5.js in 7.3s

.
.
.

src/index.standalone.ts → dist/index.standalone.js...
created dist/index.standalone.js in 7.6s
Warning: ./firebase-js-sdk/packages/database/dist/src/api/Database.d.ts:52:5 - (ae-incompatible-release-tags) The symbol "_root" is marked as @public, but its signature references "ReferenceImpl" which is marked as @internal
Warning: ./firebase-js-sdk/packages/database/dist/src/api/Database.d.ts:86:4 - (tsdoc-param-tag-with-invalid-name) The @param block should be followed by a valid parameter name: The identifier cannot non-word characters
Warning: ./firebase-js-sdk/packages/database/dist/src/api/Reference_impl.d.ts:887:5 - (ae-incompatible-release-tags) The symbol "_apply" is marked as @public, but its signature references "QueryImpl" which is marked as @internal
Warning: ./firebase-js-sdk/packages/database/dist/src/core/PersistentConnection.d.ts:96:8 - (tsdoc-tag-should-not-have-braces) The TSDoc tag "@inheritDoc" is not an inline tag; it must not be enclosed in "{ }" braces
Warning: ./firebase-js-sdk/packages/database/dist/src/core/ServerActions.d.ts:43:8 - (tsdoc-param-tag-missing-hyphen) The @param block should be followed by a parameter name and then a hyphen
Warning: ./firebase-js-sdk/packages/database/dist/src/core/view/EventRegistration.d.ts:27:38 - (tsdoc-at-sign-in-word) The "@" character looks like part of a TSDoc tag; use a backslash to escape it
./firebase-js-sdk/node_modules/typescript/lib/typescript.js:89385
                        void ts.Debug.assertNode(visited, test);
                                      ^
Error: Debug Failure. False expression: Unexpected node.
Verbose Debug Information: Node NotEmittedStatement did not pass test 'isClassElement'.
    at visitNodes (./firebase-js-sdk/node_modules/typescript/lib/typescript.js:89385:39)
    at Object.visitEachChild (./firebase-js-sdk/node_modules/typescript/lib/typescript.js:89835:362)
    at visitNodeAndChildren (./firebase-js-sdk/repo-scripts/prune-dts/prune-dts.ts:533:17)
    at ./firebase-js-sdk/repo-scripts/prune-dts/prune-dts.ts:535:22
    at visitNodes (./firebase-js-sdk/node_modules/typescript/lib/typescript.js:89367:48)
    at visitLexicalEnvironment (./firebase-js-sdk/node_modules/typescript/lib/typescript.js:89407:22)
    at Object.visitEachChild (./firebase-js-sdk/node_modules/typescript/lib/typescript.js:89958:55)
    at visitNodeAndChildren (./firebase-js-sdk/repo-scripts/prune-dts/prune-dts.ts:533:17)
    at ./firebase-js-sdk/repo-scripts/prune-dts/prune-dts.ts:539:12
    at transformation (./firebase-js-sdk/node_modules/typescript/lib/typescript.js:109638:24)
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@firebase/database'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</blockquote>

**Comment by hsubox76** [comment]
It seems like a TypeScript version incompatibility but that would be odd because the repo has a pinned dependency to typescript 4.7.4 (ignore the line about "Analysis will use the bundled TypeScript version 4.1.6", that's for the api extractor, not the build). You don't have a global version of TypeScript installed, or changed the version in the repo, did you?

When I run the build I get
```
Analysis will use the bundled TypeScript version 4.1.6
*** The target project appears to use TypeScript 4.7.4 which is newer than the bundled compiler engine; consider upgrading API Extractor.
```

and it looks like you're not getting the second part, so did you downgrade TypeScript to 4.1.6 somehow?

**Comment by TheNotary** [comment]
My working directory is clean and checked out from the commit tagged with `firebase@9.17.1`.  

As far as I can tell, I only have typescript installed locally in node_modules:

```
$  yarn run tsc -v
yarn run v1.22.19
$ ./node_modules/.bin/tsc -v
Version 4.7.4
✨  Done in 0.27s.

$  tsc -v
-bash: tsc: command not found
```

I see the `...project appears to use TypeScript 4.7.4...` note higher up in the logs, but it isn't showing up when it gets to the package that seems to be failing the build, `@firebase/database`.

**Comment by hsubox76** [comment]
Not sure what it could be, it runs fine for me on a fresh clone. Are you running it on a fresh clone or did you modify anything before building?

I notice the script being run (`api-report`) at that point uses `ts-node`. Do you have ts-node installed globally?

Also if you are trying to figure out what's wrong you can also save yourself some time on every try by `cd`ing into the `packages/database` directory and running `yarn build` in there (so you only build database).

Also since you opened another issue about auth I'm guessing you're doing this to debug something wrong with auth? You can just build auth then (cd packages/auth, yarn build), and then copy/symlink the packages/auth directory to the `node_modules/@firebase/auth` path in your app project.

**Comment by TheNotary** [comment]
Thanks for the development tips, @hsubox76 I'll keep those in mind.  I sketched up this crude Dockerfile below thinking it would reproduce the error I was experiencing, but in fact it built absolutely fine telling me there's something specific to my local environment jinxing things up.  

```
FROM node:latest

RUN mkdir /app
WORKDIR /app
COPY . ./

RUN yarn
RUN yarn build
```

I'm beginning to doubt that this is a common issue, but in case this issue starts getting traffic, removing the `&& yarn api-report` clause of the build command in the database package allows the build to complete normally on my local.  Probably the next time api-report's version is bumped, this issue will go away even on my system.

**Comment by TheNotary** [comment]
It's not stale, he has enough info around using v16.15.1.  He said he was going to just update the readme.  

> @TheNotary I use v16.15.1 and it works well. Try using the lts version and see if that works correctly, if not fall back to the version I previously mentioned. In the meantime, we'll update the readme to avoid this future confusion.

Can you make the readme update @google-oss-bot?   It should be a very simple update to make.

**Comment by DellaBitta** [comment]
Hi @TheNotary

I updated the readme about a month ago to suggest a range of node versions. Is the current readme still inadequate?

Thanks!

**Comment by TheNotary** [comment]
Hi @DellaBitta.  My research from months ago left me with two impressions, 1) that there was some weird stuff going wrong with my Yarn in docker somehow, and 2) that node `v10.15.0` was not compatible with this system.  If you or the bot were able to find evidence supporting `v10.15.0` is now compatible then the bot should close this issue as resolved.  However if not, then there has been some drift and the README should be updated.  The build system no longer using v10.15.0 would be a red flag for me that the readme should be brought up to speed with how you're building via CI/ CD.

**Comment by DellaBitta** [comment]
I updated the docs. Thanks!
