### ISSUE TITLE
FirebaseError: [code=invalid-argument]: Invalid database id [object Object]

### ISSUE THREAD

**Issue by csicky** [firebase/firebase-js-sdk#7046]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro 21H2
  * Browser version: Chrome 109.0.5414.122 
  * Firebase SDK version: 9.17.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
I upgraded from "firebase": "9.9.3" to "firebase": "9.17.1" and now it doesn't work at all. If I revert to 9.9.3 it does work. I don't know if I have something special in the project, but I can paste here the logs if it helps.

#### Steps to reproduce:
As soon as I start the project the error says:
```
@firebase/firestore: Firestore (9.17.1): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=invalid-argument]: Invalid database id [object Object]
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```
After I enable log level debug, these are the previous logs before the error:

![image](https://user-images.githubusercontent.com/3931907/219655988-520a6dce-0dab-495b-9b63-7904e81b218d.png)

I see there is this `"database":"projects/wisk-162305/databases/[object Object]"` where `[object Object]` should probably be a string, but I am not sure if I am doing something wrong and the previous version was more permissive, or is it a bug, I don't know. Searching for it did not bring anything on Google search.

#### Relevant Code:

```javascript

const firebaseApp = initializeApp(config)

export const db = getFirestore(firebaseApp, {
  cacheSizeBytes: CACHE_SIZE_UNLIMITED,
  synchronizeTabs: true,
  ignoreUndefinedProperties: true
})

enableMultiTabIndexedDbPersistence(db).catch(err => {
  if (err.code === 'failed-precondition') {
    // Multiple tabs open, persistence can only be enabled in one tab at a a time.
    toaster.error('For better performance, please keep Wisk in only one tab per browser')
  } else if (err.code === 'unimplemented') {
    // The current browser does not support all of the features required to enable persistence
  }
  console.log('enableMultiTabIndexedDbPersistence error', err.code)
})

export const AUTH = getAuth(firebaseApp)
export const uiConfig = uiConf
export const firebaseUI = new firebaseui.auth.AuthUI(AUTH)

const realTimeDatabase = getDatabase()
export const onlineCheckReference = ref(realTimeDatabase, '.info/connected')
```

**Comment by ehsannas** [comment]
Thanks for reporting @csicky . I'll take a look.

**Comment by csicky** [comment]
Thank you. If you need some more data, just let me know and I try to get it.

**Comment by tom-andersen** [comment]
Replace `getFirestore` with `initializeFirestore` in following code:

```
export const db = getFirestore(firebaseApp, {
  cacheSizeBytes: CACHE_SIZE_UNLIMITED,
  synchronizeTabs: true,
  ignoreUndefinedProperties: true
})
```

**Comment by csicky** [comment]
Wow, I don't know how I missed this, and even more, how did it work with `getFirestore` until now. Thank you for your help!
