### ISSUE TITLE
Add TypeScript definitions for firebase.functions()

### ISSUE THREAD

**Issue by ztzven** [firebase/firebase-js-sdk#705]
* Operating System version: All
  * Firebase SDK version: 4.12.1
  * Firebase Product: functions

In this version there are no TypeScript definitions for functions. Resulting in a ts error of:

`[ts] Property 'functions' does not exist on type 'typeof firebase'.`

**Comment by maxdobler** [comment]
No TypeScript definitions in 4.13.1 either. Please add some. Thank you! =)

**Comment by ztzven** [comment]
They'll come.

**Comment by mpoehler** [comment]
This is also described here (including dirty fix): https://stackoverflow.com/questions/49669360/using-firebase-functions-from-web-sdk-using-typescript 

I submitted a pull request with the changes here: https://github.com/firebase/firebase-js-sdk/pull/724
