### ISSUE TITLE
Firebase authentication for an Angular application is not working on iOS version 16

### ISSUE THREAD

**Issue by HoshenIshay** [firebase/firebase-js-sdk#7050]
### [REQUIRED] Describe your environment

  * Operating System version: win 11
  * Browser version: Chrome101
  * Firebase SDK version: 11.16.1
  * Firebase Product: auth , 

### [REQUIRED] Describe the problem
Firebase authentication for an Angular application is not working on iOS version 16 
Users who have updated to IOS 16 are unable to log in to the system using a Google account, 
whereas users with previous versions can still log in without any issues.

When a user tries to log in with a Google account, the system does not log them in

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by BiffBish** [comment]
I believe this is part of #6716

**Comment by renkelvin** [comment]
Thanks @HoshenIshay for reporting this. Please refer to https://firebase.google.com/docs/auth/web/redirect-best-practices. Let me know if it fix the issue for you.

**Comment by HoshenIshay** [comment]
> Thanks @HoshenIshay for reporting this. Please refer to https://firebase.google.com/docs/auth/web/redirect-best-practices. Let me know if it fix the issue for you.

@renkelvin 
Change to signInWithPopup
TXN :)

**Comment by prameshj** [comment]
Thanks for confirming!
