### ISSUE TITLE
Sign in with redirect blocked on firefox due to tracking cookies

### ISSUE THREAD

**Issue by noook** [firebase/firebase-js-sdk#7056]
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Monterey 12.2.1
  * Browser version: Firefox 111
  * Firebase SDK version: 9.17.1
  * Firebase Product: auth

#### Steps to reproduce:

- Sign in with GoogleAuthProvider
- Choose Google account
- Wait for `getRedirectResult()` to be executed

###### Console logs:

```
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 2
Request to access cookie or storage on “https://apis.google.com/js/api.js?onload=__iframefcb931308” was blocked because it came from a tracker and content blocking is enabled.

Request to access cookie or storage on “https://apis.google.com/_/scs/abc-static/_/js/k=gapi.lb.en.AMZ27oQJoUI.O/m=gapi_iframes/rt=j/sv=1/d=1/ed=1/rs=AHpOoo9dsXwz2g0gTMdQFEKa7ZoVvtQf4g/cb=gapi.loaded_0?le=scs” was blocked because it came from a tracker and content blocking is enabled.
```

**Note:**

I am using a very standard configuration of firefox, the default one when you install it, no custom settings for cookies.
The setting that seems to be the problem is the "Enhanced Tracking Protection" which is enabled by default. I can't ask my users to disable it just to sign in

#### Relevant Code:
This is a Vue framework context:

```ts
function signInWithGoogle() {
  const provider = new GoogleAuthProvider();
  signInWithRedirect(auth, provider);
}

onMounted(async () => {
  const credentials = await getRedirectResult(auth);
  if (credentials) {
    router.push(appConfig.login.redirectOnSuccess);
  }
});
```

**Comment by prameshj** [comment]
Thanks! I see the same behavior. Please follow the best practices in https://firebase.google.com/docs/auth/web/redirect-best-practices to avoid the cross-origin storage access.

**Comment by prameshj** [comment]
This is broken on Firefox 109 and later. The recommendation is to follow one of the options from the above link - 


More information from Firefox team:

Individual sites can be allowlisted by users by disabling Enhanced Tracking Protection for the given site. This can be done via the toggle in the shield panel or via "Manage Exceptions" in about:preferences#privacy.

There is also a help article on this here: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?as=u&utm_source=inproduct#w_what-to-do-if-a-site-seems-broken
