### ISSUE TITLE
TypeScript error in /node_modules/@firebase/util/dist/util-public.d.ts(496,91): ',' expected.  TS1005

### ISSUE THREAD

**Issue by shekhawat777** [firebase/firebase-js-sdk#7086]
* Operating System version: mac os m1 
  * Firebase SDK version: 9.17.1

I had installed firebase's latest version for analytics when I import these  
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
and  try to run the project  I am getting an error 
TypeScript error in /node_modules/@firebase/util/dist/util-public.d.ts(496,91): ',' expected. TS1005

export declare const getDefaultEmulatorHostnameAndPort: (productName: string) => [hostname: string, port: number] | undefined;

**Comment by shekhawat777** [comment]
export declare const getDefaultEmulatorHostnameAndPort: (productName: string) => [hostname: string, port: number] | undefined;
 getting error  in this line 
 TypeScript error in /node_modules/@firebase/util/dist/util-public.d.ts(496,91): ',' expected.  TS1005

**Comment by dwyfrequency** [comment]
Could you provide a repo where we can reproduce this error? I just created a simple create-react-app project with version 9.17.1 and I do not have any issues. I also tried this with 9.17.2 and had no issues. It could be the version of typescript you have installed https://stackoverflow.com/questions/71993624/error-in-node-modules-firebase-firestore-dist-index-d-ts2728-error-ts1005

```
...
"dependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "firebase": "^9.17.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },
...
```

```
import React from 'react';
import logo from './logo.svg';
import './App.css';

import { initializeApp } from 'firebase/app';
import { getAnalytics } from 'firebase/analytics';

const app = initializeApp({
 // add own credentials
});

const analytics = getAnalytics(app);
console.log(analytics);

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**Comment by shekhawat777** [comment]
yes I tried in the new project it's working I'm attaching an error file my
project is running smoothly but when I installed firebase and just import
and re-run the project it's giving me an error
my typescript version is  "typescript": "3.8.3",
and react "react": "^16.13.1",


import { initializeApp } from "firebase/app";
import { getAnalytics, logEvent } from "firebase/analytics";

**Comment by dwyfrequency** [comment]
@shekhawat777 - can you attach the error file you referenced? I tried an app with your exact typescript version and it ran correctly. Are any of your coworkers (if you have some) having issues with this? Have you been able to reproduce this in any other environments?
