### ISSUE TITLE
Realtime database does not function well when reopen

### ISSUE THREAD

**Issue by nes123** [firebase/firebase-js-sdk#709]
On IOS everything works fine. But on Android, when the app is sent to the background and then coming to the front in later stage, it seems that the connection to the firebase database is lost.

Is it a known bug ?

**Comment by schmidt-sebastian** [comment]
Hey! Thanks for the report. This is not a known issue, and if would help us if you could provide debug logs for your app. You can enable them via `FirebaseDatabase.getInstance().setLogLevel(Logger.Level.DEBUG);`

Note that this is the JS SDK GitHub repo. We don't yet have a way to tackle issues for the Android client via GutHub. Do you mind sending your logs to our support team? You can find contact information here: https://firebase.google.com/support/contact/troubleshooting/
