### ISSUE TITLE
Error: INTERNAL ASSERTION FAILED: Pending promise was never set

### ISSUE THREAD

**Issue by tanuj101** [firebase/firebase-js-sdk#7093]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 22.04.1 LTS
  * Browser version: Firefox 110.0.1
  * Firebase SDK version: 9.14.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem
When using `signInWithPopup` to sign in with Microsoft, An unhandled error is thrown `INTERNAL ASSERTION FAILED: Pending promise was never set`. This issue happens 5/10 times which makes it difficult to offer authentication with Microsoft.
P.S. This flow works perfectly fine on google chrome.

#### Steps to reproduce:

- Setup sign-in button.
- Execute `signInWithPopup` function from `firebase/auth`.

#### Relevant Code:

```javascript
    const provider = new OAuthProvider('microsoft.com');
    const auth = getAuth();
    const credentials = await signInWithPopup(auth, provider);
```

**Comment by jbalidiong** [comment]
Hi @tanuj101, thanks for reaching out. I tried replicating, but I wasn't able to reproduce the error.
 
If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by tanuj101** [comment]
Hi @jbalidiong, Thanks for responding. I've created a minimal code project where the issue is still reproducible on firefox https://codepen.io/Tanuj69/pen/wvErMrm, Once you add application configuration in `initializeApp`. The page will load.

**Comment by jbalidiong** [comment]
Thanks for the additional information @tanuj101. I was able to replicate the issue when running it on Firefox. Let me check what we can do for this issue or bring someone from our Auth team here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by silas** [comment]
This might be the same issue as https://github.com/firebase/firebase-js-sdk/issues/6956. It seems like there is a custom code path in `/__/auth/handler` (or maybe the auth library) for Firefox which is causing problems.

You could probably confirm this by installing something like https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/ and faking a chrome user-agent.

**Comment by tanuj101** [comment]
It seems due to this issue, this issue also exists in [firebaseui-web](https://github.com/firebase/firebaseui-web/issues/947) library since April 6, 2022.

**Comment by bhparijat** [comment]
Hi Tanuj, 
Thank you for bringing this up. While we work on figuring out the cause here, could you please try @silas's hack. It may help us understand this better. b/272821123 for google internal tracking.  Thanks!!

**Comment by tanuj-101** [comment]
@bhparijat Thanks, but faking a user-agent that @silas mentioned is not a hack but s proof that there is some firefox specific code which is causing this issue. We can not ask our users to use this extension :)

**Comment by tanuj101** [comment]
@bhparijat Thanks, but faking a user-agent that @silas  mentioned is not a hack but s proof that there is some firefox specific code that is causing this issue. We can not ask our users to use this extension :)

**Comment by silas** [comment]
@tanuj101 I think @bhparijat is just asking you to confirm/deny that setting the user-agent fixes the issue, not to actually recommend it as a workaround to your users.

**Comment by tanuj101** [comment]
Oh then yes @bhparijat, it does fixes the issue.

**Comment by tanuj-101** [comment]
This is fixed
