### ISSUE TITLE
sendSignInLinkToEmail throws auth/argument-error when handleCodeInApp set to false

### ISSUE THREAD

**Issue by pklitscher** [firebase/firebase-js-sdk#7101]
### [REQUIRED] Describe your environment

  * Operating System version: Window 10 10.0.19044
  * Browser version: Version 110.0.5481.178 (Official Build) (64-bit)
  * Firebase SDK version: 9.17.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem
`sendSignInLinkToEmail` throws `auth/argument-error` when `handleCodeInApp: false` in `firebase.auth.ActionCodeSettings`. However if you set it to `handleCodeInApp: true` in the below code it will succeed. I am doing email auth for a web app only so don't need iOS and android etc. & docs say they are optional. Also, even when using example   `firebase.auth.ActionCodeSettings` from docs it will fail when `handleCodeInApp: false

#### Steps to reproduce:

1. Call `sendSignInLinkToEmail` with below code (replacing url with own)
2. Throws `auth/argument-error`
3. Change `handleCodeInApp: false` to  `handleCodeInApp: true`
4. Code `sendSignInLinkToEmail` will succeed

Reference [this](https://firebase.google.com/docs/auth/web/passing-state-in-email-actions#handling_email_actions_in_a_web_application) when setting `firebase.auth.ActionCodeSettings`

#### Relevant Code:

```javascript
sendSignInLinkToEmail(auth, email, { url: "https://your-project-name.web.app/signin/action" , handleCodeInApp: false })
  .then(() => {
    console.log('Success');
  })
  .catch((error) => {
    console. Error(error.code);
    console. Error(error.message);
  });
```

**Comment by prameshj** [comment]
Thanks for reporting! I see the same behavior in the demo app. This error is coming from - https://github.com/firebase/firebase-js-sdk/blob/26b197f562d4c7b27f1910b4b24bb64486da6ebb/packages/auth/src/core/strategies/email_link.ts#L86, looks like it can be removed. @sam-gc any reason to keep this check?

**Comment by NhienLam** [comment]
Hi [pklitscher](https://github.com/pklitscher),
According to
https://firebase.google.com/docs/auth/web/email-link-auth#send_an_authentication_link_to_the_users_email_address, `handleCodeInApp` should always be set to true when doing `signInWithEmailLink`. 

> handleCodeInApp: Set to true. The sign-in operation has to always be completed in the app unlike other out of band email actions (password reset and email verifications). This is because, at the end of the flow, the user is expected to be signed in and their Auth state persisted within the app.

handleCodeInApp tells the backend to have the link go directly to the customer's website (provided in the continueUrl) as opposed to the firebase-hosting-provided action callback page. This is required for signInWithEmailLink because if the link doesn't go to the customer's website, the customer's website can never get the ID token.

Hence, you should set `handleCodeInApp` to true even when you only do email auth for a web app. Hope this helps!

**Comment by pklitscher** [comment]
Thank you @NhienLam  🙏🏻

Ok, I didn't fully understand the option. I think I was reading it as mobile app vs web (which actually sounds a tad silly now I think of it 😂) Why does it exist then if it's always true? I can't see when you wouldn't want receive the ID token? 

Also, I get this message in the emulator console which made me think I was selecting the wrong option? Is this just saying I won't get an email and I have to paste the link? 
![image](https://user-images.githubusercontent.com/24360902/224459866-9e8c295d-f2fb-4253-bb2e-b19e96fd6b65.png)

Thanks for helping with this one. Sorry it wasn't a bug
