### ISSUE TITLE
Bump issue #6063 - Installation request 400 INVALID_ARGUMENT

### ISSUE THREAD

**Issue by Tim-W** [firebase/firebase-js-sdk#7105]
This issue is very similar to the one reported in #6063 - since that one is closed and did not solve my problem, I created a new issue.

### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 22
  * Browser version: Firefox 110.0.1
  * Firebase SDK version: 9.7.2
  * Firebase Product: Cloud Messaging

#### Steps to reproduce:

1. Register firebaseApp via `firebase.initializeApp()` (completes successfully) 
2. call `getToken(messaging, {vapidKey: vapidKey})` with the correct VAPID key that was obtained from firebase console
#### Relevant Code:

```
initializeApp(firebaseConfig);
const messaging = getMessaging();
const messaging = getMessaging();
  console.log('Registering for notifications with key: ' + vapidKey)

  getToken(messaging, {
    vapidKey: vapidKey
  }).then((t) => {
    if (t) {
      console.log('Subscribing for notifications...')
      notifsApi.notifsSubscribePost({
        notifsSubscribePostRequest: {
          email: "", fcmDeviceToken: t
        }
      }).then(r => {
        console.log('Subscribed to notifications: ' + r)
      }).catch(reason => {
        console.warn('Could not subscribe to notifications: ' + reason)
      });
    } else {
      console.warn('Could not register VAPID token for FCM')
    }
  }).catch((err) => {
    console.warn('Error registering VAPID token for FCM', err)
  })
```

This outputs the following error:
```
Error registering VAPID token for FCM FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument." (installations/request-failed).
```
I am pretty certain that my credentials and my vapid token are both setup correctly as the intializeApp() does pass without issues.

**Comment by DellaBitta** [comment]
Hi @Tim-W,

I'm sorry to say that I wasn't able to reproduce this issue. Could you explain more about your build setup (frameworks, tools, etc) as well as if this issue happens 100% of the time?

This is the code I used:

```
window.onload = function () {
  if (Notification.permission === 'granted') {
    getToken(messaging, { vapidKey: '<your token> }).then((currentToken) => {
console.log("current token", currentToken);
    }).catch((err) => {
      console.log('An error occurred while retrieving token. ', err);
      // ...
    });
  }
}
```

I also included an empty `firebase-messaging-sw.js` file in the same directory.

Thanks!

**Comment by hsubox76** [comment]
I looked at the previous issue and found this:

> The only way I've been able to reproduce this error is if the appId is incorrect. Can you double check you have the correct appId string in your firebase config when you initialize Firebase? Make sure there aren't any extra quote marks or whitespace.

Can you double check your appId string in your `firebaseConfig`, and/or log your `firebaseConfig` variable? Completing initializeApp successfully doesn't mean your appId isn't wrong, it doesn't do any checks at that point.
