### ISSUE TITLE
Firestore v9 sign in with email and password alerts worng password even the password is correct

### ISSUE THREAD

**Issue by urlsab** [firebase/firebase-js-sdk#7109]
* Operating System version: windows 11
  * Browser version: chrome 110.0.5481.178
  * Firebase SDK version: 9
  * Firebase Product: auth

The login works only for the first time after you just create a new account, but when you logout - firestore forget the password or see that as null

on consloe i get:  auth/wrong-password Firebase: Error (auth/wrong-password).

And here my code: [consider all imports etc]

        const onLogin = async (e) => { 
        
       e.preventDefault();

        await signInWithEmailAndPassword(curAuth, email, password)

        .then((userCredential) => {
            const user = userCredential.user;
            console.log(user);
            console.log(curAuth);
            console.log(password);
            navigate("/dashboard");    
        })

        .catch((error) => {
            const errorCode = error.code;
            const errorMessage = error.message;
            console.log(errorCode, errorMessage);
            console.log(curAuth);
            // alert(errorCode);
        });

    }

**Comment by hsubox76** [comment]
I see you have a console.log for the password only after a successful login. For debugging, I would suggest logging the email and password strings before creating the account (before createUserWithEmailAndPassword), and then again before signing in (before signInWithEmailAndPassword), just to make sure there isn't some error in your code processing the string that causes it to be empty or null before you pass it to the Firebase auth functions.

**Comment by urlsab** [comment]
ok I'll do it

**Comment by urlsab** [comment]
I think i found  the answer.

https://github.com/firebase/firebaseui-web/issues/122

Don't sign in firestore auth if your google accouny t is connected.

I tried another email/google account I know, that is not connected to my pc - and i succeeded login and time.

**Comment by malcolmdeck** [comment]
I'm glad you were able to resolve this issue on your own :)

**Comment by urlsab** [comment]
Thanks

בתאריך יום ב׳, 13 במרץ 2023, 19:18, מאת Malcolm Deck ‏<
***@***.***>:
