### ISSUE TITLE
Cannot read property 'ns' of null at Object.load, proto file missing in 4.13

### ISSUE THREAD

**Issue by nkovacs** [firebase/firebase-js-sdk#711]
### [REQUIRED] Describe your environment

  * Operating System version: Google cloud functions
  * Firebase SDK version: 4.13
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

My cloud function started failing after upgrading to 4.13:

    Cannot read property 'ns' of null at Object.load (/user_code/node_modules/firebase/node_modules/grpc/index.js:146:28) at loadProtos 

The proto file is missing from dist in 4.13.

#### Relevant Code:

```javascript
const firebase = require('firebase');
// Required for side-effects
require("firebase/firestore");
function firebaseInit() {
    const config = {
...
    };
    firebase.initializeApp(config);
    return firebase.firestore();
}

exports.hello = (req, res) => {
    const db = firebaseInit();
    const docRef = db.collection('test').doc('foo');
};
```

**Comment by mikelehen** [comment]
Thanks for the report! I confirm this is an issue and we'll look into getting it fixed ASAP.

cc/ @jshcrowthe I think we over-filtered the dist/ folder...
