### ISSUE TITLE
AppCheck token refresh is triggering `permission-denied` in existing Firestore snapshot listeners

### ISSUE THREAD

**Issue by harrisonlo** [firebase/firebase-js-sdk#7116]
### Describe your environment

  * Operating System version: macOS Monterey 12.6.3
  * Browser version: Chrome 110
  * Firebase SDK version: 9.17.2
  * Firebase Product: AppCheck, Firestore

### Describe the problem

When the browser tab is left open for an extended period of time, the app regularly detects `permission-denied` errors from Firestore snapshot listeners. Here is a screenshot in which you may see a pattern:

<img width="257" alt="Screen Shot 2023-03-13 at 7 17 50 AM" src="https://user-images.githubusercontent.com/7886751/224580489-79576d78-fd19-4bfb-aee0-342241b8402e.png">

These errors mostly have a 55 minutes interval, which I suspect is due to the token refresh from AppCheck, which I recently enforced. There are 5~7 active snapshot listeners in the app, not all of them trigger this all the time. As you can see in the screenshot, only a pair of them *consistently* did. However, all of them erroneously triggered the error at one point. 

Depending on the app logic, it sometimes breaks the app. i.e. when you don't have permission, you can't access a document.

Also I should clarify, the user **does** have permission. Refreshing always solves the permission issue.

#### Steps to reproduce:

Enforce Firestore AppCheck in the Firebase console, then open a page with a Firestore listener for 55 minutes to an hour until the AppCheck token refreshes.

#### Relevant Code:

This error is captured in the third argument of the Firestore `onSnapshot` hook.

```javascript
const unsubscribe = onSnapshot(
    query(...),
    snapshot => {...},
    error => capture(error)
)
```

**Comment by dwyfrequency** [comment]
@harrisonlo - Can you confirm the `Token time to live` in the firebase console for this project? Did you change this value from the default to be 1 hour? 

![TimeToRefresh](https://user-images.githubusercontent.com/8900894/224821673-05b4a317-108c-44d7-9853-cae88c0fed8e.png)

**Comment by harrisonlo** [comment]
@dwyfrequency The app is using reCAPTCHA Enterprise and yes it is indeed 1 hour. I don't remember changing this, but should I change it to 1 day?

**Comment by harrisonlo** [comment]
Here is a new set of error logs:

<img width="1000" alt="Screen Shot 2023-03-14 at 7 14 20 AM" src="https://user-images.githubusercontent.com/7886751/224852963-765152fe-1728-43e4-9794-87699842d851.png">

At 20:12, all 5 snapshot listeners trigger the error. Then you can see the 55 minutes intervals. The snapshot pair at row 6 & 7 is also part of the first 5, so the interval there is about 16 minutes only.

Interestingly, here are the console logs from the browser:

<img width="440" alt="Screen Shot 2023-03-14 at 7 19 36 AM" src="https://user-images.githubusercontent.com/7886751/224853816-e5845cfe-101a-4fc4-8be8-4b597ebcd2ad.png">

`2023-03-13T12:12:20.723Z` translates to `Mar 13, 2023, 8:12:20 PM` my time. This is when the errors start to show. I suspect it was the moment I opened my laptop and the internet was unavailable for ~2 seconds.

**Comment by hsubox76** [comment]
So if I'm understanding correctly, the computer was asleep (closed) for a while, and when you opened it, you saw these console logs, and nothing before it (from while the computer was asleep)?

The reason I'm asking is that a `fetch-network-error` doesn't trigger the 1 day throttle, only a `fetch-status-error` does: https://github.com/firebase/firebase-js-sdk/blob/a57f435ec1fffdd167eb413f58c02647d73309d5/packages/app-check/src/providers.ts#L84. The initial throttle error message, when the throttling begins, looks exactly like the yellow warnings but it should be an error. Do you see any error like that before this?

The only thing that should trigger the throttle should be a 403 or 404 error, which means it would have to be connected to the internet, reach the App Check endpoint, and get one of those errors in response. One guess is that this happened while the computer was asleep, and reCAPTCHA fails somehow if the computer is closed, which causes a 403 error when the SDK tries to exchange the reCAPTCHA token with the App Check endpoint, which causes you to be locked out for a day.

Do all these examples occur when the computer is closed, or asleep? Or does it also happen when the computer is open and active the whole time?

**Comment by hsubox76** [comment]
Possible solution:

We currently only clear the throttle if there's a successful request:
https://github.com/firebase/firebase-js-sdk/blob/a57f435ec1fffdd167eb413f58c02647d73309d5/packages/app-check/src/providers.ts#L100

Instead, maybe we should clear it if there's any other error other than a FETCH_STATUS_ERROR (right before line 97) - or clear it if it's a set of specific errors (including FETCH_NETWORK_ERROR).

**Comment by harrisonlo** [comment]
Update: the errors went away after setting the token time to live to 1 day. I don't know if the underlying issue is solved tho. Back when I created this issue, the errors happened during usage, not when the computer is closed. I also don't remember seeing any ReCAPTCHA error.

**Comment by DellaBitta** [comment]
Hi @harrisonlo,

In April we changed the behavior a bit to better deal with these sorts of errors. Could you update your Firebase dependency to see if this issue is still a problem? Thanks!
