### ISSUE TITLE
Auto SignIn does not work any more in react native expo

### ISSUE THREAD

**Issue by Haseebshah936** [firebase/firebase-js-sdk#7119]
* Operating System version: macOS Ventura
  * React native expo: SDK 48
  * React native: 0.71.3
  * Firebase SDK version:  9.17.2
  * Firebase Product: auth 

onAuthStateChange does not get triggered it self after reopening the app once getting authenticated. The issue seems to me is the removal of asyncStorage from react native core in the latest version. If thats the issue please add the community version of asyncStorage.

**Comment by hsubox76** [comment]
See https://github.com/firebase/firebase-js-sdk/issues/6493 . We plan to make some changes in the next major version to make the community package the default for getAuth(). In the meantime, you can use initializeAuth and pass it the AsyncStorage object from the community package manually as described in that issue.
