### ISSUE TITLE
FR: convert Timestamp to Date automatically

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-js-sdk#7124]
### [REQUIRED] Describe your environment

  * Operating System version: Pop!_OS 22.04 LTS
  * Browser version: Vivaldi 5.7.2921.63 (Stable channel) stable (64-bit) 
  * Firebase SDK version: 9.17.1
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
It would be nice to have the SDK convert any Timestamps to JS Date automatically, so that we don't need to specify it every time we're making converters. Firebase Android SDK do this.

#### Relevant Code:
Current method:
```typescript
export const itemConverter: FirestoreDataConverter<Item> = {
	toFirestore(data: PartialWithFieldValue<Item>, options?: SetOptions): DocumentData {
		return data
	},
	fromFirestore(snap: QueryDocumentSnapshot): Item {
		const data = snap.data()
		return {...data, id: snap.id, createdAt: data.createdAt?.toDate()} as Item
	}
}
```

Proposed method:
```typescript
export const itemConverter: FirestoreDataConverter<Item> = {
	toFirestore(data: PartialWithFieldValue<Item>, options?: SetOptions): DocumentData {
		return data
	},
	fromFirestore(snap: QueryDocumentSnapshot): Item {
		const data = snap.data({convertTimestamps: true})
		return {...data, id: snap.id} as Item
	}
}
```

**Comment by cherylEnkidu** [comment]
Hi @risalfajar 

Thank you for filling up the feature request ticket! I will pass this to our team and will keep you updated.

**Comment by risalfajar** [comment]
Using Lodash `mapValues()` this is easy to achieve. Maybe you can start from this.

```typescript
fromFirestore(snap: QueryDocumentSnapshot): Order {
    const data = mapValues(snap.data({serverTimestamps: "estimate"}), it => it?.toDate ? it.toDate() : it) as Order
    data.id = snap.id
    return data
}
```

**Comment by cherylEnkidu** [comment]
Hi,

Thank you for filling up the ticket again. The team decided not to move forward with this feature request, since the js sdk is sensible to package size and user have work around for this feature. Please feel free to reopen the ticket if you have more questions.
