### ISSUE TITLE
Safari iOS 16.4 supports web push

### ISSUE THREAD

**Issue by fred-boink** [firebase/firebase-js-sdk#7145]
Describe your environment
  * Operating System version: iOS 16.4
  * Browser version: Safari 16.4 beta
  * Firebase SDK version: 9.18.0
  * Firebase Product: FCM

Describe the problem
Fails to initiate FCM on iOS 16.4

`Unhandled Promise Rejection: FirebaseError: Messaging: This browser doesn't support the API's required to use the Firebase SDK. (messaging/unsupported-browser).`

Steps to reproduce:
- On device with iOS 16.4 beta
- Install firebase
- initiate FCM in app

**Comment by fred-boink** [comment]
This is pretty big since this version of iOS releasing next week will support web push and firebase should support.

**Comment by zwu52** [comment]
Hi @fred-boink  thanks for reporting. Pointing to a relevant q & a here: https://github.com/firebase/firebase-admin-java/issues/779#issuecomment-1481614528.

Have you tried to enable the push API on the browser? similar to the guide written here: https://www.xda-developers.com/how-enable-safari-notifications-iphone/?newsletter_popup=1

**Comment by fred-boink** [comment]
> Have you tried to enable the push API on the browser?

Hi zwu52, thanks for responding. I have turned it on. Still gives me an error even when installed on homescreen, on a device running 16.4 beta.

**Comment by zwu52** [comment]
Looks like the error thrown here https://github.com/firebase/firebase-js-sdk/blob/5fd01e55860a32cf648f0a4e64a7108436c293e4/packages/messaging/src/api.ts#L56.

Can you try validating your browser instance is fulfilling checks here: https://github.com/firebase/firebase-js-sdk/blob/5fd01e55860a32cf648f0a4e64a7108436c293e4/packages/messaging/src/api/isSupported.ts#L26

**Comment by fred-boink** [comment]
It seems to be closer to working (not on device though but in the 16.4 simulator) but now I get the following error:
`firebaseerror: Messaging: The notification permission was not granted and blocked instead. (messaging/permission-blocked).`

Firebase does not seem to prompt the same way as other platforms

**Comment by zwu52** [comment]
sdk calls Notification.requestPermission() internally. but for ios & macos safari per https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/ . one would need to make an explicitly request call that is wrapped inside a user action (ex, a button click)

**Comment by fred-boink** [comment]
@zwu52 All seems to work now! I'm not sure what did it, but I can confirm firebase push worked on iOS beta 16.4 with newest everything

**Comment by JoergTiedemann** [comment]
Hi
I've same issue and can't get push on io16.4 with FCM to work.
Did you have any example code for me ?

**Comment by ShijinaShajahanWT** [comment]
@fred-boink  Could you please give sample code
