### ISSUE TITLE
`in` and `array-contains-any` combination is possible now, but it shouldnt be.

### ISSUE THREAD

**Issue by tylim88** [firebase/firebase-js-sdk#7147]
### [REQUIRED] Describe your environment
  * Firebase SDK version: 9.17.2 and onward
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

According to the documentation https://firebase.google.com/docs/firestore/query-data/queries#query_limitations

![image](https://user-images.githubusercontent.com/5227509/227008133-ad2649bf-143b-4bdd-a7fc-282dba80c9a9.png)

any combination of `in`, `not-in` and `array-contains-any` will throw error. However since v9.17.2, I discovered that `in` and `array-contains-any` query is possible, simple tests show that it returns correct result

v9.17.2 is released in this year, and this is 2023 release notes
![image](https://user-images.githubusercontent.com/5227509/227011471-a960d147-e029-41fe-8c4b-16c2d2397019.png)

it mentions nothing about it

#### Steps to reproduce:
1. create a `abc` collection in firestore
2. create a document with any id
3. filll the document with `{ a:'a', b:['b'] }`
4. Run the code(see relevant code)
5. before v9.17.2, it will throw
![image](https://user-images.githubusercontent.com/5227509/227010994-9ec06781-6ccc-49a6-8941-4912b4b1486a.png)
6. with v9.17.2 and onward, simple tests show that it works as expected

#### Relevant Code:

```ts
getDocs(
  query(
    collection(db, "abc"),
    where("a", "in", ['a']),
    where("b", "array-contains-any", ["b"])
  )
).then((qs) =>
  qs.forEach((doc) => {
    console.log({ docid: doc.id, data: doc.data() });
  })
);
```

**Comment by tylim88** [comment]
Is this API safe to use now? because firebase no longer throw error on it

if it is not safe to use, please bring back the error

**Comment by dconeybe** [comment]
I believe the documentation just needs to be updated. But I'm confirming internally and will reply here once I have a definitive answer.
