### ISSUE TITLE
Possible Mismatch with Typings and Browser Bundles?

### ISSUE THREAD

**Issue by gauntface** [firebase/firebase-js-sdk#716]
When build a Firebase project using Typescript, I'm outputting a ESModules bundle (which works fine) and then run that through Rollup to generate a final browser bundle.

At the moment Rollup is outputting the following error:

```
'initializeApp' is not exported by 'node_modules\firebase\app\index.js'
```

The Typescript code this relates to is simply:

```
import * as firebase from 'firebase/app';
const firebaseApp = firebase.initializeApp(config);
```

Firebase 4.13.1

Any ideas what might be causing this? Seems that ionic have been having this for some time: https://github.com/angular/angularfire2/issues/565 where a workaround is to basically exclude firebase from the rollup build and import as a global asset :(

**Comment by gauntface** [comment]
Previous bug with exact same issue was closed: https://github.com/firebase/firebase-js-sdk/issues/47

**Comment by gauntface** [comment]
Rollup Config is:

```
return rollupStream({
    rollup,
    input: moduleFile,
    output: {
      format: 'iife',
      sourcemap: true,
      name: path.basename(moduleFile),
    },
    plugins: [
      // Enable rollup to resolve node modules
      resolve({
        module: true,
        browser: true,
      }),
      // Converts commonjs to ES6 modules
      commonjs(),
      // This module enabled Rollup to *ingest* a sourcemap to apply
      // further manipulations
      sourcemapPlugin(),
      // Minify the bundled JS
      uglifyPlugin({}, esMinify),
    ],
  })
```

**Comment by codinronan** [comment]
@gauntface check this issue also opened yesterday: https://github.com/firebase/firebase-js-sdk/issues/715

Basically the scoped packages don't work yet, you need to import from `firebase` instead of `firebase/app`. This breaks tree shaking (which is what that rollup error means) but is unavoidable until all the package splitting is done. The Typescript types report that they are independent but in the actual JS they are not.

**Comment by jshcrowthe** [comment]
@gauntface I know we had some issues w/ our typings can you try installing `5.x` again and see if the issue still exists?

**Comment by Feiyang1** [comment]
@gauntface are you still facing the issue with the latest firebase version ?

**Comment by gauntface** [comment]
I think I had to drop Firebase or take some other approach for my project, so no idea if this is an issue still or not sorry. Feel free to close it.
