### ISSUE TITLE
`callableFromURL` does not return any value despite the V2 CF end with `POST 200`

### ISSUE THREAD

**Issue by 0xjei** [firebase/firebase-js-sdk#7172]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 22.04.2 LTS 
  * Browser version: Brave ([Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)](https://brave.com/latest/))
  * Firebase SDK version: 9.18.0
  * Firebase Product: functions

### [REQUIRED] Describe the problem

Currently, I'm working with a Cloud Function V2 (callable) that performs memory and cpu intensive tasks. The problem is that I do not get any value back from the `httpsCallableFromURL` method used to call the function (seems the function remains in execution). The configuration of the function is CPU equal to 4 and Memory equal to 16 GiB. Execution would seem to work fine as evidenced by the logs (POST 200).

#### Steps to reproduce:

Therefore, the potential problem could be related to the `httpsCallableFromURL` method, perhaps failing to retrieve the information due to computationally intensive task or execution time. IMHO, I am hypothesizing this because it is unlikely to be the case of incomplete termination due to POST 200 and the fact that the business logic of the function is correctly applied from start to finish. 

I leave you a log of the function execution and the source code of the function + `httpsCallableFromURL` method call. Unfortunately, I could not reproduce a similar and less complex case with another cloud function.

![logs](https://user-images.githubusercontent.com/20580910/228838739-523131d9-ae1a-41a5-ba9d-3e1f844d7feb.png)

Looking forward for your support, cheers!

#### Relevant Code:
- [`verifycontribution` V2 Cloud Function](https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/backend/src/functions/circuit.ts#L333)
- [`verifycontribution` call using the `httpsCallableFromURL` method](https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/src/helpers/functions.ts#L311)

**Comment by hsubox76** [comment]
Hm, if you check your browser's dev tools network tab, is a response received from the functions endpoint? I see it's sent by the cloud function, just wondering if it was received by the browser and what the payload looks like. If it's an SDK error, then the browser should have received the response, and the SDK is failing to do something with it. If I know what the response looks like it might help figure out which branch the SDK is going down.
