### ISSUE TITLE
FR: FirestoreDataConverter: don't pass data by reference

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-js-sdk#7188]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 22.04
  * Browser version: Vivaldi 64 Bit 5.7.2921.65
  * Firebase SDK version: 9.17.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
When I modify data inside `FirestoreDataConverter.toFirestore()`, the source data is also modified, this causes error. Of course this could be fixed if I deep-copied the data first, but it's much simpler if the library handles this.

#### Steps to reproduce:
1. Create an object to be sent to firestore
2. Send the data/object to Firestore by calling `set()` on a document reference that have converter
3. Modify the data inside converter's `toFirestore()`. For example: assign `serverTimeStamp` or delete unneded field.
4. The source data would also be modified

#### Relevant Code:

```typescript
export const salesConverter: FirestoreDataConverter<Sales> = {
        // this passed `data` should be deep copied so that it doesn't affect the original data
	toFirestore(data: PartialWithFieldValue<Sales>, options?: SetOptions): DocumentData {
		delete data.id
		if (!data.createdAt) data.createdAt = serverTimestamp()
		return data
	},
	fromFirestore(snap: QueryDocumentSnapshot, options: SnapshotOptions | undefined): Sales {
                // ....
	}
}
```

**Comment by milaGGL** [comment]
Hi @risalfajar. Thank you for submitting this ticket. I will take this feature request to our team's discussion and keep you informed of any updates.

**Comment by milaGGL** [comment]
Hi @risalfajar. After discussion, we have decided not to proceed with this feature request. Handling the deep copy within the SDK may negatively impact both time and memory efficiency. Additionally, implementing this feature would require a breaking change, which we want to avoid.

Thank you once again for bring this up with us. We appreciate your valuable feedback and suggestions.

**Comment by risalfajar** [comment]
Okay, I understand. Thanks for considering!
