### ISSUE TITLE
TypeError: childPathObj.split is not a function (observed only in v9 modular sdk methods and not in v8 methods)

### ISSUE THREAD

**Issue by idreameducationtech** [firebase/firebase-js-sdk#7189]
####  **Environment**
  * Operating System version: MacOS Ventura version 13.3
  * Browser version: _____
  * Firebase SDK version: "firebase - 9.15.0" and "firebase-admin - 11.4.1",
  * Firebase Product: database

#### **Problem description**
When the data is set or updated in the realtime database at a very frequent rate (10 requests per 100 milliseconds) using the 'ref' and 'set/update' functions of the version 9 modular SDK, the following error occurs

**TypeError: childPathObj.split is not a function**

Note: 
1. Please refer to the attachment for the complete Error stack

#### Steps to reproduce:
Q: What happened? How can we make the problem occur?
The problem occurs when the set/update function of the v9 modular SDKs are used to set/update data in the realtime database at a very frequent rate. The number of set/update queries we tried varied from 5 to 1000 queries, requested instantly. For example, 10 queries took 100 milliseconds and a random number of queries failed. 

Note: 
1. This is happening every time, even with the number of queries as small as 5.
2. **This is important to note here that the same issue isn't observed with the v8 set/update methods. This was tried with number of queries ranging from 10 to 5000, sent instantly**

#### Relevant Code:
The following piece of code refers to the methods used to set/update the data

```
import { ref, set, update } from 'firebase/database';

const setValueAsync = (path, data, next) => {
    try {
      const dbRef = ref(db, path);    // db refers to the database instance obtained from the method getDatabase(app)
      set(dbRef, data)
        .then(() => {
          next();
        })
        .catch((error) => {
          next(error);
        });
    } catch (error) {
      console.log(error);
      next(error);
    }
  };

const updateValueAsync = (path, data, next) => {
    try {
      const dbRef = ref(db, path);     // db refers to the database instance obtained from the method getDatabase(app)
      update(dbRef, data)
        .then(() => {
          next();
        })
        .catch((error) => {
          next(error);
        });
    } catch (error) {
      console.log(error);
      next(error);
    }
  };
```

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/95030746/229357087-e8cb628a-6aed-49a5-9095-57825c73cd5f.png">

**Comment by GarimaSharmaa** [comment]
I have been facing the same issue lately.
