### ISSUE TITLE
ID token in security rules not updated after phone authentication

### ISSUE THREAD

**Issue by gaeldestrem** [firebase/firebase-js-sdk#719]
**Firebase SDK version**: 4.13.0
**Firebase Product**: Auth / Security Rules

We have recently implemented a phone authentification. We're using the following methods of the firebase SDK to reauthenticate an user:
- `firebase.auth.PhoneAuthProvider.credential(verificationId, verificationCode)` 
- `user.linkWithCredential(credential))`

When a user verify his phone and try to save something in the DB, he got a Permisson Denied (some rules test for `auth.token.phone_number`). The prop `auth.token.phone_number` doesn't to seem to be updated when evaluated by the security rules.

We tried to force a token refresh after phone authentification, It works most of the time but sometimes, the token is not refreshed.

**When it works**
![image](https://user-images.githubusercontent.com/5053593/39180310-d48f0e6e-47b6-11e8-950c-01c0b1ea7fb7.png)

**When it doesn't**
![image](https://user-images.githubusercontent.com/5053593/39180285-bb76c1e2-47b6-11e8-9511-82008633fcce.png)

## What we don't understand
- Why we have to force the token refresh even if the idToken has been refreshed and contains the phone_number prop.
- Why the forceRefresh of the token doesn't work sometimes.

**Comment by SamyPesse** [comment]
@wti806 Any news on what may cause this ?

**Comment by wti806** [comment]
There are two issues here. First one is security rules not updated and second one is token didn't refreshed.  I tried to replicate the token refresh issue but was not able to. If you could provide me more detail to reproduce, it would be very helpful. For the first issue, need to assign to security rules folks.

**Comment by MeghaB** [comment]
@gaeldestrem I'm not able to reproduce this issue. If you are still seeing issues, please file a [Support ticket](https://firebase.google.com/support/troubleshooter/contact), and we can dig into your project/case specifically!
