### ISSUE TITLE
Requests from getDocs are closed after 1 minute

### ISSUE THREAD

**Issue by maxirozay** [firebase/firebase-js-sdk#7196]
* Operating System version: Debian 11
  * Browser version: brave Version 1.49.120  Chromium: 111.0.5563.64 (Official Build)  (64-bit)
  * Firebase SDK version: 9.19.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

`getDocs` requests return value in less than 10ms but stays open for 1 minute.

[related to this issue](https://stackoverflow.com/questions/74167286/firebase-query-wont-finish-it-returns-values-but-stays-open)

#### Steps to reproduce:
Create a collection with a few documents. Use `getDocs` to get those documents and check the console => network => time and waterfall. You will see in waterfall the message "CAUTION: request is not finished yet!". This message will disappear after 1 minute when the request is done.

#### Relevant Code:

```javascript
const db = getFirestore()

await getDocs(collection(db, 'documents'))
```

**Comment by milaGGL** [comment]
Hi @maxirozay, have you enabled `experimentalAutoDetectLongPolling` or `experimentalForceLongPolling`?

**Comment by maxirozay** [comment]
Hi @milaGGL, yes I tried with and without `experimentalAutoDetectLongPolling` with the same behavior. Then I read [here](https://firebase.google.com/docs/reference/js/firestore_.firestoresettings.md#firestoresettings_interface) that it's supposed to be normal and if you don't want this behavior you should use `experimentalForceLongPolling`. Effectively with `experimentalForceLongPolling` it doesn't wait anymore so I guess it's not a bug.

This behavior is not an issue but googlebot (google web crawler) doesn't want to load my firestore request so I thought it was linked. I'm still looking for why firestore is not working on googlebot but everywhere else it's fine.

**Comment by milaGGL** [comment]
@maxirozay, please feel free to open a new issue ticket with the googlebot + firestore problem, preferably with a reproducible code. We are happy to help.

**Comment by maxirozay** [comment]
@milaGGL, I could fix the issue with `experimentalForceLongPolling`. So I let the explanation here for someone who would have the same issue.

I don't think opening a new issue would be useful as it doesn't seem to be a bug, just the normal behavior to let the request open in case there is more to fetch. Which googlebot will ignore since it can't wait that long. I think the best think to do would be to write in the doc that googlebot needs `experimentalForceLongPolling`.

To reproduce, a simple `getDocs()` will be enough to see that the request stays open for one minute and create an error on https://search.google.com/search-console/inspect.
