### ISSUE TITLE
Failed to get aggregate result because the client is offline

### ISSUE THREAD

**Issue by sellsjonathan** [firebase/firebase-js-sdk#7198]
* Browser version: **Chrome 111.0.5563.146**
  * Firebase SDK version: **firebase 9.15**
  * Firebase Product: **firestore database**
  *  React Application compiles via Vite.

I wanted to start using the new aggregate queries, to be more efficient in my reads.

My project has collections of `projects` and `tasks`

I wanted to find the totals of tasks per project with the following query, through a `forEach()`

```javascript
projectIds.forEach((projectId: string) => {
  const allTasksQuery = query(
	  firebase.documents(),
	  where('taskEmails', 'array-contains', encodedEmail),
	  where('project.uid', '==', projectId),
	  where('isLatestVersion', '==', true)
  );
  const promise = getCountFromServer(allTasksQuery)
	  .then((result) => {
		  const projectCount = result.data().count;
		  totalTasks[projectId] = projectCount;
	  })
	  .catch((err) => console.error('Error getting task Totals', err));
  allPromises.push(promise);
  });
```

NOTE: `firebase.documents()` is just a wrapper for this ref:
```javascript
	const documents = () => collection(firestore, 'documents');
```
This works roughly 50% of the time, especially when coming from a page that has already recieved data back from firestore in a more convention `getDoc` or `getDocs` query.  If I hard reload on the page that executes this query, as well as in other circumstances I receive the following error:

`FirebaseError: Failed to get aggregate result because the client is offline.`
![image](https://user-images.githubusercontent.com/8787299/230112913-38fcc8d9-b6c0-4c93-b56e-d1b4e4d9a054.png)

Any help or clarification would be greatly appreciated.  Thank-you.

**Comment by ehsannas** [comment]
Thanks for reporting @sellsjonathan . I'll take a look.

**Comment by ehsannas** [comment]
@sellsjonathan Are you using `enableMultiTabIndexedDbPersistence()` in your code?

**Comment by ehsannas** [comment]
Second question: Is the authenticated user changing for cases when you get the error?

**Comment by sellsjonathan** [comment]
@ehsannas 

Hey there, yes we do appear to be using `enableMultiTabIndexedDbPersistence()`, and the authenticated user is consistent for these cases.  It is an authorized user landing on a page within the application.

**Comment by atsjo** [comment]
Getting the same error with my project, using sdk 9.19.1with enableMultiTabIndexedDbPersistence() configured via the new caching api. I can trigger it by opening a second tab with my web-page... I am also testing with a user already logged in...

**Comment by ehsannas** [comment]
Thanks for confirming @sellsjonathan @atsjo. This appears to be a bug specific to `count` when multi-tab is enabled. I am actively working on a fix.

**Comment by sellsjonathan** [comment]
Thanks @ehsannas , really appreciate your time and investigation into this.  When do you think this will get released?

**Comment by ehsannas** [comment]
The fix has been merged. It'll be available in the upcoming release (likely next week)
