### ISSUE TITLE
Package path . is not exported from package

### ISSUE THREAD

**Issue by tuanhai2712** [firebase/firebase-js-sdk#7217]
### [REQUIRED] Describe your environment
Operating System version: Windows 10
Browser version: Google Chrome 111.0.5563.149
Firebase SDK version: "9.17.1"
webpack: "5.78.0"
webpack-cli: "5.0.1"

I'm trying to upgrade firebase from v7.24.0 to v9.17.1 and runing npm install. I have this error

![image](https://user-images.githubusercontent.com/35209688/231692516-5e86a554-bb7b-490b-9c42-93cae8bdc4a9.png)

#### Steps to reproduce:
install firebase 9 and run npm install

**Comment by hsubox76** [comment]
The API changed drastically from version 8 to version 9. Check out the migration guide here: https://firebase.google.com/docs/web/modular-upgrade
