### ISSUE TITLE
app check token error [App attesetation failed] react native

### ISSUE THREAD

**Issue by vipulguria** [firebase/firebase-js-sdk#7223]
### [REQUIRED] Describe your environment

  * Operating System version: Android version (11)
  * Firebase versions: 
  * "@react-native-firebase/analytics": "^17.4.1",
    "@react-native-firebase/app": "^17.4.1",
    "@react-native-firebase/app-check": "^17.4.1",
    "@react-native-firebase/crashlytics": "^17.4.1",
    "@react-native-firebase/dynamic-links": "^17.4.1",
    "@react-native-firebase/messaging": "^17.4.1",
    "@react-native-firebase/perf": "^17.4.1",
    "@react-native-firebase/remote-config": "^17.4.1",
  * Firebase Product: App check 

### [REQUIRED] Describe the problem
When i try to generate the app check token in debug build using the debug provider it works fine(on an unrooted device), and also when i try to generate the app check token in release build it works fine...but when i test it on a rooted device for release build it gives me the following error:
![Screenshot_20230414-071115__01](https://user-images.githubusercontent.com/51699678/231920889-9dc9859f-00e1-45c3-b151-f4a3e37570c8.jpg)

#### Relevant Code:
Below is my code [i used a try catch block to catch the error]
<img width="921" alt="Screenshot 2023-04-14 at 7 27 07 AM" src="https://user-images.githubusercontent.com/51699678/231922248-a0d4e305-87eb-4f29-ba2d-c9cd6b869f88.png">

Please help me out ...i am not able to debug the issue on how to fix it

**Comment by hsubox76** [comment]
This API doesn't look familiar. Are you using React Native Firebase (https://rnfirebase.io/)? It seems to be. If so, this is the repo for that product: https://github.com/invertase/react-native-firebase
