### ISSUE TITLE
new providers replace the email/password provider when the email is not verified

### ISSUE THREAD

**Issue by gustavdz** [firebase/firebase-js-sdk#7225]
* Operating System version:Osx
  * Browser version: Chrome Version 112.0.5615.49 
  * Firebase SDK version: 9.15.0
  * Firebase Product: auth

I got users without verified emails registered to sign in with email/password, but when they try to sign in with Google for example, this provider replace the email/password provider registered but not verified.
This just happens when the user does not verify the email address and then try to use another provider.
It would be nice to not replace the exists provider at any time because the user could verified his account maybe after use the Google provider. 

#### Steps to reproduce:
1) Create a user with email/password provider and not verify his email address.
2) Sign in with another provider for the same user, Google for example.
3) try to login with the email/password provider and you get an invalid password error
4) check the list of users in firebase and the email/password provider was replaced by Google provider and it was not added as a new provider

**Comment by prameshj** [comment]
This is the correct default behavior. Can you try changing this setting and see if that gives the behavior you are looking for?

![image](https://user-images.githubusercontent.com/35932340/232571192-de1e6451-7fb7-48a9-87c3-557f1889b747.png)

**Comment by gustavdz** [comment]
> This is the correct default behavior. Can you try changing this setting and see if that gives the behavior you are looking for?
> 
> ![image](https://user-images.githubusercontent.com/35932340/232571192-de1e6451-7fb7-48a9-87c3-557f1889b747.png)

I did that before and then I have different accounts based on the provider, but what I need is to link the accounts with different provider to use the same email address.

I identify the problem and it is just happening when the email address is not verified, but I want to know if is there a way to add a new provider to an existing account **without** the email verified?

**Comment by prameshj** [comment]
I am not sure i fully understand the scenarios:

1) Default behavior - create user with email/password, email not verified, user logs in with Google(same email) and the same user has 2 providers.

2) Allow duplicate emails - create user with email/password, email not verified (user1), user logs in with Google(same email) and a second user is created.

Are you asking for a hybrid of the 2?

**Comment by gustavdz** [comment]
> 

No, actually what I need is to complete the scenario No.1, but this is not happening, because it just works when the email is verified. If the user does not verify his/her email when the user logs in with Google (same email) the email/password provider its replaced by the Google provider and the user lose the capability to use email/password provider again.
