### ISSUE TITLE
onSnapshot / docData sometimes does not work when offline on iOS

### ISSUE THREAD

**Issue by rspy** [firebase/firebase-js-sdk#7240]
### Describe your environment

  * Operating System version: iOS 16.3.1
  * Browser version: 16.3?
  * Firebase SDK version: Firestore 3.10.1, rxfire 6.0.3
  * Firebase Product: firestore (auth, database, storage, etc)

### Describe the problem
I try to load the user doc from firestore using docData (rxfire, uses onSnapshot undeneath) using the userId provided as a custom claim in the auth user. This works fine when online and also offline on my computer (macOS/Chrome) when blocking requests to firestore simulator (localhost:8080), but on iOS it only works about half the time, the other half I get undefined back from docData.

It could be a timing issue since I try to load the user on application startup, but firestore is properly initialized and enableIndexedDbPersistence is called. Adding a delay didn't solve the problem though.

#### Steps to reproduce:
Enable flight mode, docData sometimes returns undefined.

#### Relevant Code:

```javascript
user(this.firebase.auth).subscribe(async (authUser) => {
      const token = await authUser?.getIdTokenResult();
      const userId = token.claims.userId;
      this.user = docData(doc(firestore, `users/${userId`) as DocumentReference<User>, {
            idField: 'id',
      });
     // user sometimes is undefined - workaround is to reload the app (location.reload()), which "solves" the problem
});
```

**Comment by wu-hui** [comment]
Can you take auth out of the picture? Or are you sure you always get a valid `userId`?

You could also share your reproduction in a git repo to us. Alternatively enable debug logging and send us the log might also help us trouble shoot: https://firebase.google.com/docs/reference/js/firestore_#setloglevel

**Comment by rspy** [comment]
Hi wu-hui

auth works perfectly, the userId is always present in the custom claims. As soon as the user registers, we write it into the custom claims using a function and we get that value back from the auth token every time. Since you need to log in when online, I'm also quite sure that the user object must be in the cache.

Despite that, docData sometimes returns undefined when I start the app while offline, online always works. I could only reproduce it when running on an iPhone and it happens around 50% of the time. It recovers when I go online (aka flight mode off). My workaround is to reload the app when the userDoc is undefined, which isn't a valid state (userId in the claims and no userDoc). After reload, it eventually works.

I'll put together a demo app since the code of the app is in a private repo.

**Comment by wu-hui** [comment]
The only thing I can think of is that maybe Firestore's garbage collector has kicked in and decided to delete this document. Do you know how big your cache size might be, it only starts to collect documents when it's more than 100MB by default. When you develop your App, the usage is usually low, if that is the case then my guess is wrong.

Anyways, looking forward to you reproduction.
