### ISSUE TITLE
Codebase spelling issue - Identify

### ISSUE THREAD

**Issue by jonshaffer** [firebase/firebase-js-sdk#7268]
### [REQUIRED] Describe your environment

  * Operating System version: All
  * Browser version: All
  * Firebase SDK version: All
  * Firebase Product: auth (auth, database, storage, etc)

#### Steps to reproduce:

Just a misspelling of the word identify.

#### Relevant Code:

```javascript
SEE PR
```

**Comment by hsubox76** [comment]
PR is merged.
