### ISSUE TITLE
Blank page after sign-in in with OAuth on iOS

### ISSUE THREAD

**Issue by maclementED** [firebase/firebase-js-sdk#7273]
### [REQUIRED] Describe your environment

  * Operating System version: iOS 16.4 
  * Browser version: Safari/604.1
  * Firebase SDK version: 9.16.0
  * Firebase Product: auth
  * Not using firebase hosting but using a reverse proxy for `__/auth/*`

### [REQUIRED] Describe the problem
Hi, Im using Firebase on my PWA to sign in with Google and Apple. The app open the Google/Apple auth page and after sign in in, it's redirecting to a blank page on iOS only. 

On iOS, the application is in a **webview**. I tried both `signInWithPopup` and  `signInWithRedirect` method. I'm now testing using `signInWithRedirect` only.

I also followed the best pratices from the docs ([https://firebase.google.com/docs/auth/web/redirect-best-practices](https://firebase.google.com/docs/auth/web/redirect-best-practices)). I manage to setup a reverse proxy but it didn't help solving the issue.

#### Steps to reproduce:
1. Open https://www.pwabuilder.com/
2. Enter app.wavecnt.com as the url
3. build for iOS and add those permitted URLs: (accounts.google.com, accounts.youtube.com, accounts.google.ru, appleid.apple.com)
4. Open xCode and run on an iOS 15 or 16 device 
5. Sign In with Google or Apple
6. Now the `__/auth/handler` page should be blank.

**Comment by hsubox76** [comment]
Not on the auth team so I could be off base here, but you mention a webview. I know you said PWA and not Cordova/Ionic but since Cordova is also webview-based, wondering if it has the same needs. Would using the Cordova build help? (import everything from `firebase/auth/cordova` instead of `firebase/auth`)

**Comment by renkelvin** [comment]
Hey @maclementED , I'm unable to replicate the problem on my end (by the way, I'm not able to access app.wavecnt.com via the browser). Would it be possible for you to provide a screen recording of the issue?

**Comment by maclementED** [comment]
hey @renkelvin,
I was just able this morning to fix it. I want apologize to you for searching for a bug that I had already fixed earlier. 

At first, I was using the correct method `signInWithRedirect`, but I didn't used custom domains. While adding the custom domain, I also introduce another issue that made my app use `signInWithPopup` in the WebView.

I had the following code in my app.
```typescript
if (isInAppBrowser()) {
        return signInWithRedirect(auth, new GoogleAuthProvider());
} 
return signInWithPopup(auth, new GoogleAuthProvider());
```

I didn't checked that `isInAppBrowser` was false in a iOS webview.
