### ISSUE TITLE
Not getting current user details from firebase auth.

### ISSUE THREAD

**Issue by jaypalrana** [firebase/firebase-js-sdk#7274]
I am trying to integrate Firebase authentication in my React native project using the "firebase/auth: "^0.21.4" and "firebase":"^9.20.0" packages.
After integrating Firebase authentication, when I log in the first time, it works fine and I can fetch current user details. But when I kill the application and reopen it, Firebase auth returns me a null value as the current user.
I tried many different solutions from Google but nothing is work for me.

**Comment by hsubox76** [comment]
We need a little more information, can you provide us a minimal repro (best option) or if not, at least show us your code where you are importing, initializing, and calling auth?

**Comment by jaypalrana** [comment]
@hsubox76 
That was version related issue and it is fixed now.
Thanks for your support!
