### ISSUE TITLE
Compatibility issues with create-react-app

### ISSUE THREAD

**Issue by jshcrowthe** [firebase/firebase-js-sdk#73]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Sierra
  * Firebase SDK version: 4.1.2
  * Firebase Product: core (auth, database, storage, etc)

### [REQUIRED] Describe the problem

Cross Posting from #26 

>I writing some unit for React with the Jest unit test framework but I got the following error while
>TypeError: _firebase2.default.storage is not a function
>
>Here the stacktrace :
>
>` FAIL src/components/organisms/PriceSettingsBlock/PriceSettingsBlock.test.js
>● Test suite failed to run
>
>TypeError: _firebase2.default.storage is not a function
>
  >at Object.<anonymous> (src/core/firebase/firebase.js:8:120)
  >at Object.<anonymous> (src/core/firebase/firebase-list.js:1:815)
  >at Object.<anonymous> (src/core/chat/eventList.js:30:77)
  >at Object.<anonymous> (src/core/chat/sagas.js:4:44)
  >at Object.<anonymous> (src/core/chat/index.js:2:62)
  >at Object.<anonymous> (src/core/init/sagas.js:3:39)
  >at Object.<anonymous> (src/core/init/index.js:1:387)
  >at Object.<anonymous> (src/components/organisms/PriceSettingsBlock/PriceSettingsBlock.js:6:39)
  >at Object.<anonymous> (src/components/organisms/PriceSettingsBlock/PriceSettingsBlock.test.js:4:53)
  >at handle (node_modules/worker-farm/lib/child/index.js:41:8)
  >at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
  >at emitTwo (events.js:106:13)
  >at process.emit (events.js:194:7)
  >at process.nextTick (internal/child_process.js:766:12)
  >at _combinedTickCallback (internal/process/next_tick.js:73:7)
  >at process._tickCallback (internal/process/next_tick.js:104:9)`
>Test file is here :
>PriceSettingsBlock.js.txt
>PriceSettingsBlock.test.js.txt
>
>My configuration is here:
>`import firebase from 'firebase';
>import { firebaseConfig } from './config';
>
>export const firebaseApp = firebase.initializeApp(firebaseConfig);
>export const firebaseAuth = firebaseApp.auth();
>export const firebaseDb = firebaseApp.database();
>// firebase.storage() seems to be null
>export const firebaseStorage = firebase.storage();`
>
>And my configuration ( config.js):
>
>export const firebaseConfig = {
>apiKey: 'my api key',
>authDomain: 'my-project-id.firebaseapp.com',
>databaseURL: 'https://my-project-id.firebaseio.com',
>projectId: 'my-project-id',
>storageBucket: 'my-project-id.appspot.com',
>messagingSenderId: 'my-sender-id'
>};
>
> Any idea ?

#### Steps to reproduce:

> @jshcrowthe I have create a new project with create-react-app:
> https://github.com/ataliadvanstep/firebase-jest
> Just clone the project and run npm test
> ![image](https://user-images.githubusercontent.com/26287180/27306155-e065fa28-5544-11e7-91b7-fc830fff2845.png)

#### Relevant Code:

https://github.com/ataliadvanstep/firebase-jest

**Comment by jshcrowthe** [comment]
Firebase leverages the `browser` field in its `package.json`. This allows us to ship a different binary  for different environments in the same package. Jest, out of the box, does not respect this field and create-react-app, does not configure it when jsdom is set.

I don't know if this is intentional on their side but I will raise the issue there. In the mean time, you can update the test script to be:

```bash
react-scripts test --env=jsdom --browser
```

Then your tests should pass as expected.

**Comment by gaearon** [comment]
Here is another solution for CRA:
https://github.com/facebookincubator/create-react-app/issues/2590#issuecomment-310414231

**Comment by FrenchMajesty** [comment]
Hello Folks,

I am having the same problem and I tried the solutions above but I still get an error:

![screen shot 2018-09-06 at 10 15 22 am](https://user-images.githubusercontent.com/24761660/45166977-d1b47500-b1bd-11e8-9c2d-95e3ac8dbc69.png)
