### ISSUE TITLE
[Bug]: Incompatible timestamp object to firebase-admin/firestore

### ISSUE THREAD

**Issue by duncanchiu409** [firebase/firebase-js-sdk#7301]
### Operating System

ubuntu 22.04

### Browser Version

chrome

### Firebase SDK Version

^9.21.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Angular app. Using @firebase/firestore to define timestamp interface and class.
Express  API built with firebase-admin/firestore. 

### Describe the problem

interface of timestamp from firebase-admin is different to firebase-js-sdk's.

``
firebase-admin
{
"_seconds":xxx,
"_nanoseconds":xxx
}
``

``
firebase-js-sdk
{
"seconds":xxx,
"nanoseconds":xxx
}
``

### Steps and code to reproduce issue

build a simple app with angular and api communicate through json

**Comment by duncanchiu409** [comment]
#6476

**Comment by cherylEnkidu** [comment]
Hi,

Could you please share with me is there any reason you need the tag for timestamp in two SDK to be the same?

**Comment by cherylEnkidu** [comment]
In general we son't support the mix use of two different SDKs and there is no guarantee similar api layer between different SDKs.
