### ISSUE TITLE
Not sending requests to firebase on some mobile devices

### ISSUE THREAD

**Issue by Plyska** [firebase/firebase-js-sdk#7305]
### [REQUIRED] Describe your environment

  * Operating System version: iPhone 13 v16.3, iPhone 13 v15.4, 
  * Browser version: Chrome (92.0.4515.90), 
  * Firebase SDK version: v9, v8
  * Firebase Product: database

### [REQUIRED] Describe the problem

Hello

I am writing to report the problem with Firebase. 

I am using firebase version 9 in my project, and some mobile devices do not send requests to firebase (namely .set() method  ). If updating chrome and safari, then everything works fine, but not all users have an updated browser.

I have also tried using firebase v8, but nothing changed.

Can you please tell me how to solve this problem?

**Comment by jbalidiong** [comment]
Hi @Plyska, thanks for bringing this to our attention. Is it possible to turn on debug log and share the log with us: https://firebase.google.com/docs/reference/js/firestore_#setloglevel

**Comment by hsubox76** [comment]
Wait, is this Firestore or Realtime Database (`firebase/database`)?

Which versions of Safari or Chrome don't work? Is there an error message in the console? Does the `.set()` promise finish successfully, or is there an error that can be caught with `catch()` or `try/catch`?
