### ISSUE TITLE
Combination of orderByChild and equalTo doesn't work in v9

### ISSUE THREAD

**Issue by varungupta85** [firebase/firebase-js-sdk#7308]
This issue is already opened at https://github.com/firebase/firebase-js-sdk/issues/6929 but the conversation has been limited and there is no progress on it since Jan. This seems like a major bug in the code and surprised to see the issue is open for last 4 months. I ran into this while upgrading from v8 to v9 and spent hours trying to figure out why it is not working and eventually landing on issue #6929.

Please either allow conversation on issue #6929 such that other people can also add their report and get status updates.

**Comment by looptheloop88** [comment]
Hi @varungupta85, we can continue the discussion on this issue. Per #6929, the solution to get rid of the error after migrating the JS v8 implementation to JS v9 is to update the Firebase SDK and CLI versions.

I also tried replicating the issue using the code snippets provided in #6929, but I wasn't able to. I connected to a database from an actual project and even used an emulator. I didn't encounter any errors and I was able to get the expected value from the database.

It seems that orderByChild with equalTo is working fine using the latest version of Firebase SDK (9.22.0) and Firebase CLI (12.0.1). Try to compare if you're using the same SDK version and see if the issue persists. I'll close this issue now, but you may reopen it when you still have additional concerns.

**Comment by varungupta85** [comment]
@looptheloop88 My apologies for jumping the gun in opening the issue. I didn't realize that Firebase CLI could play a part in behavior of the SDK. I am still don't know how as once we ship the application, the clients don't have any Firebase SDK installed on their system where they access the application. Is the web app bundle creation affected by the Firebase CLI version? Maybe because the Firebase function in which the code was run was running in an emulator? It would be great if you could shed some light on it just for the readers' understanding for future.

I downgraded to Firebase 9.14.0 which also fixed the issue for time-being. I will update the Firebase CLI version and the Firebase version and test again. Thanks for your response.
