### ISSUE TITLE
[Bug]: Login from Okta shows "Unable to process request due to missing initial state"

### ISSUE THREAD

**Issue by derekperkins** [firebase/firebase-js-sdk#7317]
### Operating System

Desktop

### Browser Version

Chrome/113

### Firebase SDK Version

9.15.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React app with Vite

### Describe the problem

SSO is configured for a customer. When they go to our app login page and click Login with SSO, everything works as expected. If they click from inside Okta for a direct login, it fails, showing this screen

![image](https://github.com/firebase/firebase-js-sdk/assets/3588778/25b87f96-cc26-4b81-a688-4a0adda8cff6)

### Steps and code to reproduce issue

The link in the customer portal looks like:
https://customer123.okta.com/app/customer123_nozzleio_1/exk7wsldzdbPP3qwL5d7/sso/saml

**Comment by derekperkins** [comment]
cc @tannerlinsley

**Comment by jbalidiong** [comment]
Hi @derekperkins, thanks for reaching out. This might be related to #4256. To narrow down the possible cause of the issue, you can follow the suggestion provided by one of our engineers:

> 
> The most common case for this error is if the auth helper code and the main application are NOT on the same origin. This can be fixed by following one of the best practices in https://firebase.google.com/docs/auth/web/redirect-best-practices
> 
> If you are on the same origin and still seeing this issue, please file a separate issue describing the setup + repro steps. If you are seeing this in mobile, please open an issue in the relevant mobile SDK. Again, a repro app + the browser info will be very useful. Thanks!

**Comment by johnanthonyeletto** [comment]
Hi @jbalidiong I'm having the same issue. We are using a SAML provider. I set up a custom domain and it does not resolve the issue.

The thing here is that the request is originating from Okta. I'm not sure exactly how it works behind the scenes, but I'm not sure what kind of initial state Firebase is expecting when Firebase didn't originate the request.

This seems like it would likely need to be resolved on the server-side by Firebase as opposed to an issue strictly related to firebase-js.

**Comment by derekperkins** [comment]
Thanks for tracking that down @johnanthonyeletto. I found two upstream issues for it from a few years ago that show no signs of life
- https://issuetracker.google.com/issues/190383166
- https://issuetracker.google.com/issues/180929215

**Comment by DellaBitta** [comment]
Hi folks,

If you would please update the header of this issue to be a feature request from server-side SAML support, and then I'll tag it as a feature request internally and leave it up. People can continue to upvote it and those linked tickets to drive demand for the feature.

I also recommend everybody filing your own [Support Ticket feature request](https://firebase.google.com/support/troubleshooter/contact) that describes your use case. This can help the service team determine the demand for the feature.

Thanks.

**Comment by derekperkins** [comment]
Reopen
