### ISSUE TITLE
False positive check. Annoying warning. @firebase/firestore: Firestore: Host has been set in both settings() and useEmulator(), emulator host will be used

### ISSUE THREAD

**Issue by iSuslov** [firebase/firebase-js-sdk#7331]
Look at the arguments here:
https://github.com/firebase/firebase-js-sdk/blob/e642fc7cd73161adb925d57af086c6f3e1a38d44/packages/firestore/src/lite-api/database.ts#L294-L301

Now look at how you set `host` in settings:
https://github.com/firebase/firebase-js-sdk/blob/e642fc7cd73161adb925d57af086c6f3e1a38d44/packages/firestore/src/lite-api/database.ts#L312-L316

Now look at how you comparing `host:port` (from settings) with `host` :

https://github.com/firebase/firebase-js-sdk/blob/e642fc7cd73161adb925d57af086c6f3e1a38d44/packages/firestore/src/lite-api/database.ts#L305-L310

**Comment by ehsannas** [comment]
Thanks for reporting @iSuslov . I'll take a look.
