### ISSUE TITLE
FR: add data() to QuerySnapshot and the likes

### ISSUE THREAD

**Issue by cedvdb** [firebase/firebase-js-sdk#7332]
Simple convenience request to add a method `data()` to a QuerySnapshot, as `docs.map(doc => doc.data())` is so frequent.

```
docs.data() 

// equivalent to:

docs.map(doc => doc.data())
```

This would be especially convenient when working with streams / observables as it's not uncommon to have things like`querySnapshotStream.map((snap) => snap.docs.map(doc => doc.data())` which could be reduced to `querySnapshotStream.map((snap) => snap.data())`.

**Comment by ehsannas** [comment]
Thanks for your suggestion @cedvdb . I'll bring it up with the team.

**Comment by ehsannas** [comment]
Thanks for your suggestion @cedvdb . It doesn't look like this is something that we're going to prioritize at the moment.

Having a simple helper function to do this mapping should be sufficient.
