### ISSUE TITLE
Do Google signInWithRedirect and getRedirectResult().

### ISSUE THREAD

**Issue by torretorich** [firebase/firebase-js-sdk#7341]
### Operating System

iOS 16.2

### Browser Version

Safari 16.2 (18614.3.7.1.5)

### Firebase SDK Version

9.19.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

React js google signin with firebase and google drive API

### Describe the problem

I want to do Google Sign-In with redirect using Firebase. However, when I retrieve the sign-in result from getRedirectResult().then(async function (result) and run the website in Chrome or Brave browser, I receive the user account details in the result. But, when I run this in Safari browser, I get null user account details in the result. How can I fix this issue? Why do I get null in Safari browser?

### Steps and code to reproduce issue

import firebase from "firebase/compat/app";

export const auth = firebase.auth();
export const provider = new firebase.auth.GoogleAuthProvider();

export async function googleSigIn() {
    await auth.signInWithRedirect(provider)
}

auth.getRedirectResult().then(async function (result) {
            console.log("signIn result = " , result)
}

**Comment by bhparijat** [comment]
Please refer https://github.com/firebase/quickstart-js/blob/master/auth/google-redirect.html to the usage of google sign-in with redirect
