### ISSUE TITLE
Permission denied when changing from v8 to v9 on session already authenticated

### ISSUE THREAD

**Issue by LaetiPlanity** [firebase/firebase-js-sdk#7344]
### Operating System

macOS 13.3.1

### Browser Version

Chrome/114.0.5735.90

### Firebase SDK Version

9.22.1

### Firebase SDK Product:

Auth, Database, Remote-Config

### Describe your project's tooling

React app with Webpack and Jest

### Describe the problem

I changed firebase version from `8.10.0` to `9.22.1` (also tried with `9.0.0` and it's the same) and choose to use compat libs for now (`firebase/compat/app`, `firebase/compat/auth`, `firebase/compat/remote-config`, `firebase/compat/database`). I was already logged before the change. Now, I have a `Permission_denied` that I never had on a node `foo/${userIs}`.
If I clean the cookies and log again, all works well, no permission denied.

The rule on the node `foo/${userId}` is `".read": "auth.uid === $userId || root.child('foo').hasChild(auth.uid)"`
I am using `firebase.auth().createCustomToken` from firebase-admin 9.12.0 on server side.

### Steps and code to reproduce issue

Create token with `firebase.auth().createCustomToken` from `firebase-admin` `9.12.0` on server side.
Login with `auth.signInWithCustomToken` from `firebase` `8.10.0`.
Change `firebase` version `8.10.0` to `9.22.1`.
Use compat libs.
Try to access to a node `foo/${userId}` with the rule described above.

**Comment by bhparijat** [comment]
Hi,
Please share  reproducible  code. Thanks!
