### ISSUE TITLE
Is the value of Auth.currentUser not displayed normally?

### ISSUE THREAD

**Issue by Sunjae95** [firebase/firebase-js-sdk#7348]
### Operating System

MAC 13.3.1

### Browser Version

chrome 114.0.5735.90

### Firebase SDK Version

9.22.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

I was testing auth.currentUser in a development environment with Next.js version 13.2.4. 
auth.currentUser represents the currently signed-in user. 
When I console.log auth, it shows auth.currentUser as null, but when I expand the auth object, currentUser is present. 

What I want is for it to come out the same if auth.currentUser exists.

This inconsistency in auth.currentUser led me to raise an issue 😊

### Describe the problem

```
/pages/app.js
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
console.log('auth', auth);
console.log('auth.currentUser', auth.currentUser);

// The image below shows the result of the code:
```

![image](https://github.com/firebase/firebase-js-sdk/assets/63578094/05ccbbe1-d430-42a9-94cc-24c132588310)

## 1. I tested auth.currentUser to see if it was asynchronous using async await.
However, the same result was obtained.

## 2. I pressed save twice to check the results in development
For example, it means to re-insert and re-execute other code in a problem situation.

![image](https://github.com/firebase/firebase-js-sdk/assets/63578094/adddc669-d7c6-4ccf-9d8e-a609160918f7)

**Comment by hsubox76** [comment]
It's generally not recommended to use `auth.currentUser` as a reliable source of the current user. See https://github.com/firebase/firebase-js-sdk/issues/6752#issuecomment-1306135052 for a brief explanation.

The recommended way to reliably get the state of the current user is `onAuthStateChanged()`. Do you have similar issues if you use `onAuthStateChanged()` instead?

**Comment by Sunjae95** [comment]
> 



> It's generally not recommended to use `auth.currentUser` as a reliable source of the current user. See [#6752 (comment)](https://github.com/firebase/firebase-js-sdk/issues/6752#issuecomment-1306135052) for a brief explanation.
> 
> The recommended way to reliably get the state of the current user is `onAuthStateChanged()`. Do you have similar issues if you use `onAuthStateChanged()` instead?

I was using it wrong. 
I didn't find any other problems.
Thank you for your kind explanation.
