### ISSUE TITLE
Firebase Auth LOCAL persistence unsupported in chrome extension manifest v3

### ISSUE THREAD

**Issue by aryaputras** [firebase/firebase-js-sdk#7349]
### Operating System

Macos

### Browser Version

Chrome 113.0.5672.126

### Firebase SDK Version

9.0.2 Compat

### Firebase SDK Product:

Auth

### Describe your project's tooling

Did not use any JS front end framework. 

### Describe the problem

I get this error while trying to set the persistence type to SESSION / LOCAL

`firebase.auth().setPersistence(firebase.auth.Auth.Persistence.SESSION); 
`
```
Uncaught (in promise) FirebaseError: Firebase: The current environment does not support the specified persistence type. (auth/unsupported-persistence-type).
at J (assert.ts:122:55)
at $ (assert.ts:153:11)
at ci.setPersistence (persistence.ts:76:3)
at background.js:17:21
```

The only type I'm not getting error is when I set is to NONE. But the problem is, everytime my chrome extension is not open for few minutes, it will fire up firebase.initailizeApp again which log user out!

This making my app really useless.

This is what my code looks like
```

try {
    self.importScripts('/firebase/firebase-app.js', 'firebase/firebase-auth.js', 'utils.js', 'const.js');

    const firebaseConfig = {
    // config
    };

    const app = firebase.initializeApp(firebaseConfig);

    const auth = firebase.auth(app);
    auth.setPersistence(firebase.auth.Auth.Persistence.SESSION);

    // const auth = firebase.auth();
    console.log(`auth is ${auth}`);
    console.log(`currentuser is ${auth.currentUser}`);

```
  
I expect it to persist my user authentication state. So that they don't need to re-login everytime the extension sleeps.

My chrome version is 113.0.5672.126, and use Standard Protection option for security. (in browser settings)

### Steps and code to reproduce issue

use
auth.setPersistence(firebase.auth.Auth.Persistence.SESSION);.

And go to chrome://extension on developer mode. Click load unpack, and choose folder.

1. Open the extension(at this step, unsupported type error will shown in popup console.)
2. login (sign in with email and password)
3. then close it. 

4. wait a few minutes (usually 1-5 mins)

open again, user will be signed out.

My takeaways is, the only persistence type supported is .NONE. but why?

**Comment by hsubox76** [comment]
Filling in some missing background: https://developer.chrome.com/docs/extensions/migrating/to-service-workers/#state

Manifest v3 replaces the "background" script in extensions with a service worker. Service workers cannot access local or session storage.

That page has a couple of [suggestions](https://developer.chrome.com/docs/extensions/migrating/to-service-workers/#convert-localstorage):
1) move the call to an "offscreen document". Not sure what this means exactly, but you can try following the directions on that page and moving your auth calls to that offscreen document and see if it's a possible workaround. This would have to be done on the app developer's side
2) Replace localStorage with chrome.storage.local. This would mean writing an additional custom persistence in the Auth SDK just for extensions - up to the auth team to prioritize this
3) Clicking on the "Other options" link, it indicates IndexedDB still works in the Manifest V3 service worker. From the Auth documentation, it seems LOCAL persistence includes both localStorage and indexedDB, not sure how it uses each. If there were a way to specify indexedDB only, it might work. Will leave it to the Auth team to provide more info on this.

**Comment by aryaputras** [comment]
thank you. I read out your suggestion. But I didn't think it's related to the problem. From what I conclude, it's basically a chrome API. And the way you use it is with chrome.offscreen.createDocument / closeDocument. I don't see it as viable solution to authenticating user. 
 
 Will wait for the auth team for response

**Comment by bhparijat** [comment]
Hello @aryaputras, here are a few things to try:
1. Try  doing ` firebase.auth()` without setting any persistence explicitly and share with us what the persistence behavior is?
2. Please verify that indexDb is indeed available in the environment  by writing and reading a value like - https://github.com/firebase/firebase-js-sdk/blob/713363d3088f8d11ac2a08beaaeca0b4a7a40003/packages/auth/src/platform_browser/persistence/indexed_db.ts#L313

When persistence is set to LOCAL, SDK implementation tries indexDB first if it's available. [Link] (https://github.com/firebase/firebase-js-sdk/blob/713363d3088f8d11ac2a08beaaeca0b4a7a40003/packages/auth-compat/src/auth.ts#LL221C27-L221C27) 

You can also try using modular SDK format https://firebase.google.com/docs/auth/web/custom-dependencies

**Comment by aryaputras** [comment]
I downloaded and installed another version of my firebase.js and firebase-auth.js. this seem to fixed this issue. I think the issue is on my end. therefore, I am closing the ticket

**Comment by conorg000** [comment]
@aryaputras out of curiosity, what version of firebase did you get this working on? I'm using v9.5.0 and `setPersistence` does not seem to work in the Chrome Extension

**Comment by aryaputras** [comment]
I believe it’s 9.23. But you can just try the latest v10. might be a lot
better

**Comment by conorg000** [comment]
Thanks for the quick reply - I'll give it a go!
