### ISSUE TITLE
App Check error when using emulator: "Uncaught (in promise) cancelled"

### ISSUE THREAD

**Issue by thdoan** [firebase/firebase-js-sdk#7358]
### Operating System

Windows 10

### Browser Version

Chrome 114

### Firebase SDK Version

9.22.2

### Firebase SDK Product:

AppCheck, Auth, Functions, Logger

### Describe your project's tooling

No tooling right now.

- `firebase deploy` to deploy to Firebase Hosting
- `firebase emulators:start` to test locally <-- ISSUE

### Describe the problem

My app is working fine on production, but when I tried to run it locally this error was thrown:

![image](https://github.com/firebase/firebase-js-sdk/assets/4110567/ba9fb396-283e-40f8-a2d7-1f900784b1ad)

I traced this error to `proactive-refresh.ts`:

![image](https://github.com/firebase/firebase-js-sdk/assets/4110567/f1e38d2c-ed6a-4e61-8ad4-b28d5f464879)

My setup:

- Node v16.20.0
- Firebase Tools v12.3.1
- App Check via reCAPTCHA v3

### Steps and code to reproduce issue

1. Follow instructions to enable [App Check](https://firebase.google.com/docs/app-check/cloud-functions) using [reCAPTCHA v3 provider](https://firebase.google.com/docs/app-check/web/recaptcha-provider).
2. Run `firebase emulators:start` to start the emulator.
3.  Go to http://127.0.0.1:5000/ and you should see the error in the console.

Relevant code follows...

index.html:

```
<!-- FirebaseUI requires namespaced SDK -->
<script src="https://www.gstatic.com/firebasejs/9.22.2/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.22.2/firebase-app-check-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.22.2/firebase-auth-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.22.2/firebase-functions-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/ui/6.0.2/firebase-ui-auth.js"></script>
```

Client script:

```
// Initialize Firebase
firebase.initializeApp({/* config */});
// Bypass App Check for local testing
self.FIREBASE_APPCHECK_DEBUG_TOKEN = true;
// Initialize App Check (refresh tokens automatically)
firebase.appCheck().activate(/* site key or provider */, true);
```

**Comment by jbalidiong** [comment]
Hi @thdoan, thanks for reaching out. I would like to reproduce this behavior you’re encountering. Would it be okay if you could provide me with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) I can run locally, so I can have a better look into it.

**Comment by thdoan** [comment]
@ jbalidiong thanks for offering to look into this. I'm going this since it's an edge case and I was able to resolve it by setting up the Firebase emulator suite to authenticate locally.
