### ISSUE TITLE
Writing directly after auth.logout() fails [gets queued as the wrong user]

### ISSUE THREAD

**Issue by Nostrus** [firebase/firebase-js-sdk#737]
### Environment

  * Operating System version: MacOS High Sierra, 10.13.4
  * Firebase SDK version: 4.13.1
  * Firebase Product: Firestore
  * Angularfire2 5.0.0-rc.6.0

### Problem
I have a working app and started switching from realtime database to firestore. 
I'm trying the simplest operations, but 90% of the time I don't see my changes in the database, in the rest of the cases the data is properly created, without me changing anything in the codebase. I tried stack tracing with breakpoints, but even when data is not created in the DB, I can see that the new document's path and id is correctly set in local variables. 
I see no console errors, so not sure how to debug this further. Tried reverting Firebase to 4.12.1, but same issue happens.

#### Relevant Code:

```javascript
const userData = this.signupForm.value;

this.authProvider.auth
    .createUserWithEmailAndPassword(userData.email, userData.password)
    .then(response => {

        delete userData.password;
        const uid = response.uid;

        this.authService.logout();

        const museumData = {
            name: userData.museumName,
            isActive: false,
            country: 'hu'
        };

        this.museumService.create(museumData)
            .then(docRef => {

                const museumKey = docRef.id;

                userData.museumKey = museumKey;
                userData.role = 'admin';

                const userKey = this.userService.create(uid, userData)
                    .then(() => {

                        this.isSignupSuccessful = true;
                    });

                this.museumService.addUser(museumKey, uid);

            });

    })
```

` this.museumService.create(museumData)` doesn't return its promise. You can see the related service method below.

```
    constructor (
        private db: AngularFirestore
    ) {
        db.firestore.settings({ timestampsInSnapshots: true });
        this.collection = db.collection<Museum>('museums');
    }

    create(data) {
        return this.collection.add(data);
    }
```

Any tips to debug or feedback is appreciated.

**Comment by mikelehen** [comment]
Hrm...  I think you may be running into an unfortunate interaction between Auth and Firestore.  I think I've seen this before and the issue is essentially that Firestore isn't notified of the logout synchronously and so the write you're doing immediately after logout() is incorrectly getting queue as-if it was performed by the logged-in user. But then the logout takes effect and so Firestore doesn't send the write (because the user is no longer signed-in).

As a workaround you could hook the auth state event and delay your write, something like:

```
var listener = firebase.auth().onAuthStateChanged(function(user) {
  if (!user) {
    // sign out has taken effect. Do your write.

    // unregister listener.
    listener();
  }
```

Or you could perhaps rearrange your code some other way (it's not clear to me why you are logging in and then out directly before doing the write).

Let me know if this helps, and sorry for the inconvenience.

**Comment by Nostrus** [comment]
Thanks for the explanation @mikelehen  :) 
Indeed that was happening, after I moved `this.authService.logout();` to be called last, it started working just fine. Maybe a little documentation about this behavior would be nice at some point if this is the indended behavior for Firestore.

>it's not clear to me why you are logging in and then out directly before doing the write

I want newly signed up users to be inactive, but `createUserWithEmailAndPassword` logs them in by default (I couldn't find an option not to do so), so I have to explicitly log users out, and wanted to do it as soon as possible.

**Comment by mikelehen** [comment]
Ah! Thanks for explaining.

This is not intended behavior and so I'll leave this open. It may be difficult to fix though, so I'm not sure when it will be resolved.  Thanks for the report!

**Comment by hsubox76** [comment]
As part of an issue cleanup effort, we are closing old issues related to versions before 9. The SDK had a large rewrite for version 9 to introduce the modular API, and issues opened under previous versions may no longer apply or may manifest in a different way. If you are still experiencing the same issue with the latest version of the Firebase JS SDK, please open a new issue with as much information as you can provide about how you are currently experiencing it. Thank you!
