### ISSUE TITLE
Title for the bug

### ISSUE THREAD

**Issue by Loscho19** [firebase/firebase-js-sdk#7378]
### Operating System

Mac 12.6.6

### Browser Version

Chrome/Version 114.0.5735.133

### Firebase SDK Version

9.22.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

"@reduxjs/toolkit": "^1.9.5",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/react": "^18.2.13",
    "@types/react-dom": "^18.2.6",
    "bootstrap": "^5.3.0",
    "firebase": "^9.22.2",
    "react": "^18.2.0",
    "react-bootstrap": "^2.7.4",
    "react-dom": "^18.2.0",
    "react-redux": "^8.1.1",
    "react-router-dom": "^6.13.0",
    "react-scripts": "5.0.1",
    "typescript": "^5.1.3",
    "web-vitals": "^3.3.2"

### Describe the problem

I have a problem with Firebase's onAuthStateChanged function. Every time I log in an error is produced. What am I doing wrong?

When i login this error show up

[Chrome Error](https://i.stack.imgur.com/Cyv6x.png)

I've already tried removing dispatch from the deps. Tested on Chrome Browser

EDIT:

Error only appears with "signInWithEmailAndPassword" and "createUserWithEmailAndPassword"

### Steps and code to reproduce issue

```
useEffect(() => {
    const subscriber = onAuthStateChanged(auth, (userdata) => {
      if (userdata) {
        dispatch(
          login({
            uid: userdata.uid,
            displayName: userdata.displayName,
            email: userdata.email,
            phoneNumber: userdata.phoneNumber,
            photoURL: userdata.photoURL,
            providerId: userdata.providerId,
          }),
        );
      } else {
        console.log('Loged Out');
      }
      return subscriber; // unsubscribe on unmount
    });
  }, [dispatch]);
```

**Comment by dwyfrequency** [comment]
Do you have a minimum repo you can link to for replication of the issue?

**Comment by DellaBitta** [comment]
I believe that this error is generally due to an infinite loop.

It looks like `dispatch` is a dependency of the `useEffect` block, which means that `useEffect` will be executed every time `dispatch` changes. In addition`dispatch` is called within the block, which might cause `useEffect` to get called again, and `dispatch` to be invoked again, in a loop. Could that be the problem?
