### ISSUE TITLE
Modify or override messaging notificationclick method

### ISSUE THREAD

**Issue by JoseASolis** [firebase/firebase-js-sdk#739]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.9.1
  * Firebase Product: messaging (auth, database, storage, etc)

### [REQUIRED] Describe the problem
So basicly im using firebase to send push  notifications, but I wanted to register who clicks the notifications and who doesnt, so I searched if theres a way to catch the notification and I found out that i can use the "notificacionclick" on the service worker, so I implemented it , tested it but the listener never triggered, so I dug into the "@firebase" library and there I found that basicly it overrides the notificationclick method, So is there a way to modify it? i tried to modify "node_modules\@firebase\messaging\dist\cjs\src\controllers\sw-controller.js", building it, uploading to the server but it doesnt change when I build it, and the source js is changed. It would be great if you could override it easily , something like "messaging.setonnotificationclicklistener" from angular project .

**Comment by mmermerkaya** [comment]
Currently there is no way of handling clicks of a notification created by the SDK (without using unsupported hacks).

You can display your own notification by using [setBackgroundMessageHandler](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#setBackgroundMessageHandler), and your custom `notificationclick` event handler would get triggered on clicks on that notification.

[Here](https://firebase.google.com/docs/cloud-messaging/js/receive#setting_notification_options_in_the_service_worker) is an example that shows how you can create a notification using `setBackgroundMessageHandler`.

Also remember that your message will be passed to your message handler callback only if it **does not** have a `notification` payload. To do that, you should put all your payload inside `data`.

**Comment by henrylearn2rock** [comment]
@mmermerkaya is it still true that "there is no way of handling clicks of a notification created by the SDK (without using unsupported hacks)" with 5.3.0?

See my Q on: https://stackoverflow.com/questions/51645538/notificationclick-handler-not-being-triggered-by-firebase-sdk-5-3-0
