### ISSUE TITLE
Firebase Rules Unit Testing | Error: Not Implemented

### ISSUE THREAD

**Issue by Psycarlo** [firebase/firebase-js-sdk#7391]
### Operating System

Windows 10 Pro

### Browser Version

Google Chrome 114.0.5735.134

### Firebase SDK Version

^9.17.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Vue SPA with Vite and Vitest

### Describe the problem

When running my unit tests with the firebase emulators I get "Error: Not implemented"

beforeAll(async () => {
  try {
    testEnv = await initializeTestEnvironment({
      projectId: MY_PROJ_ID,
      storage: { rules: readFileSync('storage.rules', 'utf-8') }
    })
  } catch (err) {
    console.log(err)
  }
})

Error: Not Implemented
    at loadStorageRules (.../node_modules/@firebase/rules-unit-testing/src/impl/rules.ts:87:11) 
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Module.initializeTestEnvironment (.../node_modules/@firebase/rules-unit-testing/src/initialize.ts:102:5)

### Steps and code to reproduce issue

Here are the versions:

"firebase": "^9.17.2",
"firebase-tools": "^12.4.0",
"vitest": "^0.32.2",

Script:

"test:unit:ci": "firebase emulators:exec --only auth,firestore,storage --import=./data/test/ \"vitest --dir=tests/unit --watch=false\"

Identical: https://stackoverflow.com/questions/75441714/why-am-i-getting-a-not-implemented-error-when-unit-testing-firebase-security-r

**Comment by Psycarlo** [comment]
@MarkDuckworth Yes, I tried that and still nothing

`storage: { rules: readFileSync('storage.rules', 'utf-8'), host: '127.0.0.1', port: 9199 }`

and the `firebase.json` file:

`
"emulators": {
    ...
    "storage": {
      "port": 9199
    },
    ...
`

Also tried in Github Actions and I get the same error.
The `--debug` flag seems to give nothing relevant.

Pretty sure it is because of the emulators. But how can I doctor this problem?

**Comment by MarkDuckworth** [comment]
@Psycarlo, Can you confirm the output of `firebase -version` matches what is in your package.json `"firebase-tools": "^12.4.0"`?

**Comment by MarkDuckworth** [comment]
@DellaBitta, this issue was mislabeled as "api:firestore". I've attempted to take a look, but it might require some attention from the emulator, rules, or storage team.

**Comment by Psycarlo** [comment]
> @Psycarlo, Can you confirm the output of `firebase -version` matches what is in your package.json `"firebase-tools": "^12.4.0"`?

Yes it does.

**Comment by christhompsongoogle** [comment]
Could this be related to https://github.com/firebase/firebase-tools/issues/5904 ?

**Comment by DellaBitta** [comment]
Hi @Psycarlo, as @christhompsongoogle pointed out it looks like [a fix for a very similar issue](https://github.com/firebase/firebase-tools/pull/6014) was just merged and will be part of our next release (v10). I'm going to close this issue for now, but if v10 does not solve your issue then please open a new ticket and link to this one in the description. Thank you!
