### ISSUE TITLE
sendSignInLinkToEmail() not working w/ tenantId

### ISSUE THREAD

**Issue by kevinmitch14** [firebase/firebase-js-sdk#7395]
### Operating System

MacOS

### Browser Version

Chrome 114

### Firebase SDK Version

9.23.0, 9..20.0, 9.10.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

NextJS application

### Describe the problem

When using `sendSignInLinkToEmail()`, it will not work whenever I set `auth.tenantId`. When I don't set `auth.tenantId`, the emails send with no issues. 

I get the error `auth/operation-not-allowed`. I am using a valid tenantId, and email/password is enabled on the google console configuration for each tenant. There is an example here on the documentation, https://cloud.google.com/identity-platform/docs/multi-tenancy-authentication#email_link. 

There is no issue logging in with email + password and even sending a reset password link works when passing `auth.tenantId`.

Also the email will not send unless I set `handleCodeInApp: true`. This is an optional parameter, so I am not sure exactly why that would be the case.

### Steps and code to reproduce issue

UI
```js
auth.tenantId = "tenantid";
...
<Button
  onClick={async () =>
    await sendSignInLinkToEmail(auth, userConfig.GENERAL.email, {
      handleCodeInApp: true,
      url: "http://localhost:3000",
    })
  }
>
  Email Link
</Button>
```

Network Tab Response
```js
"error": {
    "code": 400,
    "message": "OPERATION_NOT_ALLOWED",
    "errors": [
      {
        "message": "OPERATION_NOT_ALLOWED",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
```

**Comment by DellaBitta** [comment]
Hi @kevinmitch14,

Checking first to see if you have [enabled multi-tenancy in Google Identity Platform](https://cloud.google.com/identity-platform/docs/multi-tenancy-quickstart)? If so, then I recommend that you reach out to [Firebase Support](https://firebase.google.com/support) as this seems like a service error and not an SDK issue. They may of course come back and ping us internally if it's found to be an SDK issue after all, but they have better tools than we do to diagnose this issue at the account level.

Thanks!

**Comment by kevinmitch14** [comment]
Hey @DellaBitta yes, multi tenancy is enabled. I have tried this on another account and the problem persists. Is this functionality working on your end?

**Comment by kevinmitch14** [comment]
All good now

**Comment by DellaBitta** [comment]
Hi @kevinmitch14,

Could you shed any light on what the issue was for future readers? Thanks!

**Comment by kevinmitch14** [comment]
Allow passwordless logins are turned off by default. Tenants don't inherit the configuration from the 'global scope'

**Comment by DellaBitta** [comment]
Great, thanks for following up! Glad the issue is resolved.
