### ISSUE TITLE
Connectivity issues with Firestore after 9.22.0 update

### ISSUE THREAD

**Issue by NinitoAS** [firebase/firebase-js-sdk#7406]
### Operating System

iOS 16 & Windows

### Browser Version

Chrome + Safari (newest)

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

React web app

### Describe the problem

Since 9.22.0 we have experienced major connectivity issues with Firestore. We have two projects, one running 9.21.0 with absolutely 0 issues and another project that is deployed in 500+ locations. Around 5% of these locations are reporting issues related to database connectivity, where Firestore stops listening to the database over time.

These devices are running 24/7 and they are subscribed to the database. We have never had any connectivity issues prior to this update, been running these devices for the last 5 years without any issues.

We recently had to invest in highlight.io to try to debug these issues, we are still trying to figure out what is happening exactly, and still waiting for more bug reports and data.

As these are highly valued clients, we are considering downgrading to 9.21.0 to see if this can solve our issues.

Some of the errors we are seeing, but we are not sure are related: `): WebChannelConnection RPC 'Listen' stream 0x651b58f8 transport errored`

The reason we are posting this issue is to see if anyone else is experiencing these issues in their production env.

### Steps and code to reproduce issue

Upgrade to SDK version 9.22.0 or higher

**Comment by luke-rogers** [comment]
We are also seeing similar errors reported. Makes me wonder if it could be related to this change introduced in 9.22.0

> Enabled long-polling networking mode auto detection by default. It can be explicitly disabled by setting FirestoreSettings.experimentalForceLongPolling to false. See Github PR #7236.

**Comment by cherylEnkidu** [comment]
Hi @NinitoAS and @luke-rogers ,
Could you please try set `FirestoreSettings.experimentalAutoDetectLongPolling` to `false` to explicitly disable long polling?

**Comment by cherylEnkidu** [comment]
Also it would be especially helpful if you could gather logs from https://debug-my.firebaseapp.com/ when you experience this issue. Thanks!

**Comment by tadeumelembe** [comment]
I'm having the same issue using `firebase 9.22`

**Comment by tadeumelembe** [comment]
I'm having the same issue using `firebase 9.22`
