### ISSUE TITLE
iOS HomeScreen Google signInWithPopup errors with auth/network-request-failed if the redirect domain is not *.firebaseapp.com

### ISSUE THREAD

**Issue by HazzMan2409** [firebase/firebase-js-sdk#7443]
### Operating System

iOS 16.5

### Browser Version

Safari (standalone as a HomeScreen web app)

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Preact with Vite

### Describe the problem

Try to signInWithPopup from a custom domain on an iOS HomeScreen web app and it fails with an auth/network-request-failed error.

### Steps and code to reproduce issue

See above.

**Comment by bhparijat** [comment]
Please share a HAR file or a log of network requests and reproducible code snippet
