### ISSUE TITLE
MFA is not available for the given first factor. (auth/unsupported-first-factor) when using email as first factor

### ISSUE THREAD

**Issue by kubacichorski** [firebase/firebase-js-sdk#7455]
### Operating System

macOS 13.4.1 (22F82)

### Browser Version

Firefox 115.0.1 (64 bit)

### Firebase SDK Version

10.0.0 / 9.23.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

NX, WebPack, Firebase, React, TS

### Describe the problem

I'm trying to enroll a new user to MFA with email/password as the first factor. When i complete the reCAPTCHA, `phoneAuthProvider.verifyPhoneNumber(phoneInfoOptions, recaptchaVerifier)` throws an error with this message:
```
{
  "error": {
    "code": 400,
    "message": "UNSUPPORTED_FIRST_FACTOR : MFA is not available for the given first factor.",
    "status": "INVALID_ARGUMENT"
  }
}
```

I did everything according to the documentation and I've tried downgrading firebase version, to no effect.

The docs state `Every provider supports MFA, except phone auth, anonymous auth, and Apple Game Center`. This would mean that the email/password provider should suffice. I am 100% sure that it's on, since it's been the only way to sign in for years.

Would greatly appreciate any help! Thanks!

### Steps and code to reproduce issue

```
const recaptchaVerifier = new RecaptchaVerifier(
  auth,
  're-captcha-verifier',
  {
    size: 'normal',
  },
)
multiFactor(auth.currentUser).getSession()
  .then(session => {
    const phoneInfoOptions = {
      phoneNumber,
      session,
    }
    const phoneAuthProvider = new PhoneAuthProvider(auth)
    return phoneAuthProvider.verifyPhoneNumber(phoneInfoOptions, recaptchaVerifier)
  })
  .then(verId => {
    // this block is never reached
  })
```

**Comment by bhparijat** [comment]
Hi, can you confirm that you have MFA enabled from pantheon console ?

**Comment by kubacichorski** [comment]
@bhparijat Hi, not sure what do you mean by pantheon console, is it [this](https://console.cloud.google.com/marketplace/product/pantheon/pantheon-webops)? If so, we do not use it. But I am 100% sure it's turned on in the Firebase console. In the authentication tab I can see we have two sign-in providers, email+password and phone. Below that, in the advanced section I can see the SMS Multi-factor Authentication has status `Enabled`.

**Comment by prameshj** [comment]
We meant the Google Cloud Console and firebase console. If you see SMS MFA enabed in the firebase console, then it should be enabled.


Do you already have email/password users that have enrolled in MFA in order to be prompted during sign in?

Can you share an HAR file for a user login (you can setup a test user + password combination for this purpose) where you get the error?

**Comment by prameshj** [comment]
Also, note that MFA is not supported for custom authentication either.
