### ISSUE TITLE
Firebase/auth's fetchSigninMethodsForEmail function error

### ISSUE THREAD

**Issue by nanashi-03** [firebase/firebase-js-sdk#7460]
### Operating System

Linux x86_64

### Browser Version

Mozilla/5.0

### Firebase SDK Version

10.0.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Nextjs app with firebase and firebase-admin

### Describe the problem

Calling fetchSigninMethodsForEmail function, I am receiving an error 400 bad request.
```
FirebaseError: Firebase: Error (auth/missing-identifier).
    FirebaseError index.esm2017.js:949
    create index.esm2017.js:977
    createErrorInternal index-59cc561a.js:497
    _fail index-59cc561a.js:468
    _performFetchWithErrorHandling index-59cc561a.js:911
    _performApiRequest index-59cc561a.js:849
    createAuthUri index-59cc561a.js:5664
    fetchSignInMethodsForEmail index-59cc561a.js:5706
    loginWithGithub login.tsx:101
    promise callback*loginWithGithub login.tsx:98
    onClick login.tsx:214
    React 23
    renderReactElement index.js:390
    doRender index.js:537
    render index.js:551
    hydrate index.js:679
    async* next-dev.js:48
    promise callback* next-dev.js:42
    NextJS 7
client.js:1:909
```

### Steps and code to reproduce issue

I am running this code with one account per email option turned on in firebase. If I turn that off and remove this piece of code, everything is working as intended. 
```js
if (error.code === 'auth/account-exists-with-different-credential') {
	let email = error.email;
	fetchSignInMethodsForEmail(auth, email).then((result) => {
		console.log(result);
	}).catch((error) => {
		console.error(error);
	})
}
```

**Comment by bhparijat** [comment]
Hi,  can you confirm that email is not undefined or null here when this error is thrown.

**Comment by nanashi-03** [comment]
Ah, it was undefined but I'm not sure why that is happening either because without the one account per email setting, the login works just fine.
