### ISSUE TITLE
Out of memory (OOM) warning when loading app with persistence enabled 

### ISSUE THREAD

**Issue by michaelAtCoalesce** [firebase/firebase-js-sdk#7462]
### Operating System

Mac OS x

### Browser Version

Version 114.0.5735.198 (Official Build) (arm64) Automatically update Chrome for all users Learn more

### Firebase SDK Version

9.22.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

create react app with yarn 

### Describe the problem

when loading one of the pages of our app that is data intensive with firestore local persistence enabled, when the debugger is open we are seeing a warning about potential OOM. 

<img width="1262" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/96628583/703ca702-b263-4087-8588-71add0c4823f">

upon resuming execution, the app does continue to work, but it is concerning that chrome is saying that it's about to run out of memory. 

### Steps and code to reproduce issue

this occurs in our application when a lot of data is being handled, which makes it somewhat difficult to create a separate reproducible test case. 

im happy to jump on a call and try out binaries as needed.

**Comment by ehsannas** [comment]
Thanks for reporting @michaelAtCoalesce. 

When persistence is enabled, the Firestore Web SDK should keep most things on disk, and only load necessary pieces of information into the memory. Note that if you make a query, the entire result set is loaded into memory completely. So, if your application is making queries with a large result set, it could use a lot of memory.

**Comment by dconeybe** [comment]
Could this be a symptom of https://github.com/firebase/firebase-js-sdk/issues/6118?

**Comment by ehsannas** [comment]
This issue occurs on Chrome, whereas #6118 seems to be a Safari-only issue (web-channel uses a large amount of memory on Safari).

**Comment by dconeybe** [comment]
> This issue occurs on Chrome, whereas #6118 seems to be a Safari-only issue (web-channel uses a large amount of memory on Safari).

True, although the fact that the customer only experiences the issue on mobile Safari could be a red herring. The investigation in b/242550738 (Googlers only, sorry) seems to be converging on a non-Safari-specific root cause. It's something to keep an eye on anyways.

**Comment by ehsannas** [comment]
Oh, interesting. I wasn't aware of b/242550738. I'll keep following the investigation there.

**Comment by dconeybe** [comment]
FYI for anyone experiencing this (or a similar issue), it possibly has the same root cause as https://github.com/firebase/firebase-js-sdk/issues/6118. So follow that issue and see if its resolution (once it is resolved) helps your situation.
