### ISSUE TITLE
Service worker is registered twice

### ISSUE THREAD

**Issue by nojaf** [firebase/firebase-js-sdk#7481]
### Operating System

Windows 11

### Browser Version

Chrome/114

### Firebase SDK Version

10.0.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Plain ES6 with importmap (getting Firebase from https://esm.sh)

```html
<script type="importmap">
    {
        "imports": {
            "fable-library/": "https://esm.sh/fable-library@1.1.1/",
            "react": "https://esm.sh/react@18.2.0",
            "react-dom": "https://esm.sh/react-dom@18.2.0",
            "usehooks-ts": "https://esm.sh/usehooks-ts@2.9.1?exports=useCopyToClipboard,useMediaQuery",
            "firebase": "https://esm.sh/firebase@10.0.0",
            "firebase/app": "https://esm.sh/firebase@10.0.0/app",
            "firebase/auth": "https://esm.sh/firebase@10.0.0/auth",
            "firebase/firestore": "https://esm.sh/firebase@10.0.0/firestore",
            "firebase/storage": "https://esm.sh/firebase@10.0.0/storage",
            "firebase/functions": "https://esm.sh/firebase@10.0.0/functions",
            "firebase/messaging": "https://esm.sh/firebase@10.0.0/messaging",
            "react-firehooks/auth": "https://esm.sh/react-firehooks@2.5.0/auth",
            "react-firehooks/firestore": "https://esm.sh/react-firehooks@2.5.0/firestore",
            "@iconify/react": "https://esm.sh/@iconify/react@4.1.1",
            "react-router-dom": "https://esm.sh/react-router-dom@6.14.1",
            "use-sync-external-store/shim": "https://esm.sh/use-sync-external-store@1.2.0/shim",
            "react-map-gl": "https://esm.sh/react-map-gl@7.1.1",
            "react-use": "https://esm.sh/react-use@17.4.0?exports=useGeolocation",
            "react-webcam": "https://esm.sh/react-webcam@7.1.1"
        }
    }
</script>
```

### Describe the problem

My service worker is being registered twice for some reason:

![image](https://github.com/firebase/firebase-js-sdk/assets/2621499/53086f8b-715d-4628-a756-b89264ef7247)

I'm registering the service worker myself (with `{ "type": "module" }`) using:
```
export function registerServiceWorker() {
    const matchValue = navigator.serviceWorker;
    if (matchValue != null) {
        const serviceWorker = matchValue;
        const options = { "type": "module" };
        return serviceWorker.register("/firebase-messaging-sw.js", options);
    }
    else {
        return Promise.reject(new Error("Service worker not available"));
    }
}

export function getFcmToken() {
    return PromiseBuilder__Run_212F1D4B(promise, PromiseBuilder__Delay_62FBFDE1(promise, () => (messaging_1().then((_arg) => {
        const messaging = _arg;
        return registerServiceWorker().then((_arg_1) => {
            const registration = _arg_1;
            return getToken(messaging, {
                serviceWorkerRegistration: registration,
                vapidKey: "...",
            });
        });
    }))));
}
```

but when I open another SPA route (where my messaging code isn't even used), I get the 

`Uncaught SyntaxError: Cannot use import statement outside a module (at firebase-messaging-sw.js:1:1)`

message.

This makes sense as my actual `firebase-messaging-sw.js` looks like:

```js
import {initializeApp} from "https://esm.sh/firebase@10.0.0/app";
import { getMessaging, onBackgroundMessage } from 'https://esm.sh/firebase@10.0.0/messaging/sw';

const firebaseConfig = { ...};

const app = initializeApp(firebaseConfig);

// Retrieve firebase messaging
const messaging = getMessaging(app);

function onMessage(payload) {
  console.log('Received background message ', payload);
  const { locationId, locationName, userName } = payload.data;

  const notificationTitle = "";
  const notificationOptions = {
  };

  return self.registration.showNotification(notificationTitle, notificationOptions);
}

onBackgroundMessage(messaging, onMessage);
```

I'm using `import` syntax there, so my SW needs `type: "module"` to work. 

### Steps and code to reproduce issue

- Use `import` syntax in your service worker.
- Manually register the service worker with `{ "type": "module" }`
- Invoke `getToken` with that registered worker.

I'm not quite sure how to draw out the actual problem.
But some other firebase code is registering the worker again without the options.

I had in my file:

```
import { addDoc, Timestamp, collection, getDocs } from "firebase/firestore";
import { uploadBytes, ref } from "firebase/storage";
import { useAuthIdTokenResult, useAuthState } from "react-firehooks/auth";
```

and that shows the behaviour. But I do not get why.

**Comment by nojaf** [comment]
Ok, I've done some digging and I think I know where this is coming from.
I can reliably reproduce the problem the moment I start executing a `httpsCallable` from `"firebase/functions"`.

I'm able to patch my browser to always use `"type": "module"` when the service worker is registered:
```html
<script>
    const originalRegister = navigator.serviceWorker.register;
    navigator.serviceWorker.register = function (scriptURL, options) {
      console.trace();
      options.type = "module";
      return originalRegister.call(navigator.serviceWorker, scriptURL, options);
    };
</script>
```

The trace showed my that:

![image](https://github.com/firebase/firebase-js-sdk/assets/2621499/36c24fc7-da34-4549-ae7b-16ebc3cfb20c)

Where `getUsers` is invoking `httpsCallable`.

**Comment by nojaf** [comment]
Hi @jbalidiong, Thanks for looking into this.
I'm off on vacation now, I might eventually come back to this and try and extract a sample from my codebase.

The race condition theory is quite likely the problem.

**Comment by luisgurmendez** [comment]
@jbalidiong  Following this guide from firebase docs https://firebase.google.com/docs/cloud-messaging/flutter/receive#web for flutter at least. It says we should manually register the sw. I expect under the hood the package for flutter is using this library, so is this documentation wrong?

**Comment by themightychris** [comment]
It appears that `flutter-messaging-sw.js` gets loaded by the framework when you're debugging but doesn't when you build for release

**Comment by nojaf** [comment]
Yeah, sorry for never reporting a proper sample that reproduces the issue.
Long story short, I changed my code to not register the script myself.

**Comment by hsubox76** [comment]
I'm going to close this for lack of a repro from the original user - if anyone else has this problem and can provide a repro, please feel free to open a new issue.
