### ISSUE TITLE
Inconsistent Realtime Database documentation

### ISSUE THREAD

**Issue by IvoBiaus** [firebase/firebase-js-sdk#7482]
### Operating System

Microsoft Windows 11 Home Version 10.0.22621 Build 22621

### Browser Version

Chrome 115.0.5790.99 ( Official Build) (64 bits)

### Firebase SDK Version

10.0.0

### Firebase SDK Product:

Database

### Describe your project's tooling

React on Javscript

### Describe the problem

I'm trying to create a query to the "Realtime Database" at Firebase by doing:

```js
// ...
const queryRef = query(ref(database, 'users'), orderByChild("something"), equalTo(true));
// ...
onValue(queryRef, snapshot => {
    setLoading(true);
    const data = snapshot.val();
    setData(data);
    setLoading(false);
});
```

But when running the code I'm getting an error that breaks the site:
(From file: `@firebase/database/dist/index.esm2017.js`)
`Uncaught Error: Query: When ordering by priority, the first argument passed to startAt(), startAfter() endAt(), endBefore(), or equalTo() must be a valid priority value (null, a number, or a string).`

Which basically tells me that I'm not supposed to use a `boolean` in the `equalTo` parameter. But this is false if you look at the real code and the data types taken by the `equalTo` function:

(From file: `@firebase/database/dist/public.d.ts`)
`equalTo(value: string | number | boolean | null, key?: string | undefined): QueryConstraint`

### Steps and code to reproduce issue

Code was provided at the "Describe the problem" section.

**Comment by maneesht** [comment]
Hi, @IvoBiaus, this error appears when you are ordering a query by priority, but shouldn't trigger if you're ordering by child. Is there a place where you're ordering by priority?

**Comment by IvoBiaus** [comment]
Hey @maneesht , thanks for the reply. Mmm, no i dont think so. The whole code related to this query is this:

```js
  useEffect(() => {
    // Unsubscribe from previous
    unsubRef.current();

    let queryRef;
    switch (filterType) {
      case ORG_KEY:
        queryRef = orgId && query(ref(database, 'users'), orderByChild(orgId), equalTo(true));

        break;
      case DIV_KEY:
        queryRef =
          filterDivId && query(ref(database, 'users'), orderByChild(filterDivId), equalTo(true));

        break;
      case USER_KEY:
        queryRef = filterUid && ref(database, `users/${filterUid}`);
        break;

      default:
        break;
    }

    if (queryRef) {
      // "OnValue" returns the unsubscribe function.
      unsubRef.current = onValue(queryRef, snapshot => {
        setLoadingPositions(true);
        const data = snapshot.val();
        setPositionsByUser(data);
        setLoadingPositions(false);
      });
    }

    // When un-mounted, unsubscribe.
    return unsubRef.current;
  }, [filterType, orgId, filterDivId, filterUid]);
```

If i remember correctly, when i first started writing this code it would run ok, and one day it just started doing it. I tried cleaning every cache i found to shake the error off but not luck.
And - I forgot to update the Issue later but, one day i asked a coworker to try the code at their machine and it works fine, so its just mine that gets it, so its probably not a real error in the lib, sorry :/ , its prob some magic in my cache.

**Comment by maneesht** [comment]
Thanks for the update. I'll go ahead and close this, but feel free to comment if it needs to be reopened.
