### ISSUE TITLE
Can not access named database

### ISSUE THREAD

**Issue by aronsuarez** [firebase/firebase-js-sdk#7491]
### Operating System

web

### Browser Version

Chrome  114.0.5735.198 (Official Build) (arm64)

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Vue App with vite

### Describe the problem

I want to try the new named database feature of firestore but when i try to access a named database from the client i get always an FirebaseError: Missing or insufficient permissions. error.

When I switch back to (default) database everything works fine. 

Here my security rules:

```
rules_version = '2';
service cloud.firestore {
	match /databases/{database}/documents {
    
    match /admin/{elementId} {
    	allow read, write: if database == 'test-db'
    }
    
    match /admin2/{elementId} {
    	allow read, write: if database == '(default)'
    }
  
    //
    // Users
    //
    match /users/{userId} {
    	allow get, write: if true
    }
  }
}
```

### Steps and code to reproduce issue

When I init the Firestore instance like this: 

`const firestore = getFirestore('test-db')`

It's not working, if I do that:

`const firestore = getFirestore()`

It works

**Comment by tom-andersen** [comment]
Each named database and default have separate rules.

Please go to following page and verify the security rules for you database.

https://pantheon.corp.google.com/firestore/databases

You can use the Firebase CLI to deploy rules. During the public preview, there is no Console support for editing rules. See:

https://firebase.google.com/docs/rules/manage-deploy

For example, after running `firebase init firestore`, edit:

named.rules
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}

```

firebase.json
```
{
  firestore: [  
    {
      "database": "test-db",
      "rules": "named.rules",
    },
    {
      "database": "test-db-1",
      "rules": "named.rules",
    },
    {
      "database": "test-db-2",
      "rules": "named.rules",
    },
  ]
}
```

Then run, `firebase deploy --only firestore`.

**Comment by aronsuarez** [comment]
Hello tom-andersen

Thank you very much for your reply, now the things are clear. 

One question, how can I access this link: https://pantheon.corp.google.com/firestore/databases I don't have a @google.com address ;-)

**Comment by tom-andersen** [comment]
Oops! Sorry, that should have been: https://console.cloud.google.com/firestore/databases

(I edited my original response to reflect this)

**Comment by aronsuarez** [comment]
Thank's for the link, but I get 404 with this link.

<img width="1941" alt="Screenshot 2023-07-24 at 18 45 01" src="https://github.com/firebase/firebase-js-sdk/assets/10696903/dbf4018f-9686-447e-a93f-19916a5a0a79">

**Comment by tom-andersen** [comment]
Hmm... I need to verify, but you might need to be on the Blaze plan instead of Spark. Do you know which plan you are on?

**Comment by aronsuarez** [comment]
I'm on the Blaze plan with all of my projects.

**Comment by tom-andersen** [comment]
Sorry ... I have learned that page isn't launched yet. 😢 

You will need to use the CLI for now:

https://cloud.google.com/firestore/docs/manage-databases#create_a_database

**Comment by aronsuarez** [comment]
I thought that is the case, by the way, i have tested the connection, it works perfect.

Great job with that feature, thank you!!
