### ISSUE TITLE
TypeError: Cannot read property 'getElementsByTagName' of undefined

### ISSUE THREAD

**Issue by pandam77** [firebase/firebase-js-sdk#7517]
### Operating System

iOS 16.0.2

### Browser Version

n/a

### Firebase SDK Version

10.10.0

### Firebase SDK Product:

Analytics

### Describe your project's tooling

React app

### Describe the problem

I get a warning when using getAnalytics().
> WARN Possible Unhandled Promise Rejection (id: 0):
> TypeError: Cannot read property 'getElementsByTagName' of undefined

I get an error when using logEvent().
> WARN Promise Rejection Handled (id: 0)
> This means you can ignore any previous messages of the form "Possible Unhandled Promise Rejection (id: 0):"
> ERROR [] @firebase/analytics: [TypeError: Cannot read property 'getElementsByTagName' of undefined]

### Steps and code to reproduce issue

import {initializeApp} from "firebase/app";
import {getAnalytics, logEvent} from "firebase/analytics";

const firebaseConfig = {
// your firebase config
};

const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);

logEvent(analytics, 'test_logEvent');

**Comment by dwyfrequency** [comment]
I created a new react project and I was not able to reproduce this error. Could you provide a repo where you have this error message?
