### ISSUE TITLE
Firestore depends on @grpc/proto-loader 0.6.13 that still depends on vulnerable version of protobufjs < 7.2.4

### ISSUE THREAD

**Issue by Arsnj** [firebase/firebase-js-sdk#7524]
### Operating System

WIndows

### Browser Version

Chrome/114.0

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Angular app with Webpack.

### Describe the problem

protobufjs  6.10.0 - 7.2.3
Severity: high
protobufjs Prototype Pollution vulnerability - https://github.com/advisories/GHSA-h755-8qp9-cq85
fix available via `npm audit fix --force`
Will install firebase@8.6.8, which is a breaking change
node_modules/protobufjs
  @grpc/proto-loader  0.6.0-pre1 - 0.6.13
  Depends on vulnerable versions of protobufjs
  node_modules/@grpc/proto-loader

Grpc have already fixed their security issue. Could you update this package as well, please?

### Steps and code to reproduce issue

npm audit fix.

**Comment by Djeisen642** [comment]
https://github.com/firebase/firebase-js-sdk/issues/7484
