### ISSUE TITLE
Firebase Incorrect Password Error After Account Verification in Next.js App

### ISSUE THREAD

**Issue by jkr86** [firebase/firebase-js-sdk#7528]
### Operating System

iOS 12.6.7

### Browser Version

Version 115.0.5790.170 (Official Build) (x86_64)

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Nextjs 13.0.5 pages directory + Firebase

### Describe the problem

I'm working on Firebase authentication within my Next.js app. After a user signs up using email and password, I require account verification during their initial login. However, after account verification, an issue arises on the second login attempt after signing out. Firebase throws an "incorrect password" error, despite the account being verified.

Interestingly, when I manually reset the password via the Google console, I can successfully log in with the new password. I'm puzzled by this behavior. Any insights into why Firebase is presenting this error post-verification would be greatly appreciated.

I tried to verify my account which is what I successfully did but I'm unable to log in after verifying my account if I log out and try to log in again. Got an incorrect password error.

### Steps and code to reproduce issue

1: Signup successfully
2: Login successfully 
3: Verify account 
4: log out after successfully verifying the account
5: then try to log in again it will throw firebase password incorrect error

Here is my login code:

```
data: {
        "returnSecureToken": true,
        "email": "junaid223@yopmail.com",
        "password": "Test123!@#",
        "clientType": "CLIENT_TYPE_WEB"
       }
```
```
const onSubmit = async (data) => {
   try {
        signInWithEmailAndPassword(auth, data?.email, data?.password)
          .then(async (res) => {
            if (res?.user?.uid) {
              //create profile
            }
          })
          .catch (error) {
        // Handle error here
        toast.error("Login failed. Please check your email and password.");
      } catch (error) {
        // Handle error here
        toast.error("Login failed. Please check your email and password.");
        console.error(error);
      }
    }
```
```
    "error": {
        "code": 400,
        "message": "INVALID_PASSWORD",
        "errors": [
            {
                "message": "INVALID_PASSWORD",
                "domain": "global",
                "reason": "invalid"
            }
        ]
    }
```

**Comment by epark10** [comment]
Bump, also having this issue

**Comment by jbalidiong** [comment]
Hi @jkr86, thanks for bringing this to our attention. I tried replicating, but I wasn't able to reproduce the error. Would it be okay if you could provide me with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that I can run locally, so I can have a better look into it.
