### ISSUE TITLE
Repetitive RPC transport error

### ISSUE THREAD

**Issue by DaltonPelkey** [firebase/firebase-js-sdk#7547]
### Operating System

iOS 17

### Browser Version

Expo Go

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React Native -- Expo managed workflow using Firebase Web SDK

### Describe the problem

Initializing `onSnapshot` eventually fires the warning:
`Firestore (10.1.0): WebChannelConnection RPC 'Listen' stream ... transport errored`

### Steps and code to reproduce issue

1. Setup a React Native project for Expo's managed workflow
2. Include and initialize firebase/firestore
3. Set up an `onSnapshot` listener (mine is set up in a root component)
4. Close the app and wait ~10 minutes (Although I have gotten the error randomly while the app was open but not being used)

[Here](https://gist.github.com/DaltonPelkey/470741e83b354a567d9c8ad04af24d81) is a Gist containing a response from `setLogLevel('debug')` and from debug-my.firebaseapp.com

**Comment by dconeybe** [comment]
Thank you for the report and the logs. The log lines "detected buffering proxy" indicate that Firestore detected a network condition that required that it fall back to "long-polling" mode. It appears that you are aware of this, and attached the logs from https://debug-my.firebaseapp.com/, which show that long-polling is _not_ required.

This _may_ be a case where Firestore has _incorrectly_ determined that long-polling is needed. Could you try setting `FirestoreSettings.experimentalAutoDetectLongPolling` to `false` and reproducing?

Also, other than the warning, are you seeing any other effects of this warning? For example, is the snapshot listener still working? Firestore is written to be robust in the presence of networking issues so I'd expect the snapshot listener to continue to work.
