### ISSUE TITLE
It looks like the index.d.ts under compat folder is missing a lot of methods and has wrong signatures

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7555]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

latest

### Firebase SDK Product:

Auth

### Describe your project's tooling

index.html with source tag.

### Describe the problem

The index.d.ts file under _firebase-js-sdk-master/packages/firebase/compat/_ seems to be missing a bunch of methods...for example I can't find the [deleteApp](https://firebase.google.com/docs/reference/js/app.md#deleteapp) method. There is no [getApps](https://firebase.google.com/docs/reference/js/app.md#getapps) method either. There is the [initializeApp](https://firebase.google.com/docs/reference/js/app.md#initializeapp) method, but the signature in the file is `function initializeApp(options: Object, name?: string): firebase.app.App;`, whereas in the docs it's `export declare function initializeApp(): FirebaseApp;`. Is this file outdated or something? Is there an index.d.ts that matches the API description from the docs?

### Steps and code to reproduce issue

Just look at the file.

**Comment by jbalidiong** [comment]
Hi @marcusx2, thanks for reaching out to us. For compat documents you should use our [Javascript - compat (namespaced) version](https://firebase.google.com/docs/reference/js/v8/firebase.app.App) and not the modular version of the SDK. Here are some of the links for the methods you are looking for:

- [delete](https://firebase.google.com/docs/reference/js/v8/firebase.app.App#delete)
- [apps](https://firebase.google.com/docs/reference/js/v8/firebase#apps)
- [initializeApp](https://firebase.google.com/docs/reference/js/v8/firebase#initializeapp)

I'll be closing this issue now. If you encounter another issue, feel free to create a new one.

**Comment by marcusx2** [comment]
Hello @jbalidiong , thanks for answering. So, is there not a file of the modular version with all the definitions like the namespaced version?

**Comment by jbalidiong** [comment]
Hi @marcusx2, the closest document I can find the overview of [Javascript modular version](https://firebase.google.com/docs/reference/js). This document list all the modular packages for the JS SDK. However, you have to go to each packages to see the methods under it.

**Comment by hsubox76** [comment]
All the modular typings are defined in the source code, and separate d.ts files generated from each source code file. There is no single file. What do you need this for? If you want to consult it for reference docs, all our reference docs are available at the link @jbalidiong provided above. If you need it for typings to use at runtime, any typescript system should be able to follow the package.json typings path to reference the various d.ts files.
