### ISSUE TITLE
FirebaseError: Installations: Generate Auth Token request failed with error "403 PERMISSION_DENIED"

### ISSUE THREAD

**Issue by cgilbe27** [firebase/firebase-js-sdk#7566]
### Operating System

Windows 10

### Browser Version

Chrome/Version 115.0.5790.171

### Firebase SDK Version

9.0.0 -> 10.1.0

### Firebase SDK Product:

Analytics

### Describe your project's tooling

Create react app

App is hosted with firebase

### Describe the problem

Getting the following error on load in console, it doesn't happen between page navigation

Interestingly enough, events are still tracked with `logEvent`

common.ts:53 Uncaught (in promise) FirebaseError: Installations: Generate Auth Token request failed with error "403 PERMISSION_DENIED: The request is missing a valid API key." (installations/request-failed).
    at getErrorFromResponse (common.ts:53:1)
    at async generateAuthTokenRequest (generate-auth-token-request.ts:75:1)
    at async fetchAuthTokenFromServer (refresh-auth-token.ts:142:1)
    at async refreshAuthToken (refresh-auth-token.ts:72:1)
    at async refreshAuthToken (refresh-auth-token.ts:72:1)
    at async getToken (get-token.ts:40:1)

![image](https://github.com/firebase/firebase-js-sdk/assets/14813436/169ef268-342e-4f70-979a-bfad9822f8a0)

### Steps and code to reproduce issue

```
// Import the functions you need from the SDKs you need
import { getAnalytics } from "firebase/analytics"
import { initializeApp } from "firebase/app"
// Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// All info filled out correctly, stubbed values here

const firebaseConfig = {
  apiKey: "A",
  authDomain: "n",
  projectId: "n",
  storageBucket: "n",
  messagingSenderId: "4",
  appId: "1:",
  measurementId: "G-",
}

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig)
export const analytics = getAnalytics(firebaseApp)
```

**Comment by hsubox76** [comment]
I've tried a number of ways to reproduce this and the only case that caused this specific error was when the `apiKey` didn't match the `appId`. Is there any chance that you modified the apiKey separately from the appId or vice versa, especially after initially running the app with some other combo in the past?

**Comment by cgilbe27** [comment]
> I've tried a number of ways to reproduce this and the only case that caused this specific error was when the `apiKey` didn't match the `appId`. Is there any chance that you modified the apiKey separately from the appId or vice versa, especially after initially running the app with some other combo in the past?

I'm using the configuration directly from 

https://console.firebase.google.com/u/2/project/XXX/settings/general/XXX

**Comment by hsubox76** [comment]
Sorry, I don't mean changing it during the run of the app, I mean, did you run this app last week, and change to a new project sometime after? It stores the token you originally got in indexedDB in your browser.

Can you clear your indexedDB cache in your browser and try again? If you don't know how to clear your indexedDB cache, you can just clear all browser data. If you want to try clearing just the indexedDB cache, here's the entry you want to clear:
![Screenshot 2023-08-17 at 12 58 35 PM](https://github.com/firebase/firebase-js-sdk/assets/10716545/fb1bea2c-e58f-4a67-b9db-c2bee6a8d53b)

If that doesn't help, you might want to contact [Firebase Support](https://firebase.google.com/support), where you can privately provide your API config values and try to figure out what's going on with your exact project.

**Comment by cgilbe27** [comment]
> Sorry, I don't mean changing it during the run of the app, I mean, did you run this app last week, and change to a new project sometime after? It stores the token you originally got in indexedDB in your browser.
> 
> Can you clear your indexedDB cache in your browser and try again? If you don't know how to clear your indexedDB cache, you can just clear all browser data. If you want to try clearing just the indexedDB cache, here's the entry you want to clear: ![Screenshot 2023-08-17 at 12 58 35 PM](https://user-images.githubusercontent.com/10716545/261423505-fb1bea2c-e58f-4a67-b9db-c2bee6a8d53b.png)
> 
> If that doesn't help, you might want to contact [Firebase Support](https://firebase.google.com/support), where you can privately provide your API config values and try to figure out what's going on with your exact project.

This error popped up on us about 2-4 weeks ago, I looked back through commit history, we haven't touched these files in months

I cleared the indexedDB as well as cleared site data, did not work, error still appears

**Comment by hsubox76** [comment]
Since I can't reproduce this in my own project, I'm not sure I can go any further without your exact project config, which I'm sure you don't want to provide publicly, so can you run this through Firebase Support as linked above? If they're able to reproduce or pin down the cause to a bug in the SDK, you can report back here.
