### ISSUE TITLE
onLog from firebase-app not working

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7577]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

index.html with source tag.

### Describe the problem

If the code raises an exception on _initializeApp_ , the error is **not** caught on _onLog_. See the example HTML on the next  section.

### Steps and code to reproduce issue

```
<!DOCTYPE html>
<html lang='en'>
<head>
	<title>Basic HTML5 document</title>
	<meta charset='utf-8'>
</head>
<body>
	<!-- Insert this script at the bottom of the HTML, but before you use any Firebase services -->
	<script type="module">
	        import { initializeApp} from 'https://www.gstatic.com/firebasejs/10.1.0/firebase-app.js'
           
        
                const firebaseConfig = {
                  //config
		        };
        
                setLogLevel("verbose");
                onLog(LogCallbackParams => {
	                console.log("error here");//never runs
	                console.log(LogCallbackParams));
                });
        
                // Initialize Firebase
                try {
	                const app = initializeApp();//didn't provide config, get error
                } catch(e) {
	                console.error(e);
	                console.error("catched error with try catch");//error is catched here, but not _onLog_
                }
		
	</script>
</body>
</html>
```

**Comment by hsubox76** [comment]
Unfortunately it's a thrown error and not a logged error, and the Firebase logger is only called to explicitly log error messages, equivalent to calling `console.error`. It's usually used when we want to surface an error, but we don't want to throw. We don't have a mechanism to intercept and catch thrown errors in general. You should use catch (as you're doing here) to intercept thrown errors and log them as you like.

**Comment by marcusx2** [comment]
@sam-gc @hsubox76 quick question but unrelated...regarding the `onAuthStateChanged` method, when does the `complete` or `error` trigger if I use an `Observer` instead of a `NextFn`? I didn't find anything documented anywhere about using the `Observer` here, even in the source code. The unit tests seem to cover only the `NextFn` case. I had opened another [issue here](https://github.com/firebase/firebase-js-sdk/issues/6254), and I am aware that the `error` and `complete` parameters are deprecated, but I am talking about the `error` and `complete` from the `Observer` parameter. Since the method uses a [NextOrObserver](https://firebase.google.com/docs/reference/js/auth.md#nextorobserver) type I thought the `Observer` itself isn't deprecated, but since I can't find anything...is the `Observer` deprecated as well and it's really just `NextFn`? If not, when does the `complete` and `error` from the `Observer` trigger?

Example code

```
const unsub = onAuthStateChanged(auth,
	{
		complete: () => console.log("complete"),//never triggers...what is 'complete'?
		error: error => console.error(error),//never triggers...what errors does this catch?
		next: user => {//this triggers normally...
			if (user) {
			console.log(user.providerId);
			// ...
				} else {
			// User is signed out
			// ...
				}
		}
	});
```

If the `Observer` is also deprecated, I think the docs should be updated as well to reflect that and just leave `NextFn`. @sam-gc on his last comment in the locked issue seems to indicate that errors indeed never trigger in the `onAuthStateChanged`, even in the `Observer`, though I could be wrong...

If you want to, can you move this question to this [locked issue](https://github.com/firebase/firebase-js-sdk/issues/6254)? I think it belongs there..

Thanks!
