### ISSUE TITLE
npm install firebase fails

### ISSUE THREAD

**Issue by aseutin** [firebase/firebase-js-sdk#759]
* Operating System version: Mac OSX 10.13.4
  * Firebase SDK version: NA
  * Firebase Product: all

node version 10.0
npm version 5.6.0

I have tried everything but 'npm install firebase' is still failing. Here is the log:

[log.txt](https://github.com/firebase/firebase-js-sdk/files/1966140/log.txt)

**Comment by aseutin** [comment]
Whoops sorry about that. Here is the actual log file:

[log.txt](https://github.com/firebase/firebase-js-sdk/files/1971793/log.txt)

The main problem is that it is failing due to a syntax error during installation:

CXX(target) Release/obj.target/grpc/deps/grpc/src/core/plugin_registry/grpc_plugin_registry.o
  LIBTOOL-STATIC Release/libgrpc.a
  File "./gyp-mac-tool", line 607
    return {k: self._ExpandVariables(data[k], substitutions) for k in data}
                                                               ^
SyntaxError: invalid syntax

**Comment by jshcrowthe** [comment]
Looks like the issue is a `grpc` compile error on your machine. You would probably be better served filing this here: https://github.com/grpc/grpc-node
