### ISSUE TITLE
initializeAuth throws error if no deps object is passed in.

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7619]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

index.html with source tag.

### Describe the problem

[initializeAuth](https://firebase.google.com/docs/reference/js/auth.md#initializeauth) method's documentation indicates that the `deps` argument is optional, however if you don't use it, a `Firebase: Error (auth/argument-error).` error is thrown.

### Steps and code to reproduce issue

Call the method without the deps argument

`const auth = initializeAuth(app);`

**Comment by NhienLam** [comment]
Hi @marcusx2, thanks for reaching out to us. 
I wasn't able to repro the issue. I didn't see the auth/argument-error when doing `initializeAuth(app)`. The `deps` argument is marked as optional in the code - https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/core/auth/initialize.ts#L53.

Could you provide more information or code samples to help repro the issue?

**Comment by marcusx2** [comment]
Hm...I can't replicate the problem now. Weird. I am sure this was happening. I'll let you know if I come across this again.

**Comment by NhienLam** [comment]
Ok, thanks. I'm going to close this issue for now. Feel free to re-open it if you come across this again. Thanks!
