### ISSUE TITLE
Google auth error: auth/web-storage-unsupported

### ISSUE THREAD

**Issue by zob360** [firebase/firebase-js-sdk#7620]
### Operating System

any

### Browser Version

any

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.js

### Describe the problem

Google auth with redirect flow triggers sometimes this error: Error: (auth/web-storage-unsupported)

It seems that some users have block the web storage feature.

### Steps and code to reproduce issue

User sign-in google auth then error triggered: auth/web-storage-unsupported

```
Step1: signInWithRedirect
 const googleAuth = new GoogleAuthProvider();
      await signInWithRedirect(auth, googleAuth);
      
Step2: get results of redirect
   const handleRedirectLogin = async () => {
      try {
        const {user} = await getRedirectResult(auth);
        const idToken = await user.getIdToken();
      } catch (e) {
        if (e?.code === "auth/web-storage-unsupported") {
          alert(
            "Web Storage is not supported in your browser. Please enable it or try a different browser."
          );
        }
      }
    };
```

**Comment by zob360** [comment]
Is there get around this error?: auth/web-storage-unsupported

Thanks

**Comment by DellaBitta** [comment]
Hi @zob360,

There's an article [Best practices for using signInWithRedirect on browsers that block third-party storage access](https://firebase.google.com/docs/auth/web/redirect-best-practices) which may help. Could you work through it to see if solves your issue. If not, could you descirbe in more detail which of the hosting scenarios (listed on that page) that you're using?

Thanks!
