### ISSUE TITLE
https://fcmregistrations.googleapis.com/v1/projects/{project_id}/registrations gives 401

### ISSUE THREAD

**Issue by Deeptrentium** [firebase/firebase-js-sdk#7623]
### Operating System

windows 11

### Browser Version

chrome/116

### Firebase SDK Version

10.3.1

### Firebase SDK Product:

Messaging

### Describe your project's tooling

its just a normal expo project where I want push notification

### Describe the problem

when i call getToken I got 401 in  https://fcmregistrations.googleapis.com/v1/projects/{project_id}/registrations

![image](https://github.com/firebase/firebase-js-sdk/assets/85158218/31f1f2fa-1edb-494b-be82-a2e646529ba5)

### Steps and code to reproduce issue

simple calling getToken API

**Comment by jbalidiong** [comment]
Hi @Deeptrentium, thanks for reaching out to us. I tried replicating, but I wasn't able to reproduce the error. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by Deeptrentium** [comment]
@jbalidiong here is the sample project https://github.com/Deeptrentium/firebase-cloud-messaging where I face the issue run this project on web and click on notification button 

let me know if you want more information

**Comment by hsubox76** [comment]
@Deeptrentium As mentioned above, the Firebase JS SDK doesn't support Cloud Messaging in React Native. I've described your options in the comment above, and I'm sorry we can't provide any better ones.
