### ISSUE TITLE
Invalid response from checkActionCode for RECOVER_EMAIL

### ISSUE THREAD

**Issue by motzyball** [firebase/firebase-js-sdk#7628]
### Operating System

All

### Browser Version

All

### Firebase SDK Version

11.10.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

Irrelevant, this seems like an API issue.

### Describe the problem

`checkActionCode` doesn't return the recovery email

### Steps and code to reproduce issue

1. Start with an account with this setup:
    - Google provider for `a@gmail.com`
    - Password provider for `a@gmail.com`
2. Generate an email change request to `b@gmail.com` with the Admin SDK's `generateVerifyAndChangeEmailLink` method
3. Apply the OOB code for the email change with the client SDK's `applyActionCode` method
4. This should work fine. If you search for `a@gmail.com` in the Firebase console, the account for `b@email.com` will show up, with the Google and password providers
5. Click on the OOB recovery link sent to `a@gmail.com`
6. Pass the OOB code into `checkActionCode`. You'll get a response that doesn't reflect the email being recovered to:
```
    data: {
        email: "b@gmail.com";
        previousEmail: "b@gmail.com";
    };
```

**Comment by motzyball** [comment]
I believe I found the problem, `checkActionCode` on the `RECOVER_EMAIL` OOB code is returning the current email address in both email fields, e.g.:
```
    data: {
        email: "b@gmail.com";
        previousEmail: "b@gmail.com";
    };
```

**Comment by motzyball** [comment]
I wonder if this is some kind of race or sticky state; I tested the same flow with the same email address pair on Sep 6 without issue.

**Comment by DellaBitta** [comment]
Hi @motzyball,

This behavior is driven by the Firebase Console / Backend, but this repo is for the Web Client SDK. I'd recommend that you [open a Firebase Support ticket](https://firebase.google.com/support/troubleshooter/contact) so our support engineers can see what's going-on with your account in the backend. Thanks!
