### ISSUE TITLE
Users not receiving reset password emails

### ISSUE THREAD

**Issue by 0xori** [firebase/firebase-js-sdk#7654]
### Operating System

macOS Monterey v 12.6.2

### Browser Version

Chrome Version 117.0.5938.88

### Firebase SDK Version

8.3.2

### Firebase SDK Product:

Analytics, Auth, Database, Firestore, Functions, Remote-Config, Storage

### Describe your project's tooling

React app made with create-react-app installer

### Describe the problem

Users not receiving reset password emails.
tried from js and got a successful response: 
`
{
    "kind": "identitytoolkit#GetOobConfirmationCodeResponse",
    "email": "********@gmail.com"
}
`
tried also from admin ui and problem persist.
tried with different email addresses and non of them got the email message, also not in spam folder.

### Steps and code to reproduce issue

send a reset password link via app or admin ui

**Comment by jbalidiong** [comment]
Hi @0xori, thanks for reaching out. I tried replicating and I wasn't able to reproduce the same behavior. I noticed that you are using an outdated SDK version,  I verified that it's working fine for the latest version of the SDK. Would you mind trying to the update the SDK version that you're using and see if the issue persists?

**Comment by 0xori** [comment]
@jbalidiong thanks! it's working.

**Comment by jbalidiong** [comment]
I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
