### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by marck283** [firebase/firebase-js-sdk#7660]
### Operating System

Windows 11

### Browser Version

Google Chrome 117.0.5938.132

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Auth, Firestore, Functions, Storage

### Describe your project's tooling

Node.js web application using Firebase tools to authenticate the user.

### Describe the problem

Upgrading node-fetch to version 3.0.0 prompts a  _MaxListenersExceededWarning: Possible EventEmitter memory leak detected_ warning when a project depends on packages that depend on a version of node-fetch prior to 3.2.5. NPM's version of firebase-tools, firebase/auth, firebase/auth-compat, firebase/firestore, firebase/functions and firebase/storage all use version 2.6.7 of the package node-fetch or depend on packages that use a version of node-fetch prior to 3.2.5, which are known to be vulnerable to this MaxListenersExceededWarning. As stated [here](https://github.com/node-fetch/node-fetch/issues/1295), upgrading to node-fetch@3.2.5 or later should solve the issue.

Further information on the problem can be found [here](https://github.com/node-fetch/node-fetch/issues/1295).

### Steps and code to reproduce issue

Upgrade Node.js to version 20.7.0 while having some packages depending on node-fetch prior to version 3.2.5.

**Comment by marck283** [comment]
As a side-note, node-fetch's versions up to 3.2.10 also suffer from Regular Expression Denial of Service (as can be seen [here](https://security.snyk.io/package/npm/node-fetch)), making node-fetch@3.2.10 the earliest non-vulnerable version of that package.

**Comment by hsubox76** [comment]
Thanks for the detailed info. We already have it on our list to upgrade to node-fetch 3+ in response to a previous issue: https://github.com/firebase/firebase-js-sdk/issues/7280 but we can increase the priority of this.

**Comment by marck283** [comment]
Thank you for answering! Just in case, I have also left a comment on the PR #7359 associated to the issue #7280 which describes the proposed solution for the issues reported here.

**Comment by marck283** [comment]
Since the commit that solves this issue is now merged into the master branch, I will now close this issue.
