### ISSUE TITLE
FirestoreDataConverter example doesn't work.

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7671]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.4.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

This [example](https://firebase.google.com/docs/reference/js/firestore_.firestoredataconverter#example) does not work at all. The thrown error is `TypeError: collection(db,'posts').withConverter(postConverter).doc is not a function. (In 'collection(db,'posts').withConverter(postConverter).doc()', 'collection(db,'posts').withConverter(postConverter).doc' is undefined`.

The example is probably from the v8 version of the library. Can someone provide the v9 version of the example here until the docs get patched?

### Steps and code to reproduce issue

```
class Post {
    constructor(title, author) { }

    toString() {
        return this.title + ', by ' + this.author;
    }
}

const postConverter = {
    toFirestore(post) {
        return { title: post.title, author: post.author };
    },
    fromFirestore(
        snapshot,
        options
    ) {
       const data = snapshot.data(options);
       return new Post(data.title, data.author);
    }
};

const db = getFirestore();
const postSnap = await collection(db,'posts').withConverter(postConverter).doc().get();

const post = postSnap.data();
if (post !== undefined) {
    post.title; // string
    post.toString(); // Should be defined
    post.someNonExistentProperty; // TS error
}
```

**Comment by marcusx2** [comment]
I tried modifying the code with the following

```
const col = await collection(db, 'posts').withConverter(postConverter);
const queryDocumentSnapshot = (await getDocs(col)).docs[0];
const doc = queryDocumentSnapshot.get(new FieldPath(queryDocumentSnapshot._key.path.segments));//undefined
console.log(queryDocumentSnapshot.data());//empty post
```


but apparently it's still wrong because I can't retrieve the document. This is what I have
<img width="1280" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/5656275/da2c666b-9162-4892-a126-9aff008bfd59">

**Comment by dconeybe** [comment]
@marcusx2 Thank you for pointing out this obvious issue with the documentation. I have opened a PR that re-writes the sample code. If you have some time, please take a look and let me know what you think. I added a "simple" converter and a "complex" converter sample: https://github.com/firebase/firebase-js-sdk/pull/7673

**Comment by marcusx2** [comment]
Looks good to me! I hope it gets merged sooner rather than later.
