### ISSUE TITLE
Getting json parse error while installing latest firebase js sdk

### ISSUE THREAD

**Issue by palakgandhi10** [firebase/firebase-js-sdk#768]
Hi, I'm installing firebase in my ionic application.

Below is the error that i'm facing.

OS: Windows 10
Node: v8.10.0
NPM: v6.0.0

>npm i firebase --save
npm ERR! Unexpected end of JSON input while parsing near '...0.1.2-canary.a538b83"'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Maven8\AppData\Roaming\npm-cache\_logs\2018-05-03T12_45_21_140Z-debug.log

Log File: 
[2018-05-03T12_45_21_140Z-debug.log](https://github.com/firebase/firebase-js-sdk/files/1970915/2018-05-03T12_45_21_140Z-debug.log)

**Comment by mmermerkaya** [comment]
Can you delete your `node_modules` directory, run `npm cache clean --force` and try again? Sounds like a package wasn't downloaded properly.

**Comment by TeamInnovations** [comment]
Try clearing the npm cache and update it back again before re-install firebase tools.

1. npm cache clean --force
2. npm install -g @angular/cli@latest
3. npm install -g firebase-tools

follow the steps.
