### ISSUE TITLE
Web SDK attempts to connect to localhost even if emulator is not connected

### ISSUE THREAD

**Issue by anicolao** [firebase/firebase-js-sdk#7681]
### Operating System

MacOS 13.5.2 (22G91)

### Browser Version

Chrome 117.0.5938.132 (Official Build) (arm64) 

### Firebase SDK Version

^9.9.3

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Svelte app built with vite

### Describe the problem

When I call `setDoc` I expect it to hit my production database unless I have connected the emulator. However, it tries to post against `127.0.0.1:8080` instead. It presents similarly to this bug https://github.com/firebase/firebase-js-sdk/issues/6993 though it is not exactly the same, but enabling `experimentalForceLongPolling` does fix it so that it hits the real server. So my workaround is:
```
firestore: initializeFirestore(app, {
    experimentalForceLongPolling: true,
  }),
```
as the method to access firestore instead of calling `getFirestore()` which ought to work the same.

### Steps and code to reproduce issue

Create a basic svelte app and try to initialize firestore and write a doc with `setDoc`. If needed I can produce a barebones repo that show the issue.

**Comment by cherylEnkidu** [comment]
Hi,

Please try to upgrade to the latest SDK version to see if it fixes the problem. If not, could you please provide minimum reproduce code for the team to investigate further?

**Comment by anicolao** [comment]
I can confirm that when I install `^10.4.0` the problem still reproduces. I will make a github repo to clone and test with over the weekend.
