### ISSUE TITLE
 Error on OEM Android 6 running Chrome 44.0.2403.117

### ISSUE THREAD

**Issue by JonasWater** [firebase/firebase-js-sdk#7684]
### Operating System

MacOS Android Emulator

### Browser Version

Chrome 44.0.2403.117

### Firebase SDK Version

10.4.0

### Firebase SDK Product:

Auth

### Tech
Nuxt.js

### Conf
package.json
    "firebase": "^10.4.0",

nuxt.config.js
    build: { transpile: [/^firebase/, '@firebase', 'firebase'] }

### Describe the problem

Using nuxt.js combined with "firebase": "^10.4.0" will result in an error in Chrome44: **Uncaught SyntaxError: Unexpected token =>**

![PROBLEM](https://github.com/firebase/firebase-js-sdk/assets/118031233/b360d86f-9916-4a3d-8390-c0e561df863e)

### Steps and code to reproduce issue

Using nuxt.js combined with "firebase": "^10.4.0" will result in an error in Chrome44: **Uncaught SyntaxError: Unexpected token =>**

**Comment by hsubox76** [comment]
@jbalidiong Were you able to repro this?

@JonasWater Does this only cause issues in Chrome on the Android emulator, or can we reproduce this error in regular Chrome on Mac or some other more easily accessible environment?

**Comment by JonasWater** [comment]
@hsubox76 

Thank you for your reply.
This error will occur only in the lower versions of Chrome, such as 44.xx.xxx or 50.xx.xxx.
You can use the Android emulator to repeat the above error

**Comment by JonasWater** [comment]
Hi~

Everybody can help me to solve this issue?

@hsubox76

**Comment by hsubox76** [comment]
Does this work outside of the Android emulator? I don't really have the Android emulator set up on my machine and I'm not easily able to install an older Chrome version. Has anyone else been able to reproduce this? If not, I'll try to get to this when I can but the amount of time that it will take to get this repro working may mean it will have to wait until I can find a time slot for it.

**Comment by JonasWater** [comment]
The key of the issue is not the virtual machine, but that this plugin(firebase-js-sdk) does not support Chrome around version 44 or 53.
Can you make this plug-in support older versions of Chrome browsers(such as Chrome44、Chrome50)?

@hsubox76

**Comment by JonasWater** [comment]
Hi~ Somebody can solve this issue?

@hsubox76
