### ISSUE TITLE
export 'FirebaseError' (reexported as 'FirebaseError') was not found in '@firebase/util' (possible exports: default)

### ISSUE THREAD

**Issue by hienphan0111** [firebase/firebase-js-sdk#7700]
### Operating System

Windown 11

### Browser Version

Version 118.0.5993.70 (Official Build) (64-bit)

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Nextjs 13.5

### Describe the problem

I just install and config firebase package for receive notification in my nextjs app. But it got an issue and crash my app.
This is description of bug:
./node_modules/@firebase/app/dist/esm/index.esm2017.js
export 'FirebaseError' (reexported as 'FirebaseError') was not found in '@firebase/util' (possible exports: default)        

Import trace for requested module:
./node_modules/@firebase/app/dist/esm/index.esm2017.js        
./node_modules/firebase/app/dist/index.mjs
./utils/firebase.ts
./components/notification/Notification.tsx

### Steps and code to reproduce issue

import { initializeApp, getApps } from 'firebase/app';

import { getMessaging, getToken, onMessage } from 'firebase/messaging';

// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  firesbaseConfigInfo
};

// Initialize Firebase

let firebaseApp = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0];

**Comment by hsubox76** [comment]
Is this a new install or an upgrade from a previous version of Firebase? If it's an upgrade, can you try cleaning out `node_modules` and removing `yarn.lock` or `package-lock.json` and reinstalling (yarn/npm)?

**Comment by hienphan0111** [comment]
@hsubox76 This is new install, I have tried remove node module, clean cache, yarn.lock and reinstall, but it still got that error.

**Comment by hsubox76** [comment]
Here's what I did to try to reproduce this:

```
npx create-next-app next-app-2
cd next-app-2
npm install firebase@10.5.0
```

Then I added the lines of code you provided into `page.tsx`, plus a `console.log(firebaseApp)` to make sure it's not tree-shaken out.

Then

```
npm run dev
```

And I opened the page and it seems fine. Can you provide a change to these steps that will reproduce the error?

**Comment by girishneosoft** [comment]
same issue facing
