### ISSUE TITLE
TotpMultiFactorGenerator not included in React Native bundle

### ISSUE THREAD

**Issue by RichMeeson** [firebase/firebase-js-sdk#7701]
### Operating System

Mac OS 13.3

### Browser Version

Chrome 118.0.5993.70

### Firebase SDK Version

10.4.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React Native app, metro

### Describe the problem

When attempting to configure our app to work with the TOTP authentication flow, we discovered that `TotpMultiFactorGenerator` was not exported in the React Native bundle. We had previously used this in our web app with the same version of the SDK.

We've found a work around by taking the code we needed from the bundle used on the web and adding it as a patch to `@firebase/auth/dist/rn/index-1dd41d18.js` using patch-package though obviously this isn't ideal as I imagine this would break upon updating the package.

### Steps and code to reproduce issue

Install Firebase SDK in a React Native app and attempt to import TotpMultiFactorGenerator.

**Comment by jbalidiong** [comment]
Hi @RichMeeson, thanks for reaching out to us and apologies for the delay. I was able to replicate the behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.
