### ISSUE TITLE
emailVerified property is set to false even for trusted providers like Google login

### ISSUE THREAD

**Issue by jayhomn** [firebase/firebase-js-sdk#7702]
### Operating System

Windows 11

### Browser Version

Edge 118.0.2088.46

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.js app hosted on Vercel

### Describe the problem

According to the firebase documentation, logging in through a trusted provider such as Google will result in the emailVerified field to be set to true. This appears to be the case when running my webapp locally and using the Auth Emulator when logging in through signInWithPopup. However, when we do the same when accessing the site hosted on Vercel, the emailVerfied field appears to be false.

### Steps and code to reproduce issue

```js
const signInWithGoogle = async () => {
    const provider = new GoogleAuthProvider();
    try {
      setInitializing(true);
      const creds = await signInWithPopup(auth, provider);
      console.log(creds); // <-- the emailVerified prop in the credentials returned is false
    } catch (error) {
      setInitializing(false);
      return Promise.reject("Error signing in with Google: " + error);
    }
  };
```

**Comment by DellaBitta** [comment]
Hi @jayhomn,

Unfortunatley I wasn't able to reproduce this when using Vercel. Could you provide more information about your app (Next.JS version, etc)?

Also, did you happen to add the Vercel URL for your App to the Firebase Authorized Domains? This setting is in the Firebase Console > Auth > Settings > Auth Domains.

Thanks!

**Comment by DellaBitta** [comment]
Hi @jayhomn,

We'll need more information since I wasn't able to reproduce this with a frest app in Vercel. Is there any chance that you could setup a fresh Vercel project that exhibits the behavior and share it (minus the FirebaseConfig & personal data, of course).

Thanks!
