### ISSUE TITLE
isEqual doesn't work on arrayUnion, arrayRemove, and increment

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7706]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

isEqual doesn't work on arrayUnion, arrayRemove, and increment. They always return false, even when they are equal.

### Steps and code to reproduce issue

```
console.log(arrayUnion().isEqual(arrayUnion()));//return false
console.log(arrayRemove().isEqual(arrayRemove()));//return false
console.log(increment().isEqual(increment()));//return false
```

**Comment by MarkDuckworth** [comment]
Thanks for reporting this. I investigated and found some old TODOs in the code for these isEqual methods. I've opened a new internal feature request to get this implemented.

Internal tracking b/306399547
