### ISSUE TITLE
@firebase/firestore: Firestore (10.5.0): FIRESTORE (10.5.0) INTERNAL ASSERTION FAILED: Unexpected state

### ISSUE THREAD

**Issue by brianmhunt** [firebase/firebase-js-sdk#7717]
### [REQUIRED] Environment info

**firebase-tools:** 12.7.0

**Platform:**. Codespace/Ubuntu.

### [REQUIRED] Test case

Unable to reproduce, sorry.  Error emits from mutation:624 in `serverTransformResults`, specifically:

```ts
hardAssert(
    fieldTransforms.length === serverTransformResults.length,
    `server transform result count (${serverTransformResults.length}) ` +
      `should match field transform count (${fieldTransforms.length})`
  );
```

<img width="977" alt="CleanShot 2023-10-19 at 13 10 45@2x" src="https://github.com/firebase/firebase-tools/assets/135528/d9995551-6406-4c74-aa53-1624a09019a8">

The stack trace does not show where this occurs.

### [REQUIRED] Steps to reproduce

In our app when using the emulator this is occurring infrequently but regularly.  It is a complex and we cannot easily narrow the trigger point.

It did not occur with 9.x.

### [REQUIRED] Expected behavior

Firestore actions should perform

### [REQUIRED] Actual behavior

Noted error.

Related: firebase/firebase-tools#1073

All we seem to see in the `firestore-debug.log` is:

```
Oct 19, 2023 5:11:27 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Oct 19, 2023 5:12:13 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Oct 19, 2023 5:12:28 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Oct 19, 2023 5:13:13 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Oct 19, 2023 5:13:28 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
```

I appreciate this may be difficult to reproduce but I wanted to at least note it for visibility and discovery.  If we get more info we will share.

Thank you!

**Comment by tom-andersen** [comment]
Could you enable debug logging?
https://firebase.google.com/docs/reference/js/firestore_#setloglevel
https://firebase.google.com/docs/reference/node/firebase.firestore#setloglevel

The code seems to indicate that the Emulator is returning an unexpected result. Meaning, the root cause might exist in the emulator, and not the SDK. Some more information will help clarify that.

What version of the emulator are you using?

Some context might also be helpful. The error is related to data that is being written to Firestore. What type of write operations are you performing? Are these update, set or delete operations?

**Comment by brianmhunt** [comment]
I would also note that we routinely see a case where `doc.get` fails:

> await firestore.doc(fkp).get()

... simply never finishes.  Reloading the browser is the only way to fix it, but it routinely comes back, and this is a catastrophic problem for a single page app.

**Comment by brianmhunt** [comment]
Linking related [firebase-tools/6432](https://github.com/firebase/firebase-tools/issues/6432).

Also: we can reproduce and fixed this.  It was related to a `doc.get()` being called for the same document many times in succession from different parts of our codebase.

We would expect that Firestore would queue these requests. We resolved it by adding a singleton/cache for the request.

**Comment by tom-andersen** [comment]
The bug was introduced in 10.4.0. We are reverting the change and working on a long term fix.

> I would also note that we routinely see a case where `doc.get` fails:
> 
> > await firestore.doc(fkp).get()
> 
> ... simply never finishes. Reloading the browser is the only way to fix it, but it routinely comes back, and this is a catastrophic problem for a single page app.

**Comment by tom-andersen** [comment]
Sorry, seeing the current version isn't trivial.

> Also: how can we tell what version of the emulator we are using?

What I really want to make sure is that you are running an up to date emulator.

If starting emulator with `gcloud` CLI, you can run:

`gcloud components update`

If start emulator with `firebase` CLI, you can run:

`firebase setup:emulators:firestore`

**Comment by tom-andersen** [comment]
> We enabled `setLogLevel` from `firebase/app` but it does nothing. We're using `firebase/app/compat` everywhere else and there doesn't seem to be a `setLogLevel` equivalent for `compat`. Is there?

`firebase/firestore-compat` is wrapping code found in `firebase/firestore`. Ideally you should migrate away from using compat if possible. However, you still need to use the `setLogLevel` from within `firebase/firestore` to enable logging for Firestore, even if you are using `compat`.

**Comment by brianmhunt** [comment]
Thanks for the great info @tom-andersen .  We ought to be using a recent emulator because we routinely reinstall from a docker image for testing.

Is there anything actionable on this now? If we experience it again we can re-open, or we can leave it open and I will follow-up as we try new versions.

**Comment by MarkDuckworth** [comment]
> I would also note that we routinely see a case where doc.get fails ... simply never finishes.

I don't think this hanging `doc.get` call is related to the original issue reported, but I'd like to state that v10.5.2 released a fix for hanging queries.

**Comment by tom-andersen** [comment]
@brianmhunt Yes, please let us know if you experience this again.

We need more context or debug info to make progress on this.
