### ISSUE TITLE
Firestore (10.5.0): WebChannelConnection RPC 

### ISSUE THREAD

**Issue by ayobamiseun** [firebase/firebase-js-sdk#7725]
### Operating System

ios 10

### Browser Version

chrome

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React App vite

### Describe the problem

i was trying to submit a sign up information

### Steps and code to reproduce issue

`  const userCredential = await createUserWithEmailAndPassword(
        auth,
        formData.email,
        formData.password
      );
      updateProfile(auth.currentUser, {
        username: formData.username,
        displayName: formData.fullName,
      }); 
      const user = userCredential.user
      const formDataCopy = {...updatedFormData}
      delete formDataCopy.password  
      formDataCopy.timestamp = serverTimestamp();
      await setDoc(doc(db, "users", user.uid), formDataCopy)`

**Comment by tom-andersen** [comment]
Hi @ayobamiseun!

I have a sneaky suspicion I can guess your error. But I rather not jump to any conclusion.

Could you describe the problematic behaviour?

Any logs or other information you can provide will also be helpful.

Thanks!
