### ISSUE TITLE
Firebase sendEmailVerification error (too many requests)Title for the bug

### ISSUE THREAD

**Issue by ang9009** [firebase/firebase-js-sdk#7733]
### Operating System

macOS Monterey 12.4

### Browser Version

Chrome/118.0.5993.117

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

React app

### Describe the problem

Hi, I recently added a "resend email" button on my email verification page which uses the sendEmailVerification function, and I noticed that I got the error "Firebase: Error (auth/too-many-requests)". It seems like this is triggered when you click the resend button too frequently (running the function sendEmailVerification), but I couldn't find any documentation regarding what this frequency exactly is, only [this page](https://firebase.google.com/docs/auth/limits) that tells me how many email verification links can be generated per day with the free tier. I would like to implement a delay that disables the button to prevent the error from showing up.

I'm also worried about what this will mean if multiple users attempt to sign up at the same time, especially with the same IP, since I'm sending email verification every time an account is created. Does this mean that some sign up attempts will be blocked due to this error? If so, how can I circumvent this? Please let me know, thanks.

### Steps and code to reproduce issue

I have a button that runs the following function:

```
  function sendEmail() {
    sendEmailVerification(userData)
      .then(() => {
        toast.success("Email sent!", {
          autoClose: 2000,
        });

        setError("");
      })
      .catch((error) => setError(error.message));
  }
```

If it is run too frequently, it will trigger the aforementioned error.

**Comment by pragatimodi** [comment]
Hi, thanks for reporting this issue. 
To further assist you, it may be necessary for you to submit a Firebase support ticket so that we can examine the details of your project. 
In the meantime, could you please share with us the number of times the button was clicked to trigger sendEmailVerification?

**Comment by ang9009** [comment]
Hello, thank you for your reply. I clicked it twice in succession, which triggered the error. I will open a Firebase suport ticket as per your suggestion.

**Comment by DellaBitta** [comment]
Ok, thanks. I'll keep this bug open for now. Let us know what Firebase Support says. Thanks!
