### ISSUE TITLE
heartbeatService.ts: cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by malk90** [firebase/firebase-js-sdk#7736]
### Operating System

Windows >=10

### Browser Version

Opera 102.0.0

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Analytics, Auth, Messaging, Performance

### Describe your project's tooling

React app with webpack, cordova, typescript

### Describe the problem

Opera users have repeated errors from time to time, most of all in version 102, but it started with 101

In file /node_modules/@firebase/app/src/heartbeatService.ts line 132 error 
Cannot read properties of undefined (reading 'length')

`this._heartbeatsCache.heartbeats.length === 0`

### Steps and code to reproduce issue

https://github.com/firebase/firebase-js-sdk/blob/12ad9f1818f141163e126839ece81e39e9404a60/packages/app/src/heartbeatService.ts#L132

**Comment by DellaBitta** [comment]
Hi @malk90,

I wasn't able to reproduce this with my own test app. Could you provide a reproducible test app or the code that causes this behavior? Thanks!

**Comment by malk90** [comment]
hi, no, unfortunately I can’t help with the code, but if you look at the code, you’ll immediately see the error

**Comment by DellaBitta** [comment]
Hi @malk90,

We still couldn't reproduce this issue, unfortunately. However, we just shipped 10.6.0 which includes some better checks around the state of the HeartBeat object that _should_ avoid the error that you're seeing. Could you please give the new release a test?

If you still encounter issues then could you post a minimum reproducible test case so we can better attempt to reproduce the probelm ourselves? Thanks!

**Comment by DellaBitta** [comment]
Hi @malk90,

We've put some more protections in the upcoming release of 10.7.0 which should be released soon. I'll post here when it's out. Thanks!

**Comment by DellaBitta** [comment]
Hi @malk90,

v10.7.0 was released on Monday. Can you check to see if this clears up your issue? Thanks.

**Comment by DellaBitta** [comment]
I'm going to close this issue since we released a change to address this issue and we haven't heard if it's still affecting your app after an upgrade. If you find that the issue persists at a later time, please create a new GitHub issue and link to this one. Thank you!
