### ISSUE TITLE
Issue on Mac os and Ios devices: evaluating 'o.fbase_key'

### ISSUE THREAD

**Issue by praveenfsdev** [firebase/firebase-js-sdk#7737]
### Operating System

iOS 14, 15, 16, 17 and Mac OS X 10.15

### Browser Version

Safari, Mobile Safari and Chrome Mobile ios.

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Auth, Database

### Describe your project's tooling

React with typescript.

### Describe the problem

Here is the error message which I was receiving from Bugsnag(Error tracking tool).
![Screenshot from 2023-10-30 13-30-38](https://github.com/firebase/firebase-js-sdk/assets/149364485/9eb2fc3a-1905-4082-aba0-1ce7e4b7e2fc)

This error is not occurring always when I load the app. But this is happening often( around 5 times a day) for an users.

### Steps and code to reproduce issue

There is no dedicated steps to reproduce. This is reproducing some times when an app is loading on ios and Mac os browsers.

**Comment by pragatimodi** [comment]
Hi, thanks for reporting this issue. 
Can you share more details about how frequently you see this error and if there's a specific event flow that triggers it?

**Comment by praveenfsdev** [comment]
@pragatimodi The frequency rate is 5 - 6 times a day as I have mentioned in the description and this issue happening when an app gets loading.
**Note:** This error is not occurring every time on load. It is happening randomly.

**Comment by DellaBitta** [comment]
Hi @praveenfsdev,

This is a standard operation that occurs during the initialization of Firebase Auth. A few follow up questions if you don't mind:

- 5-6 times a day out of how many page loads?
- Is it failing in certain environments and not others?
- Can you provide more information about the browser that the user is running?
- Does it throw an error every time the user attempts to use the Web App, or only some of the times?
- Do you have a stack trace for the error?

Thanks!

**Comment by praveenfsdev** [comment]
Hi @DellaBitta , Sure here are the details:

- The average page load will be around 1000. 
- Yes as mentioned in the description, it is happening only on 2OS. one is Mac OS and the second is iOS. 
- I have already attached the browsers in the description.(Safari, Mobile Safari and Chrome Mobile ios)
- It is not happening every time, it is only happening randomly.
- Here is the stack trace of the error.
`TypeError undefined is not an object (evaluating 'o.fbase_key') 
    src/platform_browser/persistence/indexed_db.ts:372:17 
    build/static/node_modules/regenerator-runtime/runtime.js:63:44 tryCatch
    build/static/node_modules/regenerator-runtime/runtime.js:294:30 
    build/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:24 asyncGeneratorStep
    build/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:27 _next`

**Comment by praveenfsdev** [comment]
@DellaBitta still we are getting this error at the same rate. Any update on this?

**Comment by DellaBitta** [comment]
Hi @praveenfsdev,

I've just merged a change that should be part of the next release and it  should prevent this error from occuring. I'll update this GitHub issue again when the release is out so that you may test it.

**Comment by DellaBitta** [comment]
Hi @praveenfsdev,

Firebase JS SDK v10.7.1 has been released. Can you give it a try for this error scenario? Thanks!
