### ISSUE TITLE
Firestore doc + setDoc performs CREATE+UPDATE vs addDoc is just CREATE.

### ISSUE THREAD

**Issue by adamcw** [firebase/firebase-js-sdk#7739]
### Operating System

Ubuntu

### Browser Version

Version 117.0.5938.132 (Official Build) (64-bit)

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Webpack + Firebase.

### Describe the problem

The documentation tells me:

> Behind the scenes, .add(...) and .doc().set(...) are completely equivalent, so you can use whichever is more convenient.
> https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document

From my testing, this doesn't appear to be true. Using the v9 equivalents `addDoc`, and `doc`/`setDoc`, the former makes a single `CREATE` request, while the latter creates a redundant `UPDATE` as well as `CREATE` request.

The documentation fails to really explain what a `write` is, but I'm assuming **this will double write costs** with the latter approach.

### Steps and code to reproduce issue

This does `CREATE` only.

```
data = {id: "some_id", name: "name"};
commentRef = await addDoc(collection(chapRef, "comments"), data);
```

This does `CREATE` + `UPDATE`.

```
const commentRef = doc(collection(chapRef, "comments"));
data = {id: commentRef.id, name: "name"};
await setDoc(commentRef, data);
```

Now, this doesn't look equivalent, because the latter is using `commentRef.id`, so to make the first option match, I would need to do an `UPDATE`.

_However, the whole reason I'm trying to use `setDoc` is to avoid needing the `UPDATE`._ 

Looking at the emulator, the `CREATE` already has the `id`, so the `UPDATE` is entirely redundant and contains the exact same `request.resource` making it appear to be entirely pointless and a waste of a `write`.

Removing the dependency on `commentRef.id` still reproduces the issue.

```
const commentRef = doc(collection(chapRef, "comments"));
data = {id: "blah", name: "name"};
await setDoc(commentRef, data);
```

Commenting out `setDoc` results in neither `CREATE` nor `UPDATE` from being called.

**setDoc queries:**

**CREATE: request.resource from emulator**

```
__name__
/databases/(default)/documents/content/PQhOz6btA8ne7iT9QiO2/chapters/Jsi6LS54H4l9wIEQYMkk/comments/hgwfWq94KYE5mYF7ADnz
(path)
arrow_drop_down
data
(map)
name
"name"
(string)
id
"hgwfWq94KYE5mYF7ADnz"
(string)
```

**UPDATE: request.resource from emulator**

```
__name__
/databases/(default)/documents/content/PQhOz6btA8ne7iT9QiO2/chapters/Jsi6LS54H4l9wIEQYMkk/comments/hgwfWq94KYE5mYF7ADnz
(path)
arrow_drop_down
data
(map)
name
"name"
(string)
id
"hgwfWq94KYE5mYF7ADnz"
(string)
```

**Comment by tom-andersen** [comment]
Thank you for the information. I am going to verify the behavior.

**Comment by tom-andersen** [comment]
The `CREATE: request.resource from emulator` and `UPDATE: request.resource from emulator` appear to be related to Firestore Rules. Validation of rules is not the same as an actual request, though rules validation my cause read requests if the rule requires access to existing document values.

How are you observing the CREATE + UPDATE writes?

**Comment by tom-andersen** [comment]
There doesn't appear to be duplicate requests sent. The only difference is that `add` has precondition that `exists` must be false. I think this has more to do with the Emulator implementation, and doesn't necessarily represent CREATE + UPDATE in production. I will followup that maintainers of Emulator and production environment.
