### ISSUE TITLE
Firebase memory leak when building production version of small ionic app

### ISSUE THREAD

**Issue by CKunhardt** [firebase/firebase-js-sdk#774]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home Version: 1709 OS Build: 16299.371
  * Firebase SDK version: 4.13.1
  * Firebase Product: database + auth

#### Steps to reproduce:

The app works fine when served locally through `ionic serve`, and when build for development with just `ionic build`. However, when I run `ionic build --prod`, the process exits with `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`.

When I downgrade to firebase@4.12.1, the issue is resolved. This is new as of 4.13.1, apparently, and is an issue with the Firebase code, hence me not posting in Ionic's repo. I can also confirm that someone else is having this issue. See: [Link](https://forum.ionicframework.com/t/memory-leak-when-generate-a-production-version-of-small-app/129077/4).

I am content to use Firebase 4.12.1 for now. Just wanted to let you all know that 4.13.1 has this major bug!

#### Relevant Code:

I have started a small app with Ionic CLI 3, using the Firebase NPM package and not much else. I'm calling several Firebase functions from my FirebaseProvider:

From Auth:
`createUserWithEmailAndPassword()`
`signInWithEmailAndPassword()`
`sendPasswordResetEmail`

From DB:
`once()`
`set()`

Link to my repository:  [Here](https://github.com/CKunhardt/matchbox)

**Comment by CKunhardt** [comment]
Just saw the other issue with this, feel free to close.

**Comment by SteveKennedy** [comment]
@CKunhardt Can you point me to the "other issue with this"? I cannot seem to find an open issue for this specific issue.
