### ISSUE TITLE
refs loses track when changing rapidly

### ISSUE THREAD

**Issue by sacrosanctic** [firebase/firebase-js-sdk#7744]
### Operating System

WIN11

### Browser Version

Chrome/118

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

sveltekit with firebase

### Describe the problem

I am trying to a list of documents with pagination using, limit, limitToLast, startAfter, and endBefore.

### Steps and code to reproduce issue

demo: https://svelte-firebase-nine.vercel.app/
repro: https://github.com/ammarriq/svelte-firebase

In this demo, when clicking next and previous, it will lose track of the reference randomly

**Comment by MarkDuckworth** [comment]
@sacrosanctic, I'm having trouble understanding the problem or reproducing with your demo. Can you tell me more about "it will lose track of the reference"? Which reference is lost? What's the behavior you are seeing in code to indicate that the reference "is lost"?

**Comment by sacrosanctic** [comment]
I was referring to the collection snapshot/reference. Let me try with as video. 

https://github.com/firebase/firebase-js-sdk/assets/2974920/dcb07ad1-8b99-4606-a029-fe5813ae7513

As I navigate between pages, the No. will go out of sync, the total documents retrieved will vary, and eventually, it will simply return no data.

The bug is not consistent, it can happen in 1-2 clicks or 10 or more.

**Comment by MarkDuckworth** [comment]
I think you might have a bug in your application that results in sending bad data to Firestore which is returning an empty result set. Consider putting some logging where you call `getDocs(...)` and ensure you're calling Firestore with the expected data. Could your application allow multiple click handlers to run before the first finishes?
