### ISSUE TITLE
Query from documentation doesn't return expected result

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7750]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

The following query does not work, no document is returned

```
const db = getFirestore();
const citiesRef = collection(db, "cities");
querySnapshot = await getDocs(query(citiesRef, where("regions", "in", [ [ "west_coast", "east_coast" ] ])));
querySnapshot.forEach(doc => console.log(doc.id));
```

The code in question is [documented here](https://firebase.google.com/docs/firestore/query-data/queries#limitations_2), you need to scroll up a little bit. Or search for the text "array-contains-any always filters by the array data type".

The documentation explicitly states "From the example data, only the DC document qualifies with its regions field of ["east_coast"]". However, it **does not** return the DC document, or any document for that matter.

You have to set up the [data first](https://firebase.google.com/docs/firestore/query-data/queries#example_data).

### Steps and code to reproduce issue

Already explained.

**Comment by MarkDuckworth** [comment]
@morganchen12, can you help me get this to the right person to modify these code snippets and documentation across all SDKs? We need to correct snippets and documentation for the `in` operator across all SDK languages.
