### ISSUE TITLE
Issue with FCM modular API (onPush is not firing on "push notification", if service worker is in stopped state)

### ISSUE THREAD

**Issue by dpeese** [firebase/firebase-js-sdk#7754]
### Operating System

Windows 11

### Browser Version

chrome Version 118.0.5993.118 (Official Build) (64-bit)

### Firebase SDK Version

All versions with 9 & 10. Tested in latest 10.5.2 as well

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Angular 14

### Describe the problem

 have a usecase which is working with compat but not working with modular API.
When service worker is stopped, triggering push notification starting service worker again but that message is not send to onPush function. It is working fine in compat. Could you please help in resolving it. Appreciate your help.

### Steps and code to reproduce issue

1. Once service worker is up and started, stop the service worker
2. Trigger push notification
3. Notification is not showing up in UI 
4. What we have observed is service worker is changing to start mode, script is loading, event listeners are getting registered, but onPush is not firing.
5. Please note that this issue is not there in compat js.

**Comment by Deepads** [comment]
Facing the same issue.

**Comment by tarunnaidu99** [comment]
Facing the same issue

**Comment by shvyriaev** [comment]
Facing the same issue

**Comment by zwu52** [comment]
Just trying to get more information, why are the use cases for stopping the service work? It's a required component for the SDK
