### ISSUE TITLE
Loading data bundles in the client outdated docs

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7755]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

The documentation regarding [loading data bundles in the client](https://firebase.google.com/docs/firestore/bundles#loading_data_bundles_in_the_client) is outdated. The code doesn't work, probably because it refers to the firebase v8 SDK.

### Steps and code to reproduce issue

Here's an up-to-date version

```
const resp = await fetch('./bundle.txt');//assuming the bundle is in the same folder
await loadBundle(db, resp.body);
const query = await namedQuery(db, 'latest-stories-query');
const querySnapshot = await getDocs(query);
querySnapshot.forEach(doc => console.log(doc.id, " => ", doc.data()));
```

There is also no equivalent to the line `const storiesSnap = await query.get({ source: 'cache' });`, how would this be adapted to v9?

**Comment by MarkDuckworth** [comment]
@marcusx2, You're right, it looks like that page does not have a bundle loading snippet for the modular Web API. It only has a snippet for the v8/compat API. @morganchen12, can you help us get this doc page updated with a new sample for the modular web SDK? The code provided from @marcusx2 looks like a good starting point, I can provide anything else you need.


Regarding your second question:

> There is also no equivalent to the line const storiesSnap = await query.get({ source: 'cache' });, how would this be adapted to v9?

You need [`getDocsFromCache()`](https://firebase.google.com/docs/reference/js/firestore_.md#getdocsfromcache).

**Comment by morganchen12** [comment]
This has been fixed in the docs.
