### ISSUE TITLE
Getting while Google Auth : cannot get of undefined _getidtokenresponse(auth)

### ISSUE THREAD

**Issue by st1992** [firebase/firebase-js-sdk#7758]
### Operating System

Mac OS - 12.5.1

### Browser Version

Chrome/118.0.5993.117

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

React app with webpack

### Describe the problem

Google signin with popup , getting error intermittently 

cannot get of undefined _getidtokenresponse(auth)

### Steps and code to reproduce issue

happening very intermittently, flaky issue.

**Comment by Xiaoshouzi-gh** [comment]
Can you share your code snippet or a MVCE?

**Comment by Lupobb** [comment]
Annulla l'iscrizione
Grazie

Il lun 27 nov 2023, 03:03 Google Open Source Bot ***@***.***>
ha scritto:
