### ISSUE TITLE
FR: Allow FCMs setBackgroundMessageHandler to handle all notifications

### ISSUE THREAD

**Issue by andrewfluck** [firebase/firebase-js-sdk#777]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.3
  * Firebase SDK version: 4.13.1
  * Firebase Product: FCM (auth, database, storage, etc)

### [REQUIRED] Describe the problem

I propose with a flag, allow `setBackgroundMessageHandler` to be used to handle all notifications. This is an issue in some cases where the user wants to append some data to their notification object, or handle their notifications in certain ways.

Something like this would solve the issue and allow the user to handle everything themselves
```js
messaging.setBackgroundMessageHandler(payload => {
    // ...
}, true);
```

**Comment by andrewfluck** [comment]
This is a gotcha for many people first starting out with this, they do not realize Firebase is handling this themselves and think that it is a bug.

**Comment by mmermerkaya** [comment]
Thanks for the FR (and the PR).

This behavior is documented [here](https://firebase.google.com/docs/cloud-messaging/js/receive
).

We try to follow the Android SDK behaviors in the JS SDK. In this case, Android SDK [does the same thing](https://firebase.google.com/docs/cloud-messaging/android/receive).

As @gauntface mentioned in your PR, we are trying to improve the way we do things in the JS SDK, but I'm afraid this will happen as part of a bigger API change and not anytime soon.

A workaround is to put your webpush notification payload inside the `data` field. This will make the SDK consider your message a "data message" and will trigger your background message handler.

**Comment by andrewfluck** [comment]
Unfortunately, we cannot do so as we could break things for other services. I'm aware of this workaround, but I'm afraid this is the only way. Maybe we could discuss an easy fix that doesn't break anything and is minimally invasive if possible? I know you would like to change this as well. I hope to find a solution to this.

**Comment by mmermerkaya** [comment]
A hackier workaround is to add an event handler _before_ you call `firebase.messaging()` and to call `event.stopImmediatePropagation()` in your event handler, which will prevent the SDK from handling the message. Keep in mind that this is **not** supported at all, and might break your app in a future release.

If you do this, you'll receive the raw [PushEvent](https://developer.mozilla.org/en-US/docs/Web/API/PushEvent) object in your event handler. You can get the message payload by calling `event.data.json();`.

In `firebase-messaging-sw.js`:
```
import firebase from 'firebase';
firebase.initializeApp(...);

self.addEventListener('push', event => {
  // Your function here

  event.stopImmediatePropagation();
});

const messaging = firebase.messaging();
```

**Comment by andrewfluck** [comment]
Hmm, I'm going to try that. Seems promising! Could you maybe even add that to the documentation, or note this in the Readme? Some users could also benefit from this. Ofc note this is a hacky workaround

**Comment by mmermerkaya** [comment]
We really don't want to make hacks like this any more public than they already are :smile:. There's a plan to make this available soon without hacky workarounds, so I'd rather change the documentation when that happens.
