### ISSUE TITLE
getDocs never resolves or rejects

### ISSUE THREAD

**Issue by abelHodasz** [firebase/firebase-js-sdk#7787]
### Operating System

Ubuntu 20.04.6 LTS

### Browser Version

Chrome Version 119.0.6045.105

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

I'm using vite with typescript and react and react-router.

### Describe the problem

I'm trying to run multiple queries after each other. But about 10% of the time, it hangs on one of the queries and getDocs doesn't resolve and doesn't throw error. It just stops the main thread.

It is an issue both with emulator and in production code.

Here are the relevant logs:
[logs.json](https://github.com/firebase/firebase-js-sdk/files/13368882/logs.json)

### Steps and code to reproduce issue

```ts
    const menuItemsQuery = query(collection(firestore, "menuItems"), where("restaurantId", "==", restaurantId)).withConverter(menuItemConverter);
    const categoriesQuery = query(collection(firestore, "categories"), where("restaurantId", "==", restaurantId)).withConverter(categoryConverter);
    const menuQuery = query(collection(firestore, "menus"), where("restaurantId", "==", restaurantId)).withConverter(menuConverter);
    const extrasQuery = query(collection(firestore, "extras"), where("restaurantId", "==", restaurantId)).withConverter(extraConverter);
    try {
        const timeout = window.setTimeout(() => {
            console.log("________________________________FETCH FAILED________________________________")
        }, 10000)

        const menuItemsSnapshot = await getDocs(menuItemsQuery);
        console.log("got menuItems")
        const categoriesSnapshot = await getDocs(categoriesQuery);
        console.log("got categories")
        const menuSnapshot = await getDocs(menuQuery);
        console.log("got menu")
        const extraSnapshot = await getDocs(extrasQuery);
        console.log("got extras")
        window.clearTimeout(timeout)
    } catch(err) {
        console.log(err)
    }
```

**Comment by dconeybe** [comment]
Hi @abelHodasz. Thank you for the bug report. I'll be taking a look. Could you please reproduce the issue with debug logging enabled, and post the logs? To enable debug logs, call `setLogLevel('debug')` (https://firebase.google.com/docs/reference/js/firestore_#setloglevel).

**Comment by dconeybe** [comment]
Also, are you calling `initializeFirestore()` to create your Firestore instance? If so, could you provide the code you are using to create the `FirestoreSettings` object?

**Comment by abelHodasz** [comment]
I'm calling initializeApp like this:
```ts
const app = initializeApp(firebaseConfig);
export const firestore = getFirestore(app);
if (import.meta.env.DEV) {
    connectFirestoreEmulator(firestore, "localhost", 8080)
}
```
I attached logs.json in the issue.

**Comment by dconeybe** [comment]
I see from the logs that you are using v10.5.0 of the Firestore SDK, which suffers from a known "query hanging" bug that was introduced in v10.4.0. Please upgrade to v10.5.2 (or later) to get the fix for this bug. See https://firebase.google.com/support/release-notes/js#version_1040_-_september_14_2023 for more details.

**Comment by abelHodasz** [comment]
I updated to Firebase 10.6.0, confirmed with pnpm list and node_modules firebase package.json, but logs still say 10.5.0.

**Comment by dconeybe** [comment]
If the logs say you are using v10.5.0 then that must be the version you are using, and that version is _known_ to suffer from the exact issue you are reporting. You'll need to figure out why your app at runtime is using a different version of the Firestore SDK than the one from pnpm and node_modules.

**Comment by abelHodasz** [comment]
Managed to really update it, seems to be working fine now, thanks for the help!
