### ISSUE TITLE
queryEqual fails

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7799]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

The queryEqual method doesn't seem to work for all cases. It is my understanding that it should return true if both queries return the same set of documents. I will give you an example where it returns false even though the document set is the same.

### Steps and code to reproduce issue

Use the [example data](https://firebase.google.com/docs/firestore/query-data/get-data#example_data).

```
var q3 = query(collection(db, "cities"), or(where("capital", "==", true), where("capital", "==", false)));
var q4 = collection(db, "cities");

const querySnapshot = await getDocs(q3);
querySnapshot.forEach(doc => console.log(doc.id, " => ", doc.data()));

const querySnapshot2 = await getDocs(q3);
querySnapshot.forEach(doc => console.log(doc.id, " => ", doc.data()));

console.log(queryEqual(q3, q4));
```

Both queries return the same document set, and it's guaranteed that q3 will always return the same set as q4, yet queryEqual returns false.

Even something much more simple and obvious returns false

```
var q3 = query(collection(db, "cities"), or(where("capital", "==", true), where("capital", "==", false)));
var q4 = query(collection(db, "cities"), or(where("capital", "==", false), where("capital", "==", true)));

console.log(queryEqual(q3, q4));
```

From further tests, it seems that queryEqual only returns true if both queries are written exactly the same way, not if the result would turn out the same. Is this by design? In that case, what is the use case of queryEqual? It seems pointless to me.

**Comment by dconeybe** [comment]
Hi @marcusx2. What you have discovered is _intended behavior_. Although the `queryEqual()` function does some rudimentary normalization when comparing queries for equality, that normalization is, indeed, quite basic. In particular, we do _not_ guarantee that `queryEqual()` returns `true` if, and only if, the two queries are guaranteed to have the same result set. In fact, the documentation specifically says "Returns true if the provided queries point to the same collection and apply the same constraints.". So, basically, `queryEqual()` returns `true` if the two queries were created identically. It would, for sure, be useful to provide deep normalization but that is not an operation that is provided by the SDK. I've logged an internal ticket, b/312455217, to maybe revisit this some day. I'm sorry that I don't have a more satisfying answer.

If interested, here are some links that show how queryEqual() is implemented.

https://github.com/firebase/firebase-js-sdk/blob/00235ba68fdbb5d9788a14ba2bdd75cad87301e4/packages/firestore/src/lite-api/reference.ts#L633-L657

https://github.com/firebase/firebase-js-sdk/blob/00235ba68fdbb5d9788a14ba2bdd75cad87301e4/packages/firestore/src/core/query.ts#L429-L434

https://github.com/firebase/firebase-js-sdk/blob/00235ba68fdbb5d9788a14ba2bdd75cad87301e4/packages/firestore/src/core/target.ts#L178-L216

**Comment by marcusx2** [comment]
Hi @dconeybe , thank you for the clarification. What is the use case of queryEqual then? Can you provide an example?
