### ISSUE TITLE
SDKs should be consistent with the errors class/interface

### ISSUE THREAD

**Issue by jshcrowthe** [firebase/firebase-js-sdk#78]
### [REQUIRED] Describe your environment

  * Operating System version: n/a
  * Firebase SDK version: n/a
  * Firebase Product: auth, database, storage

### [REQUIRED] Describe the problem

We provide an error class ([`FirebaseError`](https://github.com/firebase/firebase-js-sdk/blob/master/src/app/errors.ts#L88-L110)) that we should be using cross SDK to be more consistent with our Error reporting.

#### Steps to reproduce:

n/a

#### Relevant Code:

All error implementatinos

cc: @sphippen, @bojeil-google, @schmidt-sebastian

**Comment by sphippen** [comment]
Storage errors have a string property "serverResponse" that contains the body of the server's response (if the error was generated based on a server response) which can be useful for debugging. In fact, some of Storage's error messages tell the user to inspect "serverResponse" for more info.

Would it make sense to add something like this to FirebaseError? I don't want to switch the error implementation until we find a suitable replacement for that property.

**Comment by jshcrowthe** [comment]
From the perspective of `FirebaseError` I think it makes a lot of sense to allow for custom meta fields. That's something we could totally do. 

Then each component can leverage the same base error, and extend it as they please.

**Comment by bojeil-google** [comment]
Auth error is quite complicated. Auth errors can contain additional data in some cases. For example when the credential already exists, an email or phoneNumber and an optional credential can be returned. The only time we return the server response is for cryptic internal-error where we stringify the entire server response and return it in the error message.

**Comment by jshcrowthe** [comment]
@bojeil-google if `FirebaseError` supported arbitrary "meta" fields, would that suit your use case?

**Comment by jshcrowthe** [comment]
Closing this, will open a larger "Consolidate all the things" Issue where I will try and identify some duplication we can address.
