### ISSUE TITLE
Issues in iOS 17.2 Beta 3, 4 - `undefined is not an object (evaluating 'n.index0f')`

### ISSUE THREAD

**Issue by vojto** [firebase/firebase-js-sdk#7806]
### Operating System

iOS 17.2 Beta 3 (21C5046c)

### Browser Version

Safari/604.1

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

Capacitor app with Next.js and React

### Describe the problem

Some of our users upgraded to latest iOS Beta 3.

We started tracking a new error coming from Firebase:

![CleanShot 2023-11-23 at 09 29 51@2x](https://github.com/firebase/firebase-js-sdk/assets/50943/040476c3-3682-466d-86ed-0cb552d9757e)

The console log captured this message multiple times:

```
FirebaseError: [code=unavailable]: Initialization of query 'Query(target=Target(users/73viAKTTqgOXlfw4OeIBA0TA2sU2, orderBy: [__name__ (asc)]); limitType=F)' failed: IndexedDbTransactionError: [code=unavailable]: IndexedDB transaction 'Execute query' failed: AbortError: IDBTransaction will abort due to uncaught exception in an event handler [object Object]
```

There's also a lot of instances of this:

```
[2023-11-23T04:36:45.288Z]  @firebase/firestore: Firestore (10.5.2): FIRESTORE (10.5.2) INTERNAL ASSERTION FAILED: Unexpected state
```

It's exclusive to iOS Beta 3.

I tried upgrading my own device, but couldn't reproduce the error.

However, my sync stopped working, and I was seeing this in the console:

```
Unhandled Promise Rejection: FirebaseError: Firebase: Error (auth/internal-error).
```

I'm not sure if it's related to the error users were seeing, or separate issue.

### Steps and code to reproduce issue

1. Create a Firebase app with auth and some basic Firestore `onSnapshot`s.
2. Run it on iOS 17.2 Beta 2, and if not possible, then on iOS 17.1
3. Upgrade to iOS 17.2 Beta 3
4. The issue should reproduce

**Comment by vojto** [comment]
Update - so it initially shows as stuck sync, but after I try logging out and back in, I can reproduce the reported exception:

![CleanShot 2023-11-23 at 10 41 37@2x](https://github.com/firebase/firebase-js-sdk/assets/50943/d090b261-2211-4ce4-93d4-84748cd99335)

**Comment by maccman** [comment]
We're seeing this increasingly across any customer who's using ios 17.2 beta 3.

They are getting indexOf errors, and then the sync stops working.

**Comment by vojto** [comment]
I just tried this on my girlfriend's iPhone (ran out of testing devices) by upgrading from 17.1 to 17.2 beta 4, and can't reproduce anymore.

I also used Firebase 10.7.0.

So there are 2 possible explanations:

1. This problem was only reproducing when upgrading from Beta 2 → Beta 3
2. Since I originally reproduced with Firebase at 10.5.2, it's also possible it was fixed in the meantime.

**Comment by milaGGL** [comment]
Hi @vojto, sorry for the late reply, I was out of office for 2 weeks. Thank you for reporting this issue and I am glad to hear that the problem was lifted on beta4.  I am going to close this ticket, but please feel free to reopen it if the issue re-appears.
