### ISSUE TITLE
Error auth/argument-error on signInWithPopup

### ISSUE THREAD

**Issue by jabaGR** [firebase/firebase-js-sdk#7809]
### Operating System

Windows 11

### Browser Version

Edge 119.0.2151.72

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React (NextJS)

### Describe the problem

The data from the application is correct, and the + is the same as the others, but it gives the error auth/argument-error

### Steps and code to reproduce issue

`firebase.ts
const firebaseConfig = {
  apiKey: "XXXXXXXXXXXXXX",
  authDomain: "XXXXXXXXXXXXXX",
  databaseURL: "XXXXXXXXXXXXXX",
  projectId: "XXXXXXXXXXXXXX",
  storageBucket: "XXXXXXXXXXXXXX",
  messagingSenderId: "XXXXXXXXXXXXXX",
  appId:"XXXXXXXXXXXXXX",
  measurementId: "XXXXXXXXXXXXXX"
};
// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = initializeAuth(app, {persistence: browserSessionPersistence, popupRedirectResolver: undefined});
const provider = new GoogleAuthProvider()
export {auth,provider};`

`LoginButton.tsx
import {auth,provider} from './firebase'
export default function LoginButton(){
    const Auth = () => {
        signInWithPopup(auth, provider).then(data => data.user.getIdToken().then((token) => console.log(token)))
    }
    return (
        <button onClick={() => Auth()}>Войти</button>
    )
}`

**Comment by renkelvin** [comment]
Hi @jabaGR , could you share the source code that can reproduce this issue?
