### ISSUE TITLE
INVALID_PASSWORD on first login after user registration on server side

### ISSUE THREAD

**Issue by Wevaleum** [firebase/firebase-js-sdk#7812]
### Operating System

MAC OS 14.1.1

### Browser Version

Chrome/119.0.6045.159

### Firebase SDK Version

9.2.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Client/Server application:

- email/password registration on server side by calling firebaseAuth.createUser(request) - java
- SignIn on client side with angularFireAuth.signInWithEmailAndPassword(email, password) - angular

### Describe the problem

after registration the signIn method is returning wrong password,
This configuration was working before, the issue appears two months ago

### Steps and code to reproduce issue

first step: Server side - java:
`UserRecord.CreateRequest request = new UserRecord.CreateRequest()
                .setEmail(user.getUsername())
                .setPassword(user.getPassword())
                .setUid(user.getId().toString());
firebaseAuth.createUser(request);`

second step: Client side - angular:
angularFireAuth.signInWithEmailAndPassword(email, password)

http response:
{
  "error": {
    "code": 400,
    "message": "INVALID_PASSWORD",
    "errors": [
      {
        "message": "INVALID_PASSWORD",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

**Comment by DellaBitta** [comment]
Hi @Wevaleum,

The `INVALID_PASSWORD` response originates from the Firebase Service and isn't produced by the Firebase SDK. Please open a [Firebase Support ticket](https://firebase.google.com/support/troubleshooter/contact) to connect with the support team who can diagnose issues in the backend. I'm going to close this issue for now, but feel free to reopen a new issue and link this one if the Firebase Support team sends you back to us SDK folks. Thanks!
