### ISSUE TITLE
Firebase: Error (auth/network-request-failed).Title for the bug

### ISSUE THREAD

**Issue by TechLateef** [firebase/firebase-js-sdk#7817]
### Operating System

debian 12

### Browser Version

using postman 

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

nodejs 

### Describe the problem

trying to create user using  createUserWithEmailAndPassword(); it was working fine at first and i try create user now and i keep on getting (auth/network-request-failed). 

### Steps and code to reproduce issue

 constructor() {
    this.auth = getAuth(firebaseApp);
  }

 const userCredential = await createUserWithEmailAndPassword(
        this.auth,
        email,
        password
      );

**Comment by DellaBitta** [comment]
Hi @TechLateef,

Could you tell us which version of Firebase you have upgraded from, and what version of Node you're using? Thanks!

**Comment by TechLateef** [comment]
Firebase vesions : 10.6.0 and Nodejs version is : 21.2.0

**Comment by DellaBitta** [comment]
Ok, thanks for circling back. I'm gald things are up and running for you. I'll close this issue for now. Please open a new issue if you run into any more problems!
