### ISSUE TITLE
v10.7.0 messaging bundles missing from www.gstatic.com

### ISSUE THREAD

**Issue by atsjo** [firebase/firebase-js-sdk#7821]
### Operating System

All

### Browser Version

All

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Angular 17 with nx

### Describe the problem

Messaging bundles missing from google cdn:
https://www.gstatic.com/firebasejs/10.6.0/firebase-messaging-compat.js (works)
https://www.gstatic.com/firebasejs/10.7.0/firebase-messaging-compat.js (missing)
https://www.gstatic.com/firebasejs/10.6.0/firebase-messaging.js (works)
https://www.gstatic.com/firebasejs/10.7.0/firebase-messaging.js (missing)

however this works:
https://www.gstatic.com/firebasejs/10.7.0/firebase-messaging-sw.js

Other bundles I've tested are present...

### Steps and code to reproduce issue

Just try the links in the description... I ended up importing from cdnjs instead to make it work...
I still use compat bundles in the service worker, instead of bundling or moduler from cdn, just to have a generic worker referencing /__/firebase/init.js for initialization.

**Comment by DellaBitta** [comment]
Thanks for the issue! Looks like we indeed have a problem with our release yesterday, but I was able to fix it just now. If you continue to have any related issues then please open a new issue and link this one to it. Thanks!

**Comment by atsjo** [comment]
working now...
