### ISSUE TITLE
unhandledRejection Messaging

### ISSUE THREAD

**Issue by mahanteshaCloudMPower** [firebase/firebase-js-sdk#7828]
### Operating System

ubuntu

### Browser Version

Version 119.0.6045.123 (Official Build) (64-bit)

### Firebase SDK Version

firebase@10.7.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

nuxt 3.4
node 20.0.0
firebase 10.7.0

### Describe the problem

[unhandledRejection] Messaging: This browser doesn't support the API's required to use the Firebase SDK. (messaging/unsupported-browser).   

 ERROR  [nitro] [unhandledRejection] Messaging: This browser doesn't support the API's required to use the Firebase SDK. (messaging/unsupported-browser).               7:01:30 PM

  at node_modules/@firebase/messaging/dist/esm/index.esm2017.js:1167:33

### Steps and code to reproduce issue

while static file generating time am getting error like this

**Comment by jbalidiong** [comment]
Hi @mahanteshaCloudMPower, thanks for reaching out to us. Could you provide a minimal reproducible test case so that we can better understand and reproduce your code usage? Thanks!
