### ISSUE TITLE
QueryConstraint's type can't be accessed

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7835]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Database

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

QueryConstraint's [type](https://firebase.google.com/docs/reference/js/database.queryconstraint.md#queryconstrainttype) property is inaccessible, however the API seems to indicate that it shouldn't be. Coupled with the fact that on firestore and firestorelite I can access this property, I think this is a bug.

### Steps and code to reproduce issue

```
const limitConstraint = limitToLast(100);
console.log(limitConstraint.type)//undefined
```

**Comment by maneesht** [comment]
Thanks for catching this, the fix should be out in the next release
