### ISSUE TITLE
Regression on update from 10.6.0 to 10.7.1 with jest unit testing: ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#7845]
### Operating System

windows

### Browser Version

chrome 120

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Analytics, AppCheck, Auth, Database, Firestore, Functions, Messaging, Performance, Storage

### Describe your project's tooling

firebase, angularFire, angular

### Describe the problem

regression of packages
![image](https://github.com/firebase/firebase-js-sdk/assets/1098243/9f6eff24-99f8-4493-9633-9a0cc0068d79)

### Steps and code to reproduce issue

just an update to 10.7.1 and running jest tests

**Comment by DellaBitta** [comment]
Hi @LanderBeeuwsaert, 

To help us narrow down the issue, could you tell us which version you were upgrading from? Thanks!

**Comment by LanderBeeuwsaert** [comment]
Hi @DellaBitta ,
sure:
firebase-js-sdk: 10.6.0 to 10.7.1
angularFire (but because of the stacktrace I would think it's a firebase issue): 16.0.0 to 17.0.0

**Comment by DellaBitta** [comment]
Which version of the JavaScript runtime are you using?

**Comment by LanderBeeuwsaert** [comment]
@DellaBitta ah apologies, I forgot, jest runs on node, we're using:
Node: 20.9.0
Package Manager: npm 8.19.1

**Comment by DellaBitta** [comment]
Hi @LanderBeeuwsaert,

We [recently](https://firebase.google.com/support/release-notes/js#version_1070_-_november_27_2023) updated our `node-fetch` dependency with `undici`, and that stack trace points to the fact that undici uses `TextDecoder`. This was done in jest uses [jdom](https://github.com/jsdom/jsdom) to simulate browser enviornments, which, [unfortunately seems to not have TextDecoder](https://github.com/jsdom/jsdom/issues/2524).

Looking into the discussion of that pull request there seems to be [a work around](https://github.com/jsdom/jsdom/issues/2524#issuecomment-897707183). Could you try it out and see if it solves the issue?

If that doesn't work, [this older StackOverflow post](https://stackoverflow.com/questions/68468203/why-am-i-getting-textencoder-is-not-defined-in-jest) has some other recommendations. I hope this helps!

**Comment by LanderBeeuwsaert** [comment]
Hi @DellaBitta yes great, works like a charm.
I did add it to setup-jest.ts instead so I only needed to add it once.
but that necessitates to add node in the tsconfig types which seems to impact the run performance
But anyway, it works, thanks!

**Comment by NickFoden** [comment]
Thanks for documenting this. Added the below to my `jest.setup.ts` and tests are able to run again. 

```
import { TextEncoder, TextDecoder } from "util";
global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```
Thank you 👍
