### ISSUE TITLE
Requesting data with `source: server` does not actually go to server and returns data from cache 

### ISSUE THREAD

**Issue by andreymikhadyuk** [firebase/firebase-js-sdk#7848]
### Operating System

Windows 11 Pro 22H2

### Browser Version

Firefox v120.0.1 (64-bit)

### Firebase SDK Version

^8.3.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

It is web app written using React `v17.0.1`. For state management we use redux (with sagas).

### Describe the problem

We've enabled persistence in our app. In some places we rely on the cached data. So sometimes we do request using `source: cache` and if there is no data in cache we try same request using `source: server`.

We display a list of items and for each item we fetch its `discussion`. The issue is that for one of our teammates somehow after some time of app usage some discussions become empty in the cache, but even doing a request with `source: server` does not really go to server, we still get empty data in the response (and yes, by the query we have data in the db). In another browser or after clearing the cache the issue is solved. Changing cache size to unlimited did not solve the problem.

Me and my teammate tried to intentionally reproduce the issue by doing following:
- we tried to limit the cache size to 1 Mb and play with the app. We tried to reach some cache clearings by garbage collector and everything worked fine, we could not get the state when we see incorrect data (I tested in Chrome (119.0.6045.159) and Firefox (120.0.1) on my MacBook (macOS 13.4.1));
- going offline with `source: server` did not throw an error. The code continued working in the `try` block and in the logs we could see `null` data having `fromCache=false`.

So we could not reproduce the issue. But my teammate has this issue in our dev and prod environments in his Firefox.

### Steps and code to reproduce issue

As I mentioned in the problem description, we could not intentionally reproduce it.
Here is the code example of how we fetch that data:
```
const getDiscussionById = async (
  discussionId: string,
  source: "default" | "server" | "cache" = "default",
): Promise<Discussion | null> => {
  try {
    const snapshot = await firebase
      .firestore()
      .collection("discussion")
      .withConverter(converter)
      .doc(discussionId)
      .get({ source });
    const discussion = snapshot.data() || null;

    if (!discussion && source === "cache") {
      return getDiscussionById(discussionId, "server");
    }

    return discussion;
  } catch (error) {
    if (source === "cache" && isFirestoreCacheError(error)) {
      return getDiscussionById(discussionId, "server");
    } else {
      throw error;
    }
  }
};
```

We tried to remove the logic of fetching with `source: cache` by using just `source: server` to get data directly from server, but we still get empty data having `fromCache=false`. As I mentioned in the problem description, going offline does not throw the error during the request, the code keeps executing in the `try` block with empty data in the `snapshot.data()`.
```
const getDiscussionById = async (
  discussionId: string,
): Promise<Discussion | null> => {
  const snapshot = await firebase
    .firestore()
    .collection("discussion")
    .withConverter(converter)
    .doc(discussionId)
    .get({ source: "server" });
  const discussion = snapshot.data() || null;

  return discussion;
};
```

**Comment by ehsannas** [comment]
Hi @jbalidiong , thanks for reporting.

You seem to be using a very old SDK version (8.3.2 is at least 2 major versions behind). The newest version is 10.7.1. Please upgrade to the newest version. Unfortunately we won't look into issues related to version 8, as it's been deprecated now.

If you continue to see the issue in the latest version, please let me know along with a way to reproduce the issue.

**Comment by andreymikhadyuk** [comment]
@ehsannas Thanks for the info, I've updated the version and we will check whether the issue is still there or not.

**Comment by andreymikhadyuk** [comment]
After updating the version to latest one we still had fully the same issue. We decided to clear the cache and see whether the issue will return or not with the latest version. If yes, then I will come back to this issue.

**Comment by andreymikhadyuk** [comment]
@ehsannas Hello!
We've gotten the issue again. Now in Chrome `121.0.6167.140 (64-bit)` on the same computer. Firebase SDK Version is `^10.7.1` now.
The issue is the same:
1. we try to fetch specific data using `source: cache`
2. after getting `null` we try to make request using `source: server` and it also returns `null` (the query is correct, the data is in the DB and in another browser for the same user everything is fine)

Here is the snapshot screen (you can see that `fromCache` is `false` and the response is empty):
![image](https://github.com/firebase/firebase-js-sdk/assets/29727923/1714d4fa-9be1-4e10-acf1-6ff372480131)

I do not really have steps to reproduce, it is such a rare thing, but we cannot fix it. The only way is to clear the cache in the browser.
Is there a potential fix on our side or on your side?

**Comment by DanielFlockhart** [comment]
> @ehsannas Hello! We've gotten the issue again. Now in Chrome `121.0.6167.140 (64-bit)` on the same computer. Firebase SDK Version is `^10.7.1` now. The issue is the same:
> 
> 1. we try to fetch specific data using `source: cache`
> 2. after getting `null` we try to make request using `source: server` and it also returns `null` (the query is correct, the data is in the DB and in another browser for the same user everything is fine)
> 
> Here is the snapshot screen (you can see that `fromCache` is `false` and the response is empty): ![image](https://private-user-images.githubusercontent.com/29727923/302313230-1714d4fa-9be1-4e10-acf1-6ff372480131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzkwNjIsIm5iZiI6MTcwNzMzODc2MiwicGF0aCI6Ii8yOTcyNzkyMy8zMDIzMTMyMzAtMTcxNGQ0ZmEtOWJlMS00ZTEwLWFjZjEtNmZmMzcyNDgwMTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIwNDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0N2M2NTU4YjliNjE2ZmU3NmVhYzRjZDRiZjI3OTk1MjI4MjBjNmI4OWJhZWY0NzQ0NmMzOGUwNTY5NWExOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTwyOChVBJjx1ssTutMFyS72MJFqfAaBwjGBMQpiifs)
> 
> I do not really have steps to reproduce, it is such a rare thing, but we cannot fix it. The only way is to clear the cache in the browser. Is there a potential fix on our side or on your side?

Any Updates on this? Dealing with the same problem.

**Comment by andreymikhadyuk** [comment]
@ehsannas Hey👋🏻 Any thoughts on this?

**Comment by ehsannas** [comment]
hi folks, can anyone provide a minimal code to reproduce this?

**Comment by andreymikhadyuk** [comment]
> hi folks, can anyone provide a minimal code to reproduce this?

From my side this is just a rare thing which appears after some time of using our app.
@DanielFlockhart Maybe you know how to reproduce this issue?

**Comment by noskiboots** [comment]
> > hi folks, can anyone provide a minimal code to reproduce this?
> 
> From my side this is just a rare thing which appears after some time of using our app. @DanielFlockhart Maybe you know how to reproduce this issue?

Any updates? Same exact issue in my app. Only every once in a while and specifically in chrome Version 123.0.6312.107 (Official Build) (x86_64).

**Comment by dconeybe** [comment]
Drive-by comment: If anyone is able to reproduce this bug, please enable Firestore debug logging by calling `setLogLevel('debug')` ([docs](https://firebase.google.com/docs/reference/js/firestore_?_gl=1*13ibyzk*_up*MQ..*_ga*NjUyMjkwOTI1LjE3MTMxOTc3MTg.*_ga_CW55HF8NVT*MTcxMzE5NzcxOC4xLjAuMTcxMzE5NzcxOC4wLjAuMA..#functionloglevel_)) and providing the logs. The logs will give some insight into the internals of the SDK and the steps it is taking to surface the results of the query, which may help us debug in the absence of concrete reproduction steps.

**Comment by bbonds007** [comment]
Can confirm I am experiencing the same exact issue. Its been plaguing my firebase project for almost a year now and I only now have been have to locate the issue due it being such a rare and difficult bug to locate. 

I haven't tried Firestore debug logging yet but I will attempt that tomorrow and report back if I find anything.

Here are the bullet points of what I found so far.

- Only appears to effect Chrome, firefox appears unaffected even when trying to replicate it with the steps below. 
- Only effected if firebase persistence is enabled (if you turn it persistence off, then .get() retrieves the document just fine)
- There are no reported errors from firebase, making this bug difficult to locate or notice. 
- I can somewhat reliably produce the bug. I have had it happen organically without partially deleting my cookies, but its rare and this is the fastest way to replicate it. 
1.  Start by clearing my "Cookies and other site data" entirely by starting fresh. 
2. Run my project and sign in using firebase auth, and be sure to retrieve a few documents from firestore. 
3. Wait OVER 1 hour at least, then go under chrome settings -> "Clear browsing data" -> then delete "Cookies and other site data" for ONLY the last hour. This effectively deletes part of my IndexedDB files, and I believe is the source of the problem. I believe some IndexedDB documents are being deleted and labeled as "noDocument". When this happens, it then breaks firebase's ability to ever retrieve that document again, even if .get({ source: 'server' }) is used, it will still return the doc.exists: false. 

**Temporary Solution:** This isn't a great solution but it can fix the issue if you are able to detect it occurred. Basically just delete IndexedDB and reload the page so it does a fresh reload of firestore. 
1.  await this.AngularFirestore.firestore.terminate()
2.  await this.AngularFirestore.firestore.clearPersistence()
3.  window.location.reload();

![Screenshot 2024-05-28 184206](https://github.com/firebase/firebase-js-sdk/assets/68559599/cf0eb2a0-74dc-43fa-9d12-bab7affaedb2)

**Comment by bbonds007** [comment]
> Drive-by comment: If anyone is able to reproduce this bug, please enable Firestore debug logging by calling `setLogLevel('debug')` ([docs](https://firebase.google.com/docs/reference/js/firestore_?_gl=1*13ibyzk*_up*MQ..*_ga*NjUyMjkwOTI1LjE3MTMxOTc3MTg.*_ga_CW55HF8NVT*MTcxMzE5NzcxOC4xLjAuMTcxMzE5NzcxOC4wLjAuMA..#functionloglevel_)) and providing the logs. The logs will give some insight into the internals of the SDK and the steps it is taking to surface the results of the query, which may help us debug in the absence of concrete reproduction steps.

Okay here are my Firestore debug logs. Hopefully its helpful, I apologize if they are lengthy, but there does appear to be some important happenings in them, specifically the problematic document in question (users/i8AVk3h2EcdBt2SC9fXmimOE89A2) appears to be getting deleted in the last screenshot. 

![Screenshot 2024-05-29 061624](https://github.com/firebase/firebase-js-sdk/assets/68559599/a5032dde-2cb4-427b-8647-dd641d956672)
![Screenshot 2024-05-29 061644](https://github.com/firebase/firebase-js-sdk/assets/68559599/7fb9fdb7-7c85-4414-9c7d-7097e6241ad8)
![Screenshot 2024-05-29 061656](https://github.com/firebase/firebase-js-sdk/assets/68559599/6372505d-48c8-42d4-8f55-95a351671fff)
![Screenshot 2024-05-29 061710](https://github.com/firebase/firebase-js-sdk/assets/68559599/568972d1-3ace-49b1-aa99-4708aace929f)
![Screenshot 2024-05-29 061722](https://github.com/firebase/firebase-js-sdk/assets/68559599/d9dccec7-f7ae-4267-b9a0-e84013b27282)
![Screenshot 2024-05-29 061734](https://github.com/firebase/firebase-js-sdk/assets/68559599/8ef37873-f137-46b2-b164-3db2f75110b1)
![Screenshot 2024-05-29 061756](https://github.com/firebase/firebase-js-sdk/assets/68559599/124b9307-9e2c-453d-8172-f0c9677e8754)

**Comment by dconeybe** [comment]
For anyone experiencing this issue, please upgrade to [v10.12.1](https://firebase.google.com/support/release-notes/js#version_10121_-_may_20_2024) (released May 20, 2024) and try again. A fix went into this version (https://github.com/firebase/firebase-js-sdk/pull/8247) for a bug where flaky/empty snapshots were being raised when multi-tab persistence was enabled. I have high confidence that the problems reported in this issue will be fixed in that version.
