### ISSUE TITLE
Upload from a String documentation issue

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7863]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Storage

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

[Upload from a string](https://firebase.google.com/docs/storage/web/upload-files#upload_from_a_string) says 

> uploadString() returns an UploadTask, which you can use as a promise or use to manage and monitor the status of the upload.

Which is false. uploadString returns a Promise<[UploadResult](https://firebase.google.com/docs/reference/js/storage.uploadresult.md#uploadresult_interface)>

### Steps and code to reproduce issue

Already described.

**Comment by DellaBitta** [comment]
Hi @marcusx2,

Thanks for pointing this out! I've updated the docs to remove the errant clause. Thanks again!
