### ISSUE TITLE
[Error] Firebase 5.0.0: Generic type 'Observer<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by paulstelzer** [firebase/firebase-js-sdk#787]
Issue: Generic type 'Observer<T>' requires 1 type argument(s).

Observer types in Firebase 5.0.0 not fixed on all positions. In commit #770 the interface Observer is now "export interface Observer<T> {...}", but in "/packages/auth-types/index.d.ts" at line 271 and 276 it's still the old one. The same at "/packages/storage-types/index.d.ts" line 80.

### Environment

  * Operating System version: Windows 10
  * Firebase SDK version: 5.0.0

**Comment by nayfin** [comment]
I'm seeing this too. Using `"angularfire2": "5.0.0-rc.8.", "firebase": "4.12.1", "@angular/core": "6.0.2"`. I started getting the following after upgraging to Angular 6. 

```
ERROR in node_modules/@firebase/auth-types/index.d.ts(255,21): error TS2314: Generic type 'Observer<T>' requires 1 type argument(s).
node_modules/@firebase/auth-types/index.d.ts(260,21): error TS2314: Generic type 'Observer<T>'
requires 1 type argument(s).
node_modules/@firebase/messaging-types/index.d.ts(25,38): error TS2314: Generic type 'Observer<T>' requires 1 type argument(s).
node_modules/@firebase/messaging-types/index.d.ts(30,38): error TS2314: Generic type 'Observer<T>' requires 1 type argument(s).
node_modules/@firebase/storage-types/index.d.ts(77,22): error TS2314: Generic type 'Observer<T>' requires 1 type argument(s).
```

Any help would be appreciated. I've been trying every possible configuration of firebase and angularfire that I can find.

**Comment by paulstelzer** [comment]
@nayfin use the latest versions of angularfire2 and firebase. then everything should work again

**Comment by sreekanth-karini** [comment]
Update typescript, `npm install typescript@2.3 --save` will fix the error.
