### ISSUE TITLE
Getting ''Attempted import error: ErrorFactory'' on build in Nextjs

### ISSUE THREAD

**Issue by fahisayub** [firebase/firebase-js-sdk#7871]
### Operating System

Windows 11

### Browser Version

Microsoft Edge Version 119.0.2151.97 (Official build) (64-bit)

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Storage

### Describe your project's tooling

- NextJs 13
- Firebase
- MongoDB
- Mongoose
- Typescript : 5.2.2
- react-pdf, pdfjs, pdfme
- Nodejs

### Describe the problem

when I am running the npm run build it shows the below error. It works fine when sending data to Firebase storage, but the build is failing. I am only using Firebase storage, **this error comes when I import this way**
 ` 
import firebase from "firebase/compat/app";
import  "firebase/compat/storage";
` 

Failed to compile.
./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
Attempted import error: 'ErrorFactory' is not exported from '@firebase/util' (imported as 'ErrorFactory').

Import trace for requested module:
./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
./node_modules/firebase/compat/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
Attempted import error: 'contains' is not exported from '@firebase/util' (imported as 'contains').

Import trace for requested module:
./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
./node_modules/firebase/compat/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
Attempted import error: 'contains' is not exported from '@firebase/util' (imported as 'contains').

Import trace for requested module:
./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
./node_modules/firebase/compat/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
Attempted import error: 'deepExtend' is not exported from '@firebase/util' (imported as 'deepExtend').

Import trace for requested module:
./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
./node_modules/firebase/compat/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
Attempted import error: 'createSubscribe' is not exported from '@firebase/util' (imported as 'createSubscribe').

Import trace for requested module:
./node_modules/@firebase/app-compat/dist/esm/index.esm2017.js
./node_modules/firebase/compat/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx
> Build failed because of webpack errors

**if i do the import this way** `
import {initializeApp} from 'firebase/app';
import {getStorage} from 'firebase/storage';
` **it will give another error** 
Failed to compile.

./node_modules/@firebase/app/dist/esm/index.esm2017.js
export 'FirebaseError' (reexported as 'FirebaseError') was not found in '@firebase/util' (possible exports: default)

Import trace for requested module:
./node_modules/@firebase/app/dist/esm/index.esm2017.js
./node_modules/firebase/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app/dist/esm/index.esm2017.js
Attempted import error: 'ErrorFactory' is not exported from '@firebase/util' (imported as 'ErrorFactory').

Import trace for requested module:
./node_modules/@firebase/app/dist/esm/index.esm2017.js
./node_modules/firebase/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app/dist/esm/index.esm2017.js
Attempted import error: 'getDefaultAppConfig' is not exported from '@firebase/util' (imported as 'getDefaultAppConfig').

Import trace for requested module:
./node_modules/@firebase/app/dist/esm/index.esm2017.js
./node_modules/firebase/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app/dist/esm/index.esm2017.js
Attempted import error: 'deepEqual' is not exported from '@firebase/util' (imported as 'deepEqual').

Import trace for requested module:
./node_modules/@firebase/app/dist/esm/index.esm2017.js
./node_modules/firebase/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

./node_modules/@firebase/app/dist/esm/index.esm2017.js
Attempted import error: 'deepEqual' is not exported from '@firebase/util' (imported as 'deepEqual').

Import trace for requested module:
./node_modules/@firebase/app/dist/esm/index.esm2017.js
./node_modules/firebase/app/dist/index.mjs
./src/config/firebaseConfig.ts
./src/helpers/firebaseStorageHelpers.ts
./src/store/slices/signNsealSlice.ts
./src/store/store.ts
./src/app/(Individual)/page.tsx

> Build failed because of webpack errors

### Steps and code to reproduce issue

**this is the config file (i am commenting one of the import method)**

```// Import the functions you need from the SDKs you need
import firebase from "firebase/compat/app";
 import  "firebase/compat/storage";
//import {initializeApp} from 'firebase/app';
//import {getStorage} from 'firebase/storage';
// import { getAnalytics } from "firebase/analytics";


// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "kdfks,
  authDomain: "abc.firebaseapp.com",
  databaseURL: "https://abc-default-rtdb.firebaseio.com",
  projectId: "abc",
  storageBucket: "abc.appspot.com",
  messagingSenderId: "kdslfdlsjfkdslf",
  appId: "1:dljfslf:web:dkslfdlf",
  measurementId: "G-ldjflsdjlfsdf"
};

// Initialize Firebase
  export const firebaseApp = firebase.initializeApp(firebaseConfig);
  export const storage = firebase.storage();

//export const firebaseApp =initializeApp(firebaseConfig);
//export const storage=getStorage(firebaseApp)
// export const analytics = getAnalytics(firebaseApp);
```

**And this is the file I use the Firebase storage ( I am commending the corresponding approach as in the config file)**

```// Assuming you have initialized Firebase as shown above

// import {firebaseApp} from "@/config/firebaseConfig";
// import {getStorage,ref,uploadString,getDownloadURL} from "firebase/storage";

// let storage=getStorage(firebaseApp)

// export const uploadToStorage = async (blobUrl: any,filename:string) => {
//     const imageRef =ref(storage, "images/" + filename);
//     try {
//         const snapshot = await uploadString(imageRef, blobUrl,'data_url', );
//         console.log('File uploaded successfully:', snapshot.ref.fullPath);
//         // You can obtain the download URL like this:
//         const downloadURL = await getDownloadURL(imageRef);
//         //convert the download url to a blob
//         return downloadURL
//       } catch (error) {
//         console.error('Error uploading file:', error);
//       }
      
      
// }

import { storage } from '@/config/firebaseConfig';



export const uploadToStorage = async (blobUrl:any, filename:any) => {
  const storageRef = storage.ref();
  const imageRef = storageRef.child('images/' + filename);

  try {
    // Create a reference to the file you want to upload
    const snapshot = await imageRef.putString(blobUrl, 'data_url');

    console.log('File uploaded successfully:', snapshot.ref.fullPath);

    // You can obtain the download URL like this:
    const downloadURL = await imageRef.getDownloadURL();

    // Convert the download URL to a blob if needed
    // Example: const blob = await fetch(downloadURL).then((response) => response.blob());

    return downloadURL;
  } catch (error) {
    console.error('Error uploading file:', error);
  }
};
```

**This is the next config file**

```//
/** @type {import('next').NextConfig} */
const nextConfig = {
        webpack: (config) => {
          config.module.rules.push({
            test: /\.node/,
            use: 'raw-loader',
          });

          return config;
        },
        compiler: {
          styledComponents: true,
        },
        }


module.exports = nextConfig

**Comment by fahisayub** [comment]
I am still facing this error, any idea how to fix this

**Comment by DellaBitta** [comment]
Hi @fahisayub,

We've received a report like this before but we couldn't reproduce it here. Is there a chance that you could post a minimal reproducible test case that exhibits this behavior? Thanks!

**Comment by fahisayub** [comment]
Here is the reproduced error, i have created a minimal repo that will reproduce the above error,i hope this will help
[https://github.com/fahisayub/error-repod](https://github.com/fahisayub/error-repod)
- clone it -> npm install -> npm run build

**Comment by DellaBitta** [comment]
Hi @fahisayub,

Thanks for the project, I was able to reproduce the error. However, I wans't able to reproduce the problem with a fresh [Next.js app using these instructions](https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup). Even more curious, I migrated over the tsconfig file, all of the dependencies from your project, and the next-config file, but I'm still not able to reproduce the problem.

Do you have any insight as to what sort of further configuration was made to your project that may have caused a change in this behavior? Can you reproduce this using the baseline Next.js app?

The code that I'm using is:

```
import {initializeApp} from 'firebase/app';
const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: ""
};
const firebaseApp = initializeApp(firebaseConfig);
```

Thanks!

**Comment by DellaBitta** [comment]
Oh, I should have also noted that this doesn't seem to be related to storage, as I was able to reproduce the problem with the `initializeApp` call after removing the storage calls. Does this align with your findings?

**Comment by fahisayub** [comment]
yes, it is not directly related to storage and the error is showing @firebase/util, this may be called internally in the package.

**Comment by DellaBitta** [comment]
Hi @fahisayub,

Just making sure you saw my previous post, too.

**Comment by fahisayub** [comment]
i have fixed this issue, it happens when i use firebase with canvas-based pdf rendering packages like react-pdf, which need a custom loader, when i add this custom loader like raw-loader or node-loader in the next.config.js , the above firebase error starts to happen. i belive the reason is there is some file ends with .node in firebase which is targeted by the raw-loader , which is basically used to fix the issue with canvas.node file. this is the previous next.config.js


`const nextConfig = {webpack: (config) => {
 config.module.rules.push({
  test: /\.node/,
  use: 'raw-loader',
    });
    return config;
  },
  compiler: {
    styledComponents: true,
  },
}`

 and no updating this to this resolved the issue ( only change is the test regex) also removed next/bable from .eslintrc.json

 `const nextConfig = {
  webpack: (config) => {
    config.module.rules.push({
      test: /canvas\.node/,
      use: 'raw-loader',
    });
    return config;
  },
  compiler: {
    styledComponents: true,
  },
}`


Thanks @DellaBitta

**Comment by jahangeer7704** [comment]
ok now i got it,using react pdf u have to use raw loader its a kind of loader ,which loades the files ,when  you use this loader this gives firebase error ,to prevent this you have to changes your nextjs config file as like this                                                                                    /** @type {import('next').NextConfig} */
const nextConfig = {
    webpack: (config) => {
        config.module.rules.push({
          test: /\.node/,
          exclude:/node_modules\/(firebase|@firebase)\//,
          use: "raw-loader",
        });
    return config;
      },
};

export default nextConfig;
       in this snipppet helps you renderring all data instead of binary it skips the fire base packs
