### ISSUE TITLE
ControlParams method missing

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-js-sdk#7873]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Analytics

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

The [ControlParams](https://firebase.google.com/docs/reference/js/analytics.controlparams.md#controlparams_interface) is missing the method associated with it. For example, [CustomParams](https://firebase.google.com/docs/reference/js/analytics.customparams.md#customparams_interface) has the [setDefaultEventParameters](https://firebase.google.com/docs/reference/js/analytics.md#setdefaulteventparameters).

The documentation says 
> Standard gtag.js control parameters. For more information, see [the GA4 reference documentation](https://developers.google.com/gtagjs/reference/ga4-events)

However if you follow the link and search for "control" or "control params" you won't find anything. It looks to me that this CustomParams might have been valid at some point for google analytics v3 or lower, but now it doesn't exist. Even if you search for each property individually, nothing comes up.

It looks to me that ControlParams is a "dead" interface, it exists but there is no application for it. If there is a way to use it, the documentation should be updated to clarify. If there isn't, ControlParams should just be removed.

### Steps and code to reproduce issue

Already described.

**Comment by DellaBitta** [comment]
Hi @marcusx2,

The ControlParams interface definition is for use with the simplified [gtag.js interface](https://developers.google.com/analytics/devguides/collection/gtagjs), [as defined here](https://developers.google.com/tag-platform/gtagjs/reference/parameters). It is not meant to be used with the functional interface provided by the rest of the Firebase Analytics SDK.

I hope that clears some things up.
