### ISSUE TITLE
Firebase: Error (auth/argument-error)

### ISSUE THREAD

**Issue by lakshyarawat1** [firebase/firebase-js-sdk#7882]
### Operating System

Windows 11

### Browser Version

Firefox

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

I am using React (Vite) along with Nodejs at the backend.

### Describe the problem

I have successfully created the createUserWithEmailAndPassword but when creating the functionality with signInWithPopUp along with GoogleProvider, I am facing an error saying "Firebase: Error (auth/argument-error)". 

### Steps and code to reproduce issue

Steps to reproduce the error.

```
import { browserPopupRedirectResolver, browserSessionPersistence, initializeAuth } from 'firebase/auth'
import { GoogleAuthProvider } from 'firebase/auth/cordova';
import { initializeApp } from 'firebase/app';

const firebaseConfig = {
  /* your config */
};

export const app = initializeApp(firebaseConfig);
export const provider = new GoogleAuthProvider();
export const auth = initializeAuth(app,{
  persistence: browserSessionPersistence,
  popupRedirectResolver: browserPopupRedirectResolver,
})
```

Here is the function created.

```
const handleGoogleLogin = async () => {
    signInWithPopup(auth, provider)
      .then((user) => {
        Swal.fire({
          title: "User Created !",
          text: "New user has been created ! ",
          icon: "success",
        });
        console.log(user);
      })
      .catch((err) => {
        Swal.fire({
          title: "Error !",
          text: err.message,
          icon: "error",
        });
        console.log(err.message);
      });
  };
```

Note: All exports and imports are perfect and not a reason for the error.

**Comment by looptheloop88** [comment]
Hi @lakshyarawat1, I tried replicating the issue and I was able to. The `GoogleAuthProvider` imported from `firebase/auth/cordova` package being used in `signInWithPopup` is the one causing the argument error. The authentication flow or process will work as expected if you use `GoogleAuthProvider` from `firebase/auth` package.

**Comment by lakshyarawat1** [comment]
> Hi @lakshyarawat1, I tried replicating the issue and I was able to. The `GoogleAuthProvider` imported from `firebase/auth/cordova` package being used in `signInWithPopup` is the one causing the argument error. The authentication flow or process will work as expected if you use `GoogleAuthProvider` from `firebase/auth` package.

I implemented your solution, i.e. changing the import from `firebase/auth/cordova` to `firebase/auth`, but unfortunately the issue still persists.
