### ISSUE TITLE
cannot disconnect function from emulator after using connectFunctionsEmulator

### ISSUE THREAD

**Issue by Yukinosuke-Takada** [firebase/firebase-js-sdk#7895]
### Operating System

macOS 14.0

### Browser Version

Chrome Version 117.0.5938.149 (Official Build) (arm64)

### Firebase SDK Version

firebase v 10.7.0, @firebase/functions v 0.11.0

### Firebase SDK Product:

Functions

### Describe your project's tooling

I'm using firebase/function in my webapp.

My mac is running node v19.7.0, yarn 1.22.19

### Describe the problem

I have a web app that tests Firebase functions. It tests the onCall function on the Emulator and Deployed in the same run. After using `connectFunctionsEmulator()`, The specified function will use the Emulator afterward (even if I don't call connectFunctionsEmulator). 

### Steps and code to reproduce issue

Code:

```
  const invokeWithFunctionName = async (
    environment: Environment,
    functionRegion: string,
    functionName: string,
    sendingParameters: Record<string, string>
  ) => {
    const firebaseFunctions: Functions = getFunctions(currentApp, functionRegion);
    if (environment === 'Emulator') {
      connectFunctionsEmulator(firebaseFunctions, 'localhost', 5001);
    } else {
      // disconnect emulator
      
    }
    const callable = httpsCallable(firebaseFunctions, functionName, { timeout: 10000 });
    const res = await callable(sendingParameters);
    return (res.data as string);
  };
```

```
await invokeWithFunctionName('Deployed', 'asia-northeast1', 'f', {});
await invokeWithFunctionName('Emulator', 'asia-northeast1', 'f', {});
await invokeWithFunctionName('Deployed', 'asia-northeast1', 'f', {});
```

The POST request it's sending
```
POST https://asia-northeast1-****.cloudfunctions.net/f
POST http://localhost:5001/****/asia-northeast1/f
POST http://localhost:5001/****/asia-northeast1/f
```

See that the 3rd POST request is stuck with using localhost.

**Comment by looptheloop88** [comment]
Hi @Yukinosuke-Takada, thanks for bringing this matter to our attention. I was able to replicate the same behavior that you reported. Let me check with the team if there’s a way to disconnect from the Emulator programmatically.

**Comment by hsubox76** [comment]
So this isn't a very official way to do it but I think you should be able to do this: `firebaseFunctions.emulatorOrigin = null` and that should reset it back to the way it was before calling `connectFunctionsEmulator()`.

I don't think we ever thought of this use case because we assumed people would run emulator tests in one process and non-emulator tests in a separate process. We could try to provide a more official way to do this if there is demand, but at the moment I think this is a somewhat uncommon use case and there is (maybe) a workaround. Also I don't think any of the other `connect[Product]Emulator` methods allow this, so we'd have to try to make it consistent.

Anyway let me know if that works, if it doesn't I'll look into it further.

**Comment by Yukinosuke-Takada** [comment]
Hi, thanks for the response.

I modified my code like this:
```ts
if (environment === 'Emulator') {
  connectFunctionsEmulator(firebaseFunctions, 'localhost', 5001);
} else {
  // disconnect emulator
  firebaseFunctions.emulatorOrigin = null;  // <- Error here
}
```

But I get error: Property 'emulatorOrigin' does not exist on type 'Functions'.

It seems the type `Functions` does not have the method `.emulatorOrigin`. Looking at the source code, type `FunctionService` has this method instead. I tried to type cast like `(firebaseFunctions as FunctionService).emulatorOrigin = null;` but, `FunctionService` seems not to be exported.

**Comment by Yukinosuke-Takada** [comment]
Looking at the source code, creating like a `disconnectFunctionEmulator` method doesn't look difficult at first glance. I can make a PR. let me know :)

**Comment by hsubox76** [comment]
That's true, but if we make an actual change to the SDK we have to be consistent across all connect[Product]Emulator functions (Auth, Storage, and Firestore), and not just for Functions, which is a larger change that I don't think we can do without talking to some other teams.

If this is blocking you, for now you can either
(1) ts-ignore (I think it's just a TS error, but the method is actually there?)
(2) Use [patch-package](https://www.npmjs.com/package/patch-package) to patch connectFunctionsEmulator in your project
(3) run emulator tests in a different suite from live endpoint tests, run by a separate process. I think this is usually recommended, and this is how we structure our own tests, but you know your own project's needs best, so I'd suggest one of the other solutions if you really need this.

**Comment by Yukinosuke-Takada** [comment]
> That's true, but if we make an actual change to the SDK we have to be consistent across all connect[Product]Emulator functions (Auth, Storage, and Firestore), and not just for Functions, which is a larger change that I don't think we can do without talking to some other teams.

ah yes true. thanks for the response tho. I'll look into the patch-package (which I'm not familiar with).
