### ISSUE TITLE
Minified FirebaseFirestore datatypes (Map, List, etc.) in release mode (Flutter Web)

### ISSUE THREAD

**Issue by Nico1911** [firebase/firebase-js-sdk#7896]
### Operating System

macOS 14.1.2

### Browser Version

Safari Version 17.1.2

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

AppCheck, Auth, Firestore, Functions, Storage

### Describe your project's tooling

I program a Flutter website with Android Studio and use Firebase to manage my data and for hosting.

### Describe the problem

Every Firestore data I got in my flutter web (as e.g. in the stream below) were minified in release mode. In detail the runtimeTypes Map, List and Timestamp become "minified:...". In reference to the example below: Already the values of the DocumentSnapshot fields of snapshot.data are minified. I don't get any errors or special log output.

I´ve the newest Version of flutter, dart and android studio. My temporary workaround is to launch the website with:
flutter build web --profile --dart-define=Dart2jsOptimization=O0 --no-tree-shake-icons

but of course this is neither a solution to the problem nor a permanent method.
Thank you very much for your comments!

<img width="905" alt="Bildschirmfoto 2023-12-21 um 17 00 59" src="https://github.com/firebase/firebase-js-sdk/assets/82755433/2431e3e7-cf64-4786-9855-bab139892374">

### Steps and code to reproduce issue

I wish I knew exactly how this error came about. It occurs as soon as I simulate the website in release mode or publish it.

**Comment by looptheloop88** [comment]
Hi @Nico1911, I saw that you already filed an [issue](https://github.com/firebase/flutterfire/issues/12067) on FlutterFire repository. To avoid duplicate effort, I suggest you monitor the updates in the FlutterFire repository and if they verified that the issue is coming from the Firebase JS SDK, you may reopen this issue.
