### ISSUE TITLE
Incorrect cache when querying documents.

### ISSUE THREAD

**Issue by KyleSmith0905** [firebase/firebase-js-sdk#7897]
### Operating System

Windows 11

### Browser Version

Chrome 120.0.6099.72

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

This bug has occurred in both of these tools:
- Vite + React
- Angular

### Describe the problem

If you query query data on Firestore, it will use that data as a small local database as a cache. This may lead queries to return incorrect values in the cache.

This is almost never an expected behavior on the web. This leads to a flash of different content.

I'm using "onSnapshot" btw.

### Steps and code to reproduce issue

I'm concurrently loading popular articles and latest articles. After some time I'm loading more latest articles.
Hosted site: https://mre--incorect-firestore-cache.web.app
Repository: https://github.com/KyleSmith0905/mre--incorrect-firebase-cache

**Comment by wu-hui** [comment]
You are correct that Firestore SDK utilizes cache from previous results. On Web, the default behavior is to use memory as cache, and eagerly delete cache as soon as they are not used by any active listeners. 

If you want to make sure you always use the results from the backend, you need to subscribe the metadata for your listener as well, and wait for the snapshot's metadata to be fromCache==false and hasPendingWrite==false.

**Comment by KyleSmith0905** [comment]
I added the following the the reproduction app:
`articles.metadata.fromCache === false && articles.metadata.hasPendingWrites === false`

I also changed around the reproduction app to show exactly what I need for my project (I have a main page with all the videos, and other pages with filtered content from them).

Reproduction again: https://mre--incorect-firestore-cache.web.app
Github again: https://github.com/KyleSmith0905/mre--incorrect-firebase-cache

**Comment by KyleSmith0905** [comment]
I envision a `finishedQuery` metadata property that will be true if:
- A non cached value is returned
- A cached value is returned, but it will not be revalidayed.

**Comment by wu-hui** [comment]
You need to actually subscribe for metadata in order to see all metadata changes: https://firebase.google.com/docs/firestore/query-data/listen#web-modular-api

**Comment by KyleSmith0905** [comment]
I must've missed that, adding `includeMetadataChanges` fixed the issue, thank you so much for the response.
