### ISSUE TITLE
Identifier Failure

### ISSUE THREAD

**Issue by OldManMeta** [firebase/firebase-js-sdk#7901]
### Operating System

Windows 11 (N/A????)

### Browser Version

Edge, Chrome, Brave, Safari (N/A????)

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React, TS, Webpacl

### Describe the problem

Authentication is failing INSIDE the firebase dashboard.

New users are no longer getting an identifier (see image)

The Auth object fails to pass the email address of the authenticated user to my code from the auth object. The UID is being returned correctly.

![image](https://github.com/firebase/firebase-js-sdk/assets/107874035/0581240f-1e58-4788-8009-fb6cb11492fb)

The image is showing GOOGLE oauth failures, but I can confirm this is happening on ALL oauth clients.

### Steps and code to reproduce issue

No idea when this started to happen. Has worked as expected for months - CLEARLY something has changed on the Firebase backend services which is causing this issue.

**Comment by bhparijat** [comment]
Hi, please share small reproducible code implementation. Thanks.

**Comment by OldManMeta** [comment]
Thanks for the response.

I actually see the issue is a change in how the firebase object is returned from the Auth process.

Previously in the object model, the email address was returned in the root properties, and now (it is always null) and you have a providerData array object.

The providerData object may have always been there (unsure?) - but either way, it appears that this is the only place that an email address is returned now, given the correct scopes requested.

I'm not sure why this has changed? Furthermore, it should NEVER change (even if the original versioned response is in error).

This is the reason WHY we use versioned libraries - so the response object is known.

I will close this now - please ensure your library responses moving forward are version locked.

Cheers.
