### ISSUE TITLE
Property 'database' does not exist on type 'FirebaseNamespace'

### ISSUE THREAD

**Issue by realgsong** [firebase/firebase-js-sdk#791]
### [REQUIRED] Describe your environment

  * Operating System version:
    * Distributor ID:	Ubuntu
    * Description:	Ubuntu 18.04 LTS
    * Release:	18.04
    * Codename:	bionic
  * Firebase SDK version: 5.0.1
  * Firebase Product: database

#### Steps to reproduce:

```
import firebase from 'firebase/app';
import 'firebase/database';

...

in code
firebase.database().ref(userRef).once('
...
```
causes following error.

error TS2339: Property 'database' does not exist on type 'FirebaseNamespace'.

#### Workaround
When I changed my code like following solves issue.

```
firebase['database']().ref(userRef).once('
```

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by ebeloded** [comment]
The same problem with firebase.firestore:
![screen shot 2018-05-09 at 15 38 55](https://user-images.githubusercontent.com/5859177/39804759-255c7ae0-539f-11e8-8cb2-bcc185a01d17.png)

Thank you @realgsong for the workaround.

**Comment by mmermerkaya** [comment]
Looks like the `index.d.ts` files for both of these didn't make it to the NPM release. I can't see them in `node_modules/@firebase/<packageName>/dist` after a `npm install`.

**Comment by kenzierocks** [comment]
Did this happen again? I'm getting the same error, it looks like TS isn't pickup on the `index.node.d.ts` in `@firebase/firestore`.

**Comment by mmermerkaya** [comment]
This was only fixed for imports from `firebase/*`, not `@firebase/*`. It's recommended to import from `firebase/*` packages for now. You can open a different issue for imports from `@firebase/*`.

CC @jshcrowthe.
