### ISSUE TITLE
Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore

### ISSUE THREAD

**Issue by cybercoder-naj** [firebase/firebase-js-sdk#7912]
### Operating System

EndeavourOS

### Browser Version

Chrome 119

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Nuxt3 with Typescipt

### Describe the problem

I am trying to get all documents from a collection, but it keeps throwing an error which does not make any sense to me. 

### Steps and code to reproduce issue

I have a plugin which provides the firestore instance to my application:
```ts
import { initializeApp, type FirebaseOptions } from 'firebase/app';
import { getAnalytics } from 'firebase/analytics';
import { getFirestore } from 'firebase/firestore';

export default defineNuxtPlugin(nuxtApp => {
  const config = useRuntimeConfig();

  const firebaseConfig: FirebaseOptions = {...};

  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);
  const firestore = getFirestore(app);

  return {
    provide: {
      firestore: firestore
    }
  };
});
```

I can now use this inside a composable function as such below:

```ts
import { collection } from 'firebase/firestore';

export default async function() {
  const { $firestore } = useNuxtApp();

  console.log($firestore);
  // const event = collection($firestore, 'events');

  return [];
}
```

As evidenced by this picture, I am retrieving a valid firestore object.
![screenshot-2023-12-27_16:01:21](https://github.com/firebase/firebase-js-sdk/assets/48282810/79887bb3-6e2d-48b7-b7ae-0f3530c027cc)

However, when I uncomment the line `const event = collection($firestore, 'events');`, I can this error from firebase:
![screenshot-2023-12-27_16:02:30](https://github.com/firebase/firebase-js-sdk/assets/48282810/ce5f1dd3-7bba-431b-8141-417580b78f6b)

**Comment by MarkDuckworth** [comment]
@cybercoder-naj,
What is the output if you add the following to your file?
```
import { collection, Firestore } from 'firebase/firestore';

console.log(`$firestore instanceof Firestore: ${$firestore instanceof Firestore}`)
```

**Comment by cybercoder-naj** [comment]
I have solved the issue. The problem was that firebase was initialised in the client side only and I was trying to access it in the server side of the application.
