### ISSUE TITLE
FR: force twitter to re-approve when relinking

### ISSUE THREAD

**Issue by Ernest5663** [firebase/firebase-js-sdk#7926]
### Operating System

macOS

### Browser Version

Chrome/120.0.6099.199

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

NextJS web app

### Describe the problem

When the account has been linked once, unlinking from auth and going to link the app again, is there any way that we can force the user to approve on twitter side again?

### Steps and code to reproduce issue

N/A

**Comment by Xiaoshouzi-gh** [comment]
Can you elaborate on what do you mean by "approve on twitter side"?
