### ISSUE TITLE
firebase web does not appear in the realtime dashboard

### ISSUE THREAD

**Issue by KOSSOKO** [firebase/firebase-js-sdk#7928]
I use firebase in my Android App and my web app. Same project for both. I have two configurations, one for Android and one for Web.

When i open my Android App, automatically events are triggered and I can see the user in the realtime overview.
`Mobile is always 100%`. 

![image](https://github.com/firebase/firebaseui-web/assets/11942543/420edc7d-d738-4ac4-ae5b-c861d2fa042f)

In my web i have a file called `firebase.js` with this code

```
  // Import the functions you need from the SDKs you need
  import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
  import { getAnalytics, logEvent } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-analytics.js";
  // TODO: Add SDKs for Firebase products that you want to use
  // https://firebase.google.com/docs/web/setup#available-libraries

  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  const firebaseConfig = {
    apiKey: "AIzaXXXXXXXXXXXXXXXXXXXCWdu6fMbeqU",
    authDomain: "XXXXXXXXXXXXXXXXXXXfirebaseapp.com",
    projectId: "gXXXXXXXXXXXXXXXXXXXXore",
    storageBucket: "XXXXXXXXXXXXXXXXXXXXXXXappspot.com",
    messagingSenderId: "XXXXXXXXXXXXXXXXXXXX",
    appId: "XXXXXXXXXXXXXXXXXXX24659b36c5f51b63",
    measurementId: "G-XXXXXXXXXXXXXXXXXXXXXXX"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);
  
  logEvent(analytics ,'test_event_from_game', { name: 'hiiiiiiiiiii'});
    
  console.log(app);
  console.log(analytics);
```
  and I included it in my `index.html`

```<script src="./firebase.js" type="module"> </script>```

For what reasons the Android only is working in realtime ?

**Comment by hsubox76** [comment]
This seems to be working fine for me. Here's my full setup. I have a local directory with two files:

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script src="./index.js" type="module"></script>
</body>
</html>
```

index.js (identical to your code above, shortened for brevity)
```
  import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
  import { getAnalytics, logEvent } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-analytics.js";

  const firebaseConfig = {
    // config
  };

  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);
  
  logEvent(analytics ,'test_event_from_game', { name: 'hiiiiiiiiiii'});
    
  console.log(app);
  console.log(analytics);
```

I put those in the same dir, and then ran http-server locally and went to that site. I see the event sent in my dev tools network tab:

![Screenshot 2024-01-16 at 11 16 40 AM](https://github.com/firebase/firebase-js-sdk/assets/10716545/1ba49883-f290-4263-a9f6-f687f51d42aa)

In the console I see the event (there's 3 because I ran this 3 times)

![Screenshot 2024-01-16 at 11 16 53 AM](https://github.com/firebase/firebase-js-sdk/assets/10716545/dc3d1b2d-7a51-4db6-8ac5-9a1fba889320)

Are you seeing the event being sent in your network tab? It should be a request to a url with the endpoint `collect` as you can see in the first screenshot. If not, do you have any kind of ad blockers or private browsing mode enabled?

**Comment by KOSSOKO** [comment]
Veru strange. Even the firebase team did not succeed to explain why the data is not in my dashboard. Also, you have the desktop appeared...I never got desktop.
Firebase team said that it is about threshhold, but your data have been detected.
What is also strange is the fact that during debug i saw the data sent.

I'm really confused.

**Comment by hsubox76** [comment]
I'm not sure I really understand your comments. By the "firebase team" do you mean Firebase support? Are you talking to the Firebase support team separately? Do you see the "collect" request sent from the network tab?

I suspect this isn't an issue with Firebase specifically (which just wraps calls to Google Analytics) but with Google Analytics.

The best way to test if this is Firebase problem or a Google Analytics problem is to create a test page that does not use Firebase, but makes a call to Google Analytics directly using gtag.js: https://developers.google.com/tag-platform/gtagjs/install (Under the hood, Firebase Analytics just calls gtag.js).

Check your network traffic (in the dev tools network tab) and then also check the Google Analytics dashboard (not the Firebase dashboard) to see if the event was received. If you're still having the same problem, there is some issue with Google Analytics and/or your browser environment, and not with the Firebase wrapper, and you'll have to try to contact the Google Analytics team for support.

**Comment by KOSSOKO** [comment]
Hello @hsubox76, I created few days ago a ticket for the support because data were not sent to bigquery too. The ticket is closed now.

This is what I have in debug.

and i have also the collect:

`https://region1.analytics.google.com/g/collect?v=2&tid=G-25L48DR5H1&gtm=45je41a0v9115978792&_p=1705507221640&_dbg=1&gcd=11l1l1l1l1&dma_cps=sypham&dma=1&_fid=eGSP3o3BNMMU2slBi212WG&cid=566941529.1705506934&ul=fr-fr&sr=414x896&uaa=&uab=&uafvl=&uamb=0&uam=&uap=&uapv=&uaw=0&are=1&pae=1&_s=1&sid=1705506934&sct=1&seg=1&dl=https%3A%2F%2Fd333wz42ngbii5.cloudfront.net%2F1%2Fhtml5-data%2Fhtml5%2Fhtml5-1695526988621%2Fbuild%2FBuild%2Findex.html&dt=Knife%20Master&en=page_view&_ee=1&ep.origin=firebase&_et=1&tfd=980`


![image](https://github.com/firebase/firebase-js-sdk/assets/11942543/b2e6b3dd-7908-4502-b672-bcdb427c0b26)

**Comment by KOSSOKO** [comment]
Hello @hsubox76 we created a new project with Angular, imported the configuration and test. We have same situation. We can see logs in Chrome, but nothing appears in the firebase console. 
We are all confused.

**Comment by KOSSOKO** [comment]
Also I just connect, I can see my user in the map, but it is said mobile instead of WEB. I'm connected using pc browser.
![image](https://github.com/firebase/firebase-js-sdk/assets/11942543/13dee734-1327-4abb-b849-865602f16e1f)

**Comment by hsubox76** [comment]
Thanks for doing that, just to confirm, is the new project using gtag.js and not using Firebase? If so, it seems the problem is outside of the Firebase SDK, and is an issue with either Google Analytics or your device/browser, or some combination of these. Are you able to contact Google Analytics for support?

Let me know if I misunderstood and the new project still uses Firebase.
