### ISSUE TITLE
Can't catch any logs or do any actions after linkWithRedirect success

### ISSUE THREAD

**Issue by Ernest-Tribe3** [firebase/firebase-js-sdk#7935]
### Operating System

macOS

### Browser Version

Chrome/120.0.6099.199

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

NextJS

### Describe the problem

When performing a linkWithRedirect() with .then() or .catch(), the content inside .then() can't be logged.
E.g. from the example, linkWithRedirect completed was never been logged on the console

### Steps and code to reproduce issue

linkWithRedirect(curUser, twitterProvider).then(async () => {
        console.log('linkWithRedirect completed')
      })

**Comment by Xiaoshouzi-gh** [comment]
Can you provide a context snippet? Do you observe anything in the catch block?  Please note that you need to check the preserve log checkbox to keep all the console logs when there is a redirect.
