### ISSUE TITLE
FR: mutable firestore query results

### ISSUE THREAD

**Issue by wooliet** [firebase/firebase-js-sdk#7938]
### Operating System

macOS 14

### Browser Version

Chrome 120.0.6099.199

### Firebase SDK Version

10.5.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Vue app using Quasar

### Describe the problem

I am trying to reduce the size of a snapshot result as each document in the snapshot is processed. This is not a monitored snapshot, but instead a single `getDocs` collection of documents.

The goal is general memory reduction. We need to build up a separate collection using the snapshot documents. I thought clearing out the source of the data as it is processed would be helpful. 

But the more I dug into this, the more I realized everything in these results is immutable. 

My feature request is to provide an alternate to the current `getDocs` such that results are mutable (either a new method or an additional argument to the existing method).

### Steps and code to reproduce issue

```javascript
const snapshot = getDocs(dataQuery);
const convertedData = [];
// will always evaluate to true
while (snapshot.docs.length > 0) {
  const doc = snapshot.docs.pop();
  const newData = getConvertedData(doc);
  convertedData.push(newData);
}
```

**Comment by cherylEnkidu** [comment]
Hi @wooliet,

Generally SDK wants to provide data guarantee on the return object. Could you provide more context on why do you want to use it in this way? Are you try to allow the garbage collector to collect used Snapshot data sooner? You can also save the result to a local variable to free the reference of snapshot.

**Comment by wooliet** [comment]
We have a case where our app will get (not monitor) a large number of documents. Part of the data flow was a call to `map` the documents to the format needed for display. We did not do any profiling, just observed certain devices really struggling when they ran into this particular case. I thought one way to reduce our memory consumption would be to `pop` from the snapshot docs as we added to our display docs.

At the moment we are using `.forEach` to iterate through the docs instead of `.docs`. But honestly, I am not sure which of the two methods are most memory effecient. I see [`.forEach` create new instances](https://github.com/firebase/firebase-js-sdk/blob/42bfb0b8243a6c36b66a0bbedf61436e70591062/packages/firestore/src/api/snapshot.ts#L583) of `QueryDocumentSnapshot` for each item. And I see `.docs` create a whole new array ([but push the existing instances into that result](https://github.com/firebase/firebase-js-sdk/blob/42bfb0b8243a6c36b66a0bbedf61436e70591062/packages/firestore/src/api/snapshot.ts#L555)).

It just seemed simpler to me, and hopefully more memory efficient, to be able to get the query result and work directly against it.

**Comment by cherylEnkidu** [comment]
Hi @wooliet ,

Thank you for explaining your use case!

It is unlikely the SDK is going to provide a mutable return type because of type safety reason and the return object should be treated as "source of true" from the backend.

However, there are other ways you can consider to improve your app performance:

1. 
```javascript
// Don't hold the reference to snapshot, so that it can be garbage collected
// Every time calling .docs creates a new copy of data array, so try to do it only once.
let docs = getDocs(dataQuery).docs;
const convertedData = [];
while (docs.length > 0) {
  const doc = docs.pop();
  const newData = getConvertedData(doc);
  convertedData.push(newData);
}
```

2. Consider using [limit](https://firebase.google.com/docs/firestore/query-data/order-limit-data#order_and_limit_data) to only fetch part of data each time.

**Comment by wooliet** [comment]
Thank you for the help @cherylEnkidu !
