### ISSUE TITLE
Firestore read not working for multi-page app in Safari private mode

### ISSUE THREAD

**Issue by gunnarmein-ts** [firebase/firebase-js-sdk#7940]
### Operating System

macOS 14.2

### Browser Version

Safari 17.2.1

### Firebase SDK Version

10.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

HTML/TypeScript app built with esbuild

### Describe the problem

We have a document shell (index.html) and the actual document editor (document.html). Both initialize Firebase auth. We use signingWithPopup and our subdomain is our config auth domain. We can sign in successfully on index.html, but transitioning to document.html, the first call to getDoc() will not resolve until some ridiculous time later (I noticed it had resolved after I took the dogs for a walk). Meanwhile, a couple of promises were rejected:

[Warning] [2024-01-11T16:45:26.104Z]  @firebase/app: – "Firebase: Error thrown when reading from IndexedDB. Original error: Error looking up record in object store by key range. (app/idb-get)." (document-bundle.js, line 142)
[Error] Unhandled Promise Rejection: AbortError: AbortError
	error (document-bundle.js:1541)

<img width="392" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/86687645/b203e177-6528-4f61-9035-1225f775d7bf">

and another one, both by the heartbeat service.

This works fine in Chrome. I cannot say whether it works in Safari. It becomes an issue because when Safari is automated (by Selenium in our case), it will only launch in a private window now, making all of our Safari tests fail.

### Steps and code to reproduce issue

- Write firebase app with 2 html pages
- Open Safari private window
- sign in on page one
- load page 2
- read doc from firestore db (the doc is not protected by auth or identity, it is marked "allow read;" in firestore.rules)
-> hangs for a long time (deadlock?)

**Comment by gunnarmein-ts** [comment]
Could be related to #7890

**Comment by gunnarmein-ts** [comment]
Completely giving up on persistentLocalCache (not just the persistentMultipleTabManager) for Safari seems to be a workaround.

**Comment by dconeybe** [comment]
Drive-by comment: Note that IndexedDb is typically not available in "private" or "incognito" tabs. So Firestore persistence won't work in such an environment. That being said, it _should_ gracefully fall back to memory persistence (i.e. the default persistence mode) so there may be a bug here.

**Comment by diginikkari** [comment]
Getting this error also in normal mode (non private) with Safari (Version 17.2.1 (19617.1.17.11.12)). Firebase version 10.7.1.

**Comment by gunnarmein-ts** [comment]
> Getting this error also in normal mode (non private) with Safari (Version 17.2.1 (19617.1.17.11.12)). Firebase version 10.7.1.

I find that once this error happens, I need to shut Safari down or nothing - private or public - will work again.

**Comment by cherylEnkidu** [comment]
Hi @gunnarmein-ts and @diginikkari ,

I try to reproduce the issue with the same MacOS, Safari, Firebase version but did not succeed. If you are still experiencing this issue, could you please provide a minimum repo app?

**Comment by gunnarmein-ts** [comment]
[cherylEnkidu](https://github.com/cherylEnkidu) I can do it this week, but not today.  Thanks for looking into it!

**Comment by jmw11x** [comment]
No this issue needs re-opened. This is a current live bug and outage that google team is actively ignoring that looks like for multiple years. Upgrading from name-spaced to modular code does not fix this problem. FIrestore does not even load properly and even without caching I am getting errors and no data loading.

**Comment by cherylEnkidu** [comment]
Hi @jmw11x ,

Sorry for your experience :(, I cannot successfully reproduce this issue on my side. Given your issue is not related to this ticket, can you open a new github ticket and provide us a minimum repo? Also In your repo app, can you only use Firestore without functions, auth, database?

**Comment by jmw11x** [comment]
Sure thing I can if needed, I am also working with support team on ticket I have MCVE for them I can have it added here if needed. 

Using modular javascript sdk..

I have the mcve with auth. I will make a branch / other section without it too.

Please note that this is related to this ticket/OP. I have the same problem except it is not in private mode it is in safari in general with SAME error / behavior produced. Without persistant cache I get no data at all on safari from onSnaphot functions.

**Comment by cherylEnkidu** [comment]
Thank you for your repo! Can you also pass me the support ticket id? I will follow up with the support team.

**Comment by jmw11x** [comment]
Case #: 10271607

Repo: https://github.com/jmw11x/FirebaseFirestore-Case-10271607/tree/main

**Comment by jmw11x** [comment]
> Thank you for your repo! Can you also pass me the support ticket id? I will follow up with the support team.

Hello and thanks for the help,

I added an update today on this repo with cache enabled. You can see it now. It was not working under any settings on safari on friday and today it works without cache. The same problem is still occurring with cache as this thread and my op states. Please look into this issue and fix it as it appears a fix was applied to safari in general over the weekend/this morning.

**Comment by cherylEnkidu** [comment]
The issue is been tracked here: https://github.com/firebase/firebase-js-sdk/issues/8081
