### ISSUE TITLE
firebase outages over the past few days

### ISSUE THREAD

**Issue by michaelAtCoalesce** [firebase/firebase-js-sdk#7961]
### Operating System

Linux

### Browser Version

Node 18.x

### Firebase SDK Version

10.1.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Node.js 

### Describe the problem

We have tried escalating this through firebase support but have not gotten helpful answers. Due to the nature that we are seeing this from multiple different regions, this appears to be a real firestore availability issue and needs to be looked at which is why I am opening a ticket on this github. 

We are seeing connectivity errors from different cloud providers and regions, across our DEV, QA and Production Firebase instances. 

We have observed the following error multiple times:
```
@firebase/firestore: Firestore (10.1.0): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
FirebaseError: [code=unavailable]: Failed to get document because the client is offline.
```

This has recently been happening at the following times from different locations:

2024-01-14 around 14:04 GMT+13
from a Kubernetes pod on GCP europe-west3

2024-01-16 around 03:34 GMT+13
from a Kubernetes pod on AWS us-west-2

2024-01-16 around 13:04 GMT+13
from a kubernetes pod on GCP us-central1
from a Kubernetes pod on GCP europe-west3
from a Kubernetes pod on AWS us-east-1
from a Kubernetes pod on AWS us-west-2

At  2024-01-18T18:05:34.584Z, we saw this again. 

Given the fact that we are seeing connectivity issues connecting to Firestore from different locations, this appears to be a firestore availability issue that needs to be looked into with **HIGH** urgency. 

### Steps and code to reproduce issue

This is a transient connectivity issue that we are detecting across multiple clients over the past few days, failing to connect to Firestore.

**Comment by michaelAtCoalesce** [comment]
i would like to also call out, that at January 15th, 4:00:23 Pacific time, we saw a firestore outage from FOUR different regions 

GCP us-central1
GCP europe-west3
AWS us-east-1
AWS us-west-2

this points to a firestore availability issue...

**Comment by milaGGL** [comment]
Hi @michaelAtCoalesce, thank you for filing this issue. This seems like a cloud connectivity issue rather than a firebase SDK specific problem. I would suggest filing a cloud support ticket, the procedure should be [this](https://cloud.google.com/support/docs/customer-care-procedures), I believe.
