### ISSUE TITLE
Expo app with Firebase authentication not working in google play store production

### ISSUE THREAD

**Issue by TenaciousMoose** [firebase/firebase-js-sdk#7967]
### Operating System

IOS 14.1.1

### Browser Version

Chrome 120.0.6099.216

### Firebase SDK Version

10.7.0

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

- Expo
- React
- React Native
- React Navigation
- Jest & Jest Expo
- Typescript
- Babel
- React Hook Form
- Firebase
- Expo Dev Client
- Async Storage
- React Refresh

### Describe the problem

Howdy! My Expo app with Firebase realtime db / firebase auth with google sign in works as intended in dev. However, when submitting the app to google play store for internal testing a couple odd things happen:
1. User is able to signin using GoogleAuthProvider but instead of being rerouted to the app's home page after signin, the user gets my [...missing].tsx screen. 
2. If the user then clicks on the "go to home screen" link from the [...missing].tsx file they will be at the home page but the app is unable to read or write to firebase. Instead of showing a list at the home screen, an infinite loader shows, which is only available in the beginning of the firebase call but goes to false when it's complete. 
3. The user is also unable to logout or write to firestore

With the hopes of narrowing down potential issues I made a new expo project and uploaded it to google play store. I was able to connect and fetch data from the same data base as the original app, as long as I didn't include authentication. After authentication gets introduced, is when the issue appeared again in the second app.

Thanks so much for your time!

### Steps and code to reproduce issue

Below is my firebaseConfig, auth, and SignIn files. If I don't have these files I'm able to read and write to the db from production but with them I'm not.

**firebaseConfig.ts**
---------------
import { initializeApp } from 'firebase/app';
import {
  getAuth,
  initializeAuth,
  GoogleAuthProvider,
  getReactNativePersistence,
  signInWithCredential,
} from 'firebase/auth';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { initializeFirestore, CACHE_SIZE_UNLIMITED } from 'firebase/firestore';

// Initialize Firebase
const firebaseConfig = {
...
};

const app = initializeApp(firebaseConfig);

// Initialize Authentication
const auth = initializeAuth(app, {
  persistence: getReactNativePersistence(AsyncStorage),
});

// Initialize Firestore
const db = initializeFirestore(app, {
  cacheSizeBytes: CACHE_SIZE_UNLIMITED,
});

export { auth, db, GoogleAuthProvider, signInWithCredential };

----------------
**Auth.tsx**

import React, {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
} from 'react';
import {
  onAuthStateChanged,
  signOut,
  User as FirebaseUser,
} from 'firebase/auth';
import { auth } from '../firebaseConfig';
import { useRouter } from 'expo-router';

interface AuthContextType {
  currentUser: FirebaseUser | null;
  signOutUser: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType | null>(null);

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};

interface AuthProviderProps {
  children: ReactNode;
}

export const AuthProvider: React.FC<AuthProviderProps> = ({ children }) => {
  const [currentUser, setCurrentUser] = useState<FirebaseUser | null>(null);
  const router = useRouter();

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
      if (!user) {
        router.replace('/(auth)/SignIn');
      }
    });

    return unsubscribe;
  }, [router]);

  const signOutUser = async () => {
    await signOut(auth);
    setCurrentUser(null);
  };

  return (
    <AuthContext.Provider value={{ currentUser, signOutUser }}>
      {children}
    </AuthContext.Provider>
  );
};

-----------------
**app/SignIn.tsx**

import React, { useEffect } from 'react';
import { View, Text, Button, Platform } from 'react-native';
import * as Google from 'expo-auth-session/providers/google';
import { GoogleAuthProvider, signInWithCredential } from 'firebase/auth';
import { auth } from '../../firebaseConfig';
import * as WebBrowser from 'expo-web-browser';
import { router } from 'expo-router';

WebBrowser.maybeCompleteAuthSession();

const SignIn = () => {
  const clientId = Platform.select({
    ios: iosClientId,
    android:
      androidClientId
  });

  const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
    clientId,
  });

  useEffect(() => {
    if (response?.type === 'success') {
      const { id_token } = response.params;
      const credential = GoogleAuthProvider.credential(id_token);
      signInWithCredential(auth, credential)
        .then(() => {
          router.replace('/tallies');
        })
        .catch((error) => {
          console.error('Sign In Error', error.message);
        });
    }
  }, [response]);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ fontSize: 32, fontWeight: 'bold', marginBottom: 90 }}>
        Sign In
      </Text>
      <Button
        title="Sign in with Google"
        onPress={() => {
          if (!request) {
            console.error('Error', 'Google sign-in configuration error.');
            return;
          }
          promptAsync();
        }}
      />
    </View>
  );
};

export default SignIn;

**Comment by pragatimodi** [comment]
Looking at this code sample, I believe the issue is unrelated to the Firebase Auth JS SDK. You're using `signInWithCredential()`, which only gets invoked _after_ the Google sign in completes and redirects to your app. You can confirm this by trying to upload an app without the Firebase bits but with the `Google.useIdTokenAuthRequest()` and associated return callbacks. I suspect that you'll have the same issue.

I'd recommend verifying this and then opening an issue with the Expo folks https://docs.expo.dev/versions/latest/sdk/auth-session

**Comment by TenaciousMoose** [comment]
Hey thank you @pragatimodi for taking the time to respond to my question and sorry for the delay, I didn't see the notification until today. For anyone viewing this in the future - between posting it and today I converted the application to use react native firebase and didn't run into any issues with Google Play. Next app I make I'll take a closer look at your suggestion. Thank you!
