### ISSUE TITLE
firebase@10.7.0 cause "Could not reach Cloud Firestore backend." error.

### ISSUE THREAD

**Issue by youngeun-ahn** [firebase/firebase-js-sdk#7968]
### Operating System

Windows 11

### Browser Version

Chrome 120.0.0.0

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React 18 with craco.
I used `react-query@^3` and `@react-query-firebase/firestore` to use firebase with hook.
Actually `@react-query-firebase/firestore` depends on `firebase@^9`, but I think there doesn't seem to be a significant relationship, as there are no issues observed with version `firebase@10.6.0`.

### Describe the problem

**Console**
<img width="1037" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/81739167/7028ee99-c78c-4e10-9002-9f3d7d034c21">

**Network**
<img width="452" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/81739167/cda1e6ff-6785-457b-940c-4979728ac952">

---

**Description**
I have encountered the 'offline' error in my project today, and the issue occurs only when accessing a specific Firestore document. Intermittently, it success to access the document, but most of the time, the error occurs. 
Though not certain, it seems suspicious when the document name or path contains an `_`(it just a speculation...).

The recent change in my project was upgrading from `firebase@^9` to `firebase@^10`.
So, after downgrading to `firebase@9`, the problem was resolved.

However, to pinpoint the exact version where the issue occurred, I conducted tests by incrementally upgrading the minor version starting from `10.0.0`. 
The error did not occur up to version `10.6.0`, but it occurs with version `10.7.0`.

### Steps and code to reproduce issue

It might be challenging to implement reproduction steps since the problem occurs intermittently with a specific document.

**Comment by milaGGL** [comment]
Hi @youngeun-ahn, thank you for filing this issue. I have a suspect, but not sure if it is the root cause.  Could you please try enabling the [`experimentalForceLongPolling`](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Settings#optional-experimentalforcelongpolling) and see if it solves the problem? 

Other than that, let's try setting [debug level logging](https://firebase.google.com/docs/reference/js/v8/firebase#setloglevel) to get more log info. Is there any abnormal activity in network tab while this bug happens?

**Comment by youngeun-ahn** [comment]
Hello @milaGGL . 
I apologize for the delayed response. 
I was on a trip this week, so I couldn't check your message earlier. 

I tried enabling the `experimentalLongPolling` option and checking with `debug-level logs`.
But the bug still occurred and I couldn't find any suspicious logs.
One difference thing is that there are no occurrences of "404" in the network tab.

**Screenshots**
> I've obscured my project name in the screenshot

| Console | Network |
| - | - |
| <img width="761" alt="log" src="https://github.com/firebase/firebase-js-sdk/assets/81739167/f29a8695-0ff6-4165-843f-39babfeaa37e"> | <img width="611" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/81739167/a969357d-b497-4807-b6d2-0962b97c71c1"> |

**Comment by milaGGL** [comment]
Strange. Would you be able to provide a minimal repro app so that I can reproduce and debug it on my end?

**Comment by malnafei** [comment]
Hi @youngeun-ahn 
there is an issue with Firebase JS SDK from 10.7.0 and above. So I advise you to use `10.6.0` untile new release is published.

Thank you

REF: https://github.com/firebase/firebase-js-sdk/issues/8017#issuecomment-1938183043
