### ISSUE TITLE
Version 4.13.1 is not available at gstatic.com

### ISSUE THREAD

**Issue by apaatsio** [firebase/firebase-js-sdk#797]
### Describe your environment
  * Operating System: Linux / Chrome
  * Firebase SDK version: 4.13.1
  * Firebase Product: full build / firebase.js

### Describe the problem

`firebase.js` file for version 4.13.1 is not found on gstatic.com.

#### Steps to reproduce:

Visit https://www.gstatic.com/firebasejs/4.13.1/firebase.js

Expected result: returns the build for version 4.13.1
Actual result: returns 404

For comparison these links work:
- https://www.gstatic.com/firebasejs/4.13.0/firebase.js
- https://www.gstatic.com/firebasejs/5.0.0/firebase.js
- https://www.gstatic.com/firebasejs/5.0.1/firebase.js

**Comment by jshcrowthe** [comment]
Hey @apaatsio `4.13.1` included a fix that was only applicable to Node.js usage of Firestore. As such the binary wasn't pushed to the gstatic CDN as there is no actually code change.

Using `4.13.0` will give you the same experience via the CDN 😄
