### ISSUE TITLE
Cannot inject key into script value on iOS 16.7.4

### ISSUE THREAD

**Issue by bo-rik** [firebase/firebase-js-sdk#7974]
### Operating System

iOS 16.7.4

### Browser Version

Safari

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

React app

### Describe the problem

This issue affects users on iOS 16.7.4. The problem was also present in the iOS 17.2 Beta, but was fixed before release. It was not fixed in iOS 16.7.4, however.

The Firebase SDK does not respond anymore. We use a subscription to `onAuthStateChanged` in our app state, but nor the nextObserver, neither the errorCallback is called.

When the issue arises, we observe following error when our app is launched on an affected device.

`UnknownError: Cannot inject key into script value`
<img width="992" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/118435082/1bc61981-5727-4218-a376-62aa2b81f7dd">

This issue was also referenced [here](https://github.com/firebase/firebase-js-sdk/issues/7742), but closed already.

### Steps and code to reproduce issue

Create Firebase app (auth, Firestore) and open it in Safari on iOS 16.7.2. Make sure offline persistence is enabled.
Upgrade the device to iOS 16.7.4.
Open the app again. It will print the error above, and the sync will hang.

**Comment by bigjimhere** [comment]
We are experiencing this issue as well. We upgraded the Firebase SDK from 8.10.1 to 10.7.2 in an attempt to resolve the issue but can confirm that it is still occurring on 10.7.2, on iOS 16.7.4 only. In our case it's a cordova app.

**Comment by hsubox76** [comment]
This seems to be the same as this issue https://github.com/firebase/firebase-js-sdk/issues/7742 It seems to be a Safari/iOS bug and I'm not sure what we could do to work around it.

**Comment by DellaBitta** [comment]
The other issue that was link has since been closed and resolved. Are you still experiencing this issue? Thanks!
