### ISSUE TITLE
Refactor _loadJS out of the library by default

### ISSUE THREAD

**Issue by seaders** [firebase/firebase-js-sdk#7976]
### Operating System

MacOS 14.1.2

### Browser Version

Chrome/1200.6099.234

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Analytics, Auth, Firestore, Functions

### Describe your project's tooling

Chrome web extension with Plasmo

### Describe the problem

Including the firebase library will now get any extension using it rejected from the Chrome Web Store, with a violation like

    Violation: Including remotely hosted code in a Manifest V3 item.
    Violating content:
    
        Code snippet: static/background/index.js: https://apis.google.com/js/api.js?onload=, https://www.google.com/recaptcha/enterprise.js?render= 

Even if you don't use any elements of Phone registration / login from Auth, nor Recaptcha, and are on a platform (like Chrome Web Store) which disallows dynamic loading of remote code, the firebase app includes this - by Google's own definition - "dangerous" feature that allows remote code to be loaded into your app, without any way to exclude it from your build.

### Steps and code to reproduce issue

Include the firebase sdk into your app, then compile and package it for the Chrome Web Store.  After some delay your app will be rejected with a code violation.

**Comment by hsubox76** [comment]
This should be fixed by https://github.com/firebase/firebase-js-sdk/pull/7766 which was just merged. It should be available in the next release. You'll have to refactor your code to import from `firebase/auth/extension` instead of `firebase/auth`.

There's also an existing issue: https://github.com/firebase/firebase-js-sdk/issues/7617
