### ISSUE TITLE
Unable to receive SMS verification code for Malaysia country since few weeks ago

### ISSUE THREAD

**Issue by dodomui** [firebase/firebase-js-sdk#7978]
### Operating System

iOS, Android, Web

### Browser Version

Chrome 120.0.6099.234

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

Angular App with Ionic + Capacitor, deploy for iOS, Android, Web

### Describe the problem

Everything has been functioning well until a few weeks ago when some users from Malaysian Telcos started experiencing issues with receiving SMS verification codes for authentication. From January 18, 2024, until now, none of our Malaysian users have been able to receive SMS verification codes. Despite submitting two support tickets, there has been no update from Firebase.

### Steps and code to reproduce issue

I have tested to login with Singapore mobile number and can successfully receive SMS verification codes. From the backend, it's observed that users from Macau, Singapore, Taiwan, Hong Kong, etc., have been able to utilize phone authentication. However, none of the users from Malaysia can access the system using phone authentication.

**Comment by jbalidiong** [comment]
Hi @dodomui, apologies for the delay and thank you for reaching out to us. This seems to be a project specific issue and not an SDK issue. As per checking, we can rule out that this is not an SDK issue as you've observed that users outside of Malaysia were able to successfully receive SDS verification code. I suggest filing a ticket via our [support channel](https://firebase.google.com/support) so the Auth team will be able to get your project details and investigate it in our backend. With this, I'll now close the ticket.
