### ISSUE TITLE
Firebase uses eval() which can be unsafe

### ISSUE THREAD

**Issue by apaatsio** [firebase/firebase-js-sdk#798]
### [REQUIRED] Describe your environment

  * Operating System version: Linux / Chrome
  * Firebase SDK version: 5.0.1
  * Firebase Product: full build

### [REQUIRED] Describe the problem

Firebase uses the `eval()` function which is considered unsafe.

You can see it being used here https://www.gstatic.com/firebasejs/5.0.1/firebase.js in the statement `try{return eval("("+a+")")}catch(e){}`.

#### Steps to reproduce:

I'm not sure exactly how to reproduce, but I got a Content-Security-Policy report from my site about the use of `eval()` and as far as I can tell, Firebase is the only library on my site that uses that function.

### Workaround

Currently, the workaround is to set `unsafe-eval` in Content-Security-Policy but this is [considered a bad practice](https://www.owasp.org/index.php/JavaScript_Closure_Within_Eval).

Similar issue was reported in 2016: firebase/quickstart-js/issues/95

**Comment by Slapbox** [comment]
Can anyone please take a look at this? GRPC, required by `Firestore` introduces a dangerous security hole into all apps that use it as they are required to allow `unsafe-eval`

https://github.com/grpc/grpc-node/issues/453

**Comment by Slapbox** [comment]
@Feiyang1 the Grpc issue was indeed addressed. Some more details here: https://github.com/firebase/firebase-js-sdk/issues/1036

**Comment by mikelehen** [comment]
I think it's coming from closure's JSON parsing: https://github.com/google/closure-library/blob/db35cf1524b36a50d021fb6cf47271687cc2ea33/closure/goog/json/json.js#L141

It looks like we can opt out of it by setting goog.json.USE_NATIVE_JSON to false at compile time. I'm looking into how to do that with our closure builder setup...
