### ISSUE TITLE
apiKey is blank in link generated by sendSignInLinkToEmail

### ISSUE THREAD

**Issue by acomanescu** [firebase/firebase-js-sdk#7981]
### Operating System

macOs 14.2.1

### Browser Version

Chrome/121.0.6167.85

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.js with app dir

### Describe the problem

When calling `sendSignInLinkToEmail` I receive an email with a link that contains a query parameter `apiKey` with no value. This redirects to a page that says `The selected page mode is invalid.`. 

### Steps and code to reproduce issue

Simply execute `sendSignInLinkToEmail` and check the email link.

**Comment by DellaBitta** [comment]
This seems like this was a backend issue. I'm going to close this issue for now, but if you encounter the issue again the please open a new isssue and feel free to link this issue if it provide any additional context. Thanks!
