### ISSUE TITLE
FirebaseError: Installations: Firebase Installation is not registered. (installations/not-registered).

### ISSUE THREAD

**Issue by DevSpareChange** [firebase/firebase-js-sdk#7988]
### Operating System

17.0.3

### Browser Version

unknown

### Firebase SDK Version

9.23.0

### Firebase SDK Product:

Analytics, Installations, Messaging, Remote-Config

### Describe your project's tooling

React App with Webpack and Jest

### Describe the problem

I have my react app running in a mobile context within a native app on both iOS and android and often receive this error in my sentry. What may cause this issue and how may this be resolved? This error occurs on both platforms

### Steps and code to reproduce issue

unknown

**Comment by hsubox76** [comment]
Error is thrown here: https://github.com/firebase/firebase-js-sdk/blob/dc11a27618819396944368f421dcbcb62c395f07/packages/installations/src/helpers/refresh-auth-token.ts#L49

Comment on the function indicates this function should only be called if the installation is registered, and the 2 calls that I see seem to check for that, maybe one of the checks is buggy, or maybe there is a race condition.

**Comment by DevSpareChange** [comment]
The only thing we really do is calling `initializeApp` at the beginning of our React App.

```ts
initializeApp(
    {
      apiKey: window.ENV.firebase_api_key,
      authDomain: window.ENV.firebase_auth_domain,
      projectId: window.ENV.firebase_project_id,
      storageBucket: window.ENV.firebase_storage_bucket,
      messagingSenderId: window.ENV.firebase_message_sender_id,
      appId: window.ENV.firebase_app_id,
      measurementId: window.ENV.firebase_measurement_id
    },
    { automaticDataCollectionEnabled: false }
  );
```

**Comment by DellaBitta** [comment]
Does the error occur when initializing a particiular Firebase SDK package?
