### ISSUE TITLE
Firestore read from cache is way too slow on page refresh

### ISSUE THREAD

**Issue by Merwan1010** [firebase/firebase-js-sdk#7992]
### Operating System

Mac os

### Browser Version

Chrome 120

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React / Vite / PWA / Firestore

### Describe the problem

During a refresh I want to fetch the data from the cache to populate the UI as fast as possible. 
However, when reloading a page the first fetch for a doc will take an excessive amount of time. (around 500ms)

If this is only reading data from the IndexDB why is it taking so much time ? 🤔

<img width="1103" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/42877823/26542b6d-642b-4cb7-9dc0-06892f4eb42b">

### Steps and code to reproduce issue

```typescript
const App: React.FC = () => {
  const app = initializeApp(firebaseConfig);
  initializeFirestore(app, {
    localCache: persistentLocalCache({ tabManager: persistentSingleTabManager({ forceOwnership: true }) })
  });
  connectFirestoreEmulator(getFirestore(app), 'localhost', 8080);

  const getDummyDocument = async (fromCache: boolean): Promise<{ dummy: boolean, createdAt: Timestamp } | null> => {
        
        const docRef = doc(firestore, 'dummyCollection', 'dummyDocument');
        const docSnap = fromCache ? await getDocFromCache(docRef) : await getDoc(docRef);
        return docSnap.exists() ? (docSnap.data() as { dummy: boolean, createdAt: Timestamp }) : null;
    }

  useEffect(() => {
        getDummyDocument(true)
    }, []);
  return <> </>
}
```

**Comment by ehsannas** [comment]
Hi @Merwan1010 , reading documents from cache does indeed use IndexedDB. Are you sure your timer is _just_ instrumenting the `getDocFromCache()` call?

**Comment by Merwan1010** [comment]
Hi @ehsannas yes this is only measuring the getDocFromCache() function.
This issue is only happening on reload. If I wait 1 second before making the query, this will get the document under 30ms, so the caching logic is working.

Firestore might be waiting for something to initialize before reading the cache.. 🤔

**Comment by ehsannas** [comment]
There are various things that occur before presenting query results (e.g. establishing connections to the remote endpoint, opening the indexedDb on disk, finding the list of mutations that may have happened when you were offline, etc). So I do expect it to have overhead the first time around (although 500ms seems a bit high). I also wonder whether the measurement relates to the stack you're using. Meaning, if you have a simple html+js webpage and only measure the time of `getDocFromCache()` would you observe a different outcome?

**Comment by Merwan1010** [comment]
@ehsannas Indeed I tried with a brand new react project, and the query only took 30ms.. 
I will try to figure out what is wrong with my stack. Thank you for your help.
