### ISSUE TITLE
auth/operation-not-supported-in-this-environment in Cordova application

### ISSUE THREAD

**Issue by rosendin** [firebase/firebase-js-sdk#80]
### Environment

* Operating System version: MacOS Sierra 10.12.5
* Firebase SDK version: 4.1.3
* Firebase Product: Authentication

### Problem

`firebase.auth.Auth` is returning this error on both iOS and Android Cordova platforms.

#### Steps to reproduce / Relevant Code:

A reproducible example with steps is at [this repository](https://github.com/rosendin/firebase-oauth-cordova-mcve/tree/example).

The error occurs when the app loads. The code triggering the error is nearly the same as in the [docs](https://firebase.google.com/docs/auth/web/cordova) at the bottom, "to handle the case where the app activity is destroyed before the sign-in operation completes, call getRedirectResult when your app loads.":

```javascript
firebase.auth().getRedirectResult().then(result => {
  var user = result.user
  console.log(user)
}).catch(error => {
  this.message = error.message
})
```

Since the example received this error without providing an API key, I have a full example on the master branch where you can provide an API key and install the plugins, but the error still occurs.

**Comment by bojeil-google** [comment]
The code waits for deviceready event to trigger right after auth initialization. In my tests I add it in the www/js/index.js after app initialization and it always works. In your setup it must be timing out (deviceready not triggering in the wait period). I didn't inspect your code yet as I am really swamped. Can you confirm this behavior first before I start looking into this?  I would like to solve this issue as it keeps coming up.

**Comment by rosendin** [comment]
Yes, I think it's timing out in the setup that I have. I've confirmed in this [index.html](https://github.com/rosendin/firebase-oauth-cordova-mcve/blob/test/index.html) that it works.

I have not been using any Cordova APIs yet in my project so I did not include the `deviceready` event listener. Thanks.

**Comment by bojeil-google** [comment]
Thanks for following up on this. I definitely think we can improve our docs on this.
