### ISSUE TITLE
Firebase Installations returning 404

### ISSUE THREAD

**Issue by bpfeiffer187** [firebase/firebase-js-sdk#8007]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

React JS

Firebase Installations getting 404 repose. As i understand it firebase installations, is called by firebase after the base library is initialized.

It is hitting this url: [https://firebaseinstallations.googleapis.com/v1/projects/"projectKey"/installations/"api](https://firebaseinstallations.googleapis.com/v1/projects/%22projectKey%22/installations/%22api) key"/authTokens:generate.

we get back this console error: FirebaseError: Installations: Generate Auth Token request failed with error "404 NOT_FOUND: Requested entity was not found."

This is only happening in our prod environment i haven't been able to reproduce it locally.

So wondering if anyone else ran into this.

The base firebase library is being initialized from a react js app.

We define it by:
```js
const registerFirebaseApp = (config?: FirebaseOptions): FirebaseApp | undefined => {
  if (!config || isUnitTestMode) {
    return undefined;
  }
  return initializeApp(config, config.appId);
};

export const webFirebaseApp = registerFirebaseApp(
  validateFirebaseConfig({
    apiKey: StaticConfig.firebaseApiKey,
    authDomain: StaticConfig.firebaseAuthDomain,
    projectId: StaticConfig.firebaseProjectId,
    storageBucket: StaticConfig.firebaseStorageBucket,
    messagingSenderId: StaticConfig.firebaseMessagingSenderId,
    appId: StaticConfig.firebaseAppId
  })
);
```
We Call it:
```js
const webRemoteConfig = registerRemoteConfig(webFirebaseApp);

 useEffect(() => {
    setRemoteConfigValues((currentValues) => ({...currentValues, IsLoading: true, HasError: undefined}));
    Promise.all<IncompleteRemoteConfigValues>([
      fetchRemoteConfig(webRemoteConfig),
      fetchDotEnvFeatureFlagOverrides(!isDevelopmentMode),
      fetchRemoteConfig(mobileRemoteConfig),
      fetchDotEnvFeatureFlagOverrides(isDevelopmentMode)
    ]).then((values) => {
      setRemoteConfigValues({
        ...RemoteConfigDefaults,
        ...values.reduce<IncompleteRemoteConfigValues>(
          (mergedRemoteValues, remoteValues) => ({...mergedRemoteValues, ...remoteValues}),
          {}
        ),
        IsLoading: false
      });
    });
  }, []);
```

**Comment by DellaBitta** [comment]
Hi @bpfeiffer187,

Could you check [this post](https://github.com/firebase/firebase-js-sdk/issues/7566#issuecomment-1682898721) in a similar report to see if clearing your IndexedDB cache solves your issue? Thanks!
