### ISSUE TITLE
applyActionCode succeeds using the wrong auth session

### ISSUE THREAD

**Issue by francescov1** [firebase/firebase-js-sdk#8011]
### Operating System

Web

### Browser Version

Any

### Firebase SDK Version

10.6.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React.js

### Describe the problem

We are finding that we can call applyActionCode using an auth session that does not match the user verifying their email, and the email still gets verified.

We would expect an error in this case (eg invalid verification URL). Is this expected? It gives users the impression that they are signed into their own account, when it is actually someone elses.

### Steps and code to reproduce issue

1. sign up with firebase on web
2. sign out, sign into different account
3. open email verification link. Email is now verified for original account

**Comment by NhienLam** [comment]
Hi, thank you for filing this! 

This is working as intended. We don't check for auth session before calling the API. If we call `applyActionCode` with user A's oobCode (verification code sent to the user by email), email of user A will be verified.
