### ISSUE TITLE
Upgrade from 10.6.0 to 10.7.0 or 10.8.0: no such file or directory, open 'node:stream'

### ISSUE THREAD

**Issue by PMG-VascoSaavedra** [firebase/firebase-js-sdk#8021]
### Operating System

Windows

### Browser Version

n/a

### Firebase SDK Version

10.7.0; 10.8.0

### Firebase SDK Product:

Auth, Database, Firestore

### Describe your project's tooling

React App, yarn, Jest

### Describe the problem

When updating from firebase 10.6.0 to 10.7.0/10.8.0, i get the following error when executing the Jest tests:

ENOENT: no such file or directory, open 'node:stream'
   at Runtime.readFile (../../../node_modules/jest-runtime/build/index.js:1987:21)
   at Object.<anonymous> (../../../node_modules/@fastify/busboy/lib/main.js:3:24)

This seems to be related to a change on [version 10.7.0](https://firebase.google.com/support/release-notes/js#version_1070_-_november_27_2023):

> Replaced node-fetch dependency with the latest version of undici in Node.js SDK builds for Auth, Firestore, Cloud Functions, and Storage. See [GitHub issue #7280](https://github.com/firebase/firebase-js-sdk/issues/7280).

### Steps and code to reproduce issue

I''ve created a small project to replicate the problem using firebase 10.8.0 version (all versions from 10.7.0 produce the same error):

1. Download and unzip project file: [firebase_issue.zip](https://github.com/firebase/firebase-js-sdk/files/14273267/firebase_issue.zip)
2. Install libs > yarn install
3. Run tests > yarn test

Tests will fail with the following error:
ENOENT: no such file or directory, open 'node:stream'
   at Runtime.readFile (../../../node_modules/jest-runtime/build/index.js:1987:21)
   at Object.<anonymous> (../../../node_modules/@fastify/busboy/lib/main.js:3:24)

When using version 10.6.0, the tests run successfully.

**Comment by jbalidiong** [comment]
Hi @PMG-VascoSaavedra, thank you for reaching out to us. I was able to replicate the reported behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by PMG-VascoSaavedra** [comment]
Thank you!

**Comment by PMG-VascoSaavedra** [comment]
Thank you for your analysis and feedback.

I'll look into it, and i'll get back to you once i have found a way to correct this issue!
