### ISSUE TITLE
Error (auth/network-request-failed)

### ISSUE THREAD

**Issue by jaseemuddinn** [firebase/firebase-js-sdk#8024]
### Operating System

Windows 11

### Browser Version

Version 1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit)

### Firebase SDK Version

10.8.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React and Node

### Describe the problem

Trying to check the login and signup using insomina api testing software and whenever api is being called it is showing this error: Error (auth/network-request-failed)
```
const { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword } = require('firebase/auth');
const { initializeApp } = require('firebase/app');
const { error } = require('../utils/responseWrapper');

const firebaseConfig = {
    ...
};

const app = initializeApp(firebaseConfig);
const auth = getAuth();


const signUp = async (email, password) => {
    try {
        console.log("signUp function called");
        const userCredential = await createUserWithEmailAndPassword(auth, email, password);
        console.log("inside signUp function");
        return userCredential.user;
    } catch (e) {
        // return error(400, e.message) // Propagate error for specific handling in authController.js
        console.log(e.message);
    }
};

const signIn = async (email, password) => {
    try {
        console.log("signIn function called");
        const userCredential = await signInWithEmailAndPassword(auth, email, password);
        console.log("inside signIn function");
        return userCredential.user;
    } catch (e) {
        // return error(400, e.message); // Propagate error for specific handling in authController.js
        console.log(e.message);
    }
};
```

### Steps and code to reproduce issue

npm i firebase

**Comment by jbalidiong** [comment]
Hi @jaseemuddinn, thank you for reaching out to us. Can you share the line of code where you're encountering the error? Upon checking the Insomnia API Client, this is for the REST API request. Can you also share your use-case on what you're trying to achieve using Insomnia and JS SDK.
