### ISSUE TITLE
Can't sign in to the web app via google on apple devices

### ISSUE THREAD

**Issue by morozovamv** [firebase/firebase-js-sdk#8026]
### Operating System

iOS 17.3.1; Sonoma 14.3.1

### Browser Version

Safari 17.3 (19617.2.4)

### Firebase SDK Version

13.3.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

yarn, nx, vite, react, ts, emotion

### Describe the problem

I created and deployed an app following the firebase guides ([google-signin](https://firebase.google.com/docs/auth/web/google-signin), [hosting/quickstart](https://firebase.google.com/docs/hosting/quickstart)). Then I checked how the auth works, turned out that I can't login to the app from the [auth--testing.web.app](https://auth--testing.web.app/) subdomain on my iPhone; on Mac it works only in Chrome; on my pc it works in Chrome and Edge:

| | Mac | iPhone | Win11 PC |
|--------|--------|--------|--------|
| Safari | - | - | ? |
| Chrome | + | - | + |
| Edge | ? | ? | + | 

Note: 

I also added both https://auth--testing.firebaseapp.com/__/auth/handler and https://auth--testing.web.app/__/auth/handler to the "Authorised redirect URIs" section on Google Cloud -> APIs and services -> Credentials.

Everything seem working fine under https://auth--testing.firebaseapp.com

### Steps and code to reproduce issue

The repo: [https://github.com/morozovamv/firebase-auth-testing](https://github.com/morozovamv/firebase-auth-testing)

STR:
- go to [https://auth--testing.web.app/](https://auth--testing.web.app/)
- click the "sign in" button
- follow google instructions

Expected result: user is authorized and signed in to the app
Actual result: the app opens in the initial state

**Comment by 3420580499** [comment]
I can successfully use (signInWithRedirect and getRedirectResult)  on the web

**Comment by morozovamv** [comment]
@3420580499 could you please follow the STR (steps to reproduce) on your Mac or iPhone using Safari and share a screenshot (the whole screen if possible), and show that you are signed in?

**Comment by Xiaoshouzi-gh** [comment]
This might be due to the third-party storage access issue. Seems like your case land into [option 1](https://firebase.google.com/docs/auth/web/redirect-best-practices#update-authdomain) `If you host your app with Firebase Hosting on a custom domain or a subdomain of web.app, use [Option 1](https://firebase.google.com/docs/auth/web/redirect-best-practices#update-authdomain).`.  Can you follow the instruction and try again?

**Comment by morozovamv** [comment]
> Can you follow the instruction and try again?

Sure! Initially I followed that [option 1], but I can share everything I've done to let you validate it, maybe I made a mistake.

1. Configure the Firebase JS SDK to use your custom domain as the authDomain:
```js
const firebaseConfig = {
  apiKey: "<api-key>",
  authDomain: "<the-domain-that-serves-your-app>",
  databaseURL: "<database-url>",
  projectId: "<project-id>",
  appId: "<app-id>"
};
```
Since the app is hosted on the default domain, I didn't do anything because it was also already pre-configured. These are the links to the hosted app:
<img width="714" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/19936650/ff4ff2d8-7210-4a93-8389-cdb8aa9c71f2">
My config in the code: https://github.com/morozovamv/firebase-auth-testing/blob/774c4657ea0764d487adf0566385762d78b2fd6a/src/app/auth.ts#L16

2. Add the new `authDomain` to your OAuth provider's list of authorized redirect URIs. How you do this will depend on the provider, but in general you can follow the "Before you begin" section in any provider for exact instructions (for example, the [Facebook provider](https://firebase.google.com/docs/auth/web/facebook-login)). The updated URI to authorize looks like `https://<the-domain-that-serves-your-app>/__/auth/handler` — the trailing `/__/auth/handler` is important.
Similarly, if you're using a SAML provider, add the new `authDomain` to the SAML Assertion Consumer Service (ACS) URL.

Since the app is hosted on the default domain, I again don't need to do anything because it's done by default:
<img width="670" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/19936650/4189b282-ab04-4cfb-b9c9-10589481fa9f">


3. Make sure your `continue_uri` is in the list of [authorized domains](https://console.firebase.google/project/_/authentication/settings).

Same story:
<img width="713" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/19936650/3e68e0cd-777d-42d9-b08d-65c9a2367235">

4. Re-deploy with Firebase Hosting if needed to fetch the most up-to-date Firebase configuration file hosted at `/__/firebase/init.json`.

I run `nx build && firebase deploy --only hosting`. It's done
<img width="636" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/19936650/48edfaaa-1676-470e-bae1-a080d9991a14">


Then I repeat the STR I shared in the initial message - the same result.

**Comment by Xiaoshouzi-gh** [comment]
the previous step looks good to me.  Can you let me know what page do you see after you login in with Idp? Do you see the the redirect back to your app? any error msg from the network / console?

**Comment by morozovamv** [comment]
After I login via Google, I land back to the initial page with the "login" button, because user is null in the auth state:
https://github.com/morozovamv/firebase-auth-testing/blob/main/src/app/auth.ts#L47

I recorded a video which starts after I enter my creds on the Google Login form. I don't see any error in the network/console tabs.

https://github.com/firebase/firebase-js-sdk/assets/19936650/a50c968f-aab7-4dd9-a360-b19ea70620c4

**Comment by NhienLam** [comment]
Thanks @morozovamv for the recording! I agree with https://github.com/firebase/firebase-js-sdk/issues/8026#issuecomment-1964691800 that this seems to be the third-party storage access issue and following [option 1](https://firebase.google.com/docs/auth/web/redirect-best-practices#update-authdomain) should work.

I saw you set your authDomain as `auth--testing.firebaseapp.com`. Have you tried setting it as `auth--testing.web.app`?

**Comment by morozovamv** [comment]
@NhienLam yes I've tried, there is the same issue, but with auth--testing.firebaseapp.com.
Here is the change: https://github.com/morozovamv/firebase-auth-testing/commit/0ea18f478fe7909a162a79d3457f1edf33d45e2b
So now I can login at https://auth--testing.web.app/; and I can't login at https://auth--testing.firebaseapp.com/, it even get worse because it doesn't work on all devices and browsers.

Is it possible to make it work for both https://auth--testing.web.app/ and https://auth--testing.firebaseapp.com/?

**Comment by NhienLam** [comment]
>Is it possible to make it work for both https://auth--testing.web.app/ and https://auth--testing.firebaseapp.com/?

Currently, it's not possible to make it work for both on browsers that block third-party storage access.
As you mentioned, it will work for 
- https://auth--testing.web.app when we set the `authDomain` to `auth--testing.web.app` domain 
- https://auth--testing.firebaseapp.com when we set the `authDomain` to `auth--testing.firebaseapp.com` domain

**Comment by morozovamv** [comment]
aaaah, it wasn't clear for me, thank you for clarification!
