### ISSUE TITLE
Error handling documentation is incomplete/lacking

### ISSUE THREAD

**Issue by nickdnk** [firebase/firebase-js-sdk#8030]
### Firebase SDK Product:

Messaging

### Describe your project's tooling

I realize this is probably not the right place to submit this request, but I don't really know where else to ask.

I use the raw "REST" API (https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send) to send messages to iOS/Android as there is no official PHP SDK. The community-managed PHP SDK there is doesn't support what I need it to do.

### Describe the problem

The documentation of errors is incomplete. It's almost entirely trial-and-error to figure out how errors are designed.

Looking at the documentation here (https://firebase.google.com/docs/reference/fcm/rest/v1/FcmError), it is indicated that an `error_code` property is at the root of every response, which simply isn't the case.

1. More than one error code may be returned.
1. It's nested in an object under `error.details`.
2. It's called `errorCode` - camelcase, not snakecase; I've not once seen an instance of snakecase so far.

As demonstrated by this example response:
```json5
{
  "error": {
    "code": 400,
    "message": "The registration token is not a valid FCM registration token",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "INVALID_ARGUMENT" // 2x INVALID_ARGUMENT; one nested, one root? Why?
      }
    ]
  }
}

```

I need to know which kinds of errors I can expect inside the `details` array and which error codes are to be expected under `status` in the root. It simply isn't clear where I can find which errors when looking at https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode. For instance: Does the `INTERNAL` error go in the details array or in the root? What `@type` would this error be, if it's in the details array?

I tried looking at the JS SDK, but it's kind of hard to figure out how these errors are mapped, and some of them seem to overlap with each other (such as an invalid token giving `INVALID_ARGUMENT` in both the root and the details array, but `REGISTRATION_TOKEN_NOT_REGISTERED` in the SDK being mapped by both `NOT_FOUND` and `UNREGISTERED`) - so which one is it? I can't even simulate this error as all attempts I've tried with invalid tokens just give `INVALID_ARGUMENT`, so I can't test it to figure out when this error would be returned.

From the admin SDK:
```js
  /* FCM v1 canonical error codes */
  NOT_FOUND: 'REGISTRATION_TOKEN_NOT_REGISTERED', // unregistered here
  PERMISSION_DENIED: 'MISMATCHED_CREDENTIAL',
  RESOURCE_EXHAUSTED: 'MESSAGE_RATE_EXCEEDED',
  UNAUTHENTICATED: 'THIRD_PARTY_AUTH_ERROR',

  /* FCM v1 new error codes */ // what does "new eror codes" mean? Does that mean the "canonical" ones above are no longer used?
  APNS_AUTH_ERROR: 'THIRD_PARTY_AUTH_ERROR',
  INTERNAL: 'INTERNAL_ERROR',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  QUOTA_EXCEEDED: 'MESSAGE_RATE_EXCEEDED',
  SENDER_ID_MISMATCH: 'MISMATCHED_CREDENTIAL',
  THIRD_PARTY_AUTH_ERROR: 'THIRD_PARTY_AUTH_ERROR',
  UNAVAILABLE: 'SERVER_UNAVAILABLE',
  UNREGISTERED: 'REGISTRATION_TOKEN_NOT_REGISTERED', // and unregistered here
  UNSPECIFIED_ERROR: 'UNKNOWN_ERROR',
  ```

In comparison, the legacy API has this fairly clear documentation: https://firebase.google.com/docs/cloud-messaging/http-server-ref#table9 - which adequately describes the response structure of the result, including which error codes one might encounter.

#### Update

I found some tests in the admin-node SDK, which helps a little. Apparently `UNREGISTERED` is a detail error of the type `type.googleapis.com/google.firebase.fcm.v1.FcmError` with a parent error of `INVALID_ARGUMENT`. I hope this helps to demonstrate how difficult it is to figure out.

https://github.com/firebase/firebase-admin-node/blob/5fe41189279c0a037db3fb48298a1adc657e9701/test/unit/messaging/messaging.spec.ts#L488-L506

**Comment by vanso-hubsi** [comment]
I just stumbled across the same and searching for better documentation brought me here.

> I found some tests in the admin-node SDK, which helps a little. Apparently UNREGISTERED is a detail error of the type type.googleapis.com/google.firebase.fcm.v1.FcmError with a parent error of INVALID_ARGUMENT. I hope this helps to demonstrate how difficult it is to figure out.

This also seems to not be correct: On my local tests I received parent error "INVALID_ARGUMENT" as stated above. On the staging system though, FCM unexpectedly responded with "NOT_FOUND" instead, as shown below. So I had to rework my error handling and as you said do a lot of trail-and-error.

```json
{
  "error":{
    "code":404,
    "message":"Requested entity was not found.",
    "status":"NOT_FOUND",
    "details":[
      {
        "@type":"type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode":"UNREGISTERED"
      }
    ]
  }
}
```

Also, what's not clear to me yet is if the error codes as documented [here](https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode) are a direct mapping of `"error":{"code" ...` and `"error":{"details":[{"errorCode" ...` 🤷‍♂️

**Comment by 925dk** [comment]
I fully agree, the documentation is missing/lacking. I ended up checking `error.details[0].errorCode` for `UNREGISTERED` to prune stale tokens server side.

**Comment by DellaBitta** [comment]
Hi @nickdnk, @vanso-hubsi and @925dk,

Thanks for reaching out. Unfortunately the developers of this SDK don't have the information that you're seeking about the REST API. I recommend that you [reach out to Firebase Support](https://firebase.google.com/support/troubleshooter/contact). They should be able to help you better. I'd suggest asking for a Feature Request for more documentation on a supported feature.

Thanks!
