### ISSUE TITLE
Nuxt build error with undici

### ISSUE THREAD

**Issue by emiltsang-flow** [firebase/firebase-js-sdk#8036]
### Operating System

macOS 14.1

### Browser Version

Chrome/ 121.0.6167.184

### Firebase SDK Version

10.8.0

### Firebase SDK Product:

Analytics, Auth, Installations, Performance

### Describe your project's tooling

Nuxt: 2.17.0

### Describe the problem

Failed to build with Nuxt.

[fatal] Nuxt build error
  ERROR in ./node_modules/undici/lib/cache/cachestorage.js 13:2
  Module parse failed: Unexpected character '#' (13:2)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  |    * @type {Map<string, import('./cache').requestResponseList}
  |    */
  >   #caches = new Map()
  |
  |   constructor () {
  @ ./node_modules/undici/index.js 128:27-62
  @ ./node_modules/@firebase/auth/dist/node/index.js
  @ ./node_modules/firebase/auth/dist/index.cjs.js
  @ ./plugins/firebase.js
  @ ./.nuxt/index.js
  @ ./.nuxt/server.js
  @ multi ./.nuxt/server.js

### Steps and code to reproduce issue

[fatal] Nuxt build error
  ERROR in ./node_modules/undici/lib/cache/cachestorage.js 13:2
  Module parse failed: Unexpected character '#' (13:2)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  |    * @type {Map<string, import('./cache').requestResponseList}
  |    */
  >   #caches = new Map()
  |
  |   constructor () {
  @ ./node_modules/undici/index.js 128:27-62
  @ ./node_modules/@firebase/auth/dist/node/index.js
  @ ./node_modules/firebase/auth/dist/index.cjs.js
  @ ./plugins/firebase.js
  @ ./.nuxt/index.js
  @ ./.nuxt/server.js
  @ multi ./.nuxt/server.js

**Comment by DellaBitta** [comment]
Hi @emiltsang-flow,

Some of our users have encountered errors with older resolvers pulling in the wrong package targets when building for browsers. Please see [this post in a similar thread](https://github.com/firebase/firebase-js-sdk/issues/7849#issuecomment-1857889012).

If the link doesn't help, then could you please post the minimal steps to reproduce this issue? I see that Nuxt has moved on to v3+ and their initialiation instructions aren't compatible with `v2.17.0`. Thanks!
