### ISSUE TITLE
FR: Query Firestore Document by Object Array (or, in MongoDB speak, an Array of Embedded Documents)

### ISSUE THREAD

**Issue by JonathanAsbury-Dovaxis** [firebase/firebase-js-sdk#8037]
### Operating System

Any

### Browser Version

Any

### Firebase SDK Version

10.8.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React App with WebPack.  Web Modular SDK.  

### Describe the problem

Query a Firestore document by object array.  Example document:

```js
let contact = {
 displayName: `${FirstName} ${LastName}`,
 emails: [{email: {email1}, type: 'work'}, {email: {email2}, type: 'personal'},]
 phones: [{phone: {phone1}, type: 'work'}, {phone: {phone2}, type: 'personal'},]
}
```

How do you query the Users collection to find a user by a specific email?

A Collection group query doesn't offer this for you have to know the contact we're trying to find by email.  And so far, the 'in' or array-contains-array technique doesn't seems to accept options like the following:
- `where('emails.email', 'in', {email1})`
- `where('emails.email', 'in', [{email1}])`
- `where('emails.0.email', 'in', [{email1}])  // not ideal since this will require many calls.  `

Flattening the emails and phones like the following is not idea because it limits a user can have:
```js
let contact = {
 displayName: `${FirstName} ${LastName}`,
 email1: {email1}
 email1Type: 'work'
 email2: {email2}
 ...
}
```

 Plus the query get's increasingly ugly and the count goes up.
 
If you don't support this today, what do you suggest?  

### Steps and code to reproduce issue

Create a Firestore DB as described above and try to extract a content by matching email or phone, ignoring type.
Here's MongoDB's technique:  https://www.mongodb.com/docs/manual/tutorial/query-array-of-documents/

Is there something similar in Firebase?

**Comment by JonathanAsbury-Dovaxis** [comment]
I got it to work....well, kind of.  
It's possible to query an array of objects but the entire object must match.  This is less ideal than a partial object query because one may have the email in advance but not know if, for example, it is a Work or Personal email.  But, if you have an exact match, something like the following works:
const q = query(col, where("Emails", "array-contains", {'Email': 'jon@mydomain.com', 'EmailType': 'Work'})); 

Again, unfortunately the entire object needs to match.  It's not possible to search just by email like:
const q = query(col, where("Emails", "array-contains", {'Email': 'jon@mydomain.com'})); 

And unfortunately, this also does work (for those astute and adventurous data mashers):

const q = query(col, where("Emails", "in", [{'Email': 'jon@mydomain.com', 'EmailType': 'Work'}, {'Email': 'jon@mydomain.com', 'EmailType': 'Personal'}])); 

Consequently, unless I'm missing something, organizing data has it's limits in Firebase.  Hopefully, I'm wrong.  
I look forward to hearing what you recommend.

**Comment by dconeybe** [comment]
@JonathanAsbury-Dovaxis Firestore does not support the general searching of nested fields in an array. However, in this specific example where "type" has a small, finite set of values, the desired query can be achieved using the `array-contains-any` filter or an `or` filter combined with an `array-contains` filter.

#### Example 1: finding users with the email `foo@bar.com` using `array-contains-any`

```js
import { query, where } from 'firebase/firestore';
...
const q = query(
  col,
  where('emails', 'array-contains-any', [
    { email: 'foo@bar.com', type: 'home' },
    { email: 'foo@bar.com', type: 'work' }
  ])
);
```

#### Example 2: Finding users with the email `foo@bar.com` using `or` combined with `array-contains`

```js
import { or, query, where } from 'firebase/firestore';
...
const q = query(
  col,
  or(
    where('emails', 'array-contains', {
      email: 'foo@bar.com',
      type: 'home'
    }),
    where('emails', 'array-contains', {
      email: 'foo@bar.com',
      type: 'work'
    })
  )
);
```

I believe that this answers your original question; therefore, I'm going to close this issue. But if you have further discussion or issues, please comment further or open a new issue. Thanks!
