### ISSUE TITLE
beforeCreate does not pass error code / message when throwing error but generic 47 error

### ISSUE THREAD

**Issue by reimertz** [firebase/firebase-js-sdk#8054]
### Operating System

macOS 14.2.1

### Browser Version

123.0 (64-bit)

### Firebase SDK Version

10.8.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.js App.

### Describe the problem

We are trying to show different error messages depending on why we are blocking the creation of a user but the only information available in the error is;

```
{"code":"auth/error-code:-47","customData":{},"name":"FirebaseError"}'
```

Things works as intended when running in the emulator. 

### Steps and code to reproduce issue

1. Enable blocking auth functions
2. create beforeCreate function

```
import { beforeUserCreated } from 'firebase-functions/v2/identity'
import { HttpsError } from 'firebase-functions/v2/identity'

const SIGNUP_DISABLED = true

export const beforeCreate = beforeUserCreated(async ({ data: user }) => {
  
  if (SIGNUP_DISABLED) throw new HttpsError('unavailable', 'registration is not allowed')

})
```
3. create demo frontend code
```

import {
  getAuth,
  createUserWithEmailAndPassword,
} from 'firebase/auth'



const createRandomUser = async () => {
  try {
    await createUserWithEmailAndPassword(
      getAuth(),
      'test@example.com',
      'bestpasswordever1337!',
    )
  } catch (signUpError) {
    console.log(signUpError)
  }
}

createRandomUser()
```

Then you'd get this error back

![Screenshot 2024-03-05 at 14 40 04](https://github.com/firebase/firebase-js-sdk/assets/625287/b33308e6-877f-4067-9bfb-763af35fe858)

**Comment by Xiaoshouzi-gh** [comment]
503 seems to be the working as design error codes.  Please see [this section](https://cloud.google.com/identity-platform/docs/blocking-functions#blocking_registration_or_sign-in) for error codes mapping.  Is there another  error code in the map suits your case better?

Reaching out internally to check why error msg has discrepancy for "unavailable" use case.
