### ISSUE TITLE
Bug/Error: v5.0.1 - compilation failed - 'rootDir' is expected to contain all source files.

### ISSUE THREAD

**Issue by AnthonyNahas** [firebase/firebase-js-sdk#806]
Issue with [ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)
that rely on firebase for user's authentication with firebase's project

### Environment

  * Operating System version: MacOs HighSierra
  * Firebase SDK version: 5.0.1
  * Firebase Product: auth, (firestore)

### The problem

I have recently developed  [ngx-auth-firebaseui](https://www.npmjs.com/package/ngx-auth-firebaseui) angular library built with material design to allow user's authentication with firebase.
This project rely 100% on firebase. The latest release of **ngx-auth-firebaseu**i had dependency to `firebase` `v.4.10.1 | 4.12.1 | 4.13.1`

I was planning today to update my `firebase` dependency to v.5.0.1 but it seems to be buggy...

#### Steps to reproduce:
1. clone [ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)
2. change the version of `firebase` to any v5 version like `5.0.0` or `5.0.1` in the package.json
3. run `gulp build`

and finally you will get the below error ---> 

```
/usr/local/bin/node /Users/.../ngx-auth-firebaseui/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/.../ngx-auth-firebaseui/gulpfile.js build
[21:42:26] Using gulpfile ~/Git/ngx-auth-firebaseui/gulpfile.js
[21:42:26] Starting 'clean:dist'...
[21:42:26] Starting 'clean:coverage'...
[21:42:26] Starting 'clean:build'...
[21:42:26] Finished 'clean:dist' after 2.92 ms
[21:42:26] Finished 'clean:coverage' after 1.96 ms
[21:42:26] Finished 'clean:build' after 9.28 ms
[21:42:26] Starting 'clean'...
[21:42:26] Finished 'clean' after 16 μs
[21:42:26] Starting 'build'...
[21:42:26] Starting 'compile'...
[21:42:26] Starting 'lint'...
[21:42:38] Finished 'lint' after 13 s
[21:42:38] Starting 'pre-compile'...
[21:42:38] Finished 'pre-compile' after 34 ms
[21:42:38] Starting 'inline-templates'...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[21:42:39] Finished 'inline-templates' after 211 ms
[21:42:39] Starting 'ng-compile'...
error TS6059: File '/Users/.../ngx-auth-firebaseui/node_modules/firebase/app/index.ts' is not under 'rootDir' '/Users/.../ngx-auth-firebaseui/tmp/'. 'rootDir' is expected to contain all source files.

[21:42:40] ng-compilation failed. See below for errors.

[21:42:40] undefined

Process finished with exit code 1
```

**Comment by jshcrowthe** [comment]
@AnthonyNahas if you read the error message you'll see that the `node_modules` directory containing firebase **is not** under your `rootDir` which is why the error is being thrown. This doesn't seem to be an issue w/ firebase but rather your config.

Let me know if you find any more info upon more investigation here.

**Comment by AnthonyNahas** [comment]
that was actually easy... 
the firebase had some problem with @firebase dependencies after upgrading to from `v4` to `v5`
solution:

```
$ rm -rf /node_modules package-lock.json && npm i
```

that worked for me...
