### ISSUE TITLE
It looks like you're using the development build of the Firebase JS SDK

### ISSUE THREAD

**Issue by mrmanicou** [firebase/firebase-js-sdk#807]
### [REQUIRED] Describe your environment

  * Operating System version: macOs 10.13.4
  * Firebase SDK version: 5.0.1
  * Firebase Product: __all___ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
`It looks like you're using the development build of the Firebase JS SDK...` 

How do I get rid of it?
#### Relevant Code:

Typescript
`
import * as firebase from 'firebase';
import 'firebase/auth';
import 'firebase/firestore';
`

**Comment by jshcrowthe** [comment]
@mrmanicou when you do the following, you include **all** of firebase in your app (which is likely more than you need and is bloating your app size!):

```typescript
import firebase from 'firebase';
```

Instead, if you do the following, you can remove the error and trim down your app size!

```typescript
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
```

**Comment by devpascoe** [comment]
If i perform the above i get the console error ... ever since the 5.x releases

import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';

even if all i include is import firebase from 'firebase/app';

I have uninstalled, deleted the folder from node_modules etc.. fresh install and still same result. App works fine, just annoying message.

**Comment by jshcrowthe** [comment]
Hey @devpascoe, if you could file another issue with a sample illustrating your use case that'd help us get it fixed!

**Comment by nickjuntilla** [comment]
This is still an issue. Is there a problem in still using firebase.auth after importing like 

`import 'firebase/auth';`

Do you still use auth like firebase.auth? What is triggering the warning. It's in production too, which is not good.

**Comment by abhi1030** [comment]
# I was getting the same error when i was using firebase auth in my Angular project.
## previously imported as:
            import { auth } from 'firebase';

## It is fixed by simply adding   "/app"  after firebase like this:
            import { auth } from 'firebase/app';

**Comment by lmenus** [comment]
@abhi1030 Fixes the same issue in React projects, thanks!

**Comment by WorldofDataScience** [comment]
What about **CDN**? Only importing the following: 

`<script src='https://www.gstatic.com/firebasejs/5.8.1/firebase.js'></script>
    <script src='https://www.gstatic.com/firebasejs/5.8.0/firebase-app.js'></script>
    <script src='https://www.gstatic.com/firebasejs/5.0.0/firebase-storage.js'></script>
    <script src='https://www.gstatic.com/firebasejs/5.8.0/firebase-auth.js'></script>`

Still gives the warning in the console: 

_It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the CDN builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

https://www.gstatic.com/firebasejs/5.0.0/firebase-<PACKAGE>.js_

**Comment by naveenkash** [comment]
if i import firebase like that then how do i use firebase and make firestore db
import firebase from 'firebase/app';
import 'firebase/firestore';
