### ISSUE TITLE
"302 found" for react-web firebase event on chrome instead of firefox/edge.

### ISSUE THREAD

**Issue by lifeike** [firebase/firebase-js-sdk#8080]
### Operating System

Linux/Windows

### Browser Version

Version 122.0.6261.128 (Official Build) (64-bit)

### Firebase SDK Version

"firebase": "^9.22.1",

### Firebase SDK Product:

Analytics

### Describe your project's tooling

react app with webpack and jest

### Describe the problem

I have a view_item google analytics event to send "project detail" data to ga4.

this "POST" request has "302 found" error on chrome. However, firefox/edge works fine which return "204 no content".

### Steps and code to reproduce issue

1. open production URL: https://portal.karbon-x.com
2. click "onetime sponsorship" blue button to go to project list page
3. open chrome dev console, network tab, filter request by "google-analytics" to get all google analytics request
4. click  ”view details“ button on any project card
5. look into request details, this request will return "302 found" error on chrome, however, firefox/edge works fine.

**Comment by DellaBitta** [comment]
Hi @lifeike,

This group doesn't have direct insights into server response codes for particular calls. I recommend upgrading your Firebase JS SDK version to see if it persists, and to also reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) so that someone can look into why this issue occurs in the backend. Thanks!

**Comment by lifeike** [comment]
> Hi @lifeike,
> 
> This group doesn't have direct insights into server response codes for particular calls. I recommend upgrading your Firebase JS SDK version to see if it persists, and to also reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) so that someone can look into why this issue occurs in the backend. Thanks!

hi DellaBitta and everyone, I have already updated to latest version, and this error persists.

I will contact "Firebase Support" and post updates for someone else who run into same issue in the future.

Although this bug report is closed. Please reply me here if someone have ever solved this problem before, thx
