### ISSUE TITLE
How to disable reCAPTCHA while using firebase/auth

### ISSUE THREAD

**Issue by VladislavSorokin-sy** [firebase/firebase-js-sdk#8084]
### Operating System

Mac OS 

### Browser Version

Chrome 122

### Firebase SDK Version

10.4.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Chrome extension, manifest v3, built with webpack

### Describe the problem

firebase/auth is injecting [recaptcha/enterprise.js](https://www.google.com/recaptcha/enterprise.js) which violates Google Store policy of not having remote code in the extension. 

I am trying to understand how to build my extension without including reCAPTCHA and comply with store policies

### Steps and code to reproduce issue

just build the app that uses firebase/auth and inspect compiled code, there will be reference to injected script

**Comment by DellaBitta** [comment]
Hi @VladislavSorokin-sy,

We have a separate SDK entry point for the use of Firebase Auth in Google web extensions. Please see the guide [Authenticate with Firebase in a Chrome extension](https://firebase.google.com/docs/auth/web/chrome-extension). I hope this helps!
