### ISSUE TITLE
FirebaseError: Initialization of query failed

### ISSUE THREAD

**Issue by vojto** [firebase/firebase-js-sdk#8087]
### Operating System

iPad

### Browser Version

Latest

### Firebase SDK Version

10.8.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React, Next.js, Capacitor

### Describe the problem

In Sentry, we're seeing a lot of errors like this one:

```
FirebaseError: [code=unavailable]: Initialization of query 'Query(target=Target(graphs/xx/notes, filters: [updated_at >= time(1710758459,216000000)], orderBy: [updated_at (asc), __name__ (asc)]); limitType=F)' failed: IndexedDbTransactionError: [code=unavailable]: IndexedDB transaction 'Allocate target' failed: UnknownError: Connection to Indexed Database server lost. Refresh the page to try again [object Object]
```

This seems to be affecting only a handful of users, but generating a ton of events. Here is the log for the past week:

![image](https://github.com/firebase/firebase-js-sdk/assets/50943/1ea61fd1-3dbf-4a1c-b7e9-2c8de95e9f9a)

From Sentry tags, it looks like this issue affects **mainly iPad users** on mobile Safari.  We're seeing this problem affecting users both on our Capacitor iPad app, and directly through iPad Safari.

Sadly, we don't have much more info, as we haven't been able to reproduce this one.

### Steps and code to reproduce issue

No reproduction so far

**Comment by tom-andersen** [comment]
Thank you for the report. I will look into this as soon as possible.

**Comment by vojto** [comment]
> This appears to be a duplicate of #8068

It is not - this is a different issue.
