### ISSUE TITLE
Erroneous behavior when app is started while offline

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-js-sdk#81]
### [REQUIRED] Describe your environment

  * Operating System version: n/a
  * Firebase SDK version: 4.1.3
  * Firebase Product: database

### [REQUIRED] Describe the problem
If a web app is started while the device is offline (for example if it's cached via service workers, or a Cordova app) the SDK doesn't properly initialize.
When the app regains connectivity. all the subsequent long polling requests (`https://the-nss-server.firebaseio.com/.lp?...`) return with a  status of `400 Bad request`, and the attempted web socket connection is immediatley closed.

Once the app is in that state, not even refreshing the page fixes it. After a while, though, it seems to sort itself out and reconnects.

#### Steps to reproduce:
1. `git clone https://github.com/firebase/quickstart-js.git`
2. `cd quickstart-js/database`
3. Create a new project, allow write from anyone to the database, enable Google auth
4. `firebase use --add` and select the new project
5. `firebase serve`
6. While still online go to http://localhost:5000 and check that everything works as expected
7. Close the app
8. Go offline, either by disabling the network adapter or by any other means (checking "Offline" in dev-tools is not an option here since we still want to access the local server)
8. Open the app again. Long polling connections will fail to connect as expected.
9. Go online
10. Notice that all long polling requests fail with a 400 status, websocket is immediately closed

#### Relevant Code:
n/a

**Comment by mikelehen** [comment]
Thanks for the report.  I believe this was actually due to https://status.firebase.google.com/incident/Realtime%20Database/17057 which has since been fixed, so the issue should no longer appear.  If you continue to have issues, please do let us know!

**Comment by jsayol** [comment]
Yep, it's working fine now. Thanks Mike!
