### ISSUE TITLE
Couldn't upload a buffer to firebase storage

### ISSUE THREAD

**Issue by EssaadaniYounes** [firebase/firebase-js-sdk#8103]
### Operating System

Window 10

### Browser Version

Chrome

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Storage

### Describe your project's tooling

ExpressJS with typescript and sharp

### Describe the problem

I'm having a task as follow
- You give the API a image URL you get this image URL data as ArrayBuffer using axios
- Take the ArrayBuffer and pass it to sharp to resize the image
- Store the result from sharp (a Buffer ) in firebase storage

### Steps and code to reproduce issue

#Upload buffer to firebase storage

**Comment by EssaadaniYounes** [comment]
![code](https://github.com/firebase/firebase-js-sdk/assets/85531385/e7d772c3-503e-4aca-a6dd-d6d76d6d31ea)
I hope this image describe the steps and what i did

**Comment by hsubox76** [comment]
1. What is the error message?
2. You're mentioning you're using ExpressJS. Is this a Node project? Would it make more sense to use `firebase-admin`?

**Comment by EssaadaniYounes** [comment]
> 1. What is the error message?
> 2. You're mentioning you're using ExpressJS. Is this a Node project? Would it make more sense to use `firebase-admin`?

The error is when I'm visiting firebase storage and i click on the image to preview it i got no preview available instead of actual image.

And yeah it's a node project and the same issue with firebase admin

**Comment by dlarocque** [comment]
Hi @EssaadaniYounes 

Could you try modifying your sharp code to be:
```javascript
const sharped = await sharp(image)
  .raw()
  .ensureAlpha()
  .resize(size.width, size.height, { fit: "inside" })
  .jpeg() // Write it in jpeg format https://sharp.pixelplumbing.com/api-output#jpeg
  .toBuffer({ resolveWithObject: true });
```

I have reproduced your error locally, and found the same preview error you encountered. Adding the jpeg() call fixed the issue for me.

If you are still having issues viewing the preview, try writing the file to disk with `toFile()`, and make sure you can open that locally. If you are able to open it locally, and it still fails to preview in storage, please send us the code as well as the image.
