### ISSUE TITLE
isPlainObject validation fails with Object.create(null)

### ISSUE THREAD

**Issue by saranrapjs** [firebase/firebase-js-sdk#811]
### Describe your environment

  * Operating System version: Mac OS X
  * Firebase SDK version: latest
  * Firebase Product: database

### Describe the problem

When trying to store Objects that have been created with `Object.create(null)`, these objects will [fail input validation](https://github.com/firebase/firebase-js-sdk/blob/53d15106091470b80c4a1d5de4dce9801488ee9b/packages/firestore/src/util/input_validation.ts#L292) because their prototype is not the `Object.prototype`.

Using `Object.create(null)` is a relatively common pattern for creating "safe" dictionaries that are nonetheless plain objects; it looks like other libraries' implementations of `isPlainObject` [_don't_ return false for objects created this way](https://github.com/lodash/lodash/blob/b36f21cbaff7c885223b44267c70e6711b754af6/isPlainObject.js#L27). Particularly in cases where libraries that create objects via `Object.create(null)`, this current implementation of this type checking results in extra copying (e.g. an `Object.assign`) in a case where it doesn't seem like it should.

For what it's worth, I'd be happy to contribute a patch, if addressing this is something you'd consider adding to the SDK!

#### Relevant Code:

Reproduced issue:
https://stackblitz.com/edit/firebase-issue-sandbox-zebjuw

```javascript
const db = firebase.firestore();
db.collection("cities").doc("LA").set(Object.create(null))
```

**Comment by mikelehen** [comment]
@saranrapjs Whoops! I think that is indeed an oversight. Thanks for raising it. A patch would be welcome! :-)

**Comment by mikelehen** [comment]
@schmidt-sebastian FYI- We have the same bug here: https://github.com/googleapis/nodejs-firestore/blob/84f56b49e69d7c298671ef8565e8c381a3db5321/src/document.js#L1653
