### ISSUE TITLE
onAuthStateChanged gives the user after a long time on app reloads

### ISSUE THREAD

**Issue by stee1ix** [firebase/firebase-js-sdk#8118]
### Operating System

Android 14

### Browser Version

React Native

### Firebase SDK Version

10.10.0

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

Bare React Native

### Describe the problem

When doing a fresh signInWithEmailAndPassword, the onAuthStateChanged fires and gives the user quickly, but after killing the app and starting again the persisted user takes 20-30secs to be returned, even on hot reloads. Has anyone experienced this issue as well. Please help, it's urgent.

### Steps and code to reproduce issue

Listener:
onAuthStateChanged(auth, user => {
      console.log(user);
      if (user) {
        setUser(user)
      } else {
        setUser(null);
      }
    });

Initialization:
const createFirebaseApp = () => {
  let app;
  let auth;
  if (getApps().length === 0) {
    app = initializeApp(config);
    auth = initializeAuth(app, {
      persistence: getReactNativePersistence(ReactNativeAsyncStorage)
    });
  } else {
    app = getApp();
  }

  return { app, auth };
};
const { app, auth } = createFirebaseApp();

export const firestore = getFirestore(app);
export { auth };

**Comment by MichaelVIU** [comment]
I have the same experience - but only for one account (one day it works, the other day it does not).
After deleting the application storage, the behavior disappears.
<img width="200" alt="Bildschirmfoto 2024-04-05 um 15 18 12" src="https://github.com/firebase/firebase-js-sdk/assets/10629779/37dd7d3e-46c6-41ed-902a-0b8649d763fb">

But the code got stuck at onAuthStateChanged - no idea why.

**Comment by bhparijat** [comment]
@stee1ix Could you please try clearing application storage and see if the issue still persists?

**Comment by stee1ix** [comment]
@MichaelVIU I'm facing the problem in React Native
