### ISSUE TITLE
isSupported returns false positive

### ISSUE THREAD

**Issue by ptahchiev** [firebase/firebase-js-sdk#8129]
### Operating System

iOS  v 17.3

### Browser Version

Safari 

### Firebase SDK Version

10.10.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

React app with webpack

### Describe the problem

I'm trying to develop push notifications with FCM. Here's part of the code:
```
import { getMessaging, onMessage, getToken, isSupported } from "firebase/messaging";
....
try {
  if (isSupported) {
    console.log('is supported');
      // Retrieve Firebase Messaging object
      messaging = getMessaging(app);
  }
} catch (e) {
  console.error(e)
}
```
As you can see I'm using `isSupported`. However in the log  I can see that `is supported` is printed and then an error is thrown: `This browser does not support the APIs required to use the Firebase SDK`.
![Screenshot from 2024-04-05 16-29-32](https://github.com/firebase/firebase-js-sdk/assets/5320045/f90340ba-9773-4f5f-8ed4-22dd01fedf96)

If I comment the snippet then no error is thrown and nothing is logged in the console.

### Steps and code to reproduce issue

Just call `isSupported` on iOS and you will see it returns `true`

**Comment by jbalidiong** [comment]
Hi @ptahchiev, thanks for bringing this to our attention. I tried replicating, but I wasn't able to reproduce the error. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by DellaBitta** [comment]
Just checking to ensure that your code is correct.

Are you invoking `if(isSupported())` or just checking if it's defined `if(isSupported)`. Looks like the latter is in the test case above.

Thanks!

**Comment by ptahchiev** [comment]
Here's  a reproducible site:
https://ptahchiev.github.io/test-firebase/
with repository:
https://github.com/ptahchiev/test-firebase/
and result:
![image](https://github.com/firebase/firebase-js-sdk/assets/5320045/44fe84f1-e83d-44f1-b92a-bf7685ccd9eb)

**Comment by jbalidiong** [comment]
Thanks for the minimal repro, @ptahchiev. I was able to replicate the behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by hsubox76** [comment]
I'm not able to get an iOS emulator running at the moment to repro this, but I think the problem is that `isSupported()` is an async function, so you would have to do `if (await isSupported())`. In your sample code, the value of `isSupported()` isn't actually `true`, it's a promise, which is truthy, which always causes your `if` to pass. If you logged the value of `isSupported()` instead of the string "isSupported() is true", this would show up.

Can I ask what documentation guide or tutorial you used for adding `isSupported()`? I want to make sure we didn't make a mistake and we add `await` if needed.

**Comment by hsubox76** [comment]
Can you provide a repro like the original poster did?

**Comment by zwu52** [comment]
Is your manifest configured correctly  with `{ "display": "standalone" } // or {"display": "fullscreen"}`? (more in https://firebase.blog/posts/2023/08/fcm-for-safari/)

**Comment by CalvinJamesHeath** [comment]
Same issue here for Safari IOS, it returns true but I get "Can't find variable: Notification", it the website is added to the frontscreen then it works fine.

**Comment by hsubox76** [comment]
Can you open a new issue and provide a minimal repro or code snippet? Let's isolate this from the original issue (which seems to be incorrect usage) so we can focus on what's going wrong in your specific situation.
