### ISSUE TITLE
Error " dependent-sdk-initialized-before-auth" received when calling `getAuth`

### ISSUE THREAD

**Issue by GogoVega** [firebase/firebase-js-sdk#8133]
### Operating System

MacOS 14.2.1

### Browser Version

Safari/17.2.1

### Firebase SDK Version

10.10.0 (Node/JsCore/10.10.0/FirebaseCore-web)

### Firebase SDK Product:

Auth, Database

### Describe your project's tooling

My project consists of using the RTDB, to do this I initialize an app, I authenticate, and I retrieve the database.

### Describe the problem

I always get the error in `_errorFactory`
```
dependent-sdk-initialized-before-auth : 'Another Firebase SDK was initialized and is trying to use Auth before Auth is initialized. Please be sure to call `initializeAuth` or `getAuth` before starting any other Firebase SDK.'
```
when trying to get the `Auth` object.

I don't know from which version this appeared.

### Steps and code to reproduce issue

```js
const app_1 = require("firebase/app");
const auth_1 = require("firebase/auth");
const database_1 = require("firebase/database");

const app = app_1.initializeApp({
    apiKey: "AIza........",
    databaseURL: "https://my-project-default-rtdb.firebaseio.com/",
}, "someName");
const auth = auth_1.getAuth(app);
const database = database_1.getDatabase(app);
```

**Comment by bhparijat** [comment]
Hi, can you share what line throws this error? is it `database_1.getDatabase(app);` ?

**Comment by GogoVega** [comment]
It's the correct line, the error is not thrown, this error message is in the `_errorFactory.errors` object when I inspect the `auth` object. However the following line (getDatabase) throws the error `Firebase: Error (auth/admin-restricted-operation)`.

```
FirebaseError: Firebase: Error (auth/admin-restricted-operation).
    at createErrorInternal (/Users/gauthierdandele/Documents/Programmation/Firebase/node-red-contrib-firebase/node_modules/@firebase/auth/dist/node/totp-ed04dddc.js:520:55)
    at _fail (/Users/gauthierdandele/Documents/Programmation/Firebase/node-red-contrib-firebase/node_modules/@firebase/auth/dist/node/totp-ed04dddc.js:488:31)
    at /Users/gauthierdandele/Documents/Programmation/Firebase/node-red-contrib-firebase/node_modules/@firebase/auth/dist/node/totp-ed04dddc.js:989:29
    at step (/Users/gauthierdandele/Documents/Programmation/Firebase/node-red-contrib-firebase/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/gauthierdandele/Documents/Programmation/Firebase/node-red-contrib-firebase/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/Users/gauthierdandele/Documents/Programmation/Firebase/node-red-contrib-firebase/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'auth/admin-restricted-operation',
  customData: {}
}
```

**Comment by DellaBitta** [comment]
Does this issue persist if you await the auth state?

`await auth.authStateReady();`

Thanks!

**Comment by GogoVega** [comment]
Yes, I still get the error.

Sorry, I confused the line that throws the error (one is missing) - it's the `signInAnonymously` line that throws the `auth/admin-restricted-operation` error. Everything else is correct.

```js
const app_1 = require("firebase/app");
const auth_1 = require("firebase/auth");
const database_1 = require("firebase/database");

(async function () {
	const app = app_1.initializeApp({
		apiKey: "AIza...",
		databaseURL: "https://my-project-default-rtdb.firebaseio.com/",
	}, "someName");
	const auth = auth_1.getAuth(app);
	await auth.authStateReady();
	const user = await auth_1.signInAnonymously(auth);
	const database = database_1.getDatabase(app);
}());
```

**Comment by DellaBitta** [comment]
Is Anonymous sign in enabled as an Authentication sign in method for your project in the Firebase Console? It's disabled by default, I believe.

**Comment by GogoVega** [comment]
Interesting, you are right, I thought that was the problem.

So let's go straight to the main problem which is that the following line returns me an empty array even though the email is registered and the method enabled.

```js
...
const auth = auth_1.getAuth(app);
await auth.authStateReady();
console.log(await auth_1.fetchSignInMethodsForEmail(auth, "my-email@test.com")); // Returns []
...
```
