### ISSUE TITLE
Cannot invoke HttpsCallable functions on Safari

### ISSUE THREAD

**Issue by gpawlik-cais** [firebase/firebase-js-sdk#8157]
### Operating System

Ventura 13.2

### Browser Version

Safari 16.3

### Firebase SDK Version

9.12.1

### Firebase SDK Product:

~Firestore~ Functions

### Describe your project's tooling

React web (Expo)

### Describe the problem

In Safari when invoking a callable function created with `httpsCallable` method, the promise never get resolved. In Chrome it works perfectly fine.

### Steps and code to reproduce issue

Follow the example from the docs: https://firebase.google.com/docs/functions/callable?gen=1st

Open Safari and check that it does not work

**Comment by gpawlik-cais** [comment]
On localhost the function is being invoked correctly, actually I see the function URL in the Network tab (even that it is not defined as a HTTP function). Once again - it is only a Safari issue.

**Comment by dconeybe** [comment]
Note: Updated "Firebase SDK Product" in the OP to specify "Functions" (rather than "Firestore") since this issue seems to be related to the Functions product.
