### ISSUE TITLE
Support offline memoryLocalCache persistence for node

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-js-sdk#8167]
regarding https://github.com/firebase/firebase-js-sdk/issues/6945, is `initializeFirestore(app, {localCache: memoryLocalCache()})` supported in node and does it avoid the additional costs on reconnection as described [here](https://firebase.google.com/docs/firestore/pricing?authuser=0#listens)?

(This would of ideally been a comment on https://github.com/firebase/firebase-js-sdk/issues/6945 but its locked)

**Comment by dconeybe** [comment]
Yes, `memoryLocalCache()` is supported in node; however, to get the cost savings as described in the linked article you need to enable LRU garbage collection (the default is _eager_ garbage collection).

Here is a code sample, for clarification:

```ts
import { getApp } from 'firebase/app';
import { initializeFirestore, memoryLocalCache, memoryLruGarbageCollector } from 'firebase/firestore';

...

const db = initializeFirestore(getApp(), {
  localCache: memoryLocalCache({garbageCollector: memoryLruGarbageCollector()})
});
```

Although it may be obvious by its naming, the cache is in-memory and lost upon process termination. So each new process will incur the full cost of the query upon startup.

I should also mention that node support is primarily intended for unit and integration testing, and not production applications.

**Comment by dconeybe** [comment]
After talking with the team, I wanted to clarify an incorrect statement that I made in my previous comment. I had said

> node support is primarily intended for unit and integration testing, and not production applications.

This statement was not true. We fully support using the Firestore components of the Firebase JS SDK in a Node runtime. Some such use cases include unit and integration testing, as well as server-side rendering applications. In fact, our entire suite of unit and integration tests all pass in Node and in a browser. What we _don't_ officially support in using a persistent disk cache (i.e. local storage and indexeddb) in a Node environment. There are some ways to hack it in, such as we do during our integration tests (https://github.com/firebase/firebase-js-sdk/blob/4be78a3d287ab8f7b805bf9c535f7018aba4564b/packages/firestore/test/util/node_persistence.ts) but support for this is done on a best-effort basis.

**Comment by nbransby** [comment]
Thanks for solution and the clarification!
