### ISSUE TITLE
Expo: Unable to resolve "./index.shared" from "node_modules/@firebase/auth/dist/index.rn.d.ts"

### ISSUE THREAD

**Issue by michalpawlowski34** [firebase/firebase-js-sdk#8169]
### Operating System

macOS Sonoma 14.4.1

### Browser Version

Expo 50.0.14 | iOS 17.4

### Firebase SDK Version

10.11.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Expo

### Describe the problem

`Unable to resolve "./index.shared" from "node_modules/@firebase/auth/dist/index.rn.d.ts"`

Navigating through VSC I can view the file by the import correctly.
Even after commenting the line `export * from './index.shared';` the error log indicates the next line `export { PhoneAuthProvider } from './src/platform_browser/providers/phone';` as also - unable to resolve file.

This happens on iOS both Simulator and iPhone and on Android.

### Steps and code to reproduce issue

```
// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { initializeAuth, getReactNativePersistence } from "firebase/auth";
import ReactNativeAsyncStorage from "@react-native-async-storage/async-storage";
// import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {

};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
// const analytics = getAnalytics(app);
export const auth = initializeAuth(app, {
  persistence: getReactNativePersistence(ReactNativeAsyncStorage),
});
export const db = getFirestore(app);
```

**Comment by michalpawlowski34** [comment]
So eventually after changing the auth initialization to `getAuth` therefore removing persistance the error is gone.

**Comment by NhienLam** [comment]
Hi, thank you for your update. Since the error is gone, I will be closing this issue. Feel free to reopen if you have anymore questions or concerns. Thank you!

**Comment by cfiekert** [comment]
I'm still encountering this issue. Surely avoiding the issue by removing persistence is not a viable fix.
Below is my similar Firebase configuration:
```
import ReactNativeAsyncStorage from '@react-native-async-storage/async-storage';
import { getAnalytics } from 'firebase/analytics';
import { initializeApp } from 'firebase/app';
import { initializeAuth, getReactNativePersistence } from 'firebase/auth';
import { getDatabase } from 'firebase/database';

// Initialize Firebase
const firebaseConfig = {

};

export const FIREBASE_APP = initializeApp(firebaseConfig);
export const FIREBASE_AUTH = initializeAuth(FIREBASE_APP, {
  persistence: getReactNativePersistence(ReactNativeAsyncStorage),
});
export const FIREBASE_DB = getDatabase(FIREBASE_APP);
// export const FIREBASE_ANALYTICS = getAnalytics(FIREBASE_APP);
```
Could this be partially related to the path declaration required in tsconfig.json for React Native?
```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,

    "baseUrl": "./",
    "paths": {
      "@firebase/auth": ["./node_modules/@firebase/auth/dist/index.rn.d.ts"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"]
}
```
