### ISSUE TITLE
Auth: ES modules build

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-js-sdk#818]
### Environment

  * Operating System version: any
  * Firebase SDK version: 5.0.2
  * Firebase Product: auth

### The problem

`auth` package does not include an ES modules build

#### Steps to reproduce:

Install `@firebase/app` and use it in a project aimed for module-aware browsers, e.g. Polymer 3 application. Observe an error in the console:
```
Uncaught ReferenceError: require is not defined
    at auth.js:2
    [...]
```

The issue is caused by a lack of ES module build of the library (no valid output file and no `module` field in a `package.json`.

#### Relevant Code:
```javascript
import firebase from '@firebase/app';
import '@firebase/auth';
```

**Comment by merlinnot** [comment]
I made a PR to add one, but there is something funky going on with Travis. There is some process which does not exit, but I have trouble identifying which one is it. I probably won't have time to dig deeper for a next few days.

**Comment by salah-saleh** [comment]
Hi Merlinnot, sorry to bug you but any progress here?

**Comment by okydk** [comment]
Had a similar issue, but all is working in latest build (firebase@5.0.4).
```javascript
import firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/firestore'
import 'firebase/storage'
```

**Comment by merlinnot** [comment]
Hi, thanks for the ping, kinda forgot about it. I'll give it another shot right now.

**Comment by merlinnot** [comment]
Status update: found a 🐛, now 🛠.

**Comment by merlinnot** [comment]
Fixed, now waiting for a review.

**Comment by salah-saleh** [comment]
@okydk still not working for me even with 5.0.4

**Comment by davie-robertson** [comment]
the other work-around is in #815
