### ISSUE TITLE
getDoc() is never resolved nor rejected using Remix and Firestore Lite

### ISSUE THREAD

**Issue by jdgamble555** [firebase/firebase-js-sdk#8195]
### Operating System

Windows 11, Vercel Production

### Browser Version

Chrome 124.0.6367.61

### Firebase SDK Version

10.11.0

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Remix does not resolve on regular `getDoc` path. I am using the latest version of Remix, although there is a [rollup bug](https://github.com/remix-run/remix/issues/9276#issuecomment-20682766310) so I had to override the latest version in package.json.
```ts
"overrides": {
  "rollup": "4.15.0"
}
```

### Describe the problem

Everything works find and resolves as expected when using `firebase/firestore`, but when switching to `firebase/firestore/lite`, the path does not resolve. I believe it is related to the [same issue here](https://github.com/firebase/firebase-js-sdk/issues/7911).

### Steps and code to reproduce issue

Create a new Remix project and with a path `about`. Fetch a document using the loader and `firebase/firestore`. Make sure that works. Now switch to `firebase/firestore/lite` and you will see it never resolves.

### Debug Info
```
[2024-04-22T13:05:29.729Z]  @firebase/firestore: Firestore (10.11.0_lite): RestConnection Sending RPC 'BatchGetDocuments' 0x23ee4115: https://firestore.googleapis.com/v1/projects/test-projects-19046/databases/(default)/documents:batchGet {
  documents: [
    'projects/test-projects-19046/databases/(default)/documents/about/ZlNJrKd6LcATycPRmBPA'
  ]
}
```

Here is the test repo (need to add any Firebase credentials):

https://github.com/jdgamble555/remix-firebase-test/blob/master/app/lib/about.server.ts

https://github.com/jdgamble555/remix-firebase-test

The test deployed version (deployed working without Lite):

https://remix-firebase-test.vercel.app/

J

**Comment by cherylEnkidu** [comment]
Hi @jdgamble555 

Could you please try to use lite SDK directly without Remix and check if you are running into same problem?

**Comment by hsubox76** [comment]
Following the linked issue in Remix, it looks like it is in fact a Remix issue (trying an experimental flag in Remix fixes this issue). I'll close this for now, notify us to reopen it if there turns out to be an error on our end.
