### ISSUE TITLE
The accessToken property is missing in the User interface

### ISSUE THREAD

**Issue by NicolasPlanas1998** [firebase/firebase-js-sdk#8209]
### Operating System

iOS 16.4

### Browser Version

Google Chrome 124.0.6367.79 

### Firebase SDK Version

10.11.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

React App with Typescript

### Describe the problem

The accessToken property is present in the User obj but is missing from the [User interface](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L21-L81) and also the [documentation](https://firebase.google.com/docs/reference/js/auth.user)

### Steps and code to reproduce issue

```
  signInWithEmailAndPassword(auth, email, password).then((res) => {
      const token = res.user.accessToken;
    });
```

Error : `Property 'accessToken' does not exist on type 'User'.ts(2339)`

**Comment by jbalidiong** [comment]
Hi @NicolasPlanas1998, thanks for bringing this to our attention. I found a similar issue about this and I recommend following the suggestion of one of our engineers on how to retrieve the accessToken:

>There are 3 tokens at play here:
>- The Firebase ID token (publicly exposed via user.getIdToken()).
>- The Firebase refresh token (not exposed to client code via interface, and won't ever be made easily accessible)
>- OAuth providers' accessToken field. This is provided by the OAuth credential itself but is not stored on the User object

I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
