### ISSUE TITLE
Analytics Consent not sent on update

### ISSUE THREAD

**Issue by megamisan** [firebase/firebase-js-sdk#8210]
### Operating System

Windows 11 23H2

### Browser Version

Edge 124.0.2478.51

### Firebase SDK Version

10.11.0

### Firebase SDK Product:

Analytics, AppCheck, Auth, Firestore, Functions, Storage

### Describe your project's tooling

Vue.js app.

### Describe the problem

I'm trying to get analytics to work with consent banner and sending advanced consent information with the `setConsent` method.

### Steps and code to reproduce issue

In the projet, initialize Firebase first. I consider `app` to be a constant containing the firebase application instance in the following snippet:

```js
import { setAnalyticsCollectionEnabled, setConsent } from 'firebase/analytics'

const analytics = app.analytics()
// Add some delay to wait for gtag loading
setTimeout(() => {
  console.log('Called')
  setAnalyticsCollectionEnabled(this._analytics, consent)
  setConsent({
    ad_personalization: 'denied',
    ad_storage: 'denied',
    ad_user_data: 'denied',
    analytics_storage: 'granted',
    functionality_storage: 'granted',
    personalization_storage: 'denied',
    security_storage: 'granted',
  })}, 5000)
```

Using [Tag Assitant](https://tagassistant.google.com/), I can see the tag events. However, I get this result:
![image](https://github.com/firebase/firebase-js-sdk/assets/12088094/89527775-5153-49ed-a763-33b46696878c)

The granted value is missing and there is strange numbered items.

Doing a some step-by-step debugging, I found the call to gtag. The third parameter which should be the `ConsentSettings` (see [Set up consent mode on websites](https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#update-consent) is set to the second parameter `update` instead of the third.
![Debug screenshot](https://github.com/firebase/firebase-js-sdk/assets/12088094/8ea37c5c-1068-4c8a-baf3-9643a09b820e)

The `setConsent` method code is here [packages/analytics/src/api.ts#L768](https://github.com/firebase/firebase-js-sdk/blob/7709f1016d6e491847bb4e8e4c731603d47f7eae/packages/analytics/src/api.ts#L768).
It trigger the call to the gtagWrapper function with this line:
```js
wrappedGtagFunction(GtagCommand.CONSENT, 'update', consentSettings);
```
The `wrappedGtagFunction` is an instance of the `gtagWrapper` function found in [packages/analytics/src/helpers.ts#L279](https://github.com/firebase/firebase-js-sdk/blob/7709f1016d6e491847bb4e8e4c731603d47f7eae/packages/analytics/src/helpers.ts#L279).

When the method is called before initialization of `gtag`, the call is made correctly. `setContent` sends the settings to `_setConsentDefaultForInit` and the [packages/analytics/src/initialize-analytics.t:`_initializeAnalytics`s#L129](https://github.com/firebase/firebase-js-sdk/blob/7709f1016d6e491847bb4e8e4c731603d47f7eae/packages/analytics/src/initialize-analytics.ts#L129) function use these settings correctly.

I see two possible fixes:
* Removing the `'update'` parameter in `setConsent`, thus the diff: 
  ```patch
  @@ -766,5 +766,5 @@
    // Check if reference to existing gtag function on window object exists
    if (wrappedGtagFunction) {
  -    wrappedGtagFunction(GtagCommand.CONSENT, 'update', consentSettings);
  +    wrappedGtagFunction(GtagCommand.CONSENT, consentSettings);
    } else {
      _setConsentDefaultForInit(consentSettings);
  ```
* Retrieves the second argument from the args array.

I recommend the first option.

Original commits:
* [Feature introduction](https://github.com/firebase/firebase-js-sdk/commit/1d3a34d7da5bf3c267d014efb587e03c46ff3064)
* [Where the bug was introduced](https://github.com/firebase/firebase-js-sdk/commit/0a27d2fbf268f07099d4fa5ecab7fbf35a579780)
  Some checks failed for this commit but where not fixed. This test [packages/analytics/src/api.test.ts#L143](https://github.com/firebase/firebase-js-sdk/blob/7709f1016d6e491847bb4e8e4c731603d47f7eae/packages/analytics/src/api.test.ts#L143) should have detected the issue.

**Comment by jbalidiong** [comment]
@megamisan, thanks for reaching out to us. I was able to replicate the behavior you've mentioned. Also, thanks for sending a PR for a possible fix. I'll raise this to our engineering team or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by DellaBitta** [comment]
This fix should be in our next release. If you find that there's still an issue, or a new one, then please open a new support issue and feel free to link to this issue for context. Thanks!
