### ISSUE TITLE
Cross-Origin-Opener-Policy policy would block the window.closed call.

### ISSUE THREAD

**Issue by flurryunicorn** [firebase/firebase-js-sdk#8213]
### Operating System

Windows 11

### Browser Version

124.0.6367.118

### Firebase SDK Version

^10.11.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

React bootstrap app with vite

### Describe the problem

I have implemented signIn/signUp using firebase auth. When I try to signIn with email and password, there are no errors consoled. When I try to signInWithGoogle, it was successfully signed in, but it consoled

```
Cross-Origin-Opener-Policy policy would block the window.closed call.
firebase_auth.js?v=7506f255:6655 
```

### Steps and code to reproduce issue

Here is specific code part in `firebase_auth.js` that shows the console error:

```javascript
pollUserCancellation() {
    const poll = () => {
      var _a, _b;
      if ((_b = (_a = this.authWindow) === null || _a === void 0 ? void 0 : _a.window) === null || _b === void 0 ? void 0 : _b.closed) {
        this.pollId = window.setTimeout(
          () => {
            this.pollId = null;
            this.reject(_createError(
              this.auth,
              "popup-closed-by-user"
              /* AuthErrorCode.POPUP_CLOSED_BY_USER */
            ));
          },
          8e3
          /* _Timeout.AUTH_EVENT */
        );
        return;
      }
      this.pollId = window.setTimeout(poll, _POLL_WINDOW_CLOSE_TIMEOUT.get());
    };
    poll();
  }
  ```

**Comment by bhparijat** [comment]
Hi, this blog post talks about workaround for getting rid of the error https://stackoverflow.com/questions/76446840/cross-origin-opener-policy-policy-would-block-the-window-closed-call-error-while
