### ISSUE TITLE
[FCM] `updateToken` always blocked by CORS

### ISSUE THREAD

**Issue by k-1ee** [firebase/firebase-js-sdk#8225]
### Operating System

MacOS Sonoma 14.4.1

### Browser Version

Chrome/124.0.6367.92

### Firebase SDK Version

10.8.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Next.js app 

### Describe the problem

When `getToken` is called with an expired FCM token, the SDK attempts to update the token by making a call to [`updateToken`](https://github.com/firebase/firebase-js-sdk/blob/f25b9e53e9d77a3f92e36ff62218bbcf24aae857/packages/messaging/src/internals/token-manager.ts#L73), which sends a PATCH request to the Firebase backend. However, this update sequence always fails due to the following CORS error:

`Access to fetch at 'https://fcmregistrations.googleapis.com/v1/projects/{projectId}/registrations/{token}' from origin '...' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.`

Is the PATCH method missing from the allowed methods list of this endpoint?

Since the token expiry is set to one week, this issue is not easy to reproduce. However, a subsequent call to `getToken` (refreshing the page in our case) seems to work fine.

### Steps and code to reproduce issue

- Initialize Firebase & call `getToken`
- After the token has expired (set to one week by SDK), call `getToken` 
- See that `getToken` fails at PATCH request due to CORS

**Comment by zwu52** [comment]
Checked server stats, fm server has been serving patch to the `update_token` endpoint without outages. Unsure why the error. If it's non-recurring, feel free to close.

**Comment by k-1ee** [comment]
@zwu52 - this has been recurring issue for the past couple weeks. 

Just to make sure, does the following endpoint allow PATCH under Access-Control-Allow-Methods?

`https://fcmregistrations.googleapis.com/v1/projects/{projectId}/registrations/{token}`

**Comment by k-1ee** [comment]
Still facing this issue

**Comment by k-1ee** [comment]
> Checked server stats, fm server has been serving patch to the `update_token` endpoint without outages. Unsure why the error. If it's non-recurring, feel free to close.

@zwu52  I believe there wouldn't be outages since the request was blocked by CORS in the first place.

This screenshot shows that the preflight response does not include PATCH:
 
![Screenshot 2024-07-08 at 10 24 12 AM](https://github.com/firebase/firebase-js-sdk/assets/118038250/9006d1ee-9143-4575-b4fd-afd1514e52a2)

**Comment by zwu52** [comment]
hmm. Server is configured to accept PATCH.

When I  making preflight  curl   
```
curl -X PATCH 'https://api.example2.com/v1/resource' \
     -H 'Origin: http://example.com' \
     -H 'Content-Type: application/json' \
     -H 'X-Custom-Header: some-value' \
     -i
``` 

I get
  ```
HTTP/2 200 
access-control-allow-origin: {my_origin}
vary: origin
vary: referer
vary: x-origin
access-control-allow-methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT```
