### ISSUE TITLE
Interface 'FirebaseServerAppSettings' incorrectly extends interface 'FirebaseAppSettings' when "exactOptionalPropertyTypes": true is enabled

### ISSUE THREAD

**Issue by dckz74** [firebase/firebase-js-sdk#8227]
### Operating System

macOS Sonoma 14.4.1

### Browser Version

Chrome/124.0.6367.119

### Firebase SDK Version

10.11.1

### Firebase SDK Product:

Analytics, Auth, Component, Installations, Logger

### Describe your project's tooling

Vue3 app with Vite and Jest

### Describe the problem

I'm encountering a TypeScript compilation error involving `FirebaseServerAppSettings` when "exactOptionalPropertyTypes": true is set in my `tsconfig.json`. This is the error message:

```ts
error TS2430: Interface 'FirebaseServerAppSettings' incorrectly extends interface 'FirebaseAppSettings'.
  Types of property 'name' are incompatible.
    Type 'undefined' is not assignable to type 'string'.
```

If I set "exactOptionalPropertyTypes" to false it works.
Here you can see both interfaces:

```ts
export declare interface FirebaseAppSettings {
    name?: string;
    automaticDataCollectionEnabled?: boolean;
}
```
```ts
export declare interface FirebaseServerAppSettings extends FirebaseAppSettings {
    authIdToken?: string;
    releaseOnDeref?: object;
    name?: undefined;
}
```

### Steps and code to reproduce issue

1. In your TypeScript project, set "exactOptionalPropertyTypes": true in tsconfig.json.
2. Execute `vite build` to build the project.

**Comment by dlarocque** [comment]
Hi @dckz74, I was not able to reproduce the issue. I attempted to reproduce the issue with the following steps:
1. `npm create vite@latest`
2. `cd vite-app`
3. `yarn install && yarn install firebase`
4. Modify `src/main.ts` to be the following
```typescript
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import { initializeApp } from 'firebase/app';

const firebaseConfig = { 
    // My config (omitted)
};

initializeApp(firebaseConfig, "proj");
createApp(App).mount('#app')
```
5. Add `"exactOptionalPropertyTypes": true` to `tsconfig.json`
6. Run `npx vite build`

This was the output from the build
```
$ npx vite build
vite v5.2.11 building for production...
✓ 25 modules transformed.
dist/index.html                  0.46 kB │ gzip:  0.30 kB
dist/assets/index-B87vROlf.css   1.27 kB │ gzip:  0.65 kB
dist/assets/index-Cmnve67z.js   90.79 kB │ gzip: 30.66 kB
✓ built in 355ms
```

**To help me reproduce the issue, could you provide a code snippet that causes the issue to occur, or a minimal project I can clone to reproduce the issue?**

**Comment by dlarocque** [comment]
> Hey @dlarocque, thanks for your quick response!
> 
> You are right, this does not reproduce the issue, my bad. Unfortunately, I am currently not able to give you a minimal project to reproduce this issue.
> 
> I will need to look deeper into my code base to see why the issue occurs. Thank you for your time!

No worries! Please let us know when you are able to share more information that could help us identify the issue.
