### ISSUE TITLE
Realtime Firestore query results in error for "docChanges" 

### ISSUE THREAD

**Issue by Thkasis** [firebase/firebase-js-sdk#824]
### [REQUIRED] Describe your environment

  * Operating System version: Windows, Google Chrome
  * Firebase SDK version: 5.0.1
  * Firebase Product: Firestore

Simple query for realtime onSnapshot() results in error when trying to work with snapshot.docChanges. 
I don't see any doc.docChanges defined as it was in the previous version (4.9.1) that I was using and I get this error: 
snapshot.docChanges.forEach is not a function. Logging snapshot.docChanges is not an array of changes as it was before and instead shows the prototype method. 

#### Steps to reproduce:
Simply query data either using get() or realtime onSnapshot() similar to Firestore documents. 

For realtime query: 

> firebase.firestore(firebase.app("ProjectFirst")).collection('test').where("flg", "==", "i").onSnapshot(function(snapshot) {
        //there is data in database and I see them using get() method for instance
        snapshot.docChanges.forEach(function(change) {
             ...
        });
});

when I log snapshot.docChanges I see this instead of the array of results : 
 
ƒ (e){validateOptionNames("QuerySnapshot.docChanges",e,["includeMetadataChanges"]),e&&validateNamedOptionalType("QuerySnapshot.docChanges","boolean","includeMetadataChanges",e.includeMetadataChanges);v…

**Comment by mikelehen** [comment]
@Thkasis Sorry for the trouble! We changed docChanges into a method in 5.0.0 so you must now do `snapshot.docChanges()` instead of `snapshot.docChanges`. You can find more details in our release notes here: https://firebase.google.com/support/release-notes/js#5.0.0

Thanks and sorry!

**Comment by Thkasis** [comment]
@mikelehen, not a problem, thanks for the update. It would definitely be helpful to have this in the documentation instead if it's supposed to be the standard from now on as documentation still shows docChanges.forEach() 

Thanks for all the good work.
Cheers

**Comment by mikelehen** [comment]
Thank you! I see that indeed https://firebase.google.com/docs/firestore/query-data/listen still has the old syntax. Whoops! We'll get that updated shortly. Thanks for mentioning it.

**Comment by samtstern** [comment]
@mohshraim yep we will add this to the docs soon, sorry about the delay!

**Comment by myleftshoe** [comment]
@google-cloud/firestore 0.16.1 has the opposite problem - snapshot.docChanges() errors with docChanges is not a function so I'm using snapshot.docChanges instead!

**Comment by mikelehen** [comment]
cc/ @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
PR for @google-cloud/firestore pending: https://github.com/googleapis/nodejs-firestore/pull/324

This will make docChanges() a method in all of our JavaScript-based SDKs.

**Comment by elchefuser** [comment]
it seems they came back to a property , for me just works like docChanges, without parenthesis

**Comment by mikelehen** [comment]
@elchefuser It should still be a method.  Which npm module are you using and what version?
