### ISSUE TITLE
getToken not working on Ungoogled Chromium

### ISSUE THREAD

**Issue by CypherPotato** [firebase/firebase-js-sdk#8252]
### Operating System

Windows 10

### Browser Version

Versão 122.0.6261.94 (Official Build, ungoogled-chromium) 64 bits

### Firebase SDK Version

^10.12.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

JavaScript, PHP, PNPM

### Describe the problem

The `getToken` method is called but does never returns an result from the async result. This only happens on [Ungoogled Chromium](https://github.com/ungoogled-software/ungoogled-chromium) browser, but not other browsers like Edge or Firefox.

### Steps and code to reproduce issue

I'm running this code as an module on the website running at an HTTPs localhost endpoint. The service worker file is present.

```js
import { initializeApp } from "firebase/app";
import { getMessaging, getToken } from "firebase/messaging";

const firebaseConfig = {
    ;
};

initializeApp(firebaseConfig);

const messaging = getMessaging();

window.initNotificationService = () => {
    Notification.requestPermission().then(permission => {
        if (permission == 'granted') {
            console.log("perm granted");
            getToken(messaging, { vapidKey: '...' })
                .then((currentToken) => {
                    if (currentToken) {
                        console.log(currentToken);
                    } else {
                        // Show permission request UI
                        console.log('No registration token available. Request permission to generate one.');
                        // ...
                    }
                })
                .catch((err) => {
                    console.log('An error occurred while retrieving token. ', err);
                    // ...
                });
        }
    });
};
```

Edge:

![image](https://github.com/firebase/firebase-js-sdk/assets/17441745/f4abd9bb-136e-49d2-8deb-a5f8c2726c73)

Firefox:

![image](https://github.com/firebase/firebase-js-sdk/assets/17441745/d0340277-f3de-4b94-a4a8-cdf6fec7f2f8)

Ungoogled Chromium:

![image](https://github.com/firebase/firebase-js-sdk/assets/17441745/81837896-f081-4f1d-a4c1-7afa4e0db0ef)

**Comment by DellaBitta** [comment]
Hi @CypherPotato,

It sounds like the Ungoogled Chromium implementation purposefully doesn't provide the fundamental support for what the Messaging implementation requires from a web browser. Is that your understanding as well?

Thanks!

**Comment by CypherPotato** [comment]
Hello @DellaBitta.

Yes, as discused in https://github.com/ungoogled-software/ungoogled-chromium/issues/2867, we concluded that the issue is an expected behavior just because the unchromium doens't listen to google push services.

I'm closing the issue now. Thank you.

**Comment by DellaBitta** [comment]
Hi @CypherPotato,

OK, and thanks for getting back to us!
