### ISSUE TITLE
ERR_INSUFFICIENT_RESOURCES Error

### ISSUE THREAD

**Issue by KKimj** [firebase/firebase-js-sdk#8253]
### Operating System

MacOS 14.4.1

### Browser Version

124.0.6367.208 (Official Build) (x86_64)

### Firebase SDK Version

10.11.1

### Firebase SDK Product:

Firestore

### Describe your project's tooling

I'm using Firestore version 10.11.1 with Flutter. 

I'm using Firestore divided into 8 collection shards. 

I implemented it to obtain count() through whereQuery and AggregationQuery for each collection.

### Describe the problem

At the same time, I make multiple asynchronous calls, so "not always" but "intermittently about 1 out of 5 times" ERR_INSUFFICIENT_RESOURCES occurs.

Even if it occurs, it automatically recovers within 10-30 seconds.

### Steps and code to reproduce issue

<img width="582" alt="Screenshot 2024-05-18 at 17 25 27" src="https://github.com/firebase/firebase-js-sdk/assets/40026920/da6837bb-7570-4199-adb1-4f20f44e54c9">

### Help
Is it Bad practices to call AggregationQuery at the same time?
Or is there a limit or restriction on the number of calls that can be made at the same time?

**Comment by wu-hui** [comment]
How big are your collections? I am wondering if the backend is too busy running these queries at the same time.
