### ISSUE TITLE
getToken returns error on iOS, after Permission is granted and app reloaded.

### ISSUE THREAD

**Issue by NobleUpFront** [firebase/firebase-js-sdk#8269]
### Operating System

17.5.1

### Browser Version

17.5.1

### Firebase SDK Version

10.12.1

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Angular 17, PWA.

### Describe the problem

Problem: After permission has been granted with`Notification.requestPermission()` the status is correctly returned as "granted". After PWA reload, the status thereafter returns "default", both by using `Notification.requestPermission()` or `Notification.permission`: This includes that getToken will return an error when trying to fetch the token, to see if the user has received a new one.

Chrome:
It works correctly in Google Chrome, if page is reloaded, the status returns as granted and getToken returns a valid token.

iOS Safari - PWA added to home screen
Steps to reproduce:
1. Open app
2. Accept notifications, get token.
3. App now gets notifications
4. Close app
5. Open app again
6. Now permission is default, and getToken returns an error.
7. App can still receive notifications.

// edit 30-05-2024
Seems that adding a delay to the notification call, in app.component, makes the request.permission return the correct permissions. (Sometimes)

### Steps and code to reproduce issue

Happens from examples given by the documentation.

`getToken(this.messaging, {
        vapidKey: environment.vapidKey,
      })
        .then((token) => {
          console.log(token);
        })
        .catch((error) => {
          console.log("Error getting token:", error);
        `});``

**Comment by dlarocque** [comment]
Hi @NobleUpFront, I tried reproducing this issue in a PWA on my iOS device, but it seems that this is working fine for me. Could you please provide a code snippet showing how you're requesting permissions?

Here's how I did it:
```js
const requestPermission = () => {
  Notification.requestPermission().then((permission) => {
    if (permission === 'granted') {
      getToken(messaging, { vapidKey: <vapid-key> })
        .then((currentToken) => {
          if (currentToken) {
            console.log(`Token: ${currentToken}`);
          } else {
            console.log("No registration token available");
          }
        })
        .catch((err) => { 
          console.error(err); 
        })
    } else {
      console.warn("Notification permission denied");
    }
  })
}
```
