### ISSUE TITLE
firebase-js-sdk has typos

### ISSUE THREAD

**Issue by jsoref** [firebase/firebase-js-sdk#8279]
### Operating System

N/A

### Browser Version

N/A

### Firebase SDK Version

master

### Firebase SDK Product:

Installations

### Describe your project's tooling

The [check-spelling action](https://github.com/marketplace/actions/check-spelling) identifies misspellings and other errors using words.

### Describe the problem

The misspellings have been reported at https://github.com/jsoref/firebase-js-sdk/actions/runs/9310397584#summary-25627717291

### Steps and code to reproduce issue

1. Fork this repository
2. Add https://github.com/jsoref/firebase-js-sdk/commit/97e22c4f2ef056ec3c8d5095300453a62f682842
3. Push to the fork

**Comment by DellaBitta** [comment]
Thank you!
