### ISSUE TITLE
sendSignInLinkToEmail results in status 400 error

### ISSUE THREAD

**Issue by lanbau** [firebase/firebase-js-sdk#828]
### [REQUIRED] Describe your environment

  * Operating System version: MAC OSX High Sierra 10.13.3 (17D47)
  * Firebase SDK version: 5.0.2
  * Firebase Product: auth

#### Steps to reproduce:

The function sendSignInLinkToEmail is not working today, it was working for 2 days in a row since i tried this method.

I got this error "auth/dynamic-link-not-activated" in my console.log which is not relevant as i am building a web app and not a mobile app.

```
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getOobConfirmationCode?key=mykey 400 ()
Xg @ auth.js

 {code: "auth/dynamic-link-not-activated", message: "FDL domain is empty"}
```
-->
The Code is from the official firebase tutorial. I have also enabled passwordless login in firebase console.
```
let email = this.passwordlessEmail
var actionCodeSettings = {
        // URL you want to redirect back to. The domain (www.example.com) for this
        // URL must be whitelisted in the Firebase Console.
        url: 'http://localhost:3000/authfb',
        // This must be true.
        handleCodeInApp: true,
      }


      firebase.auth().sendSignInLinkToEmail(email, actionCodeSettings)
        .then(function(res) {
          console.log(res)
          // The link was successfully sent. Inform the user.
          // Save the email locally so you don't need to ask the user for it again
          // if they open the link on the same device.
          window.localStorage.setItem('emailForSignIn', email);
        })
        .catch(function(error) {
          console.log(error)
          // Some error occurred, you can inspect the code: error.code
        })
```

**Comment by coluccini** [comment]
Same issue here. It was working fine util yesterday. I didn't update anything, I'm still on 4.x version

**Comment by coluccini** [comment]
Same thing happens when trying to send the email address verification email 😔

**Comment by mo-tottenham** [comment]
I am also experiencing this error. It was working up until yesterday.
I was using Firebase version 4.x.x so I upgraded to 5.0.2 to see if the problem still persists and I was still getting a status 400 error.

It started working for me after going through the "Add Firebase to your ios App" step in the console despite not having an IOS nor an Android app. 

I guess "auth/dynamic-link-not-activated" is telling in this case, but what is strange is that the only way to activate it is by registering a mobile app. 

Also annoying that it is not mentioned in the firebase tutorial code.

**Comment by mkotsur** [comment]
@mo-tottenham wow, dude, you saved me tons of time! An official response from Firebase would be much appreciated!

**Comment by acanimal** [comment]
I have the same issue and tried to add both iOS and Android app to firebase but error persists.

**Comment by coluccini** [comment]
@mo-tottenham: I went through the "Add Firebase to your ios App" but I'm still getting the same error. Did you use any specific or just random info?

**Comment by mo-tottenham** [comment]
@coluccini No just random info.

**Comment by coluccini** [comment]
Now is working! Beside the "Add firebase to your ios App" I then went to "Dynamic Links" and hit the "Get started" button.
Thanks @mo-tottenham!

**Comment by bojeil-google** [comment]
Thanks for reporting this. I will escalate this internally. Just to confirm, is everyone using web flows only (sign in with email link for web redirects only and not mobile redirect)?

**Comment by coluccini** [comment]
I confirm that I'm using web flow only.
PS: cause we are just starting, but this could be a pretty big issue if we already had a bunch of users. We only have email link as login method and for a few hours it was impossible to log in…

**Comment by bojeil-google** [comment]
We apologize for this disruption of service. For now, I recommend enabling firebase dynamic links in the Firebase Console which requires you add a mobile app. You can add a dummy one as you are not gonna use it. This should fix the problem.

**Comment by bojeil-google** [comment]
The fix should be fully rolled out at this point.

**Comment by postalangel** [comment]
not working at all as for today. tried both adding android and ios apps and also by activating dynamic links

**Comment by webmint** [comment]
well i had similar issue when using send email verification. Enabling dummy dynamic link helped get rid of this error in project console 

POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/getOobConfirmationCode?key=mykey 400 ()
Xg @ auth.js
