### ISSUE TITLE
"Maximum call stack size exceeded" in Firebase Auth (web extensions version)

### ISSUE THREAD

**Issue by GaurangTandon** [firebase/firebase-js-sdk#8297]
### Operating System

macOS

### Browser Version

Chrome 124

### Firebase SDK Version

10.11.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

JavaScript (`webpack`) with 'firebase/auth/web-extension' import. Webpack config:

```
const path = require('path');

module.exports = {
  entry: './src/js/firebase.js',
  mode: 'production',
  experiments: {
    outputModule: true
  },
  output: {
    library: {
      type: 'module'
    },
    path: path.resolve(__dirname, 'src/resources'),
    filename: 'firebase.js',
    chunkFormat: 'module'
  },
  devtool: 'source-map',
  target: 'webworker'
};
```

### Describe the problem

When using `getAuth` to determine the loggedIn user, we are getting "Maximum call stack size exceeded" error.

### Steps and code to reproduce issue

The issue only happened for 1 user so far, out of thousands of users. We are not sure what may have caused the issue. There are two stack traces (for the same user):

Stack trace 1 is:

```
RangeError: Maximum call stack size exceeded
  at HeartbeatServiceImpl.triggerHeartbeat(./node_modules/@firebase/app/dist/esm/index.esm2017.js:704:5)
  at ne(./node_modules/@firebase/app/dist/esm/index.esm2017.js:262:34)
  at getAuth(./node_modules/@firebase/auth/dist/esm2017/index-4dc22a28.js:9474:22)
  at loggedIn(./file2.js:13:12)
  at <anonymous>(./file1.js:1123:29)
```

(file*.js are our package files)

Stack trace 2 is:

```
RangeError: Maximum call stack size exceeded
  at HeartbeatServiceImpl.triggerHeartbeat(./node_modules/@firebase/app/dist/esm/index.esm2017.js:704:5)
  at ne(./node_modules/@firebase/app/dist/esm/index.esm2017.js:262:34)
  at getAuth(./node_modules/@firebase/auth/dist/esm2017/index-4dc22a28.js:9474:22)
  at uid(./file2.js:22:10)
  at readonlySubscription(./file2.js:472:44)
  at unsubscribe(./file3.js:374:9)
  at c.next(./node_modules/@firebase/firestore/dist/index.esm2017.js:19358:23)
  at apply(./node_modules/@firebase/firestore/dist/index.esm2017.js:15696:27)
  at sentryWrapped(../node_modules/src/helpers.ts:95:1)
```

**Comment by jbalidiong** [comment]
Hi @GaurangTandon, thanks for bringing this to our attention. I tried replicating using my own app, but I wasn't able to experience any error. Could you share a minimal app with steps I can follow to run it so that I can reproduce the issue?

**Comment by GaurangTandon** [comment]
Hi @jbalidiong sadly we are also not able to reproduce the issue. The app is live for a few weeks on v10.11.0 and this issue just happened those two times out of thousands of invocations.

Our Firebase setup is pretty straightforward with `experimentalForceLongPolling` enabled. Let me know if I can share any specific information with you.

**Comment by jbalidiong** [comment]
Hi @GaurangTandon, I'm currently checking with our engineers the possible reasons why your app is encountering this behavior or error. To help us further investigate the issue, could you provide the following:

- Manifest config
- Code snippet that's causing the error
- Webpack config

**Comment by hsubox76** [comment]
Just wanted to be clear that the larger the context of the code, the better - not just a small snippet where you are calling getAuth, but also how you're importing, instantiating, etc.

I see some subscribe/unsusbscribe code above getAuth() in the call stack from file2 and file3. Is that your own code? It seems to be sandwiched in the stack between firestore and auth lines, are you somehow calling getAuth inside of a Firestore subscribe event? Inside onSnapshot or something?

**Comment by GaurangTandon** [comment]
Hi @hsubox76 and @jbalidiong unfortunately this issue did not happen again so I am unable to fetch more details at this point. If this issue happens again, I will be back with more detailed information. I really thank you for your time and quick followup!
