### ISSUE TITLE
FR: Ability to intercept and handle message in our code, even if `notification` fields are set

### ISSUE THREAD

**Issue by oberhamsi** [firebase/firebase-js-sdk#83]
### [REQUIRED] Describe your environment

  * Operating System version: win7
  * Firebase SDK version: 3.9.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

Sending a message with `notification` payload never triggers the `setBackgroundMessageHandler` callback.

The guide (but not the reference) hint at this behaviour: "If you set notification fields [...] those values take precedence over any values specified in the service worker."

This makes it impossible to intercept the message if `notification` fields are set.

Use case: we are sending additional fields in `data` but are not able to access and use them. We also can't modify the `notification` fields before displaying them to the user.

#### Steps to reproduce:

Send a message with `notification` data. The callback of `setBackgroundMessageHandler` is never called.

**Comment by gauntface** [comment]
You can add a push event handler before instantiating the messaging SDK.

```javascript
self.addEventListener('push', function() {...});

// Import and setup the messaging SDK here.
```
