### ISSUE TITLE
firebase/auth no typescript support

### ISSUE THREAD

**Issue by vladkarataiyardex** [firebase/firebase-js-sdk#8311]
### Operating System

any

### Browser Version

any

### Firebase SDK Version

any

### Firebase SDK Product:

Auth

### Describe your project's tooling

nexjts, firebase. thats all. empty project

### Describe the problem

where the f is typescript support for firebase auth???? why according to the official docs I CANT JUST NORMALLY USE YOUR FKN SDK? ANY ONTHER PACKAGE HAS ITS TYPESCRIPT, LITERALLY ANY, BUT ONLY FIREBASE GOT ISSUES WITH TYPES

### Steps and code to reproduce issue

empty project
webstorm
^10.12.2 firebase

**Comment by dlarocque** [comment]
what issues are you having with types
