### ISSUE TITLE
BUG: using multi-tab persistence, the queries in the secondary tabs don't report metadata.fromCache=false

### ISSUE THREAD

**Issue by atsjo** [firebase/firebase-js-sdk#8314]
### Operating System

Latest Windows 10/11 (probably all os)

### Browser Version

Latest Chrome/Edge (probably all browsers)

### Firebase SDK Version

10.12.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Angular 18 app via newest tooling

### Describe the problem

When using multi-tab persistence and realtime listeners via onSnapshot and includeMetadataChanges: true, the queries in secondary tabs never report metadata.fromCache=false, so I cannot detect correct online state for queries when having multiple tabs...

This works fine with 10.12.0, and I tracked down a PR included in 10.12.1 related to a multi-tab issue (https://github.com/firebase/firebase-js-sdk/pull/8247) which probably causes this issue. This PR says it fixes that queries in secondary tabs include empty snapshots, but it SHOULD report empty snapshots with changed metadata when includeMetadataChanges=true, or else we cannot determine online state of queries...

### Steps and code to reproduce issue

1. create app with multi-tab persistence that opens a realtime listener via onSnapshot and with includeMetadataChanges: true (```initializeFirestore(getApp(), { localCache: persistentLocalCache({ tabManager: persistentMultipleTabManager() }) });```)
2. Open app in multiple tabs in browser, and observe the the queries in the secondary tabs never report metadata.fromCache=false

**Comment by atsjo** [comment]
This is NOT a question, but a serious regression introduced in 10.12.1 related to multi-tab persistence...

**Comment by milaGGL** [comment]
Hi @atsjo, thank you for reporting this issue. 
> I cannot detect correct online state for queries when having multiple tabs

Are you trying to switch network condition between online and offline, and expecting to see snapshots with "fromCache: true/false"? I have tried in local test app, and it is working as expected.

**Comment by atsjo** [comment]
No, but my queries always fetch newer than what's in my local cache, so they return 0 elements, with fromCache true, but then usually return 0 again with fromCache false

**Comment by milaGGL** [comment]
Could you please provide reproduction steps, and what was expected vs what is the current behaviour?

**Comment by atsjo** [comment]
I'll try to make a repro... I expect to always receive fromCache=false so I know I'm up to date with the server, and I use this to detect if I'm offline or online. This doesn't work in 10.12.2, but DOES work in 10.12.0.

**Comment by atsjo** [comment]
Hi @milaGGL , I've made a repro and deployed it with different versions of the sdk to different sites:
v10.12.2 -> https://test-57faf.web.app/ (NOT working with multiple tabs)
v10.12.0 -> https://test1-57faf.web.app/ (working with multiple tabs)

You can just use view source to see the source for these projects, as no bundling is used, and all logic is contained within a couple of lines in index.html. Open the first link in multiple tabs, and do some refreshing on the tabs, and you should see some of the tabs turning red). This does NOT happen with link nr 2.... I use the fromCache metadata to determine when I'm up to date and connected to the firestore backend, as this is the preferred way of doing that according to the docs....

The firestore db allows only reads, and contain no data....

**Comment by milaGGL** [comment]
@atsjo, thank you for the repro, i am looking into the cause.
