### ISSUE TITLE
Firebase in Next.js 14 causes Error: Cannot find module 'undici'

### ISSUE THREAD

**Issue by codercatdev** [firebase/firebase-js-sdk#8323]
### Operating System

macOS 14.5 (23F79)

### Browser Version

Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64)

### Firebase SDK Version

10.12.2

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

Next.js 14, hosted on vercel

### Describe the problem

When accessing pages I am getting a 500 error `Cannot find module 'undici'`. If I try to statically generate these pages it they build but when accessing live they do not render and throw a hard 500. 

<img width="1507" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/3102249/03f12ae2-cda2-4f20-ade0-3f29c0b408ea">

If I remove the static generation and run only on a function they still throw a 500 but the page actually loads.

<img width="1497" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/3102249/261f3b6d-109f-4d82-97b7-07173fc3f387">

<img width="1494" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/3102249/bfa65d59-05cc-4355-a3d6-55da0845c8be">

Everything worked fine until I introduced `firebase/auth` into the mix

<img width="1496" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/3102249/4020c8e3-672f-4a0e-b779-f8d1132b2a67">

### Steps and code to reproduce issue

1. git clone https://github.com/codercatdev/cms-sanity.git
2. git checkout no-firebase OR git checkout firebase-no-static OR git checkout firebase-with-static

You will then need to host on Vercel as running locally will not show this issue.

**Comment by abusada** [comment]
Facing the same issue, I'm using firebase via [next-firebase-auth-edge](https://github.com/awinogrodzki/next-firebase-auth-edge).

The issue happens only on production deployments on vercel, for example it doesn't happen when I make a production build locally.

Even though my logs are full of Error 500:
> Error: Cannot find module 'undici'

And in the devtools network panel i see
![screenshot- 2024-06-19 at 13 26 34@2x](https://github.com/firebase/firebase-js-sdk/assets/2572320/83b70877-3f06-4dfa-9b47-7d966b3c7310)

But the page is served properly and functioning as expected! 

I don't know if this should be reported for firebase, vercel, or nextjs! but I'm gonna report it on every repo to make sure it gets the needed attention.

**Comment by jbalidiong** [comment]
Thank you for bringing this to our attention. I tried implementing firebase via [next-firebase-auth-edge](https://github.com/awinogrodzki/next-firebase-auth-edge) but I wasn't able to experience any error 'Cannot find module undici'. Aside from Auth, are you using any other Firebase products? Also, I noticed a similar issue filed in [Vercel repo](https://github.com/orgs/vercel/discussions/6900#discussioncomment-9821638). Does rolling back the version to `14.1.4` works on your end?

**Comment by SaizFerri** [comment]
I have the same issue. Page loads fine but the first load is always a 500 which is poluting the logs.

**Comment by DellaBitta** [comment]
@SaizFerri Can you test rolling back your version as mentioned above by @jbalidiong?

**Comment by SaizFerri** [comment]
@DellaBitta Issue is that I need at least v14.3.0-canary.24 as that version introduced a critical fix to how cookies are set in the middleware, which I also need for auth. :/

**Comment by DellaBitta** [comment]
Still, if we can pinpoint exactly which version things started to go wrong then we can bring the support case to the Next.js team and ask them what the problem might be.

**Comment by SaizFerri** [comment]
@DellaBitta I see what you mean but that app is running on production so I can't easily downgrade the Next.js version there. I can try on our dev env and keep a look at the logs.

**Comment by DellaBitta** [comment]
Hi @SaizFerri,

that would be very helpful since we can't reproduce it ourselves.  Thanks!

**Comment by codercatdev** [comment]
Undici remains an issue on Vercel

**Comment by dlarocque** [comment]
> @DellaBitta I see what you mean but that app is running on production so I can't easily downgrade the Next.js version there. I can try on our dev env and keep a look at the logs.

Hi @SaizFerri, any luck with this?

**Comment by dlarocque** [comment]
Related: https://github.com/orgs/vercel/discussions/6900

User fixed this issue by downgrading next: https://github.com/orgs/vercel/discussions/6900#discussioncomment-9821638

**Comment by deltaepsilon** [comment]
`npm install undici`

It just worked for me.
