### ISSUE TITLE
Module '"firebase/auth"' has no exported member 'getReactNativePersistence'.

### ISSUE THREAD

**Issue by hritickjaiswal22** [firebase/firebase-js-sdk#8332]
### Operating System

Ubuntu 22.04.4 LTS

### Browser Version

N/A

### Firebase SDK Version

^10.12.2

### Firebase SDK Product:

Auth

### Describe your project's tooling

React native expo with typescript and @react-native-async-storage/async-storage

### Describe the problem

Module '"firebase/auth"' has no exported member 'getReactNativePersistence'.
![getReactNativePersistence bug](https://github.com/firebase/firebase-js-sdk/assets/76635865/708aa493-2612-4779-b885-2a72b58914d0)

From the firebase/auth module the method getReactNativePersistence is showing not available , there is a problem with the typescript declarations.

### Steps and code to reproduce issue

npx create-expo-app@latest
cd into the project 
npx expo install firebase

import { getReactNativePersistence,} from "firebase/auth";

Will show the typescript error
![getReactNativePersistence bug](https://github.com/firebase/firebase-js-sdk/assets/76635865/1a44b30e-33df-4ecf-9965-d19a6a754e77)

**Comment by jbalidiong** [comment]
Hi @hritickjaiswal22, thanks for reaching out to us. This seems related to #7584. Kindly follow the workaround provided by one of our engineer by updating the `ts.config.json`:

```
{
  "compilerOptions": {
    "paths": {
      "@firebase/auth": ["./node_modules/@firebase/auth/dist/index.rn.d.ts"]
    }
  },
  "extends": "expo/tsconfig.base"
}
```

> This forces VSCode to look at the index.rn.d.ts typings file for any imports from @firebase/auth. This actually seems to be a TypeScript issue, which is odd, because the default npx create-expo-app doesn't seem on the surface to have any TypeScript in it. But VSCode is using TypeScript to get your syntax highlighting and all that.

I'll be closing this issue now. If you encounter another issue, feel free to create a new one.
