### ISSUE TITLE
Apple Sign In Blank screen on Web using Chrome 126

### ISSUE THREAD

**Issue by chinesehemp** [firebase/firebase-js-sdk#8358]
### Operating System

macOS 14.5

### Browser Version

Chrome/126

### Firebase SDK Version

10.12.3

### Firebase SDK Product:

Auth

### Describe your project's tooling

React, VSCode, Typescript

### Describe the problem

When using Sign in With Apple on Web, I'm getting a blank screen in the popup where I would normally see a cancel or continue after successfully authenticating myself. The strange thing is the features work fine on iOS and when installed as a web app using desktop Safari as a PWA as it triggers faceID to authenticate. But somehow on web and using password, the success screen is blank.

<img width="501" alt="Screenshot 2024-07-08 at 18 57 59" src="https://github.com/firebase/firebase-js-sdk/assets/58605231/396a9859-0e6b-4843-ab32-19fb3517aa74">

<img width="492" alt="Screenshot 2024-07-08 at 18 58 22" src="https://github.com/firebase/firebase-js-sdk/assets/58605231/9445307a-b285-477b-b3ab-cd2b4fbea6ba">

### Steps and code to reproduce issue

Try sign in with apple using macOS 14.5 and Chrome 126.
After signing in, you can't continue as the screen is blank where before there was an option to cancel or continue.

**Comment by chinesehemp** [comment]
Screenshot of the sequence of screens during sign in. As you can see the 2nd screen is quickly shown and then disappears to a blank screen.
<img width="497" alt="Screenshot 2024-07-09 at 19 35 20" src="https://github.com/firebase/firebase-js-sdk/assets/58605231/1f092550-9662-42f8-af6d-49a002e3d369">
<img width="499" alt="Screenshot 2024-07-09 at 19 35 29" src="https://github.com/firebase/firebase-js-sdk/assets/58605231/24ced5e1-b048-48d2-9795-ca51990f9e1b">
<img width="500" alt="Screenshot 2024-07-09 at 19 35 36" src="https://github.com/firebase/firebase-js-sdk/assets/58605231/17610d0d-69ac-4e48-8c4c-3d2e6e082ccd">

**Comment by dlarocque** [comment]
Hi @chinesehemp, thanks for submitting this issue! To help us reproduce this issue, could you share some code we could use to try to reproduce the issue?
