### ISSUE TITLE
Sign in With Redirect best practice #3 failing

### ISSUE THREAD

**Issue by ajoy39** [firebase/firebase-js-sdk#8360]
### Operating System

Mac OS 14

### Browser Version

Firefox Latest, Chrome Latest, Safari latest

### Firebase SDK Version

=@firebase/auth@1.7.3

### Firebase SDK Product:

Auth

### Describe your project's tooling

React app with create-react-app

### Describe the problem

When implementing option #3 on the redirect based login best practices page, getting a firebase "no site" error 
<img width="7" alt="Screenshot 2024-07-08 at 5 53 08 PM" src="https://github.com/firebase/firebase-js-sdk/assets/4281903/5cb10335-05bf-41b8-9c65-5c9e0aeaee98">

I have implemented option #3, https://firebase.google.com/docs/auth/web/redirect-best-practices#proxy-requests, to support redirect based login

When I try to authenticate using redirects, I get the firebase site not found error screen once my app redirects me to firebase to initiate authentication

### Steps and code to reproduce issue

Setup Firebase auth in a React app not hosted on firebase

using a load balancer or nginx proxy, 301 proxy all requests from /___/auth to the firebase app, preserving URL

attempt redirect based login

observe URL is https://{project{.firebaseapp.com/__/auth?apiKey={key}&appName=%5BDEFAULT%5D&authType=signInViaRedirect&redirectUrl={url}%2Flogin&v=10.12.1&providerId=oidc.clever

observe site not found page

**Comment by dlarocque** [comment]
> ### Operating System
> Mac OS 14
> 
> ### Browser Version
> Firefox Latest, Chrome Latest, Safari latest
> 
> ### Firebase SDK Version
> =@firebase/auth@1.7.3
> 
> ### Firebase SDK Product:
> Auth
> 
> ### Describe your project's tooling
> React app with create-react-app
> 
> ### Describe the problem
> When implementing option #3 on the redirect based login best practices page, getting a firebase "no site" error <img alt="Screenshot 2024-07-08 at 5 53 08 PM" width="7" src="https://private-user-images.githubusercontent.com/4281903/346735385-5cb10335-05bf-41b8-9c65-5c9e0aeaee98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzcwODAsIm5iZiI6MTcyMDUzNjc4MCwicGF0aCI6Ii80MjgxOTAzLzM0NjczNTM4NS01Y2IxMDMzNS0wNWJmLTQxYjgtOWM2NS01YzllMGFlYWVlOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTQ1MzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTJhMDdmNzNkNmE4ZWU1NzRiMmNmNmJmZGQxOTQ3NzU1MTQ2ZWU3ODAwMzYxZmZjMDhiZjZhNzNlZGE5YWFjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6y75HMRcKxLqCace7dpVqvdPof3epF_V1KCtKoApDbg">
> 
> I have implemented option #3, https://firebase.google.com/docs/auth/web/redirect-best-practices#proxy-requests, to support redirect based login
> 
> When I try to authenticate using redirects, I get the firebase site not found error screen once my app redirects me to firebase to initiate authentication
> 
> ### Steps and code to reproduce issue
> Setup Firebase auth in a React app not hosted on firebase
> 
> using a load balancer or nginx proxy, 301 proxy all requests from /___/auth to the firebase app, preserving URL
> 
> attempt redirect based login
> 
> observe URL is https://{project{.firebaseapp.com/__/auth?apiKey={key}&appName=%5BDEFAULT%5D&authType=signInViaRedirect&redirectUrl={url}%2Flogin&v=10.12.1&providerId=oidc.clever
> 
> observe site not found page

Hi @ajoy39, to help us reproduce this issue, would you be willing to share your nginx configuration?

**Comment by ajoy39** [comment]
Hi @dlarocque , we aren't using Nginx, but a GCP Application load balancer, here is my config for that though 

```defaultService: projects/helloworldcs-dev/global/backendServices/learn
name: firebase-auth
routeRules:
- urlRedirect:
    pathRedirect: /__/auth
    stripQuery: false
    hostRedirect: helloworldcs-dev.firebaseapp.com
  matchRules:
  - prefixMatch: /__/auth
  priority: 10
`

**Comment by ajoy39** [comment]
I thought maybe this was happening because we weren't using firebase hosting, since that was the page I see when we land on the redirected route, so I deployed a minimal firebase hosting site but that didn't change anything. Now instead of the "firebase site not found" page I land on the firebase site landing page. This is the URL that it lands on after redirect https://helloworldcs-dev.firebaseapp.com/__/auth note that I stripped all the query params for security but they are present on the initial redirect.

**Comment by ajoy39** [comment]
Apologies, this was my mistake, the pathRedirect portion of the load balancer rule I set up was redirecting all requests from /__/auth/* to just /__/auth, stripping out the /handler part of the path

**Comment by dlarocque** [comment]
> Apologies, this was my mistake, the pathRedirect portion of the load balancer rule I set up was redirecting all requests from /**/auth/* to just /**/auth, stripping out the /handler part of the path

No worries- glad you were able to solve the issue

**Comment by ajoy39** [comment]
To anyone reading this issue in the future I was wrong 2x, not only was my redirect rule wrong but also _don't use a redirect for this_. While it did seem to work it also seemed to cause a decent number of login hangs. Instead, create an Internet NEG backend for your firebase instance, and proxy all requests to /__/ to that instead. Thats the closest match to using nginx proxy pass, which is what the docs suggest, just took me awhile to figure out how to do that on an application load balancer
