### ISSUE TITLE
FirebaseServerApp cannot use ignoreUndefinedProperties boolean

### ISSUE THREAD

**Issue by tzuhaohuang** [firebase/firebase-js-sdk#8406]
### Operating System

MacOS 14.4.1

### Browser Version

Safari/Version 17.4.1 

### Firebase SDK Version

10.12.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

Next.js 14 app with server components.

### Describe the problem

I have a server action (form action executed on server side) that will initialize a firebase server app.
In the server action, it's setting a doc that has a property with value undefined. (I'm using converter toFirestore())
I'm getting this error message `Function setDoc() called with invalid data (via `toFirestore()`). Unsupported field value: undefined`
I have no way to setting ignoreUndefinedProperties property when using initializeServerApp() 

### Steps and code to reproduce issue

1. Follow firebase tutorial for Next.js 14 with firebase server app
2. Create a firebase server app
3. Create firestore from that server app
4. create a doc, with a undefined value in key/value pair.
5. Observing error log in project console since it's from server function

**Comment by milaGGL** [comment]
Hi @tzuhaohuang , thank you for reporting this issue. Could you please provide a minimal repro app?

**Comment by tzuhaohuang** [comment]
omg, I apologize. I figure out how to set ignoreUndefinedProperties for fiestore based on server app. I'm gonna close this issue.
