### ISSUE TITLE
(Firefox extension) Error: Not allowed to define cross-origin object as property on [Object] or [Array] XrayWrapper

### ISSUE THREAD

**Issue by CharlieDigital** [firebase/firebase-js-sdk#8407]
### Operating System

Mac M1, macOS 14.5

### Browser Version

Firefox 129.0

### Firebase SDK Version

10.12.4

### Firebase SDK Product:

Auth

### Describe your project's tooling

Vue, Vite

### Describe the problem

Firebase auth seems to fail at code startup when making a heartbeat call to IndexDB:

![image](https://github.com/user-attachments/assets/7e5f3b51-3383-41f0-9f76-c13d3f25e11a)

Error message:

```
Error: Not allowed to define cross-origin object as property on [Object] or [Array] XrayWrapper
```

Call is being made from a Vue component injected into a browser page via content script.

The code works fine in Chrome and in Firefox locally against the Firebase emulator in local development.

This failure to connect to the IndexDB appears to then affect the call to `signInWithCustomToken` at a later juncture in the code (not certain that they are related):

![image](https://github.com/user-attachments/assets/010d5c34-7a6b-42ae-9236-af9da03f8dca)

### Steps and code to reproduce issue

I'm in the process of creating a reproducible sample, but so far I've only observed this with a published extension (everything works fine when working locally and connected to the emulator as it does not care about the referrer).

Chrome version of the extension: https://chromewebstore.google.com/detail/turasapp/lpfijfdbgohlblnadiokliolkkeeblpo

Firefox version: https://addons.mozilla.org/en-US/firefox/addon/turas-app/

Both are non-obfuscated so it should be possible to step through the source in the file `maps-connector.js`

**Comment by CharlieDigital** [comment]
Follow on error seems to be related to this earlier issue: #7997 

Here is the error in Firefox:

![Screenshot 2024-08-06 at 10 29 28 PM](https://github.com/user-attachments/assets/40a8b575-c80f-447a-8ba5-9bff524914a7)

Network request is sent and response is received as an HTTP 403 due to `empty` referrer in the request.

**Comment by hsubox76** [comment]
We should never error the user in heartbeats code. We should probably gracefully fail in this case - most likely wrap this call in a try/catch. Maybe we should wrap the entirety of triggerHeartbeat in a try/catch and log the error at debug loglevel.

**Comment by CharlieDigital** [comment]
@hsubox76 would the failure to access IndexDB then affect the subsequent call to the auth API endpoint (`identitytoolkit.google.com`)? The `<empty>` referrer is current preventing the code from working in FF and I haven't determined yet whether this is definitively related to the failure to `IndexDB`.

**Comment by hsubox76** [comment]
No product code depends on heartbeats code, it's independent. Several other products use the native indexedDB API, and if indexedDB has limitations in this environment (firefox extension), then those products may have their own problems, which should be addressed separately.

**Comment by CharlieDigital** [comment]
I'll file a separate issue for it then.

**Comment by naveedahmed1** [comment]
I am seeing `heartbeats undefined` waring in dev console after upgrade.
