### ISSUE TITLE
Cannot resolve symbol 'getAuth' from firebase/auth

### ISSUE THREAD

**Issue by golyo** [firebase/firebase-js-sdk#8418]
### Operating System

Windows

### Browser Version

Google Chrome

### Firebase SDK Version

10.12.5

### Firebase SDK Product:

Auth

### Describe your project's tooling

using Webstorm
react typescript with vite

### Describe the problem

After vite quickstart the project, install firebase, than open on Webstorm IDE

import { getAuth } from 'firebase/auth';
has error : Cannot resolve symbol 'getAuth' 

Other packages has no problem.

### Steps and code to reproduce issue

Steps to reproduce:

npm create vite@latest 
   - with params, name: test-firebase, framework: react, variant_ Typescript
 cd test-firebase
 npm i --save firebase
 npm i
 
 Open project in Webstorm
 
and after edit App.tsx add lines:
import { getAuth } from 'firebase/auth';
Error message: Cannot resolve symbol 'getAuth' 

Other packages are working well for example: 
import { initializeApp } from 'firebase/app';
import { getAnalytics } from 'firebase/analytics';
import { getFirestore } from 'firebase/firestore';

![create-firebase-vite](https://github.com/user-attachments/assets/822e77da-a842-474f-b4f3-5d5d0dbd486b)
![firebase-getAuth](https://github.com/user-attachments/assets/67644e4a-42a8-41c2-a33a-036bbd23a927)

**Comment by golyo** [comment]
node: v20.16.0
npm: 10.8.2

**Comment by DellaBitta** [comment]
Hi @golyo,

I ensured I was used the same `node` and `nvm` versions as you but I wasn't able to reproduce this on macOS nor Windows with the latest version of WebStorm v2024.2:

`Build #WS-242.20224.342, built on August 8, 2024`.  Is this the version that you're testing against?  If not, does upgrading fix the issue?

Thanks!
