### ISSUE TITLE
TypeError in @firebase/webchannel-wrapper on iOS/macOS

### ISSUE THREAD

**Issue by eraydurak** [firebase/firebase-js-sdk#8422]
### Operating System

iOS 17.5.1

### Browser Version

Mobile Safari 17.5

### Firebase SDK Version

^9.6.7

### Firebase SDK Product:

Functions

### Describe your project's tooling

Vue3 - TS

### Describe the issue
We're encountering a `TypeError: undefined is not an object (evaluating 'this.l.status')` error that occurs only on iOS and macOS devices. This issue has been persistent for about a month. The error points to the following file:

`./../node_modules/@firebase/webchannel-wrapper/dist/esm/index.esm2017.js`

### Steps to reproduce
- Describe any specific steps needed to reproduce the issue.
- Include relevant code snippets, if possible.

### Expected behavior
The application should function without encountering this TypeError.

### Screenshots
- Attach screenshots showing the error.

### Environment
- **SDK version**: [e.g., 9.15.0]
- **Platform**: iOS/macOS
- **Other relevant info**: [e.g., Browser version, etc.]

### Additional context
- Any other details that might help in diagnosing the issue.

### Steps and code to reproduce issue

![image](https://github.com/user-attachments/assets/b0ffccdb-8e78-45f1-b884-9705c5b21d52)
![image](https://github.com/user-attachments/assets/c8059dd6-64e9-40ff-83d8-0360314ed4b1)
![image](https://github.com/user-attachments/assets/507069f6-80c3-4501-82c2-03e0857e677e)

While I can't provide a specific scenario to consistently reproduce the issue, it is likely to occur when visiting our website, as this error frequently appears in our Sentry logs.

**Comment by DellaBitta** [comment]
The error appears to be an internal issue within the Closure dependency that the WebChannel Wrapper implementation wraps. I've noticed that the Firebase SDK version is from 2 years ago and the WebChannel Wrapper Closure dependency has changed a few times since then. Would it be possible for you to update your dependencies?

Additionally can you confirm which Firebase products that you're using? I believe the `webchannel-wrapper` library is exclusively used by Firestore and not Functions. Unless another dependency of your app is using it, too. Thanks!

**Comment by eraydurak** [comment]
Thanks for the feedback! 
`webchannel-wrapper` is not directly imported and used in my project. But I guess its in firestore that I used. 
package.lock file says its the version `"@firebase/webchannel-wrapper": "0.10.1",`
I tried to update the package itself and sadly it did not effect the issue
additional imports :
```
"firebase": "^9.23.0",
"@vueuse/firebase": "^7.7.0",
```

**Comment by DellaBitta** [comment]
Did you run `npm install firebase@latest` ?

Also, could you let us know what `@vueuse/firebase` is, and does that have a peer dependency? You may need to update `vueuse`, too, which is on version 11.x.
