### ISSUE TITLE
Invalid query. You cannot use 'not-in' filters with 'in' filters.

### ISSUE THREAD

**Issue by vpishuk** [firebase/firebase-js-sdk#8429]
### Operating System

macOS

### Browser Version

Chrome 126.0.6478.185 (Official Build) (arm64)

### Firebase SDK Version

10.12.4

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React-based application. Firestore is used on frontend side.

### Describe the problem

I have a query builder that generates firestore queries based on JSON input.
Here is an input:
```
{
            type: "and",
            children: [
                {
                    field: "status",
                    op: "in",
                    value: ["new"]
                },
                {
                    field: "__name__",
                    op: "not-in",
                    value: ['uid1', 'uid2']
                }
            ]
        }
```

The converter works fine but firestores' query method throws an error:
```
FirebaseError: Invalid query. You cannot use 'not-in' filters with 'in' filters.
```

### Steps and code to reproduce issue
```
query(
            collection(firestore, "animals"),
            and(where("status", "in", ["new"]), where("__name__", "not-in", ["uid"]))
        );
```

**Comment by tom-andersen** [comment]
Hi @vpishuk 

Unfortunately, this is a known limitation of the system.

As a work around, you could perform multiple queries for each of the `status` values.

Please let me know if you need further help.

**Comment by vpishuk** [comment]
Hi @tom-andersen ,

Thank you for your response. I solved it using a different query that do not require combination of in and not-in operators.
But this is something that is nice to be addressed.
