### ISSUE TITLE
undici <v6.16.0 memory ballooning bug

### ISSUE THREAD

**Issue by JesperLindholmNG** [firebase/firebase-js-sdk#8431]
### Operating System

macOS

### Browser Version

Firefox

### Firebase SDK Version

10.13.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

React, Next.js

### Describe the problem

The undici dependency contains a code path that, starting with Node 20.16.0, results in memory leaks (in our experience significant). See https://github.com/nodejs/undici/pull/3445 and https://github.com/nodejs/node/issues/54274 for details about the issue.

Upgrading undici to v6.19.6 or later, will include the fix. As of yet the fix does not appear to be backported to v5 [which this repository uses](https://github.com/firebase/firebase-js-sdk/blob/f7c6dc4fe10ca3999b1499476ecf9b911c534d25/package.json#L159). 

### Steps and code to reproduce issue

See https://github.com/nodejs/undici/pull/3445 for more details.

**Comment by DellaBitta** [comment]
Hi @JesperLindholmNG,

I've updated our undici dependency to v6.19.7, which will be part of our next release. I'm going to close this issue for now. Please create a new issue if you encounter any problems with the new version. Thanks!
