### ISSUE TITLE
console.log "heartbeats" is unnecessary

### ISSUE THREAD

**Issue by tzappia** [firebase/firebase-js-sdk#8436]
### Operating System

macOS 14.6.1

### Browser Version

Chrome/127.0.6533.120

### Firebase SDK Version

10.13.0

### Firebase SDK Product:

Auth, Firestore, Functions, Storage

### Describe your project's tooling

Angular v18 app

### Describe the problem

During initialization, an unhelpful console.log is repeated:

`heartbeats undefined`

### Steps and code to reproduce issue

After initializing the app, initialize Firestore (for example)

```
    this.app = initializeApp({
      apiKey: environment.firebase.apiKey,
      authDomain: environment.firebase.authDomain,
      databaseURL: environment.firebase.databaseURL,
      projectId: environment.firebase.projectId,
      storageBucket: environment.firebase.storageBucket,
      messagingSenderId: environment.firebase.messagingSenderId,
      appId: environment.firebase.appId,
    });

    this.db = initializeFirestore(this.app, {
      ignoreUndefinedProperties: true,
    });
```

**Comment by tzappia** [comment]
Appears to have been introduced with #8425

**Comment by BastianBrouwers** [comment]
Can confirm that after updating to `"firebase": "^10.13.0",` i now end up getting:

![image](https://github.com/user-attachments/assets/50ae0415-d5dc-459a-a6d9-f0bd0a69654e)

**Comment by NickFoden** [comment]
Same, but in a react app and it's super noisy in the logs and in local dev. 

```
heartbeats [
  {
    date: '2024-08-18',
    agent: 'fire-core/0.10.9 fire-core-esm2017/0.10.9 fire-js/ fire-js-all-app/10.13.0 fire-gcs/0.13.0 fire-fn-node/0.11.6 fire-fn-esm2017/0.11.6 fire-auth-node/1.7.7 fire-auth-esm2017/1.7.7 fire-rtdb-node/1.0.7 fire-rtdb-esm2017/1.0.7 fire-fst-node/4.7.0 fire-fst-esm2017/4.7.0 fire-iid/0.6.8 fire-iid-esm2017/0.6.8 fire-analytics/0.10.7 fire-analytics-esm2017/0.10.7'
  }
]

**Comment by hqw567** [comment]
Same problem.

**Comment by jbalidiong** [comment]
Hi @tzappia, thank for bringing this to our attention. I was able to reproduce the behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by jeffgaynor** [comment]
Experiencing the same issue when I just updgraded to ` "firebase": "^10.13.0"`.

**Comment by dlarocque** [comment]
Thanks for reporting this!

This was introduced in 10.13.0, so if anyone wants to get rid of this they can downgrade to 10.12.5 until the removal of the `console.log` is released next Thursday.

**Comment by ben519** [comment]
> This was introduced in 10.13.0, so if anyone wants to get rid of this they can downgrade to 10.12.5 until the removal of the `console.log` is released next Thursday.

~~10.12.5~~ 10.12.4

**Comment by ben519** [comment]
> Are you seeing this in 10.12.4?

No, but I see it in 10.12.5

**Comment by dlarocque** [comment]
> > Are you seeing this in 10.12.4?
> 
> No, but I see it in 10.12.5

Sorry, I meant 10.12.5.

I just tested this, and I am seeing it in 10.13.0, but not 10.12.5. Could you share what version of `@firebase/app` you have installed?

**Comment by ben519** [comment]
@dlarocque Apologies, I must've been mistaken. Indeed, 10.12.5 does NOT display the "heartbeats" logs.

**Comment by saifbechan** [comment]
Seeing this as well in version 10.13.0. We are using this in a nextjs app and I am seeing the message both on server side and client side. 

`heartbeats undefined`

Coming from these lines:

```
export const auth = getAuth(app);

export const db = getFirestore(app);
```

**Comment by dlarocque** [comment]
This was removed in https://github.com/firebase/firebase-js-sdk/pull/8437, which will be released next thursday. I'll keep this issue open until it's released. Thanks everyone for +1'ing this

**Comment by nickredmark** [comment]
a tip: we have an eslint rule that errors on console.log so that it forces temporary usage. for permanent logs we use console.info/warn/error.

**Comment by Xaypanya** [comment]
This is a temporary workaround. Insert this snippet at the beginning of your main JavaScript file (e.g., index.js, main.js, etc.) or wherever you initialize Firebase: `// Save the original console.log function
const originalConsoleLog = console.log;

console.log = function(...args) {
  // Check if the log message contains the word "heartbeats"
  if (args.some(arg => typeof arg === 'string' && arg.includes('heartbeats'))) {
    return; // Skip the log message
  }

  // Otherwise, use the original console.log
  originalConsoleLog.apply(console, args);
};`

**Comment by Xaypanya** [comment]
This is a temporary workaround. Insert this snippet at the beginning of your main JavaScript file (e.g., index.js, main.js, etc.) or wherever you initialize Firebase:
```

// Save the original console.log function
const originalConsoleLog = console.log;

console.log = function(...args) {
// Check if the log message contains the word "heartbeats"
if (args.some(arg => typeof arg === 'string' && arg.includes('heartbeats'))) {
return; // Skip the log message
}

// Otherwise, use the original console.log
originalConsoleLog.apply(console, args);
};`
```

**Comment by flomoto** [comment]
This is super annoying. How can this happen?

**Comment by erlichmen** [comment]
doesn't eslint caches this kind of things? how did it pass the CI? (asking for next time)

**Comment by RicardoESH** [comment]
Great! I'm looking forward to the update

> This was removed in #8437, which will be released next thursday (08/29). I'll keep this issue open until it's released. Thanks everyone for +1'ing this

**Comment by Kronenberg** [comment]
Great Success
