### ISSUE TITLE
JS SDK Old version - supported or not

### ISSUE THREAD

**Issue by jnosal** [firebase/firebase-js-sdk#8452]
### Operating System

Ubuntu 22

### Environment (if applicable)

Latest version of firefoxx

### Firebase SDK Version

5.5.8

### Firebase SDK Product(s)

Messaging

### Project Tooling

vuejs

### Detailed Problem Description

No known issue here. I just wanted to ask a question because its very hard to find definitive answer.
I have two legacy projects that still users old javascript sdks - one uses v4 and another v6. They seem to work but is there any concern that the integration can stop working as of now?

We're talking about very simple sites that use cdn version of firebase libraries

### Steps and code to reproduce issue

.

**Comment by dlarocque** [comment]
Yes, I believe these old versions should still work fine for simple sites. If they don't work, consider upgrading to more recent versions.
