### ISSUE TITLE
messaging.usePublicVapidKey   not defined

### ISSUE THREAD

**Issue by 0wwafa** [firebase/firebase-js-sdk#8471]
### Operating System

any

### Environment (if applicable)

Chrome latest (128)

### Firebase SDK Version

10.13.1

### Firebase SDK Product(s)

Messaging

### Project Tooling

my hands. (HTML)

### Detailed Problem Description

In my  old code I had:
```
const messaging = firebase.messaging();
messaging.usePublicVapidKey('MYKEY');

```
now usePublicVapidKey is not existant anymore.

### Steps and code to reproduce issue

```
firebase.initializeApp({ THE CONFIG  });
const messaging = firebase.messaging();
messaging.usePublicVapidKey('MYKEY');
```

**Comment by GuillermoPeralta** [comment]
Im having the same issue.

Any idea?

Thank you

**Comment by zwu52** [comment]
`usePublicVapidKey` is deprecated. If you wish to use the modular SDK, please read the doc carefullyhttps://firebase.google.com/docs/reference/js/messaging_sw.gettokenoptions.md#gettokenoptions_interface

**Comment by 0wwafa** [comment]
> `usePublicVapidKey` is deprecated. If you wish to use the modular SDK, please read the doc carefully https://firebase.google.com/docs/reference/js/messaging_sw.gettokenoptions.md#gettokenoptions_interface

I know that.
There are no examples anywhere (not just about the get token)
but about vapid.

**Comment by GuillermoPeralta** [comment]
> > `usePublicVapidKey` is deprecated. If you wish to use the modular SDK, please read the doc carefully https://firebase.google.com/docs/reference/js/messaging_sw.gettokenoptions.md#gettokenoptions_interface
> 
> I know that. There are no examples anywhere (not just about the get token) but about vapid.

True, its clear we have to change, but doc about this change is not so clear for me.

@Owwafa FYI, chatGPT helped me a little bit, maybe you can ask as well. Im not done yet, but looks good, if i get success I reply here.

**Comment by GuillermoPeralta** [comment]
I solved this and looks its working fine.

I wil try to explain what i did to solve. Maybe it helps someone.

You have to remove this, because is not longer necesary. Now you have to use getToken with the 'MYKEY'
`messaging.usePublicVapidKey('MYKEY');`

lso you have to change this


> messaging.onTokenRefresh(() => {
>      messaging.getToken().then((refreshedToken) => {
>          // Indicate that the new Instance ID token has not yet been sent to the
>         // app server.
>          // Send Instance ID token to app server.
>          // [START_EXCLUDE]
>          // Display new Instance ID token and clear UI of all previous messages.
>          // [END_EXCLUDE]
>      }).catch((err) => {
>         //console.log('Unable to retrieve refreshed token ', err);
>         showToken('Unable to retrieve refreshed token ', err);
>      });
>  });`

with this

> Notification.requestPermission().then((permission) => {
>     if (permission === 'granted') {
>         messaging.getToken({ vapidKey: usePublicVapidKey }).then((currentToken) => {
>             if (currentToken) {
>                 // Send Instance ID token to app server.
>                 // [START_EXCLUDE]
>                 // Display new Instance ID token and clear UI of all previous messages.
>             } else {
>                 console.warn(Unable to retrieve FCM token.');
>             }
>         }).catch((err) => {
>             console.warn('Unable to retrieve FCM token.', err);
>         });
>     } else {
>         console.warn('Denied.');
>     }
> }).catch((err) => {
>     console.error('Error.', err);
> });

Now your sw.js file (in your root page) will call onMessage method fron `firebase.messaging`.

Also you have to change the server side.
Until now, you just needed to send a request including your authorization key in headers, but after change, firebase needs an oAUTH grant. 
In my case, I was using php so I included Google library in my project.

You need to generate a service account private key (which will dwnload a json with the key)

You can go to your firebase project console -> configuration -> service account tab -> Generate new private key button (it will download a json.

You have to be sure that you have 'API HTTP v1 " enabled on firebase cloud messaging
You can go to your firebase project console -> configuration -> Cloud messaging and check if tis correct

Once you have it, you have to include the Json in googles service and generate the Bearer key.
here is an example with the php code

  
      

>   $json = 'yout_private_key_json_generated_path.json';
>         $client = new Google();
>         $client->setAuthConfig($json)
>         $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
>         $accessToken = $client->fetchAccessTokenWithAssertion()['access_token'];
>         $fcmUrl = 'https://fcm.googleapis.com/v1/projects/erp-zafiro/messages:send';
>         $headers = [
>             'Authorization: Bearer ' . $accessToken,
>             'Content-Type: application/json'
>         ];
>         $notification = [
>             'message' => [
>                 'token' => 'client_id_notifications_token',
>                 'notification' => [
>                     'title' => 'Your title',
>                     'body' => 'Message',
>                 ],
>                 'data' => [
>                     'attribute_key' => 'value1',
>                     'attribute_key2' => 'value2',
>                 ]
>             ]
>         ];
> 
>         $ch = curl_init ();
>         curl_setopt ( $ch, CURLOPT_URL, $fcmUrl );
>         curl_setopt ( $ch, CURLOPT_POST, true );
>         curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
>         curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false);
>         curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
>         curl_setopt ( $ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
>         curl_setopt ( $ch, CURLOPT_POSTFIELDS, $jsonEnvio );
>         $response = curl_exec($ch);


I hope its clear... For me to do this was enough

Sorry for my english as well, i tried to do my best. I know its not the best english gramar and vocabulary

Reguards

**Comment by 0wwafa** [comment]
@GuillermoPeralta thanks for your message. Before I was able to do everything CLIENT SIDE. My program (a webapp) was:

1) subscribing to notifications
2) subscribing to group "xxxxxx"
3) waiting for notifications
4) on user action, it sent a notification to group "xxxxxx"

(in group "xxxxxx"there were always only 2 users, thus allowing the two users to message each other and send a notification to each other too!) it was working perfectly until a month ago.

**Comment by DellaBitta** [comment]
Hi @0wwafa,

As mentioned, the previous API that you were using is deprecated. We have a [guide on how to setup the SDK](https://firebase.google.com/docs/cloud-messaging/js/client#configure_web_credentials_in_your_app) that should help you restructure your originally posted code.

> Before I was able to do everything CLIENT SIDE.

Aside from initialization, could you post the code that once worked that is no longer working? Thanks.

**Comment by marcoahp** [comment]
> I solved this and looks its working fine.
> 
> I wil try to explain what i did to solve. Maybe it helps someone.
> 
> You have to remove this, because is not longer necesary. Now you have to use getToken with the 'MYKEY' `messaging.usePublicVapidKey('MYKEY');`
> 
> lso you have to change this
> 
> > messaging.onTokenRefresh(() => {
> > messaging.getToken().then((refreshedToken) => {
> > // Indicate that the new Instance ID token has not yet been sent to the
> > // app server.
> > // Send Instance ID token to app server.
> > // [START_EXCLUDE]
> > // Display new Instance ID token and clear UI of all previous messages.
> > // [END_EXCLUDE]
> > }).catch((err) => {
> > //console.log('Unable to retrieve refreshed token ', err);
> > showToken('Unable to retrieve refreshed token ', err);
> > });
> > });`
> 
> with this
> 
> > Notification.requestPermission().then((permission) => {
> > if (permission === 'granted') {
> > messaging.getToken({ vapidKey: usePublicVapidKey }).then((currentToken) => {
> > if (currentToken) {
> > // Send Instance ID token to app server.
> > // [START_EXCLUDE]
> > // Display new Instance ID token and clear UI of all previous messages.
> > } else {
> > console.warn(Unable to retrieve FCM token.');
> > }
> > }).catch((err) => {
> > console.warn('Unable to retrieve FCM token.', err);
> > });
> > } else {
> > console.warn('Denied.');
> > }
> > }).catch((err) => {
> > console.error('Error.', err);
> > });
> 
> Now your sw.js file (in your root page) will call onMessage method fron `firebase.messaging`.
> 
> Also you have to change the server side. Until now, you just needed to send a request including your authorization key in headers, but after change, firebase needs an oAUTH grant. In my case, I was using php so I included Google library in my project.
> 
> You need to generate a service account private key (which will dwnload a json with the key)
> 
> You can go to your firebase project console -> configuration -> service account tab -> Generate new private key button (it will download a json.
> 
> You have to be sure that you have 'API HTTP v1 " enabled on firebase cloud messaging You can go to your firebase project console -> configuration -> Cloud messaging and check if tis correct
> 
> Once you have it, you have to include the Json in googles service and generate the Bearer key. here is an example with the php code
> 
> > $json = 'yout_private_key_json_generated_path.json';
> > $client = new Google();
> > $client->setAuthConfig($json)
> > $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
> > $accessToken = $client->fetchAccessTokenWithAssertion()['access_token'];
> > $fcmUrl = 'https://fcm.googleapis.com/v1/projects/erp-zafiro/messages:send';
> > $headers = [
> > 'Authorization: Bearer ' . $accessToken,
> > 'Content-Type: application/json'
> > ];
> > $notification = [
> > 'message' => [
> > 'token' => 'client_id_notifications_token',
> > 'notification' => [
> > 'title' => 'Your title',
> > 'body' => 'Message',
> > ],
> > 'data' => [
> > 'attribute_key' => 'value1',
> > 'attribute_key2' => 'value2',
> > ]
> > ]
> > ];
> > ```
> >     $ch = curl_init ();
> >     curl_setopt ( $ch, CURLOPT_URL, $fcmUrl );
> >     curl_setopt ( $ch, CURLOPT_POST, true );
> >     curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
> >     curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false);
> >     curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
> >     curl_setopt ( $ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
> >     curl_setopt ( $ch, CURLOPT_POSTFIELDS, $jsonEnvio );
> >     $response = curl_exec($ch);
> > ```
> 
> I hope its clear... For me was enough to do this.
> 
> Sorry for my english as well, i tried to do my best. I know its not the best english gramar and vocabulary
> 
> Regards

Hi Gillermo, I'm in the same situation as you. I had my web client and server working perfectly for years and stopped working one month ago.
Wher did you get this code?
I've used your code but I still haver errors wit this line
     const messaging = firebase.messaging();  
     Uncaught ReferenceError: firebase is not defined
How have you solved it? Could you send your full working javascript code related to firebase?

Best regards

**Comment by GuillermoPeralta** [comment]
Hi marcoahp,

Here my sw.js file


```
importScripts('https://www.gstatic.com/firebasejs/10.13.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.13.1/firebase-messaging-compat.js');


var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxx",
    projectId: "xxxxxxxx",
    storageBucket: "xxxxxxxxxxxxx",
    messagingSenderId: "xxxxxxxxxxx",
    appId: "xxxxxxxxxxxxx"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();

messaging.setBackgroundMessageHandler(function(payload) {
    const notificationTitle = payload.notification.title;
    const notificationOptions = {
        body: payload.notification.body,
        icon: 'logo.png'
    };
    return clients.matchAll({
        type: 'window',
        includeUncontrolled: true
    })
        .then((windowClients) => {
            for (let i = 0; i < windowClients.length; i++) {
                const windowClient = windowClients[i];
                windowClient.postMessage(payload.data);
            }
        })
        .then(() => {
            if (payload.data.notificar == "1" && false) {
                self.registration.showNotification(notificationTitle,
                    notificationOptions);
            } else {
                return null;
            }
        });

});
```
now here is my initfirebase.js

```
var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxx",
    projectId: "xxxxxxxx",
    storageBucket: "xxxxxxxxxxxxx",
    messagingSenderId: "xxxxxxxxxxx",
    appId: "xxxxxxxxxxxxx"
};


firebase.initializeApp(firebaseConfig);
firebase.analytics();
const messaging = firebase.messaging();

const usePublicVapidKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
```


When i wnat to manage notifications, i use this one

```
messaging.onMessage((payload) => {
    var data = null;
    if( typeof payload.data === 'undefined'){
        data = payload.notification;
    }else{
        data = payload.data;
    }
    var notificacion = new Notificacion(data);
    notificacion.ejecutar();
});

navigator.serviceWorker.addEventListener('message', function(event) {
    let data = null;
    if (Notification.permission === 'granted') {
        if (typeof event.data.firebaseMessaging !== 'undefined' &&
            typeof event.data.firebaseMessaging.payload !== 'undefined' &&
            typeof event.data.firebaseMessaging.payload.data !== 'undefined')
        {
            data = event.data.firebaseMessaging.payload.data;
        }else{
            data = event.data;
        }
        if(data !== null){
            var notificacion = new Notificacion(data);
            notificacion.ejecutar();
        }
    } else {
        console.warn('Permisos de notificación no concedidos.');
    }
});
```

Of ctouse, you have to use functions to get token, save token in your server, request for permisions, but this did not change.
I have a Notificaion.js class and i manage all notifications with some methods which are not so interesting.

I hope it can helps  you

Regards

**Comment by marcoahp** [comment]
Thanks Guillermo, I’ll test this and answer you with result

 

De: GuillermoPeralta ***@***.***> 
Enviado el: miércoles, 25 de septiembre de 2024 14:04
Para: firebase/firebase-js-sdk ***@***.***>
CC: marcoahp ***@***.***>; Comment ***@***.***>
Asunto: Re: [firebase/firebase-js-sdk] messaging.usePublicVapidKey not defined (Issue #8471)

 

Hi marcoahp,

Here my sw.js file

importScripts('https://www.gstatic.com/firebasejs/10.13.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.13.1/firebase-messaging-compat.js');
 
 
var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxx",
    projectId: "xxxxxxxx",
    storageBucket: "xxxxxxxxxxxxx",
    messagingSenderId: "xxxxxxxxxxx",
    appId: "xxxxxxxxxxxxx"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();
 
messaging.setBackgroundMessageHandler(function(payload) {
    const notificationTitle = payload.notification.title;
    const notificationOptions = {
        body: payload.notification.body,
        icon: 'logo.png'
    };
    return clients.matchAll({
        type: 'window',
        includeUncontrolled: true
    })
        .then((windowClients) => {
            for (let i = 0; i < windowClients.length; i++) {
                const windowClient = windowClients[i];
                windowClient.postMessage(payload.data);
            }
        })
        .then(() => {
            if (payload.data.notificar == "1" && false) {
                self.registration.showNotification(notificationTitle,
                    notificationOptions);
            } else {
                return null;
            }
        });
 
});

now here is my initfirebase.js

var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxx",
    projectId: "xxxxxxxx",
    storageBucket: "xxxxxxxxxxxxx",
    messagingSenderId: "xxxxxxxxxxx",
    appId: "xxxxxxxxxxxxx"
};
 
 
firebase.initializeApp(firebaseConfig);
firebase.analytics();
const messaging = firebase.messaging();
 
const usePublicVapidKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

When i wnat to manage notifications, i use this one

messaging.onMessage((payload) => {
    var data = null;
    if( typeof payload.data === 'undefined'){
        data = payload.notification;
    }else{
        data = payload.data;
    }
    var notificacion = new Notificacion(data);
    notificacion.ejecutar();
});
 
navigator.serviceWorker.addEventListener('message', function(event) {
    let data = null;
    if (Notification.permission === 'granted') {
        if (typeof event.data.firebaseMessaging !== 'undefined' &&
            typeof event.data.firebaseMessaging.payload !== 'undefined' &&
            typeof event.data.firebaseMessaging.payload.data !== 'undefined')
        {
            data = event.data.firebaseMessaging.payload.data;
        }else{
            data = event.data;
        }
        if(data !== null){
            var notificacion = new Notificacion(data);
            notificacion.ejecutar();
        }
    } else {
        console.warn('Permisos de notificación no concedidos.');
    }
});

Of ctouse, you have to use functions to get token, save token in your server, request for permisions, but this did not change.
I have a Notificaion.js class and i manage all notifications with some methods which are not so interesting.

I hope it can helps you

Regards

**Comment by marcoahp** [comment]
I’m testing but  there is something missing. Where do you use initfirebase.js?

 

I get an error at sw.js:

Uncaught TypeError: messaging.setBackgroundMessageHandler is not a function

 

I used this code for years without any problem, how could I adapt it to the new version?

Thanks for your help.

 

<script src="https://www.gstatic.com/firebasejs/6.0.1/firebase-app.js"></script>

                <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-messaging.js"></script>

                <script>

                  // Your web app's Firebase configuration

                  var firebaseConfig = {

                               apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxx",

                               authDomain: " xxxxxxxxxxxxxxxxxxxxxxxxxx ",

                               databaseURL: " xxxxxxxxxxxxxxxxxxxxxxxxxx ",

                               projectId: " xxxxxxxxxxxxxxxxxxxxxxxxxx ",

                               storageBucket: " xxxxxxxxxxxxxxxxxxxxxxxxxx ",

                               messagingSenderId: " xxxxxxxxxxxxxxxxxxxxxxxxxx ",

                               appId: " xxxxxxxxxxxxxxxxxxxxxxxxxx "

                  };

                  // Initialize Firebase

                  firebase.initializeApp(firebaseConfig);

                </script>

 

                <script>  

                  const messaging = firebase.messaging();  

                  messaging.usePublicVapidKey('xxxxxxxxxxxxxxxxxxxxxxxxxx ');   

                  const tokenDivId = 'token_div';

                  const permissionDivId = 'permission_div';         

                  messaging.onTokenRefresh(function() {

                               messaging.getToken().then(function(refreshedToken) {

                                 console.log('Token refreshed.');

                                 // Indicate that the new Instance ID token has not yet been sent to the

                                 // app server.

                                 setTokenSentToServer(false);

                                 // Send Instance ID token to app server.

                                 sendTokenToServer(refreshedToken);

                                 // [START_EXCLUDE]

                                 // Display new Instance ID token and clear UI of all previous messages.

                                 resetUI();

                                 // [END_EXCLUDE]

                               }).catch(function(err) {

                                 console.log('Unable to retrieve refreshed token ', err);      

                               });

                  });

                  

                  messaging.onMessage(function(payload) {

                               console.log('Message received. ', payload);

                                               

                               

                               if (!("Notification" in window)) {

                                               alert("El navegador no soporta notificaciones");

                               }

                               else if (Notification.permission === "granted") {

                                               var options = {

                                                               body: payload.data.body,

                                                               icon: 'favicon-4x.png',   

                                                               badge: 'badge.png',                                                       

                                                               requireInteraction: true

                                               }                              

                                               var isAndroid = /(android)/i.test(navigator.userAgent);

                                               if (isAndroid) {                                  

                                                               navigator.serviceWorker.ready.then(function(registration) {

                                                                               registration.showNotification(payload.data.title,options);

                                                               });           

                                                }

                                               else

                                               {

                                                               var notification = new Notification(payload.data.title,options);                                                

                                               }

                                               

                                                               

                               }

                

                  });

                  // [END receive_message]

 

                  function resetUI() {    

                                  

                               messaging.getToken().then(function(currentToken) {

                                 if (currentToken) {

                                               sendTokenToServer(currentToken);       

                                 } else {

                                               // Show permission request.

                                               console.log('No Instance ID token available. Request permission to generate one.');

                                               // Show permission UI.       

                                               setTokenSentToServer(false);

                                               requestPermission();

                                 }

                               }).catch(function(err) {

                                 console.log('An error occurred while retrieving token. ', err);      

                                 setTokenSentToServer(false);

                               });

                               // [END get_token]

                  }

 

 

                  // Send the Instance ID token your application server, so that it can:

                  // - send messages back to this app

                  // - subscribe/unsubscribe the token from topics

                  function sendTokenToServer(currentToken) {

                               if (!isTokenSentToServer()) {

                                               console.log('Sending token to server:' + currentToken);

                                               var xmlhttp = new XMLHttpRequest();                                  

                                               xmlhttp.onreadystatechange = function() {

                                                 if (this.readyState == 4 && this.status == 200) {

                                                               if (this.responseText=="ok")

                                                               {

                                                                               setTokenSentToServer(true);

                                                               }

                                                 }

                                               };                                            

                                               xmlhttp.open("GET", "token.asp?token=" + currentToken, true);

                                               xmlhttp.send();

                               } else {

                                 console.log('Token already sent to server so won\'t send it again ' +

                                                 'unless it changes');

                               }

 

                  }

 

                  function isTokenSentToServer() {

                               return window.localStorage.getItem('sentToServer') === '1';

                  }

 

                  function setTokenSentToServer(sent) {

                               window.localStorage.setItem('sentToServer', sent ? '1' : '0');

                  }

 

                  function showHideDiv(divId, show) {

                               const div = document.querySelector('#' + divId);

                               if (show) {

                                 div.style = 'display: visible';

                               } else {

                                 div.style = 'display: none';

                               }

                  }

 

                  function requestPermission() {

                               console.log('Requesting permission...');

                               // [START request_permission]

                               messaging.requestPermission().then(function() {

                                 console.log('Notification permission granted.');

                                 // TODO(developer): Retrieve an Instance ID token for use with FCM.

                                 // [START_EXCLUDE]

                                 // In many cases once an app has been granted notification permission, it

                                 // should update its UI reflecting this.

                                 resetUI();

                                 // [END_EXCLUDE]

                               }).catch(function(err) {

                                 console.log('Unable to get permission to notify.', err);

                               });

                               // [END request_permission]

                  }

 

                  function deleteToken() {

                               // Delete Instance ID token.

                               // [START delete_token]

                               messaging.getToken().then(function(currentToken) {

                                 messaging.deleteToken(currentToken).then(function() {

                                               console.log('Token deleted.');

                                               setTokenSentToServer(false);

                                               // [START_EXCLUDE]

                                               // Once token is deleted update UI.

                                               resetUI();

                                               // [END_EXCLUDE]

                                 }).catch(function(err) {

                                               console.log('Unable to delete token. ', err);

                                 });

                                 // [END delete_token]

                               }).catch(function(err) {

                                 console.log('Error retrieving Instance ID token. ', err);      

                               });

 

                  }

                               resetUI();

 

Best regards,

 

Marco

 

 

 

 

De: GuillermoPeralta ***@***.***> 
Enviado el: miércoles, 25 de septiembre de 2024 14:04
Para: firebase/firebase-js-sdk ***@***.***>
CC: marcoahp ***@***.***>; Comment ***@***.***>
Asunto: Re: [firebase/firebase-js-sdk] messaging.usePublicVapidKey not defined (Issue #8471)

 

Hi marcoahp,

Here my sw.js file

importScripts('https://www.gstatic.com/firebasejs/10.13.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.13.1/firebase-messaging-compat.js');
 
 
var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxx",
    projectId: "xxxxxxxx",
    storageBucket: "xxxxxxxxxxxxx",
    messagingSenderId: "xxxxxxxxxxx",
    appId: "xxxxxxxxxxxxx"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();
 
messaging.setBackgroundMessageHandler(function(payload) {
    const notificationTitle = payload.notification.title;
    const notificationOptions = {
        body: payload.notification.body,
        icon: 'logo.png'
    };
    return clients.matchAll({
        type: 'window',
        includeUncontrolled: true
    })
        .then((windowClients) => {
            for (let i = 0; i < windowClients.length; i++) {
                const windowClient = windowClients[i];
                windowClient.postMessage(payload.data);
            }
        })
        .then(() => {
            if (payload.data.notificar == "1" && false) {
                self.registration.showNotification(notificationTitle,
                    notificationOptions);
            } else {
                return null;
            }
        });
 
});

now here is my initfirebase.js

var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxx",
    projectId: "xxxxxxxx",
    storageBucket: "xxxxxxxxxxxxx",
    messagingSenderId: "xxxxxxxxxxx",
    appId: "xxxxxxxxxxxxx"
};
 
 
firebase.initializeApp(firebaseConfig);
firebase.analytics();
const messaging = firebase.messaging();
 
const usePublicVapidKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

When i wnat to manage notifications, i use this one

messaging.onMessage((payload) => {
    var data = null;
    if( typeof payload.data === 'undefined'){
        data = payload.notification;
    }else{
        data = payload.data;
    }
    var notificacion = new Notificacion(data);
    notificacion.ejecutar();
});
 
navigator.serviceWorker.addEventListener('message', function(event) {
    let data = null;
    if (Notification.permission === 'granted') {
        if (typeof event.data.firebaseMessaging !== 'undefined' &&
            typeof event.data.firebaseMessaging.payload !== 'undefined' &&
            typeof event.data.firebaseMessaging.payload.data !== 'undefined')
        {
            data = event.data.firebaseMessaging.payload.data;
        }else{
            data = event.data;
        }
        if(data !== null){
            var notificacion = new Notificacion(data);
            notificacion.ejecutar();
        }
    } else {
        console.warn('Permisos de notificación no concedidos.');
    }
});

Of ctouse, you have to use functions to get token, save token in your server, request for permisions, but this did not change.
I have a Notificaion.js class and i manage all notifications with some methods which are not so interesting.

I hope it can helps you

Regards

**Comment by GuillermoPeralta** [comment]
Be careful, you are usin old versions of firebase, change it with my script imports. If not, maybe you have not the same versions.

I use it in the end of my page

<script src="https://www.gstatic.com/firebasejs/10.13.1/firebase-app-compat.js"></script>
	<script src="https://www.gstatic.com/firebasejs/10.13.1/firebase-messaging-compat.js"></script>
	<script src="https://www.gstatic.com/firebasejs/10.13.1/firebase-analytics-compat.js"></script>
	<script src={{ asset('assets/js/firebase/notificacion.js') }}></script>
	<script src={{ asset('assets/js/firebase/init.js') }}></script>
	<script src={{ asset('assets/js/firebase/custom.js') }}></script>

i hope that helps you

Regards

**Comment by traffox-tech** [comment]
> I solved this and looks its working fine.
> 
> I wil try to explain what i did to solve. Maybe it helps someone.
> 
> You have to remove this, because is not longer necesary. Now you have to use getToken with the 'MYKEY' `messaging.usePublicVapidKey('MYKEY');`
> 
> lso you have to change this
> 
> > messaging.onTokenRefresh(() => {
> > messaging.getToken().then((refreshedToken) => {
> > // Indicate that the new Instance ID token has not yet been sent to the
> > // app server.
> > // Send Instance ID token to app server.
> > // [START_EXCLUDE]
> > // Display new Instance ID token and clear UI of all previous messages.
> > // [END_EXCLUDE]
> > }).catch((err) => {
> > //console.log('Unable to retrieve refreshed token ', err);
> > showToken('Unable to retrieve refreshed token ', err);
> > });
> > });`
> 
> with this
> 
> > Notification.requestPermission().then((permission) => {
> > if (permission === 'granted') {
> > messaging.getToken({ vapidKey: usePublicVapidKey }).then((currentToken) => {
> > if (currentToken) {
> > // Send Instance ID token to app server.
> > // [START_EXCLUDE]
> > // Display new Instance ID token and clear UI of all previous messages.
> > } else {
> > console.warn(Unable to retrieve FCM token.');
> > }
> > }).catch((err) => {
> > console.warn('Unable to retrieve FCM token.', err);
> > });
> > } else {
> > console.warn('Denied.');
> > }
> > }).catch((err) => {
> > console.error('Error.', err);
> > });
> 
> Now your sw.js file (in your root page) will call onMessage method fron `firebase.messaging`.
> 
> Also you have to change the server side. Until now, you just needed to send a request including your authorization key in headers, but after change, firebase needs an oAUTH grant. In my case, I was using php so I included Google library in my project.
> 
> You need to generate a service account private key (which will dwnload a json with the key)
> 
> You can go to your firebase project console -> configuration -> service account tab -> Generate new private key button (it will download a json.
> 
> You have to be sure that you have 'API HTTP v1 " enabled on firebase cloud messaging You can go to your firebase project console -> configuration -> Cloud messaging and check if tis correct
> 
> Once you have it, you have to include the Json in googles service and generate the Bearer key. here is an example with the php code
> 
> > $json = 'yout_private_key_json_generated_path.json';
> > $client = new Google();
> > $client->setAuthConfig($json)
> > $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
> > $accessToken = $client->fetchAccessTokenWithAssertion()['access_token'];
> > $fcmUrl = 'https://fcm.googleapis.com/v1/projects/erp-zafiro/messages:send';
> > $headers = [
> > 'Authorization: Bearer ' . $accessToken,
> > 'Content-Type: application/json'
> > ];
> > $notification = [
> > 'message' => [
> > 'token' => 'client_id_notifications_token',
> > 'notification' => [
> > 'title' => 'Your title',
> > 'body' => 'Message',
> > ],
> > 'data' => [
> > 'attribute_key' => 'value1',
> > 'attribute_key2' => 'value2',
> > ]
> > ]
> > ];
> > ```
> >     $ch = curl_init ();
> >     curl_setopt ( $ch, CURLOPT_URL, $fcmUrl );
> >     curl_setopt ( $ch, CURLOPT_POST, true );
> >     curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
> >     curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false);
> >     curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
> >     curl_setopt ( $ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
> >     curl_setopt ( $ch, CURLOPT_POSTFIELDS, $jsonEnvio );
> >     $response = curl_exec($ch);
> > ```
> 
> I hope its clear... For me was enough to do this.
> 
> Sorry for my english as well, i tried to do my best. I know its not the best english gramar and vocabulary
> 
> Regards

Hi, GuillermoPeralta! Do you send notifications with php? I have some problems after firebase update. Before their update i sent batch of 500 items with registration_ids, but this feature was depricated. Do you know how to fix this without using any "topics"? Cause i have more than 1 million subscribers, i don't understand how to send them push after firebase update.
