### ISSUE TITLE
Getting error https://firebaseinstallations.googleapis.com/v1/projects/"projectKey"/installations/"api key"/authTokens:generate 

### ISSUE THREAD

**Issue by Nalumasu-Anjali** [firebase/firebase-js-sdk#8477]
### Operating System

All

### Environment (if applicable)

Prod

### Firebase SDK Version

8.2.8

### Firebase SDK Product(s)

Remote-Config

### Project Tooling

Reat app 

### Detailed Problem Description

Hi When we are trying to get auth token we are getting 404 error with the following APiI , this is only happening on Production and is happening in the recent days.

https://firebaseinstallations.googleapis.com/v1/projects/"projectKey"/installations/"api key"/authTokens:generate

We have used firebase as the core for our project config, becuase of this our config is not loaded and in the recent days we have seen this issue multiple times. 
Can some one please suggest what may the solution for this 

### Steps and code to reproduce issue

When we login to the application we are facing issue.

**Comment by Nalumasu-Anjali** [comment]
Can someone please guide why we will get this issue.

**Comment by hsubox76** [comment]
Does it literally say "projectKey" and "api key" in the url or does it have your correct project and API key there, and you just replaced it when reporting the issue?

**Comment by Nalumasu-Anjali** [comment]
No, it will have my project name and api key. While posting this i replaced those values.

**Comment by dlarocque** [comment]
Thanks for reporting this issue @Nalumasu-Anjali. I'd like to try to reproduce the issue- could you please share a minimal reproduction of the issue, along with steps I can follow to reproduce it?

**Comment by DellaBitta** [comment]
Hi @Nalumasu-Anjali,

Has your app's usage of the SDK changed recently? Did you upgrade the SDK version or alter the methods you call? If not, I suggest reaching out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact). Perhaps they know of a service outage or could look into to see if there have been any recent problems with your projects endpoint.
