### ISSUE TITLE
query using collection.limit() returns entire collection - limit remains set to null

### ISSUE THREAD

**Issue by andyfusniak** [firebase/firebase-js-sdk#849]
* Operating System version: Mac OS 10.11.6 using Node v8.11.1 with Vue.js webpack project

  * Firebase SDK version:
```json
"dependencies": {
    "@firebase/app": "^0.3.2",
    "@firebase/auth": "^0.5.2",
    "@firebase/firestore": "^0.5.3"
  }
```
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

Invoking the .limit() method on a collection fails to set the limit. Instead the entire collection is returned.

#### Steps to reproduce:

Create a collection in a Firestore and add 4 items. Set up a limit query using Node.js Client using similar code shown below.

#### Relevant Code:
```javascript
try {
      let colRef = firebase.firestore().collection('stuff');

      colRef.limit(2);

      let querySnapshot = await colRef.get(); // _query.limit = null so returns the entire collection
```

https://stackblitz.com/edit/firebase-issue-sandbox-zw5mmw

**Comment by andyfusniak** [comment]
This problem seems to arise as a result of a broken fluent interface, creating new Query objects for each link in the chain.

https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/core/query.ts#L146-L166

This works:

```javascript
let colRef = firebase.firestore().collection('things');
let query = colRef.orderBy('created', 'desc').limit(2);
```

But, this doesn't because of the change in the call site of the method.

```javascript
let colRef = firebase.firestore().collection('things');
let query = colRef.orderBy('created', 'desc');
query.limit(2);
```

**Comment by mikelehen** [comment]
@andyfusniak This is the intended behavior of the API.  You build up a query through chaining operations together.  We explicitly want you to be able to do things like:

```
const todos = db.collection('todos');
...
const importantTodos = todos.where('priority', '>', 8);
const overdueTodos = todos.where('due_date', '<=', new Date());
```

And so it's important that the query operators don't modify the original query.  Hope this helps!

**Comment by mikelehen** [comment]
I'm not sure I understand what you're asking.  Your example does:

```
  col.limit(limit);  // THIS IS IGNORED
  return col.get(); // returns the entire collection
```

You need to do:

```
  const query = col.limit(limit);  // THIS IS IGNORED
  return query.get(); // returns the entire collection
```

Collection and Query objects are immutable in Firestore. You cannot change them. You can only call methods that return new (mutated) instances.

**Comment by andyfusniak** [comment]
Thanks @mikelehen. I got it now.
