### ISSUE TITLE
Firebase Messaging SDK expects firebase-messaging-sw.js to be in the web root folder, which is often not accessible

### ISSUE THREAD

**Issue by andynewman10** [firebase/firebase-js-sdk#8496]
### Operating System

Any

### Environment (if applicable)

Any

### Firebase SDK Version

10.20.0

### Firebase SDK Product(s)

Messaging

### Project Tooling

Plain Javascript

### Detailed Problem Description

I did not find a way to customize the location of the Firebase service worker using the Firebase JS SDK.

Reading the source file, it seems this is not possible:

https://github.com/firebase/firebase-js-sdk/blob/main/packages/messaging/src/helpers/registerDefaultSw.ts

```
...
    messaging.swRegistration = await navigator.serviceWorker.register(
      DEFAULT_SW_PATH,
      {
        scope: DEFAULT_SW_SCOPE
      }
    );
...
```

### Steps and code to reproduce issue

1. Create any basic Javascript app using Firebase Messaging.
2. Add a blank firebase-messaging-sw.js file next to your index.html file. Make sure things work locally.
3. Now deploy your application to a non-root web folder, eg. to https://www.example.com/foo/. This means your application HTML file will be https://www.example.com/foo/index.html and the Firebase service worker will be https://www.example.com/foo/firebase-messaging-sw.js.
4. Run your application with your browser: the Firebase JS SDK will try to load firebase-messaging-sw.js from the root folder, not from /foo/, as it should.

The only possible workaround is to fiddle with Javascript prototypes and alter the behavior of register(), which is extremely hacky.

**Comment by dlarocque** [comment]
This is the expected behaviour for the default SW registration.

If you want to use a `firebase-messaging-sw.js` that is not at the root, you can register it yourself and pass it to `getToken` (https://firebase.google.com/docs/reference/js/messaging_.gettokenoptions.md#gettokenoptionsserviceworkerregistration).

```js
navigator.serviceWorker.register(/* firebase-messaging-sw.js in /foo */).then((registration) => getToken(registration, vapidKey));
```

Let me know if doesn't work for you or if I misunderstood your issue.

**Comment by andynewman10** [comment]
Thank you. I see, you also support this scenario, which is great. I'll have to see how I can integrate this with Flutter, but this is another story.
Thanks again.
