### ISSUE TITLE
onAuthStateChanged concurrency issue

### ISSUE THREAD

**Issue by Dipen-Dedania** [firebase/firebase-js-sdk#850]
I'm facing an issue while checking if user is logged in or not. I have tried both the approaches to check if user is logged in or not.
1. firebase.auth().currentUser
2. firebaseApp.auth().onAuthStateChanged

My use case is something like this. I have hybrid application in which I'm displaying browser. I have login browser in which if user login then it will spawn multiple browsers. So in those browsers I need to check if user is logged-in (fail-check) and if he/she is logged in then I'll need a user info. But sometimes it returns null randomly in some browsers (may be concurrency issue while checking **onAuthStateChanged** listener) so I was trying to debug the issue. I put a breakpoints in both browser (chrome) and tried to refresh both browser at the same time. I came across a weird behavior that even it's a separate browser and they are trying to execute below code, one browser will freeze until the other instance doesn't resume the execution. Refer attached GIF for details. Not sure if it's related to the same file debugging. And it was also working fine before few days. Also tried updating a package to recent one but no luck. Looking forward to hear from you soon.

Environment
  * Operating System version: Windows 10, Chrome
  * Firebase JS SDK version: 4.10.1 / 5.0.3
  * Firebase Product: auth

```
let unsubscribe = firebaseApp.auth().onAuthStateChanged(function (user) {
	if (!user) {
		// User is not logged in
		unsubscribe();
	}
	else {
		// User is logged in - process to next
		unsubscribe();
	}
});
```
![fb_issue2](https://user-images.githubusercontent.com/5135662/40309293-97c511b0-5d26-11e8-8dbe-a11db89c0c63.gif)

Thanks!

**Comment by bojeil-google** [comment]
I don't quite understand what you are trying to say: " I came across a weird behavior that even it's a separate browser and they are trying to execute below code, one browser will freeze until the other instance doesn't resume the execution. "
If it helps, `onAuthStateChanged` will not trigger at the exact time as the tab where the user signed in. There will be a fraction of second delay. This is expected.

**Comment by Vindexus** [comment]
I have also been encountering an issue where the data returned by `onAuthStateChanged` is null. This commonly happens in my dev environment when I save a file and webpack rebuilds and refreshes the app.

On production this issue would sometimes happen on page refresh, or when a link from the app was opened in a new tab.

While trying to debug I did this
```
function getFirebaseAuthCookie () {
  return localStorage.getItem(`firebase:authUser:${firebaseConfig.apiKey}:[DEFAULT]`)
}```

and found that the value was sometimes null.

I'm not sure if this is helpful.

**Comment by Dipen-Dedania** [comment]
@bojeil-google basically the issue is, even I'm logged into Firebase, when I tried to check (run **firebaseApp.auth().onAuthStateChanged** ) into other tabs **simultaneously**, it returns _null_ randomly. It's not a scenario of user is just logged-in and you are trying to fetch the data, it happens almost every time when you refresh your tab simultaneously which execute onAuthStateChanged. If you refresh it one by one then it will work perfectly. And this started happening from last month only.

Note: I also tried adding timeout, but still no luck.

@Vindexus Thanks! I tried to do workaround like storing User object into local-storage but it fails to read the data from Firebase DB due to permission level. Seems like there is no session accessible in that.

**Comment by bojeil-google** [comment]
I have been unable to reproduce this. I will try to run some tests and keep an eye on this. 
The only unusual thing I have noticed from recent reports and which I was able to reproduce was when the Auth library is double included. In that case user state is not persisted correctly and some weird stuff happens. However, as long as you are using the library as expected, I have not noticed any of the reported unexpected behavior.

**Comment by Dipen-Dedania** [comment]
@bojeil-google I have created repo to reproduce this bug. On login it will open 5 tabs so make sure to **Allow popup** in browser. You can see that in some tabs, user's data is not available.

Repo link - https://github.com/Dipen-Dedania/firebase-bug

Demo - https://dipen-dedania.github.io/firebase-bug/#/

**Comment by Vindexus** [comment]
@Dipen-Dedania Have you managed to find a solution to this? It's still plaguing me.

**Comment by rommelpe** [comment]
@Dipen-Dedania sorry for the delay. I was wondering if you are still experiencing this issue after the fix. 

You may also consider upgrading your [SDK to the latest version](https://firebase.google.com/support/release-notes/js), and see if it persists from there. Thanks!

**Comment by Dipen-Dedania** [comment]
@rommelpe I have stopped using Firebase Authentication so not sure if it's fixed. We can close this for now.
