### ISSUE TITLE
FunctionsError exported as a type only, but implementation exists 

### ISSUE THREAD

**Issue by ilyary** [firebase/firebase-js-sdk#8511]
### Operating System

macOS

### Environment (if applicable)

vite@5

### Firebase SDK Version

"firebase": "10.13.1", "@firebase/functions": "0.11.7"

### Firebase SDK Product(s)

Functions

### Project Tooling

vite@5

### Detailed Problem Description

In my setup FunctionsError is resolved from ./node_modules/@firebase/functions/dist/functions-public.d.ts
![image](https://github.com/user-attachments/assets/916a5334-0d59-4cbc-86e4-5dbddc564a64)

And it's not a class although an implementation exist in the bundle ./node_modules/firebase/firebase-functions.js

Vite output:
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/firebase_functions.js?v=bd8c5d40' does not provide an export named 'FunctionsError' (at callable.ts:3:3)

Could you pls export FunctionsError as class for better error handling?

### Steps and code to reproduce issue

import { FirebaseError } from 'firebase/app';
import {
  FunctionsError,
} from 'firebase/functions';

console.log({ FunctionsError });

**Comment by jbalidiong** [comment]
Hi @ilyary, thanks for bringing this to our attention. I was able to reproduce the behavior. This feature is being tracked internally. I'll keep the ticket open until the feature is implemented or bug is fixed for visibility.

b/368936180
