### ISSUE TITLE
Firebase client sometimes tries to production server while using connectAuthEmulator

### ISSUE THREAD

**Issue by bunyaminmrcn** [firebase/firebase-js-sdk#8519]
### Operating System

Kali Linux

### Environment (if applicable)

Chrome 129, Firefox 130

### Firebase SDK Version

10.13.2

### Firebase SDK Product(s)

Auth

### Project Tooling

next project with next-auth@4.24.7

### Detailed Problem Description

I set it up local emulator for firebase auth & firestore & storage & functions. But issue happen while authorizing

### Steps and code to reproduce issue

I run `initEmulator` function in useEffect hook after login. It asks to credentials to production server 
(`https://identitytoolkit.googleapis.com/v1/accounts:lookup`)

```
import { initializeApp, getApp } from 'firebase/app';
import { connectAuthEmulator, getAuth } from 'firebase/auth';

const firebaseConfig = {
  apiKey: "test",
  authDomain: 'http://127.0.0.1:9099',
  databaseURL: "http://127.0.0.1:8080",
  projectId: "test",
};

const firebaseApp = initializeApp(firebaseConfig);

let initialized = false;
const initEmulator = () => {
  if (!initialized) {
    try {
      
      connectAuthEmulator(firebaseAuth, 'http://127.0.0.1:9099')
      console.log("Connected to Emulator")
      initialized = true;
    } catch(err) {
      console.log("Error occured")
    }
    
  }
}

const firebaseAuth = getAuth(firebaseApp)
export { firebaseApp, firebaseAuth, initEmulator }


```

**Comment by hsubox76** [comment]
I'm not sure I am understanding correctly - you're running initEmulator after login? Isn't it too late? Doesn't the login operation itself call the backend, if no emulator has been initialized? Or do you mean you're running it after initializing auth, not login?

Regardless, useEffect has some weird timing and usually happens after initial page load. I don't think I'd feel safe putting anything in there that I want to run before the rest of my code. I'd probably start the emulator outside of any component. It's not a UI operation.

**Comment by bunyaminmrcn** [comment]
Put initEmulator to directly in component doesn't effect

**Comment by jbalidiong** [comment]
Hi @bunyaminmrcn, I tried replicating the issue but wasn't able to reproduce the same behavior. I created this [repo](https://github.com/jbalidiong/issue-8519) to try and replicate the setup you have. In case I missed anything or made a mistake with the setup, just let me know. Alternatively, any chance you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us replicate the issue?
