### ISSUE TITLE
Firebase signInWithPopup triggers Cross-Origin-Opener-Policy policy would block the window.closed call.

### ISSUE THREAD

**Issue by ionutcirja** [firebase/firebase-js-sdk#8541]
### Operating System

MacOS Sonoma 14.6.1

### Environment (if applicable)

Chrome 129.0.6668.71

### Firebase SDK Version

10.12.3

### Firebase SDK Product(s)

Auth

### Project Tooling

NextJS 14

### Detailed Problem Description

I managed to authenticate successfully with Firebase, but when I call signInWithPopup this error can be seen in the console: Cross-Origin-Opener-Policy policy would block the window.closed call.

In my nextjs project I set the opener policy header like this:
```
async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'Cross-Origin-Opener-Policy',
            value: 'same-origin-allow-popups',
          },
        ],
      },
    ];
  },
```

### Steps and code to reproduce issue

When I click on a button, I call firebase auth signInWithPopup method. The open opens, now the error appears in the console.

Error doesn't trigger in latest versions of Firefox and Safari.

**Comment by ExpertzZ** [comment]
same problem here.

**Comment by jbalidiong** [comment]
Hi @ionutcirja, thanks for bringing this to our attention. This seems similar to #8265. Just for clarification, can you provide the following information:

- Does the authentication fails when encountering this issue? 
- If you check through the code that sends the request using the debugger, are you able to see where the problematic header is attached to the request?
- If the previous step fails, could you provide a minimal application (an app with the minimal amount of code and dependencies, e.g. no react effects, context, etc.) where the issue occurs? If I can replicate the issue, I can have a better look into it and try to identify the problem.

Also, was the error reported by Firebase? According to the related issue above, it is possible that it is reported by the browser engine ([source](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/dom_window.cc;l=63?q=Cross-Origin-Opener-Policy%20policy%20would%20block%20the%20window.close&ss=chromium)), not the SDK.

**Comment by ionutcirja** [comment]
Hi @jbalidiong,

The authentication works perfectly actually.
And yes, the error is reported by the browser engine, not the sdk.

**Comment by vrathi101** [comment]
I am facing a similar issue as well. I am using react native with expo to run my app and am trying to integrate google authentication into my app.
The following is the relevant piece of code I have:
`const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
    clientId: "********.apps.googleusercontent.com",
    redirectUri: "https://auth.expo.io/@my-username/my-slug"
  });`
I added this redirectUri to my google cloud console project as well (connected to firebase for authentication). 

Whenever I run my app and log in through google I get the message "Something went wrong trying to finish signing in. Please close this screen to go back to the app." and the error `Cross-Origin-Opener-Policy policy would block the window.closed call`

**Comment by dlarocque** [comment]
> Hi @jbalidiong,
> 
> The authentication works perfectly actually. And yes, the error is reported by the browser engine, not the sdk.

If authentication is working, the error is coming from Chrome, and the `Cross-Origin-Opener-Policy` header is configured in NextJS, what is the issue or desired behavior in the Firebase JS SDK?
