### ISSUE TITLE
Firestore rule not working

### ISSUE THREAD

**Issue by bunyaminmrcn** [firebase/firebase-js-sdk#8544]
### Operating System

Apple M2

### Environment (if applicable)

Chrome 129, Firefox 130

### Firebase SDK Version

10.13.2

### Firebase SDK Product(s)

Auth, Firestore

### Project Tooling

Next.js

### Detailed Problem Description

match /posts/{document} {
     allow read: if request.auth != null && resource.data.public == true;
     allow write: if request.auth != null ;
     allow list: if request.auth != null && resource.data.public == true;
}

### Steps and code to reproduce issue

I am logged as admin user. My error case happens in `list` . My posts collection of documents has public identifier/attribute. Real error is `FirebaseError: 
Property public is undefined on object. for 'list' @ L39, Property public is undefined on object`

**Comment by bunyaminmrcn** [comment]
![IMG_20240928_191133_DRO.jpg](https://github.com/user-attachments/assets/4789f2d2-d14f-4930-807c-3214a3e1108d)

Here is a document in posts collection

**Comment by ehsannas** [comment]
@yuchenshi could you take a look and/or route to the right person?

**Comment by yuchenshi** [comment]
As this issue isn't with the open source JavaScript SDK but with Firebase Rules (backend / emulator), please submit a Support ticket at https://firebase.google.com/support instead.
