### ISSUE TITLE
Property 'database' does not exist on type 'FirebaseApp'

### ISSUE THREAD

**Issue by NeoLegends** [firebase/firebase-js-sdk#855]
Citing @mmermerkaya from https://github.com/firebase/firebase-js-sdk/issues/791:

> This was only fixed for imports from `firebase/*`, not `@firebase/*`. It's recommended to import from `firebase/*` packages for now. You can open a different issue for imports from `@firebase/*`.

Here is that different issue. This is a regression that breaks peoples builds (if they're not using lockfiles -- we fortunately do), so please fix it quickly.

**Comment by unnisapp** [comment]
I was using the firebase.database option earlier, it was working great for me, but all of a sudden for my new code it shows above issue. 

[ts] Property 'database' does not exist on type 'typeof "/node_modules/firebase/app/index"

When I checked the file at "\node_modules\@firebase\database\package.json", it was also showing an error as given below.

"bundleDependencies": false -> Incorrect type. Expected "array"

The same code is working for me, in my old apps created. only for new one its giving error.

Thanks,
Unni

**Comment by jshcrowthe** [comment]
@NeoLegends, the `@firebase/*` packages were all shipped at a major `0` so we could make breaking changes as needed. For now, you should use only the `firebase/*` packages in your production builds.

@unnisapp if you can open a new issue and get me a repro of what it is your seeing that'd be great.

**Comment by NeoLegends** [comment]
> @NeoLegends, the @firebase/* packages were all shipped at a major 0 so we could make breaking changes as needed. For now, you should use only the firebase/* packages in your production builds.

Ah, interesting. Seems like we made the mistake of declaring the `firebase`-module a dependency of our app, but subsequently used the `@firebase`-packages for importing. This way we didn't notice the `@firebase` modules were at `0.x`. Thanks for the heads-up!
