### ISSUE TITLE
Vertex AI - `generateContentStream` aggregated output undefined

### ISSUE THREAD

**Issue by andrewheard** [firebase/firebase-js-sdk#8566]
### Operating System

macOS Sonoma 14.1

### Environment (if applicable)

NodeJS

### Firebase SDK Version

main

### Firebase SDK Product(s)

VertexAI

### Project Tooling

N/A - @dlarocque may have more details

### Detailed Problem Description

Vertex AI omits default values (`index == 0`) when serializing its responses as JSON but the SDK assumes the `index` value will always be there in [`aggregateResponses()`](https://github.com/firebase/firebase-js-sdk/blob/64db19264bb5811683b3413b5c5f1e6b79e5b090/packages/vertexai/src/requests/stream-reader.ts#L149). See https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/21 for more details ([test failure](https://github.com/FirebaseExtended/vertexai-sdk-test-data/actions/runs/11299334600/job/31430076375?pr=21)).

### Steps and code to reproduce issue

The following snippet demonstrates the issue:
```
async function run() {
  const prompt = "Write a story about a magic backpack."

  const result = await model.generateContentStream(prompt);
  for await (const chunk of result.stream) {
    const chunkText = chunk.text();

    // No issues - WAI
    console.log(chunkText);
  }

  // Not working because of the undefined index
  console.log('aggregated response: ', await result.response);
}

run()
```

**Comment by hsubox76** [comment]
Not sure why the `Fixes` didn't autoclose this.
