### ISSUE TITLE
.delete() not sufficient for node process to disconnect

### ISSUE THREAD

**Issue by one19** [firebase/firebase-js-sdk#859]
### Environment:

  * Operating System version: MacOS 10.13.4
  * Environment: Node command line interface
  * Firebase SDK version: at least 4.4.0 and beyond
  * Firebase Product: database/auth

### Issue:
calling `.delete()` not sufficient for node process to disconnect.

#### Steps to reproduce:

What I've thought all along was a pretty standard use for a small cli module:
```js
const ref = await firebase.initializeApp({...});
await ref.auth().signInWithEmailAndPassword(...);

const currentStatusObj = await ref
    .database()
    .ref(...current)
    .once('value');

const newKey = await ref
      .database()
      .ref(...log)
      .child('all')
      .push().key;

await firebase
      .database()
      .ref()
      .update({
        ... multiple paths using path/newKey
      });

return ref.delete()
```
**Except** ref.delete() doesn't allow the node process to exit. Ever.

I've had to hack around it with a `process.exit()` callback for a while now. But now I'm 11 messages into a `firebase-functions` support issue because using the `firebase` module in an isomorphic way (functions & cli) causes delays of 20 -> 40 seconds if you return early [(even on a hot start)](https://gfycat.com/ElasticFirstDoctorfish). I'd love to narrow down the cause, and to see if this crazy hangup issue that [Version 3.4.1](https://firebase.google.com/support/release-notes/js) says was fixed is the culprit.

And, just to check, I removed the nice function wrappers and `ref` passing, and `firebase` still wouldn't exit on a `firebase.app().delete()`. *nor does `.goOffline()`*

#### Relevant Code:

https://github.com/one19/im-doin (isomorphic firebase interaction module)
https://github.com/one19/im-doin-slack (function environment where it's not invoked via command line)

firebase web sandbox doesn't provide an adequate location for realizing use case of a node environment.

**Comment by a-xin** [comment]
I had a similar issue where node was not terminating. In my case, I had to also call `auth().signOut()`:
```
firebase.database().ref()
  .update(...)
  .then(() => database.goOffline())
  .then(() => firebase.auth().signOut())
  .then(() => app.delete())
``

**Comment by one19** [comment]
ohmygosh i forgot that I had this as an open ticket! You're absolutely right, thanks!
