### ISSUE TITLE
Google Sign In redirects to __auth/handler

### ISSUE THREAD

**Issue by kelvinwatson** [firebase/firebase-js-sdk#86]
### Environment

  * Operating System version:  Windows
  * Firebase SDK version: 4.1.3
  * Firebase Product: auth 

### Problem

I implemented Google Sign-In using Firebase Auth by following the instructions here. https://firebase.google.com/docs/auth/web/google-signin. I used `.signInWithPopup(provider)`. Everything seems to work, except after entering my gmail and password, I am redirected to https://mysite.com/__auth/handler, rather than back to the page I was on on my site. Is this the expected behavior?

#### Reproduction Steps:
Follow the implementation described at https://firebase.google.com/docs/auth/web/google-signin under `To sign in by redirecting to the sign-in page, call signInWithRedirect`

#### Relevant Code:

```
      _googleSignIn() {
        var provider = new firebase.auth.GoogleAuthProvider();
        firebase.auth().signInWithRedirect(provider).then(function(result) {
          console.log('Sign in finished');
          console.log(result);
          // This gives you a Google Access Token. You can use it to access the Google API.
          var token = result.credential.accessToken;
          // The signed-in user info.
          var user = result.user;
          // ...
        }).catch(function(error) {
          console.log(error);
          // Handle Errors here.
          var errorCode = error.code;
          var errorMessage = error.message;
          // The email of the user's account used.
          var email = error.email;
          // The firebase.auth.AuthCredential type that was used.
          var credential = error.credential;
          // ...
        });
      }
```

**Comment by bojeil-google** [comment]
`signInWithRedirect` promise will not resolve in a browser environment as the page will redirect.
To get back the result from the redirect, you should use `getRedirectResult`.
As for your question, when your trigger signInWithRedirect, the flow is as follows:
your app -> https://PROJECT_ID.firebaseapp.com/__/auth/handler -> IdP website, for google accounts.google.com -> https://PROJECT_ID.firebaseapp.com/__/auth/handler -> your app.

The popup flow is similar but instead of a redirect, it opens a popup directly and redirects it to https://PROJECT_ID.firebaseapp.com/__/auth/handler.

If you are not get redirected back to your app then there is some other problem. Please check the console for any errors and report them back. Make sure you also provide network request errors from the Auth backend.

**Comment by kelvinwatson** [comment]
I see three consecutive calls in the Network traffic: 
1. `https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=<MY-API-KEY>&cb=1499037801685` Request Method: OPTIONS
2. `https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=<MY-API-KEY>&cb=1499037801685` Request Method: GET
3. `https://my-example-app.firebaseapp.com/__/auth/handler?apiKey=<MY-API-KEY>&appName=%5BDEFAULT%5D&authType=signInViaRedirect&providerId=google.com&scopes=profile&redirectUrl=https%3A%2F%2F<my-example-app.firebaseapp.com>%2Faccount&v=4.1.3` Request Method: GET

These three calls returned with status code of 200. However, I did get the following errors in my console:

    Uncaught 
    e {code: "app/duplicate-app", message: "Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).", name: "[DEFAULT]", stack: "FirebaseError: Firebase: Firebase App named '[DEFA…polymer/lib/mixins/property-effects.html:1:11618)"}
    code
    :
    "app/duplicate-app"
    message
    :
    "Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app)."
    name


    Uncaught Error: Network Error
    at firebase-auth.js:161

**Comment by bojeil-google** [comment]
Where and when are you getting these errors? in the original window? Is there a corresponding 400 error in the network log?
It appears you are initialization the same Firebase app twice. That could be the reason. You need to provide more context or actual reproducible code. If you can provide a website link for me to check, it would make debugging this issue a lot easier.

**Comment by kelvinwatson** [comment]
Sorry, the duplicate-app was a red herring and wasn't related to the sign-in redirect issue.

I believe I have resolved the issue. After fixing the duplicate-app error and debugging further I've confirmed that the issues stems from using `polymer build` using the `es6-unbundled` preset. If I simply `firebase deploy` without `polymer build`, the sign in flow works. That gave me a hint that it could be related to the generated service worker, which led me to this github issue:  https://github.com/Polymer/polymer-build/issues/35
 
When I follow the example and add the navigateFallback lines to sw-precache-config.js, it worked.

## sw-precache-config.js

```
module.exports = {
  staticFileGlobs: [
    '/index.html',
    '/manifest.json',
    '/bower_components/webcomponentsjs/webcomponents-lite.min.js'
  ],
  navigateFallback: '/index.html',
  navigateFallbackWhitelist: [/^(?!\/__)/]
};
```

**Comment by bojeil-google** [comment]
Thanks for the update @kelvinwatson. Glad you figured it out.

**Comment by kelvinwatson** [comment]
Thanks @bojeil-google for taking the time!
