### ISSUE TITLE
FCM send duplicate message

### ISSUE THREAD

**Issue by bangln** [firebase/firebase-js-sdk#8624]
### Operating System

window 11

### Environment (if applicable)

N/A

### Firebase SDK Version

9.16

### Firebase SDK Product(s)

Messaging

### Project Tooling

React app, php

### Detailed Problem Description

I send message to firebase and got 2 noti in my device: 
![image](https://github.com/user-attachments/assets/d8150741-7f68-43ac-9370-03f05fb22791)

### Steps and code to reproduce issue

API endpoint: https://fcm.googleapis.com/v1/projects/project-id/messages:send
body: {
  "message": {
    "token" : "token",
    "notification": {
      "title": "test"
    },
    "webpush": {
      "headers": {
        "Urgency": "high"
      },
      "notification": {
        "body": "test"
      }
    }
  }
}

**Comment by hsubox76** [comment]
In order to see if this is an SDK error, we need to see the code you are using in your app that is receiving the messages, not the REST call you are making to send the message. Are you using onMessage, onBackgroundMessage, or both? What does your code in each look like? Make sure to indicate which code is in your main app and which code is in the service worker.

**Comment by bangln** [comment]
I use this code: 
export const getMessagingToken = async () => {
    let currentToken = "";
    const messagingResolve = await messaging();
    if (!messagingResolve) return;
    try {
        currentToken = await getToken(messagingResolve, {
            vapidKey: ""
        });
    } catch (error) {
        console.log("An error occurred while retrieving token. ", error);
    }
    return currentToken;
};
export const onMessageListener = () =>
    new Promise((resolve) => {
        messaging.onMessage((payload) => {
            resolve(payload);
        });
    });
export default {
    getMessagingToken,
    onMessageListener
}
but I dont call onMessageListener in antwhere, i just getToken and use it to push message
