### ISSUE TITLE
Default Auth State Persistence not working as expected with React + Vite

### ISSUE THREAD

**Issue by dpschramm** [firebase/firebase-js-sdk#8626]
### Operating System

macOS 14.5 (23F79)

### Environment (if applicable)

Chrome 129.0.6668.60 (arm64), Vite 5.4.10, React 18.3.1

### Firebase SDK Version

11.0.1

### Firebase SDK Product(s)

Auth

### Project Tooling

React app built with Vite

### Detailed Problem Description

I expected auth state to persist by default as I am creating a web app with React and Vite. However, the auth state is cleared on page refresh.

I am accessing the auth state using onAuthStateChanged(). It never fires an event with a non-null user by default.

Setting the persistence setting fixes this:
```
const firebaseAuth = initializeAuth(firebaseApp, {
    persistence: [browserLocalPersistence]
});
```

I'm filing this bug as the default behaviour does not match the documentation in: https://firebase.google.com/docs/auth/web/auth-state-persistence#web

### Steps and code to reproduce issue

1. Create a new React app using Vite
2. Attempt to read previous auth state using onAuthStateChanged()

Expected: receive an onAuthStateChanged() callback with a valid user, if the user was previously signed in.

Observed: never receive an onAuthStateChanged() callback with a valid user. Setting persistence manually during initializeAuth fixes this.

**Comment by DellaBitta** [comment]
Hi @dpschramm,

Unfortunately we couldn't reproduce this issue. We've created an [verifiable example here](https://github.com/jbalidiong/issue-8626). Could you alter it to reproduce the issue that you're seeing and let us know what the required changes are? Thanks!
