### ISSUE TITLE
Update Firestore Indexes Documentation

### ISSUE THREAD

**Issue by TimmNL** [firebase/firebase-js-sdk#8634]
### Operating System

all

### Environment (if applicable)

all

### Firebase SDK Version

11.0.1

### Firebase SDK Product(s)

Firestore

### Project Tooling

Firestore Indexes JSON

### Detailed Problem Description

Currently the documentation states there is no support for vector values in indexes. By accident I found this following PR https://github.com/firebase/firebase-tools/pull/6900 that made it possible to add vectors in indexes. The documentation on however is still missing

### Steps and code to reproduce issue

Try adding indexes by JSON with a vector

**Comment by MarkDuckworth** [comment]
I've updated the two pages I linked with more information on creating and managing vector indexes. If you have a link to the specific page you were concerned with, please follow up.
