### ISSUE TITLE
[Documentation] Do all browser tabs in the same browser session return the same Firebase anonymous authentification id?

### ISSUE THREAD

**Issue by andynewman10** [firebase/firebase-js-sdk#8640]
### Operating System

All

### Environment (if applicable)

Chrome

### Firebase SDK Version

10.x/11.x

### Firebase SDK Product(s)

Auth

### Project Tooling

Plain JavaScript

### Detailed Problem Description

On the web, when performing Firebase anonymous authentification, is it guaranteed that the same authentification id will be returned across all browser tabs, or is Firebase anonymous authentification specific to the JavaScript/window.sessionStorage space it is running in? I do not see this information in the documentation, however this information is important for developers.

### Steps and code to reproduce issue

- create a JavaScript web page with Firebase set up and sign in anonymously using Firebase
- open the same page in a second tab and repeat the process. Compare the returned authentification IDs. Are they guaranteed to be equal? Based on my experience, they are.

**Comment by dlarocque** [comment]
Thanks for submitting this issue. If you have a question about Firebase, please see [Firebase Support | Ask the Firebase community](https://firebase.google.com/support)

**Comment by sam-gc** [comment]
This is documented here: https://firebase.google.com/docs/auth/web/auth-state-persistence#web

The tl;dr is by default (i.e. unless you program it otherwise), persistence is shared across tabs and browser sessions (within the same browser) via `localStorage` or `indexedDB`.
