### ISSUE TITLE
getAuth is adding new events listeners infinitely

### ISSUE THREAD

**Issue by mbret** [firebase/firebase-js-sdk#8642]
### Operating System

mac

### Environment (if applicable)

chrome

### Firebase SDK Version

11.0.1

### Firebase SDK Product(s)

Auth

### Project Tooling

vite

### Detailed Problem Description

When calling `getAuth` at top level module (not in a loop) the performance tabs show events being added infiitely by batch of 2 every second.

This looks like some sort of heartbeat that does not clean up correctly.

### Steps and code to reproduce issue

import { getAuth } from "firebase/auth"

const auth = getAuth()

**Comment by dlarocque** [comment]
Hi @mbret, thanks for submitting this issue. Could you please share the full event logs, and highlight which are coming from the Firebase JS SDK?

**Comment by mbret** [comment]
I'm not sure how to find this in the performance tab or memory tab. If I make a blank page and record memory footprint we might be able to pinpoint it. I will try tomorrow.

**Comment by mbret** [comment]
Since we can manually trigger the GC I will try to do a repro and do it to see if it effectively get GC or not. Thanks for the linked issue, it seems like it is likely related indeed.
