### ISSUE TITLE
Reset password to a weak password, the error message received doesn't meet the password policy minimum length setting

### ISSUE THREAD

**Issue by comicat-hu** [firebase/firebase-js-sdk#8655]
### Operating System

macOS 15.0.1, Windows 11

### Environment (if applicable)

Chrome 130

### Firebase SDK Version

10.12.3

### Firebase SDK Product(s)

Auth

### Project Tooling

React 18

### Detailed Problem Description

I use Firebase Authentication to manage my users and I have set the password policy to require a minimum password length of 8.

<img width="932" alt="截圖 2024-11-26 下午6 45 51" src="https://github.com/user-attachments/assets/cb3eed80-e604-4c64-8f5d-088ba4c355c2">

But when I open the email link to reset my password, when I use a weak password (for example: enter 8 spaces), the error message does not meet the minimum password requirements I set.

<img width="417" alt="截圖 2024-11-26 下午6 42 52" src="https://github.com/user-attachments/assets/9397d52d-b014-4ce4-83f8-dc4bd9a04984">

This error message should comply with the password policy's minimum length requirements or the password policy settings should have special handling of whitespace.

### Steps and code to reproduce issue

```js
import { initializeApp } from 'firebase/app';
import { getAuth, sendPasswordResetEmail } from "firebase/auth";

const firebaseConfig = {
  apiKey: //
};
  
const app = initializeApp(firebaseConfig);

const auth = getAuth();

sendPasswordResetEmail(auth, email)
    .then(() => {
      console.log('Password reset email sent');
    })
    .catch((error) => {
      console.error(error);
    });
```

**Comment by DellaBitta** [comment]
Hi @comicat-hu,

Unfortunately I wasn't able to reproduce this problem. I set the minimum characters to both 8 and 12 and the reset password page displays the correct error text in both cases when I try to use too short of a password.

I should also note that the password reset page is part of the Firebase service and not part of the Firebase JS SDK (which this support forum represents). If you continue to have an issue then I recommend reaching out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact). They will be able to contact the engineers that are responsible for the back end service that generates this page.

I hope this helps!
