### ISSUE TITLE
Sign in with Microsoft creates new account when the account is not linked to an existing auth record

### ISSUE THREAD

**Issue by densk1** [firebase/firebase-js-sdk#8676]
### Operating System

OSX 14.5

### Environment (if applicable)

Chrome 131

### Firebase SDK Version

firebase@11.0.2

### Firebase SDK Product(s)

Auth

### Project Tooling

React@18.0.2
Webpack

### Detailed Problem Description

When calling `signInWithPopup(getAuth(), microsoftProvider)`, if the Microsoft account does not have a linked auth record Firebase creates a new account.

### Steps and code to reproduce issue

```tsx
const microsoftProvider = new OAuthProvider("microsoft.com").setCustomParameters({
  prompt: "consent", // Force re-consent.
});

function signinWithMicrosoft() {
  return signInWithPopup(getAuth(), microsoftProvider)
}
```

If I disable `allow account creation` in the Firebase auth UI, the error that returns is `"auth/admin-restricted-operation"` which is an error related to account creation not being allowed.

1. call `signinWithMicrosoft()` with an unlinked Microsoft account
2. Popup happens and closes
3a. An auth record is created for the microsoft account when account creation is enabled in the project
3b. An `"auth/admin-restricted-operation"` error is thrown when account creation is disabled in the project

I would expect a sign in failure or related error because sign in has been called.

**Comment by NhienLam** [comment]
Hi @densk1, thanks for filing an issue. 

It's expected that calling `signInWithPopUp` will create a new Firebase user if you haven't previously signed in with that Microsoft account. 
And if you disable account creation (sign-up), the `auth/admin-restricted-operation` error is expected when a user calls `signInWithPopup` with a new Microsoft account - https://firebase.google.com/docs/auth/users?hl=en&authuser=0#user-actions. Although the method is called "signIn"WithPopup, calling it with a new Microsoft account creates a new Firebase user and is therefore treated as account creation. 

Please correct me if I misunderstood the problem. Thank you.

**Comment by densk1** [comment]
> Hi @densk1, thanks for filing an issue. 
> 
> 
> 
> It's expected that calling `signInWithPopUp` will create a new Firebase user if you haven't previously signed in with that Microsoft account. 
> 
> And if you disable account creation (sign-up), the `auth/admin-restricted-operation` error is expected when a user calls `signInWithPopup` with a new Microsoft account - https://firebase.google.com/docs/auth/users?hl=en&authuser=0#user-actions. Although the method is called "signIn"WithPopup, calling it with a new Microsoft account creates a new Firebase user and is therefore treated as account creation. 
> 
> 
> 
> Please correct me if I misunderstood the problem. Thank you.

You are correct. I had not expected that this is how it would work due to method name. Thanks for the explanation.
