### ISSUE TITLE
ReferenceError: docRef is not defined

### ISSUE THREAD

**Issue by mickychen0524** [firebase/firebase-js-sdk#868]
```
db.collection('users').doc(auth.currentUser.uid).set(userObject)
                    .then(() => {

                    })
                    .catch((error) => {

                    });
```
user document has been created successfully but getting catch promise instead of then promise. any idea?

**Comment by jshcrowthe** [comment]
@mickychen0524 there is not enough info here to really tell what is going on. Can you get us a repro of the issue so we can take a look?

**Comment by mikelehen** [comment]
Even just including the contents of error (e.g. `console.log(error)`) would make it much more likely we can help you.

**Comment by mikelehen** [comment]
Oh.  I guess maybe "ReferenceError: docRef is not defined" is the error?  But your code doesn't reference `docRef` so as @jshcrowthe says, we definitely need more info.
