### ISSUE TITLE
Auth - Cordova - signInWithRedirect - A network error (such as timeout, interrupted connection or unreachable host) has occurred.

### ISSUE THREAD

**Issue by washowasho** [firebase/firebase-js-sdk#87]
* Operating System version: Android / Cordova
  * Firebase SDK version: 4.1.3
  * Firebase Product: auth

Followed these instructions, so I assume it is officially supported and this can be a forum to ask: https://firebase.google.com/docs/auth/web/cordova

When using signInWithRedirect in a Cordova environment and regardless of the auth provider (happen in Facebook, Google, Twitter), I receive this error below **90%** of the time. Yes, it works perfectly fine around 10% of the time:

`auth/network-request-failed`
`A network error (such as timeout, interrupted connection or unreachable host) has occurred.`

My thought is Auth is giving up and failing because the the cordova-browsertab-plugin is taking a few too many milliseconds to respond. The would explain why I am receiving sporadic timeouts/network errors. If not this, any reason why I receive this error?

signInWithEmailAndPassword works perfectly fine, all the time. But, I think it's because there is no use of the Cordova browser tab plugin.

**Comment by bojeil-google** [comment]
There are many reasons why network errors could occur.

Please provide details on your issue. The first thing you need to do is report network logs. Check the network call that is failing and please report it with full details. 

I doubt this happens because of the browser tab plugin. It is hard to speculate on the exact reason with no data available.

Are other calls failing at the same rate? Can you check signInWithEmailAndPassword? This would help clarify if this is related to a network request to the Firebase Auth backend or something else client related.

Underneath, we also check navigator.onLine to check the status of the connection. Can you confirm this returns true when the connection fails?

**Comment by washowasho** [comment]
What specific network logging will be helpful?

My initial post stated that signInWithEmailAndPassword works fine and still does consistently,, so I do not suspect it's a drop in connectivity.

I'm running the sample code provided by Google documentation. It's falling into the catch for getRedirectResult.

```
firebase.auth().signInWithRedirect(provider).then(function() {
  firebase.auth().getRedirectResult().then(function(result) {
    // This gives you a Google Access Token.
    // You can use it to access the Google API.
    var token = result.credential.accessToken;
    // The signed-in user info.
    var user = result.user;
    // ...
  }).catch(function(error) {
    // Handle Errors here.
    var errorCode = error.code;
    var errorMessage = error.message;
  });
});
```

Step 1 - signInWithRedirect function opens up a browser tab
Step 2 - Credentials are entered into provider's login screen within the browser tab
Step 3 - Browser tab closes, a small loader square shows up in the middle of the page
Step 4 - Error occurs (again, 90% of the time) in getRedirectResult, which is called when the browser tab closes.

Some additional data points:
- This does not happen in browser mode, only Cordova (I only tested on Android so far)
- I switched between cellular and WiFi, and still received the error.
- I suspect there may be some similarities with https://github.com/firebase/firebase-js-sdk/issues/20

**Comment by washowasho** [comment]
More info on XHR activity:

Called When Error:
- verifyAssertion?key=<key> (contains JSON response)

Called When Success:
- verifyAssertion?key=<key> (contains JSON response)
- getAccountInfo?key=<key> (contains JSON response)

**Comment by washowasho** [comment]
Ok, just an update. @bojeil-google, I confirmed that my Cordova device was switching between offline and online when I checked 'navigator.onLine'. That would explain why Firebase worked sometimes and not other times. I was wondering why, so I plugged in the 'cordova-plugin-network-information' to determine if my device was online or offline. Then it was fixed... works every time. I'm looking now to see if the 'cordova-plugin-network-information' is a more accurate wrapper to 'navigator.onLine'. If so, Firebase Auth may be getting better information and not failing. Stay tuned.

**Comment by bojeil-google** [comment]
Sounds promising. I suspected there may be issues with navigator.onLine in such environments when I heard recurring reports on network errors in Cordova apps. I just haven't been able to reproduce them to confirm this.

**Comment by washowasho** [comment]
Including the [cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information) corrected this issue for me. I confirmed that the 'navigator.onLine' was occasionally 'false', which I believe was causing Firebase to think there was an issue. Once I added the cordova-plugin-network-information to my project, the problem went away. I didn't dig deep into why, but I suspect this plugin has a better wrapper around the navigator which may be giving Firebase better information. I did confirm this problem came back after removing the plugin, but re-applying it fixes it. I will update this if I dig deeper. I hope this helps.

**Comment by mohshraim** [comment]
face the same problem on WKWebView
anyone find the correct solution?

**Comment by wahengchang** [comment]
did you guys find out what was happened ?

**Comment by redaelkhayat** [comment]
@mohshraim @wahengchang
try to change the Content-Security-Policy `default-src 'self'` to `default-src *`

**Comment by mohshraim** [comment]
@redaelkhayat 
Thanks for suggestion, my case was somehow on different environment. but was giving the same error.
this full case [582](https://github.com/firebase/firebase-js-sdk/issues/582)
that was a bug on google backend. and they solve it
