### ISSUE TITLE
Getting  old/unknown notifications from GCM in chrome browser 

### ISSUE THREAD

**Issue by sandeepkundu4344** [firebase/firebase-js-sdk#881]
### [REQUIRED] Describe your environment

  * Operating System version: windows
  * Firebase SDK version: 5.0.3
  * Firebase Product: Cloud messaging

#### Steps to reproduce:

 I add FCM js sdk into my project and it is working fine on all machine but there is one machine where i am getting 3 notifications which are not related to current message that I should receive. Everytime i fire push notification I receive this weird message 3 times

pls see attached video to replicate the exact bug
https://www.youtube.com/watch?v=IidSj3n4Iso&feature=youtu.be
#### Relevant Code:

it is just happening on single browser and I added an video for that 

https://stackblitz.com/fork/firebase-issue-sandbox

**Comment by mmermerkaya** [comment]
I haven't seen any bug reports similar to this, so I'm assuming there's something wrong with your configs or implementation. Unfortunately without a way to reproduce this issue we can't help you further.
