### ISSUE TITLE
Why Firebase auth does not take @googlemail.com into account?

### ISSUE THREAD

**Issue by rfk91** [firebase/firebase-js-sdk#888]
For example [fetchSignInMethodsForEmail()](https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#fetchSignInMethodsForEmail) should return google.com as a provider since name@gmail.com and name@googlemail.com are the same?

**Comment by bojeil-google** [comment]
You will get a better answer if you go through [Firebase support](https://firebase.google.com/support/).

I am not a backend engineer but will give this a shot. `fetchSignInMethodsForEmail` will lookup users by email as stored in our database (these are indexed for faster lookup). This does not take into account aliases for various reasons: we don't know all possible aliases of an email and checking every possible alias will be too expensive. 

However, if you do try to sign in with Google using the alias, you will end up with the same Firebase User account.

**Comment by rommelpe** [comment]
Haven’t heard from you in a while, @rfk91. I would like to check if you are still having issues or clarifications here. Just leave a comment and we are happy to re-open this.
