### ISSUE TITLE
Google login doesn't works android > 7

### ISSUE THREAD

**Issue by gbarrionuevo** [firebase/firebase-js-sdk#889]
### [REQUIRED] Describe your environment

  * Operating System version: Android
  * Firebase SDK version: 4.12.0
  * Firebase Product: auth 

#### Steps to reproduce:
  Login with provider (google) in android apk generated by cordova doesn't works after redirect back to app, it works on web.
#### Relevant Code:

"cordova-android": "^6.2.3",
"cordova-plugin-browsertab": "^0.2.0",
"cordova-plugin-buildinfo": "^2.0.1",
"cordova-plugin-compat": "^1.2.0",
"cordova-plugin-customurlscheme": "^4.3.0",
"cordova-plugin-device": "^2.0.2",
"cordova-plugin-fcm": "^2.1.2",
"cordova-plugin-inappbrowser": "^2.0.2",
"cordova-universal-links-plugin": "^1.2.1",

How to reproduce these conditions
It works on web and android 7 but it doesn't in previous version.

It doesn't and show no errors in console, after i choose the google account it comes back to the app but doesn't login.

```javascript

Code:

I've tried both with :

this.afAuth.auth.getRedirectResult().then(result => {
if (result && result.user.uid) {
this.afAuth.auth.currentUser = result.user;
} else {
this.authenticated.next(false);
this.isPerformingAuth.next(false);
console.log('user not logged in');
}
}).catch(function (error) {
// Handle Errors here.
var errorCode = error.code;
var errorMessage = error.message;
// The email of the user's account used.
var email = error.email;
// The firebase.auth.AuthCredential type that was used.
var credential = error.credential;
// ...
});

and

this.afAuth.auth.onAuthStateChanged(res => {
  if (res && res.uid) {
    this.isAuthenticated = true;
    this.authenticated.next(true);
    if (res.displayName) {
      this.setCurrentUserName(res.displayName);
    }
    localStorage.setItem('uid', res.uid);
    this.setCurrentUserToken(true, res);
  } else {
    this.authenticated.next(false);
    this.isPerformingAuth.next(false);
  }
});
My login method:

socialSignIn(provider: any) {
this.afAuth.auth.signInWithRedirect(provider);
}


```

**Comment by MatthewPringle** [comment]
cordova-plugin-compat screws up Android builds.

cordova-plugin-browsertab installs the above plugin and that repo is no longer being updated.

**Comment by rommelpe** [comment]
Sorry for the delay here, @gbarrionuevo. Are you still having this issue? It would be great if you could provide an updated [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) using the [latest version](https://firebase.google.com/support/release-notes/js) (7.4.0)  so we can look into this further.
