### ISSUE TITLE
Problem converting a promise to an observable

### ISSUE THREAD

**Issue by gempain** [firebase/firebase-js-sdk#89]
Hello,

I was redirected here by the people at [Angularfire 2](https://github.com/angular/angularfire2) regarding [an issue I opened a few days ago](https://github.com/angular/angularfire2/issues/1042). I'm not sure I should copy-paste the issue content, but here it is. Please feel free to remove everything below if you feel like it's unnecessary to write it all again).

All the best, and thank you for the amazing work.

### Version info

**Angular:** 4.0.0
**Firebase:** 4.1.2
**AngularFire:** 4.0.0-rc.1
**Other (e.g. Ionic/Cordova, Node, browser, operating system):** 
- RxJS 5.4.1
- OS X 10.12.5
- Safari 10.1.1

### How to reproduce these conditions

```
public logout1(): Observable<any> {
  return Observable.fromPromise(
    this.afAUth.auth.signOut()
  ).map(() => this.cleardData());
}

public logout2(): Observable<any> {
  return Observable.create(obs => {
    this.afAUth.auth.signOut()
      .then(() => {
        console.log('logged out');
        obs.next();
      })
      .catch(err => {
        throw Error(JSON.stringify(err));
      });
  }).map(() => this.cleardData());
}

public logout3(): Promise<any> {
  return new Promise((reject, resolve) => {

    this.afAUth.auth.signOut()
      .then(() => {
        console.log('logged out');
        this.cleardData();
        resolve();
      })
      .catch(err => {
        reject(err);
      });

  });
}

this.auth.logout1().subscribe(
  () => console.log('Logged out'),
  err => console.error('Could not log out')
);

this.auth.logout2().subscribe(
  () => console.log('Logged out'),
  err => console.error('Could not log out')
);

this.auth.logout3()
  .then(() => console.log('Logged out'))
  .catch(err => console.error('Could not log out'));
```

### Expected behavior

All above calls should output something.

### Actual behavior

Only that to `logout3` does.

**Comment by jshcrowthe** [comment]
Hey @gempain I appreciate the issue but there are a lot of things that could still be at play here. Can you get me a full repro of the issue (something I can just run to see the behavior you're describing), I'd be happy to take a look.

**Comment by gempain** [comment]
@jshcrowthe sounds great, I'll setup a repo that you can look at ASAP. Thanks a lot for your help, and sorry for the late response !

**Comment by jshcrowthe** [comment]
@gempain I'm going to close this as it hasn't seen activity in a long time. If you get that repro please feel free to re-open w/ more information.
