### ISSUE TITLE
Return type is Promise<any>

### ISSUE THREAD

**Issue by zaru** [firebase/firebase-js-sdk#896]
### [REQUIRED] Describe your environment

* Operating System version: Max OSX 10.13.4
* Firebase SDK version: 5.0.3
* Firebase Product: auth

### [REQUIRED] Describe the problem

The returned value definition of signInWithEmailAndPassword and signInWithCustomToken is `Promise<any>` in index.d.ts of the auth package. Looking at externs seems that `firebase.auth.UserCredential` is returned from SDK version 5.

I'd like to make a pull request specifying the type, how do you like it?

ref

- https://github.com/firebase/firebase-js-sdk/blob/4a85602be0ae5418530f3f9c1f9c86d71939aafd/packages/auth-types/index.d.ts#L258
- https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/externs/firebase-auth-externs.js#L1710

**Comment by bojeil-google** [comment]
Actually this was fixed in https://github.com/firebase/firebase-js-sdk/pull/870 but it was never merged.

**Comment by wti806** [comment]
PR #870 is merged.

**Comment by zaru** [comment]
Thanks!
