### ISSUE TITLE
Release 5.0.3 and 5.0.4 not pushed to firebase/firebase-bower

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-js-sdk#897]
Versions 5.0.3 and 5.0.4 have been released respectively on May 17, 2018 and May 24, 2018 but the repository `firebase/firebase-bower` has not been updated. As a consequence, these versions are not available on Bower.

https://github.com/firebase/firebase-bower/releases

PS: This is not possible to report issues on the previous repository.

**Comment by lpellegr** [comment]
@jshcrowthe Could you please have a look?

**Comment by jshcrowthe** [comment]
Hey @lpellegr thanks for the ping here. The latest two versions have been published so PTAL.
