### ISSUE TITLE
Generic type 'Observer<V, E>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by rtm** [firebase/firebase-js-sdk#900]
I receive the following error:

> ./../../node_modules/@firebase/storage-types/index.d.ts(80,9): error TS2314: Generic type 'Observer<V, E>' requires 2 type argument(s).

The version of `@firebase/storage-types` is 0.2.3 (brought in by firebase@5.0.4). The line in question is

```
  on(
    event: TaskEvent,
    nextOrObserver?:
      | Observer<UploadTaskSnapshot>
      | null
      | ((a: UploadTaskSnapshot) => any),
    error?: ((a: Error) => any) | null,
    complete?: (Unsubscribe) | null
  ): Function;
```

The repo from which this is being brought in has

```
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.0"
```

**Comment by hiepxanh** [comment]
![screen shot 2018-06-13 at 9 07 40 am](https://user-images.githubusercontent.com/16970990/41326455-41cb5182-6ee9-11e8-9f2f-35881a489727.png)

**Comment by mmermerkaya** [comment]
Looks like `@firebase/storage` has [their own implementation](https://github.com/firebase/firebase-js-sdk/blob/73a586c92afe3f39a844b2be86086fddb6877bb7/packages/storage/src/implementation/observer.ts) but uses `@firebase/util` types in `@firebase/storage-types` (without adding that as a dependency in `package.json`): https://github.com/firebase/firebase-js-sdk/blob/785cc8b49f149068dbabb6f7482ac0763aeec85e/packages/storage-types/index.d.ts#L18

**Comment by hiepxanh** [comment]
sir, is that a bug ? or what should we do?

**Comment by hiepxanh** [comment]
@mmermerkaya is that a bug? what shoud I do sir?

**Comment by mmermerkaya** [comment]
Try updating to the latest Firebase SDK version. See #787 for details.

The only issue I see here is that auth-types and storage-types packages don't have the `@firebase/util` dependency in their `package.json` files even though they are using it, which might have caused your version to stay behind. I opened another issue to track that: #952.

**Comment by sreekanth-karini** [comment]
Update typescript,       `npm install typescript@2.3`       will fix the error.
