### ISSUE TITLE
AoT build hangs with freezing at bundling @firebase SDKs.

### ISSUE THREAD

**Issue by vincent-cm** [firebase/firebase-js-sdk#904]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.5
  * Firebase SDK version: @firebase/database 0.3.3
  * Firebase Product: (auth, database, storage, etc) comes from below dependency:

```

"firebase": "5.0.4", "angularfire2": "5.0.0-rc.10", 

"firebase": {
      "version": "5.0.4",
      "resolved": "https://registry.npmjs.org/firebase/-/firebase-5.0.4.tgz",
      "integrity": "sha512-UIlUOcISw6uiAwbsj/bamDDKJtdjx9GU2m9XgPF58DSA8IJaIbfdL6jT5C03R5mL+mMpXoKDAOeOq+ynf+R09w==",
      "requires": {
        "@firebase/app": "0.3.3",
        "@firebase/auth": "0.5.3",
        "@firebase/database": "0.3.3",
        "@firebase/firestore": "0.5.4",
        "@firebase/functions": "0.2.4",
        "@firebase/messaging": "0.3.4",
        "@firebase/polyfill": "0.3.3",
        "@firebase/storage": "0.2.3"
      }
    }
```

### [REQUIRED] Describe the problem
When building with angular cli using `ng build --prod`, the memory will increase to around 10.39GB and hangs in `69% building modules 1404/1405 modules 1 active …es/@firebase/database/dist/index.cjs.js`

#### Steps to reproduce:
You can use webpack or ng cli
ngcli: `ng build --prod`
webpack: `cross-env BUILD_AOT=1 SOURCE_MAP=0 npm run webpack -- --config config/webpack.prod.js --mode production --progress --profile --bail`

#### Relevant Code:

`git clone git@github.com:vincent-cm/angular-starter-test.git`
`git checkout migrate-to-webpack4`
 run `npm run clean:install `
`npm run build:aot`

The process will be stucked at building @firebase SDKs.

**Comment by hiepxanh** [comment]
hello? any update there?

**Comment by vincent-cm** [comment]
@hiepxanh Haven’t get out from it. Did u find the same issue?

**Comment by hiepxanh** [comment]
ERROR in Cannot read property 'map' of undefined with `ng build --prod --aot` I still dont know why and keep investigating

**Comment by vincent-cm** [comment]
@hiepxanh did u install the rxjs-compat?

**Comment by hiepxanh** [comment]
nope, I use rxjs 6 directly, however I remove everything and start again with new repository. everything is OK. with [ng build --aot --prod ](https://github.com/hiepxanh/angular-cli-angularfire)

**Comment by hiepxanh** [comment]
cannot install your project `Failed at the node-sass@4.9.0 postinstall script.`

**Comment by vincent-cm** [comment]
@hiepxanh a latest version of node and npm should be used in the demo project. Thank you for your test.

**Comment by vincent-cm** [comment]
Had downgrade angularfire2 to 4.0.0-rc.6.0 and firebase to 4.12.1, and it worded @hiepxanh thanks for your demo project, I did not use ng cli, probably the latest webpack I am using is not compatible with this version of @firebase SDKs

**Comment by vincent-cm** [comment]
my fault, missing && in between cross-env and npm command

**Comment by hiepxanh** [comment]
good to know that :) have a nice day

**Comment by vincent-cm** [comment]
https://github.com/firebase/firebase-js-sdk/issues/874
