### ISSUE TITLE
XMLHttpRequest

### ISSUE THREAD

**Issue by nessup** [firebase/firebase-js-sdk#910]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS X, 10.13.4, Muon 5.2.7 (Electron)
  * Firebase SDK version: app: 0.3.3, auth: 0.5.3, database: 0.3.3
  * Firebase Product: app, auth, database

Importing firebase via `firebase/app` does not load XMLHttpRequest. You get "Error: The XMLHttpRequest compatibility library was not found."

#### Steps to reproduce:

1. `yarn add firebase/app firebase/auth firebase/database`
2. Write code below

#### Relevant Code:

```javascript
import firebase from '@firebase/app';
import '@firebase/auth';
import '@firebase/database';
...
firebase.initializeApp(firebaseConf);
```
Are there any low hanging fruit fixes for this? It seems to me that, when `app/index.node.cjs.js` is required, the compatibility layer is loaded. However I'm not sure how webpack, which I'm using for bundling, determines whether to load that or the `browser` version of the module.

**Comment by jshcrowthe** [comment]
@nessup, the firebase scoped packages are highly volatile (hence the major version 0) and should not be considered "production ready". Change your code to use the `firebase` NPM package instead and things should work fine.

e.g.

```
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
...
firebase.initializeApp(firebaseConf);
```

**Comment by nessup** [comment]
Hi @jshcrowthe, I can't add the firebase package to my project because there is a dependency in firestore called `grpc` that fails to compile against my particular legacy node runtime. By using scoped packages, I've been able to avoid this dependency entirely. Would you know of another way to avoid this dependency?

**Comment by jshcrowthe** [comment]
Your use case is one of the things we are targeting for when we ship stable versions of the `@firebase/*` packages. However until then, I don't really have a great answer for you. 

However, if your Node runtime isn't compatible with Firestore then you probably aren't using a version of Node that is being maintained, and that is an issue in-and-of itself. I'd recommend you upgrade your Node version 😄 .
