### ISSUE TITLE
error while compling in angular project 

### ISSUE THREAD

**Issue by jaswanth1998** [firebase/firebase-js-sdk#911]
`ERROR in node_modules/angularfire2/firebase.app.module.d.ts(2,42): error TS2305: Module '"/Users/apple/Desktop/FML_firebase_work-master/node_modules/firebase/index"' has no exported member 'functions'.`

i had updated my angular project from 5 to 6 then this error came to know

**Comment by jshcrowthe** [comment]
I just double checked the latest Firebase version and we do indeed export the functions API in our `.d.ts` (see https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L139-L172).

I'd recommend checking your Firebase version here.
