### ISSUE TITLE
Update firebase@4.13.1>@firebase/firestore->grpc to grpc@1.12.2

### ISSUE THREAD

**Issue by amitport** [firebase/firebase-js-sdk#912]
Libraries that use firebase@4 can't run with win+Node.js because of an issue in grpc@1.10. this issue was later resolved in future backward compatible versions of grpc.

Would have submitted a pull request but I can't create a new branch for `firebase@4.13.2` in a Github pull-request.

https://github.com/firebase/firebase-js-sdk/compare/878d392f212fef10b04c00d0f697f625c8271712...amitport:firebase@4.13.2

This fix will resolve the issue for packages requiring firebase@^4.13.0

see
https://github.com/grpc/grpc/issues/15403
https://github.com/angular/material2/issues/10401
https://github.com/angular/material2/issues/11735

**Comment by jshcrowthe** [comment]
The version of GRPC has been updated in later Firebase releases. Please update to the latest and your issue should be fixed.

**Comment by amitport** [comment]
I know the issue is fixed on master. This was a maintenance request.  `firebase@^4.13.0` is used by a library I depend on. (`@angular/material`, in my case)

**Comment by jshcrowthe** [comment]
We currently don't have support for previous major releases and our recommendation has been "upgrade to the latest version to get the bugfixes." If `@angular/material` has outdated dependencies I'm sure they'd love a PR to help get them up to date!

The release notes for v5.0.0 are here: https://firebase.google.com/support/release-notes/js#5.0.0 there aren't a ton of breaking changes so it should be a fairly straightforward update.

**Comment by AAverin** [comment]
Firebase 5.x does not work with GatsbyJS 1.X (https://github.com/shaunpersad/gatsby-and-firebase), and Firebase 4.x doesn't compile due to this GRPC issue.

Would it be possible to have Firebase 4.x release with this fix included?
It's not possible for me to migrate to GatsbyJS 2.0 for my project
