### ISSUE TITLE
Firebase auth and database dont work together

### ISSUE THREAD

**Issue by gobalistik** [firebase/firebase-js-sdk#913]
### [REQUIRED] Describe your environment

  * Operating System version: ____Windows 10_
  * Firebase SDK version: ___5.0.4__
  * Firebase Product: auth and database_____ (auth, database, storage, etc)

Ionic app info
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v8.11.2
    npm               : 5.3.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\android-sdk

Misc:

    backend : legacy

package.json
"dependencies": {
    "angular/animations": "5.2.10",
    "angular/common": "5.2.10",
    "angular/compiler": "5.2.10",
    "angular/compiler-cli": "5.2.10",
    "angular/core": "5.2.10",
    "angular/forms": "5.2.10",
    "angular/http": "5.2.10",
    "angular/platform-browser": "5.2.10",
    "angular/platform-browser-dynamic": "5.2.10",
    "ionic-native/core": "4.7.0",
    "ionic-native/splash-screen": "4.7.0",
    "ionic-native/status-bar": "4.7.0",
    "ionic/storage": "2.1.3",
    "firebase": "^5.0.4",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "ionic/app-scripts": "3.1.9",
    "typescript": "~2.6.2"
  },

Since upgrading to firebase 5.0.4, firebase/database and firebase/auth don't work together.  I've tried various versions down to 4.7.0

#### Steps to reproduce:
I've created a new ionic project using

ionic start tabs testapp
npm install firebase --save

In home.ts added 
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import firebase from 'firebase/app';
import 'firebase/database';
**import 'firebase/auth';**

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  tournaments: any[] = [];

  constructor(public navCtrl: NavController) {

  }

  ionViewDidEnter(){
    firebase.database().ref('tournaments').on('child_added', snap =>{
      console.log(snap.val());
      this.tournaments.push(snap.val());
    });

  }

}

home.html

ion-content padding>
  ion-list>
    ion-item *ngFor="let tournament of tournaments">
      Name: {{tournament?.Name}}
    /ion-item>
  /ion-list>
/ion-content>

This runs without firebase/auth but with it the view takes 15+ seconds to bind even though I can see in the console the data is returned sub second.  It's possible to click the page or hit f12 to open dev tool, this forces the page to bind.  On a device rotate the screen and the view binds.  If I remove the firebase/auth import the page binds sub second as expected.

**Comment by gobalistik** [comment]
Think this may be a chrome 67 bug.  Works fine on phone with chrome 66 installed, problem phone has 67 which was updated a few days ago.  Also have 67 on dev machine and have the same issue there although not as consistent as on phone.

**Comment by gobalistik** [comment]
Uninstalled chrome updates, back to version 65. App now works so definitely chrome 67 issue.

**Comment by jayordway** [comment]
Why did you include it within this component? I don't see the auth library being used here.

**Comment by gobalistik** [comment]
It's not being used, it's just a simple example to show how to recreate the issue.

**Comment by jayordway** [comment]
@gobalistik They are working together from my experience. There is a difference between not working together and creating a latency from importing code that is not used.

**Comment by gobalistik** [comment]
@jayordway - thanks for your comment.  I'm glad in your experience they work together, the point is that in my experience they aren't. Obviously my app uses the imported code, the example given was to make it as simple as possible for others to recreate.
