### ISSUE TITLE
ENVIRONMENTS.md is missing Firestore and Functions

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebase-js-sdk#914]
https://github.com/firebase/firebase-js-sdk/blob/master/ENVIRONMENTS.md lists the supported browsers for most Firebase features but it's currently missing Firestore and the Cloud Functions's Callable Functions feature. Would be cool to add them in.

Especially would be nice to know if some features are working or not depending on the browser. For instance Firestore's offline support.

**Comment by nicolasgarnier** [comment]
I hate you Bot. My issue is great :D

**Comment by jshcrowthe** [comment]
I'd love a PR 😉

**Comment by Feiyang1** [comment]
fixed by https://github.com/firebase/firebase-js-sdk/pull/1772
