### ISSUE TITLE
Firebase auth not working on iOS 12 due to XHR access control checks

### ISSUE THREAD

**Issue by ahmadtawakol** [firebase/firebase-js-sdk#916]
Describe your environment

  * Operating System version: iOS 12 (cordova)
  * Firebase SDK version: 5.0.4
  * Firebase Product: auth

Describe the problem

#### Steps to reproduce:

- Try to sign in using `signInWithEmailAndPassword()`

#### Relevant Code:

```javascript
firebase.auth().signInWithEmailAndPassword(email, password)
```

#### Error Received (from console):
`[Error] Preflight response is not successful
[Error] XMLHttpRequest cannot load https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=[key_removed] due to access control checks.
[Error] Failed to load resource: Preflight response is not successful (verifyPassword, line 0)`

#### Error Received on phone:
`A network error (such as timeout, interrupted connect or unreachable host) has occurred.`

#### Notes:
This only happens on an iOS 12 device. The same exact code works fine in the browser and on iOS 11 devices.

**Comment by wti806** [comment]
@ahmadtawakol  Can you run cordova emulate ios --list from your cordova project to see if iOS 12 is supported by Cordova? I cannot find the documentation from cordova saying iOS 12 is officially supported.

**Comment by ahmadtawakol** [comment]
Well, obviously nothing right now officially supports iOS 12, but I can build and run apps on iOS 12 using cordova.

$ cordova emulate ios --list`
Available iOS Simulators:
	Apple-Watch-38mm, watchOS 5.0
	Apple-Watch-42mm, watchOS 5.0
	Apple-Watch-Series-2-38mm, watchOS 5.0
	Apple-Watch-Series-2-42mm, watchOS 5.0
	Apple-Watch-Series-3-38mm, watchOS 5.0
	Apple-Watch-Series-3-42mm, watchOS 5.0
	Apple-TV-1080p, tvOS 12.0
	Apple-TV-4K-4K, tvOS 12.0
	Apple-TV-4K-1080p, tvOS 12.0
	iPhone-5s, 10.3
	iPhone-5s, 12.0
	iPhone-6, 10.3
	iPhone-6, 12.0
	iPhone-6-Plus, 10.3
	iPhone-6-Plus, 12.0
	iPhone-6s, 10.3
	iPhone-6s, 12.0
	iPhone-6s-Plus, 10.3
	iPhone-6s-Plus, 12.0
	iPhone-7, 10.3
	iPhone-7, 12.0
	iPhone-7-Plus, 10.3
	iPhone-7-Plus, 12.0
	iPhone-8, 12.0
	iPhone-8-Plus, 12.0
	iPhone-SE, 10.3
	iPhone-SE, 12.0
	iPhone-X, 12.0
	iPad-Air, 10.3
	iPad-Air, 12.0
	iPad-Air-2, 10.3
	iPad-Air-2, 12.0
	iPad--5th-generation-, 10.3
	iPad--5th-generation-, 12.0
	iPad-Pro--9-7-inch-, 12.0
	iPad-Pro, 12.0
	iPad-Pro--12-9-inch---2nd-generation-, 10.3
	iPad-Pro--12-9-inch---2nd-generation-, 12.0
	iPad-Pro--10-5-inch-, 10.3
	iPad-Pro--10-5-inch-, 12.0
	iPhone-5, 10.3
	iPad-Pro--9-7-inch-, 10.3
	iPad-Pro, 10.3
	iPad--6th-generation-, 12.0`

**Comment by mohshraim** [comment]
this issue already exist on some enviroment  
https://github.com/firebase/firebase-js-sdk/issues/582#

check the request curl 
https://github.com/firebase/firebase-js-sdk/issues/582#issuecomment-381898609

if the origin is null google auth will reject it as CORS.

**Comment by bojeil-google** [comment]
I suspect it is the same issue. I will try to escalate to the relevant owners to try to fix this.

**Comment by mmmaxi** [comment]
Is there any workaround for this for the moment? Especially for using it in Ionic?

**Comment by ahmadtawakol** [comment]
Fixed in beta 2.
