### ISSUE TITLE
writeResult is undefined when trying to replicate example

### ISSUE THREAD

**Issue by wzard** [firebase/firebase-js-sdk#917]
I am using firestore in react. 
I am trying to replicate the example documentation. 
I am able to set the doc with the value provided but function is returning undefined on being fulfilled.

The below code which is taken from documentation [here](https://cloud.google.com/nodejs/docs/reference/firestore/0.14.x/WriteResult) is returning writeResult is undefined.

I am able to successfully write the doc though. 
Can anyone check. 

```
let documentRef = firestore.doc('col/doc');

documentRef.set({foo: 'bar'}).then(writeResult => {
  console.log(`Document written at: ${writeResult.writeTime}`);
});

```

**Comment by wzard** [comment]
In the set method of Document reference [here](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#set) it is written that the promise returns a non-null void.

Then I presume, writeResult is not forwarded after set and the docs I have mentioned in the issue are wrong?

**Comment by jshcrowthe** [comment]
It seems like there may be something going on here, but we need more information to really diagnose the problem. Can you put together a repro for us to help triage?

**Comment by mikelehen** [comment]
This is expected. set() returns a Promise<void>.  See https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#set

You are perhaps looking at the gcloud server SDK (https://github.com/googleapis/nodejs-firestore) which has a similar but not quite identical API.  Sorry for the confusion.
