### ISSUE TITLE
Firestore timestamps replaced with object

### ISSUE THREAD

**Issue by baikunz** [firebase/firebase-js-sdk#921]
### [REQUIRED] Describe your environment

  * Operating System version: N/A
  * Firebase SDK version:  5.0.2
  * Firebase Product: firestore

#### Steps to reproduce:

This is a tricky one. The issue is only appearing randomly and not quite often.
I'm using a service responsible to add a `createdAt` field on every document I create/update, using this snippet: 
```js
createdAt: document.createdAt || serverTimestamp()
```
This code adds the server timestamp to the `createdAt` field if it's not there, otherwise it just keeps the value that was there. And most of the time it works just fine.
But I started noticing that sometimes my field was filled with an object in firestore instead of the timestamp.
The object saved has 2 properties: `nanoseconds` and `seconds` like the one returned from firestore.

I looked around my code, but I never edit this field anywhere, I expected it to stay a timestamp if it's not edited.
I don't even know if this code snippet is responsible for this behaviour but this is the only hint I could find.

EDIT: It looks like it's actually related to all input fields with timestamps which get resubmitted with a .set().
EDIT2: I'm using the `timestampsInSnapshots: true` setting on firestore

**Comment by mikelehen** [comment]
Is it possible to provide a minimal code snippet that demonstrates the issue?

**Comment by baikunz** [comment]
I updated the code for the issue. I didn't noticed that it was using an old version of the sdk.

**Comment by var-const** [comment]
@baikunz Thanks for the repro case! I'll investigate and will post an update here when I have it.

**Comment by baikunz** [comment]
Thanks ! 
Quick reply today, I spent some time trying to debug it in my own app because the code I setup does not seem to fail and it seems that finally it might be related to a Vue devtool issue...
I'm going to further investigate on this and will come back to you ASAP.

**Comment by baikunz** [comment]
Well, sorry for wasting your time guys, it seems that the issue is indeed related to the vue devtool and not in any way related to the firestore-sdk!

Just in case someone face the same issue, i'm leaving the link to the [vue devtool issue](https://github.com/vuejs/vue-devtools/issues/492) over here.

Sorry guys !

**Comment by mikelehen** [comment]
No worries.  Thanks for the follow-up!
