### ISSUE TITLE
Firebase JS SDK not working inside an Iframe that loads an script containing Firebase.

### ISSUE THREAD

**Issue by sandrocsimas** [firebase/firebase-js-sdk#922]
### Environment

  * Operating System version: Ubuntu 16.04
  * Firebase SDK version: @firebase/app - 0.3.3 and @firebase/messaging - 0.3.4
  * Firebase Product: Messaging

### Problem

I'm getting the following error when I try to get Firebase token in my React application.

````javascript
browserErrorMessage: "Failed to register a ServiceWorker: No URL is associated with the caller's document."
code: "messaging/failed-serviceworker-registration"
message: "Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: No URL is associated with the caller's document. (messaging/failed-serviceworker-registration)."
````

My application is a Chat widget that should be loaded in any page. When the page includes my javascript file, my application is loaded and creates an Iframe. Inside the Iframe another script is included and this script contains all the Chat widget code and the Firebase library.

index.html
````html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://example.net/lib.js"></script>
  </head>
  <body>
    <script>
      Lib.init({});
    </script>
  </body>
</html>
````
lib.js
````javascript
const div = document.createElement('div');
div.setAttribute('id', Components.ID_DIV);
document.body.appendChild(div);

const iframe = document.createElement('iframe');
iframe.setAttribute('id', Components.ID_FRAME);
iframe.setAttribute('allowFullScreen', '');
iframe.setAttribute('frameborder', '0');
iframe.setAttribute('scrolling', 'no');
iframe.className = Components.CLASS_BUTTON;
div.appendChild(iframe);

const iframeDocument = iframe.contentDocument;
iframeDocument.open();
iframeDocument.write(`
  <!DOCTYPE html>
  <html>
    <head>
      <script src="https://example.net/frame.js"></script>
    </head>
    <body/>
  </html>
`);
iframeDocument.close();
````
frame.js
````javascript
const config = {
  apiKey: '<API_KEY>',
  projectId: '<PROJECT_ID>',
  messagingSenderId: '<SENDER_ID>',
};
firebase.initializeApp(config);
const messaging = firebase.messaging();
messaging.getToken().then((currentToken) => {
  if (currentToken) {
    console.log(currentToken);
  } else {
    messaging.requestPermission().then(() => {
      console.log('Notification permission granted.');
    }).catch((err) => {
      console.log('Unable to get permission to notify.', err);
    });
  }
}).catch((err) => {
  console.log('An error occurred while retrieving token. ', err);
});
````
The Firebase configuration will be provided by the client.
I'm running everything using HTTPS, including the index.html page.
How to make Firebase works in this kind of application?

**Comment by mmermerkaya** [comment]
Push API is not allowed in iframes and Messaging needs Push API to work.

[Here](https://bugs.chromium.org/p/chromium/issues/detail?id=430496) is the Chromium bug report where it was decided to add this restriction and [here](https://stackoverflow.com/questions/40240155/how-subscribe-pushmanager-via-iframe-in-chrome) is a related question on StackOverflow.
