### ISSUE TITLE
Firebase-firestore.js cannot work on iOS Safari 9

### ISSUE THREAD

**Issue by wira** [firebase/firebase-js-sdk#931]
* Operating System version: iOS 9.3.5
  * Firebase SDK version: 5.0.4
  * Firebase Product: app, auth, firestore

### [REQUIRED] Describe the problem
Firebase firestore is not working on iOS Safari 9 because of an error in the firebase-firestore.js file. on console: `Strict mode does not allow function declarations in a lexically nested statement.`

#### Steps to reproduce: (in iPad)

- Load the script
`<script src="https://www.gstatic.com/firebasejs/5.0.4/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/5.0.4/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/5.0.4/firebase-firestore.js"></script>`
- Create firebase object
`firebase.initializeApp(firebaseConfig);
  const db = firebase.firestore();`

**Comment by billyz313** [comment]
This is also true in:
safari 5.1 browser on windows 10 using firebase 5.1.0

![firestoreerror](https://user-images.githubusercontent.com/1868821/42060840-cc6dd304-7aed-11e8-8b40-207611a6c7fc.gif)

**Comment by Feiyang1** [comment]
The issue has been fixed by https://github.com/firebase/firebase-js-sdk/pull/1239
