### ISSUE TITLE
Auth & 3rd party cookies

### ISSUE THREAD

**Issue by jimmyff** [firebase/firebase-js-sdk#934]
Getting the following error when authenticating with Google via popup:
`This browser is not supported or 3rd party cookies and data may be disabled.`

I do have 3rd party cookies turned off but this is quickly becoming common practice. Other sites with Google authenticate don't seem to have this issue?

**Comment by bojeil-google** [comment]
This is a known limitation. signInWithPopup/Redirect will not work when 3rd party cookies are not available.
To get around it, you need to use the Google JS sign in SDK to get a Google Access token/ID token and then pass to `signInWithCredential`.

**Comment by TeoTN** [comment]
Could you please update the docs [here](https://firebase.google.com/docs/auth/web/google-signin) so that people can actually start working with Firebase auth immediately, instead of searching why example from docs is not working?
