### ISSUE TITLE
Bug in 5.0.4 version.

### ISSUE THREAD

**Issue by berpcor** [firebase/firebase-js-sdk#938]
https://stackoverflow.com/questions/50891391/importing-firebase-in-non-root-file-of-react-native-causes-error-in-android-emul
Look at there please.
I've downgraded to 5.0.2 and it's helped.

**Comment by jshcrowthe** [comment]
Hey there @berpcor, I don't think this is an issue with Firebase but rather a dupe of a react native issue. Can you try loading Firebase before everything else and see if that fixes the problem?

**Comment by jshcrowthe** [comment]
Duplicate of #871

**Comment by berpcor** [comment]
Unfortunately yes, I've tried all possible orders: before, after, middle, different depth in hierarchy...
