### ISSUE TITLE
Testing https.onCall with locally running serve

### ISSUE THREAD

**Issue by fxfactorial** [firebase/firebase-js-sdk#941]
I have cloud functions running locally via: `"firebase": "4.13.1",` (yes I know I could test via shell) 

```
firebase serve --only functions
```

and in my JS web sdk, I get at those functions with

```js
firebase.functions().httpsCallable
```
but those functions always use a production version of the URL. 

How can I change it so that they use a local version of my URL? I'm in a gatsby based projected and I did try adding to `gatsby-config.js`: 

```
module.exports = {
  proxy: { prefix: '/', url: 'http://localhost:5000' },
```

**Comment by jshcrowthe** [comment]
Hey @fxfactorial, as of `5.2.0` (released yesterday) we support an API to do exactly this!

```javascript
import firebase from 'firebase/app';
import 'firebase/functions';

const app = firebase.initializeApp({ ... });
app.functions().useFunctionsEmulator('http://localhost:8080'); // Or whatever the port is for your local emulator

...
```

**Comment by fxfactorial** [comment]
Oh that's awesome! unfortunately I had to move away from using the function based on onCall because of this issue: https://github.com/firebase/firebase-functions/issues/274

**Comment by abraztsov** [comment]
app.functions().useFunctionsEmulator('....') - doesn't work. Using `5.30` version.

**Comment by ssijak** [comment]
I am using this fix in vuejs-cli : 

```
const functions = firebase.functions()
// if dev mode, test with local cloud functions server
if (process.env.NODE_ENV === 'development') {
  functions._url = function (name) {
    return `${process.env.VUE_APP_API_URL}/${name}`
  }
}
```

**Comment by fxfactorial** [comment]
That's really great, I will definitely use that in future projects. Thank you for the great iteration speed on this.

**Comment by alenl** [comment]
For the benefit of future searchers, the above doesn't work in even in latest version of AngularFire. But a kludge like this does:
```js
import { AngularFireFunctions } from '@angular/fire/functions';
import { FirebaseFunctions } from 'firebase/functions';
[...]
constructor(
    private afFuncs: AngularFireFunctions ) {
[...]     (afFuncs.functions as FirebaseFunctions).useFunctionsEmulator('http://localhost:5000');
```

**Comment by dirkjot** [comment]
This functionality is now built-in to Firestore / AngularFire:
```typescript
import { AngularFireFunctions } from '@angular/fire/functions'

export mainComponent {
  constructor(private firefunctions: AngularFireFunctions) { 
    if (environment.myApp.useLocalFunctions) {
      this.firefunctions.functions.useFunctionsEmulator('http://localhost:5000')   
    }
  }
}
```

**Comment by yemanaung** [comment]
Support and protect secure system issues for my account.
https:///github.com/koyemanaung
https://github.com/yemanaung
https://github.com/DrAryone
