### ISSUE TITLE
[Bug] 5.0.4 at `tsconfig.json` path

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#945]
in `tsconfig.json` the path at `"extends": "../../config/tsconfig.base.json",` this path doesn't exist / leads to nowhere. This is giving me some bugs in VScode in the "problems" tab.

**Comment by krondog4090** [comment]
![capture](https://user-images.githubusercontent.com/38766508/42031967-b14ea724-7a9d-11e8-8995-d82ac3438387.PNG)


getting this too

**Comment by jshcrowthe** [comment]
Hey all, we fixed this issue in https://github.com/firebase/firebase-js-sdk/pull/915. If you can please update to the latest firebase you should see this issue has been resolved.
