### ISSUE TITLE
"Signed In" is not the last time a token was generated, but the last time actually "signed in".

### ISSUE THREAD

**Issue by boon4376** [firebase/firebase-js-sdk#948]
### [REQUIRED] Describe your environment

  * Operating System version: _Mac OSX Mojave____
  * Browser version: _Chrome Latest____
  * Firebase SDK version: _
        "firebase": "^5.0.2",
        "firebaseui": "^3.0.0"
  * Firebase Product: __Auth___ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
This might sound completely duh, so maybe this is more of a feature request... But it seems like every time a token is generated for the user, this auth metric should update.

The ["metadata"]["lastSignInTime"] in the user object is the last time the user actually went through the whole sign in process, not the last time they signed in (last time a token was generated). 

For example, if I login to my website using firebaseui (firebase authentication web js sdk), and then come back tomorrow and use some features that generate a fresh token, I do not need to actually sign in again, and my "lastSignInTime" is not updated either.

This is with the Google based auth.

**The problem**  is that if I'm attempting to pull a list of their most recent users, then I must create a separate metric to track in a user's firestore profile called "lastActive" or something.

It seems like the firebase auth user object should track the last time the user was seen signed in, not the last time they went through the sign in process. 

The metric of when the user was last authenticated / the last time a token was generated for a user, is something I'd expect to be tracked and kept updated in firebase auth. 

#### Relevant Code:
This is the code I expected to keep the "lastSignInTime" updated. 
```javascript
let user = firebaseAuth().currentUser;

user.getIdToken(/* forceRefresh */ true)
            .then(function(idToken) {
.....
```
In this event, the token is sent with a request to a firebase function, where it is decoded, and the function does things pertaining to that user, based on the user-id decoded from the token.

**Comment by bojeil-google** [comment]
This is the expected behavior. Last sign in time is last auth time, what you want is the last token refresh time. `user.getIdTokenResult` returns a [firebase.auth.IdTokenResult](https://firebase.google.com/docs/reference/js/firebase.auth.IdTokenResult) with the `issuedAtTime` (last refresh time of token for current user.
