### ISSUE TITLE
Safari bug causing Firebase write to fail

### ISSUE THREAD

**Issue by curiouslybrown** [firebase/firebase-js-sdk#95]
Hello,

I'm attempting to write a large amount of data to Firebase in a single write (I inspected the WS messages through Charles to make sure, meaning it is being sent in big chunks). There are some WebSocket errors in the console, data isn't written, and the error callback is not called. 

I believe it is related to this bug: https://bugs.webkit.org/show_bug.cgi?id=170463

Errors:
Failed to send WebSocket frame. 
Failed to send WebSocket frame.
 INTERNAL ASSERT FAILED: sendRequest call when we're not connected not allowed.

**Comment by schmidt-sebastian** [comment]
How large are the packets that you are sending? Are you using a recent version of Safari that does not have this issue anymore?

**Comment by schmidt-sebastian** [comment]
Please re-open should this issue re-occur with current versions of Safari.
