### ISSUE TITLE
A lot of dependencies are out of date

### ISSUE THREAD

**Issue by mmermerkaya** [firebase/firebase-js-sdk#953]
Most of our dependencies are minor or even major versions behind.

https://david-dm.org/firebase/firebase-js-sdk?path=packages%2Ffirebase&type=dev
https://david-dm.org/firebase/firebase-js-sdk?path=packages%2Fmessaging&type=dev
https://david-dm.org/firebase/firebase-js-sdk?path=packages%2Fstorage&type=dev
https://david-dm.org/firebase/firebase-js-sdk?path=packages%2Ffunctions&type=dev

**Comment by mmermerkaya** [comment]
Related: #698.

**Comment by hsubox76** [comment]
Seems to be addressed now that we have added Gardener auto-updates: https://github.com/firebase/firebase-js-sdk/pull/1599
