### ISSUE TITLE
updateCurrentUser is not a function error

### ISSUE THREAD

**Issue by annslittleflower** [firebase/firebase-js-sdk#957]
please help me with firebase js sdk. In doc there is a function updateCurrentUser which belongs to auth, but seems like this function is not present in sdk, when i call it i get error "is not a function". Please help.
it doesnot work neither auth.updateCurrentUser nor auth().updateCurrentUser. Thanks in advance

**Comment by wti806** [comment]
`updateCurrentUser` is introduced in v5.0. What version are you using?

**Comment by annslittleflower** [comment]
i guess we should close this question, problem was in other stuff
i updated user with auth.currentUser.getIdToken(true)
