### ISSUE TITLE
Strange import/require problem

### ISSUE THREAD

**Issue by richtera** [firebase/firebase-js-sdk#965]
A react-static app with firebase.
node 9.11
Mac OS
firebase sdk ^5.1.0
trying to do just auth and database ... see further.

When I use
```javascript
import firebase from 'firebase'
```
or
```javascript
const firebase = require('firebase');
```
everything seems to work normally.
When I use
```javascript
import firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/database'
```
it seems to mostly build, but when it tried to generate the static parts I get this strange error.
```javascript
  TypeError: Cannot read property 'fetch' of undefined
  
  - fetch.js:4 
    [app]/[whatwg-fetch]/fetch.js:4:12
  
  - fetch.js:1 
    [app]/[whatwg-fetch]/fetch.js:1:1
  
  - firebase-app.js:1 e.searchParams
    [app]/[firebase]/firebase-app.js:1:84
  
  - firebase-app.js:1 Object.<anonymous>
    [app]/[firebase]/firebase-app.js:1:151
  
  - loader.js:654 Module._compile
    internal/modules/cjs/loader.js:654:30
  
  - loader.js:665 Module._extensions..js
    internal/modules/cjs/loader.js:665:10
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [app]/[babel-register]/lib/node.js:152:7
  
  - loader.js:566 Module.load
    internal/modules/cjs/loader.js:566:32
  
  - loader.js:506 tryModuleLoad
```
Looking at line 4 for fetch.js I can see
```javascript
  if (self.fetch) {
    return
  }
```
And self is a closure on ... at the end of the file ...
```javascript
})(typeof self !== 'undefined' ? self : this);
```
So for some reason both self and this are "undefined" when I load the firebase files separately and not if I load them as a single file. Obviously this doesn't sound like a firebase issue, but for some reason the import of the firebase file makes whatwg.fetch happy.

### [REQUIRED] Describe the problem

Setup the firebase react-static example and try to change the firebase import.
Then build a release (it works in dev mode)

#### Relevant Code:

As above.

**Comment by Feiyang1** [comment]
Hi @richtera , What do you mean by generate static parts? Do you mean rendering the webpage? I would need more information to help you.
It's interesting that how you import firebase makes the behavior different. Can you please create minimal working repo that reproduces the issue?

**Comment by richtera** [comment]
Wow I don't remember. This would mean a server side static render, but I don't recall the actual problem here, sorry. This is a long time ago.

**Comment by Feiyang1** [comment]
np. Please file a new issue if you face it again. closing this issue.

**Comment by djoks** [comment]
I'm facing the same problem.
