### ISSUE TITLE
Firebase not recognizing authorized domains for Oauth operations

### ISSUE THREAD

**Issue by lrs** [firebase/firebase-js-sdk#998]
OS: Linux Mint 18.3/Windows 10 1803
Firebase JS SDK: 5.2.0

I receive the console warning: 

`Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working.`

I receive the above warning from both localhost and the live site.

I've checked that the domains are included in Authentication> Sign-in Method > Authorized domains.

I've checked that I'm using the correct apiKey, authDomain and projectId. The Email/Password Sign-in provider is working fine on the live site.

**Comment by lrs** [comment]
In case anyone stumbles across this, the js sdk console message `Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working.` was a red herring and provided the wrong information.

The reason why I was getting this message was because I didn't have the firebase app domain itself (*.firebaseapp.com) included in the `Accept requests from these HTTP referrers (web sites)` list in the Google API credentials for the app key (https://console.developers.google.com/apis/credentials/key). This must be a fairly recent requirement as accepting requests from just my actual site domain was enough beforehand.

**Comment by tonydiep** [comment]
@lrs Thanks for the solution!

**Comment by lrs** [comment]
@tonydiep Glad it helped. That was a bit of a head scratcher for me!
